### ISSUE TITLE
Group support 

### ISSUE THREAD

**Issue by macarlet** [springdoc/springdoc-openapi#1]
Hi, can this library split the definition in groups? Maybe based on tags or on explicit definitions. So that we can obtain more than one definition on the same spring boot. Thanks

**Comment by springdoc** [comment]
Hi, 
 The library only uses standard OpenAPI 3 fields, and the swagger core/annotations only.
 Managing custom concepts like groups is not the aim, for the moment.

**Comment by neiser** [comment]
@macarlet For what it's worth, I've introduced multiple OpenApi beans into the demo application which are exposed via a new request param "group". See the commits on this branch: https://github.com/neiser/springdoc-openapi-demos/commits/multiple-open-api Hope this helps
