### ISSUE TITLE
PropertyCustomizer not invoked for multiple properties of same type with the same annotations.

### ISSUE THREAD

**Issue by banderous** [springdoc/springdoc-openapi#1000]
A PropertyCustomizer is not invoked for every property where those properties have the same type and annotations.

For example with the following class ([HelloController test here](https://github.com/springdoc/springdoc-openapi/compare/master...banderous:property-customizer-bug)):

```
  public static class ApiType {
      Long a;
      Long b;
      String c;
     // getters...
  }
```

A PropertyCustomizer is invoked for properties 'a' & 'c' only; it is **not** invoked for property b (which shares the result of 'a').

This appears to be because the swagger generator [is caching properties that share the same type and annotations](https://github.com/swagger-api/swagger-core/blob/d5ca168b70b93bff34ee2d0bfcc383476b41944b/modules/swagger-core/src/main/java/io/swagger/v3/core/converter/ModelConverterContextImpl.java#L84) and this is bypassing the type resolution process that drives the PropertyCustomizer.

Springdoc 1.5.2
Spring boot 2.4.1

**Expected behavior**
PropertyCustomizer is invoked for every property.

**Comment by bnasslahsen** [comment]
@banderous, 


 The root cause is that your properties are assumed to be equal from swagger-core library.
 In order to tell swagger the properties are not the same, you can add the Schema annotation on each property, so they can have different annotations :)

```java
package test.org.springdoc.api.app70.model;

import io.swagger.v3.oas.annotations.media.Schema;

public class ApiType {

	@Schema(name = "a")
	private Long a;

	@Schema(name = "b")
	private Long b;

	private String c;

	public Long getA() {
		return this.a;
	}

	public Long getB() {
		return this.b;
	}

	public String getC() {
		return this.c;
	}
}
```

 I know this is not the ideal solution, but as you mentioned, this is handled in the swagger-core library code.
 If you want the solution in the swagger-core, you could ask the swagger team for an enhancement to handle this case.

**Comment by banderous** [comment]
Thanks for the response @bnasslahsen. The java code in question is autogenerated so unfortunately that's not an option for me.

My objective is to make all properties required by default; is there any other way of achieving this?

**Comment by bnasslahsen** [comment]
You still can use `OpenApiCustomiser`.
This is a sample code that you can adapt:

```java
@Bean
public OpenApiCustomiser openApiCustomiser() {
  return openAPI -> openAPI.getComponents().getSchemas().values()
      .forEach(schema -> schema.setRequired(new ArrayList<>(schema.getProperties().keySet())));
}
```

**Comment by banderous** [comment]
Big thanks @bnasslahsen!

**Comment by jaco0646** [comment]
In SpringFox this can be accomplished using `ModelPropertyBuilderPlugin`, which applies to every Property of a Model, regardless of whether its Type is the same as another Property. Perhaps that offers some inspiration of how it might be implemented in SpringDoc.
