### ISSUE TITLE
RequestBody in GET requests are rendered as query parameter

### ISSUE THREAD

**Issue by OnnoH** [springdoc/springdoc-openapi#1003]
**Describe the bug**
I know it's uncommon for GET requests to have a RequestBody, but sometimes the payload can be quite large for the query parameter in the URL to handle it. Using a RequestBody makes more sense, but the generator does not render it. Instead a query parameter entry is there and when executed in the Swagger UI the following exception is thrown:
```
org.springframework.http.converter.HttpMessageNotReadableException: Required request body is missing:
```

**To Reproduce**
- Spring Boot 2.4.0
- springdoc-openapi v1.5.2
- modules: springdoc-openapi-ui, springdoc-openapi-security, springdoc-openapi-data-rest
- JSON result (excerpt)
```
    "/api/{domain}/ids/search": {
      "get": {
        "tags": [
          "Get Controller"
        ],
        "summary": "Get a list of all visible documents from a givendomain filtered by the given list of id's",
        "description": "Sample Request Body:\n\n{ \"ids\" : [ 1010334, 1010356 ] }",
        "operationId": "getDomainDocumentsByListOfIds",
        "parameters": [
          {
            "name": "domain",
            "in": "path",
            "description": "Name of domain",
            "required": true,
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "ids",
            "in": "query",
            "required": true,
            "schema": {
              "type": "object"
            }
          },
          {
            "name": "pageable",
            "in": "query",
            "required": true,
            "schema": {
              "$ref": "#/components/schemas/Pageable"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/QueryResult"
                }
              }
            }
          }
        }
      }
    },
```
- SampleController (excerpt)

```
@RequestMapping(value = "/api/{domain}/ids/search", method = RequestMethod.GET,
          produces = {MediaType.APPLICATION_JSON_VALUE})
@Transactional(readOnly = true)
@Operation(summary = "Get a list of all visible documents from a given domain filtered by the given list of id's",
          description = "Sample Request Body:\n\n"
                  + "{ \"ids\" : [ 1010334, 1010356 ] }")
@Parameter(name = "domain", description = "Name of domain", in = ParameterIn.PATH)
public QueryResult getDomainDocumentsByListOfIds(@PathVariable String domain,
                                                          @RequestBody Object ids,
                                                          final Pageable pageable,
                                                          HttpServletRequest request) {
    Path path = parser.parsePath(domain, request.getQueryString());
    validator.validatePath(path, HttpMethod.GET);

    List<Long> fetchIds = parseRequestBody(ids);
    path.setSearchIds(fetchIds);

    return this.documentService.getByDomain(path.getDomain(),
              path.getSearchFilter(), pageable, null);
}
```

**Expected behavior**
- Similar to a PUT request, I would expect 
- Sample JSON (excerpt)
```
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "additionalProperties": {
                  "type": "object"
                }
              }
            }
          },
          "required": true
        },
```

**Screenshots**
Some Swagger UI screenshots from the actual API

The 'old' Springfox-GET
![Screenshot 2020-12-29 at 16 44 38](https://user-images.githubusercontent.com/11159729/103295999-71cce280-49f5-11eb-958f-0322060756c8.png)

The 'new' GET
![Screenshot 2020-12-29 at 16 45 46](https://user-images.githubusercontent.com/11159729/103296091-a2148100-49f5-11eb-8a67-0d10f4fb474d.png)

The 'new PUT
![Screenshot 2020-12-29 at 16 46 18](https://user-images.githubusercontent.com/11159729/103296123-bb1d3200-49f5-11eb-8d74-ea1978722bf8.png)

**Comment by bnasslahsen** [comment]
springdoc-openapi only supports [OpenAPI 3](https://swagger.io/docs/specification/describing-request-body/), where : `GET, DELETE and HEAD are no longer allowed to have request body because it does not have defined semantics as per RFC 7231.`

**Comment by okohub** [comment]
@bnasslahsen RFC 7231 is now obsolete, RFC 9110 is published on June. 

https://www.rfc-editor.org/rfc/rfc9110.html#section-9.3.1-6

This section now says;

> Although request message framing is independent of the method used, content received in a GET request has no generally defined semantics, cannot alter the meaning or target of the request, and might lead some implementations to reject the request and close the connection because of its potential as a request smuggling attack ([Section 11.2](https://www.rfc-editor.org/rfc/rfc9112#section-11.2) of [[HTTP/1.1](https://www.rfc-editor.org/rfc/rfc9110.html#HTTP11)]). A client SHOULD NOT generate content in a GET request unless it is made directly to an origin server that has previously indicated, in or out of band, that such a request has a purpose and will be adequately supported. An origin server SHOULD NOT rely on private agreements to receive content, since participants in HTTP communication are often unaware of intermediaries along the request chain.

What do you think about this?

**Comment by bnasslahsen** [comment]
@okohub, 

We support OAS 3, [which clearly states](https://swagger.io/docs/specification/describing-request-body/): GET, DELETE and HEAD are no longer allowed to have request body because it does not have defined semantics ...
