### ISSUE TITLE
Authentication for OIDC on openapi-ui

### ISSUE THREAD

**Issue by villain-market** [springdoc/springdoc-openapi#1007]
I cannot say your project is the cause of the problem I am facing. However, you guys might have tested this feature, or at least implemented at some point so I'll ask.

I am trying to make Open ID Connect authentication work for springdoc-openapi-ui. But when I click 'Authorize' button on swagger UI, 'Available authentication' modal is empty.

I have set up security scheme as suggested in the swagger documentation in a Spring configuration way. API documentation is generated correctly as following.
```
"components": {
  "securitySchemes": {
    "openId": {
      "type": "openIdConnect",
      "openIdConnectUrl": "https://{---}.okta.com/oauth2/default/.well-known/openid-configuration" 
    }
  }
}
```
I have omitted the url on purpose but have confirmed that the GET request succeeds.
I read up on similar issues, but most of them points out that swagger-ui for OIDC was not supported prior to 3.38.0. Since I am using springdoc v1.5.2 which has a dependency on swagger-ui v.3.38.0 I don't think this is the cause.

Wondering if you guys saw OIDC authentication at work. Any help would be greatly appreciated.

**Comment by bnasslahsen** [comment]
@villain-market, 

 OpenidConnect is not yet tested against springdoc-openapi. Only Oauth2 is tested.

 There is some remaining issues that you can follow on the[ swagger-ui project instead](https://github.com/swagger-api/swagger-ui/pull/6750).

**Comment by virendrachaudhary06** [comment]
@villain-market the linked issued has been closed now and new version has been released. I also get the latest version of swagger-ui webjars and tested it. But still facing the same issue.
