### ISSUE TITLE
How/where is the "Generated server URL" generated?

### ISSUE THREAD

**Issue by BudWhiteStudying** [springdoc/springdoc-openapi#1008]
I am using the `springdoc-openapi-ui` module within my Spring Boot project in order to generate my OAS code-first documentation. Overall, the library works exactly as expected.

I have one of those rather common problems where the "Generated server URL" I can see on the Swagger UI does not match my expectations. I know I can override it with an annotation, but first I'd like to understand how it is generated, since the fact that the URL is not the way I'd like it might actually reflect some misconfiguration on the application server.

Can you please point me to the piece of code responsible for the generation of the server URL? I was unable to find it myself.

For the record, my problem is the following:
- in my local environment all is fine, I'm running on `localhost` and the Generated server URL is `http://localhost/context-root/`;
- in the on-premise environment (a Websphere cluster with two servers, say host `h001` and host `h002`) the Generated server URL is `http://h001/context-root` on `h001`, and *again* `http://h001/context-root` on `h002` i.e. on the second instance I can see the generated URL that I would expect on the first instance; this leads to `CORS` issues when trying out APIs on the second instance, since calls are actually done against the other host.

Thank you very much for any pointers you might give on this.

**Comment by bnasslahsen** [comment]
You can read the [F.A.Q:](https://springdoc.org/#how-is-server-url-generated) 
The link says you can customize the server URL using the server annotation.
You can read the discussions here for sample code details about annotations: https://github.com/springdoc/springdoc-openapi/issues/89

If you want investigate deeper, you can look for `calculateServerUrl` in the code:
https://github.com/springdoc/springdoc-openapi/blob/3e43d72e0f7c89b15e2d5b28cccab9b50bb02786/springdoc-openapi-webmvc-core/src/main/java/org/springdoc/webmvc/api/OpenApiResource.java#L293

**Comment by BudWhiteStudying** [comment]
Just in case this could be useful for someone else, my problem was caused by caching.

At Spring level I integrated Spring's cache abstraction with a Hazelcast distributed cache implementation, I suppose Swagger UI piggybacks on whatever cache is available from Spring, therefore the Swagger UI was also using the distributed cache. As a consequence, if e.g. I hit the UI on server `h001` first, the results would be cached and later accessed from either `http://h001/context-root` or `http://h002/context-root`, resulting in the same server URL being shown.

Disabling the cache through the property `springdoc.cache.disabled=true` fixed the problem.

**Comment by kaus02** [comment]
> You can read the [F.A.Q:](https://springdoc.org/#how-is-server-url-generated)
> The link says you can customize the server URL using the server annotation.
> You can read the discussions here for sample code details about annotations: #89
> 
> If you want investigate deeper, you can look for `calculateServerUrl` in the code:
> https://github.com/springdoc/springdoc-openapi/blob/3e43d72e0f7c89b15e2d5b28cccab9b50bb02786/springdoc-openapi-webmvc-core/src/main/java/org/springdoc/webmvc/api/OpenApiResource.java#L293

Can we implement our own method , to generated the URL since the url is not generated correctly if the application is behind a reverse proxy setting a prefix path?
