### ISSUE TITLE
Not working with spring webflux 

### ISSUE THREAD

**Issue by mmaryo** [springdoc/springdoc-openapi#1009]
Hello

Nothing appear at /swagger-ui.html with SpringDoc
I see swagger-ui but not endpoints 

@Configuration
open class AppRoutes {

    @Bean
    @RouterOperations(
        RouterOperation(path = "/app/get", method = arrayOf(RequestMethod.GET), beanClass = AppRoutes::class, beanMethod = "get"),
    )
    open fun init(): RouterFunction<*> {
        return routes
    }

    val routes = router {
        "/app".nest {
            accept(MediaType.APPLICATION_JSON).nest {
                GET("/get", { request: ServerRequest ->
                    val slogan = Mono.just("CodeCouple roxx!")
                    ServerResponse.ok()
                        .contentType(MediaType.APPLICATION_JSON)
                        .body(slogan, String::class.java)
                })
            }
        }
    }

    fun get(request: ServerRequest): Mono<ServerResponse> {
        val slogan = Mono.just("MY APP!")
        return ServerResponse.ok()
            .contentType(MediaType.APPLICATION_JSON)
            .body(slogan, String::class.java)
    }

}

I use this dependencies

implementation("org.springdoc:springdoc-openapi-webflux-ui:1.5.2")
implementation("org.springdoc:springdoc-openapi-kotlin:1.5.2")

And last version of spring boot 

Do you know how to activate SpringDoc with webflux ?

**Comment by bnasslahsen** [comment]
Please make sure you respect at least minimum syntax highlighting features offered by GITHUB.

To answer your question, you have two ways for using springodc with webflux: Using annotations or functional DSL. 

You can read the guidance [here](https://springdoc.org/#spring-webfluxwebmvc-fn-with-functional-endpoints).

Some working [demos](https://springdoc.org/#demos) are available for both:
- https://github.com/springdoc/springdoc-openapi-demos/tree/master/springdoc-openapi-spring-boot-2-webflux
- https://github.com/springdoc/springdoc-openapi-demos/tree/master/springdoc-openapi-spring-boot-2-webflux-functional

If you are still unable to make it work or you suspect facing a bug, make sure you provide a [Minimal, Reproducible Example - with HelloController](https://stackoverflow.com/help/minimal-reproducible-example) that reproduces the problem.

This ticket will be closed, and can be reopened if any relevant information is provided.
