### ISSUE TITLE
Hidden Sample Pet Store Server—Intentional?

### ISSUE THREAD

**Issue by UgmaDevelopment** [springdoc/springdoc-openapi#1011]
**Describe the bug**
When you remove the parameters from the swagger URL, down to `/swagger-ui/index.html` a Sample Pet Store Swagger page appears.
This kind of seems like an accident. If not, would someone be so kind as to offer some explanation?

**To Reproduce**
1. Launch the spring boot app
2. Navigate to the `/swagger-ui.html` endpoint
3. Remove parameters from URL down to `/swagger-ui/index.html`

- What version of spring-boot you are using?
    - It's reproducible with the demo in the readme: [Demo Spring Boot 2 and Spring Hateoas with OpenAPI 3](http://158.101.164.60:8085/swagger-ui.html).

**Expected behavior**
I expected when I got rid of the parameters that it would go back to the swagger page of the underlying REST service, not that of a hidden example service.

**Screenshots**
![J9sRJSOSEv](https://user-images.githubusercontent.com/19827042/104346064-3b469b80-54bc-11eb-990a-86c8c6bf6029.gif)

Thanks in advance for any explanation.

**Comment by bnasslahsen** [comment]
@UgmaDevelopment, 

 This is the default swagger-ui url. That coms from the swagger-ui project.
 springdoc-openapi is built on top of the swagger-ui library, swagger-core and spring-boot.

 You have a property to hide this page as explained in the [documentation](https://springdoc.org/#how-can-i-disable-the-default-swagger-petstore-url).
