### ISSUE TITLE
exampleSetFlag included in output 

### ISSUE THREAD

**Issue by Quantumplation** [springdoc/springdoc-openapi#1017]
**Describe the bug**
When generating api-docs (either json or yaml format), the `exampleSetFlag` property leaks into the `schema`, which is not valid via the OpenAPI spec.  This prevents the generated API from being used with some tools which validate the file first.

**To Reproduce**
- What version of spring-boot you are using?  `2.2.2.RELEASE`
- What modules and versions of springdoc-openapi are you using? `springdoc-openapi-ui` version `1.5.2`
- Provide with a sample code (HelloController) or Test that reproduces the problem: see: https://gist.github.com/Quantumplation/484dc05a3bbec30293325ea82b041a58

**Expected behavior**
- The generated json or yaml should conform to the OpenAPI standard
- Specifically, there is no such `exampleSetFlag` property in the standard

**Additional context**
This problem seems to have come up elsewhere, see: https://github.com/swagger-api/swagger-core/issues/3702

**Comment by bnasslahsen** [comment]
@Quantumplation, 

 Thank for your description.
 Unfortunately, this issue is not reproducible and this is the generated spec.
 I have pushed the test case for it as you can see.

 In case, you have a fully reproducible example, don't hesitate to comment the issue and add the link to it, and this ticket can be reopened.

**Comment by Quantumplation** [comment]
@bnasslahsen Sure thing, here's my minimal reproduce, complete with pom etc.:

https://github.com/Quantumplation/springdoc-1017/tree/main

I also included the result of `mvn -v` in the readme, in case that's relevant.

**Comment by bnasslahsen** [comment]
@Quantumplation, 

 I am looking at the repository, and i have identified 5 pom.xml files for 1 class HelloController.
 This might work, but not ideal to diagnose.

  Please help to speed up problem diagnosis.

 You can provide a [Minimal, Reproducible Example - with HelloController](https://stackoverflow.com/help/minimal-reproducible-example) that reproduces the problem
 You can use https://start.spring.io/ to generate the sample structure.

**Comment by Quantumplation** [comment]
This is just one project in `sample` referring to eachother via a parent/child relationship, as in my project at work.  I'm not familiar enough with the pom.xml file format to know how to eliminate that structure (which fields from which pom.xml need to be preserved, and which can be thrown away, etc.), though I did spend nearly an hour eliminating as much as I could.

**Comment by bnasslahsen** [comment]
@Quantumplation, 

 Sorry, with a `HelloController` you don't need 5 pom.xml files.
 If you could  provide a [Minimal, Reproducible Example - with HelloController](https://stackoverflow.com/help/minimal-reproducible-example) that reproduces the problem, it would be great.

**Comment by Quantumplation** [comment]
I'm not sure if this was intentional, but your messages are coming off as really condescending, and it's not really productive to the conversation.  Regardless, I'll try to explain again:

I've already invested a substantial amount of effort in extracting a reproduce faithfully out of a 600k+ LOC project, eliminating every dependency and plugin that was irrelevant.  The pom files are mostly empty, and shouldn't be difficult for someone familiar with Java (for example, the maintainer of a popular Java open source maven plugin) to skim through them and identify if there is anything relevant.

I'm more of a C# / Rust guy, so I'm not familiar enough with the Java pom.xml format to know how to safely collapse those further.  For example, I don't know which parts of the XML can be safely copied from one pom.xml to another, which would be duplicates, etc.  It would require a large amount of trial-and-error on my part to do so.

Given that your test case didn't reproduce the issue, it's possible that starting from scratch with start.spring.io would eliminate whatever was causing the issue, so I don't think it's a productive use of my time.

I appreciate the amount of time you must volunteer to maintain an open source project, and I'm under no illusions that you're obligated to fix every issue; at this point, though, I've demonstrated that there is a bug, and invested as much time as I'm going to into providing a decently minimal reproducible example.  If you choose to leave this bug in your software, that's certainly your prerogative.

**Comment by bnasslahsen** [comment]
@Quantumplation, 
 
 Maybe you haven't read my previous message.

 I have already extracted [your code](https://github.com/springdoc/springdoc-openapi/commit/ed5f8b5f07c85ceb7cdc1b8d582d9cc71f52f4cd), and it's already pushed in a test case.
And you can see it' is not reproducible.  The test is passing on tavis-ci.

**Comment by Quantumplation** [comment]
Have you tried running `mvn verify` in the repository I linked above, in the root directory? because for me, that *does* reproduce the issue, whereas whatever project setup you are using for your test case does not (supposedly, I haven't tested it).

You don't even need to read the 5 pom.xml files to confirm that.

**Comment by bnasslahsen** [comment]
> Have you tried running `mvn verify` in the repository I linked above, in the root directory? because for me, that _does_ reproduce the issue, whereas whatever project setup you are using for your test case does not (supposedly, I haven't tested it).
> 
> You don't even need to read the 5 pom.xml files to confirm that.


 Maybe you haven't read my previous message.

 I have already extracted [your code](https://github.com/springdoc/springdoc-openapi/commit/ed5f8b5f07c85ceb7cdc1b8d582d9cc71f52f4cd), and it's already pushed in a test case.
And you can see it' is **not reproducible**.  The test is passing on tavis-ci which is the reference.

Your repository might reproduce, but we can create many issues just by using the wrong version of jars or dependencies which the case of your project.
And the most important thing is to share a minimal sample, not 5 pom.xml files for one class. 
We count on you to help us speed up problem diagnosis.

If you go from a clean basis, you will not have this kind of problems. You have also the [demos](https://github.com/springdoc/springdoc-openapi-demos) repo to guide you for that.

As you are not very familiar with java. I have looked further, the problem is that you are adding dependencies not need:
 Note you don't need to declare any `swagger` additionnal dependencies with springdoc-openapi.

 The springdoc-openapi starter ships all the OpenAPI necessary dependencies like `swagger-core` / `swagger-annotations` or `swagger-ui`, and the coherence of versions with spring-boot is already tested.

 This is the cause of your problem:

  ```xml
          <dependency>
                <groupId>io.swagger.core.v3</groupId>
                <artifactId>swagger-core</artifactId>
                <version>2.1.1</version>
            </dependency>
```

 I see you using in your project an old version of swagger.
 Using the  springdoc-openapi current version is `2.1.6`.

To sum up. You should get rid off on unnecessary dependencies that cause conflicts:
All these dependencies in you code-dependencies pom.xml are useless:

```xml
            <dependency>
                <groupId>io.swagger.core.v3</groupId>
                <artifactId>swagger-core</artifactId>
                <version>2.1.1</version>
            </dependency>
            <dependency>
                <groupId>io.swagger</groupId>
                <artifactId>swagger-annotations</artifactId>
                <version>1.6.0</version>
            </dependency>
            <dependency>
                <groupId>org.webjars</groupId>
                <artifactId>swagger-ui</artifactId>
                <version>3.28.0</version>
            </dependency>
            <dependency>
                <groupId>org.webjars</groupId>
                <artifactId>webjars-locator-core</artifactId>
                <version>0.46</version>
            </dependency>
```

**Comment by Quantumplation** [comment]
Thank you for taking the time to look into that.  I'll try that tomorrow when I'm at work, provided these dependencies aren't required by other teams for other reasons.  Working from a clean basis / demo repo isn't really an option for me, as this is functionality I'm adding to a very large project.

re: versions, I guess this is where my unfamiliarity with Java comes in to play.  Most of the languages I'm used to will either throw errors if you specify conflicting versions of libraries, or allow each library to have a separate copy fixed to the version it needs.

**Comment by bnasslahsen** [comment]
Well, now it's getting out of the topic...Anyway, for your dependencies management you can use [maven-enforcer-plugin](https://maven.apache.org/enforcer/maven-enforcer-plugin/index.html) to control the desired behavior, duplicated dependencies may banned and the build can[ fail consequently](https://www.baeldung.com/maven-enforcer-plugin).

**Comment by aditya9509** [comment]
@Quantumplation  Facing the same issue where the exampleSetFlag is leaking into the api-docs response. Did you come across any working solution yet?

 Looks like the issue starts from springdoc-openapi-ui version 1.4.8 and above which depends on swagger-core 2.1.4+.
For the time being, I got past this issue by downgrading to springdoc-openapi-ui version 1.4.3.
