### ISSUE TITLE
Issue with handling of multipart form data

### ISSUE THREAD

**Issue by logicatmidod** [springdoc/springdoc-openapi#1018]
Hi While trying to work with multipart form data I don't see swagger working correctly below is the code and curl command created by swagger which goes to error however it works fine with POSTMAN

``java
   public ResponseEntity sendEMail(@RequestParam String emailEssential,@Parameter(array = @ArraySchema(schema = @Schema(type = "string",format = "binary"))) @RequestParam(value = "files",required = false) MultipartFile[] files) {
        if(files!=null){
           emailService.sendEmail(emailEssential, Arrays.asList(files));
        }
       else{
           emailService.sendEmail(emailEssential, null);
       }
       return ResponseEntity.ok().body("Email send succesfully");

    }
``

Swagger curl command

curl -X POST "http://localhost:8080/api/email/sendemail?emailEssential=%7B%7D&files=[object File]" -H "accept: */*"

error:

``java
java.lang.IllegalArgumentException: Invalid character found in the request target [/api/email/sendemail?emailEssential=%7B%7D&files=[object%20File]]. The valid characters are defined in RFC 7230 and RFC 3986
	at org.apache.coyote.http11.Http11InputBuffer.parseRequestLine(Http11InputBuffer.java:490) ~[tomcat-embed-core-9.0.39.jar:9.0.39]
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:261) ~[tomcat-embed-core-9.0.39.jar:9.0.39]
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65) ~[tomcat-embed-core-9.0.39.jar:9.0.39]
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868) ~[tomcat-embed-core-9.0.39.jar:9.0.39]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1590) ~[tomcat-embed-core-9.0.39.jar:9.0.39]
``

**Comment by bnasslahsen** [comment]
@logicatmidod, 

  Please make sure you format at least the code using the GITHUB features.
 Make sure you follow the [guidance](https://github.com/springdoc/springdoc-openapi/blob/master/CONTRIBUTING.adoc
) here before reporting any bug.
 
If you are reporting a bug, please help to speed up problem diagnosis by providing as much information as possible:
- You need to describe your context (the title of an issue is not enough)
- What version of spring-boot you are using?
- What modules and versions of springdoc-openapi are you using?
- What are the actual and the expected result using OpenAPI Description (yml or json)?
- Provide a [Minimal, Reproducible Example - with HelloController](https://stackoverflow.com/help/minimal-reproducible-example) that reproduces the problem


This ticket will be now closed, and can be reopned if the relevant information are provided.
