### ISSUE TITLE
Deterministic Ordering of Response Status-Codes to avoid diffs

### ISSUE THREAD

**Issue by hotzen** [springdoc/springdoc-openapi#1019]
when regenerating the open-api spec (via maven-plugin and then git-commited), the response status code are generated in an undetermistic/unordered fashion.
so while nothing actual changes, we have diffs just because the response-codes are shuffled:
e.g. from
```
responses:
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiErrorResponse'
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiErrorResponse'
```
to
```
responses:
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiErrorResponse'
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiErrorResponse'
```

Please order responses by status-code, so we avoid unnecessary commits/changes.
Thanks for the great project!

**Comment by bnasslahsen** [comment]
@hotzen, 

Have you used `springdoc.writer-with-order-by-keys=true`, for deterministic order, as stated in the [documentation](https://springdoc.org/#springdoc-openapi-core-properties) ?
