### ISSUE TITLE
Uncaught ReferenceError: x is not defined at <anonymous>:1:5

### ISSUE THREAD

**Issue by saraminto** [springdoc/springdoc-openapi#1022]
**Describe the bug**
Upon opening swagger-ui.html in browser I cannot see rendered responses
![image](https://user-images.githubusercontent.com/77557375/104828119-8cfd7600-586e-11eb-825b-b68b9cd005c1.png)

**console output:** 

```
"("+x+", "+y+")"
Uncaught ReferenceError: x is not defined at <anonymous>:1:5
﻿
2
root-injects.jsx:94 TypeError: Cannot read property 'xml' of undefined
    at R (fn.js:110)
    at e (fn.js:213)
    at A (fn.js:336)
    at configure-map.js:61
    at We (utils.js:557)
    at Ke (utils.js:591)
    at n.value (response.jsx:158)
    at n.I.t.render (root-injects.jsx:92)
    at u._renderValidatedComponentWithoutOwnerOrContext (ReactCompositeComponent.js:796)
    at u._renderValidatedComponent (ReactCompositeComponent.js:819)
```

**To Reproduce**
- What version of spring-boot you are using? 2.4.0
- What modules and versions of springdoc-openapi are you using? 1.5.2
- What is the actual and the expected result using OpenAPI Description (yml or json)?
- Provide with a sample code (HelloController) or Test that reproduces the problem
```
<dependency>
    <groupId>org.springdoc</groupId>
    <artifactId>springdoc-openapi-ui</artifactId>
    <version>1.5.2</version>
</dependency>
```
```
    @PostMapping(path = "/test/request", consumes = MediaType.APPLICATION_XML_VALUE,
            produces = MediaType.APPLICATION_XML_VALUE)
    public @ResponseBody
    @ApiResponses(value = {@ApiResponse(responseCode = "200", content = @Content(schema = @Schema(implementation = MyResponse.class), encoding = @Encoding(contentType = "application/xml" ), mediaType = MediaType.APPLICATION_XML_VALUE, examples = {
            @ExampleObject(name = "test1",
                    summary = "a response to a good request",
                    value = "<value></value>")})),
            @ApiResponse(responseCode = "400", content = @Content(mediaType = MediaType.APPLICATION_XML_VALUE, examples = {
                    @ExampleObject(name = "NOT OK response",
                            summary = "a response to a bad request",
                            value = "<value></value>")}))})
    JAXBElement<MyResponse> test(
            @RequestBody @io.swagger.v3.oas.annotations.parameters.RequestBody(content = @Content(examples = {
                    @ExampleObject(
                            name = "A correct example",
                            summary = "test",
                            value = "<value></value>"),
            })) JAXBElement<MyRequest> message) {}
```

**Expected behavior**
- I expect to not see that sad face explaining about rendering issues

**Additional context**
Application is written in Java

**Comment by bnasslahsen** [comment]
@saraminto, 

 Your description doesn't provide any relevant information to go further.

 Please read the [contribution guide ](https://github.com/springdoc/springdoc-openapi/blob/master/CONTRIBUTING.adoc)how to use github issues.

 Also, please make sure you respect the  [Code of Conduct ](https://github.com/springdoc/springdoc-openapi/blob/master/CODE_OF_CONDUCT.md)

Note that there is no need to open a new issue. 
You can update your description with the relevant information, and we will review it.
