### ISSUE TITLE
Custom Spring Security Provider End Points

### ISSUE THREAD

**Issue by mehmet6parmak** [springdoc/springdoc-openapi#1023]
**Is your feature request related to a problem? Please describe.**
It is not related to a problem. We use custom spring security providers which are implemented as Filters actually. Those registered filters are not visible in swagger UI. 

**Describe the solution you'd like**
- If it is possible, displaying custom auth providers automatically would be easiest way. 
- If not, I guess it should be manually added by providing PathItem objects. 

**Describe alternatives you've considered**
- I tried adding the missing auth endpoints by providing PathItem objects but creating even a simple ApiResponse object takes quite time (creation of PathItem, Operation, RequestBody, Tag... ) 
- I did not think of another alternative.

**Additional context**
- .

I actually want to ask if there is a way to create a schema object for an existing class without describing its all properties. Can't it simply be created by reflection? It is very cumbersome to define all properties again and it also needs maintenance when the original class changes. 

I mean can the following be sufficient
`Schema deviceInfo = new Schema<DeviceInfo>().clazz(DeviceInfo.class)`
Instead of
```
Schema deviceInfoSchema = new ObjectSchema();
deviceInfoSchema.setDefault(createExampleDeviceInfo());
deviceInfoSchema.addProperties("uuid", new StringSchema());
deviceInfoSchema.addProperties("name", new StringSchema());
deviceInfoSchema.addProperties("deviceType", new StringSchema());
deviceInfoSchema.addProperties("language", new StringSchema());
deviceInfoSchema.addProperties("osVersion", new StringSchema());
deviceInfoSchema.addProperties("appVersion", new StringSchema());
```

**Comment by bnasslahsen** [comment]
You can use `ModelConverters/resolveAsResolvedSchema` with class name:

```java
ResolvedSchema resolvedSchema = ModelConverters.getInstance()
					.resolveAsResolvedSchema(new AnnotatedType(Problem.class));
```

 Here is a [sample code](https://github.com/springdoc/springdoc-openapi/blob/master/springdoc-openapi-webmvc-core/src/test/java/test/org/springdoc/api/app126/SpringDocApp126Test.java) for it.

You have also the combination for using `OpenApiCustomiser`, which will help you add your custom spring-security endpoints.
