### ISSUE TITLE
Support for @Operation in @RepositoryRestResource Spring Data Repositories

### ISSUE THREAD

**Issue by MarcelBruch** [springdoc/springdoc-openapi#1026]
I've a MongoRepository similar to the one below. I wasn't able to set

```
@RepositoryRestResource(path = "contacts")
interface JavaCompletionSessionRepository : MongoRepository<Contact, String> {

    @Operation(summary = "Find an existing contact", description = "", tags = ["contacts"], operationId="someId")
    //@RouterOperation(operation = Operation(summary = "Find an existing contact", description = "", tags = ["contacts"]))
    @ApiResponses(
        value = [
            ApiResponse(responseCode = "200", description = "successful operation"),
            ApiResponse(responseCode = "400", description = "Invalid ID supplied"),
            ApiResponse(responseCode = "404", description = "Contact not found"),
            ApiResponse(responseCode = "405", description = "Validation exception")]
    )
    fun findByUserId(@Param("userId") userId: String): List<Contact>
```

It seems that Springdoc is not picking up any information about here (just some unsatisfying defaults)?

This is particular ugly since I'm generating a client from the generated OpenAPI and the defaults lead to bad method names there.

Could this feature be added - or is there a reasonable workaround for this issue?

**Comment by bnasslahsen** [comment]
@MarcelBruch, 

 For the moment, only `@Tags` and `@SecurityRequirements` are picked up.

 You can rename/enhance any generated field using [OpenApiCustomiser](https://springdoc.org/#how-can-i-customise-the-openapi-object), where you have full access the `OpenAPI` object.

 The support of `@Operation`, can be planned for a future release in the level of **search Repositories**.

**Comment by MarcelBruch** [comment]
Okay. my workaround looks as follows:

```
    @Bean
    open fun consumerOpenAPICustomiser(): OpenApiCustomiser {
        return OpenApiCustomiser { openApi ->
            openApi.paths
                .filterKeys { path -> path.contains("/search/") }
                .mapKeys { (path, item) -> path.substringAfterLast("/") }
                .flatMap { (path, item) -> item.readOperations().map { path to it } }.toMap()
                .forEach { path, item -> item.operationId = path }
        }
    }
```


Question:
There is also no support for  custom countXYZ(...) methods, right?

Repository methods like ```fun countByXYZ(@Param("xyz") xyz: String): Long``` 

have a wrong response content type:
 
```
 "responses":{
               "200":{
                  "description":"OK",
                  "content":{
                     "application/hal+json":{
                        "schema":{
                           "$ref":"#/components/schemas/EntityModelXZY"
                        }
                     }
                  }
               },
               "404":{
                  "description":"Not Found"
               }
            }
            
```

But it should return Long here. Any idea how to fix this?

**Comment by bnasslahsen** [comment]
@MarcelBruch, 

 The support is now added for @Operation / @Responses / @Parameter annotations in the level of the search repositories.
 Also, the count type return should be fixed.

 You can already test it using the [last SNAPSHOT](https://springdoc.org/#how-can-i-use-the-last-springdoc-openapi-snapshot).

**Comment by MarcelBruch** [comment]
Awesome! Thank you!
