### ISSUE TITLE
springdoc-openapi-ui: Support configuration of background colour and headerbar (icon)

### ISSUE THREAD

**Issue by maecval** [springdoc/springdoc-openapi#1028]
**Need to be able to control the background colour (and headerbar/icon) via configuration**
As a user of springdoc-openapi in a SpringBoot 2.3 application I want to be able to configure the background colour (and headerbar/icon) of the Swagger-UI via the configuration of the SpringBoot 2.3 application.
In this application it is a requirement to have different background colours depending on the target environment (e.g. test, staging, production).

**Support configuration of background colour (and headerbar/icon) of the Swagger-UI via the configuration of the SpringBoot 2.3 application**
e.g. application.properties
```
springdoc.swagger-ui.background.colour=#3b4151
```

**setup of SB 2.3 application**
- org.springdoc:springdoc-openapi-ui:1.4.8
- org.webjars:swagger-ui:3.34.0

**Comment by bnasslahsen** [comment]
@maecval, 

 There is no such properties available in the [swagger-ui](https://swagger.io/docs/open-source-tools/swagger-ui/usage/configuration/).
You can look at my answer here for manual customization of the swagger-ui: https://github.com/springdoc/springdoc-openapi/issues/951

 If you want additional properties for that, please submit your request to the swagger-ui project instead.
