### ISSUE TITLE
defining @ApiResponse removes autogenerated openapi doc for org.springframework.data.domain.Page

### ISSUE THREAD

**Issue by mickroll** [springdoc/springdoc-openapi#1029]
**Describe the bug**
If a controller method uses both `Page<...>` as result and is annotated with `@ApiResponse`, the swagger ui does not contain the 200-response anymore.

**To Reproduce**
The following contoller shows the bug:
```java
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import javax.transaction.Transactional;
import org.springframework.data.domain.Page;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

@RestController
@RequestMapping("/api/v1.0/example")
@Transactional
public class ExampleController {

  @Operation
  @GetMapping("/fine")
  public Page<ExampleTO> getPageCorrect() {
    return null;
  }

  @Operation
  @GetMapping("/bug")
  @ApiResponse(responseCode = "401", description = "Unauthorized")
  public Page<ExampleTO> getPageBuggy() {
    return null;
  }

  public static interface ExampleTO {
    String getName();
  }
}

```
- What version of spring-boot you are using? `2.4.2`
- What modules and versions of springdoc-openapi are you using? `springdoc-openapi-ui`,`springdoc-openapi-security`, `springdoc-openapi-data-rest`; all in version `1.5.2`
- What is the actual and the expected result using OpenAPI Description (yml or json)? See screenshots.
- Provide with a sample code (HelloController) or Test that reproduces the problem :heavy_check_mark:

**Expected behavior**
Using `@ApiResponse` for response code 401 should not remove documentation of another response code (200) in swagger ui.
I would expect that the Annotation is just used as an additional input. So any responses that are declared by using this annotation  just 'overwrite' the default generated responses _of the same response code_.
The JavaDoc of the annotation states the following:
> swagger-jaxrs2 reader engine considers this annotation **along with method return type** and context as input to resolve the OpenAPI Operation responses.

**Screenshots**
With `@ApiResponse`: 200-response is missing
![grafik](https://user-images.githubusercontent.com/9883575/105338187-8d35a280-5bdb-11eb-80a8-cdc53c309790.png)

Without `@ApiResponse`: 200-response is shown
![grafik](https://user-images.githubusercontent.com/9883575/105338148-8313a400-5bdb-11eb-9f4d-46a2cd21e724.png)

**Additional context**
This behaviour can also be triggered, if `@ApiResponse` is used on controller level or on a meta-annotation.
This seems to affect only return type `org.springframework.data.domain.Page`. Using `java.util.List` works as expected.

**Comment by bnasslahsen** [comment]
@mickroll, 

  Your expected behavior doesn 't correspond to the way springdoc-openapi is working.
- The JavaDoc that you are referecing is related to how swagger-jaxrs2 reader works. 
We do not use this reader.

Response code may vary, it is not only about 200 for success cases, especially in Restful architecture.

Here is how springdoc-openapi works:
- If you document your response by `@ApiResponse`, you declare **all** the response codes that your controller method is returning.
- If you don't document, but use the spring `@ResponseStatus`, it will be used a default response code.
- If you declare a `@ControllerAdvice` and that handles your `401` error and put the `@ApiResponse` at it's level , you will get your Expected behavior
- **Only** if you do nothing, where http 200 will be assumed as response code

**Comment by mickroll** [comment]
Thank you for your detailed answer.

Well, adding `@ApiResponse(responseCode = "200")` is fine for me.

> For your last point `Using java. Util. List works as expected.` I don't understand what you mean by that.
> Maybe, if given us more code samples to what you are referring to, it will more clear.

Just for clarification, I thought to have tested, that the following works without defining `@ApiResponse(responseCode = "200")`. But it doesn't:
```
  @Operation
  @GetMapping("/list")
  @ApiResponse(responseCode = "401", description = "Unauthorized")
  public List<ExampleTO> getList() {
    return null;
  }
```
So the behaviour is exactly as you described, and not dependent on using `Page<T>` or `List<T>` or any other return type.
