### ISSUE TITLE
Unable to add response header

### ISSUE THREAD

**Issue by patips34** [springdoc/springdoc-openapi#103]
I am trying to add response headers. Trying something like below:

@Operation(operationId = POST_API_OPERATION_ID, summary = POST_API_SUMMARY, description = POST_API_DESCRIPTION, tags = {
			ENTITY_NAME })
	@ApiResponses(value = { 
			@ApiResponse(responseCode = "201", description = API_RESP_201_DESC,
					headers = @Header(name = API_RESP_201_HEADER_LOCATION_NAME, 
					description =  API_RESP_201_HEADER_LOCATION_DESC, 
					schema = @Schema(implementation = String.class))
					),

In output swagger definition has error for location header. 
Actual response:
201:
          description: <description>
          headers:
            Location:
              description: <header_description>
              style: simple
          content:......

Expected:
201:
          description: <description>
          headers:
            Location:
              description: URL of the updated resource
              schema: 
                 type: String
          content:....

**Comment by springdoc** [comment]
Hi, 

 We rely on official swagger-core library: swagger-core-2.0.9.
 This is the behaviour of the libray which ignores implementation on the following Class/method:
- AnnotationsUtils.getHeader  (Line 938)
 
 You can follow this issue for more details:
- https://github.com/swagger-api/swagger-core/issues/2965


 As workaround: You can set the Header this way:
```java
@Header(name = "API_RESP_201_HEADER_LOCATION_NAME", description = "API_RESP_201_HEADER_LOCATION_DESC", schema = @Schema(type="string")
```
