### ISSUE TITLE
Swagger UI text goes beyond width limit

### ISSUE THREAD

**Issue by cosmin-rezmerita** [springdoc/springdoc-openapi#1030]
**Describe the bug**
If the request URL is big or the response body contains a big string, the text doesn't wrap so that it can fit inside the predefined box for it, but it rather is displayed as a single line that goes beyond the screen width

**To Reproduce**
- What version of spring-boot you are using?
**using Spring Boot 2.4.2**
`<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>2.4.2</version>
		<relativePath/> 
	</parent>`
- What modules and versions of springdoc-openapi are you using?
**using springdoc-openapi-ui 1.5.2**
`<dependency>
			<groupId>org.springdoc</groupId>
			<artifactId>springdoc-openapi-ui</artifactId>
			<version>1.5.2</version>
		</dependency>`

**Expected behavior**
- A clear and concise description of what you expected to happen.
it is expected that the text displayed by the swagger ui should wrap so that it can fit inside its panel

**Screenshots**
![image](https://user-images.githubusercontent.com/28341822/105383423-c68d0300-5c19-11eb-838d-62dddae1ea31.png)

**Additional context**
We have another app that uses version **1.4.8** of _springdoc-openapi-ui_ and for that it works fine. I also tested the new application (which was using version 1.5.2) with version 1.4.8 of springdoc-openapi-ui and it is displayed at expected, but **neither of 1.5.0 or 1.5.1 version work fine**.

**Comment by bnasslahsen** [comment]
@cosmin-rezmerita, 

- springdoc-openapi-ui  **v1.4.8**, ships swagger-ui **v3.34.0**.
- springdoc-openapi-ui  **v1.5.2**, ships swagger-ui **v3.38.0**.

You can change swagger-ui version used by springdoc-openapi 1.5.2, simply as follow:
- https://github.com/springdoc/springdoc-openapi/issues/871#issuecomment-695329263

If you confirm the cause, please raise a ticket on the [swagger-ui project ](https://github.com/swagger-api/swagger-ui) instead and link it to this issue.

**Comment by cosmin-rezmerita** [comment]
@bnasslahsen , could you also tell me **what versions of swagger-ui** do _springdoc-openapi-ui_ **v1.5.0** and **v1.5.1** use? or how can i find this out?

**Comment by bnasslahsen** [comment]
Simply go to the [tag](https://github.com/springdoc/springdoc-openapi/blob/v1.5.0/pom.xml), and look for `swagger-ui.version`. You will find (3.36.1)
Same principle applies to v1.5.1.

**Comment by cosmin-rezmerita** [comment]
hi @bnasslahsen , i just tested **springdoc-openapi-ui v1.5.0** with **swagger-ui v3.37.2** (instead of v3.38.0 that comes included) and the problem is not reproduced - the text wraps.
however, i also tested **springdoc-openapi-ui v1.5.0** with **swagger-ui v3.40.0** and it also works as expected with regards to this issue. is this a bad practice? - using a version of a dependency that is ahead of what comes out of the box

**Comment by bnasslahsen** [comment]
@cosmin-rezmerita, 

 It's better to use the `swagger-ui `version that is shipped with `springdoc-openapi-ui`. As you each version is tested against this UI version and other swagger-ui. The main idea is hiding all the complexity of combining different jars versions.

 This is said, from software architecture perspective, the generation of the OpenAPI spec should be working. The impact doing things manually is you might not get all the new available properties of the UI, or different presentation behavior.

 Version `3.40.0` which is shipped in the last snapshot of `springdoc-openapi-ui`, should already fixes your issue. Which means next release; You can you test the [latest SNAPSHOT](https://springdoc.org/#how-can-i-use-the-last-springdoc-openapi-snapshot) to confirm.

**Comment by cosmin-rezmerita** [comment]
@bnasslahsen , thank you for your swift response and valuable explanation! for the moment i will stick with an older version springdoc-openapi-ui that ships a good swagger-ui. in the future i will consider upgrading
