### ISSUE TITLE
Generate explode property as false for schema type array in springdoc

### ISSUE THREAD

**Issue by kdss91** [springdoc/springdoc-openapi#1032]
**Describe the bug**
- If you are reporting a bug, please help to speed up problem diagnosis by providing as much information as possible:
- A clear and concise description of what the bug is: the title of an issue is not enough
  I read the official documentation for openapi at the link (https://github.com/OAI/OpenAPI-Specification/blob/3.0.1/versions/3.0.1.md#schemaObject). It says that for array types, items should be present. 
  I also checked explode property of Parameter annotation, it says that "When style is form, the default value is true. For all other styles, the default value is false.  Ignored if the properties content or array are specified.". If I use array which is of type 	  ArraySchema, explode property is ignored. 
  Also, ArraySchema and Schema cannot coexist. 
  I want to request a List of string as a request parameter also put style as 'form' and and explode as 'false'.
  

**To Reproduce**
- What version of spring-boot you are using?
  2.4.1
  
- What modules and versions of springdoc-openapi are you using?
  	
    springDocVersion = "1.4.8"
    implementation("org.springdoc:springdoc-openapi-ui:$springDocVersion")
    implementation("org.springdoc:springdoc-openapi-kotlin:$springDocVersion")
    implementation("org.springdoc:springdoc-openapi-security:$springDocVersion")
    implementation("org.springdoc:springdoc-openapi-webmvc-core:$springDocVersion")

- What is the actual and the expected result using OpenAPI Description (yml or json)?
      1) when I use , schema = Schema(type = "array"), api-docs are generated as below.
      
      - name: xyz
        in: query
        description: "desc"
        required: true
        style: form
        explode: false
        schema:
          type: array
      
      2) When I use,  array = ArraySchema(schema = Schema(type = "string"))	
      
      - name: xyz
        in: query
        description: "desc"
        required: true
        style: form
        schema:
          type: array
          items:
            type: string
	
- Provide with a sample code (HelloController) or Test that reproduces the problem.

    1) Code for case 1 above
    
    @Operation(summary = "summary", description = "description", tags = ["tag"])
    @PatchMapping("/{id}/xyz/delete")
    fun deleteFromSomething(@Parameter(name = "id", description = "desc", `in` = ParameterIn.PATH)
                          @PathVariable id: UUID,
                          @RequestParam @Parameter(description = "desc",
                                  style = ParameterStyle.FORM, explode = Explode.FALSE, schema = Schema(type = "array")) xyz: MutableList<String>) {
        return "something";
    }
    
    
    2) Code for case 2 above
    
    @Operation(summary = "summary", description = "description", tags = ["tag"])
    @PatchMapping("/{id}/xyz/delete")
    fun deleteFromSomething(@Parameter(name = "id", description = "desc", `in` = ParameterIn.PATH)
                          @PathVariable id: UUID,
                          @RequestParam @Parameter(description = "desc",
                                  style = ParameterStyle.FORM, explode = Explode.FALSE, array = ArraySchema(schema = Schema(type = "string"))) xyz: MutableList<String>) {
        return "something";
    }

**Expected behavior**
- A clear and concise description of what you expected to happen. 
   I want to request a list of String and want style as 'form' and explode as 'false' to be generated in my api-docs.

- What is the expected result using OpenAPI Description (yml or json)?
      I want my api-docs to be generated exactly as below:
      
      - name: xyz
        in: query
        description: "desc"
        required: true
        schema:
          type: array
          items:
            type: string
        style: form
        explode: false

**Comment by bnasslahsen** [comment]
@kdss91, 

 We don't see any issue from your description.

 There is no need to open new ticket.
 This ticket will remain closed and can be reopened if any relevant information is provided.

**Comment by kdss91** [comment]
Hi @bnasslahsen ,

For schema type array, I am not able to set explode property as false. I can change the description if there is any doubt in that.

I have specified in the above comments that I am specifically looking to generate explode property as false for ArraySchema.

- name: xyz
  in: query
  description: "desc"
  required: true
  style: form
  schema:
    type: array
    items:
      type: string

**Comment by bnasslahsen** [comment]
make sure you are using the [last stable version](https://github.com/springdoc/springdoc-openapi/releases/tag/v1.5.2)

**Comment by kdss91** [comment]
@bnasslahsen 

Thanks, I saw it was just corrected in the latest version.
