### ISSUE TITLE
Arguments where @AuthenticationPrincipal is applied indirectly should be ignored

### ISSUE THREAD

**Issue by pavilalopes** [springdoc/springdoc-openapi#1033]
**Describe the bug**
As documented in https://springdoc.org/#spring-security-support, I was expecting method parameters annotated with @AuthenticationPrincipal to be omitted from the service specification. This does not work if the @AuthenticationPrincipal annotation is applied indirectly via a custom annotation.

In other words, Spring Security supports replacing something like this:
```java
@RequestMapping(value = "/{somethingId}", method = RequestMethod.GET)
Something getSomething(@AuthenticationPrincipal(expression = "domainId") Integer domainId, @PathVariable int somethingId) {
    // ...
}
```
With something like this:
```java
@RequestMapping(value = "/{somethingId}", method = RequestMethod.GET)
Something getSomething(@MyCustomAnnotation Integer domainId, @PathVariable int somethingId) {
    // ...
}
```
Where @AuthenticationPrincipal is applied to MyCustomAnnotation:
```java
@Target({ElementType.PARAMETER})
@Retention(RetentionPolicy.RUNTIME)
@Documented
@AuthenticationPrincipal(expression = "domainId")
public @interface MyCustomAnnotation {}
```

Springdoc does not appear to be able to detect the indirect application of @AuthenticationPrincipal, and proceeds to include domainId parameter in the service specification, when in fact it should be omitted.

- What version of spring-boot you are using?
  - 2.3.1.RELEASE
- What modules and versions of springdoc-openapi are you using?
  - springdoc-openapi-webmvc-core 1.5.2
  - springdoc-openapi-security 1.5.2

**Comment by bnasslahsen** [comment]
This is correctly handled. And you have here the exact  [test case.](https://github.com/springdoc/springdoc-openapi/blob/master/springdoc-openapi-security/src/test/java/test/org/springdoc/api/app7/CurrentUser.java) are passing without any issue. 

You have guidance on the [documentation](https://springdoc.org/#how-can-i-ignore-authenticationprincipal-parameter-from-spring-security).

Make sure `springdoc-openapi-security` is loaded.

if you want to declare an issue, make sure you add a [minimal reproducible sample.](https://github.com/springdoc/springdoc-openapi/blob/master/CONTRIBUTING.adoc)

This ticket will be closed. And can be reopened if you provide any further relevant information.
