### ISSUE TITLE
Swagger UI: Support Open ID Connect Security Scheme

### ISSUE THREAD

**Issue by daniel-shuy** [springdoc/springdoc-openapi#1038]
**Describe the bug**
`springdoc-openapi-ui` with `SecurityScheme.Type.OPENIDCONNECT` displays a blank Authorization popup.
![image](https://user-images.githubusercontent.com/17351764/105864584-0e05fb80-602d-11eb-8f18-a626a727e285.png)

**To Reproduce**
- What version of spring-boot you are using? `2.4.1`
- What modules and versions of springdoc-openapi are you using? `springdoc-openapi-ui:1.5.1`
- Example OpenAPI Description?
```json
{
  "openapi":"3.0.1",
  "servers":[
    {
      "url":"http://localhost:8080/api",
      "description":"Generated server url"
    }
  ],
  "security":[
    {
      "openIdConnect":[]
    }
  ],
  "paths": {},
  "components":{
    "schemas": {},
    "securitySchemes":{
      "openIdConnect":{
        "type":"openIdConnect",
        "openIdConnectUrl":"http://localhost:18080/auth/realms/sample/.well-known/openid-configuration"
      }
    }
  }
}
```
- Provide with a sample code (HelloController) or Test that reproduces the problem:
```java
new OpenAPI()
    .addSecurityItem(new SecurityRequirement()
        .addList("openIdConnect")
    )
    .components(new Components()
        .addSecuritySchemes("openIdConnect", new SecurityScheme()
            .type(SecurityScheme.Type.OPENIDCONNECT)
            .openIdConnectUrl("http://<serverUrl>/.well-known/openid-configuration")
        )
    );
```

**Expected behavior**
Swagger UI should support the Open ID Connect Security Scheme. eg. when using the same OpenAPI Description on https://petstore.swagger.io, the following popup is displayed when clicking on the Authorize button, and is fully functional:
![image](https://user-images.githubusercontent.com/17351764/105864978-7228bf80-602d-11eb-8e02-c3a476c648eb.png)

**Screenshots**

**Additional context**

**Comment by bnasslahsen** [comment]
Please read the [contribution guide ](https://github.com/springdoc/springdoc-openapi/blob/master/CONTRIBUTING.adoc), before opening this kind issues.

Make sure you are using the last stable version, ie `v1.5.3 `before reporting any issue.
The last swagger-ui versions has fixed some issues about openid connect.
