### ISSUE TITLE
Application failed to start - An attempt was made to call a method that does not exist. The attempt was made from the following location:  org.springframework.cloud.stream.binder.rabbit.config.RabbitServiceAutoConfiguration.configureCachingConnectionFactory(RabbitServiceAutoConfiguration.java:72) 

### ISSUE THREAD

**Issue by shalini12kohli** [springdoc/springdoc-openapi#1039]
I'm using spring boot 2.3.1.RELEASE and spring-cloud-services.version 2.0.0.RC2 and spring-cloud.version Hoxton.M1, i am facing following issue while starting application:
 APPLICATION FAILED TO START
 ***************************
Description:
An attempt was made to call a method that does not exist. The attempt was made from the following location:
org.springframework.cloud.stream.binder.rabbit.config.RabbitServiceAutoConfiguration.configureCachingConnectionFactory(RabbitServiceAutoConfiguration.java:72)
The following method did not exist:
org.springframework.boot.autoconfigure.amqp.RabbitProperties.isPublisherConfirms()Z
The method's class, org.springframework.boot.autoconfigure.amqp.RabbitProperties, is available from the following locations:
 jar:file:/home/vcap/app/BOOT-INF/lib/spring-boot-autoconfigure-2.3.1.RELEASE.jar!/org/springframework/boot/autoconfigure/amqp/RabbitProperties.class
 The class hierarchy was loaded from the following locations:
 org.springframework.boot.autoconfigure.amqp.RabbitProperties: file:/home/vcap/app/BOOT-INF/lib/spring-boot-autoconfigure-2.3.1.RELEASE.jar
 Action:
 Correct the classpath of your application so that it contains a single, compatible version of org.springframework.boot.autoconfigure.amqp.RabbitProperties

Can anyone please help me with this issue

**Comment by bnasslahsen** [comment]
Make sure your read the [contribution](https://github.com/springdoc/springdoc-openapi/blob/master/CONTRIBUTING.adoc) guide.
