### ISSUE TITLE
Adding springdoc-openapi-ui dependency to my Spring Boot 2.1 application breaks my public/index.html welcome page

### ISSUE THREAD

**Issue by patrickhancke** [springdoc/springdoc-openapi#104]
Spring Boot: 2.1.8.RELEASE
springdoc-openapi-ui: 1.1.45

custom property: springdoc.swagger-ui.path=/api-docs.html

I have a static welcome page defined in the "public/index.html" file, placed in the default location as advised by Spring Boot.

This welcome page is shown on the root as long as I don't add the "springdoc-openapi-ui" dependency. As soon as I add the dependency, I get a 404 error on the welcome page.

**Comment by patrickhancke** [comment]
I tried to downgrade the "springdoc-openapi-ui" dependency to investigate the issue. I didn't try all intermediate versions (way too many) but found that the above issue is not present with version 1.1.20. It is however present with version 1.1.30.

**Comment by patrickhancke** [comment]
It starts breaking from version 1.1.23 on.

**Comment by M0rfic** [comment]
I've had a similar issue recently. I did some debugging and I suspect it has something to do with the [SwaggerConfig](https://github.com/springdoc/springdoc-openapi/blob/master/springdoc-openapi-ui/src/main/java/org/springdoc/ui/SwaggerConfig.java) static resource handler setup:

```java
@Configuration
@EnableWebMvc
@SuppressWarnings("deprecation")
public class SwaggerConfig extends WebMvcConfigurerAdapter { // NOSONAR

	@Value(SWAGGER_UI_PATH)
	private String swaggerPath;

	@Override
	public void addResourceHandlers(ResourceHandlerRegistry registry) {
		String uiRootPath = "";
		if (swaggerPath.contains("/")) {
			uiRootPath = swaggerPath.substring(0, swaggerPath.lastIndexOf('/'));
		}
		registry.addResourceHandler(uiRootPath + "/**").addResourceLocations(WEB_JARS_PREFIX_URL + "/")
				.resourceChain(false);
	}
}
```

I also have one such configuration for the angular pages:
```java
    @Override
    public void addResourceHandlers(ResourceHandlerRegistry registry) {
        registry.addResourceHandler("/*").addResourceLocations("classpath:/static/");
    }
```

I imagine that the springdoc config overrides mine since the resulting root path is "/". Not sure what the best solution is yet, but my current workaround is to define a different path for springdoc in `application.yaml`:

```yaml
springdoc:
    swagger-ui:
        # do not forget the trailing / to avoid clashes between resource handler configured by MyOwnServerConfig & SwaggerConfig
        # also update the paths in SwaggerUiRedirectController
        path: /api-viewer/
```

I also have added a "_redirect controller_" to redirect from `/api-viewer` to `/api-viewer/`
```java
@Controller
public class SwaggerUiRedirectController {
    @RequestMapping("/api-viewer")
    public String swaggerUi() {
        return "redirect:/api-viewer/";
    }
}
```

**Comment by springdoc** [comment]
Hi, 

 If you already have static content on your root, and you don't want it to be overridden by springdoc-openapi-ui configuration, you can just define a custom configuration of the swagger-ui, in order not to override the configuration of your files from in your context-root:

For example use:
- springdoc.swagger-ui.path=/swagger-ui/api-docs.html

**Comment by patrickhancke** [comment]
This solves my issue, thanks.
I previously configured

`springdoc.swagger-ui.path=/api-docs.html`

but now reconfigured as you suggested. It now works fine with version 1.1.45 of _springdoc-openapi-ui_.
