### ISSUE TITLE
Support for Java Record

### ISSUE THREAD

**Issue by christophe-f** [springdoc/springdoc-openapi#1041]
**Is your feature request related to a problem? Please describe.**
Schemas are not generated when using Java Record

**Describe the solution you'd like**
I would like to see my schema definitions generated from a record.

**Describe alternatives you've considered**
Not using Java Records and revert to Lombok :(

**Comment by bnasslahsen** [comment]
springdoc-openapi is built on top of spring-boot, swagger-core and swagger-ui libraries.
This enhancement request should be submitted to [swagger-core](https://github.com/swagger-api/swagger-core) library first.
Once available, we can add it to sprindoc-openapi.
