### ISSUE TITLE
springdoc-openapi-ui: I did not customize, but overwrite dummy data by default

### ISSUE THREAD

**Issue by traeper** [springdoc/springdoc-openapi#1043]
https://github.com/springdoc/springdoc-openapi/issues/1042

Unfortunately my opinion is not about a customization by `OpenAPI Bean` but **default settings.**
Even though I didn't customize, the data in my openapi3 spec file is not reflected properly.

**Comment by bnasslahsen** [comment]
You don't need to open new issues.
You can add your comments to your original ticket. If relevant, it will be reopened.
This ticket will be deleted.
