### ISSUE TITLE
Default ApiResponses order && group order option

### ISSUE THREAD

**Issue by YunaBraska** [springdoc/springdoc-openapi#1046]
**Is your feature request related to a problem? Please describe.**
- We are generating our API docs and create a MR to verify and track changes. Since humans are reviewing the changes, it's annoying when the order of some objects are just random or unlogical. We are currently defining our sorting by using `OpenApiCustomiser` which are now in every team I have been kind of the same.
- Endpoints are not in the order as they are defined in the class. `operations-sorter: method` Is really nice for the operations like GET, PUT, POST,... but not enough for the endpoint order itself.
- Responses are without the `OpenApiCustomiser` not sortable at all as far as I have seen.
- We are using yaml and json

**Describe the solution you'd like**
1) First we would love to have descriptions to JavaDoc and Spring properties which are not described properly. We know about sorting parameters `alpha` and `method`, are there more? couldn't find the implementation of these :( 
2) Response order should be default always the same currently we are archiving this by simply using a TreeMap
```java
private OpenAPI sortResponses(final OpenAPI openApi) {
        openApi.getPaths().values().forEach(path -> path.readOperations().forEach(operation -> {
            var sorted = new TreeMap<>(operation.getResponses());
            operation.getResponses().clear();
            operation.getResponses().putAll(sorted);
        }));
        return openApi;
    }
```
3) Would be nice to have a possibility to order the endpoints. E.g. `@Tag(order = 1)` or `@Operation(order = 1)` (I guess the current order comes from the unsorted spring RequestMappingHandler)
We currently archive that with the combination of `operations-sorter: method` and customisation were we put numbers on the Tag name (e.g. `@Tag(name = "[0] General")`) logic behind looks like this:
```java
private void sortByTag(final OpenAPI openApi) {
        sortEndpoints(openApi, (o1, o2) -> String.CASE_INSENSITIVE_ORDER.compare(o1.getValue().readOperations().toString(), o2.getValue().readOperations().toString()));
        removeOrderPrefixKeys(openApi);
    }
private OpenAPI removeOrderPrefixKeys(final OpenAPI openApi) {
        openApi.getPaths().values().forEach(item -> item.readOperations().forEach(operation -> {
            if (operation != null && operation.getTags() != null) {
                operation.setTags(operation.getTags().stream().map(tag -> tag.replaceAll("^\\[\\d*]", "")).collect(toList()));
            }
        }));
        return openApi;
    }
```

**Comment by bnasslahsen** [comment]
@YunaBraska, 

 For order, you can use `springdoc.writer-with-order-by-keys=true`, which will give you all time the same order.
 Isn't that what you expecting?

**Comment by YunaBraska** [comment]
@bnasslahsen wow cool the config `springdoc.writer-with-order-by-keys=true` works 👍 Tank you!
So then only endpoint order and better yaml docs is missing ;)

**Comment by bnasslahsen** [comment]
@YunaBraska, 

 The endpoint order will be the same if you use the property listed above.
 This enables a deterministic/alphabetical orderding, of your endpoints.
 This property is available for yaml and json.

 Ordering the endpoints using other criteria, is very specific to projects, and we prefer let each project customise it.

 For the `@Tag` annotation, with `order` attribute. This is not a springdoc-openapi annotation. You can ask for this enhancement in the swagger-core project instead.
