### ISSUE TITLE
Web Flux OpenApi FilePart Showing unwanted special characters in Filename

### ISSUE THREAD

**Issue by susimsek** [springdoc/springdoc-openapi#1048]
Hi,when I try to upload files in openapi ui, there are unwanted special characters in filename.
Openapi ui has utf8 encoding problem for FilePart class type.
It works fine when I send the same request via postman.

The request I sent via open api ui.

![image](https://user-images.githubusercontent.com/46258776/106360033-6851d580-6327-11eb-8a4f-2e807d50fc9c.png)

The request I sent via postman.

![image](https://user-images.githubusercontent.com/46258776/106360120-cd0d3000-6327-11eb-80f7-8f5f2d65a0d0.png)

Framework Version Information: 

Java Version : **11**
Spring Boot Version: **2.4.1**
Springdoc Openapi Webflux Ui Version : **1.5.2**

My File Upload Endpoint Controller

```
@ApiResponses({
            @ApiResponse(responseCode = "200", description = "Ok",content = @Content(schema = @Schema(implementation = FileResponseDto.class))),
            @ApiResponse(responseCode = "500", description = "Internal Server Error",content = @Content)

    })
    @Operation(summary = "Upload new File")
    @PostMapping(value = "/files", consumes = MediaType.MULTIPART_FORM_DATA_VALUE )
    @ResponseStatus(HttpStatus.OK)
    public Mono<FileResponseDto> uploadFile(@RequestPart(name = "file") @Parameter(description = "File to be uploaded", content = @Content(mediaType = MediaType.APPLICATION_OCTET_STREAM_VALUE)) Mono<FilePart> file){
        return fileService.uploadFile(file);
    }
```

My File Upload Endpoint Service

```
public Mono<FileResponseDto> uploadFile(Mono<FilePart> filePart) {
        BasicDBObject object = new BasicDBObject();
        object.put("type","file");

         return filePart.flatMap(part ->
                 gridFsOperations.store(part.content(), part.filename(),object)
                 .map(objectId -> FileResponseDto.builder()
                         .id(objectId.toHexString())
                         .name(part.filename())
                         .uploadedDate(objectId.getDate())
                         .build())
         );
    }

```

Any help would be appreciated.

**Comment by bnasslahsen** [comment]
@susimsek, 

 springdoc-openapi generates the OpenAPI description of your api under /v3/api-docs.
 If you have any issue there, we can have look at it.

 The parsing of the file name, is done by swagger-ui and not springdoc-openapi.
