### ISSUE TITLE
@Hidden at class level ignored on default path mapping methods in 1.5.3

### ISSUE THREAD

**Issue by sgrimm** [springdoc/springdoc-openapi#1049]
I have some controller classes that are not ready to expose in the API docs yet, so I annotated them with `@Hidden` to hide all their endpoints. 1.5.3 changed the behavior of that annotation at the class level. Example code (Kotlin):

```java
@RequestMapping("/foo/bar")
@RestController
@Hidden
public class MyController {
    @GetMapping
    @Operation(summary = "An endpoint without a subpath")
    public String getAll() {
        return "the result";
    }

    @GetMapping("/baz")
    @Operation(summary = "An endpoint with a subpath")
    public String getBaz() {
        return "the other result";
    }
}
```

Under 1.5.2, both of these endpoints would be excluded from the generated API docs thanks to the `@Hidden` annotation at the class level.

Under 1.5.3, the `getAll()` endpoint shows up in the docs, but `getBaz()` continues to be hidden.

Explicitly annotating `getAll()` with `@Hidden` causes it to be hidden.

**Comment by bnasslahsen** [comment]
@sgrimm, 

 With v1.5.3, there have been an enhancement of operation scaning mecanism https://github.com/springdoc/springdoc-openapi/issues/1020.

If the developer adds the @Operation annotation, we assume that he wants his Rest API to be scanned. Unless, you have added hidden on the `@Operation` attribute.
 - This is just confusing, when you combine two swagger annotations, that are describing two opposite behaviors:
   -  `@Operation` with hidden attribute equals to `false`.
   - `@Hidden` with hidden attribute equals to `true`

For your case, simply, remove the `@Operation `annotations, which are useless in your case, and the `@Hidden` annotation will work on the controller level as well as expected.
