### ISSUE TITLE
Add support for addPathPrefix with Webflux swagger-ui

### ISSUE THREAD

**Issue by shota-hizawa-reazon** [springdoc/springdoc-openapi#1050]
**Describe the Feature**
When we use WebFluxConfigurer to set base-path, it's unable to access `http://server:port/context-path/swagger-ui.html`.
We can access to `http://server:port/context-path/v3/api-doc` though.
![image](https://user-images.githubusercontent.com/70615091/106597362-a6eec680-6599-11eb-9a65-7c99caf5652f.png)
![image](https://user-images.githubusercontent.com/70615091/106598312-e964d300-659a-11eb-840b-f12aaca54522.png)

WebfluxConfigurer
```
@Configuration
@EnableWebFlux
class WebFluxConfiguration : WebFluxConfigurer {

    override fun configurePathMatching(configurer: PathMatchConfigurer) {
        configurer.addPathPrefix("/api/v1") { true }
    }
}
```

In this case, `context-path` should be replaced with `/api/v1`, so we should see swagger-ui at `http://server:port/api/v1/swagger-ui.html`.

![image](https://user-images.githubusercontent.com/70615091/106597400-b66e0f80-6599-11eb-8a62-3404daf6eda9.png)

It seems like that context-path is not loaded when generating the url of springdoc-config, because we can access to `http://server:port/api/v1/v3/api-docs/swagger-config`.
![image](https://user-images.githubusercontent.com/70615091/106597492-d69dce80-6599-11eb-8f63-4f62bce22ec8.png)

**To Reproduce**
- What version of spring-boot you are using?
Running with Spring Boot v2.4.0, Spring v5.3.1

- What modules and versions of springdoc-openapi are you using?
Using springdoc-openapi-webflux-ui v1.5.2 with springdoc-openapi-kotlin v.1.5.2

- Provide with a sample code (HelloController) or Test that reproduces the problem
I put a sample code to set context-path by WebFluxConfigurer above. so please refer that.

**Expected behavior**
We should be able to access swagger-ui.html

**Comment by bnasslahsen** [comment]
@shota-hizawa-reazon, 

 This seems to be a dupblicate of https://github.com/springdoc/springdoc-openapi/issues/1034.
Have you tested with the latest stable release: v1.5.3 ?

**Comment by shota-hizawa-reazon** [comment]
@bnasslahsen,

I've tested v1.5.3 now, but I got the same error as #1047.

```
Description:

Parameter 3 of method swaggerWelcome in org.springdoc.webflux.ui.SwaggerConfig required a bean of type 'org.springframework.boot.autoconfigure.web.reactive.WebFluxProperties' that could not be found.


Action:

Consider defining a bean of type 'org.springframework.boot.autoconfigure.web.reactive.WebFluxProperties' in your configuration.
```

As you say, the problem itself seems to be a duplicate of #1037, so I close this.
Thank you for your quick reply!

**Comment by shota-hizawa-reazon** [comment]
I tried `springdoc-openapi-webflux-ui: v1.5.4`, but I'm still unable to access to Swagger UI with base-path settings.

```kotlin
@Configuration
@EnableWebFlux
class WebFluxConfiguration : WebFluxConfigurer {

    override fun configurePathMatching(configurer: PathMatchConfigurer) {
        configurer.addPathPrefix("/api/v1") { true }
    }
```

In my WebFluxConfigurer, I set the `base-path ` to `/api/v1`.
Then, I opened `http://localhost:<PORT>/api/v1/swagger-ui.html`, however, the page shows error and console also shows  errors.
![image](https://user-images.githubusercontent.com/70615091/108038818-a3ba0700-707e-11eb-89a5-e2a5593c430c.png)

If I  comment out the base-path settings shown above, and open `http://localhost:<PORT>/swagger-ui.html`, it works.

Anything I’m missing?

**Comment by bnasslahsen** [comment]
@shota-hizawa-reazon, 

 This seems a different problem, as you are setting the path prefix using `addPathPrefix`.
 This one is not supported yet.

**Comment by bnasslahsen** [comment]
@shota-hizawa-reazon, 

The support is now added.
You can test it using the latest snapshot.

**Comment by shota-hizawa-reazon** [comment]
@bnasslahsen,

I've tested with the latest of 1.5.5-SNAPSHOT, and it works.
Thank you so much!

**Comment by Zaky7** [comment]
> @bnasslahsen,
> 
> I've tested with the latest of 1.5.5-SNAPSHOT, and it works.
> Thank you so much!

@shota-hizawa-reazon can ping me how can I enable this without changing the autoconfiguration of spring web flux?. That is without @EnableWebFlux annotation
