### ISSUE TITLE
IllegalStateException in org.springdoc.core.SpringDocConfiguration$OpenApiResourceAdvice.handleNoHandlerFound

### ISSUE THREAD

**Issue by speralta** [springdoc/springdoc-openapi#1051]
**Describe the bug**
OpenApiResourceNotFoundException handler fails with IllegalStateException
```
[19303290-1373] There was an unexpected error (type=Internal Server Error, status=500).
Could not resolve parameter [1] in public org.springframework.http.ResponseEntity<org.springdoc.api.ErrorMessage> org.springdoc.core.SpringDocConfiguration$OpenApiResourceAdvice.handleNoHandlerFound(org.springdoc.api.OpenApiResourceNotFoundException,org.springframework.web.context.request.WebRequest): No suitable resolver
java.lang.IllegalStateException: Could not resolve parameter [1] in public org.springframework.http.ResponseEntity<org.springdoc.api.ErrorMessage> org.springdoc.core.SpringDocConfiguration$OpenApiResourceAdvice.handleNoHandlerFound(org.springdoc.api.OpenApiResourceNotFoundException,org.springframework.web.context.request.WebRequest): No suitable resolver
	at org.springframework.web.reactive.result.method.InvocableHandlerMethod.getMethodArgumentValues(InvocableHandlerMethod.java:197)
	Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException: 
Error has been observed at the following site(s):
	|_ checkpoint ⇢ HTTP GET "/v3/api-docs/test" [ExceptionHandlingWebHandler]
```

**To Reproduce**
On spring boot 2 Web flux with Open API 3 demo for example :
http://158.101.164.60:8082/v3/api-docs/test
- What version of spring-boot you are using?
2
- What modules and versions of springdoc-openapi are you using? 
1.5.3
- What is the actual and the expected result using OpenAPI Description (yml or json)? 
N/A
- Provide with a sample code (HelloController) or Test that reproduces the problem
I use springdoc demo site to reproduce

**Expected behavior**
- A clear and concise description of what you expected to happen.
A correct error handling
- What is the expected result using OpenAPI Description (yml or json)?
N/A

**Comment by bnasslahsen** [comment]
@speralta, 

 Can you add the source code of your [sample](https://stackoverflow.com/help/minimal-reproducible-example) to reproduce this issue. (this is the most important part)?

**Comment by speralta** [comment]
I did use your hosted sample.

**Comment by bnasslahsen** [comment]
Not sure which [sample](https://springdoc.org/#springdoc-applications-demos) you are refering to.
They are all deployed without any issue!

**Comment by speralta** [comment]
The link i used is on the README.md here : https://github.com/springdoc/springdoc-openapi/blob/master/README.md

**Comment by bnasslahsen** [comment]
Much clearer, with your last line description!
