### ISSUE TITLE
spring app not starting when no validator implementation is present in the classpath

### ISSUE THREAD

**Issue by danitutu** [springdoc/springdoc-openapi#1055]
**Describe the bug**
When adding `springdoc-openapi-webflux-ui` in the classpath spring boot app won't start because it is missing an implementation of the validation API. I noticed that when I add springdoc to the project it also fetches `jakarta-validation-api`.

```
***************************
APPLICATION FAILED TO START
***************************

Description:

The Bean Validation API is on the classpath but no implementation could be found

Action:

Add an implementation, such as Hibernate Validator, to the classpath
```

My application doesn't use the bean validation at all. It's a Kotlin Spring Boot App with functional endpoints.

**To Reproduce**
spring boot version: 2.3.5.RELEASE
springdoc-openapi version: 1.5.3

1. make sure not validation dependency is in the classpath
2. make sure webflux with functional endpoints is used
3. add `springdoc-openapi-webflux-ui` to the project
4. run the application  => it should fail at startup

**Expected behavior**
When no bean validation is used in the project then springdoc-openapi should not require a bean implementation.

**Screenshots**
-

**Additional context**
-

**Comment by bnasslahsen** [comment]
@danitutu,

 Please provide a [Minimal, Reproducible Example - with HelloController ](https://stackoverflow.com/help/minimal-reproducible-example)that reproduces the problem

**Comment by nkvaratskhelia** [comment]
Same problem with `springdoc-openapi-ui` dependency. I had to add `spring-boot-starter-validation` to make it work, even though I'm not using bean validation.

In my case the version of spring boot is `2.4.2`.

**Comment by bnasslahsen** [comment]
@nkvaratskhelia, 

 Please provide a[ Minimal, Reproducible Example - with HelloController ](https://stackoverflow.com/help/minimal-reproducible-example)that reproduces the problem.

This ticket will be closed, and might be reopened if the relevant information is provided.

**Comment by nkvaratskhelia** [comment]
> @nkvaratskhelia,
> 
> Please provide a[ Minimal, Reproducible Example - with HelloController ](https://stackoverflow.com/help/minimal-reproducible-example)that reproduces the problem.
> 
> This ticket will be closed, and might be reopened if the relevant information is provided.

There's no need to provide it from my side. Like I mentioned in the previous comment, the problem in my case is with vault dependency and not springdoc dependency. So yeah, for me this issue can be closed but I can't say the same about danitutu's case, though. Not sure what caused his prolem.
