### ISSUE TITLE
Schema of Spring Data Sort not generated correctly

### ISSUE THREAD

**Issue by tobi6112** [springdoc/springdoc-openapi#1056]
**Describe the bug**
I would like to use `org.springframework.data.domain.Sort` as a query parameter for my controller. However the resulting OpenApi schema does not match my expectation and does not represent the behaviour. (See the code sample for a practical explanation)

**To Reproduce**
- What version of spring-boot you are using?
- What modules and versions of springdoc-openapi are you using?
```xml
<dependency>
  <groupId>org.springdoc</groupId>
  <artifactId>springdoc-openapi-hateoas</artifactId>
  <version>1.5.3</version>
</dependency>
<dependency>
  <groupId>org.springdoc</groupId>
  <artifactId>springdoc-openapi-ui</artifactId>
  <version>1.5.3</version>
</dependency>
<dependency>
  <groupId>org.springdoc</groupId>
  <artifactId>springdoc-openapi-webmvc-core</artifactId>
  <version>1.5.3</version>
</dependency>
<dependency>
  <groupId>org.springdoc</groupId>
  <artifactId>springdoc-openapi-data-rest</artifactId>
  <version>1.5.3</version>
</dependency>
```
- What is the actual and the expected result using OpenAPI Description (yml or json)?

Actual:
```json
{
  "Sort":{
    "type":"object",
    "properties":{
      "sorted":{
        "type":"boolean"
      },
      "unsorted":{
        "type":"boolean"
      },
      "empty":{
        "type":"boolean"
      }
    }
  }
}
```

Expected:
```json
{
  "Sort": {
    "type":"object",
    "additionalProperties": {
      "type":"string"
    }
  }
}
```

- Provide with a sample code (HelloController) or Test that reproduces the problem

Simple, but easy:
```java
@GetMapping(value = "foos")
public ResponseEntity<List<Foo>> getFoo(Sort sort) throws Exception {
  var foo = fooService.getFoos();
  return ResponseEntity.ok(foo);
}
```
I would now be able to sort the results by calling `/foos?sort=foo` whenever I would actually pass it into a repository query method.

Here is a repository which reproduces the issue: https://github.com/tobi6112/springdoc-issue-demo

**Comment by bnasslahsen** [comment]
This is not an issue, but an enhancement request. 
There is no actual direct support of Sort.
This is nice to have. But not a priority. 

You can propose a PR, if you feel it useful for the community. If you are interested on that, i will reopen the ticket.

For the case you are describing, simply use standard swagger annotations: `@Parameter(schema = @Schema(type = "string")) `
