### ISSUE TITLE
Malformed spec with path variables and command object

### ISSUE THREAD

**Issue by sciros** [springdoc/springdoc-openapi#1058]
**Describe the bug**
Short description: if a Spring controller is using path variables in its URL mapping and a command object in its method signature (where the command object is constructed from the path variables automagically), the OpenAPI spec that gets automatically generated for this basically ignores the path variables and this leads to validation errors.

Long description:
I am trying to generate an OpenAPI spec with Springdoc for a Spring Boot controller. I have a mapping for a path that has multiple path variables and the method signature accepts a command object (the command object is automatically constructed from these path variables). The generated JSON/YAML spec does not appear to be valid.

Code snippet I'm referring to:
```
@GetMapping("/myPath/{foo}/{bar}/{baz}")
public Mono<MyServiceResponse> doSomethingInteresting(@Valid DoSomethingInterestingCommand command) {
    return interestingService.doSomethingInteresting(command);
}
```

The OpenApi snippet this generates is:
```
paths:
  '/myPath/{foo}/{bar}/{baz}':
    get:
      tags:
        - my-controller
      operationId: doSomethingInteresting
      parameters:
        - name: command
          in: query
          required: true
          schema:
            $ref: '#/components/schemas/DoSomethingInterestingCommand'
```

This then yields errors such as this:
```
Semantic error at paths./myPath/{foo}/{bar}/{baz}
Declared path parameter "foo" needs to be defined as a path parameter at either the path or operation level
```
My workaround so far has been to use Parameter annotations, which I can live with, but with 1 annotation per path variable and then an additional one to hide the command parameter, it starts to clutter up my code.

Am I doing something wrong or is this a misbehavior of the springdoc package? 

**To Reproduce**
- What version of spring-boot you are using? 2.4.2
- What modules and versions of springdoc-openapi are you using? springdoc-openapi-webflux-ui:1.5.2
- What is the actual and the expected result using OpenAPI Description (yml or json)?
Actual: 
```
paths:
  '/myPath/{foo}/{bar}/{baz}':
    get:
      tags:
        - my-controller
      operationId: doSomethingInteresting
      parameters:
        - name: command
          in: query
          required: true
          schema:
            $ref: '#/components/schemas/DoSomethingInterestingCommand'
```
Expected: 
```
parameters:
      - name: foo
        in: path
        required: true
        schema:
          type: string
      - name: bar
        in: path
        required: true
        schema:
          type: string
      - name: baz
        in: path
        required: true
        schema:
          type: string
```
- Provide with a sample code (HelloController) or Test that reproduces the problem
```
@GetMapping("/myPath/{foo}/{bar}/{baz}")
public Mono<MyServiceResponse> doSomethingInteresting(@Valid DoSomethingInterestingCommand command) {
    return interestingService.doSomethingInteresting(command);
}
```

**Expected behavior**
- See above

**Screenshots**
N/A

**Additional context**
N/A

**Comment by bnasslahsen** [comment]
@sciros,

 Not sure you could find easy way to automate this. If you find out, your PR will be welcome.
You can simply use the swagger-annotations as follow:


```java
@RequestMapping("/foo/bar")
@RestController
public class HelloController {

	@GetMapping("/myPath/{foo}/{bar}/{baz}")
	public String doSomethingInteresting(@ParameterObject DoSomethingInterestingCommand command) {
		System.out.println(command);
		return null;
	}

	class DoSomethingInterestingCommand {

		@Parameter(in = ParameterIn.PATH)
		private String foo;

		@Parameter(in = ParameterIn.PATH)
		private String bar;

		@Parameter(in = ParameterIn.PATH)
		private String baz;

		public String getFoo() {
			return foo;
		}

		public void setFoo(String foo) {
			this.foo = foo;
		}

		public String getBar() {
			return bar;
		}

		public void setBar(String bar) {
			this.bar = bar;
		}

		public String getBaz() {
			return baz;
		}

		public void setBaz(String baz) {
			this.baz = baz;
		}
	}

}
```

**Comment by sciros** [comment]
Thanks for the fast feedback, @bnasslahsen. Your proposed workaround feels more elegant than what I was doing (stacking Parameter annotations on the Controller method) so it's very welcome. I'll see if I can think of a way to automate the generation.
Cheers.
