### ISSUE TITLE
Support per method security requirement in RepositoryRestResource

### ISSUE THREAD

**Issue by bschoenmaeckers** [springdoc/springdoc-openapi#1059]
**Is your feature request related to a problem? Please describe.**
I'm using spring-data-rest to export rest endpoints for a repository. This works great but the @SecurityRequirement annotation does only work on the class level. I would like to give each method a different security requirement.

Example:
```Java
@RepositoryRestResource(excerptProjection = UserBasicProjection.class)
public interface UserRepository extends JpaRepository<User, Long> {

    @Override
    @IsAuthenticated
    Optional<User> findById(Long id);

    @IsAuthenticated
    Optional<User> findOneByEmailAndDeletedIsFalse(String email);

    @Override
    @IsAdmin
    Page<User> findAll(Pageable pageable);

    @IsAdmin
    List<User> findByDebtIsGreaterThan(double debt);
 
    ....
}
``` 

`@IsAdmin` infers `@SecurityRequirement(name = OAUTH2_SECURITY_SCHEME, scopes = "api_admin")`
`@IsAuthenticated` infers `@SecurityRequirement(name = OAUTH2_SECURITY_SCHEME, scopes = "api_full")`

**Describe the solution you'd like**

The DataRestTagsService should check the actual repository method in addition to the repository type.
https://github.com/springdoc/springdoc-openapi/blob/4a25acfcd4b3556f2562daba5cb221f11e4d5a03/springdoc-openapi-data-rest/src/main/java/org/springdoc/data/rest/core/DataRestTagsService.java#L113

**Comment by bnasslahsen** [comment]
@bschoenmaeckers, 

The support is now added.
You can test it using the latest snapshot.

**Comment by bschoenmaeckers** [comment]
Works as expected. Thanks!
