### ISSUE TITLE
Response schemas are merged together using `oneOf` unexpectedly

### ISSUE THREAD

**Issue by lzhoucs** [springdoc/springdoc-openapi#106]
We are using media type versioning for our REST APIs. This means the same API consumes different media types. After using springdoc to product swagger API docs, We found that response schemas are merged together. 

This is a gist of what the API and swagger annotations look like:

```java
@PostMapping(value = "/helloworld", produces = "application/json", consumes = "application/vnd.v1+json")
    @ApiResponses({
        @ApiResponse(responseCode = "200", description = "Successful operation",
            content = @Content(schema = @Schema(implementation = HelloDTO.class))),
        @ApiResponse(responseCode = "400", description = "Bad name",
            content = @Content(schema = @Schema(implementation = ErrorDTO.class)))
    })
    public ResponseEntity<?> hellov1(@RequestBody RequestV1 request)
    {
    }

    @PostMapping(value = "/helloworld", produces = "application/json", consumes = "application/vnd.v2+json")
    @ApiResponses({
        @ApiResponse(responseCode = "200", description = "Successful operation",
            content = @Content(schema = @Schema(implementation = HelloDTO.class))),
        @ApiResponse(responseCode = "400", description = "Bad name",
            content = @Content(schema = @Schema(implementation = ErrorDTO.class)))
    })
    public ResponseEntity<?> hellov2(@RequestBody RequestV2 request)
    {
    }
```
This is a gist of generated API doc where I don't expect to see `ResponseEntityObject`:
```yaml
      responses:
        200:
          content:
            application/json:
              schema:
                oneOf:
                - $ref: '#/components/schemas/ResponseEntityObject'
                - $ref: '#/components/schemas/HelloDTO'
```
This is what it looks like in swagger-ui:
![image](https://user-images.githubusercontent.com/1444104/66232258-1571fa80-e6ae-11e9-9960-66cf26028ac7.png)

Please see demo project for more details: https://github.com/lzhoucs/springboot-demo/tree/springdoc-issue1

If I change one of the path from "/helloworld" to "/helloworld1", the schema won't be merged and I will only see one `HelloDTO` schema as expected. However, we are not doing media type versioning in that case.

Changing `ResponseEntity<?>` to `ResponseEntity<HelloDTO>` and use ControllerAdvice for error handling may work, but I haven't tried as this may not be a good option for us as we have a large number of APIs written in the above style where we declare `ResponseEntity<?>` and return different type of entities based on condition. Again, please see the demo project for details.

**Comment by springdoc** [comment]
Hi, 

 A fix will be available on v1.1.46 of springdoc-openapi.
 For this case, the merge will be based on content element inside @ApiResponse annotation only.
