### ISSUE TITLE
Hide @DecimalMax annotations during rendering maximum for BigDecimal

### ISSUE THREAD

**Issue by santhosh-v** [springdoc/springdoc-openapi#1067]
**Is your feature request related to a problem? Please describe.**
- @DecimalMax annotation is being rendered with wrong precision in swagger-ui. When using BigDecimal and Decimal max for validations, this annotation is respected and this is rendered but the actual precision cannot be kept in swagger ui due to javascript limitation of plotting decimal.
- number data type with maximum and minimum

**Describe the solution you'd like**
- We need to have one option to ignore @DecimalMax annotation. Springfox didnt respected this and didnt had this issue. We added limit as part of description
- Do not provide maximum for @DecimalMax 

**Describe alternatives you've considered**
- A clear and concise description of any alternative solutions or features you've considered.

**Additional context**
- Issue is seen with swagger-ui since it cannot render decimal values like 999999999999.99999 , instead it will be rounded. One option is to use some decimal library with swagger-ui. I dont find any  documentation to render property values with custom plugin. Other option is hide the maximum. For that we need to ignore the @DecimalMax annotation.

**Comment by bnasslahsen** [comment]
@santhosh-v, 

 Your description is not enough to address.
 You need to describe your context (the title of an issue is not enough)
- What version of spring-boot you are using?
- What modules and versions of springdoc-openapi are you using?
- What are the actual and the expected result using OpenAPI Description (yml or json)?
- Provide a [Minimal, Reproducible Example - with HelloController](https://stackoverflow.com/help/minimal-reproducible-example) that reproduces the problem

This ticket will be closed and can be reopened if the relevant information are provided.
