### ISSUE TITLE
Add support for @JsonView annotations in Spring MVC APIs

### ISSUE THREAD

**Issue by joaodias14** [springdoc/springdoc-openapi#107]
Swagger itself already supports @JsonView annotations and is already able to process them when used in JAX-RS APIs. However, Swagger can't process @JsonView annotations used in Spring MVC APIs. Do you think it makes sense to add support for them in **springdoc** project?

**Comment by springdoc** [comment]
Hi, 

 The support of @JsonView was not a priority. It might be possible to support it, if there are many projects that need it.
 Can you provide examples of controllers that show your usage of @JsonView and the expected OpenAPI description ?

**Comment by joaodias14** [comment]
Hi,

Thanks for the quick response. My example:

**Controller**
```
@RestController
public class MealPartiesAdminController {
    @GetMapping(value = "/parties/{id}")
    @JsonView(Views.Public.class)
    @Operation(summary = "Gets meal party details [Meal party admin restricted]")
    @ApiResponses(value = { @ApiResponse(responseCode = "200", description = "Successfully retrieved the meal party") })
    public MealParty getMealParty(@PathVariable("id") long mealPartyId) {
        return this.mealPartyAdminService.getMealParty(mealPartyId);
    }
}
```

**Views definition**
```
public interface Views {
    public interface Public {}
    public interface MealPartyAdmin extends Public {}
}
```

**DTO**
```
public class MealParty {
    @JsonView(Views.Public.class)
    private String name;
    
    @JsonView(Views.MealPartyAdmin.class)
    private List<String> members = new ArrayList<>();
}
```

**OpenAPI description**
```
{
  "openapi": "3.0.1",
  "paths": {
    "/parties/{id}": {
      "get": {
        "summary": "Gets meal party details [Meal party admin restricted]",
        "operationId": "getMealParty",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "schema": {
              "type": "integer",
              "format": "int64"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Successfully retrieved the meal party",
            "content": {
              "*/*": {
                "schema": {
                  "$ref": "#/components/schemas/MealParty"
                }
              },
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/MealParty"
                }
              }
            }
          }
        }
      }
    }
  },
  "components": {
    "schemas": {
      "MealParty": {
        "required": [
          "name"
        ],
        "type": "object",
        "properties": {
          "name": {
            "type": "string"
          },
          "members": {
            "type": "array",
            "items":{
              "type":"string"
            }
          }
        }
      }
    }
  }
}
```

**Expected OpenAPI description**
```
{
  "openapi": "3.0.1",
  "paths": {
    "/parties/{id}": {
      "get": {
        "summary": "Gets meal party details [Meal party admin restricted]",
        "operationId": "getMealParty",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "schema": {
              "type": "integer",
              "format": "int64"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Successfully retrieved the meal party",
            "content": {
              "*/*": {
                "schema": {
                  "$ref": "#/components/schemas/MealParty_PublicView"
                }
              },
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/MealParty_PublicView"
                }
              }
            }
          }
        }
      }
    }
  },
  "components": {
    "schemas": {
      "MealParty_PublicView": {
        "required": [
          "name"
        ],
        "type": "object",
        "properties": {
          "name": {
            "type": "string"
          }
        }
      }
    }
  }
}
```

Swagger has a module specifically to parse JAX-RS Controllers (https://mvnrepository.com/artifact/io.swagger.core.v3/swagger-jaxrs2) if you want to take a look.

Best regards!

**Comment by patips34** [comment]
I am also waiting to have this feature in, currently I need to expose many unnecessary field through the API only because generated swagger has these fields.

**Comment by Stexxen** [comment]
Can you not annotate the field with `@Schema(hidden=true)`

**Comment by springdoc** [comment]
Hi, 

 Support for @JsonView annotations will be available on v1.2.1 of springdoc-openapi;

**Comment by joaodias14** [comment]
Awesome, many thanks!!!

**Comment by patips34** [comment]
> Can you not annotate the field with `@Schema(hidden=true)`

that will cause to hide in request, response. I want to only hide in post request but not in response.

**Comment by Andrew3431** [comment]
@springdoc Could you please share an example on how to use @JsonView in POST methods, where we can hide certain fields only in request and not response ? I am using springdoc-openapi-ui version 1.2.15 and Spring boot 2.1.x

**Comment by springdoc** [comment]
Hello, 

 You can have a look at https://github.com/springdoc/springdoc-openapi/blob/master/springdoc-openapi-webmvc-core/src/test/java/test/org/springdoc/api/app54/SpringDocApp54Test.java.
 Where you can see an example of using `@JsonView` with `@PostMapping`.

**Comment by alizaga** [comment]
Is @JsonView working with spring-webflux?

**Comment by naivefun** [comment]
> https://github.com/springdoc/springdoc-openapi/blob/master/springdoc-openapi-webmvc-core/src/test/java/test/org/springdoc/api/app54/SpringDocApp54Test.java

I don't think so. I just tried latest version with webflux and no luck.

**Comment by naivefun** [comment]
@alizaga  I don't think so. I just tried latest version with webflux and no luck.
