### ISSUE TITLE
support add wrapper for ok response entities

### ISSUE THREAD

**Issue by lmtoo** [springdoc/springdoc-openapi#1072]
the generated schema , don't have wrapper for ok repsonse entities by default.
please provide a configuration like 

> springdoc.wrapper.template={\"code\": 200,\"success\": true,\"msg\": \"success\",\"data\":"$"}

where $ is replaced by default generated eneities

or provide a way to influence eneitie schema generation process

**Comment by bnasslahsen** [comment]
@lmtoo, 

 Your feature request is not clear.
 I encourage you to propose a PR, if you feel it useful for the community and will integrate it if it's not breaking all the existing tests.
