### ISSUE TITLE
Petstore API still visible after disabling it

### ISSUE THREAD

**Issue by helenrensiyu** [springdoc/springdoc-openapi#1076]
Hi, I am using 1.5.4 of springdoc with springboot 2.1.6. I have added springdoc.swagger-ui.disable-swagger-default-url=true to my application,properties file and also created another application.yml file, following the webmvc demo 2, adding

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    disable-swagger-default-url: true

But the default url is still working with the petstore. I tried separately with either file but no luck either. I created a swagger configuration class, following the answers to other issues in this repo but didnt work either. 
I have looked at issue #714 and #1064
Any idea why this is happening?

**Comment by bnasslahsen** [comment]
@helenrensiyu, 

 Only check your configuration...
 If you are still having an issue, you can add the link to a **minimal reproductible sample** with a HelloController, and we can help.

 This ticket will be closed and can be reopened if the relevant information is provided.
