### ISSUE TITLE
Centralized API Documentation

### ISSUE THREAD

**Issue by octopus-prime** [springdoc/springdoc-openapi#108]
Assume more than one micro-service, all implemeting APIs and providing a swagger-ui.
To access all this API documentation from a single URL, a solution can be implemented using the SpringFox library.

See https://dzone.com/articles/centralized-documentation-in-microservice-spring-b

As you can see the implementation uses the classes

- springfox.documentation.swagger.web.SwaggerResource
- springfox.documentation.swagger.web.SwaggerResourcesProvider

which of course are not provided by spingdoc.

So how can i achieve this goal with springdoc?

**Comment by octopus-prime** [comment]
> In addition, this behaviour is very specific to services that relies on Eureka.

Or Zuul, or Kubernetes, etc.
There are a lot of service-discovery implementations in spring.

> Then, you will need the swagger-ui to retrieve the documentation from the registred endpoints

That's the part of question. How to?
Without SwaggerResource and SwaggerResourcesProvider...

**Comment by bnasslahsen** [comment]
Hi @octopus-prime, 

Its now possible to agregate multiple OpenAPI definitions using springdoc-openapi.
Here is a sample in a microservices architecture:
- https://piotrminkowski.com/2020/02/20/microservices-api-documentation-with-springdoc-openapi/
 - https://github.com/piomin/sample-spring-microservices-new

**Comment by kyle18th** [comment]
@bnasslahsen I noticed that it is a spring-cloud-gateway implementation, have you ever thought about zuul?

**Comment by bnasslahsen** [comment]
@kyle18th, 

 Springdoc is about the integration with spring.
 The integration principle should be the same with zuul:
 - https://spring.io/blog/2019/01/23/spring-cloud-greenwich-release-is-now-available

 Zuul, is now deprecated and you should migrate to spring-cloud-gateway...

**Comment by paolodedo** [comment]
Hello,

Zuul and Eureka are just service-discovery products like other ones, as stated by @octopus-prime , so if you want to use it with Kubernetes (as my case) you are free to do.

The problem is another one: **springdoc-openapi** is very powerful but unfortunately, **it relies on swagger UI for the presentation part**, instead of having its own.

So, as for now, it is basically impossible to provide another implementation of _springfox.documentation.swagger.web.SwaggerResource_ &
_springfox.documentation.swagger.web.SwaggerResourcesProvider_ to **io.springfox.springfox-swagger2.2.9.2**.

For now, we have to make it work this way, waiting for the team to upgrade:
- springdoc-openapi: create spring-doc models;
- swagger-ui : accept spring-doc models.

So, when will this improvement be available?

Thanks

**Comment by danielgatis-mb** [comment]
This works for me:

```
public class Application {

  private final String servicePattern = "myproject\\-(?<name>.*?)\\-service";

  @Autowired
  private EurekaClient discoveryClient;

  @Bean
  public PatternServiceRouteMapper serviceRouteMapper() {
    return new PatternServiceRouteMapper(servicePattern, "${name}");
  }

  @GetMapping("/swagger-config.json")
  public Map<String, Object> swaggerConfig() {
    Map<String, Object> rtn = new LinkedHashMap<>();
    List<Map<String,String>> urls = new LinkedList<>();

    discoveryClient
      .getApplications()
      .getRegisteredApplications()
      .forEach(application -> {
        Pattern p = Pattern.compile(servicePattern, Pattern.CASE_INSENSITIVE);
        Matcher m = p.matcher(application.getName());

        if (m.find()) {
          String g = m.group(1);
          String serviceName = g.toLowerCase();

          Map<String, String> url = new LinkedHashMap<>();
          url.put("url", "/" + serviceName + "/v3/api-docs");
          url.put("name", serviceName);
          urls.add(url);
        }
      });

    rtn.put("urls", urls);
    return rtn;
}

  public static void main(String[] args) {
    SpringApplication.run(Application.class, args);
  }
}
```

```
springdoc.swagger-ui.configUrl=/swagger-config.json
```

**Comment by daniel-schel** [comment]
A simpler solution based on the reply from @danielgatis-mb using spring cloud discovery abstraction:


```
@RestController
public class SwaggerUiConfig {

    @Autowired
    private DiscoveryClient discoveryClient;

    @GetMapping("/swagger-config.json")
    public Map<String, Object> swaggerConfig() {
        Map<String, Object> config = new LinkedHashMap<>();
        List<SwaggerUrl> urls = new LinkedList<>();
        discoveryClient.getServices().forEach(serviceName -> 
                        discoveryClient.getInstances(serviceName).forEach(serviceInstance ->
                                urls.add(new SwaggerUrl(serviceName, serviceInstance.getUri() + "/v3/api-docs"))
                        )
        );
        config.put("urls", urls);
        return config;
    }
}
```
