### ISSUE TITLE
@Schema(accessMode) doesn't work for objects that are contained by other objects

### ISSUE THREAD

**Issue by Shryne** [springdoc/springdoc-openapi#1080]
**Describe the bug**
`@Schema(accessMode = READ_ONLY)` (or WRITE_ONLY) doesn't work, if it's used on an object that is contained by another object in the same class:

```java
@Getter
@Setter
public class Person {
    // This works. Name will only be visable in GET requests
    @Schema(accessMode = Schema.AccessMode.READ_ONLY)
    private String name;

    // This doesn't work. Age will be visable in GET and POST requests. WRITE_ONLY doesn't work here as well
    @Schema(accessMode = Schema.AccessMode.READ_ONLY)
    private Age age;
    
    // The class Mother has an Age instance variable. This is the reason why @Schema doesn't work for Person.age
    private Mother mother;
}
```

**To Reproduce**
I have a minimal project here: [https://github.com/Shryne/SwaggerAccess](https://github.com/Shryne/SwaggerAccess).
Just start `SwaggerAccessApplication.main` and visit [http://localhost:8090/swagger-ui/index.html?configUrl=/v3/api-docs/swagger-config#/](http://localhost:8090/swagger-ui/index.html?configUrl=/v3/api-docs/swagger-config#/).
It will show:
```
GET /person

200 Response:
{
  "name": "string",
  "age": {
    "value": 0
  },
  "mother": {
    "bid": {
      "value": 0
    }
  }
}
```

```
POST /person

Request Body (example Value)
{
  "age": {
    "value": 0
  },
  "mother": {
    "bid": {
      "value": 0
    }
  }
}
```

**Expected behavior**
`name` and `age` are read only values. `name` isn't shown in the POST request, as expected. Unfortunately, this doesn't apply to age. POST should look like this:

```
{
  "mother": {
    "bid": {
      "value": 0
    }
  }
}
```

**Comment by bnasslahsen** [comment]
@Shryne, 

The resolution is not handled by springdoc-openapi.
You can check  the following schema, generated by swagger-core:  Mainly the `readOnly` attribute that is generated.

```java
		ResolvedSchema resolvedSchema =	ModelConverters.getInstance()
				.resolveAsResolvedSchema(
						new AnnotatedType(Person.class));
```

You can ask the swagger-core project instead.
