### ISSUE TITLE
support for kotlin suspend functions for webflux functional endpoints

### ISSUE THREAD

**Issue by danitutu** [springdoc/springdoc-openapi#1088]
**Is your feature request related to a problem? Please describe.**

Before springdocs
```
    @Bean
    fun router() = coRouter {
        POST("", ::createNewEntity)
    }
    
    private suspend fun createNewEntity(req: ServerRequest): ServerResponse {
```

After springdocs
```
    @Bean
    fun router(): RouterFunction<ServerResponse>? {
        return route().POST(
            "",
            { req -> createNewEntity(req).toMono() },
            ::createNewEntityApi
        )
            .build()
    }
```

I couldn't find a way to create a bridge between `coRouter` and `SpringdocRouteBuilder.route()` config. I also couldn't find a way to make `SpringdocRouteBuilder.route()` work with `suspend` functions. Are any of these supported?

Also found a similar topic here: https://github.com/springdoc/springdoc-openapi/issues/980

**Describe the solution you'd like**
The final purpose is to be able to use Kotlin `suspend` functions in the configuration. 

**Additional context**
![image](https://user-images.githubusercontent.com/69974119/110087361-37d4df80-7d9c-11eb-972a-868d4059d13f.png)

**Potential solution**
I found `asHandlerFunction` inside `CoRouterFunctionDsl`.

```
    @Bean
    fun router(): RouterFunction<ServerResponse>? {
        return route().POST(
            "",
            asHandlerFunction(::createNewEntity),
            ::createNewEntityApi
        )
            .build()
    }

    private fun asHandlerFunction(init: suspend (ServerRequest) -> ServerResponse) = HandlerFunction {
        mono(Dispatchers.Unconfined) {
            init(it)
        }
    }
```

**Comment by bnasslahsen** [comment]
@danitutu, 

 Your description is not clear. 

 Make sure you provide all the[ relevant information ](https://github.com/springdoc/springdoc-openapi/blob/master/CONTRIBUTING.adoc)to help us speed up problem diagnosis by providing as much information as possible.

You can also see on #980, how the description is be done. And make sure you add a minimal sample project to reproduce your issue.

I am closing this ticket and there is no need to open a new one. 
This one can be reopened if the relevant information is provided.
