### ISSUE TITLE
Not working on openshift

### ISSUE THREAD

**Issue by smustaoglu** [springdoc/springdoc-openapi#1089]
Same application is working on local. but Not working on openshift
Fetch error
Service Unavailable /context/v1/v3/api-docs

how can I debug?

**Comment by bnasslahsen** [comment]
@smustaoglu, 

 Please read the [contribution guide](https://github.com/springdoc/springdoc-openapi/blob/master/CONTRIBUTING.adoc), before you log this kind of tickets.
