### ISSUE TITLE
Ignore Controllers with @ApiIgnore

### ISSUE THREAD

**Issue by atilla8huno** [springdoc/springdoc-openapi#109]
I need to remove some of the controllers from the generated documentation. There are options like this on other libs like springfox.
Some of the APIs are not meant to be documented/exposed on the generated docs.
What's the best way to do it?
A simple annotation like `@ApiIgnore` class or method level would fit great.

**Comment by lzhoucs** [comment]
`@Operation(hidden = true)` worked for me. See https://github.com/springdoc/springdoc-openapi/issues/32.

**Comment by atilla8huno** [comment]
> `@Operation(hidden = true)` worked for me. See #32.

Yep, worked. Thank you so much!

**Comment by yuanpli** [comment]
Is there any one annotation to ignore the whole restcontroller in spring?

**Comment by bnasslahsen** [comment]
Hi @atilla8huno, 

 You have the information at many places:
- https://springdoc.github.io/springdoc-openapi-demos/migrating-from-springfox.html
- https://springdoc.github.io/springdoc-openapi-demos/faq.html

Or simply at swagger documentation:
- https://github.com/swagger-api/swagger-core/wiki/Swagger-2.X---Annotations#hidden
