### ISSUE TITLE
Parameter 4 of method swaggerWelcome in org.springdoc.webflux.ui.SwaggerConfig required a bean of type 'org.springframework.web.reactive.result.method.RequestMappingInfoHandlerMapping' that could not be found.

### ISSUE THREAD

**Issue by patpatpat123** [springdoc/springdoc-openapi#1091]
Hello,

I have a Springboot 2.5.0 app with springdoc-openapi-webflux-ui 1.5.4, and everything was very fine, very happy.

Upgraded to 1.5.5, still with Springboot 2.5.0.

From there, seeing this issue:
***************************
APPLICATION FAILED TO START
***************************

Description:

Parameter 4 of method swaggerWelcome in org.springdoc.webflux.ui.SwaggerConfig required a bean of type 'org.springframework.web.reactive.result.method.RequestMappingInfoHandlerMapping' that could not be found.

Action:

Consider defining a bean of type 'org.springframework.web.reactive.result.method.RequestMappingInfoHandlerMapping' in your configuration.

Could you please help?
Thank you

**Comment by bnasslahsen** [comment]
@patpatpat123, 

 ` v1.5.5` does not yet support 2.5.0 which not yet GA.  
It is validated against 2.4.3 or earlier versions of spring-boot.

 You have the last version supported of spring-boot, using the parent [pom.xml](https://github.com/springdoc/springdoc-openapi/blob/v1.5.5/pom.xml)

 This ticket will be now closed. And it will be treated as part of the support of the next spring-boot 2.5.0 G.A.

 If you are having a minimal reproducible sample, don't hesitate to add it.

**Comment by larrywest** [comment]
I just want to say thanks to @patpatpat123 -- I ran into the same issue (or at least the same symptom) using springdoc-openapi-webflux-ui 1.5.5 with Spring Boot 2.4.3.  Saw this posting, rolled back to 1.5.4 and (with only that one character change) now the app launches fine.

@bnasslahsen It would take a fair amount of effort to strip this down to a minimal example - if important, reply and I'll make the time this week.  But it is odd no one else has reported it in two months.

**Comment by bnasslahsen** [comment]
Hi @larrywest, 
 
The current version 1.5.8 supports vspring-boot 2.4.5 without any issue.

Would be happy to help if you provide a minimal reproducible sample.
You have a lot of samples [on the project tests](https://github.com/springdoc/springdoc-openapi/tree/master/springdoc-openapi-webflux-core/src/test/java/test/org/springdoc/api).

**Comment by patpatpat123** [comment]
Hello @bnasslahsen,

2.5.0 is now GA, the issue still persist.
Can you please help check?

Thank you

**Comment by patpatpat123** [comment]
Parameter 3 of method swaggerWelcome in org.springdoc.webflux.ui.SwaggerConfig required a bean of type 'org.springframework.web.reactive.result.method.RequestMappingInfoHandlerMapping' that could not be found.


Consider defining a bean of type 'org.springframework.web.reactive.result.method.RequestMappingInfoHandlerMapping' in your configuration.

**Comment by bnasslahsen** [comment]
@patpatpat123, 

The support of 2.5.0 is done. There is nothing related to `RequestMappingInfoHandlerMapping`.
As suggested earlier, you should provide a minimal reproducible sample, so we can reproduce your issue.

You have a lot of samples [on the project tests](https://github.com/springdoc/springdoc-openapi/tree/master/springdoc-openapi-webflux-core/src/test/java/test/org/springdoc/api).

**Comment by patpatpat123** [comment]
Is it possible to publish the support to Maven Central (the support or 2.5.0) please?

When I use 1.5.5, 1.5.6, 1.5.7 and 1.5.8, the issue is 100% reproducible.

When I stick with 1.5.4, no issue.

I am trying to find out what is the change between 1.5.4 and 1.5.5 causing this issue, as well as I parallel, would like to test the new support for 2.5.0 please

**Comment by bnasslahsen** [comment]
I understand you can reproduce the issue. But we cannot!
Again, without **without you providing a reproducible sample**, we can do nothing about it.

All the [demos are here](https://github.com/springdoc/springdoc-openapi-demos), working fine.

Release `v1.5.9`, which will officially be supporting spring-boot `2.5.0` should be released later this weekend.

Note that, If you are not willing to provide a reproducible sample, i will lock this thread.

**Comment by patpatpat123** [comment]
Hello @bnasslahsen ,
Thanks for the release, can see it can Maven Central now.

And tried and tested with 1.5.9:
Result -> Working fine

I tried version by version, here is the table.

1.5.9 -> OK
1.5.8 -> BROKE
1.5.7 -> BROKE
1.5.6 -> BROKE
1.5.5 -> BROKE
1.5.4 -> OK
1.5.3 -> OK

root cause of BROKE: unknown

Also, may I ask if there is any release strategy for future Spring update? I think some issues got opened in the past for 2.4.0 release, then this one for 2.5.0 release. 

Should community start a new thread every time there is a new 2.X.0 of spring coming up? (This would be rather inefficient maybe)
