### ISSUE TITLE
Allow to map java.time.YearMonth to String

### ISSUE THREAD

**Issue by ydemartino** [springdoc/springdoc-openapi#1103]
**Is your feature request related to a problem? Please describe.**
- I am using the java.time.YearMonth in my objects. The value of this type looks `{"yearMonth": "2021-03"}` in json
- The issue I am facing is that, in the generated documentation, the type is mapped to primitive types:
```
{"yearMonth": {
      "year": 0,
      "month": "JANUARY",
      "monthValue": 0,
      "leapYear": true
}}
```

**Describe the solution you'd like**
- I would like to be able to map this type to string `{"yearMonth": "2021-03"}` and in the schema `yearMonth: string`

**Describe alternatives you've considered**
- I have tried to customize my type using this without success:
```
OpenAPI().schema("YearMonth", Schema<YearMonth>().type("string").example("2021-03"))
```

**Comment by bnasslahsen** [comment]
@ydemartino, 

 Here is a sample working code: using `@Schema` annotation


```java
@RestController
public class HelloController {

	@GetMapping(value = "/persons")
	public PersonDTO persons(final String dto) {
		return null;
	}

	class PersonDTO {

		@JsonProperty
		private String email;

		@JsonProperty
		private String firstName;

		@Schema(name = "yearMonth", type = "string", example = "2021-03")
		@JsonProperty
		private java.time.YearMonth yearMonth;

	}

}
```

**Comment by ydemartino** [comment]
Thanks this is working, but I was wondering if there is a way to activate this globally?

**Comment by bnasslahsen** [comment]
Using `springdoc-openapi`, you can use: `PropertyCustomizer`
You have here a sample test, that shows how you can use it:
 - https://github.com/springdoc/springdoc-openapi/tree/master/springdoc-openapi-webmvc-core/src/test/java/test/org/springdoc/api/app70

Using [swaggerr-core](https://github.com/swagger-api/swagger-core), you can use a `ModelConverter` and simply declare it as a spring bean, and it will scanned.

**Comment by ydemartino** [comment]
Awesome, thanks!
