### ISSUE TITLE
Error when using with spring boot 1.5.9

### ISSUE THREAD

**Issue by jamesfanduel** [springdoc/springdoc-openapi#1108]
Hi,

I am using spring boot 1.5.9 and am getting the following error when I add springdoc-openapi-ui 1.5.5.
Is there a different version I should use?

***************************
APPLICATION FAILED TO START
***************************

Description:

Parameter 4 of method openApiResource in org.springdoc.webmvc.core.SpringDocWebMvcConfiguration required a bean of type 'org.springframework.web.servlet.mvc.method.RequestMappingInfoHandlerMapping' that could not be found.

Action:

Consider defining a bean of type 'org.springframework.web.servlet.mvc.method.RequestMappingInfoHandlerMapping' in your configuration.

**Comment by bnasslahsen** [comment]
@jamesfanduel, 

 Make sure your project uses: `spring-boot-starter-web`.
 `v1.5.5` is compatible with spring boot 1 as well.

This is the code of a working demo with spring-boot 1, that is working without any issue :
 - https://github.com/springdoc/springdoc-openapi-demos/tree/master/springdoc-openapi-spring-boot-1

 This ticket will be closed, and can be reopened more relevant information are provided.

If you feel you are facing any issue, make sure you **[Provide a Minimal, Reproducible Example - with HelloController](https://stackoverflow.com/help/minimal-reproducible-example)** that reproduces the problem
