### ISSUE TITLE
webflux: contextPath not used while behind a load balancer/reverse proxy

### ISSUE THREAD

**Issue by ethali** [springdoc/springdoc-openapi#1109]
SwaggerUI doesn't work at all while behind a reverse proxy like Traefik even if good HTTP Headers are sent.

contextPath is available but doesn't seem to be used as you can see below

https://github.com/springdoc/springdoc-openapi/blob/1346f01706ec42369fda4b8b44ba692f33613c67/springdoc-openapi-common/src/main/java/org/springdoc/ui/AbstractSwaggerWelcome.java#L207

https://github.com/springdoc/springdoc-openapi/blob/1346f01706ec42369fda4b8b44ba692f33613c67/springdoc-openapi-common/src/main/java/org/springdoc/ui/AbstractSwaggerWelcome.java#L197

I tried setting this.swaggerConfigUrl and this.apiDocsUrl by appending default urls to the contextPath as we could expect according to the method signatures and it works well behind Traefik.

Is it really an issue that contextPath variable in thoses methods are not used?

**Comment by bnasslahsen** [comment]
Please read this [section](https://springdoc.org/#how-can-i-deploy-springdoc-openapi-ui-behind-a-reverse-proxy):

**Comment by ethali** [comment]
I did read this section actually.

I tried all of it.

server.forward-headers-strategy=native OR framework
server.use-forward-headers=true

I also added cause I'm using reactive.
```java
@Bean
ForwardedHeaderTransformer forwardedHeaderTransformer() {
    return new ForwardedHeaderTransformer();
}
```

the contextPath is '/transcodification'

First root call is good with a temporary redirect
![Capture d’écran de 2021-03-16 15-35-02](https://user-images.githubusercontent.com/890917/111327111-6345ad00-866d-11eb-9d71-4a156601e8e7.png)

Then redirect to UI with the right contextPath but not the queryParam configUrl
![Capture d’écran de 2021-03-16 15-35-08](https://user-images.githubusercontent.com/890917/111327139-69d42480-866d-11eb-80f2-b1fdb11a1513.png)

Then and so we've got a 404
![Capture d’écran de 2021-03-16 15-35-17](https://user-images.githubusercontent.com/890917/111327157-6ccf1500-866d-11eb-83ce-b6fe97fd3e6b.png)

**Comment by bnasslahsen** [comment]
@ethali,  

 You should make sure your proxy sends the correct headers, as described. Make sure your restart your application after the configuration changes.

For example, using Apache 2, configuration:
- `X-Forwarded-Prefix "/custom-path"`

If you are still facing this problem: You can set manually the configurl as workaround and test if it's ok.
`springdoc.swagger-ui.configUrl = /transcodification/v3/api-docs/swagger-config`

If it's working after setting the configUrl manually, this means it's a bug and we can reopen the issue.

**Comment by ethali** [comment]
- `X-Forwarded-Prefix "/custom-path"` is sent

I set `server.forward-headers-strategy=framework` wiith the ForwardedHeaderTransformer Bean as mentioned above.

Only redirect to `/transcodification/webjars/swagger-ui/index.html` is OK.

if I set `springdoc.swagger-ui.configUrl = /transcodification/v3/api-docs/swagger-config` all is OK about networking but I get PetStore example...

![Capture d’écran de 2021-03-16 17-15-48](https://user-images.githubusercontent.com/890917/111343008-4912cb80-867b-11eb-9c7d-2dc8ffaaa43c.png)

**Comment by bnasslahsen** [comment]
@ethali, 

 Can you [Provide a Minimal, Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example) - with HelloController that reproduces the problem ?

**Comment by bnasslahsen** [comment]
@ethali, 

 This should be fixed with the [latest SNAPSHOT](https://springdoc.org/#how-can-i-use-the-last-springdoc-openapi-snapshot).
 You can test it, and if you are still facing other issues you can let me know.

**Comment by ethali** [comment]
@bnasslahsen,

Just tested with 1.5.7-SNAPSHOT and it seems to work great behind my Traefik container.

It works with:

just `server.forward-headers-strategy=framework` set

OR just with bean injected
```java
@Bean
ForwardedHeaderTransformer forwardedHeaderTransformer() {
    return new ForwardedHeaderTransformer();
}
```

Thank you!

**Comment by sergey-volkov-lm** [comment]
For now, you can try springdoc version 1.4.8, it works fine for me.

**Comment by evan-qianjh** [comment]
@bnasslahsen  Hi. This bug reappears in version 1.6.9
