### ISSUE TITLE
global SecurityRequirement definition cannot be removed for single operations

### ISSUE THREAD

**Issue by mhaeusler** [springdoc/springdoc-openapi#1111]
**Describe the bug**
- when setting a global SecurityRequirement there is no way to remove that for single operations.
- the only workaround is to set a non-existing security scheme, but that feels wrong and is not what is specified on swagger.io

**To Reproduce**
- using springdoc-openapi v1.5.5
- set a global securityRequirement like this:
`        new OpenAPI()
                .info(new Info().title("REST API"))
                .components(new Components().
                        addSecuritySchemes("bearer-key",
                        new SecurityScheme().type(SecurityScheme.Type.HTTP).scheme("bearer").bearerFormat("JWT")))
                .addSecurityItem(new SecurityRequirement().addList("bearer-key"));
`
- in one REST controller I don't want to have any SecurityRequirement, so I try to override the global setting with an empty name
`@Operation(summary = "Authenticate a user",
            security = { @SecurityRequirement(name= "")})
    @RequestMapping(value = "/authenticate", method = RequestMethod.POST)
    public ResponseEntity<JwtResponse> createAuthenticationToken(@RequestBody JwtRequest authenticationRequest) throws Exception {
}
`

the resulting openapi.json will contain no security section for the "/authenticate" path and therefore the global definition still applies.

**Expected behavior**
- as specified in https://swagger.io/docs/specification/authentication/  
chapter "Step 2. Applying security"
 the openapi.json should look like this because the global security scheme is overridden.
`         "/authenticate": {
            "post": {
                "summary": "Authenticate a user",
                "operationId": "createAuthenticationToken",
                "requestBody": {
...
                },
                "responses": {
...
                },
                "security": [
                ]
            }
        }
`

**Comment by mamsen** [comment]
I have this issue too! Would be great if this would be fixed!

**Comment by bnasslahsen** [comment]
Hi, 

 This is answered here: https://github.com/springdoc/springdoc-openapi/issues/639
This is the [sample code](https://github.com/springdoc/springdoc-openapi/blob/master/springdoc-openapi-webmvc-core/src/test/java/test/org/springdoc/api/app76/HelloController.java) for it.
