### ISSUE TITLE
Expose actuator endpoint to list available group definitions

### ISSUE THREAD

**Issue by mabako** [springdoc/springdoc-openapi#1117]
**Is your feature request related to a problem? Please describe.**
We've currently set up a handful of GroupedOpenApi beans in our application, mostly based around our current module structure.

- `/actuator/` only lists the `/actuator/openapi`-endpoint for the non-grouped configuration, which we don't have - `/actuator/openapi` results in a 404 Not Found for our configuration.
- `/actuator/openapi/a` works fine, `/actuator/openapi/b` works fine
- there is no way to find out that `a` and `b` are valid group names

**Describe the solution you'd like**
I'd actually like an additional actuator endpoint to retrieve all groups.

Unfortunately, it's probably impossible to do this in the same way that "normal" actuator endpoints do this, where e.g. `/metrics` lists all metric names to use with `/metrics/{name}`; with how `/actuator/openapi` works at the moment.

It would probably also be useful to configure actuator to list `/actuator/openapi/{group}` as a templated endpoint if groups are enabled.

**Comment by bnasslahsen** [comment]
@mabako, 

 You have the list of available endpoints/groups under (`urls` list):
 - `actuator/swaggerui/swagger-config`

**Comment by mshima** [comment]
@bnasslahsen is there a way to list current groups using actuator or other endpoint?
We are using a custom actuator to list groups so we can lazily look for microservices openapi definitions in the gateway.
Is this something acceptable?
Swagger is custom maid to look for those openapi definitions.
https://github.com/jhipster/jhipster-bom/blob/main/jhipster-framework/src/main/java/tech/jhipster/config/apidoc/JHipsterOpenApiEndpoint.java

**Comment by bnasslahsen** [comment]
Hi @mshima, 

If you just need to expose OpenAPI definitions, under the actuator endpoint.
There is already built in support: https://springdoc.org/#actuator-support
```properties
springdoc.use-management-port=true
# This property enables the openapi and swagger-ui endpoints to be exposed beneath the actuator base path.
management.endpoints.web.exposure.include=openapi
```

If you are looking to use actuator endpoints, in a spring-cloud-gateway, **you will need to add an actuator endpoint as you defined**.
Note that there is [a working example](http://158.101.191.70:8060/) using spring-cloud-gateway without actuator:
- https://github.com/springdoc/springdoc-openapi-demos/tree/master/springdoc-openapi-microservices

Hope that helps!

**Comment by mshima** [comment]
@bnasslahsen thanks.
We have a working implementation that gets microservices routes using actuator and then gets each microservice openapi group using a custom made actuator.

But this is a JHipster specific feature.
If we springdoc exposes info about groups through actuator, would be generic.

Is this a acceptable feature?
Maybe a `openapi-groups` endpoint.
