### ISSUE TITLE
Path conflict issue

### ISSUE THREAD

**Issue by Gustavo-Bernardi** [springdoc/springdoc-openapi#1118]
**Describe the bug**

I'm having a problem with HTTP request method conflicts because I use a regex in the path, I have two APIs with different functionality but OpenAPI understands that they are the same paths, it does not differentiate the regex in the path and understands that they are the same API and the same HTTP request methods. My APIs:

- "v2 / sellers / {governmentId: \\ d {14}} / steps / picture"
- "v2 / sellers / {governmentId: \\ d {11}} / steps / picture"

In the image below I show that he understands it as a single path, in the image where it is marked with a red rectangle he is conflicting with the endpoint methods because he understands that they are the same API and adding .json_1 in the file extension, with that I cannot document the endpoints of my two APIs.
![issue](https://user-images.githubusercontent.com/71278086/112388092-683fd780-8cd1-11eb-8159-f99f051a097e.png)

**What I need**

Is there any way that OpenAPI does not ignore the regex in the path? I need him to understand that they are different paths or even if he understands that it is the same path he cannot have conflict with HTTP request methods so that I can document my endpoints.

**Comment by bnasslahsen** [comment]
@Gustavo-Bernardi,


If you are reporting a bug, please help to speed up problem diagnosis by providing as much information as possible:

- What version of spring-boot you are using?
- What modules and versions of springdoc-openapi are you using?
- What are the actual and the expected result using OpenAPI Description (yml or json)?
- Provide a [Minimal, Reproducible Example - with HelloController](https://stackoverflow.com/help/minimal-reproducible-example) that reproduces the problem

This ticket will be closed and can be reopened if the relevant information is provided.

**Comment by Gustavo-Bernardi** [comment]
@bnasslahsen 

- What version of spring-boot you are using?
**2.3.9.RELEASE**
- What modules and versions of springdoc-openapi are you using?
**springdoc-openapi - 1.5.4**
**io.swagger.core.v3 - 2.1.6**

- Provide a Minimal, Reproducible Example - with HelloController that reproduces the problem
**Below are my two classes that are my APIs with their respective endpoints using HTTP request method @PostMapping, I use the annotation @Operation in my endpoints to parameterize my endpoint contracts. OpenApi does not understand that they are different APIs, it ignores the existing regex in @RequestMapping, formatting the governmentID for 11 and 14, when generating the documentation it understands that they are the same HTTP request methods that in this case is the Post method of the same API, I need him to understand that they are different things because I need to document the two APIs. What can I do in this case? Because I cannot change my APIs.** 

```
@RestController
@AllArgsConstructor
@RequestMapping("v2/sellers/{governmentId:\\d{11}}/steps/picture")
@ExposesResourceFor(NaturalSellerStepPicture.class)
class NaturalSellerStepPictureRestService {

	private final NaturalSellerStepPictureQuery stepPictureQuery;

	private final NaturalSellerStepPictureCommand stepPictureCommand;

	private final NaturalSellerStepPictureAssemblerSupport assemblerSupport;

	@PostMapping
	@ResponseStatus(HttpStatus.CREATED)
	@Operation(operationId = "naturalsellersteppicture/CreateNaturalSellerStepPictureContract.json")
	NaturalSellerStepPicture pictureStep(@PathVariable String governmentId,
			@Valid @RequestBody NaturalSellerStepPicture stepPicture) {
		return assemblerSupport.toModel(stepPictureCommand.create(stepPicture.governmentId(governmentId)));
	}
}
```

```
@RestController
@AllArgsConstructor
@ExposesResourceFor(SellerStepPicture.class)
@RequestMapping("v2/sellers/{governmentId:\\d{14}}/steps/picture")
class SellerStepPictureRestService {

	private final SellerStepPictureQuery sellerStepPictureQuery;

	private final SellerStepPictureCommand sellerStepPictureCommand;

	private final SellerStepPictureAssemblerSupport sellerStepPictureAssemblerSupport;

	@PostMapping
	@ResponseStatus(HttpStatus.CREATED)
	@Operation(operationId = "sellersteppicture/CreateSellerStepPictureContract.json")
	SellerStepPicture create(@PathVariable String governmentId,
			@Valid @RequestBody SellerStepPicture sellerStepPicture) {
		return sellerStepPictureAssemblerSupport
				.toModel(sellerStepPictureCommand.create(sellerStepPicture.governmentId(governmentId)));
	}
}
```

**Comment by bnasslahsen** [comment]
You are not respecting one of the basic rules of OpenAPI 3.

`Two POST methods for the same path are not allowed – even if they have different parameters (parameters have no effect on uniqueness).`

More details are available on OpenAPI 3 [site](https://swagger.io/docs/specification/paths-and-operations/).

**Comment by Gustavo-Bernardi** [comment]
@bnasslahsen

Ok, thanks for the feedback.
