### ISSUE TITLE
Add ability to disable default responses

### ISSUE THREAD

**Issue by pohorilyi** [springdoc/springdoc-openapi#1123]
I want to migrate from SpringFox library to SpringDoc.  In my SpringFox configuration, I have disabled default response messages:

```
@Bean
public Docket publicApi(ServletContext servletContext) {
    Docket docket = new Docket(DocumentationType.SWAGGER_2)
        ...
        .useDefaultResponseMessages(false);
```
But I can't find a way to do it in SpringDoc. [Migration guide](https://springdoc.org/#migrating-from-springfox) says "remove Docket and use application.properties instead". But there is no such property. 

**Solution I'd like**
- Posibility to disable default responses as a property in application.properties
- Expected result using OpenAPI Description - json

**Comment by bnasslahsen** [comment]
@pohorilyi, 

 If you define a response description, it will used instead.
 **Each response status requires a description**. So if it's empty, springdoc-openapi produces a default response. Otherwise you get incorrect OpenAPI document.

**Comment by pohorilyi** [comment]
@bnasslahsen,

thanks for answering my question. But according to springdoc demo it is possible to have only a few response codes included in the document. e.g. here is only 200 and 400. 
http://158.101.164.60:8081/v3/api-docs/users
![image](https://user-images.githubusercontent.com/5315669/112960229-e1658180-914c-11eb-8a62-1748919c5280.png)
For a similar get endpoint springdoc adds a lot of other responses by default. 
![image](https://user-images.githubusercontent.com/5315669/112959515-2d63f680-914c-11eb-9014-00383e41f7d9.png)

Do I understand correctly, document in demo is incorrect? And it is not possible to generate document only with some specified responses?

**Comment by bnasslahsen** [comment]
@pohorilyi, 

 According to the demo, springdoc reflects the http responses that are available on the code:
- If you have seen the demo in details: HTTP 200 comes from the controller
-  HTTP 400 code comes from a global exception handler.

 By default: springdoc automatically adds @ControllerAdvice responses to all the generated responses.
 If you want disable this, you have: 
```java
springdoc.override-with-generic-response= false
```

 Note that mainly: springdoc-openapi reflects the http codes that are available on your code.
 And this can be customized, if you use `@ApiResponse `annotations.

**Comment by pohorilyi** [comment]
@bnasslahsen,

thanks a lot for the explanation 🙏  Now it's much more clear.
`springdoc.override-with-generic-response= false` is what I was looking for. I should have dived deeper into the docs.

**Comment by istibekesi** [comment]
Is it possible to keep default response configuration `true` and hide some of them on specific endpoints with `@ApiResponse`?
