### ISSUE TITLE
swagger-ui config lacks useUnsafeMarkdown

### ISSUE THREAD

**Issue by tonig** [springdoc/springdoc-openapi#1124]
This config was introduced in swagger-ui 3.26.1 (https://github.com/swagger-api/swagger-ui/releases/tag/v3.26.1) and it's false by default.

**Comment by bnasslahsen** [comment]
@tonig, 

 This parameter is Deprecated and will be removed in `4.0.0`.
 As we are just working just fine, without it, we don't find any added value on investing on adding support for deprecated features.

 If you really feel it's something useful to the community, you can propose a PR and we will have a look on it.
