### ISSUE TITLE
Generic fields in ParameterObject are not resolved

### ISSUE THREAD

**Issue by orange-buffalo** [springdoc/springdoc-openapi#1128]
Consider the following use-case, where `@ParameterObject` refers to a class that extends a parametrized class:

```kotlin
open class AbstractParameterObject<T : Enum<T>> {

    var primitiveBaseField: Int? = null
    var genericField: T? = null
}

enum class ConcreteEnum {
    ONE,
    TWO
}

class ConcreteParameterObject : AbstractParameterObject<ConcreteEnum>() {
    var primitiveConcreteField: Int? = null
}

@RestController
@RequestMapping("/")
class HelloController {

    @GetMapping
    fun test(@ParameterObject requestData: ConcreteParameterObject): String = "hello"

}
```

Expected schema should contain the `genericField` definition, but it does not:

```json
"parameters": [
  {
    "name": "primitiveConcreteField",
    "in": "query",
    "required": false,
    "schema": {
      "type": "integer",
      "format": "int32"
    }
  },
  {
    "name": "primitiveBaseField",
    "in": "query",
    "required": false,
    "schema": {
      "type": "integer",
      "format": "int32"
    }
  }
],
```

I reproduced the problem with a test in `springdoc-openapi` code base - please see the [branch changes](https://github.com/springdoc/springdoc-openapi/compare/master...orange-buffalo:generic-parameter-object?expand=1) - and was able to get the field in the API definition. Unfortunately, the schema is still not generated properly. The issue is that at the moment when `calculateSchema` is called, the information about the original parameter class (`ConcreteParameterObject` from the example above) is already lost and we only have the declaring class for the getter (`AbstractParameterObject`). Obviously, there is not enough information to resolve the type information and wrong schema gets generated (or not at all for the enum case).

**Comment by bnasslahsen** [comment]
@orange-buffalo, 

 Thank for your search and contribution. 
 I have added your proposed change.

 There is an error related to swagger-core: https://github.com/swagger-api/swagger-core/issues/3858
  A NPE is thrown by Jackson, in the swagger-core call from `ModelResolver._addEnumProps(ModelResolver.java:944)`

  But i think, your fix should be working for other cases, and you have workarounds for enum inheritance.

 You can also test this enhancement using the latest [snapshot](https://springdoc.org/#how-can-i-use-the-last-springdoc-openapi-snapshot).

 Please have a look at the [commit](https://github.com/springdoc/springdoc-openapi/commit/31dae3399b3af146b297d6b78855d05ef55e0a7b) and tell if it covers your case ?

**Comment by orange-buffalo** [comment]
Hi @bnasslahsen, thank you for the solution. Yes, it covers the case. Hopefully once the Swagger issue is resolved, `@Parameter(schema=@Schema(type = "string", allowableValues = {"ONE", "TWO"}) )` workaround can be removed and schema gets generated based on the types.
