### ISSUE TITLE
@ResponseStatus is broken

### ISSUE THREAD

**Issue by nkavian** [springdoc/springdoc-openapi#1129]
**Describe the bug & To Reproduce**
Create a controller with @ControllerAdvice and a method with @ResponseStatus.
Use SpringDoc version 1.4.0: works as expected.
Use SpringDoc version 1.4.1+: it doesn't render in the final output.

**Expected behavior**
I'd like to upgrade to the latest version 1.5.6 but cant because version 1.4.1 broke this functionality.

**Additional context**
I'm not able to debug any deeper other than to narrow what version that @ResponseStatus broke.

**Comment by bnasslahsen** [comment]
@nkavian, 

 Not reproducible. 
 All tests using @ResponseStatus are passing.

 This ticket will be closed, and can be reopened more relevant information are provided.

If you feel you are facing any issue, make sure you **[Provide a Minimal, Reproducible Example - with HelloController](https://stackoverflow.com/help/minimal-reproducible-example)** that reproduces the problem
