### ISSUE TITLE
Enums as ref has unexpected behaviour/bug

### ISSUE THREAD

**Issue by nkavian** [springdoc/springdoc-openapi#1135]
**Describe the bug**
Define a `Currency` Enum with enumAsRef = true.
Create a schema `Account` where that enum is `accessMode = AccessMode.READ_ONLY`
Create a schema `Payment` where that enum is `@NotBlank`, i.e. read and write.
The generated openapi.json file shows that the Account->Currency is actually writable.
Remove the `Currency` variable from `Payment` and all of a sudden the `Account` schema is correct, read only.

**To Reproduce**
Clone this repo and `mvn clean spring-boot:run`: https://github.com/nkavian/example-bug
Branch "start" shows the code as I want it to be but with the wrong output.
Branch "compare" removes `Currency` from `Payment` and shows the correct `Account` output that I really want.
Branch "workaround" shows correct output with `Payment` `Currency` enabled, however I can no longer refer to `<SchemaDefinition schemaRef="#/components/schemas/Currency" />` in my Redoc Markdown to render the enum as part of my documentation.

**Expected behavior**
I expect enumAsRef to work as expected and be able to mark the enum as readonly in one place and read/write/required in other places.

I expect that when I set annotations on a `Payment` and `Account` schema that you don't augment the `Currency` schema. You'll notice between the example branches, that's what's going on, that the schema `Currency` is being marked readonly in some cases when the context of readonly was applicable only in context of `Account`.

**Screenshots**
[Redoc visualization of the output](http://127.0.0.1:8080/)
[openapi.json output](http://127.0.0.1:8080/v1/openapi.json)
[Swagger UI](http://127.0.0.1:8080/v1/swagger)

**Additional context**
I see endless companies using swagger based documentation and they all muck up their enum variables as pure strings, I think now I understand why they do that. The enumAsRef is broken and they workaround by turning it into string variables as well as avoiding ref.  uggh.

**Comment by bnasslahsen** [comment]
This is related to `swagger-core` issue as explained here how you can reproduce it : https://github.com/springdoc/springdoc-openapi/issues/1080

You can follow the [swagger-core issue](https://github.com/swagger-api/swagger-core/issues/3905.
) or actively propose a PR for it.
