### ISSUE TITLE
@ResponseStatus is broken

### ISSUE THREAD

**Issue by nkavian** [springdoc/springdoc-openapi#1136]
**Describe the bug**
Create a controller with @ControllerAdvice and a method with @ResponseStatus.
Use SpringDoc version 1.4.0: works as expected.
Use SpringDoc version 1.4.1+: it doesn't render in the final output.

**To Reproduce**
Clone this repo and `mvn clean spring-boot:run`: https://github.com/nkavian/example-bug
Branch "1.4.0" shows the output correctly.
Branch "1.5.6" shows that all 4xx excluded from output.

**Expected behavior**
I'd like to upgrade to the latest version 1.5.6 but cant because version 1.4.1 broke this functionality.

**Screenshots**
[Redoc visualization of the output](http://127.0.0.1:8080/)
[openapi.json output](http://127.0.0.1:8080/v1/openapi.json)
[Swagger UI](http://127.0.0.1:8080/v1/swagger)

**Additional context**
I'm not able to debug any deeper other than to narrow what version that @ResponseStatus broke.

**Comment by bnasslahsen** [comment]
@nkavian, 

Your branch v1.5.6 uses `springdoc.override-with-generic-response=false`.
The correct behavior of this property when enabled, is to hide all the responses from  `@ControllerAdvice`.
 
Just remove this property, and this will solve your issue.
 
Note also ,that the last stable release per today is `v1.5.7.` 
Make sure while reporting issues to use the last stable version.
