### ISSUE TITLE
Unable to generate operation responses that reference a global reusable response component

### ISSUE THREAD

**Issue by M0rfic** [springdoc/springdoc-openapi#114]
_**Small note**: this can be "somewhat related" to #113 in the sense that it's an attempt at having an easier way to define "global" responses instead of copy pasting everything on each operation._

In an effort to reduce duplication and make it easier to define responses that are common for most operation, such as Unauthorized, Internal Server Error, etc, I'm attempting to achieve [reusable responses as described in the specs](https://swagger.io/docs/specification/describing-responses/#reuse).

I haven't yet figured out how to add global response components via annotations (hints are appreciated if someone has any), so I've switched to a programmatic approach. Thus, I have created an OpenAPI bean that adds the common response components:

```java
@Configuration
public class OpenApiConfiguration {
    @Bean
    public OpenAPI defineOpenApi() {
        OpenAPI api = new OpenAPI();
        ...
        api.components(
                new Components().addResponses(
                        "Unauthorized",
                        new ApiResponse().description("Unauthorized")
                                         .content(new Content().addMediaType(
                                                 APPLICATION_JSON_VALUE,
                                                 new MediaType().schema(new Schema().$ref(ErrorResponse.class.getSimpleName())))))
        );
        ...
        return api;
    }
}
```

Afterwards, the responses are referenced on the appropriate operations:
```java
@Operation(description = "Obtain the list of services available in the system")
@ApiResponses({
        @ApiResponse(responseCode = HttpCode.UNAUTHORIZED, ref = "Unauthorized")
})
@GetMapping(produces = MediaType.APPLICATION_JSON_VALUE)
Collection<ServiceDescriptor> list();
```

In theory this setup should generate:
```yaml
paths:
  /api/v1/services:
    get:
      ...
      responses:
        '401':
          $ref: '#/components/responses/Unauthorized'
```

But I'm actually getting:
```yaml
        '401':
          description: default response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ServiceDescriptor'
```

The referenced components are all generated correctly, but it would seem that default values are used to generate the operation response instead of the ref provided inside `@ApiResponse(responseCode = HttpCode.UNAUTHORIZED, ref = "Unauthorized")`.

**Comment by springdoc** [comment]
Hi, 

 An enhancement to handle this use case, will be available on v1.1.47 of springdoc-openapi.

**Comment by Andrew3431** [comment]
Hi, is there a sample test to understand how to create global response message and use them in apis ?

**Comment by nolik** [comment]
> Hi, is there a sample test to understand how to create global response message and use them in apis ? Also can we set global response ( say , for status codes 401 and 403) and make it appear for all apis by default without even mentioning their reference in
> `@ApiResponse(responseCode = "403", ref = "Unauthorized")`

excuse me, do u find a way to create a global response?

**Comment by sereysopheak-gl** [comment]
Here is wht I do to create global  response
```java
@Bean
 public OperationCustomizer customizeOperation() {
    return (operation, handlerMethod) ->
        operation
            .responses(
                operation
                    .getResponses()
                    .addApiResponse("401", new ApiResponse().$ref("Unauthenticated-Exception"))
                    .addApiResponse("403", new ApiResponse().$ref("Unauthorized-Exception")));
  }
```
