### ISSUE TITLE
Could these constants be parametrized in application.properties?

### ISSUE THREAD

**Issue by amilicevic107** [springdoc/springdoc-openapi#1141]
https://github.com/springdoc/springdoc-openapi/blob/718c736cfd5e2d909cb34a8934d4c1e44eecd244/springdoc-openapi-common/src/main/java/org/springdoc/core/ActuatorProvider.java#L121-L126

**Comment by bnasslahsen** [comment]
@amilicevic107, 

 Please feel free to propose a PR and we will have a look at it.
