### ISSUE TITLE
configUrl does not include the api gateway route

### ISSUE THREAD

**Issue by kamatvishal** [springdoc/springdoc-openapi#1144]
I am using Springdoc openapi ui running behind a spring cloud gateway (route /myapi). I followed this link for that https://springdoc.org/#how-can-i-deploy-springdoc-openapi-ui-behind-a-reverse-proxy. So when I hit the url

`https://myhost.com/myapi`

it redirects me to a url

`https://myhost.com/myapi/webjars/swagger-ui/index.html?configUrl=/swagger-config.json`

Note the configUrl value in the above redirected url. Instead of configUrl=/myapi/swagger-config.json, it has a value configUrl=/swagger-config.json.

I have below code in my application.yml file

    springdoc:
      swagger-ui:
        path: /
        configUrl: /swagger-config.json
	
and I have set the below property as well

`server.forward-headers-strategy: framework`

I would have expected the redirected url to be

`https://myhost.com/myapi/webjars/swagger-ui/index.html?configUrl=/myapi/swagger-config.json`

and NOT

`https://myhost.com/myapi/webjars/swagger-ui/index.html?configUrl=/swagger-config.json`

Please advise

**Comment by bnasslahsen** [comment]
@kamatvishal, 

If you are reporting a bug, please help to speed up problem diagnosis by providing as much information as possible:

You need to describe your context (the title of an issue is not enough)

- What version of spring-boot you are using?
- What modules and versions of springdoc-openapi are you using?

**Comment by kamatvishal** [comment]
@bnasslahsen sorry, I have provided the details below. Please let me know if any other details are required.

> What version of spring-boot you are using?

I am using 2.4.3

>What modules and versions of springdoc-openapi are you using?

I am using springdoc-openapi-webflux-ui version 1.5.7

**Comment by bnasslahsen** [comment]
Do you have any [ Minimal, Reproducible Example - with HelloController ](https://stackoverflow.com/help/minimal-reproducible-example)that reproduces the problem ?

**Comment by sergey-volkov-lm** [comment]
Does your gateway add header X-Forwarded-Prefix?

**Comment by kamatvishal** [comment]
@bnasslahsen With the current code that I have, everything works fine on local. Its when I integrate with gateway on kubernetes platform is when I face this issue. Let me see if I can somehow add the gateway locally and try to reproduce locally

@sergey-volkov-lm Yes it does by default. I even tried adding it explicitly just in case but still facing the issue.

**Comment by bnasslahsen** [comment]
@kamatvishal, 

I have now your configuration error.
In general, you don't need to set manually the path of `springdoc.swagger-ui.configUrl`: It all works out of the box...

When you decide to set  `configurl` manually, then it's up to you to set the right path:

```properties
springdoc.swagger-ui.configUrl=/myapi/swagger-config.json
```

**Comment by kamatvishal** [comment]
@bnasslahsen Ah got it. I just confirmed that with default `springdoc.swagger-ui.configUrl` the gateway route gets prefixed in the redirected configurl . Thanks for pointing that out. Appreciate it.
