### ISSUE TITLE
 Expose @Id fields for entity with spring-data-rest/springdoc-openapi-data-rest

### ISSUE THREAD

**Issue by janderssonse** [springdoc/springdoc-openapi#1146]
**Is your feature request related to a problem? Please describe.**

Background:

We have an 'REST api based on mostly spring-data-rest - An Entity field @Id in configured to be exposed with a configuration on the Spring RepositoryRestConfiguration - exposeIdsFor(ENTITY.class). All well there but,,,

The same @Id field is not visible in the documentation generated for the same Entity model with springdoc-openapi-data, since v1.5.6. I have tried setting hidden=false directly on it using the @Schema-annotation, like this.
   
 @Schema(
        description = "The Internal Job Identity", example = "fb2baa17-8972-451b-bb1e-1bc773283476",
        accessMode = Schema.AccessMode.READ_ONLY, hidden=false, defaultValue = "A random UUID"
    )
    @Id val id: UUID = UUID.randomUUID(),

- What is the actual result using OpenAPI Description (yml or json)?
- 
 The field with @Id is missing, even though we set hidden=false on it

**Describe the solution you'd like**

openapi-spring-rest-data should respect the [ RepositoryRestConfiguration - exposeIdsFor(ENTITY.class) ](https://docs.spring.io/spring-data/rest/docs/current/api/org/springframework/data/rest/core/config/RepositoryRestConfiguration.html#exposeIdsFor-java.lang.Class...-)configuration.

OR

allow an configuration like in Spring-rest-data to expose @Ids, for example, springdocRespositoryRestConfiguration - exposeIdsFor(

OR

respect that if the hidden=false is set on on an @Id field and expose it.

**Describe alternatives you've considered**
- Searched in the docs, looked at a few examples, tried setting hidden=false on the @Schema for the @Id field.

The @Id field was exposed automatically up until version 1.5.5, but after 1.5.6 of the libs it is gone.

**Additional context**
The @Id field is not visible ...

![Skärmbild från 2021-04-25 11-23-51](https://user-images.githubusercontent.com/37870813/115988202-d0c3f200-a5b8-11eb-991c-d202d9393a96.png)

![Skärmbild från 2021-04-25 11-23-05](https://user-images.githubusercontent.com/37870813/115988203-d15c8880-a5b8-11eb-9281-c32de17f2b46.png)

Note: I'm using the following dependencies:
   
 //openapi generation
    implementation("org.springdoc:springdoc-openapi-ui:1.5.7")
    implementation("org.springdoc:springdoc-openapi-kotlin:1.5.7")
    implementation("org.springdoc:springdoc-openapi-data-rest:1.5.7")
    implementation("org.springdoc:springdoc-openapi-hateoas:1.5.7")

**Comment by janderssonse** [comment]
I downgraded to version 1.5.5 as a test, and then the field was exposed as expected !! hmm.
![Skärmbild från 2021-04-25 11-45-24](https://user-images.githubusercontent.com/37870813/115988918-fdc5d400-a5bb-11eb-8810-7a6f3558e9e9.png)

**Comment by janderssonse** [comment]
But with 1.5.6 the id is gone. 

I'll solve this just staying on 1.5.5 for the libs until further.

**Comment by bnasslahsen** [comment]
@janderssonse, 

 exposeIdsFor, should be considered for the next release.
 You can use the latest snapshot to validate it.
