### ISSUE TITLE
Failed to load remote configuration

### ISSUE THREAD

**Issue by dodalovic** [springdoc/springdoc-openapi#1148]
Hi, I'm trying to set the project, as described here:

![image](https://user-images.githubusercontent.com/6358061/116041288-54d7b180-a66d-11eb-8d22-ef2434e1d5da.png)

but I'm getting `Failed to load remote configuration.` when accessing from the `UI`. 

I'm using spring functional router kotlin, the latest spring doc version. 

Thank you for any assistance!

**Comment by bnasslahsen** [comment]
@dodalovic, 

 Please read the section [Using GitHub Issues](https://github.com/springdoc/springdoc-openapi/blob/master/CONTRIBUTING.adoc), and make sure you provide the all the listed information.

If you are reporting a bug, please help to speed up problem diagnosis by providing as much information as possible:

- You need to describe your context (the title of an issue is not enough)
- What version of spring-boot you are using?
- What modules and versions of springdoc-openapi are you using?
- What are the actual and the expected result using OpenAPI Description (yml or json)?
- Provide a Minimal, Reproducible Example - with HelloController that reproduces the problem

This ticket will be now closed. And can be reopened if the relevant information are provided.

**Comment by dodalovic** [comment]
Spring boot 2.4.1

```kotlin
implementation("org.springdoc:springdoc-openapi-webflux-ui:1.5.7")
implementation("org.springdoc:springdoc-openapi-kotlin:1.5.7")
```

**Comment by bnasslahsen** [comment]
You are not providing all the required information if you really need help... 👎 

Note that the current [last stable ](https://springdoc.org/#demos)version is 1.5.8 ...
Demos codes are available [here](https://github.com/springdoc/springdoc-openapi-demos)
