### ISSUE TITLE
Enable strict JSON output checking in tests

### ISSUE THREAD

**Issue by neiser** [springdoc/springdoc-openapi#115]
I noticed that in `test.org.springdoc.api.AbstractSpringDocTest` the `assertEquals(expected, result, false)` does not check the generated JSON strictly against the expected output (last argument is `false`). Is there any reason for this? 

From my experience, strict checking can hint at unwanted changes to already existing features and prevent regression bugs. Especially when output is added this is not covered by tests.

Would you appreciate a PR which enables strict checking and fixes JSONs? Or do you have a specific reason why it's disabled? Then a comment should be added I guess.

**Comment by springdoc** [comment]
Hi, 

 There is no reason for disabling strict checking.
 Thank you for your feedback.
