### ISSUE TITLE
Swagger-UI causing browser crash for some endpoints

### ISSUE THREAD

**Issue by komatiraju032** [springdoc/springdoc-openapi#1150]
I am using this [project](https://github.com/Netflix/conductor). I am not able to access some endpoints.

Check the below screenshot when I try to access the endpoint browser become unresponsive.

![Screenshot (6)](https://user-images.githubusercontent.com/22415463/116127876-f13d9a80-a6e5-11eb-947d-fef4c27e755e.png)

**Comment by bnasslahsen** [comment]
springdoc-openapi is built on top of swagger-ui. This is an issue with the swagger-ui.

You can test it by simply getting the produced json/yaml of your OpenAPI description and past it on the [swagger-ui editor.](https://editor.swagger.io/).

You will see that you can reproduce the same issue on your endpoint.
Note that before submitting issue in springdoc-openapi project, make sure you are using the [last stable version](https://github.com/springdoc/springdoc-openapi/releases).

If you need further help, submit you yaml document to the swagger-ui project instead.
