### ISSUE TITLE
Support for Zalando Problem Library Errors

### ISSUE THREAD

**Issue by ChrisJBurns** [springdoc/springdoc-openapi#1151]
So this is a very handy tool with regard to automatically generating OAPI specifications without the manual work of annotating the controllers. However, with the use of [Zalando Problem Spring](https://github.com/zalando/problem-spring-web), errors are not throw in the form of a `@ControllerAdvice`. This removes the errors from being shown on the generated specification UI.

Could I request a possible look into supporting a problem library for Spring such as Zalando. As [Problem Details for HTTP APIs](https://tools.ietf.org/html/rfc7807) are becoming more and more popular. This would allow any HTTP errors that are thrown by the Zalando library, to be shown in the specification UI.

At the moment, I don't think there's an alternative to trying to do the above manually.

**Comment by bnasslahsen** [comment]
@ChrisJBurns, 

Did you see   #953 ?

**Comment by ChrisJBurns** [comment]
I've just had a read, I believe the autoconfigured `ObjectMapper` for Spring already has the problem libraries registered, or is there a separate `ObjectMapper` bean for this library that I need to override?

e.g. 

```java
    @Bean
    public ObjectMapper jsonMapper() {
        return Json.mapper().registerModule(new ProblemModule())
            .registerModule(new ConstraintViolationProblemModule());
    }
```

**Comment by bnasslahsen** [comment]
You should respect the solution proposed in #953: Which uses swagger-core mapper.

**Comment by ChrisJBurns** [comment]
I'm not entirely sure what the solution proposed in #953 is, I can't see any mention of `swagger-core` mapper? Is the proposed solution to override the autoconfigured Spring ObjectMapper or to override the one that is used in `springdoc-openapi` ?

**Comment by bnasslahsen** [comment]
@ChrisJBurns, 

 If you have a sample code with the problem library, you can test it.
There is no overriding. But more additional configuration to declare on the object mapper that used by `springdoc-openap`i and  `swagger-core`.

Simply declare it in a static block, and you will see the difference.
I am closing this ticket now, i think we have provided you enough information.

If you are still having questions, make sure you Provide a Minimal, Reproducible Example - with HelloController that explains where you need exactly help.

**Comment by mmighri** [comment]
any advise to make Zalando default errors visible in open api specifications ?
