### ISSUE TITLE
Recursively defined collection fields are omitted in generated api docs

### ISSUE THREAD

**Issue by ConnorJBeck** [springdoc/springdoc-openapi#1158]
**Describe the bug**
Imagine you have a set of models as described below:

    public class TagCollection {
        private List<TagGroup> tagGroups;
        
        ... constructors, getters, setters, etc.
    }

    public class TagGroup {
        private String tagGroupName;
        private List<TagGroup> subgroups;
    
        ... constructors, getters, setters, etc.
    }

If springdoc is used to generate the swagger docs for these models (assume an appropriate controller elsewhere that utilizes `TagCollection`), the model definition for `TagGroup` does not include a `subgroups` property. It is entirely omitted.

**To Reproduce**
https://github.com/ConnorJBeck/SpringdocRecursiveExample

I made a quick and simple sample repo that replicates the problem, but given the above models it's very simple to reproduce. Note that this is reproduced using the latest versions of springboot, springdoc-openapi, etc.

**Actual vs. Expected**
The actual definition of the `TagGroup` model looks something like this

    {
      "components": {
        "schemas": {
          "TagGroup": {
            "type":"object",
            "properties": {
              "tagGroupName": { "type": "string" }
            }
          }
        }
      }
    }

But I would expect it to look like this:

    {
      "components": {
        "schemas": {
          "TagGroup": {
            "type":"object",
            "properties": {
              "tagGroupName": { "type": "string" },
              "subgroups": {"type": "array", "items": {"$ref": "#/components/schemas/TagGroup"}}
            }
          }
        }
      }
    }

Note that this behaviour works fine in springfox, which I am currently transitioning from, so I am fairly certain this is not a swagger issue of some sort.

**Additional Context**
I tried a few variations, and all of them worked properly. For example, changing the property in `TagCollection` into `TagGroup` instead of `List<TagGroup>` allows the `TagGroup` model to generate properly. Similar behaviour is observed if you instead change the type of `subgroups` from `List<TagGroup>` to `TagGroup`, or if you change both. So it seems to have something to do with the fact they are both collections.

**Comment by bnasslahsen** [comment]
@ConnorJBeck, 

You should add `@JsonBackReference` jackson annotation, for circular references resolution:
springdoc-openapi is built on top of swagger-core, which is based on Jackson library for resolving models schema.

If you use the following definition, it will work as expected:

```java
@Data
public class TagGroup {
	private String tagGroupName;

	@JsonBackReference
	private List<TagGroup> subgroups;

}
```

**Comment by ConnorJBeck** [comment]
That solved my issue. Thank you!
