### ISSUE TITLE
ParameterObject doesn't work with Groovy class

### ISSUE THREAD

**Issue by AndrewNorgrenTR** [springdoc/springdoc-openapi#1161]
**Describe the bug**
When using the @ParameterObject annotation with a Groovy class, it gets stuck stuck in an infinite loop in this method:  private static Stream<MethodParameter> extractFrom(Class<?> clazz, String fieldNamePrefix)

It looks like the ReflectionUtils to get the class fields isn't working right with Groovy classes

**To Reproduce**
-Spring Boot 2.3.4
- springdoc-openapi-ui:1.5.8

**Comment by bnasslahsen** [comment]
@AndrewNorgrenTR, 

Your description is not enough.

```java
static {
	SpringDocUtils.getConfig().addSimpleTypesForParameterObject(YourGroovyType.class);
}
```


 Please read the section [Using GitHub Issues](https://github.com/springdoc/springdoc-openapi/blob/master/CONTRIBUTING.adoc), and make sure you provide the all the listed information.

If you are reporting a bug, please help to speed up problem diagnosis by providing as much information as possible:

- You need to describe your context (the title of an issue is not enough)
- What version of spring-boot you are using?
- What modules and versions of springdoc-openapi are you using?
- What are the actual and the expected result using OpenAPI Description (yml or json)?
- Provide a Minimal, Reproducible Example - with HelloController that reproduces the problem

This ticket will be now closed. And can be reopened if the relevant information are provided.
