### ISSUE TITLE
Warning on referenced example

### ISSUE THREAD

**Issue by EstebanDugueperoux2** [springdoc/springdoc-openapi#1162]
**Describe the bug**
I get the same problem as https://github.com/springdoc/springdoc-openapi/issues/437 but for example in RequestBody

**To Reproduce**
Have an operation with a complex object in parameter to be specified in JSON:
```
  public ResponseEntity<CommissionDto> updateCommission(

@Parameter(description = "Security account number to update the Commission", required = true) @PathVariable("id") @Size(min = SecuritiesAccount.SECURITY_ACCOUNT_ID_SIZE, max = SecuritiesAccount.SECURITY_ACCOUNT_ID_SIZE) @Valid String id,

@io.swagger.v3.oas.annotations.parameters.RequestBody(description = "A Security account's commission rates to update", required = true, content = @Content(schema = @Schema(implementation = CommissionDto.class), examples = @ExampleObject(name = "requestBodyExample", ref = PUT_COMMISSION_REQUEST_BODY_EXAMPLE_KEY))) @RequestBody(required = true) @Valid CommissionDto commission

){
...
}
```

**Expected behavior**
I expect to have a valid openapi.yaml, i.e. without description field in example which give a warning when using https://editor.swagger.io/:

```
paths:
  '/api/v1/commissions/{id}':
    put:
      tags:
        - commissions-resource
      summary: Updates the security account's commission details into Base tiers repository
      description: updateCommission
      operationId: updateCommission
      parameters:
        - name: id
          in: path
          description: Security account number to update the Commission
          required: true
          schema:
            maxLength: 21
            minLength: 21
            type: string
      requestBody:
        description: A Security account's commission rates to update
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Commission'
            examples:
              requestBodyExample:
                description: requestBodyExample
                $ref: '#/components/examples/httpPutCommissionRequestBodyExample'
```

Could we have a similar fix than in 437 issue?

Thanks in advance.

**Comment by bnasslahsen** [comment]
@EstebanDugueperoux2, 

The description is not even readable. 
Please make sure you format the code and use github code/syntax highlighting features.

**Comment by EstebanDugueperoux2** [comment]
Do you agree this issue?

**Comment by bnasslahsen** [comment]
@EstebanDugueperoux2 , 

Unfortunately, i am not even to reproduce the issue.
You sample, is referencing many missing objects.

Please add complete description, of a minimal reproducible sample.
You have samples in [the project tests](https://github.com/springdoc/springdoc-openapi/tree/master/springdoc-openapi-webmvc-core/src/test/java/test/org/springdoc/api).
