### ISSUE TITLE
Add a way for knowing the springdoc-openapi made the request or not

### ISSUE THREAD

**Issue by talentedasian** [springdoc/springdoc-openapi#1163]
It would be nice if it was possible to determine whether if springdoc-openapi made the request.

**Comment by talentedasian** [comment]
This is already possible through the `Referer` header name in the `HttpServletRequest`

**Comment by talentedasian** [comment]
Opening this issue again because the `Referer` can feasibly spoofed.

**Comment by bnasslahsen** [comment]
@talentedasian, 

With the next release, you can add debug log level on:
`org.springdoc.api.AbstractOpenApiResource`
