### ISSUE TITLE
Provide GraalVM native image support

### ISSUE THREAD

**Issue by sdeleuze** [springdoc/springdoc-openapi#1164]
We don't provide such support directly on [Spring Native](https://github.com/spring-projects-experimental/spring-native) side because we only support what supported on start.spring.io, but I will be happy to provide some guidance and help if somebody is interested to contribute it here.

**Comment by bnasslahsen** [comment]
Hi @sdeleuze, 

I confirm WIP to have [GraalVM](https://github.com/oracle/graal) fully supported together with [spring-native](https://github.com/spring-projects-experimental/spring-native).

It should be working, out of the box without any additional configuration starting from the next release `v1.5.9`!

The only missing peace was related to https://github.com/oracle/graal/issues/1108  or https://github.com/spring-projects-experimental/spring-native/issues/157, but i added workaround for it 60e458ebc8250eaa257fe408094c4d0963003891.

I will add a simple [the demos project](https://github.com/springdoc/springdoc-openapi-demos) that will be available soon using the latest SNAPSHOT.

**Comment by sdeleuze** [comment]
Amazing

**Comment by bnasslahsen** [comment]
Hi @sdeleuze, 

I confirm, that release `springdoc-openapi v1.5.9` is now [released](https://github.com/springdoc/springdoc-openapi/releases/tag/v1.5.9).

There is huge improvement of `load time during the first and second access to the swagger-ui`. 

The improvement is just **impressive** with the native image on many levels.
The springdoc demos applications, has been built using `paketobuildpacks/builder:tiny`, with the default configuration (no optimization).

**VM characteristics:**

| Component  | characteristics|
| ------------- | ------------- |
| CPU(Intel) | 2 OCPU |
| Memory | 8 GB |

**Components versions:**

| Component  | Version|
| ------------- | ------------- |
| spring-boot | 2.5.0 |
| spring-native | 0.9.2 |

**[springdoc-openapi-spring-boot-2-webflux](https://github.com/springdoc/springdoc-openapi-demos/tree/master/springdoc-openapi-spring-boot-2-webflux) demo results:**


| Native<br/>Image | JVM | Startup time <br/>(sec) |  swagger-ui<br/>Tweets-API <br/>1st run (ms) | swagger-ui <br/> Stream-API <br/>2nd run (ms)  | Image<br/>Size  <br/> (MB) | Memory <br/> Usage  <br/>(MB) | CPU <br/> Usage <br/> (%) |
|      :---:      |     :---:      |     :---:      |     :---:      |     :---:      |     :---:      |     :---:      |     :---:      |
| No   | Hotspot 1.8.0_292  | 2.603     | 183    | 19    |  240  | 527    | 4  |
| Yes  | GraalVM 21.0.0.2  | 0.084       | 8     | 3    |  224  | 132    | 0.8   |


**[springdoc-openapi-spring-boot-2-webmvc](https://github.com/springdoc/springdoc-openapi-demos/tree/master/springdoc-openapi-spring-boot-2-webmvc) demo results:**


| Native<br/>Image | JVM | Startup time <br/>(sec) |  swagger-ui<br/>Users-API <br/>1st run (ms) | swagger-ui <br/> Stores-API <br/>2nd run (ms)  | Image<br/>Size  <br/> (MB) | Memory <br/> Usage  <br/>(MB) | CPU <br/> Usage <br/> (%) |
|      :---:      |     :---:      |     :---:      |     :---:      |     :---:      |     :---:      |     :---:      |     :---:      |
| No   | Hotspot 1.8.0_292  | 2.569     | 416    | 39    |  238  | 481    | 5  |
| Yes  | GraalVM 21.0.0.2  | 0.13       |  38     | 9    |  214  | 126    | 0.7   |

**Comment by goafabric** [comment]
@bnasslahsen 
Thanks for your support .. i barely missed this post .. and up to know i did not know that there are two OpenApi Implementations for Spring (Springfox is the one I knew)

I tried version 1.5.9 with the latest Spring Native 0.10.1 ... unfortunately its not working out of the box.
The code Compiles and i can access the OpenAPI page .. but it than throws one of those dreaded 
NativeHint Exceptions ...
Indication missing Nativehints on RestController and SynthesizedAnntation .. even setting this does not resolve the issue.

Is there anything special that has to be adjusted here ? The Demo Example e.g. excludes the health endpoint

thx

**Comment by bnasslahsen** [comment]
@goafabric, 

As mentioned in the previous post, the demo was validated with:

| Component  | Version|
| ------------- | ------------- |
| spring-boot | 2.5.0 |
| spring-native | 0.9.2 |

For the support for newer versions which, it's better to create a separate enhancement request. (I have now created #1225)
