### ISSUE TITLE
Issue with displaying generics type on request in Swagger UI

### ISSUE THREAD

**Issue by EyalGavr** [springdoc/springdoc-openapi#1165]
when the request have class with generic type its show the class without the generic type

**To Reproduce**
controller:
public ResponseEntity<Response<Campaign>> getById(@RequestBody Request<SqlFilters> request) 

Request Model:
public class Request<T> implements Serializable {

	private static final long serialVersionUID = 5869786216855441232L;
	@Valid
	private T data;
	private ActionSource actionSource;
}

pom:
<dependency>
  <groupId>org.springdoc</groupId>
  <artifactId>springdoc-openapi-ui</artifactId>
  <version>1.5.2</version>
</dependency>

<parent>
  <groupId>org.springframework.boot</groupId>
  <artifactId>spring-boot-starter-parent</artifactId>
  <version>2.1.3.RELEASE</version>
  <relativePath /> 
</parent>

**result:**
![image](https://user-images.githubusercontent.com/84378536/118624042-543bc200-b7b8-11eb-9524-cb5e5ec93e3e.png)

the response is working fine and have same structure!

Thanks

**Comment by bnasslahsen** [comment]
@EyalGavr, 

We only can address issue on the generated openapi docs.
springdoc-openapi is built on top of the swagger-ui.

Display errors should to be reported to[ swagger-ui project](https://github.com/swagger-api/swagger-ui) instead.

**Comment by EyalGavr** [comment]
thanks for ur answer.
here is open api doc:

"/campaign/getById": {
	"post": {
		"tags": [
			"campaign-controller"
		],
		"operationId": "getById_1",
		"requestBody": {
			"content": {
				"application/json": {
					"schema": {
						"$ref": "#/components/schemas/RequestSqlFilters"
					}
				}
			},
			"required": true
		},
		"responses": {
			"200": {
				"description": "OK",
				"content": {
					"*/*": {
						"schema": {
							"$ref": "#/components/schemas/ResponseCampaign"
						}
					}
				}
			}
		}
	}
}

"RequestSqlFilters": {
      "type": "object",
      "properties": {
	      "data": {
		      "type": "object"
	      },
	      "actionSource": {
		      "type": "string",
		      "enum": [
			      "1",
			      "2",
			      "3"
		      ]
	      }
      }
}
