### ISSUE TITLE
/api-docs works but swagger_ui.html is blank 

### ISSUE THREAD

**Issue by iwtxokhtd83** [springdoc/springdoc-openapi#1167]
Spring boot version: 2.3.x. RELEASE
springdoc-openapi-ui: 1.5.x
Issue example:
http://localhost:9100/lct/auth/swagger-ui/index.html?configUrl=/lct/auth/api-docs/swagger-config, this page is **blank**.
The content of index.html is:

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <title>Swagger UI</title>
    <link rel="stylesheet" type="text/css" href="./swagger-ui.css" />
    <link rel="icon" type="image/png" href="./favicon-32x32.png" sizes="32x32" />
    <link rel="icon" type="image/png" href="./favicon-16x16.png" sizes="16x16" />
    <style>
      html
      {
        box-sizing: border-box;
        overflow: -moz-scrollbars-vertical;
        overflow-y: scroll;
      }

      *,
      *:before,
      *:after
      {
        box-sizing: inherit;
      }

      body
      {
        margin:0;
        background: #fafafa;
      }
    </style>
  </head>

  <body>
    <div id="swagger-ui"></div>

    <script src="./swagger-ui-bundle.js" charset="UTF-8"> </script>
    <script src="./swagger-ui-standalone-preset.js" charset="UTF-8"> </script>
    <script>
    window.onload = function() {
      // Begin Swagger UI call region
      const ui = SwaggerUIBundle({
        url: "",
        dom_id: '#swagger-ui',
        deepLinking: true,
        presets: [
          SwaggerUIBundle.presets.apis,
          SwaggerUIStandalonePreset
        ],
        plugins: [
          SwaggerUIBundle.plugins.DownloadUrl
        ],
        layout: "StandaloneLayout"
      });
      // End Swagger UI call region

      window.ui = ui;
    };
  </script>
  </body>
</html>

**Comment by bnasslahsen** [comment]
@iwtxokhtd83, 

Please make sure, you provide a minimal reproductible sample before opening issues.

**Comment by daniyal-mujtaba-paysys** [comment]
@bnasslahsen, 
I have been facing the same issue. 

Springdoc dependency 

`<dependency>
	      <groupId>org.springdoc</groupId>
	      <artifactId>springdoc-openapi-ui</artifactId>
	      <version>1.6.9</version>
	   </dependency>
`

**JAVA VERSION 11**
**MAVEN 3.8+**
**Spring boot starter 2.7.1**

Steps to reproduce 

visit localhost:8080/dbservice/swagger-ui.html and it redirects to localhost:8080/dbservice/swagger-ui/index.html 
localhost:8080/dbservice/v3/api-docs is providing the desirable result 


**Enteries in my application.yml**

`springdoc:
  packagesToScan: dbservice
  pathsToMatch: /api/**
  writer-with-default-pretty-printer: true
  swagger-ui:
    url : v3/api-docs
    disable-swagger-default-url: true
    `






Following screenshot is for the additional detail  
![Uploading Screenshot (2).png…]()
