### ISSUE TITLE
Solution of #1146 is not exclusively for @id

### ISSUE THREAD

**Issue by rsierra83** [springdoc/springdoc-openapi#1169]
The solution was not specifically for ID of entities. 

Please review this method
org.springdoc.data.rest.utils.SpringDocDataRestUtils.customise(OpenAPI, ResourceMappings, PersistentEntities)

When looking for entity which its ID eis exposed,

`if (!repositoryRestConfiguration.isIdExposedFor(entity.getType())) 
 entityInfo.setIgnoredFields(ignoredFields);`

Now no properties are being ignored, not only @id.

Probably, should be modified this method:
org.springdoc.data.rest.utils.SpringDocDataRestUtils.getIgnoredFields(ResourceMetadata, PersistentEntity<?, ?>)

----
In order to allow soft-customization of SpringDocDataRestUtils, could you allow some ot its methods protected instead of private? For instance, the proper setIgnoredFields()

**Comment by bnasslahsen** [comment]
@rsierra83, 

Remember, contributions to this repository should follow its contributing guidelines and code of conduct..

Make sure you read the [contribution guide](https://github.com/springdoc/springdoc-openapi/blob/master/CONTRIBUTING.adoc), especially section: **Using GitHub Issues.**
