### ISSUE TITLE
Using @Schema for classes

### ISSUE THREAD

**Issue by MaxRybalkin91** [springdoc/springdoc-openapi#1170]
I'm using `SpringDoc OpenApi` v3 and the `@Schema` annotation to describe my classes and fields.
I've created a file named `swagger-message.properties` to replace my Cyrillic symbols.
I've also created the classes for reading Cyrillic from the file:
```
@Bean
public ResourceBundleMessageSource translator() {
    ResourceBundleMessageSource source = new ResourceBundleMessageSource();
    source.setBasenames("swagger-message");
    source.setUseCodeAsDefaultMessage(true);
    source.setDefaultEncoding("utf-8");
    return source;
}

public static class TranslationSchemaCustomizer implements PropertyCustomizer {

    @Autowired
    protected MessageSource translator;

    @Override
    public Schema customize(Schema property, AnnotatedType type) {
        property.setDescription(translate(property.getDescription()));
        return property;
    }

    private String translate(String message) {
        return translator.getMessage(message, null, message, Locale.getDefault());
    }
}
```
Here is my class I want to describe:
```
@Schema(description = "ErrorResponse")
@Data
public class ErrorResponse {

    @Schema(description = "ErrorCode", required = true)
    private final Integer errorCode;

    @Schema(description = "ErrorMessage")
    private final String errorMessage;
}
```
The values of the description params are the links to my property file. My problem is that the links can be used for the fields (I'm getting a value from my file for them), but I can't get values for the annotation of the entity class (`@Schema(description = "ErrorResponse"`)). It is shown not like a value from my file, I'm just getting 'ErrorResponse' in my browser.

Is it a bug, or it's my incorrect using the annotation?

**Comment by MaxRybalkin91** [comment]
![image](https://user-images.githubusercontent.com/47355826/119475085-7bb10280-bd55-11eb-8b50-e33c29e33dec.png)
Here is how I see my description in browser. As you see, `errorCode` and `errorMessage` are read from my file, but `ErrorResponse` is not

**Comment by bnasslahsen** [comment]
@MaxRybalkin91, 

`PropertyCustomizer` is not relevant for use case. It will only change the properties description, which explains your result.
This a sample working code:

1. First you can keep your Cyrillic symbols in your files: `swagger-message.properties`

2. Then you can set the following property, in your `application.properties`.

```properties
springdoc.api-docs.resolve-schema-properties=true
```
3.  Last, this is a full working code :

```java
@RestController
public class HelloController {

	@PostMapping("test")
	public ErrorResponse doSomethingInteresting() {
		return null;
	}

	@PropertySource("classpath:swagger-message.properties" )
	@Configuration
	public class SwaggerMessage{}

	@Schema(description = "${ErrorResponse}")
	@Data
	public class ErrorResponse {

		@Schema(description = "${ErrorCode}", required = true)
		private final Integer errorCode;

		@Schema(description = "${ErrorMessage}")
		private final String errorMessage;
	}

	@Bean
	public ResourceBundleMessageSource translator() {
		ResourceBundleMessageSource source = new ResourceBundleMessageSource();
		source.setBasenames("swagger-message");
		source.setUseCodeAsDefaultMessage(true);
		source.setDefaultEncoding("utf-8");
		return source;
	}

}
```

**Comment by MaxRybalkin91** [comment]
@bnasslahsen Sorry, but I didn't got it.
Here is my yml settings:
```
springdoc:
  api-docs:
    enabled: true
    resolve-schema-properties: true
```
I've added `SwaggerMessage` as a registered bean. Do I need to add all my values from my "swagger-message" file to the Configuration? I've tried the way, but I've not got a required result

**Comment by MaxRybalkin91** [comment]
> @MaxRybalkin91,
> 
> `PropertyCustomizer` is not relevant for use case. It will only change the properties description, which explains your result.
> This a sample working code:
> 
>     1. First you can keep your Cyrillic symbols in your files: `swagger-message.properties`
> 
>     2. Then you can set the following property, in your `application.properties`.
> 
> 
> ```ini
> springdoc.api-docs.resolve-schema-properties=true
> ```
> 
>     1. Last, this is a full working code :
> 
> 
> ```java
> @RestController
> public class HelloController {
> 
> 	@PostMapping("test")
> 	public ErrorResponse doSomethingInteresting() {
> 		return null;
> 	}
> 
> 	@PropertySource("classpath:swagger-message.properties" )
> 	@Configuration
> 	public class SwaggerMessage{}
> 
> 	@Schema(description = "${ErrorResponse}")
> 	@Data
> 	public class ErrorResponse {
> 
> 		@Schema(description = "${ErrorCode}", required = true)
> 		private final Integer errorCode;
> 
> 		@Schema(description = "${ErrorMessage}")
> 		private final String errorMessage;
> 	}
> 
> 	@Bean
> 	public ResourceBundleMessageSource translator() {
> 		ResourceBundleMessageSource source = new ResourceBundleMessageSource();
> 		source.setBasenames("swagger-message");
> 		source.setUseCodeAsDefaultMessage(true);
> 		source.setDefaultEncoding("utf-8");
> 		return source;
> 	}
> 
> }
> ```

I need an answer again, because that doesn't work

**Comment by bnasslahsen** [comment]
@MaxRybalkin91, 

You have been answered.
If you need more help, Provide a [**Minimal, Reproducible Example - with HelloController**](https://stackoverflow.com/help/minimal-reproducible-example) that reproduces all the steps above.

**Comment by MaxRybalkin91** [comment]
@bnasslahsen 

Here is a part of my configuration

```
    public OpenAPI customOpenAPI(BuildProperties buildProperties) {
        return new OpenAPI()
                .info(new Info()
                        .title("bundle-ws")
                        .version(buildProperties.getVersion())
                        .description("Bundle Ws"));
    }

    @Bean
    public GroupedOpenApi bundleApi() {
        return buildGroupedOpenApi("Bundle", "/bundle/**");
    }

    @Bean
    public GroupedOpenApi infoApi() {
        return buildGroupedOpenApi("Info", "/info/**");
    }

    private GroupedOpenApi buildGroupedOpenApi(String group, String... pathsToMatch) {
        return GroupedOpenApi.builder()
                .group(group)
                .pathsToMatch(pathsToMatch)
                .addOperationCustomizer(translationOperationCustomizer())
      
```

I've added a `properties` file for describing my fields and entities:


```
    @Bean
    public ResourceBundleMessageSource translator() {
        ResourceBundleMessageSource source = new ResourceBundleMessageSource();
        source.setBasenames("swagger-message");
        source.setUseCodeAsDefaultMessage(true);
        source.setDefaultEncoding("utf-8");
        return source;
    }

@PropertySource(value = "classpath:swagger-message.properties", encoding = "utf-8")
@Configuration
@Data
class SwaggerMessage {
}
```
If I use my GroupedOpenApi beans, I will get this:
<img width="317" alt="изображение" src="https://user-images.githubusercontent.com/47355826/120347069-9f9bb780-c304-11eb-9f78-340f7a355039.png">

I need to get this(it's with my cyrillic symbols), and I can get it without using `GroupedOpenApi` beans
<img width="327" alt="изображение" src="https://user-images.githubusercontent.com/47355826/120347831-4aac7100-c305-11eb-9407-844d05c1068f.png">
But I want to keep my requests grouped. Is it possible to have grouped requests and have the descriptions from `properties` file?

**Comment by bnasslahsen** [comment]
@MaxRybalkin91, 

For using groups, you can use `OpenApiCustomiser`:
This is a sample definition, that you can adapt for your group context: There is no additional property `springdoc.api-docs.resolve-schema-properties=true` required.
```java
@Bean
public GroupedOpenApi bundleApi(PropertyResolverUtils propertyResolverUtils, OpenAPIService openAPIService) {
	return GroupedOpenApi.builder()
			.group("test")
			.pathsToMatch("/**")
			.addOpenApiCustomiser(propertiesResolverForSchema( propertyResolverUtils, openAPIService))
			.build();
}

OpenApiCustomiser propertiesResolverForSchema(PropertyResolverUtils propertyResolverUtils, OpenAPIService openAPIService) {
	return openApi -> {
		Components components = openApi.getComponents();
		Map<String, Schema> schemas = components.getSchemas();
		schemas.values().forEach(schema -> openAPIService.resolveProperties(schema, propertyResolverUtils));
	};
}
```

We will see to make this property `springdoc.api-docs.resolve-schema-properties=true` consistent across groups out of the box, for a future release.
