### ISSUE TITLE
Duplicated Schema properties when @JsonProperty is used

### ISSUE THREAD

**Issue by Maxeh** [springdoc/springdoc-openapi#1172]
If a transfer object contains the @JsonProperty annotation with a JSON name, e.g. @JsonProperty("myMessage"), the generated swagger file contains the property twice, once with with the real property name and once with the JSON name. 

Simple example:

```
public class Event {
  
  private final String message;

  @JsonCreator
  public Event(@JsonProperty("myMessage) String message) {
    this.message = message;
  }
}
```
The generated swagger file will contain the schema like this:
```

"Event": {
  required": [
    message"
  ],
  "type": "object",
  "properties": {
    "MyMessage": {
      "type": "string",
      "writeOnly": true
    },
    "message": {
      "type": "string"
    }
  }
}
```
Normally, only the JSON property name should occur here, right? And why is the JSON property param "MyMessage" not required and marked as writeOnly? I don't want it to be writeOnly.

If I add `@Hidden` then only the JSON name is shown in swagger, but still it is marked as writeOnly and as NOT required. Also I don't really want to add `@Hidden` to all my fields all the time. 

SpringBoot version: 2.4.5
Springdoc openapi version: 1.5.9

**Comment by bnasslahsen** [comment]
@Maxeh, 

This is not related to springdoc-openapi.
You could use `ModelConverters.getInstance().resolveAsResolvedSchema(new AnnotatedType(Event.class));` to inspect the content.

You have sample code here https://github.com/springdoc/springdoc-openapi/issues/1094

If you feel you are facing a bug, you should raise an issue to the [swagger-core](https://github.com/swagger-api/swagger-core/issues) project instead.

**Comment by Maxeh** [comment]
Alright, I found a way to fix it. In case anyone is interested in the future. You also need to add the @JsonProperty on the fields, otherwise there will be a difference between writing(POST)/reading(GET) properties. If you only have the @JsonProperty on the constructor, you would POST with the JSON name, but read with the Java field name.

So just go with:

```
public class Event {
  
  @JsonProperty("myMessage) 
  private final String message;

  @JsonCreator
  public Event(@JsonProperty("myMessage) String message) {
    this.message = message;
  }
}
```
