### ISSUE TITLE
Errorous parameters for complex types in GET requests in "try it out"

### ISSUE THREAD

**Issue by andreptiloid** [springdoc/springdoc-openapi#1174]
**When I use a complex type as parameter in GET request it generates wrong URL**
When I open swagger-ui I want to use generated curl in "try it out", but it has errorous format.
- What I want to see in generated curl: 
`curl -X GET "http://host:port/context/test?address.city=NY&address.house=1&address.street=NewStreet&firstName=First&lastName=Arnold" -H "accept: application/json"`
- What I really see:
`curl -X GET "http://host:port/context/test?firstName=First&lastName=Arnold&address[city]=NY&address[street]=NewString&address[house]=1 -H "accept: application/json"`
- Pay attention on delimiter in address. It should be "address.street", but somehow it is "address[street]".

**To Reproduce**
- Create RestController class, with method like this
``` 
@GetMapping(value = "/test")
public MyResponseWrapper<ResultExample> testGet(@Valid Person request) throws SomeException {
    ResultExample result = ResultExample.builder()
            .address(getAddressString(request.getAddress()))
            .name(request.getFirstName() + " " + request.getLastName())
            .build();
    return wrapMe(result);
}
```
- Create Person class, like this :
```
@Data
@JsonInclude(JsonInclude.Include.NON_NULL)
public class Person {

    @NotEmpty
    @JsonProperty("firstName")
    private String firstName;

    @NotEmpty
    @JsonProperty("lastName")
    private String lastName;

    @Valid
    @JsonProperty("address")
    private Address address = new Address();

}
```
- And Address class, like this :
```
@Data
@JsonInclude(JsonInclude.Include.NON_NULL)
public class Address {

    @NotEmpty
    @JsonProperty("city")
    private String city;

    @NotEmpty
    @JsonProperty("street")
    private String street;

    @NotEmpty
    @JsonProperty("house")
    private String house;
}
```
- Then you should go to swagger-ui, select your controller, method and press on "try it out" and watch on curl, which is errorous
- I use 1.5.9 version of springdoc-openapi-ui but 1.5.7 has the same error
- The generated specification is correct. This error occurs only in swagger-ui "try it out"

**Comment by bnasslahsen** [comment]
@andreptiloid, 

The `curl` query is not generated by springdoc-openapi.
springdoc-openapi is responsible for generating the OpenAPI spec.
If the generated OpenAPI description is correct, then feel free to report your issue to the [swagger-ui ](https://github.com/swagger-api/swagger-ui/issues)project.
