### ISSUE TITLE
springdoc.packages-to-scan not working

### ISSUE THREAD

**Issue by poteii** [springdoc/springdoc-openapi#1175]
I'm using SpringDoc to work with flowable-rest and I have tried to add
`springdoc.packages-to-scan=org.flowable.rest.service.api` to application.properties file but I still not working

Can you please advise?

Note: 
springdoc-openapi-ui: 1.5.9
org.flowable:flowable-spring-boot-starter-rest: 6.6.0

**Comment by bnasslahsen** [comment]
@poteii, 

Please make sure you provide all the relevant information, described in [Using GitHub Issues section](https://github.com/springdoc/springdoc-openapi/blob/master/CONTRIBUTING.adoc):
- Make sure you [Provide a Minimal, Reproducible Example - with HelloController](https://stackoverflow.com/help/minimal-reproducible-example) that reproduces the problem

This ticket will be closed and can be reopened if the relevant information are provided.

**Comment by ogarose** [comment]
@poteii  did you solve your issues? I have similar problem with flowable library.
