### ISSUE TITLE
NotBlank-Annotation produces wrong reference in documentation

### ISSUE THREAD

**Issue by vanDarg** [springdoc/springdoc-openapi#1176]
**Describe the bug**
I have a class with a field which is of the type of an abstract super-class. That abstract class bears the @Schema-Annotation with two subtypes given. In the resulting documentation, the expected 'oneOf' is generated for the corresponding schema (see fieldTwo & fieldThree below).
However, once I annotate said field with @NotBlank, the schema only references the super-class and does not show the subtypes (fieldOne).

    TestParameter:
      required:
        - fieldOne
      type: object
      properties:
        fieldOne:
          $ref: '#/components/schemas/AbstractValueParameter'
        fieldTwo:
          oneOf:
            - $ref: '#/components/schemas/ValueParameterOne'
            - $ref: '#/components/schemas/ValueParameterTwo'
        fieldThree:
          oneOf:
            - $ref: '#/components/schemas/ValueParameterOne'
            - $ref: '#/components/schemas/ValueParameterTwo'

I am using Spring Boot 2.4.2 and springdoc-openapi 1.5.9.

**Expected behavior**
Correct schema generation with all subtypes as if not annotated.

**Comment by bnasslahsen** [comment]
@vanDarg, 

If you are reporting a bug, please help to speed up problem diagnosis by providing as much information as possible:
Make sure you [provide a Minimal, Reproducible Example - with HelloController ](https://stackoverflow.com/help/minimal-reproducible-example)that reproduces the problem.

This ticket will be closed, and can be reopened if the relevant information are provided.

**Comment by vanDarg** [comment]
Do you by chance have at least an idea where to start looking? I will try to come up with an example controller but I am afraid it might not actually reproduce the issue at hand. Any help would be appreciated.

**Comment by bnasslahsen** [comment]
@vanDarg, 

Your description is incomplete.
Make sure you [provide a Minimal, Reproducible Example - with HelloController ](https://stackoverflow.com/help/minimal-reproducible-example)that reproduces the problem.
