### ISSUE TITLE
Why don't properties work with GroupedOpenApi?

### ISSUE THREAD

**Issue by MaxRybalkin91** [springdoc/springdoc-openapi#1177]
Here is a part of my configuration

```
    public OpenAPI customOpenAPI(BuildProperties buildProperties) {
        return new OpenAPI()
                .info(new Info()
                        .title("bundle-ws")
                        .version(buildProperties.getVersion())
                        .description("Bundle Ws"));
    }

    @Bean
    public GroupedOpenApi bundleApi() {
        return buildGroupedOpenApi("Bundle", "/bundle/**");
    }

    @Bean
    public GroupedOpenApi infoApi() {
        return buildGroupedOpenApi("Info", "/info/**");
    }

    private GroupedOpenApi buildGroupedOpenApi(String group, String... pathsToMatch) {
        return GroupedOpenApi.builder()
                .group(group)
                .pathsToMatch(pathsToMatch)
                .addOperationCustomizer(translationOperationCustomizer())
      
```

I've added a `properties` file for describing my fields and entities:

```
    @Bean
    public ResourceBundleMessageSource translator() {
        ResourceBundleMessageSource source = new ResourceBundleMessageSource();
        source.setBasenames("swagger-message");
        source.setUseCodeAsDefaultMessage(true);
        source.setDefaultEncoding("utf-8");
        return source;
    }

@PropertySource(value = "classpath:swagger-message.properties", encoding = "utf-8")
@Configuration
@Data
class SwaggerMessage {
}
```
If I use my GroupedOpenApi beans, I will get this:
<img width="317" alt="изображение" src="https://user-images.githubusercontent.com/47355826/120347069-9f9bb780-c304-11eb-9f78-340f7a355039.png">

I need to get this(it's with my cyrillic symbols), and I can get it without using `GroupedOpenApi` beans
<img width="327" alt="изображение" src="https://user-images.githubusercontent.com/47355826/120347831-4aac7100-c305-11eb-9407-844d05c1068f.png">
But I want to keep my requests grouped. Is it possible to have grouped requests and have the descriptions from `properties` file?

**Comment by bnasslahsen** [comment]
@MaxRybalkin91, 

Please add your description to your original issue: #1170
And we will add the answer ...
