### ISSUE TITLE
Show /api-docs & /api-docs/yaml in swagger document

### ISSUE THREAD

**Issue by ratna-qualica** [springdoc/springdoc-openapi#1180]
###  Show /api-docs & /api-docs.yaml endpoints in openApi spec.
- Currently when we request /api-docs we get generated openApi spec with all the endpoints.
- We can also show actuator by setting property `springdoc.show-actuator` to `true`.
- We need a way to tell speingdoc to generate /api-docs  & /api-docs.yaml as well.

**Comment by bnasslahsen** [comment]
@ratna-qualica, 

You can adapt the paths using the properties:

```properties
springdoc.api-docs.path=/api-docs
```

More details are available in [the official documentation](https://springdoc.org/).
