### ISSUE TITLE
Please add OpenAPI 3.1 supports

### ISSUE THREAD

**Issue by andrejs-sinkevics** [springdoc/springdoc-openapi#1181]
Please add OpenAPI 3.1 supports
[OpenAPI Specification](https://spec.openapis.org/oas/v3.1.0)

**Comment by bnasslahsen** [comment]
@andrejs-sinkevics, 

springdoc-openapi is buit on top of the swagger-core library.
There is an [ongoing request](https://github.com/swagger-api/swagger-core/issues/3913) about the support of OpenaAPI 3.1.

Once this is done, the support will be updated in the springdoc-openapi.

**Comment by linarkou** [comment]
Hey, [v2.2.0](https://github.com/swagger-api/swagger-core/releases/tag/v2.2.0) of swagger-core with OAS 3.1.0 support was released! Looking forward to updates 🙂

**Comment by bnasslahsen** [comment]
@linarkou, 

The initial support for OAS 3.1.0 is now added.
To use this support, you need to declare the following property:

```properties
springdoc.api-docs.version=openapi_3_1
```

Note that the swagger-ui support is not yet available.
We will wait for [this ticket](https://github.com/swagger-api/swagger-ui/issues/5891) to be completed.

**Comment by okohub** [comment]
@bnasslahsen Do we need to wait extra things to have "requestBody" in GET-HEAD-DELETE?

**Comment by bnasslahsen** [comment]
@okohub, 

Please stop writing same messages in many tickets...
As answered in https://github.com/springdoc/springdoc-openapi/issues/1003, You need a version of OpenAPI that supports that which is not the case. 

In other cases where the HTTP spec is vague (such as GET, HEAD and DELETE), **requestBody is permitted but does not have well-defined semantics and SHOULD be avoided if possible.**

The recommendation is the avoid this kind of representation and we will stick on that.
