### ISSUE TITLE
Parameter 3 of method swaggerWelcome in org.springdoc.webflux.ui.SwaggerConfig required a bean of type 'org.springframework.web.reactive.result.method.RequestMappingInfoHandlerMapping' that could not be found.

### ISSUE THREAD

**Issue by KafkaProServerless** [springdoc/springdoc-openapi#1182]
**Describe the bug**
- If you are reporting a bug, please help to speed up problem diagnosis by providing as much information as possible:
OK

- A clear and concise description of what the bug is: the title of an issue is not enough
I just upgraded to Sprinng Boot 2.5.0 who went GA. With this, I upgraded from 1.5.4 to 1.5.5, 1.5.6, 1.5.7, 1.5.8, 1.5.9, and all yields this error:
Parameter 3 of method swaggerWelcome in org.springdoc.webflux.ui.SwaggerConfig required a bean of type 'org.springframework.web.reactive.result.method.RequestMappingInfoHandlerMapping' that could not be found.

**To Reproduce**
- What version of spring-boot you are using?
2.5.0

- What modules and versions of springdoc-openapi are you using?
        <dependency>
            <groupId>org.springdoc</groupId>
            <artifactId>springdoc-openapi-webflux-ui</artifactId>
            <version>1.5.9</version>

        </dependency>

- What is the actual and the expected result using OpenAPI Description (yml or json)?
The app cannot start when using the latest version of this project.

- Provide with a sample code (HelloController) or Test that reproduces the problem
https://github.com/KafkaProServerless/questionopenapi

**Expected behavior**
- A clear and concise description of what you expected to happen.
The app can start, and this issue can be fixed 
Parameter 3 of method swaggerWelcome in org.springdoc.webflux.ui.SwaggerConfig required a bean of type 'org.springframework.web.reactive.result.method.RequestMappingInfoHandlerMapping' that could not be found.

- What is the expected result using OpenAPI Description (yml or json)?
on more 
Parameter 3 of method swaggerWelcome in org.springdoc.webflux.ui.SwaggerConfig required a bean of type 'org.springframework.web.reactive.result.method.RequestMappingInfoHandlerMapping' that could not be found.

**Screenshots**
No screenshot

**Additional context**
I searched the issues, and found something very similar:
https://github.com/springdoc/springdoc-openapi/issues/1091

But mine is parameter 3, but I think this patpatpat123 try to raise a valid issue. I am seeing the same (I am parameter 3 instead)

And I think some resolution was found in the discussion, but I saw a deleted comment. Also, the thread is locked, I wanted to add on as I am also observing this, but have to start a new one.

What else can I provide please? I did join a small project.

**Comment by guilhermeginezsilva** [comment]
Hello guys, just to complement the issue details. I had the same issue using Spring 2.5.0 and 2.5.1, and I've got that the problem occurs when I use Spring Data Rest dependency in the project.

Currently my project has:
implementation("org.springframework.boot:spring-boot-starter-webflux")
	implementation("org.springframework.boot:spring-boot-starter-data-jpa")
	implementation("org.springframework.boot:spring-boot-starter-validation")
//	implementation("org.spr/ingframework.boot:spring-boot-starter-data-rest")
	implementation("org.springframework.boot:spring-boot-starter-security")

If I uncomment this data rest dependency the reported error occurs.
