### ISSUE TITLE
springdoc-openapi-common: Parameter reference is resolved as query parameter in generated schema

### ISSUE THREAD

**Issue by sadam21** [springdoc/springdoc-openapi#1183]
**Describe the bug**
I'm unable to add reference to `components/parameters`. Fields `in` with `query` value and String `schema` is automatically added by `OpenApiResource` despite these fields are properly defined in references parameter.

**To Reproduce**
I wanted to create reference to parameter as described in [OpenAPI specification](https://swagger.io/docs/specification/describing-parameters/). We have our implementation of `RepositoryRestResourceProvider` which creates parameter (io.swagger.v3.oas.models.parameters.Parameter)
```java
new Parameter.$ref("someReferencedParameter")
```
(`$ref` is the only parameter).

We also use `OpenApiResource` and the problematic code seems to be in [AbstractOpenApiResource::calculatePath](https://github.com/springdoc/springdoc-openapi/blob/master/springdoc-openapi-common/src/main/java/org/springdoc/api/AbstractOpenApiResource.java#L502) which contains:
```java
if (!CollectionUtils.isEmpty(operation.getParameters()))
    operation.getParameters().forEach(parameter -> {
        if (parameter.getSchema() == null)
            parameter.setSchema(new StringSchema());
        if (parameter.getIn() == null)
            parameter.setIn(ParameterIn.QUERY.toString());
    }
);
```
`query` value and string schema is added despite it's just reference where are properly defined different values.

**Expected behavior**
Generated parameter in OpenAPI schema should be:
```json
{"$ref":"#/components/parameters/someReferencedParameter"}
```

but was:
```json
{"$ref":"#/components/parameters/someReferencedParameter","in":"query","schema":{"type":"string"}}
```

**Additional context**
Used Springdoc version is 1.5.0. Version 1.5.9 seems to have the same mechanism according to the source code. I tried to upgrade but there are some incompatible changes which will take some time.

I'm not sure if it's bug or feature request. Is this behaviour intended? We used workaround with subclass of `Parameter`:

```kotlin
    private class RefParameter(referenceName: String) : Parameter() {
        init {
            `$ref` = referenceName
        }
        override fun getIn(): String? {
            return null
        }

        override fun getSchema(): Schema<*>? {
            return null
        }
    }
```

Is there better solution?

Thank you!

**Comment by bnasslahsen** [comment]
Hi @sadam21, 

It is an enhancement request, to get it out of the box.
Note that you can still achieve your goal using `OpenApiCustomiser`.

I propose that you submit a PR, with the related test case. And we will get it merged for the next release.

**Comment by sadam21** [comment]
Hi @bnasslahsen,

thanks for your reply.

I'll look at it and try to create some PR.
