### ISSUE TITLE
Sort is not supported outside of Pageable.

### ISSUE THREAD

**Issue by dhasilin** [springdoc/springdoc-openapi#1186]
**Describe the bug**
Almost everything works fine with `Sort` being part of `Pageable`. But it's not when we want to pass `Sort` by itself.
And documentation is confusing:
According to docs [https://springdoc.org/index.html#getting-started](url) (v1.5.9):
- 3.5 says that `springdoc-openapi-data-rest` is enough to support data types, but no, annotation like `@ParameterObject` is needed.
- 11.20 says about annotation (cool) but also says that Pageble should be hidden and  `you will have to declare the explicit mapping of Pageable` but it is working without hiding.

**To Reproduce**
Add dependencies
```    
    implementation 'org.springdoc:springdoc-openapi-ui:1.5.9'
    implementation 'org.springdoc:springdoc-openapi-data-rest:1.5.9'
```
Use Sort in controller
```
    @GetMapping("/wait")
    public String what(@ParameterObject Sort s) {
        return "but why?";
    }
```
It doesn't matter if there is `@ParameterObject` annotation.
![image](https://user-images.githubusercontent.com/1693842/121534367-d3b06000-ca09-11eb-905f-e3946a258847.png)

**Expected behavior**
I expect sort to behave the same way as it behaves inside `Pageable`:
![image](https://user-images.githubusercontent.com/1693842/121534700-1f630980-ca0a-11eb-9a89-b0786058d509.png)
Preferably without any annotation. At least when there is no need to transfer some defaults or etc.

Sorry if I missed something or misunderstood. I've tried to read documentation and navigate though all existing issued with "Sort" keyword :)

**Comment by bnasslahsen** [comment]
@dhasilin, 

There is no such a feature supported out of the box.
You can simply use, `replaceWithSchema` method to replace the `Sort` schema everywhere:

```java
static {
	SpringDocUtils.getConfig().replaceWithSchema(org.springframework.data.domain.Sort.class, new ArraySchema().items(new StringSchema()));
}

```

If you feel it's useful for the community. Please feel free, to propose a PR.

**Comment by dhasilin** [comment]
@bnasslahsen  thanks, it worked great, but now sorts are always required :( even adding @Parameter(required=false) not helping.

**Comment by bnasslahsen** [comment]
@dhasilin, 

The only way is to implement the integration with `@SortDefaults`: Same way as it's done for `PageableDefault`...
Don't hesitate to see the [source code](https://github.com/springdoc/springdoc-openapi) for the existing implementation..

And as said earlier: If you feel it's useful for the community. Please feel free, to propose a PR.

**Comment by dhasilin** [comment]
@bnasslahsen not sure its usefull, but i'll try.
I guess it should llok like https://github.com/springdoc/springdoc-openapi/blob/master/springdoc-openapi-data-rest/src/main/java/org/springdoc/data/rest/customisers/DataRestDelegatingMethodParameterCustomizer.java 
Or am I missing something?)

**Comment by bnasslahsen** [comment]
@dhasilin, 

Yes, most of the logic for handling `PageableDefault` is there.
