### ISSUE TITLE
Add support for @ModelAttribute annotations

### ISSUE THREAD

**Issue by ckubik-monster** [springdoc/springdoc-openapi#119]
It would be nice to have support also for @ModelAttribute annotation used in a parameter of controller method.

Example:
```java
@RestController
public class ExampleController {

  @GetMapping("/example")
  void get(@ModelAttribute InputDTO input) {
    //...
  }
}

class InputDTO {
  @Schema(required = true, description = "...")
  String first;

  @Schema(description = "...")
  String second;
}
```

Now is such parameter processed with no special care what leads to false API docs.

For Java example above it would lead to:
```javascript
//parameters for path /example
"parameters": [
  {
    "name":"input",
    "in":"query",
    "required":true,
    "schema":{"$ref":"#/components/schemas/InputDTO"}
  }
]

//schema for InputDTO
{
  "required":["first"],
  "type": "object",
  "properties": {
    "first": {
      "type": "string",
      "description" :"..."
    },
    "second": {
      "type": "string",
      "description": "..."
    }
  }
}
```

As a result Spring will handle request parameters in different way than what API doc is declaring and also Swagger UI is unable to call a such endpoint of course.

Expected API docs for the example is following:
```javascript
"parameters": [
	{
		"name": "first",
		"in": "query",
		"description": "...",
		"required": true,
		"schema": {
			"type": "string"
		}
	},
	{
		"name": "second",
		"in": "query",
		"description": "...",
		"required": true,
		"schema": {
			"type": "string"
		}
	}
]
```

**Comment by springdoc** [comment]
Hi, 

 @ModelAttribute is related to web views. 
 Its not supposed to be used on REST APIs.
 We are not planning to support it.

**Comment by Mattias-Sehlstedt** [comment]
> > Hi,
> > [@ModelAttribute](https://github.com/ModelAttribute) is related to web views. Its not supposed to be used on REST APIs. We are not planning to support it.
> 
> I know this issue is closed, but this means that it's not possible to use `@ModelAttributes` with `springdoc-openapi`. I understand that one might not be "supposed" to use ModelAttributes in REST APIs, but one _CAN_, and it's powerful (unless there is another way to achieve the same effect by other means).
> 
> So from what I understand, one would need to choose one or the other... is there no workaround that can be done that enables us to be able to use both?

@roberto-welzel, are you still looking for an answer to this or have you found a solution?

**Comment by alkismavridis** [comment]
Hi there, can you provide some links or explanation why it is not supposed to be used in rest apis and why?
To my understanding (please correct me if I am wrong) this comes from the same package that GetMapping and so on come from. We extensively use it in our rest apis actually, so I would be interested to know if we do something wrong.

We would also we VERY glad if  spring-doc supports this or gives us some other annotation through which we can achieve the same effect. At the moment we have to choose between our swagger pages not really being workable, or having 15+ method parameters in our endpoint methods with no ability to wrap them. :(

**Comment by Mattias-Sehlstedt** [comment]
@alkismavridis Have you tried `@ParameterObject` as per https://github.com/springdoc/springdoc-openapi/issues/2439?
