### ISSUE TITLE
Redirecting UI index doesn't work correctly

### ISSUE THREAD

**Issue by totikj** [springdoc/springdoc-openapi#1190]
**Describe the bug**
Earlier if we type this url: https://ourdomainname/rest/swagger-ui.html in browser, it was redirected to this url: https://ourdomainname/rest/swagger-ui/index.html?configUrl=/rest/v3/api-docs/swagger-config but now it is redirected to 
https://ourdomainname/rest/rest/swagger-ui/index.html?configUrl=/rest/v3/api-docs/swagger-config and we got the error 403.
The wrong url contains the "rest" string twice.

**To Reproduce**
With 1.5.5 openapi-ui.version it works correctly, but with 1.5.6 or above it doesn't.
Maybe this commit causes this problem: https://github.com/springdoc/springdoc-openapi/commit/35139eeabcd9a8ff08adafca1b57103f9c09f3b0

**Comment by bnasslahsen** [comment]
@totikj, 

Your description is not clear.
Unless you provide a [Minimal, Reproducible Example - with HelloController](https://stackoverflow.com/help/minimal-reproducible-example) that reproduces the problem, we cannot help more.

This ticket will be closed, and can be reopened if any relevant information is provided.
