### ISSUE TITLE
The default @Deprecated annotation's function is not enough

### ISSUE THREAD

**Issue by Chance2017** [springdoc/springdoc-openapi#1191]
**Is your feature request related to a problem? Please describe.**
- For springdoc-openapi-ui module:
- I'm always frustrated when I plan to deprecate all Apis of a certain prefix and switch to a new prefix.

**Describe the solution you'd like**
- Maintain a @Deprecated annotation containing the "String[] include();" and "String[] exclude();" in the springdoc package.
- include[] includes the URL prefixes that need to be deprecated.
- exclude[] excludes URL prefixes that should not be deprecated.
- Then support this in the corresponding business logic code.

**Comment by debargharoy** [comment]
Not sure about the deprecation but there is a way to exclude everything under a particular package.

You can use the `springdoc.packages-to-exclude` property and specify all the packages that should be excluded from the Swagger documentation like so:
```
springdoc.packages-to-exclude = com.example.api.v1,com.example.api.v2
```
The above property will exclude all the endpoints under v1 and v2 packages.

**Comment by bnasslahsen** [comment]
@Chance2017, 

Thank you for your suggestion.
Please feel free to propose a PR for this enhancement.
