### ISSUE TITLE
springdoc-openapi-ui :: OAuth::CORS error

### ISSUE THREAD

**Issue by tamilsmani** [springdoc/springdoc-openapi#1192]
I am trying to integrate spring boot with Swagger using springdoc-openapi-ui.
I have enabled OAuth security (Client credentials). when I fetch the OAuth token, I am getting the CORS error on the UI (attached the screenshot on the same)

Config details
------------------

@Bean
	public WebMvcConfigurer corsConfigurer() {
		return new WebMvcConfigurer() {
			@Override
			public void addCorsMappings(CorsRegistry registry) {
				registry.addMapping("*")
						.allowedOrigins("*").allowCredentials(true)
						.allowedHeaders("*")
						.allowedMethods("*");
			}
		};
	}

------------------
@Bean
public OpenAPI oauthOpenAPI(Server server) {
		LOGGER.info(String.format(SWAGGER_SECURITY_LOG, "oauth2-security"));
		return openAPI
			  .servers(List.of(server))
	          .components(new Components()
	          .addSecuritySchemes("Authentication",
	        		  new SecurityScheme()
	        		  	.type(SecurityScheme.Type.OAUTH2)
	        		  	.description("Oauth2 flow")
	        		  	.flows(new OAuthFlows()
	        		  			.clientCredentials(new OAuthFlow()
	        		  					.authorizationUrl(tokenURL)
	        		  					.refreshUrl(tokenURL)
	        		  					.tokenUrl(tokenURL)
	        		  					 .scopes(new Scopes()))
                      )));
	}

---------------------

Spring boot version: 2.3.3.RELEASE
org.springdoc:springdoc-openapi-ui:jar:1.5.9

Could u help me in resolve the issue?

**Comment by tamilsmani** [comment]
<img width="1061" alt="Screenshot 2021-06-14 at 20 21 35" src="https://user-images.githubusercontent.com/39116373/121914224-b3f1a280-cd4f-11eb-9eea-2ff3ed918920.png">

Attached the screenshot.

**Comment by devDinoFukuda** [comment]
Hello @tamilsmani , did you solve your problem?
I'm having the same difficulty.

**Comment by debargharoy** [comment]
Just to be sure that we are all on the same page, is your app registered with the destination app?

**Comment by devDinoFukuda** [comment]
Hi @debargharoy, 
I didn't understand the question.

**Comment by bnasslahsen** [comment]
CORS is related to your configuration. 
You need to have CORS enabled, on your applications that is blocking the swagger-ui.

**Comment by fabrizio-cannizzaro** [comment]
Hello, I have the same problem. I have tried ot remove the Origin header, replicating the request with cURL, and it works.
How to is possible to avoid the Origin header apppended?

**Comment by ujhazib** [comment]
Just to note here, even if I disable CORS in my application, the integrated swagger will throw a CORS error.

**Comment by mjaksa** [comment]
Same issue by me anyone has a solution?

**Comment by MetaiR** [comment]
I have the same issue with the latest version of spring boot, java (21) and springdoc

**Comment by ajmalch** [comment]
Same issue for me as well
