### ISSUE TITLE
Swagger UI does not show up due to wildcard path

### ISSUE THREAD

**Issue by MarekSuchanek** [springdoc/springdoc-openapi#1193]
**Describe the bug**

When using a generic path `@GetMapping(path="**")`, the route `/swagger-ui/index.html` is consumed by the get mapping. However, `/swagger-ui.html` (redirect) and `/v3/api-docs` are working as expected.

**To Reproduce**
- Add endpoint with  `@GetMapping(path="**")` to the app.

Or use https://github.com/MarekSuchanek/spring-boot-openapi-test

**Expected behavior**
- `/swagger-ui/index.html` should show Swagger UI.

**Additional context**
The provided example is of course a dummy app; we need `@GetMapping(path="**", produces={"!application/json"})` in a different larger application (it is inevitable as URI fragments are variable, potentially nested and without prefix).

**Comment by bnasslahsen** [comment]
@MarekSuchanek,

This is not a bug! Your configuration is in conflict with the swagger-ui.

You are intercepting all the request, and getting redirected to your endpoint `@GetMapping(path="**")`.
