### ISSUE TITLE
How can I get the group name?

### ISSUE THREAD

**Issue by obarat** [springdoc/springdoc-openapi#1195]
I have defined a group `dev` and another group `test`: 

```java
    @Bean
    public GroupedOpenApi devGroup() {
        return GroupedOpenApi.builder().group("dev").pathsToMatch("/**").build();
    }

    @Bean
    public GroupedOpenApi testGroup() {
        return GroupedOpenApi.builder().group("test").pathsToMatch("/**").build();
    }
```

I would like to populate a global header the name of the group for every request in order to control which backend service to call.  How can I get the name of the group when I'm processing the swagger request?  

I've tried using `@Value("${springdoc.swagger-ui.urls[0].name}")` and I've tried to fetch it using `SpringDocPropertiesUtils` but I have been unsuccessful.

**Comment by bnasslahsen** [comment]
Use `getGroup()` from `GroupedOpenApi`.

```java
// where ctx is the spring context
ctx.getBean("testGroup").getGroup()
```
