### ISSUE TITLE
Cannot disable Petstore on plain Spring (non-boot) app

### ISSUE THREAD

**Issue by agilehorse** [springdoc/springdoc-openapi#1198]
Hello, 
even if I included 
`springdoc.swagger-ui.disable-swagger-default-url=true`
in my properties file, when I enter swagger ui without config url (/swagger-ui/index.html) it still displays petstore. (I tried changing other springdoc properties such as api-docs path and it worked)

**Dependencies:**
![image](https://user-images.githubusercontent.com/39390272/122746873-be012d00-d28a-11eb-8249-39cbad51a131.png)
**Versions**
![image](https://user-images.githubusercontent.com/39390272/122746934-ca858580-d28a-11eb-8d1d-c44f0f4abaf7.png)

**Config file that is imported in class that implements WebMvcConfigurer**

`

    @Configuration
    @Profile("!test")
    @Import({
            SpringDocConfiguration.class,
            SwaggerUiConfigProperties.class,
            SwaggerUiOAuthProperties.class
    })
    @ComponentScan(basePackages = {"our.package", "org.springdoc"})
    public class SwaggerConfig {

        @Bean
        public OpenAPI springShopOpenAPI() {
            return new OpenAPI()
                    .servers(Collections.singletonList(new Server().url("/xxx")))
                    .info(new Info().title("Documentation XXX")
                            .version("1.0.0"));
        }
    }
`

**Comment by bnasslahsen** [comment]
@agilehorse, 

I see here other spring-boot missing dependencies. 
Make sure you follow the steps of the [F.A.Q](https://springdoc.org/#how-to-integrate-open-api-3-with-spring-project-not-spring-boot).

If you need further help, make sure you provide a [Minimal, Reproducible Example - with HelloController](https://stackoverflow.com/help/minimal-reproducible-example) that reproduces the problem.

This ticket will be closed and can be reopened, if the relevant information is provided.

**Comment by agilehorse** [comment]
Actually the springdoc worked well even without those springboot autoconfiguration dependencies. 
I have found a solution for my problem, so if anyone encounters this, hey can solve it using custom bean SwaggerUiConfigProperties
![image](https://user-images.githubusercontent.com/39390272/124282211-e0c4f880-db4a-11eb-8d7a-e96e479fbbef.png)
