### ISSUE TITLE
Reading annotation values from properties file not working properly

### ISSUE THREAD

**Issue by amreldeeb0** [springdoc/springdoc-openapi#1202]
**Describe the bug**
I am trying to read the description values from properties files, so the annotation would look like @Tag(name = "${checkout.controller.tag.name}", description = "${checkout.controller.tag.desc}")
but unfortunately it is not reading the values properly although the key value pair are correct in the properties file.
e.g **checkout.controller.tag.desc=some description here**
The strange thing that it works fine for other annotations like: @Operation(summary = "${api.create.checkout.desc}")
_code is shown below.._
Any idea what might be wrong here?

**To Reproduce**
- using spring-boot 2.3.4.RELEASE
- using springdoc-openapi-ui 1.5.9
@RestController
@Tag(name = "${checkout.controller.tag.name}", description = "${checkout.controller.tag.desc}")
public class CheckoutController {

    @Operation(summary = "${api.create.checkout.desc}")
    @PostMapping(value = "/checkouts")
    public ResponseEntity<CreateResource> createCheckout(@RequestBody CheckoutRequest checkoutRequest)
            throws CustomValidationException, ApplicationException, RestClientApplicationException {

}

**Expected behavior**
in the generated openapi.json tag is still showing as **${checkout.controller.tag.desc}** not **some description here**

**Comment by bnasslahsen** [comment]
@amreldeeb0, 

Nothing strange here.  All the supported properties are in the [documentation](https://springdoc.org/#can-i-use-spring-property-with-swagger-annotations).

If you feel this feature useful for the community. Feel free to propose a PR.
