### ISSUE TITLE
Add support for asyncapi (https://www.asyncapi.com/)

### ISSUE THREAD

**Issue by dharezlak** [springdoc/springdoc-openapi#1203]
**Is your feature request related to a problem? Please describe.**
- Currently springdoc works well with REST APIs but support for asynchronous APIs is missing (as in messaging).

**Describe the solution you'd like**
- Tooling such as https://www.asyncapi.com/ could be used to add support for autogenerating documentation for async payloads (e.g. Kafka payloads).

**Describe alternatives you've considered**
- There is already https://github.com/springwolf/springwolf-core but having a single documenting library (which is well supported) would be convenient.

**Comment by bnasslahsen** [comment]
@dharezlak, 

The springdoc-openapi only supports OpenAPI 3.
Please feel free to propose a PR and will be happy to review it.
