### ISSUE TITLE
Pageable as request param not respecting one-indexed-parameters

### ISSUE THREAD

**Issue by dennie170** [springdoc/springdoc-openapi#1204]
When I edit my application properties file and set for example `default-page-size` to 50, this also changes the documentation, as expected. However, when I set `one-indexed-parameters` to true this does not get reflected in the documentation. My docs keep saying `Zero-based page index (0..N)`. 
This is unexpected an might lead to confusion for API consumers

**To Reproduce**
- **What version of spring-boot you are using?** 2.4.4
- **What modules and versions of springdoc-openapi are you using?** springdoc-openapi-ui and springdoc-openapi-data-rest
- **What is the actual and the expected result using OpenAPI Description (yml or json)?**
Actual:
`"description": "Zero-based page index (0..N)",`
Expected:
`"description": "Page index (1..N)",`

As you can see the `size` is updated based on my application properties, but the page still starts on 0
![image](https://user-images.githubusercontent.com/6575697/123652371-86ffbe00-d82c-11eb-9a79-0a7a4f715248.png)

I hope this is enough information. If something's missing please let me know!

**Comment by bnasslahsen** [comment]
@dennie170, 

Your description is is not sufficient.
Please make sure you provide a complete description, with sample code and configuration. Precising, the version of the dependencies you are using.

You have guidance [here](https://github.com/springdoc/springdoc-openapi/blob/master/CONTRIBUTING.adoc) how to report a bug or enhancement.
Please make sure you provide a reproducible minimal project.

This ticket will be closed, and can be reopened if the relevant information are provided.
