### ISSUE TITLE
multiple response schemas for the same status code

### ISSUE THREAD

**Issue by danitutu** [springdoc/springdoc-openapi#1211]
For an endpoint definition, for the same response code I need to have multiple schemas.

I saw that openapi has support for this. Here is an example: 

https://stackoverflow.com/a/48427558/869793
![image](https://user-images.githubusercontent.com/74911256/125072130-d8c50580-e0c2-11eb-9235-f04c5b13a18a.png)

I am thinking about the following usage:

Option 1:
```
ApiResponse(
                        responseCode = "400",
                        description = "...",
                        content = [
                            Content(schema = Schema(implementation = C1::class)),
                            Content(schema = Schema(implementation = C2::class))
                        ],
                    ),
```
Option 2:
```
                    ApiResponse(
                        responseCode = "400",
                        description = "...",
                        content = [Content(schema = Schema(implementation = C1::class))],
                    ),
                    ApiResponse(
                        responseCode = "400",
                        description = "....",
                        content = [Content(schema = Schema(implementation = C2::class))]
                    ),
```

I have tried the previous usages with 1.5.9 but it didn't work.

It looks like it needs a `oneOf` in the schema definition.

**Comment by bnasslahsen** [comment]
@danitutu, 

This is [sample code](https://github.com/springdoc/springdoc-openapi/blob/master/springdoc-openapi-webmvc-core/src/test/java/test/org/springdoc/api/app6/HelloController.java).
