### ISSUE TITLE
v1.5.9 doesn't display Firefox api paths properly

### ISSUE THREAD

**Issue by danitutu** [springdoc/springdoc-openapi#1212]
springdoc-openapi version: 1.5.9

On Firefox 90.0b12 (64-bit) the API paths don't look properly. On Edge 91.0.864.64 it looks as it should.

![image](https://user-images.githubusercontent.com/69974119/125074312-cac4b400-e0c5-11eb-8109-2622e4e79130.png)

**Comment by bnasslahsen** [comment]
@danitutu, 

Not reproducible.
Note that  any display issue, should be reported to the [swagger-ui](https://github.com/swagger-api/swagger-ui/issues) project, not to sprindoc-openapi.
