### ISSUE TITLE
How to apply kotlin coroutine?

### ISSUE THREAD

**Issue by ManHyuk** [springdoc/springdoc-openapi#1213]
I am currently using kotlin + spring webflux and am trying to add springdoc

And using  Webflux's functional endpoint with coroutine 

Is there a way to satisfy the HandlerFunction type while using the suspend keyword (coroutine)?

If not, I wonder if there are plans to apply

Or is there a way to add springdoc inside coRouter?

### using libraray
- org.springdoc:springdoc-openapi-webflux-ui:1.5.9
- org.springdoc:springdoc-openapi-webflux-core:1.5.9
- org.springdoc:springdoc-openapi-kotlin:1.5.9
- org.jetbrains.kotlinx:kotlinx-coroutines-reactor
- org.jetbrains.kotlin:kotlin-reflect

### sample code

```kotlin
// ApiRouter.kt
@Configuration
class ApiRouter(private val apiHandler: ApiHandler) {
    @Bean
    fun openApiRoute(): RouterFunction<ServerResponse> {
        return route()
            .GET("/mono", apiHandler::monoHandler) { ops -> ops.tag("mono") } // success
            .GET("/coroutine", apiHandler::coroutineHandler) { ops -> ops.tag("coroutine") } // error
            .build()
    }
    @Bean
    fun tempRoute() = coRouter {
        "/temp".nest {
            GET("/coroutine", apiHandler::coroutineHandler) // success
        }
    }
}

// ApiHandler.kt
class ApiHandler {
    fun monoHandler(request: ServerRequest): Mono<ServerResponse> {
        return ServerResponse.ok().build()
    }

    suspend fun coroutineHandler(request: ServerRequest): ServerResponse {
        return ServerResponse.ok().buildAndAwait()
    }
}
```

### error message

![image](https://user-images.githubusercontent.com/11765448/125170119-461e8680-e1e8-11eb-880c-31137b1fcb70.png)
> // error message
None of the following functions can be called with the arguments supplied.
GET(String!, HandlerFunction<ServerResponse!>!, Consumer<Builder!>!) defined in org.springdoc.webflux.core.fn.SpringdocRouteBuilder
GET(RequestPredicate!, HandlerFunction<ServerResponse!>!, Consumer<Builder!>!) defined in org.springdoc.webflux.core.fn.SpringdocRouteBuilder

**Comment by bnasslahsen** [comment]
Not reproducible.
Make sure you provide a a Minimal, Reproducible Example - with HelloController that reproduces the problem as precised [here](https://github.com/springdoc/springdoc-openapi/blob/master/CONTRIBUTING.adoc).

This ticket can be reopened, if the relevant information are provided.

**Comment by lockhartja** [comment]
Hey Team...do we have a recommendation on how to make this work with a suspend func...I am seeing the exact same behavior as mentioned above. Is a demo still required to confirm the error?

**Comment by lockhartja** [comment]
@ManHyuk were you able to work around this issue?
