### ISSUE TITLE
Generate OpenAPI v3 document at compile time

### ISSUE THREAD

**Issue by koen-serneels** [springdoc/springdoc-openapi#1214]
At the moment it is possible to generate open API from a running spring boot application using springdoc. OpenApiResource will for example use the application context to find all relevant beans. However, this makes the build process more complex as the application needs to be deployed in order to produce the open api document. Would it be possible to generate the openapi also at at compile time?  This is afaik what the following plugin is doing : https://github.com/KonCheng However, this plugin is not recently updated and still depending on an older Swagger version (not openapi v3 compatible)

**Comment by bnasslahsen** [comment]
@koen-serneels, 

Please do not create duplicates as this point is already explained and answered:  https://github.com/springdoc/springdoc-openapi/issues/739 and https://github.com/springdoc/springdoc-openapi/issues/636

**Comment by koen-serneels** [comment]
> @koen-serneels,
> 
> Please do not create duplicates as this point is already explained and answered: #739 and #636

I was aware of these tickets. However, the answer on the first ticket (_The necessary metadata for the OpenAPI spec are only available on runtime, which explains the choice of generation at runtime._) seems wrong as the repo stated in the body if this ticket is exactly doing that: generating at compile time. The last ticket answers with "_Nothing planned about that._" which is of course an open end as I thought in maybe it can be planned now (backlog anyone?). Anyway, it's clear that there is no motivation in helping out on this
