### ISSUE TITLE
Spring boot forward header strategy set to "framework" replaces servlet context path with proxy prefix path in the swagger config url

### ISSUE THREAD

**Issue by kaus02** [springdoc/springdoc-openapi#1216]
> How is the url generated in case the application is behind the reverse proxy? it does not takes into account the prefix path set by the proxy.

Read the [documentation](https://springdoc.org/index.html#how-can-i-deploy-springdoc-openapi-ui-behind-a-reverse-proxy).

_Originally posted by @bnasslahsen in https://github.com/springdoc/springdoc-openapi/issues/89#issuecomment-879001990_

**Comment by bnasslahsen** [comment]
Please do not create duplicates.

Read the documentation et and [guiding rules before opening any issue](https://github.com/springdoc/springdoc-openapi/blob/master/CONTRIBUTING.adoc).
