### ISSUE TITLE
PathVariable Mixed with MultipartForm has a bug?

### ISSUE THREAD

**Issue by jetadore** [springdoc/springdoc-openapi#1217]
I use Spring Boot 2.4.7

---

- this is the java code

```java
@Data
public class FilePatchFormVO {
    @Pattern(regexp = RegExp.FILE_NAME)
    @Schema(description = "新文件名")
    private String name;
}

    @Operation(summary = "修改信息")
    @PatchMapping(value = "/{id}", consumes = MediaType.MULTIPART_FORM_DATA_VALUE)
    public FileVO patchInfo(@Parameter(description = "文件ID")
                            @PathVariable("id") String id,
                            FilePatchFormVO filePatchFormVO) {
           //...
    }
```

- then  when  use springdoc  1.5.7

  the swagger ui is : 
![1 5 7](https://user-images.githubusercontent.com/20695541/125599963-3d325b97-91f7-4931-a242-5b7e60862041.png)

- and when use spring doc 1.5.8+
the swagger ui  is :

![1 5 8+](https://user-images.githubusercontent.com/20695541/125600061-bc9df939-494c-4999-ac3e-c330fba7bbf2.png)

###  when use 1.5.8+, the swagger ui missed multipartform , and will failed to execute with  "MediaType Not Supported" error!!!

---

now i must downgrade the dep version to 1.5.7 ! 

is this a bug ?

**Comment by jetadore** [comment]
aaaahh ,  additional info :
 when use 1.5.8+, the swagger ui missed multipartform , and will failed to execute with  "MediaType Not Supported" error!!!

**Comment by bnasslahsen** [comment]
add @RequestBody from` io.swagger.v3.oas.annotations.parameters.RequestBody` to your parameter `filePatchFormVO`.
