### ISSUE TITLE
Is there any way to disable all the schemas?

### ISSUE THREAD

**Issue by surajkj** [springdoc/springdoc-openapi#1218]
![image](https://user-images.githubusercontent.com/8409961/125613460-ca1cb632-e0ce-4344-8fa8-739e46c4b510.png)

Is there any way to hide all the DTOs from schema? I don't want to annotate hundreds of class for hiding.

Thanks for the support!

**Comment by wireless81** [comment]
You can set **springdoc.swagger-ui.defaultModelsExpandDepth** to **-1** to hide all of the schemas/models.

See [5.2. swagger-ui properties](https://springdoc.org/#swagger-ui-properties) for more information.

**Comment by bnasslahsen** [comment]
alternatively, you can use `OpenApiCustomiser`, to adapt the openAPI object.
All attributes, can be hidden using this object programmatically.

**Comment by libra-999** [comment]
springdoc.swagger-ui.defaultModelsExpandDepth=-1 , you can use this config in yaml then it will work
