### ISSUE TITLE
POST @ParameterObject on request body not getting all fields

### ISSUE THREAD

**Issue by laffer1** [springdoc/springdoc-openapi#1219]
**Environment**
- Using springdoc-openapi 1.5.9  (and the kotlin extension) 
- spring boot 2.5.2
- kotlin 1.4.32
- java 11

**To Reproduce**
Controller with code like this: 

```
fun search(@ParameterObject @Valid @RequestBody myrequest: MyRequest, @ModelAttribute("myid") myId: String): ResponseEntity<SearchResponse> {
}
```

MyRequest: 

```
data class MyRequest(
val clientKey: String, 
val address: Address?, 
val year: Int? = null, 
val enableFilters: Boolean? = true, 
val filters: Map<String, String>?
) 
```

**Expected behavior**
- All fields should be mapped in a parameter object on a request body for a POST
- Object contains maps as well as string and, Int and Boolean types. Maps should appear in the listing of fields e.g. we should see filters in the example

Unfortunately, I can't copy the real code as it's for a client at work.  This is a simplified test case.

**Comment by bnasslahsen** [comment]
@laffer1, 

Make sure you [Provide a Minimal, Reproducible Example - with HelloController ](https://stackoverflow.com/help/minimal-reproducible-example) that reproduces the problem.
This ticket is being closed, until any relevant information is provided.

**Comment by laffer1** [comment]
```
@RestController("/hello")
class HelloController {

    @PostMapping
    fun search(@ParameterObject @RequestBody request: MyRequest): MyRequest {
        return request
    }

    data class MyRequest(
        val enableFilters: Boolean? = true,      // appears in swagger ui
        val filters: Map<String, String>?        // does not appear
    ) 
}

```

**Comment by bnasslahsen** [comment]
@laffer1, 

This is the expected behavior. https://github.com/springdoc/springdoc-openapi/issues/154

Simply use:
```java
	static {
		SpringDocUtils.getConfig().removeRequestWrapperToIgnore(Map.class);
	}
```

You can see:  [How can i disable ignored types section](https://springdoc.org/#how-can-i-disable-ignored-types).
