### ISSUE TITLE
How to configure swagger-ui

### ISSUE THREAD

**Issue by venaud** [springdoc/springdoc-openapi#122]
Hi,

First thanks for this library.
We moved from Springfox a week ago because some features were missing, and it was without many difficulties!

We still have one issue: how can we configure swagger-ui?

We would like to configure two things to begin with:
1. Order tags & operations alphabeticaly: by default swagger-ui keep the order of generated swagger yaml. And swagger-core cannot keep the same order for the operations generated.
2. Fold all tags

The first point is the most annoying.
Each time we deploy, our users find their routes scrambled.

Springfox allowed to configure that (but the default configurations were good for us)

Because you rely on swagger-ui webjar, it is already packaged, and I cannot find a way to add a configuration file.
And I haven't find a way in your examples.

Is it possible to configure swagger-ui?

If not, is it a feature you would consider?

**Comment by springdoc** [comment]
Hi, 

 You have OpenApiCustomiser Interface that is available. 
 You will need to override the method: customise.
 You have on this method, the full control on the OpenAPI swagger Object, and you will be able to sort the elements as you wish.

**Comment by venaud** [comment]
Thanks for your answer.

I found an example in your code, did you mean something like this?
```
@Bean
public OpenApiCustomiser sortTagsAlphabitecally() {
    return openApi -> openApi.setTags(openApi.getTags()
            .stream()
            .sorted(Comparator.comparing(tag -> StringUtils.stripAccents(tag.getName())))
            .collect(Collectors.toList()));
}
```

This indeed solve the sort issue by controlling the generated swagger file.

But it doesn't allow to control the options of swagger-ui.
(For example for the fact that all tags are extended by default)

**Comment by edgeofoblivion** [comment]
@venaud 
See configuration property docExpansion at https://swagger.io/docs/open-source-tools/swagger-ui/usage/configuration/

You can set this property in your application.yml like so for example:
```yaml
springdoc:
  swagger-ui:  
    doc-expansion: none
```
UI will then open with that configuration, e.g. /swagger-ui/index.html?url=/v3/api-docs&docExpansion=none

**Comment by venaud** [comment]
@edgeofoblivion

Thanks for your input.

I tried it, but it doesn't work.

I put your configuration in my `application.yml`.
I then went to `http://localhost:8080/swagger-ui.html` (I understood that it was the redirection that added the `docExpansion=none` to the url).

But nothing changed.
The url doesn't have the `docExpansion=none` parameter.

How does springdoc pass the configuration to swagger-ui ?

**Comment by edgeofoblivion** [comment]
@venaud Presumably this is what you are interested in?
`springdoc-openapi-ui/src/main/java/org/springdoc/ui/SwaggerWelcome.java`

It's working OK for me here on the following versions:
```properties
springBootVersion=2.2.1.RELEASE
springdocOpenApiVersion=1.2.16
```

Properties for the ui are loaded as per this class once the prefix matches:
`springdoc-openapi-common/src/main/java/org/springdoc/core/SwaggerUiConfigProperties.java`
```java
@Configuration
@ConfigurationProperties(prefix = "springdoc.swagger-ui")
public class SwaggerUiConfigProperties {
...
}
```

**Comment by venaud** [comment]
My bad, I forgot to update my springdocOpenApi version.
I was still on the 1.2.12...

It is a bit tricky to follow the updates of this library, as there is no changelog, and the commit messages are not really helping... :/

But well, your solution is now up and running, thank you!
