### ISSUE TITLE
How to get springdoc groups when disable swagger-ui?

### ISSUE THREAD

**Issue by Bricks-Man** [springdoc/springdoc-openapi#1222]
I just want to use another ui, so I use `springdoc.swagger-ui.enabled=false` to disable swagger-ui.
But I found that the groups url: `/v3/api-docs/swagger-config` is also disabled.I also can visit `/v3/api-docs/{group}`.But how can I get the group list?

**Comment by bnasslahsen** [comment]
Get the beans of type `GroupedOpenApi`.
Then call: `groupedOpenApi.getGroup()`

For example: 	

```java
@Autowired
List<GroupedOpenApi> groupedOpenApiList;

//print all the group names
groupedOpenApiList.forEach(groupedOpenApi -> System.out.println(groupedOpenApi.getGroup()));
```
