### ISSUE TITLE
Question: set ApiResponse description from an Enum

### ISSUE THREAD

**Issue by zappee** [springdoc/springdoc-openapi#1224]
This question is related to #629.

The question there is answered, but the recommended solution is really complex, contains a hardcoded method name, and is related to `io.swagger.v3.oas.models.responses.ApiResponse` class. In the official doc [here](https://springdoc.org/faq.html#how-can-i-customise-the-openapi-object-) there are only examples of how to group, set package scan, etc. but there is no recommendation to customize the Open API doc.

My GET rest endpoint has multiply HTTP response codes:

- 200: ok
- 404: not found

```
@GetMapping(value = "/status/{id}", produces = { MediaType.APPLICATION_JSON_VALUE})
@ApiResponses({
        @ApiResponse(responseCode = "200"),
        @ApiResponse(responseCode = "404", description = "...")
})
public ResponseEntity<StatusResponse> getStatus(@PathVariable(name = "id") String requestId) {
}
```

I store the descriptions (and the HTTP response codes)  in ENUM and this ENUM is used while producing the HTTP response. 

I would like to use the ENUM values to generate the Open API doc. I do not want to copy-paste the descriptions and the HTTP response codes from my ENUM to the annotation.

I would like to have something like this:
```
@ApiResponses({
        @ApiResponse(responseCode = MyStatusEnum.OK.getHttpResponse()),

        @ApiResponse(responseCode = MyStatusEnum.NOT_FOUND.getHttpResponse(),
                      description = MyStatusEnum.NOT_FOUND.getDescription())
})

```

The copy-paste solution is really bad because we duplicate the text and in case of modification it must be modified two different places. The code quality checkers are also complaining about the duplications.

I use this ugly code to configure properly OpenAPI responses:
```
@Override
public Operation customize(Operation operation, HandlerMethod handlerMethod) {
    String methodName = handlerMethod.getMethod().getName();
    Set<Map.Entry<String, ApiResponse>> operations = operation.getResponses().entrySet();
    if ("getStatus".equals(methodName)) {
        updateOpenApiDoc(operations, StatusCode.NOT_FOUND);
    } else if (...) {
    } else ...

    return operation;
}

private void updateOpenApiDoc(Set<Map.Entry<String, ApiResponse>> operations, StatusCode statusCode) {
    for (Map.Entry<String, ApiResponse> entry : operations) {
        if (String.valueOf(statusCode.getHttpStatus()).equals(entry.getKey())) {
            ApiResponse apiResponse = entry.getValue();
            apiResponse.setDescription(statusCode.getMessage());
        }
    }
}
```

Is there any professional, clear way to manage this property?

**Comment by bnasslahsen** [comment]
@zappee, 

You can also define your responses as global response, instead of repeating the response code and description.
Sample code is available here:  https://github.com/springdoc/springdoc-openapi/issues/809
