### ISSUE TITLE
Add option to get the CSRF token from the Local Storage

### ISSUE THREAD

**Issue by esfomeado** [springdoc/springdoc-openapi#1228]
**Is your feature request related to a problem? Please describe.**
Allow to get the CSRF token from the Local Storage and not only from the cookies.

**Describe the solution you'd like**
Add a new configuration to load the CSRF token from the Local Storage.

**Describe alternatives you've considered**
The alternative solution it's to write a custom request interceptor.

**Comment by bnasslahsen** [comment]
@esfomeado, 

Are you willing to propose a PR for this feature ?

**Comment by esfomeado** [comment]
Yeah, I can do this when I have some time.

**Comment by bnasslahsen** [comment]
ok. I am closing this ticket.
You can directly submit your PR and will be glad to review it.
