### ISSUE TITLE
How to describe parameters using a .yaml file 

### ISSUE THREAD

**Issue by jalbissimo** [springdoc/springdoc-openapi#1229]
Hello there! 

I recently started using the springdoc-openapi library and what I want to know is how can I describe parameters based on an .yaml file.
So far I have managed to add a schema to specify the type of a parameter programmatically by adding it in the configuration bean, just like this:
```
@Bean
public OpenAPI customOpenAPI() {
    return new OpenAPI()
        .components(new Components().addSchemas("MyCustomSchema", new MapSchema()
            .addProperties("propA", new NumberSchema())
            .addProperties("propB", new NumberSchema())
            .addProperties("propC", new StringSchema())
        ));
}
```
*example taken from here :https://github.com/springdoc/springdoc-openapi/issues/743

What I want to know is how I can use a schema defined in an .yaml file to specify the type of parameters?

**Comment by bnasslahsen** [comment]
This looks to be something custom. There is nothing about this in OpenAPI spec.
Which means, you can use your own file and load it.
