### ISSUE TITLE
Feign clients that uses SpringMVCContract appears in OpenApi like controllers exposed if spring-boot-starter-actuator is in classpath

### ISSUE THREAD

**Issue by migueltercero** [springdoc/springdoc-openapi#1230]
**Describe the feature**

If you use https://spring.io/projects/spring-cloud-openfeign and define `@FeingClients` with SpringMVCContract, SpringDoc shows this clients in OpenApi. 

The problem is that this clients uses same annotations that RestControllers (@RequestMapping, @GetMapping ...)

**To Reproduce**

- Define @FeignClient

```
@FeignClient("feignclient")
	@RequestMapping(value = "/api/v1/echo")
	public interface EchoClient {

		@GetMapping
		String echo(@RequestParam int size);

}
```

- Call OpenApi endpoint
```
@Test
	 void givenFeignClient_whenGetAppApiDoc_thenDontAppear() {
		given()
		.when()
			.get("/v3/api-docs/app")
		.then().log().all()
			.statusCode(200)
			.body("paths['/api/v1/echo'].get", notNullValue());
	}
```

**Expected behavior**

- This test must be ok:

```
@Test
	 void givenFeignClient_whenGetAppApiDoc_thenDontAppear() {
		given()
		.when()
			.get("/v3/api-docs/app")
		.then().log().all()
			.statusCode(200)
			.body("paths['/api/v1/echo'].get", nullValue());
	}
```

**Solution**

Posibles solutions:

- Have an `annotationsToExclude` and pass `FeignClient.class` to exclude
```
return GroupedOpenApi
				.builder()
					.group(info.getArtifact())
					.pathsToMatch("/api/**")
					.annotationsToExclude(FeignClient.class)
				.build();
```
- Shows only endpoints that have "@RestController" or "@Controller" annotation by default. If beans don´t have this annotation, spring don´t exposes it as controller, and beans that aren´t exposed as controller, dont appear in open api endpoint.
- ...

**Comment by bnasslahsen** [comment]
@migueltercero, 

This is an enhancement request.

You can use `addHiddenRestControllers`, with the name of the rest controller to ignore.
We will see to get it out of the box for the next realse.

```java
static {
		SpringDocUtils.getConfig().addHiddenRestControllers(EchoClient.class)
	}
```

**Comment by bnasslahsen** [comment]
@migueltercero; 

Can you provide a [Minimal, Reproducible Example - with HelloController](https://stackoverflow.com/help/minimal-reproducible-example) that reproduces the problem ?

You can use https://start.spring.io/.

**Comment by migueltercero** [comment]
Hi, I uploaded a sample here:

https://github.com/migueltercero/springdoc-issue

You can reproduce issue/feature if execute `com.github.ma3.controller.HelloControllerTest#givenFeignClient_whenGetAppApiDoc_thenFeignClientShouldNotAppear` test method.

NOTE: This is related with Spring `actuator` starter:

```
<dependency>
   <groupId>org.springframework.boot</groupId>
   <artifactId>spring-boot-starter-actuator</artifactId>
</dependency> 
```

If you remove `actuator` dependency, client don´t appear and OpenApi is generated ok. 

Thank you
