### ISSUE TITLE
Hide Hateoas Links

### ISSUE THREAD

**Issue by esfomeado** [springdoc/springdoc-openapi#1231]
Is there any way to hide the Hateoas links?

**Comment by bnasslahsen** [comment]
@esfomeado, 

Please read the [section](https://github.com/springdoc/springdoc-openapi/blob/master/CONTRIBUTING.adoc) **Using GitHub Issues** before opening issues.

This ticket will be closed, and can be reopened if you provide all the information listed.
You need to describe your context (the title of an issue is not enough)

- What version of spring-boot you are using?
- What modules and versions of springdoc-openapi are you using?
- What are the actual and the expected result using OpenAPI Description (yml or json)?
- Provide a Minimal, Reproducible Example - with HelloController that reproduces the problem
