### ISSUE TITLE
Operation ids for actuator endpoints

### ISSUE THREAD

**Issue by fjakop** [springdoc/springdoc-openapi#1233]
We're generating typescript fetch clients from openapi definition. When we enable actuator to be generated into the openapi.yaml the operation ids are rather unuseable because the're named `handle_14` and so on while the summary looks good. Example below.

    /actuator/health:
      get:
        tags:
          - Actuator
        summary: Actuator web endpoint 'health'
        operationId: handle_14

In consequence the generated typescript methods look like `actuatorApi.handle14()` that is unreadable.

I would expect the operationId to be set to the endpoint name, i.e. in this example

    /actuator/health:
      get:
        tags:
          - Actuator
        summary: Actuator web endpoint 'health'
        operationId: health

which would lead to a method `actuatorApi.health()`.

Used springdoc-openapi version is 1.5.4.

**Comment by bnasslahsen** [comment]
@fjakop, 

Note that `operationIds` using actuator is not unique.
An update will be available with the next release to make them clearer/understandable ...
