### ISSUE TITLE
OAuth2 does not complete authorization_code grant

### ISSUE THREAD

**Issue by tvogel8570** [springdoc/springdoc-openapi#1235]
**Describe the bug**
Using the Authorize link on the OpenAPI ui and after authenticating with an OAuth2 Authorization server, there is no JWT token and all OpenAPI UI calls fail with 401.
When configured as below and verified with a WireShark debugging session, the redirect page receives a code but never submits the code to be exchanged for a full JWT authorization token.

**To Reproduce**
OpenAPI security annotation

	@SecurityScheme(scheme = "custom", type = SecuritySchemeType.OAUTH2, in = SecuritySchemeIn.HEADER, name = "access_token",
			flows = @OAuthFlows(authorizationCode = @OAuthFlow(
					authorizationUrl = "https://login.myauthserver.com/v2/oauth/authorize", 
					tokenUrl = "https://login.myauthserver.com/v2/oauth/token", scopes = {})))
	public class OpenApiConfig {}
	

The OAuth2 configuration for the REST API Resource Server that has the API being documented 

	server:
	   port: 8070
	spring:
	  security:
		oauth2:
		  resourceserver:
			jwt:
			  jwk-set-uri: https://login.myauthserver.com/oauth/jwks

The Authorization server is configured with a redirect URL

	http://localhost:8070/swagger-ui/oauth2-redirect.html

The OAuth2 configuration for a working client  to compare with

	server:
	   port: 8075
	spring:
	  security:
		oauth2:
		  client:
			registration:
			  myauth:
				client-id: ${custom-sso-client}
				client-secret: ${custom-sso-secret}
				authorization-grant-type: authorization_code
				redirect-uri: http://localhost:8075/login/oauth2/code/myauth
			provider:
			  myauth:
				authorization-uri: https://login.myauthserver.com/v2/oauth/authorize
				token-uri: https://login.myauthserver.com/v2/oauth/token
				user-info-uri: https://login.myauthserver.com/oauth/verify       
				user-name-attribute: userName

- Spring-boot 2.5.2 (spring-boot-starter-web, spring-boot-starter-security)
- springdoc-openapi-ui - v1.5.9
- Actual result is the springdoc-openapi receives a code but never requests an authorization token.  

**Expected behavior**
Expected result is that a JWT authorization/authentication token is present in the request

**Comment by bnasslahsen** [comment]
@tvogel8570, 

Please see the sample configuration project here:

- https://github.com/springdoc/springdoc-openapi-demos/tree/master/springdoc-openapi-oauth2

You have an `oauth-authorization-server` and `oauth-resource-server` using `spring-boot-starter-oauth2-resource-server`.
It's all configured and running using Oauth2 authorization Code flow and just ran the test again without any issue.

You run the demo from end to end and adapt it for your case.

**Comment by tvogel8570** [comment]
@bnasslahsen ,
Thank you for the reference to the demo.  Although the test pass when using the embedded authorization server, the external 3rd party authorization server I need to use does not allow login via uid/pwd.  

Please suggest a couple of classes / methods to set a break point that will allow me to trace through the process started when clicking on the Authorize button on the main documentation page.  This will allow me to troubleshoot the specific responses from the 3rd party auth server when the OpenAPI UI goes through the OAuth2 login (request login, receive code, request token, receive token) for an authorization_code grant type.

**Comment by bnasslahsen** [comment]
@tvogel8570, 

All the source code of sprindoc-openapi is available via github.

If you feel you believe you are facing an issue, make sure you provide the necessary data described in the section [Using GitHub Issues](https://github.com/springdoc/springdoc-openapi/blob/master/CONTRIBUTING.adoc).

Note that the UI interactions are handled by [swagger-ui](https://github.com/swagger-api/swagger-ui).
If you feel you are facing any issue in the swagger-ui, feel free to get in touch with the swagger-ui team instead.
