### ISSUE TITLE
Support for customer parameter resolver annotations

### ISSUE THREAD

**Issue by ByteGen** [springdoc/springdoc-openapi#1237]
**Is your feature request related to a problem? Please describe.**

As we are using an self-defined annotation to resolve request parameters in the json body, the openapi tool can not recognize the parameter type correctly. The primitive parameters are showing in the query parameter section, And others are showing in request body section.
So, is it possible to add some customize interfaces to support the recognition of this situation?

**Describe the solution you'd like**

I think there may be two ways to deal with that.
- Add customize support before building operations in the `AbstractRequestService`. Maybe something like the `DelegatingMethodParameterCustomizer`(witch only executes on some conditions). Users can modify the method parameters for further usage.
- Add an `ParameterService` interface, and export `new ParameterInfo` function in the interface (instead of directly `new ParameterInfo`). There would be a default `GenericParameterService`. And users can setup their own `CustomerParameterService`.

**Comment by bnasslahsen** [comment]
@ByteGen, 

Only spring annotations are supported.
Feel free to override the interfaces/classes you have mentioned for your own implementation.
