### ISSUE TITLE
Support for ResponseBodyResultHandler

### ISSUE THREAD

**Issue by lilimapradhan9** [springdoc/springdoc-openapi#1238]
**Is your feature request related to a problem? Please describe.**
- We have a use case in our project where we are modifying the response using ResponseBodyResultHandler and currently springdoc-openapi is not able to process it.
- It shows an error page

**Describe the solution you'd like**
- After removing ResponseBodyResultHandler from the code the api documentation was generated successfully

**Additional context**
- 
<img width="1503" alt="Screenshot 2021-08-04 at 4 45 14 PM" src="https://user-images.githubusercontent.com/24977719/128171865-44430f15-b2b2-4527-8397-92ea658f93ee.png">

**Comment by bnasslahsen** [comment]
@lilimapradhan9, 

Please provide a [Minimal, Reproducible Example - with HelloController ](https://stackoverflow.com/help/minimal-reproducible-example)that reproduces the problem.
