### ISSUE TITLE
The property description in the schema definitions can not show in the openapi document

### ISSUE THREAD

**Issue by fuchengli1024** [springdoc/springdoc-openapi#1240]
**Describe the bug**
The property description in the schema definitions can not show in the openapi document

**To Reproduce**
spring boot :2.3.2.RELEASE
springdoc-openapi :1.5.10
the property descriptions should be displayed in the api doc, so the user can understand the definitions better.

for example in yam file.
      startTime:
        type: string
        description: this is the start of this task

expect : the description of startTime display on the api doc
**Screenshots**

![image](https://user-images.githubusercontent.com/88135102/128868279-bcecc519-1a13-4890-869b-fd044e6adb76.png)

**Comment by bnasslahsen** [comment]
@fuchengli1024, 

Make sure you Provide [a Minimal, Reproducible Example - with HelloController](https://stackoverflow.com/help/minimal-reproducible-example) that reproduces the problem.

This ticket can be reopened, if the relevant information are provided.

**Comment by fuchengli1024** [comment]
Hi ,

The example code is provided. please look into the yml  and I want to display the description in the ui.
[SwaggerSpringDemo-master.zip](https://github.com/springdoc/springdoc-openapi/files/6981224/SwaggerSpringDemo-master.zip)


        title:
          type: string
          example: Oathbringer
          description: this is the description I want to show in the openapi ui

**Comment by bnasslahsen** [comment]
@fuchengli1024, 

Your project is using `openapi-generator-maven-plugin` to generate his your java classes.
The OpenAPI 3 description should be available on the generated classes, which is done by `openapi-generator-maven-plugin`.

You can have deeper analysis to the code generated and ask for support of [openapi-generator-maven-plugin](https://github.com/OpenAPITools/openapi-generator/tree/master/modules/openapi-generator-maven-plugin) instead.

**Comment by fuchengli1024** [comment]
Hi Bnasslagsen,

I removed the openapi-generator-maven-plugin and just use the java code. it is still not have description in the openapi doc.

Please let me know if there has any problem in my model code.

[SwaggerSpringDemo-master.zip](https://github.com/springdoc/springdoc-openapi/files/6986492/SwaggerSpringDemo-master.zip)

**Comment by fuchengli1024** [comment]
I can see the swagger annotation in the code .

    @ApiModelProperty(
        example = "Oathbringer",
        value = "this is the description I want to show in the openapi ui"
    )
    public String getTitle() {
        return this.title;
    }

**Comment by fuchengli1024** [comment]
![image](https://user-images.githubusercontent.com/88135102/129447029-7a91993c-f163-4d6b-b928-e33eb97630f6.png)
please look into the screenshot. What I can see is the issue is on openapi-doc. please let me know where am I worng

Thanks

**Comment by bnasslahsen** [comment]
`ApiModelProperty` is not an OpenApi 3 annotation...
