### ISSUE TITLE
Please get rid of redirection to /swagger-ui/index.html

### ISSUE THREAD

**Issue by bvn13** [springdoc/springdoc-openapi#1242]
I implemented a documentation of my project with SpringDoc (many thanks!).
But my application is deployed into kubernetes using ingress - this fact leads to the application is running behind subURL: https://api-qa.company.com/appname/.
In my case /appname/ is not a context-path of servlet - it is a reverse proxy (I guess).
I set `springdoc.swagger-uipath=/swagger` and `springdoc.api-docs.path=/api-docs`
Now when I open https://api-qa.company.com/appname/swagger it redirects me to https://api-qa.company.com/swagger-ui/index.html?configUrl=/api-docs/swagger-config
And.... it is not proxied into my application!
How to fix this behavior? How not to redirect outside of proxied subURL `/appname`?

**Comment by darioseidl** [comment]
I've only just started using springdoc myself, so I'm not sure, but this section in the docs might be of interest to you: [How can I deploy springdoc-openapi-ui behind a reverse proxy](https://springdoc.org/index.html#how-can-i-deploy-springdoc-openapi-ui-behind-a-reverse-proxy)

**Comment by bnasslahsen** [comment]
@bvn13, 

There are no plan to remove the redirection. springdoc, just works fine inside and outside kubernetes. 
Just review your configuration the section described by @darioseidl.

If you believe you can bring added value, please feel free to propose a PR!

**Comment by jcmillett** [comment]
The redirect doesn't work well when you have a k8s cluster that uses an ingress that doesn't support adding request headers. For example, we're using a k8s cluster with AWS app mesh, which doesn't appear to support adding the `X-Forwarded-Prefix` header.
