### ISSUE TITLE
NPE when @Autowire @ConfigurationProperties property setting up 

### ISSUE THREAD

**Issue by marcellodesales** [springdoc/springdoc-openapi#1245]
**Describe the bug**

* All the properties of the API are loaded from a ConfigurationProperties class, loading from the application.yaml
* The configuration is not loading because of a NPE because the properties are not loaded.
  * Might be the order in which the components are loaded.

```java
  @Autowired
  private AuthServiceProperties properties;

  public OpenAPI springShopOpenAPI() {
    return new OpenAPI()
            .info(new Info().title(properties.getInfoTitle())
                    .description(properties.getDescription())
                    .version(properties.getApiVersion())
                    .license(new License().name(properties.getLicenseName()).url(properties.getLicenseUrl())))
                    .externalDocs(new ExternalDocumentation()
                      .description(properties.getWikiDescription())
                      .url(properties.getWikiUrl())
                    );
  }
```

**To Reproduce**

* SpringBoot 2.3.x

**Expected behavior**

* Should work

**Comment by bnasslahsen** [comment]
@marcellodesales,

Please review your code and read the [contribution guide](https://github.com/springdoc/springdoc-openapi/blob/master/CONTRIBUTING.adoc) before opening this kind of issues.

If you believe you are facing a bug, make sure you [Provide a Minimal, Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example) - with HelloController that reproduces the problem.
