### ISSUE TITLE
@DirtiesContext in one test affecting Spring Data REST Swagger definition in another

### ISSUE THREAD

**Issue by mjustin** [springdoc/springdoc-openapi#1246]
## Describe the bug
I have an application with a test that's verifying the Swagger endpoint provided by SpringDoc OpenAPI, mainly to ensure no accidental changes are made to the exposed Swagger documentation.  I recently discovered a bug that occurs in a very specific scenario involving this Swagger test plus two other `@SpringBootTest` tests, where the tree tests have very specific configurations and are run in a particular order.  When the bug is triggered, the Swagger endpoint test is missing some details about the Spring Data REST endpoints.  It took a bit of doing, but I have narrowed down the scenario that triggers this bug.

## To Reproduce
1. Given three tests with `@SpringBootTest` (details below) — `Test1`, `Test2`, and `Test3` — which are run in that order by the Gradle build.  `Test1` & `Test3` have `@AutoConfigureMockMvc`, `Test2` has `@DirtiesContext`, and `Test3` retrieves the Swagger details from `/v3/api-docs`
2. When running `Test3` by itself, `Test3` will pass with expected Swagger output.
3. When running the tests in this order: `Test1`, `Test2`, `Test3` — `Test3` will be missing some expected Swagger elements.  Missing will be the objects at `components.schemas.PageMetadata`, `components.schemas.PagedModelEntityModelItem`, and the child objects of `paths."/items".get.200.content` (`"application/hal+json"`, `"application/x-spring-data-compact+json"`, `"text/uri-list"`), .
4. When running only one of `Test1` or `Test2`, followed by `Test3` — `Test3` will pass with expected Swagger output.
5. When running the tests in this order: `Test2`, `Test1`, `Test3` — `Test3` will pass with expected Swagger output.

### Files
**`build.gradle`

```groovy
plugins {
    id 'org.springframework.boot' version '2.5.3'
    id 'io.spring.dependency-management' version '1.0.11.RELEASE'
    id 'java'
}

sourceCompatibility = '11'

repositories {
    mavenCentral()
}

dependencies {
    runtimeOnly 'com.h2database:h2'
    implementation 'org.springdoc:springdoc-openapi-data-rest:1.5.10'
    implementation 'org.springdoc:springdoc-openapi-webmvc-core:1.5.10'
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    implementation 'org.springframework.boot:spring-boot-starter-data-rest'
    implementation 'org.springframework.boot:spring-boot-starter-web'

// Using the 5.8.0 version of JUnit to ensure specific test execution order
    testImplementation 'org.junit.jupiter:junit-jupiter:5.8.0-M1'
    testImplementation 'org.junit.jupiter:junit-jupiter-api:5.8.0-M1'
    testImplementation 'org.junit.jupiter:junit-jupiter-engine:5.8.0-M1'
    testImplementation 'org.junit.jupiter:junit-jupiter-params:5.8.0-M1'

    testImplementation 'org.springframework.boot:spring-boot-starter-test'
}

test {
    useJUnitPlatform()

    systemProperty('junit.jupiter.testclass.order.default', 'org.junit.jupiter.api.ClassOrderer$OrderAnnotation')

// Output the test order to manually verify that tests are running in the expected order
    beforeTest { TestDescriptor descriptor ->
        logger.lifecycle("$descriptor.className#$descriptor.name")
    }
}
```

```java
package com.example.issue;

import javax.persistence.Entity;
import javax.persistence.Id;

@Entity
public class Item {
    @Id
    private Integer id;

    private String value;
}
```

```java
package com.example.issue;

import org.springframework.data.repository.PagingAndSortingRepository;
import org.springframework.stereotype.Repository;

@Repository
public interface ItemRepository extends PagingAndSortingRepository<Item, Integer> {
}
```

```java
package com.example.issue;

import org.junit.jupiter.api.Order;
import org.junit.jupiter.api.Test;
import org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureMockMvc;
import org.springframework.boot.test.context.SpringBootTest;

@SpringBootTest
@AutoConfigureMockMvc
@Order(1)
public class Test1 {
    @Test
    public void test() {
    }
}

```

```java
package com.example.issue;

import org.junit.jupiter.api.Order;
import org.junit.jupiter.api.Test;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.annotation.DirtiesContext;

@SpringBootTest
@DirtiesContext
@Order(2)
public class Test2 {
    @Test
    public void test() {
    }
}
```

```java
package com.example.issue;

import org.junit.jupiter.api.Order;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureMockMvc;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.web.servlet.MockMvc;

import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.get;
import static org.springframework.test.web.servlet.result.MockMvcResultHandlers.print;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.content;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.status;

@SpringBootTest
@AutoConfigureMockMvc
@Order(3)
public class Test3 {
    @Autowired
    private MockMvc mockMvc;

    @Test
    public void swagger() throws Exception {
        mockMvc.perform(get("/v3/api-docs"))
                .andDo(print())
                .andExpect(status().isOk())
                .andExpect(content().json("{\"components\": {\"schemas\": {\"PagedModelEntityModelItem\": {}}}}"));
    }
}
```

### Missing data

The following diff shows the missing portions of the JSON output:

```diff
--- expected.json
+++ actual.json
@@ -58,21 +58,6 @@
           "200": {
             "description": "OK",
             "content": {
-              "application/hal+json": {
-                "schema": {
-                  "$ref": "#/components/schemas/PagedModelEntityModelItem"
-                }
-              },
-              "application/x-spring-data-compact+json": {
-                "schema": {
-                  "$ref": "#/components/schemas/PagedModelEntityModelItem"
-                }
-              },
-              "text/uri-list": {
-                "schema": {
-                  "type": "string"
-                }
-              }
             }
           }
         }
@@ -401,49 +386,6 @@
           }
         }
       },
-      "PageMetadata": {
-        "type": "object",
-        "properties": {
-          "size": {
-            "type": "integer",
-            "format": "int64"
-          },
-          "totalElements": {
-            "type": "integer",
-            "format": "int64"
-          },
-          "totalPages": {
-            "type": "integer",
-            "format": "int64"
-          },
-          "number": {
-            "type": "integer",
-            "format": "int64"
-          }
-        }
-      },
-      "PagedModelEntityModelItem": {
-        "type": "object",
-        "properties": {
-          "_embedded": {
-            "type": "object",
-            "properties": {
-              "items": {
-                "type": "array",
-                "items": {
-                  "$ref": "#/components/schemas/EntityModelItem"
-                }
-              }
-            }
-          },
-          "_links": {
-            "$ref": "#/components/schemas/Links"
-          },
-          "page": {
-            "$ref": "#/components/schemas/PageMetadata"
-          }
-        }
-      },
       "ItemRequestBody": {
         "type": "object"
       },
```

## Expected behavior
- The generated Swagger should not be affected by this test ordering, and should always return the same expected JSON regardless of the order in which the given tests run.

## Additional context
I am using the not yet released version 5.8.0-M1 of JUnit in this example in order to be able to declare the order of the tests.  This issue occurs with the released version of JUnit Jupiter, but the test ordering is not guaranteed or in a particularly predictable order, so using that for this bug report would make the issue reproduction more difficult.

Forcing a new Spring context at the beginning of `Test3` by annotating it with `@DirtiesContext(classMode = DirtiesContext.ClassMode.BEFORE_CLASS)` will cause the test to pass.

Adding `@AutoConfigureMockMvc` to `Test2` or removing it from `Test1` will cause `Test3` to pass.  I think the critical piece here is that `Test1` & `Test3` have identical configuration so that the Spring test runner uses the same Spring context for them, but `Test2` must be configured differently.  Another way to confirm this is to add `@AutoConfigureMockMvc` as well as something that would cause it to differ, for instance `@TestPropertySource(properties = "com.example.fake=true")`.  In this case, `Test3` will still fail, since `Test2` still requires its own Spring Boot instance

Accessing the Swagger endpoint in `Test1` through the autowired `MockMvc` will cause `Test3` to pass.

**Comment by bnasslahsen** [comment]
@mjustin, 

This is not a bug.
Use `@DirtiesContext(classMode = DirtiesContext.ClassMode.BEFORE_CLASS)`, on your springdoc test, to launch your test with a clean spring context.

**Comment by mjustin** [comment]
> This is not a bug.

@bnasslahsen Is this expected behavior of this library that it could be affected by prior tests this way?

**Comment by bnasslahsen** [comment]
No. It all depends on how the test is written.
You can see the project tests for samples...
