### ISSUE TITLE
swagger-ui.html returns 404 when large resource files are present

### ISSUE THREAD

**Issue by AnthonyNicholas** [springdoc/springdoc-openapi#1249]
**Describe the bug**
- SpringDoc swagger-ui.html returns 404 / Whitelabel Error Page when large resource files are present (eg 7 files of ~380Mb each).  This is occuring after building and running the JAR file.  The endpoint works fine when the project is run directly from Intellij.

The logs show:

```
19:30:49.012 [http-nio-8080-exec-2] INFO  o.s.web.servlet.DispatcherServlet - Completed initialization in 14 ms
19:30:49.023 [http-nio-8080-exec-2] TRACE o.s.web.servlet.DispatcherServlet - GET "/swagger-ui.html", parameters={}, headers={masked} in DispatcherServlet 'dispatcherServlet'
19:30:49.026 [http-nio-8080-exec-2] TRACE o.s.w.s.m.m.a.RequestMappingHandlerMapping - Mapped to org.springdoc.webmvc.ui.SwaggerWelcomeWebMvc#redirectToUi(HttpServletRequest)
19:30:49.036 [http-nio-8080-exec-2] TRACE o.s.web.method.HandlerMethod - Arguments: [org.apache.catalina.connector.RequestFacade@5e68b13]
19:30:49.064 [http-nio-8080-exec-2] DEBUG o.s.w.s.m.m.a.HttpEntityMethodProcessor - Using 'application/json;q=0.8', given [text/html, application/xhtml+xml, image/avif, image/webp, image/apng, application/xml;q=0.9, application/signed-exchange;v=b3;q=0.9, */*;q=0.8] and supported [application/json, application/*+json, application/json, application/*+json]
19:30:49.064 [http-nio-8080-exec-2] DEBUG o.s.w.s.m.m.a.HttpEntityMethodProcessor - Nothing to write: null body
19:30:49.065 [http-nio-8080-exec-2] TRACE o.s.w.s.m.m.a.RequestMappingHandlerAdapter - Applying default cacheSeconds=-1
19:30:49.065 [http-nio-8080-exec-2] TRACE o.s.web.servlet.DispatcherServlet - No view rendering, null ModelAndView returned.
19:30:49.065 [http-nio-8080-exec-2] DEBUG o.s.web.servlet.DispatcherServlet - Completed 302 FOUND, headers={masked}
19:30:49.071 [http-nio-8080-exec-3] TRACE o.s.web.servlet.DispatcherServlet - GET "/swagger-ui/index.html?configUrl=/v3/api-docs/swagger-config", parameters={masked}, headers={masked} in DispatcherServlet 'dispatcherServlet'
19:30:49.073 [http-nio-8080-exec-3] TRACE o.s.w.s.h.SimpleUrlHandlerMapping - Matching patterns [/swagger-ui*/**, /**]
19:30:49.073 [http-nio-8080-exec-3] TRACE o.s.w.s.h.SimpleUrlHandlerMapping - Mapped to HandlerExecutionChain with [ResourceHttpRequestHandler [Classpath [META-INF/resources/webjars/]]] and 3 interceptors
19:30:49.074 [http-nio-8080-exec-3] DEBUG o.s.w.s.r.ResourceHttpRequestHandler - Resource not found
19:30:49.074 [http-nio-8080-exec-3] TRACE o.s.web.servlet.DispatcherServlet - No view rendering, null ModelAndView returned.
19:30:49.074 [http-nio-8080-exec-3] DEBUG o.s.web.servlet.DispatcherServlet - Completed 404 NOT_FOUND, headers={masked}
```

**To Reproduce**

1. Clone https://github.com/springdoc/springdoc-openapi-demos
2. Create 7 large resource files:
`head -c 400000000 /dev/urandom > BigTestFile1.bin`
`head -c 400000000 /dev/urandom > BigTestFile2.bin`
`head -c 400000000 /dev/urandom > BigTestFile3.bin`
`head -c 400000000 /dev/urandom > BigTestFile4.bin`
`head -c 400000000 /dev/urandom > BigTestFile5.bin`
`head -c 400000000 /dev/urandom > BigTestFile6.bin`
`head -c 400000000 /dev/urandom > BigTestFile7.bin` 
3. Create a folder called `LargeFiles` in springdoc-openapi-book-service src/main/java/resources and place all 7 TestFiles in that folder.
4. Build the jar `mvn clean package` 
5. Run the jar `java -jar ./target/springdoc-openapi-book-service-3.1.6-SNAPSHOT.jar`
6. Navigate to [http:/0.0.0.0:8080/swagger-ui.html](url).

**Expected behavior**
- Should see the swagger-ui page load showing book service resources.

**Additional context**
One of our APIs requires the use of large binary resource files.  Springdoc is working aok for all the others.  It is only failing where these large files are involved.  I am able to replicate the issue in your own demo environment as detailed above.

**Comment by bnasslahsen** [comment]
@AnthonyNicholas, 

First, the jar size where this limitation occurs is about `2.37 GB` which is an uncommon case.
Note that **it is working with a jar of `2.04 GB`** (which is also uncommon)

Second, the limitation is not related to springdoc-openapi itself.  If you choose any spring-boot-web application with `webjars-locator` with this context, you should be able to reproduce this issue / limitation.

We will not go for further analysis as the root cause is not related to springdoc-openapi.
There might be a setting in [webjars-locator](https://github.com/webjars/webjars-locator) to exceed this limit and the `webjars-locator,` team will better help you on that and provide a more precise answer.

**As workaround**

For the sample you gave, using `v1.5.10` of springdoc-openapi you have two solutions:

1. Use:  `springdoc.enable-native-image-support=true`, which will enable springdoc-openapi to add the version automatically.
2. Without any additional property, navigate directly to the url: [http://localhost:8080/webjars/swagger-ui/3.51.1/index.html?configUrl=/v3/api-docs/swagger-config](url)

**Comment by AnthonyNicholas** [comment]
Hi there @bnasslahsen - thanks v much for the quick response!  Is there a workaround for `v1.4.8`?

**Comment by bnasslahsen** [comment]
For v1.4.8, 

**Workaround 2)**

- Without any additional property, navigate directly to the url: http://localhost:8080/webjars/swagger-ui/3.34.0/index.html?configUrl=/v3/api-docs/swagger-config

**Comment by AnthonyNicholas** [comment]
The workaround fo v1.4.8 didn't work in my project but i have been able to update to `1.5.10`.  Thanks v much for your help!
