### ISSUE TITLE
How does this work with Spring Data Rest ?

### ISSUE THREAD

**Issue by SamD** [springdoc/springdoc-openapi#125]
Not seeing any related documentation and it doesn't discover anything with a Spring Data Rest project

**Comment by springdoc** [comment]
Documentation is available on the official page: https://springdoc.github.io/springdoc-openapi-demos/
Spring Data Rest is not a priority. It will be supported on a future release.

**Comment by SamD** [comment]
What ??

> Spring Data Rest is not a priority

Given how Spring has been pitching this as a more viable alternative to Spring MVC I'm not sure how this is the case

**Comment by Kjens93** [comment]
@springdoc We would really appreciate it if this issue could be re-opened and treated as a feature request. Totally understand that it may not be a priority for your team, but it is a priority for us. Lack of spring-data-rest support is the only thing my company from switching from Springfox to Springdoc. We really love Springdoc and we are super sick of the lack of maintenance with Springfox, but without this feature we will not be able to switch. I tried to make a PR adding this functionality into Springdoc, but I wasn't able to get it working on my own. Someone who is more familiar with the Springdoc codebase will probably have to assist on this.
