### ISSUE TITLE
GET request doesn't work with a request body

### ISSUE THREAD

**Issue by tamanna2702** [springdoc/springdoc-openapi#1250]
**Describe the bug**
- I am using springdoc-openapi version 1.5.9 and have a GET method in my controller with a request body. The endpoint works completly fine with postman but with Swagger UI, it gives 'TypeError : Failed to execute fetch on Window.Request with GET/HEAD method cannot have body'.

**Expected behavior**
- GET with request body should be allowed
- The PR to support this expectation : https://github.com/OAI/OpenAPI-Specification/pull/2117

**Comment by bnasslahsen** [comment]
@tamanna2702, 

This is not handled in springdoc-openpi code, but in the swagger-ui code.
This is the related thread: https://github.com/swagger-api/swagger-ui/issues/5388
