### ISSUE TITLE
Spring Swagger 3 Response Body Model information is not displayed

### ISSUE THREAD

**Issue by kimchanjung** [springdoc/springdoc-openapi#1251]
**Describe the bug**  

I am using springdoc-openapi-webflux-ui  in spring webflux
The model information of the request body is not displayed in swagger-ui

<img width="481" alt="스크린샷 2021-08-27 오후 5 57 16" src="https://user-images.githubusercontent.com/31494790/131102654-67b1eb97-0543-4f5a-922c-4bfb696d0416.png">

**class information**

<img width="470" alt="스크린샷 2021-08-27 오후 5 57 45" src="https://user-images.githubusercontent.com/31494790/131102814-aca7dbdf-a886-4533-9166-160f514b24c1.png">

**controller information**

<img width="538" alt="스크린샷 2021-08-27 오후 5 58 18" src="https://user-images.githubusercontent.com/31494790/131102877-9cffe8f4-c6d8-4fbc-bd98-1edc2daa1c05.png">

**api-docs information**

Body information is displayed as requestBody property item.
<img width="637" alt="스크린샷 2021-08-27 오후 6 09 19" src="https://user-images.githubusercontent.com/31494790/131103167-da08baf2-4771-4099-8a6e-cd1f87c72e10.png">

And I googled it

https://stackoverflow.com/questions/64645528/java-spring-boot-openapi-3-how-to-add-description-for-requestbody

I tried various methods such as @Schema, @RequestBody, etc., but the model information was not output.

**To Reproduce**

spring-boot - v2.4.9
java - v11
org.springdoc:springdoc-openapi-webflux-ui:1.5.10

**Expected behavior**
However, the model information should be output like this

When swagger v1, v2 api-docs is linked with swagger ui 3, model information is output.

However, the request body of the controller of my original project using swagger 3 does not display the model information correctly.

<img width="708" alt="스크린샷 2021-08-27 오후 5 57 03" src="https://user-images.githubusercontent.com/31494790/131103015-c2671b5f-debb-44cb-a111-11155c8e1ea7.png">

api-docs information
The other one is included in the parameters section. (swagger oldest version api-docs)
<img width="713" alt="스크린샷 2021-08-27 오후 6 10 50" src="https://user-images.githubusercontent.com/31494790/131103346-381cbc19-7b9c-4f19-82cb-a53e076857e6.png">

Rather, if you link api-docs v1, v2 with springdoc-openapi, the model information of the request body is displayed well.

But the model info in the controller request body of my local springboot project using springdoc-openapi is not covered

The reason seems to be the difference in the api-docs property item.

**Comment by bnasslahsen** [comment]
@kimchanjung, 

Your description is not clear.
See [The contribution guide ](https://github.com/springdoc/springdoc-openapi/blob/master/CONTRIBUTING.adoc)for guidance. Make sure you provide a :
- The actual and the expected result using OpenAPI Description (yml or json)?
- A Minimal, Reproducible Example - with HelloController that reproduces the problem

**Comment by kimchanjung** [comment]
Thank you for answer

Let's see more guides
