### ISSUE TITLE
using old authenticated user after user logs out and a different user logs in 

### ISSUE THREAD

**Issue by jmoraleda** [springdoc/springdoc-openapi#1254]
### Background

We require authentication to access the REST API"s themselves. This is working fine. 

We also require an authenticated user to access API documentation and swagger-ui in the browser: When going to the `/docs` endpoint in the browser for the first time (which is the end point we have configured for swagger-ui), the default spring boot login form appears and, after a correct authentication, the API"s are shown in swagger-ui, and they can be tested using the credentials of the user that just logged in in the login form. All this is as expected and working fine.

### Describe the bug

The problem occurs if in the browser (reproducible firefox and chrome) we manually go to the `/logout` endpoint. This appears to work fine and the `login` form is displayed again and one will not be able to refresh the swagger-ui  or test any API in any tab will until a user correctly authenticates, after which the documentation at `/docs` is shown again. This all appears to work as intended. But then, when submitting a test request from swagger-ui to the rest api, **the credentials that are sent are for the user that originally authenticated in the browser before logout instead of the newly authenticated user.**

### Configuration

This is how we configure the requirement of authentication to see the documentation:

```
  @Configuration
  @ConditionalOnProperty(name = "springdoc.swagger-ui.enabled", havingValue = "true")
  @Order(1) // we test this first
  public static class WebAppsWebSecurityConfigurationAdapter extends WebSecurityConfigurerAdapter {

    private static final String[] BROWSER = {
        "/docs/**", // entry point for swagger documentation
        "/swagger-ui/**",
        "/api-docs/**"
    };

    @Override
    protected void configure(HttpSecurity http) throws Exception {
      http.requestMatchers()
              .antMatchers(BROWSER).antMatchers("/logout").antMatchers("/login")
              .and()
          .authorizeRequests()
              .antMatchers(BROWSER).authenticated()
              .and()
          .formLogin().defaultSuccessUrl("/docs")
              .and()
          .logout();
    }
  }
```

and this is how we configure the authentication of the actual API's:

```
    @Override
    protected void configure(HttpSecurity http) throws Exception {
      http.authorizeRequests()
             .antMatchers(AUTHENTICATED).authenticated()
             .anyRequest().denyAll()
             .and()
          .httpBasic()
             .realmName("OurRealm")
    }
```

We use maven and these are the relevant versions:

**spring-boot** 

```
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-starter-parent</artifactId>
    <version>2.5.4</version>
```

**springdoc-openapi**
```
        <groupId>org.springdoc</groupId>
        <artifactId>springdoc-openapi-ui</artifactId>
        <version>1.5.10</version>

```

**swagger parser**
```
        <groupId>io.swagger.parser.v3</groupId>
        <artifactId>swagger-parser-core</artifactId>
        <version>2.0.27</version>
```

**Expected behavior**
After log out, the credentials for the former user should be forgotten and never used again and the credentials for the newly logged in user should be used.

**Comment by bnasslahsen** [comment]
@jmoraleda, 


Make sure you Provide [a Minimal, Reproducible Example - with HelloController](https://stackoverflow.com/help/minimal-reproducible-example) that reproduces the problem.

This ticket can be reopened, if the relevant information are provided.

**Comment by jmoraleda** [comment]
@bnasslahsen Thank you. I just created a fully working example to reproduce the bug at https://github.com/jmoraleda/boot-login-bug

To reproduce, after building and running the server:

1. Go in your browser to `localhost:8081/docs`
2. Log in as `user1` -> `user1Pass`
3. Try `whoami` method in the controller. It will print `you are logged in as user1`
4. Go in your browser to `localhost:8081/logout`
5. 2. Log in as `user2` -> `user2Pass`
6. Try `whoami` method in the controller. It will print `you are logged in as user1`, which is incorrect, as user1 logged out.

**Comment by bnasslahsen** [comment]
@jmoraleda, 

This has nothing to do with springdoc. It's related to your browser cache (cookies).
Simply, use the same test using the url http://localhost:8080/whoami.

**Comment by jmoraleda** [comment]
Thank you. I can reproduce what you say and agree that this means this is  not a bug in springdoc. 

I assume this is not a bug in Spring, since it is being widely used and this would have been noticed much earlier. But then I would appreciate if someone could clarify for me what does the default `logout` endpoint accomplish. I feel it should clear cookies and all state and prevent a previous authentication from succeeding, which evidently not the case.
