### ISSUE TITLE
Server addresses are updated even if they were provided

### ISSUE THREAD

**Issue by dmittriy13** [springdoc/springdoc-openapi#1255]
**Describe the bug**
Server addresses are updated if they were provided through the customizer.
I have a customizer through which I set the server addresses for each group, but when I get the openApi specification from the cache, the servers are updated to the default. This is because the condition for the serversPresent flag to be set (see [link](https://github.com/springdoc/springdoc-openapi/blob/4a1221f372e174954abbf99faf819b14b4526c09/springdoc-openapi-common/src/main/java/org/springdoc/api/AbstractOpenApiResource.java#L290)) is located before the customizer invocation (see [link](https://github.com/springdoc/springdoc-openapi/blob/4a1221f372e174954abbf99faf819b14b4526c09/springdoc-openapi-common/src/main/java/org/springdoc/api/AbstractOpenApiResource.java#L298)).

I propose to postpone the condition for checking the availability of server addresses after calling the customizer

**Comment by bnasslahsen** [comment]
@dmittriy13, 

Please read the contribution guide for [opening issues](https://github.com/springdoc/springdoc-openapi/blob/master/CONTRIBUTING.adoc).

This ticket will be closed, and can be reopened if the relevant information are provided.
