### ISSUE TITLE
Array of strings shown with [ ... ] in Schema view but not Example Value view

### ISSUE THREAD

**Issue by TimMillerDyck** [springdoc/springdoc-openapi#1257]
Hello, one of our API users reported this issue. I tested with SpringDoc 1.5.10.

We have a parameter "recipientList" of e-mail To: addresses that is an array of Strings (one string per address).

In Schema view, one can see that the parameter is an array:

Collapsed view:
recipientList*	[...]

Expanded view:
recipientList*	[
maxItems: 20
minItems: 1
example: fheette@myorg.com
Array of recipient destination addresses
string
example: fheette@myorg.com
Array of recipient destination addresses
]

However, in Example Value view, the square brackets are omitted, making the parameter appear to be a single string.

{
  ...
  "recipientList": "fheette@myorg.com",
  ...
}

Expected output:

{
  ...
  "recipientList": ["fheette@myorg.com"],
  ...
}

Thank you for this very useful library.

-Tim Miller Dyck

**Comment by bnasslahsen** [comment]
This is not related to openAPI document.
if you are having UI, presentation issues, report them to the swagger-ui directly.

**Comment by TimMillerDyck** [comment]
Thank you for the forward. I had not realized that was a separate project.
