### ISSUE TITLE
The authorize information disappear in UI when we change definition page

### ISSUE THREAD

**Issue by kbenhdech** [springdoc/springdoc-openapi#1259]
Hello,

**Description**

With versions 1.5.6 to 1.5.10, It seems to have a regression with authentication in IHM.
The token is not persisted when we change the group/definition page

I looked in the Issues and the release note but I couldn't find anything.

It's a bug or the configuration has changed for keep this behavior ?

**To Reproduce**

- clicking on the 'Authorize' button, the popup appear
- enter the token
- click on the authorize button then on the close button
- select an other definition page
- click on the authorize button -> token not here anymore

**Comment by bnasslahsen** [comment]
Your are not having issue with the generated OpenAPI definition.
Feel free to search on the [swagger-ui ](https://github.com/swagger-api/swagger-ui)project instead.
