### ISSUE TITLE
Server set through OpenApiCustomiser changes after first request

### ISSUE THREAD

**Issue by SKrutko** [springdoc/springdoc-openapi#1260]
I am setting custom server:

```    
@Bean
    public GroupedOpenApi api() {
        Server server = new Server();
        server.setUrl(myUrl);
        return GroupedOpenApi.builder()
                .addOpenApiCustomiser(openApi -> {
                        openApi.setServers(List.of(server));
                })
                .build();
    }
```

First request to /api-docs returns section "servers" containing myUrl. But second request and all following requests return generated by default URL.

**To Reproduce**
- spring-boot  2.5.3
- springdoc-openapi 1.5.8/1.5.9/1.5.10 (1.5.7 works fine)

**Expected behavior**
- Each request to /api-docs returns the same section "servers" that contains myUrl

**Actual behavior**
- First request to /api-docs returns section "servers" that contains myUrl, next request returns URL generated by default.

**Comment by bnasslahsen** [comment]
@SKrutko, 

same as #1188.
You can test using the [latest available snapshot v1.5.11-SNAPHOT](https://springdoc.org/#how-can-i-use-the-last-springdoc-openapi-snapshot).
