### ISSUE TITLE
Provide Tests which actually use org.springdoc.kotlin.SpringdocRouterFunctionDsl

### ISSUE THREAD

**Issue by snv** [springdoc/springdoc-openapi#1261]
I found the docRouter function and the DSL unintuitive to use (in contrast to the normal router-functions -- I will open seperate issues regarding the usage). 
So i was looking to find running examples in the tests.

Surprisingly there are none, all the tests only use the RequestMapping-Annotation.

Which means org.springdoc.kotlin.SpringdocRouterFunctionDsl is basically untestet, so i'm not surprised that the example mentioned therein does not work.

**Comment by bnasslahsen** [comment]
@snv, 

`SpringdocRouterFunctionDsl`, will be removed...

**Comment by snv** [comment]
Thanks for the pointers to the relevant examples, but i was looking for examples specifically using Functional Endpoints with kotlin. 
Kotlins ability to define & use nicer DSLs makes all the difference, IMO: With the kotlin DSL i prefer Functional Endpoints, but with the java syntax the Annotated Endpoints are the more readable variant.

It's a bit sad to see that the DSL will be removed rather than enhanced.

**Comment by snv** [comment]
Since the `SpringdocRouterFunctionDsl` gets removed, what is the recommended way to use router functions with kotlin instead?

I do hope for not having to use `@RouterOperation`

**Comment by bnasslahsen** [comment]
@snv, 

see the samples...
