### ISSUE TITLE
Issue with @Hidden When Using @JsonTypeInfo / @JsonSubTypes

### ISSUE THREAD

**Issue by ssmoss** [springdoc/springdoc-openapi#1269]
**Describe the bug**

Both the `@Schema(hidden = true)` and `@Hidden` annotation seem to not be working as expected. Using `@Schema(readOnly = true, writeOnly = true)` does but both the `readOnly` and `writeOnly` fields are depreciated.

**To Reproduce**

`spring-boot` version 2.4.5
`springdoc-openapi` version 1.5.10

```java
@JsonTypeInfo(use=JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.EXISTING_PROPERTY, property="object-type")
@JsonSubTypes({
    @JsonSubTypes.Type(value = XXX.class, name = "xxx"),
    @JsonSubTypes.Type(value = YYY.class, name = "yyy"),
})
@JsonPropertyOrder(alphabetic = true)
public abstract class Base {
    @Schema(hidden = true)
    @JsonProperty("object-type")
    private String objectType;

    ...
}

@JsonTypeInfo(use=JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.EXISTING_PROPERTY, property="object-type", defaultImpl = XXX.class)
@JsonTypeName("xxx")
public class XXX extends Base {
    ...
}

@Tag(name = "xxx")
@RequestMapping(
    path     = "/v1/xxx
)
public class XXX {
    @Operation(summary = "Get xxx by name.", operationId = "getXXXByName")
    @GetMapping("/{name}")
    public XXX get(@PathVariable("name") String name) { return new XXX(name); }

    ...
}
```

**Expected behavior**
I would not expect the field `object-type` to not be present in the schema for classes `XXX` and `YYY`

**Screenshots**
N / A

**Additional context**
N / A

**Comment by bnasslahsen** [comment]
@ssmoss, 

Not an issue using in the springdoc-openapi code.
You have also the workaround listed here #902

**Comment by ssmoss** [comment]
@bnasslahsen I think there is an issue filed with swagger-core https://github.com/swagger-api/swagger-core/issues/3980 . Thanks for the great library and the clarification.
