### ISSUE TITLE
OpenAPI response caching doesn't respect group.

### ISSUE THREAD

**Issue by ssmoss** [springdoc/springdoc-openapi#1270]
**Describe the bug**
If there is more than one `GroupedOpenApi` created using different a different `group` identifier and `caching` is enabled the first group return is cached and always returned no matter which group is specified.

**To Reproduce**
`spring-boot` version 2.4.5
`springdoc-openapi` version 1.5.10

```java
@Configuration
public class Swagger {
    @Bean
    public GroupedOpenApi apiV1() {
        return GroupedOpenApi.builder()
            .addOpenApiCustomiser(a -> a.info(
                new Info()
                    .title("My Cool API")
                    .description("API Documentation")
                    .version("V1")
            ))
            .group("v1")
            .packagesToScan("com.my.company.api.v1.resources")
            .build();
    }

    @Bean
    public GroupedOpenApi apiV2() {
        return GroupedOpenApi.builder()
            .addOpenApiCustomiser(a -> a.info(
                new Info()
                    .title("My Cool API")
                    .description("API Documentation")
                    .version("V2")
            ))
            .group("v2")
            .packagesToScan("com.my.company.api.v2.resources")
            .build();
    }

    @Bean
    public OpenAPI ui() { return new OpenAPI(); }
}
```

Make a call to `http://server:port/context-path/v3/api-docs/v1` and then try to make a call to `http://server:port/context-path/v3/api-docs/v2`. The call to `http://server:port/context-path/v3/api-docs/v2` will return `v1` OpenAPI. If caching is disabled `springdoc.cache.disabled=true` the respective calls return the correct OpenAPI.

**Expected behavior**
I would caching to respect the group provide.

**Screenshots**
N / A

**Additional context**
It seems people have run into this issue before and it has been closed without any resolution.

https://github.com/springdoc/springdoc-openapi/issues/538
https://github.com/springdoc/springdoc-openapi/issues/858

**Comment by bnasslahsen** [comment]
@ssmoss , 

Not reproducible.
Make sure you Provide [a Minimal, Reproducible Example - with HelloController](https://stackoverflow.com/help/minimal-reproducible-example) that reproduces the problem.

This ticket can be reopened, if the relevant information are provided.
