### ISSUE TITLE
SwaggerUiConfigParameters `urls` serialization issue

### ISSUE THREAD

**Issue by ssmoss** [springdoc/springdoc-openapi#1271]
**Describe the bug**
When setting more than one url via `springdoc.swagger-ui.urls[%d].name` and `springdoc.swagger-ui.urls[%d].url` and using a custom object mapper that requires properties to be serialized using `@JsonProperty`  the call to `http://server:port/context-path/v3/api-docs/swagger-config` breaks as it returns a `AbstractSwaggerUiConfigProperties.SwaggerUrl.class` object instead of a `HashMap` containing the keys `name` and `url` set to their respective values.

**To Reproduce**
`spring-boot` version 2.4.5
`springdoc-openapi` version 1.5.10

```
springdoc.swagger-ui.urls[0].name = v1
springdoc.swagger-ui.urls[0].url = /v3/api-docs/v1

springdoc.swagger-ui.urls[1].name = v2
springdoc.swagger-ui.urls[1].url = /v3/api-docs/v2
```

**Expected behavior**
I would expect the response builder for to not set `urls` to objects but to `Set` of `HashMaps` or for the fields in `AbstractSwaggerUiConfigProperties.SwaggerUrl.class` to be tagged with `@JsonProperty`

**Screenshots**
N / A

**Additional context**
N / A

**Comment by bnasslahsen** [comment]
@ssmoss, 

Your description is just not clear.
Please respect the [guidance](https://github.com/springdoc/springdoc-openapi/blob/master/CONTRIBUTING.adoc) for opening issues.

Make sure you Provide [a Minimal, Reproducible Example - with HelloController](https://stackoverflow.com/help/minimal-reproducible-example) that reproduces the problem.

This ticket can be reopened, if the relevant information are provided.
