### ISSUE TITLE
Mark optional parameters as nullable: true

### ISSUE THREAD

**Issue by mjustin** [springdoc/springdoc-openapi#1275]
## Is your feature request related to a problem? Please describe.
By default, if a property on a controller request parameter is not required, it can be passed in to a Spring controller endpoint by setting the value in the request JSON to `null`.  Likewise, a `null` value will be returned for such a null property if returned by a controller endpoint.

However, springdoc-openapi does not mark parameters as null unless extra steps are taken, such as adding `@Schema(nullable = true)`.  This means that by default, for any non-required property, there will be a discrepancy between the generated OpenAPI documentation and the behavior of the endpoint.  Such an endpoint will accept null properties, or return null properties, even though the OpenAPI documentation specifies it can't and won't.

### Example

```java
import io.swagger.v3.oas.annotations.media.Schema;
import javax.validation.constraints.NotNull;

public class RequiredExample {
    @NotNull
    private String key;

    private String value;

    public String getKey() { return key; }
    public void setKey(String key) { this.key = key; }
    public String getValue() { return value; }
    public void setValue(String value) { this.value = value; }
}
```

### Generated OpenAPI schema:

```json
"components": {
  "schemas": {
    "RequiredExample": {
      "required": [
        "key"
      ],
      "type": "object",
      "properties": {
        "key": {
          "type": "string"
        },
        "value": {
          "type": "string"
        }
      }
    }
  }
}
```

## Describe the solution you'd like
I would like any optional property to also be nullable by default.  I could see where it might be opt-in via a Spring property, especially given that this would otherwise change how existing documentation would be generated.

### Desired OpenAPI schema:

```lang-json
"components": {
  "schemas": {
    "RequiredExample": {
      "required": [
        "key"
      ],
      "type": "object",
      "properties": {
        "key": {
          "type": "string"
        },
        "value": {
          "type": "string"
          "nullable": true
        }
      }
    }
  }
}
```

## Describe alternatives you've considered
I currently have this functionality implemented in an app using a custom [`OpenApiCustomiser`](https://javadoc.io/static/org.springdoc/springdoc-openapi-common/1.5.10/org/springdoc/core/customizers/OpenApiCustomiser.html) to achieve this effect:

```java
import io.swagger.v3.oas.models.OpenAPI;
import io.swagger.v3.oas.models.media.Schema;
import org.springdoc.core.customizers.OpenApiCustomiser;
import org.springframework.stereotype.Component;
import java.util.Map;

@Component
public class NullableIfNotRequiredOpenApiCustomizer implements OpenApiCustomiser {
    @Override
    @SuppressWarnings({"rawtypes", "unchecked"})
    public void customise(OpenAPI openApi) {
        for (Schema schema : openApi.getComponents().getSchemas().values()) {
            if (schema.getProperties() == null) {
                continue;
            }

            ((Map<String, Schema>) schema.getProperties()).forEach((String name, Schema value) -> {
                if (schema.getRequired() == null || !schema.getRequired().contains(name)) {
                    value.setNullable(true);
                }
            });
        }
    }
}
```

**Comment by bnasslahsen** [comment]
@mjustin, 

This handled in the swagger-core and you can ask for this enhancement for the [swagger-core](https://github.com/swagger-api/swagger-core/issues) instead.

```java
	ResolvedSchema resolvedSchema = ModelConverters.getInstance()
				.resolveAsResolvedSchema(
						new AnnotatedType(RequiredExample.class));
		Assert.isTrue(((Schema) resolvedSchema.schema.getProperties().get("value")).getNullable(), "I'd like it to be true!");
```

Overriding this resolution, might lead to other issues... 
In addition, you have too many workarounds using `springdoc`.

**Comment by mjustin** [comment]
> This handled in the swagger-core and you can ask for this enhancement for the swagger-core instead.

Thank you.  I had checked, and saw the "NotNull" annotation handling in [`AbstractRequestService`](https://github.com/springdoc/springdoc-openapi/blob/99fe5d704abd912519c00bc84162131841f4a3ef/springdoc-openapi-common/src/main/java/org/springdoc/core/AbstractRequestService.java#L101), and had incorrectly reached the conclusion that the annotation handling for properties was a springdoc thing, not a Swagger Core thing.  I missed that the annotation handling of the actual models occurred in Swagger Core's [`ModelResolver`](https://github.com/swagger-api/swagger-core/blob/56d233b68aec8dafeea9cc39532abe30774c26ec/modules/swagger-core/src/main/java/io/swagger/v3/core/jackson/ModelResolver.java).

> In addition, you have too many workarounds using springdoc.

I'm not quite sure what the intended meaning of this sentence is.
