### ISSUE TITLE
How to reset the origin header?

### ISSUE THREAD

**Issue by yuanpli** [springdoc/springdoc-openapi#1278]
Hello,

There is a requirement is that the application API server will check the 'origin' header. In a real prod environment, there is no problem due to the decoupling of the frontend and backend. 

But in the development phase, if someone has a try the API from swagger UI, the `origin` header got by the backend server always is the one that where the backend server is running on. The reason is that the swagger UI is integrated with the backend server together.

So I am trying to reset the `origin` header from the given input in swagger UI in the following way, but it didn't work.
```
    @Bean
    public OperationCustomizer customGlobalHeaders() {
        return (Operation operation, HandlerMethod handlerMethod) -> {
            Parameter originHeader = new Parameter().in(ParameterIn.HEADER.toString()).schema(new StringSchema())
                    .name("origin").description("header origin").required(true);
            operation.addParametersItem(originHeader);
            return operation;
        };
    }
```
Could someone share that how to make it work? Thanks!

**Comment by bnasslahsen** [comment]
@yuanpli,

Check the `curl` code, and you will see it's correct.
![image](https://user-images.githubusercontent.com/13404829/135723074-9b4dbc88-50b4-4c0d-9789-ab48ee3eb4b1.png)

You can log the issue in the [swagger-ui](https://github.com/swagger-api/swagger-ui/issues).

Dont forget to add the curl request in the new ticket.
