### ISSUE TITLE
Setting springdoc.api-docs.path prevents auto loading of api

### ISSUE THREAD

**Issue by T3rm1** [springdoc/springdoc-openapi#1279]
I can set `springdoc.swagger-ui.path` to a value and the swagger ui will be available under this url and load the api definition. This works fine.

However, as soon as I set the value of `springdoc.api-docs.path` (and of course `springdoc.swagger-ui.config-url` to the same value + "/swagger-config") the api definition won't be loaded any more and the page only displays the message `No API definition provided.`.

Looking at the network tab I can see that the endpoint `springdoc.swagger-ui.config-url` is accessed but not the api doc itself.

**Comment by T3rm1** [comment]
Here is a demo project:
[springdoc-bugs.zip](https://github.com/springdoc/springdoc-openapi/files/7271428/springdoc-bugs.zip)

Start the application and go to http://localhost:8090/swag
You will see the empty swagger page.

As soon as I remove `springdoc.swagger-ui.config-url` and `springdoc.api-docs.path` it works again.

Another thing I noticed is that when I don't add `@EnableConfigurationProperties` to my `SwaggerConfig` class, the configuration does not work because `SwaggerUiConfigProperties` relies on it. I didn't find any mention of `@EnableConfigurationProperties` in the documentation or the FAQ. This should be noted somewhere as it took quite some time to pinpoint this issue.

**Comment by bnasslahsen** [comment]
Only remove the useless `springdoc.swagger-ui.configUrl `.

As explained here, https://github.com/springdoc/springdoc-openapi/issues/1144, you don't need to set manually the path of `springdoc.swagger-ui.configUrl`: It all works out of the box...

When you decide to set  `configurl` manually, then it's up to you to put the configuration resources in the right path:

```properties
springdoc.swagger-ui.configUrl=/myapi/swagger-config.json
```

**Comment by T3rm1** [comment]
When I set `springdoc.api-docs.path` to `/apidocs`, I also get an endpoint `/apidocs/swagger-config`. So when I set the `springdoc.swagger-ui.configUrl` to that path it should still work, right?

**Comment by bnasslahsen** [comment]
No.
As explained. When you set this path manually, you have also to put the json configuration in that path.
