### ISSUE TITLE
@ExampleObject, mixed up fields?

### ISSUE THREAD

**Issue by Stexxen** [springdoc/springdoc-openapi#128]
Using the @ExampleObject like so

`@ExampleObject(name = "Short Name", summary = "Longer Summary Text, blah blah blah", value = "{}")`

I see the following.
<img width="626" alt="image" src="https://user-images.githubusercontent.com/4494301/67559414-d2d19a00-f710-11e9-9023-bad75eeb5739.png">

I'm thinking it should be the other way round? the Name in the dropdown and the summary in the description area?

**Comment by springdoc** [comment]
Hi,

We rely on swagger-ui (v3.24.0) official webjars. We build our library on top of it.
The springdoc-openapi library fills the @ExampleObject according to the OpenAPI 3 specification.

You are describing that the behaviour of the ui is not the same, depending on @ExampleObject/summary field:
- If the summary is absent, it picks the name from the examples dropdown list.
- If the summary is present, it is used on the examples dropdown list.

You can submit your request to the swagger-ui project team instead:
- https://github.com/swagger-api/swagger-ui/issues

**Comment by Stexxen** [comment]
ahhh I see. I did wonder if that was the case.
Thanks for clearing that up.
