### ISSUE TITLE
Sorter is not applied on OpenAPI API docs

### ISSUE THREAD

**Issue by netaravind** [springdoc/springdoc-openapi#1281]
**Bug Description**
SpringDocs provides an option to sort the API resources by tags and operation id by using the following properties,

> #For sorting endpoints alphabetically
> springdoc.swagger-ui.operationsSorter=alpha
> #For sorting tags alphabetically
> springdoc.swagger-ui.tagsSorter=alpha
> 

This works fine for Swagger UI page, however the API docs link for OpenAPI spec file still shows **unsorted** resources. 

**To Reproduce**
- springdoc-openapi-ui 1.5.10 
- The expectation is to show the Swagger UI and API docs API resources in the tags, operation id sort order, however Swagger UI shows the resources in the sorted order and API docs not.

**Expected behavior**
- Both Swagger UI and API docs should show API resources in the sorted order specified in the application configuration

**Screenshots**
**Swagger UI**
![Swagger UI](https://user-images.githubusercontent.com/13508952/135516357-b12cced4-d14c-46e5-a626-7110f8212d93.png)

**API Docs**
![API Docs - OpenAPI Spec](https://user-images.githubusercontent.com/13508952/135516375-a477dc06-d951-46b1-98e4-bf01b80eb395.png)

**Comment by bnasslahsen** [comment]
@netaravind, 

As it's mentioned in the documentation. 
These are ui properties:  **springdoc.swagger-ui**

The only sorting available for the `/v3/api-docs` endpoints is the alphabetical ordering using `springdoc.writer-with-order-by-keys`.

For anything else, use `OpenApiCustomiser`. And you have a lot of samples for ordering that you can adapt: https://github.com/springdoc/springdoc-openapi/issues/890
