### ISSUE TITLE
Is there a way to inline a types definition and not $ref it?

### ISSUE THREAD

**Issue by finsterwalder** [springdoc/springdoc-openapi#1298]
We use some types often for many attributes. Since they are all referenced, we can not provide individual descriptions.
A simplified example:
@Schema(description = "Tax amount")
MonetaryAmount tax;

@Schema(description = "Billed amount")
MonetaryAmount billed;

Sadly, OpenAPI does not allow $ref and an individual description. So this can only be achieved by not using $ref.
Is it possible to somehow "manipulate" the processing, so a type is never $ref-erenced?

I played around with a PropertyCustomizer and a ModelConverter, but could not get it to work.

I already found the FAQ article on:
How can i define different schemas for the same class?
But that is very cumbersome for the many location, where I want to use the same type, so I'm looking for a solution, that I can somehow write into an annotation or similar on the referenced type or the attribute to not use a $ref.

**Comment by bnasslahsen** [comment]
@finsterwalder, 

Already answered here: [How can i define different description for a class attribute](https://springdoc.org/#how-can-i-define-different-description-for-a-class-attribute-depending-on-usage)

But if you come out with something better, feel free to share :)
