### ISSUE TITLE
A support for Spring Cloud Fuction Web

### ISSUE THREAD

**Issue by Marx2** [springdoc/springdoc-openapi#1299]
**Is your feature request related to a problem? Please describe.**
After implementing a Java Function and adding spring-cloud-function-web dependency all such functions are exposed as REST endpoint automatically. It's described here: https://spring.io/blog/2020/12/23/cloud-events-and-spring-part-2

**Describe the solution you'd like**
I'd like to see all such endpoints be visible on Swagger documentation.

**Comment by bnasslahsen** [comment]
@Marx2, 

The support is now added. 
Don't hesitate to test it with the latest [SNAPSHOT](https://springdoc.org/#how-can-i-use-the-last-springdoc-openapi-snapshot) and provide your feedback.
