### ISSUE TITLE
@Parameter in @Operation not working

### ISSUE THREAD

**Issue by membersound** [springdoc/springdoc-openapi#13]
The following example shows `No parameters` in the ui.
`springdoc-openapi-ui-1.1.6`

```
@RestController
public class PersonServlet {
	@GetMapping(value = "/persons")
	@Operation(parameters = {@Parameter(name = "name", in = ParameterIn.QUERY)})
	public void get() {

	}
}
```

**Comment by springdoc** [comment]
The example is not complete. The parameter type (schema) is not specified.
However, handling @Parameter in @Operation with proper schema will be available on version: 1.1.7
`	@Operation(parameters = {
			@Parameter(name = "name", in = ParameterIn.QUERY, schema = @Schema(implementation = String.class)) })`
