### ISSUE TITLE
Multiple models with the same class name will be parsed into the same

### ISSUE THREAD

**Issue by tomgao365** [springdoc/springdoc-openapi#130]
`cc.tomgao.demo.springdoc.crm.model.User` and `cc.tomgao.demo.springdoc.sys.model.User` 

![image](https://user-images.githubusercontent.com/13798931/67645590-96967780-f964-11e9-8782-0ccd084a6213.png)

[demo](https://github.com/my-alpha/springdoc-openapi-demo)

**Comment by springdoc** [comment]
Hi, 

 By default, Both of your models will use the same schema name, which is the class name. 
 You can just provide a different schema name, for each class in this case:
 
```java
package cc.tomgao.demo.springdoc.sys.model.User;
@Schema(name = "User1")
public class User
```
and:
```java
package cc.tomgao.demo.springdoc.crm.model.User;
@Schema(name = "User2")
public class User
```

**Comment by olaisolheim** [comment]
The solution outlined in this solution is not really a solution, but a workaround, which requires access to alter the classes, which is not always the case.

Spring Doc assumes classes with the same name will also have the same schema/contract, which is obviously not a great assumption to begin with.

Is there another way to have Spring Doc differentiate between the two?
