### ISSUE TITLE
Implement differents examples for the same field

### ISSUE THREAD

**Issue by oscarTala** [springdoc/springdoc-openapi#1300]
I have this POJO:

@Data
@Builder
public class Metadata {
  @Schema(example = "d290f1ee-6c54-4b01-90e6-d701748f0851")
  private String requestId;
  @Schema(example = "8.55235")
  private double executionTime;
  private List<String> errors;
  private int statusCode;
}

And I want status code would be different for each scenario on my RestControllerHandler:

@RestControllerAdvice
public class GlobalControllerExceptionHandler {

  @ExceptionHandler(javax.ws.rs.BadRequestException.class)
  @ApiResponse(responseCode = "400", description = "Invalid request. Parameters missing or invalid.")
  @RequestMapping(produces="application/json")
  public ResponseEntity<ResponseDataWrapper> handleNotFound(RuntimeException ex) {
    return new ResponseEntity(ex.getMessage(), HttpStatus.BAD_REQUEST);
  }

  @ExceptionHandler(javax.ws.rs.NotAuthorizedException.class)
  @ApiResponse(responseCode = "401", description = "Invalid User Token.")
  public ResponseEntity<ResponseDataWrapper> handleUnauthorized(RuntimeException ex) {
    return new ResponseEntity(ex.getMessage(), HttpStatus.UNAUTHORIZED);
  }

@ExceptionHandler(javax.ws.rs.NotFoundException.class)
  @ApiResponse(responseCode = "404", description = "Resource not found.")
  @RequestMapping(produces="application/json")
  public ResponseEntity<ResponseDataWrapper> handleBadRequest(RuntimeException ex) {
    return new ResponseEntity(ex.getMessage(), HttpStatus.NOT_FOUND);
  }

  @ExceptionHandler(javax.ws.rs.ClientErrorException.class)
  @ApiResponse(responseCode = "500", description = "Internal Server Error.")
  @RequestMapping(produces="application/json")
  @io.swagger.v3.oas.annotations.media.Schema(name="InternalServer")
  public ResponseEntity<ResponseDataWrapper> handleApplicationError(RuntimeException ex) {
    return new ResponseEntity(ex.getMessage(), HttpStatus.INTERNAL_SERVER_ERROR);
  }

@Bean
	public OpenAPI customOpenAPI() {
		return new OpenAPI().components(new Components()
				.addSchemas("InternalServer", getFieldSchemaWithDifferentDescription(Metadata.class, "500", "Internal Server Error")));
	}

	private Schema getFieldSchemaWithDifferentDescription(Class className, String statusCode, String errors){
		ResolvedSchema resolvedSchema = ModelConverters.getInstance()
				.resolveAsResolvedSchema(
						new AnnotatedType(className).resolveAsRef(false));
		return resolvedSchema.schema.addProperties("statusCode", new StringSchema().example(statusCode))
				.addProperties("errors", new StringSchema().example(errors));
	}
}

**Comment by bnasslahsen** [comment]
@oscarTala, 

Make sure you post clear issue with at least code formatting ...

You can follow the  [contributing guidelines](https://github.com/springdoc/springdoc-openapi/blob/master/CONTRIBUTING.adoc)

Do not create any other issues. You can update this ticket and we can reopen it.
