### ISSUE TITLE
Does it really support spring boot 2.2.0.RELEASE?

### ISSUE THREAD

**Issue by danieleforberghi** [springdoc/springdoc-openapi#132]
Does open api have the same issue with spring-plugin-version as springfox ? Does it support spring-plugin-2.0.0.RELEASE or just 1.2.0.RELEASE of the plugin ?

**Comment by springdoc** [comment]
Hi, 

 No special issue with v2.2.0.RELEASE of spring-boot.
You can have a look at the demos for examples: springdoc-openapi-test-app2 and springdoc-openapi-test-app3
- https://github.com/springdoc/springdoc-openapi-demos.git

These applications are also deployed with v1.2.0 of springdoc-openapi:

- https://springdoc-openapi-test-app2-silly-numbat.eu-de.mybluemix.net/swagger-ui.html
- https://springdoc-openapi-test-app3-terrific-rabbit.eu-de.mybluemix.net/swagger-ui.html
