### ISSUE TITLE
Sponsorship question

### ISSUE THREAD

**Issue by GonMMarques** [springdoc/springdoc-openapi#1323]
Hello,

I noticed that you have sponsoring enabled but would you be open to having GitHub Sponsors (directly) as a sponsoring opportunity?

Thanks in advance.

**Comment by bnasslahsen** [comment]
Hi @GonMMarques, 

The team is open for GitHub Sponsors-directly.
If you have more questions, feel free to reach out directly using support@springdoc.org

**Comment by GonMMarques** [comment]
Thanks for enabling the GitHub sponsors and happy the project got sponsored by the Mercedes-Benz group 😃
