### ISSUE TITLE
springdoc-openapi-javadoc doesn't work with @ParameterObject

### ISSUE THREAD

**Issue by ddulaney** [springdoc/springdoc-openapi#1324]
**Describe the bug**
I'm using [`springdoc-openapi-javadoc`](https://springdoc.org/#javadoc-support) to generate descriptions from my docs (kdocs, since I'm using Kotlin). It works great for the most part, but it isn't pulling docs from `@ParameterObject` classes.

**To Reproduce**

- What version of spring-boot you are using? 
`2.5.5`

- What modules and versions of springdoc-openapi are you using?
```kts
plugins {
    id("org.springdoc.openapi-gradle-plugin") version "1.3.3"
}

dependencies {
    // OpenAPI
    implementation("org.springdoc:springdoc-openapi-ui:1.5.11")
    implementation("org.springdoc:springdoc-openapi-kotlin:1.5.11")
    // Expand Pageable into page, size, sort
    implementation("org.springdoc:springdoc-openapi-data-rest:1.5.11")
    // Pull documentation from kdocs
    implementation("org.springdoc:springdoc-openapi-javadoc:1.5.11")
    kapt("com.github.therapi:therapi-runtime-javadoc-scribe:0.12.0")
}
```

- Provide with a sample code (HelloController) or Test that reproduces the problem
```kotlin
/**
 * Gets a list of things.
 */
@GetMapping
fun getThings(@ParameterObject params: MyParams) = ...

data class MyParams(
    /**
     * My query param description.
     */
    val myQueryParam: String? = null
)
```
Note that it does work if I use `@Parameter` like this:
```kotlin
data class MyParams(
    @field:Parameter(description = "My query param description.")
    val myQueryParam: String? = null
)
```

**Expected behavior**

I would expect the kdocs from my `@ParameterObject` to be used as the parameter descriptions.
Here's what I'm hoping for:
```json
{
  "/v1/things": {
    "get": {
      "description": "Gets a list of things.",
      "operationId": "getThings",
      "parameters": [
        {
          "name": "myQueryParam",
          "in": "query",
          "description": "My query param description.",
          "required": false,
          "schema": {
            "type": "string"
          }
        }
      ]
    }
  }
}
```

But here's what I'm getting:
```json
{
  "/v1/things": {
    "get": {
      "description": "Gets a list of things.",
      "operationId": "getThings",
      "parameters": [
        {
          "name": "myQueryParam",
          "in": "query",
          "required": false,
          "schema": {
            "type": "string"
          }
        }
      ]
    }
  }
}
```

Thank you!

**Comment by burimkrasniqi** [comment]
Im using Spring Boot Webflux, @ParameterObject is not working at all in my case.

OpenApi 3 is working properly in case of queryParameters, pathParameters, requestBody. Its not working only in case of Query Parameters that are mapped in ContainerFilters.class(by using HandlerMethodArgumentResolver in spring boot) and its not working for Pageable as well.

```
  @Authorized
  @RequestMapping(value = "", method = RequestMethod.GET)
  public Flux<ContainerResResDto> getContainers(
      @Include User user,
      @ParameterObject @Include ContainerFilters filters,
      @ParameterObject Pageable pageable) {

    return containerService.getContainers(user, filters, pageable).map(ContainerResResDto::of);
  }
```

**Comment by ddulaney** [comment]
Hey @burimkrasniqi, you probably want to open a separate issue for that. This one is about using [springdoc-openapi-javadoc](https://springdoc.org/#javadoc-support) with `@ParameterObject`.
