### ISSUE TITLE
@ParameterObject is not working for spring boot webflux

### ISSUE THREAD

**Issue by burimkrasniqi** [springdoc/springdoc-openapi#1325]
Im using Spring Boot Webflux, @ParameterObject is not working at all in my case.

OpenApi 3 is working properly in case of queryParameters, pathParameters, requestBody. Its not working only in case of Query Parameters that are mapped in ContainerFilters.class(by using HandlerMethodArgumentResolver in spring boot) and its not working for Pageable as well.

```
  @Authorized
  @RequestMapping(value = "", method = RequestMethod.GET)
  public Flux<ContainerResResDto> getContainers(
      @Include User user,
      @ParameterObject @Include ContainerFilters filters,
      @ParameterObject Pageable pageable) {

    return containerService.getContainers(user, filters, pageable).map(ContainerResResDto::of);
  }
```

_Originally posted by @burimkrasniqi in https://github.com/springdoc/springdoc-openapi/issues/1324#issuecomment-956168952_

**Comment by bnasslahsen** [comment]
@burimkrasniqi,

Make sure you provide a minimal reproducible simple as described in the contribution guide.


This ticket will be closed and can be reopened if the relevant information are provided.

**Comment by Pashulity** [comment]
@burimkrasniqi 

faced this issue on 1.5.13

upgrading to 1.6.0 worked for me.
