### ISSUE TITLE
Pageable - couple of questions or suggestions

### ISSUE THREAD

**Issue by cvetan** [springdoc/springdoc-openapi#1327]
I have one endpoint that gets multiple filtering and sorting conditions so I added one object as `@ParameterObject`. Also `Pageable` is one field in that object.

Swagger shows that as it should, however Pageable instance does not get injected in object and it is null.

Is this by design or is there a way around that? One thing that also makes me think that this is discouradged is that you can't set `PageableDefault` inside object if it is not inside API method definition.

Second question is related about pagination information inside swagger. 
I've configured spring data one based index, but swagger still shows that it is zero based. It works as it should, however it can be misleading to someone that uses API without this knowledge. 

Can this be altered?

Thanks

**Comment by bnasslahsen** [comment]
Hi @cvetan, 

All is explained in the [documentation](https://springdoc.org/#spring-data-rest-support)u 
You can have also a look in the sample tests of the project.

If you want report an issue, make sure you follow the [contributing guidelines](https://github.com/springdoc/springdoc-openapi/blob/dd0a8eba6761de9a32c7cd77deca87f26e52eafb/CONTRIBUTING.adoc).
