### ISSUE TITLE
springdoc still not compatible with latest spring native 0.11-M2

### ISSUE THREAD

**Issue by goafabric** [springdoc/springdoc-openapi#1328]
As already noted in 
https://github.com/springdoc/springdoc-openapi/issues/1294

Springdoc ist not compatible with the latest spring native version.
It basically still fails with the same exception, see below.
Please note the "Could not resolve placeholder 'springdoc.swagger-ui.version' in value "${springdoc.swagger-ui.version}"

I upgraded to the latest version 1.5.12 of springdoc, while also moving from 0.11-M1 -> 0.11 M2 + Spring Boot 2.6.0-RC1
This is a very simple spring boot project, with no specific configuration for springdoc at all.

--- exception

org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'securityConfiguration': Unsatisfied dependency expressed through method 'setContentNegotationStrategy' parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'org.springframework.boot.autoconfigure.web.servlet.WebMvcAutoConfiguration$EnableWebMvcConfiguration': Unsatisfied dependency expressed through method 'setConfigurers' parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'swaggerWebMvcConfigurer': Unsatisfied dependency expressed through method 'swaggerWebMvcConfigurer' parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.springdoc.core.SwaggerUiConfigParameters': Unexpected exception during bean creation; nested exception is java.lang.IllegalArgumentException: Could not resolve placeholder 'springdoc.swagger-ui.version' in value "${springdoc.swagger-ui.version}"
	at org.springframework.aot.beans.factory.InjectedMethodResolver.resolve(InjectedMethodResolver.java:63) ~[na:na]
	at org.springframework.aot.ContextBootstrapInitializer.lambda$initialize$5(ContextBootstrapInitializer.java:295) ~[na:na]
	at org.springframework.aot.beans.factory.ThrowableFunction.apply(ThrowableFunction.java:18) ~[na:na]

**Comment by bnasslahsen** [comment]
@goafabric, 

`springdoc-openapi` is tested against the latest spring-native stable release - as per today: `0.10.5`
For `0.11-M2`, it is a milestone release. We will not invest on it and wait for the official 0.11.x release, to make sure we are working on a relatively stable version.

Don't hesitate to report any issue, with the latest stable releases of `spring-native`.
