### ISSUE TITLE
Dictionnaries as RequestBody are not taken into account if not required

### ISSUE THREAD

**Issue by CChemin** [springdoc/springdoc-openapi#1330]
**Describe the bug**

When a Map<String, String> is used as a RequestBody springdoc-openapi generates a schema with a type object containing string additionalProperties as specified here : https://swagger.io/docs/specification/data-models/dictionaries/.

```json
{"post": {
        "tags": [
          "something-controller"
        ],
        "operationId": "createSomethingWithProperties",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "additionalProperties": {
                  "type": "string"
                }
              }
            }
          },
          "required": true
        }}
```

but if we indicate that the RequestBody is not required, no request body will be registered in the schema instead of a non required one : 

```json
{"post": {
        "tags": [
          "something-controller"
        ],
        "operationId": "createSomethingThatMayHaveProperties",
        "responses": {
          "200": {
            "description": "OK"
          }
        }
      }}
```

I have noticed this behaviour only with Map.

I'm not sure this is a bug or it is only due to a bad practice of using a Map as a RequestBody. So it may be more of a question. But as it is working well when the body is required I was surprised that it didn't work as well when the body is optional.

**To Reproduce**

The versions I used were **spring-boot 2.5.6** and **springdoc-openapi-ui 1.5.12** .

You can find a minimal reproduction of this behaviour here : https://github.com/CChemin/not-required-body-bug

with this Controller :

```java
@RestController
public class SomethingController {

    @PostMapping(
        value = {"/something"})
    public void createSomethingThatMayHaveProperties(
        @RequestBody(required=false) Map<String, String> propertiesNotRequired 
    ){}
}
```

**Expected behavior**

I would expect this schema : 

```json
{
"post": {
        "tags": [
          "something-controller"
        ],
        "operationId": "createSomethingThatMayHaveProperties",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "additionalProperties": {
                  "type": "string"
                }
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "OK"
          }
        }
      }
    }
```

**Comment by bnasslahsen** [comment]
@CChemin, 

This is not a bug. 
Map parameters are by default ignored, unless explicitly declared. Putting the parameter as required, is an explicit declaration.

See F.A.Q:
- [What are the ignored types in the documentation?](https://springdoc.org/#what-are-the-ignored-types-in-the-documentation)
- [How can i disable ignored types?](https://springdoc.org/#how-can-i-disable-ignored-types)
