### ISSUE TITLE
operationsSorter and tagsSorter custom function example?

### ISSUE THREAD

**Issue by breakline87** [springdoc/springdoc-openapi#1335]
Hello,

I'm trying to implement a custom sorting function. In my case, I'd like to sort by "operationId" of the @Operation annotation. However I have a hard time finding a working example of this:

Function=(a ⇒ a). Apply a sort to the operation list of each API. It can be 'alpha' (sort by paths alphanumerically), 'method' (sort by HTTP method) or a function (see Array.prototype.sort() to know how sort function works). Default is the order returned by the server unchanged.

Per this, it seems to me that this needs a javascript function, but I have not managed to make it work and I haven't found a single example of this anywhere in the docs or in google/stackoverflow/etc.

My idea would be like:

`operationsSorter: sort((a, b) => {if (a.operationId < b.operationId) {return -1;} if (a.operationId > b.operationId) {return 1;} return 0;})`

But this does not work. But it's probably not the good approach. Also is there a way to do this from java code? Maybe via the OpenAPI or OpenApiCustomiser Bean?

Any help is appreciated.

**Comment by bnasslahsen** [comment]
@breakline87, 

To inject your own javascript code, you can have a look [how to inject custom JS code from Java](https://github.com/springdoc/springdoc-openapi/blob/master/springdoc-openapi-common/src/main/java/org/springdoc/ui/AbstractSwaggerIndexTransformer.java).

After `window.ui = SwaggerUIBundle`, you can add your customer functions.

**Comment by oleg-cherednik** [comment]
Until now, I still can't find out how to properly use the custom function. I have added it after window.ui, but it still does not work.
