### ISSUE TITLE
@Schema annotation on field overrides description

### ISSUE THREAD

**Issue by T3rm1** [springdoc/springdoc-openapi#1336]
**Description**
I want to add a description to a property of a schema. In OAS2 this was possible with setting the _value_ parameter of `@ApiModelProperty`. In OAS3 the `@Schema` annotation has to be used for this.

If a class (see below for example code) has two fields of the same type and a schema annotation with a description is present on both of them, the latter schema annotation overrides the first one and setting the description of the schema (and not of the property).

**How to reproduce**
```java
public class Data implements CommonData {

    @Schema(description = "You won't see this")
    public String hiddenGetter;

    @Schema(description = "This is a description of notHiddenData")
    public String notHiddenData;

    @Schema(description = "This info will be lost")
    public MoreData interfaceData;

    @Schema(description = "New description")
    public MoreData moreInterfaceData;

    @Override
    public MoreData getInterfaceData() {
        return interfaceData;
    }

    @Override
    @Hidden
    public String getSomething() {
        return notHiddenData;
    }

    public String getup() {
        return "this should not end up in the api docs";
    }
}

public interface CommonData {

    MoreData getInterfaceData();

    String getSomething();

    @Hidden
    default String getHiddenGetter() {
        return "foo";
    }
}

public class MoreData {

    public String moreThings;
}
```

**Context**
Problems is see here are:

1. It is not possible to add a description of the fields `interfaceData` and `moreInterfaceData`.
2. The provided description of the annotation for `moreInterfaceData` overrides the description of `interfaceData`. The description "This info will be lost" is not present in the generated api docs.
3. It is required to provide annotations for methods, not only fields.
3.1. This is kinda odd and is different to known behavior of other libraries (e.g. Hibernate, Jackson). Either annotations on field or on methods are evaluated but not both. The method `getup()` ends up as a property `getup` in the api doc.
3.2 The `@Hidden` annotation on the interface method `getHiddenGetter` prevents the field `hiddenGetter` to be in the api doc although it is a public field.
4. The description of the schema `MoreData` is set to `New description` although only fields (properties of the schema) are annotated. The intention here is to better describe the properties of the schema, especially those with identical type.

**Comment by bnasslahsen** [comment]
@T3rm1, 

Already answered in the F.A.Q:
- https://springdoc.org/#how-can-i-define-different-schemas-for-the-same-class

Or might help :
- https://springdoc.org/#how-can-i-define-different-description-for-a-class-attribute-depending-on-usage

**Comment by T3rm1** [comment]
@bnasslahsen 
That's more than complicated and not usefull at all to have the description for a property in a different class. This should work with only the annotation.

Anyway, you closed the issue without responding to the other points.

**Comment by bnasslahsen** [comment]
@T3rm1, 

You didn't understand the answer...Nothing is mentioning `description for a property in a different class`
Please read the F.A.Q links, which allows you get different description for the same Class.
