### ISSUE TITLE
OAuth2 redirect broken in WebFlux when context-path is not set to root

### ISSUE THREAD

**Issue by optimisticninja** [springdoc/springdoc-openapi#1338]
**Describe the bug**
When `spring.webflux.base-path` is set to a different context, the oauth2-redirect.html is broken. It tries to send you to root.

For instance, after authenticating at /v1/webjars, the redirect sends you to /webjars. You can change the path and it closes the redirect.

**To Reproduce**
- What version of spring-boot you are using? 
  - 2.5.6
- What modules and versions of springdoc-openapi are you using? 
  - security
  - webflux
- What is the actual and the expected result using OpenAPI Description (yml or json)?
- Provide with a sample code (HelloController) or Test that reproduces the problem

**Expected behavior**
Redirected to /context-root/webjars/...

**Screenshots**
![image](https://user-images.githubusercontent.com/21355332/142087244-f9fe75ac-c9ff-4700-b465-a20ede9646fc.png)
![image](https://user-images.githubusercontent.com/21355332/142087337-9b0769f4-0add-4946-ac52-9cb61a924b33.png)

**Additional context**

**Comment by bnasslahsen** [comment]
@optimisticninja, 

- Which springdoc-openapi version are you using ?
- Are you able to provide any [Minimal, Reproducible Example - with HelloController ](https://stackoverflow.com/help/minimal-reproducible-example) that reproduces the problem?

**Comment by optimisticninja** [comment]
> @optimisticninja,
> 
>     * Which springdoc-openapi version are you using ?
> 
>     * Are you able to provide any [Minimal, Reproducible Example - with HelloController ](https://stackoverflow.com/help/minimal-reproducible-example) that reproduces the problem?

Hi @bnasslahsen producing a minimal example may be difficult given that oauth2 would need an authorization server. You may view the project [here](https://github.com/optimisticninja/posts-api)

As for the versions:
```gradle
dependencyManagement {
    dependency group: 'io.springfox', name: 'springfox-swagger-common', version: '3.0.0'
    dependencySet(group: 'org.springdoc', version: '1.5.2') {
      entry 'springdoc-openapi-webflux-ui'
      entry 'springdoc-openapi-security'
    }
  }
}

**Comment by optimisticninja** [comment]
It doesn't look like there is a workaround, the redirect path property `springdoc.swagger-ui.oauth2RedirectUrl ` starts after `/webjars` at `/swagger-ui/`

| /swagger-ui/oauth2-redirect.html | String. OAuth redirect URL.

**Comment by optimisticninja** [comment]
Upon further inspection, [this functionality](https://github.com/springdoc/springdoc-openapi/blob/77ff1136e3c4beafa21df93e1914aaac42f74f0a/springdoc-openapi-ui/src/main/java/org/springdoc/ui/SwaggerWelcome.java#L90) needs to be ported to the webflux-ui project.

**Comment by bnasslahsen** [comment]
@optimisticninja, 

First, make sure you are using the last stable version `v1.5.12`, before reporting any issues.
There is no known issues with the OAuth2 redirect url.

I have updated the demos, that shows it is just working fine with `spring.webflux.base-path`.

- https://github.com/springdoc/springdoc-openapi-demos/tree/master/springdoc-openapi-oauth2

If you are still facing the issue, then i invite to provide a sample [test like this one](https://github.com/springdoc/springdoc-openapi/blob/master/springdoc-openapi-webflux-ui/src/test/java/test/org/springdoc/ui/app18/SpringDocApp18Test.java), which explains what you are facing.

**Comment by optimisticninja** [comment]
Thank you and sorry for wasting your time. 1.5.12 fixed the issue.
