### ISSUE TITLE
Please add license block to all Maven pom.xml files - also sub module pom.xml files

### ISSUE THREAD

**Issue by carlbjor** [springdoc/springdoc-openapi#1341]
**Description of feature/bug**

License scanners, for example [JFrog Xray](https://jfrog.com/xray/), needs license information in every pom.xml to be defined.

- For example [springdoc-openapi-webmvc-core/pom.xml](https://github.com/springdoc/springdoc-openapi/blob/master/springdoc-openapi-webmvc-core/pom.xml) does not define the license information in the pom.xml itself, and thefore JFrog Xray complains about missing license information.

**Solution**

Add the license information explicitly to all pom.xml files, as is already done in the main [pom.xml](https://github.com/springdoc/springdoc-openapi/blob/master/pom.xml)

```xml
<licenses>
    <license>
        <name>The Apache License, Version 2.0</name>
	<url>http://www.apache.org/licenses/LICENSE-2.0.txt</url>
    </license>
</licenses>
```

**Comment by bnasslahsen** [comment]
@carlbjor, 

The licence is declared in the parent pom.xml.
I invite you to review the settings of JFrog Xray or contact them directly to know why how to handle inheritance...

**Comment by carlbjor** [comment]
I think the fastest and most robust solution is to add the license info in the sub module pom.xml files. It would not take more than a minute of work
