### ISSUE TITLE
@ParameterObject List Cannot be generated correctly

### ISSUE THREAD

**Issue by leshalv** [springdoc/springdoc-openapi#1342]
![image](https://user-images.githubusercontent.com/30397655/142750005-99f5ac58-916b-416c-b6dd-04b34baf6db7.png)
![image](https://user-images.githubusercontent.com/30397655/142750006-2a1b6058-5930-47c6-808f-b8fe4719b3b8.png)

**Comment by bnasslahsen** [comment]
@leshalv, 

There is no such a feature.
Make sure you provide the necessary information described in the [contribution guide](https://github.com/springdoc/springdoc-openapi/blob/master/CONTRIBUTING.adoc), while opening issues.

This ticket, will be closed and can be reopened, if any relevant information is provided.

**Comment by norbson** [comment]
Are you planning to add support for object list? In our case we would like to migrate from springfox and lack of this feature is blocker.
