### ISSUE TITLE
Allow customizing the default schema and create yaml with required fields by default

### ISSUE THREAD

**Issue by kamerm** [springdoc/springdoc-openapi#1346]
When creating a yaml, the default for properties in object is not "required". 
We are using also open-api to create Typescript code automatically and it puts "?" after each property (make it optional).

In order to make it mandatory - I must add @schema(required = true) on ALL fields.
So I would like to have an option to change that default - and create all fields as mandatory and allow optional with @schema(required=false)

Same as we do for enumAsRef (we added the solution described here: https://github.com/springdoc/springdoc-openapi/issues/232 to make all our enum as ref by default (without adding @schema annotation to all enums)

**Comment by bnasslahsen** [comment]
@kamerm, 

Already answered here: https://github.com/springdoc/springdoc-openapi/issues/704
You can see this sample git for inspiration. (https://gist.github.com/finsterwalder/deecf4399dcceea12eef07cd9af825e6), or the sample tests in the project.
