### ISSUE TITLE
Break circular references which disabled by default since spring boot 2.6

### ISSUE THREAD

**Issue by quaff** [springdoc/springdoc-openapi#1347]
```

***************************
APPLICATION FAILED TO START
***************************

Description:

The dependencies of some of the beans in the application context form a cycle:

┌─────┐
|  requestMappingHandlerMapping defined in class path resource [org/springframework/boot/autoconfigure/web/servlet/WebMvcAutoConfiguration$EnableWebMvcConfiguration.class]
↑     ↓
|  openApiResource defined in class path resource [org/springdoc/webmvc/core/SpringDocWebMvcConfiguration.class]
└─────┘


Action:

Relying upon circular references is discouraged and they are prohibited by default. Update your application to remove the dependency cycle between beans. As a last resort, it may be possible to break the cycle automatically by setting spring.main.allow-circular-references to true.

```

**Comment by thodorispa** [comment]
I have this error too.  I put in application.properties : 
spring.main.allow-circular-references=true
but it didn't work

**Comment by quaff** [comment]
> I have this error too. I put in application.properties : spring.main.allow-circular-references=true but it didn't work

`spring.main.allow-circular-references: true` works for me.

**Comment by abdimajidov** [comment]
worked on me too

**Comment by bnasslahsen** [comment]
Guys, would be great if you provide a minimal reproducible sample or directly propose a PR.
We will release by the EOM and would be great to prevent this issue without the additionnal property.

**Comment by abdimajidov** [comment]
putting @Lazy on the constructor is also a good option

**Comment by bnasslahsen** [comment]
This ticket will be closed, as no one has provided a [Minimal, Reproducible Example - with HelloController](https://stackoverflow.com/help/minimal-reproducible-example).

**Comment by quaff** [comment]
> SpringDocWebMvcConfiguration

Do you have customized `RequestMappingHandlerMapping` like this?
```java
@Component
public class DefaultWebMvcRegistrations implements WebMvcRegistrations {

	@Override
	public RequestMappingHandlerMapping getRequestMappingHandlerMapping() {
		return new MyRequestMappingHandlerMapping();
	}

}
```
@thodorispa @abdimajidov

**Comment by quaff** [comment]
@bnasslahsen  Here is [example.zip](https://github.com/springdoc/springdoc-openapi/files/7616534/example.zip) 
In customized `DefaultRequestMappingHandlerMapping`
```java
	@Override
	protected void detectHandlerMethods(Object handler) {
		Object handlerObject = (handler instanceof String ? obtainApplicationContext().getBean((String) handler)
				: handler); // getBean will cause circular references
		handlerHolder.set(handlerObject);
		super.detectHandlerMethods(handler);
		handlerHolder.remove();
	}
```

**Comment by bnasslahsen** [comment]
@quaff, 

Thank you for providing a reproducible sample.
This should be now fixed with the [latest SNAPSHOT.](https://springdoc.org/#how-can-i-use-the-last-springdoc-openapi-snapshot) 
You can give it a try and let us know.

**Comment by quaff** [comment]
> @quaff,
> 
> Thank you for providing a reproducible sample. This should be now fixed with the [latest SNAPSHOT.](https://springdoc.org/#how-can-i-use-the-last-springdoc-openapi-snapshot) You can give it a try and let us know.

It works now, thanks.

**Comment by KahugiaEriq** [comment]
I placed the spring.main.allow-circular-references: true and it worked for me too.
