### ISSUE TITLE
org.springdoc.springdoc-openapi-core:1.2.0

### ISSUE THREAD

**Issue by urswiss** [springdoc/springdoc-openapi#135]
Are there plans to release version 1.2.0 of the core library, too? Currently, I can only find version 1.1.49. Thanks
![image](https://user-images.githubusercontent.com/19600534/67934443-356ede00-fbc8-11e9-9e08-779ce5924f49.png)

**Comment by urswiss** [comment]
could it be that the library was renamed from `springdoc-openapi-core` to `springdoc-openapi-webmvc-core`?

![image](https://user-images.githubusercontent.com/19600534/67938902-b4681480-fbd0-11e9-919d-49825eec3629.png)

**Comment by Stexxen** [comment]
That is exactly what has happened, and probably why the version was bumped the way it was.
See : 
https://github.com/springdoc/springdoc-openapi/commit/44f50ad654fdfe8c5fc3842eb51a593021819643#diff-7addfdb1ce1bb7bcede1a2fc54d03b2b

**Comment by springdoc** [comment]
Hi @urswiss , 

 The springdoc-openapi-core has been renamed to springdoc-openapi-webmvc-core spring with the last 1.2.0 release.

 If you use the springdoc-openapi-ui dependency and you want to upgrade to 1.2.0, its transparent. (You just need to change the version in your pom.xml)

 If you are using only the core dependency in your project, without the ui, you will have to change dependency artifactid name to:
 
```xml
  <dependency>
      <groupId>org.springdoc</groupId>
      <artifactId>springdoc-openapi-webmvc-core</artifactId>
      <version>1.2.0</version>
   </dependency>
```
