### ISSUE TITLE
@JsonIgnore(value = false) not handled correctly

### ISSUE THREAD

**Issue by pgmahoney** [springdoc/springdoc-openapi#1350]
I am using @JsonIgnore(value = false) to override a @JsonIgnore in the interface, but the value property is being ignored such that the property is ignored even if the @JsonIgnore is removed from the interface. Only removing both annotations results in the property being included.

- Spring Boot 2.5.7
- springdoc-openapi-ui 1.5.12

- @JsonIgnore(value = false) should override any @JsonIgnore in a superclass

**Comment by bnasslahsen** [comment]
@pgmahoney, 

Not sure what you really mean by not working correctly.
`@JsonIgnore` is not handled directly in `springdoc-openapi` code.

Start by providing a [Minimal, Reproducible Example - with HelloController](https://stackoverflow.com/help/minimal-reproducible-example) that reproduces the problem and this ticket can be reopened.

**Comment by pgmahoney** [comment]
public class HelloController {

	@PostMapping("/hello")
	public String hello(Hello hello) {
		return "hi";
	}
	
	public static class Hello {
		@JsonIgnore(value = false)
		public String getHello() {
			return "hello";
		}
	}
}

In this example I would expect the "hello" property to be included, as the JsonIgnore is inactive

**Comment by bnasslahsen** [comment]
@pgmahoney, 

This handled in the swagger-core and you can ask for this enhancement for the [swagger-core](https://github.com/swagger-api/swagger-core/issues) instead.

```java
ResolvedSchema resolvedSchema = ModelConverters.getInstance()
				.resolveAsResolvedSchema(
						new AnnotatedType(HelloController.Hello.class));
Assert.notNull(resolvedSchema.schema.getProperties().get("hello"), "I'd like it to be present!");
```

In addition, you have too many workarounds using `springdoc` `customizers`.
