### ISSUE TITLE
Add support for caching based on Locale.

### ISSUE THREAD

**Issue by ianwallen** [springdoc/springdoc-openapi#1354]
**Describe the feature**
Caching does not seem to take locale into account.

https://github.com/springdoc/springdoc-openapi/blob/f86c3256594dca2f6e11ee67c2c71a7da8be4134/springdoc-openapi-common/src/main/java/org/springdoc/core/OpenAPIService.java#L727-L729

This can causes the wrong language to be displayed.

**To Reproduce**
Turn on caching (`springdoc.cache.disabled=false`)
Generate first request to swagger page using English locale
Generate second request swagger page using French locale

**Expected behavior**
I would expect that the second request using the French locale would return the French content however it returns the cached data which is the English content.

Note: Doing the reverse produces the opposite results. i.e. French local first and then English locale second will end up producing French data for the English locale.

**Additional context**
Work around seems to be to set 
`springdoc.cache.disabled=true`

**Comment by bnasslahsen** [comment]
@oscarTala, 

Make sure you post clear issue.

You can follow the  [contributing guidelines](https://github.com/springdoc/springdoc-openapi/blob/master/CONTRIBUTING.adoc)
All the relevant information are listed.

Do not create any other issues. You can update this ticket and we can reopen it.

**Comment by ianwallen** [comment]
Please see unit test 
https://github.com/ianwallen/springdoc-openapi/tree/1354_unit_test_170

It fails but if you uncomment the following, it will work

`//@TestPropertySource(properties = Constants.SPRINGDOC_CACHE_DISABLED + "=true")`

**Comment by bnasslahsen** [comment]
Well the cache as implemented, is not based on Locale.
This is not a bug, But feature request...
Are you willing to propose a PR for it ?
