### ISSUE TITLE
Add support for @Tag description using i18n

### ISSUE THREAD

**Issue by ianwallen** [springdoc/springdoc-openapi#1355]
**Describe the feature**

Tag description attribute does not apply properties values

**To Reproduce**
In unit test
Add the following property
`test=This is a test message`
Run unit test App14
And look at the produced json.

**Expected behavior**
With the following properties

```
greeting=Hello! Welcome to our website!
test=This is a test message

```

And the following tag

`@Tag(name = "greeting", description = "test")`

I would expect it to product 

`"name":"Hello! Welcome to our website!","description":"This is a test message"`

But it produced

`"name":"Hello! Welcome to our website!","description":"test"`

**Comment by bnasslahsen** [comment]
@ianwallen, 

Same as #1354. This is not a bug, but a feature request.
When Locale support is introduced, only Tag Name is covered.
You can read the enhancement request here https://github.com/springdoc/springdoc-openapi/issues/1268
