### ISSUE TITLE
Add support for `AsyncAPI` so that the `springdoc` can be used to describe `Websocket`

### ISSUE THREAD

**Issue by linghengqian** [springdoc/springdoc-openapi#1361]
**Is your feature request related to a problem? Please describe.**
- A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
- What is the actual result using OpenAPI Description (yml or json)?

Yes, This issue is related to https://github.com/springdoc/springdoc-openapi/issues/1203 . In fact, the question I want to ask has nothing to do with `Swagger`. Describing `websocket` in `swagger` seems to be an unsupported thing.  So I thought of the `AsyncAPI` that can be used to describe `Websocket`. But it doesn't seem to have a well-known application in the `spring` ecology, I hope `springdoc` can consider it.

**Describe the solution you'd like**
- A clear and concise description of what you want to happen.
- What is the expected result using OpenAPI Description (yml or json)?

`AsyncAPI` is very similar to the `OpenAPI` specification, but `AsyncAPI` is designed for event-driven messaging APIs, including `WebSocket` API. Since I am not sure where to provide such an issue in `springdoc`, I posted this issue to `springdoc-openapi`. This may be a project similar to the name of `springdoc-asyncapi` in the future, rather than as an extension of `springdoc-openapi`.

**Describe alternatives you've considered**
- A clear and concise description of any alternative solutions or features you've considered.

I'm not sure about any alternatives. After all, `swagger-socket` has been out of maintenance for a long time.
(  https://github.com/swagger-api/swagger-socket )

**Additional context**
- Add any other context or screenshots about the feature request here.

Here are some links I refer to.
- https://community.smartbear.com/t5/Swagger-Open-Source-Tools/May-I-use-swagger-to-describe-websocket/td-p/184531?sbsearch=websocket
-  https://www.asyncapi.com/
- https://github.com/asyncapi/java-spring-template

**Comment by bnasslahsen** [comment]
@linghengqian, 

You are not the first one asking for this feature 👍  
But are you willing to provide any PR for it ?

**Comment by linghengqian** [comment]
> @linghengqian,
> 
> You are not the first one asking for this feature 👍 But are you willing to provide any PR for it ?

I'm sorry I don't have experience in this area to try to implement it. I'm just curious if the springdoc community has similar goals to achieve the description of `websocket`. The first thing I thought of was `AsyncAPI`, so I raised this issue.
