### ISSUE TITLE
What is the relationship between OpenAPI and GroupedOpenApi? 

### ISSUE THREAD

**Issue by a2011318824** [springdoc/springdoc-openapi#1363]
**Is your feature request related to a problem? Please describe.**
- A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
- What is the actual result using OpenAPI Description (yml or json)?

**Describe the solution you'd like**
Can all groups only share one OpenAPI?
I want each group to have its own OpenApi configuration.

**Describe alternatives you've considered**
- A clear and concise description of any alternative solutions or features you've considered.

**Additional context**
- Add any other context or screenshots about the feature request here.

**Comment by bnasslahsen** [comment]
The `OpenAPI` bean represents your OpenAPI definition.
When you define a `GroupedOpenApi`, each `GroupedOpenApi`  can have its own `OpenAPI` definition.
For that, you use `OpenApiCustomiser` as follow:

```java
@Bean
public GroupedOpenApi apiV1() {
    return GroupedOpenApi.builder()
        .addOpenApiCustomiser(a -> a.info(
            new Info()
                .title("My Cool API")
                .description("API Documentation")
                .version("V1")
        ))
        .group("v1")
        .packagesToScan("com.my.company.api.v1.resources")
        .build();
}
```

**Comment by a2011318824** [comment]
Thank you very much for your answer.

I have one more question.
how to manually generate a api Infomation by params?
I use the dynamic controller of springboot and I hope that while generating a API, I can also add the corresponding swgger documentation
