### ISSUE TITLE
MediaType "loginRequestBody" should be "application/json"

### ISSUE THREAD

**Issue by quaff** [springdoc/springdoc-openapi#1365]
https://github.com/springdoc/springdoc-openapi/blob/cfe86b6554bd46e2e4b74f686d1e9837fee65f29/springdoc-openapi-security/src/main/java/org/springdoc/security/SpringDocSecurityConfiguration.java#L126

I have not seen any content type named `loginRequestBody`, and the content of request actually is `application/json`, am I missing something?

**Comment by bnasslahsen** [comment]
@quaff, 

Is this nice a nice to have enhancement, or are you facing an issue ?

**Comment by quaff** [comment]
> @quaff,
> 
> Is this nice a nice to have enhancement, or are you facing an issue ?

Yes, request content type always be `loginRequestBody` in Swagger UI, will be rejected by server.

**Comment by bnasslahsen** [comment]
@quaff, 

I have added a fix.  Don't hesitate to validate it with the latest SNAPSHOT.

**Comment by quaff** [comment]
It fixed now.
