### ISSUE TITLE
Swagger UI - Aggregate external endpoints using springdoc.swagger-ui.urls.* is not working

### ISSUE THREAD

**Issue by asakchris** [springdoc/springdoc-openapi#1366]
**Describe the bug**
I was trying to aggregate external endpoints in one single swagger UI application by following [this](https://springdoc.org/faq.html#how-can-i-agreagte-external-endpoints-exposing-openapi-3-spec-inside-one-single-application) documentation, but it is not working.

**To Reproduce**
- What version of spring-boot you are using?
2.6.0
- What modules and versions of springdoc-openapi are you using?
org.springdoc:springdoc-openapi-ui:1.5.13
- Provide with a sample code (HelloController) or Test that reproduces the problem
Refer [this](https://github.com/asakchris/swagger-ui-external-api) sample application in github.
Using below properties to configure external API, but it is still showing Explore search bar:
```
springdoc.swagger-ui.urls[0].name=Pet Store
springdoc.swagger-ui.urls[0].url=https://petstore.swagger.io/v2/swagger.json
springdoc.swagger-ui.urls[1].name=Weather
springdoc.swagger-ui.urls[1].url=https://idratherbewriting.com/learnapidoc/docs/openapi_spec_and_generated_ref_docs/openapi_openweathermap.yml
```

**Expected behavior**
The properties *springdoc.swagger-ui.urls.** has no effect, it is still showing *Explore* search bar. The top bar should show the *Select a definition* combo with *Pet Store* and *Weather* as values.

**Screenshots**
[Swagger UI](http://localhost:8080/swagger-ui/index.html) still shows *Explore* search bar, refer below screen shot:
![image](https://user-images.githubusercontent.com/15003620/145059839-3f26939b-6080-4c19-bc82-74a6ff4a1c88.png)

**Comment by bnasslahsen** [comment]
@asakchris, 

Not reproducible.
Your sample is just working fine.

**Comment by asakchris** [comment]
@bnasslahsen Are you able to see dropdown with Pet Store and Weather as values? I still see Explore bar as below:

![image](https://user-images.githubusercontent.com/15003620/145063737-cce703fd-2f0d-4bff-b2c9-abaa3b86ad27.png)

**Comment by bnasslahsen** [comment]
@asakchris, 

This is the result: 
![image](https://user-images.githubusercontent.com/13404829/145107980-237f5db0-4fc4-401b-9521-b62eda674f30.png)

If you believe you are facing an issue, i encourage you to provide a unit test that shows your issues. (you can find samples in  the s`pringdoc-openapi-ui` project tests)

**Comment by asakchris** [comment]
@bnasslahsen I don't have the content of html page with "Select a definition", so I have added a test to make sure html content is not the default one with "Explore" and the test failed. Please refer [this](https://github.com/asakchris/swagger-ui-external-api/blob/main/src/test/java/com/test/SwaggerUiTest.java) test.

**Comment by bnasslahsen** [comment]
@asakchris, 

The test `shouldNotHaveDefaultContent` is not correct. It's normal to have equal contents.

Not that http://localhost:8080/swagger-ui/index.html will return "No API definition provided."
In your case, you should use the following url: http://localhost:8080/swagger-ui/index.html?configUrl=/v3/api-docs/swagger-config.
