### ISSUE TITLE
How to Specify responseContainer in swagger3 

### ISSUE THREAD

**Issue by himabindu2781** [springdoc/springdoc-openapi#1367]
here  is my code

@ApiOperation(value = "Returns attribute details based on search criteria.", 
				response = AttrSearchResultDTO.class, responseContainer = "List")
    @ApiResponses(value = { 
			@ApiResponse(code = 200, message = "Success"),
			@ApiResponse(code = 400, message = "Invalid Input"),
			@ApiResponse(code = 404, message = "Not Found"), 
			@ApiResponse(code = 500, message = "Internal Server Error"), })

after upgrade swagger3 to swagger2:

@Operation(summary = "Returns attribute details based on search criteria.", 
				responses = {  -------------------------------?
			@ApiResponse(responseCode ="200", description = "Success"),
			@ApiResponse(responseCode ="400", description = "Invalid Input"),
			@ApiResponse(responseCode ="404", description = "Not Found"), 
			@ApiResponse(responseCode ="500", description = "Internal Server Error"), })

how to add response of DTO class and responseContainer . please sugges.

**Comment by bnasslahsen** [comment]
@himabindu2781, 

This question is related to swagger [annotations usage](https://github.com/swagger-api/swagger-core/wiki/Swagger-2.X---Annotations).

If the documentation is not enough. Make sure you provide a concrete sample.

**Comment by kamalbadri** [comment]
> @himabindu2781,
> 
> This question is related to swagger [annotations usage](https://github.com/swagger-api/swagger-core/wiki/Swagger-2.X---Annotations).
> 
> If the documentation is not enough. Make sure you provide a concrete sample.
His question is pretty clear and his example is concrete enough.

**Comment by kamalbadri** [comment]
> @himabindu2781,
> 
> This question is related to swagger [annotations usage](https://github.com/swagger-api/swagger-core/wiki/Swagger-2.X---Annotations).
> 
> If the documentation is not enough. Make sure you provide a concrete sample.

His question is pretty clear and his example is concrete enough.

**Comment by yura2201** [comment]
I've just came across the same problem and managed to deal with it. 
Although the issue looks abandoned, this page is on top of the google indexes, so I suppose I'll be useful for anyone if I put a convenient way of container declaration. Now we should use an `@ArraySchema` within the `@Schema`:
@Operation(summary = "Returns attribute details based on search criteria.",
        responses = @ApiResponse(content = @Content(mediaType = MediaType.APPLICATION_JSON_VALUE,
            array = @ArraySchema(schema = @Schema(implementation = AttrSearchResultDTO.class)))))

**Comment by tymfear** [comment]
> I've just came across the same problem and managed to deal with it. Although the issue looks abandoned, this page is on top of the google indexes, so I suppose I'll be useful for anyone if I put a convenient way of container declaration. Now we should use an `@ArraySchema` within the `@Content`:
> 
> ```
> @Operation(summary = "Returns attribute details based on search criteria.",
>         responses = @ApiResponse(content = @Content(mediaType = MediaType.APPLICATION_JSON_VALUE,
>             array = @ArraySchema(schema = @Schema(implementation = AttrSearchResultDTO.class)))))
> ```

Would be also useful to have and older version example for comparison
