### ISSUE TITLE
Hide/Show an API based on a property

### ISSUE THREAD

**Issue by viccsjain** [springdoc/springdoc-openapi#1368]
**Is your feature request related to a problem? Please describe.**
We are using springdoc-openapi in our spring boot project to generate the swagger documentation. Recently we had a requirement to add some properties (feature flag). I can use the @hidden property to hide an API, but I would like to have this based on a flag. 

**Describe the solution you'd like**
Can @hidden annotation support true/false based on some property? With that we can enable the feature flags at method level. 

**Describe alternatives you've considered**
I have tried using openApiCustomizer but somehow "customize" method never called for that class.
I was thinking i can customize the OpenAPI definition in that class to remove specific methods based on property.

**Comment by bnasslahsen** [comment]
@viccsjain, 

For enhancing `@Hidden `, this is not a springdoc-openapi annotation. (but swagger-core project)
Define groups of API (`GroupedOpenApi`)  that can be different and even conditionnally loaded depending on your own properties.
