### ISSUE TITLE
Empty api definitions in spring-cloud-gateway after update to 1.5.13

### ISSUE THREAD

**Issue by SnakeSVx** [springdoc/springdoc-openapi#1369]
**Describe the bug**
- If you are reporting a bug, please help to speed up problem diagnosis by providing as much information as possible:
- A clear and concise description of what the bug is: the title of an issue is not enough

Spring-cloud-gateway fails to show the correct api-docs together with external api remotes using a loadbalancer starting from 1.5.13.
Problem is most likely caused with the changes from the following commit: https://github.com/springdoc/springdoc-openapi/commit/b12677973565527d9be86424ca080be08bde1716

Everything works fine when reverting back to 1.5.12.

**To Reproduce**
- What version of spring-boot you are using? 2.6.1 with spring-cloud 2021.0.0
- What modules and versions of springdoc-openapi are you using? webflux-core and webflux-ui
- What is the actual and the expected result using OpenAPI Description (yml or json)? json
- Provide with a sample code (HelloController) or Test that reproduces the problem

**Expected behavior**
- A clear and concise description of what you expected to happen. The remote api-docs to be shown
- What is the expected result using OpenAPI Description (yml or json)? a blanks json docs file.

**Screenshots**

Expected (using 1.5.12)

![image](https://user-images.githubusercontent.com/271542/145177238-e031b382-7d40-4274-9a27-9385e9edde26.png)

Received (using 1.5.13)

![image](https://user-images.githubusercontent.com/271542/145177840-b0f23910-d923-428c-a0de-77c720c6dc58.png)

**Additional context**

Since 1.5.13 MultipleOpenApiWebFluxResource seems to overrule the configured loadbalanced paths.
In 1.5.13 with MultipleOpenApiWebFluxResource (ui is disabled then) a manual call to v3/api-docs/MyGroup returns the correct json from the loadbalanced remote.

With MultipleOpenApiWebFluxResource enabled the json response is as follows: 

![image](https://user-images.githubusercontent.com/271542/145177890-1ad825ac-60b2-488c-a296-f72b1a0d5a17.png)

**Comment by bnasslahsen** [comment]
@SnakeSVx, 

Just not reproducible.
You have [here a full sample](https://github.com/springdoc/springdoc-openapi-demos/tree/master/springdoc-openapi-microservices), using spring-cloud-gateway `v2021.0.0` and spring-boot `v2.6.1`.
This [sample is also deployed here](http://158.101.191.70:8060/).

If you believe you are facing a bug. Make sure you provide a [minimal reproducible sample](https://stackoverflow.com/help/minimal-reproducible-example).
