### ISSUE TITLE
How to specify responseContainer in swagger2 upgrade to swagger3

### ISSUE THREAD

**Issue by himabindu2781** [springdoc/springdoc-openapi#1371]
I working on a Migration from Springfox to Springdoc with Swagger version 3.0.0

 <groupId>org.springdoc</groupId>
	      <artifactId>springdoc-openapi-ui</artifactId>
	      <version>1.5.12</version>
	   </dependency>

Therefore the Annotations must be rewritten and I cant find the equivalent Annotations for the old Swagger Annotations.

I have this API Controller:

@GetMapping
@ApiOperation(value = "Load Building")
@ApiResponses(value = {
   @ApiResponse(code = 200, message = "OK", response = Building.class, responseContainer = "List")
})
public ResponseEntity<Page<Building>> getBuilding(Pageable building) {
   final Page<Building> building = buildingrepo.findAll(page).map(bw -> mapper.map(bd, Building.class));

return ResponseEntity.ok().body(building);
With the new Swagger Annotation it must be re-written, but I don`t know how i put the  "responseContainer" 

@GetMapping
@Operation(summary = "Load Building")
@ApiResponses(value = {
   @ApiResponse(responseCode = "200", 
                description = "OK",
                content = @Content(schema = @Schema(implementation = Building.class))) // <--- Here i need the List class somehow as Container!!!
})
public ResponseEntity<Page<Building>> getBuilding(Pageable building) {
   final Page<Building> building = buildingrepo.findAll(page).map(bw -> mapper.map(bd, Building.class));

return ResponseEntity.ok().body(building);

The Output Response in the Api Docs schould look like this:

responses:
  200:
    schema: 
      $ref: "#/definitions/Page<Building>"
And also in the Swagger UI as Example:

{
  "content": [
    { Building: "" }
   ]
}
I cant find the right Parameter for the "responseContainer"

**Comment by bnasslahsen** [comment]
@himabindu2781, 

I am deleting this ticket as duplicate.
Make sure you format your code and add relevant information to the original ticket, so it can be reopened.
