### ISSUE TITLE
@JsonIgnore is not worked for @ParameterObject

### ISSUE THREAD

**Issue by asiaon123** [springdoc/springdoc-openapi#1375]
I'm using @ParameterObject for query string object, and i want to ignore some properties with @JsonIgnore, but i still listed in the swagger page.

Here is an example:
```java

@GetMapping()
public Resp xxx(@ParameterObject SomeRequstObj request) {

}

public class SomeRequestObj {

    ....

    @JsonIgnore
    private Integer someProperies;

}

```

**Comment by bnasslahsen** [comment]
You can use `@Hidden` or `@Parameter(hidden = true)` as alternatives.
Or use: 

```java
SpringDocUtils.addAnnotationsToIgnore(JsonIgnore.class);
```

This will be set as default in the future release.
