### ISSUE TITLE
Docs not being generated for @controller class

### ISSUE THREAD

**Issue by ucraida** [springdoc/springdoc-openapi#138]
This does not generate any documentation unless I change @Controller to @RestController, even though ResponseBody is declared on the method. 

```
package com.package.controllers;

import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.responses.ApiResponses;
import org.springframework.http.HttpStatus;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.bind.annotation.ResponseStatus;

@Controller
@Tag(name =  "health")
public class HealthServiceController {

    /**
     * Ping endpoint used for health checks.
     */
    @RequestMapping(value = "/ping", method = RequestMethod.GET)
    @Operation(summary = "Simple health check")
    @ApiResponses({
        @ApiResponse(responseCode = "200",description = "OK")
    })
    @ResponseBody
    @ResponseStatus(HttpStatus.OK)
    public Boolean ping() {
        return true;
    }
}
```

**Comment by springdoc** [comment]
Hi, 

 The fix for this issue, will be available on v1.2.3 version of springdoc-openapi.

**Comment by ucraida** [comment]
That was fast. So to be clear just defining @Controller without @ResponseBody  will not create documentation currently, correct? Is there plans to support @Controller without @ResponseBody?

**Comment by springdoc** [comment]
Hi, 

 @Controller annotation is not enough to create REST API documentation.  
 If you have a clear rule of how to identify, @Controller without @ResponseBody as a REST API, we will be happy to support.

**Comment by ddcruver** [comment]
What about looking for RequestMapping?

**Comment by bnasslahsen** [comment]
not enough.

**Comment by ddcruver** [comment]
With spring you can return ResponseEntity instead of the body of the response. Springfox supported this use case.  It may not be able to detect information about the return type but isn't that what @ApiResponses can provide?

**Comment by bnasslahsen** [comment]
If you any related feature or bug request, you can have a look to the contribution guide:
https://github.com/springdoc/springdoc-openapi/blob/master/CONTRIBUTING.adoc
