### ISSUE TITLE
Missing paths after upgrading from Spring Docs 1.5.13 to 1.6.0

### ISSUE THREAD

**Issue by mathieu-amblard** [springdoc/springdoc-openapi#1381]
**Describe the bug**
After upgrading from Spring Docs 1.5.13 to 1.6.0, we lost all paths of our application except the Actuator ones.

**To Reproduce**
- What version of spring-boot you are using? We have tried with 2.3.11.RELEASE and  2.5.7.
- What modules and versions of springdoc-openapi are you using? 1.6.0
```xml
        <dependency>
            <groupId>org.springdoc</groupId>
            <artifactId>springdoc-openapi-webmvc-core</artifactId>
            <version>1.6.0</version>
        </dependency>
        <dependency>
            <groupId>org.springdoc</groupId>
            <artifactId>springdoc-openapi-ui</artifactId>
            <version>1.6.0</version>
        </dependency>
```

We have also the following properties :
```properties
springdoc.api-docs.path=/swagger.json
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.show-actuator=true
springdoc.paths-to-exclude=/error
management.endpoints.web.base-path=/rest/actuator
```

**Expected behavior**
We expect to get both, paths from actuator and and paths from our application.

**Additional context**
By modifying the actuator base path property as following it is working :
```properties
management.endpoints.web.base-path=/
```
But we cannot change it.

It seems, that this change cause the issue.
1.5.13 :
https://github.com/springdoc/springdoc-openapi/blob/v1.5.13/springdoc-openapi-common/src/main/java/org/springdoc/core/customizers/ActuatorOpenApiCustomizer.java#L38-L40

You use the `filter` method so the paths are kept.

1.6.0 :
https://github.com/springdoc/springdoc-openapi/blob/master/springdoc-openapi-common/src/main/java/org/springdoc/core/customizers/ActuatorOpenApiCustomizer.java#L37-L39

You use the `removeIf` method so the paths are removed.

**Comment by pfund** [comment]
I confirm this. Only adding

`springdoc.show-actuator=true`

Will show the actuator endpoints but remove the other ones

**Comment by bnasslahsen** [comment]
@mathieu-amblard, 

You can test with the [latest SNAPSHOT](https://springdoc.org/#how-can-i-use-the-last-springdoc-openapi-snapshot).
v`1.6.1` will be released shortly.
