### ISSUE TITLE
Bidirectional relationships not work well

### ISSUE THREAD

**Issue by asiaon123** [springdoc/springdoc-openapi#1382]
For bidirectional relationships, it just rendering as string prop.

I have object like this, and annotated with @JsonManagedReference and @JsonBackReference

```java
public class Node {
    private Integer id;
    private String name;

    @JsonBackReference
    private Node parent;

    @JsonManagedReference
    private List<Node> children;

}
```

but, on the swagger ui, it renders like this: 

```json
{
  "id": 0,
  "name": "string",
  "parent": "string",
  "children": [
    "string"
  ]
}
```

Which i think should not be rendered as a string when it's a OBJECT with structure

**AND** also, as well as `@JsonManagedReference`, `@JsonIdentityInfo`, `@JsonView` not work too.

**Comment by bnasslahsen** [comment]
@asiaon123, 

 The generated Schema is correct:

```yaml
Node:
    type: object
    properties:
      id:
        type: integer
        format: int32
      name:
        type: string
      parent:
        $ref: '#/components/schemas/Node'
      children:
        type: array
        items:
          $ref: '#/components/schemas/Node'   
```
