### ISSUE TITLE
Add support for BasePathAwareController

### ISSUE THREAD

**Issue by crizzis-unordinal** [springdoc/springdoc-openapi#1383]
**Describe the feature**
Using `@BasePathAwareController` does not result in any endpoints generated in the OpenAPI

**To Reproduce**
- Create a `@BasePathAwareController`-annotated controller
- Start app and navigate to generated API Docs

**Expected behavior**
- Operations defined inside `@BasePathAwareController` get declared in the generated API Docs

**Screenshots**

Assume there is a base repository rest resource `user-profile` declared as `@RepositoryRestResource(collectionResourceRel = "profiles", path = "profiles")`. When declaring an extension to the base API using:

```
@Tag(name = "user-profile-projects", description = "Managing user profile projects")
@RestController
```

we get: 

<img width="1486" alt="Zrzut ekranu 2021-12-14 o 12 43 20" src="https://user-images.githubusercontent.com/95409665/145992052-5bca2435-0d21-49ec-bfcd-9ba44f0afea9.png">

However, switching to:

```
@Tag(name = "user-profile-projects", description = "Managing user profile projects")
@BasePathAwareController
```

results in: 
<img width="1611" alt="Zrzut ekranu 2021-12-14 o 12 44 25" src="https://user-images.githubusercontent.com/95409665/145992204-f4a16f3b-bdb5-4891-a709-c2b39a549937.png">

where `user-profile-projects` is gone. 

**Additional context**

Tried with both 1.5.2 and 1.6.0. This bug probably means `@RepostoryRestController` is ignored, too.

**Comment by bnasslahsen** [comment]
@crizzis-unordinal, 

Not a bug but a feature request ...
And `@RepostoryRestController` is already supported.

**Comment by crizzis-unordinal** [comment]
@bnasslahsen 

> Not a bug but a feature request ...

Depends on the point of view, really. The docs say 'This dependency [springdoc-openapi-data-rest] enables the support of spring-boot-starter-data-rest types like: @RepositoryRestResource and QuerydslPredicate annotations.' 

I think it is not unreasonable to assume **all** spring-boot-starter-data-rest types are implied here. But fair enough.

**Comment by bnasslahsen** [comment]
@crizzis-unordinal 

This #1053 shows you it's not implemented. We stopper at `@RepositoryRestController` which covered the majority of use cases. 

Are you willing to propose a PR for this enchantement ?

**Comment by gdl276s** [comment]
Can someone explain to me why this ticket is called "Add support for BasePathAwareController" and the solution was to "Add support for RepositoryRestController"?  Could we not knock out both in one swoop with this ticket?

**Comment by bnasslahsen** [comment]
@gdl276s ,

why are you saying:  the solution was to "Add support for RepositoryRestController" ? Did you see the [commit](https://github.com/springdoc/springdoc-openapi/commit/b2fecd1cc7cc32392e3cddbe777a903af3f4173f)?

**Comment by gdl276s** [comment]
@bnasslahsen sorry, maybe I was confused with #1053
