### ISSUE TITLE
validator.swagger.io should not be used as a default

### ISSUE THREAD

**Issue by waschmittel** [springdoc/springdoc-openapi#1385]
I just realized that Swagger UI as included in springdoc-openapi makes requests to validator.swagger.io with the default settings.

This effectively sent URLs of our internal services to validator.swagger.io, which was not what we intended.

Since this was a surprising default (for me), I'd suggest a different one (`springdoc.swagger-ui.validator-url: null`)

**Comment by bnasslahsen** [comment]
@waschmittel, 

There are no plans to change the default validation.
