### ISSUE TITLE
Disable validation for 1.6.1

### ISSUE THREAD

**Issue by mathieu-amblard** [springdoc/springdoc-openapi#1386]
**Describe the bug**
After upgrading from Spring Docs 1.5.13 to 1.6.1, Swagger UI validation is enabled.

**To Reproduce**
- What version of spring-boot you are using? We have tried with 2.3.11.RELEASE and 2.5.7.
- What modules and versions of springdoc-openapi are you using? 1.6.1
```xml
        <dependency>
            <groupId>org.springdoc</groupId>
            <artifactId>springdoc-openapi-webmvc-core</artifactId>
            <version>1.6.1</version>
        </dependency>
        <dependency>
            <groupId>org.springdoc</groupId>
            <artifactId>springdoc-openapi-ui</artifactId>
            <version>1.6.1</version>
        </dependency>
```
We have also the following properties :
```properties
springdoc.api-docs.path=/swagger.json
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.show-actuator=true
springdoc.paths-to-exclude=/error
```

**Expected behavior**
- We do not change the `springdoc.swagger-ui.validatorUrl` property, so we expect that Swagger UI validation is disabled by default as mentioned in the documentation : https://springdoc.org/#swagger-ui-properties

**Comment by bnasslahsen** [comment]
@mathieu-amblard, 

The validation has been enabled by default, with the last release. This related to the upgrade the swagger-ui `v4.1.3`.
You can keep the old compatibility mode using (Not recommended):   `springdoc.swagger-ui.queryConfigEnabled=true`

Documentation is now updated: You can disable the validation using:
```properties 
springdoc.swagger-ui.validator-url=none
```
We will try to make it the default behavior again for the next release, as you are not the first one asking for it.
