### ISSUE TITLE
Spring doc version 1.6.2 not published to maven repository or oss.sonatype.org

### ISSUE THREAD

**Issue by neoneo008** [springdoc/springdoc-openapi#1390]
**Describe the bug**
Spring doc version 1.6.2 not published to maven repository or oss.sonatype.org 
**To Reproduce**
Version upto 1.6.1 published. 
[https://mvnrepository.com/artifact/org.springdoc/springdoc-openapi-ui](url)
[https://oss.sonatype.org/content/groups/public/org/springdoc/springdoc-openapi-ui/](url)

**Expected behavior**
1.6.2 version should be published as per the release notes [https://github.com/springdoc/springdoc-openapi/releases](url)

**Screenshots**
![image](https://user-images.githubusercontent.com/12123685/146404393-66ce48cf-33db-45ab-aa6c-85b872ff5a03.png)

![image](https://user-images.githubusercontent.com/12123685/146403668-40104f18-15e8-4f39-8027-33b431da69ce.png)

**Comment by bnasslahsen** [comment]
@neoneo008, 

Refer to the current version here (https://springdoc.org/).
And wait for the next release. 
We depend on nexus availbility for releases which is not so good lately.

**Comment by bnasslahsen** [comment]
This ticket is being deleted, as it creates confusion
