### ISSUE TITLE
Q: Conversion from Springfox 2.9.2 .... support for operations in method names (xxxxUsingGET, ....)?

### ISSUE THREAD

**Issue by SaschaAusUlm** [springdoc/springdoc-openapi#1391]
Hi!

We're converting from Springfox 2.9.2 and testing Springdoc.

Quick question. 
In Springfox it is possible to have the operation extending the method name and you will get an operationId à la

"operationId":"saveGroups**UsingPOST**"

which is kind of nice (not everyone likes it, I do).

How would I achieve the same in Springdoc?

Thanks in advance.

**Comment by bnasslahsen** [comment]
@SaschaAusUlm, 

Use `OpenApiCustomiser`.
This is sample code that you have to test and adapt:

```java
@Bean
public OpenApiCustomiser changeOperationId() {
	return openApi -> openApi.getPaths().values().stream().forEach(pathItem ->
			pathItem.readOperationsMap()
					.forEach((httpMethod, operation) -> operation.setOperationId(operation.getOperationId() + "Using" + httpMethod)));
}
```

**Comment by SaschaAusUlm** [comment]
Thanks a lot for the quick reply

**Comment by hostops** [comment]
Should this be added to documentation in section #migrating-from-springfox?
It would spare me a few hours of searching.
