### ISSUE TITLE
Update to 1.6.1 exposes internal API URL to validator.swagger.io

### ISSUE THREAD

**Issue by Agh42** [springdoc/springdoc-openapi#1399]
**Describe the bug**
We recently updated org.springdoc:springdoc-openapi-ui:1.5.13 to org.springdoc:springdoc-openapi-ui:1.6.1. We observed a change in behaviour (without other configuration changes on our side): every time we call our internal API, an external request is sent to an AWS server with our internal API URL as a parameter.

I know that there is a `validatorUrl` configuration setting, but we did not actively set it in the past or now.

I supposed this is related to #1386 but it does not appear fixed in v1.6.1:

**To Reproduce**
Use libraries and versions:
```
org.springframework.boot 2.6.1
org.springdoc:springdoc-openapi-ui:1.6.1
io.swagger.core.v3:swagger-core:2.1.11
```

The only configuration regarding springdoc that we have in application.yaml is:
``` 
springdoc:
  swagger-ui:
    disable-swagger-default-url: true
```

When calling our internal URL:

 `https://redacted.example/contextpath/swagger-ui/index.html?configUrl=/contextpath/v3/api-docs/swagger-config`

the following request is made:

`https://validator.swagger.io/validator?url=https%3A%2F%2Fredacted.example%2Fcontextpath%2Fswagger-ui%2Findex.html`

**Expected behavior**
No call should be made to an external URL (validation.swagger.io) by default. (Since this is potentially a security issue when private parts of the URI are exposed to an external service hosted by a 3rd party.)

IMHO a safe default setting for validationUrl should be "none" or "localhost".

**Comment by bnasslahsen** [comment]
@Agh42, 

Please read the [contribution guide](https://github.com/springdoc/springdoc-openapi/blob/master/CONTRIBUTING.adoc).
Clearly mentioned: **If you are starting using springdoc-openapi, we advise you to use the last available release.**

And in the [Changlog](https://github.com/springdoc/springdoc-openapi/blob/master/CHANGELOG.md) or [release notes](https://github.com/springdoc/springdoc-openapi/releases/tag/v1.6.2), or even on the [official documentation](https://springdoc.org/) you have all the information to that this request is just outdated.

**Comment by Agh42** [comment]
I did indeed miss the 1.6.2 release from two days ago. Thank you for the quick fix!
