### ISSUE TITLE
Any @GetMapping parameters should be marked as required, even if @RequestParam missing

### ISSUE THREAD

**Issue by membersound** [springdoc/springdoc-openapi#14]
The following should mark the argument as **required*:
```
	@GetMapping(value = "/persons")
	public void persons(@Valid @NotBlank String name) {

	}
```

But in fact this renders to optional.
When adding `@RequestParam` to the parameter, it is rendered correctly.
But in general the `@RequestParam` is an optional parameter for spring mvc. By default, any parameters given in the method are assumed to be `@RequestParam` with `required=true` by spring. So springdoc should assume the same.

**Comment by springdoc** [comment]
Fix will be available on v1.1.7
