### ISSUE TITLE
How can we generate the openapi yml file at compile time?

### ISSUE THREAD

**Issue by ntherrien** [springdoc/springdoc-openapi#140]
Hi!

I am trying to obtain the resulting yml file at compile time instead of at runtime.   Is there a location where the yml file is generated by the plugin which we could use during the tests phase?

- Nicolas

**Comment by springdoc** [comment]
Hi, 

 Please have a look at springdoc-openapi-maven-plugin which can help you generate the yml/json OpenAPI description during build time. 

- https://github.com/springdoc/springdoc-openapi-maven-plugin

 You can customise the output directory (property outputDir). The default value is: ${project.build.directory}

**Comment by bnasslahsen** [comment]
@sjdhanasekaran, 

There are no alternatives availble.
