### ISSUE TITLE
Server set using OpenApiCustomiser only works right after starting up the application

### ISSUE THREAD

**Issue by A-K-L** [springdoc/springdoc-openapi#1400]
The server cannot be set correctly using an OpenAPICustomiser for spring-web-flux (only works for the initial load of the open API spec). I believe the issue is similar to https://github.com/springdoc/springdoc-openapi/issues/1188. Maybe it was only fixed for springdoc-openapi-ui and not springdoc-openapi-webflux-ui ?

**How to reproduce the problem**
Use the following dependencies:
```
spring-boot and spring-boot-starter-webflux 2.4.6
org.springdoc:springdoc-openapi-webflux-ui 1.6.1
```

And the following configuration:

```
import io.swagger.v3.oas.models.OpenAPI;
import io.swagger.v3.oas.models.servers.Server;
import org.springdoc.core.GroupedOpenApi;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

import java.util.List;

@Configuration
public class OpenApiConfig {
    @Bean
    public OpenAPI openApi() {
        return new OpenAPI();
    }

    @Bean
    public GroupedOpenApi apiGroupCustomServer() {
        return GroupedOpenApi
                .builder()
                .addOperationCustomizer((operation, handlerMethod) -> operation)
                .addOpenApiCustomiser(openApi -> openApi.servers(List.of(new Server().url("/"))))
                .group("API_GROUP_WITH_SERVER")
                .build();
    }
}
```

Right after having started the application, I can get the following OpenAPi spec from http://localhost:8080/v3/api-docs/API_GROUP_WITH_SERVER:
`{"openapi":"3.0.1","info":{"title":"OpenAPI definition","version":"v0"},"servers":[{"url":"/"}],"paths":{},"components":{}}`

The server is as defined by the OpenApiCustomier. However, as soon as I reload the page, it no longer respects the OpenApiCustomier. The server will be reverted to the default "http://localhost:8080" until I restart the application:
`{"openapi":"3.0.1","info":{"title":"OpenAPI definition","version":"v0"},"servers":[{"url":"http://localhost:8080","description":"Generated server url"}],"paths":{},"components":{}}`

**Comment by vmckinneyCA** [comment]
For wandering googlers, updating to the latest _does_ fix this issue ^-^
