### ISSUE TITLE
Document that springdoc-openapi is intended to be used as an imported BOM

### ISSUE THREAD

**Issue by mjustin** [springdoc/springdoc-openapi#1403]
Per #1099 & #1256, it looks like `org.springdoc:springdoc-openapi` is designed to be used as a BOM, enforcing the dependency versions in a consuming project to match the version of the BOM.  However, this does not appear to be mentioned in the [project documentation](https://springdoc.org) anywhere that I can see.

If using `org.springdoc:springdoc-openapi` as a BOM by projects using `springdoc-openapi` is intended, it would be helpful to document that fact.  First, it makes this feature more discoverable.  Second, and IMO more importantly, it makes it clear to users of the library that this is a supported usage pattern, and not just taking advantage of internal implementation details that are subject to change without notice in the future.

This issue is therefore a request to update the project documentation to document the usage of `org.springdoc:springdoc-openapi` as a BOM by consuming projects.

**Comment by bnasslahsen** [comment]
Do not create duplicateur
This will be deleted
