### ISSUE TITLE
Using springdoc-openapi as BOM uses Gradle project verson rather than BOM version

### ISSUE THREAD

**Issue by mjustin** [springdoc/springdoc-openapi#1405]
## Describe the bug
I don't see it in the [project documentation](https://springdoc.org), but from springdoc/springdoc-openapi#1099 & springdoc/springdoc-openapi#1256, it looks like `springdoc-openapi` is designed to be used as a BOM, enforcing the dependency versions in the project to match the version of the BOM.

When I use this project as a BOM with Gradle using the [Spring dependency management plugin](https://docs.spring.io/dependency-management-plugin/docs/current/reference/html/), it uses the version of my Gradle project as the SpringDoc versions, rather than the version of the BOM.  For instance, if I have my Gradle project at version 0.0.1, use `org.springdoc:springdoc-openapi:1.6.1` as a BOM, and import `org.springdoc:springdoc-openapi-ui`, the version of `springdoc-openapi-ui` will be 0.0.1, not 1.6.1.

### `build.gradle`

```groovy
plugins {
    id 'org.springframework.boot' version '2.6.1'
    id 'io.spring.dependency-management' version '1.0.11.RELEASE'
    id 'java'
}

group = 'com.example'
version = '0.0.1'
sourceCompatibility = '11'

repositories {
    mavenCentral()
}

dependencyManagement {
    imports {
        mavenBom 'org.springdoc:springdoc-openapi:1.6.1'
        mavenBom 'org.springframework.boot:spring-boot-dependencies:2.6.1'
    }
}

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter'
    implementation 'org.springdoc:springdoc-openapi-ui'
}
```

### Execute

```
$ gradle compileJava

> Task :compileJava FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileJava'.
> Could not resolve all files for configuration ':compileClasspath'.
   > Could not find org.springdoc:springdoc-openapi-ui:0.0.1.
     Required by:
         project :

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s
1 actionable task: 1 executed
```

## Expected behavior
The expected behavior is that the version used for the `springdoc-openapi` BOM be used for the `org.springdoc` dependencies.

**Comment by bnasslahsen** [comment]
@mjustin, 

I have enhanced the BOM support so that we get rid of the `bomProperty` line for next releases.
You can already validate it using the [latest SNAPSHOT](https://springdoc.org/#how-can-i-use-the-last-springdoc-openapi-snapshot).

**Comment by mjustin** [comment]
I can confirm that the updated BOM works as desired in my Gradle project where I found this issue.  Thanks for the quick fix!

**Comment by breun** [comment]
Using `org.springdoc:springdoc-openapi` as a BOM import is dangerous. We tried it, but importing `springdoc-openapi` 1.6.6 as a BOM in our Spring Boot 2.6.5 project caused third-party dependencies like Log4j and Jackson to get downgraded to (vulnerable) older versions. A clean BOM for a project should only manage the versions of the project's own modules, but that is not what `org.springdoc:springdoc-openapi` is.
