### ISSUE TITLE
No longer displays welcome page

### ISSUE THREAD

**Issue by mortenk** [springdoc/springdoc-openapi#141]
Using spring boot 2.2.0
Welcome page is set this way:
@Configuration
public class WebServerStaticResourceConfiguration implements WebMvcConfigurer {
    @Override
    public void addViewControllers(ViewControllerRegistry registry) {
        registry.addViewController("/foo/**").setViewName("forward:/index.html");
        registry.addRedirectViewController("/", "/foo/");
    }
}
After adding springdoc-openapi-ui 1.2.3, the welcome page is no longer displayed.

**Comment by springdoc** [comment]
Hi, 

Just change the path of the swagger documentation as follows, in order not to be in conflict with your configuration:


```properties
# swagger-ui custom path
springdoc.swagger-ui.path=/swagger/swagger-ui.html
```
