### ISSUE TITLE
Springdocs not loading in springboot application and also with custom springmvc configuration

### ISSUE THREAD

**Issue by nnait2** [springdoc/springdoc-openapi#1410]
@bnasslahsen

**Describe the bug**
This is a springboot application: 
**1.**
By adding 'springdoc-openapi-ui' in the pom.xml and also updating application.properties, I was not able to get the springdocs openapi urls to work.( /context-path/swagger-ui.html and /context-path/v3/api-docs).
Assuming that my springboot application autoconfiguration perhaps must have gone out of wack due to some customization, I tried to configure the springdocs openapi as for a springmvc project in the same application.
**2.**
So I followed https://github.com/springdoc/springdoc-openapi/issues/841   by @bnasslahsen
but as soon as i add **@Import**  in the SwaggerConfig.java, the application starts giving following error, application deployment failing with bean initialization failing, as below:
**Error with SpringMvc Configuration:**
o.s.web.context.ContextLoader | Context initialization failed
org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'webSecurityConfig': Unsatisfied dependency expressed through field 'userDetailsService'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'userDetailsService' defined in URL [jar:file:/C:/Java/workspace/nex/nex-web/target/nexWEB-INF/lib/nex-spring-7.3.0.0.jar!/com/xx/xx/xx/spring/security/CNexUserDetailsService.class]: Unsatisfied dependency expressed through constructor parameter 1; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'com.xx.xx.xx.common.services.security.ISecurityService' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {}

If  i comment **@Import**  in the SwaggerConfig.java, the application  deploys, but as expected the springdocs and swagger-ui does not work.

1. Why is the the simple setup as per springdocs openapi springboot application is not working for my project..?
     (By adding 'springdoc-openapi-ui' in the pom.xml and also updating application.properties if necessary)

2. Why when trying to configure the springdocs openapi as springmvc application is breaking the application during deployment..?
  and giving the error  
o.s.web.context.ContextLoader | Context initialization failed
org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'webSecurityConfig': Unsatisfied dependency expressed through field 'userDetailsService'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'userDetailsService' defined in URL [jar:file:/C:/Java/workspace/nex/nex-web/target/nexWEB-INF/lib/nex-spring-7.3.0.0.jar!/com/xx/xx/xx/spring/security/CNexUserDetailsService.class]: Unsatisfied dependency expressed through constructor parameter 1; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'com.xx.xx.xx.common.services.security.ISecurityService' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {}

**Additional context**

Have the following configuration:

**pom.xml**  has following:

		<dependency>
			<groupId>org.springdoc</groupId>
			<artifactId>springdoc-openapi-ui</artifactId>
			<version>1.6.3</version>
		</dependency>

**NexWebApplication .java**
@SpringBootApplication
@EnableAspectJAutoProxy(proxyTargetClass = true)
public class NexWebApplication {
}

**WebMvcConfig .java**
@Configuration
@EnableWebMvc
@ComponentScan(basePackages = "com.xx.xx.xx.*")

@ImportResource({ "/WEB-INF/conf.spring.xml", "/WEB-INF/jndi.spring.xml", "/WEB-INF/dao/dao.spring.xml",
		"/WEB-INF/services/services.spring.xml", "classpath:/web/web.menu.spring.xml" })
public class WebMvcConfig implements WebMvcConfigurer {
...
}

**WebSecurityConfig.java** has following:
@Override
	public void configure(WebSecurity web) {
	web.ignoring().antMatchers("/swagger-ui/**", "/swagger-ui.html", "/api-docs/**", "/v2/api-docs/**","/v3/api-docs/**", "/swagger*/**", "/api/**", 
									"/api/**", "/login**","/error**", "/accessDenied", "/enrollment/requestAccess","/enrollment/submitAccess", "/css/**", "/js/**", "/images/**");
	}

As per solution: https://github.com/springdoc/springdoc-openapi/issues/841
added 
SwaggerConfig.java/ GroupsConfiguration.java as in the thread.

**GroupsConfiguration.java**
@Configuration
public class GroupsConfiguration {

	@Bean
	public GroupedOpenApi publicApi() {
		return GroupedOpenApi.builder().group("user").pathsToExclude("/api/v2/**").pathsToMatch("/api/v1/**").build();
	}

	@Bean
	public GroupedOpenApi adminApi() {
		return GroupedOpenApi.builder().group("admin").pathsToExclude("/api/v1/**").pathsToMatch("/api/v2/**").build();
	}

	@Bean
	public OpenAPI customOpenAPI() {
		return new OpenAPI().components(new Components()).info(new Info().title("Spring MVC REST API")
				.contact(new Contact().name("Rasika Kaluwalgoda")).version("1.0.0"));
	}

}

**SwaggerConfig.java**
@Configuration
@Import({ org.springdoc.core.SpringDocConfigProperties.class,
		org.springdoc.webmvc.core.MultipleOpenApiSupportConfiguration.class,
		org.springdoc.core.SpringDocConfiguration.class, org.springdoc.webmvc.core.SpringDocWebMvcConfiguration.class,
		SwaggerUiConfigParameters.class, SwaggerUiOAuthProperties.class,
		org.springdoc.core.SwaggerUiConfigProperties.class, org.springdoc.core.SwaggerUiOAuthProperties.class,
		org.springdoc.webmvc.ui.SwaggerConfig.class, GroupsConfiguration.class,
		org.springframework.boot.autoconfigure.jackson.JacksonAutoConfiguration.class })
public class SwaggerConfig {
}

**springboot version:**
org.springframework.boot spring-boot-starter-parent 2.5.4

comes with **Spring Version**: spring 5.3.9 jars

Please let me know if more information may be required.

**Comment by nnait2** [comment]
Please let me know if more information may be required.

**Comment by nnait2** [comment]
springboot version:

<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>2.5.4</version>
		<relativePath/> 
	</parent>

comes with:  spring 5.3.9 jars

**Comment by bnasslahsen** [comment]
@nnait2, 

At least make sure you format your description and  [Provide a Minimal, Reproducible Example - with HelloController](https://stackoverflow.com/help/minimal-reproducible-example) that reproduces the problem.

This ticket will be closed and can be reopened if any relevant information is provided.
