### ISSUE TITLE
Init duration for springdoc-openapi causes high cpu usage and long delays

### ISSUE THREAD

**Issue by Pashulity** [springdoc/springdoc-openapi#1413]
**Describe the bug**
Opening `{myhost}/webjars/swagger-ui/index.html` from time to time causes init procedures e.g. 
`[or-http-epoll-1] o.springdoc.api.AbstractOpenApiResource : Init duration for springdoc-openapi is: 9485 ms` which lead to high CPU usage (80-100%) for init period of time.

**To Reproduce**

springBootVersion = 2.5.7
openApiVersion = 1.6.3

```
implementation 'org.springframework.boot:spring-boot-starter-webflux'
implementation "org.springdoc:springdoc-openapi-webflux-ui:$openApiVersion"
implementation "org.springdoc:springdoc-openapi-webflux-core:$openApiVersion"
```

**Expected behavior**
Get rid of this long delays and high CPU usage

**Comment by bnasslahsen** [comment]
@Pashulity, 

Make sure you read the [contribution](https://github.com/springdoc/springdoc-openapi/blob/0a8150b3158447e7ed88215e6bdeae2a7b75808b/CONTRIBUTING.adoc) guide.

And provide all the listed information before raising issues.

**Comment by pqdn** [comment]
We have 200 endpoints
Init duration for springdoc-openapi is: 116960 ms
