### ISSUE TITLE
Not able to send request with body that includes multipart files

### ISSUE THREAD

**Issue by minditer1** [springdoc/springdoc-openapi#1416]
I have a DTO that contains other DTOs and a list of multipart files. I am trying to process that DTO but I can't seem to be able to read the request.

````
class TeacherDTO {
   private SpecializationDto specializationDto;
   private List<MultipartFile> files;
}

@PostMapping(consumes = {MediaType.MULTIPART_FORM_DATA_VALUE},
            produces = {MediaType.APPLICATION_JSON_VALUE})
public ResponseEntity<Object> saveNewTeacher(@ModelAttribute @Valid TeacherDTO teacherDto){

//process request

}
````

When creating an example request from Swagger UI, I get the following exception:
````
type 'java.lang.String' to required type 'SpecializationDto' for property 'specializationDto': no matching editors or conversion strategy found
````

If I put @RequestBody instead of @ModelAttribute then I get
````
Content type 'multipart/form-data;boundary=----WebKitFormBoundaryVEgYwEbpl1bAOjAs;charset=UTF-8' not supported]
````

Swagger dependencies:
````
<dependency>
   <groupId>org.springdoc</groupId>
   <artifactId>springdoc-openapi-ui</artifactId>
   <version>1.5.2</version>
</dependency>
<dependency>
   <groupId>org.springdoc</groupId>
   <artifactId>springdoc-openapi-data-rest</artifactId>
   <version>1.5.2</version>
</dependency>
````

OpenAPI3.0 config:
````
@Configuration
public class OpenApi30Config {

  private final String moduleName;
  private final String apiVersion;

  public OpenApi30Config(
      @Value("${spring.application.name}") String moduleName,
      @Value("${api.version}") String apiVersion) {
    this.moduleName = moduleName;
    this.apiVersion = apiVersion;
  }

  @Bean
  public OpenAPI customOpenAPI() {
    final var securitySchemeName = "bearerAuth";
    final var apiTitle = String.format("%s API", StringUtils.capitalize(moduleName));
    return new OpenAPI()
        .addSecurityItem(new SecurityRequirement().addList(securitySchemeName))
        .components(
            new Components()
                .addSecuritySchemes(securitySchemeName,
                    new SecurityScheme()
                        .name(securitySchemeName)
                        .type(SecurityScheme.Type.HTTP)
                        .scheme("bearer")
                        .bearerFormat("JWT")
                )
        )
        .info(new Info().title(apiTitle).version(apiVersion));
  }
}
````

Stackoverflow question: https://stackoverflow.com/questions/70392548/spring-mvc-post-request-with-dto-that-contains-multipart-files-and-other-dtos

**Comment by bnasslahsen** [comment]
@minditer1, 


First before reporting bugs, make sure you use the last available release, before creating any ticket.

`@ModelAttribute` is related to web views. We are not planning to support it. So any error you are getting about it is normal.


For multipart requests you have to pass them in the [RequestBody](https://spec.openapis.org/oas/latest.html#special-considerations-for-multipart-content) as per the OpenAPI spec.  

Using spring, you can `@RequestPart ` spring annotation to describe the different parts, with the related encoding media type. 
Note that there is a limitation with the current [swagger-ui](https://github.com/swagger-api/swagger-ui) implementation as the encoding attribute is not respected on the request. Similar question has been already answered [here](https://github.com/springdoc/springdoc-openapi/issues/820).

This is sample workaround to this limitation, to make your code work from the `swagger-ui`: 

```java
@PostMapping(consumes =  MediaType.MULTIPART_FORM_DATA_VALUE,
		produces = MediaType.APPLICATION_JSON_VALUE)
public ResponseEntity<Object> saveNewTeacher( @RequestPart(value = "specializationDto") @Parameter(schema =@Schema(type = "string", format = "binary"))  final SpecializationDto specializationDto,
		@RequestPart(value = "files")  final List<MultipartFile> files){
	return null;
}
```
