### ISSUE TITLE
Proxy Routing Cache Problem When Using Swagger-UI

### ISSUE THREAD

**Issue by seymabatige** [springdoc/springdoc-openapi#1419]
Hi,

I've been migrating one of my applications from springfox to springdoc and I've run into the very same problem as in https://github.com/springdoc/springdoc-openapi/issues/331 

I start both my application and the proxy. When I go to swagger ui directly from my application and then through the proxy, it seems to cache the config url and in one of two ways I get :
Failed to load remote configuration error. swagger-config gets 404 due to incorrectly created config url. (When I go through the application endpoint, it adds the forwarded prefix, 
or when I go through the proxy, it lacks the forwarded prefix)

I added "server.forward-headers-strategy:framework" to my application yml file and in my swagger config class I added the following bean :

    @Bean
    fun forwardedHeaderFilter(): ForwardedHeaderFilter? {
        return ForwardedHeaderFilter()
    }

I also disabled springdoc cache as suggested in issue 331. However, it didn't work and when I debug it seems to be caching the config url although springdoc cache is disabled.
My springdoc-openapi version is 1.6.3 and spring-boot version is 2.6.2

Thanks for your help

**Comment by bnasslahsen** [comment]
@seymabatige, 

There are no known proxy issues. Note that demos are served behind proxies...
- Why are you mentioning `configURL` which is not present by default in v1.6.3 (are you adding your own configUrl ...) ?

Your description is unclear. Try describing your steps to reproduce one by one. (Use GITHUB formatting).
- Make sure you provide a **Minimal, Reproducible Example - with HelloController** that reproduces the problem
- Share your poxy configuration.

**Comment by bnasslahsen** [comment]
@seymabatige, 

This ticket will be closed and can be reopened if any relevant information is provided.

**Comment by abenjell** [comment]
Hello @seymabatige,
Did you resolve the problem?
Thanks

**Comment by abenjell** [comment]
Ok thank you for your feedback @seymabatige

**Comment by antechrestos** [comment]
@seymabatige did you find a solution?
I observe the same behaviour with the same approach...

@bnasslahsen any news on the subject?

**Comment by antechrestos** [comment]
Apparently the issue also impacts automatically generated server url

**Comment by abenjell** [comment]
Hello,
for information i create new issue here:
https://github.com/springdoc/springdoc-openapi/issues/1712

**Comment by antechrestos** [comment]
I put a hack for this problem in #1712
