### ISSUE TITLE
Add  springdoc-openapi-bom to make dependency management easier

### ISSUE THREAD

**Issue by paskos** [springdoc/springdoc-openapi#1420]
**Is your feature request related to a problem? Please describe.**
Our projects are a mix of mvc and webflux applications. Some with ui some without.
It requires us to declare all possible springdoc-openapi libraries in our dependencies management.
Gradle platform example:

        // open-api is used to document and generate client code
        api "org.springdoc:springdoc-openapi-common:${springdocOpenApiVersion}"
        api "org.springdoc:springdoc-openapi-data-rest:${springdocOpenApiVersion}"
        api "org.springdoc:springdoc-openapi-hateoas:${springdocOpenApiVersion}"
        api "org.springdoc:springdoc-openapi-security:${springdocOpenApiVersion}"

        api "org.springdoc:springdoc-openapi-webmvc-core:${springdocOpenApiVersion}"
        api "org.springdoc:springdoc-openapi-ui:${springdocOpenApiVersion}"
        api "org.springdoc:springdoc-openapi-webflux-core:${springdocOpenApiVersion}"
        api "org.springdoc:springdoc-openapi-webflux-ui:${springdocOpenApiVersion}"

**Describe the solution you'd like**
It  would be nice to have a single springdoc-openapi-bom to add in our dependencies management section.
Then we would not have to add an additional line in our platform in case we need to use a new springdoc-openapi-XXXX library in one of our projects.

Gradle platform example:

        // open-api is used to document and generate client code
        api "org.springdoc:springdoc-openapi-bom:${springdocOpenApiVersion}"

Thanks in advance

**Comment by bnasslahsen** [comment]
There is already `springdoc-openapi` bom.

```gradle
dependencyManagement {
	imports {
		mavenBom('org.springdoc:springdoc-openapi:1.6.3') 
	}
}
```

**Comment by paskos** [comment]
Oh !
Great !! thanks !
