### ISSUE TITLE
Parameter 2 of method indexPageTransformer in org.springdoc.webmvc.ui.SwaggerConfig required a single bean, but 2 were found:

### ISSUE THREAD

**Issue by walnut-tom** [springdoc/springdoc-openapi#1425]
Parameter 2 of method indexPageTransformer in org.springdoc.webmvc.ui.SwaggerConfig required a single bean, but 2 were found:

When there are two types of beans, JsonMapper and XmlMapper, an error will be reported
```
  @Bean
  protected XmlMapper xmlMapper() {
    return new XmlMapper();
  }

  @Bean
  protected JsonMapper jsonMapper() {
    return new JsonMapper();
  }

```

**Comment by bnasslahsen** [comment]
@walnut-tom, 

If you want to use your own objectMapper, the simplest way to override the default configuration is to define an ObjectMapper bean and to mark it as `@Primary`.

We will improve this anyway.
