### ISSUE TITLE
Only in test class, "Error creating bean with name 'multipleOpenApiResource' defined in class path resource [org/springdoc/webflux/core/MultipleOpenApiSupportConfiguration.class]" occured.

### ISSUE THREAD

**Issue by jake-mathpresso** [springdoc/springdoc-openapi#1427]
**Describe the bug**
I try to migrate from springfox-swagger to springdoc-openapi.
In a Kotlin + Spring Webflux application, I have the following dependencies

```
implementation("org.springdoc:springdoc-openapi-ui:1.6.3")
        implementation("org.springdoc:springdoc-openapi-webflux-ui:1.6.3")
        //implementation("org.springdoc:springdoc-openapi-security:1.6.3") -- App using spring security
        implementation("org.springdoc:springdoc-openapi-kotlin:1.6.3")
```

And this is springdoc config:

```
import io.swagger.v3.oas.annotations.enums.ParameterIn
import io.swagger.v3.oas.models.media.StringSchema
import io.swagger.v3.oas.models.parameters.Parameter
import org.springdoc.core.GroupedOpenApi
import org.springdoc.core.customizers.OperationCustomizer
import org.springframework.context.annotation.Bean
import org.springframework.context.annotation.Configuration
import org.springframework.context.annotation.Profile

@Configuration
//@Profile(ProfileCode.EXCEPT_PROD)
class SpringdocConfig {

    @Bean
    fun api(): GroupedOpenApi {
        return GroupedOpenApi.builder()
            .group("group name")
            .packagesToScan("my.package")
            .addOperationCustomizer(globalParameters())
            .build()
    }

    @Bean
    fun globalParameters(): OperationCustomizer {
        return OperationCustomizer { operation, _ ->
            operation
                .addParametersItem(Parameter().name(HttpHeader.AUTHORIZATION_KEY).description("access token").required(true).`in`(ParameterIn.HEADER.toString()).schema(StringSchema()))
                //.addParametersItem ........ and a lot of parameters
        }
    }
}
```

When the app starts, there is no error.
However when the test code execute, I get the following error:

```Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'multipleOpenApiResource' defined in class path resource [org/springdoc/webflux/core/MultipleOpenApiSupportConfiguration.class]: Unsatisfied dependency expressed through method 'multipleOpenApiResource' parameter 3; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'responseBuilder' defined in class path resource [org/springdoc/webflux/core/SpringDocWebFluxConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springdoc.core.GenericResponseService]: Factory method 'responseBuilder' threw exception; nested exception is java.lang.NoClassDefFoundError: javax/servlet/ServletException```

Since I'm not sure there is no error on my test code, so I create sample test code like: 

```
import org.junit.jupiter.api.Test
import org.springframework.boot.test.context.SpringBootTest

@SpringBootTest
class SampleTest {

    @Test
    fun test(){

    }
}
```

but, error still..... :(

**To Reproduce**
- What version of spring-boot you are using? : 2.5.6
- What modules and versions of springdoc-openapi are you using? : 1.6.3
- What is the actual and the expected result using OpenAPI Description (yml or json)?
- Provide with a sample code (HelloController) or Test that reproduces the problem

**Comment by bnasslahsen** [comment]
@jake-mathpresso, 

You have sample [webflux/repo tests](https://github.com/springdoc/springdoc-openapi/tree/master/springdoc-openapi-kotlin/src/test) in the repo. 
Use always the last version before creating an issue: as per today **v1.6.4**

**Provide with a sample code (HelloController) or Test that reproduces the problem.**

This ticket will be closed and can be reopened and if any additional information is provided.

**Comment by addio3305** [comment]
@bnasslahsen 
I changed springdoc version to v1.6.4 but still error occured. (I change my github account.)

You can get sample code from "https://github.com/addio3305/springdoc.git"

**Comment by bnasslahsen** [comment]
@addio3305, 

Remove the following line as you are using `spring-boot-starter-webflux`:`implementation("org.springdoc:springdoc-openapi-ui:1.6.4")`

https://github.com/addio3305/springdoc/blob/eca6acf9c783e5c902707be1a05fcacc77522cb2/build.gradle.kts#L39

**Comment by addio3305** [comment]
@bnasslahsen 
Thank you for your guide.
