### ISSUE TITLE
ExampleObject with examples having externalValue does not load in swagger-ui

### ISSUE THREAD

**Issue by ShambuGIT** [springdoc/springdoc-openapi#1432]
**Issue**
Configuring the @ExampleObject with examples specifying the externalValue="http://localhost:8090/context/examples/test.json" not showing in swagger-ui.

**RestController**
 ```
  @GetMapping("/testopenapi")
    @Operation(summary = "Get thing", responses = {
            @ApiResponse(description = "Successful Operation", responseCode = "200", content = @Content(examples = @ExampleObject(name = "readJson", externalValue = "http://localhost:8090/context/examples/test.json", summary = "Request")))
            })
    public @ResponseBody ResponseEntity<String> testopenapi()
    {
        return new ResponseEntity<String>("Hello welcome! This is testopenapi controller.",
                HttpStatus.OK);
    }
```
**Issue screenshot**
![image](https://user-images.githubusercontent.com/5293623/148689458-c24849c2-6c3b-4335-bda9-672076de5929.png)

I tried multiple options specified in forum but noting helped much. But if i change it to value and provide the json as string it works fine.

**Comment by bnasslahsen** [comment]
@ShambuGIT, 

Do not create duplicates.
This is already answered here #17
