### ISSUE TITLE
swagger-ui is not showing "select a definition" instead shows Explore option with text box

### ISSUE THREAD

**Issue by ShambuGIT** [springdoc/springdoc-openapi#1433]
**Issue**
I have spring mvc project without spring boot that integrated springdoc-openapi as mentioned in the [document](https://springdoc.org/#how-to-integrate-open-api-3-with-spring-project-not-spring-boot). Everything works fine. but one issue seen in UI where I could not see "select a definition" with list of groups instead it was showing Text box with Explore option. 

springdoc-openapi-ui - 1.6.4
spring-boot & spring-boot-autoconfigure - 2.6.2

**Screen shot taken from non spring boot app**
![image](https://user-images.githubusercontent.com/5293623/148689749-9386a862-cb88-49db-b5d9-bd37145f50e0.png)

If i specify api-docs path manually, it works fine. I tried with simple spring boot project where I could see the select a definition option.  Is something am i missing in non spring boot integration.

**Screen shot taken from  spring boot app**

![image](https://user-images.githubusercontent.com/5293623/148689780-09a2ca8a-4bac-4b61-9eb3-049cc997553a.png)

**Comment by bnasslahsen** [comment]
@ShambuGIT, 

Provide you complete configuration. Same incomplete information as  #1431.
Make sure you follow the[ contribution guidelines](https://github.com/springdoc/springdoc-openapi/blob/a63426eaeb12faca0b6ee181ba1c9925d1a2c34e/CONTRIBUTING.adoc) before opening issues.

**Looks like you are not scanning for your `GroupedOpenApi` beans **
If you choose not to use spring-boot. Then you have to scan for all the beans that are automatically auto-configured with spring-boot.

**Comment by ShambuGIT** [comment]
@bnasslahsen  - I have provided the sample[hello](https://github.com/springdoc/springdoc-openapi/files/7835614/hello.zip) project that shows text box with Explore button if you access http://localhost:8090/hello/openapi/swagger-ui/index.html 

Please validate and let me know what am missing.

**Note:** if I map "DefaultSwagger" as root path(change the  `<url-pattern>/openapi/*</url-pattern> into  <url-pattern>/*</url-pattern> `) then it works fine.

**Comment by bnasslahsen** [comment]
already answered here: #841

Simply, move your Beans definition inside a dedicated configuration class:

```java
package com.example.hello;

import org.springdoc.core.GroupedOpenApi;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

@Configuration
class GroupsConfiguration {

    @Bean
    public GroupedOpenApi accountApi()
    {
        return GroupedOpenApi.builder()
                .group("v1")
                .packagesToScan("com.example.hello")
                .build();
    }
}
```

**Comment by ShambuGIT** [comment]
@bnasslahsen - Still it does not work under different context (http://localhost:8090/hello/**openapi**/swagger-ui/index.html). Attached the latest [hello](https://github.com/springdoc/springdoc-openapi/files/7836048/hello.zip) project

**Comment by bnasslahsen** [comment]
@ShambuGIT, 

You are missing the following property in your project as explained here https://github.com/springdoc/springdoc-openapi/issues/899: 

```properties
spring.mvc.servlet.path=/openapi
```

**Comment by ShambuGIT** [comment]
Thanks @bnasslahsen. It resolved the issue. One suggestion it would be nice if you put this details in https://springdoc.org/#faq
