### ISSUE TITLE
Is it possible to share schemas across groups?

### ISSUE THREAD

**Issue by Alexander-Steiniger** [springdoc/springdoc-openapi#1436]
Hello, I was wondering whether it is possible to share schemas across different groups?

My idea is to define an `OpenAPI`-bean in which I add the `Schema` I want to use in different `GroupedOpenAPI`-beans:

```
@bean
public OpenAPI globalOpenApi() {
    return new OpenAPI().components(new Components().schemas(ModelConverters.getInstance().read(ExtendedResult.class)));
}
```

Is it possible to access such a global schema in an `OpenApiCustomiser` within a `GroupedOpenApi`? I couldn't do so. If this is not possible, is there another way to add a schema programmatically so that it can be referred to in an `OperationCustomizer`. It seems that `OperationCustomizers` are run before `OpenApiCustomisers`.

The background of my question is the requirement to wrap responses of certain endpoints in an extended result class based on a custom annotation. In the code this is realized by a `@ControllerAdvice` that implements the `ResponseBodyAdvice`.

**Comment by bnasslahsen** [comment]
@Alexander-Steiniger, 

This is sample code, how you can customize OpenAPI object programmatically [different schemas](https://springdoc.org/#can-i-customize-openapi-object-programmatically).

You can attach your custom Schemas to each `OpenApiCustomiser`.
