### ISSUE TITLE
Does this lib supports openapi spec "3.0.3" or "3.1"?

### ISSUE THREAD

**Issue by ShambuGIT** [springdoc/springdoc-openapi#1438]
Hi,

I see that api-docs returns open api version "3.0.1" even i upgrade to the latest version. Any plan to support the latest spec soon? Or did i am miss something in the dependancies.

Thanks & Regards
Shan

**Comment by bnasslahsen** [comment]
@ShambuGIT, 

Read the [contribution guide](https://github.com/springdoc/springdoc-openapi/blob/master/CONTRIBUTING.adoc) before sending this kind of questions.
The answer is [here](https://github.com/swagger-api/swagger-core/blob/master/README.md) and the detail is [here](https://github.com/swagger-api/swagger-core/blob/v2.1.12/modules/swagger-models/src/main/java/io/swagger/v3/oas/models/OpenAPI.java).
