### ISSUE TITLE
Swagger UI by url does not automatically unfold method which is under some definition 

### ISSUE THREAD

**Issue by darkula** [springdoc/springdoc-openapi#1439]
**Describe the bug**
In order to faster move from our local documentation to concrete Swagger UI method we store in documentation full link to this method, so when someone would click on this Swagger UI link, then Swagger UI would automatically open this method. It worked find till springdoc-openapi-ui version 1.5.13.
Upgrading springdoc-openapi-ui from 1.5.13 version to 1.6.4 it does not automatically open method under specific definition by url.

**To Reproduce**
- Spring Boot 2.5.6
- springdoc-openapi-ui 1.6.4
- In an example, clicking on this link http://158.101.191.70:8084/webjars/swagger-ui/index.html?urls.primaryName=users#/Users/putUser it does not automatically open method PUT /api/user/put/{id} under User definition
- ![image](https://user-images.githubusercontent.com/38877693/148936286-970dc8dc-a2e4-4e6d-b56b-875a9d17e8dd.png)

**Expected behavior**
- In an example, clicking on this link http://158.101.191.70:8084/webjars/swagger-ui/index.html?urls.primaryName=users#/Users/putUser it would open automatically PUT /api/user/put/{id} method
- ![image](https://user-images.githubusercontent.com/38877693/148935934-b9456249-6cc6-4a61-9617-7c54736635fe.png)

**Comment by bnasslahsen** [comment]
@darkula, 

Not reproducible.

**Comment by darkula** [comment]
@bnasslahsen did you even tried to reproduce an error? 
Or does it work on your local computer?

**Comment by bnasslahsen** [comment]
@darkula, 

It just works everywhere :) 

You just using wrong config. Query params are disabled in sprindoc since 1.6.0 for security reasons as explained in the documentation.

In your case:  Add the following property  `springdoc.swagger-ui.urlsPrimaryName=users` and use the following url: `http://localhost:8080/swagger-ui.html#/Users/putUser`

If you want it in query params (not recommended):
Use: `springdoc.swagger-ui.query-config-enabled=true`
And the access url: 
`http://localhost:8080/swagger-ui.html?configUrl=/v3/api-docs/swagger-config&urls.primaryName=users#/Users/putUser`

**Comment by darkula** [comment]
@bnasslahsen Okey, thank you for your answer, will try to adjust config and see how it goes :)

**Comment by darkula** [comment]
@bnasslahsen 
I tried this, not recommended way (Use: springdoc.swagger-ui.query-config-enabled=true) and it works perfectly.

Then tried preferred way (springdoc.swagger-ui.urlsPrimaryName=users), but this does not works exacly as above solution.
Yes it works as you described, but this will work only of one particular group, exactly as written in documentation (The name of the swagger group which will be displayed when Swagger UI loads.)

I have multiple groups, each groups can have multiple services (@Tag) each services can have multiple API paths (REST methods).
It is really does not matter in which group and which service and which method is opened, tester or dev would have simply copy link from browser and store it into documentation or simple send via some chatting platform and receiver would simple press on any link and this link would open Swagger UI with concrete group and concrete method would unfold and be ready to   press the button Try it out.

So in example:
http://158.101.191.70:8084/webjars/swagger-ui/index.html?urls.primaryName=users#/coffee-service/getOrdersForCoffeeById
This should open automatically this:
![image](https://user-images.githubusercontent.com/38877693/149082137-f009f756-f75c-4db9-b3ce-63e0ce735dde.png)

Some one else would simply send this link:
http://158.101.191.70:8084/webjars/swagger-ui/index.html?urls.primaryName=employees#/Employees/findAllEmployees
This should open automatically this:
![image](https://user-images.githubusercontent.com/38877693/149082255-239c80b1-f62d-4c87-9a2b-27ac874ee943.png)

Some one else would simply send this link:
http://158.101.191.70:8084/webjars/swagger-ui/index.html?urls.primaryName=users#/Users/deleteUser
This should open automatically this:
![image](https://user-images.githubusercontent.com/38877693/149082399-59ff84b6-20cd-4a8b-b9d8-4eb7f0d0a39d.png)
 

Is this achievable with "springdoc.swagger-ui.urlsPrimaryName" ?

**Comment by evgenbal** [comment]
@bnasslahsen All links open page like below. Looks like a bug

![image](https://user-images.githubusercontent.com/36564408/149827196-3d56b3ae-88af-4bcd-aa95-c53d201e9cb8.png)

P.S. I have faced with the same issue
