### ISSUE TITLE
Open API specification are not generated correctly for GET request

### ISSUE THREAD

**Issue by 5aab** [springdoc/springdoc-openapi#1440]
**Open API specifications are not generated correctly for GET request**
- I have a spring boot app with more than 1000 GET-type endpoints currently using spring fox libraries. I am migrating the project to use OAS 3 using Spring doc libraries. All of them have the same request parameters. in order to make the code look cleaner, I've put all the request parameters in a wrapper class and used this wrapper class to handle request parameters. There are close to 25 request parameters
- This is how wrapper class will look like:

```
@Setter
@Getter
public class RequestParameterWrapper {
    private String filter;
    private Integer max;
    private Integer skip;
    private String id;
    private String pageSize;
} 
```

- Sample controller code looks like this:

```
@GetMapping("sample/request")
    public String findData(RequestParameterWrapper parameters) {
        return "data found";
    }
```
- Intended URL looks like this:
 _/sample/request?filter=true&max=5&skip=6_

**Generated API documentation with Spring fox looks like the following and is correct as per expectation**
![image](https://user-images.githubusercontent.com/38609507/149116985-f4ba0f03-4531-453c-afb3-bdf8fc4f0bf1.png)

**For OAS 3, using Spring Doc libraries, it is turning out like this and is not right**
![image](https://user-images.githubusercontent.com/38609507/149117346-643c6db8-90e7-4aac-8954-ecdd21d16afe.png)

- I tried to find the solution but couldn't make it work. the only way ,at this time, looks like is to take out request parameters from RequestParameterWrapper and put them as method arguments individually. but given the count of end points I've, I don't really wanna go on to that route. 
- Is there any way to fix it?

**Comment by 5aab** [comment]
I just realized that I need to use **@ParameterObject** annotation. it is now generating in the correct fashion but documentation for **JSR303 validation** in this wrapper object has gone missing now. any suggestions?

**Comment by 5aab** [comment]
It seems to be Swagger UI issue. no descriptions are visible. otherwise generated json spec is good and have all details of JSR-303 validations

**Comment by bnasslahsen** [comment]
Use [swagger-ui Github](https://github.com/swagger-api/swagger-ui/issues) if you face swagger-ui issues.
