### ISSUE TITLE
Springdoc-openapi-webmvc-core not enought for Springdoc-openapi-native 

### ISSUE THREAD

**Issue by JulienHoullier** [springdoc/springdoc-openapi#1442]
**Describe the bug**
When only using the Springdoc-openapi-webmvc-core and adding Springdoc-openapi-native, the application fails to start since SpringDocHints expect a bean SwaggerUiConfigProperties why is i guess provided by auto-configuration in springdoc-openapi-ui 

**To Reproduce**
- Create a Spring Boot Native APP (Spring boot 2.6.2 + Spring Native 0.11.1) using Spring Initialzer
- Add module **springdoc-openapi-webmvc-core** and **springdoc-openapi-native** 1.6.3
- Activate springdoc.api-docs.enabled=true
- Error printed 

Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'org.springdoc.nativex.core.SpringDocHints': Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'org.springdoc.core.SwaggerUiConfigProperties' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {}

**Expected behavior**
- No error

**Workaround**
- Add the expected bean in your application:
`@Bean
    public SwaggerUiConfigProperties swaggerUiConfigProperties() {
        return new SwaggerUiConfigProperties();
    }`

**Comment by bnasslahsen** [comment]
@JulienHoullier, 

First make sure you use the last stable version before opening issues.
Second, [webmvc](https://github.com/springdoc/springdoc-openapi-demos/tree/master/springdoc-openapi-spring-boot-2-webmvc) demo is just deployed using spring-native.

So make sure you review your configuration.
And if you still believe, you faced an issue, then make sure you provide Provide a [Minimal, Reproducible Example - with HelloController that reproduces](https://stackoverflow.com/help/minimal-reproducible-example)the problem.

**Comment by JulienHoullier** [comment]
Okay, i'll try to provide you an example project, but the problem is obvious for me,
even in the 1.6.4 the problematic code is present 
https://github.com/springdoc/springdoc-openapi/blob/master/springdoc-openapi-native/src/main/java/org/springdoc/nativex/core/SpringDocHints.java#L305

The demo [webmvc](https://github.com/springdoc/springdoc-openapi-demos/tree/master/springdoc-openapi-spring-boot-2-webmvc) you are referencing is using the ui dependency:

`<dependency>
			<groupId>org.springdoc</groupId>
			<artifactId>springdoc-openapi-ui</artifactId>
</dependency>`

What i use is only le webmvc-core
`<dependency>
			<groupId>org.springdoc</groupId>
			<artifactId>springdoc-openapi-webmvc-core</artifactId>
</dependency>`

Regards

**Comment by JulienHoullier** [comment]
Here your example project, a small spring initializr with springdoc-openapi-native and springdoc-openapi-webmvccor
So you can re-open the issue

[test.zip](https://github.com/springdoc/springdoc-openapi/files/7865628/test.zip)
e
