### ISSUE TITLE
Documentation doesn't render when the app sets a sensible CSP

### ISSUE THREAD

**Issue by lol768** [springdoc/springdoc-openapi#1443]
```
    <script>
    window.onload = function() {
      // Begin Swagger UI call region
      const ui = SwaggerUIBundle({
        url: "https://petstore.swagger.io/v2/swagger.json",
        dom_id: '#swagger-ui',
        deepLinking: true,
        presets: [
          SwaggerUIBundle.presets.apis,
          SwaggerUIStandalonePreset
        ],
        plugins: [
          SwaggerUIBundle.plugins.DownloadUrl
        ],
        layout: "StandaloneLayout" ,

  "configUrl" : "/v3/api-docs/swagger-config",
  "validatorUrl" : ""

      });
      // End Swagger UI call region

      window.ui = ui;
    };
  </script>
  ```

This is `unsafe-inline` JS, and will be blocked by a strict CSP.

Could you reference a separate endpoint/static JS file instead to initialise the documentation UI?

**Comment by bnasslahsen** [comment]
No

**Comment by lol768** [comment]
Can you expand on why? I genuinely don't understand your perspective here.

Obviously it's possible to just render your own Swagger UI template, which is exactly what I've done to work around this for now (so I just rely on the JSON endpoint that the library provides) .. but I really don't see the harm in supporting this use-case out of the box. Would you review a PR that fixes it?

Currently this library doesn't work in the recommended configuration when it's built into an application which follows security best practice at preventing stored/reflected XSS, which is pretty poor.

**Comment by bnasslahsen** [comment]
@lol768, 

There are no plans to change the UI configuration. We prefer relying on the standard `swagger-ui` application, with the very less/ minimal `custom` changes.

Now, if you feel you can bring added value. Feel free to propose a PR and we will have a look at it.
