### ISSUE TITLE
@JsonView on class level is ignored

### ISSUE THREAD

**Issue by FireFoxG** [springdoc/springdoc-openapi#1444]
I would like to bring back the topic which was raised **[here](https://github.com/springdoc/springdoc-openapi/issues/665)** by **Strunevskiy**

I faced the same issue while working on another project.

Strunevskiy provided a repository, which reproduces the issue perfectly, and it still happens with version 1.6.4.

**Describe the bug**

- In openapi-ui, class fields do not inherit `@JsonView` from the class-level annotation, the same way as they usually do it in Jackson.
This causes a lot of boilerplate, in case you want most of the class fields to own specific view by default, but only override some of them, to display with a certain view in openapi-ui. The only way to achieve it right now - set JsonView annotation per field.

**To Reproduce**

    spring-boot - 2.2.6
    springdoc-openapi-ui - 1.6.4

  Run the project
  Go to Swagger UI or spec
  Compare with actual response

  [ I updated and cleaned up original version provided by Strunevskiy ]( https://github.com/FireFoxG/springdoc-openapi-jsonview)

_fields status and createdTime are displayed on swagger-ui and in spec, whereas a returned response by a controller has only status field._

**Expected behavior**
_only status field is displayed on swagger-ui_

**Comment by bnasslahsen** [comment]
@FireFoxG, 

There is no need to create duplicates. 
Make sure you read the contribution guidelines.

Add your comment to the original ticket.
We will see if its relevant, to consider reopening it.

**Comment by bnasslahsen** [comment]
This ticket will be deleted in less than 30 min

**Comment by glebrimmel-change** [comment]
It the spec is generated incorrectly, then now swagger-core can help here?
As I mentioned in original post, workaround is creating too much boilerplate and makes simple DTO too overwhelming.
