### ISSUE TITLE
Parameter 5 of method springDocProviders in org.springdoc.core.SpringDocConfiguration required a bean of type 'org.springdoc.core.providers.SpringWebProvider' that could not be found.

### ISSUE THREAD

**Issue by patpatpat123** [springdoc/springdoc-openapi#1449]
Hello SpringDoc Team,

After upgrading a Springboot 2.6.2 project using this dependency

```
      <dependency>
            <groupId>org.springdoc</groupId>
            <artifactId>springdoc-openapi-webflux-ui</artifactId>
        </dependency>
```

From version ```<version>1.6.3</version>``` to ```<version>1.6.4</version>```

I am getting tis error on application startup, preventing the app to start:

```
***************************
APPLICATION FAILED TO START
***************************

Description:

Parameter 5 of method springDocProviders in org.springdoc.core.SpringDocConfiguration required a bean of type 'org.springdoc.core.providers.SpringWebProvider' that could not be found.


Action:

Consider defining a bean of type 'org.springdoc.core.providers.SpringWebProvider' in your configuration.
```

May I ask what is the root cause of this issue please?

Is this issue related to:
https://github.com/springdoc/springdoc-openapi/issues/1446
https://github.com/springdoc/springdoc-openapi/issues/1091

And may I ask when is the fix available in Maven central please?

Thank you

**Comment by bnasslahsen** [comment]
@patpatpat123,

Do  not create duplicates.
By the end of the month.
