### ISSUE TITLE
Whether the project structure can be adjusted

### ISSUE THREAD

**Issue by Hccake** [springdoc/springdoc-openapi#1450]
Now when you use SpringDoc, because Springdoc-common is already a minimum dependency and it is a spring-boot auto-configured project (with spring.Factories), this can cause exceptions for services that do not need to expose documents to the outside world due to transitive dependencies, such as:  

#1449
#1446
#1091 

Based on this, can we extract the basic Annotation and Model into a smaller module by referring to Swagger?  Although the @parameterObject annotation seems to be the only one available right now, it is quite common.  
 
Or do you take  spring.factories out of springdoc-common and move it to a starter?

**Comment by bnasslahsen** [comment]
@Hccake 

Do not create duplicates.
