### ISSUE TITLE
get swagger-ui version

### ISSUE THREAD

**Issue by T-Developer1** [springdoc/springdoc-openapi#1452]
Hi,

for my project i need to know which swagger-ui Version Springdoc is using. 
In Version 1.5.10 i used the following code to get the Version 

```
import static org.springdoc.core.Constants.SWAGGER_UI_VERSION;

   @Value( SWAGGER_UI_VERSION )
   private String swaggerUiVersion;
```

With the newest Version i can't use this Feature anymore. 
It was deleted in this commit:
https://github.com/springdoc/springdoc-openapi/commit/6725f08a990262385d34ed112f0b8572225fed30

i already tried to get it with the swaggerUiConfigProperties

```
   @Autowired
   SwaggerUiConfigProperties swaggerUiConfigProperties;

swaggerUiConfigProperties.getVersion();
```

but the Version is always null.
Is there any new way to get the swagger-ui-version?

**Comment by bnasslahsen** [comment]
@T-Developer1, 

This is only a workaround for a graalVM issue.
This has been moved to spring-native module when introduced. 

The swagger-ui is available in the springdoc bom.
Why do you need to get the swagger-ui version in your code?

**Comment by T-Developer1** [comment]
Hi,

i register a resource Handler for webmvc


  ```
import static org.springdoc.core.Constants.SWAGGER_UI_VERSION;

 @Value( SWAGGER_UI_VERSION )
   private String swaggerUiVersion;

   @Override
   public void addResourceHandlers( ResourceHandlerRegistry registry )
   {
      registry.addResourceHandler( "/swagger-ui/**" )
              .addResourceLocations( "classpath:" + "/META-INF/resources/webjars/swagger-ui/"
                                     + swaggerUiVersion + "/" );
   }
```

**Comment by T-Developer1** [comment]
I also tried working with the BOM

```
<springdoc-openapi-ui.version>1.5.12</springdoc-openapi-ui.version>

<dependencyManagement>
      <dependencies>
         <dependency>
            <groupId>org.springdoc</groupId>
            <artifactId>springdoc-openapi-ui</artifactId>
            <version>${springdoc-openapi-ui.version}</version>
            <type>pom</type>
            <scope>import</scope>
         </dependency>
      </dependencies>
   </dependencyManagement>
```


but in my POM i can only see the dependency

```
      <dependency>
        <groupId>org.webjars</groupId>
        <artifactId>swagger-ui</artifactId>
        <version>3.52.5</version>
      </dependency>
```

and not the propertie

`		<swagger-ui.version>4.2.1</swagger-ui.version>
`

So if i try to get the Version i get an error

```
   @Value( "${swagger-ui.version}" )
   protected String swaggerV;
```

**Comment by bnasslahsen** [comment]
@T-Developer1, 

You have a sample code here. There is no need to reference the version, you need `webjars-locator`.

https://github.com/springdoc/springdoc-openapi/blob/ce39c7b917fb623a87f3064b1822499fbb93b85d/springdoc-openapi-ui/src/main/java/org/springdoc/webmvc/ui/SwaggerWebMvcConfigurer.java#L89-L100

**Comment by T-Developer1** [comment]
Thank you very much! This helped a lot.
But if i call swagger-ui.html now, it redirect me to the petstore url.

I changed the api-docs path to /api-docs, but with my old addResources it worked

```
springdoc:
  api-docs:
    #to change default path /v3/api-docs to /api-docs
    path: /api-docs 
```

This is how i use addResources now:

```

   @Autowired
   SwaggerUiConfigParameters swaggerUiConfigParameters;

   @Autowired
   SwaggerIndexTransformer swaggerIndexTransformer ;
   
   @Autowired
   Optional<ActuatorProvider> actuatorProvider;
   
   @Override
   public void addResourceHandlers( ResourceHandlerRegistry registry )
   {
      String swaggerPath = swaggerUiConfigParameters.getPath();

      StringBuilder uiRootPath = new StringBuilder();
      if ( swaggerPath.contains( DEFAULT_PATH_SEPARATOR ) )
         uiRootPath.append( swaggerPath, 0, swaggerPath.lastIndexOf( DEFAULT_PATH_SEPARATOR ) );
            if (actuatorProvider.isPresent() && actuatorProvider.get().isUseManagementPort())
               uiRootPath.append(actuatorProvider.get().getBasePath());

      registry.addResourceHandler( uiRootPath + SWAGGER_UI_PREFIX + "*/**" )
              .addResourceLocations( CLASSPATH_RESOURCE_LOCATION + DEFAULT_WEB_JARS_PREFIX_URL
                                     + DEFAULT_PATH_SEPARATOR )
              .resourceChain( false ).addTransformer( swaggerIndexTransformer );
   }
```

**Comment by bnasslahsen** [comment]
@T-Developer1 , 

Why aren't you just using `springdoc-openapi-ui` ?

**Comment by bnasslahsen** [comment]
@T-Developer1, 

You shouldn't be overriding `sprindoc-openapi-ui`configuration then, just use it as is.
Otherwise, make sure you add the link a **Minimal, Reproducible Example - with HelloController** that reproduces your context.

I am closing this ticket and can be reopened, if you provide any relevant information.
