### ISSUE TITLE
Post without @RequestBody not getting all fields

### ISSUE THREAD

**Issue by yzqdev** [springdoc/springdoc-openapi#1455]
My minimal example is here  https://github.com/yzqdev/springdoc-demo

**Expected behavior**
**it's  expected as the image below** 
(i also have a springfox-demo here to show th expected result. https://github.com/yzqdev/springfox-demo )

![image](https://user-images.githubusercontent.com/20037151/150411792-d014c618-d03a-4a4c-a85d-b3e7f49e2823.png)

**while it is like this(I didn't add a @ResponseBody annotation on this parameter)**

![image](https://user-images.githubusercontent.com/20037151/150412093-8569edca-6e8c-419c-bed5-9b304bc672df.png)

**Comment by bnasslahsen** [comment]
@yzqdev, 

Use `@ParameterObject`, if you want to get all the properties of your object parsed as separate query parameters:

```java
    @PostMapping("/query")
    public User query(@ParameterObject User user) {
        return user;
    }
```
