### ISSUE TITLE
Support for Authorization Code Grant

### ISSUE THREAD

**Issue by anj-kr** [springdoc/springdoc-openapi#1457]
**Describe the bug**
-  Is the Spring Doc Open API supports Authorization Code Grant when loading the application using configuration data - Client ID, Secret, Redirect Url

Unable to find the specific example using the mentioned context.

**Additional context**
Looking for example when the user accesses the application in the browser, authorization code grant (with Redirect URL) configured should get triggered and when redirected to swagger UI token from the provider should exist instead of manually entering client id/secret to authorize.

Thanks
Ed

**Comment by bnasslahsen** [comment]
@anj-kr, 

See the demos: https://github.com/springdoc/springdoc-openapi-demos/tree/master/springdoc-openapi-oauth2
