### ISSUE TITLE
Generated Server URL not including context path when behind reverse proxy (Spring Cloud Zuul)

### ISSUE THREAD

**Issue by skylar-stark** [springdoc/springdoc-openapi#1459]
I am experiencing issues with the generated server URL when the service is behind a reverse proxy, specifically in this case Spring Cloud Zuul. In this case, it contains the "context path" of the reverse proxy but does not include the "context path" of the API using Springdoc.

My Spring Boot service is deployed at the location (using "my-awesome-api" as its context path):
https://server-a.com/my-awesome-api

The Spring Cloud Zuul instance is deployed at (using "api-proxy" as its own context path):
https://server-b.com/api-proxy

In order to access "my-awesome-api" via the reverse proxy, we call the context path of the service after the context path of the reverse proxy, like so:
https://server-b.com/api-proxy/my-awesome-api/rest/doSomething

When I access the Swagger URL for "my-awesome-api"
https://server-a.com/my-awesome-api/swagger-ui.html

It correctly generates the server URL as "https://server-a.com/my-awesome-api"

However, when I access the Swagger URL for "my-awesome-api" via the reverse proxy
https://server-b.com/api-proxy/swagger-ui.html?urls.primaryName=my-awesome-api

The generated server URL is "https://server-b.com/api-proxy"

This means that if I try to hit "/rest/doSomething", the Swagger page is generating the request URL as
https://server-b.com/api-proxy/rest/doSomething", dropping the "my-awesome-api" context path after "api-proxy"

I have set the property "server.forward-headers-strategy=framework" and this doesn't change anything (changing this to "native" actually makes it so the generated server URL through the reverse proxy includes the "api-proxy" context path instead of the "my-awesome-api" context path, so I know changing it to "framework" is having some effect)

I have also tried setting
server.use-forward-headers=true

I've also tried creating my own ForwardedHeaderFileter bean, creating filters to manually attach the context path to the end of the "x-forwarded-prefix" header, etc, but nothing seems to work.

Edit: this is with using latest version 1.6.4 of "springdoc-openapi-ui"

**Comment by bnasslahsen** [comment]
@skylar-stark, 

 Note that Zuul, is now deprecated and most of projects using zuul, migrate to spring-cloud-gateway...
 - https://spring.io/blog/2019/01/23/spring-cloud-greenwich-release-is-now-available

Have you tries the workaround proposed here: https://github.com/springdoc/springdoc-openapi/issues/108

**Comment by skylar-stark** [comment]
There is a long term proposal to move off of Spring Cloud Zuul and into Spring Cloud Gateway, but unfortunately that looks to be quite some time off still. We cannot really make any updates to the Zuul instance at this point either. Making matters even more complicated I'm sure is that our Zuul instance uses Springfox for Swagger. 

Our Zuul instance can display the Swagger pages of all services that are registered to it, it does this by connecting to each service once every 30 seconds to get the JSON for Swagger, and then can display the Swagger page from itself. This part is already working well

When the downstream service is also using Springfox, this all works fine, as the "/v2/api-docs" path will return the correct server URL, but when the downstream service uses Springdoc, the context path of the downstream service is dropped

Is there a way to use something like "OpenApiCustomiser" to do "on-the-fly" changes when the JSON doc path is accessed? If that is possible, then I could do something where if I recognize the request for the JSON doc (via "/v3/api-docs") comes from our "api-proxy", then I can update the server URL (or even each of the API paths) to include the service's context path.

**Comment by skylar-stark** [comment]
I think the biggest problem I am experiencing is that it appears the "Generated server URL" is only generated a single time, and that appears to be the very first time the Swagger docs are accessed. For our use case, we need this to be generated per each request, as it needs to be set appropriately when the user access the Swagger directly via the service at:
https://server-a.com/my-awesome-api/swagger-ui.html

but it also needs to be updated appropriately when the user accesses the Swagger via our Zuul proxy at:
https://server-b.com/api-proxy/swagger-ui.html?urls.primaryName=my-awesome-api

I wrote an OpenApiCustomiser which takes the context path of the service and prefixes it to each "path" in the API, and then it strips the service's context path from each of the servers in the list. In theory, this would allow it to work from the reverse proxy when the generated server URL is "https://server-b.com/api-proxy" and also from the service itself when the generated server URL is "https://server-a.com/my-awesome-api" (because in this case, it would strip the "/my-awesome-api" from the server URL). However, this doesn't work, because as soon as my app starts up, if I first access it via Zuul, it the "https://server-b.com/api-proxy" URL is set as the generated URL, even when I then access the Swagger from "https://server-a.com/my-awesome-api/swagger-ui.html"

**Comment by bnasslahsen** [comment]
@skylar-stark,

Have you tried the workaround proposed here: https://github.com/springdoc/springdoc-openapi/issues/108 ?

For your Last comment try disabling https://springdoc.org/#how-can-i-disable-springdoc-openapi-cache cache:

**Comment by skylar-stark** [comment]
Disabling the cache worked for me. Can't believe I overlooked that in the docs. Thanks!

Below is my hastily written OpenApiCustomiser which removes the context path from the server URL and places in front of each API path:
```
@Bean
public OpenApiCustomiser contextPathCustomiser(Environment environment) {
	var contextPath = environment.getProperty("server.servlet.context-path", "/");
	return openApi -> {
		if (!"/".equals(contextPath)) {
			//Strip context path from the "server"
			openApi.getServers().stream().forEach(server -> {
				server.setUrl(server.getUrl().replace(contextPath, ""));
			});

			//Add context path to each "path"
			var openApiPaths = openApi.getPaths();
			var pathsToDelete = new HashSet<String>();
			var tempOpenApiPaths = new Paths();

			// Do everything in temp objects to not mess up iteration
			//TODO: refactor
			openApiPaths.entrySet().forEach(pathsEntry -> {
				tempOpenApiPaths.put(contextPath + pathsEntry.getKey(), pathsEntry.getValue());
				pathsToDelete.add(pathsEntry.getKey());
			});

			pathsToDelete.forEach(openApiPaths::remove);
			openApiPaths.putAll(tempOpenApiPaths);
		}
	};
}
```

**Comment by bnasslahsen** [comment]
@skylar-stark,

Thank you for your feedback.
