### ISSUE TITLE
Change Long data at runtime

### ISSUE THREAD

**Issue by Labradors** [springdoc/springdoc-openapi#1461]
The follow iis my real data
![]( https://cdn.jsdelivr.net/gh/labradors/image_repo/img/202201221313467.png)
but when i use swagger-ui，result is
![]( https://cdn.jsdelivr.net/gh/labradors/image_repo/img/202201221316716.png)
postman result is ok.
openapi-ui version is 1.6,3

**Comment by bnasslahsen** [comment]
@Labradors, 

Your description has nothing to do with `springdoc-openapi`.

Before you open tickets, make sure you follow the [contributing guidelines](https://github.com/springdoc/springdoc-openapi/blob/master/CONTRIBUTING.adoc).
