### ISSUE TITLE
How to replace SwaggerResourcesProvider class in SpringDoc/OpenApi?

### ISSUE THREAD

**Issue by kishorsamadder** [springdoc/springdoc-openapi#1462]
@Bean
    public SwaggerResourcesProvider swaggerResourcesProvider(InMemorySwaggerResourcesProvider defaultResourcesProvider) {
        return () -> {
        	List<SwaggerResource> resources = new ArrayList<>();
            SwaggerResource wsResource = new SwaggerResource();
            wsResource.setName("TPS");
            wsResource.setSwaggerVersion("2.0");
            wsResource.setLocation("/swagger.json");
            
            SwaggerResource notificationResource = new SwaggerResource();
            notificationResource.setName("NOTIFICATION");
            notificationResource.setSwaggerVersion("2.0");
            notificationResource.setLocation("/notification-swagger.json");
            
            resources.add(wsResource);
            resources.add(notificationResource);
            return resources;
        };
    }
Above code is custom implementation for SwaggerFox but,
How to replace this above code SpringDoc/OpenApi?

**Comment by bnasslahsen** [comment]
@kishorsamadder, 

The idea is that you want serve groups where the URLs are manually provided by your application:
I see that you are changing the version of the external OpenAPIs. 
This is not possible in springdoc-openapi: External resources are served directly as they are with the `swagger-ui` and there is no plan to change this behavior.

This is a sample code that you can adapt:

```java
@Bean
public Set<SwaggerUrl> apis(SwaggerUiConfigProperties swaggerUiConfig) {
	Set<SwaggerUrl> swaggerUrlSet = new HashSet<>();
	SwaggerUrl wsResource = new SwaggerUrl( "TPS", "/v3/api-docs");
	swaggerUrlSet.add(wsResource);
	SwaggerUrl notificationResource = new SwaggerUrl( "NOTIFICATION", "/notification-swagger.json");
	swaggerUrlSet.add(notificationResource);
	swaggerUiConfig.setUrls(swaggerUrlSet);
	return swaggerUrlSet;
}
```

**Comment by kishorsamadder** [comment]
@bnasslahsen 
Issue is not resolved after adding the code you shared, below is the class - 


@Configuration
public class SwaggerSpecConfig{
	
	@Autowired
	private SwaggerDocHelper swaggerdocHelper;
	
	@Autowired
	private Environment env;
	
	private List<Map<String, String>> tags;
	
	@PostConstruct
	public void jsonToSwaggerConverter() {
		SwaggerInfo swaggerInfo = swaggerdocHelper.initialise(env.getProperty("swagger.app.name"));
		if (Objects.nonNull(swaggerInfo)) {
			tags = swaggerInfo.getTags();
		}
	}
	
	@Bean
	  public OpenAPI springShopOpenAPI() {
	      return new OpenAPI()
	              .info(new Info().title("TPS API")
	              .description("Spring shop sample application")
	              .version("2.0")
	              .license(new License().name("Apache 2.0").url("http://springdoc.org")))
	              .externalDocs(new ExternalDocumentation()
	              .description("SpringShop Wiki Documentation")
	              .url("https://springshop.wiki.github.org/docs"));
	  }

    
    @Primary
    @Bean
    public Set<SwaggerUrl> apis(SwaggerUiConfigProperties swaggerUiConfig) {
    	Set<SwaggerUrl> swaggerUrlSet = new HashSet<>();
    	SwaggerUrl wsResource = new SwaggerUrl( "TPS", "/swaggerdoc/Global.json");
    	swaggerUrlSet.add(wsResource);
    	SwaggerUrl notificationResource = new SwaggerUrl( "NOTIFICATION", "/swaggerdoc/openapi.json");
    	swaggerUrlSet.add(notificationResource);
    	swaggerUiConfig.setUrls(swaggerUrlSet);
    	return swaggerUrlSet;
    }
	
 }

==================================================

After adding the code snippet, **Select a definition** tag not showing on top bar of swagger-ui page- 

![image](https://user-images.githubusercontent.com/27721609/151203724-6506815f-bb0f-47d9-995e-256589d29ccf.png)

Please suggest me what am i missing?

**Comment by bnasslahsen** [comment]
@kishorsamadder, 

Make sure you Provide the link to a [Minimal, Reproducible Example - with HelloController](https://stackoverflow.com/help/minimal-reproducible-example) that reproduces the problem.

**Comment by kishorsamadder** [comment]
@bnasslahsen 

Could you please tell how to call api(SwaggerUiConfigProperties swaggerUiConfig) method  from my config?

**Comment by bnasslahsen** [comment]
> @bnasslahsen
> 
> Could you please tell how to call api(SwaggerUiConfigProperties swaggerUiConfig) method from my config?

see my comment below and make sure you provide the relevant information.

**Comment by kishorsamadder** [comment]
@bnasslahsen 
Thanks , its working with fresh new project. But i incorporate same changes that piece of code you shared in my project, its not working.

**Comment by kishorsamadder** [comment]
@bnasslahsen 
Could you please tell me how to refresh this below bean after application starts?

@Primary
@Bean
public Set<SwaggerUrl> apis(SwaggerUiConfigProperties swaggerUiConfig) {
	Set<SwaggerUrl> swaggerUrlSet = new HashSet<>();
	SwaggerUrl wsResource = new SwaggerUrl( "Swagger", "/swaggerdoc/swagger.json");
	swaggerUrlSet.add(wsResource);
	SwaggerUrl notificationResource = new SwaggerUrl( "OpenApi", "/swaggerdoc/openapi.json");
	swaggerUrlSet.add(notificationResource);
	swaggerUiConfig.setUrls(swaggerUrlSet);
	return swaggerUrlSet;
}

**Comment by MaheshMore4321** [comment]
> @bnasslahsen Could you please tell me how to refresh this below bean after application starts?
> 
> @primary @bean public Set apis(SwaggerUiConfigProperties swaggerUiConfig) { Set swaggerUrlSet = new HashSet<>(); SwaggerUrl wsResource = new SwaggerUrl( "Swagger", "/swaggerdoc/swagger.json"); swaggerUrlSet.add(wsResource); SwaggerUrl notificationResource = new SwaggerUrl( "OpenApi", "/swaggerdoc/openapi.json"); swaggerUrlSet.add(notificationResource); swaggerUiConfig.setUrls(swaggerUrlSet); return swaggerUrlSet; }

@kishorsamadder 

with @EventListener(ApplicationReadyEvent.class) you can load/refresh after application start
