### ISSUE TITLE
Add support for @Schema description using i18n

### ISSUE THREAD

**Issue by t0kieu** [springdoc/springdoc-openapi#1464]
**Is your feature request related to a problem? Please describe.**
`@Schema` description attribute does not apply properties values

**Describe the solution you'd like**
Generated component Schema RequestObject properties does not use i18n internationalization, it is rendered only key.

```java
  @Schema(
      description = "key.1",
      type = "string",
      required = true,
      example = "car")
  @NotNull
  @Size(min = 1, max = 50)
  String word();
```
```
components:
  schemas:
    WordRequest:
      required:
      - word
      type: object
      properties:
        word:
          maxLength: 50
          minLength: 1
          type: string
          description: key.1
          example: car

**Comment by bnasslahsen** [comment]
@t0kieu, 

Try adding the following property!

```properties
springdoc.api-docs.resolve-schema-properties=true
```

**Comment by t0kieu** [comment]
Adding the mentioned setting property helped to resolve the placeholders, but there is probably a bug, still force only the default localization.

**Comment by bnasslahsen** [comment]
feel free to update this ticket with all the required information listed in the [Contribution guide](https://github.com/springdoc/springdoc-openapi/blob/231db66ef1c64d2ea5fe3ee84c39e31a8b331b70/CONTRIBUTING.adoc)

**Comment by t0kieu** [comment]
@bnasslahsen please reopen ticket

**Comment by bnasslahsen** [comment]
I am happy to Open it.
But Before, make sure you provide the required elements to  reproduce.

**Comment by Serik0** [comment]
I can confirm that in such circumstances described by @t0kieu locale is used from the "LANG" environment variable (JDK 17, Ubuntu Linux)
At the same time, localization works fine using locale provided by MessageSource bean when property key is used in such cases:
1. 
```java
@OpenAPIDefinition(info = @Info(title = "open-api.title"))   // "open-api.title" property is localized ok
```   
2. 
```java
@RestController
public class TheController {
  @Operation(
            method = "POST",
            summary = "post.operation.description"    // this property is localized ok
  )
  public ResponseEntity<SomeObject> thePostOperation(args) {
///.....
  }
}
```


Could you please consider reopening the bug?
