### ISSUE TITLE
generic response not generated

### ISSUE THREAD

**Issue by calaracey** [springdoc/springdoc-openapi#1465]
**Describe the bug**

I have a controller method which returns a generic response like so:
```public` ServiceResponse<String> methodName() ```

However, the generated response type is always empty instead of including the ServiceResponse<String>: 
```responses":{"200":{"description":"OK","content":{}}}}}```

It is clear that the problem is the generic "ServiceResponse" wrapper because when I remove it the response type is successfully generated. 

I'm not sure if I am just doing something wrong, or perhaps generics are not supported, but I thought it was a common enough use case to be worth filing an issue to get some clarity.

**To Reproduce**
- What version of spring-boot you are using?
  2.6.1
- What modules and versions of springdoc-openapi are you using?
    \<groupId>org.springdoc\</groupId>
    \<artifactId>springdoc-openapi-ui\</artifactId>
    \<version>1.5.13\</version>
- What is the actual and the expected result using OpenAPI Description (yml or json)?
   See above. Actual result is that the "content" field in response is empty. Expected result is that ServiceResponse<String> is generated as the content response type.
- Provide with a sample code (HelloController) or Test that reproduces the problem
   See above.

**Comment by calaracey** [comment]
Some additional details: 

Here is an example of the ServiceResponse class:
```
public class ServiceResponse<T> {
    private Enum serviceResponseCode;
    private T response;
}
```
I also discovered that there was an error I had missed: 
```
2022-01-27 15:57:55 [http-nio-8081-exec-1] WARN  o.s.core.SpringDocAnnotationsUtils - Graceful exception occurred
2022-01-27T15:57:55.460627100Z java.lang.NullPointerException: Cannot read the array length because "enumConstants" is null
```

I suspect that there is some issue with using the base ```Enum``` type with SpringDoc.  A workaround solution is to use a specific Enum implementation which is what worked for me. Alternatively, you might be able to use a generic instead of an Enum.

**Comment by bnasslahsen** [comment]
@calaracey, 

As explained in the [contribution guide](https://github.com/springdoc/springdoc-openapi/blob/master/CONTRIBUTING.adoc), before reporting any bugs: **we advise you to use the last available release.** 

Not reproducible using: `v1.6.5`
