### ISSUE TITLE
Resolved [ResponseStatusException: 404 NOT_FOUND] for HTTP GET /swagger-ui

### ISSUE THREAD

**Issue by durgesh8** [springdoc/springdoc-openapi#1466]
I have configured springdoc openApi in my sprint boot app. 
spring boot version -> id("org.springframework.boot") version "2.6.2"
springgoc version -> implementation("org.springdoc:springdoc-openapi-webflux-ui:1.6.4")

In local when i access the baseurl/contextpath/swagger-ui.html i can see the sawgger-ui.html page loaded.
but when deployed to cloud its giving 404 issue. > Resolved [ResponseStatusException: 404 NOT_FOUND] for HTTP GET /swagger-ui

properties in app.properties:
springdoc:
  show-actuator: true  #use this flag to include spring-boot-actuator endpoints to swagger-ui
  webjars:
    prefix:  #use this to add prefix in swagger url

**Comment by bnasslahsen** [comment]
@durgesh8, 

Read the [contributing guidelines](https://github.com/springdoc/springdoc-openapi/blob/d8c3d0cbaa79fbf30e120637a75317a9f8056f47/CONTRIBUTING.adoc).
Make sure you answer all the questions and don't forget to Provide a [Minimal, Reproducible Example - with HelloController ](https://stackoverflow.com/help/minimal-reproducible-example)that reproduces the problem.

**Comment by bpawan** [comment]
I have a similar problem when following combination.
**OS**:
```
NAME="Ubuntu"
VERSION="20.04.5 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.5 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal

```

**Java version:** 
```
openjdk version "17.0.6" 2023-01-17
OpenJDK Runtime Environment Temurin-17.0.6+10 (build 17.0.6+10)
OpenJDK 64-Bit Server VM Temurin-17.0.6+10 (build 17.0.6+10, mixed mode, sharing)
```
**Maven version:** 
```
Apache Maven 3.6.3
Maven home: /usr/share/maven
Java version: 17.0.6, vendor: Eclipse Adoptium, runtime: /home/<user>/.sdkman/candidates/java/17.0.6-tem
Default locale: en_AU, platform encoding: UTF-8
OS name: "linux", version: "5.15.0-60-generic", arch: "amd64", family: "unix"

```


**Spring boot parent:**
```
<parent>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-starter-parent</artifactId>
    <version>3.0.3</version>
    <relativePath /> <!-- lookup parent from repository -->
</parent>
``` 

**Spring dependencies**
```
<dependency>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-starter-webflux</artifactId>
</dependency>

<dependency>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-starter-security</artifactId>
</dependency>
```
**and springdoc dependency**
```
<dependency>
    <groupId>org.springdoc</groupId>
    <artifactId>springdoc-openapi-webflux-ui</artifactId>
    <version>1.6.15</version>
</dependency>

<dependency>
    <groupId>org.springdoc</groupId>
    <artifactId>springdoc-openapi-security</artifactId>
    <version>1.6.15</version>
</dependency>
```
I did tried tried completelöy disabling security but still no luck.

**Comment by bnasslahsen** [comment]
@bpawan, 

Read the doc please: https://springdoc.org/#Introduction for spring-boot v3
You should use https://springdoc.org/v2/

Your project is using wrong versions. 1.6.x is for spring-boot-1 and 2 only.
