### ISSUE TITLE
How do I set the request to HTTPS

### ISSUE THREAD

**Issue by YAGAMIL** [springdoc/springdoc-openapi#1467]
When I publish, I will use HTTPS requests instead of HTTP, but swagger original URL is still HTTP, I have no idea how to set it up, and there is no documentation for servers in the original springdoc-openapi-ui configuration

 
![image](https://user-images.githubusercontent.com/16757285/151095703-6494b4b3-0444-45f8-9370-05f930da75a7.png)

I have the same problem in Springfox, but I have been fixed in 3.0.1.

https://github.com/springfox/springfox/issues/3468

**Comment by bnasslahsen** [comment]
see answer here: https://github.com/springdoc/springdoc-openapi/issues/171
