### ISSUE TITLE
Whether the project structure can be adjusted

### ISSUE THREAD

**Issue by Hccake** [springdoc/springdoc-openapi#1476]
First of all, I'm really sorry that I opened another issue. The last issue I opened, issue #1450, was marked as a duplicate, but it wasn't actually a duplicate, and I can't reply right now.

I just want to discuss whether **springdoc-openapi-common** can be split into smaller and simpler modules, such as adding a **springdoc-openapi-core** module to migrate some necessary annotations and models from common?
Or move the `spring.factories` file to other modules, so that **springdoc-openapi-common** is no longer automatically configured in spring-boot？

For example, there are the following module divisions：
```
|-- common-model			
|-- server-a		
|-- server-b
```
Some query objects are defined in the common-model module, using the `@ParameterObject` annotation, so it introduces the springdoc-openapi-common dependency.

server-b is a spring-boot project that does not require external openapi documentation, but since it depends on common-model, we have to add springdoc shutdown configuration for it. Even when upgrading the springdoc version, there will be previous exceptions, like #1446.

Based on the above scenario, I hope **springdoc-openapi-common** can make some adjustments, 

thank you

**Comment by bnasslahsen** [comment]
@Hccake, 

There is [ongoing enhancements](https://github.com/springdoc/springdoc-openapi/tree/2.x).
`springdoc-openapi-common` will be renamed to `springdoc-openapi-starter-common` to be more explicit.
But if you want disable it. Just exclude the related auto-configuration classes located in the `spring.factories`.

If you have better enhancement and feel free to propose a PR (Just make sure there is no duplication in your PR!).

**Comment by Hccake** [comment]
@bnasslahsen 

Thanks for your reply, I tried making a little change on the master branch and opened a PR.

Just added a new module and moved some files to this module, without changing any package names for compatibility.

Please review when you have time
