### ISSUE TITLE
Springdoc BOM overrides spring boot version

### ISSUE THREAD

**Issue by nkvaratskhelia** [springdoc/springdoc-openapi#1479]
Gradle 7.3.3, Spring Boot 2.6.3, springdoc-openapi bom 1.6.5

In `gradle.build`, when using spring boot plugin `id 'org.springframework.boot' version '2.6.3'` and springdoc-openapi bom (`mavenBom 'org.springdoc:springdoc-openapi:1.6.5'`), spring boot version is overriden by the version from springdoc-openapi bom (screenshot below).

![image](https://user-images.githubusercontent.com/16168235/151384973-645618c0-ecb0-4b22-a549-124f7d15a907.png)

Same problem with these dependencies described in the bom:

![image](https://user-images.githubusercontent.com/16168235/151386231-f18723df-3b95-42c8-a6c1-7d63f7e7c04f.png)

[Minimal reproducer](https://github.com/nkvaratskhelia/springdoc-openapi-demo)

**Expected behavior**
`springdoc-openapi` bom should only be responsible for `sprindoc-openapi-*` dependency versions.

**Comment by bnasslahsen** [comment]
@nkvaratskhelia, 

`springdoc-openapi` is not overriding anything.
Make sure you use the right syntax.

See the [demos](https://github.com/springdoc/springdoc-openapi-demos), which are based on spring-boot 1 / 2 with so many versions ....

**Comment by nkvaratskhelia** [comment]
Hi @bnasslahsen,

I'm using the syntax according to your comment here: #1420.
Regarding the demos, there doesn't seem to be a single gradle example there, so not sure which demos you mean.

**Comment by bnasslahsen** [comment]
@nkvaratskhelia, 

The demos shows you the sprindoc BOM is not overriding spring-boot version.
For gradle, while importing Multiple Boms which is your case, If you import more than one bom, the order in which the boms are imported can be important. 
The boms are processed in the order in which they are imported.

So this is a sample configuration that you can adapt:
```groovy
dependencyManagement {
	imports {
		mavenBom 'org.springdoc:springdoc-openapi:1.6.5'
		mavenBom 'org.springframework.boot:spring-boot-dependencies:2.6.3'
	}
}
```
