### ISSUE TITLE
Include /oauth/token endpoint using OpenApi Swagger 1.6.5

### ISSUE THREAD

**Issue by ZamasuG** [springdoc/springdoc-openapi#1481]
**Describe the bug**
I'm trying to show /oauth/token endpoint in Swagger output JSON. I already include the following dependency into the project:

```
<dependency>
    <groupId>org.springdoc</groupId>
    <artifactId>springdoc-openapi-security</artifactId>
    <version>1.6.5</version>
</dependency>
```

I include the regular dependency too:

```
<dependency>
    <groupId>org.springdoc</groupId>
    <artifactId>springdoc-openapi-ui</artifactId>
    <version>1.6.5</version>
</dependency>
```

I'm using the following oauth dependency:

```
<dependency>
    <groupId>org.springframework.cloud</groupId>
    <artifactId>spring-cloud-starter-oauth2</artifactId>
</dependency>
```

When I go to the Swagger endpoint in browser, I'm getting the following endpoints:

/oauth/authorize
/oauth/check_token
/oauth/token_key

But, POST /oauth/token endpoint is not getting generated.

Could you help please?

**Comment by bnasslahsen** [comment]
`spring-cloud-starter-oauth2` is not at all supported.
Try providing a [Minimal, Reproducible Example - with HelloController ](https://stackoverflow.com/help/minimal-reproducible-example)that reproduces this missing endpoint. So we can know the exact problem you are facing.

**Comment by ZamasuG** [comment]
Hello @bnasslahsen,

I found the solution. I created a HelloController and I realized that I had a proxy for retries (org.aspectj:aspectjrt:1.9.5).

Something like that:

`
public class TokenEndpointRetryInterceptor {

    private static final int MAX_RETRIES = 3;

    @Around("execution(* org.springframework.security.oauth2.provider.endpoint.TokenEndpoint.*(..))")
    public Object execute (ProceedingJoinPoint aJoinPoint) throws Throwable {
        int tts = 1000;
        final var log = new OauthLogger();
        for (int i=1; i<=MAX_RETRIES; i++) {
            try {
                return aJoinPoint.proceed();
            } catch (DuplicateKeyException e) {
                log.logInterceptorTrace(i,  aJoinPoint.getSignature().getName());
                Thread.sleep(tts);
                tts=tts*2;
            }
        }
        throw new IllegalStateException("Could not execute: " + aJoinPoint.getSignature().getName());
    }
}
`

With Aspect and Component annotations above the class.

I removed the class and the /oauth/token endpoint appears...

Do you know how I could include both?

**Comment by bnasslahsen** [comment]
@ZamasuG, 

I don't have the elements to answer you.
Try providing a [Minimal, Reproducible Example - with HelloController ](https://stackoverflow.com/help/minimal-reproducible-example)that reproduces this missing endpoint. 

I am closing this ticket and it will reopened if you provide the relevant information.

**Comment by ZamasuG** [comment]
Hello @bnasslahsen, 

Sorry for the inconvenience. I have a [Minimal, Reproducible Example - with HelloController](https://stackoverflow.com/help/minimal-reproducible-example) here: https://github.com/ZamasuG/springdoc-hello-controller

While I was preparing the example for you, I realized that there are two dependencies that conflict with OpenApi:

```
		<dependency>
			<groupId>org.aspectj</groupId>
			<artifactId>aspectjrt</artifactId>
			<version>1.9.5</version>
		</dependency>

		<dependency>
			<groupId>org.springframework.cloud</groupId>
			<artifactId>spring-cloud-starter-netflix-hystrix</artifactId>
		</dependency>
```

If you remove one of them, /oauth/token endpoint appears. I don't know why. Anyways, I give you the example with the error.

Thanks you and sorry for the delay.
