### ISSUE TITLE
Swagger UI not POSTing JSON

### ISSUE THREAD

**Issue by mnoky** [springdoc/springdoc-openapi#1482]
**Describe the bug**

I have a Spring Boot REST app that is Swagger-enabled using springdoc-openapi-ui. I can't get the generated Swagger UI to actually POST JSON *and* show the user-friendly form.

If I add the `@ParameterObject` annotation to the controller method, then the Swagger UI will show all the POJO fields in a user-friendly form with all the `@Schema` documentation. However, then the Swagger UI won't submit JSON to the backend (it marshalls the POJO fields using request parameters).

If I omit the `@ParameterObject` annotation on the controller method, the Swagger UI will submit JSON to the backend. However, the Swagger UI won't show all the user-friendly form fields with all the `@Schema` documentation.

Am I missing something or is this a bug?

**To Reproduce**

Spring Boot: 2.6.3, springdoc-openapi-ui: 1.6.5

POJO:
```
@Schema(description = "my pojo")
@Data
public static class SampleData {
    @Schema(description = "friendly msg for users")
    private String info;		
}
```
Controller:
```    
@PostMapping(value = "/test", consumes = "application/json")
public void postData(@ParameterObject @RequestBody SampleData data) {
    // do something
}
```
After clicking "Try it out" and "Execute" in the Swagger UI, the request fails with:
```
{
  "status": 415,
  "error": "Unsupported Media Type",
  ...
}
```
Because the UI tried to POST this:
```
http://localhost:8080/test?info=test
```
The generated curl command is also incorrect (not POSTing JSON):
```
curl -X 'POST' \
  'http://localhost:8080/test?info=test' \
  -H 'accept: */*' \
  -d ''
```

**Expected behavior**

I expect the Swagger UI to POST JSON instead of submitting request parameters

**Comment by bnasslahsen** [comment]
@mnoky, 

`@ParameterObject` is not relevant in your case.
You should remove it, as you are changing the nature of the expected request.
If you choose the other tab  `Schema`, you get  the user-friendly form fields with all the @Schema documentation.

![image](https://user-images.githubusercontent.com/13404829/151657675-1abd1a0e-8aac-4b16-a2fa-c47eed08ed44.png)

And you can get this description displayed by default using:

```properties
springdoc.swagger-ui.defaultModelRendering=model
```

**Comment by mnoky** [comment]
Thank you for your quick response!

To further complicate things, I was previously using the config parameter `springdoc.default-produces-media-type: application/json` in my `application.yml` which was preventing the "Schema" view from rendering in the Swagger UI. I removed that and now I can actually see/access the "Schema" link in the UI.

The additional `defaultModelRendering` config parameter then worked fine. Not exactly the solution I was hoping for (would have liked for my users to see the docs in the "Try it Out" view), but this works. 

Thanks again.
