### ISSUE TITLE
@RepositoryRestResource enhancement

### ISSUE THREAD

**Issue by migueltercero** [springdoc/springdoc-openapi#1484]
**Describe the bug**
When document spring data rest repositories with `@RepositoryRestResource`, methods declared by CrudRepository or PagingAndSortingRepository are ignored by springdoc.  Custom methods works fine.

**To Reproduce**

Declare RepositoryRestResource repository,  and annotate method inherit from PagingAndSourtingRepository, for example, findById with `@Operation` or `@ApiResponses`:
```
@RepositoryRestResource(collectionResourceRel = "people", path = "peopleme")
public interface PersonRepository extends PagingAndSortingRepository<Person, Long> {
	
	@Operation(summary = "find by id")
	@ApiResponses(
			value = {
					@ApiResponse(responseCode = "200", description = "successful operation"),
					@ApiResponse(responseCode = "400", description = "Invalid ID supplied"),
					@ApiResponse(responseCode = "404", description = "Contact not found"),
					@ApiResponse(responseCode = "405", description = "Validation exception") }
	)
	@RestResource
	Optional<Person> findById(Long id);
```

**Expected behavior**

When call to `/v3/api-docs`, `paths['/peopleme/{id}'].get.description` must be description declared by `@Operation` annotation.

```
	@Test
	void given_repositoryRestResource_when_getApiDocs_then_findByIdDocumentationOk() {
		// @formatter:off
		given()
		.when()
			.get("/v3/api-docs")
		.then()
			.status(HttpStatus.OK)
			.rootPath("paths['/peopleme/{id}']")
				.body("get.description", equalTo("find by id"));
		// @formatter:on
	}
```

You can check issue in:

https://github.com/migueltercero/springdoc-issue

https://github.com/migueltercero/springdoc-issue/blob/master/src/test/java/test/org/springdoc/api/app21/PersonRepositoryTest.java

**Comment by bnasslahsen** [comment]
@migueltercero, 

This has never been supported. As the majority of use cases, people do not override the base repositories !
They only add the search methods, which are supported out of the box.
See the initial [support here for more details](https://github.com/springdoc/springdoc-openapi/issues/644)

Note that you can add your desired changes to the spring-data-rest endpoints using OpenApiCustomiser.

**Comment by migueltercero** [comment]
Thank you for your quickly response!!!

People must override base repositories for security reasons. For example, if you want control wich methods must be exposed or not:

https://docs.spring.io/spring-data/rest/docs/current/reference/html/#getting-started.setting-repository-detection-strategy

And perhaps `findById` isn´t the best example. For example, method `Page<T> findAll(Predicate predicate, Pageable pageable);`
is from base repository `QuerydslPredicateExecutor` from spring data:

```
@RestResource
Page<T> findAll(Predicate predicate, Pageable pageable);
```

When use queryDSL, you need document `Predicate` options, is not trivial like `save`/ `path` / `put`. You need to specify wich param supports, type ...

I know that can be documented use `OpenApiCustomiser`, but isn´t the best option. Support open api annotations in this methods would be great!!

Thank you!!
