### ISSUE TITLE
Documentation on passing the springdoc properties

### ISSUE THREAD

**Issue by knyttl** [springdoc/springdoc-openapi#1485]
**Is your feature request related to a problem? Please describe.**

I am trying to pass the springdoc java properties programmatically. I am following the documentation in:

https://springdoc.org/#swagger-ui-properties

And official swagger doc:

https://swagger.io/docs/open-source-tools/swagger-ui/usage/configuration/

It seems that setting the parameters programmatically as:

```kotlin
@Configuration
@ComponentScan(basePackages = ["org.springdoc"])
@Import(OpenApiSecurityConfig::class)
open class OpenApiConfig(
    @Value("#{systemEnvironment['SERVICE_NAME']?:''}")
    private val serviceName: String,
) : WebMvcConfigurer {
    init {
        // For details, see https://springdoc.org/#swagger-ui-properties
        System.setProperty("springdoc.swagger-ui.path", "/services/$serviceName")
        System.setProperty("springdoc.swagger-ui.url", "/services/$serviceName/v3/api-docs")
        System.setProperty("springdoc.swagger-ui.configUrl", "/services/$serviceName/v3/api-docs/swagger-config")
        System.setProperty("springdoc.swagger-ui.showCommonExtensions", "true")
    }
}
```

Is too late and therefore ignored. I cannot use static parameters file as I need to take into account the `SERVICE_NAME` variable.

**Describe the solution you'd like**
It would be great to add description programmatically setting the springdoc java properties.

**Describe alternatives you've considered**
I couldn't find any other solution.

**Additional context**
🙏 🙏 🙏 🙏 🙏

**Comment by bnasslahsen** [comment]
@knyttl, 

psringdoc properties are spring-beans that you can access programatically. 
Use `SwaggerUiConfigProperties` bean for your case.

This is sample code that you can adapt.

```java
@Bean
public Set<SwaggerUrl> apis(SwaggerUiConfigProperties swaggerUiConfig) {
	Set<SwaggerUrl> swaggerUrlSet = new HashSet<>();
	SwaggerUrl wsResource = new SwaggerUrl( "TPS", "/swagger.json");
	swaggerUrlSet.add(wsResource);
	SwaggerUrl notificationResource = new SwaggerUrl( "NOTIFICATION", "/notification-swagger.json");
	swaggerUrlSet.add(notificationResource);
	swaggerUiConfig.setUrls(swaggerUrlSet);
	return swaggerUrlSet;
}
```

**Comment by knyttl** [comment]
Thanks, this has helped. Solved with:

```
    @Bean
    open fun swaggerUiConfig(config: SwaggerUiConfigProperties): SwaggerUiConfigProperties {
        // For details, see https://springdoc.org/#swagger-ui-properties
        // Controls the display of extensions (pattern, maxLength, minLength, maximum, minimum) fields and values for Parameters.
        config.showCommonExtensions = true
        // Allows to configure source for the documentation via query params (?url=/v3/api-docs).
        config.queryConfigEnabled = true
        return config
    }
```

Maybe you could add this to the documentation?

**Comment by bnasslahsen** [comment]
Sure.
Feel free to propose your PR to the [F.A.Q](https://github.com/springdoc/springdoc.github.io/blob/master/src/docs/asciidoc/faq.adoc).
