### ISSUE TITLE
How to customize the Swagger UI files

### ISSUE THREAD

**Issue by mjovanc** [springdoc/springdoc-openapi#1487]
I'm using Spring Boot project with Gradle and I'm trying to understand how to modify the Swagger UI HTML/CSS/JS files so I can customize it so it looks similar to my project. I tried putting the _dist_ directory inside resources folder and rebuild, but nothing changed. I tried also to exclude the org.webjars, swagger-ui but that just gave me an empty whitelabel page. 

I started get suspicious how I put my files since I saw somewhere that you need to convert all the files you modified to a webjar? Is this true? And how would I do that?

Anyway, could someone give me a simple example how to load these files and into what directory using Gradle as my build tool?

**Comment by bnasslahsen** [comment]
@mjovanc, 

See samples here https://github.com/springdoc/springdoc-openapi/issues/737

**Comment by mjovanc** [comment]
For other people encountering this, I wrote an article how to achieve it: https://medium.com/@mjovanc/how-to-customize-your-swagger-ui-with-spring-boot-and-gradle-2fd32508c29a
