### ISSUE TITLE
after restart "No API definition provided.", should redirect to default

### ISSUE THREAD

**Issue by 2019-05-10** [springdoc/springdoc-openapi#1488]
load UI
navigate to an end-point
execute

restart browser
address bar still contains old (working) url "localhost:8888/swagger-ui/index.html#/my/endpoint"
page is empty and only shows "No API definition provided."
reloading does not change anything

I need to manually edit the url to
"localhost:8888/swagger-ui/"
OR
type "/v3/api-docs" into the "Explore" field

Expected:
If "No API definition provided." go to the default (be it "springdoc.swagger-ui.path" OR "/v3/api-docs"), instead of simply sitting there.

I tried several settings, but so far none worked.

**Comment by bnasslahsen** [comment]
@2019-05-10, 

If you believe, you are facing an issue, make sure you follow and provide all the relevant information listed in the [Contribution guidelines.](https://github.com/springdoc/springdoc-openapi/blob/master/CONTRIBUTING.adoc)
Especially, make sure you provide a [Minimal, Reproducible Example - with HelloController](https://stackoverflow.com/help/minimal-reproducible-example) that reproduces the problem.

This ticket will be closed, and can be reopened if any relevant information is provided.
