### ISSUE TITLE
subsequent endpoint-executions pause 10secs before start

### ISSUE THREAD

**Issue by 2019-05-10** [springdoc/springdoc-openapi#1489]
The first execution of an end-poit is rather quick.
Every new attempt after that does nothing for about 10 seconds.
Only then the spinner starts and a request is send.
Browser console shows nothing.

springdoc 1.6.1
Vivaldi 5.0.2497.51

**Comment by bnasslahsen** [comment]
@2019-05-10, 

If you believe, you are facing an issue, make sure you follow and provide all the relevant information listed in the [Contribution guidelines.](https://github.com/springdoc/springdoc-openapi/blob/master/CONTRIBUTING.adoc)
Especially, make sure you provide a [Minimal, Reproducible Example - with HelloController](https://stackoverflow.com/help/minimal-reproducible-example) that reproduces the problem.

This ticket will be closed, and can be reopened if any relevant information is provided.
