### ISSUE TITLE
Is it possible show or hide endpoints based on Spring Security roles? (Like ROLE_USER, ROLE_ADMIN, etc)

### ISSUE THREAD

**Issue by ZamasuG** [springdoc/springdoc-openapi#1494]
I'm building a Spring Boot project with Maven as a Gateway in order to serve several Swagger specifications. I want to hide or show endpoints based on roles, but I did not find any documentation related to this. Is this possible? 

If this is possible... Could someone give me a simple example that explain how to hide or show endpoints based on role?

Thanks!!

**Comment by bnasslahsen** [comment]
@ZamasuG, 

There is no such a feature support out of the box.
