### ISSUE TITLE
Add support to generate components.schemas documentation from schema classes javadoc

### ISSUE THREAD

**Issue by mnisius** [springdoc/springdoc-openapi#1495]
**Is your feature request related to a problem? Please describe.**
Hello I noticed that springdoc-openapi-javadoc only adds javadoc from controller classes to the openapi specification.
But I also want to describe my specification classes with javadoc. I have javadoc on all my specification classes and on all their attributes and I want to have it in my openapi specification as well. 

**Describe the solution you'd like**
Grap the Javadoc from the specification classes and add them to the openapi specification. Grab the class level javadoc to generate the components.schemas.$classname.description and Grab the javadoc on the getter Methods to generate the components.schemas.$classname.properties.$propertyname.description.

**Comment by bnasslahsen** [comment]
@mnisius, 

There is no plans to support this feature.
Please feel free to propose a PR, if you feel it useful for the community.
