### ISSUE TITLE
Choose pre-selected server by host or make pre-selected server configurable by env var when displaying provided spec

### ISSUE THREAD

**Issue by SamyAteia** [springdoc/springdoc-openapi#1497]
I'm using spring doc with the following configuration to display a provided api specification file as [described in the faq](https://springdoc.org/#what-is-a-proper-way-to-set-up-swagger-ui-to-use-provided-spec-yml):
```
springdoc.api-docs.enabled=false
springdoc.swagger-ui.url=/spec.yml
springdoc.swagger-ui.use-root-path=true
```
When having multiple servers defined in the provided OpenAPI 3 specification, the first entry is always preselected in springdoc.
Users often forget to choose the correct environment before trying out API requests in the ui, which leads to unexpected errors.

Instead it would be nice if springdoc would select the server that is matching the host where the springdoc ui is served from by default.
It would be also nice if this preselected server is configurable via an environment variable.

See the following similar swagger-ui issue, with workarounds:
[4751](https://github.com/swagger-api/swagger-ui/issues/4751)

Related S[tack Overflow question](https://stackoverflow.com/questions/70876274/how-to-configure-the-selected-server-environment-from-the-servers-dropdown-in-sp) that I asked.

**Comment by bnasslahsen** [comment]
@SamyAteia, 

This should be on option in the swagger-ui out of the box.
There is no plan for it in springdoc-openpai.
