### ISSUE TITLE
Support for @ExceptionHandler inside @RestController only works if a @RestControllerAdvice class is present

### ISSUE THREAD

**Issue by SimonAlthoff** [springdoc/springdoc-openapi#1498]
**Describe the bug**
The @ExceptionHandler methods inside a @RestController are picked up correctly if and only if there is at least one class present which is annotated with @RestControllerAdvice. This class might be empty, though.

**To Reproduce**
I created a fork of the master branch and added a new test app182 which is a copy of the test app124.
Except that both @ExceptionHandlers are contained in the @RestController and the @RestControllerAdvice class was removed.

https://github.com/SimonAlthoff/springdoc-openapi/commit/8db9112a0be42ad41f9f3c6a8844570b0fc43cdf

**Expected behavior**
@ExceptionHandler within a @RestController are picked up even when no @RestControllerAdvice class exists.

**Additional context**
The original feature was implemented in ticket #748

**Comment by eshishkin** [comment]
I have created a simple PR for fixing this issue - https://github.com/springdoc/springdoc-openapi/pull/1500
Suppose, it can help
