### ISSUE TITLE
Support @RequestMapping.param for overloaded endpoints

### ISSUE THREAD

**Issue by membersound** [springdoc/springdoc-openapi#15]
In spring it is possible to create multiple endpoints on the same path, that only differ by parameters.

```
@RestController
public class SearchController {
    @GetMapping(path = "/items", params = "name")
    public Object searchItemsByName(String name) {

    }

    @GetMapping(path = "/items", params = "description")
    public Object searchItemsByDescription(String description) {

    }
}
```

It would be nice if springdoc could render those endpoints as 2 distinct endpoints, so that both are shown individually.

If we'd make the query parameters a bean here, maybe you could detect the overloaded endpoints, and generate `parameters.schema.oneOf`? But I'm not sure if that would help.

```
{
 "path": {
   "/items:" {
     "get": {
       "parameters": [
	 {
	    "name": "req",
	    "in": "query",
	    "schema": {
		"oneOf": [
		    {
		        "$ref": "#/components/schemas/FirstFilter"
		    },
		    {
		        "$ref": "#/components/schemas/SecondFilter"
		    }
		]
	    }
	 }
       ]
     }
   }
}
```

**Comment by springdoc** [comment]
This feature is not a priority and the importance should be proven before being addressed.
It needs to be clearly described as well.
It's  not the natural choice, to create two methods for the same API resource. I will encourage you to refactor and review the design of the APIs instead.
For example, if we have swagger annotation @Operation with a description of both, which one will be chosen. Same question for all the fields. summary, operationId, .
