### ISSUE TITLE
Is it possible to get final .html documentation [Question]

### ISSUE THREAD

**Issue by kuza2010** [springdoc/springdoc-openapi#1503]
Hi!
I'd like my swagger UI page be accessible from Vue client only for users who have certain role. 
To do that, at the backend I configured http security and cors policy. So, only users with specific role have access to `/swagger-ui.html` page. But when I'm trying to fetch that page I get initial [index.html](https://github.com/swagger-api/swagger-ui/blob/master/dist/index.html).

I am expecting to see the final .html page, like [Demo Spring Boot 2](http://158.101.191.70:8081/) 

I found a class `SwaggerIndexTransformer` can be helpful with page transformation, but I can't understand how to apply that.
What is my options here?

**Comment by bnasslahsen** [comment]
@kuza2010, 

This is not the goal of `springdoc-openapi`.
You need to look at the possibilities available in the swagger-ui directly.
