### ISSUE TITLE
springdoc.override-with-generic-response should add only Controller Advices for thrown Exceptions.

### ISSUE THREAD

**Issue by ChrTall** [springdoc/springdoc-openapi#1504]
**Describe the bug**
 If you enable springdoc.override-with-generic-response all ControllerAdvices are added to all Endpoints even though only some of them throw the exception that is handled by the Controller advice.

**To Reproduce**
- spring-boot-starter-web version 2.6.3
- springdoc-openapi-ui version: 1.6.4
- add springdoc.override-with-generic-response=true to application.properties
- Create a Controller that throws an exception that is handled by a @ControllerAdvice.
- The Response for the Controller Advice is added to all Endpoints even though only 1 Endpoint throws the exception. 

`@DeleteMapping("/charts/{chartId}") @Operation(summary = "Deletes a Chart.")
    public ResponseEntity<?> deleteChart(@PathVariable long chartId) throws ChartNotFoundException {
        chartService.delete(chartId); return ResponseEntity.noContent().build();
    }`

`@ApiResponse(responseCode = "404", description = "The Chart was Not Found.",
            content = {@Content(mediaType = MediaType.APPLICATION_JSON_VALUE,
                    schema = @Schema(implementation = ExceptionResponse.class))})
    @ResponseBody
    @ExceptionHandler(ChartNotFoundException.class)
    @ResponseStatus(HttpStatus.NOT_FOUND)
    public ExceptionResponse chartNotFoundExceptionHandler(ChartNotFoundException ex, HttpServletRequest request) {
        logger.debug("Requested Chart could not be found.", ex);
        return new ExceptionResponse(ex.getMessage(), request.getRequestURI());
    }
`

`@GetMapping("/charts")
 @Operation(summary = "Returns a List of all saved Charts.")
 public ResponseEntity<List<ChartDto>> getAll() {
        return ResponseEntity.ok(chartService.findAll(false));
    }
`

**Expected behavior**
- Only the Endpoint that actually throws the exception should get a Response for that Exception Response.

This would be great, because you could define the Response once for an exception. At the moment I have to add the Response to every Endpoint where the Exception is thrown.

**Comment by bnasslahsen** [comment]
@ChrTall, 

Such a feature doesn't make sense especially for uncheked exceptions.
