### ISSUE TITLE
Schema/example for Java Time classes do not match content 

### ISSUE THREAD

**Issue by jlous** [springdoc/springdoc-openapi#1506]
Recent versions of Spring Boot are by default aware of the Java Time types, and maps them to appropriate strings as you would usually want.
Springdoc-openapi, however, still uses introspection for these types.
The resulting documentation does not match what the API actually produces.  

**My setup**
- kotlin 1.6.10
- spring-boot-starter-parent 2.6.2
- springdoc-openapi-ui 1.6.6
- springdoc-openapi-kotlin 1.6.6
```
@RestController
class TestApi {
    @GetMapping("localTime")
    fun localTime(): LocalTime {
        return LocalTime.now()
    }

    @GetMapping("year")
    fun year(): Year {
        return Year.now()
    }
}
```

**Expected behavior**
- localTime returns something like "17:45:29.300235"
- year returns "2022"
- OpenAPI Description contains schemas somehow matching those formats

**Actual behavior**
- localTime returns something like "17:45:29.300235"
- year returns "2022"
- OpenAPI Description describe return values as respectively
```
{
  "type": "object",
  "properties": {
    "value": {
      "type": "integer",
      "format": "int32"
    },
    "leap": {
      "type": "boolean"
    }
  }
}
```
and
```
{
  "type": "object",
  "properties": {
    "hour": {
      "type": "integer",
      "format": "int32"
    },
    "minute": {
      "type": "integer",
      "format": "int32"
    },
    "second": {
      "type": "integer",
      "format": "int32"
    },
    "nano": {
      "type": "integer",
      "format": "int32"
    }
  }
}
```

**Comment by bnasslahsen** [comment]
@jlous, 

The support is available through the [swagger-core](https://github.com/swagger-api/swagger-core).
There is no change in the `springdoc-openapi` for that.

**Comment by bnasslahsen** [comment]
@jlous, 

This means this not implemented in springdoc-openapi. 
We do not mention java time in the code.  The java time support is implemented in [swagger-core](https://github.com/swagger-api/swagger-core) library.

**Comment by jlous** [comment]
Thanks for replying. The fact remains, though, that if I set up my app with:

- a default configuration of spring 
- a default configuration of springdoc-openapi starter, 
- no explicit mention of swagger-core anywhere

then the resulting documentation is just plain wrong.

If this is a bug in swagger-core, and it should have discovered the JavaTime mappings by itself, then I agree my report here is invalid.

But otherwise, the only solution left for users is to manually configure swagger-core in order to have springdoc-api work correctly with spring.  If that is the only way then it should at the very least be prominently documented.
Swagger-core can of course not be expected to know or care about Spring's changing defaults.
