### ISSUE TITLE
Spring Doc Open API swagger UI is not displaying attribute in snake case

### ISSUE THREAD

**Issue by viniljose** [springdoc/springdoc-openapi#1507]
**Spring Doc Open API swagger UI is not displaying attribute in snake case. I am using below configs**
`implementation group: 'org.springdoc', name: 'springdoc-openapi-webflux-ui', version: '1.6.5'
@OpenAPIDefinition(info = @Info(title = "Samples API", version = "1",
        description = "This is a sample api with Open API"),
        servers = { @Server(url = "/", description = "Default URL")})
spring.jackson.property-naming-strategy=snake_case`

**Describe alternatives you've considered**
-But the request body attribute is coming in camel case. If I add the below, request body attribute is coming in snake case.
`@Bean
public ModelResolver modelResolver(ObjectMapper objectMapper) {
     return new ModelResolver(objectMapper);
}`

**Additional context**
- [Post in Stackoverflow](https://stackoverflow.com/questions/71004537/spring-doc-open-api-swagger-ui-is-not-displaying-attribute-in-snake-case)
- Either there should be a property to achieve the same or it should come automatically

**Comment by bnasslahsen** [comment]
@viniljose, 

There is no plan for this.
Feel free to propose a PR if you find it useful for the community.
