### ISSUE TITLE
How can I add custom json to Open api object ?

### ISSUE THREAD

**Issue by jishnunitc** [springdoc/springdoc-openapi#1509]
https://github.com/springdoc/springdoc-openapi/blob/master/springdoc-openapi-webmvc-core/src/test/java/test/org/springdoc/api/app39/SpringDocTestApp.java

This example is about adding a Parameter.
can you please share any other example which i can use to add a json

**Comment by bnasslahsen** [comment]
Not clear.
Remember, contributions to this repository should follow its [contributing guidelines](https://github.com/springdoc/springdoc-openapi/blob/63d43a154a89c1da65103f0319f15a6fa441bd26/CONTRIBUTING.adoc)
