### ISSUE TITLE
Can support pageable params?

### ISSUE THREAD

**Issue by huijiewei** [springdoc/springdoc-openapi#151]

**Comment by springdoc** [comment]
Hi,

Can you please add more details about your request :

- What is the description of the actual behaviour ?
- What are the actual and the expected result using OpenAPI Description (yml or json)?
- Provide with a sample code code to reproduce it?

 This issue, will be reopened when you provide the necessary elements to investigate.

Thank you in advance.

**Comment by springdoc** [comment]
Finally, we have added the support of Pageable on a specefic module. #177

**Comment by Majlanky** [comment]
Hello,

I was not able to find the solution anywhere in the documentation. If you want to pageable behave as a set of standard parameters you **have to  add dependency** of `springdoc-openapi-data-rest` to your classpath and annotate your Pageable with @ParameterObject like:
```java
@Operation(description = "blahblah")
@GetMapping(value = ALL_URI, produces = MediaType.APPLICATION_JSON_VALUE)
public Whatever getAll(@ParameterObject @PageableDefault(size = 20, sort = "name") Pageable pageable) {
        ...
    }
```
The annotation of @ParameterObject causes additional customizing of Pageable. It even transfer setting of PageableDefault to the final documentation! 👍
