### ISSUE TITLE
Not able to populate description in @Schema with values from a yml file 

### ISSUE THREAD

**Issue by ObergG** [springdoc/springdoc-openapi#1511]
Version 1.6.6 and Boot 2.6.3

when converting a project from SpringFox we came across an issue where the placeholders for external documentation residing in a yml-file doesn't get substituted in our model. We have complex multi-line documentation in this file which makes it undesirable to create inline.    
	
	@Include
	@JsonProperty("version")
	@JsonInclude(ALWAYS)
	@Schema(description = "${linear.model.services.version}", required = true, example = "117")
	private Integer version;

Substitutes correctly in Springfox:

	@Include
	@JsonProperty("version")
	@JsonInclude(ALWAYS)
	@ApiModelProperty(value = "${linear.model.services.version}", required = true, example = "117")
	private Integer version;

**Comment by bnasslahsen** [comment]
use: `springdoc.api-docs.resolve-schema-properties=true`
