### ISSUE TITLE
Jackson core library version mismatch

### ISSUE THREAD

**Issue by vfedoriv** [springdoc/springdoc-openapi#1512]
Have strange behavior: 
I trying to integrate springdoc in a new project.
Spring boot version 2.6.3
In dependencies, **I have Jackson libraries dependencies, all with version 2.13.1**

Now I add springdoc in pom.xml
```
<dependency>
      <groupId>org.springdoc</groupId>
      <artifactId>springdoc-openapi-ui</artifactId>
      <version>1.6.6</version>
    </dependency>
```
then refresh maven dependencies and try to start the project.
And now I have exception on start:  Failed to introspect Class [com.fasterxml.jackson.databind.ObjectMapper]

When a look into dependencies I see that **for some reason jackson core library version was downgraded to 2.12.5:**
Maven: com.fasterxml.jackson.core:jackson-core:2.12.5
Other jackson libraries versions stay 2.13.1

After I directly specify jackson core in pom:
```
    <dependency>
      <groupId>com.fasterxml.jackson.core</groupId>
      <artifactId>jackson-core</artifactId>
      <version>2.13.1</version>
    </dependency>
```
and refresh dependencies, the problem is gone and I can successfully start the project and be able to reach out swagger endpoint.

**Comment by Anricx** [comment]
try
```java
<dependencies>
    <dependency>
        <groupId>org.springdoc</groupId>
        <artifactId>springdoc-openapi-ui</artifactId>
        <version>${springdoc-ui.version}</version>
        <exclusions>
            <exclusion>
                <groupId>com.fasterxml.jackson.core</groupId>
                <artifactId>jackson-core</artifactId>
            </exclusion>
        </exclusions>
    </dependency>
</dependencies>
```

**Comment by bnasslahsen** [comment]
@vfedoriv, 

If you don't want to rely on the `springdoc-openapi` transitive dependencies, you have so many ways to override it;
