### ISSUE TITLE
asyncAPI (again)

### ISSUE THREAD

**Issue by sdratepay** [springdoc/springdoc-openapi#1515]
**Is your feature request related to a problem? Please describe.**
- A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
Currently, springdoc does not provide support for asynchronous APIs, namely Apache Kafka Events

- What is the actual result using OpenAPI Description (yml or json)?
Nothing - it's not possible to create asyncAPI descriptions yet

**Describe the solution you'd like**
- A clear and concise description of what you want to happen.
We would be willing to invest some time, implement this for Apache Kafka Events, and provide a pull request

- What is the expected result using OpenAPI Description (yml or json)?
ideally, both

**Describe alternatives you've considered**
- A clear and concise description of any alternative solutions or features you've considered.
there are none, because the only available tools for Spring Boot are not very mature, and cannot be used for professional use in production environments

**Additional context**
- Add any other context or screenshots about the feature request here.
Question: if we would provide a pull request, and apply to your coding rules and quality standards, would you be willing to accept/merge it, and at some point take ownership of the code?

**Comment by bnasslahsen** [comment]
@sdratepay, 

Already answered here https://github.com/springdoc/springdoc-openapi/issues/1361 and https://github.com/springdoc/springdoc-openapi/issues/1203. 

Again, feel free to propose your PR!
