### ISSUE TITLE
Swagger UI Not working with Azure function

### ISSUE THREAD

**Issue by mayurgupta** [springdoc/springdoc-openapi#1516]
✏Note: I have created this issure here earlier : [https://github.com/springdoc/springdoc-openapi-demos/issues/38](https://github.com/springdoc/springdoc-openapi-demos/issues/38)
Which I dont think is the right place. So posting the same here and closing the previous one.

I have tried running **spring-cloud-function-webmvc** app. and hit the /swagger-ui URL. I can see swagger UI comming up, 
But when i put Azure function plugin in pom. The swagger UI stops comming you.
I have attached modified version of this working project with Azure function here.

[spring-cloud-function-webmvc.zip](https://github.com/springdoc/springdoc-openapi-demos/files/8097480/spring-cloud-function-webmvc.zip)

now when i start this project, it scans the end point correctly. Below is the startup logs:
![image](https://user-images.githubusercontent.com/4255397/154690995-c1dd3939-fd45-40c7-88f7-f404170348dd.png)

But hitting the Swagger url gives the following error :
URL: http://[localhost](http://localhost:8080/api/swagger-ui.html):8080/api/swagger-ui.html

![image](https://user-images.githubusercontent.com/4255397/154691166-161064bd-ccf9-4dd6-a4dd-52518c9ff901.png)

Is swagger UI not yet supported with Azure function?

Let me know if further info is required.

**Comment by bnasslahsen** [comment]
@mayurgupta, 

You sample is working just fine in local.
Not sure what you problem with Azure ...
