### ISSUE TITLE
Specify where to look for the api-docs by parameter

### ISSUE THREAD

**Issue by padmalcom** [springdoc/springdoc-openapi#1517]
We are publishing an openapi endpoint behind a proxy in kong and add a prefix to the url since each service is mapped to one base url, e.g. https://our-services.com/sales/api/v1/sales, https://our-services.com/hr/api/v1/hr ... where sales and hr are the newly added prefixes.

When we deploy our services, the endpoint is visible via https://our-services.com/sales/swagger-ui.html but if opens the pet store definition. We need to manually type in the edit field on top /sales/v3/api-docs and click explore to select the right endpoint. That works well but I'd like to request a feature to set the "exploration" field to a specific value via the application.yaml.

**Comment by bnasslahsen** [comment]
@padmalcom, 

Feel free to propose a PR for your feature request.
