### ISSUE TITLE
Customizer vs. Customiser

### ISSUE THREAD

**Issue by azizabah** [springdoc/springdoc-openapi#1518]
**Describe the bug**
- There are two similarly purposed objects where one is a customizer (American English) and one is a customiser (British English). We should aim for consistent names / English locale where possible. 

**Expected behavior**
- A single English locale is used in the code base.

**Comment by Anricx** [comment]
Customizer +1

**Comment by jefftindall** [comment]
Customizer +2

**Comment by linghengqian** [comment]
I haven't seen a description of these two differences on [springdoc.org](https://springdoc.org/) , can anyone point out the definitions of their usage and the corresponding links to the differences?

**Comment by bnasslahsen** [comment]
It will be `Customizer` for everything. This has been planned for while, but we need the right timing for it.
it's decided to have it for 2.x when the spring-boot 3 GA.

see [here](https://github.com/springdoc/springdoc-openapi/tree/2.x/springdoc-openapi-starter-common/src/main/java/org/springdoc/core/customizers) what is planned for 2.x.

You already a [preview version](https://springdoc.org/v2) with spring-boot 3.
