### ISSUE TITLE
Will springdoc-openapi support regular Spring Framework?

### ISSUE THREAD

**Issue by MrAsimov** [springdoc/springdoc-openapi#152]
Hi,

Will springdoc-openapi ever support regular Spring Framework (via WebMvcConfigurerAdapter)? Or do I have to use springfox instead for that?

**Comment by springdoc** [comment]
Hi, 

 SwaggerConfig class in the springdoc-openapi-ui module uses WebMvcConfigurerAdapter, in order to keep the compatibility for users using spring 4 or spring 5 versions.
 So there should be no issue with this class.

 By default, there is no need to do any additional configuration on WebMvcConfigurerAdapter.
 You just need:
```xml
   <dependency>
      <groupId>org.springdoc</groupId>
      <artifactId>springdoc-openapi-ui</artifactId>
      <version>1.2.4</version>
   </dependency>
```
 And to set the path for the swagger-ui, if you don't want serve the ui from the root context:
```properties
# swagger-ui custom path
springdoc.swagger-ui.path=/myapp/swagger-ui.html
```

**Comment by arturCwiklinsky** [comment]
Hi, I know that issue is closed but...

Is it possible to use springdoc-openapi 1.6.8 with Spring 5.3 and Configuration class that extend WebMvcConfigurationSupport?

I am facing the problem when everything works beside of swagger-ui page.

```
@Override
    public void addResourceHandlers(ResourceHandlerRegistry registry) {
        registry.addResourceHandler("/swagger-ui/**")
                .addResourceLocations("classpath:/META-INF/resources/webjars/swagger-ui/4.10.3/");
    }
```

This resource handler has helped me, but there's always default petstore doc. which is annoying.

**Comment by dawidtoczek** [comment]
> Hi, I know that issue is closed but...
> 
> Is it possible to use springdoc-openapi 1.6.8 with Spring 5.3 and Configuration class that extend WebMvcConfigurationSupport?
> 
> I am facing the problem when everything works beside of swagger-ui page.
> 
> ```
> @Override
>     public void addResourceHandlers(ResourceHandlerRegistry registry) {
>         registry.addResourceHandler("/swagger-ui/**")
>                 .addResourceLocations("classpath:/META-INF/resources/webjars/swagger-ui/4.10.3/");
>     }
> ```
> 
> This resource handler has helped me, but there's always default petstore doc. which is annoying.

What was the solution for your issue?

**Comment by jinyulei0710** [comment]
> default petstore doc



> > Hi, I know that issue is closed but...
> > Is it possible to use springdoc-openapi 1.6.8 with Spring 5.3 and Configuration class that extend WebMvcConfigurationSupport?
> > I am facing the problem when everything works beside of swagger-ui page.
> > ```
> > @Override
> >     public void addResourceHandlers(ResourceHandlerRegistry registry) {
> >         registry.addResourceHandler("/swagger-ui/**")
> >                 .addResourceLocations("classpath:/META-INF/resources/webjars/swagger-ui/4.10.3/");
> >     }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > This resource handler has helped me, but there's always default petstore doc. which is annoying.
> 
> What was the solution for your issue?

any solution?

**Comment by arturCwiklinsky** [comment]
Springdoc 2.2.0 and Spring 6 with `WebMvcConfigurationSupport`.

This helped us with SwaggerUI and OpenAPI configurations beans

```
@Resource
private SwaggerIndexTransformer indexPageTransformer;

@Resource
private SwaggerResourceResolver swaggerResourceResolver;

// We have to manually register resource handler for springdoc-ui
    @Override
    public void addResourceHandlers(ResourceHandlerRegistry registry) {
        registry.addResourceHandler("/swagger-ui*/**")
                .addResourceLocations("classpath:/META-INF/resources/webjars/")
                .resourceChain(false)
                .addTransformer(indexPageTransformer)
                .addResolver(swaggerResourceResolver);
    }
```

**Comment by arturCwiklinsky** [comment]
If you are configuring message converters like this

```
@Override
    public void configureMessageConverters(List<HttpMessageConverter<?>> converters) {
    ...
    }
```

Remember to put **ByteArrayHttpMessageConverter** at first place

```
@Bean
    public ByteArrayHttpMessageConverter byteArrayHttpMessageConverter() {
        return new ByteArrayHttpMessageConverter();
    }
```
