### ISSUE TITLE
Enable selection of which Actuator endpoints to document

### ISSUE THREAD

**Issue by Mumeii** [springdoc/springdoc-openapi#1521]
**Is your feature request related to a problem? Please describe.**

In my company, the API Management team is requesting us to expose our API documentation 

To do so, we're using springdoc !! :)

Unfortunately, they also require to expose a ping like endpoint

To do so, I'd like to : 
- use the Actuator heath endpoint feature
- then, activate the springdoc-openapi option that enable also exposing Actuator endpoints

But when I'm doing so, all available Actuator endpoints are exposed, whereas I'd like to expose only a single of those endpoints ...

Would it be possible to have more fine grained configuration parameter(s) : 
- Whitelisting mode : that would let users specify which endpoint patterns **should** be visible in the documentation
- Blacklisting mode : that would let users specify which endpoint patterns **shouldn't** be visible in the documentation

**Comment by bnasslahsen** [comment]
@Mumeii, 

Use:  `pathsToExclude`/`pathsToMatch` methods.
You have sample code here with groups:
- https://github.com/springdoc/springdoc-openapi-demos/blob/master/springdoc-openapi-spring-boot-2-webmvc/src/main/java/org/springdoc/demo/app2/Application.java
