### ISSUE TITLE
parameter of type com.querydsl.core.types.Predicate ignored when unique

### ISSUE THREAD

**Issue by metcox** [springdoc/springdoc-openapi#1522]
When an operation has a single parameter of type `com.querydsl.core.types.Predicate` annotated with `@QuerydslPredicate`, the generated schema does not expose the expected input query param.

Let's say we have the following operation:
```
@RequestMapping(method = RequestMethod.GET, value = "/operation")
@ResponseBody
public String operation(@QuerydslPredicate(root = MyUser.class) Predicate predicate) {
    return "hi";
}
```
we get something like
```
"/auth/operation":
    {"get":{
        "operationId":"operation",
        "responses":{"200":{"content":{"*/*":{"schema":{"type":"string"}}}}}
    }}
```
With a additional parameter:
```
@RequestMapping(method = RequestMethod.GET, value = "/operation")
@ResponseBody
public String operation(@QuerydslPredicate(root = MyUser.class) Predicate predicate, String param) {
    return "hi";
}
```

we get something like
```
"/auth/operation":
    {"get":{
        "operationId":"operation",
        "parameters":[
            {"name":"param","in":"query","required":true,"schema":{"type":"string"}},
            {"name":"firstName","in":"query","schema":{"type":"string"}}
        ],
        "responses":{"200":{"content":{"*/*":{"schema":{"type":"string"}}}}}
    }}
```
where firstName is a field of MyUser POJO.

The QuerydslPredicateOperationCustomizer class only customize the operation if parameters are found.

https://github.com/springdoc/springdoc-openapi/blob/c56df04de6128f0432552123c4ed4de5123d335d/springdoc-openapi-data-rest/src/main/java/org/springdoc/data/rest/customisers/QuerydslPredicateOperationCustomizer.java#L88-L91

However parameters of type Predicate are ignored

https://github.com/springdoc/springdoc-openapi/blob/58896787d7a5826c0e8841989c726eff330339e2/springdoc-openapi-data-rest/src/main/java/org/springdoc/data/rest/SpringDocDataRestConfiguration.java#L114-L120

**Comment by bnasslahsen** [comment]
Not reproducible.
Try providing a [Minimal, Reproducible Example - with HelloController](https://stackoverflow.com/help/minimal-reproducible-example) that reproduces the problem

**Comment by metcox** [comment]
Hello @bnasslahsen,

Sorry for the inconvenience. 
You will find a reproducible exemple here: https://github.com/metcox/springdoc-openapi/commit/42d281e57e0fa3559563a70da6b5532da051c2bb
the output does not contains any parameter but should have two.

**Comment by bnasslahsen** [comment]
@metcox, 

Exactly, agree.
