### ISSUE TITLE
[springdoc-openapi-data-rest] @RestResource(exported = false) does not work for custom existsByXyz methods

### ISSUE THREAD

**Issue by uqix** [springdoc/springdoc-openapi#1523]
**Describe the bug**

`@RestResource(exported = false)` does not work for custom `existsByXyz` methods

**To Reproduce**
- What version of spring-boot you are using? 2.5.4
- What modules and versions of springdoc-openapi are you using? springdoc-openapi-data-rest
- Provide with a sample code (HelloController) or Test that reproduces the problem

```java
package app.pricequery;

import org.springframework.data.repository.CrudRepository;
import org.springframework.data.rest.core.annotation.RepositoryRestResource;
import org.springframework.data.rest.core.annotation.RestResource;

@RepositoryRestResource
public interface DisabledPriceQueryRepository extends CrudRepository<DisabledPriceQuery, Long> {

    // case 1 error: org.springframework.data.mapping.MappingException: Couldn't find PersistentEntity for type boolean!
    @RestResource(exported = false)
    boolean existsByUserNicknameAndMatchKeyword(String userNickname, String matchKeyword);

    // case 2 works
    @RestResource(exported = false)
    DisabledPriceQuery findByUserNickname(String userNickname);

    // case 3 works
    @RestResource(exported = false)
    @Override
    void deleteById(Long id);
}
```

**Expected behavior**
- `existsByUserNicknameAndMatchKeyword` method should not be exposed.

**Comment by bnasslahsen** [comment]
@uqix, 

Not reproducible using `v1.6.8`. See the updated test case.
If you believe you are facing an issue, make sure you provide a [Minimal, Reproducible Example - with HelloController](https://stackoverflow.com/help/minimal-reproducible-example) that reproduces the problem.
