### ISSUE TITLE
Swagger-UI disabled by springdoc.api-docs.enabled=false

### ISSUE THREAD

**Issue by m-kay** [springdoc/springdoc-openapi#1524]
I wanted to only include the swagger-ui part from springdocs without generating the api docs because it is served as a static file in my project. However when I disable the api-docs generation with `springdoc.api-docs.enabled=false` it also disables swagger ui.

**Comment by bnasslahsen** [comment]
@m-kay, 

This is expected behavior.
If you want serve static OpenAPI Configuration, it's explained in the F.A.Q:
- https://springdoc.org/#what-is-a-proper-way-to-set-up-swagger-ui-to-use-provided-spec-yml
