### ISSUE TITLE
Null vendor extensions are excluded from Json/Yaml

### ISSUE THREAD

**Issue by loomisdf** [springdoc/springdoc-openapi#1525]
### Description
I haven't been able to create a vendor extension with a null value, the generated yaml/json won't include any. This could be a bug, but maybe there's a workaround I haven't found yet.

### Versions
- springboot 2.6.4
- springdocs-openapi 1.6.6
- Java 11

### Example Code
```Java
@Configuration
public class SwaggerConfig {

    @Bean
    public OpenAPI api() {
        return new OpenAPI()
                .extensions(apiExtensions());
    }

    private Map<String, Object> apiExtensions() {
        var extensions = new HashMap<String, Object>();

        var linkedMap = new LinkedHashMap<String, String>();
        linkedMap.put("property1", "value1");
        linkedMap.put("property2", null);

        extensions.put("x-my-vendor-extensions", linkedMap);

        return extensions;
    }
}
```
### Expected Output
```Json
"x-my-vendor-extensions": {
	"property1": "value1",
        "property2": null
}
```
### Actual Output
```Json
"x-my-vendor-extensions": {
	"property1": "value1"
}
```
Null is an acceptable value for vendor extensions according to the openAPI spec: https://swagger.io/docs/specification/openapi-extensions/

> The extension value can be a primitive, an array, an object or `null`

**Comment by bnasslahsen** [comment]
@loomisdf, 

This should completely be fixed at the source in the swagger-core library. Please raise an issue for it.
The `OpenApiMixin` as well as ExtensionMixin should include: `@JsonInclude(value = Include.ALWAYS)`

I have only added a workaround:
Use `springdoc.writer-with-order-by-keys=true` for the next release.
