### ISSUE TITLE
How to force user to use only the valid configUrl 

### ISSUE THREAD

**Issue by vidhya03** [springdoc/springdoc-openapi#1526]
**How to force user to use only the valid configUrl  ?**

I have two different set of API's configured in two different valid configUrl ,  

1. /v3/api-docs/swagger-config
2. /internal/private-api/swagger-config

by default if we try http://hostname/swagger-ui.html which redirects to http://hostname/swagger-ui/index.html?configUrl=/v3/api-docs/swagger-config 

Now if i try http://hostname/swagger-ui/index.html , i got No API definition provided screen 

![image](https://user-images.githubusercontent.com/534679/155919885-05804d49-bea7-495c-a11e-32a82e0dad65.png)

Is there any way to redirect to default http://hostname/swagger-ui/index.html?configUrl=/v3/api-docs/swagger-config  page. 
I want to user to access only the valid configUrl page.

**Comment by bnasslahsen** [comment]
Remember, contributions to this repository should follow its [contributing guidelines](https://github.com/springdoc/springdoc-openapi/blob/63d43a154a89c1da65103f0319f15a6fa441bd26/CONTRIBUTING.adoc)

Please make sure you provided all the listed information before opening tickets.
This one will be closed and can be reopened if any relevant information is provided.
