### ISSUE TITLE
@JsonView and preventing additional schemas generation in a global way

### ISSUE THREAD

**Issue by Nhoutain** [springdoc/springdoc-openapi#1527]
After migrate all our µ-service to openapi, we refresh the generate doc. 
When perform this, I realise that all model which use `@JsonView` are generate for each possible view. 

I can understand it can make a lot of sens in some case to handle the @JsonView and generate all possible model to have a representative view. But in my case, I want to prevent this behavior, and only generate one model.

Is there a way to prevent openapi to generate these model? 
I read the issue https://github.com/springdoc/springdoc-openapi/issues/392, which provide a simple way for only one endpoint.

Is there a option to disable the jsonview behavior for all the generation?
I don't find any properties on this..

**Comment by bnasslahsen** [comment]
@Nhoutain, 

This is an option in the `swagger-core` only available in the operation level.
