### ISSUE TITLE
Generating OpenAPI json in multimodule project

### ISSUE THREAD

**Issue by iitsalex** [springdoc/springdoc-openapi#1528]
I have a multimodule project where I have been able to generate openAPI.json files for one module within the project. I was wondering if there was an elegant way to generate 1 or N (N being the number of modules in the project) openAPI json files in order to cover the entire project.

I was also hoping that if this was possible that it would only require HTTP security configuration to be set once, so I can set an antMatcher for the "/v3/api-docs" once, instead of setting up security for each module.

**Comment by bnasslahsen** [comment]
Remember, contributions to this repository should follow its [contributing guidelines](https://github.com/springdoc/springdoc-openapi/blob/a27af7c48473a44d4fcd28d5b5e5925b3098889c/CONTRIBUTING.adoc)

This ticket will be closed and can be reopened, if you provide all the relevant information listed in the link above.
