### ISSUE TITLE
[BUG] Using webflux with router functions results in duplicated swagger-ui api doc

### ISSUE THREAD

**Issue by influence160** [springdoc/springdoc-openapi#1529]
**Describe the bug**
i have created a demo project starting from https://github.com/springdoc/springdoc-openapi-demos/tree/master/springdoc-openapi-spring-boot-2-webflux-functional this demo project and i have used the generated openapi.yaml and wanted to recreate the same project using openApiGenerator maven plugin https://github.com/OpenAPITools/openapi-generator/

i have commited my project in this location https://github.com/influence160/openapi-generator-springdoc-boot-webflux-fonctionnal-example

The bug is that in the resulted swagger-ui, the api doc is duplicated like this 
![image](https://user-images.githubusercontent.com/3180939/156219556-d8ddfed1-40d7-42a2-80e3-9fd1c40f98a1.png)

**To Reproduce**
- Provide with a sample code (HelloController) or Test that reproduces the problem
https://github.com/influence160/openapi-generator-springdoc-boot-webflux-fonctionnal-example
- What version of spring-boot you are using?
- What modules and versions of springdoc-openapi are you using?
versions are in the pom.xml
- What is the actual and the expected result using OpenAPI Description (yml or json)?
expected when i open http://localhost:8080/webjars/swagger-ui/index.html i should have the api doc shown one time
actual : the api doc is shown twice

to reproduce clone the project  : build the project and run the WebfluxFunctionalDemoApplication class and go to http://localhost:8080/webjars/swagger-ui/index.html

note that in this project i just use the module users from the original demo project and i havent used the modules employees and coffee.
note2 : and because i wanted to have a webflux with routing functions project and openpi-generator is generating interfaces that returns ``Mono<ResponseEntity<T>>``  i had to convert all the Mono<ResponseEntity> to Mono<ServerResponse> using the method https://github.com/influence160/openapi-generator-springdoc-boot-webflux-fonctionnal-example/blob/master/src/main/java/othmen/test/openapigenerator/springdoc/demo/app4/user/Util.java

**Comment by bnasslahsen** [comment]
Not a bug.
