### ISSUE TITLE
Possibility to configure SpringDoc to serve YAML by default at /v3/api-docs?

### ISSUE THREAD

**Issue by jklingst** [springdoc/springdoc-openapi#1531]
**Is your feature request related to a problem? Please describe.**

No, this isn't really a problem, per se, and it isn't a major issue either. However, in the project I'm currently working, we would like to serve the OpenAPI documentation as YAML by default instead of JSON, and not having to explicitly use the .yaml suffix.

It would be nice to either have some content negotiation on a single `/v3/api-docs` (or whatever URL is set using `springdoc.api-docs.path`) endpoint, for example by means of the "Accept" header, or to be able to configure which format to serve by default on the mentioned endpoint.

Would this be possible? Or is there already some way to achieve it?

**Comment by bnasslahsen** [comment]
@jklingst, 

There is no plan for that. This will lead to many regressions.
You still can override `OpenApiResource` with your own Bean, for this custom change.
