### ISSUE TITLE
Method level tag causes duplicate UI entiry

### ISSUE THREAD

**Issue by jayfray12** [springdoc/springdoc-openapi#1532]
**Describe the bug**
When a tag is added to the `@Operation` it causes duplication in the UI and I see both an entry for the API and the tag

**To Reproduce**
- What version of spring-boot you are using: 2.6.4
- What modules and versions of springdoc-openapi are you using: springdoc-openapi-ui 1.6.6 (this doesn't happen in 1.6.5)
- Provide with a sample code (HelloController) or Test that reproduces the problem:
```
@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2022-03-03T09:36:36.898148959-05:00[America/New_York]")
@Validated
@Tag(name = "NetworkServices", description = "the NetworkServices API")
public interface NetworkServicesApi {

    default Optional<NativeWebRequest> getRequest() {
        return Optional.empty();
    }

    /**
     * GET /networkservices/healthcheck
     * used to determine the health of network services
     *
     * @return The health of the system (status code 200)
     */
    @Operation(
        operationId = "getHealthCheck",
        tags = { "networkServices" },
        responses = {
            @ApiResponse(responseCode = "200", description = "The health of the system", content = @Content(mediaType = "application/json", schema = @Schema(implementation =  HealthCheck.class)))
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/networkservices/healthcheck",
        produces = { "application/json" }
    )
    default ResponseEntity<HealthCheck> getHealthCheck(
        
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"ansibleUp\" : true, \"databaseUp\" : true }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }

}
```

**Expected behavior**
I would expect it to not duplicate the entries in the UI like it did in 1.6.5

**Screenshots**
![openapi-duplication](https://user-images.githubusercontent.com/38667521/156586436-e6ca67e6-6d4e-4c96-8410-011a3703726b.jpg)

**Additional context**
If I remove the `tags = { "networkServices" },` line then I don't see the duplication.  This works fine in 1.6.5.

**Comment by bnasslahsen** [comment]
@jayfray12, 

You are declaring: `networkServices` and `NetworkServices` Tags.
Use the same tag name if you don't want duplications.

**Comment by jayfray12** [comment]
It worked in version 1.6.5.  Something must have changed to make it case sensitive...
