### ISSUE TITLE
Is it possible to hide Schemas under certain package?

### ISSUE THREAD

**Issue by ZamasuG** [springdoc/springdoc-openapi#1535]
I wanna hide all Schemas under certain package. 

I have my DTOs under com.example.dto package, I want to hide them and I want to avoid the annotations (like @Schema(hidden = true) or @Parameter(hidden = true). Something like packages-to-exclude but for Schemas.

Is this possible? Could you provide a simple example?

**Comment by bnasslahsen** [comment]
@ZamasuG, 

There nothing planned for that.
