### ISSUE TITLE
GetMapping with the same path but different Params

### ISSUE THREAD

**Issue by T-Developer1** [springdoc/springdoc-openapi#1536]
Hi,
i have two GetMappings with the Same Path. The one will return a List if a no Param is set, and the other one will return a specific String, if a key is set.

`
   @GetMapping( value = "/getTest" )
   public @ResponseBody ResponseEntity<String> testGetMapping()
   {
      return new ResponseEntity<String>( "TestString", HttpStatus.OK );
   }

   @GetMapping( value = "/getTest", params = { "key" } )
   public @ResponseBody ResponseEntity<List<String>> testGetMappingList(@RequestParam String key )
   {
      return new ResponseEntity<List<String>>( new ArrayList<String>(), HttpStatus.OK );
   }
`

The created OpenAPi Json Looks Like this:

 		"/getTest": {
			"get": {
				"tags": [
					"i18n"
				],
				"operationId": "testGetMapping_1",
				"parameters": [
					{
						"name": "key",
						"in": "query",
						"required": true,
						"schema": {
							"type": "string"
						}
					}
				],
				"responses": {
					"200": {
						"description": "OK",
						"content": {
							"*/*": {
								"schema": {
									"oneOf": [
										{
											"type": "array",
											"items": {
												"type": "string"
											}
										},
										{
											"type": "string"
										}
									]
								}
							}
						}
					}
				}
			}
		},

![image](https://user-images.githubusercontent.com/21088411/156770447-d9d7c2fc-b458-42dc-a331-b22db23b5be6.png)

In the OpenApi Resonse and in Swagger-ui is only one GetMapping.

Are there any workarounds to show both GetMappings

one with The Param and one without it

**Comment by pgross41** [comment]
@bnasslahsen I have the same issue, why is this marked as invalid?
