### ISSUE TITLE
The operationsConsumer in SpringdocRouteBuilder.filter() should be applied to all other operations

### ISSUE THREAD

**Issue by sohoffice** [springdoc/springdoc-openapi#1538]
**Describe the bug**

In a functional endpoint RouterFunction, the route may have many operations that share the same filter. At the moment, the filter method is taking a operationsConsumer parameter, which is fine. However, this consumer must not require operationId, and it must be applied to the building results of other operations in the same function.

**To Reproduce**

- What version of spring-boot you are using? 2.6.4
- What modules and versions of springdoc-openapi are you using? springdoc-openapi-webflux-ui
- What is the actual and the expected result using OpenAPI Description (yml or json)? The filter should not require operationId, the settings must combine, not override the builder result of other operation.
- Provide with a sample code (HelloController) or Test that reproduces the problem

```
  public RouterFunction<ServerResponse> fooRoutes(FooHandler handler) {
    return route()
      .GET("/foo/{fooId}", handler::get,
        builder -> builder
          .operationId("getFoo")
          .parameter(parameterBuilder().name("fooId").in(ParameterIn.PATH))
          .response(responseBuilder()
            .responseCode("200")
            .implementation(FooOutput.class)
            .content(contentBuilder().schema(schemaBuilder().implementation(FooOutput.class)))))
      .filter(commonFilters.someFilter(), builder -> builder
        .operationId("this-should-not-be-needed")
        .parameter(parameterBuilder().name("foo-header").in(ParameterIn.HEADER)))
      .build();
  }
```

The generated document is as the below. The filter builder completely replaces the getFoo builder.

```
  /foo/{fooId}:
    get:
      operationId: this-should-not-be-needed
      parameters:
      - name: foo-header
        in: header
        schema:
          type: string
```

There are the below issues too:

1. filter() method can not be placed before operations
2. filter() method require the operationId to be supplied.

**Expected behavior**

I think we can either remove the mandatory operationsConsumer parameter from filter method, so that the developer can repeat them in all operations. Or better, we can implement the logic so that the operationsConsumer is applied on top of the business builder.

**Comment by bnasslahsen** [comment]
@sohoffice, 

There is no need to pass you openAPI description to your filter methods.
You should be able to describe you API, in your router level.

**Comment by sohoffice** [comment]
@bnasslahsen If you don't mind, can you share a short example please?

**Comment by bnasslahsen** [comment]
@sohoffice, 

Just remove the openAPI description from your filter.
If you need an enhanced sample. Make sure you provide a Provide a [Minimal, Reproducible Example - with HelloController](https://stackoverflow.com/help/minimal-reproducible-example)[](https://github.com/springdoc/springdoc-openapi/blob/378edcf142d9b2c5af637339b926f98687e55650/CONTRIBUTING.adoc#reporting-security-vulnerabilities) that reproduces the problem.

**Comment by sohoffice** [comment]
Hi @bnasslahsen 

Thanks, I've already done that. For example, I've modified the filter as the below

```
      .filter(commonFilters.someFilter(), builder -> {})
```

However, the below exception is thrown.

```
java.lang.IllegalStateException: You should either fill, the Operation or at least the bean class and the bean method
	at org.springdoc.core.fn.builders.operation.Builder.build(Builder.java:466) ~[springdoc-openapi-common-1.6.6.jar:1.6.6]
	Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException: 
Error has been observed at the following site(s):
	*__checkpoint ⇢ HTTP GET "/v3/api-docs" [ExceptionHandlingWebHandler]
Original Stack Trace:
		at org.springdoc.core.fn.builders.operation.Builder.build(Builder.java:466) ~[springdoc-openapi-common-1.6.6.jar:1.6.6]
		at org.springdoc.core.fn.RouterOperation.<init>(RouterOperation.java:165) ~[springdoc-openapi-common-1.6.6.jar:1.6.6]
		at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197) ~[na:na]
		at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625) ~[na:na]
		at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[na:na]
		at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[na:na]
		at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921) ~[na:na]
		at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[na:na]
		at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682) ~[na:na]
```

I was forced to pass a dummy builder, and this is the reason why above exception is thrown. Obviously when OPERATION_ATTRIBUTE is available the builder will be executed. Once executed, it require certain attribute to be available, for example operationId. However, this is a filter, it doesn't actually need the operationId.

I think the springdoc should either provide a filter method without builder consumer. Or better, allow the filter builder to be applied to other methods in the same router.

**Comment by bnasslahsen** [comment]
@sohoffice, 

As asked earlier, make sure you add the link to a valid repo which includes a [Minimal, Reproducible Example - with HelloController](https://stackoverflow.com/help/minimal-reproducible-example)[](https://github.com/springdoc/springdoc-openapi/blob/378edcf142d9b2c5af637339b926f98687e55650/CONTRIBUTING.adoc#reporting-security-vulnerabilities) that reproduces the problem.

**Comment by blacelle** [comment]
I encounter a similar issue:

```
package eu.solven.kumite.app.webflux;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.springdoc.webflux.core.fn.SpringdocRouteBuilder;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.web.reactive.AutoConfigureWebTestClient;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.context.annotation.Bean;
import org.springframework.core.env.Environment;
import org.springframework.http.MediaType;
import org.springframework.security.config.annotation.web.reactive.EnableWebFluxSecurity;
import org.springframework.security.config.web.server.ServerHttpSecurity;
import org.springframework.security.web.server.SecurityWebFilterChain;
import org.springframework.security.web.server.util.matcher.ServerWebExchangeMatchers;
import org.springframework.test.context.junit.jupiter.SpringExtension;
import org.springframework.test.web.reactive.server.StatusAssertions;
import org.springframework.test.web.reactive.server.WebTestClient;
import org.springframework.web.reactive.function.BodyInserters;
import org.springframework.web.reactive.function.server.HandlerFilterFunction;
import org.springframework.web.reactive.function.server.RequestPredicates;
import org.springframework.web.reactive.function.server.RouterFunction;
import org.springframework.web.reactive.function.server.ServerRequest;
import org.springframework.web.reactive.function.server.ServerResponse;

import eu.solven.kumite.app.EmptySpringBootApplication;
import reactor.core.publisher.Mono;

@ExtendWith(SpringExtension.class)
@SpringBootTest(classes = { EmptySpringBootApplication.class, TestSecurity_WithoutAuth.MoreBeans.class },
		webEnvironment = SpringBootTest.WebEnvironment.RANDOM_PORT)
@AutoConfigureWebTestClient(timeout = "P1D")
public class TestSecurity_WithoutAuth {

	@EnableWebFluxSecurity
	public static class MoreBeans {

		@Bean
		public SecurityWebFilterChain configureUi(ServerHttpSecurity http, Environment env) {
			return http.securityMatcher(ServerWebExchangeMatchers.anyExchange())
					.authorizeExchange(auth -> auth.anyExchange().permitAll())
					.build();
		}

		public Mono<ServerResponse> hello(ServerRequest request) {
			return ServerResponse.ok().contentType(MediaType.APPLICATION_JSON).body(BodyInserters.fromValue("Hello"));
		}

		@Bean
		public RouterFunction<ServerResponse> loginRoutes() {
			HandlerFilterFunction<ServerResponse, ServerResponse> someFilter = (request, next) -> next.handle(request);

			return SpringdocRouteBuilder.route()

					.GET(RequestPredicates.path("/api/v1"), this::hello, ops -> ops.operationId("searchPlayers"))

					.filter(someFilter, ops -> {
					})

					.build();

		}
	}

	@Autowired
	private WebTestClient webTestClient;

	@Test
	public void testOpenApi() {
		StatusAssertions expectStatus =
				webTestClient.get().uri("/v3/api-docs").accept(MediaType.APPLICATION_JSON).exchange().expectStatus();

		expectStatus.isOk();
	}
}
```

**Comment by JohnNiang** [comment]
IMO, this issue is similar to <https://github.com/springdoc/springdoc-openapi/issues/2399>. I'm willing to make a contribution.
