### ISSUE TITLE
Java Map type is ignored

### ISSUE THREAD

**Issue by JBertaux** [springdoc/springdoc-openapi#154]
Hello,

Why the type `Map` is ignored ? https://github.com/springdoc/springdoc-openapi/blob/master/springdoc-openapi-webmvc-core/src/main/java/org/springdoc/core/RequestBuilder.java#L35

It could be usefull for endpoints like this one : 
```java 
@PutMapping("/test")
public String test(@RequestParam Map<String, String> parameters) {
    return "test";
} 
```

`PUT /test?param1=a&param2=b`

**Comment by springdoc** [comment]
Hi, 

 This is the default behaviour of the springdoc-openapi library in order to ignore other injectable parameters supported by Spring MVC.
- https://docs.spring.io/spring/docs/5.1.x/spring-framework-reference/web.html#mvc-ann-arguments

 If you want to change this behaviour, you can just override the method isParamTypeToIgnore of RequestBuilder Bean, in your own application.

**Comment by JBertaux** [comment]
Thanks for the advice :)

**Comment by bnasslahsen** [comment]
Here is an example code:


```java

@Bean
@Primary
MyRequestBuilder myRequestBuilder(GenericParameterBuilder parameterBuilder, RequestBodyBuilder requestBodyBuilder,
		OperationBuilder operationBuilder, Optional<List<OperationCustomizer>> operationCustomizers, Optional<List<ParameterCustomizer>> parameterCustomizers) {
	return new MyRequestBuilder(parameterBuilder, requestBodyBuilder,
			operationBuilder, operationCustomizers, parameterCustomizers);
}

public class MyRequestBuilder extends RequestBuilder {

	public MyRequestBuilder(GenericParameterBuilder parameterBuilder, RequestBodyBuilder requestBodyBuilder,
			OperationBuilder operationBuilder, Optional<List<OperationCustomizer>> customizers,
			Optional<List<ParameterCustomizer>> parameterCustomizers) {
		super(parameterBuilder, requestBodyBuilder, operationBuilder, customizers, parameterCustomizers);
	}

	@Override
	protected boolean isParamToIgnore(java.lang.reflect.Parameter parameter) {
		if (Map.class.isAssignableFrom(parameter.getType()))
			return false;
		return super.isParamToIgnore(parameter);
	}
}
```

**Comment by Andrew3431** [comment]
@bnasslahsen With springdoc-openapi-ui version 1.3.9, RequestBuilder class is not present. Could you please tell which method should we override ?

**Comment by bnasslahsen** [comment]
@Andrew3431, 

 The RequestBuilder is still there ...
  - https://github.com/springdoc/springdoc-openapi/blob/v1.3.9/springdoc-openapi-webmvc-core/src/main/java/org/springdoc/webmvc/core/RequestBuilder.java
