### ISSUE TITLE
The SecuritySchemeIn param in SecurityScheme annotation mixing issue with kotlin expression term

### ISSUE THREAD

**Issue by situkangsayur** [springdoc/springdoc-openapi#1540]
Problem
- I am using kotlin and springboot with the openAPI, then want to use the security scheme to lock the swagger UI with a specific security scheme (Ex. basic). 
- But when I want to choose the value for parameter **"in"** in the SecurityScheme annotation (_io.swagger.v3.oas.annotations.security.SecurityScheme_) with SecuritySchemeIn the build process gave me an error for "kotlin mixing named and positioned arguments" or the gradle expecting an expression, it expecting ')' just like looping expression.

Potential solution :
-  Maybe you could change the name of parameter difference with any expression term in kotlin ?

The alternative is to create a config bean to config the OpenApi, but it will be nice if could still use the annotation to config the open API and the security scheme

**Comment by bnasslahsen** [comment]
@situkangsayur,

These are [swagger-annotations](https://github.com/swagger-api/swagger-core/issues). 
If you have any issue, choose the right github repo then.
