### ISSUE TITLE
Discrepancy to actual JSON object

### ISSUE THREAD

**Issue by Backfighter** [springdoc/springdoc-openapi#1541]
I have discovered that the MethodParameterPojoExtractor uses Introspector.getBeanInfo to gather fields of pojos. This leads to an inconsistency between actual JSON representation and open api specification if a method is defined that is not actually backed by a field (every get method is considered a property). 

Consider for example the following POJO:
```java
class Person {
  private String firstName;
  private String lastName;

  public String getFirstName() {
    return firstName;
  }

  public String getLastName() {
    return lastName;
  }

  public String getFullName() {
    return firstName + " " + lastName;
  }
}
```

Most JSON-Serializers will produce something like:
```json
{
  "firstName": "first",
  "lastName": "last"
}
```

But springdoc creates the schema:
```json
{
  "Person": {
    "type": "object",
    "properties": {
      "fristName": {
         "type": "string"
       },
      "lastName": {
         "type": "string"
       },
      "fullName": {
         "type": "string"
       }
    }
  }
}
```
Which suggests that there is a property the api provides that is never returned by the api.

**Comment by bnasslahsen** [comment]
@Backfighter, 

Your analysis is wrong. This has nothing to do with MethodParameterPojoExtractor!
This behavior is in the swagger-core introspection which is based on **jackson library**.

If you want hide ur full name filed, just add @JsonIgnore on your getter.
If you want set it globally use:

```java
static {
Json.mapper().setVisibility(PropertyAccessor.ALL, Visibility.NONE);
Json.mapper().setVisibility(PropertyAccessor.FIELD, Visibility.ANY);
}
```
