### ISSUE TITLE
POJO with reference to themselves do not produce complete api

### ISSUE THREAD

**Issue by ejchet** [springdoc/springdoc-openapi#1542]
I have been migrating from swaggerfox and I believe I have uncovered an issue.  I created a test program to recreate the issue.

If I have a class which has a field which references itself the complete api isn't generated, childOrders array is missing for the schema definition of Order.

@Setter @Getter @NoArgsConstructor @AllArgsConstructor
public class Order {
    private Long sku;
    private List<Order> childOrders;
}

    @GetMapping(value = "/api/orders")
    public ResponseEntity<List<Order>> getOrders() {
        List<Order> results = new ArrayList<>();
        return new ResponseEntity<>(results, HttpStatus.OK);
    }

The generated api spec doesn't contain the array of child orders:

From /v3/api-docs you can see the Order schema is missing the childOrders array field.

{
  "openapi": "3.0.1",
  "info": {
    "title": "OpenAPI definition",
    "version": "v0"
  },
  "servers": [
    {
      "url": "http://localhost:9080/server",
      "description": "Generated server url"
    }
  ],
  "paths": {
    "/api/api/orders": {
      "get": {
        "tags": [
          "test-controller"
        ],
        "operationId": "getOrders",
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "*/*": {
                "schema": {
                  "type": "array",
                  "items": {
                    "$ref": "#/components/schemas/Order"
                  }
                }
              }
            }
          }
        }
      }
    }
  },
  "components": {
    "schemas": {
      "Order": {
        "type": "object",
        "properties": {
          "sku": {
            "type": "integer",
            "format": "int64"
          }
        }
      }
    }
  }
}

Outside of this issue SpringDoc is working great for us on a project with 10k+ domain objects, thank you for your work.

Thanks,

Eric

**Comment by bnasslahsen** [comment]
@ejchet, 

Even, you code is not well formatted. 
I tried to guess that what you need would be the annotation `@JsonBackReference`
This is explained here https://github.com/springdoc/springdoc-openapi/issues/1158.

**Comment by ejchet** [comment]
@[bnasslahsen](https://github.com/bnasslahsen)

Thank you JsonBackReference solved my issue.

Eric
