### ISSUE TITLE
The pageable still not working properly

### ISSUE THREAD

**Issue by micobarac** [springdoc/springdoc-openapi#1547]
Hi, 

 The support for Pageable of spring-data-rest is now added on v1.2.11.

 The projects that uses spring-data-rest should add this dependency together with the springdoc-openapi-ui dependency:
```xml
  <dependency>
            <groupId>org.springdoc</groupId>
            <artifactId>springdoc-openapi-data-rest</artifactId>
            <version>1.2.11</version>
 </dependency>
 ```

_Originally posted by @springdoc in https://github.com/springdoc/springdoc-openapi/issues/177#issuecomment-557845875_

I added:

```xml
  <dependency>
            <groupId>org.springdoc</groupId>
            <artifactId>springdoc-openapi-data-rest</artifactId>
            <version>1.6.6</version>
 </dependency>
```

The controller:

```java
    /**
     * {@code GET /admin/users/pageable} : get all users with all the details - calling this are only allowed for the administrators.
     *
     * @return the {@link ResponseEntity} with status {@code 200 (OK)} and with body all users.
     */
    @GetMapping("/users/pageable")
    @PreAuthorize("hasAuthority(\"" + AuthoritiesConstants.ADMIN + "\")")
    public Page<AdminUserDTO> getAllUsersPageable(Pageable pageable) {
        log.debug("REST request to get all User for an admin");
        return userService.getAllManagedUsers(pageable);
    }
```

The Swagger form looks like this:

![image](https://user-images.githubusercontent.com/16001837/157855196-64c6e74e-341e-491e-b76d-052144ac2680.png)

**Comment by bnasslahsen** [comment]
Read the documentation: https://springdoc.org/#how-can-i-map-pageable-spring-data-commons-object-to-correct-url-parameter-in-swagger-ui
