### ISSUE TITLE
Spring Data Rest: Missing relationships

### ISSUE THREAD

**Issue by marciovmartins** [springdoc/springdoc-openapi#1549]
**Describe the bug**
- The ManyToOne relationship is not been added to the documentation
- The OneToMany relationship is not been added to the documentation

**To Reproduce**
- What version of spring-boot you are using?
2.6.2 and 2.6.4
- What modules and versions of springdoc-openapi are you using?
springdoc-openapi-ui:1.6.6
springdoc-openapi-data-rest:1.6.6
- What is the actual and the expected result using OpenAPI Description (yml or json)?
Actual:
```json
{
  "EntityModelAccount": {
    "type": "object",
    "properties": {
      "expiryDate": {
        "type": "string",
        "format": "date-time"
      },
      "_links": {
        "$ref": "#/components/schemas/Links"
      }
    }
  }
}
```
Expected:
```json
{
  "EntityModelAccount": {
    "type": "object",
    "properties": {
      "expiryDate": {
        "type": "string",
        "format": "date-time"
      },
      "customer": {
        "type": "object",
        "$ref": "#/components/schemas/EntityModelAccount"
      },
      "_links": {
        "$ref": "#/components/schemas/Links"
      }
    }
  }
}
```
- Provide with a sample code (HelloController) or Test that reproduces the problem
For ManyToOne can be reproduced with current version in the demo version `3.1.6-SNAPSHOT`: https://github.com/springdoc/springdoc-openapi-demos/tree/master/springdoc-openapi-data-rest
For OneToMany can be reproduced with this example: https://stackoverflow.com/questions/71429672/how-to-create-swagger-documentation-to-list-of-object-with-kotlin

**Expected behavior**
- A clear and concise description of what you expected to happen.
The relationship to appear in the documentation
- What is the expected result using OpenAPI Description (yml or json)?

**Screenshots**
![image](https://user-images.githubusercontent.com/6377735/158029878-1d3980b6-5683-4e89-a9d4-59ae11bf30df.png)
![image](https://user-images.githubusercontent.com/6377735/158030077-32e95551-8fbd-450f-87b5-26ee8ec5d480.png)

**Comment by bnasslahsen** [comment]
@Delirante, 

There is no need to spam and create duplicates.
Make sure you update the original ticket with the relevant information and it can be reopened.
