### ISSUE TITLE
Customize operation by path

### ISSUE THREAD

**Issue by rupert-madden-abbott** [springdoc/springdoc-openapi#1551]
I would like to be able to override the global security configuration for specific operations, according to their path.

The `OperationCustomizer` provides access to a given `Operation` and `HandlerMethod`, both of which, I think, do not include path mapping information.

Please could the existing customizer, or an additional customizer, supply more of the surrounding context of an operation and in particular the `operationPath`?

Happy to raise a PR!

**Comment by bnasslahsen** [comment]
Use `OperationCustomizer` which is relevant in this case.

**Comment by rupert-madden-abbott** [comment]
HI @bnasslahsen - in my original post, I mention `OperationCustomizer` and explain why it is insufficient (as far as I can see). It is possible I have misunderstood but this is my understanding:

I can't see how either `Operation` or the `HandlerMethod` contain information about the path since both of these objects do not relate directly to a path. They are both mapped to a path, but they do not contain this mapping information within them. The surrounding context does have this information in [this method](https://github.com/springdoc/springdoc-openapi/blob/c56df04de6128f0432552123c4ed4de5123d335d/springdoc-openapi-common/src/main/java/org/springdoc/api/AbstractOpenApiResource.java#L384-L490)


So I am proposing something like this change to `OperationCustomizer`:

```java
@FunctionalInterface
public interface OperationCustomizer {

	Operation customize(Operation operation, HandlerMethod handlerMethod, String operationPath);
}
```

Then AbstractOpenApiResource would change like this:

```java
	protected void calculatePath(HandlerMethod handlerMethod, RouterOperation routerOperation, Locale locale) {
                        ...snip...
			operation = customiseOperation(operation, handlerMethod, operationPath);
                       ...snip...
            }
            
         ...snip
            
	protected Operation customiseOperation(Operation operation, HandlerMethod handlerMethod, String operationPath) {
		if(operationCustomizers.isPresent()){
			List<OperationCustomizer> operationCustomizerList = operationCustomizers.get();
			for (OperationCustomizer operationCustomizer : operationCustomizerList)
				operation = operationCustomizer.customize(operation, handlerMethod, operationPath);
		}
		return operation;
	}

```

What I am trying to do is path based customisation of the operation. For example, I want to alter the security element, based on the path e.g. if the path contains "admin" or "public", then I want to make a customisation. I can't see how to achieve that with `OperationCustomizer` as it stands.

**Comment by Shabin** [comment]
@bnasslahsen 
This is a requirement which I also have encountered. I need to find the path of the current operation for modifying `RequestBody` as below, But there is no way to get the `operationPath` in `OperationCustomizer`.
```
@Bean
public OperationCustomizer bodyVersionCustomizer() {
    return new OperationCustomizer() {
		@Override
		public Operation customize(Operation operation, HandlerMethod handlerMethod) {
			if(handlerMethod.getBeanType().getAnnotation(Versioned.class) !=null && 
                             operationPath.contains("v2")) { //operationPath is not available to check this
				// modify request body
			}
			return operation;
		}
	};
}
```
So I checked `AbstractOpenApiResource` to see whether I can override some method to achieve the same. The only method in `AbstractOpenApiResource` which has `requestMethod, operation and operationPath` is [`buildPathItem()`](https://github.com/springdoc/springdoc-openapi/blob/bd4dabff0ef859bb55af6f683df50c3405968d8b/springdoc-openapi-common/src/main/java/org/springdoc/api/AbstractOpenApiResource.java#L1059) which is a private method. So I don't see any way by which we can get the `operationPath` for customizing `Operation`. 
So can you please consider making the change @rupert-madden-abbott suggested or can you please make `buildPathItem()` method as `protected`. Or is there any other way forward?

**Comment by bnasslahsen** [comment]
@Shabin,

Maybe you could propose a PR with relevant test case.
I would be happy to review it and integrate it for  the next release.

**Comment by Shabin** [comment]
@bnasslahsen
Thanks for the reply and suggestion. But after reading though the docs I understood that my requirement would be satisfied with `GroupedOpenApi` with `pathsToMatch` and hence I can have specific `OperationCustomizer` for each path specific group.
