### ISSUE TITLE
The latest date type example or defaultValue setting is invalid

### ISSUE THREAD

**Issue by zxiaozhou** [springdoc/springdoc-openapi#1557]
**Describe the bug**
The latest date type example setting is invalid

1. setting
<img width="989" alt="image" src="https://user-images.githubusercontent.com/62740686/158727414-51ce69f1-ba07-4d86-aae1-da9faa9221b0.png">
2. result
<img width="872" alt="image" src="https://user-images.githubusercontent.com/62740686/158727482-bc71692d-f7ee-44d9-9630-d9fe049c3948.png">
3. There is no example for the data type in JSON
<img width="833" alt="image" src="https://user-images.githubusercontent.com/62740686/158727875-04a8f342-9d6c-4812-a2f6-2270593e5bf3.png">

**Comment by bnasslahsen** [comment]
@zxiaozhou, 

see the answer here https://github.com/springdoc/springdoc-openapi/issues/221
