### ISSUE TITLE
String with format byte (base64) is being an array of strings and not a string

### ISSUE THREAD

**Issue by weesftw** [springdoc/springdoc-openapi#1559]
When I'm creating an object and it has an attribute of type String with the format: byte (base64), the documentation view (UI) converts this type to an array of strings and not just a string...

- **spring-boot** version 2.6.4
- Using **springdoc-openapi-ui** version 1.6.6

[Source code for example](https://github.com/weesftw/openapi-string-byte-schema) and [swagger.yaml](https://github.com/weesftw/openapi-string-byte-schema/blob/master/src/main/resources/swagger.yaml).

![swagger](https://user-images.githubusercontent.com/58608499/158883606-634f0fce-4b25-4495-a44e-984f91a2f26f.png)

**Comment by bnasslahsen** [comment]
@weesftw, 

This is related to swagger-core enhancement. https://github.com/swagger-api/swagger-core/issues/3944
And there is a related PR: https://github.com/swagger-api/swagger-core/pull/3955

Once fixed, we can integrate it.
As workaround on your message, and make sure you remove  `@Schema` from the getter.

```java
    @Schema(name = "message",  required = true, type = "string", format = "binary")
    @JsonProperty("message")
    @lombok.Builder.Default
    @NotNull
    private byte[] message = null;
```

**Comment by spulci** [comment]
> @weesftw,
> 
> This is related to swagger-core enhancement. [swagger-api/swagger-core#3944](https://github.com/swagger-api/swagger-core/issues/3944) And there is a related PR: [swagger-api/swagger-core#3955](https://github.com/swagger-api/swagger-core/pull/3955)
> 
> Once fixed, we can integrate it. This the syntax to get your expected result. And make sure you remove `@Schema` from the getter.
> 
> ```java
>     @Schema(name = "message",  required = true, type = "string", format = "binary")
>     @JsonProperty("message")
>     @lombok.Builder.Default
>     @NotNull
>     private byte[] message = null;
> ```

PR has changed:

**Comment by spulci** [comment]
A new version of Swagger Core has been released with the above bug FIXED.

https://github.com/swagger-api/swagger-core/releases/tag/v2.2.22

@bnasslahsen have you got an idea of the release date of Spring Doc based on this new swagger-core version?
