### ISSUE TITLE
Bug: Required param object is not marked as required

### ISSUE THREAD

**Issue by hectoryo** [springdoc/springdoc-openapi#156]
So to make a simplified example, I  have these 2 entities:
```java
public class EntityA {
	@Schema(required = true)
	private String fieldA;
	//Getters and setters...
}
```

```java
public class EntityB {

	@Schema(required = true)
	private String fieldB;
	
	@Schema(required = true)
	private EntityA entityA;
	//Getters and setters...
}
```
As you see, EntityB has 2 required atributes fieldB and entityA.

 I also have this method in the controller:
```java
	@GetMapping(path = "/entity-b", produces = { "application/json", "application/xml" })
	public EntityB getEntityB(){
		return new EntityB();
	}
```

When the doc is generated, in the EntityB, only fieldB is marked as required:
```json
         "EntityA":{
            "required":[
               "fieldA"
            ],
            "type":"object",
            "properties":{
               "fieldA":{
                  "type":"string"
               }
            }
         },
         "EntityB":{
            "required":[
               "fieldB"
            ],
            "type":"object",
            "properties":{
               "fieldB":{
                  "type":"string"
               },
               "entityA":{
                  "$ref":"#/components/schemas/EntityA"
               }
            }
         }
```
![image](https://user-images.githubusercontent.com/5202409/68655835-08f48380-0531-11ea-964a-cefc5c8d26e8.png)

The expected behaviour is that both fieldB and entityA should be marked as required in the schema EntityB

**Comment by springdoc** [comment]
Hi, 

 This issue is not related to springdoc-openapi. We generate the OpenAPI description, and then we mainly rely on the official swagger jars (annotations/models/ui). Our library is built on top of them.

This behaviour you are describing is an issue on the swagger-ui. We rely on v3.24.0 of the swagger-ui.

You can submit your request to the swagger-ui team for this feature:
https://github.com/swagger-api/swagger-ui/issues

**Comment by hectoryo** [comment]
Thanks for the info, I've found this issue already reported in swagger-core git:

https://github.com/swagger-api/swagger-core/issues/3259

There I've found this workaround:

https://stackoverflow.com/a/51724683

**Comment by glockbender** [comment]
FYI: swagger issue now fixed and closed: https://github.com/swagger-api/swagger-core/issues/3259

**Comment by bnasslahsen** [comment]
FYI v1.3.1 of springdoc-openapi ships swagger-core 2.1.2 which fixes this issue.
