### ISSUE TITLE
Incompatible with ComponentScan and multiple Servlets

### ISSUE THREAD

**Issue by lbenedetto** [springdoc/springdoc-openapi#1560]
**Describe the bug**
When using `@ComponentScan` SpringDocs does not detect any endpoints.

**To Reproduce**

- What version of spring-boot you are using? 2.6.4
- What modules and versions of springdoc-openapi are you using? `ui`, 1.6.6
Actual json: `"paths":{},"`
Expected json: `"paths":{"/api/v1/neat":{ ... `

But it should have my configured API title and information about the endpoint.

In my actual project, there are many excluded packages, and each one gets its own ServletRegistrationBean. This way they can all have their own JSON serialization configuration.
```java
package com.example;

@SpringBootApplication(scanBasePackages = "com.example")
@ComponentScan(basePackages = "com.example", excludeFilters = {
    @ComponentScan.Filter(type = FilterType.REGEX, pattern = "com.example.demo.*")
})
public class DemoApplication {

  public static void main(String[] args) {
    SpringApplication.run(DemoApplication.class, args);
  }

  @Bean
  public OpenAPI springShopOpenAPI() {
    return new OpenAPI()
        .info(new Info()
            .title("Demo API")
            .version("v0.0.1"));
  }

  @Bean
  public ServletRegistrationBean<DispatcherServlet> api(ApplicationContext parent) {
    return createChildServlet(
        Arrays.asList("/api/*"),
        DocsConfig.class,
        "api",
        parent);
  }

  private ServletRegistrationBean<DispatcherServlet> createChildServlet(List<String> urlMappings,
      Class<?> configuration, String servletRegistrationBeanName, ApplicationContext parent) {

    var applicationContext = new AnnotationConfigWebApplicationContext();
    applicationContext.register(configuration);
    applicationContext.setParent(parent);
    var dispatcherServlet = new DispatcherServlet(applicationContext);
    var servletRegistrationBean = new ServletRegistrationBean<>(dispatcherServlet,
        urlMappings.toArray(new String[] {}));
    servletRegistrationBean.setName(servletRegistrationBeanName);
    servletRegistrationBean.setLoadOnStartup(1);
    return servletRegistrationBean;
  }

}
```
```java
package com.example.demo;

@Configuration
@ComponentScan
public class DocsConfig {
  @Bean
  public GroupedOpenApi demoApiDocs() {
    return GroupedOpenApi.builder()
        .group("demo")
        .packagesToScan("com.example.demo")
        .build();
  }
}
```

```java
package com.example.demo;

@RestController
@RequestMapping("/api/v1")
public class DemoController {
  @Operation(summary = "Demo documentation")
  @GetMapping("/neat")
  public ResponseEntity<String> neat() {
    return ResponseEntity.ok("Neat");
  }
}
```

If I remove my ComponentScan stuff, everything works as expected. 

I've tried manually importing some SpringDoc beans as I've seen in the FAQ
```
@Import({org.springdoc.core.SpringDocConfiguration.class,
    org.springdoc.webmvc.core.SpringDocWebMvcConfiguration.class,
    org.springdoc.webmvc.ui.SwaggerConfig.class,
    org.springdoc.core.SwaggerUiConfigProperties.class,
    org.springdoc.core.SwaggerUiOAuthProperties.class,
    org.springdoc.core.SpringDocConfigProperties.class,
    org.springframework.boot.autoconfigure.jackson.JacksonAutoConfiguration.class})
```

**Comment by bnasslahsen** [comment]
@lbenedetto, 

This has nothing to do with springdoc. 
Make sure you review your configuration.

**Comment by lbenedetto** [comment]
Ah, it seems I was a little overzealous in trimming my project down to provide the demo and actually removed the bit that registers the endpoint. The endpoint actually doesn't get registered in the provided demo, so of course, spring doc doesn't find it.

However, if I fix that issue by adding `@EnableWebMvc` to DocsConfig, the endpoint is registered and functional, but is still not detected by Springdoc.

If I am still missing configuration, I would greatly appreciate being pointed in the right direction as I haven't been able to find anything on springdoc.org or the FAQ.

**Comment by bnasslahsen** [comment]
@lbenedetto, 

You have so many tickets around this : #1227 https://github.com/springdoc/springdoc-openapi/issues/150 https://github.com/springdoc/springdoc-openapi/issues/361 https://github.com/springdoc/springdoc-openapi/issues/236

First, you don't need `@EnableWebMvc` with spring-boot.
If you are still struggling, try Providing a [Minimal, Reproducible Example - with HelloController](https://stackoverflow.com/help/minimal-reproducible-example)[](https://github.com/springdoc/springdoc-openapi/blob/231db66ef1c64d2ea5fe3ee84c39e31a8b331b70/CONTRIBUTING.adoc#reporting-security-vulnerabilities) that reproduces the problem, so we can help you.

**Comment by bnasslahsen** [comment]
@lbenedetto, 

Your project is not respecting any best practice.
There is a much easier configuration to use spring-boot.

Your project is mixing spring-mvc classic application (without spring-boot) and spring-boot configuration.
Note that `SpringBootApplication` already contains `basePackages` scan ....

You will find attached the fixed version.
Swagger-ui will be available at `http://localhost:8080/swagger-ui/index.html` or `http://localhost:8080/MyServlet/swagger-ui/4.5.0/index.html`

I strongly encourage you to simplify your project, which is just a source of errors.

[demo.zip](https://github.com/springdoc/springdoc-openapi/files/8322294/demo.zip)

**Comment by lbenedetto** [comment]
Thanks for helping, but in your version, the endpoint is duplicated and is available at `/persons`, and the generated documentation only documents `/persons` and NOT `/MyServlet/persons` which is the exact opposite of what I need.

I get that my demo project seems overly complicated, but it is a representation of my actual project which is complicated by necessity.  Dozens of servlets each with hundreds of endpoints. Different serialization, error handling, and security configurations for each servlet to remain compatible with various existing web and mobile clients already in production.

As far as I can tell from research, ComponentScan is the correct way to achieve what is needed for my project.

My configuration may not be the ideal configuration but it is a valid spring configuration and it was supported by Springfox.

Here is an updated demo project that captures some of the complexity from my real project that justifies the need for ComponentScan filters and multiple servlets. It has multiple controllers with conflicting endpoint names and different serialization configs for each controller.

[demo.tar.gz](https://github.com/springdoc/springdoc-openapi/files/8324177/demo.tar.gz)

**Comment by lbenedetto** [comment]
I got SpringDoc to work with my existing setup.
In case anyone else has this issue, here is how I did it:

1. Disable SpringDoc
```
springdoc.api-docs.enabled=false
```

2. Create a class for registering custom property sources
```
	private static class CustomBooleanPropertySource extends PropertySource<Boolean> {

		private boolean value;

		public CustomBooleanPropertySource(String name, boolean value) {
			super(name);
			this.value = value;
		}

		@Override
		public Boolean getProperty(String name) {
			if (name.equals(this.name)) {
				return value;
			}
			return null;
		}
	}
```
3. Enable springdoc in each servlet (this is inside createChildServlet)
```
applicationContext.setParent(parent);
applicationContext.getEnvironment().getPropertySources()
    .addFirst(new CustomBooleanPropertySource("springdoc.api-docs.enabled", true));
```

4. Scan org.springdoc inside your servlet. 
```
@ComponentScan(basePackages = {"com.example.other", "org.springdoc"})
```

Here is a complete example project that is working as expected.
[demo.tar.gz](https://github.com/springdoc/springdoc-openapi/files/8410288/demo.tar.gz)

**Comment by lbenedetto** [comment]
One issue with solving it the way I have is that while `/hello/v3/api-docs` and `/hello/v3/api-docs/swagger-config` work fine, when you try to load the UI, it returns HTML pointing to `/v3/api-docs/swagger-config` because it doesn't know there is a prefix in the path. So the UI doesn't work.

I was able to hack around this by using a BeanPostProcessor to replace SwaggerWelcomeWebMvc with my own version that just overrides `buildApiDocUrl()` with some logic for handling the custom prefix per servlet. (Setting the 'correct' URL in SwaggerUiConfigProperties doesn't work, it just breaks everything else. It is only this one bean that needs extra prefix logic)
