### ISSUE TITLE
swagger-ui.enabled = false --> Not Working

### ISSUE THREAD

**Issue by aablan** [springdoc/springdoc-openapi#1567]
**Describe the bug**
I  want to disable swagger-ui in spring boot based application, I used property swagger-ui.enabled = false
the ui is not accessible directly from <root-url>/swagger-ui.html, it can still be access from <root-url>/webjars/swagger-ui/index.html

**To Reproduce**
- use the dep in spring boot based app.
```
<dependency>
            <groupId>org.springdoc</groupId>
            <artifactId>springdoc-openapi-ui</artifactId>
            <version>1.6.6</version>
</dependency>
```
- configure the property swagger-ui.enabled = false in the application.properties
- hit the url <root>/webjars/swagger-ui/index.html, it will show pet store swaggers.
- replace the url in search bar (https://petstore.swagger.io/v2/swagger.json) with the configure docs path for yr application (/v3/api-docs)
- swagger-ui for your application will show up

**Expected behavior**
- swagger-ui should be completely disabled. and not accessible from anywhere

**Screenshots**
<img width="1108" alt="Screen Shot 2022-03-21 at 4 21 51 PM" src="https://user-images.githubusercontent.com/17702504/159269885-b0a9b34b-f7ea-4860-bd70-e620b834a75c.png">

<img width="1648" alt="Screen Shot 2022-03-21 at 4 22 20 PM" src="https://user-images.githubusercontent.com/17702504/159270070-5f878a7e-dd14-438c-9608-9ac15133f365.png">

**Additional context**
Same issue is there when using dependency 
```
       <dependency>
            <groupId>org.springdoc</groupId>
            <artifactId>springdoc-openapi-webflux-ui</artifactId>
            <version>1.6.6</version>
        </dependency>
```

**Comment by bnasslahsen** [comment]
@aablan, 

see the properties list in the documentation: https://springdoc.org/#swagger-ui-properties

**Comment by aablan** [comment]
@bnasslahsen , I ve seen the properties, if you think I am missing smth, can you please point out a specific property that should solve the issue, instead of the whole list ?

**Comment by bnasslahsen** [comment]
@aablan, 

You haven't read the documentation, as you have no where `swagger-ui.enabled`
The only property available is:  `springdoc.swagger-ui.enabled=false`

Remember, contributions to this repository should follow its [contributing guidelines](https://github.com/springdoc/springdoc-openapi/blob/6ce3b5abed24ec6676783519488b1a5a13c52e93/CONTRIBUTING.adoc) and [code of conduct](https://github.com/springdoc/springdoc-openapi/blob/6ce3b5abed24ec6676783519488b1a5a13c52e93/CODE_OF_CONDUCT.md)[](https://github.com/bnasslahsen)[](https://github.com/aablan)[](https://github.com/).

If you have any other comment, make sure you follow the above guidance.

**Comment by aablan** [comment]
@bnasslahsen  updated the property name.

**Comment by jbrugman** [comment]
Please re-open this issue, I experience exactly the same.

```
// Swagger dependencies
implementation 'org.springdoc:springdoc-openapi-kotlin:1.6.8'
implementation 'org.springdoc:springdoc-openapi-webflux-ui:1.6.8'
```

application.yaml
```
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    display-request-duration: true
    groups-order: DESC
    operationsSorter: method
    disable-swagger-default-url: true
```

http://localhost:8080/v3/api-docs shows the proper json and specs
http://localhost:8080/swagger-ui.htm shows the petstore demo.

When replacing the  `https://petstore.swagger.io/v2/swagger.json `in the text-box to` /v3/api-docs`, you’ll see the documentation that I would have expected. 

Tried clean rebuilding, adding ?configUrl= to the url, cleaning browser cache, using another browser... no luck

When using curl:

`curl "http://localhost:8080/webjars/swagger-ui/index.html?configUrl=/v3/api-docs/swagger-config"`

The response is: 

```
<!-- HTML for static distribution bundle build -->
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <title>Swagger UI</title>
    <link rel="stylesheet" type="text/css" href="./swagger-ui.css" />
    <link rel="icon" type="image/png" href="./favicon-32x32.png" sizes="32x32" />
    <link rel="icon" type="image/png" href="./favicon-16x16.png" sizes="16x16" />
    <style>
      html
      {
        box-sizing: border-box;
        overflow: -moz-scrollbars-vertical;
        overflow-y: scroll;
      }

      *,
      *:before,
      *:after
      {
        box-sizing: inherit;
      }

      body
      {
        margin:0;
        background: #fafafa;
      }
    </style>
  </head>

  <body>
    <div id="swagger-ui"></div>

    <script src="./swagger-ui-bundle.js" charset="UTF-8"> </script>
    <script src="./swagger-ui-standalone-preset.js" charset="UTF-8"> </script>
    <script>
    window.onload = function() {
      // Begin Swagger UI call region
      const ui = SwaggerUIBundle({
        url: "https://petstore.swagger.io/v2/swagger.json",
        dom_id: '#swagger-ui',
        deepLinking: true,
        presets: [
          SwaggerUIBundle.presets.apis,
          SwaggerUIStandalonePreset
        ],
        plugins: [
          SwaggerUIBundle.plugins.DownloadUrl
        ],
        layout: "StandaloneLayout"
      });
      // End Swagger UI call region

      window.ui = ui;
    };
  </script>
  </body>
</html>
```

Why is there still an onlload function pointing to the petstore???

**Comment by jbrugman** [comment]
ps. `http://localhost:8080/webjars/swagger-ui/index.html?configUrl=/v3/api-docs/swagger-config` is what `http://localhost:8080/swagger-ui.html` redirected me to when trying 1.4.1.
Using 1.6.8 I get redirected to `http://localhost:8080/webjars/swagger-ui/index.html`

Both pages give the same petstore result.

**Comment by Tnwmack** [comment]
I have the same issue. It appears to be caused by the dependency org.webjars.swagger-ui. Even if you set springdoc.swagger-ui.enabled to false, org.webjars.swagger-ui will still put the static files in the webjars directory at build time, which Spring will serve by default.

The dependency can be excluded though:
````
<dependency>
  <groupId>org.springdoc</groupId>
  <artifactId>springdoc-openapi-webflux-ui</artifactId>
  <version>1.6.9</version>
  <exclusions>
    <exclusion>
      <groupId>org.webjars</groupId>
      <artifactId>swagger-ui</artifactId>
    </exclusion>
  </exclusions>
</dependency>

**Comment by aablan** [comment]
@jbrugman , @Tnwmack , as u can see this issue was closed, I am not sure how to reopen it

**Comment by hajdukd** [comment]
The same issue here, there is no way to disable swagger-ui...
