### ISSUE TITLE
Springdoc ui ignores urls.primaryName query parameter

### ISSUE THREAD

**Issue by evgenbal** [springdoc/springdoc-openapi#1569]
**Describe the bug**
- If your url path have query parameter `urls.primaryName`, springdoc ui opens default definition instead of definition in  `urls.primaryName` query parameter

**To Reproduce**
- Spring Boot 2.6.2, springdoc-openapi 1.6.6, Google Chrome Version 99.0.4844.82 (Official Build) (64-bit)
- Create openapi doc with >1 definition for ex `notification-private` and `notification-public`
- Open documentation. It openes with default definition, for ex `notification-private` ![1](https://user-images.githubusercontent.com/36564408/159525000-630d7e45-9e39-491a-ab57-54b0692bf13f.png)
- In ui select another definition, for ex `notification-public` ![2](https://user-images.githubusercontent.com/36564408/159525033-4d856e0e-5306-40a9-ab9e-f6dffdf1cb35.png)
- refresh page 

**Expected behavior**
- You are on page with `notification-public` definition 

**Actual behavior**
- You are on page with `notification-private` definition ![3](https://user-images.githubusercontent.com/36564408/159525070-ba11cc9f-8afc-430b-b451-0880e0ac68ed.png)

**Additional context**
Bug did not reproduced in springdoc version 1.5.12

**Comment by bnasslahsen** [comment]
@evgenbal, 

See the answer here: https://github.com/springdoc/springdoc-openapi/issues/1439
