### ISSUE TITLE
swagger-ui/index.html works fine while visiting path swagger-ui/ returns 404

### ISSUE THREAD

**Issue by drz0910** [springdoc/springdoc-openapi#1571]
Hi, I've integrated springdoc and the functions works well, there's only one thing left that I would like to ask for some help/guidance here. 
So far when visiting the following urls, the response codes are:
- http://localhost/swagger-ui.index.html , returns 200, auto redirect to http://localhost/swagger-ui/index.html
- http://localhost/swagger-ui/index.html , returns 200
- http://localhost/swagger-ui/ , returns 404

Did I miss any configuration that controls the auto loading of index.html under this path? Thanks!

Additional info:
Integration: 
- Spring Boot 2.5.6
- springdoc-openapi-ui 1.6.6

Configuration:
- springdoc.webjars.prefix=""

**Comment by bnasslahsen** [comment]
@drz0910, 

Please read the documentation. 

`springdoc.webjars.prefix` is relevant for webflux.

For the url of the swagger-ui, see https://springdoc.org/#getting-started

**Comment by drz0910** [comment]
Hi @bnasslahsen, thanks for the reply. Maybe I'm not describing clear. 
My questions is not about the `springdoc.webjars.prefix` configuration. The swagger UI works as expected, but the url redirection only partially works.
- visiting `/swagger-ui.index.html` works, will be redirect to `/swagger-ui/index.html`.
- directly visiting `/swagger-ui/index.html` works as well.
- directly visiting `/swagger-ui/` fails with `404 Not Found`, which means the path is not handled to load `/swagger-ui/index.html` automatically
I'm trying to find a configuration that deals with this route, but cannot find from the document.
Would appreciate if you could help to give some more inputs. Thanks!

**Comment by TranGiaBao-2000** [comment]
@drz0910 did you find out the solution? I have the same problem. Please help me.

**Comment by superfrogbe** [comment]
Same behaviour here, and no real solution?
