### ISSUE TITLE
JodaMoney serialisation and deserialisation problem

### ISSUE THREAD

**Issue by lovewithmind** [springdoc/springdoc-openapi#1575]
Hi,

I am using springdoc-openapi-ui version 1.6.4.
While using JodaMoney in request or response the springfox swagger jackson serialization is not picking up JodaMoneyModule . I have tried multiple ways to pass the modules but it is still not able to register with the objectmapper used by spring doc to serialize the request while creating the swagger documentation.

I have added this for JodaMoney serialization.
This module is able to get registered with objectMapper normally but with swagger it is still using the objectMapper without JodaMoneyModule and generating invalid json.
`
 @Bean
    fun jodaMoney(): JodaMoneyModule {
        return JodaMoneyModule()
    }
`

This is a sample request of joda money
`  @Operation
    @ApiResponse
    @PostMapping("/open/api")
    fun someApi(@RequestBody jodaMoney: Money): ResponseEntity<String> {
        val money = objectMapper.writeValueAsString(jodaMoney)
        return ResponseEntity.ok(money)
    }
`

JodaMoney serialization should only return 
`{
    "currency": "USD",
    "amount": 12
}`
but right now it is showing
`{
  "negative": true,
  "zero": true,
  "positive": true,
  "currencyUnit": {
    "code": "string",
    "numericCode": 0,
    "decimalPlaces": 0,
    "symbol": "string",
    "numeric3Code": "string",
    "countryCodes": [
      "string"
    ],
    "pseudoCurrency": true
  },
  "scale": 0,
  "amount": 0,
  "amountMajor": 0,
  "amountMajorLong": 0,
  "amountMajorInt": 0,
  "amountMinor": 0,
  "amountMinorLong": 0,
  "amountMinorInt": 0,
  "minorPart": 0,
  "positiveOrZero": true,
  "negativeOrZero": true
}`

Please help how can I configure the swagger request/response converter to use JodaMoneyModule.

Thanks

**Comment by bnasslahsen** [comment]
@lovewithmind, 

Try this:


```java
static {
    SpringDocUtils.getConfig().replaceWithClass(org.joda.money.Money.class, org.springdoc.core.converters.models.MonetaryAmount.class);
}

```

**Comment by lovewithmind** [comment]
Thank you @bnasslahsen that worked
