### ISSUE TITLE
No matching handler error

### ISSUE THREAD

**Issue by monstrfolk** [springdoc/springdoc-openapi#158]
Added below to existing project with no swagger ui

        <dependency>
            <groupId>org.springdoc</groupId>
            <artifactId>springdoc-openapi-webflux-ui</artifactId>
            <version>1.2.6</version>
        </dependency>

Go to localhost/swagger-ui.html and redirects to http://localhost/webjars/swagger-ui/index.html?url=/v3/api-docs&validatorUrl=

Get error message

{"timestamp":1573802303481,"path":"/webjars/swagger-ui/index.html","status":404,"error":"Not Found","message":"No matching handler"}

Are there other steps to setup swagger ui?

**Comment by springdoc** [comment]
Hi, 

 No additional steps needed if you use webflux. You just choose the right dependency (webflux or webmvc)
 Here a sample application springdoc-openapi-test-app3 using webflux;
- https://github.com/springdoc/springdoc-openapi-demos.git

 If you still have issues, you can add the sample code to reporduce it and we will have a look at it.
