### ISSUE TITLE
OpenAPI response caching doesn't respect group. 

### ISSUE THREAD

**Issue by azizabah** [springdoc/springdoc-openapi#1583]
**Describe the bug**
If there is more than one GroupedOpenApi created at runtime using a replacement multipleOpenApiResource bean using a different group identifier and caching is enabled the first group return is cached and always returned no matter which group is specified.

**To Reproduce**
https://github.com/azizabah/springdocs-example

If you run the three separate test classes:
noCache and manual will always pass. 
dynamic will fail if the tests are run as one instance but pass separately. 

**Expected behavior**
The cache should respect the groups correctly.

I believe this is what #1270 and #858 had stumbled upon but couldn't provide an example to replicate.

**Comment by bnasslahsen** [comment]
@azizabah, 

This is the correction of your code that shows the right config:


```kotlin
package com.example.springdocs.config

import com.example.Constants.API_VERSION_1
import com.example.Constants.API_VERSION_2
import io.swagger.v3.oas.models.Paths
import org.springdoc.core.GroupedOpenApi
import org.springframework.context.annotation.Bean
import org.springframework.context.annotation.Configuration
import org.springframework.context.annotation.Profile

@Profile("dynamic")
@Configuration
class SpringDocsConfig1 {

	val swaggerBasePath = "objects"

	@Bean
	fun version1(): GroupedOpenApi? {
		return buildApi(API_VERSION_1,Version1::class.java)
	}


	@Bean
	fun version2(): GroupedOpenApi? {
		return buildApi(API_VERSION_2,Version2::class.java)
	}

	fun buildApi(name: String, version: Class<out Annotation>):GroupedOpenApi {
		return GroupedOpenApi.builder()
			.group(name)
			.addOpenApiMethodFilter { method -> method.isAnnotationPresent(version) }
			.addOpenApiCustomiser { openApi ->
				openApi?.paths = Paths().extensions(openApi?.paths?.mapKeys {
					it.key.replace(swaggerBasePath, "")
				})
			}
			.build()
	}
}

@Target(AnnotationTarget.FUNCTION)
annotation class Version1

@Target(AnnotationTarget.FUNCTION)
annotation class Version2
```

**Comment by azizabah** [comment]
@bnasslahsen - Sure that works but it doesn't explain why turning caching off makes the existing code work.

**Comment by bnasslahsen** [comment]
@azizabah, 

The right explanation, is just trying to keep things simple and respecting standards makes it work out of the box.
Without the need of any complexity. You overriding `MultipleOpenApiWebMvcResource`, was the cause leading to this behavior...
