### ISSUE TITLE
Multiple GroupedOpenApi - Select definition button

### ISSUE THREAD

**Issue by NullpointerForever** [springdoc/springdoc-openapi#1585]
**Describe the bug**
If I have multiple GroupedOpenApi beans, in Swagger UI there isn't a _Select definition_ button.

**To Reproduce**
- What version of spring-boot you are using?
2.6.3
- What modules and versions of springdoc-openapi are you using?
springdoc-openapi-ui 1.6.6
- What is the actual and the expected result using OpenAPI Description (yml or json)?
In Swagger UI there is a list of all endpoints.
- Provide with a sample code (HelloController) or Test that reproduces the problem
```java
@Configuration
public class MyWebappApiConfig {

	@Bean
	public GroupedOpenApi apiV1() {
		return GroupedOpenApi.builder().group("v1").packagesToScan("company.webapp.api.v1").build();
	}

	@Bean
	public GroupedOpenApi apiV2() {
		return GroupedOpenApi.builder().group("v2").packagesToScan("company.webapp.api.v2").build();
	}
}
```

**Expected behavior**
- A clear and concise description of what you expected to happen.
In Swagger UI I expect a _Select definition_ button visible to select one of my definition (v1, v2).

**Additional context**
When I add a definitions in my _bootstrap.yml_ file like:
```
springdoc:
  group-configs:
    - group: v3
      packages-to-scan: company.webapp.api.v3
      paths-to-match: /v3/**
```
the button is visible with my v1, v2 and v3.

**Comment by bnasslahsen** [comment]
@NullpointerForever, 

Not reproducible.
Try Providing a [Minimal, Reproducible Example - with HelloController](https://stackoverflow.com/help/minimal-reproducible-example)[](https://github.com/springdoc/springdoc-openapi/blob/008aad6de05b211ab83fdd052ab3ced1d85bd2bf/CONTRIBUTING.adoc#reporting-security-vulnerabilities) that reproduces the problem
