### ISSUE TITLE
Add support for Kotlin Coroutines

### ISSUE THREAD

**Issue by joaodias14** [springdoc/springdoc-openapi#159]
Kotlin coroutines add an extra `Continuation` parameter in the suspending function. This means that there is an additional parameter in our Controller's methods. Currently, we are facing two issues with this.

**1st Issue**
Depending on where the code is built, we get the following error while accessing Swagger:
> com.fasterxml.jackson.databind.JsonMappingException: Null key for a Map not allowed in JSON (use a converting NullKeySerializer?) (through reference chain: io.swagger.v3.oas.models.OpenAPI["paths"]->io.swagger.v3.oas.models.Paths["/srv/v1/{redisInstance}/keys/{key}"]->io.swagger.v3.oas.models.PathItem["put"]->io.swagger.v3.oas.models.Operation["requestBody"]->io.swagger.v3.oas.models.parameters.RequestBody["content"]->io.swagger.v3.oas.models.media.Content["*/*"]->io.swagger.v3.oas.models.media.MediaType["schema"]->io.swagger.v3.oas.models.media.ObjectSchema["properties"]->java.util.LinkedHashMap["null"])

We found that code built in my IDE works, but the one built on my colleague IDE or via command line does not work. We think the issue is related to the name that is given to the `Continuation` parameter. On the code that works, its name is `paramContinuation` and on the one that does not work, its name is `$completion`. Our assumption is that Springdoc/Swagger doesn't "like" this dollar sign in the name which leads to the exception above. You may be wondering if we've found the reason for this parameter name difference, but we didn't 😞 

**2nd Issue**
If we run the code built in my IDE (the one which actually works), we can access Swagger. However, we see that the `Continuation` parameter is now part of it in every endpoint with a suspending function. This parameter is considered a request body or query parameter depending on the HTTP method (our guess). We would like to have this parameter removed from the endpoints.

Our questions:
1. Do you have Kotlin Coroutines support on your roadmap (which may require ignoring `Continuation` parameters)?
2. If not (or until you do) is there any possibility to instruct Springdoc/Swagger to simply ignore a given class so that we can work-around this issue?

Thanks and keep up the good work!

**Comment by springdoc** [comment]
Hi,

 Our library first goal is to cover the main functionalities using spring-boot/Java and swagger-annotations for OpenAPI 3.

 It's difficult to investigate on your issue to get the root cause, because the stackTrace you are providing is coming from Jackson.

  There are some guys that use springdoc-openapi for kotlin, but when they face an issue they try to translate it (when possible) to the Java world, so we can fix it for both.
- @Parameter(hidden = true)
- use a custom converter for your type,  (You can have a look at ObjectNodeConverter)

**Comment by joaodias14** [comment]
I forgot to mention, but that Jackson stack-trace is related to the serialization of api-docs. 
I understand that the library focuses on main functionalities, but Kotlin Coroutines will soon get popular in the Spring world (its support has just been added to Spring). We have moved from springfox to springdoc, because the first just lagged behind some new features in the Spring world.

I can't translate this issue to Java world because it is specific to Kotlin. The `Continuation` () parameter is added behind the scenes when using suspending functions. Having said that we can't use `@Parameter(hidden = true)`. We will take a look at `ObjectNodeConverter `. Thanks!

**Comment by joaodias14** [comment]
I've created a PR for this support. Can you please take a look and check if it is ok? I believe this would be valuable since Kotlin is gaining traction.

**Comment by jnfeinstein** [comment]
@joaodias14 by any chance are responses from suspending functions being generated correctly in your application?  I am using WebFlux w/ Kotlin coroutines and there are no generated responses.  I am not sure if this is a bug or user error.

**Comment by joaodias14** [comment]
Hi @jnfeinstein, yup we have no issues with kotlin-coroutines version 1.3.3 and springdoc-openapi version 1.2.18.

**Comment by jnfeinstein** [comment]
I tried with the versions you've specified as well as the latest of each package.
```kotlin
enum class SystemStatus(val status: String) {
    OK("OK")
}

data class SystemStatusResponse(
  val status: SystemStatus
)

@RestController
@RequestMapping("/\${api.version}/public/status")
class SystemStatusController {
    @GetMapping
    suspend fun index() = SystemStatusResponse(SystemStatus.OK)
}
```
produces:
```
{
  "/v1/public/status": {
    "get": {
      "tags": [
        "system-status-controller"
      ],
      "operationId": "index",
      "responses": {
        "200": {
          "description": "default response",
          "content": {
            "*/*": {
              "schema": {
                "type": "object"
              }
            }
          }
        }
      }
    }
  }
}
```
Removing `suspend` results in:
```
{
  "/v1/public/status": {
    "get": {
      "tags": [
        "system-status-controller"
      ],
      "operationId": "index",
      "responses": {
        "200": {
          "description": "default response",
          "content": {
            "*/*": {
              "schema": {
                "$ref": "#/components/schemas/SystemStatusResponse"
              }
            }
          }
        }
      }
    }
  }
}
```
Have I missed something grotesquely obvious?

**Comment by jnfeinstein** [comment]
As an easy workaround, it appears that this works fine:
```kotlin
@RestController
@RequestMapping("/\${api.version}/public/status")
class SystemStatusController {
    @GetMapping
    fun index() = mono { status() }

    suspend fun status() = SystemStatusResponse(SystemStatus.OK)
}
```
Not perfect but close enough for jazz.

**Comment by simonherbert** [comment]
I'm still having this issue. Is there no solution?

**Comment by Duduxs** [comment]
4 me, not worked putting springdoc open-api in testImplementation, but

` runtimeOnly("org.springdoc:springdoc-openapi-kotlin:1.6.11")`

at runtimeOnly in gradle.
