### ISSUE TITLE
Double quotes missing for header parameter example value

### ISSUE THREAD

**Issue by vikramsetty** [springdoc/springdoc-openapi#1590]
**Describe the bug**
An example of the header parameter in the handler method should be enclosed with double quotes. 

**Version: 3.0.1**

**To Reproduce**
@Parameters({ @Parameter(name = "If-Match",
            description = " etag of the request",
            required = true, schema = @Schema(implementation = String.class), in = ParameterIn.HEADER,
            example = "\"1\"") })

**Expected behavior**
Expect "1" instead of 1
Since this example is a String, why doesn't it take "1" as an example value

**Code**
library: io\swagger\core\v3\swagger-annotations\2.1.12\swagger-annotations-2.1.12-javadoc.jar
package: io.swagger.v3.oas.annotations
interface: Parameter
parameter: example 

**Actual current screenshot**
![image](https://user-images.githubusercontent.com/11085368/161532659-6bebde48-1883-49c1-8a43-58b036c2f169.png)
**Expected screenshot**
![image](https://user-images.githubusercontent.com/11085368/161531743-08aae891-fa95-404c-b94c-cf1b68b34e6e.png)

**Comment by bnasslahsen** [comment]
@vikramsetty, 

This is the expected behaviour. You should esapce when necessary.
see the answer here https://github.com/springdoc/springdoc-openapi/issues/478
