### ISSUE TITLE
Some fields are not generated in the superclass but in the subclass instead (polymorphism with @Schema annotation)

### ISSUE THREAD

**Issue by kevin-gautama-l** [springdoc/springdoc-openapi#1591]
**Description**

I am trying to generate openapi specs from Java code in a Spring Boot project that contains tree-structured object (with polymorphism), and found that some fields are missing in the super type. Fields of type list of refs are instead declared in one of the subtypes, and therefore missing in all other subtypes. But fields of other types work, so I think this may be a bug.

I am using:
- Spring Boot 2.6.6
- springdoc-openapi-ui 1.6.6
- Java 8

I have reproduced the problem here: https://github.com/kevin-gautama-l/test-springdocs-polymorphism
When this project is started (MyApp.java), the specs will be available under http://localhost:8080/v3/api-docs.yaml

In this example, I want to return a tree-structured object. There are leaf nodes and container nodes. Container nodes should contain `childNodes` - however, this field is missing in the generated specs for the Container model. Instead, I found it in one of the subclasses (ContainerType1), so it is missing for the other concrete subclasses (ContainerType2, ContainerType3):

**Java Code**

    @Schema(
            allOf = Node.class,
            subTypes = {
                    ContainerType1.class,
                    ContainerType2.class,
                    ContainerType3.class,
            },
            discriminatorProperty = "className",
            discriminatorMapping = {
                    @DiscriminatorMapping (value = "ContainerType1", schema = ContainerType1.class),
                    @DiscriminatorMapping (value = "ContainerType2", schema = ContainerType2.class),
                    @DiscriminatorMapping (value = "ContainerType3", schema = ContainerType3.class),
            }
    )
    public abstract class Container extends Node
    {
        private List<Node> childNodes;
    
        public List<Node> getChildNodes() {return childNodes;}
    
        public void setChildNodes( List<Node> childNodes ) {this.childNodes = childNodes;}
    }

**Generated api-docs.yaml**

    Container:
      type: object
      discriminator:
        propertyName: className
        mapping:
          ContainerType1: '#/components/schemas/ContainerType1'
          ContainerType2: '#/components/schemas/ContainerType2'
          ContainerType3: '#/components/schemas/ContainerType3'
      allOf:
      - $ref: '#/components/schemas/Node'
    ContainerType1:
      type: object
      allOf:
      - $ref: '#/components/schemas/Container'
      - type: object
        properties:
          nodeType:
            type: string
          childNodes:
            type: array
            items:
              oneOf:
              - $ref: '#/components/schemas/Container'
              - $ref: '#/components/schemas/NodeType1'
              - $ref: '#/components/schemas/NodeType2'
              - $ref: '#/components/schemas/NodeType3'
    ContainerType2:
      type: object
      allOf:
      - $ref: '#/components/schemas/Container'
    ContainerType3:
      type: object
      allOf:
      - $ref: '#/components/schemas/Container'

**Expected behavior**

`childNodes` should be defined under `Container` instead of under `ContainerType1`

**Additional info**

If I add fields which are not of type `List<Node>` in the `Container` class (e.g. `boolean` or `List<String>`), they would actually be exported correctly under the `Container` model specs and not under `ContainerType1`.

I tried removing the `@Schema` annotation completely from the `Node` class and the `childNodes` field is now correctly specified under the `Container` model instead of `ContainerType1`. But I need this `@Schema` annotation in the `Node` class so that the models for the other node types are exported too in the specs (`NodeType1`, `NodeType2`, `NodeType3`).

**Comment by bnasslahsen** [comment]
@kevin-gautama-l, 

`springdoc-openapi` relies on `swagger-core` project.
The behavior you are describing is directly handled using [swagger-core](https://github.com/swagger-api/swagger-core/).

This is a sample code that shows how the generation is done, with only `swagger-core` classes:
```java
ResolvedSchema resolvedSchema = ModelConverters.getInstance()
		.resolveAsResolvedSchema(
				new AnnotatedType(ContainerType1.class));
Assert.isTrue(!((ObjectSchema) resolvedSchema.schema.getAllOf().get(1)).getProperties().containsKey("childNodes"), "I'd like it to be true!");
```

Feel free to ask the swagger team instead and reference this ticket.
