### ISSUE TITLE
Possibility to add an Default Cached OpenAPI for every Locale

### ISSUE THREAD

**Issue by TimmyHil** [springdoc/springdoc-openapi#1592]
**Is your feature request related to a problem? Please describe.**
Hi, when i am starting my application, i register my own OpenAPI Object and save it into the cache. 

```
   public OpenAPIServiceConfigurator( OpenAPIService service, OpenAPI openApiLoaded )
   {
      if ( openApiLoaded instanceof OpenAPIWithoutDefaultServerDescription )
      {
         service.setCachedOpenAPI( openApiLoaded, Locale.getDefault() );
      }
   }
```

But if someone sends an request with a different Locale, it will not respond with my own OpenAPI Object.

**Describe the solution you'd like**
I tired to override the getCachedopenAPI methode

https://github.com/springdoc/springdoc-openapi/blob/00744d7b8ab7e02bfa16378e226a07786dea5a1a/springdoc-openapi-common/src/main/java/org/springdoc/core/OpenAPIService.java#L681-L688

But there is no easy solution for that. 

**Describe alternatives you've considered**

I could put my OpenAPI object with every possible Locale into the Map

```
   public OpenAPIServiceConfigurator( OpenAPIService service, OpenAPI openApiLoaded )
   {
      if ( openApiLoaded instanceof OpenAPIWithoutDefaultServerDescription )
      {
         service.setCachedOpenAPI( openApiLoaded, Locale.GERMAN );
         service.setCachedOpenAPI( openApiLoaded, Locale.US );
          ...
         service.setCachedOpenAPI( openApiLoaded, Locale.getDefault() );
      }
   }
```

but that isn't a really clean solution too. 

My other Solution would be to create a own LocaleResolver which would override the Locale if there is api-docs in the URL. 

I hope you get what i tried to describe.

And thank u btw for the great work. :)

**Comment by bnasslahsen** [comment]
@TimmyHil,

It doesn't look to be the right approach.
The straight forward solution is that you define your own implementation of `OpenApiCustomizer`.
Note that you have also `OpenApiLocaleCustomizer`, which can help you customize the `OpenAPI` definition depending on the `Locale`.
