### ISSUE TITLE
@ParameterObject inheritance class problem

### ISSUE THREAD

**Issue by 721806280** [springdoc/springdoc-openapi#1594]
`
@Data
public class Hello {

     @Schema(title = "hello", example = "hello")
     @Parameter(description = "hello", example = "hello")
     private String hello;

}

@Data
@EqualsAndHashCode(callSuper = true)
public class Word extends Hello {

     @Schema(title = "word", example = "word")
     @Parameter(description = "word", example = "word")
     private String word;

}
`

When the parameters of the controller are `@ParameterObject Word word` or `@org.springframework.web.bind.annotation.RequestBody Word word`, is there a simplified way of writing, such as providing only one `@Schema` or `@Parameter`?

org.springframework.web.bind.annotation

**Comment by bnasslahsen** [comment]
@721806280, 

already answered here #1564
