### ISSUE TITLE
Add support for the asyncapi specification

### ISSUE THREAD

**Issue by pauldburton** [springdoc/springdoc-openapi#1598]
**Is your feature request related to a problem? Please describe.**
Taken from [AsyncAPI Specification](https://www.asyncapi.com/docs/specifications/v2.3.0) as they say it better

> The AsyncAPI Specification is a project used to describe and document message-driven APIs in a machine-readable format. It’s protocol-agnostic, so you can use it for APIs that work over any protocol (e.g., AMQP, MQTT, WebSockets, Kafka, STOMP, HTTP, Mercure, etc). 

**Describe the solution you'd like**
As Spring supports multiple message-driven systems Like AMQP, WebSockets, and Kafka to name a few, it would be nice if the AsyncApi specification can be used in parallel to the OpenAPI for documenting these systems.

**Describe alternatives you've considered**
There is an existing library called [springwolf](https://github.com/springwolf/springwolf-core).  Their support is limited to Kafka and AMQP.  I will most likely use this library, but as we are already pulling in springdoc-openapi it would be nice to consolidate.

**Additional context**
I understand that this project is specifically for the OpenApi, but the entire feature is called SpringDoc so I felt like it would be reasonable to assume this is a valid request here.

**Comment by bnasslahsen** [comment]
@pauldburton, 

See answer here #1515

**Comment by pauldburton** [comment]
I apologize, I should have searched for it.  Thank you for directing me to that issue.
