### ISSUE TITLE
Illegal reflective access operation warning at startup of the application

### ISSUE THREAD

**Issue by Celludriel** [springdoc/springdoc-openapi#1599]
**Describe the bug**
We upgraded to Spring Boot 2.6.6 as to fix a security issue and while doing that upgraded from springdoc-openapi 1.6.5 to 1.6.6.  Afterwards when we start the application, we ended up with following warning

```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by nonapi.io.github.classgraph.classpath.CallStackReader (file:/C:/maven/repo/io/github/classgraph/classgraph/4.8.138/classgraph-4.8.138.jar) to method java.lang.SecurityManager.getClassContext()
WARNING: Please consider reporting this to the maintainers of nonapi.io.github.classgraph.classpath.CallStackReader
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
```

Currently our workaround is upgrading classgraph from 4.8.138 to 4.8.143 and this seems to solve the issue the warning is gone

**To Reproduce**
- What version of spring-boot you are using? 2.6.6
- What modules and versions of springdoc-openapi are you using? 1.6.6
- What is the actual and the expected result using OpenAPI Description (yml or json)? json

**Expected behavior**
When the spring application starts we should not get a warning about illegal use of code

**Screenshots**
![MicrosoftTeams-image (4)](https://user-images.githubusercontent.com/5664766/162147616-a9556305-a481-4c31-94aa-16c5700b0141.png)

![MicrosoftTeams-image (3)](https://user-images.githubusercontent.com/5664766/162147659-fe720edc-09ce-4fa5-9d8d-1575b8876fed.png)

**Comment by bnasslahsen** [comment]
see this commit 9368d363a0b6c2ff1866b239c4240e4b13207948
