### ISSUE TITLE
Support hiding of Schema and Example Value

### ISSUE THREAD

**Issue by membersound** [springdoc/springdoc-openapi#16]
If my webservice returns objects like `ResponseEntity, JsonObject, Object` or whatever, it would be nice if the "Example Value" and "Schema" node in the generated json specs could be hidden.

For schema, there is property
`@Operation(responses = @ApiResponse(content = @Content(schema = @Schema(hidden = true)))`.
Maybe you could evaluate it and hide it for the specific endpoint?

For example `ExampleObject` I have no suggestion how to derive the hiding.

**Comment by springdoc** [comment]
It is not clear.
Maybe you can add an example including: The sample documentation using OpenAPI annotations et the expected result in OpenAPI Format.

**Comment by membersound** [comment]
It would be nice if the following code would hide the `schema` node entirely:

```
@RestController
public class PersonServlet {
	@GetMapping(value = "/persons")
	@Operation(responses = @ApiResponse(responseCode = "200", content = @Content(schema = @Schema(hidden = true))))
	public JSONObject persons() {
		return new JSONObject();
	}
}
```
{
   "openapi":"3.0.1",
   "info":{
      "title":"OpenAPI definition",
      "version":"v0"
   },
   "paths":{
      "/persons":{
         "get":{
            "operationId":"persons",
            "responses":{
               "200":{
                  "description":"default response",
                  "content":{
                     "*/*":{
                        "schema":{
                           "type":"string"
                        }
                     }
                  }
               }
            }
         }
      }
   },
   "components":{

   }
}
```

**Comment by springdoc** [comment]
Hi , 

This feature will be part of 1.1.15 release.
It will be possible to hide the response element, using eh @Schema annotation, as follows, at operational level::

`@Operation(responses = @ApiResponse(responseCode = "200", content = @Content(schema = @Schema(hidden = true))))`

Or directly at ApiResponses level:

`@ApiResponses(value = {@ApiResponse(responseCode = "200", content = @Content(schema = @Schema(hidden = true))) })`
