### ISSUE TITLE
It is not possible to download yaml representation for specific api group

### ISSUE THREAD

**Issue by martinsefcik** [springdoc/springdoc-openapi#1600]
**Describe the bug**
- It is not possible to download yaml open api representation per specific api group by providing path: `<server>/v3/api-docs/<group_name>.yaml`
- Instead of getting yaml definition I'm getting the following exception `org.springdoc.api.OpenApiResourceNotFoundException: No OpenAPI resource found for group: <group_name>.yaml`

**To Reproduce**
- create open api group with name `group`
- try to download yaml representation for specific group with the following url: `<server>/v3/api-docs/group.yaml`

**Expected behavior**
- I would expect that url `<server>/v3/api-docs/group.yaml` would return yaml representation for given group the same way as the following url: `<server>/v3/api-docs/group` is returning json representation

**Comment by bnasslahsen** [comment]
Yes it is possible and this is the url:

- http://server:port/context-path/v3/api-docs.yaml/groupName

**Comment by martinsefcik** [comment]
Thank you

--
Martin Šefčík


št 7. 4. 2022 o 13:11 bnasslahsen ***@***.***> napísal(a):

**Comment by ErwanLeroux** [comment]
@bnasslahsen It would be helpful to mention that in the following documentation :

>  Documentation can be available in yaml format as well, on the following path : /v3/api-docs.yaml (https://springdoc.org/#getting-started)

With the exemple from documentation I thought that the correct way was to add .yaml at the end of the url, like this http://server:port/context-path/v3/api-docs/groupName.yaml

**Comment by bnasslahsen** [comment]
The documentation examples you are referencing is the default yaml endpoint. (without any group)
