### ISSUE TITLE
Release 2.0.0-M1 unavailable on Maven Central

### ISSUE THREAD

**Issue by jycr** [springdoc/springdoc-openapi#1601]
**Describe the bug**
[Release 2.0.0-M1](https://github.com/springdoc/springdoc-openapi/releases/tag/v2.0.0-M1) currently not available on [Maven Central](https://search.maven.org/artifact/org.springdoc/springdoc-openapi-ui) (current last available version: [1.6.6](https://search.maven.org/artifact/org.springdoc/springdoc-openapi-ui/1.6.6/jar))

**Comment by bnasslahsen** [comment]
@jycr, 

you are using wrong url: https://mvnrepository.com/artifact/org.springdoc/springdoc-openapi-starter-webmvc-ui
Modules will be renamed for 2.x

see this ticket for more details: 
https://github.com/springdoc/springdoc-openapi/issues/1284
