### ISSUE TITLE
1.6.7 not available in Maven Central

### ISSUE THREAD

**Issue by lrozenblyum** [springdoc/springdoc-openapi#1602]
E.g. see 
https://search.maven.org/search?q=g:org.springdoc
https://search.maven.org/search?q=g:org.springdoc%20AND%20a:springdoc-openapi-ui

**Comment by bnasslahsen** [comment]
@lrozenblyum, 

Jars are deployed since yesterday. https://repo.maven.apache.org/maven2/org/springdoc/springdoc-openapi-ui/1.6.7/springdoc-openapi-ui-1.6.7.jar

The indexation using search.maven.org might take time...

**Comment by lrozenblyum** [comment]
Thanks for pointing this out @bnasslahsen, it's truly resolved fine by local Maven.
