### ISSUE TITLE
Processing done over getter and should be over setter

### ISSUE THREAD

**Issue by boskokg** [springdoc/springdoc-openapi#1606]
**Describe the bug**
Having the String parameter with **String setter** and **Integer getter** is processed by springdoc-openapi as **Integer**.

**To Reproduce**
- What version of spring-boot you are using? spring-boot-starter-parent 2.6.6
- What modules and versions of springdoc-openapi are you using? springdoc-openapi-webmvc-core 1.6.7
- What is the actual and the expected result using OpenAPI Description (yml or json)?
- Provide with a sample code (HelloController) or Test that reproduces the problem

**Expected behavior**
I think the problem desription is crear. If needed I can provide details.

**Screenshots**
I think the problem desription is crear. If needed I can provide details.

**Additional context**
I do not understant why proccessing the code is done over getter. In my opinion, getter is used for the internal logic proccessing by Controllers and setter is important for mapping request data to object parameter.

**Comment by bnasslahsen** [comment]
@boskokg, 

Thank you for your comments.
The processing will stay as it is.

If you feel you have a better proposal, feel free to propose directly a PR.
