### ISSUE TITLE
More options for sorting tags than Alpha

### ISSUE THREAD

**Issue by rhanton** [springdoc/springdoc-openapi#1608]
**Is your feature request related to a problem? Please describe.**
I'd like the ability to sort tags based on more than alphanumeric (A to Z) names.  I'd love to have my tags logically ordered per order of operations for a client or user on the swagger-ui.

**Describe the solution you'd like**
Ideally we'd have another parameter on each `@Tag` that could be used for sorting if-provided like a "sort" param. Alternatively having more options than alpha for sorting may be helpful, like reverse alpha or something that allows providing an ordered list of tags to determine the ordering.

**Describe alternatives you've considered**
Simplest idea I found on StackOverflow that works is to add a number in front of each tag name (like "1. ", "2. ", "3. ",...) and then turn on alpha-sorting. This works, but seems like a hack.
![Screen Shot 2022-04-11 at 12 14 51 PM](https://user-images.githubusercontent.com/26878180/162813020-53d45a9a-3aa5-4f5c-8cfa-232d15150a30.png)

**Additional context**
N/A

**Comment by bnasslahsen** [comment]
@rhanton,

For that use `OpenApiCustomizer` to add any options you want.

**Comment by AtanasVYordanov** [comment]
OpenApiCustomizer doesn't appear to be affecting the output of the OpenAPI json and yaml spec files but only the Swagger UI. Is there a way to configure the sorting of the tags that are output in these files?
