### ISSUE TITLE
Customizer for all OpenAPI descriptions ("default" and GroupedOpenApi)

### ISSUE THREAD

**Issue by christophejan** [springdoc/springdoc-openapi#1609]
**Is your feature request related to a problem? Please describe.**

Currently, OpenApiCustomiser & OperationCustomizer beans are take in account only for the "default" OpenAPI description. When GroupedOpenApi are declared to just obtain a subset of the described operations, customizer beans are ignored and so the result is inconsistent.

When GroupedOpenApi are declared programmatically, it's possible to manually retrieve the customizer beans and apply them, but I think this Springdoc could make it easier.

When GroupedOpenApi are declared through spring properties, this is especially uncomfortable as I see no way to apply customizer on them.

I think the main usage for GroupedOpenApi is to build an OpenAPI description on a subset of available operations (i.e. a filtered view), and the current behavior on customizer don't seems to ease such use cases.

**Describe the solution you'd like**

I would like a way to specify customizers applied to all OpenAPI descriptions ("default" and GroupedOpenApi) (i.e. global).

This can be achieved by many ways :
1. Either by applying OpenApiCustomiser & OperationCustomizer beans on GroupedOpenApi ; but this could have quite strong impacts on existing applications
1. Or by introducing GlobalOpenApiCustomiser & GlobalOperationCustomizer interfaces
1. Or by introducing and using a GroupedOpenApiBuilder bean that can be either overridden by applications (@ConditionalOnMissingBean) or customized by providing bean(s) implementing some interface

Etc...

**Additional context**

Springdoc 1.6.7 - Kotlin webflux

**Comment by bnasslahsen** [comment]
@christophejan; 

Groups and Global OpenAPI definitions are different.
You can define a single `OpenApiCustomiser` Bean which will be used by the Gloabl OpenAPI Bean. 
And for the `GroupedOpenApi` reference this `OpenApiCustomiser` using `addOpenApiCustomizer`.

**Comment by christophejan** [comment]
@bnasslahsen, you have just described the behavior I've already given.

This was a feature request to improve current behavior ; I was expecting a path to improve springdoc handling of use case as simple as : some operations need customization whatever the requested OpenAPI description (default one or group).

I will try to rephrase the points to improve :
1. By default, /v3/api-doc/mygroup is inconsistent with /v3/api-docs for operations customized through OperationCustomizer
1. GroupedOpenApi declared through spring properties (yml) should be customizable
1. Make easier to apply all customizer beans on GroupedOpenApi declared programmatically

Regards

**Comment by bnasslahsen** [comment]
@christophejan, 

These are my answers for your comments:

1. By default, /v3/api-doc/mygroup is inconsistent with /v3/api-docs for operations customized through OperationCustomizer
**-> This is not inconsistent. From the moment you do not attach an operation customizer to group, it will not be applied.
  if you need to attach it, you have `addOperationCustomizer` available.**

1. GroupedOpenApi declared through spring properties (yml) should be customizable
**-> This the case, for that use: `springdoc.group-configs` properties**

1. Make easier to apply all customizer beans on `GroupedOpenApi` declared programmatically
**-> It's already so easy, you have `addOperationCustomizer` and `addOpenApiCustomizer` for the `GroupedOpenApi`. Not sure you will get easier...**

The last thing, is if you believe there you are able to propose better solutions, feel free to propose a PR.
