### ISSUE TITLE
add @NotEmpty @NotBlank @PositiveOrZero @NegativeOrZero support

### ISSUE THREAD

**Issue by JaynLau** [springdoc/springdoc-openapi#161]
add `@NotEmpty` `@NotBlank` support for `required`.
add `@PositiveOrZero` support for `minimum value 0`.
add `@NegativeOrZero` support for `maximum value 0`.

**Comment by springdoc** [comment]
Hi,

This enhancement, will be part of next release v1.2.8, of springdoc-openapi.
