### ISSUE TITLE
UI: collapse "Responses" section

### ISSUE THREAD

**Issue by 2019-05-10** [springdoc/springdoc-openapi#1610]
**Is your feature request related to a problem? Please describe.**
The REST API I am using has a large number of endpoints and each endpoint again a rather large number of possible responses, hence the "Responses" section at every endpoint is very long,  about 2/3 of the whole page consists of "Responses", and thus navigation requires constant scrolling.

**Describe the solution you'd like**
Make "Responses" section collapsible and add config setting to keep collapsed initially

**Comment by bnasslahsen** [comment]
@2019-05-10, 

This is not clear. By default all the sections are collapsed.
In addition this kind of features should be asked to the swagger-ui project instead.
