### ISSUE TITLE
Getter method conflicting with field name

### ISSUE THREAD

**Issue by lbenedetto** [springdoc/springdoc-openapi#1611]
**Describe the bug**
Getter and field of different type but same name are considered to be the same property. Hiding the getter hides the field as well.

**To Reproduce**
- What version of spring-boot you are using? 2.6.6
- What modules and versions of springdoc-openapi are you using? 1.6.7
- What is the actual and the expected result using OpenAPI Description (json)?
- Actual: (for the request body)
```
{
  "openapi": "3.0.1",
  "info": {...},
  "servers": [...],
  "paths": {...},
  "components": {
    "schemas": {
      "BrokenDocumentation": {
        "type": "object",
        "properties": {
          "things": {
            "title": "Thing",
            "uniqueItems": true,
            "type": "array",
            "items": {
              "$ref": "#/components/schemas/MappedThing"
            }
          }
        }
      },
      "MappedThing": {
        "title": "Thing",
        "type": "object"
      }
    }
  }
}


```
- Expected (Achieved by renaming the getter and adding `@Hidden`)
```
{
  "openapi": "3.0.1",
  "info": {...},
  "servers": [...],
  "paths": {...},
  "components": {
    "schemas": {
      "BrokenDocumentation": {
        "type": "object",
        "properties": {
          "things": {
            "type": "array",
            "writeOnly": true,
            "items": {
              "$ref": "#/components/schemas/Thing"
            }
          }
        }
      },
      "Thing": {
        "type": "object",
        "properties": {
          "a": {
            "title": "Thing a",
            "type": "string"
          }
        }
      }
    }
  }
}

```
- Provide with a sample code (HelloController) or Test that reproduces the problem
```
@Schema
public class BrokenDocumentation {

  @Schema(title = "Thing")
  private List<Thing> things;

  public BrokenDocumentation() {}

  public Set<MappedThing> getThings() {
    return null;
  }
}
```
The issue only occurs if the getter is named such that it matches the naming of the field.
If I rename it stop conflicting with the field, and if I also `@Hidden` it then it fully matches the expected output.
But if I only hide the getter without renaming it, then the schema json becomes
```
      "BrokenDocumentation": {
        "type": "object"
      }
```

I think that I should be able to name my Hidden internal use only getters whatever I want without them messing up my documentation.

Ideally, I'd like to be able to ignore all methods by default, and only include them in documentation if I mark them with `@Schema`

**Comment by bnasslahsen** [comment]
@lbenedetto, 

This is the expected behavior.
