### ISSUE TITLE
请问是否可以对UI进行优化？

### ISSUE THREAD

**Issue by shift-alt-ctrl** [springdoc/springdoc-openapi#1613]
Springdoc是一个非常优秀的组件，我们的团队都很喜欢，不过默认的UI或许不够美观，而且自定义UI也非常的困难，这或许是swagger官方的遗憾。
我们期待springdoc团队能够提供一个更漂亮的UI界面，它能够像POSTMAN那样美观、而且体验更佳。
谢谢！Good Luck！

**Comment by linghengqian** [comment]
- You shouldn't be asking this question here, it's not about `SpringDoc`. Swagger UI is the Swagger of standard page, if you want to improve the page, you should go to https://github.com/swagger-api/swagger-ui for help. 

- Second, through reverse proxy, you can proxy OpenAPI YAML files to third-party components like `ReDoc`.
 
- Third, I think few people in this community know Chinese, so you should translate the title and content.
