### ISSUE TITLE
Add more flexibility to exploding method parameters

### ISSUE THREAD

**Issue by alexmach** [springdoc/springdoc-openapi#1614]
If a spring application takes advantage of the `ModelAttributeMethodProcessor` from `ModelAndViewResolverMethodReturnValueHandler.modelAttributeProcessor`  they are still [required to add `ParameterObject` ](https://github.com/springdoc/springdoc-openapi/blob/master/springdoc-openapi-common/src/main/java/org/springdoc/core/DelegatingMethodParameter.java#L118) annotation to either the class or to the parameter. 

I would like to see the conditional for determining if the `paramClass` should be run through the `MethodParameterPojoExtractor.extractFrom` method be run from a provider that will allow many different checks where at the first condition of true it proceeds to extract the parameters.

Additional information about the projects I have been using this in.
I have been working with springdoc-openapi:1.6.6 and spring:5.13.7 and spring-boot:2.6.4

**Comment by bnasslahsen** [comment]
@alexmach, 

Feel free to propose a PR for this enhancement and reference this ticket.
