### ISSUE TITLE
File upload not working v1.6.7

### ISSUE THREAD

**Issue by devdevx** [springdoc/springdoc-openapi#1615]
**Describe the bug**
- An endpoint with `MultipartFile` is documented correctly but when I try to upload the file then nothing happens.

**To Reproduce**
- Create an empty Spring Boot project with web dependency
- Add the springdoc-openapi-ui library with version 1.6.7
- Add a `MultipartFile`endpoint:
```
@PostMapping("/data")
public void import(MultipartFile file) throws IOException {
// Empty
}
```

**Expected behavior**
- When I execute the call (click the button) the file is uploaded

**Currentbehavior**
- When I execute the call (click the button) nothing happens (no errors in web console nor calls to the backend)

**Screenshots**
![image](https://user-images.githubusercontent.com/36246454/163787060-79ada238-5d91-4e3a-b627-57abd2401cc9.png)
![image](https://user-images.githubusercontent.com/36246454/163787887-6c9f3ee1-b02c-45b1-9a39-39dd241f6b88.png)
![image](https://user-images.githubusercontent.com/36246454/163787916-72f34088-5217-4af5-be3b-bcc49fcbbe14.png)

**Comment by bnasslahsen** [comment]
@devdevx, 

If you are trying to report a swagger-ui issue, use the swagger-ui repo instead.
This is a sample working code

```java
import io.swagger.v3.oas.annotations.parameters.RequestBody;

import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RestController;
import org.springframework.web.multipart.MultipartFile;

@RestController
public class HelloController {


	@PostMapping(value = "/test", consumes = MediaType.APPLICATION_OCTET_STREAM_VALUE )
	public ResponseEntity<Void> saveDocu2ment(@RequestBody final MultipartFile file) {
		return null;
	}
}
```

**Comment by Easy0Fame** [comment]
> If you are trying to report a swagger-ui issue, use the swagger-ui repo instead. This is a sample working code that you can adapt.
> 
> ```java
> import io.swagger.v3.oas.annotations.parameters.RequestBody;
> 
> import org.springframework.http.MediaType;
> import org.springframework.http.ResponseEntity;
> import org.springframework.web.bind.annotation.PostMapping;
> import org.springframework.web.bind.annotation.RestController;
> import org.springframework.web.multipart.MultipartFile;
> 
> @RestController
> public class HelloController {
> 
> 
> 	@PostMapping(value = "/test", consumes = MediaType.APPLICATION_OCTET_STREAM_VALUE )
> 	public ResponseEntity<Void> saveDocu2ment(@RequestBody final MultipartFile file) {
> 		return null;
> 	}
> }
> ```

Same bug happens with v1.6.8. Have to both assign 'consumes' attribute of @PostMapping and add @io.swagger.v3.oas.annotations.parameters.RequestBody before the method param MultipartFile to get the execute button work. Not sure if it is a swagger-ui issue.
