### ISSUE TITLE
springdoc-openapi-webflux-ui v1.6.7 + spring actuator + spring cloud crashes at startup

### ISSUE THREAD

**Issue by 3mtee** [springdoc/springdoc-openapi#1617]
**Describe the bug**
If your java/kotlin application uses a combination of springdoc-openapi-webflux-ui v1.6.7 + spring actuator + spring cloud stream - it crashes on startup with the message:
```
***************************
APPLICATION FAILED TO START
***************************

Description:

Parameter 0 of method webConversionServiceProvider in org.springdoc.core.SpringDocConfiguration$WebConversionServiceConfiguration required a single bean, but 2 were found:
	- webFluxConversionService: defined by method 'webFluxConversionService' in class path resource [org/springframework/boot/autoconfigure/web/reactive/WebFluxAutoConfiguration$EnableWebFluxConfiguration.class]
	- integrationConversionService: defined in null
```

**To Reproduce**
1. Create a new spring boot application at the [spring initializr](https://start.spring.io/). Add the following dependencies:
    - "Spring Boot Actuator"
   - "Cloud Stream"
   - "Spring Reactive Web"
2. Programming language doesn't matter (I reproduced the bug with Java and Kotlin).
3. Download and unpack the archive.
4. Add the swagger into `build.gradle`: 
  ```gradle
implementation("org.springdoc:springdoc-openapi-webflux-ui:1.6.7")
```
5. Run the app

**My `build.gradle`**:
```
plugins {
    id 'org.springframework.boot' version '2.6.6'
    id 'io.spring.dependency-management' version '1.0.11.RELEASE'
    id 'java'
}

group = 'com.example'
version = '0.0.1-SNAPSHOT'
sourceCompatibility = '17'

repositories {
    mavenCentral()
}

ext {
    set('springCloudVersion', "2021.0.1")
}

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-actuator'
    implementation 'org.springframework.boot:spring-boot-starter-webflux'
    implementation 'org.springframework.cloud:spring-cloud-stream'
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testImplementation 'io.projectreactor:reactor-test'

    implementation("org.springdoc:springdoc-openapi-webflux-ui:1.6.7")
}

dependencyManagement {
    imports {
        mavenBom "org.springframework.cloud:spring-cloud-dependencies:${springCloudVersion}"
    }
}
```

**Expected behavior**
Web app shouldn't crash

**Screenshots**
none

**Additional context**
Versions:
- Spring-boot 2.6.6
- springdoc-openapi-webflux-ui v1.6.7

Any of the following actions fix the problem:
1. change the `springdoc-openapi-webflux-ui` to v1.6.6
2. remove the `spring-boot-starter-actuator` dependency
3. remove the `spring-cloud-stream` dependency

**Comment by mshima** [comment]
This is probably the same problem https://github.com/springdoc/springdoc-openapi/issues/1607.
And is preventing us to migrate to v1.6.7 https://github.com/jhipster/jhipster-bom/pull/744

We have many webflux samples. Only 1 is failing.
Seems a specific scenario.

**Comment by bnasslahsen** [comment]
Thank you @3mtee for the reproducible steps!

@mshima i confirm it's specific to the case when `spring-cloud-stream` is included.
Should be fixed with the next release.

**Comment by mshima** [comment]
Thanks @bnasslahsen

**Comment by jongidal** [comment]
I had a same situation.

**Comment by bnasslahsen** [comment]
@jongidal,

Use `v1.6.8`
