### ISSUE TITLE
Annotation @ParameterObject doesn't work with objects from class Sort

### ISSUE THREAD

**Issue by NikolayDoronkin** [springdoc/springdoc-openapi#1618]
The annotation **@ParameterObject** correctly works with class **Pageable**, but doesn't work with class **Sort**.

Expected Results:
An object from class **Sort** are able to get data about sorting type.

Actual Results:
An object from class **Sort** doesn't get any data from request.

**Comment by bnasslahsen** [comment]
@NikolayDoronkin, 

Already answered here https://github.com/springdoc/springdoc-openapi/issues/1186
