### ISSUE TITLE
Some context problems

### ISSUE THREAD

**Issue by basven** [springdoc/springdoc-openapi#1619]
I just recently migrated from springfox to springdoc 1.6.7 and having some issues with the context path.  This is all running in spring-boot 2.6.6

api-docs: /real-context/v3/api-docs and loads
swagger-config: /real-context/v3/api-docs/swagger-config.  However when you open that I see the following:
configUrl: "/war-name/v3/api-docs/swagger-config
url: /war-name/v3/api-docs
swagger-ui: /real-context/swagger-ui/index.html.  Loads but gives me a 'failed to load remote configuration' and the attempted request is going to /war-name/v3/api-docs/swagger-config
When going to /real-context/swagger-ui.html I get a 404.

Since it could load/find the context I defined springdoc.swagger-ui=/realcontext/v3/api-docs/swagger-config.  Now I see the following behavior:
api-docs: /real-context/v3/api-docs and loads
swagger-config: /real-context/v3/api-docs/swagger-config.  However when you open that I see the following:
configUrl: "/war-name/v3/api-docs/swagger-config
url: /war-name/v3/api-docs/
swagger-ui: /real-context/swagger-ui/index.html.  However I get a "No API definition provided" error.  When I then type in "/real-context/v3/api-docs the paths and tags all load but executing any of the requests are going to /war-name/path_to_rest_endpoints and the generated server is showing as /war-name/path_to_rest_endpoint.
When going to /real-context/swagger-ui.html it gets redirected to /war-name/swagger-ui/index.html and gives me a 503

Below the behavior when I downgraded to springdoc 1.5.13:

With no additional swagger or springdoc properties configured (although I tried setting the server.servlet.contextPath) I see the following:
api-docs: /real-context/v3/api-docs
swagger-config: /real-context/v3/api-docs/swagger-config.  However when you open that I see the following:
configUrl: "/war-name/v3/api-docs/swagger-config
url: /war-name/v3/api-docs
swagger-ui: /real-context/swagger-ui/index.html.  However I get a "No API definition provided" error.  When I then type in "/real-context/v3/api-docs the paths and tags all load but executing any of the requests are going to /war-name/path_to_rest_endpoints and the generated server is showing as /war-name/path_to_rest_endpoint.
When going to /real-context/swagger-ui.html it gets redirected to /war-name/swagger-ui/index.html?configUrl=/war-name/v3/api-docs/swagger-config
I tried setting the springdoc.swagger-ui.config-url and springdoc.api-docs.path properties but to no avail.
Do you have any suggestions?  

PS: I did have similar problems using springfox but was able to work around it by providing my own PathProvider which would set the incorrect 'war-name' context to the real one and by implementing my own JsonSerializer to an empty basePath.

**Comment by bnasslahsen** [comment]
@basven, 

At least, please try to use the GITHUB formatting while writing ...

If you are reporting any issue, please help to speed up problem diagnosis by providing as much information as possible:
Provide a [Minimal, Reproducible Example - with HelloController](https://stackoverflow.com/help/minimal-reproducible-example)[](https://github.com/springdoc/springdoc-openapi/blob/b7380a6d3b6afafc19bc96abbd43e33d760740d8/CONTRIBUTING.adoc#reporting-security-vulnerabilities) that reproduces the problem.

This ticket will be closed and can be reopened if any relevant information is provided.
