### ISSUE TITLE
ParameterCustomizer is invoked also for @RequestBody

### ISSUE THREAD

**Issue by yashkolte3** [springdoc/springdoc-openapi#1622]
`org.springdoc.core.customizers.ParameterCustomizer.customize(Parameter, MethodParameter)` is invoked also for `@RequestBody`, however the supplied argument `Parameter parameterModel` is null always in such cases.

What is the desired behavior ? 

The same plugin must be used also for `@RequestBody` or `@PathVariable` ? If yes, how do you then customize the `io.swagger.v3.oas.models.Operation.requestBody` ?

The use-case here is to update the `description` of the request body dynamically.

**Comment by bnasslahsen** [comment]
@yashkolte3, 

use `OperationCustomizer`
