### ISSUE TITLE
1.6.7 results in a 500 response opening api/v3/api-docs

### ISSUE THREAD

**Issue by berniPLN** [springdoc/springdoc-openapi#1623]
Moving from 1.6.6 to 1.6.7 and opening api/swagger-ui/index.html resulting in an 500 error response on opening api/v3/api-docs

Trace:
2022-04-20 11:49:13.023 ERROR 26482 --- [4-8080-exec-195] d.p.l.exception.GlobalExceptionHandler   : GET::/xxx/api/v3/api-docs from 10.153.7.76 failed unhandled:

org.springframework.web.util.NestedServletException: Handler dispatch failed; nested exception is java.lang.NoClassDefFoundError: io/swagger/v3/oas/annotations/media/PatternProperties
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1082) ~[spring-webmvc-5.3.18.jar:5.3.18]
[...]
        at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]
Caused by: java.lang.NoClassDefFoundError: io/swagger/v3/oas/annotations/media/PatternProperties
        at io.swagger.v3.core.jackson.ModelResolver.resolvePatternProperties(ModelResolver.java:1552) ~[swagger-core-2.2.0.jar:2.2.0]
        at io.swagger.v3.core.jackson.ModelResolver.resolve(ModelResolver.java:767) ~[swagger-core-2.2.0.jar:2.2.0]
        at org.springdoc.core.converters.PageableOpenAPIConverter.resolve(PageableOpenAPIConverter.java:75) ~[springdoc-openapi-common-1.6.7.jar:1.6.7]
[...]

Just switching back to 1.6.6 everything running fine.

Just tried to see what changed between 1.6.6 and 1.6.7 but did not get a hint, what might be wrong.

**Comment by bnasslahsen** [comment]
@berniPLN, 

Try Providing a [Minimal, Reproducible Example - with HelloController](https://stackoverflow.com/help/minimal-reproducible-example)[](https://github.com/springdoc/springdoc-openapi/blob/722b793da7b473862cbd7ca19a716fb846fc25cd/CONTRIBUTING.adoc#reporting-security-vulnerabilities) that reproduces the problem.

This ticket will be closed, and can be reopened if the relevant information are provided.

**Comment by gabac** [comment]
We have the same issue in our code base. Trying to get a reproducible sample running

**Comment by gabac** [comment]
There seems to be a version issue?

While trying to map `PatternProperties` we get the ClassNotFoundException
<img width="985" alt="image" src="https://user-images.githubusercontent.com/50061/164614630-de7d32c2-921d-4f36-a8fa-f1f2e12d2ce4.png">
Checking the imports shows:
<img width="512" alt="image" src="https://user-images.githubusercontent.com/50061/164614656-f96aabcb-dfd6-4b60-8f48-db974de083fb.png">
That the class does not exists at the desired package
<img width="688" alt="image" src="https://user-images.githubusercontent.com/50061/164614684-53766c51-5ac0-44a6-b9e3-50cf69966315.png">
Swagger Core / Annotation versions
<img width="703" alt="image" src="https://user-images.githubusercontent.com/50061/164614526-af6c04eb-a950-4a8b-bb4a-597ebe610448.png">

Hope this helps?

**Comment by berniPLN** [comment]
Thanks you for your code. In our code we are NOT using the PatternProperties class.
Anyway we are getting the NoClassDefFound Exception on PatternProperties.class during runtime on using 1.6.7.

The version conflict seems to be evident:

our swagger-annotations are on version 2.1.10, while swagger-core and swagger-models are on 2.2.0
wer are using spring-boot-starter-parent 2.6.6

**Comment by berniPLN** [comment]
I am trying to force with explicit import via pom:
		<dependency>
			<groupId>io.swagger.core.v3</groupId>
			<artifactId>swagger-annotations</artifactId>
			<version>2.2.0</version>
		</dependency>

resulting in a working backend.
The dependency analyzer shows that a complete different package are still uinsg 2.1.10 resulting in a maven conflict.
So have to wait until that

**Comment by bnasslahsen** [comment]
Note: In your dependencies, you should only declare `springdoc-openapi` relevant dependency,
You should never declare yourself `swagger-core` or `swagger-annotations` dependencies: springdoc starter is responsible of shipping all time the correct versions that are compatible.

**Comment by berniPLN** [comment]
Sure, you a right, I will stay on 1.6.6 until the conflicting other package updates its dependencies on swagger-annotation to 2.2.0 from 2.1.10 will open a bug report there ...
