### ISSUE TITLE
Unable to render this definition

### ISSUE THREAD

**Issue by LawranceFung** [springdoc/springdoc-openapi#1624]
What could be the cause of
Unable to render this definition
The provided definition does not specify a valid version field.
Please indicate a valid Swagger or OpenAPI version field.  Supported version fields are swagger: "2.0" and those that match openapi: 3.0.n (for example, openapi: 3.0.0).  
I followed the instructions to add swagger to my spring project and it's loading the swagger-ui.html without the endpoints documented in localhost:port/context-path/swagger-ui.html

**Comment by LawranceFung** [comment]
It's worked for several similar projects but not this one.  Any known dependencies in the pom that might cause this conflict, or another related conflict?

**Comment by bnasslahsen** [comment]
Remember, contributions to this repository should follow its [contributing guidelines](https://github.com/springdoc/springdoc-openapi/blob/d2e71dc5743196dd64759ec472ad82717e0b6dfe/CONTRIBUTING.adoc) and [code of conduct](https://github.com/springdoc/springdoc-openapi/blob/d2e71dc5743196dd64759ec472ad82717e0b6dfe/CODE_OF_CONDUCT.md)[](https://github.com/LawranceFung)[](https://github.com/).
