### ISSUE TITLE
Allow override Interface tags in Controller

### ISSUE THREAD

**Issue by amb-jarek** [springdoc/springdoc-openapi#1626]
**Is your feature request related to a problem? Please describe.**
In project I'm working on we are using openapi-generator to generate server api interfaces from `api.yaml` (OAS v3). It generates infterfaces and automatically annotate them with tagname=classname (CamelCase) while operations in `api.yaml` have kebab-case tags (company naming convention)
```java
@Generated(value = "org.openapitools.codegen.languages.SpringCodegen")
...
@Tag(name = "SyncByEmail", description = "the SyncByEmail API")                      
public interface SyncByEmailApi {
...
  @Operation(
      tags = {"sync-by-email"},                             
  ...
  )
  ...
  Mono<ResponseEntity<BaseDTO>> createTask(Mono<SyncByEmailTaskRequestDTO> body,
      @Parameter(hidden = true) final ServerWebExchange exchange);
...
}
```

Now, when I implement such interface springdoc will generate two tags with duplicated operations - which is OK, works as expected and is desirable in most cases.
![obraz](https://user-images.githubusercontent.com/38923701/164458661-4232ca8f-81b8-4998-9191-dec6027d39c5.png)
In my case I would like to avoid such situation and have just kebab-case tag. 
I've tried to overrwrite the interface tag in my controller like this:
```java
@Tag(name = "sync-by-email")
public class SyncByEmailController implements SyncByEmailApi {
}
```
but it doesn't work because as i see springdoc merge all tags defined in interface and controller - not overwrite the one defined in interface.
So I was hoping that `@Tags` will do the job and overwrite tags to the only defined in controller like this:
```java
@Tags({@Tag(name = "sync-by-email")})
public class SyncByEmailController implements SyncByEmailApi {
}
```
But it also doesn't work as I expected - it looks tags are also merged.

**Describe the solution you'd like**
One possible solution to this problem would be change `@Tags` handler to overwrite tags - but it will be breaking change and may affect other developers
Second - safe - solution would be new springdoc option like: 
```
springdoc.tagsOverwritePolicy
``` 
with possible values like:
- `merge` (default) - merge tags from interface and controller
- `overwrite` - use tags from `@Tags` defined in controller. If not exists use tags from interface
- `error` - do not allow overwriting tags - maybe somebody need it ;)

Other possible solution would be option to hide particular tags like:
```
springdoc.hideTags: CustomTag1,CustomTag2
``` 
or something like that

**Comment by 7s-jarek** [comment]
@bnasslahsen I've already checked that. It toesnt work in this case.
`org.springdoc:springdoc-openapi-webflux-ui:1.6.7`
