### ISSUE TITLE
When I use @SecurityScheme, the UI shows 'Could not render n, see the console.'

### ISSUE THREAD

**Issue by Jenyow** [springdoc/springdoc-openapi#1631]
**Describe the bug**
1. Add spring security oauth2 dependency, and ignore urls '/swagger-ui/**','/v3/api-docs/**'.
2. Add the Controller annotation 
    ```
    @SecurityScheme(name = "登录", type = SecuritySchemeType.OAUTH2, scheme = "bearer")
    ```
3. The console does not show any exception.  The UI show below
    
![image](https://user-images.githubusercontent.com/7712958/165250880-01cd8713-71d6-456b-8709-f69dd0e1f9ae.png)

4. If remove @SecurityScheme, the 'Could not render n, see the console. ' not show.

**To Reproduce**
- What version of spring-boot you are using?
  * spring boot：2.3.12.RELEASE
  * spring-cloud-starter-oauth2：2.2.5.RELEASE

- What modules and versions of springdoc-openapi are you using?
  * springdoc-openapi-ui：1.6.8
  * springdoc-openapi-security：1.6.8
 
- JDK：1.8

**Comment by bnasslahsen** [comment]
@Jenyow, 

You might be facing an issue related to the [swagger-ui](https://github.com/swagger-api/swagger-ui/).
If you see a JS error, in the console, of the developer tools tab of your browser.
Try updating this ticket.
