### ISSUE TITLE
Problem with unpacking object param

### ISSUE THREAD

**Issue by BartoszCoyote** [springdoc/springdoc-openapi#1632]
Hello, i have problem with unpacking object param.

I have controller with method getSmth

`getSmth(
            @ParameterObject @Valid final FilterRequest filterRequest) {`

and my filterRequest holds several fields params like 

`    @Parameter(description = "identifier (possible only for ADMIN role)")
    private String id;`

and it works well.

 but I came across one problem with unwanted unpacking object param.

`    @Parameter(description = "refundDateFrom", hidden = true)
    private PointInTime refundDateFrom;`

PointInTime has to fields DateTimeFormatter and ZonedDateTime.

and it and it ends up extracting the object and putting it into swagger ui.

![image](https://user-images.githubusercontent.com/4238723/165308253-2def6151-1ce6-42bc-ae5e-d59710b8cd56.png)

How can I lock the unwrapping of this object and display it as a single string field or just simply hide it from swagger?

**Comment by bnasslahsen** [comment]
@BartoszCoyote, 

If you to consider `DateTimeFormatter` as simpleType so that `springdoc-openapi`can parse the `@Parameter` annotations, without introspecting the related fields.

```java
	static {
		SpringDocUtils.getConfig().addSimpleTypesForParameterObject(DateTimeFormatter.class);
	}
```
