### ISSUE TITLE
GroupedOpenApi.builder addOpenApiCustomiser execution order is reversed

### ISSUE THREAD

**Issue by FelixStumvoll** [springdoc/springdoc-openapi#1633]
Since 1.6.8 when using `GroupedOpenApi.builder().addOpenApiCustomiser()` multiple times, the customizers are executed in reverse compared to the previous version. 
E.g. if i add customizer `A` and then customizer `B` i expect that `A` is executed first. However in 1.6.8 the order is reversed and `B` is called first.

I'm not sure if this is intended behavior or was introduced on accident.

**Comment by bnasslahsen** [comment]
@FelixStumvoll, 

It was correctly introduced, to handle other cases ...
Maybe, we should preserve this order and accept that `OpenApiCustomiser` list will not be final.

I have made a change that could help handling other cases; without impacting the one you are mentionning. 
Let me know if the [last SNAPSHOT](https://springdoc.org/#how-can-i-use-the-last-springdoc-openapi-snapshot) fixes the issue for you.
