### ISSUE TITLE
When I use @JsonProperty in kotlin. The request body in the generated API is wrong.

### ISSUE THREAD

**Issue by Ador-able** [springdoc/springdoc-openapi#1635]
When I use @JsonProperty in kotlin. The request body in the generated API is wrong.
The same attribute appears repeatedly.

spring-boot:2.5.4
springdoc-openapi-webflux-ui:1.6.8

![image](https://user-images.githubusercontent.com/17660606/165432848-702e1be1-4bc6-4b68-8e49-213321a4ca72.png)
![image](https://user-images.githubusercontent.com/17660606/165433119-65004c21-9413-4b21-9117-d2d7186b6401.png)

It should only be UCID

**Comment by bnasslahsen** [comment]
@Ador-able, 

Read the doc: https://springdoc.org/#kotlin-support
