### ISSUE TITLE
The mediaType of webflux's response cannot be resolved to "application/json"

### ISSUE THREAD

**Issue by Ador-able** [springdoc/springdoc-openapi#1636]
## Description error:

When I use webflux to generate documentation, the content of responseBody is always

```json
"*/*": {
   "schema": {
       "$ref": "#/components/schemas/ResultQueryRes"
    }
}
```

Even if I use @RestController, it still cannot be resolved as

```
"application/json"
```

I can only use

```java
@ApiResponse(description = "Successful Operation", responseCode = "200", content = @Content(mediaType = "application/json", schema = @Schema(implementation = Result.class)))
```

to generate.

But my return result is a generic (Mono<Result<QueryRes>>), doing so will lose the information about QueryRes.

## Environment:

spring boot:2.6.3

springdoc-openapi-webflux-ui:1.6.8

Actual result of OpenAPI:

```json
"responses": {
    "200": {
        "description": "OK",
        "content": {
            "*/*": {
                "schema": {
                    "$ref": "#/components/schemas/ResultQueryRes"
                }
            }
        }
    }
}
```

expected outcome:

```
"responses": {
    "200": {
        "description": "OK",
        "content": {
            "application/json": {
                "schema": {
                    "$ref": "#/components/schemas/ResultQueryRes"
                }
            }
        }
    }
}
```

Below is my Controller:
![image](https://user-images.githubusercontent.com/17660606/165437924-14d585d4-5109-4752-ae03-2f342272c106.png)

I'm not sure if this is a bug, but I want to generate "application/json" correctly, how should I do this

**Comment by bnasslahsen** [comment]
@Ador-able, 

Remember, contributions to this repository should follow its [contributing guidelines](https://github.com/springdoc/springdoc-openapi/blob/6ee577f3ace610769825d5b58a56c6a885d927e2/CONTRIBUTING.adoc) and [code of conduct](https://github.com/springdoc/springdoc-openapi/blob/6ee577f3ace610769825d5b58a56c6a885d927e2/CODE_OF_CONDUCT.md).

Next time: These are some basic guidelines before opening an issue. First of all you need to make sure, you don’t create duplicate issues, and there no question already answered on https://stackoverflow.com/tags/springdoc.


Review your code. 

This is a working code:

```java
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;

import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RestController;

@RestController
public class HelloController {

	@PostMapping(value = "/values/data")
	@ApiResponse(description = "Successful Operation", responseCode = "200", content = @Content(mediaType = "application/json", schema = @Schema(implementation = String.class)))
	String list(String toto) {
		return toto;

	}

}
```

**Comment by Ador-able** [comment]
> @Ador-able,
> 
> Remember, contributions to this repository should follow its [contributing guidelines](https://github.com/springdoc/springdoc-openapi/blob/6ee577f3ace610769825d5b58a56c6a885d927e2/CONTRIBUTING.adoc) and [code of conduct](https://github.com/springdoc/springdoc-openapi/blob/6ee577f3ace610769825d5b58a56c6a885d927e2/CODE_OF_CONDUCT.md).
> 
> Next time: These are some basic guidelines before opening an issue. First of all you need to make sure, you don’t create duplicate issues, and there no question already answered on https://stackoverflow.com/tags/springdoc.
> 
> Review your code.
> 
> This is a working code:
> 
> ```java
> import io.swagger.v3.oas.annotations.media.Content;
> import io.swagger.v3.oas.annotations.media.Schema;
> import io.swagger.v3.oas.annotations.responses.ApiResponse;
> 
> import org.springframework.web.bind.annotation.PostMapping;
> import org.springframework.web.bind.annotation.RestController;
> 
> @RestController
> public class HelloController {
> 
> 	@PostMapping(value = "/values/data")
> 	@ApiResponse(description = "Successful Operation", responseCode = "200", content = @Content(mediaType = "application/json", schema = @Schema(implementation = String.class)))
> 	String list(String toto) {
> 		return toto;
> 
> 	}
> 
> }
> ```

thanks. I will remember. But I still want to know how to generate application/json when using mono or flux. Can this be done?

**Comment by bnasslahsen** [comment]
See the sample working code in the comment above
