### ISSUE TITLE
The configuration of the generated document is invalid

### ISSUE THREAD

**Issue by MZHY08** [springdoc/springdoc-openapi#1637]
**Describe the bug**
I added the following configuration to the code,but it doesn't work
<img width="951" alt="image" src="https://user-images.githubusercontent.com/44521439/165672289-50d50cc0-6a5f-43eb-9463-1f71b899d08b.png">
<img width="346" alt="image" src="https://user-images.githubusercontent.com/44521439/165672454-5194f440-bbee-4562-bcf5-c9f961303631.png">

**To Reproduce**
- What version of spring-boot you are using?
2.6.7
- What modules and versions of springdoc-openapi are you using?
springdoc-openapi-ui:1.6.8

**Expected behavior**
- A clear and concise description of what you expected to happen.
pageable should be in parameters, not request body

**Comment by bnasslahsen** [comment]
@MZHY08, 

Your are using v1.6.8. The config you are showing is useless.

If you are reporting a bug, please help to speed up problem diagnosis by providing as much information as possible:

You need to describe your context (the title of an issue is not enough)

What version of spring-boot you are using?

What modules and versions of springdoc-openapi are you using?

What are the actual and the expected result using OpenAPI Description (yml or json)?

Provide a [Minimal, Reproducible Example - with HelloController](https://stackoverflow.com/help/minimal-reproducible-example) that reproduces the problem
