### ISSUE TITLE
Customising certain types from YAML

### ISSUE THREAD

**Issue by nigelsim** [springdoc/springdoc-openapi#1638]
We use a lot of GeoJSON in our API, via the `org.n52.jackson` `jackson-datatype-jts` library. GeoJSON is a discriminator union data structure, so if I define `Geometry` it could be one of many `Point`, `Polygon`, etc.

The default behaviour for generating the OpenAPI schema from these Java objects pulls out all kinds of internal factories, and unneeded data structures.

Ideally, in the generated client we just map to the appropriate language types (`geojson` library in TS for instance).

But, as an intermediate solution, we'd like to replace the OpenAPI definitions for these types with some hand crafted OpenAPI YAML. Specifically https://app.swaggerhub.com/apis/OlivierMartineau/GeoJSON/1.0.1 in this case.

Can we currently include these definitions in the generated definition? If not, is this a feature you'd consider?

**Comment by bnasslahsen** [comment]
@nigelsim, 

From the moment it's an OpenAPI 3 valid description, it could be included.
IF you are willing to propose a feature, feel free to propose directly a PR.
