### ISSUE TITLE
OperationCustomizer response type is in common with all the  MediaType

### ISSUE THREAD

**Issue by bmaschio** [springdoc/springdoc-openapi#1640]
**Describe the bug**
I am implementing an OperationCustomizer that wants to describe an envelope implemented with a class that implements ResponseBodyAdvice 

```java
@Slf4j
@Configuration
public class ApiDocsOperationCustomizer implements OperationCustomizer {

    @Override
    public Operation customize(Operation operation, HandlerMethod handlerMethod) {


        //TODO aggiungere gestione errori
        //TODO gestire anche gli altri codici es 201 o trovare un modo generico
        //TODO Questo modifica eventuali 200 esistenti

        operation.getResponses().forEach((s, apiResponse) -> {

               if (Integer.parseInt(s) >= 200 && Integer.parseInt(s) < 300) {
                   if (apiResponse.getContent() != null && !apiResponse.getContent().isEmpty()) {
                       if (apiResponse.getContent().get("application/json") != null){
                           MediaType mediaType = apiResponse.getContent().get("application/json");
                           mediaType.schema(customizeSchema(mediaType.getSchema()));
                       }
                   }
               }
        });

        return operation;
    }

    private Schema<?> customizeSchema(Schema<?> objSchema) {

        ModelConverters mc=ModelConverters.getInstance();
        Map<String, Schema> read = mc.read(SuccessResponse.class);
        Schema<?> wrapperSchema = read.get("SuccessResponse");
        return  wrapperSchema.addProperties("body", objSchema);
    }
```

**To Reproduce**

- What version of spring-boot you are using?
```
    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>2.6.6</version>
        <relativePath/> <!-- lookup parent from repository -->
    </parent>
```
- What modules and versions of springdoc-openapi are you using?
```
        <dependency>
            <groupId>org.springdoc</groupId>
            <artifactId>springdoc-openapi-ui</artifactId>
            <version>1.6.6</version>
        </dependency>
```
- What is the actual and the expected result using OpenAPI Description (yml or json)?
   
I would expect only the MediaType ("application/json") would be affected by the change in the documentation

**Screenshots**
I expected this
![image](https://user-images.githubusercontent.com/12083716/165908984-25abeb06-2329-44ee-9612-9cfd22313807.png)

I did not expect this

![image](https://user-images.githubusercontent.com/12083716/165909107-a0abd985-a5b9-453b-941c-9c8977450189.png)

**Additional context**

**Comment by bnasslahsen** [comment]
@bmaschio, 

This is not clear, what your are trying to achieve.

Provide a [Minimal, Reproducible Example - with HelloController](https://stackoverflow.com/help/minimal-reproducible-example) that reproduces the problem.

This ticket will be closed and can be reopened if you prove the relevant information.
