### ISSUE TITLE
SwaggerIndexPageTransformer changes in 1.6.7

### ISSUE THREAD

**Issue by gee4vee** [springdoc/springdoc-openapi#1642]
**Describe the bug**
This is not so much a bug but a question: in 1.6.7, `SwaggerIndexPageTransformer` was changed to look for `swagger-initializer.js` instead of `index.html`. We were relying on this transformer as a parent to make changes to `index.html` in our own transformer. What is the reason behind changing to the js page and what is the correct approach for us to transform `index.html`?

Here is our transform method for reference:

```
	/**
	 * add nonce to inline script block
	 */
	@Override
	public Resource transform(
			final HttpServletRequest request,
			final Resource resource,
			final ResourceTransformerChain transformerChain) throws IOException {
		// first, call parent
		Resource result = parent.transform(request, resource, transformerChain);

		// check if index page
		if (antPathMatcher.match("**/swagger-ui/**/index.html", resource.getURL().toString())) {
			// this casting is OK
			// assuming no change in SwaggerIndexPageTransformer.transform method
			String html = new String(((TransformedResource) result).getByteArray(), StandardCharsets.UTF_8);
			String nonce = (String) request.getAttribute(ResponseCSPFilter.CSP_NONCE_ATTRIBUTE);

			// should have only one inline script block
			// and each nonce should only be used once anyway
			html = html.replaceFirst("<script>", "<script nonce=\"" + nonce + "\">");

			result = new TransformedResource(resource, html.getBytes(StandardCharsets.UTF_8));
		}

		return result;
	}
```

**To Reproduce**
N/A

**Expected behavior**
N/A

**Screenshots**
N/A

**Additional context**
N/A

**Comment by bnasslahsen** [comment]
@gee4vee, 

This related to the `swagger-ui `enhancement to remove inline-code:
- https://github.com/swagger-api/swagger-ui/pull/7905

The logic, to transform the `index.html` is the same to all the static resources of the `swagger-ui`, which is described already documented in the F.A.Q:
- https://springdoc.org/#customizing-swagger-static-resources

**Comment by fanson369** [comment]
Another way,you can find the  swaggerWebMvcConfigurer and add call  swaggerWebMvcConfigurer.addResourceHandlers.
It is prefect for me.
Maybe,it is the best way.
