### ISSUE TITLE
How to add description to body request parameters?

### ISSUE THREAD

**Issue by jsmwoolf** [springdoc/springdoc-openapi#1643]
You can use `@Parameter` to add descriptions and additional information for a query parameter.  However, there doesn't appear to be a straightforward way to do it for request bodies, especially for POST and PUT requests.

Is there a way to do this via annotations or is this a non-supported feature?

**Comment by bnasslahsen** [comment]
@jsmwoolf, 

You can use `@RequestBody(description = "test value")`
For similar questions, see [wagger-annotations documentation](https://github.com/swagger-api/swagger-core/wiki/Swagger-2.X---Annotations).
