### ISSUE TITLE
Inline response objects

### ISSUE THREAD

**Issue by rockxwre** [springdoc/springdoc-openapi#165]
I am not sure if this question belongs here. But I will give it a try anyway.
I am using springdoc-openapi to generate an OAS3 yaml documentation based on my Spring controller/models.
What I want to achieve is to have an inline operation response. Something like this:

```
paths:
  /myoperation:
    get:
      ...
      responses:
        '200':
          content:
            application/json:
              schema:
                required:
                  - count
                  - results
                type: object
                properties:
                  count:
                    type: integer
                  results:
                    type: array
		    ...
```

The annotations of the operation method in the controller class looks like this:

```
@ApiResponse(responseCode = "200",
             description = "OK",
             content = @Content(mediaType = "application/json", schema = @Schema(implementation = MyResponseDTO.class, requiredProperties = { "count", "results"} ))
```

and MyResponseDTO:

```
public class MyResponseDTO {

    @Schema(required = true, description = "")
    private long count;

    @ArraySchema(schema = @Schema(implementation = MyModel.class))
    private List<DTO> results;

    ... getters/setters

}
```

This results in a schema with:

```
...
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MyResponseDTO'

...
components:
    MyResponseDTO:
      required:
      - count
      type: object
      properties:
        count:
          type: integer
          format: int64
        results:
          type: array
          items:
            $ref: '#/components/schemas/MyModel'
```

The response content is a reference instead of an inline object. Is there a way I can annotate the response/schema so that it will appear inline in the documentation?

**Comment by springdoc** [comment]
Hi, 

 We don't have any special feature related to inline object. We just rely on the official libraries.
 You can ask your question, on the official swagger-core github:
- https://github.com/swagger-api/swagger-core/issues

**Comment by rockxwre** [comment]
Thank you for your reply.
I have asked the question again [here](https://github.com/swagger-api/swagger-core/issues/3366).
