### ISSUE TITLE
UI Authorize button - OAuth2 with clientCredentials returns error of CORS

### ISSUE THREAD

**Issue by weesftw** [springdoc/springdoc-openapi#1650]
After configuring the securitySchemes and filling in all the elements (flows, tokens, scopes), the button to authenticate returns the CORS error and the OAuth server side is ok... it seems to me that swagger-ui does not send headers valid CORS, how can I configure this?

- **spring-boot** version 2.6.6
- Using **springdoc-openapi-ui** version 1.6.8

example [swagger.yaml](https://github.com/weesftw/openapi-string-byte-schema/blob/master/src/main/resources/swagger.yaml).

<img width="384" alt="example" src="https://user-images.githubusercontent.com/58608499/167234201-7a2daaf5-8274-4169-ad74-a4d6f08ed773.png">

**Comment by bnasslahsen** [comment]
@weesftw, 


CORS is related to your configuration.
You need to have CORS enabled, on your applications that is blocking the swagger-ui.

**Comment by weesftw** [comment]
> @weesftw,
> 
> CORS is related to your configuration. You need to have CORS enabled, on your applications that is blocking the swagger-ui.

The question is: do I need to configure CORS on the part of my application that is swagger-ui or oauth server?

**Comment by bnasslahsen** [comment]
@weesftw,

You should allow CORS requests. 
The answer depends on each application architecture...
