### ISSUE TITLE
Support for Spring Integration (Spring Boot 2.6.x)

### ISSUE THREAD

**Issue by grzeprza** [springdoc/springdoc-openapi#1653]
Hi, 

I was using SpringFox/Swagger 2 and due to the recent issue with Spring I upgraded to most recent version of Spring Boot that solved vulnerability.
Unfortunately, with the new version swagger died and I don't want to do [workarounds/hacks](https://github.com/springfox/springfox/issues/3982). In older version of this problem they suggested [switching to SpringDoc](https://github.com/springfox/springfox/issues/3462#issuecomment-1035511583) so here I am...

I'm encountering difficulties setting up Spring Integration (where I you define endpoints as @Bean's to Gateways). 
```
    @Operation(
        description = "Hello world",
        summary = "this is spring integration"
    )
    @ApiResponses({
        @ApiResponse(
            responseCode = "200",
            description = "Request example",
            content = @Content(schema = @Schema(implementation = String.class))
        )
    })
    @Bean
    public HttpRequestHandlingMessagingGateway endpointInbound(MessageChannel endpointInboundChannel) {
        return createGateway(endpointInboundChannel, headerMapper, integrationResponseErrorChannel,
            BASE_URL + ENDPOINT_URL, HttpMethod.GET);
    }
```

For test, I've created "normal" @RestController and it works as expected.
```
    @Operation(
        description = "Hello world",
        summary = "this is rest controller"
    )
    @ApiResponses({
        @ApiResponse(
            responseCode = "200",
            description = "Request example",
            content = @Content(schema = @Schema(implementation = String.class))
        )
    })
    @GetMapping
    ResponseEntity<?> getMapping() {
        return ResponseEntity.ok("Heelo wrold");
    }
```

Is there a chance that [Spring Integration](https://spring.io/projects/spring-integration) will be supported in the near future by SpringDoc?

Or maybe it is already supported? if yes, then please provide some reference, because I couldn't find anything.

Thanks in advance for answering.

**Comment by bnasslahsen** [comment]
@grzeprza, 

Maybe, you are willing to propose a PR for it ?
