### ISSUE TITLE
Custom headers via authorize button

### ISSUE THREAD

**Issue by weesftw** [springdoc/springdoc-openapi#1654]
So I recently reported a CORS related [issue](https://github.com/springdoc/springdoc-openapi/issues/1650) I was getting. However, I haven't been able to express exactly what's going on and I haven't had a chance to get into the subject I'm going to go into now.

Basically when I send a request through `swagger-ui`, it doesn't send the headers correctly, in particular the **ORIGIN** header... I would like to know if it's possible to **customize the headers** that will be sent via `swagger-ui` above the authorization button.

![Example](https://user-images.githubusercontent.com/58608499/167412461-4cf37cfd-1add-4d54-a68f-dba4bf24d987.png)

**Comment by bnasslahsen** [comment]
@weesftw, 

See the documentation of the `swagger-ui `to use `requestInterceptor`.
You have examples how it is used in `springdoc-openapi` that you can adapt for your custom headers https://github.com/springdoc/springdoc-openapi/blob/master/springdoc-openapi-common/src/main/java/org/springdoc/ui/AbstractSwaggerIndexTransformer.java.

Then you declare, your own `SwaggerIndexTransformer` as described [here](https://springdoc.org/#customizing-swagger-static-resources).
