### ISSUE TITLE
@Schema with ref in library does not seem to be picked up

### ISSUE THREAD

**Issue by Boyen86** [springdoc/springdoc-openapi#1656]
**Describe the bug**
We are trying to get Java properties of the type "Object" to be correctly read by Python.
As of now, Object is translated to `{ }`, and `{ }` is picked up as a Dictionary/Map by Python.

The solution for this was to create a custom schema as provided here: https://stackoverflow.com/questions/69257874/how-can-i-generate-the-openapi-arbitrary-type-using-swagger-core-springdoc-open

This however does not seem to be picked up.

**To Reproduce**
Given a simple REST application with springdoc-openapi.
Given the following class in a library:
```
public class ObjectDescription {
    @JsonProperty("value")
    @Schema(ref = "api-docs-anyvalue.yml#/components/schemas/AnyValue")
    private Object value;
}
```
given the following schema specification in the same folder
```
components:
  schemas:
    AnyValue: {}
```

**Expected behavior**
I expected the OpenApiSpec on an application that is using the library for the DTO objects, to have the AnyValue schema inside the OpenAPI spec. This is not the case. The ObjectDescription has the reference, but the schema for AnyValue is not available.

Any other methodology to support proper integration between Python and Java API's is good too.

**Comment by bnasslahsen** [comment]
@Boyen86, 

The integration between Python and Java depends on your Generated OpenAPI Spec.
The generated spec by springdoc-openapi in your case is valid.

See the documentation of https://swagger.io/docs/specification/components/ where it's possible to reference external files.

**Comment by Boyen86** [comment]
@bnasslahsen can you explain why the schema specification is not picked up then or what I am doing wrong?
