### ISSUE TITLE
Annotation @EnableConfigServer overrides swagger-ui

### ISSUE THREAD

**Issue by anvo1115** [springdoc/springdoc-openapi#1658]
We have a config-server org.springframework.cloud:spring-cloud-config-server:jar:3.1.0  and org.springframework.boot:spring-boot-starter-web:jar:2.6.6, where Application.java is marked with annotation @EnableConfigServer (org.springframework.cloud.config.server.EnableConfigServer).

We tried to add openapi-ui :
        <dependency>
            <groupId>org.springdoc</groupId>
            <artifactId>springdoc-openapi-ui</artifactId>
            <version>1.6.8</version>
        </dependency>

When I try to open swagger-ui , spring config-server controller is called instead of swagger:

[caller=o.s.w.s.DispatcherServlet] GET "/swagger-ui/index.html?configUrl=/v3/api-docs/swagger-config", parameters={masked}
[caller=o.s.w.s.m.m.a.RequestMappingHandlerMapping] Mapped to org.springframework.cloud.config.server.environment.EnvironmentController#defaultLabel(String, String)

If I disable config-server deleting @EnableConfigServer , swagger-ui is opened without problem.

**Comment by bnasslahsen** [comment]
Provide a [Minimal, Reproducible Example - with HelloController](https://stackoverflow.com/help/minimal-reproducible-example) that reproduces the problem
