### ISSUE TITLE
@Size min/max optional

### ISSUE THREAD

**Issue by rockxwre** [springdoc/springdoc-openapi#166]
Any thoughts on the following one?
When I use the `minLength` element with the `@Schema` annotation without the `maxLength` element, springdoc-openapi returns only a `minLength` in the documentation. 
However, when I use the `@Size` annotation with only the `min` element, also the `maxLength` will be returned in the documentation. In my opinion the `maxLength` should not appear in the documentation.
The same goes for only annotating the `max` element of the `@Size` annotation. In this case, only the `maxLength` should be returned in the documentation.

**Comment by springdoc** [comment]
Hi, 

 @Size annotation has a default value set to min(0) and max (Integer.MAX_VALUE).
 springdoc-openapi just returns the value of the annotations used.

**Comment by rockxwre** [comment]
Thank you for your reply.
That makes sense. However, in my opinion these defaults (0, Integer.MAX_VALUE) do not keep the documentation clean. So it looks like it is not possible to keep the `@Size` annotation for validation purposes and have the documentation minimized to what is necessary.
