### ISSUE TITLE
JsonView after migrating from Springfox to Springdoc

### ISSUE THREAD

**Issue by kershov** [springdoc/springdoc-openapi#1662]
Hi, all!

I've just migrated my project from Springfox to Springdoc and find out that JsonView processing behaviour changed.

Could, please, anyone explain how JsonViews are processed in Springdoc?

My case is as follows: I've got two controllers, DTO & View. Both controllers use the same DTO for responses but return different set of fields with help of JsonViews. First controller returns only `id` & `name` fields. Second one returns full list of fields (see the setup below). 

Before migrating to Springdoc my response schema in Swagger for the first controller was:

`/objects`
```
ObjectDto_IdAndName
  id
  name
```

And for the second one:

`/objects/{objectId}`
```
ObjectDto
  id
  name
  country
  city
  street
  house
```

After migration schema responses are:

Here is the issue. DTO is marked as IdAndName, but all the fields are available in schema response while only `id` & `name` should be available and included. All the fields are included in the OpenApi also.

`/objects`
```
ObjectDto_IdAndName
  id
  name
  country
  city
  street
  house
```

`/objects/{objectId}`
```
ObjectDto
  id
  name
  country
  city
  street
  house
```

I read FAQ for Springdoc JsonView annotation support, but there is no any helpful info. Coul'd, please, anyone explain what am I doing wrong and give some advice how I can use JsonViews with Springdoc?

PS Yes, I can switch from JsonViews to `ObjectIdAndNameDto(id, name)`, but my project is big enough and I'd like not to refactor it if there's a way to use JsonViews. 

Thanks!

----

Here is my setup: SpringBoot 2.6.7, springdoc-openapi-ui 1.6.8

**Controller :**

```java
@GetMapping(value = "/objects")
@JsonView(value = {Views.IdAndName.class})
public List<ObjectDto> getObjects() {
    return objectsService.getObjects();
}

@GetMapping(value = "/objects/{objectId}")
public ObjectDto getObject(@PathVariable Long objectId) {
    return objectsService.getObjectById(objectId);
}
```

**Response from `/objects` + `@JsonView(value = {Views.IdAndName.class})`:**

```json
[
    {
        "id": 1189486,
        "name": "Object 1"
    },
    {
        "id": 1189487,
        "name": "Object 2"
    }
]
```

**Response from `/objects/1189486`:**

```json
{
    "id": 1189487,
    "name": "Object 1",
    "country": "Country",
    "city": "City",
    "street": "Street",
    "house": "1"
}
```

**DTO:**

```java
@Data
@Builder
@AllArgsConstructor
@NoArgsConstructor
public class ObjectDto {
    @JsonView(value = {Views.IdAndName.class})
    private Long id;

    @JsonView(value = {Views.IdAndName.class})
    private String name;

    private String country;

    private String city;

    private String street;

    private String house;
}
```

**View:**

```java
public final class Views {
    public interface IdAndName {
    }
}
```

**Comment by bnasslahsen** [comment]
@kershov, 

See sample working test here: https://github.com/springdoc/springdoc-openapi/tree/master/springdoc-openapi-webmvc-core/src/test/java/test/org/springdoc/api/v30/app54

Your other fields should be declaring the respective `@JsonView` to make the filtering work.
This behavior is handled directly by `swagger-core` library and not `springdoc-openap`i.
