### ISSUE TITLE
@Schema annotation with type String and allowableValues set doesn't generate enum drop-down in swagger-ui after upgrading from 1.6.6 (when Spring custom converter is used)

### ISSUE THREAD

**Issue by solita-alperttiti** [springdoc/springdoc-openapi#1663]
**Describe the bug**

After upgrading from springdoc-openapi 1.6.6 to 1.6.7/1.6.8 enum drop-down is not visible in swagger-ui.

EDIT: problem is most likely a custom converter with enum (plain or decorated with schema-annotation). More details from comments.

This works with 1.6.6. as expected, but in 1.6.7/1.6.8 there is only normal empty text-field and not the enum drop-down with allowable values:

```

@Schema(type = "String", allowableValues = {
    "foo", "bar"
})
public enum FooBar {
[..]

```

And enum is used as pathvariable in controller:

```

@GetMapping(value = "/some/path/{fooBar}")
public void getFooBar(@PathVariable FooBar fooBar) {
[..]

```

- What version of spring-boot you are using?
2.6.7
- What modules and versions of springdoc-openapi are you using?
1.6.6 works, 1.6.7/1.6.8 doesn't

**Comment by solita-alperttiti** [comment]
Ok, digged a little bit more into this and it seems this is about spring custom converter used for that enum. If I remove converter then everything works in 1.6.8 as expected with plain enum and with decorating schema-annotation. It seems there has been some fixes for custom converters, e.g. this one #1534 . Need to check it in more detail if it explains this behaviour.

**Comment by solita-alperttiti** [comment]
As a workaround you could move @Schema-annotation for enum directly to controller(s) parameters, but obviously this isn't an optimal solution, because then you'll need to duplicate it for every place where that enum type is used. So, I think this needs to be fixed in a way, that @Schema-annotation of some type will be respected even if spring custom converter is involved.

**Comment by bnasslahsen** [comment]
@solita-alperttiti, 

Your description is not clear.
Provide a [Minimal, Reproducible Example - with HelloController](https://stackoverflow.com/help/minimal-reproducible-example) that reproduces the problem

**Comment by bnasslahsen** [comment]
@solita-alperttiti, 

Should be fixed with the next release.

This is the workaround, until then
```java
    @GetMapping(value = "/example/{fooBar}")
    public String getFooBar(@PathVariable @Parameter(schema = @Schema(allowableValues = { "foo", "bar" })) FooBar fooBar) {
        return fooBar.name();
    }
```
