### ISSUE TITLE
Springexpression in scope annotation not resolved

### ISSUE THREAD

**Issue by flatbeats** [springdoc/springdoc-openapi#1665]
The spring expression for the authorization url is resolved but the one for the scope not:

`@SecurityScheme(
        name = "SWAGGER_OAUTH",
        type = SecuritySchemeType.OAUTH2,
        flows = @OAuthFlows(
                implicit = @OAuthFlow(
                        authorizationUrl = "${springdoc.swagger-ui.oauth.authorizationUrl}"
                        scopes = {@OAuthScope(name = "${springdoc.swagger-ui.oauth.client-id}", description = "default")}
                )
        )
)`

**Comment by bnasslahsen** [comment]
@flatbeats, 

This is the expected behavior. 
See the documentation for available properties: https://springdoc.org/index.html#can-i-use-spring-property-with-swagger-annotations
