### ISSUE TITLE
JSON序列化问题

### ISSUE THREAD

**Issue by MINIPuffer** [springdoc/springdoc-openapi#1667]
https://github.com/springdoc/springdoc-openapi/blob/740827a7b4e7a4748a37708fde582c510f0ec7f2/springdoc-openapi-webmvc-core/src/main/java/org/springdoc/webmvc/api/MultipleOpenApiActuatorResource.java#L85
此方法为何不直接返回`OpenAPI`对象？函数返回值是`String`类型，`Content-Type`又是`application/json`，在返回的时候如果有一个JSON的`HttpMessageConverter`排在`StringHttpMessageConverter`前面就会造成二次序列化的问题

**Comment by bnasslahsen** [comment]
@MINIPuffer,

Please write in english

Remember, contributions to this repository should follow its [contributing guidelines](https://github.com/springdoc/springdoc-openapi/blob/740827a7b4e7a4748a37708fde582c510f0ec7f2/CONTRIBUTING.adoc) and [code of conduct](https://github.com/springdoc/springdoc-openapi/blob/740827a7b4e7a4748a37708fde582c510f0ec7f2/CODE_OF_CONDUCT.md).
