### ISSUE TITLE
update swagger api version

### ISSUE THREAD

**Issue by xiaoxiangmoe** [springdoc/springdoc-openapi#167]
https://github.com/springdoc/springdoc-openapi/blob/865a627000e72578d590c039014ed3ed1289d4ee/pom.xml#L67

please update this into [v2.1.0](https://github.com/swagger-api/swagger-core/releases/tag/v2.1.0)

**Comment by springdoc** [comment]
will be available on v1.2.10 of springdoc-openapi.
