### ISSUE TITLE
custom mime-type not availible in the UI

### ISSUE THREAD

**Issue by MehrCurry** [springdoc/springdoc-openapi#1672]
I have an OpenAPI Spec with a custom mime-type for the response:

```
openapi: 3.0.2
info:
  title: "Demo"
[...]
paths:
  /devices:
    get:
      summary: Get all devices
      operationId: getAllDevices
      responses:
        200:
          description: successful operation
          content:
            application/vnd.foo.devices.v1+json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Device'
```

But the UI only let me send `application/json` which leeds to an 406 error.

![Swagger Ui in my application](https://user-images.githubusercontent.com/328753/170073314-1cfdaa8d-932c-4e45-9da6-8ea16c54b32d.png)

**To Reproduce**
- What version of spring-boot you are using? 2.7.0
- What modules and versions of springdoc-openapi are you using? 1.6.8
- What is the actual and the expected result using OpenAPI Description (yml or json)? YAML

**Expected behavior**
- The only possible content-type should be present in the drop down box.

**Additional context**

Opening the same OpenAPI file in the swagger editor (via docker image) yields the expected result.
![Swagger Editor (external)](https://user-images.githubusercontent.com/328753/170074066-11280c32-0b69-4738-8305-cb7a9439920a.png)

**Comment by bnasslahsen** [comment]
@MehrCurry, 

You seem to be having a problem with the display in the swagger-ui and  not the generated OpenAPI Spec. 
Feel free to reach the [swagger-ui ](https://github.com/swagger-api/swagger-ui/issues)team instead.

**Comment by MehrCurry** [comment]
For those who wants to follow: https://github.com/swagger-api/swagger-ui/issues/8044
