### ISSUE TITLE
Global headers are not added with GroupedOpenApi

### ISSUE THREAD

**Issue by mkubele** [springdoc/springdoc-openapi#1674]
Global headers are not displayed in the web UI, nor the api json when GroupedOpenApi is used. It works fine if it's not used.

**To Reproduce**
Run the provided demo app, exclude the GroupedOpenApi and rerun the app.
- What version of spring-boot you are using? 
2.6.3/2.7.0
- What modules and versions of springdoc-openapi are you using? 
webflux-ui, kotlin 1.6.8

demo repo:
[https://github.com/mkubele/springdoc-demo](https://github.com/mkubele/springdoc-demo)

**Expected behavior**
The headers are included both in the UI and json

**Comment by bnasslahsen** [comment]
@mkubele, 

Please read the documentation. IT's [clearly stated](https://springdoc.org/#how-can-i-customise-the-openapi-object):
If you need the `OpenApiCustomizer` to applied to `GroupedOpenApi` as well, then use `GlobalOpenApiCustomiser` instead.
