### ISSUE TITLE
Support to customize path

### ISSUE THREAD

**Issue by seoul-afternoon** [springdoc/springdoc-openapi#1675]
I look forward to <b>create each path for each query parameter although it is the same path.</b> 
However, the path is overwritten and omitted.

I want to create 4 various paths

- `/v1/security/credentials?action=changePassword`
- `/v1/security/credentials?action=requestPasswordReset`
- `/v1/security/credentials?action=resetPassword`
- `/v1/security/credentials?action=remindUsername`

But I created 1 various path
- `/v1/security/credentials`

I think this is expected behavior for current open api spec.

[But several open api spec users have been already experiencing this problem.](https://github.com/OAI/OpenAPI-Specification/issues/164)
And it's been considered for a long time to be reflected in the next version.

In order to solve this problem, I would like to have an extension point to customize path.
I suggest adding `PathCustomizer`.

If you don't mind, I'll propose a PR about this.

I hope you consider this plan.

Thanks in advance for answering.

**Comment by bnasslahsen** [comment]
@seoul-afternoon, 

You already have `OpenApiCustomizer`, where you can customize all the attributes of the OpenAPI object. (Path included).

**Comment by seoul-afternoon** [comment]
@bnasslahsen 

Hi, I tried using `OpenApiCustomizer`. 
This is not enough to customize I want.

When I have two methods

```kotlin
@GetMapping("/members/{memberNo}")
fun findMember(@PathVariable memberNo: Long, userName: String, age: Int)

@GetMapping("/members/{memberNo}", params = "filter=admin")
fun findAdmin(@PathVariable memberNo: Long, admin : Boolean)
```

I expected to get a document for two paths like this.
```
/members/{memberNo}
/members/{memberNo}?filter=admin
```

But I got a document for one path.
```
/members/{memberNo}
```

When I try to customize using OpenApiCustomizer, 
the path is already combined, so it is not possible to customize as I want.

What should I do to be able to customize it as I want?

**Comment by seoul-afternoon** [comment]
@bnasslahsen 

Actually, it's not OpenAPI's specification yet.
But API developers sometimes face that case.
In this [issue](https://github.com/springdoc/springdoc-openapi/issues/1675#issue-1248296189), I linked the issue being discussed in the open api spec.
So, I want to points that can be customized.

**Comment by seoul-afternoon** [comment]
@bnasslahsen 

https://github.com/springdoc/springdoc-openapi/blob/f5208eb78a364931ce645ab6343c26c3d8602594/springdoc-openapi-webflux-core/src/main/java/org/springdoc/webflux/api/OpenApiResource.java#L195-L205

I think we can extract `String[] params` here and bind them to RouterOperation.

```java
@FunctionalInterface
public interface PathCustomizer {
    String customize(HandlerMethod handlerMethod, RouterOperation routerOperation, Locale locale);
}
```

And we can create a `PathCustomizer` interface and provide it to the user.

https://github.com/springdoc/springdoc-openapi/blob/f5208eb78a364931ce645ab6343c26c3d8602594/springdoc-openapi-common/src/main/java/org/springdoc/api/AbstractOpenApiResource.java#L382-L395

And if there is a  `PathCustomizer` implementation, We can pass it to the customized path when we build the operation path.

**Comment by bnasslahsen** [comment]
@seoul-afternoon, 

You are not describing the test case why you need this change.
As explained earlier, you need to provide the expected OpenAPI description or minimal sample with a test case, that shows why this change is really needed.

Without these elements, there is no need to insist.

**Comment by junoyoon** [comment]
@bnasslahsen

@seoul-afternoon will make PR for this soon. 
We're not demanding this for u to make this.
We'll make the PR for this issue and ask u review if u don't mind. 
Is it OK?

**Comment by bnasslahsen** [comment]
@junoyoon,

Feel free to propose a PR with the related unit tests.
