### ISSUE TITLE
springdoc.swagger-ui.configUrl has no effect.

### ISSUE THREAD

**Issue by yozaner1324** [springdoc/springdoc-openapi#1676]
**Describe the bug**
Setting springdoc.swagger-ui.configUrl has no effect and swagger-ui still tried to fetch configuration from the default (v3/api-docs/swagger-config.

**To Reproduce**
- Spring Boot 2.6.7
- I'm using springdoc-openapi-ui version 1.6.8.
- Set springdoc.api-docs.path to something else, for example "/v1/api-docs" and set springdoc.swagger-ui.configUrl to "/v1/api-docs/swagger-config"

**Expected behavior**
 - I expect swagger UI to pull configuration from the URL specified by springdoc.swagger-ui.configUrl, but it actually always tries pulling from the default (/v3/api-docs/swagger-config)

**Screenshots**
swagger-ui page and console showing the error fetching config: 
![Screen Shot 2022-05-25 at 5 04 53 PM](https://user-images.githubusercontent.com/10576409/170388862-f2d5658f-2346-41b2-8adf-f95b8f04363d.png)

**Additional context**
This SO comment is what made me realize that downgrading would fix my issue: https://stackoverflow.com/questions/71721477/springdoc-swagger-ui-not-using-swagger-config#comment126947343_71817365

**Comment by bnasslahsen** [comment]
@yozaner1324, 

Not reproducible.
Make sure you provide a [Minimal, Reproducible Example - with HelloController](https://stackoverflow.com/help/minimal-reproducible-example) that reproduces the problem
