### ISSUE TITLE
Annotation support beyond JSR-303

### ISSUE THREAD

**Issue by Troleus** [springdoc/springdoc-openapi#1677]
Is it possible to manually add your own annotations for verification, or annotations from other projects, for example @Length from hibernation, by expanding the list of JSR-303 annotations?

If there is no such function at the moment, will it ever appear?

**Comment by bnasslahsen** [comment]
@Troleus, 

See this article:  https://dzone.com/articles/extending-swagger-and-spring-doc-open-api
