### ISSUE TITLE
Dynamic GroupedOpenApi bean creation

### ISSUE THREAD

**Issue by cmagnuson** [springdoc/springdoc-openapi#1678]
I'm looking for a way to declare GroupedOpenApi beans dynamically - my use case is iterating over custom config to create a varied number of beans based on the consumer of my library.
 
**Is your feature request related to a problem? Please describe.**
It appears like this used to be possible per the comments here: https://github.com/springdoc/springdoc-openapi/issues/538#issuecomment-609038006 and here: https://github.com/springdoc/springdoc-openapi/issues/307#issuecomment-569819885  but it seems to no longer be possible in springdoc 1.6.8 based on my testing https://github.com/springdoc/springdoc-openapi/issues/307#issuecomment-1131920477
 
**Describe the solution you'd like**
I'd like to restore the ability to do a `beanFactory.registerSingleton()` to dynamically add beans.  Or an alternative of being able to declare an `@Bean` which returns a `Collection<GroupedOpenApi>` or a wrapper containing 1+ GroupedOpenApi beans.

**Comment by bnasslahsen** [comment]
@cmagnuson, 

In your config class: 

https://raw.githubusercontent.com/springdoc/springdoc-openapi-demos/52f42a56a359ea2f40d149141e7c3965229374aa/springdoc-openapi-book-service/src/main/java/org/springdoc/demo/services/book/MyConfig.java

Add explicitly the following bean: 

```java
@Bean
@Lazy(false)
MultipleOpenApiWebMvcResource multipleOpenApiResource(List<GroupedOpenApi> groupedOpenApis,
		ObjectFactory<OpenAPIService> defaultOpenAPIBuilder, AbstractRequestService requestBuilder,
		GenericResponseService responseBuilder, OperationService operationParser,
		SpringDocConfigProperties springDocConfigProperties,
		SpringDocProviders springDocProviders) {
	return new MultipleOpenApiWebMvcResource(groupedOpenApis,
			defaultOpenAPIBuilder, requestBuilder,
			responseBuilder, operationParser,
			springDocConfigProperties,
			springDocProviders);
}
```

**Comment by cmagnuson** [comment]
@bnasslahsen thanks!  I added the MultipleOpenApiWebMvcResource bean as suggested and do see the two definitions now.  

However they are both pointing to `/api/book/**` path.  If I define them as `@Bean`'s they point to `/api/book**` and `/api/stores/**` respectively, but doing a registerSingleton() they do not appear to be respecting the .pathsToMatch() set.

**Comment by bnasslahsen** [comment]
@cmagnuson, 

In line `27` just after `beanFactory.registerSingleton`, add: `SpringdocBeanFactoryConfigurer.initBeanFactoryPostProcessor(beanFactory);`

**Comment by cmagnuson-mck** [comment]
That solved it, much appreciated @bnasslahsen !
