### ISSUE TITLE
How do I dynamically create or delete documents

### ISSUE THREAD

**Issue by moil-xm** [springdoc/springdoc-openapi#1679]
**Is your feature request related to a problem? Please describe.**
- A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
- What is the actual result using OpenAPI Description (yml or json)?
**I read the documentation you provided.Couldn't find an interface to delete or create a OpenApi.**

**Comment by bnasslahsen** [comment]
Remember, contributions to this repository should follow its [contributing guidelines](https://github.com/springdoc/springdoc-openapi/blob/ff9c81dd9c7a4e2c8ca13eede8d3caa49a193f3d/CONTRIBUTING.adoc) and [code of conduct](https://github.com/springdoc/springdoc-openapi/blob/ff9c81dd9c7a4e2c8ca13eede8d3caa49a193f3d/CODE_OF_CONDUCT.md).
