### ISSUE TITLE
Swagger UI Path redirects to the wrong path

### ISSUE THREAD

**Issue by hisener** [springdoc/springdoc-openapi#168]
`springdoc.swagger-ui.path` redirects to static `WEB_JARS_URL`
https://github.com/springdoc/springdoc-openapi/blob/865a627000e72578d590c039014ed3ed1289d4ee/springdoc-openapi-common/src/main/java/org/springdoc/core/Constants.java#L15-L17
which is a bit problematic because we do serve webjars from `/swagger/**` path. Using the following configuration:

```
public final class SwaggerConfig implements WebFluxConfigurer {
    @Override
    public void addResourceHandlers(ResourceHandlerRegistry registry) {
        registry.addResourceHandler("/swagger/**")
                .addResourceLocations("classpath:/META-INF/resources/webjars/");
    }
}
```

The proposal is making webjars prefix configurable using a spring property like `springdoc.webjars.prefix` with the current value as default so that it will be backward compatible.

The proposal in https://github.com/PicnicSupermarket/springdoc-openapi/commit/41128e10d3be94a1963b6b465b6226350e831242 I can create a PR if that makes sense.

**Comment by springdoc** [comment]
Hi, 

 Your proposal makes sense.
 You can create a PR for both webflux/webmvc and it should be integrated for the next release.

**Comment by hisener** [comment]
Created the PR with one question about webmvc change, PTAL, https://github.com/springdoc/springdoc-openapi/pull/174
