### ISSUE TITLE
Getting Index StringIndexOutOfBoundsException during application start after adding springdoc-openapi-ui

### ISSUE THREAD

**Issue by tmnuwan12** [springdoc/springdoc-openapi#1681]
Apologies for the formatting.
We have a UI module in our classpath which creates webjar and put contents under /META-INF/resources/webjars/ directory.

Example
/META-INF/resources/webjars/index.html.

We have added the following dependency to our project.

`<dependency>`
 `           <groupId>org.springdoc</groupId>`
      `      <artifactId>springdoc-openapi-ui</artifactId>`
        `    <version>1.6.8</version>`
`       </dependency>`

Then during application start we get an exception: StringIndexOutOfBoundsException

After debugging found that in WebJarAssetLocator class has a method findWebJars in line 107 to be exact.

` for (Resource resource : scanResult.getAllResources()) {`
`            final String noPrefix = resource.getPath().substring(WEBJARS_PATH_PREFIX.length() + 1);`
`            final String webJarName = noPrefix.substring(0, noPrefix.indexOf("/"));`
`            WebJarInfo webJarInfo = allWebJars.get(webJarName);`
`            if (webJarInfo == null) {`

The line here        `final String webJarName = noPrefix.substring(0, noPrefix.indexOf("/"));`
is expecting some "/" after "webjars" directory.
/META-INF/resources/webjars/swagger-ui/index.html

 For project which has all resources directory under /META-INF/resources/webjars/ directory it's going to break. Please apply a fix just to only read swagger specific paths or product some configuration to control it.

**Comment by bnasslahsen** [comment]
@tmnuwan12, 

`findWebJars` is not part of `springdoc-openapi` code.
If you require more assitance. Make sure you provide a [Minimal, Reproducible Example - with HelloController](https://stackoverflow.com/help/minimal-reproducible-example) that reproduces the problem.
