### ISSUE TITLE
Responses without content are assigned the operations return type as content

### ISSUE THREAD

**Issue by ssg-alzi** [springdoc/springdoc-openapi#1683]
When I define an @ApiResponse on an operation in an @RestController that has no content, the generated api definition contains the controller methods return type as content.
This makes it impossible to define an response without content, which is spec conform (https://swagger.io/specification/#response-object).

I did some debugging and found the place it happens:
org/springdoc/springdoc-openapi-common/1.6.9/springdoc-openapi-common-1.6.9-sources.jar!/org/springdoc/core/GenericResponseService.java:530

The annotation @ApiResponse contains the attribute useReturnTypeSchema (default=false) that looks like it is supposed to controll exactly this behaviour. The code I linked does not make use of it.

**To Reproduce**
- What version of spring-boot you are using? 2.7.0
- What modules and versions of springdoc-openapi are you using? springdoc-openapi-ui 1.6.9

<details><summary>Sample Code</summary>
<p>

```java
package org.example;

import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.headers.Header;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RestController;

@RestController
public class HelloController {

    @Operation(summary = "Test controller to reproduce issue",
            security = @SecurityRequirement(name = "Token"), responses = {
            @ApiResponse(responseCode = "200", description = "all good",
                    content = @Content(
                            mediaType = "application/json",
                            schema = @Schema(implementation = ErrorResponse.class)
                    )
            ),
            @ApiResponse(responseCode = "401", description = "Authentication invalid", headers = {
                    @Header(name = "WWW-Authenticate", description = "see https://datatracker.ietf.org/doc/html/rfc6750#section-3.1", required = true)
            }),
            @ApiResponse(responseCode = "500", description = "Internal Server Error",
                    content = @Content(
                            mediaType = "application/json",
                            schema = @Schema(implementation = ErrorResponse.class)
                    )
            )
    })
    @PostMapping(value = "/hello", produces = MediaType.APPLICATION_JSON_VALUE)
    ResponseEntity<ErrorResponse> fetchSasToken(){

        return ResponseEntity.ok(new ErrorResponse("asdf", "asdf2"));
    }
}

```
</p>
</details>

**Expected behavior**
I expect the generated response to be without content as I defined it with the @ApiResponse annotation.

Edit: Corrected sample code

**Comment by bnasslahsen** [comment]
@ssg-alzi, 

This is answered in the FAQ https://springdoc.org/#how-can-i-return-an-empty-content-as-response
