### ISSUE TITLE
Parameter problems with generics

### ISSUE THREAD

**Issue by zl-double** [springdoc/springdoc-openapi#1686]
![泛型问题](https://user-images.githubusercontent.com/58248446/171301132-e0aad794-f3e8-4475-8d11-b85de4373687.png)

**Comment by bnasslahsen** [comment]
Remember, contributions to this repository should follow its [contributing guidelines](https://github.com/springdoc/springdoc-openapi/blob/ff9c81dd9c7a4e2c8ca13eede8d3caa49a193f3d/CONTRIBUTING.adoc) and [code of conduct](https://github.com/springdoc/springdoc-openapi/blob/ff9c81dd9c7a4e2c8ca13eede8d3caa49a193f3d/CODE_OF_CONDUCT.md).
