### ISSUE TITLE
Child classes' fields are not propely getting added to the swagger spec schema

### ISSUE THREAD

**Issue by BhaveshSuvalaka** [springdoc/springdoc-openapi#1689]
I'm using spring-boot v2.6.7 and springdoc v1.6.8. Below is the object modeling. There's one endpoint that returns the Course as the response. Here the Course is supertype and the Child type is EnglishCourse also there's an **items** field on EnglishCourse which is a supertype of CourseItem and there are subtypes for it which are Folder, Lesson, and Test. I expect swagger spec to include a proper schema definition that includes all the fields for all the subtypes.

```

      package com.example.springdocdemo.domain
      
      import com.fasterxml.jackson.annotation.JsonSubTypes
      import com.fasterxml.jackson.annotation.JsonTypeInfo
      import io.swagger.v3.oas.annotations.media.Schema
      import java.util.UUID
      
      @JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.EXISTING_PROPERTY, property = "type")
      @JsonSubTypes(
          value = [
              JsonSubTypes.Type(value = EnglishCourse::class, name = "EnglishCourse")
          ]
      )
      abstract class Course {
          abstract val id: UUID
          abstract val name: String
          abstract val code: String
      }
      
      class EnglishCourse(
          val items: List<CourseItem>,
          override val id: UUID,
          override val code: String,
          override val name: String,
      ) : Course()
      
      @JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.EXISTING_PROPERTY, property = "type")
      @JsonSubTypes(
          value = [
              JsonSubTypes.Type(value = Folder::class, name = "FOLDER"),
              JsonSubTypes.Type(value = Lesson::class, name = "LESSON"),
              JsonSubTypes.Type(value = Test::class, name = "TEST")
          ]
      )
      @Schema(discriminatorProperty = "type", allOf = [Folder::class, Lesson::class, Test::class])
      interface CourseItem {
          val type: CourseItemType
          val id: UUID
      }
      
      @Schema
      class Folder(
          val items: List<CourseItem>,
          override val id: UUID,
          override val type: CourseItemType,
      ) : CourseItem {
          fun items() = println(items)
      }
      
      class Lesson(
          val name: String,
          override val id: UUID,
          override val type: CourseItemType,
      ) : CourseItem
      
      class Test(
          val name: String,
          override val id: UUID,
          override val type: CourseItemType,
      ) : CourseItem
      
      enum class CourseItemType {
          Folder, Lesson, Test
      }

```
 And the below is the generated schema definition for the Folder type: 
      

 ```
     "Folder": {
          "required": [
            "id",
            "type"
          ],
          "type": "object",
          "allOf": [
            {
              "$ref": "#/components/schemas/CourseItem"
            }
          ]
        },
```

it includes "id" and "type" only but "items" field is missing. Is there any solution for this? The code can be found here: https://github.com/BhaveshSuvalaka/springdoc-issue

**Comment by bnasslahsen** [comment]
@BhaveshSuvalaka, 

Before reporting any issue, make sure you are using the last available release.

**Comment by BhaveshSuvalaka** [comment]
@bnasslahsen I have checked it with springdoc v1.6.9 but the same issue. Also could you please re-open the issue?

**Comment by bnasslahsen** [comment]
@BhaveshSuvalaka, 

`springdoc-openapi` relies on `swagger-core` project.
Make sure you check if it's not related to swagger-core library instead.
For that, 

The behavior you are describing is directly handled using [swagger-core](https://github.com/swagger-api/swagger-core/).

This is a sample code that helps you check if the generated schema with `swagger-core` classes is correct:

```java
ResolvedSchema resolvedSchema = ModelConverters.getInstance()
		.resolveAsResolvedSchema(
				new AnnotatedType(Folder.class));
// Then check is items is present
```

If `items` is absent, feel free to ask the swagger team instead and reference this ticket.
If `items` is present, then we can reopen this ticket...

**Comment by BhaveshSuvalaka** [comment]
Thanks @bnasslahsen , I appreciate your help on this. The resolved schema generated using above code contains the items, below is the generated generated schema for folder : 
`Folder=class Schema {
    type: object
    format: null
    $ref: null
    description: null
    title: null
    multipleOf: null
    maximum: null
    exclusiveMaximum: null
    minimum: null
    exclusiveMinimum: null
    maxLength: null
    minLength: null
    pattern: null
    maxItems: null
    minItems: null
    uniqueItems: null
    maxProperties: null
    minProperties: null
    required: [id, items, type]
    not: null
    properties: {items=class ArraySchema {
        class Schema {
            type: array
            format: null
            $ref: null
            description: null
            title: null
            multipleOf: null
            maximum: null
            exclusiveMaximum: null
            minimum: null
            exclusiveMinimum: null
            maxLength: null
            minLength: null
            pattern: null
            maxItems: null
            minItems: null
            uniqueItems: null
            maxProperties: null
            minProperties: null
            required: null
            not: null
            properties: null
            additionalProperties: null
            nullable: null
            readOnly: null
            writeOnly: null
            example: null
            externalDocs: null
            deprecated: null
            discriminator: null
            xml: null
        }
    }, id=class UUIDSchema {
        class Schema {
            type: string
            format: uuid
            $ref: null
            description: null
            title: null
            multipleOf: null
            maximum: null
            exclusiveMaximum: null
            minimum: null
            exclusiveMinimum: null
            maxLength: null
            minLength: null
            pattern: null
            maxItems: null
            minItems: null
            uniqueItems: null
            maxProperties: null
            minProperties: null
            required: null
            not: null
            properties: null
            additionalProperties: null
            nullable: null
            readOnly: null
            writeOnly: null
            example: null
            externalDocs: null
            deprecated: null
            discriminator: null
            xml: null
        }
    }, type=class StringSchema {
        class Schema {
            type: string
            format: null
            $ref: null
            description: null
            title: null
            multipleOf: null
            maximum: null
            exclusiveMaximum: null
            minimum: null
            exclusiveMinimum: null
            maxLength: null
            minLength: null
            pattern: null
            maxItems: null
            minItems: null
            uniqueItems: null
            maxProperties: null
            minProperties: null
            required: null
            not: null
            properties: null
            additionalProperties: null
            nullable: null
            readOnly: null
            writeOnly: null
            example: null
            externalDocs: null
            deprecated: null
            discriminator: null
            xml: null
        }
    }}
    additionalProperties: null
    nullable: null
    readOnly: null
    writeOnly: null
    example: null
    externalDocs: null
    deprecated: null
    discriminator: null
    xml: null
}`

Requesting you to open this issue and help us to get the fix.

**Comment by BhaveshSuvalaka** [comment]
hi @bnasslahsen, gentle reminder.
