### ISSUE TITLE
Is this library compatible Spring Boot 2.2 & Hateoas 1.0?

### ISSUE THREAD

**Issue by chadmalla-ff** [springdoc/springdoc-openapi#169]
The reason I am looking to move from `springfox` to `springdoc-openapi` is due to the lack of support for `Boot 2.2 & Hateoas 1.0` in the same project. Does this library officially work with `Spring Boot 2.2` and `Hateoas 1.0`?

**Comment by springdoc** [comment]
Hi, 

 For the moment, the support of Hateoas 1.0, is not yet implemented. It will not be supported on the springdoc-openapi-core library. 
 Technically, you can add ModelConverters for Spring Hateoas objects.
 This feature, can be supported in specific module for Spring Hateoas, during a future release.

**Comment by chadmalla-ff** [comment]
Okay thank you, looking forward to the release. Should I close this issue or leave it open?

**Comment by eiswind** [comment]
Looking forward to see this too.

**Comment by chadmalla-ff** [comment]
@springdoc  Should this ticket be closed or are you working on anything? So far on my project, Springdoc + Boot 2.2 + Hateoas 1.0 are working fine.

**Comment by springdoc** [comment]
Hi @chadmalla-ff,

 Work os still in progress for this feature.
 I understand, that for usage of Spring-boot 2 + HATEAOS, its working fine with  v1.2 16. Do you confirm?

**Comment by chadmalla-ff** [comment]
I am on v1.2.15 and it is working fine. But can try it with v1.2.16 later.

**Comment by springdoc** [comment]
Thank you @chadmalla-ff
