### ISSUE TITLE
Class level @Parameters not allowed

### ISSUE THREAD

**Issue by dashmhatre** [springdoc/springdoc-openapi#1693]
Define Parameters at class level not allowed. Below is a code snippet 

@RestController
@RequestMapping(value = "/country", produces = MediaType.APPLICATION_JSON_VALUE)
@ApiResponses(value = {@ApiResponse(responseCode = "200", description = "OK"),
        @ApiResponse(responseCode = "204", description = "No content"),
        @ApiResponse(responseCode = "400", description = "Bad Request"),
        @ApiResponse(responseCode = "401", description = "Unauthorized"),
        @ApiResponse(responseCode = "500", description = "Internal Server Error", content = @Content(schema = @Schema( implementation =  ApiErrorResponse.class)))})
@Parameters( value = {@Parameter(name = "X-Transaction-Id", in = ParameterIn.HEADER, schema = @Schema(name = "string", implementation = String.class))})

@RequiredArgsConstructor
public class CountryController {
}

**To Reproduce**
- What version of spring-boot you are using?  2.7.0 
- What modules and versions of springdoc-openapi are you using?  1.6.9

**Expected behavior**
Allow to define class level parameters

**Comment by mgohin** [comment]
@dashmhatre did you find a solution ?

**Comment by italomaia-bk** [comment]
What happened here? This looks useful.
