### ISSUE TITLE
Model with same name creating conflicting documentation

### ISSUE THREAD

**Issue by agllno** [springdoc/springdoc-openapi#1694]
Say I have 2 classes with same name in different package
1) org.springdoc.a.Pet
1) org.springdoc.b.Pet

In controller class if I use org.springdoc.a.Pet I observed sometimes documentation picks org.springdoc.b.Pet. Spring doc is not considering imported package for documentation.

**Comment by donniebrighto** [comment]
Do you have `useFqn` property set to true?

**Comment by agllno** [comment]
Nope, could not find any reference. Will try out.

**Comment by bnasslahsen** [comment]
see `springdoc.use-fqn` in https://springdoc.org/#springdoc-openapi-core-properties
