### ISSUE TITLE
swagger-ui not available in version 1.6.9 + spring boot 2.7.0

### ISSUE THREAD

**Issue by miguelangelprogramacion** [springdoc/springdoc-openapi#1697]
**To Reproduce**
- What version of spring-boot you are using? 2.7.0
- What modules and versions of springdoc-openapi are you using? 1.6.9
- What is the actual and the expected result using OpenAPI Description (yml or json)? : I am upgrading to spring boot 2.7.0. While keeping the springdoc-openapi-ui dependency on 1.6.8, I can check out the swagger-ui at http://localhost:8080/swagger-ui/index.html. However, when upgrading to 1.6.9, the result is 404.

In both cases, the api documentation is available at http://localhost:8080/v3/api-docs

**Comment by bnasslahsen** [comment]
@miguelangelprogramacion, 

If you believe you are facing an issue, make sure you provide a [Minimal, Reproducible Example - with HelloController](https://stackoverflow.com/help/minimal-reproducible-example) that reproduces the problem.

This ticket will be closed. But can be reopened, if the relevant information are provided.

**Comment by bogdan-sava** [comment]
I had the same issue.
Workaround: add @EnableConfigurationProperties annotation to your Spring Boot application  main class. It works!
