### ISSUE TITLE
OpenApiWebMvcResource.openapiJson returning String is brittle if custom MessageConverters are present

### ISSUE THREAD

**Issue by cfieber** [springdoc/springdoc-openapi#1699]
**Is your feature request related to a problem? Please describe.**
our app added a MessageConverter to support YAML content types and a JSON MessageConverter to add specific configuration of the Jackson ObjectMapper. As a result, the returned String gets serialized as a JSON String object (quoted and escaped) rather than as raw JSON

**Describe the solution you'd like**
Perhaps returning Map<String, Object> would play better with the Spring response serialization?

**Describe alternatives you've considered**
I need to figure out how to insert the correct MessageConverter to handle the String response through a WebMvcConfigurer

**Comment by bnasslahsen** [comment]
@cfieber, 

You have so many ways to achieve your goal.
You can add `StringHttpMessageConverter` to your configureMessageConverters.
Or you can define your own `OpenApiWebMvcResource` Bean which returns what you are expecting...

All these options and others are discussed here:
- https://github.com/springdoc/springdoc-openapi/issues/624
