### ISSUE TITLE
Support relative path in @ExampleObject

### ISSUE THREAD

**Issue by membersound** [springdoc/springdoc-openapi#17]
Having a file in `/src/main/resources/static/swagger/example.json`. Placed inside  `/static` because spring can expose those to the web.

It should be possible to reference the file relative to the application itself. Eg as follows:

```
@Operation(responses = @ApiResponse(content = @Content(examples = @ExampleObject(externalValue = "swagger/example.json")))
```

But even if I can access the resource via `locahost:8080/swagger/example.json`, when adding the url to `@ExampleObject` it is still not resolved:
```
@Operation(responses = @ApiResponse(content = @Content(examples = @ExampleObject(externalValue = "locahost:8080/swagger/example.json")))
```

**Comment by springdoc** [comment]
Hi, 
 
 Tested with springdoc-openapi: 1.1.15. 
  In order to add the examples reference, in the generated yaml/json documentation, you need to add the name of the ExampleObject:

`responses= @ApiResponse(content = @Content(examples = @ExampleObject(name = "toto", externalValue = "http://localhost:8080/test/example.json")))` 

Displaying the example on the swagger-ui, is not a springdoc-openapi issue, but depends on a pending issue on swagger-ui side:

- https://github.com/swagger-api/swagger-ui/issues/5433

**Comment by Aravinda93** [comment]
@bnasslahsen 

Hello, Can you please let me know if the issue has been fixed or if there is a work-around for the same? 

I am also facing the same issue where if I add the path to the file then the contents from the are not displayed within `SwaggerUI`. I tried using the `ref` and `externalValue` but nothing seems to work:

```
@RequestBody(description = "InputTemplate body",
        content = @Content(schema = @Schema(implementation = InputTemplate.class), examples = {
                @ExampleObject(name = "Example-1",
                        description = "Example-1 for InputTemplate.",
                        ref = "#/resources/Example1.json"), //externalValue = "#/resources/Example1.json"
                @ExampleObject(name = "Example-2",
                        description = "Example-2 for InputTemplate.",
                        ref = "#/resources/Example1.json") //externalValue = "#/resources/Example1.json"
        }))
```

@bnasslahsen Can you please let me know if the issue has been fixed or if there is an work-around for the same?

**Comment by Aravinda93** [comment]
Posting the answer here as it can be useful to someone else in the future:

I was able to find a work-around based on this answer: https://stackoverflow.com/a/71699253/7584240

**Comment by Spatrik95** [comment]
@bnasslahsen I tried the following in my Spring Boot v2.6.6, Spring v5.3.18 project with springdoc-openapi-ui 1.6.7 and it not worked with the request body example. I put this annotation on a `@PostMapping` method:

```
@Operation(summary = "Operation Summary",
           requestBody = @io.swagger.v3.oas.annotations.parameters.RequestBody(
                   content = @Content(examples = @ExampleObject(name = "Example name", externalValue = "http://localhost:8080/response.json"))
           )
)
```

The response json is in the resource/static folder, I can access it successfully via web browser. Maybe is it a bug? Is it only works with absolute URL?

**Comment by wenwangctl** [comment]
experience the same issue. would like to know if there is a solution to this. spring boot v2.6.7 and springdoc 1.6.7. externalValue does not populate swagger payload.

**Comment by cmy14217** [comment]
I met same problem that the relative path $ref for @ExampleObject not work and solve it by adding the **value** rootPath for the example json file content. I create a [sample project](https://github.com/cmy14217/springdoc-sample) for it, hope it works for you.

controller:
<img width="1262" alt="image" src="https://user-images.githubusercontent.com/34540238/172554295-e4ee40d6-c90d-4fa9-96bc-2f310626e43e.png">

json files defined under 'resource/static/api-docs':
<img width="377" alt="image" src="https://user-images.githubusercontent.com/34540238/172554489-143403b0-eacd-4f13-be3f-dfce792c6b88.png">

example json file content:
<img width="568" alt="image" src="https://user-images.githubusercontent.com/34540238/172554642-ad056aa6-54e0-4e97-90e2-5e5f5170c6a9.png">

**Comment by gitkidmk** [comment]
I'm facing same issue and i got an idea from **springdoc-openapi** project.

![image](https://user-images.githubusercontent.com/60382133/189850797-3ccca904-ed85-4bf3-a6fc-b5de422a5a7f.png)

In this project, it create example entry(`http500Example`) and add Example through `openApiCustomiser`

actually, this code represent ref in setValue but i put json file in `Example` object

here is my code

```
package com.semtax.application.config.swagger.exampleObject;

import io.swagger.v3.oas.models.examples.Example;
import org.json.simple.JSONObject;
import org.json.simple.parser.JSONParser;
import org.json.simple.parser.ParseException;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.context.annotation.Bean;
import org.springframework.core.io.Resource;
import org.springframework.stereotype.Component;

import java.io.IOException;
import java.io.InputStreamReader;
import java.util.*;

@Component
public class SwaggerExampleObject {

    @Value("classpath:/swagger/login.json")
    Resource loginResource;

    @Bean
    public Map.Entry<String, List<Example>> loginExample() throws IOException, ParseException, IllegalAccessError {

        JSONObject json = (JSONObject) new JSONParser().parse(new InputStreamReader(loginResource.getInputStream(), "UTF-8"));

        List<Example> ExampleList = new ArrayList<>();
        AbstractMap.SimpleEntry<String, List<Example>> loginExampleMap = new AbstractMap.SimpleEntry<>("login", null);

        for (Object s : json.keySet()){
            Example example = new Example();
            example.setValue(json.get(s));
            example.setDescription(s.toString());
            ExampleList.add(example);
        }
        loginExampleMap.setValue(ExampleList);

        return loginExampleMap;
    }
}

```

```
package com.semtax.application.config.swagger;

@OpenAPIDefinition(
        info = @Info(title = "API 명세서",
                description = "Essay Web App API 명세서입니다.",
                version = "v1"))
@Configuration
@RequiredArgsConstructor
public class Swagger2Config {

    @Autowired
    SwaggerExampleObject swaggerExampleObject;

    @Bean
    public OpenApiCustomiser openApiCustomiser(Collection<Entry<String, List<Example>>> examples) {
        return openAPI -> {
            examples.forEach(example -> {
                for(Example e : example.getValue()){
                    openAPI.getComponents().addExamples(e.getDescription(), e);
                }
            });
        };
    }

}
```

**Comment by VitorNilson** [comment]
Is there an effective solution to this problem?
