### ISSUE TITLE
Migration issue from SpringFox 

### ISSUE THREAD

**Issue by aoudiamoncef** [springdoc/springdoc-openapi#170]
Hi @springdoc,
I'm migrating an existing Spring boot 2 project with SpringFox and i doesn't found an equivalent of this code below:

```java
    @Bean
    public OpenAPI customImplementation(final ServletContext servletContext, @Value("${openapi.app.base-path:/api/v1}") final String basePath) {
        return new OpenAPI(DocumentationType.SWAGGER_2)
                .select()
                .apis(RequestHandlerSelectors.basePackage(DOC_PACKAGE_NAME))
                .build()
                .pathProvider(new BasePathAwareRelativePathProvider(servletContext, basePath))
                .directModelSubstitute(java.time.LocalDate.class, java.sql.Date.class)
                .directModelSubstitute(java.time.OffsetDateTime.class, java.util.Date.class)
                .apiInfo(this.apiInfo())
                .enable(this.appProperties.getSwagger());
    }

    static class BasePathAwareRelativePathProvider extends RelativePathProvider {
        private final String basePath;

        BasePathAwareRelativePathProvider(final ServletContext servletContext, final String basePath) {
            super(servletContext);
            this.basePath = basePath;
        }

        @Override
        protected String applicationPath() {
            return Paths.removeAdjacentForwardSlashes(UriComponentsBuilder.fromPath(super.applicationPath()).path(this.basePath).build().toString());
        }

        @Override
        public String getOperationPath(final String operationPath) {
            final UriComponentsBuilder uriComponentsBuilder = UriComponentsBuilder.fromPath("/");
            return Paths.removeAdjacentForwardSlashes(
                    uriComponentsBuilder.path(operationPath.replaceFirst("^" + this.basePath, "")).build().toString());
        }
    }
```
I read the hole tests and doc of the project before opening this issue.

Thanks for this great project :)

**Comment by springdoc** [comment]
Hi, 

 There is no relation between springfox and springdoc during the migration.
 If you want to migrate your project to OpenAPI 3, the easy way, is to:

- Remove all the dependencies and the related code to springfox
- Add springdoc-openapi-ui dependency

Please note, that by default you just need to add the right dependency to your project

**Comment by aoudiamoncef** [comment]
Hi,
Thanks for your feedback, I had made all what you suggested.

I'm sorry, i think that you haven't understood the intent of my issue. I
would achieve the same configuration with SpringDoc, the code above with
SpringFox gives me the ability to enable/disable the Swagger UI with a
configuration property. Second, it's offer a way to make a customized way
setup an equivalent of OpenApi object in Springdocs.

Is it possible to achieve the same configuration with SpringDoc ?

Thanks 🎉

**Comment by springdoc** [comment]
Hi, 

 If you want only to have the rest-api without the ui: you add only the dependcy to springdoc-openapi-webmvc-core.

 If you add  springdoc-openapi-ui dependcy, you get both: the ui and the rest api.
 Details are available here:
- https://springdoc.github.io/springdoc-openapi-demos/

 For the second point, you can define a Custom OpenApi Bean.
 You can have a look at the demos code or even the tests:
- https://github.com/springdoc/springdoc-openapi-demos/blob/master/springdoc-openapi-test-app2/src/main/java/org/springdoc/demo/app2/Application.java

**Comment by aoudiamoncef** [comment]
Hi, 
Thanks for your reply.  My use-case is very common, we have to enable Swagger Ui in dev && qa environments and disable it in production. In SpringFox, they have a boolean  value to do it.

```java
.enable(this.appProperties.getSwagger());
```
It could be a great feature to add this to SpringDocs. 

Thanks

**Comment by springdoc** [comment]
Fix is available on: https://github.com/springdoc/springdoc-openapi/issues/191
