### ISSUE TITLE
 How to refresh the API

### ISSUE THREAD

**Issue by Sureqing** [springdoc/springdoc-openapi#1703]
In my project, the plugin will be dynamically loaded during runtime，
The plugin will provide the controller
Is there a way that allows me to manually trigger springdoc to reload the api doc

In springfox I can do it through springfox.documentation.spring.web.plugins.DocumentationPluginsBootstrapper

```
documentationPluginsBootstrapper.stop();
documentationPluginsBootstrapper.start();
```

Looking forward to your reply, thank you very much

**Comment by bnasslahsen** [comment]
@Sureqing, 

You have springdoc property `springdoc.cache.disabled=true`, that you can access programatically as well by injecting an instance of the Bean `SpringDocConfigProperties`
