### ISSUE TITLE
springdoc.cache.disabled doesnt work when accessing through swagger-ui/index.html instead of swagger-ui.html

### ISSUE THREAD

**Issue by sonic-air-swimmer** [springdoc/springdoc-openapi#1709]
**Describe the bug**
buildConfigUrl does not calculated when swagger is accessed through http://<path>/swagger-ui/index.html instead of http://<path>/swagger-ui.html

It appears that it'll behaving similarly to springdoc.cache.disabled=true not set, i.e. if the first url is accessed through proxy then a direct hit would sees "Failed to load remote configuration" page, and vice versa.

**To Reproduce**
1. Instead of accessing http://localhost:8080/api/servicea/swagger-ui.html and http://localhost:8081/swagger-ui.html, hitting http://localhost:8080/api/servicea/swagger-ui/index.html and http://localhost:8081/swagger-ui/index.html
2. The latter URL accessed would not be able to load correctly. 

- What version of spring-boot you are using?
 v2.6.6.

- What modules and versions of springdoc-openapi are you using?
springdoc-openapi-ui, v1.6.7. 

- What is the actual and the expected result using OpenAPI Description (yml or json)?
Expect server url to be calculated everytime even access through swagger-ui/index.html.

- Provide with a sample code (HelloController) or Test that reproduces the problem
Minimal reproducible code at https://github.com/sonic-air-swimmer/SpringCloudGatewaySwagger

**Comment by bnasslahsen** [comment]
@sonic-air-swimmer,

Use the correct url as stated in the documentation.  
Also make sure you are using the last  stable version before logging tickets.
The url you are mentioning is not valid for webflux applications or graalvm native apps.

If you believe you can bring an enhancement, feel free to propose a PR.
