### ISSUE TITLE
Possible to set servlet path mapping?

### ISSUE THREAD

**Issue by junhuhdev** [springdoc/springdoc-openapi#1711]
**Describe the bug**
When app is deployed behind reverse proxy.
The swagger ui fails to fetch swagger-config. 

This is more of a question rather than bug. In spring fox it was possible to set servlet mapping 

![image](https://user-images.githubusercontent.com/45692017/174299061-3db2acba-d6fe-4896-8028-27735fc5dd3a.png)
![image](https://user-images.githubusercontent.com/45692017/174299098-3454574e-2716-4266-9b41-251d90cff498.png)

Is there a similar mechanism for this library?
  
**To Reproduce**
- What version of spring-boot you are using? latest
- What modules and versions of springdoc-openapi are you using? latest
- What is the actual and the expected result using OpenAPI Description (yml or json)?
- Provide with a sample code (HelloController) or Test that reproduces the problem

**Expected behavior**
- A clear and concise description of what you expected to happen.
- What is the expected result using OpenAPI Description (yml or json)?

**Screenshots**

**Additional context**

**Comment by rhu25** [comment]
@junhuhdev whats solution for this? i am having same issue, ui fails to fetch swagger-config because our app is using proxy to call api

**Comment by rhu25** [comment]
@junhuhdev whats solution for this? i am having same issue, ui fails to fetch swagger-config because our app is using proxy to call api

**Comment by bnasslahsen** [comment]
@rhu25 or @junhuhdev, 

Provide a [Minimal, Reproducible Example - with HelloController](https://stackoverflow.com/help/minimal-reproducible-example) that reproduces the problem
