### ISSUE TITLE
.formLogin() support

### ISSUE THREAD

**Issue by littl3rud3** [springdoc/springdoc-openapi#1714]
As said in [comment](https://github.com/springdoc/springdoc-openapi/issues/827#issuecomment-713368584) is there support for .formLogin()?

`@SecurityScheme(
        name = "basicAuth",
        type = SecuritySchemeType.HTTP,
        scheme = "basic"
)
public class Application`

`@SecurityRequirement(name = "basicAuth")
public class Controller `

`    @Bean
    public SecurityFilterChain filterChain(HttpSecurity http) throws Exception {

        http.csrf().disable()
                .authorizeRequests()
                .antMatchers("/login").permitAll()
                .antMatchers("/v3/api-docs/**", "/swagger-ui/**", "/swagger-ui.html").permitAll()
                .anyRequest().authenticated()
                .and()
                .formLogin();

        return http.build();
    }`

![image](https://user-images.githubusercontent.com/67325745/174857351-1b705fa7-c0fe-4f2f-a29d-367ba366e88e.png)

**If change .formLogin() to httpBasic() that will work. But how to realize it with .formLogin()?**

As said in [swagger.io](https://swagger.io/docs/specification/authentication) there are only 2 schemes(Bearer and Basic)

**Comment by yfath** [comment]
Any update on this issue ? This is a really important feature as most project uses form login...

**Comment by lawrence-pressinnov** [comment]
Any update or workaround would be much appreciated !

**Comment by bnasslahsen** [comment]
@lawrence-pressinnov,

You should be using` springdoc.show-login-endpoint=true` together with `springdoc-openapi-security`.
If you find out you are still facing the same issue, Provide a [Minimal, Reproducible Example - with HelloController](https://stackoverflow.com/help/minimal-reproducible-example) that reproduces the problem

**Comment by adrianbob** [comment]
Hi @bnasslahsen,
I have raised this issue: https://github.com/springdoc/springdoc-openapi/issues/1931
And created this repo with sample code: https://github.com/adrianbob/springdoc-form-login
The form login is not working.
