### ISSUE TITLE
Stream<T> does not transform to an array schema

### ISSUE THREAD

**Issue by sbstnzmr** [springdoc/springdoc-openapi#1715]
**Describe the bug**

Controller with return type Stream<T> will not produce a schema of [T...] but this:

Example Value:

```
{
  "parallel": true
}
```

**To Reproduce**

Return a Stream from a RestController

**Expected behavior**

The underlying type is considered in the schema, the Stream is handled as a List or Array.

**Comment by bnasslahsen** [comment]
@sbstnzmr, 

This can not be an Array in all cases...
