### ISSUE TITLE
javadoc of @JsonUnwrapped fields not set

### ISSUE THREAD

**Issue by shardt68** [springdoc/springdoc-openapi#1717]
- using springdoc-openapi-javadoc 1.6.9
- the controller contains a parameter or return type of type Foo
- Foo contains a field of type Bar which is annotated with @JsonUnwrapped
- the javadoc of the fields of Bar is not set to the output description

**To Reproduce**
download and unzip the sample project
[demo-springdoc-javadoc.zip](https://github.com/springdoc/springdoc-openapi/files/8956014/demo-springdoc-javadoc.zip)
run with 
mvn spring-boot:run
open
http://localhost:8080/swagger-ui/index.html
select Schema

**Expected behavior**
the javadoc of the Bar field should be set in the api-docs and hence will be displayed by swagger-ui

**Screenshots**
This is how it looks like
![grafik](https://user-images.githubusercontent.com/12643300/174985221-e5af2c7a-3ac9-4f71-a934-ea35c5b876dd.png)
This is how it should be (generated with the proposed solution)
![grafik](https://user-images.githubusercontent.com/12643300/174988032-1bd4d822-d4dc-4c5e-a0e4-41955fb0e46f.png)

**Solution proposal**
in org.springdoc.openapi.javadoc.JavadocPropertyCustomizer.setJavadocDescription(Class<?>, List<Field>, Schema)
the method should be called recursively for all types of fields annotated with @JsonUnwrapped

`fields.stream().filter(f -> f.isAnnotationPresent(JsonUnwrapped.class))
                    .forEach(f -> setJavadocDescription(f.getType(), FieldUtils.getAllFieldsList(f.getType()), existingSchema));`

**Comment by bnasslahsen** [comment]
@shardt68, 

As you have digged in the related line code, are you able to propose your PR?

**Comment by shardt68** [comment]
yes I would like to, but haven't done it on github yet, don't see the opportunity to create a branch, do you have to assign me?
