### ISSUE TITLE
Re-opeing (Issue#1869) - Child classes' fields are not propely getting added to the swagger spec schema

### ISSUE THREAD

**Issue by BhaveshSuvalaka** [springdoc/springdoc-openapi#1719]
I'm using spring-boot v2.6.7 and springdoc v1.6.9. Below is the object modeling. There's one endpoint that returns the Course as the response. Here the Course is supertype and the Child type is EnglishCourse also there's an items field on EnglishCourse which is a supertype of CourseItem and there are subtypes for it which are Folder, Lesson, and Test. I expect swagger spec to include a proper schema definition that includes all the fields for all the subtypes.

      package com.example.springdocdemo.domain
      
      import com.fasterxml.jackson.annotation.JsonSubTypes
      import com.fasterxml.jackson.annotation.JsonTypeInfo
      import io.swagger.v3.oas.annotations.media.Schema
      import java.util.UUID
      
      @JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.EXISTING_PROPERTY, property = "type")
      @JsonSubTypes(
          value = [
              JsonSubTypes.Type(value = EnglishCourse::class, name = "EnglishCourse")
          ]
      )
      abstract class Course {
          abstract val id: UUID
          abstract val name: String
          abstract val code: String
      }
      
      class EnglishCourse(
          val items: List<CourseItem>,
          override val id: UUID,
          override val code: String,
          override val name: String,
      ) : Course()
      
      @JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.EXISTING_PROPERTY, property = "type")
      @JsonSubTypes(
          value = [
              JsonSubTypes.Type(value = Folder::class, name = "FOLDER"),
              JsonSubTypes.Type(value = Lesson::class, name = "LESSON"),
              JsonSubTypes.Type(value = Test::class, name = "TEST")
          ]
      )
      @Schema(discriminatorProperty = "type", allOf = [Folder::class, Lesson::class, Test::class])
      interface CourseItem {
          val type: CourseItemType
          val id: UUID
      }
      
      @Schema
      class Folder(
          val items: List<CourseItem>,
          override val id: UUID,
          override val type: CourseItemType,
      ) : CourseItem {
          fun items() = println(items)
      }
      
      class Lesson(
          val name: String,
          override val id: UUID,
          override val type: CourseItemType,
      ) : CourseItem
      
      class Test(
          val name: String,
          override val id: UUID,
          override val type: CourseItemType,
      ) : CourseItem
      
      enum class CourseItemType {
          Folder, Lesson, Test
      }

And the below is the generated schema definition for the Folder type:

    "Folder": {
         "required": [
           "id",
           "type"
         ],
         "type": "object",
         "allOf": [
           {
             "$ref": "#/components/schemas/CourseItem"
           }
         ]
       },

it includes "id" and "type" only but "items" field is missing. Is there any solution for this? The code can be found here: https://github.com/BhaveshSuvalaka/springdoc-issue

Generated schema using model converted as suggested by @bnasslahsen:
Below is the generated generated schema for folder :

```
  Folder=class Schema {
      type: object
      format: null
      $ref: null
      description: null
      title: null
      multipleOf: null
      maximum: null
      exclusiveMaximum: null
      minimum: null
      exclusiveMinimum: null
      maxLength: null
      minLength: null
      pattern: null
      maxItems: null
      minItems: null
      uniqueItems: null
      maxProperties: null
      minProperties: null
      required: [id, items, type]
      not: null
      properties: {items=class ArraySchema {
          class Schema {
              type: array
              format: null
              $ref: null
              description: null
              title: null
              multipleOf: null
              maximum: null
              exclusiveMaximum: null
              minimum: null
              exclusiveMinimum: null
              maxLength: null
              minLength: null
              pattern: null
              maxItems: null
              minItems: null
              uniqueItems: null
              maxProperties: null
              minProperties: null
              required: null
              not: null
              properties: null
              additionalProperties: null
              nullable: null
              readOnly: null
              writeOnly: null
              example: null
              externalDocs: null
              deprecated: null
              discriminator: null
              xml: null
          }
      }, id=class UUIDSchema {
          class Schema {
              type: string
              format: uuid
              $ref: null
              description: null
              title: null
              multipleOf: null
              maximum: null
              exclusiveMaximum: null
              minimum: null
              exclusiveMinimum: null
              maxLength: null
              minLength: null
              pattern: null
              maxItems: null
              minItems: null
              uniqueItems: null
              maxProperties: null
              minProperties: null
              required: null
              not: null
              properties: null
              additionalProperties: null
              nullable: null
              readOnly: null
              writeOnly: null
              example: null
              externalDocs: null
              deprecated: null
              discriminator: null
              xml: null
          }
      }, type=class StringSchema {
          class Schema {
              type: string
              format: null
              $ref: null
              description: null
              title: null
              multipleOf: null
              maximum: null
              exclusiveMaximum: null
              minimum: null
              exclusiveMinimum: null
              maxLength: null
              minLength: null
              pattern: null
              maxItems: null
              minItems: null
              uniqueItems: null
              maxProperties: null
              minProperties: null
              required: null
              not: null
              properties: null
              additionalProperties: null
              nullable: null
              readOnly: null
              writeOnly: null
              example: null
              externalDocs: null
              deprecated: null
              discriminator: null
              xml: null
          }
      }}
      additionalProperties: null
      nullable: null
      readOnly: null
      writeOnly: null
      example: null
      externalDocs: null
      deprecated: null
      discriminator: null
      xml: null
  }
```

Here folder contains the items but it's not present in generated API spec. The earlier thread can be found here https://github.com/springdoc/springdoc-openapi/issues/1689

**Comment by bnasslahsen** [comment]
@BhaveshSuvalaka,

Not reproducible

![image](https://user-images.githubusercontent.com/13404829/182003092-27e52278-9778-496c-8368-29393a044690.png)

**Comment by BhaveshSuvalaka** [comment]
@bnasslahsen it would be a great help if you could share the code for the above test, I'm still facing the issue. Thanks in Advance.

**Comment by bnasslahsen** [comment]
@bnasslahsen,

The code is in your own repo: https://github.com/BhaveshSuvalaka/springdoc-issue

**Comment by BhaveshSuvalaka** [comment]
That's strange @bnasslahsen, when I'm trying I am able to reproduce :(
