### ISSUE TITLE
swaggerUiConfigParameters.setUrls always automatically prefixes the URL /v3/api-docs/

### ISSUE THREAD

**Issue by 1455668754** [springdoc/springdoc-openapi#1724]
If I set swaggerUiConfigParameters.setUrls，But when I open the browser, it always automatically prefixes the URL /v3/api-docs/；
I debugged the logic and found that it always executes the following code to replace the manually set URL
`	
	/**
	 * Add url.
	 *
	 * @param url the url
	 */
	public void addUrl(String url) {
		this.urls.forEach(elt ->
				{
					if (!isSwaggerUrlDefined(elt.getName()))
						elt.setUrl(url + DEFAULT_PATH_SEPARATOR + elt.getName());
				}
		);
	}
`
This is not correct. When integrating the gateway, it will lead to failure to forward to the correct service. If you do so, swaggeruiconfigparameters The seturl method in seturls has no value
![image](https://user-images.githubusercontent.com/88491446/175865723-c79ff101-0673-4b23-8a4c-161cc2912c34.png)
I think we should remove the Addurl method so that the user-defined seturl method can take effect normally

**Comment by bnasslahsen** [comment]
Provide a [Minimal, Reproducible Example - with HelloController](https://stackoverflow.com/help/minimal-reproducible-example) that reproduces the problem
