### ISSUE TITLE
Missing $ref usage on the documentation

### ISSUE THREAD

**Issue by infoShare** [springdoc/springdoc-openapi#1725]
**Describe the bug**
API Docs are not always generating $ref on the documentation (like on anotherFixedData). Sometimes full model is copied (fixedData below)

**To Reproduce**
- What version of spring-boot you are using? 2.7.0
- What modules and versions of springdoc-openapi are you using? 1.6.9
- What is the actual and the expected result using OpenAPI Description (yml or json)? JSON

**Expected behavior**
Use $ref on the documentation. For example:

"anotherFixedData": {
     "$ref": "#/components/schemas/AnotherFixedData"
}

**Instead of:**

"fixedData": {
	"description": "Fixed data model",
	"additionalProperties": {
		"description": "Fixed data model",
		"type": "object",
		"example": {
			"fixKey": "fixValue"
		}
	},
	"type": "object",
	"example": {
		"fixKey": "fixValue"
	}
}

Both classes (FixedData and AnotherFixedData) have the same annotations:
@Schema(name = "FixedData", description = "Fixed data model")

Are there any other required annotations/properties to enable always using $ref ?

**Comment by bnasslahsen** [comment]
see the F.A.Q how you can set ref samples for objects: https://springdoc.org/#how-can-i-define-different-schemas-for-the-same-class

**Comment by infoShare** [comment]
We have only one model, not multiple ones. But because it's implementing Map interface reference is displayed incorrectly (copy of the model in all places in documentation instead of using reference to single schema)

**Comment by bnasslahsen** [comment]
Use the same logic for multiple models.
Declare `$ref` in all your schemes.
And declare your model programmatically as mentioned in the link above.
