### ISSUE TITLE
Support Java record for @ParameterObejct annotation

### ISSUE THREAD

**Issue by min27604** [springdoc/springdoc-openapi#1728]
When using `@ParameterObject` on java record class, individual fields are not showing on swagger-ui.
As far as I know, swagger shows all the parameter needed as long as there are getters for the fields and for record, java compiler automatically produces getter for all the fields.
Is this a bug or there's something I need to know to use ParameterObject annotation on java record?

**Comment by bnasslahsen** [comment]
@bnasslahsen,

This is an enhancement, and will be available in v2.0.0-M4.
