### ISSUE TITLE
Example/Docs support for custom converters (EG: RxJava Observable)

### ISSUE THREAD

**Issue by OmriYaHoo** [springdoc/springdoc-openapi#1730]
In a project I'm working on we are using RxJava Observable with `spring-hateoas`, not Flux or Mono by the Spring team Webflux module.

When the responses from the controllers are returning `Observable` (of ResponseEntity) we can't see it properly in the swagger-ui.
I tried to search the docs but couldn't find a way to solve it.
I tried to look at the demos of [springdoc-hateoas](https://github.com/springdoc/springdoc-openapi-demos/tree/master/springdoc-openapi-hateoas-service) and [springdoc-webflux](https://github.com/springdoc/springdoc-openapi-demos/tree/master/springdoc-openapi-spring-boot-2-webflux) but I didn't see special configuration done except for adding the required modules `springdoc-openapi-webflux-ui` and `springdoc-openapi-hateoas`.

Our swagger-ui was showing the models like this:
![image](https://user-images.githubusercontent.com/5871199/177306510-9642d5d1-139c-4e14-a40f-5898fa39d660.png)

To solve our issue I ended up searching the source code to see how it's [done for Flux](https://github.com/springdoc/springdoc-openapi/blob/master/springdoc-openapi-webflux-core/src/main/java/org/springdoc/webflux/core/converters/WebFluxSupportConverter.java) since Flux's main purpose is similar to RxJava Observable.

After implementing the following converter in the **demo code of hateoas** it's working fine.
I figure I should first try to make it work with the demo since it's much simpler than our big application with multiple other configurations.

```java
@Component
public class MuServiceObservableConvertor implements ModelConverter {

    private final ObjectMapperProvider objectMapperProvider;

    public MuServiceObservableConvertor(ObjectMapperProvider objectMapperProvider) {
        this.objectMapperProvider = objectMapperProvider;
        getConfig().addResponseWrapperToIgnore(Observable.class);
    }

    @Override
    public Schema resolve(AnnotatedType type, ModelConverterContext context, Iterator<ModelConverter> chain) {
        JavaType javaType = objectMapperProvider.jsonMapper().constructType(type.getType());
        if (javaType != null) {
            Class<?> cls = javaType.getRawClass();
            if (Observable.class.equals(cls)) {
                JavaType innerType = javaType.getBindings().getBoundType(0);
                if (innerType == null)
                    return new StringSchema();
                else if (innerType.getBindings() != null && isResponseTypeWrapper(innerType.getRawClass())) {
                    type = new AnnotatedType(innerType).jsonViewAnnotation(type.getJsonViewAnnotation()).resolveAsRef(true);
                    return this.resolve(type, context, chain);
                } else {
                    ArrayType arrayType = ArrayType.construct(innerType, null);
                    type = new AnnotatedType(arrayType).jsonViewAnnotation(type.getJsonViewAnnotation()).resolveAsRef(true);
                }
            }
        }
        return (chain.hasNext()) ? chain.next().resolve(type, context, chain) : null;
    }

}
```
It's basically just copying and pasting the convertor of the Flux object with minor changes.

Implementing the same convertor in our service had a different effect.
We now see the attributes in the swagger-ui like this:
![image](https://user-images.githubusercontent.com/5871199/177307189-e367ff91-7a81-419b-800d-3fcd905bbf3f.png)
Instead of like this: (image taken from the `springdoc-heteoas` swagger-ui after wrapping the `ResponseEntity` with `Observable`)
![image](https://user-images.githubusercontent.com/5871199/177307335-78bc9092-9934-4f07-b6bf-5c2726c54c54.png)
The goal is for the swagger-ui to describe an object like this - **Observable<ResponseEntity<CollectionModel<EntityModel<ExampleModel>>>>**

The feature request is to provide an example of how to implement a convertor with more than just a basic configuration (I only saw how to set configuration regarding converters in the docs, not actually writing one), especially if generics are involved.
This could be in the docs as well as a reference to one of the demo repositories.

I'm still trying to understand why our application is behaving differently than the springdoc-hateoas demo.
Could you please assist/explain?

Additional context:
We are in the process of moving from `swagger2` with `springfox` to `OpenAPI` with `springdocs`.

**Comment by bnasslahsen** [comment]
@OmriYaHoo,

Which springdoc dependencies are you using ?

Try Providing a [Minimal, Reproducible Example - with HelloController](https://stackoverflow.com/help/minimal-reproducible-example) that reproduces the problem.

**Comment by bnasslahsen** [comment]
This ticket will be closed and can be reopened if any relevant updates are provided.
