### ISSUE TITLE
1.6.10 Release Date?

### ISSUE THREAD

**Issue by jakoberpf** [springdoc/springdoc-openapi#1732]
Hello Devs,

we would like to use `springdoc-openapi-ui` but are currently using on the kickstart graphql library as well. Is there any date on when the could be a new release which contains this fix? https://github.com/springdoc/springdoc-openapi/commit/4e6442619f697a61d632c2dc239f1d447e1dc614

Sorry for the new issue, didn't find a related issue.

Thank you guys very much.

**Comment by bnasslahsen** [comment]
@jakoberpf,

At the latest August 14th
