### ISSUE TITLE
SecurityScheme Extensions No Longer Working

### ISSUE THREAD

**Issue by ANTANISolutions** [springdoc/springdoc-openapi#1738]
As of Spring Boot v2.7.1 and OpenAPI v1.6.9 you can no longer add extensions to io.swagger.v3.oas.models.security.SecurityScheme and they be successfully rendered in the JSON output. They are now silently excluded from the JSON. 

This was previously working in Spring Bootv 2.6.6 with OpenAPI v1.6.8. I have tested extensions in other areas, e.g. directly on flows or flow, and this functionality is still working. This issue appears to be only broken in:

`io.swagger.v3.oas.models.security.SecurityScheme`

Example Java Config:

        OAuthFlows flows = new OAuthFlows();

        // Add Authorization Flow
        OAuthFlow flow = new OAuthFlow();
        flow.setAuthorizationUrl(authConfig.getAuthorizationEndpoint());
        flow.setTokenUrl(authConfig.getTokenEndpoint());
        flows = flows.authorizationCode(flow);

        // Create Security Scheme
        SecurityScheme oauthScheme = new SecurityScheme()
                .type(SecurityScheme.Type.OAUTH2)
                .flows(flows)
                .description("SSO OpenID Authentication");
        
        // Add Extensions for UI Config (TODO: Currently Broken as of Spring Boot v2.7.1 and OpenApi v1.6.9)
        oauthScheme.addExtension("x-client-id", securityProperties.getClient());
        oauthScheme.addExtension("x-receive-token-in", "request-body");

JSON Output Example (condensed for readability):

    {
      "openapi": "3.0.1",
      "info": {},
      "servers": [],
      "tags": [],
      "paths": {},
      "components": {
        "schemas": {},
        "securitySchemes": {
          "Auth-SSO": {
            "type": "oauth2",
            "description": "SSO OpenID Authentication",
            "flows": {
              "authorizationCode": {
                "authorizationUrl": "https://example.com/oauth2/authorize",
                "tokenUrl": "https://example.com/oauth2/token"
              }
            }
          }
        }
      }
    }

**Comment by bnasslahsen** [comment]
This is related to `swagger-core 2.2.1` and not implemented in springdoc-opanapi.
