### ISSUE TITLE
Update release info 1.6.9 - breaking change introduced in #1641

### ISSUE THREAD

**Issue by MichalStehlikCz** [springdoc/springdoc-openapi#1739]
Fix for #1641 introduced breaking change as public method OpenAPIService#getCalculatedOpenApi was removed.

I assume it can be replaced with new version of build that now returns OpenAPI, but such change is unexpected in patch revision and I believe it should be at least mentioned in release notes to make migration easier

**Comment by MichalStehlikCz** [comment]
Also I have some trouble converting older code that used OpenApiBuilderCustomizer - before, it was possible to use getCalculatedOpenApi and modify it in OpenApiBuilderCustomizer

Now build calls customize method on all OpenApiBuilderCustomizer beans, but only passes OpenAPIService. I believe that call on line 276 of OpenAPIService makes no sense, because all settings on OpenAPIService were already applied when building OpenAPI and OpenAPI being built itself is not available as it is now local variable in build method

**Comment by bnasslahsen** [comment]
@MichalStehlikCz, 

Provide a [Minimal, Reproducible Example - with HelloController](https://stackoverflow.com/help/minimal-reproducible-example) that shows the problem...
Or propose directly a PR.
