### ISSUE TITLE
services/v3/api-docs/swagger-config  404

### ISSUE THREAD

**Issue by rhu25** [springdoc/springdoc-openapi#1741]
because we have a setting like this

on local
api is like
https://localhost:8081/swagger-ui/index.html
but on production

api is triggered via ui proxy

https://abc.com/services/swagger-ui/index.html 

https://abc.com/services/services/v3/api-docs/swagger-config return 404
but on ui page,

how can i config this swagger setting

**Comment by antechrestos** [comment]
Maybe same as #1419?

**Comment by bnasslahsen** [comment]
@rhu25,

See https://springdoc.org/#how-can-i-deploy-springdoc-openapi-ui-behind-a-reverse-proxy
