### ISSUE TITLE
SpringDoc disable auto tagging based on path

### ISSUE THREAD

**Issue by KeerthigaMargesan4** [springdoc/springdoc-openapi#1750]
I need to disable auto tagging of APIs based on codegen generated controller API, I tried using 
springdoc.auto-tag-classes: false in my application.yml but still I am getting APIs tagged in my custom tag as well as in controller api tag.

**Comment by bnasslahsen** [comment]
Provide a [Minimal, Reproducible Example - with HelloController](https://stackoverflow.com/help/minimal-reproducible-example) that reproduces the problem
