### ISSUE TITLE
Can i controller schema order with same property?

### ISSUE THREAD

**Issue by lntuition** [springdoc/springdoc-openapi#1757]
**Is your feature request related to a problem? Please describe.**
I have below use case

1. using replaceWithSchema at configuration
``` kotlin 
    init {
        SpringDocUtils
            .getConfig()
            .replaceWithSchema(
                UserId::class.java,
                Schema<UserId>().apply {
                    description = "default description"
                    type = "integer"
                }
            )
    }
```
- because this type is so widely using, so i want to apply common schema by type

2. but sometimes i need to override schema because it need more detail description
``` kotlin
data class TwoUserIds(
  val userId: UserId,
  @Schema(description = "detail description", type = "integer")
  val otherUserId: UserId
)
```

but i couldn't find a way to control annotation processing order.

**Describe the solution you'd like**
- add some property to control annotation process order (maybe filed name is order?)
- Alternatively, annotation that having detail scope may impliclity applied later

**Comment by bnasslahsen** [comment]
These annoations are coming from to the swagger-core library and not springdoc-openapi.
