### ISSUE TITLE
springdoc.api-docs.enabled=false disabling whole swagger UI page

### ISSUE THREAD

**Issue by shivaprasadgurram** [springdoc/springdoc-openapi#1758]
**Describe the bug**
I'm using springdoc-openapi-ui version 1.6.9, My intension is to load custom **yaml** file into swagger UI page for that I used springdoc.api-docs.enabled=false property followed by springdoc.swagger-ui.url=/openapi-spec.yaml but whole swagger UI page got disabled.

**To Reproduce**
- What version of spring-boot you are using?
      - 2.5.12
- What modules and versions of springdoc-openapi are you using?
      - 1.6.9
- What is the actual and the expected result using OpenAPI Description (yml or json)?
      - Actually it should load custom yaml file and disable default "api-docs" but it is not even loading swagger UI page when I disable api-docs using above property.
- Provide with a sample code (HelloController) or Test that reproduces the problem
     - NA

**Expected behavior**
- Actually it should load custom yaml file and disable default "api-docs" but it is not even loading swagger UI page when I disable api-docs using above property.

**Screenshots**

**Additional context**
I already followed https://github.com/springdoc/springdoc-openapi/issues/358 and https://github.com/springdoc/springdoc-openapi/issues/389 but none of them helped me.

**Comment by bnasslahsen** [comment]
@shivaprasadgurram,

Read the F.A.Q https://springdoc.org/#what-is-a-proper-way-to-set-up-swagger-ui-to-use-provided-spec-yml
