### ISSUE TITLE
Missing Response Content

### ISSUE THREAD

**Issue by sjw0010** [springdoc/springdoc-openapi#176]
Hello there. I am using version 1.1.48 and trying to get it integrated into a very simple existing Spring Boot Rest Web Service. The documentation seems to generate fine for the most part, but it doesn't pick up the Response Content Types. So it defaults them to "*/*". Instead of putting a @RequestMapping annotation at the top of every Controller that specifies "produces = {"application/xml"}", I am using a Meta-Annotation with the restrictions in there. The code for the Meta-Annotation is simple and below, in case that helps (sorry in advance for the formatting):

@Target({ElementType.METHOD, ElementType.TYPE})
@Retention(RetentionPolicy.RUNTIME)
@RequestMapping()
public @interface BaseController{
    @AliasFor(annotation = RequestMapping.class)
    String[] value() = default {};
    
    @AliasFor(annotation = RequestMapping.class)
    String[] produces() = default {MediaType.APPLICATION_XML_VALUE};
}

So I guess I am curious as to why openapi doesn't pick that XML Content Type up. 

Thanks

**Comment by springdoc** [comment]
Hi, 

 You can just pick the last version v1.2.9. 
 This feature was added since  v1.2.8.

**Comment by sjw0010** [comment]
I am sorry for taking so long to get back to you, but I don't think that is completely accurate. Or maybe we are on two different pages. I upgraded to the newest version and it behaves the same way. I will try to clarify a little better:

I am working in a very simple example. My pom has the springdoc-openapi-ui dependency as needed:
```
<dependency>
    <groupId>org.springdoc</groupId>
    <artifactId>springdoc-openapi-ui</artifactId>
    <version>1.2.10</version>
</dependency>
```

My Meta-Annotation looks like the following:
```
@Target({ElementType.METHOD, ElementType.TYPE})
@Retention(RetentionPolicy.RUNTIME)
@RestController
@RequestMapping
public @interface BaseController {
    @AliasFor(annotation = RequestMapping.class)
    String[] value() default {};

    @AliasFor(annotation = RequestMapping.class)
    String[] produces() default {MediaType.APPLICATION_XML_VALUE, MediaType.APPLICATION_JSON_VALUE};
}
```

And finally, my test controller references and uses the Meta-Annotation like so:
```
@BaseController
@Tag(name = "Test Controller")
public class TestController {
    
    @GetMapping("/test")
    @Operation(summary = "This is the test endpoint")
    public String test(@RequestHeader("Accept") String accept) {
        return "This is a test";
    }
}
```

The application runs just fine and the Accept header is restricted to only allow Json and Xml like it should, but the documentation doesn't pick it up properly. It only shows the wildcard in the Swagger UI. I have attached an image showing what it looks like. 
![Capture](https://user-images.githubusercontent.com/1436871/69648885-c8692f80-1031-11ea-88cf-06a93e9f4bca.PNG)

As you can see, that drop down that shows the valid Accept header values only shows "'*/\*", which is obviously misleading to a user. 

Now, if I stop using Meta-Annotations and just include the @RequestMapping(produces = {MediaType.APPLICATION_XML_VALUE, MediaType.APPLICATION_JSON_VALUE}) at the top of the TestController, everything generates properly in the documentation. But I would very much like to use Meta-Annotations.

Any help would be appreciated.

Thanks
