### ISSUE TITLE
Excuse me, is there a springfox pathMapping function, and I want to add a prefix to all interface paths

### ISSUE THREAD

**Issue by JavaLionLi** [springdoc/springdoc-openapi#1760]
**Is your feature request related to a problem? Please describe.**
- A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
- What is the actual result using OpenAPI Description (yml or json)?

**Describe the solution you'd like**
- A clear and concise description of what you want to happen.
- What is the expected result using OpenAPI Description (yml or json)?

**Describe alternatives you've considered**
- A clear and concise description of any alternative solutions or features you've considered.

**Additional context**
- Add any other context or screenshots about the feature request here.

**Comment by bnasslahsen** [comment]
Try describing your feature ...
