### ISSUE TITLE
Exception documenting RestControllerEndpoint with PostMapping

### ISSUE THREAD

**Issue by p120ph37** [springdoc/springdoc-openapi#1761]
When a `@RestControllerEndpoint` bean defines a `@PostMapping` method and `springdoc-openapi` tries to  introspect it, the following exception is thrown:

```
java.lang.NullPointerException: Cannot invoke "java.lang.reflect.Field.get(Object)" because "operationFiled" is null
        at org.springdoc.core.customizers.ActuatorOperationCustomizer.customize(ActuatorOperationCustomizer.java:84) ~[springdoc-openapi-common-1.6.9.jar:1.6.9]
```

This is the line in question: [v1.6.9 ActuatorOperationCustomizer.java L84](https://github.com/springdoc/springdoc-openapi/blob/v1.6.9/springdoc-openapi-common/src/main/java/org/springdoc/core/customizers/ActuatorOperationCustomizer.java#L84)

This seems to have been introduced in this commit: 6ce3b5abed24ec6676783519488b1a5a13c52e93

The issue is present in version 1.6.7 and later.  Reverting to version 1.6.6 fixes it for me.

**Comment by bnasslahsen** [comment]
@p120ph37,

I have added a fix, just from coding perspective;
But was not able to reproduce your error. I are able to propose a PR, with the related test case, it would be great.
