### ISSUE TITLE
How to configure response of Map<String, Any> easily with ApiResponse

### ISSUE THREAD

**Issue by jayZipCo** [springdoc/springdoc-openapi#1762]
I have multiple endpoints that return Map as response (I know that's not the ideal way but it is legacy code). Im thinking if there is a way that I can customize the schema so it can represent different Map Response.
For example
Test1Schema
Test2Schema

```
@ApiResponses(
	ApiResponse(responseCode = "200", content = [Content(schema = Test1Schema())])
	)
@GetMapping("/test", produces = [MediaType.APPLICATION_JSON_VALUE])
fun getConnectionsSummary(): Map<String, Any>

@ApiResponses(
	ApiResponse(responseCode = "200", content = [Content(schema = Test2Schema())])
)
@GetMapping("/test1", produces = [MediaType.APPLICATION_JSON_VALUE])
fun getConnectionsSummary(): Map<String, Any>

```

Or even better if I can define within annotation
```
@ApiResponses(
	ApiResponse(responseCode = "200", content = [Content(schema = Schema({
       "name" to StringSchema
})])
)
@GetMapping("/test1", produces = [MediaType.APPLICATION_JSON_VALUE])
fun getConnectionsSummary(): Map<String, Any>
```
Please let me know what is the best way to annotate Map response

**Comment by jayZipCo** [comment]
Any help please?

**Comment by bnasslahsen** [comment]
@jayZipCo, 

You can definetly use `@ApiResponse` annotation.
Please see swagger-annotations documentation instead; 
https://github.com/swagger-api/swagger-core/wiki/Swagger-2.X---Annotations

**Comment by jayZipCo** [comment]
@bnasslahsen thanks for your reply. I couldn't seem to find what Im expecting.
I know we can
`schema = @Schema(implementation = Pet.class)`
but that means we need to create a class every time for different Map response.
Or the other way that I found
```
val petSchema = Schema<Map<String, Any>>()
	.addProperties("timestamp", StringSchema())
	.addProperties("status", IntegerSchema())
	.addProperties("error", StringSchema())
	.addProperties("exception", StringSchema())
	.addProperties("message", StringSchema())
	.addProperties("path", StringSchema())

return OpenAPI().components(Components().addSchemas("PetMap", petSchema))
```
But just wondering if there is a more simpler approach?
