### ISSUE TITLE
Spring Doc Open API shows invalid field name on swagger ui

### ISSUE THREAD

**Issue by vadymdoroshevych** [springdoc/springdoc-openapi#1764]
There is an invalid model shown on swagger UI when there is only one lowercase letter at the beginning of the field name.

My Kotlin model:

```
class TrendEvaluationModel(
    val xAxisValue: Int,
    val yAxisValue: Int,
    val customValue: Int?
)
```
What is shown on swagger UI:

```
{
  "customValue": 1,
  "xaxisValue": 1,
  "yaxisValue": 1
}
```

I've tried:

1. @Parameter annotation with specified name attribute but it does not work.
2. @Schema annotation with specified name attribute but it does not work.
3. @JsonProperty("xAxisValue") and it worked but not as expected - the model on swagger showed two fields then (xaxisValue and xAxisValue) but I need only one of them (xAxisValue).

Appreciate your help.

NOTE: There is no issue if there are two or more lowercase letters at the beginning of the field name

**Comment by bnasslahsen** [comment]
@vadymdoroshevych,

You need to instruct ObjectMapper to generate JSON properties based on fields and not based on getter methods. You can use com.fasterxml.jackson.annotation.JsonAutoDetect annotation:

```
@JsonAutoDetect(getterVisibility = JsonAutoDetect.Visibility.NONE, fieldVisibility = JsonAutoDetect.Visibility.ANY)
class TrendEvaluationModel(
	val xAxisValue: Int,
	val yAxisValue: Int,
	val customValue: Int?
)
```

**Comment by lucianiz** [comment]
@bnasslahsen  I have the same problem (but in java) , but just to note the request is correct on the jackson side, if I send the request using xaxisValue the value is not changed, the api is also returning the correct xAxisValue so jackson does expect xAxisValue,  so just the documentation in wrong, just the springdocs-openapi part. 

Can we reopen this issue?

@vadymdoroshevych did you find a way how to fix this?

**Comment by bnasslahsen** [comment]
@lucianiz,

Make sure you Provide a [Minimal, Reproducible Example - with HelloController](https://stackoverflow.com/help/minimal-reproducible-example) that reproduces the problem
