### ISSUE TITLE
Cant access the localhost:8080/app/swagger-ui.html but app/v3/api-docs working 

### ISSUE THREAD

**Issue by daniyal-mujtaba-paysys** [springdoc/springdoc-openapi#1766]
Hello. I know this is not an issue but I needed help and didnt know what to do or how to approach the creators. 

So I have followed all the steps from documention on migration from springfox. but I cant seem to access the swagger-ui as its shows a blank empty page 

Steps => 
Hit localhost:8080/appname/swagger-ui.html it redirects to appname/swagger-ui/index.html and below screenshot represent how the page looks 
![index-html](https://user-images.githubusercontent.com/108521126/181297600-85a8e9f6-9204-46f3-a3a8-1e47fd206a0a.png)

If I try to access the indvidual api json by hitting localhost:8080/appname/controller
It throws 404 

Screenshot for better idea 

![STATUS 404](https://user-images.githubusercontent.com/108521126/181297972-b947567f-f6ae-46c3-bc07-dbf9449a491c.png)

But i am able to access the v3/api-docs and the information in the returned json is accurated (tested on editor.swagger.io)

I am using 1.6.9 on spring boot application on jdk11 and maven 3.8.6. 
My server is apache tomcat 9.0.36 

my application.yml contains following entries 
springdoc:
  pathsToMatch: /api/**
  writer-with-default-pretty-printer: true
  swagger-ui:
    disable-swagger-default-url: true

**Comment by bnasslahsen** [comment]
Just review your conf...
See the [demos ](https://springdoc.org/#demos)code that is just wroking fine.
