### ISSUE TITLE
Generated Swagger file not correct with nested JsonSubtypes

### ISSUE THREAD

**Issue by spacefusion** [springdoc/springdoc-openapi#1768]
Hello,
It seems that nested JsonSubtypes are not properly generated. I am not 100% sure if this is a bug or if i just missed some configuration for this.

**How to Reproduce**
Lets assume we have a Animal Classifier interface with 2 Subtypes, Dog and Cat Classifier:
```
@JsonTypeInfo(
    use = JsonTypeInfo.Id.NAME,
    include = JsonTypeInfo.As.PROPERTY,
    property = "type",
)
@JsonSubTypes(
    JsonSubTypes.Type(value = DogClassifier::class, name = "DogClassifier"),
    JsonSubTypes.Type(value = CatClassifier::class, name = "CatClassifier")
)
interface AnimalClassifier
```

The DogClassifier has an Abstract DogClass with JsonSubTypes:
```
class DogClassifier(
    val databaseId: String,
    val dogClassInfo: AbstractDogClass
) : AnimalClassifier {
}
--------------------

@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "type")
@JsonSubTypes(
    JsonSubTypes.Type(value = Husky::class, name = "Husky"),
    JsonSubTypes.Type(value = Bulldog::class, name = "Bulldog"))
abstract class AbstractDogClass() {
}

```

when we now create an AnimalRestController to fetch the AnimalClassifiers:
```
@RequestMapping("/api")
@RestController
class AnimalController {
    @GetMapping(value = ["/AnimalClassifiers"])
    // if return type is "DocClassifier" the AbstractDocClass subtypes are resolved correctly!!
    fun getAnimalClassifier(name: String): AnimalClassifier {
        return DogClassifier("id",Husky("my husky","unknown"))
    }
}
```
For a return type "AnimalClassifier" we get following output:
![Screenshot from 2022-07-28 09-25-19](https://user-images.githubusercontent.com/97979250/181447527-16e683c1-6f83-4d84-857f-98dd9dd901c6.png)
here I only get the "AbstractDogClass" for the "dogClassInfo" property

But if I directly return a "DogClassifier", the "docClassInfo" is correctly resolved 

![Screenshot from 2022-07-28 09-24-17](https://user-images.githubusercontent.com/97979250/181447521-70e132c8-165a-4a06-8c1f-ed03c1e53ba3.png)

**Expected behavior**
For the RestController returning the "AnimalClassifier" type i would expect the dogClassInfo to be also resolved to "Husky" and "Bulldog", as in the case of resolving DogClassifier directly.
For me it seems that only the first level of abstraction is resolved correctly, but i would expect if for every level.

**Additional context**
I uploaded a sample application that shows the above described problem.
[AnimalClassifier.zip](https://github.com/springdoc/springdoc-openapi/files/9206795/AnimalClassifier.zip)

**Comment by bnasslahsen** [comment]
@spacefusion, 

You can get the Husky type displayed by adding:

```properties
springdoc.remove-broken-reference-definitions=false
```

**Comment by spacefusion** [comment]
@bnasslahsen sorry I just tried it and it still makes no difference.

Seems that i can not fix it with this parameter. The generated schemas are exactly the same with and without the parameter.

Tried it with an application.properties file and 
also to set the property directly from the main class e.g. (System.setProperty("springdoc.remove-broken-reference-definitions","false")


Any other suggestions?

**Comment by MartinHaeusler** [comment]
For future reference, the fix for us was to add the `springdoc-openapi-kotlin` dependency. Our DTOs are written in kotlin, and without this module, some `@JsonSubTypes` annotations were simply ignored (as shown in our example). With this additional dependency, the schema is generated correctly.

**Comment by pinguinjkeke** [comment]
I'm facing the same issue. subtypes of other subtypes aren't generated
