### ISSUE TITLE
Springfox Migration: OperationBuilderPlugin / ParameterBuilderPlugin

### ISSUE THREAD

**Issue by rowi1de** [springdoc/springdoc-openapi#1769]
As people migrate from Springfox to Springdoc due to better maintainance, there is one open question::
https://github.com/springfox/springfox/blob/master/docs/asciidoc/extensibility.adoc SpringFox as an SPI Module with Plugin API that can be used to customise the Swagger Model.

Is there something similar in Springdoc?

**Comment by bnasslahsen** [comment]
This is the list of available customizers:

- https://github.com/springdoc/springdoc-openapi/tree/master/springdoc-openapi-common/src/main/java/org/springdoc/core/customizers

For example, `ParameterCustomizer `to customize a parameter based on the parameter and handler method input.

See Javadoc of each one for details. You can achieve, most of what is described in your link.
