### ISSUE TITLE
Mapping of Pageable-Object to correct URL-Parameter in Swagger UI

### ISSUE THREAD

**Issue by Metanoia23** [springdoc/springdoc-openapi#177]
If you create an api-documentation with springdoc-openapi for a spring-data-rest application, that exposes the Pageable-Object as api-parameter, like this:
```java
 @RequestMapping(value = "/search",
            method = RequestMethod.GET)
public Page<ResultEntry> searchAll(@RequestParam(value = "q", required = false) String query,
                                                @PageableDefault(page = 0, size = 10) Pageable pageable) {
        return searchService.findByAuthorId(query, pageable);
    }
```
then there is a problem, because the spring-data library converts the Pagable attributes into url-parameter (like documented here: https://github.com/spring-projects/spring-data-rest/blob/master/src/main/asciidoc/paging-and-sorting.adoc) but in the Swagger UI there is only the Pageable object as parameter with the Java-Attributes (pageNumber, pageSize, sorted,...) names and not the Url-Parameter (page,size,offset, sort) names as separate parameter fields.
![pageable-object-in-swagger](https://user-images.githubusercontent.com/9010983/69425690-b6cf1180-0d2b-11ea-9cbd-c4fa0bae5c9c.png)
Therefore there is no possibilty to make a valid Test-Request with the swagger-ui. Could you please add support for the pageable object in the springdoc-openapi? 

In Springfox, there is a workaround for this problem: https://github.com/springfox/springfox/issues/2623

**Comment by springdoc** [comment]
Hi, 

 The support for Pageable of spring-data-rest is now added on v1.2.11.

 The projects that uses spring-data-rest should add this dependency together with the springdoc-openapi-ui dependency:
```xml
  <dependency>
            <groupId>org.springdoc</groupId>
            <artifactId>springdoc-openapi-data-rest</artifactId>
            <version>1.2.11</version>
 </dependency>
 ```

**Comment by NicklasWallgren** [comment]
@springdoc Great contribution! But we're still having issues with `Pageable`. 

Version: 1.2.17

The pageable-parameters are passed as
`offset=0&pageNumber=0&pageSize=0&sort=sorted,true,unsorted,true,empty,true&paged=true&unpaged=true`

![image](https://user-images.githubusercontent.com/1784879/70525983-dbf3ba80-1b48-11ea-8f9d-2606f1418cb9.png)

**Comment by Majlanky** [comment]
Hello,

I was not able to find the solution anywhere in the documentation. If you want to pageable behave as a set of standard parameters you **have to  add dependency** of `springdoc-openapi-data-rest` to your classpath and annotate your Pageable with @ParameterObject like:
```java
@Operation(description = "blahblah")
@GetMapping(value = ALL_URI, produces = MediaType.APPLICATION_JSON_VALUE)
public Whatever getAll(@ParameterObject @PageableDefault(size = 20, sort = "name") Pageable pageable) {
        ...
    }
```
The annotation of @ParameterObject causes additional customizing of Pageable. It even transfer setting of PageableDefault to the final documentation! 👍
