### ISSUE TITLE
Question: Best way to document and generate HTML based on OpenAPI annotations programmatically

### ISSUE THREAD

**Issue by hhovhann** [springdoc/springdoc-openapi#1770]
Dear all, first of all, many thanks for the nice and helpful tool that you are made.

**SITUATION:** We need to add API documentation in our project and need to generate that based on only code (if that allows the plugin).

**TASK:** Generate HTML or PDF API documentation in `mvn verify` phase based on existing controller code based on openapi annotations [springdoc rescource](https://springdoc.org/).

**ACTIONS:** We are using now [springdoc-openapi](https://github.com/springdoc/springdoc-openapi) + [openapi-generator-maven-plugin](https://github.com/OpenAPITools/openapi-generator/tree/master/modules/openapi-generator-maven-plugin) pair. After running the instance plugin generates YAML file based on the documents annotations code that could be downloaded and used as a path in the plugin configuration
` <inputSpec>${project.basedir}/src/main/resources/static/api.yaml</inputSpec>`

**RESULT:** As a result I was able to get HTML but just based on the existing YAML file.

**QUESTION:** Is there any better way to generate HTML or pdf (I think you don't have yet a proper generator to support that format yet), just based on code that had the same generated HTML as we had when using the YAML file.

The same question is asked in [openapi-generator](https://github.com/OpenAPITools/openapi-generator/issues/13027) project.
Thanks in advance

**Comment by bnasslahsen** [comment]
@hhovhann,

Not sure, there is a better way; You can also just use https://springdoc.org/#maven-plugin to generate the YAML;
Then, you would need a thrid party tool to get HTML or PDF output.
 
Already answered here:

- https://github.com/springdoc/springdoc-openapi/issues/1770
- https://stackoverflow.com/questions/54259816/how-to-generate-a-pdf-or-markup-from-openapi-3-0

**Comment by hhovhann** [comment]
@bnasslahsen has used the plugin but for the progress need to have the running instances separately. Any suggestion in this matter?

https://github.com/OpenAPITools/openapi-generator/issues/13283
