### ISSUE TITLE
Nullable Integer ignores example value "null" and defaults to 0

### ISSUE THREAD

**Issue by dreis2211** [springdoc/springdoc-openapi#1772]
Hi 👋 

**Describe the bug**
I was migrating a Spring-Boot app from SpringFox to SpringDoc and noticed that the example value of the Schema annotation for `Integer` fields is ignored and defaults to 0.

E.g. defining the following has no effect:
```
	@Schema(nullable = true, example = "null")
	private Integer id;
```
<img width="279" alt="image" src="https://user-images.githubusercontent.com/6304496/182160571-fe4b714a-bc18-45db-ab4e-31df3a63b952.png">

**To Reproduce**
- Spring-Boot 2.7.2 and SpringDoc 1.6.9 are used
- Checkout https://github.com/dreis2211/swagger-nullable-bug
- Run `./gradlew bootRun`
- Check http://localhost:8080/swagger-ui/index.html#/test-controller/hello

**Expected behavior**
- Primitive wrapper types allow `null` as example value instead of showing 0

I'm not quite sure if this is a bug in Swagger itself or SpringDoc. Just let me know.

Cheers,
Christoph

**Comment by bnasslahsen** [comment]
@dreis2211, 

Use this code, to introspect your class and you will see that this related to `swagger-core` instead of `springdoc-openapi`.

```java
	ResolvedSchema resolvedSchema = ModelConverters.getInstance()
				.resolveAsResolvedSchema(
						new AnnotatedType(TestData.class));
```

**Comment by dreis2211** [comment]
Thanks @bnasslahsen - I've opened https://github.com/swagger-api/swagger-core/issues/4229
