### ISSUE TITLE
Spring DATA Rest OneToMany/ManyToOne/OneToOne associations are absent in OpenAPI model

### ISSUE THREAD

**Issue by valb3r** [springdoc/springdoc-openapi#1773]
**Describe the bug**
OneToMany/ManyToOne associations are missing in the generated model

**To Reproduce**
- Clone https://github.com/valb3r/springdoc-issue
- Launch Gradle project, via `./gradlew clean bootRun`
- Go to http://localhost:8080/swagger-ui/index.html#/product-item-entity-controller/getItemResource-productitem-get
- Relations are missing in response:
<img width="1311" alt="Screenshot 2022-08-01 at 20 20 51" src="https://user-images.githubusercontent.com/18463491/182206506-5b129af5-3358-4186-8d5f-6c2f6683c351.png">

Observed YAML:
```
EntityModelProductItem:
      required:
      - locationInWarehouse
      type: object
      properties:
        quantity:
          type: integer
          format: int64
        locationInWarehouse:
          type: string
        _links:
          $ref: '#/components/schemas/Links'
```

**Expected behavior**
- Expected having relations in all models 
- What is the expected result using OpenAPI Description (yml or json)?
Expected YAML:
```
EntityModelProductItem:
      required:
      - locationInWarehouse
      type: object
      properties:
        quantity:
          type: integer
          format: int64
        product:
           $ref: '#/components/schemas/EntityModelProduct'
        locationInWarehouse:
          type: string
        _links:
          $ref: '#/components/schemas/Links'
```

It would be very helpful if it was possible to include associations everywhere (in GET /entities/id, GET /entities ....) as relationships can be exposed via Excerpts, but currently generated YAML is not usable due to missing relationships references in spec

Currently, desired result is achievable from RepositoryRestConfigurer:
```
@Component
public class ExposeIdConfiguration implements RepositoryRestConfigurer {

    @Override
    public void configureRepositoryRestConfiguration(RepositoryRestConfiguration config, CorsRegistry cors) {
        config.exposeIdsFor(Product.class, ProductItem.class);
    }
}
```
But IDs exposure and entity content seem to be different concepts

**Comment by valb3r** [comment]
Obvious root cause is `SpringDocDataRestUtils.updateResponseSchema`:
```
Map<String, Schema> properties = existingSchema.getProperties();
		EntityInfo entityInfo = entityInoMap.get(className);
		if (!CollectionUtils.isEmpty(properties)) {
			Iterator<Entry<String, Schema>> it = properties.entrySet().iterator();
			while (it.hasNext()) {
				Entry<String, Schema> entry = it.next();
				String propId = entry.getKey();
				if (entityInfo.getIgnoredFields().contains(propId))
					it.remove();
				else if (EMBEDDED.equals(propId)) {
					updateResponseSchemaEmbedded(components, entityInfo, entry);
				}
			}
		}
		return existingSchema;
```
Relationships are pushed into ignored list - `entityInfo.getIgnoredFields()` there

**Comment by bnasslahsen** [comment]
@valb3r, 

I have made a fix, not the one you are expecting :)
If you have a look at the generated spring-data-rest response, schema you will that the associations are part of `_links` which is already described in the generated `openapi` spec.

For the behavior you are reporting when exposeIdsFor is used, this is a bug and now fixed.
