### ISSUE TITLE
Support for nested groups

### ISSUE THREAD

**Issue by darrellme** [springdoc/springdoc-openapi#1777]
I'm currently using the latest version of springdoc (1.6.9), and I'm successfully using the dynamic grouping functionality (adding multiple GroupedOpenApi classes to the spring context. However, I'd like to be able to use sub-groups.

For example, I might want to split API's into the following groups: - 

Admin
Orders
Products

This gives me the URLs of /v3/api-docs/admin, /v3/api-docs/orders and /v3/api-docs/products.

I've like to also include a sub-group for each of these, for example the version number, which would result in the URL's
/v3/api-docs/admin/v1, /v3/api-docs/orders/v1 and /v3/api-docs/products/v2

I might also want to include additional sub-groups, perhaps read and readwrite, i.e. /v3/api-docs/products/v2/read /v3/api-docs/products/v2/readwrite

Is this something that can be done currently, or would this require further development?

Thanks

Darrell

**Comment by bnasslahsen** [comment]
@darrellme, 

There is no such a feature and there are no plans to addd it.
