### ISSUE TITLE
Support for Groovy 4

### ISSUE THREAD

**Issue by Benthum** [springdoc/springdoc-openapi#1779]
I am trying to upgrade one of my services to use Groovy 4, and since the springdoc-openapi-groovy library is targeting the old maven location (org.codehaus.groovy vs org.apache.groovy) and v3, it is running into conflicts.

I believe it would be best to create a separate library for groovy 4 to avoid breaking anyone still on groovy 3. i.e. springdoc-openapi-groovy4

I isolated this library as the only one blocking me, but without it swagger isn't working correctly since I am using groovy.

Below is a screenshot showing the error that I get.

![Groovy upgrade error](https://user-images.githubusercontent.com/7076408/182870955-7f89b04f-d45e-4617-b0e3-75bd14de3766.png)

**Comment by bnasslahsen** [comment]
@Benthum,

Why don't just use the mvc version of springdoc-openapi ?

**Comment by Benthum** [comment]
https://github.com/Benthum/swagger-groovy4

Here is a repo I made to show off the example
main branch works and is groovy 3, the other branch is groovy 4 and reproduces the error I saw.

**Comment by Benthum** [comment]
@bnasslahsen 
Thanks for the suggestion of excluding the jar, that does seem to fix it. Good to have a workaround in the meantime until official support can be added.

I updated my example branch with the exclusion in case anyone else runs into the same problem.

**Comment by bnasslahsen** [comment]
@Benthum, 

A fix has been added to the latest SNAPSHOT, so that you won't need to exclude the dependency when using groovy4.
