### ISSUE TITLE
Generate api only for @RestController

### ISSUE THREAD

**Issue by fgoulet** [springdoc/springdoc-openapi#178]
What would be the best way to instruct springdoc to generate api only for classes that are decorated with @RestController and ignore classes with @Controller annotation.

**Comment by eiswind** [comment]
I'm looking for the same answer. Probably it could help to knwo how to exclude some Controllersfrom the docs?

**Comment by springdoc** [comment]
Hi, 
 
 `@RestController` is equivalent to `@Controller` + `@RequestMapping` on the type level.
 For some legacy apps, we are constrained to still support both.

 If you need to hide the `@Controller` on the type level, in this case, you can use: `@Hidden` on controller level.
 Please note this annotation can be also used to hide some methods from the generated documentation.
