### ISSUE TITLE
No bean name "streamBridge" available when using spring-cloud-function-web

### ISSUE THREAD

**Issue by luciantimar** [springdoc/springdoc-openapi#1780]
**Describe the bug**
- I have a web-flux application for which I want to jave open-api specification with a simple controller and a spring cloud function for which I have spring.cloud.function.definition=myfunction specified in application.properties.
- Besides simple controllers I also have includes 
- No bean name "streamBridge" available error is throw when spring-cloud-function-web dependency is  added as dependency 
- 
**To Reproduce**
- What version of spring-boot you are using? 2.7.0
- What modules and versions of springdoc-openapi are you using? 1.6.9
- What is the actual and the expected result using OpenAPI Description (yml or json)?
- Create a simple gradle project with a simple controller
- Create a sprinf could function bean
- Add spring.cloud.function.definition=myfunction in aplication.properties
- add implementation 'org.springdoc:springdoc-openapi-webflux-ui:1.6.9'
- Access /api-docs.ui endpoint
- 

**Expected behavior**
- /api-docs/ui display open api documentation

**Screenshots**
-N/A

**Additional context**
N/A.

**Comment by bnasslahsen** [comment]
Not reproducible. See examples here; https://github.com/springdoc/springdoc-openapi-demos/tree/master/springdoc-openapi-spring-cloud-function/spring-cloud-function-webflux

If you believe you are facing a bug, you can adapt the demo so we can reproduce your issue.
