### ISSUE TITLE
ClassGraphException is thrown when using GraalVM's tracing agent

### ISSUE THREAD

**Issue by magnus-larsson** [springdoc/springdoc-openapi#1781]
**Describe the bug**

When a Spring Boot app that uses `springdoc-openapi` is natively compiled using Spring Native and configuration information from running the GraalVM tracing agent, it fails during startup throwing a `ClassGraphException`.

**To Reproduce**

Versions used:

- GraalVM CE v22.1.0
- Spring Boot v2.7.2
- Sprint Native v0.12.1
- springdoc-openapi v1.6.10-SNAPSHOT

1. Check out the demo project

   ```
   git clone git@github.com:magnus-larsson/myservice.git
   cd myservice
   git checkout SB2.7.2-SN0.12.1-SD1.6.10.SS
   ```

1. Start the app using the JVM

   ```
   ./gradlew bootRun
   ```

   Starts as expected with the following output in the end:

   ```
   2022-08-06 08:50:02.191  INFO 73506 --- [           main] s.magnus.myservice.MyserviceApplication  : Started MyserviceApplication in 1.022 seconds (JVM running for 1.154)
   Health: {"status":"UP"}
   Info: {"build":{"artifact":"myservice","name":"myservice","time":"2022-08-06T06:49:46.732Z","version":"0.0.1-SNAPSHOT","group":"se.magnus"}}
   2022-08-06 08:50:02.301  INFO 73506 --- [ctor-http-nio-2] o.springdoc.api.AbstractOpenApiResource  : Init duration for springdoc-openapi is: 11 ms
   OpenAPI: {"openapi":"3.0.1","info":{"title":"OpenAPI definition","version":"v0"},"servers":[{"url":"http://localhost:8080","description":"Generated server url"}],"paths":{},"components":{}}
   ```

1. Build a native image **with** info from the tracing agent

   **Note** that the output from the tracing agent already exists under: `src/main/resources/META-INF/native-image`

   ```
   ./gradlew nativeCompile
   ```

1. Start the native image **with** info from the tracing agent

   ```
   build/native/nativeCompile/myservice
   ```

   It will crash during startup with a `ClassGraphException`, with a nested `com.oracle.svm.core.jdk.UnsupportedFeatureError`:

   ```
   org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'webHandler': Initialization of bean failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'resourceHandlerMapping': Unexpected exception during bean creation; nested exception is io.github.classgraph.ClassGraphException: Uncaught exception during scan

   ...

   Caused by: java.lang.IllegalArgumentException: Method "open" could not be invoked: com.oracle.svm.core.jdk.UnsupportedFeatureError: Runtime reflection is not supported for public java.lang.module.ModuleReader jdk.internal.module.ModuleReferenceImpl.open() throws java.io.IOException
   ```

1. Build a native image **without** info from the tracing agent

   Remove the output from the tracing agent and build the native image again.

   ```
   rm -r src/main/resources/META-INF/native-image
   ./gradlew nativeCompile
   ```

1. Start the native image **without** info from the tracing agent

   ```
   build/native/nativeCompile/myservice
   ```

   Starts as expected with the same info as when started using the Java VM.

1. If required, recreate output from the tracing agent

   ```
   ./gradlew test
   ```

**Expected behavior**
- The native compiled app starts without errors also when compiled with output from the GraalVM tracing agent

**Comment by bnasslahsen** [comment]
@magnus-larsson, 

Your file `reflect-config.json` is incomplete. I let you check the differences.
But using this one instead, makes the build pass!

[reflect-config.json.zip](https://github.com/springdoc/springdoc-openapi/files/9274988/reflect-config.json.zip)

**Comment by magnus-larsson** [comment]
Thanks, with your file `reflect-config.json` it works!

May I ask how you created your `reflect-config.json` - file?

Mine was created simply by running `./gradlew test` which worked fine until I started to use springdoc-openapi.
So I guess there is something more I need to do when I create `reflect-config.json` - files in other projects that use springdoc-openapi?

**Comment by bnasslahsen** [comment]
Certainly your test is not detecting all the invoked classes.

When, you run `./gradlew nativeCompile`, spring-aot plugin generates the detected `reflect-config.json` file in `build/generated/resources/aotMain/META-INF/native-image/org.springframework.aot/spring-aot` where you can find this file.

In general, it's better to rely on spring-aot unless the libraries or your code does not support graalVM. Then, you should add your files.

If you check the json diff, you certainly view the missing classes from your file.

**Comment by magnus-larsson** [comment]
Ok, thanks for the info!

I agree with you regarding avoiding the use of the tracing agent.
Unfortunately, I have cases where libraries currently do not support GraalVM, so I need to figure out how to use `springdoc-openapi` together with the configuration generated by the tracing agent.

The `reflect-config.json` - files generated by the tracing agent and `spring-aot` seems to be very different, so I'm not sure how to merge them...

If you have any further ideas/recommendations on how to use `springdoc-openapi` together with the configuration generated by the tracing agent, it is most welcome!
