### ISSUE TITLE
add support for interfaces of hibernate-validator#6.2.3

### ISSUE THREAD

**Issue by samuelfac** [springdoc/springdoc-openapi#1784]
like made for this: https://springdoc.org/faq.html#_are_the_following_validation_annotations_supported_notempty_notblank_positiveorzero_negativeorzero  
could also add support for interfaces of package "org.hibernate.validator.constraints" from hibernate-validator#6.2.3 ?

**Comment by bnasslahsen** [comment]
@samuelfac,

You can extend the current implementation for `hibernate-validator` as well. Here is an interesting article for that.
- https://dzone.com/articles/doing-more-with-springdoc-openapi

Feel free to propose a PR, if you find out some modular approach.
