### ISSUE TITLE
Swagger UI is empty, the configuration bean is not initialized 

### ISSUE THREAD

**Issue by alexcibotari** [springdoc/springdoc-openapi#1785]
**Describe the bug**
- If you are reporting a bug, please help to speed up problem diagnosis by providing as much information as possible:
- A clear and concise description of what the bug is: the title of an issue is not enough

**To Reproduce**
Dependencies 
- **Java** - 11
- **Kotlin** - 1.6.21
- **Spring Boot WebFlux** - 2.7.2
- springdoc-openapi-webflux-ui:1.6.9
- org.springdoc:springdoc-openapi-kotlin:1.6.9

**Annotation-Based Configuration Code** 
**OpenApiConfig**
```
@Configuration
@OpenAPIDefinition(
  info = Info(
    title = "Documentation API",
    version = "0.1.0"
  )
)
@SecuritySchemes(
  value = [
    SecurityScheme(
      name = "api-v1",
      type = SecuritySchemeType.HTTP,
      scheme = "bearer",
      bearerFormat = "Opaque"
    ),
    SecurityScheme(
      name = "ui",
      type = SecuritySchemeType.HTTP,
      scheme = "bearer",
      bearerFormat = "JWT"
    )
  ]
)
class OpenApiConfig {

  @Bean
  fun externalV1OpenAPI(): GroupedOpenApi {
    return GroupedOpenApi.builder()
      .group("api-v1")
      .displayName("API v1")
      .pathsToMatch("/api/v1/**")
      .build()
  }

  @Bean
  fun uiOpenAPI(): GroupedOpenApi {
    return GroupedOpenApi.builder()
      .group("ui")
      .displayName("UI")
      .pathsToMatch("/api/tokens/**")
      .build()
  }
}
```

or

**Configuration Code** 
**OpenApiConfig**
```
@Configuration
class OpenApiConfig {

  @Bean
  fun customOpenAPI(): OpenAPI {
    return OpenAPI()
      .components(
        Components().addSecuritySchemes(
          "oauth2",
          SecurityScheme()
            .type(SecurityScheme.Type.HTTP)
            .`in`(SecurityScheme.In.HEADER)
            .scheme("bearer")
            .bearerFormat("JWT")
        )
      )
      .info(
        Info().title("Sample").version("0.1.0")
      )
  }
}
```
I have added additional checks, to see if the bean is initialized in the **Application.kt**
```
  if (context.containsBean("openApiConfig")) {
    val bp = context.getBean(OpenApiConfig::class.java)
    log.info("displayName: \t{}", bp.externalV1OpenAPI().displayName)
  }
```
result 
```
displayName: 	API v1
```
Also, I have added Logs in each bean class/method, and I can see in logs bean initialization with additional logs.
- Open Swagger UI
- Blank Page and logs I can't see Bean initialization 

HTTP Response :
```
Request URL: https://localhost:8080/swagger-ui.html
Request Method: GET
Status Code: 200 OK
Remote Address: [::1]:8080
Referrer Policy: strict-origin-when-cross-origin
```

**Expected behavior**
- See generate Open API in Swagger

**Screenshots**
just an empty screen.

**Additional context**

**Comment by alexcibotari** [comment]
Found the issue on my side

**Comment by demurgos** [comment]
![XKCD - Wisdom of the Ancients](https://imgs.xkcd.com/comics/wisdom_of_the_ancients.png)

Please don't close issues with "never mind I figured it out", but share what was the issue. If it happened to you, it can happen to anyone else and most likely means that the documentation can be improved somehow.

**Comment by demurgos** [comment]
I had a similar issue where I received an empty response. In my case, the status code was 403. This hinted at a permission issue.

The problem was in my `WebSecurityConfig` class (annotated with `@EnableWebSecurity`). In the `configure` method, the http security chain applied an allow list for path that can be access without authentication. Adding `/swagger-ui/index.html` fixed the problem.
