### ISSUE TITLE
Support all of the swagger ui properties, including plugins/pluginsOptions

### ISSUE THREAD

**Issue by darrellme** [springdoc/springdoc-openapi#1786]
According to the springdoc documentation, all of the standard [swagger properties](https://swagger.io/docs/open-source-tools/swagger-ui/usage/configuration/) are supported. However, I can't seem to find any support for the 'plugins' property, which would allow the definition of custom swagger plugins that can be used in the swagger-ui, without having to extract the webjars.

I've checked in the SwaggerUiConfigParameters class and the AbstractSwaggerUiConfigProperties and there are some swagger-ui properties that are not included, i.e. plugins, pluginsOptions are the main ones I'm interested in.

Unless there is some other way I can add these configuration properties to the configuration endpoint?

**Comment by bnasslahsen** [comment]
@darrellme, 

There is no plan to add these properties.
Feel free to propose a PR, if you feel it useful for the community.
