### ISSUE TITLE
Allow defining a method as explicitly not requiring security

### ISSUE THREAD

**Issue by sabareeshkkanan** [springdoc/springdoc-openapi#1788]
Currently this works except if SecurityRequirements is defined in the controller itself 

https://github.com/springdoc/springdoc-openapi/issues/639

```

@RestController
@RequestMapping("/)
@SecurityRequirements(value ={ @SecurityRequirement(name="rkToken")})
public class RecordKeeperAPI {

  @PostMapping
  @SecurityRequirements()
  @Operation(security = {@SecurityRequirement(name="clientToken")})
  public RecordKeeper add(@RequestBody @Valid RecordKeeper recordKeeper){
    return super.add(recordKeeper);
  }
}
```
in this scenario it returns both rktoken and clientToken instead of just client token.

**Comment by bnasslahsen** [comment]
@sabareeshkkanan, 

Remove from `@Operation` the `@SecurityRequirement` annotation.

**Comment by sabareeshkkanan** [comment]
@bnasslahsen basically i am trying to override the security requirement, so removing it wont help
