### ISSUE TITLE
Can I have an example or some documentation on how to use OpenApiCustomiser?

### ISSUE THREAD

**Issue by chadmalla-ff** [springdoc/springdoc-openapi#179]
My goal is to have a global configuration for the mediatype to `application/json` for all my `consumes` and `produces` value so I don't add it for each method? Is this possible using the `OpenApiCustomiser` interface and if so can I have an example on how to use this interface?

Thanks!

**Comment by springdoc** [comment]
Hi, 

 If the mediaType is specified on your spring-mvc annotations,there is no need to add it.
 You can also define your custom `@RestController` annotation which extends RestController and defines the mediatype for `consumes` and `produces`.  Then use this annotation, in all your controllers.
 
The last solution is to use OpenApiCustomiser. You have access to the `Operation` object, and you can iterate over all the elements to change the mediatype, but this seems to be an overkill solution.

 An example is available on the tests for setting global header:

- https://github.com/springdoc/springdoc-openapi/blob/master/springdoc-openapi-webflux-core/src/test/java/test/org/springdoc/api/app39/SpringDocTestApp.java
