### ISSUE TITLE
@Schema behavior not same as the @ApiModelProperty with Enums

### ISSUE THREAD

**Issue by majidalikhn** [springdoc/springdoc-openapi#1797]
We have a class with a field as below:

`HttpStatus errorDomain;`

And we generate api docs for this field. In springfox swagger we do this.

`@ApiModelProperty(value = "Same as http error codes", required = true)
@NotBlank
HttpStatus errorDomain;`

And result we get is:

`"errorDomain" : {
          "type" : "string",
          "description" : "Same as http error codes",
          "enum" : [ "ACCEPTED", "ALREADY_REPORTED"]`

Now in the springdoc-openapi 3.0 with the @Schema annotation as following;

`@Schema(description = "Same as http error codes", required = true)
@NotBlank
HttpStatus errorDomain;`

We get the result as following;

`"errorDomain" : {
"type" : "string",
"description" : "Same as http error codes",
"enum" : [ "100 CONTINUE", "101 SWITCHING_PROTOCOLS"]`

So my understanding is that if @Schema is replacing the @ApiModelProperty then the outcome should be same. Is there a way to get the desired behavior for the ENUMS with only the values not both key and values?``

**Comment by bnasslahsen** [comment]
@majidalikhn,

This is achieved using the Jackson [@JsonValue](https://fasterxml.github.io/jackson-annotations/javadoc/2.12/com/fasterxml/jackson/annotation/JsonValue.html) annotation in classes which you have access to the source code.

Alternatively, use `PropertyCustomizer`, for example:

```java
	@Bean
	public PropertyCustomizer enumValuePropertyCustomizer() {
		return (property, type) -> {
			var javaType = (JavaType) type.getType();
			if (HttpStatus.class.equals(javaType.getRawClass())) {
				var values = Arrays.stream(HttpStatus.class.getEnumConstants())
						.map(httpStatus -> httpStatus.name())
						.map(Object::toString)
						.collect(Collectors.toList());
				property._enum(values);
				}
			return property;
		};
	}
```
