### ISSUE TITLE
Change in the API should bump major version not patch

### ISSUE THREAD

**Issue by dejan-kosak** [springdoc/springdoc-openapi#1798]
You've created breaking change with 1.6.10 release. For example: OpenApiResource constructor arguments changed:
https://github.com/springdoc/springdoc-openapi/blob/master/springdoc-openapi-webmvc-core/src/main/java/org/springdoc/webmvc/api/OpenApiResource.java#L119

Changes of API usually bump major version or should be backward compatible.

**Comment by bnasslahsen** [comment]
@dejan-kosak,

Not relevant... If you are creating ticket Just for this.
