### ISSUE TITLE
Make the api opt-in with @EnableSpringDoc

### ISSUE THREAD

**Issue by membersound** [springdoc/springdoc-openapi#18]
Would it be possible to make the springdoc library an opt-in feature? Like `@EnableScheduling`, `@EnableCaching` does, with would be nice to have a `@EnableSpringDoc`, so that having the library on classpath does not automatically trigger the swagger endpoint generation.

This would be useful for company-wide commons libraries that define the eg the sprindoc version, common configuration, etc. But should disable the swagger ui in production. Thus opt-in (or out) would be useful.

**Comment by springdoc** [comment]
Hi, 

 The following property is available since: v1.1.15
-  springdoc.api-docs.enabled=false

 This property helps you disable springdoc-openapi endpoints.

 If you want to expose the api-docs endpoints without using the swagger-ui, you can use the core dependency:

```xml
 <dependency>
      <groupId>org.springdoc</groupId>
      <artifactId>springdoc-openapi-core</artifactId>
      <version>1.1.14</version>
 </dependency> 
```
