### ISSUE TITLE
When generating from Kotlin, automatically ignore first parameters of suspend functions that are of type ContinuationObject

### ISSUE THREAD

**Issue by matthewadams** [springdoc/springdoc-openapi#1802]
**Describe the bug**
The Kotlin compiler adds a first parameter of type `ContinuationObject` to all `suspend` methods and should be ignored.  Without this option, all operations are polluted with this unusable parameter.

**To Reproduce**
- What version of spring-boot you are using?
`2.6.7`

- What modules and versions of springdoc-openapi are you using?
`org.springdoc:springdoc-openapi-webflux-ui:1.6.0`

- What is the actual and the expected result using OpenAPI Description (yml or json)?
(snippet)
```
    "/healthz": {
      "get": {
        "tags": [
          "health-controller"
        ],
        "operationId": "health",
        "parameters": [
          {
            "name": "$completion",
            "in": "query",
            "required": false,
            "schema": {
              "$ref": "#/components/schemas/ContinuationObject"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "*/*": {
                "schema": {
                  "$ref": "#/components/schemas/HealthReport"
                }
              }
            }
          }
        }
      }
    },
```
- Provide with a sample code (HelloController) or Test that reproduces the problem
```
// imports...
@CrossOrigin(
    value = ["*"],
    allowedHeaders = ["*"],
    maxAge = 900
)
@ResponseBody
@RequestMapping(path = ["/", "/healthz", "/health"]) // make sure these are in WebFluxSecurityConfig.UNSECURED_PATHS!
class HealthController(...) {
    @GetMapping
    suspend fun health(): ResponseEntity<HealthReport> {
      // ...
    }
}
```

**Expected behavior**
- A clear and concise description of what you expected to happen.
- What is the expected result using OpenAPI Description (yml or json)?

There should be zero arguments for this operation in the generated JSON.

**Comment by bnasslahsen** [comment]
Not reproducible. See https://springdoc.org/#kotlin-support.

If you still have the issue, then Provide a [Minimal, Reproducible Example - with HelloController](https://stackoverflow.com/help/minimal-reproducible-example) that reproduces the problem.

**Comment by matthewadams** [comment]
Oh missed that dependency!  Thanks!
