### ISSUE TITLE
[Feature Request] I18n on @Schema annotation

### ISSUE THREAD

**Issue by DVD27** [springdoc/springdoc-openapi#1806]
**Is your feature request related to a problem? Please describe.**
- For some reason, we want to internationalize our API, and @Schema not work with internationalisation for text methods like title / description.
- Actually it produce : 
![image](https://user-images.githubusercontent.com/8726581/185860220-b7dbb04f-bb45-47e4-82d2-d2afe4309f2e.png)

**Describe the solution you'd like**
- Like #1268 translate this fields if possible.

**Describe alternatives you've considered**
- None

**Comment by bnasslahsen** [comment]
use `springdoc.api-docs.resolve-schema-properties=true`

**Comment by DVD27** [comment]
Thank you for your answer and excuse me for this false issue.
