### ISSUE TITLE
OpenAPIService is initialized between the server generation and access to OpenApiCustomizer, when the server uses multi processes

### ISSUE THREAD

**Issue by Tal-D** [springdoc/springdoc-openapi#1807]
**Describe the bug**
In my openAPI configuration class I added a customizer that requires access to the openAPI servers list. When sending requests to the API, it can't find the openAPI servers list (the servers list attribute value is null). This issue occurs when the API is ran with server which is used by multiple processes.

The API initializes the openAPIService attribute with the method initOpenAPIBuilder inside the class AbstractOpenApiResource ([source code](https://github.com/springdoc/springdoc-openapi/blob/v1.6.9/springdoc-openapi-webmvc-core/src/main/java/org/springdoc/webmvc/api/OpenApiResource.java#L253)):

```
protected void calculateServerUrl(HttpServletRequest request, String apiDocsUrl, Locale locale) {
		super.initOpenAPIBuilder(locale);
		String calculatedUrl = getServerUrl(request, apiDocsUrl);
		openAPIService.setServerBaseUrl(calculatedUrl);
	}
```

The openAPIService creates the openAPI server and calls it customizers in getOpenApi method inside the AbstractOpenApiResource class ([source code](https://github.com/springdoc/springdoc-openapi/blob/v1.6.9/springdoc-openapi-common/src/main/java/org/springdoc/api/AbstractOpenApiResource.java#L332)):

```
	protected synchronized OpenAPI getOpenApi(Locale locale) {

                       ....

                        openAPIService.updateServers(openAPI);

			if (springDocConfigProperties.isRemoveBrokenReferenceDefinitions())
				this.removeBrokenReferenceDefinitions(openAPI);

			// run the optional customisers
			List<Server> servers = openAPI.getServers();
			List<Server> serversCopy = null;
			try {
				serversCopy = springDocProviders.jsonMapper()
						.readValue(springDocProviders.jsonMapper().writeValueAsString(servers), new TypeReference<List<Server>>() {});
			}
			catch (JsonProcessingException e) {
				LOGGER.warn("Json Processing Exception occurred: {}", e.getMessage());
			}

			openApiLocaleCustomizers.values().forEach(openApiLocaleCustomizer -> openApiLocaleCustomizer.customise(openAPI, finalLocale));
			openApiCustomisers.ifPresent(apiCustomisers -> apiCustomisers.forEach(openApiCustomiser -> openApiCustomiser.customise(openAPI)));
```

Since the getOpenApi is defined as synchronized and calculateServerUrl is not, a process can call the openAPI customizers after its server generation, while a second process initializes the openAPIService and delete the created server.

**To Reproduce**

- Springdoc version: 1.6.9
- Using MultipleOpenApiSupportConfiguration and SpringDocWebMvcConfiguration.

1. Start a server that runs springdoc example with multiple GroupedOpenApi definitions. The server need to be in debug mode.

2. Add a breakpoint at line 332 in the file AbstractOpenApiResource.java ([the second mentioned link](https://github.com/springdoc/springdoc-openapi/blob/v1.6.9/springdoc-openapi-common/src/main/java/org/springdoc/api/AbstractOpenApiResource.java#L332)):

`openAPIService.updateServers(openAPI);`

3. Open the swagger UI page - the execution should stop at the defined breakpoint from the previous step.

4. execute the following line (can be done in IntelliJ by pressing the keys alt and F8) from the file AbstractOpenApiResource.java ([source code](https://github.com/springdoc/springdoc-openapi/blob/v1.6.9/springdoc-openapi-common/src/main/java/org/springdoc/api/AbstractOpenApiResource.java#L1166)):

`openAPIService = openAPIBuilderObjectFactory.getObject();`

5. Resume the program execution.

**Expected result**: the page is uploaded with the relevant endpoints and schemas.

**Actual result**: the page is uploaded with a server error: "response status is 500 <the group url from the swagger-configuration>"

**Comment by bnasslahsen** [comment]
Not reproducible.
If you are facing an issue, provide a Minimal, Reproducible Example - with HelloController that reproduces the problem or directly propose a PR with the relevant test case. 

There is no need to open à New ticket. This one can be reopened if the relevant information are provided.
