### ISSUE TITLE
Groups configuration non working in 1.6.10 and 1.6.11

### ISSUE THREAD

**Issue by stleray** [springdoc/springdoc-openapi#1808]
Since I upgraded my project to the version 1.6.10 and 1.6.11 groups configuration have no longer effects.

I've upgraded spring-boot from 2.7.2 to 2.7.3 and springdoc-openapi-ui from 1.6.9 to 1.6.10.
Separated documentations are no longer availables.

Moving back to 1.6.9 and keep spring-boot in 2.7.3 works.

No changes in my GroupsConfiguration class
`	@Bean
	public GroupedOpenApi internalApi() {
		return GroupedOpenApi.builder().group("internal").pathsToMatch("/internal/**").build();
	}
	@Bean
	public GroupedOpenApi mobileApi() {
		return GroupedOpenApi.builder().group("mobile").pathsToMatch("/mobile/**").build();
	}
	@Bean
	public GroupedOpenApi partnerApi() {
		return GroupedOpenApi.builder().group("partner").pathsToMatch("/partner/**").build();
	}`

No change in swagger config class
`@Configuration
@Import({ org.springdoc.core.SpringDocConfigProperties.class,
		org.springdoc.webmvc.core.MultipleOpenApiSupportConfiguration.class,
		org.springdoc.core.SpringDocConfiguration.class, org.springdoc.webmvc.core.SpringDocWebMvcConfiguration.class,
		SwaggerUiConfigParameters.class, SwaggerUiOAuthProperties.class,
		org.springdoc.core.SwaggerUiConfigProperties.class, org.springdoc.core.SwaggerUiOAuthProperties.class,
		org.springdoc.webmvc.ui.SwaggerConfig.class, GroupsConfiguration.class,
		org.springframework.boot.autoconfigure.jackson.JacksonAutoConfiguration.class })
public class SwaggerConfig {

}`

**Comment by bnasslahsen** [comment]
@stleray 

Not reproducible. 
If you are facing an issue, provide a [Minimal, Reproducible Example - with HelloController](https://stackoverflow.com/help/minimal-reproducible-example) that reproduces the problem.

There is no need to open à New ticket. This one can be reopened if the relevant information are provided.
