### ISSUE TITLE
@Tag adds order sort

### ISSUE THREAD

**Issue by fashionbrot** [springdoc/springdoc-openapi#1809]
**Is your feature request related to a problem? Please describe.**
- A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
- What is the actual result using OpenAPI Description (yml or json)?

**Describe the solution you'd like**
- A clear and concise description of what you want to happen.
- What is the expected result using OpenAPI Description (yml or json)?

**Describe alternatives you've considered**
@Tag adds order sort , In this way, it is easier to find the corresponding interface according to the sorting

**Additional context**
- Add any other context or screenshots about the feature request here.

**Comment by bnasslahsen** [comment]
@fashionbrot, 

Your description is not clear and does not follow its [contributing guidelines](https://github.com/springdoc/springdoc-openapi/blob/fd2f9a4d38a45bb34c326ae5fe2404120e2710ef/CONTRIBUTING.adoc) and [code of conduct](https://github.com/springdoc/springdoc-openapi/blob/fd2f9a4d38a45bb34c326ae5fe2404120e2710ef/CODE_OF_CONDUCT.md). 
Make sure your read it before submitting any tickets.
