### ISSUE TITLE
Support for ApiModelProperty

### ISSUE THREAD

**Issue by NicklasWallgren** [springdoc/springdoc-openapi#181]
It would be nice to have support for the @ApiModelProperty annotation.

```
@RequestBody UserDto userDto
```

```
public class UserDto {
    @ApiModelProperty(notes = "The user name property", example = "example data", required = true, position = 1)
    @Size(min = 2, max = 10)
    @NotNull @NonNull
    private String name;
}
```

```
"UserDto": {
      "type": "object",
      "properties": {
        "name": {
          "type": "string",
          "example": "example data",
          "description": "The user name property"
        },
 }
```

**Comment by hisener** [comment]
You should use `io.swagger.v3.oas.annotations.media.Schema` instead, for instance, https://github.com/springdoc/springdoc-openapi/blob/2ec686236d1461f36acbfd612fcefcf5c3b38eb2/springdoc-openapi-webmvc-core/src/test/java/test/org/springdoc/api/app4/TrackerData.java#L18-L20

https://github.com/springdoc/springdoc-openapi/blob/df16dad33491c5ee0c48bb212c2c3264072b4bbf/springdoc-openapi-webmvc-core/src/test/resources/results/app4.json#L63-L68

**Comment by springdoc** [comment]
Hi, 

 We rely on swagger-annotations 2 which supports OpenAPI 3.
 `@ApiModelProperty`  is part of swagger-annotations 1.x which supports OpenAPI 2.
 Thank you @hisener for your answer. @Schema can achieve the same purpose as `@ApiModelProperty`  .

 Here is the official answer from the swagger team:

- https://github.com/swagger-api/swagger-core/issues/2503
