### ISSUE TITLE
Headers not properly rendered in the UI if using Components.addHeaders(...)

### ISSUE THREAD

**Issue by pmerson** [springdoc/springdoc-openapi#1810]
### The bug 
- I'm trying to define headers in a global customization. 
- If I use `Components().addParameters(...)` to add a header, it works and the header is shown in the Web interface.
- If I use `Components().addHeaders(...)` instead, the corresponding entry the UI is shown with empty name and location. 

### To Reproduce
Example code (Kotlin): 
```
    @Bean
    open fun configuraSwaggerGenericoTcu(): OpenAPI {
        return OpenAPI()
            .components(
                Components()
                    .addParameters(
                        "Authorization",
                        Parameter().name("Authorization").`in`("header").description("JWT access token with format 'Bearer [token]'").schema(StringSchema())
                    )
                    .addHeaders("X-UFP", Header().description("User fingerpring").schema(StringSchema()))
            )
    }
```

I'm using: 
- Spring Boot 2.6.4
- Modules and versions of springdoc-openapi in use: 
```
    api "org.springdoc:springdoc-openapi-ui:1.6.11"
    api "org.springdoc:springdoc-openapi-kotlin:1.6.11"
    api "org.springdoc:springdoc-openapi-security:1.6.11"
```

### Expected behavior 
- The `Header` object does not have a `name` attribute. Therefore, in the UI, the header documented via `addHeaders` should use *key* of the map entry as name.  
- Also, for these headers documented via `addHeaders`, the UI should automatically show the location as  ***(header)***.

### Screenshots

![image](https://user-images.githubusercontent.com/6674738/186269322-d4a33ee4-3649-4da3-83c4-f8fb2c7336ea.png)

### PS
- Minor suggestion: `Components.addParameters(...)` should be deprecated and replaced with `Components().addParameter(...)` because it only adds one parameter. As is, the function name is confusing. Same for `addHeaders(...)`. 
- We have tons of spring fox API documentation and are migrating to spring doc. So, thanks for your great effort on this library. 😊

**Comment by bnasslahsen** [comment]
@pmerson,

Not reproducible. Make sure you Provide a [Minimal, Reproducible Example - with HelloController](https://stackoverflow.com/help/minimal-reproducible-example) that reproduces the problem.

For your suggestions, their are related to `swagger-core` library! and not `springdoc-openapi`
