### ISSUE TITLE
404 on config since 1.6.10 onwards

### ISSUE THREAD

**Issue by s-frei** [springdoc/springdoc-openapi#1811]
Hi there,

we recently upgraded from *1.6.9* to *1.6.11* and since then the config cannot be loaded in the UI.
The reuqest to fetch the configuration results in a **404**. I verified that this is also the case for *1.6.10*.

The app accessed here is proxied by a *spring-cloud-gateway*, apperently the UI works fine on that one,
so it seems like the *webflux* module is still fine.

Downgrading to *1.6.9* brings everything to work again. This bug is also verified on another machine.
I verified that this is an actual **404** and not caused by the *spring-cloud-gateway* reverse proxy/security
stuff, accessing the app directly.

**To Reproduce**
- We are using spring-boot 2.7.3
- Modules used:
  - The *spring-cloud-gateway* app uses *springdoc-openapi-webflux-ui*
  - The *spring-boot* resource server app uses *springdoc-openapi-ui* and *springdoc-openapi-webmvc-core* (adding *springdoc-openapi-security* makes no difference)

**Expected behavior**
- The config can be fetched successfully

**Screenshots**
<img width="492" alt="grafik" src="https://user-images.githubusercontent.com/25681388/186369121-0f97dc7c-cec7-4ee8-ac8e-789ff76598ca.png">

Requesting `/myApp/v3/api-docs/swagger-config` (looks exactly the same in the working version):
```json
{
  "configUrl": "/myApp/v3/api-docs/swagger-config",
  "oauth2RedirectUrl": "https://{{ host }}/myApp/swagger-ui/oauth2-redirect.html",
  "url": "/myApp/v3/api-docs",
  "validatorUrl": ""
}
```

I'm not able to localize the change that brought in that behaviour, the diff of those versions is pretty big.
But let me know if I'm able to help you somehow.

Keep up the good work,
Samuel

**Comment by bnasslahsen** [comment]
@s-frei, 

I invite you to check your application configuration.
Only changes in the UI side between the versions your are mentioning is related to the version of the swagger-ui.

If you feel you are facing a bug, Provide a [Minimal, Reproducible Example - with HelloController](https://stackoverflow.com/help/minimal-reproducible-example) that reproduces the problem.

**Comment by bnasslahsen** [comment]
@s-frei,

All the demos are working just fine:  https://springdoc.org/#demos and no regressions on tests.

You are having a miss-configuration within your application and unfortunately, if you don't Provide a [Minimal, Reproducible Example - with HelloController](https://stackoverflow.com/help/minimal-reproducible-example) that reproduces the problem, we have no way to help you.

**Comment by s-frei** [comment]
Our applications are just working fine now too, again. As I stated adding any class with `@AutoConfigureAfter(SpringDocWebMvcConfiguration.class)` will prevent the controller serving the config to be initialized.

If this is a *valid* bug for you I for sure could provide an example to demonstrate this behaviour, if not, this is fixed for me.

**Comment by bnasslahsen** [comment]
@s-frei, 

This doesn't look to be a valid bug. 
Again, to confirm you would have to Provide a [Minimal, Reproducible Example - with HelloController](https://stackoverflow.com/help/minimal-reproducible-example) that reproduces the problem, we have no way to help you.
