### ISSUE TITLE
When an Endpoint returns a Page, mandatory fields should be marked as so.

### ISSUE THREAD

**Issue by demSly** [springdoc/springdoc-openapi#1812]
When an API returns a `org.springframework.data.domain.Page`, in the generated Swagger documentation the all its fields are not mandatory.

Since we use the Swagger JSON file to generate a client in Typescript, this forces us to always null-check fields like `totalElements` and `totalPages`.

Would it be possible to generate the proper documentation for `Page`, like it's done with `Pageable`?

**Comment by bnasslahsen** [comment]
@demSly,

use `OperationCustomizer` (or others OpenApiCustomiser/PropertyCustomizer) as described here
- https://github.com/springdoc/springdoc-openapi/issues/1112
