### ISSUE TITLE
Make the copy to clipboard icon static

### ISSUE THREAD

**Issue by rayman245** [springdoc/springdoc-openapi#1815]
Loving the new functionality to copy the URL, although I feel that the animation to show/hide on hover the copy to clipboard icon is unnecessary and a bit annoying especially for a fast clicker like me. I tend to click on the other icons before it could load, and not a very good UX in my opinion.

**Expected behavior**
Should just be a static icon

**Screenshots**
![image](https://user-images.githubusercontent.com/11938827/186561983-c2c8ea8a-dba0-4388-bc7b-9897ba9474cc.png)

**Comment by bnasslahsen** [comment]
@rayman245, 

Log this in the [swagger-ui ](https://github.com/swagger-api/swagger-ui) project instead.
