### ISSUE TITLE
Refresh the browser each time, the global header is added in duplicate.

### ISSUE THREAD

**Issue by doljae** [springdoc/springdoc-openapi#1820]
**Describe the bug**
- Refresh the browser each time, the global header is added in duplicate.

**To Reproduce**
- Repo: https://github.com/doljae/decalcomanie/tree/feature/swagger
- used version: 1.16.11

### SwaggerConfiguration.kt
```kotlin
@Configuration
class SwaggerConfiguration {

    @Bean
    fun globalHeaders(): OpenApiCustomiser = OpenApiCustomiser { openApi ->
        openApi.paths.flatMap { it.value.readOperations() }
            .forEach {
                it.addParametersItem(HeaderParameter().name("Header1").required(true))
                it.addParametersItem(HeaderParameter().name("Header2").required(true))
            }
    }
}
```

**Expected behavior**
- When I refresh the browser, it works properly without any duplicated headers.

**Screenshots**
### After running Spring Boot application
<img width="1003" alt="image" src="https://user-images.githubusercontent.com/37795866/187376401-39ee642a-59b7-460e-a602-1f1170bf3137.png">

### Refresh browser once
<img width="971" alt="image" src="https://user-images.githubusercontent.com/37795866/187376506-7ba246d7-9716-40f4-9c6a-eae83d1d733e.png">

### Refresh browser twice
<img width="990" alt="image" src="https://user-images.githubusercontent.com/37795866/187376576-ad770d03-2863-4a12-adfa-ec4c086d441f.png">

**Additional context**
- Disabling the cache through the properties below does not cause duplicate headers.
```
springdoc.cache.disabled= true
```

- I wonder if this is intended or if the configuration is wrong.

- When I debug the code, it seems that `AbstractOpenApiResource` 's `OpenApiCustomizer` logic is related. If it's a bug, I want to send a PR after fixing it.

**Comment by doljae** [comment]
@bnasslahsen ,
You already fixed it, and I couldn't make a contribution 😭 
Anyway, thanks for the quick fix.

**Comment by doljae** [comment]
@bnasslahsen ,
I made PR with tiny adjustment. If you don't mind, please check 🙂

**Comment by chakilamt** [comment]
Want to know how to add alternate type rules in open API config spring boot.
