### ISSUE TITLE
Exposing OpenAPI Spec using Spring Cloud Functions

### ISSUE THREAD

**Issue by bansal-sidhant** [springdoc/springdoc-openapi#1821]
Hi,

I have seen the demo for spring-cloud-functions where the dependencies for open-api are mentioned. The project is working fine as a Spring boot application and is showing the Swagger UI. However, I cannot figure out how to expose the same Swagger UI through Cloud functions using Cloud Adapter. For instance, I am trying with Azure Functions and I have been trying to display the Swagger UI but cannot show the API operations that the Azure Functions create. So, can you please suggest some way to expose the same?

**Comment by bnasslahsen** [comment]
@bansal-sidhant, 

This is a request to the Azure cloud function team ...
