### ISSUE TITLE
MethodParameterPojoExtractor does not respect SpringDocUtils.config class replacement rules for ParameterObject annotated params

### ISSUE THREAD

**Issue by ed0906** [springdoc/springdoc-openapi#1822]
**Describe the bug**
When using the `@ParameterObject` annotation on a class that wraps `@RequestParam`s then the SpringDocUtils.config replacement rules do not seem to apply to the request params within that class.

In the `paths.{url}.{method}.parameters` block the parameter type gets expanded into its sub fields due to the recursive logic in `org.springdoc.core.MethodParameterPojoExtractor#extractFrom(java.lang.Class<?>, java.lang.String)` [(link)](https://github.com/springdoc/springdoc-openapi/blob/8fa89e01ddb7f26fb6ed94b5b4a1b1d6c8e600fd/springdoc-openapi-common/src/main/java/org/springdoc/core/MethodParameterPojoExtractor.java#L117)

For example for a `Locale` parameter which I configure `SpringDocUtils` to replace with class `String` the swagger doc output has parameters

```
{
                  "name":"locale.baseLocale.language",
                  "in":"query",
                  "required":false,
                  "schema":{
                     "type":"string"
                  }
               },
               {
                  "name":"locale.baseLocale.script",
                  "in":"query",
                  "required":false,
                  "schema":{
                     "type":"string"
                  }
               },
               {
                  "name":"locale.baseLocale.region",
                  "in":"query",
                  "required":false,
                  "schema":{
                     "type":"string"
                  }
               },
               {
                  "name":"locale.baseLocale.variant",
                  "in":"query",
                  "required":false,
                  "schema":{
                     "type":"string"
                  }
               }
```

Which is undesirable as it suggests to users all those separate fields are required which are not

**To Reproduce**
Steps to reproduce the behaviour:
- Spring Boot 2.7.1
- springdoc-openapi-ui 1.6.11

Swagger Configuration
```
@Configuration
class ControllerConfiguration() : WebMvcConfigurer {
    init {
        SpringDocUtils.getConfig()
            // Locales are not shown in Swagger endpoints by default, this overrides that setting.
            .removeRequestWrapperToIgnore(Locale::class.java)
            // This ensures they are rendered as Strings.
            .replaceWithClass(Locale::class.java, String::class.java)
    }
}
```

Controller Method
```
@GetMapping
@Operation(summary = "Searches")
fun get(
        @ParameterObject
        search: Search
): List<SomeModel> {...}
```

RequestParam Wrapper class
```
data class Search(
    @Parameter(description = "User Locale")
    val locale: Locale? = null,
)
```

Observe how the api docs json shows the `Locale` class broken down into its sub fields

**Expected behaviour**
In the `paths.{url}.{method}.parameters` block I would expect the locale param to be rendered like
```
{
    "name":"locale",
    "in":"query",
    "required":false,
    "schema":{
      "type":"string"
    }
}
```

**Comment by bnasslahsen** [comment]
@ed0906, 

Use `PropertyCustomizer` or `SpringDocUtils.getConfig().replaceParameterObjectWithClass` where you can add a mapping class.

**Comment by ed0906** [comment]
Appreciate there may be a workaround, but is this not still a bug?
