### ISSUE TITLE
Unable to open swagger API documentation after moved to HTTPs

### ISSUE THREAD

**Issue by maheshvarmasanga** [springdoc/springdoc-openapi#1825]
We have Angular as Front End which runs on ngnix and Spring boot as backend and we are using OpenAPI for API documentaion. It was working fine on localhost. URL: http://localhost:8080/swagger-ui/index.html

![image](https://user-images.githubusercontent.com/105479194/187807528-9d48c10d-7732-42aa-b7f7-dfc91025d8ec.png)

We moved our code to a different server which is behind proxy which runs on https and I am trying to access the swagger but I am getting below message No API definition found when I try to access the URL : https://mycompany.com/swagger-ui/index.html

![image](https://user-images.githubusercontent.com/105479194/187807562-50ce63bd-5f9f-4ef2-9f45-c9d045ef56ea.png)

My application.properties

server.forward-headers-strategy=framework

And my nginx.conf file

location /swagger-ui {
    allow xx.x.0.0/16;
    allow xx.x.0.0/16;
proxy_redirect off;
    proxy_set_header Host $http_host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-Proto https;
    proxy_set_header X-Forwarded-Host $http_x_forwarded_host;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-NginX-Proxy true;
    proxy_set_header X-Forwarded-Protocol https;
    proxy_set_header X-Forwarded-Ssl on;
    proxy_set_header X-Url-Scheme https;
    proxy_pass http://127.0.0.1:8080/swagger-ui;
}

Tried all the possible ways still unable to make the swagger UI work

**Comment by bnasslahsen** [comment]
@maheshvarmasanga,

GITHUB is not the right channel for these questions.
All documented in the F.A.Q:
https://springdoc.org/index.html#how-can-i-deploy-springdoc-openapi-ui-behind-a-reverse-proxy
