### ISSUE TITLE
Support for spring boot jersey

### ISSUE THREAD

**Issue by itzikiusa** [springdoc/springdoc-openapi#183]
Hi, 
i'm having an issue to setup the documentation with Jersey (under spring boot)
is there any way to establish it?

can you provide any example?

also 1 more question
is there anyway to support multiple openapi endpoints?
as we have a gateway which redirects to all of our servers, which have swagger built on them, and we display it from there

**Comment by springdoc** [comment]
Hi, 

 If you are using JAX-RS and as implementation Jersey (`@Path` for example), we do not support it.
 We only support exposing Rest Endpoints using spring managed beans (`@RestController` for example). 
 You can have a look at `swagger-jaxrs2` if it can help:
- https://github.com/swagger-api/swagger-samples/tree/2.0/java/java-jersey2-minimal

**Comment by itziklavon** [comment]
Thanks for the response, creating the swagger json is something i already have, was looking for the UI also

**Comment by isarang** [comment]
Register OpenApiResource.class to generate openapi.json and use spring-doc-mvc-ui for swagger UI
https://stackoverflow.com/questions/71207342/how-to-disable-application-wadl-in-openapi-spec-with-jersey/77744006#77744006
