### ISSUE TITLE
Support Java record for v1.6

### ISSUE THREAD

**Issue by uc4w6c** [springdoc/springdoc-openapi#1830]
Record was supported for v2 in this issue (#1728), but I want to use record for v1.6 as well.

v1.6 is build with Java8, reflection is required to support it, but if that's okay with you, I'm writing the code, so can I raise a pull request?

**Comment by bnasslahsen** [comment]
@uc4w6c,

That is ok to propose a PR.
Just make sure you dont break apps running in java 8 versions.
