### ISSUE TITLE
Caching not working with dynamically multiple GroupedOpenApi 

### ISSUE THREAD

**Issue by russoale** [springdoc/springdoc-openapi#1833]
**Describe the bug**
I am trying to dynamically build multiple `GroupedOpenApis` via `beanFactory`.

Searching through the issues it was recommended to manually register the `MultipleOpenApiResource` bean, like 
```java
    @Bean()
    MultipleOpenApiWebMvcResource multipleOpenApiResource(
            List<GroupedOpenApi> groupedOpenApis, ObjectFactory<OpenAPIService> defaultOpenAPIBuilder,
            AbstractRequestService requestBuilder, GenericResponseService responseBuilder,
            OperationService operationParser, SpringDocConfigProperties springDocConfigProperties,
            SpringDocProviders springDocProviders) {

        
        return new MultipleOpenApiWebMvcResource(groupedOpenApis, defaultOpenAPIBuilder, requestBuilder,
                responseBuilder, operationParser, springDocConfigProperties, springDocProviders);
    }
```
However, although this will register all `GroupedOpenApis` and works without caching, it doesn't with caching enabled.

Debugging the issue I found out following: 

Correct `OpenApiWebMvcResource` resolved via `MultipleOpenApiResource` per group:
https://github.com/springdoc/springdoc-openapi/blob/0b51a686edd25d044ccfeb4712366fa54b4f85e5/springdoc-openapi-webmvc-core/src/main/java/org/springdoc/webmvc/api/MultipleOpenApiResource.java#L191

But all grouped `OpenApiWebMvcResource` share the same singleton `OpenAPIService` that only considers the locale
Therefore, calling `.openapiJson()` on the correct grouped `OpenApiWebMvcResource` will always result in the first openApi cached for the default locale: 
https://github.com/springdoc/springdoc-openapi/blob/0b51a686edd25d044ccfeb4712366fa54b4f85e5/springdoc-openapi-webmvc-core/src/main/java/org/springdoc/webmvc/api/MultipleOpenApiWebMvcResource.java#L88
https://github.com/springdoc/springdoc-openapi/blob/0b51a686edd25d044ccfeb4712366fa54b4f85e5/springdoc-openapi-common/src/main/java/org/springdoc/api/AbstractOpenApiResource.java#L314

**To Reproduce**
- What version of spring-boot you are using? `2.5.14`
- What modules and versions of springdoc-openapi are you using? `1.6.10`

**Expected behavior**
Caching working with multiple `GroupedOpenApis`

**Screenshots**
N/A

**Additional context**
Not sure if this should be provided by the user and custom Factory or this should actually be handled by the `springdoc`.

**Comment by bnasslahsen** [comment]
@russoale,

Review your configuration.
The logic of groups in `springdoc-openapi` never uses `OpenAPIService.class` as Singleton in the cqse of groups.
It should be declared of scope `PROTOTYPE`

See `SpringdocBeanFactoryConfigurer.java` for examples.
