### ISSUE TITLE
RemoveBrokenReferenceDefinitions set to false doesn't work

### ISSUE THREAD

**Issue by evanholt1** [springdoc/springdoc-openapi#1838]
**Describe the bug**
I have a model, called `NotificationsFilter`,
```
@Schema
@Data
public class NotificationsFilter {
    private Long id;
    private String title;
    private String body;
    private String imageUrl;
    private LocalDateTime date;
    private String destination;
}
```
 which is currently used only in one route.
```
getNotifications(
        @ParameterObject NotificationsFilter notificationsFilter
    )
```
**this model does not show up under the `Schemas` tab in the swagger-ui.**

I read about this and about broken references, and added to my `application.properties` file,
`springdoc.remove-broken-reference-definitions=false`,
yet still the model does not show up. 

I also tried using an `OpenApiCustomiser` bean,
```
@Bean
    public OpenApiCustomiser schemaCustomiser() {
        ResolvedSchema resolvedSchema = ModelConverters.getInstance()
            .readAllAsResolvedSchema(new AnnotatedType(NotificationsFilter.class));
        return openApi -> openApi.schema(resolvedSchema.schema.getName(), resolvedSchema.schema);
    }
```
in a `@Configuration` class, but still did not work.

**How can i make the schema show up on swagger-ui, and in the generated .json file?**

if i try removing `@ParameterObject`, it does show up, but in my use case the frontend application
consuming this api will need a customized solution of its own. making another dummy route to add the model to Schemas also works fine,
```
@GetMapping("/addExtraModels")
    public void addExtraModels(
        NotificationsFilter notificationsFilter
    ) {}
```
but both solutions are not ideal.

**To Reproduce**
- What version of spring-boot you are using?
`spring-boot-starter-parent` version `2.7.2`
- What modules and versions of springdoc-openapi are you using?
`springdoc-openapi-ui` version `1.6.11`
- What is the actual and the expected result using OpenAPI Description (yml or json)?
actual: schema does not show up in the json file. expected is that it will show up.

**Expected behavior**
- the schema (and other schemas using @parameterObject) show up in the generated swagger.

**Comment by bnasslahsen** [comment]
@evanholt1, 

Check your `OpenApiCustomiser` code...
