### ISSUE TITLE
springdoc-openapi-ui配置Nginx反向代理之后不能正常访问swagger

### ISSUE THREAD

**Issue by i-mufeng** [springdoc/springdoc-openapi#1839]
我在SpringBoot项目（版本2.7.3）中引用springdoc-openapi-ui（版本1.6.11）之后，访问后端接口地址`/swagger-ui/index.html`可以正常显示。但是在配置Nginx反向代理后端地址到`/api`之后，访问/api/swagger-ui/index.html会显示“`Failed to load remote configuration.`”，检查发现找不到`/v3/api-docs/swagger-config`，但是swagger-config在`/api/v3/api-docs/swagger-config`下。

截图：
[报错页面](https://cdn.imufeng.cn/imufeng/20220909132253.png)
[正确的地址](https://cdn.imufeng.cn/imufeng/20220909132447.png)

我尝试着将`springdoc.swagger-ui.config-url`配置为`/api/v3/api-docs/swagger-config`，但是还是会出现同样的问题，他会去请求`/api/api/v3/api-docs/swagger-config`，（因为我Nginx反向代理的是/api，所以会多一个/api）

看SpringFox源码发现它会有一个baseUrl变量存储 `htts://xxx/api` ，但是springdoc就不行。

不知道是因为我配置的问题还是？希望能得到解答，万分感谢！

**Comment by BiLuoHen** [comment]
Nginx需要配置header
https://springdoc.org/#how-can-i-deploy-springdoc-openapi-ui-behind-a-reverse-proxy
