### ISSUE TITLE
@Schema(hidden = true) in combination with @JsonSerialize

### ISSUE THREAD

**Issue by BobLuursema** [springdoc/springdoc-openapi#184]
I have an entity with a datetime that we only use internally. So for the `openapi.json` I would like to hide it using `@Schema(hidden = true)` but this doesn't work because the field also has an `@JsonSerialize` annotation which makes the field appear again in the `openapi.json`.

I have created a demo to demonstrate it:

```sh
git clone https://github.com/BobLuursema/springdoc-issue-demo.git
cd springdoc-issue-demo
mvn spring-boot:run
```

Go to localhost:8080/swagger-ui.html, you will see the `updateDateTime` value. Now delete the `@JsonSerialize` line in `DemoObject` and refresh the page. The `updateDateTime` field is now gone.

I would expect `@Schema(hidden = true)` to still hide the field when a Serializer is specified.

**Comment by springdoc** [comment]
Hi,

 The behaviour you are describing is not related to springdoc-openapi. 
 We rely on swagger-core official jars. 
 You can override this behaviour by providing your own ModelConverter a spring bean:
  - https://github.com/swagger-api/swagger-core/wiki/Swagger-2.X---Extensions#extending-core-resolver

 You can also submit your enhancement, if you estimate its beneficial to the community on the swagger-core github:
- https://github.com/swagger-api/swagger-core/
