### ISSUE TITLE
Incorrect Schema generation with camel-case parsing.

### ISSUE THREAD

**Issue by ddelegal** [springdoc/springdoc-openapi#1840]
We have a class with fields as follows:

	public class CustomerData {
		private String cCode;
		private List<String> cCodeList;

		public String getcCode() {return cCode;}
		public void setcCode(String cCode) {this.cCode = cCode;}
		public List<String> getcCodeList() {return cCodeList;}
		public void setcCodeList(List<String> cCodeList) {this.cCodeList = cCodeList;}
	}

This class is parsed by OpenAPI (3.0.1) into the following Schema entry:

	"CustomerData": {
		"type": "object",
		"properties": {
			"getcCode": {
				"type": "string"
			},
			"getcCodeList": {
				"type": "array",
				"items": {
					"type": "string"
				}
			}
		}
	}

I would have expected the resulting schema property entries to be cCode and cCodeList, but the parser did not remove the "get" from the names. I suspect this is due to the methods being "getcCode()" rather than "getCCode()" and "getCCodeList()" rather than "getcCodeList()". This causes the sample JSon for the Swagger UI to be incorrect and unless the field names are manually corrected, the call will fail to populate the fields in the paramter object. This happens any time the getters and setters don't follow strict camel-case naming.

We were able to work around this by annotating each offending getter and setter with: @JsonProperty("cCode") or whatever the actual field name should be.

**Comment by bnasslahsen** [comment]
see the answer here: https://github.com/springdoc/springdoc-openapi/issues/664
