### ISSUE TITLE
Remove send empty value check box.

### ISSUE THREAD

**Issue by Sobhan-Akhavan** [springdoc/springdoc-openapi#1841]
When setting the consume in postmapping annotation to "multipart/form-data" below all parameters show Send empty value check box.
Is there any way to remove this?
![Screenshot from 2022-09-10 11-20-10](https://user-images.githubusercontent.com/95710538/189472829-d071ad41-e5e0-45fb-8512-c780e298b414.png)

_Originally posted by @Sobhan-Akhavan in https://github.com/springdoc/springdoc-openapi-demos/issues/26#issuecomment-1242650484_

**Comment by bnasslahsen** [comment]
@Sobhan-Akhavan, 

This is a swagger-ui question. 
Use the right github project for that.
