### ISSUE TITLE
It is possible to define url for each Group - OpenAPI Java

### ISSUE THREAD

**Issue by natanomotor** [springdoc/springdoc-openapi#1846]
I have to open an endpoint for external use by a client, and I have to create documentation for it, but when creating the group in openApi, I can't find a way to restrict the client so that it doesn't see the internal endpoints.

[enter image description here](https://i.stack.imgur.com/l3Hbl.png)

the client should only see the "API" group, is there any way to do this? or is it not possible?

**Comment by bnasslahsen** [comment]
Use spring-security or spring-cloud-gateway or any other api gateway solution to restrict the access to some endpoints.
