### ISSUE TITLE
wrong response schema generation

### ISSUE THREAD

**Issue by m-yazdani** [springdoc/springdoc-openapi#1847]
i'm using springdoc-openapi-ui version 1.6.11 with spring boot version 2.2.2
i have two different static class with different members with the same name in response of the controller method,
the schema that is generated using springdoc uses one of the two different class for both section in my response and actually pick the wrong schema for one of the classes in my response dto.

**Comment by bnasslahsen** [comment]
Remember, contributions to this repository should follow its [contributing guidelines](https://github.com/springdoc/springdoc-openapi/blob/29a72c512457cd01b661ccac67744a9bce04538e/CONTRIBUTING.adoc)
