### ISSUE TITLE
Accented characters not displayed correctly

### ISSUE THREAD

**Issue by AndroidLoop** [springdoc/springdoc-openapi#1849]
**Describe the bug**
When grouping using the `springdoc.group-configs[0].group` and `springdoc.group-configs[0].packages-to-scan` properties, accented characters are translated to `Ã³` (see image below).

**To Reproduce**

- Spring version: Spring boot 2.6.3 (Extrated from POM)
`<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>2.6.3</version>
		<relativePath /> 
	</parent>`
- Version of springdoc-openapi: 1.6.4. POM: `<dependency>
			<groupId>org.springdoc</groupId>
			<artifactId>springdoc-openapi-ui</artifactId>
			<version>1.6.4</version>
		</dependency>`
- OpenAPI Description: JSON
- A sample code: Inside the `application.properties`, just must set a group with an accent in it. `springdoc.group-configs[0].group=Nómina`

**Expected behavior**
- The accent to be displayed correctly in the actual name of the definition as "Nómina"

**Screenshots**
![image](https://user-images.githubusercontent.com/22803987/190406224-60f8fd61-6ca1-41ae-a61f-ed38529a2c37.png)

**Comment by bnasslahsen** [comment]
@AndroidLoop,

Tested with v1.6.11>
Not reproducble.
<img width="605" alt="image" src="https://user-images.githubusercontent.com/13404829/192911781-b81dc059-7e86-461e-98d0-4b0c708cfe35.png">

If still having the issue, review your project configuration.
