### ISSUE TITLE
Annotation @Parameters is ignored

### ISSUE THREAD

**Issue by petronika** [springdoc/springdoc-openapi#185]
Annotation @io.swagger.v3.oas.annotations.Parameters is ignored when used with controller's method.
Actually, I want to do something like this:
`
@GetMapping
@Operation(summary = "List")
@QueryPaging
@QuerySort
// I use HandlerMethodArgumentResolver for Query
public List<?> list(Query query) { ... }

@Retention(RetentionPolicy.RUNTIME)
@Target({ METHOD })
@Parameters({
    @Parameter(name = "page"),
    @Parameter(name = "size")
})
public @interface QueryPaging {
}

@Retention(RetentionPolicy.RUNTIME)
@Target({ METHOD })
@Parameters({
    @Parameter(name = "sort")
})
public @interface QuerySort {
}
`
Is it possible? (of course if @Parameters will be working)

**Comment by springdoc** [comment]
Hi, 

 The support of `@Parameters` will be available on v1.2.13 of springdoc-openapi release.

**Comment by petronika** [comment]
Hi!

I am using version v1.2.15 and @Parameters still not working.

**Comment by btocquec** [comment]
Hi, I'm using 1.3.1 but i'm facing the same issue.
If I want parameters to be taken in account, I have to declare them as parameters in @Operation but if I want my own interface (like @petronika sample), they are not bound.
