### ISSUE TITLE
Separate spring boot dependencies in springdoc-openapi-spring-boot

### ISSUE THREAD

**Issue by jgremmen** [springdoc/springdoc-openapi#1850]
I would like to include springdoc-openapi-ui in our project which is based on spring, yet runs on a WebLogic server without spring-boot. Basically the entire spring mvc infrastructure and configuration is already there but we cannot add spring-boot as a dependency as it adds a massive amount of classes/jars and it seems to break our current configuration. 

Unfortunately there is no way to include springdoc-openapi-ui to the project because of the dependencies with spring-boot. I've tried to exclude the spring boot (actuator) dependencies and write my own configuration classes based on the contents of spring.factories from swagger/spring-openapi but the classes which I still require have dependencies with spring-boot and actuator.

A common solution would be to create a new artefact springdoc-openapi-spring-boot which provides the dependencies and classes required to configure springdoc-openapi as part of a spring-boot application. All the other artefacts should be free from spring-boot dependencies so that it is possible to configure springdoc-openapi-webmvc-core by providing a couple of configuration classes to get it up and running in an already configured environment.

**Comment by bnasslahsen** [comment]
@jgremmen,

Feel free to propose a PR and we will have a look at it.
