### ISSUE TITLE
Is it possible to define multiple example values?

### ISSUE THREAD

**Issue by Vhyseris** [springdoc/springdoc-openapi#1856]
**Describe the bug**
I tried different possibilities to provide multiple example values programatically... e.g. Response Example Value
But nothing worked out.
Using OpenAPI Specification (yml or json file) it's working!
 Is this possible?

**To Reproduce**
- Spring Boot Version: 2.7.4
- Springdoc Openapi Version: 1.6.11

**Expected behavior**
- A dropdown to choose from multiple example values is expected.

**Screenshots**
Used OpenAPI Specification, where it's working
![image](https://user-images.githubusercontent.com/24312538/191800226-f771454f-48fd-43ba-8c65-e3d3b1d37214.png)
Expected result:
![image](https://user-images.githubusercontent.com/24312538/191799906-87ea1a44-2b88-4768-8f93-a20e697fd659.png)

**Comment by bnasslahsen** [comment]
@Vhyseris,

This is sample code that you can adapt:

```java
	@ApiResponse(description = "Successful Operation", responseCode = "200", content = @Content(mediaType = "application/json", schema = @Schema(oneOf = {
			String.class, Integer.class }), examples = {
			@ExampleObject(name = "The String example", value = "urgheiurgheirghieurg"),
			@ExampleObject(name = "The Integer example", value = "311414") }))
```
