### ISSUE TITLE
How can I customize the endpoint prefix?

### ISSUE THREAD

**Issue by andochiwa** [springdoc/springdoc-openapi#1857]
**Describe the bug**
As far as I know, springdoc configures the endpoint prefix via `server.servlet.context-path`.

In my application, my endpoint prefix is not configured by servlet, which means I don't use `server.servlet.context-path`. 
I configure a prefix `internal`, when I access api I use `localhost:8081/internal/xxx` to access it. So the path to swagger-ui should become `localhost:8081/internal/swagger-ui.html` or `localhost:8081/internal/swagger/index.html`. But actually, `localhost:8081/internal/swagger-ui.html` will redirect to `localhost:8081/swagger/index.html`, while `localhost:8081/internal/swagger/index.html` will get the apis information from `localhost:8081/v3/api-docs/swagger-config`, which causes that I can't get the apis information directly, I need to explore `/internal/v3/api-docs` manually on swagger-ui, and I don't know how to solve this problem.

In `springfox` I did not encounter this problem, `springfox` will default to access the prefix I configured to get apis information `/internal/v2/api-docs`

**Comment by andochiwa** [comment]
The difference is that springfox(swagger2) retrieves the apis by replacing the url with a regular expression
https://github.com/springfox/springfox/blob/1e77a660383b615f4cb3a11e854ab9db54ba3aa0/springfox-swagger-ui/src/web/js/springfox.js#L102

while springdoc retrieves api by `context-path` + constants

I think we can provide a different constant than `context-path` to set the port prefix

**Comment by bnasslahsen** [comment]
@andochiwa  use: 

`springdoc.swagger-ui.path =/internal/swagger-ui.html` to get `localhost:8081/internal/swagger-ui.html`

And same for your api-docs endpoint:

`springdoc.api-docs.path=/internal/v3/api-docs` to get `localhost:8081/internal/v3/api-docs`

**Comment by andochiwa** [comment]
@bnasslahsen Unfortunately, this just changes the path to http://localhost:8081/internal/internal/swagger-ui.html and http://localhost:8081/internal/internal/v3/api-docs
Here's a reproducible Hello world
https://github.com/andochiwa/Springdoc-Example

**Comment by andochiwa** [comment]
btw, when using springdoc I need to add `spring-boot-starter-validation` dependency to work properly, I think this is also a bug

**Comment by bnasslahsen** [comment]
@andochiwa,

Your problem comes from your armeria dependencies.
Removing them makes the applications work just as expected.

So you invite you check to what this `armeria` dependencies are doing.
We will not provide any additional help on that. You can ask the `armeria` team for that.
