### ISSUE TITLE
@Parameter(required = false) not work when I use @GetMapping

### ISSUE THREAD

**Issue by jwang0512** [springdoc/springdoc-openapi#1858]
yes, this already answered in #252

but I think springdoc annotation @Parameter(required = false) should override this default behavior.

and:

```java
    @GetMapping("/list")
    public List<DemoItem> list(Integer category, String filter, Integer page, Integer size, String sort) {
    }
```

curl -v 'http://localhost:8080/list'  works well without parameters. why springdoc requires an extra work like:
```java
    public List<DemoItem> list(@RequestParam(required = false) Integer category, @RequestParam(required = false) String filter, @RequestParam(required = false) Integer page, @RequestParam(required = false) Integer size, @RequestParam(required = false) String sort) {
    }
```
it is long and ugly :)

**Comment by bnasslahsen** [comment]
see https://github.com/springdoc/springdoc-openapi/issues/252#issuecomment-564777773
