### ISSUE TITLE
Allow documentation of `/login` and `/logout` routes added by Spring Security

### ISSUE THREAD

**Issue by MLNW** [springdoc/springdoc-openapi#1859]
**Is your feature request related to a problem? Please describe.**
Spring Security adds two routes by default: `/login` and `/logout`

Someone using our REST API should be aware of these routes and get some help on how to use them. For this purpose I would like to use springdoc. But from the documentation and issues I found regarding these routes it is only possible to show the `/login` route by configuring `springdoc.show-login-endpoint: true`. There is no such configuration for the `/logout` route.

There also seems to be no way to change the documentation of the `/login` route after "showing" it. In the UI it looks like the following which is dramatically different than the rest of our API documentation:
![image](https://user-images.githubusercontent.com/20930814/191914793-2ccc1c86-cb1e-4a17-b398-b6db141c1ce5.png)

**Describe the solution you'd like**
I would love to be able to include the `/logout` route next to the `/login` route with a similar configuration value.

It should also be possible to add tags to these routes and change their documentation.

**Describe alternatives you've considered**
It might already be possible to change the documentation of the `/login` route that I have not been able to find even though I have searched the documentation, the issues here on GitHub, and searched Google. In that case, please point me to the right documentation.

**Comment by bnasslahsen** [comment]
@MLNW, 

Feel free to propose a PR for it.

**Comment by MLNW** [comment]
Would you mind keeping the issue open then? In the end it is a feature request that should be tracked and tackled

**Comment by bnasslahsen** [comment]
@MLNW,

We only keep Open ongoing issues.
If you are proposing a PR , we can reopen it. 
Othewise, will be kept closed.
