### ISSUE TITLE
Add support to ignore parameters

### ISSUE THREAD

**Issue by skaba** [springdoc/springdoc-openapi#186]
I have a controller parameter which is resolved by a HandlerMethodArgumentResolver I want to ignore that parameter to be added to swagger definition during autogeneration? I don't see that @Hidden is supported on a Paremeter either, is there a way to do this?

**Comment by springdoc** [comment]
Hi, 

 You can use `@Parameter(hidden = true)`
 You can find some examples on the tests;
- https://github.com/springdoc/springdoc-openapi/blob/master/springdoc-openapi-webmvc-core/src/test/java/test/org/springdoc/api/app9/MyApiController.java
