### ISSUE TITLE
Support multiple domain names

### ISSUE THREAD

**Issue by nkavian** [springdoc/springdoc-openapi#1863]
**Is your feature request related to a problem? Please describe.**

I want to use a single code base for multiple domains. The API functionality is generally the same among all domains.

I'm planning to use a `Customizer` to hide certain endpoints, properties, and enum values based on the domain the request is coming from.

So I want the cached and generated `openapi.json` for domain A to be different than what's generated for domain B.

**Describe the solution you'd like**

I'd like `openAPIService.getCachedOpenAPI()` to be hostname aware and have it generate cached copies per unique hostname.
or
provide some kind of factory/lambda support so we can perform the business logic our selves while just giving you the factory/lambda.

**Describe alternatives you've considered**

I've considered pre-generating the `openapi.json` using the maven plugin or an integration test that reloads the JVM to generate different `openapi.json`; and then store them in my resources folder. But this becomes static and breaks other stuff, like the generated server url will no longer differentiate between my separate production, sandbox, and dev environments.

**Comment by rhallier** [comment]
I've got exactly the same request of a customer of mine.
Is it already supported ? On the roadmap ?

**Comment by bnasslahsen** [comment]
@nkavian, 

You will have to override `OpenApiResource` implementation.
