### ISSUE TITLE
2.0: auto-configuration broken with Spring Boot 3.0.0-M5

### ISSUE THREAD

**Issue by jkreileder** [springdoc/springdoc-openapi#1865]
See: https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-3.0.0-M5-Release-Notes#auto-configuration-registration and https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.7-Release-Notes#auto-configuration-registration

**Comment by bnasslahsen** [comment]
Fixed by #1860
