### ISSUE TITLE
Automatically mark kotlin non nullable fields as required

### ISSUE THREAD

**Issue by imchasingshadows** [springdoc/springdoc-openapi#1867]
**Describe the bug**
I'm not sure if this is a bug or by design. Fields in kotlin data classes which are not nullable or have a default still require the decorator `@field:Schema(required=true)` to generate a spec that marks these fields as required.

**To Reproduce**
- Create a dataclass with some non nullable fields
- generate openapi spec
- fields will not be marked as required

**Expected behavior**
- Mark fields as required if they are not nullable

**Comment by bnasslahsen** [comment]
see Support for non-nullable types in Kotlin #443
