### ISSUE TITLE
Whitelabel error page when accessing swagger page on DEV env but works fine on other environment

### ISSUE THREAD

**Issue by gianfcc** [springdoc/springdoc-openapi#1869]
hi, i have not seen any similar issue about this. we're trying to get swagger to work on our dev environment but it returns a whitelabel error page. but when we deploy the same thing on another environment, it works. (we are using aws)

we have migrated from spring fox to springdoc-openapi

and we use gradle, here's the import we use for springdoc-openapi
implementation 'org.springdoc:springdoc-openapi-ui:1.6.11'

no we do not use webflux. the only configurations we have is a swagger configuration that overrides the OpenAPI object. And the typical annotations in our API like @Operation etc

![dev-swagger-ui](https://user-images.githubusercontent.com/110437728/192996575-b6c97bb7-5845-416f-a723-81e137ba2569.png)

![staging-swagger-ui](https://user-images.githubusercontent.com/110437728/192996639-2e3524f3-40bd-4863-8cd2-559eb5f5a344.png)

**Comment by bnasslahsen** [comment]
Remember, contributions to this repository should follow its [contributing guidelines](https://github.com/springdoc/springdoc-openapi/blob/12a047f923271c101a58c239d552ad54d5b4f8fd/CONTRIBUTING.adoc) and [code of conduct](https://github.com/springdoc/springdoc-openapi/blob/12a047f923271c101a58c239d552ad54d5b4f8fd/CODE_OF_CONDUCT.md).
