### ISSUE TITLE
OpenAPIDefinition with apiKey won't work

### ISSUE THREAD

**Issue by jasonrberk** [springdoc/springdoc-openapi#187]
can't get OpenAPIDefinition working with API KEY

my spring bean looks like so:

```
@Component
@OpenAPIDefinition(
        security = {
                @SecurityRequirement(name = "apiKey")
        }
)
@SecurityScheme(type = SecuritySchemeType.APIKEY,  name = "Authorization", in = SecuritySchemeIn.HEADER)
public class MyBean {}
```

when I look here: http://docs.swagger.io/swagger-core/v2.0.0-RC3/apidocs/index.html?io/swagger/v3/oas/annotations/OpenAPIDefinition.html and here http://docs.swagger.io/swagger-core/v2.0.0-RC3/apidocs/io/swagger/v3/oas/annotations/security/SecurityRequirement.html

SecurityRequirement states:  `If the security scheme is of type "oauth2" or "openIdConnect", then the value is a list of scope names required for the execution. For other security scheme types, the array must be empty.
`

https://github.com/OAI/OpenAPI-Specification/blob/OpenAPI.next/versions/3.0.0.md#securityRequirementObject

says `Each name MUST correspond to a security scheme which is declared in the Security Schemes under the Components Object.`

but the OpenAPIDefinition doesn't provide a `Components` object

I seem to be able to get the `Authorize` button and it lets me set my API KEY, but the key is never attached to any outgoing calls, resulting in 401

**Comment by springdoc** [comment]
Hi, 

 The OpenAPIDefinition is not provided by springdoc-openapi.  We rely on official swagger-annotations jars. 
 If you need more  enhancements, you can submit them to the right project:
- https://github.com/swagger-api/swagger-core/issues


For setting up security, you can use OpenAPI Bean where you have full control on Components object. Please have a look at one of the sample tests:
- https://github.com/springdoc/springdoc-openapi/blob/master/springdoc-openapi-webmvc-core/src/test/java/test/org/springdoc/api/app5/sample/OpenAPIResourceBeanConfigurationComponentsSecuritySchemesTest.java

**Comment by jasonrberk** [comment]
thanks for the fast response.  Your test example worked perfectly.
