### ISSUE TITLE
How do you get a handle on the Method object that maps to any given path?

### ISSUE THREAD

**Issue by juliaisnotavailable** [springdoc/springdoc-openapi#1871]
Given a path and http method e.g. `GET`, `/api/record/{id}` how would I get the associated method object (java.lang.reflect.Method)?

I want to get all the methods annotations to do some of my own post processing as I have some custom annotations that contain additional information I want present on the respective endpoint in the generated doc

I could manually work my way towards this from first principles with a bunch of reflection, but was hoping there was a neater way of doing this provided by springdoc

**Comment by bnasslahsen** [comment]
Remember, contributions to this repository should follow its [contributing guidelines](https://github.com/springdoc/springdoc-openapi/blob/12a047f923271c101a58c239d552ad54d5b4f8fd/CONTRIBUTING.adoc) and [code of conduct](https://github.com/springdoc/springdoc-openapi/blob/12a047f923271c101a58c239d552ad54d5b4f8fd/CODE_OF_CONDUCT.md).
