### ISSUE TITLE
Cannot use Maps in the DTOs NoSuchMethodError

### ISSUE THREAD

**Issue by itmashalov** [springdoc/springdoc-openapi#1872]
org.springframework.web.util.NestedServletException: Handler dispatch failed; nested exception is java.lang.NoSuchMethodError: 'io.swagger.v3.oas.models.media.Schema io.swagger.v3.oas.models.media.Schema.addProperty(java.lang.String, io.swagger.v3.oas.models.media.Schema)'
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1085)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:963)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:898)

**Describe the bug**
I cannot use the library because when I have Java.util.Map in DTOs the swagger documentation is not generated.

**To Reproduce**
Add Map in any DTO used by any controller

**Expected behavior**
Use Maps without any extra configuration required

**Screenshots**
<img width="1266" alt="image" src="https://user-images.githubusercontent.com/5897096/193770645-a7d0dda3-2993-4667-9bc7-70e6ffedd3b8.png">

**Additional context**

**Comment by bnasslahsen** [comment]
@itmashalov,

Review you project dependencies.
And if you still believe you are facing a bug, then update this issue by Providing a [Minimal, Reproducible Example - with HelloController](https://stackoverflow.com/help/minimal-reproducible-example) that reproduces the problem
