### ISSUE TITLE
How to use extensions

### ISSUE THREAD

**Issue by jiwoongleee** [springdoc/springdoc-openapi#1876]
### I want to know how to use `x-enumDescriptions`

※ Question about using `extensions` in `redoc` as `springdoc-openapi`.

Below is sample code that doesn't work.

enum class
```
enum class GoodsStatus {
    NON_DISPLAY,
    DISPLAY,
    TERMINATE
}
```

schema class
```
data class Test(
    @field:Schema(
            description = "status",
            example = "DISPLAY",
            nullable = false,
            extensions = [Extension(
                name = "x-enumDescriptions",
                properties = [ExtensionProperty(name = "DISPLAY", value = "expose the goods")]
            )]
        )
    val status: GoodsStatus
)
```

result screen
<img width="519" alt="image" src="https://user-images.githubusercontent.com/101683129/194218442-51631359-97ba-4337-9fa7-cdeb0e75b505.png">

**Comment by bnasslahsen** [comment]
see this article on how to use extensions:
- https://dzone.com/articles/extending-swagger-and-spring-doc-open-api
