### ISSUE TITLE
Question: How to display required user roles in Swagger UI for Spring's endpoints?

### ISSUE THREAD

**Issue by juvraniak** [springdoc/springdoc-openapi#1877]
Hello,

maybe i did not see it, but is there a possibility to show what roles one needs to have in order to call REST method?

@GetMapping("/profile")
@Secured(ROLE_USER, ROLE_ADMIN)

Thank you

**Comment by bnasslahsen** [comment]
Remember, contributions to this repository should follow its [contributing guidelines](https://github.com/springdoc/springdoc-openapi/blob/12a047f923271c101a58c239d552ad54d5b4f8fd/CONTRIBUTING.adoc) and [code of conduct](https://github.com/springdoc/springdoc-openapi/blob/12a047f923271c101a58c239d552ad54d5b4f8fd/CODE_OF_CONDUCT.md).

**Comment by mauromol** [comment]
I would also be interested in this feature. Why is this closed as "incomplete"?
