### ISSUE TITLE
Improvements on the maturity of the project

### ISSUE THREAD

**Issue by martinbeentjes** [springdoc/springdoc-openapi#188]
First of all, thank you very much for this project. I am glad I can use Spring Boot 2.2.x with Swagger using Springdoc. 

**Why?**
When we improve the maturity of the project, other contributors may feel more welcome to contribute to the project. Also, the first impression to new users will be better and improve the growth of the project.

**How?**
I would like to suggest improvements in two parts of the Springdoc project: the codebase and the source code management, and also the organization side of the project.

We should write meaningful commit messages with a reference to an issue for future clarity. Next, we should keep every PR concise for the issue it is referencing. For the prioritisation of all the pull requests  and issues, we could work with milestones where we work towards and base priority based upon those.

If we want the project to evolve towards a more mature project, I suggest to create an GitHub Organization and move the repositories to that organization. There we can have project maintainers and contributors. This will make project administration a joint effort. 

I appreciate feedback and hopefully we will have a meaningful discussion.

**Comment by springdoc** [comment]
Hi, 

Thank you for your message and your first contribution. 
We will integrate these improvements very soon.

If you feel comfortable with contributing to the project you are welcome.
For other improvements, you don't need to create an issue. You can just contact us directly by email.

**Comment by marcelstoer** [comment]
@martinbeentjes Great, you kind of summerized the 101 for any open-source project.
