### ISSUE TITLE
Support @Hidden annotation on REST repositories

### ISSUE THREAD

**Issue by mjustin** [springdoc/springdoc-openapi#1881]
**Is your feature request related to a problem? Please describe.**
I have a Spring Data REST project where I would like to exclude a specific REST repository from the generated OpenAPI documentation.  I do not see an easy way to do this.  If this were a controller, I could merely annotate it with `@Hidden` to achieve this goal.

**Describe the solution you'd like**
When using `springdoc-openapi-data-rest`, it would be nice if specific repositories could be disabled using [`@Hidden`](https://docs.swagger.io/swagger-core/v2.1.1/apidocs/io/swagger/v3/oas/annotations/Hidden.html) in the same manner as applying it to a controller hides the controller.  A repository thus annotation would be completely skipped as though it did not exist when generating the OpenAPI description.

**Additional context**
This feels in line with how other annotations are supported in `@Repository` classes, for instance [`@SecurityRequirement` and `@Tag`](https://github.com/springdoc/springdoc-openapi/issues/837)

**Comment by bnasslahsen** [comment]
@mjustin, 

Support is now added in `@Repository` level. Not in the operations level.
Note that you can use `OpenApiCustomiser` for any other filtering needed.
