### ISSUE TITLE
Type of parameter defaults to string when using schema

### ISSUE THREAD

**Issue by PyDario** [springdoc/springdoc-openapi#1882]
**Describe the bug**
When a parameter is decorated with @Schema that doesn't specify a type, it default to string instead of the parameter's actual type.

**To Reproduce**
- sprint-boot 2.5.4
- java 1.8
- springdoc-openapi 1.6.11
- Sample code: 
```import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.tags.Tag;

@RestController
@Tag(name = "bug-test", description = "tag to test the bug")
@RequestMapping("/api/v1/bug-test")
public class BugTestController {
    @GetMapping
    @Operation(description = "testing the bug")
    public ResponseEntity<String> bugWithoutParameterObject(
        @Parameter(schema = @Schema(example = "123")) @PathVariable("test") final Integer test
    ) {
        ResponseEntity<String> response = new ResponseEntity<String>(HttpStatus.OK);
        return response;
    }
}
```

**Expected behavior**
When adding a @Schema decorater to a parameter, I expect it to use the actual type. Only when I specify a type, should it change in the API.

**Screenshots**
![grafik](https://user-images.githubusercontent.com/56290011/195059512-f1f9eab3-9ba5-428a-9795-3c2795141242.png)

**Comment by bnasslahsen** [comment]
@PyDario, 

You schema is empty and default value will be string.
This is handled in the swagger-core, method `AnnotationsUtils.getSchema` if you need more details.

**Comment by PyDario** [comment]
> @PyDario,
> 
> You schema is empty and default value will be string. This is handled in the swagger-core, method `AnnotationsUtils.getSchema` if you need more details.

I do realize that. My issue with that is that it seems arbitrary to default to string, if the type of the parameter is known. In my example, the parameter "test" is declared as an Integer. If no type is specified in the schema, it would make sense to default to the parameters's type instead of simply string.
