### ISSUE TITLE
Inject environment variables into static openapi.yaml file to set servers: spingdoc-openapi-ui [only]

### ISSUE THREAD

**Issue by bh4r4th** [springdoc/springdoc-openapi#1883]
### Current Behaviour

I have a static `openapi.yaml` file. 
Looks something like this:
```
openapi: 3.0.0
info:
  title: API
  description: >-
    Awesome API
  contact:
    name: bh4r4th
    email: nenethopu@gmail.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 2.0.0
servers:
  - url: http://localhost:8080
    description: Dev Server
  - url: http://www.example.com
    description: Prod Server
```

### Expected Behaviour
And I am trying to achieve something like this:

```
openapi: 3.0.0
info:
  title: API
  description: >-
    Awesome API
  contact:
    name: bh4r4th
    email: nenethopu@gmail.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 2.0.0
servers: ${SWAGGER_API_URLS}
```

**NOTE:** I am trying to set an environment variable called: `SWAGGER_API_URLS`

### Current Configuration
My application.yaml settings look something like this:

```
springdoc:
  swagger-ui:
    url: /api-docs/openapi.yaml
    path: /api-docs

    # Provides a search bar to filter tags
    filter: true

    # To disable default petstore urls
    disable-swagger-default-url: true

    # Settings allow to pick only API swagger on topbar
    # FYI: To hide swagger topbar, need to pass a custom css
    urls[0]:
      name: API
      url: /api-docs/openapi.yaml

    # Set `default-models-expand-depth` and not `default-model-expand-depth` to suppress schemas at the bottom of swagger
    default-models-expand-depth: -1
```

### **My software dependencies:**

```
* springdoc-openapi-ui: 1.6.11
    * swagger-ui: 4.14.0 (child dependency)
* spring-boot: 2.6.6
* maven: 3.8.1
```

### **I also tried (None Worked):** 
 1. I have tried setting `@OpenAPIDefinition` on main Application class and configuration class
 2. Also tried, adding Beans like `OpenApiCustomizer`, `OpenApi`, `GlobalOpenApiCustomizer`

**### Queries / Concerns / Requests:** 
 1. How can I achieve this
    * As I am building this application as docker image and using same image to build different instances.
    * Allowing this `servers` to be parameterise, I can set a `Demo` and `Prod` Servers for each of my 100's of clients
 2. Or, am I missing any out of the box solution for this?

**Comment by bnasslahsen** [comment]
@bh4r4th,

This is a static configuration file. There is no way to achieve what you want.
You should have a file generated dynamically for each environment.
