### ISSUE TITLE
Problem handling embedded records in 1.6.11

### ISSUE THREAD

**Issue by hrstoyanov** [springdoc/springdoc-openapi#1884]
**Describe the bug**
Springdoc 1.6.11 mishandles embedded Java records

**To Reproduce**
Take a look at these Java snippets of code:
```java
interface A {
  record Request(String requestA){}
  record Response(String responseA){}
}
```
and

```java
interface B {
  record Request(String requestB){}
  record Response(String responseB){}
}
```
and this api rest controller:

```java
@RestController
class Api { 

 @Operation(summary = "Operation A") @PostMapping
 A.Response operationA(@RequestBody A.Request request){...}

 @Operation(summary = "Operation B") @PostMapping
 B.Response operationA(@RequestBody B.Request request){...}

}
```

**Expected behavior**
The generated documentation should differentiate between the different embeeded Request/Response records, as they are differ between api A and B.

**The issue**
The generated documentation schema only shows one definition for  Request/Response  and spreads ithem accross all operations.

**Comment by bnasslahsen** [comment]
@hrstoyanov,

use explicit naming:
```java
interface A {
	@Schema(name = "RequestA")
	record Request(String requestA){}

	@Schema(name = "ResponseA")
	record Response(String responseA){}
}
interface B {
	@Schema(name = "RequestB")
	record Request(String requestB){}

	@Schema(name = "ResponseB")
	record Response(String responseB){}
}
```

The other solution, would be to use `springdoc.use-fqn=true`, but you will face this `swagger-core` limitation:
https://github.com/swagger-api/swagger-core/issues/4215
