### ISSUE TITLE
404 response on /swagger-ui.html

### ISSUE THREAD

**Issue by bitbaggi** [springdoc/springdoc-openapi#1887]
**Describe the bug**
Hey Guys,

i'm testing the springdoc-openapi-ui with springdoc-openapi-native and spring with native build.
But when i try to access swagger-ui with /swagger-ui.html then spring respond with an 404 page.

**To Reproduce**
Clone and start this spring project
https://github.com/bitbaggi/test-spring-docs-native
Visit http://localhost:8080/swagger-ui.html

**Expected behavior**
Swagger-UI opens with this url

**Comment by bnasslahsen** [comment]
@bitbaggi,

You using wrong version...
If you want use spring-boot-3, try using [Spring Boot 3.0.0-M5](https://spring.io/blog/2022/09/26/native-support-in-spring-boot-3-0-0-m5) with `springdoc` `2.0.0-M7-SNAPSHOT`.

**Comment by bitbaggi** [comment]
@bnasslahsen 

Can you check again my repository?
Now i use the versions you mentioned.

If i start the project with my ide (IntelliJ) then swagger-ui is working.
But when i build the project with 'gradlew bootBuildImage' its not.

When i load to http://localhost:8080/swagger-ui.html spring redirects me to /swagger-ui/index.html and shows an error 404.
[log.txt](https://github.com/springdoc/springdoc-openapi/files/9828182/log.txt)

Did i anything wrong?

**Comment by bitbaggi** [comment]
@bnasslahsen

Okay that's working.

But now i get an exception from api call /v3/api-docs
"java.lang.NoSuchMethodException: No value method found"

[exception.txt](https://github.com/springdoc/springdoc-openapi/files/9829893/exception.txt)

Is their anything wrong with my operation annotation?
```
@Controller
@Tag(name = "Test")
@RequestMapping(path = "api")
public class TestResource {

    @Operation
    @GetMapping(path = "test")
    public ResponseEntity<String> test() {
        return ResponseEntity.ok("Test");
    }
}
```

**Comment by bitbaggi** [comment]
How did you build it?
With gradlew bootBuildImage?

Or with an other way?

**Comment by bnasslahsen** [comment]
@bitbaggi,

using:

```bash
./gradlew nativeCompile
```

**Comment by nidhikaushal** [comment]
Hi, 
I am facing a similar issue. On accessing /swagger-ui.html it redirect to /${APPLICATION_NAME}/swagger/index.html and then returns error 404. 
I am using 'spring-boot-starter-webflux:3.0.3' with 'springdoc-openapi-starter-webflux-ui:2.1.0'. Following is the configuration in my application.yml:

springdoc:
  packagesToScan: com.company
  swagger-ui:
    defaultModelsExpandDepth: -1
    path: "/swagger-ui.html"
  webjars:
      prefix: /${APPLICATION_NAME}

Please guide

**Comment by matt-hires** [comment]
Maybe this helps: https://github.com/springdoc/springdoc-openapi/issues/2204#issuecomment-1511377371

**Comment by oliveira-jo** [comment]
To solve this problem in 13/03/25 just to update version in pom:
```
<dependency>
    <groupId>org.springdoc</groupId>
    <artifactId>springdoc-openapi-starter-webmvc-ui</artifactId>
    <version>2.8.5</version>
</dependency>
```

o/
