### ISSUE TITLE
Make pathsToExclude / pathsToMatch more flexible

### ISSUE THREAD

**Issue by Mumeii** [springdoc/springdoc-openapi#1890]
**Is your feature request related to a problem? Please describe.**

The trouble I've encountered is described [here](https://github.com/springdoc/springdoc-openapi/issues/1521#issuecomment-1144890001)
To sum it up : 
Right now it don't seem possible to express the following exclusion / inclusion formula : 

```
Exclude all endpoints starting with /actuator endpoint
BUT keep /actuator/ping
BUT exclude /actuator/ping/*
```

**Describe the solution you'd like**
I'd like to be able to expresse a sequence of black and white listing formulas

This way, no matter how many new actuator endpoints I activate after defining my formula, only the /actuator/health will keep appearing

**Describe alternatives you've considered**
None

**Additional context**
See previously referenced comment I've made on a previous Issue

Notice that I've experience this trouble in my team this week.

Someone needed to expose new /actuator/prometheus endpoints, but he wasn't aware that he also needed to exclude them from the exposed endpoint thru the use of the `pathsToExclude` parameter

So his modification & commit necessitated a new one afterward ... 😢

**Comment by bnasslahsen** [comment]
@Mumeii,

For paths filtering `pathsToExclude / pathsToMatch` are available and answering more than 99% of use cases.
For more specifc filtering rules, you can simply rely on `OpenApiCustomiser`

If you believe there another flexible way, please feel free to propose a PR.
