### ISSUE TITLE
springdoc.model-and-view-allowed

### ISSUE THREAD

**Issue by jlafuenteriberaLM** [springdoc/springdoc-openapi#1892]
**Describe the bug**
If property **springdoc.show-actuator=true** is set and **springdoc.model-and-view-allowed=false**, ModelAndVew Endpoints are still exposed in swagger.

If property **springdoc.show-actuator=false** is set and **springdoc.model-and-view-allowed=false**, ModelAndVew Endpoints are not exposed.

**Expected behavior**
ModelAndView endpoints should not appear even if **springdoc.show-actuator=true**.

**Comment by bnasslahsen** [comment]
Not reproducible
Please Provide a [Minimal, Reproducible Example - with HelloController](https://stackoverflow.com/help/minimal-reproducible-example) that reproduces the problem.

This ticket will be closed, and can be reopened if the relevant information are provided.

**Comment by jlafuenteriberaLM** [comment]
Here is and example,
[https://github.com/jlafuenteriberaLM/HelloTestSpringDoc](https://github.com/jlafuenteriberaLM/HelloTestSpringDoc)

SwaggerURL -> http://localhost:8080/hello/swagger-ui/index.html

If started with this properties:

springdoc.show-actuator=true
springdoc.model-and-view-allowed=false

Actuator endpoint and ModelAndView Enpoint are shown. (ModelAndView should not)
![1](https://user-images.githubusercontent.com/86775128/196624163-a64ee7c0-a6aa-4b24-809f-7434e644d7fe.png)

If started with this properties:

springdoc.show-actuator=false
springdoc.model-and-view-allowed=false
![2](https://user-images.githubusercontent.com/86775128/196624203-7ebf62ef-45de-4559-80ba-ffb8bf01a8fa.png)

Actuator endpoint and ModelAndView Enpoint are not shown.

**Comment by bnasslahsen** [comment]
@jlafuenteriberaLM,

This will be out of the box for the next release.
The workarounds for now, is to add   `@Hidden` on the method with `ModelAndView`
