### ISSUE TITLE
@Parameter Header coming as null from controller

### ISSUE THREAD

**Issue by gomesclarence** [springdoc/springdoc-openapi#1893]
Hi, 

I am passing a class object as Request Header and am using @ParameterObject to view all fields in swagger UI. The fields inside this class object do not get the values that is passed from swagger UI and are NULL. Please let me know how can this object be mapped with values passed in swagger UI.

Here is my controller signature
`
@Operation(description = "Normal desc")

@GetMapping(value = "/endpoint", produces = "application/json")

public ResponseEntity searchOrders(@ParameterObject HeaderParameterObject headerObj) {
     return null;
}
`

Here is my class object
`
public class HeaderParameterObject {

  @Parameter(name = "LanguageCode", in = ParameterIn.HEADER)
  String languageCode;
   
   --- more 5 fields with similar declaration

`

**Comment by bnasslahsen** [comment]
@gomesclarence,

Your description is not even readable.

Please provide a clear description and a [Minimal, Reproducible Example - with HelloController](https://stackoverflow.com/help/minimal-reproducible-example) that reproduces the problem.

This ticket will be closed. But can be reopened if it's updated with all the required information.

**Comment by gomesclarence** [comment]
Hi,

I am passing a class object as Request Header and am using @ParameterObject to view all fields in swagger UI. The fields inside this class object do not get the values that is passed from swagger UI and are NULL. Please let me know how can this object be mapped with values passed in swagger UI.

Issue similar to #544 

Here is my controller signature
`
@Operation(description = "Normal desc")
@GetMapping(value = "/endpoint", produces = "application/json")
public ResponseEntity HelloController(@ParameterObject HeaderParameterObject headerObj) {
return null;
}
`

Here is my class object that consists of 5 fields
`
public class HeaderParameterObject {
@parameter(name = "LanguageCode", in = ParameterIn.HEADER)
String languageCode;
}`

**Comment by jjtt** [comment]
This is an old issue, but it's the closest thing I found to the issue I'm having where fields in a `@ParameterObject` annotated with `in = ParameterIn.HEADER` do not work the way I expected.

A minimal reproducible example can be found here: https://github.com/jjtt/parameterobjectheader

@bnasslahsen would you consider reopening?

@gomesclarence did you ever find a fix or a workaround for your issue?
