### ISSUE TITLE
Can't use SpringDocUtils

### ISSUE THREAD

**Issue by AnthonyGress** [springdoc/springdoc-openapi#1894]
**Describe the bug**
- Can't seem to utilize spring doc utils. There is no import available.

**To Reproduce**
- SpringBoot 2.7.4
- Install springdoc and try to import springDocUtils into any class.

**Expected behavior**

- Should be exported from main pacakage right? I am using gradle and have installed springdoc as
`dependencies {
    implementation "org.springdoc:springdoc-openapi-ui:1.6.12"}`

**Screenshots**

<img width="469" alt="Screen Shot 2022-10-18 at 11 41 17 AM" src="https://user-images.githubusercontent.com/70029654/196478629-577d3243-13df-4428-9031-2607d96a972a.png">

**Comment by bnasslahsen** [comment]
@AnthonyGress 

Review your code
