### ISSUE TITLE
Pageable and @ParameterObject does not work for Repository specified endpoints

### ISSUE THREAD

**Issue by tmbell** [springdoc/springdoc-openapi#1895]
@gotson posted a comment about adding a global configuration property to switch the default behaviour:

====

       I understand your point, but I am dubious about the use you mention, because Pageable in Spring is a repository convenience, with argument resolvers to map the 3 params to an instance of Pageable when passed in a url.

Maybe we could have a globale configuration property to switch the behavior to something similar to what @ParameterObject does, but without having to specify the annotation on each and every Pageable in the application.

Even better, this configuration could be set to true by default, and if someone really want to use a Pageable as an object parameter, they could change the configuration to false.

_Originally posted by @gotson in https://github.com/springdoc/springdoc-openapi/issues/559#issuecomment-612611463_
      
====

I do not generally need to override the all endpoints provided by spring data jpa, but I do want swagger to document the pageables properly ( or at least only once )

**Comment by bnasslahsen** [comment]
@tmbell, 

Please provide a [Minimal, Reproducible Example - with HelloController](https://stackoverflow.com/help/minimal-reproducible-example) that shows 
- the limitation you are facing
- and the enhancement you are excepting.
