### ISSUE TITLE
@Parameter Header coming as null from controller

### ISSUE THREAD

**Issue by gomesclarence** [springdoc/springdoc-openapi#1896]
Hi,

I am passing a class object as Request Header and am using @ParameterObject to view all fields in swagger UI. The fields inside this class object do not get the values that is passed from swagger UI and are NULL. Please let me know how can this object be mapped with values passed in swagger UI.

Here is my controller signature

	@Operation(description = "Normal desc")
	@GetMapping(value = "/endpoint", produces = "application/json")
	public ResponseEntity HelloController(@ParameterObject HeaderParameterObject headerObj) 
        { 
             return null; 
        }

Here is my HeaderParameterObject class

        public class HeaderParameterObject {
	       @parameter(name = "Accept-Language", in = ParameterIn.HEADER)
                String languageCode;

                @parameter(name = "X-countryCode", in = ParameterIn.HEADER)
                String countryCode;
        }

Swagger screenshot

![Swagger](https://user-images.githubusercontent.com/31789440/196603729-209c3374-5fe3-4623-a3cd-18c5a01d3576.jpg)

Intellij Debugger screenshot

![Intellij](https://user-images.githubusercontent.com/31789440/196604799-5b126c0c-618e-4dd5-a7d6-f893ba7bd5c7.jpg)

**Comment by bnasslahsen** [comment]
@gomesclarence,

Remove `@ParameterObject` and make sure you are having a running example.
And check the REST CALL with your Intellij Debugger.

After that we can discuss...
