### ISSUE TITLE
 @Schema being ignored in @ParameterObject

### ISSUE THREAD

**Issue by fkreis** [springdoc/springdoc-openapi#1899]
Dear springdoc-openapi maintainers,
thank you for the great tool!

I faced the same issue as @olliekrk in https://github.com/springdoc/springdoc-openapi/issues/1340  using spring-doc 1.6.11. I disagree with @bnasslahsen that this is not a bug. Please let me convince you that this is an unexpected behavior.

Please consider the following example. It is a slightly adjusted version of @olliekrk 's example to make my point more clear.
```java
@Getter
@Schema(implementation = String.class)
class OrganizationId {
    String id;
    String department;

    @JsonCreator
    public OrganizationId(String id) {
        this.id = id;
        this.department = id + "_SoftwareDevelopment";
    }
}
@Getter
@AllArgsConstructor
class EmployeeFilter {

    @Parameter(name = "organizationId", description = "Id of an organization")
    OrganizationId organizationId;

    @Parameter(description = "Id of an employee")
    String employeeId;
}

@RestController
class Controller {

    @GetMapping(value = {"/employee"})
    @Operation(summary = "Get employee")
    ResponseEntity<Object> getEmployee(
            @ParameterObject EmployeeFilter employeeFilter,
            @RequestParam OrganizationId organizationIdAsRequestParam
    ) {
        return null;
    }

}
```

Please note:
- `OrganizationId` has an additional field `department`
- `OrganizationId` now has a constructor with `@JsonCreator` annotation
- `OrganizationId` still has the `@Schema(implementation = String.class)` annotation
- I moved the `@ParameterObject` annotation from `EmployeeFilter` to the `Controller`'s `employeeFilter` parameter
- Controller has an additional `@RequestParam OrganizationId organizationIdAsRequestParam`

In my example, there are two usages of `OrganizationId`, once nested in `EmployeeFilter` and once directly used as `@RequestParam organizationIdAsRequestParam`. This is how they are rendered:

![image](https://user-images.githubusercontent.com/8862141/191497432-a406a97b-bed4-4fe1-9a25-d3274a35e81a.png)

1. ✔️ `employeeId` is as expected 
2. ✔️ `organizationIdAsRequestParam` is a simple String as expected, since its class  `OrganizationId` has the `@Schema(implementation = String.class)` annotation
3. 🐞the nested `organizationId` is not displayed correctly. Its fields are being displayed with the dot notion, even though its class  `OrganizationId` has the `@Schema(implementation = String.class)` annotation

Usually you can move all `@RequestParam`s 1:1 into  `@ParameterObject` without changing the behavior (this is the purpose of  `@ParameterObject`). However, in this case this leads to a change as presented. It appears to me that within the  `@ParameterObject` , all @Schema annotations are being ignored (I did some more experiments). 

To further "proof" that this is an unexpected behavior let's execute some http requests against the Controller and observe the resolved parameters:

```
http://localhost:8080/employee?organizationIdAsRequestParam=as-expected
```
Result (✔️ es expected):
![image](https://user-images.githubusercontent.com/8862141/191502842-b8c93ec3-62c4-4818-b587-5bf08912794f.png)

```
http://localhost:8080/employee?organizationId.id=some-id&organizationIdAsRequestParam=as-expected
```
Result (⚠️):
Exception! organizationId.id cannot be bound to `OrganizationId`

```
http://localhost:8080/employee?organizationId=a-request-that-swagger-does-not-allow&organizationIdAsRequestParam=as-expected
```
Result (⚠️):
Please note that I now requested with organizationId (without .id).
This results in a properly created `OrganizationId`, even within the `EmployeeFilter`. However, this request cannot be done with the rendered Swagger UI.
![image](https://user-images.githubusercontent.com/8862141/191503811-2c9a84fe-7605-477d-b17a-ed8440c2ea8c.png)

The last two http requests proof that the generated Swagger Spec does NOT represent the actual API and hence is not correct.

P.S.:
SpringDocUtils.getConfig().replaceParameterObjectWithClass(OrganizationId .class, String.class) also did not change anything.

_Originally posted by @fkreis in https://github.com/springdoc/springdoc-openapi/issues/1340#issuecomment-1253645691_

**Comment by bnasslahsen** [comment]
@fkreis,

See there original answer and stop creating duplicates
