### ISSUE TITLE
SwaggerUIBundle is not defined at window.onload() | Autolinker Invalid regular expression

### ISSUE THREAD

**Issue by torsten-github** [springdoc/springdoc-openapi#190]
Running local is ok.
Running on JBoss the Swagger-UI crashes. See attached log.

Using spring-boot-starter-parent 2.2.1.RELEASE (see attachment)

- In a REST API with a static index.html at root. 
- Context root set via jboss-web.xml
- The static.html only works, if I set `springdoc.swagger-ui.path=` but any way swagger-ui.html does not show up when published to JBoss. Locally ok. 
- Played around with `server.servlet.context-path=` no change
- `server/context-root/swagger-ui.html` gets some how redirected to `server/context-root//swagger-ui.html?url=...`  notice the double `/` after context-root. Change url by hand has also no effect.

![2019-11-26 14_05_47-Swagger UI](https://user-images.githubusercontent.com/9803030/69636012-f8c2c500-1055-11ea-96bc-14d157b55589.jpg)
[springdoc-openapi.log](https://github.com/springdoc/springdoc-openapi/files/3891973/springdoc-openapi.log)
![2019-11-26 13_57_40-bqr-api  D__code_bqr-api  -  _pom xml - IntelliJ IDEA](https://user-images.githubusercontent.com/9803030/69636100-20b22880-1056-11ea-92da-d86b25ea6456.jpg)

**Comment by torsten-github** [comment]
After investigation e bid more, I believe it's a `UTF-8` issue. Maybe on the server side... ?

**Comment by springdoc** [comment]
Hi, 

 Tested with wildfly-servlet-17.0.1.Final and spring-boot 2.2.1.RELEASE.

 As per spring-boot documentation:
> If you use JBoss, you need to declare the webjars-locator-jboss-vfs dependency instead of the webjars-locator-core. Otherwise, all Webjars resolve as a 404

 The following dependency configuration should work on jboss.

```xml
<dependency>
	<groupId>org.springdoc</groupId>
	<artifactId>springdoc-openapi-ui</artifactId>
	<version>1.2.11</version>
	<exclusions>
		<exclusion>
			<artifactId>webjars-locator</artifactId>
			<groupId>org.webjars</groupId>
		</exclusion>
	</exclusions>
</dependency>

<dependency>
	<groupId>org.webjars</groupId>
	<artifactId>webjars-locator-jboss-vfs</artifactId>
	<version>0.1.0</version>
</dependency>| Autolinker Invalid regular expression
```

 The double / after context-root and the js errors, you can review your application configuration.
 If this doesn't help, please add the sample code of a simple demo application to reproduce.
