### ISSUE TITLE
The format of 'LocalDateTime' in 'Example Value' in the Responses is incorrect

### ISSUE THREAD

**Issue by xuxiaowei-com-cn** [springdoc/springdoc-openapi#1905]
**Describe the bug**
The format of 'LocalDateTime' in 'Example Value' in the Responses is incorrect

**To Reproduce**
Run Project https://github.com/xuxiaowei-com-cn/springdoc , access [http://127.0.0.1:8080/swagger-ui/index.html#/UsersRestController/page](http://127.0.0.1:8080/swagger-ui/index.html#/UsersRestController/page)

**Expected behavior**
It is hoped that the returned value of 'Example Value' can be processed according to the format of `@JsonFormat`

**Screenshots**
![image](https://user-images.githubusercontent.com/46893436/197470224-e8666aa4-02f0-4ad3-b08f-f2a3967a9853.png)
![image](https://user-images.githubusercontent.com/46893436/197470271-e00073c6-26d1-42cb-ad1f-640d8e369072.png)

**Additional context**

**Comment by xuxiaowei-com-cn** [comment]
![image](https://user-images.githubusercontent.com/46893436/197471099-5a3060b6-b12d-4776-95dc-3c59a8a8c4be.png)

**Comment by bnasslahsen** [comment]
@xuxiaowei-com-cn,

The generated OpenAPI description is corresponding to your code.
If you have problem in UI display. Feel free to report it to the swagger-ui project.
