### ISSUE TITLE
One click expansion

### ISSUE THREAD

**Issue by xuxiaowei-com-cn** [springdoc/springdoc-openapi#1906]
![image](https://user-images.githubusercontent.com/46893436/197494826-eb660241-4e2e-46d0-b449-ca9d0d1c57a1.png)

**Comment by bnasslahsen** [comment]
This related to https://github.com/swagger-api/swagger-ui

Remember, contributions to this repository should follow its [contributing guidelines](https://github.com/springdoc/springdoc-openapi/blob/00e7cc2b4cae904090c3d2962fc2d73bcf629c3a/CONTRIBUTING.adoc) and [code of conduct](https://github.com/springdoc/springdoc-openapi/blob/00e7cc2b4cae904090c3d2962fc2d73bcf629c3a/CODE_OF_CONDUCT.md).
