### ISSUE TITLE
Disable/enable Swagger-UI generation based on env variable

### ISSUE THREAD

**Issue by aoudiamoncef** [springdoc/springdoc-openapi#191]
Hi,
The usecase is very common, we have to enable Swagger UI in dev && QA environments and disable it in production. In SpringFox, they have a boolean value to do it.

`.enable(this.appProperties.getSwagger());`

It could be a great feature to add this to SpringDocs.

Thanks

**Comment by springdoc** [comment]
Hi, 

 This feature will be added on v1.2.12, of springdoc-openapi.
 This property helps you disable only the ui.
```properties
springdoc.swagger-ui.enabled=false
```
The following property, will help you disable the api-docs Rest endpoints as well:

```properties
springdoc.api-docs.enabled=false
```

**Comment by aoudiamoncef** [comment]
Great 👍, thank you so much.

**Comment by csckcac** [comment]
Thank you for the env variable it is very useful.

just leave a comment here for reference, if i disabled springdoc UI,
`http://localhost:8080/as/swagger-ui/index.html?configUrl=/as/v3/api-docs/swagger-config` will show a swagger ui page with a message `Failed to load remote configuration.`
![image](https://user-images.githubusercontent.com/239290/127260168-6f20097f-fa48-4916-87a5-3749db13d69e.png)

I understand i could use a reverse proxy and somehow disable this page in production, but is there any native method to hide this page ?

**Comment by ugurh** [comment]
springdoc:
  swagger-ui:
    enabled: false
  api-docs:
    enabled: false
