### ISSUE TITLE
Wrong type for springdoc.swagger-ui.oauth.useBasicAuthenticationWithAccessCodeGrant configuration property

### ISSUE THREAD

**Issue by hkinder** [springdoc/springdoc-openapi#1911]
https://github.com/springdoc/springdoc-openapi/blob/00e7cc2b4cae904090c3d2962fc2d73bcf629c3a/springdoc-openapi-common/src/main/java/org/springdoc/core/SwaggerUiOAuthProperties.java#L85

Today "springdoc.swagger-ui.oauth.useBasicAuthenticationWithAccessCodeGrant" is a String in the Properties for Springdoc.
According to the documentation of swagger-ui this entry should be a Boolean :
https://github.com/swagger-api/swagger-ui/blob/master/docs/usage/oauth2.md (look for useBasicAuthenticationWithAccessCodeGrant entry)

This result to a bug as soon as the value "false" is set for example to that property in springdoc.
It will result to a string in swagger-ui configuration :
`ui.initOAuth({"useBasicAuthenticationWithAccessCodeGrant":"false"})`
And then swagger-ui will consider the value as true in their javascript code :
https://github.com/swagger-api/swagger-ui/blob/8f63462f9eb634b9319a8be7cfe7090fbe8e304c/src/core/oauth2-authorize.js#L119

If changing the type to Boolean, then the code will be fine in swagger-ui configuration :
`ui.initOAuth({"useBasicAuthenticationWithAccessCodeGrant":false})`
Resulting in the right interpretation by swagger-ui.

**Comment by bnasslahsen** [comment]
@hkinder,

Are you willing to propose a PR for it?
