### ISSUE TITLE
Swagger-ui shows petstore as default when it's configured in WebMvcConfigurationSupport

### ISSUE THREAD

**Issue by arturCwiklinsky** [springdoc/springdoc-openapi#1913]
Is it possible to use springdoc-openapi 1.6.8 with Spring 5.3 and Configuration class that extend `WebMvcConfigurationSupport`?

I am facing the problem when everything works besides of swagger-ui page. Other issues suggested to use `addResourceHandler` and I did so.

```
@Override
    public void addResourceHandlers(ResourceHandlerRegistry registry) {
        registry.addResourceHandler("/swagger-ui/**")
                .addResourceLocations("classpath:/META-INF/resources/webjars/swagger-ui/4.10.3/");
    }
```

This resource handler has helped me, but when I get to `/swagger-ui/index.html` there's always default petstore documentation path which is annoying.

I have tried to configure springdoc in properties but with no effect.
I have used following properties

```
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.configUrl=/openapi/swagger-config
springdoc.swagger-ui.url=/openapi
springdoc.api-docs.path=/openapi
```

`springdoc.api-docs.path=/openapi` works and change the path. I see json documentation
`springdoc.swagger-ui.....` properties don't work, there's no effect.

I also have noticed that when I exchange `WebMvcConfigurationSupport` with `DelegatingWebMvcConfiguration` and remove `addResourceHandler()` everything is okay, but I need to use `WebMvcConfigurationSupport`

In dependencies i have
```
<dependency>
    <groupId>org.springdoc</groupId>
    <artifactId>springdoc-openapi-ui</artifactId>
    <version>1.6.8</version>
</dependency>
```

and plugin for code generation
```
<plugin>
    <groupId>io.swagger.codegen.v3</groupId>
    <artifactId>swagger-codegen-maven-plugin</artifactId>
    <version>3.0.27</version>
</plugin>
```

**Comment by bnasslahsen** [comment]
@arturCwiklinsky, 

By default you don't need to declare any `WebMvcConfigurationSupport`. it's all out of the box

If you are overrding the springdoc configuration, there are many cases Already answered.
There are so many tickets around this : #1227 https://github.com/springdoc/springdoc-openapi/issues/150 https://github.com/springdoc/springdoc-openapi/issues/361 https://github.com/springdoc/springdoc-openapi/issues/236
