### ISSUE TITLE
openapi-starter-webmvc-ui:2.0.0-RC1 + openapi-security crashes at startup #1904

### ISSUE THREAD

**Issue by aijaz2** [springdoc/springdoc-openapi#1914]
**Describe the bug**
This might be related to issues https://github.com/springdoc/springdoc-openapi/issues/1607, https://github.com/springdoc/springdoc-openapi/issues/1617, and https://github.com/springdoc/springdoc-openapi/issues/1904

```
***************************
APPLICATION FAILED TO START
***************************

Description:

The bean 'webConversionServiceProvider', defined in class path resource [org/springdoc/core/configuration/SpringDocConfiguration$WebConversionServiceConfiguration.class], could not be registered. A bean with that name has already been defined in class path resource [org/springdoc/core/SpringDocConfiguration$WebConversionServiceConfiguration.class] and overriding is disabled.

Action:

Consider renaming one of the beans or enabling overriding by setting spring.main.allow-bean-definition-overriding=true
```

**To Reproduce**
Include both dependancies openapi-starter-webmvc-ui:2.0.0-RC1, openapi-security:1.6.12 in a Gradle project using Spring3, OpenApi3. Then start up the application

- What version of spring-boot you are using?
	- 3.0.0-M4 
- What modules and versions of springdoc-openapi are you using? 
	- openapi-starter-webmvc-ui:2.0.0-RC1
	- openapi-security:1.6.12
- What is the actual and the expected result using OpenAPI Description (yml or json)? 
	- JSON
- Provide with a sample code (HelloController) or Test that reproduces the problem

**Expected behavior**
- A clear and concise description of what you expected to happen.
	- Application starts up and shows Swagger UI which also contains default OAuth Endpoints
- What is the expected result using OpenAPI Description (yml or json)?
	- JSON

**Additional context**
My project is based on OAuth Server 1.0. And I am trying to show the OAuth Endpoints. As mentioned in this section https://springdoc.org/#spring-security-support, in order to do that I have to include openapi-security.

**Comment by aijaz2** [comment]
After setting spring.main.allow-bean-definition-overriding to true. Another error is presented.
```
Parameter 0 of method swaggerUiConfigParameters in org.springdoc.webmvc.ui.SwaggerConfig required a bean of type 'org.springdoc.core.properties.SwaggerUiConfigProperties' that could not be found.


Action:

Consider defining a bean of type 'org.springdoc.core.properties.SwaggerUiConfigProperties' in your configuration.
``` 

Which is some what similar to issue https://github.com/springdoc/springdoc-openapi/issues/1209

**Comment by aijaz2** [comment]
I tried excluding one of the Classes by doing 
```
@ComponentScan(basePackages = {"org.springdoc.core"}, excludeFilters={
        @ComponentScan.Filter(type= FilterType.ASSIGNABLE_TYPE, value=SpringDocConfiguration.class)})
```
but was presented with this error
```
org.springframework.context.annotation.ConflictingBeanDefinitionException: Annotation-specified bean name 'springDocConfigProperties' for bean class [org.springdoc.core.properties.SpringDocConfigProperties] conflicts with existing, non-compatible bean definition of same name and class [org.springdoc.core.SpringDocConfigProperties]
```

So I tried to remove it from `org.springdoc.core.properties` and set `spring.main.allow-bean-definition-overriding=true` and was presented with this
```
Parameter 0 of method swaggerUiConfigParameters in org.springdoc.webmvc.ui.SwaggerConfig required a bean of type 'org.springdoc.core.properties.SwaggerUiConfigProperties' that could not be found.


Action:

Consider defining a bean of type 'org.springdoc.core.properties.SwaggerUiConfigProperties' in your configuration.
```
Which is somewhat similar to this issue https://github.com/springdoc/springdoc-openapi/issues/1209

**Comment by bnasslahsen** [comment]
@aijaz2,

Provide a [Minimal, Reproducible Example - with HelloController](https://stackoverflow.com/help/minimal-reproducible-example) that reproduces the problem
