### ISSUE TITLE
How to include OAuth2 endpoints to swagger-ui?

### ISSUE THREAD

**Issue by aijaz2** [springdoc/springdoc-openapi#1915]
Currently, the Swagger UI is setup and its missing endpoints such as `/oauth2/authorise` and `/oauth2/token` in the UI. 
As these endpoints are not part of any controller they are not being shown in the list.

I am using:
Spring Boot: 3.0.0-M4
Spring OAuth Server 1.0
springdoc-openapi-starter-webmvc-ui:2.0.0-RC1

**Comment by bnasslahsen** [comment]
`Spring OAuth Server 1.0` is not supported

**Comment by sskjames** [comment]
Hi @bnasslahsen, what version of [Spring Authorization Server](https://github.com/spring-projects/spring-authorization-server) is supported?
I'm using Spring Authorization Server 0.4.0 and Spring Boot 2.7.x, but the oauth2 endpoints are not listed.
