### ISSUE TITLE
provide fqn for schemas in addition to its name for customisers even if springdoc.use-fqn=false

### ISSUE THREAD

**Issue by tschniewind** [springdoc/springdoc-openapi#1916]
**problem:**
We are using the GlobalOpenApiCustomizer to enrich schemas for our dtos with information taken from an annotation of the dto classes (forEach OpenAPI.getComponents().getSchemas()).
Since the GlobalOpenApiCustomizer provides only the schema name, which is in our case the class' simple name (springdoc.use-fqn=false),  it is a nightmare to get the class of the underlying dto, cause it's simple name is not unique in our context.
If we would set springdoc.use-fqn=true everything would be fine, but we do not want to have the fully qualified name in the swagger-ui.

**solution:**
So it would be very helpfull, if the fully qualified name (fqn) would be passed to the GlobalOpenApiCoustomizer in addition to the simple name (Schema.getName()).
Probably it ist not possible since the Schema class is not under spring's control.

**alternate solutions:**
Alternatively create a new Customizer to provide the assocation from schema-name to fqn, may be simply as a Map.
Alternatively provide this Mappings within the OpenAPIService so that it can be taken via OpenApiBuilerCustomiser.

**context:**
currently we use spring-boot 2.6.13 and will upgrade to 2.7.x soon.

**Comment by bnasslahsen** [comment]
@tschniewind,

There are no plans for such a support
