### ISSUE TITLE
Consider add Spring Boot 3.0.0 support

### ISSUE THREAD

**Issue by marichka-spin** [springdoc/springdoc-openapi#1918]
I'd like to migrate our project to java 17. But it will require upgrade of spring-data-neo4j and spring boot itself. I've tried Spring boot  3.0.0-SNAPSHOT but it seems the Springdoc autonconfigure will not be compatible with new spring boot anymore.

**Comment by lfvjimisola** [comment]
See here: https://github.com/springdoc/springdoc-openapi/issues/1284#issuecomment-1023445755

**Comment by marichka-spin** [comment]
Thank you!
