### ISSUE TITLE
Add Ability to Configure Swagger UI

### ISSUE THREAD

**Issue by aoudiamoncef** [springdoc/springdoc-openapi#192]
I can configure Swagger UI via URL query params, but would be nice if I could configure some params in application.properties file, like the docExpansion param for example.

swagger official doc: https://swagger.io/docs/open-source-tools/swagger-ui/usage/configuration/

Thanks you :)

**Comment by springdoc** [comment]
Hi, 

The support of the swagger official properties will be available on v1.2.13 of springdoc-openapi release.
 You can use the same swagger properties in the documentation as spring-boot properties.
 All these properties should be declared with the following prefix: `springdoc.swagger-ui`

**Comment by aoudiamoncef** [comment]
Wow, great job 🎉👌
