### ISSUE TITLE
swagger-ui redirection not working

### ISSUE THREAD

**Issue by superfive666** [springdoc/springdoc-openapi#1925]
**Describe the bug**
I am not sure if this is a bug or missing any configuration on my end.
I am running on springboot version `2.7.5`
springdoc-openapi-ui version `1.6.12`

springdoc configuration:
```yaml
springdoc:
  api-docs: 
     path: /api/swagger/api-docs
  swagger-ui: 
     path: /api/swagger/swagger-ui.html
```

When i open: http://localhost:8080/api/swagger/swagger-ui.html, it throws 404 not found.
When i directly open webjar resources: http://localhost:8080/api/swagger/swagger-ui/4.14.3/index.html, it works.

What could I be possibly missing in my configuration?
I don't think I should be creating a redirection controller on my end to hard code the version of the swagger ui right?

**Expected behavior**
http://localhost:8080/api/swagger/swagger-ui.html redirects automatically to http://localhost:8080/api/swagger/swagger-ui/4.14.3/index.html.

**Screenshots**
<img width="1019" alt="image" src="https://user-images.githubusercontent.com/7760702/199869301-c6df598e-3159-4f03-8f36-2b119474a033.png">
<img width="835" alt="image" src="https://user-images.githubusercontent.com/7760702/199869619-9d471ead-810b-4e62-813f-6e14c5cf0ea0.png">

**Comment by bnasslahsen** [comment]
@superfive666,

Review you configuration.
You have many demos here: https://github.com/springdoc/springdoc-openapi-demos

**Comment by AlexanderBartash** [comment]
Just in case someone runs into it, there is a property `springdoc.swagger-ui.version` and `org.springdoc.ui.AbstractSwaggerResourceResolver`
```
    @Nullable
    protected String findWebJarResourcePath(String path) {
        String webjar = this.webjar(path);
        if (webjar.length() > 0) {
            String version = this.swaggerUiConfigProperties.getVersion();
            if (version != null) {
                String partialPath = this.path(webjar, path);
                return webjar + File.separator + version + File.separator + partialPath;
            }
        }

        return null;
    }
```

Which adds the version to the URL so that the resources can be resolved by an URL without the version.

The solution is to set the property to the correct version.
The version can be also seen in the swagger-ui jar `/swagger-ui-5.18.3.jar!/META-INF/resources/webjars/swagger-ui/5.18.3/index.html`
