### ISSUE TITLE
all query parameter's type is string

### ISSUE THREAD

**Issue by wulcy** [springdoc/springdoc-openapi#1926]
**Describe the bug**
all query paramter's type is string.

**To Reproduce**
- What version of spring-boot you are using?
- 2.6.12
- What modules and versions of springdoc-openapi are you using?
- 1.6.12
- What is the actual and the expected result using OpenAPI Description (yml or json)?
- json
- Provide with a sample code (HelloController) or Test that reproduces the problem
```
@RestController
@RequestMapping("/api")
public class OpenApiController {

    @GetMapping("/test")
    public void test(@ParameterObject QueryParams params) {
    }

}

@Data
public class QueryParams {

    @Schema(title = "intParam")
    private Integer intParam;

}
```

**Expected behavior**
- A clear and concise description of what you expected to happen.
- intParam's type should be integer
- What is the expected result using OpenAPI Description (yml or json)?
- json

**Screenshots**
<img width="435" alt="图片" src="https://user-images.githubusercontent.com/5967029/199952191-2c6b5ff9-06b6-4b5b-a567-74dd83680f8c.png">

**Additional context**

**Comment by bnasslahsen** [comment]
use 	`@Parameter(description = "intParam")`
Or in your `@Schema `add the `type` definition.

**Comment by mmotter** [comment]
@bnasslahsen In springdoc-openapi 1.6.9 we didn't have to specifically call out the schema type. Version 1.6.10 it appears we now have to define the type definition in only our QueryParam models. Seems kind of redundant to declare a field with a type other than string and then have to use the Schema annotation to again repeat the same type. I was always under the impression that defining the schema type definition was meant to be as an override option.
