### ISSUE TITLE
I'm getting status=404 with the Spring Boot 3.0.0-SNAPSHOT

### ISSUE THREAD

**Issue by eriksaleksans** [springdoc/springdoc-openapi#1928]
- The sample project 

`
@SpringBootApplication
public class SpringdocOpenapiUiTestApplication {

    public static void main(String[] args) {
        SpringApplication.run(SpringdocOpenapiUiTestApplication.class, args);
    }

    @RestController
    public class Hello {

        @GetMapping("/")
        @RequestMapping(value = "/", method = RequestMethod.GET, produces = MediaType.TEXT_PLAIN_VALUE)
        public String hello() {
            return "Hello";
        }
    }

}
`

- I get the Swagger UI at http://localhost:8080/swagger-ui/index.html with SpringBoot 2.7.5
- I get the Whitelabel Error Page with SpringBoot 3.0.0-SNAPSHOT
- I guess the SpringBoot 3.0.0 is not officially supported yet?

**Comment by uc4w6c** [comment]
SpringBoot3 seems to be supported by springdoc-openapi v2.

https://springdoc.org/v2/
https://github.com/springdoc/springdoc-openapi/tree/2.x

add the library to the list of your project dependencies
```
   <dependency>
      <groupId>org.springdoc</groupId>
      <artifactId>springdoc-openapi-starter-webmvc-ui</artifactId>
      <version>2.0.0-RC1</version>
   </dependency>
```

**Comment by eriksaleksans** [comment]
Thanks, it helped. I replaced springdoc-openapi-ui with springdoc-openapi-starter-webmvc-ui and now I see the Swagge UI.
