### ISSUE TITLE
Testing for Swagger UI does not work

### ISSUE THREAD

**Issue by DavesRepository** [springdoc/springdoc-openapi#193]
How can I get springdoc-opeapi to work in a maven test? 

I am facing the same problem as: https://github.com/springdoc/springdoc-openapi/issues/99

I also posted this on stackoverflow: https://stackoverflow.com/questions/59068582/unittest-call-swagger-ui-html-results-in-a-404-for-springdoc-openapi

I have spend quite some time on this issue:
- downloaded the https://github.com/springdoc/springdoc-openapi demos
- tried different tutorials. and spend many hours

If you could help, I would be very grateful.

**Comment by springdoc** [comment]
Hi, 

 You can have a look, at the sample you are mentioning from baeldung: We have added it to the demaos, and we added a sample test (SwaggerUnitTest). Its passing on CI.
 - https://github.com/springdoc/springdoc-openapi-demos/tree/master/spring-boot-springdoc
 
 As mentionned in #99, you can also have a look at the tests:

- https://github.com/springdoc/springdoc-openapi/blob/master/springdoc-openapi-ui/src/test/java/test/org/springdoc/ui/app1/SpringDocApp1Test.java

 Don't forget to leave us a feedback.
