### ISSUE TITLE
support yaml file for group

### ISSUE THREAD

**Issue by EladShechter** [springdoc/springdoc-openapi#1932]
**Is your feature request related to a problem? Please describe.**
When I using groups, I can reach the JSON file of the group by "/api-docs/{group}".
But I can't reach the YAML file the same as  "/api-docs/{group}.yaml". When I try to do so, I get an error message:
No OpenAPI resource found for group: {group}.yaml

**Describe the solution you'd like**
I would like to have the same functionality in YAML as in JSON. That I can get the yaml file that is specified for the group.

**Describe alternatives you've considered**
I tried to use queries in the URL to filter the group, but it didn't work too.

**Additional context**
- Add any other context or screenshots about the feature request here.

**Comment by uc4w6c** [comment]
see #1600
You can reach by `/api-docs.yml/{group}`.

**Comment by Caerlochlann** [comment]
How can you access it via Swagger UI without manual changes?  
In other words, how can you add `.yaml` to the created group URL?
See also https://github.com/springdoc/springdoc-openapi/issues/3241
