### ISSUE TITLE
Support disable swagger-ui per group

### ISSUE THREAD

**Issue by EladShechter** [springdoc/springdoc-openapi#1933]
**Is your feature request related to a problem? Please describe.**
The configuration property "springdoc.swagger-ui.enabled" is related to all the swagger-ui, I can't control if I want that there will be a page for one group and for other group there won't be a swagger page, but only json/yaml file.

**Describe the solution you'd like**
I would like to have a page for public API, and for internal API I want a page that can be accessed only in dev environment, so I can disable it in prod environment.
I would like to have something like: "springdoc.swagger-ui.group[0].enabled" or to handle it in programmatically like:
```
return GroupedOpenApi.builder().enableSwaggerUI(true).build();
```

**Describe alternatives you've considered**
For now, I doing:
```
@Bean
public GroupedOpenApi uiApi() {
        if (Boolean.parseBoolean(enableInternalSwagger)) {
            return GroupedOpenApi.builder()
                    .group("internal")
                    .build();
        }

        return null;
    }
```

**Additional context**
- Add any other context or screenshots about the feature request here.

**Comment by bnasslahsen** [comment]
@EladShechter, 

There is no such a feature planned.
If you think its useful for the community, please feel free to propose a PR.
