### ISSUE TITLE
 java.lang.NoSuchMethodError: 'io.swagger.v3.oas.models.media.Schema io.swagger.v3.oas.models.media.Schema.addProperty(java.lang.String, io.swagger.v3.oas.models.media.Schema)'

### ISSUE THREAD

**Issue by AlexRITIAN** [springdoc/springdoc-openapi#1937]
**Describe the bug**
I'm facing this issue when I try to lunch springboot application.
```
 java.lang.NoSuchMethodError: 'io.swagger.v3.oas.models.media.Schema io.swagger.v3.oas.models.media.Schema.addProperty(java.lang.String, io.swagger.v3.oas.models.media.Schema)'
```
there may have a wrong method name in `org.springdoc.core.RequestBodyInfo`

you can see there want to call `Schema.addProperty` method, but I can't find **addProperty** in `io.swagger.v3.oas.models.media.Schema`, I find **addProperties**.

```java
	/**
	 * Add properties.
	 *
	 * @param paramName the param name
	 * @param schemaN the schema n
	 */
	public void addProperties(String paramName, Schema schemaN) {
		if (mergedSchema == null)
			mergedSchema = new ObjectSchema();
		mergedSchema.addProperty(paramName, schemaN);
	}
```

**To Reproduce**
- spring-boot version : 2.7.5
- springdoc-openapi-ui:1.6.12

**Comment by bnasslahsen** [comment]
@AlexRITIAN 

Review your project dependencies

**Comment by vlapra** [comment]
I have same problem. Sample application attached.
[sample.zip](https://github.com/springdoc/springdoc-openapi/files/10045206/sample.zip)
