### ISSUE TITLE
With Jackson v2.14, it produces unexpected "example": null field in OpenAPI JSON

### ISSUE THREAD

**Issue by KK11045** [springdoc/springdoc-openapi#1939]
**Describe the bug**
Title: With Jackson v2.14, it produces unexpected "example": null field in OpenAPI JSON

I am using springdoc-openapi-ui v1.6.12.
When I use springdoc with `com.fasterxml.jackson.core:jackson-databind:2.14.0`, it produces OpenAPI JSON with unexpected null field as below:

```json
"components": {
        "schemas": {
            "SampleRequest": {
                "type": "object",
                "example": null, // this example field should not be appeared
                "properties": {
                    "sampleProperty": {
                        "maxLength": 4,
                        "minLength": 0,
                        "pattern": "^[0-9]*$",
                        "type": "string",
                        "description": "sampleProperty",
                        "example": "0000"
                    }
                },
                "required": [
                    "sampleProperty"
                ]
            }
        }
    }
```

As a result, Swagger UI shows `null` on Example pane.
<img width="572" alt="image" src="https://user-images.githubusercontent.com/118341542/202140321-7ed1f820-cdc4-49cf-9965-a77c23c4174a.png">

The source code used to produce OpenAPI JSON looks like:

```java
@JsonTypeName("sample_request")
@Generated(value = "xxx", date = "2022-11-16T15:22:54.131083+09:00[Asia/Tokyo]")
public class SampleRequest {

  @JsonProperty("sampleProperty")
  private String sampleProperty;

  public SampleRequest sampleProperty(String sampleProperty) {
    this.sampleProperty = sampleProperty;
    return this;
  }

  /**
   * sampleProperty
   * @return sampleProperty
  */
  @NotNull  @Pattern(regexp = "^[0-9]*$") @Size(max = 4) 
  @Schema(name = "sampleProperty", example = "0000", description = "sampleProperty", required = true)
  public String getSampleProperty() {
    return sampleProperty;
  }

  public void setSampleProperty(String sampleProperty) {
    this.sampleProperty = sampleProperty;
  }

}
```

It does not happen with `com.fasterxml.jackson.core:jackson-databind:2.13.4`. Is this a bug or Am I messed up something?
Any comments are appreciated.

**To Reproduce**
springdoc-openapi-ui: 1.6.12
Spring Boot: 2.7.4
OpenAPI: 3.0.0

**Comment by bnasslahsen** [comment]
@KK11045, 

This is not a bug.
As long as you are changing the dependencies coming from the `springdoc-openapi ` modules, you might face this non tested generation issues...
