### ISSUE TITLE
Is there a gradle plugin available?

### ISSUE THREAD

**Issue by vaibhawj** [springdoc/springdoc-openapi#194]
I am having a nice experience with this library so far. I want the open api spec to get enriched by the integration test with some request/response examples. The maven plugin [springdoc-openapi-maven-plugin](https://github.com/springdoc/springdoc-openapi-maven-plugin) seems to be doing the same job. 

Is there a gradle plugin similar to springdoc-openapi-maven-plugin which can be helpful for my requirement? Or Do you have any suggestions for it?

**Comment by springdoc** [comment]
Hi, 

 There is no springdoc-gradle-plugin planned for short term.
 But you can contribute to migrate the springdoc-maven-plugin into gradle, which mainly relies on spring-boot-maven-plugin.
