### ISSUE TITLE
Oauth2 redirect URI is not 'https'

### ISSUE THREAD

**Issue by gmazak** [springdoc/springdoc-openapi#1941]
Hi,

I'm having the following security configuration describing Oauth2 implicit flow:

```java
@SecurityScheme(name = "security_auth", type = SecuritySchemeType.OAUTH2,
        flows = @OAuthFlows(implicit =
        @OAuthFlow(
                authorizationUrl = "https://accounts.google.com/o/oauth2/v2/auth",
                scopes = {@OAuthScope(name = "https://www.googleapis.com/auth/userinfo.email", description = "View your email address")}
                })))
@OpenAPIDefinition(
        info = @Info(title = "<snip>",
                version = "${build.version}",
                description = "<snip>"),
        servers = { @Server(url = "/") }
)
```

The application is deployed on Google Cloud Platform (Cloud Run) and accessible on `https://<baseURL>/swagger-ui/index.html`.

However, when i try to authorize, I get HTTP Error 400 redirect_uri_mismatch.
The request has the following redirect URL:

`redirect_uri=http://<baseURL>/swagger-ui/oauth2-redirect.html`

I cannot register an Oauth2 redirect URI with 'http://' prefix: GCP won't let me do so.

I'm not sure if it's a bug or it's intended to work this way. 

Please let me know if you need any further input to check it.

SpringDoc: **1.6.11**
Spring Boot: **2.7.5**

**Comment by bnasslahsen** [comment]
@gmazak,

Check you configuration here: `https://<baseURL>/v3/api-docs/swagger-config`
You should be able to see the redirectURL set by default using `springdoc-openapi`, by checking the variable `oauth2RedirectUrl`

if it's not correct, you should use this property `springdoc.swagger-ui.oauth2-redirect-url`
