### ISSUE TITLE
OperationCustomizer behavior on overloaded http methods 

### ISSUE THREAD

**Issue by JSimo** [springdoc/springdoc-openapi#1944]
**Describe the bug**
To get it out of the way; Unsure if it is a bug or an expected behavior. 

We are using the `OperationsCustomizer` to add an custom header to each swagger object. In certain cases we have overloaded http methods where the params decide what method is used in spring boot. Together with a naive `OperationsCustomizer` where we add a custom parameter (header) every time.

```java
   @Bean
    public OperationCustomizer customize() {
        return (operation, handlerMethod) -> {
            return operation.addParametersItem((new Parameter()).in("header").required(false).name("X-Custom-Header"));
        };
    }
```

As a result we get `java.lang.IllegalStateException: Duplicate key class Parameter` for the third method that is overloaded. Having two overloads is fine. [Example tests](https://github.com/JSimo/springdoc-openapi/pull/1/files).

**To Reproduce**
- What version of spring-boot you are using? 

Latest 2.7.x

- What modules and versions of springdoc-openapi are you using? 

springdoc-openapi-ui, springdoc-openapi-data-rest & springdoc-openapi-security

- What is the actual and the expected result using OpenAPI Description (yml or json)?

Actual: `java.lang.IllegalStateException: Duplicate key class Parameter`
Expected: No exception.

- Provide with a sample code (HelloController) or Test that reproduces the problem

See this sample MR in this fork: https://github.com/JSimo/springdoc-openapi/pull/1/files

**Expected behavior**
Either a) or b) 
a) That it is a bug, `OperationsCustomizer` should handle the de-duplication of the added parameter for the scenario of using more than two overloaded http endpoints.
b) That it is a feature, oneself is expected to handle de-duplication in  `OperationsCustomizer` for the scenario of using more than two overloaded http endpoints.

**Screenshots**
![image](https://user-images.githubusercontent.com/2879420/202445997-2040957b-7792-4775-a06a-693797e280db.png)

**Additional context**
n/a

**Comment by hyeonisism** [comment]
try to use `RouterOperationCustomizer` instead of `OperationCustomizer`

**Comment by JSimo** [comment]
> try to use `RouterOperationCustomizer` instead of `OperationCustomizer`

Tried using it with a similar naive variant, with a similar result.

```java
    @Bean
    public RouterOperationCustomizer customize() {
        return (operation, handlerMethod) -> {
            String[] headers = operation.getHeaders();
            operation.setHeaders(ArrayUtils.add(headers, XHEADER));
            return operation;
        };
    }
```

See MR on fork for test code with failing tests: https://github.com/JSimo/springdoc-openapi/pull/1/files

If I would guess, I would say we are either:
a) required to de-dupe ourselves no matter if using `OperationsCustomizer` or `RouterOperationCustomizer`. 
b) can expect a `OperationsCustomizer`/`RouterOperationCustomizer` to handle duplicate params.
c) can expect a `OperationsCustomizer`/`RouterOperationCustomizer` to only be called once for each overloaded http method.

Probably going to solve it at least short term with a) on our side, and depending on your response here some other way long term. 

Ps. Tried finding some documentation on these customerizers, but it is hard to find, do you happen to have some docs for them?

**Comment by bnasslahsen** [comment]
@JSimo,

If your `OperationsCustomizer` is adding duplicates. Then you need to handle this custom logic.
It wil be called for each method. And not only once for each overloaded http method.
