### ISSUE TITLE
Cannot invoke "java.lang.Class.getName()" because the return value of "java.lang.Class.getSuperclass()" is null

### ISSUE THREAD

**Issue by torsten-sauer** [springdoc/springdoc-openapi#1945]
With the integration of https://github.com/springdoc/springdoc-openapi/pull/1835 and the release of 1..6.12 there is a problem at the following line:

https://github.com/springdoc/springdoc-openapi/blob/499e42c981e4977b48b98c683adf60177a96ea8d/springdoc-openapi-common/src/main/java/org/springdoc/core/MethodParameterPojoExtractor.java#L179

Error: Cannot invoke "java.lang.Class.getName()" because the return value of "java.lang.Class.getSuperclass()" is null

Looks like there should be some guard that catches the situation when paramClass.getSuperclass() is null.

**Comment by uc4w6c** [comment]
Sorry.
I want to fix it, so could you tell me how to reproduce it?

**Comment by bnasslahsen** [comment]
fixed by #1922

**Comment by torsten-sauer** [comment]
Thx 🙏

Didn't see the other issue  🙈🙉🙊
