### ISSUE TITLE
Api docs disable feature not working in 1.6.12

### ISSUE THREAD

**Issue by theanupriyasharma** [springdoc/springdoc-openapi#1946]
**Describe the bug**
Per https://github.com/springdoc/springdoc-openapi/issues/358 , I expected the disabling of /api-docs url to be disabled since I am hosting my own swagger file at the UI however , the disable functionality is not working and it still shows auto generated swagger file on /v3/api-docs , I am trying to disable it however it does not seem to respond to my config changes. I have added an example below.

**To Reproduce**
- What version of spring-boot you are using? - 2.7.5
- What modules and versions of springdoc-openapi are you using? - 1.6.12
- What is the actual and the expected result using OpenAPI Description (yml or json)? - The url is still hosting the auto generated swagger

My spring config -> 

```
  @Override
  public void addViewControllers(ViewControllerRegistry registry) {
    registry.addViewController("/swagger-ui/").setViewName("forward:/swagger-ui/index.html");
    registry.addRedirectViewController("/swagger-ui", "/swagger-ui/");
    registry.addViewController("/api-docs").setViewName("forward:/v3/api-docs");
  }


  @Bean
  SpringDocConfigProperties springDocConfigProperties() {
    SpringDocConfigProperties docConfigProperties =  new SpringDocConfigProperties();
    docConfigProperties.getApiDocs().setEnabled(false);
    return docConfigProperties;
  }

}
```

My yaml config  -> 

```
springdoc:
  swagger-ui:
    url: /swagger.yaml
```

**Expected behavior**
- the disable api-docs feature is not working , it still shows an autogenerated swagger when I am providing one myself in resources static folder.

**Screenshots**
None

**Comment by bnasslahsen** [comment]
@theanupriyasharma, 

Tests are passing. If you feel, that you are facing a bug provide in you ticket a [Minimal, Reproducible Example - with HelloController](https://stackoverflow.com/help/minimal-reproducible-example) that reproduces the problem.

**Comment by bnasslahsen** [comment]
@ilya40umov;

Again; If you feel, that you are facing a bug provide in you ticket a [Minimal, Reproducible Example - with HelloController](https://stackoverflow.com/help/minimal-reproducible-example) that reproduces the problem.

**Comment by ilya40umov** [comment]
Well. I'm not entirely sure it's a bug yet. I suspect it might be just that the webjars loader is loading the Swagger UI. As far as I can tell the configs from springdoc-openapi aren't getting loaded. :shrug: 
Do you only accept bugs or you are also open to elaborate on this topic?

**Comment by bnasslahsen** [comment]
@ilya40umov,

Well good you found out that the `springdoc-openapi` configs are not loaded.
If you want to elaborate or propose some enhancement, please feel free to propose directly a PR.

**Comment by ilya40umov** [comment]
Alright. Makes sense. I'm for now just going to add a extra entry to our spring security config to conditionally (depending on environment) deny requests going to `/webjars/**`. If this ends up causing more issues / questions, I'll look into raising a PR. Thanks!
