### ISSUE TITLE
springdoc-openapi-starter-webmvc-ui 2.0.0-RC2 not working

### ISSUE THREAD

**Issue by fourcels** [springdoc/springdoc-openapi#1948]
**Describe the bug**

Caused by: java.io.FileNotFoundException: class path resource [org/springdoc/core/properties/SwaggerUiConfigProperties.class] cannot be opened because it does not exist

**To Reproduce**

- What version of spring-boot you are using?
3.0.0-RC2
- What modules and versions of springdoc-openapi are you using?
org.springdoc:springdoc-openapi-starter-webmvc-ui:2.0.0-RC2

**Comment by bnasslahsen** [comment]
@fourcels,

if you see [demos](https://springdoc.org/v2/#demos), you will find out its working just fine.
Remember, contributions to this repository should follow its [contributing guidelines](https://github.com/springdoc/springdoc-openapi/blob/3745c32cdd742cf3e7e1ddb3f393eef238d69ba0/CONTRIBUTING.adoc), [security policy](https://github.com/springdoc/springdoc-openapi/blob/3745c32cdd742cf3e7e1ddb3f393eef238d69ba0/SECURITY.md), and [code of conduct](https://github.com/springdoc/springdoc-openapi/blob/3745c32cdd742cf3e7e1ddb3f393eef238d69ba0/CODE_OF_CONDUCT.md).

Make sure you Provide a [Minimal, Reproducible Example - with HelloController](https://stackoverflow.com/help/minimal-reproducible-example) that reproduces the problem.
