### ISSUE TITLE
[Question] How to add a "description" to a chema in API response

### ISSUE THREAD

**Issue by ityuhui** [springdoc/springdoc-openapi#1951]
**Describe the bug**

Hi

Please see the following code :
```java
@Operation(
            responses = {
                  @ApiResponse(responseCode = "200", description= "Description for response")
            }
	)
public HashMap <String, String> getResourceInfo()
{
    ....
    HashMap <String, String> resp = new HashMap <String, String>();
    ...
    return resp;
}
```

The swagger spec generated by SpringDoc is

```yaml
      responses:
        "200":
          description: Description for response.
          content:
            application/json:
              schema:
                type: object
                additionalProperties:
                  type: string
```

Now I want to add a description to the schema. e.g.
```yaml
      responses:
        "200":
          description: Description for response.
          content:
            application/json:
              schema:
                type: object
                additionalProperties:
                  type: string
                description: Description for schema.  <== what I want
```

So I updated my code to
```java
responses = {
    @ApiResponse(responseCode = "200",  description= "Asset endpoint information.", 
                content = {
                    @Content(schema = @Schema(type="object", description="Description for schema."), 
                             additionalPropertiesSchema = @Schema(type = "string")
	            )
	        }
    )
}
```

But the latest spec generated by SpringDoc is:

```yaml
      responses:
        "200":
          description: Description for response.
          content:
            application/json:
              schema:
                additionalProperties: {}
                description: Description for schema.
```

What's wrong with me ?

**To Reproduce**

- What version of spring-boot you are using?
2.7.5
- What modules and versions of springdoc-openapi are you using?
org.springdoc
springdoc-openapi-webmvc-core
1.6.11

**Expected behavior**

Can add a "description" to a chema in API response

**Comment by bnasslahsen** [comment]
Remember, contributions to this repository should follow its [contributing guidelines](https://github.com/springdoc/springdoc-openapi/blob/3745c32cdd742cf3e7e1ddb3f393eef238d69ba0/CONTRIBUTING.adoc), [security policy](https://github.com/springdoc/springdoc-openapi/blob/3745c32cdd742cf3e7e1ddb3f393eef238d69ba0/SECURITY.md), and [code of conduct](https://github.com/springdoc/springdoc-openapi/blob/3745c32cdd742cf3e7e1ddb3f393eef238d69ba0/CODE_OF_CONDUCT.md).

For swagger2-annotations:
- https://github.com/swagger-api/swagger-core/wiki/Swagger-2.X---Annotations
