### ISSUE TITLE
Support For extra documentation, example, html templates

### ISSUE THREAD

**Issue by mehaksaini2811** [springdoc/springdoc-openapi#1955]
Hi Team,

I have a peculiar requirement and I'm not sure whether it is being currently catered by the library or not.
I have a springboot application for which I created the swagger manually and it contains a lot of documentation, for e.g., a table containing comparison of difference api endpoints, an extensive explanation of one of the api endpoints with some stress on few keywords(using html <b>) and it was all achieved by embedding html in yaml file. 
Now, we are working on generating all this documentation from code rather than manually maintaining the swagger.yaml file. We are able to achieve all the basics, however for embedding html, we had to hardcode the html in our Constants.java file(which doesn't look very pretty) and then use those constants in api description. 
Is any cleaner way of doing it, any template or anything in which we don't have to hardcode html in Constants. Any help would be appreciated.

**Comment by bnasslahsen** [comment]
see [how can i generate pdf/html swagger doc by /v3/api-doc path ](https://github.com/springdoc/springdoc-openapi/issues/811)

**Comment by mehaksaini2811** [comment]
Hi @bnasslahsen , I think I wasn't clear in my question earlier. Is there any html template support in springdoc-open-api ? I wish to add some extra documentation, for example, comparison tables in the description attribute. One way is to save the html as a Constant in a Java file but that is too cumbersome, so I was looking out for any support  whatsoever.
