### ISSUE TITLE
Kotlin module for v2?

### ISSUE THREAD

**Issue by bkielczewski** [springdoc/springdoc-openapi#1956]
In v2.0.0 there seems to be no Kotlin module, yet the [doc](https://springdoc.org/v2/) mentions otherwise. Latest on Maven Central is 1.6.13.

**Comment by bnasslahsen** [comment]
@bkielczewski,

Please Read: https://springdoc.org/v2/#migrating-from-springdoc-v1
Or https://springdoc.org/v2/#kotlin-support

**Comment by bkielczewski** [comment]
Ok, thanks, but https://springdoc.org/v2/#kotlin-support bit is confusing.

This bit exactly (my use case):

If you are using spring-webflux, you should combine the springdoc-openapi-kotlin module with springdoc-openapi-starter-webflux-ui.

**Comment by bkielczewski** [comment]
Also, springdoc-openapi-starter-common seems to be a dependency of springdoc-openapi-starter-webflux-ui, so that should be ok for Kotlin support. However, when I'm using suspend function on rest endpoint I get documentation for $completion parameter there. Should I file a bug report for regression (wasn't like that in v1)?
