### ISSUE TITLE
Replace org.springframework.core.LocalVariableTableParameterNameDiscoverer which was deprecated with org.springframework.core.DefaultParameterNameDiscoverer

### ISSUE THREAD

**Issue by krupt** [springdoc/springdoc-openapi#1958]
Started from Spring Framework 6.0.1 org.springframework.core.LocalVariableTableParameterNameDiscoverer became deprecated and spring doc uses it. In logs we have a lot of warnings:
`2022-11-26 10:30:45.675  WARN --- [  XNIO-1 task-5] ocalVariableTableParameterNameDiscoverer : Using deprecated '-debug' fallback for parameter name resolution. Compile the affected code with '-parameters' instead or avoid its introspection: controller.UserController `

Spring Boot 3 uses org.springframework.core.DefaultParameterNameDiscoverer and has no problem with it.
I don't mind to fix it if you'd provide guideline how to do it in your project.
Thanks.

**Comment by bnasslahsen** [comment]
@krupt,

Feel free to propose a PR. 
This is the contribution guide: https://github.com/springdoc/springdoc-openapi/blob/master/CONTRIBUTING.adoc

**Comment by krupt** [comment]
Created PR [1959](https://github.com/springdoc/springdoc-openapi/pull/1959)

**Comment by bnasslahsen** [comment]
https://github.com/springdoc/springdoc-openapi/pull/1959 merged
