### ISSUE TITLE
Is there a way to Hide endpoints from getting listed in springdoc-openapi-ui?

### ISSUE THREAD

**Issue by Sachpat** [springdoc/springdoc-openapi#196]
Hi I want to hide some of my endpoints from getting listed in the springdoc-openapi-ui, is there a way of doing that? something like @Api(hidden = true) from springfox?

**Comment by springdoc** [comment]
Hi, 

 We rely on swagger-annotations official jars. 
 You can use: : `@Hidden`
 For other annotations, you can use the documentation of swagger-annotations for OpenAPI 3.
 - https://github.com/swagger-api/swagger-core/wiki/Swagger-2.X---Annotations

**Comment by Sachpat** [comment]
@springdoc thanks that works, is there a way to hide schemas also?

**Comment by springdoc** [comment]
You can use: `@Parameter(schema = @Schema(hidden = true))`

You can hide the response element, using @Schema annotation, as follows, at operational level::

`@Operation(responses = @ApiResponse(responseCode = "200", content = @Content(schema = @Schema(hidden = true))))`

Or directly at ApiResponses level:

`@ApiResponses(value = {@ApiResponse(responseCode = "200", content = @Content(schema = @Schema(hidden = true))) })`

If you have more questions,please provide the sample java code, with the expected OpenAPI (json/yml) description of the behaviour you are expecting.

**Comment by akalandiaelsewhen** [comment]
is there a way to conditionally hide an endpoint?
