### ISSUE TITLE
Provide Spring Boot 3 support

### ISSUE THREAD

**Issue by frecco75** [springdoc/springdoc-openapi#1960]
Hello,

Spring Boot 3 has been released and springdoc autoconfiguration is not read anymore.
See the dedicated point of the [Spring Boot 3 migration guide](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-3.0-Migration-Guide#auto-configuration-files).

Since Spring Boot 2.7 autoconfigure registration via `spring.factories` is not recommended, it should be migrated to `META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports`.

[Example from Spring Boot source code](https://github.com/spring-projects/spring-boot/blob/main/spring-boot-project/spring-boot-autoconfigure/src/main/resources/META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports).

Thanks !

**Comment by bnasslahsen** [comment]
@frecco75,

This change will break spring-boot 1 support.
If you  want Use spring-boot 3, make sure you Use springdoc-openapi v2 which already supports this enhancement request.
