### ISSUE TITLE
ContinuationObject leaks into schema

### ISSUE THREAD

**Issue by orange-buffalo** [springdoc/springdoc-openapi#1961]
**Describe the bug**

When using `springdoc-openapi` in a project with Spring Boot 3 + WebFlux + Kotlin Coroutines, the generated schema has `ContinuationObject` parameters. 

**To Reproduce**
* Spring Boot: 3.0.0
* springdoc-openapi: 2.0.0
* springdoc-openapi modules: `springdoc-openapi-starter-common` and `springdoc-openapi-starter-webflux-api`, also reproducible with `springdoc-openapi-starter-webflux-ui` alone.
* Sample project: https://github.com/orange-buffalo/reproducer-springdoc-openapi-kotlin. `SchemaTest.kt` is the test reproducing the problem.

**Expected result**

Same behaviour as on 1.x - no coroutines internals leaking into schema.

**Actual result**
 Schema gets extra parameters:
 ```yaml
 - name: $completion
    in: query
    required: false
    schema:
      $ref: '#/components/schemas/ContinuationObject'
 ```
 And extra types:
 ```yaml
   ContinuationObject:
      type: object
      properties:
        context:
          $ref: '#/components/schemas/CoroutineContext'
    CoroutineContext:
      type: object
 ```

**Comment by bnasslahsen** [comment]
@orange-buffalo,

Thank you for the report. This will be fixed for the next release.
This is a workaround for now:

```java
@ImportAutoConfiguration(
	SpringDocKotlinxConfiguration::class,
	SpringDocKotlinConfiguration::class
)
```

**Comment by orange-buffalo** [comment]
Thanks for the fast resolution! I confirm that workaround works for my use case.
