### ISSUE TITLE
Spring boot V3.0.0 support

### ISSUE THREAD

**Issue by its-Saab** [springdoc/springdoc-openapi#1964]
Everything was running fine with Spring boot V2.7.5.  However, once I upgraded to Spring boot V3.0.0. I can no longer view any docs under the usual paths (`http://server:port/context-path/swagger-ui.html`, `http://server:port/context-path/v3/api-docs`) and instead im getting a white label 404.

- What version of spring-boot you are using?
- V3.0.0
- What modules and versions of springdoc-openapi are you using?
- V1.6.13

Notes:
setting the property `log.level.web=trace` shows the following when calling the previously mentioned endpoints:

`TRACE | http-nio-8081-exec-1 | o.s.web.servlet.DispatcherServlet | GET "/v3/api-docs", parameters={}, headers={masked} in DispatcherServlet 'dispatcherServlet'
TRACE | http-nio-8081-exec-1 | o.s.w.s.h.SimpleUrlHandlerMapping | Mapped to HandlerExecutionChain with [ResourceHttpRequestHandler [classpath [META-INF/resources/], classpath [resources/], classpath [static/], classpath [public/], ServletContext [/]]] and 3 interceptors
DEBUG | http-nio-8081-exec-1 | o.s.w.s.r.ResourceHttpRequestHandler | Resource not found
TRACE | http-nio-8081-exec-1 | o.s.web.servlet.DispatcherServlet | No view rendering, null ModelAndView returned.
DEBUG | http-nio-8081-exec-1 | o.s.web.servlet.DispatcherServlet | Completed 404 NOT_FOUND, headers={masked}`

`TRACE | http-nio-8081-exec-3 | o.s.web.servlet.DispatcherServlet | GET "/swagger-ui.html", parameters={}, headers={masked} in DispatcherServlet 'dispatcherServlet'
TRACE | http-nio-8081-exec-3 | o.s.w.s.h.SimpleUrlHandlerMapping | Mapped to HandlerExecutionChain with [ResourceHttpRequestHandler [classpath [META-INF/resources/], classpath [resources/], classpath [static/], classpath [public/], ServletContext [/]]] and 3 interceptors
DEBUG | http-nio-8081-exec-3 | o.s.w.s.r.ResourceHttpRequestHandler | Resource not found
TRACE | http-nio-8081-exec-3 | o.s.web.servlet.DispatcherServlet | No view rendering, null ModelAndView returned.
DEBUG | http-nio-8081-exec-3 | o.s.web.servlet.DispatcherServlet | Completed 404 NOT_FOUND, headers={masked}`

**Comment by TomBeckett** [comment]
FYI I've reverted back to `2.0.0-M7`. This version seems stable with Spring Boot 3.

**Comment by bnasslahsen** [comment]
@its-Saab,
You are using wrong version. Please read the documentation before opening issues:
<img width="1005" alt="image" src="https://user-images.githubusercontent.com/13404829/204239551-62198b89-338e-4f5f-b6f8-ff1cfa668b29.png">

@DManhHieu 
> I saw v2(https://github.com/springdoc/springdoc-openapi/releases/tag/v2.0.0) support Spring boot v3.0.0 but not find dependencies on maven repository
You do not seem that you have searched:
- https://mvnrepository.com/artifact/org.springdoc/springdoc-openapi-starter-webmvc-api/2.0.0


@TomBeckett,
See documentation:
- https://springdoc.org/v2/

**Comment by TomBeckett** [comment]
@bnasslahsen Any hints on what I've missed?

**Comment by bnasslahsen** [comment]
@TomBeckett,

Your error is certainly, that you are using wrong dependencies. 
Please read the documentation how to get started.

Note: You should only reference springdoc-openapi dependencies. All the swagger dependencies should come fron springdoc-openapi.

In addition, you have many demos how to setup projects here: https://github.com/springdoc/springdoc-openapi-demos/tree/2.x

And if you are still unable to make it work, make sure you Provide a [Minimal, Reproducible Example - with HelloController](https://stackoverflow.com/help/minimal-reproducible-example) that reproduces the problem, and would be happy to help.

**Comment by DManhHieu** [comment]
Thank you! I change springdoc-openapi-ui to springdoc-openapi-starter-webmvc-ui and springdoc-openapi-common to springdoc-openapi-starter-common. And with some code changes it works fine.

**Comment by bnasslahsen** [comment]
@DManhHieu,

You only need `springdoc-openapi-starter-webmvc-ui`.
`springdoc-openapi-common` is transitively coming from `springdoc-openapi-starter-webmvc-ui`..
