### ISSUE TITLE
 GroupedOpenApi path filters don't work

### ISSUE THREAD

**Issue by tb-lbi** [springdoc/springdoc-openapi#1966]
The FAQ explains how to create an API group at https://springdoc.org/faq.html
However, the `pathsToMatch` function on the `GroupedOpenApi` appears to have no effect: if you create a new API group, it will always return every endpoint in the project. The desired behavior is for the /v3/api-docs/groupname endpoint (and the springdoc ui page for that group) to only include endpoints with paths matching at least one of the arguments to the `pathsToMatch` function.

**Comment by bnasslahsen** [comment]
Provide a [Minimal, Reproducible Example - with HelloController](https://stackoverflow.com/help/minimal-reproducible-example) that reproduces the problem
