### ISSUE TITLE
GroupedOpenApi path filters don't work

### ISSUE THREAD

**Issue by tb-lbi** [springdoc/springdoc-openapi#1967]
Description:
The FAQ explains how to create an API group at https://springdoc.org/faq.html
However, the pathsToMatch function on the GroupedOpenApi appears to have no effect: if you create a new API group, it will always return every endpoint in the project. The desired behavior is for the /v3/api-docs/groupname endpoint (and the springdoc ui page for that group) to only include endpoints with paths matching at least one of the arguments to the pathsToMatch function.

Code Example:

HelloController.java:
```
@RestController
@RequestMapping("/hello")
public class HelloController {
  @GetMapping("/a")
  public void a() {}

  @GetMapping("/b")
  public void b() {}
}
```
DocConfig.java:
```
@Configuration
public class DocConfig {
  @Bean
  public OpenAPI docs() {
    return new OpenAPI()
        .info(new Info()
            .title("Example")
            .description("Example"));

  @Bean
  public GroupedOpenApi groupA() {
    return GroupedOpenApi.builder().group("a").pathsToMatch("/hello/a").build();
  }

  @Bean
  public GroupedOpenApi groupB() {
    return GroupedOpenApi.builder().group("b").pathsToMatch("/hello/b").build();
  }
}
```
`/v3/api-docs/a` and `/v3/api-docs/b` give the same response, which contains both endpoints `/hello/a` and `/hello/b`

Environment :
Springdoc OpenApi 1.6.11
Spring Boot 2.7.3
Java 8

**Comment by bnasslahsen** [comment]
@tb-lbi,

Not reproducible.
Add the link to your repo with the unit tests not working.
