### ISSUE TITLE
springdoc 2.0 startup warning

### ISSUE THREAD

**Issue by yuyihan666** [springdoc/springdoc-openapi#1968]
WARN  [nio-8080-exec-9]  .s.core.LocalVariableTableParameterNameDiscoverer  : Using deprecated '-debug' fallback for parameter name resolution. Compile the affected code with '-parameters' instead or avoid its introspection:

**Comment by ctmay4** [comment]
I am having the same issue. I tried to add `-parameters` to the Maven compiler plugin but I still get the warning. Did you fix it?

**Comment by ctmay4** [comment]
Never mind. I see a PR was already merged to fix this. Also, I just suppressed warnings from `LocalVariableTableParameterNameDiscoverer`.
