### ISSUE TITLE
Set a default `client_id`

### ISSUE THREAD

**Issue by Decat-SimonA** [springdoc/springdoc-openapi#197]
Is there a way to set a default `client_id` in the "Authorize" popup ?

**Comment by springdoc** [comment]
The client_id configuration is not handled by springdoc-openapi.
We rely on swagger-ui official webjars.

There is programmatic way to set the value of client_id, but you need custom developments before the swagger-ui is called:
- https://swagger.io/docs/open-source-tools/swagger-ui/usage/configuration/

If you need a way to set a default value of the client_in on the swagger-ui, please raise it on swagger-ui github:
- https://github.com/swagger-api/swagger-ui/issues
