### ISSUE TITLE
Using an enum property on a @ParameterObject class

### ISSUE THREAD

**Issue by MoFarah9** [springdoc/springdoc-openapi#1970]
How can I use a parameter object (to hold multiple query parameters) with an enum property on the class and get that enum on the resulting API doc, consider the following sample code:

```java
// On a controller
@GetMapping(value = "/products")
public List<ItemDto> getProducts(@Valid @ParameterObject ProductFilter filter) {

    // ... method implementation

}
```

```java
public class ProductFilter {
  
  @Schema(required = true, description = "...")
  @NotEmpty
  List<ProductType> types;

  // ... Other filter attributes
}

public enum ProductType {
  TYPE_A, TYPE_B, TYPE_C, TYPE_D
}
```

I expected to get an enum in the parameter definition, like this

```
{
  "name": "types",
  "in": "query",
  "required": true,
  "schema": {
    "type": "array",
    "items": {
      "$ref": "#/components/schemas/MembershipReportColumn"
    }
  }
}
```
But instead instead of getting an array with enum definition, I get a single string.

```
{
  "name": "types",
  "in": "query",
  "required": true,
  "schema": {
    "type": "string",
  }
}
```

I tried adding `enumAsRef = true` to the enum itself and to the property on the class, but got the same results.
I understand that I can use `allowedValues`, but then I will have to list the enum values as constant.
Also, I noticed that enums are being recognized when listed directly on the controller methods parameters with @RequestParam.

Spring boot 2.7.5
springdoc 1.6.11

**Comment by bnasslahsen** [comment]
@MoFarah9,

You schema declaration is incomplete.
You should either use:

```java
@Parameter(required = true, description = "...")
```

Or

```java
@ArraySchema(schema = @Schema(description = "toto"))
```
