### ISSUE TITLE
GroupedOpenApi filters are ignored when pathsToMatch is configured globally

### ISSUE THREAD

**Issue by tb-lbi** [springdoc/springdoc-openapi#1972]
There is an `isPathToMatch` function defined in [springdoc-openapi-common/src/main/java/org/springdoc/api/AbstractOpenApiResource.java](https://github.com/springdoc/springdoc-openapi/blob/master/springdoc-openapi-common/src/main/java/org/springdoc/api/AbstractOpenApiResource.java):
```
	protected boolean isPathToMatch(String operationPath) {
		List<String> pathsToMatch = springDocConfigProperties.getPathsToMatch();
		List<String> pathsToExclude = springDocConfigProperties.getPathsToExclude();
		if (CollectionUtils.isEmpty(pathsToMatch)) {
			Optional<GroupConfig> optionalGroupConfig = springDocConfigProperties.getGroupConfigs().stream().filter(groupConfig -> this.groupName.equals(groupConfig.getGroup())).findAny();
			if (optionalGroupConfig.isPresent())
				pathsToMatch = optionalGroupConfig.get().getPathsToMatch();
		}
		if (CollectionUtils.isEmpty(pathsToExclude)) {
			Optional<GroupConfig> optionalGroupConfig = springDocConfigProperties.getGroupConfigs().stream().filter(groupConfig -> this.groupName.equals(groupConfig.getGroup())).findAny();
			if (optionalGroupConfig.isPresent())
				pathsToExclude = optionalGroupConfig.get().getPathsToExclude();
		}
		boolean include = CollectionUtils.isEmpty(pathsToMatch) || pathsToMatch.stream().anyMatch(pattern -> antPathMatcher.match(pattern, operationPath));
		boolean exclude = !CollectionUtils.isEmpty(pathsToExclude) && pathsToExclude.stream().anyMatch(pattern -> antPathMatcher.match(pattern, operationPath));
		return include && !exclude;
	}
```
If pathsToMatch is configured globally (i.e. by writing `springdoc.pathsToMatch=...` in application.properties), then any `pathsToMatch`  configured in GroupedOpenApi (see this FAQ: [https://springdoc.org/faq.html](https://springdoc.org/faq.html)) are ignored due to the two `if (CollectionUtils.isEmpty(...))` statements. One would expect the filters in GroupedOpenApi to take precedence, or for the global filter to be combined with the GroupedOpenApi filters. If not, then at the bare minimum the FAQ should document the fact that api groups won't actually filter any endpoints if there are global `pathsToMatch` / `pathsToExclude` settings.

**Comment by bnasslahsen** [comment]
@tb-lbi,

Do not create duplicates. #1967
Answer the original ticket and provide the required information.
