### ISSUE TITLE
Support Spring 6 / Spring Boot 3

### ISSUE THREAD

**Issue by tmohme** [springdoc/springdoc-openapi#1973]
**Is your feature request related to a problem? Please describe.**

We recently upgraded our application to Spring 6 / Spring Boot 3.  
Unfortunately the integration with springdoc stopped working after the upgrade.  
It looks like springdoc 1.6.13 doesn't get picked-up at all by Spring 6 / Spring Boot 3.

**Describe the solution you'd like**

I'd love to see springdoc integrate with Spring 6 / Spring Boot 3 the same way it does with Spring 5 / Spring Boot 2.7. 

**Describe alternatives you've considered**

We are forced to either revert to Spring 5 / Spring Boot 2.7 or stop using Swagger-UI for internal development purpose.
Here some kind of roadmap / announcement when Spring 6 / Spring Boot 3 support will be available would be helpful to guide our decision.

**Additional context**

./.

**Comment by guillaume-1** [comment]
Hi, same problem with our app after Springboot 3.0.0 migration . We have a HTTP 500 error when we call http://localhost:8080/swagger-ui.html  with message : {"message":"404 NOT_FOUND","status":500}
Some help will be appreciated, thanks !

**Comment by bnasslahsen** [comment]
See documentation:
- https://springdoc.org/v2/
