### ISSUE TITLE
2.0.0 not uploaded to Maven Central

### ISSUE THREAD

**Issue by phillipuniverse** [springdoc/springdoc-openapi#1974]
**Describe the bug**

Looking [in Maven central](https://mvnrepository.com/artifact/org.springdoc/springdoc-openapi-ui), I only see up to 1.6.x versions.

**To Reproduce**

1. Target version 2.0.0 of any springdoc-openapi dependencies in `build.gradle`
    ```
    ext {
	springDocVersion = '2.0.0'
    }

    dependencies {
	implementation group: 'org.springdoc', name: 'springdoc-openapi-ui', version: "$springDocVersion"
	implementation group: 'org.springdoc', name: 'springdoc-openapi-webmvc-core', version: "$springDocVersion"
     }
    ```
3. Try to build

```
> Task :compileJava FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileJava'.
> Could not resolve all files for configuration ':compileClasspath'.
   > Could not find org.springdoc:springdoc-openapi-ui:2.0.0.
     Required by:
         project :
   > Could not find org.springdoc:springdoc-openapi-webmvc-core:2.0.0.
     Required by:
         project :

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 15s
3 actionable tasks: 3 executed
```

**Expected behavior**

Dependencies resolved

**Screenshots**
N/A

**Additional context**
N/A

**Comment by ctmay4** [comment]
Same issue here.

**Comment by ParkerM** [comment]
The artifacts changed in 2.0.0 to align with Spring Boot starter naming conventions. See here: https://springdoc.org/v2/#migrating-from-springdoc-v1

**Comment by phillipuniverse** [comment]
@ParkerM thanks for that, my mistake for not checking the docs. That works!

Hopefully this will at least help with some google-bility!!
