### ISSUE TITLE
Kotlin coroutines continuation object in api schema

### ISSUE THREAD

**Issue by grzegorzekkk** [springdoc/springdoc-openapi#1978]
Hello, 
I am using springdoc-openapi-starter-webflux-ui version 2.0.0 in spring boot 3.0 with webflux and kotlin coroutines project.
Springdoc generates completion parameter in api schema requests for Continuation objects provided in suspend functions as provided below.

![image](https://user-images.githubusercontent.com/1730883/205283837-5de5c9fd-8f61-4cac-b73f-eeb7ccc32747.png)

That completion object should not be possible to define in swagger-ui.

**Comment by bnasslahsen** [comment]
see #1961
