### ISSUE TITLE
springdoc-openapi-ui doesn't work with Spring Boot 3

### ISSUE THREAD

**Issue by emeraldhieu** [springdoc/springdoc-openapi#1980]
Steps to reproduce

+ Create a simple project with spring-boot-starter-parent 3.0.0 and springdoc-openapi-ui 1.6.13
+ Access http://localhost:8080/swagger-ui.html 

Expected: Swagger UI shows up
Actual: 404 (Whitelabel Error Page)

Update spring-boot-starter-parent back to 2.7.4, it works.

Source Code: [demo.zip](https://github.com/springdoc/springdoc-openapi/files/10142682/demo.zip)

**Comment by BrotherPatrix** [comment]
For Spring Boot 3 there is the Jakarta EE update, which is not included in 1.6.13.
The new release 2.0.0 addresses the Spring Boot 3 support. Check here: https://springdoc.org/v2/

**Comment by emeraldhieu** [comment]
> For Spring Boot 3 there is the Jakarta EE update, which is not included in 1.6.13. The new release 2.0.0 addresses the Spring Boot 3 support. Check here: https://springdoc.org/v2/

It works! Thanks!

BTW there's a misleading info in V1's documentation.

> Spring-boot (v1, v2 and **v3**)
