### ISSUE TITLE
Odd spring security support configuration

### ISSUE THREAD

**Issue by BrotherPatrix** [springdoc/springdoc-openapi#1981]
**Describe the bug**
In version 2.0.0 for Spring Boot 3 as mentioned in the documentation [here](https://springdoc.org/v2/#properties) it seems that `springdoc.enable-spring-security` is by default `true` but in a project that I don't have `spring-boot-starter-security` included this is not taken in consideration, so this is good and works as expected, however there seems to be an issue in some particular cases and we might receive an error:
```bash
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.springdoc.core.configuration.SpringDocSecurityConfiguration$SpringSecurityLoginEndpointConfiguration': Lookup method resolution failed
```

**To Reproduce**
In my project, I added `spring-security-core` because I wanted to use some crypto features and other utils for some specific scenarios, and thus the error described above occurs.
If I force `springdoc.enable-spring-security=false`, the error goes away and works as expected.

I decided to remove `spring-security-core` from my project and I also removed the forced property `springdoc.enable-spring-security`, then the project starts normally and works as expected.

I started to think that there is something in `spring-security-core` that triggers this behavior, so I decided to use only `spring-security-crypto` and implement locally all other utils methods in my own project, also no additional properties added, after this the project starts normally and works as expected.

**Expected behavior**
I would normally expect that adding `spring-boot-starter-security` will enable `org.springdoc.core.configuration.SpringDocSecurityConfiguration` but not if you import `spring-security-core`.
I can see the `@ConditionalOnClass(Authentication.class)` in `org.springdoc.core.configuration.SpringDocSecurityConfiguration` where `Authentication.class` is part of `spring-security-core`, but maybe it's better to use a different class, maybe a class from `spring-security-config`.

**Additional context**
This helped me find a flaw in my project. I decided to use only `spring-security-crypto` and implement all other utils methods/classes for my particular needs or use dedicated libraries for specific scenarios.

In case others run into this type of problem where they need only `spring-security-core` and want to avoid an error, you can add:
```bash
springdoc.enable-spring-security=false
```

**Comment by bnasslahsen** [comment]
@BrotherPatrix,

Thank you for your feedback.
Please feel free to propose directly a PR, if you identify any enhancement.
