### ISSUE TITLE
Kotlin - CoroutineContext and ContinuationObject parameters exposed in swagger docs for suspend functions

### ISSUE THREAD

**Issue by bkielczewski** [springdoc/springdoc-openapi#1983]
**Describe the bug**

Since 2.0, if Kotlin suspend fun is used on rest endpoints, CoroutineContext and ContinuationObject appear in the generated docs. This behavior is a regression from 1.+ where it was properly handled (hidden) by Kotlin module.

**To Reproduce**

- What version of spring-boot you are using?

3.0.0

- What modules and versions of springdoc-openapi are you using?

webflux-ui 2.0.0

- Provide with a sample code (HelloController) or Test that reproduces the problem

`
@RestController
class HelloController {

  @GetMapping
  suspend fun hello() = "hello"

}

`

**Expected behavior**

CoroutineContext and ContinuationObject should not be visible in the docs.

**Comment by bnasslahsen** [comment]
see https://github.com/springdoc/springdoc-openapi/issues/1961
