### ISSUE TITLE
Warning use LocalVariableTableParameterNameDiscoverer

### ISSUE THREAD

**Issue by guillaumeyan** [springdoc/springdoc-openapi#1986]
**Describe the bug**

A warn is displayed when we access http://localhost:8080/swagger-ui/index.html#/ :

> LocalVariableTableParameterNameDiscoverer : Using deprecated '-debug' fallback for parameter name resolution. Compile the affected code with '-parameters' instead or avoid its introspection: com.example.warn.AppController

**To Reproduce**

clone repository `git clone https://github.com/guillaumeyan/springdoc-warn.git`
Launch app and go to http://localhost:8080/swagger-ui/index.html#/

**Expected behavior**

No warning anymore

**Comment by bnasslahsen** [comment]
see #1958
