### ISSUE TITLE
Not required RequestBody missing

### ISSUE THREAD

**Issue by MartinMogh** [springdoc/springdoc-openapi#1987]
This endpoint has a path variable, request param and request body, but in the generated spec the request body is missing.
```java
  @PostMapping("/{id}")
  public ResponseEntity<?> example(@PathVariable Integer id,
                                   @RequestParam String test,
                                   @RequestBody(required = false) Map<String, String> parameters) {
      return ResponseEntity.ok(Map.of("message", parameters));
  }
```

**Using**
- spring-boot 2.7.5
- springdoc-openapi-ui 1.6.13

**Expected result**

I expected the openapi spec
```json
  "requestBody": {
      "content": {
          "application/json": {
              "schema": {
                  "type": "object",
                  "additionalProperties": {
                      "type": "string"
                  }
              }
          }
      },
      "required": false
  }
```

**Comment by bnasslahsen** [comment]
@MartinMogh,

Check RequestBody documentation:
- https://swagger.io/docs/specification/describing-request-body/

It's by default `false`.

**Comment by MartinMogh** [comment]
i think you misunderstod, this is a problem with 

org.springframework.web.bind.annotation.RequestBody 

not 

io.swagger.v3.oas.annotations.parameters.RequestBody 

i currently use this workaround:

```java
  @PostMapping("/{id}")
  @io.swagger.v3.oas.annotations.parameters.RequestBody(description = "optional cmd parameters", content = @Content(schema = @Schema(type = "object")))
  public ResponseEntity<?> example(@PathVariable ObjectId id,
                                   @RequestParam String test,
                                   @RequestBody(required = false) Map<String, String> parameters) {
      return ResponseEntity.ok(Map.of("message", parameters));
  }
```

**Comment by bnasslahsen** [comment]
@MartinMogh,

There is no misunderstanding. 
Remember, contributions to this repository should follow its [contributing guidelines](https://github.com/springdoc/springdoc-openapi/blob/208882c87dbde2d656e2e6fb423496da3dcee9b6/CONTRIBUTING.adoc), [security policy](https://github.com/springdoc/springdoc-openapi/blob/208882c87dbde2d656e2e6fb423496da3dcee9b6/SECURITY.md), and [code of conduct](https://github.com/springdoc/springdoc-openapi/blob/208882c87dbde2d656e2e6fb423496da3dcee9b6/CODE_OF_CONDUCT.md).

Please make sure you read the Contribution guidelines before opening this kind of tickets.
