### ISSUE TITLE
Map-typed attributes missing in 2.0.0

### ISSUE THREAD

**Issue by jochenberger** [springdoc/springdoc-openapi#1993]
I'm migrating a project from Spring Boot 2.7 to Spring Boot 3.
I upgraded to `springdoc-openapi-starter-webmvc-ui:2.0.0` but now a lot of `Map`-typed attributes are no longer included in the `OpenAPI`.
If I create schemas with `ModelConverters` manually, the attributes are there, so I suspect that it has something to do with the transformation in `SpringDocAnnotationsUtils`.
The maps keys are Strings, the values are custom classes.

**Comment by bnasslahsen** [comment]
Provide a [Minimal, Reproducible Example - with HelloController](https://stackoverflow.com/help/minimal-reproducible-example) that reproduces the problem IN THE SAME TICKET

**Comment by jochenberger** [comment]
Nah, I think I'll rather let you fix it on your own and spend my time helping friendlier people. 🙂
