### ISSUE TITLE
spring boot 3 native build is failing

### ISSUE THREAD

**Issue by ozkanpakdil** [springdoc/springdoc-openapi#1995]
**native image is not having swagger-ui**

Code is running without problem from jvm side but when I build it **mvn native:compile -Pnative** native image giving 404 for swagger ui url

**To Reproduce**
here is the code https://github.com/ozkanpakdil/spring-examples/tree/master/swagger-boot3-graalvm

- What version of spring-boot you are using? **3.0.0**
- What modules and versions of springdoc-openapi are you using? **springdoc-openapi-starter-webmvc-ui**
- What is the actual and the expected result using OpenAPI Description (yml or json)? **no yml problem**
- Provide with a sample code (HelloController) or Test that reproduces the problem **http://localhost:8080/swagger-ui/index.html is giving 404 in native image**

**Expected behavior**
see the swagger-ui

**Screenshots**
![image](https://user-images.githubusercontent.com/604405/206590387-200ed9ed-564f-4b83-9a91-d6f78d141b2e.png)
suppose to look like below
![image](https://user-images.githubusercontent.com/604405/206590495-9747e3f5-c7f8-43cf-b5b9-cca785a7a41e.png)

**Additional context**
I tried to use **springdoc-openapi-native** but build is failing the error below
```bash
GraalVM Native Image: Generating 'demo' (executable)...
========================================================================================================================
[1/7] Initializing...
                                                                                    (0.0s @ 0.12GB)
Error: Could not find target method: private org.springframework.boot.Banner org.springframework.nativex.substitutions.boot.Target_SpringApplicationBannerPrinter.getImageBanner(org.springframework.core.env.Environment)
Error: Use -H:+ReportExceptionStackTraces to print stacktrace of underlying exception
------------------------------------------------------------------------------------------------------------------------
                        0.8s (7.2% of total time) in 11 GCs | Peak RSS: 0.88GB | CPU load: 2.94

```
I think spring-native is deprecated and they merge the functionality into spring-boot so this dependency is not working now. Others also having same problem check https://stackoverflow.com/q/74712624/175554

**Comment by Chuckame** [comment]
Same for me with webflux (springboot 3)

**Comment by bnasslahsen** [comment]
Read the docs

https://springdoc.org/

![Uploading image.png…]()
