### ISSUE TITLE
Whether the "@ Schema" can be grouped like "@Validated" in Springboot.

### ISSUE THREAD

**Issue by obeast-dragon** [springdoc/springdoc-openapi#1997]
**Is your feature request related to a problem? Please describe.**

- unable to group (I'm not sure whether this function exists), resulting in the creation of a large number of classes and schemas(data model).

**Describe the solution you'd like**

- Whether the "@ Schema" can be grouped like "@Validated" in Springboot.

**Describe alternatives you've considered**

- create multiple similar class or schemas(data model).

**Additional context**

**Comment by bnasslahsen** [comment]
Not clear...
