### ISSUE TITLE
Latest version 2.0.0 not available in Maven

### ISSUE THREAD

**Issue by lbenedetto** [springdoc/springdoc-openapi#1998]
Latest is 1.6.13
https://mvnrepository.com/artifact/org.springdoc/springdoc-openapi-ui

And indeed when I try to update it in my project I get
`Could not find org.springdoc:springdoc-openapi-ui:2.0.0.`

**Comment by lbenedetto** [comment]
This is because the modules have been renamed:
https://github.com/springdoc/springdoc-openapi-demos/wiki/springdoc-openapi-2.x-migration-guide

**Comment by bnasslahsen** [comment]
Just read the documentation please https://springdoc.org/v2/#migrating-from-springdoc-v1
