### ISSUE TITLE
Nested lists are not handled 

### ISSUE THREAD

**Issue by LexanRed** [springdoc/springdoc-openapi#1999]
**Describe the bug**
We have a simple DTO mapping which includes a list objects of the same data type. 
This is the class: 
```
@Data
@Builder
@AllArgsConstructor(access = AccessLevel.PRIVATE)
@Schema(name = "CourseDraftNode")
public class CourseDraftNodeResponse implements Comparable<CourseDraftNodeResponse> {

    @NotNull
    private UUID key;
    @NotNull
    private OffsetDateTime createdAt;
    @NotNull
    private OffsetDateTime updatedAt;

    private UUID parentKey;
    @NotNull
    private UUID draftKey;

    @NotNull
    private CourseNodeType type;
    @NotNull
    private Integer position;
    @NotNull
    private String title;
    private String description;

    @NotNull
    private List<CourseDraftNodeItemResponse> items = new ArrayList<>();
    @NotNull
    private List<CourseDraftNodeResponse> children = new ArrayList<>();

    @Override
    public int compareTo(CourseDraftNodeResponse otherNodeResponse) {
        // Sort by parentKey nulls first and then by position
        if (Objects.isNull(parentKey) && Objects.nonNull(otherNodeResponse.getParentKey())) {
            return -1;
        } else if (Objects.nonNull(parentKey) && Objects.isNull(otherNodeResponse.getParentKey())) {
            return 1;
        } else {
            return position.compareTo(otherNodeResponse.getPosition());
        }
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof CourseDraftNodeResponse that)) return false;
        return getKey().equals(that.getKey());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getKey());
    }
}
```

The list children is not included in the generated json. The list items is visible, but not children. 
We tried other classes and added Lists. Whenever we want to add a list with the same data type as the object to model a tree structure, the list is not present in  the generated api specification. 

![Screenshot 2022-12-10 at 17 16 25](https://user-images.githubusercontent.com/57357219/206864569-0d2af7bf-6939-4682-85e2-d107d381adff.png)
This is how the the class looks like if you inspect it with swagger ui. 

If I change the type from List to ArrayList in the response DTO, the list is added to the generated JSON. 
![Screenshot 2022-12-10 at 17 39 25](https://user-images.githubusercontent.com/57357219/206865450-d831f818-8b6c-433a-a130-e75cfb1a2d0a.png)

In the swagger UI it is displayed as a list of strings... this is really a strange behaviour. 
![Screenshot 2022-12-10 at 17 40 28](https://user-images.githubusercontent.com/57357219/206865512-128a678e-fe39-4e36-beb6-cb16ae1d571c.png)
![Screenshot 2022-12-10 at 17 40 48](https://user-images.githubusercontent.com/57357219/206865541-4253bd62-67d4-409e-b017-f152e187b1fc.png)

**To Reproduce**
Create a class which contains a list of the same data type as the class itself. 
Create a rest endpoint which returns this an object of this class. 
Inspect the generated JSON and the swagger UI. 

- What version of spring-boot you are using?
2.7.4

- What modules and versions of springdoc-openapi are you using?
```
<dependency>
    <groupId>org.springdoc</groupId>
    <artifactId>springdoc-openapi-ui</artifactId>
    <version>1.6.11</version>
</dependency>
<dependency>
    <groupId>org.springdoc</groupId>
    <artifactId>springdoc-openapi-security</artifactId>
    <version>1.6.11</version>
</dependency>
<dependency>
    <groupId>org.springdoc</groupId>
    <artifactId>springdoc-openapi-data-rest</artifactId>
    <version>1.6.11</version>
</dependency>
```

- What is the actual and the expected result using OpenAPI Description (yml or json)?
json 

- Provide with a sample code (HelloController) or Test that reproduces the problem
```
@RestController
@Tag(name = "Course Draft")
@RequestMapping("/test")
@RequiredArgsConstructor
public class TestController {
    @GetMapping
    public CourseDraftNodeResponse getCourseDraft() {
        return CourseDraftNodeResponse.builder().build();
    }
}
```

**Expected behavior**
The nested list should be added to the json response. 
Swagger should display not string as data type but the actual object.

**Additional context**
Lombok is used.

**Comment by bnasslahsen** [comment]
@LexanRed,

The generated OpenAPI spec is correct.
<img width="569" alt="image" src="https://user-images.githubusercontent.com/13404829/207038880-a2824358-14ab-49a8-9ba2-9c11d17117cb.png">

If you are having issues with the UI, please raise a bug in the https://github.com/swagger-api/swagger-ui project instead

**Comment by LexanRed** [comment]
@bnasslahsen 

The generated OpenAPI spec is **only** correct if I declare the List as ArrayList.
Instead of `private **List**<CourseDraftNodeResponse> children = new ArrayList<>();` I have to use `private **ArrayList**<CourseDraftNodeResponse> children = new ArrayList<>();`

Only then the list is included in the generated spec. This only applies to lists, which are of the same class as the class they are defined in. 

Sorry for making it not clear in my first post. 
I hardly think this is working as intended.

**Comment by bnasslahsen** [comment]
@LexanRed,

The screenshot above, is related to the declaration with `List`
Two things here: 
- if you are having an issue, add a failing testcase to your code that shows it.
- Second point, make sure that you are not referring to a bug in the [swagger-core](https://github.com/swagger-api/swagger-core) itself. As i can tell you 100% there is no difference of the processing in the `springdoc-openapi` code between `List` and `ArrayList`.

**Comment by LexanRed** [comment]
> Second point, make sure that you are not referring to a bug in the [swagger-core](https://github.com/swagger-api/swagger-core) itself. As i can tell you 100% there is no difference of the processing in the springdoc-openapi code between List and ArrayList

Exactly this is the point. If declared as List, it is not present. If declared as ArrayList, it is processed correctly

**Comment by LexanRed** [comment]
Annotating the list with @ArraySchema seems to fix the problem. 
The generated JSON looks fine. 

`@ArraySchema
    private List<CourseNodeResponse> children = new ArrayList<>();`

**Comment by gyimgabor** [comment]
Is there any information about what causing this issue? I have a similar issue:

In the example below, the `B` type **does** contains the list, but the `C` and `D` do not.

* Adding additional properties or changing the name of the property in `C` or `D` does not fixes the issue.
* Using `ArrayList` instead of `List`, or using `@ArraySchema` annotation does not fixes the issue.

I am using springdoc-openapi-maven-plugin 1.4
```java
@Data
public class A implements Serializable {

    @Data
    public class B implements Serializable {
        public String functionName;
        public List<A> arguments;
    }

    @Data
    public class C implements Serializable {
        public List<A> elements;
    }

    @Data
    public class D implements Serializable {
        public List<A> children;
    }
    public B b;
    public C c;
    public D d;
}
```
