### ISSUE TITLE
Detect context-path on standalone webservers

### ISSUE THREAD

**Issue by membersound** [springdoc/springdoc-openapi#20]
By default, the paths in the specs are autogenerated as follows:

```
{"openapi":"3.0.1","info":{"title":"OpenAPI definition","version":"v0"},"paths":{"/the/endpoint"...
```

This is fine in a standalone app.
But if the application is deployed on a standalone webserver like `tomcat`, there is a problem deriving the correct context path.

In fact, the specs are still created in the same manner. Thus, swagger ui executes the requests to: `localhost:8080/the/endpoint`.

But instead, on a standalone webserver, the correct path would be:
`localhost:8080/my-app/the/endpoint`.

It would be nice if springdoc could detect that context path and append it to the paths or server attribute in the specs, without having to set it manually programmatically.

This could be a starting point:
https://github.com/springfox/springfox/blob/master/springfox-spring-web/src/main/java/springfox/documentation/spring/web/paths/DefaultPathProvider.java

**Comment by springdoc** [comment]
context-path is detected on standalone webservers. But not used to update the paths or servers.
Generating  automatically server url may be useful, if the documentation is not present.
If the server annotations are present, they will be used instead.
This feature, will be only available for the moment spring-mvc and not webflux.
This will be released on springdoc v1.1.8
