### ISSUE TITLE
Support for other collection library (Guava, Vavr, etc...)

### ISSUE THREAD

**Issue by Decat-SimonA** [springdoc/springdoc-openapi#200]
Objects using different collection libraries such as Vavr will have a wrong Schema
For example:
```java
public class User {
  private io.vavr.collection.Set<Role> roles;
}
```
is currently appearing in the Swagger UI like this:
```json
{
  "roles": {
    "distinct": true,
    "ordered": true,
    "sequential": true,
    "singleValued": true,
    "traversableAgain": true,
    "empty": true,
    "orNull": "ADMIN",
    "async": true,
    "lazy": true,
    "memoized": true
  }
}
```
instead of simply
```json
{
  "roles": [ ]
}
```

Springfox supports this use case with `AlternateType` (see https://github.com/springfox/springfox/issues/1971 for example).

Is there a way to configure this ?

**Comment by springdoc** [comment]
Hi, 

 You can set it using @Schema annotation on your operation level.
 Or you can override this behaviour by providing your own ModelConverter a spring bean:
- https://github.com/swagger-api/swagger-core/wiki/Swagger-2.X---Extensions#extending-core-resolver
