### ISSUE TITLE
springdoc doesn't seem to be compatible wit spring-boot3

### ISSUE THREAD

**Issue by StefanSchubert** [springdoc/springdoc-openapi#2005]
Hi first of all thanks a lot for springdoc!
I suppose that it's because of the javax. package namespace switching to jakarta.

**Describe the bug**

I switched my project from spring-boot 2.7.x (with working springdoc integration) to spring-boot-3
Unfortunately the breaks the generation of the swagger (openapi) pages.

**To Reproduce**
Port your spring project to spring-boot-3 and try to access the the swagger UI.
Or take this one as reference project: https://github.com/StefanSchubert/sabi/tree/feature/sabi-85/captcha
Just launch the spring boot application and see what's happening when trying to access the swagger UI 
http://localhost:8081/captcha/swagger-ui/index.html

**Expected behavior**
UI  shows up

**Comment by bnasslahsen** [comment]
@StefanSchubert,

Read the doc: You have an important Note

http://springdoc.org/

**Comment by StefanSchubert** [comment]
Hi @bnasslahsen ,
ah I see. THX! I see it come with a different API or do we need an additional module as dependency? From the doc it seems that 

```
 <dependency>
      <groupId>org.springdoc</groupId>
      <artifactId>springdoc-openapi-starter-webmvc-ui</artifactId>
      <version>2.0.0</version>
   </dependency>
```

is sufficient. But just by relacing the libs git complaints that `import org.springdoc.core.GroupedOpenApi;` is not available. What are the future plans of both libs?

Will _springdoc-openapi-starter-webmvc-ui_ be the spring-boot 3 flavor and
_springdoc-openapi-ui_ sticks then to spring-boot 2.7 ?

Greetings from Cologne, Germany
Stefan

**Comment by bnasslahsen** [comment]
@StefanSchubert,

it's all explained in the documentation. 
Please read it: https://springdoc.org/v2/#migrating-from-springdoc-v1

And you have demos code here:
https://github.com/springdoc/springdoc-openapi-demos/tree/2.x

**Comment by StefanSchubert** [comment]
Hi @bnasslahsen,

Should have done this right from the beginning. Wasn't aware of that I'm using springdoc-openapi-v1. The migration was fairly easy following the docu. Great idea with the "Important" tags in the docu.
Sorry for bothering and thx for pushing me RTFM. :-)

Have a nice weekend!
