### ISSUE TITLE
Required mapping in Kotlin is not working with springdoc v2

### ISSUE THREAD

**Issue by ruoat** [springdoc/springdoc-openapi#2007]
Hi, I upgraded to Spring Boot 3.0.0 and replaced

springdoc 1.6.11 

org.springdoc:springdoc-openapi-data-rest
org.springdoc:springdoc-openapi-ui
org.springdoc:springdoc-openapi-kotlin

to springdoc 2.0.0
org.springdoc:springdoc-openapi-starter-common
org.springdoc:springdoc-openapi-starter-webmvc-ui

Now data classes required property is not set correctly according the nullability in val.

The following code 
```
fun listUsers(): List<UserResult> {
    return userQueryService.listUsers()
}

data class UserResult(
    val userId: UUID
)
```

produced in 1.6.11:
```
"UserResult": {
                "required": [
                    "userId"
                ],
                "type": "object",
                "properties": {
                    "userId": {
                        "type": "string",
                        "format": "uuid",
                    }
                },
            },
```

But in 2.0.0 it produces:
```
"UserResult": {
                "type": "object",
                "properties": {
                    "userId": {
                        "type": "string",
                        "format": "uuid",
                    }
                },
            },
```
So every field becomes non-mandatory and that breaks the API contract.

**Comment by bnasslahsen** [comment]
please see the answer here #1961
