### ISSUE TITLE
Upgrade to 2.0.1 is breaking when `com.fasterxml.jackson.module.kotlin.KotlinModule` is not present in classpath

### ISSUE THREAD

**Issue by rajadilipkolli** [springdoc/springdoc-openapi#2008]
**Describe the bug**

- I have CI/CD enabled in github using github-actions. when it is trying to upgrade to 2.0.1 build is failing as jackson kotlin module is not present in the classpath

Below is the error.

` java.lang.ClassNotFoundException: com.fasterxml.jackson.module.kotlin.KotlinModule`

**To Reproduce**

- What version of spring-boot you are using  - **3.0.0**
- What modules and versions of springdoc-openapi are you using - **2.0.1** webmvc starter
-  Clone [this ](https://github.com/rajadilipkolli/my-spring-boot-experiments/tree/main/spring-boot-strategy-plugin) project. start using normal spring run and it should be up and pipeline build should pass.

**Expected behavior**

- Build to pass without breaking and autoconfiguration should backoff when kotlinModule is not present

**Additional context**
Github action pileline logs can be seen [here](https://github.com/rajadilipkolli/my-spring-boot-experiments/actions/runs/3712744316/jobs/6294611262)

**Comment by bnasslahsen** [comment]
@programista-zacny, @rajadilipkolli 

Should be better with 2.0.2

**Comment by rajadilipkolli** [comment]
Its working now, thank you @bnasslahsen for the quick fix and release. This quick release cycle makes springdoc-openapi more adaptable. kudos to the team for the amazing work
