### ISSUE TITLE
Functional endpoints not visible on swagger-ui

### ISSUE THREAD

**Issue by infoShare** [springdoc/springdoc-openapi#2009]
**Describe the bug**
Functional endpoints (spring-cloud-functions) are not visible on swagger-ui for spring boot 3.0.0

**To Reproduce**
Repository with sample code: https://github.com/infoShare/SpringDoc

**Expected behavior**
Function endpoints should be visible

**Screenshots**
Only REST endpoints are visible:
![image](https://user-images.githubusercontent.com/22718112/208145794-c79fb185-a49e-4e53-ba25-1e7c7c04dc1b.png)

**Comment by bnasslahsen** [comment]
@infoShare,

Review your code.
You are filtering for `springdoc.pathsToMatch=/api/**`
Removing the property, enables the functional endpoints...

**Comment by infoShare** [comment]
Removing springdoc.pathsToMatch is not fixing the issue (and it was tested previously). Property was removed on the repository.

**Comment by bnasslahsen** [comment]
@infoShare,

Add a testcase that shows its not working...

**Comment by infoShare** [comment]
Screenshot from swagger was attached on the ticket

**Comment by bnasslahsen** [comment]
This ticket is already answered.
