### ISSUE TITLE
Hide different endpoints depending on environment 

### ISSUE THREAD

**Issue by mbedna** [springdoc/springdoc-openapi#201]
I would like to hide different endpoints on production environment than on other environments. Is it possible? I thought about using filters but I'm not sure how. Do you have any examples how to use them?

https://github.com/swagger-api/swagger-core/wiki/Swagger-2.X---Extensions#filters

**Comment by springdoc** [comment]
You can use on swagger:    ` @Operation(hidden = true) `or `@Hidden` annotations
If you need something custom, you can write your own implementation of OpenApiCustomiser.
This can help you generate different OpenAPI spec depending on environnement.

An example is available on: 
- https://github.com/springdoc/springdoc-openapi/blob/master/springdoc-openapi-webmvc-core/src/test/java/test/org/springdoc/api/app39/SpringDocApp39Test.java

Finally, you can disable the springdoc-openapi endpoints,,using:
`springdoc.api-docs.enabled=false`

**Comment by mbedna** [comment]
This works correctly. Thanks.

**Comment by himsa04** [comment]
can it be illustrated with java example

**Comment by Adriansun** [comment]
I would really like to see something like 

Method1:
@Profile("companyA", "CompanyB")
Method2:
@Profile("companyA")
Method3:
@Profile("companyB")

over each method. Then in the application.properties I would write something like:

swagger-ui.profile=companyA 
thus only the methods with companyA could show or

swagger-ui.profile=companyA , companyB
thus only the methods with companyA and companyB would show or

swagger-ui.profile=    // or just nothing
thus all methods would show alway
