### ISSUE TITLE
Upgrading beyond 1.6.6 causes example output discrepency from previous versions

### ISSUE THREAD

**Issue by soulshined** [springdoc/springdoc-openapi#2011]
**Describe the bug**

Example output for resolved schemas from version 1.6.6 is gibberish

- My assumption is that it's due to the schema having a `pattern` property supplied

**To Reproduce**

- use any springdoc version beyond 1.6.6

**Expected behavior**

Output example value should be human readable example

```java
@RestController
@RequestMapping("/reproduce")
public class RequestBodySchemaController {

    @GetMapping
    @io.swagger.v3.oas.annotations.parameters.RequestBody(
        content = @Content(
            schema = @Schema(
                ref = "https://your.server.com/schemas/schema.json"
            )
        )
    )
    public void resolve_schema(@RequestBody Map<String, Object> body) {

    }

}
```

Output with version 1.6.6
![Screen Shot 2022-12-19 at 9 46 15 AM](https://user-images.githubusercontent.com/11242654/208466100-fe456824-7b17-49be-98da-eae1eee5bb8d.png)

Output with version beyond 1.6.6
![Screen Shot 2022-12-19 at 9 48 51 AM](https://user-images.githubusercontent.com/11242654/208466184-090cc068-e6df-4f94-8628-a19160d56187.png)

My hosted schema has not changed in structure across springdoc versions. 

Here is the schema for 'productIdentifier'

```json
"productIdentifier" : {
       "type" : "string",
       "pattern" : "^\\S+$",
       "minLength" : 1
} 
```

When not using `pattern` in the schema it resolves to expected example output

**Comment by bnasslahsen** [comment]
@soulshined,

Please use last stable version, before opening bugs ...

**Comment by soulshined** [comment]
I have @bnasslahsen please note that it states *beyond* 1.6.6 - I was simply helping you determine where it started for troubleshooting purposes

**Comment by bnasslahsen** [comment]
@soulshined,

Could you please confirm your issue with the latest stable version ?

**Comment by soulshined** [comment]
Sure @bnasslahsen It is confirmed. I tested against every version starting at 1.6.6 up until 1.6.14. We can not use v2 right now as our business hasn't moved to spring v3 yet

**Comment by bnasslahsen** [comment]
@soulshined,

Can you add the link to a github repo, with a minimal reproducible sample?

**Comment by soulshined** [comment]
@bnasslahsen I am at work right now so I can not at the moment. But the mimimal thing to reproduce is in the schema in the description. But to simplify it - all you need to reproduce is

```java
@RestController
public class RequestBodySchemaController {

    @io.swagger.v3.oas.annotations.parameters.RequestBody(
        content = @Content(
            schema = @Schema(
                type = "string",
                pattern = "^\\S+$",
                minLength = 1
            )
        )
    )
    @GetMapping
    public void example_output_gibberish(@RequestBody Map<String, Object> body) {

    }

}
```

if you still want a repo considering that let me know and I'll get one going later for you

**Comment by bnasslahsen** [comment]
@soulshined,

Well, this change is related to `swagger-ui` interface and the generated OpenAPI spec is correct.
Feel free to reach out the [swagger-ui](https://github.com/swagger-api/swagger-ui)  project instead.
You have here the swagger-ui version used for v1.6.6
https://github.com/springdoc/springdoc-openapi/blob/ede57024ce054129f9cf7d230f4d9b278b5f3ead/pom.xml#L72

**Comment by soulshined** [comment]
> @soulshined,
> 
> Well, this change is related to `swagger-ui` interface and the generated OpenAPI spec is correct. Feel free to reach out the [swagger-ui](https://github.com/swagger-api/swagger-ui) project instead. You have here the swagger-ui version used for v1.6.6
> 
> https://github.com/springdoc/springdoc-openapi/blob/ede57024ce054129f9cf7d230f4d9b278b5f3ead/pom.xml#L72

Will do. Thanks bnasslahsen
