### ISSUE TITLE
Path attribute is not working in RouterOperation for Spring Cloud Functions and Swagger is showing api twice

### ISSUE THREAD

**Issue by ShubamVirdi** [springdoc/springdoc-openapi#2015]
I have integrated spring doc open api with 1.6.14 version. The issue is when i add the annotations to an function it does not show the updated path in the swagger ui instead just shows up the name of the function itself.

<img width="890" alt="Screenshot 2022-12-21 at 5 55 39 PM" src="https://user-images.githubusercontent.com/97431372/208904606-432f6d74-462e-4b47-bed5-de932385fc15.png">

And also the documentation shows up the same cloud function twice
<img width="1459" alt="Screenshot 2022-12-21 at 5 56 31 PM" src="https://user-images.githubusercontent.com/97431372/208904739-22d9143a-e344-46f7-9fa3-c6c56b3093e1.png">

**Comment by bnasslahsen** [comment]
@ShubamVirdi,

Make sure you provide a Provide a [Minimal, Reproducible Example - with HelloController](https://stackoverflow.com/help/minimal-reproducible-example) that reproduces the problem.

Once added, this ticket can be reopened.

**Comment by ShubamVirdi** [comment]
Hi @bnasslahsen I have added a sample reference.
[Repo Link](Repo Url: https://github.com/ShubamVirdi/spring-docs-demo)
but in this case i am not even getting swagger ui instead i am getting the json in the url.
http://localhost:8090/swagger-ui/index.html

**Comment by bnasslahsen** [comment]
@ShubamVirdi, 

Your path is incorrect. And then ignored...
It should match the function name.
In general it's useless to add path for spring cloud function, as we can get the name automatically from spring.

For the `swagger-ui `error, just review your code. No further time will be spent on this ticket.
