### ISSUE TITLE
`/actuator/openapi` not exposed if `management.server.port` not set explicitly

### ISSUE THREAD

**Issue by singhbaljit** [springdoc/springdoc-openapi#2016]
**Describe the bug**

When exposing SpringDoc on Actuator path, the `/actuator/openapi` is not exposed unless `management.server.port` is explicitly set. By default, `management.server.port` is the same as `server.port`. 

**To Reproduce**

Spring Boot version: 3.0.0
SpringDoc: springdoc-openapi-starter-webflux-api, version: 2.0.2

```properties
springdoc.use-management-port=true
management.endpoints.web.exposure.include=openapi
```

**Expected behavior**

The `/actuator/openapi` should be exposed on the default management port as well.

**Comment by bnasslahsen** [comment]
@singhbaljit,

It's all explained in the documentation...
`springdoc.use-management-port` has only sense when The actuator management port has to be different from the application port.
