### ISSUE TITLE
openapi endpoint do not expose swagger in yaml format

### ISSUE THREAD

**Issue by DanielFran** [springdoc/springdoc-openapi#2018]
**Describe the bug**
When exposing openapi endpoint, it is not possible to expose information in yaml format

**To Reproduce**

- What version of spring-boot you are using? **2.7.6**
- What modules and versions of springdoc-openapi are you using? springdoc-openapi-ui and springdoc-openapi-webmvc-core version **1.6.14**
- What is the actual and the expected result using OpenAPI Description (yml or json)? yml
- Provide with a sample code (HelloController) or Test that reproduces the problem
```ini
management.server.port=7080
management.endpoint.health.probes.enabled=true
management.endpoints.web.base-path=/management
management.endpoints.web.exposure.include=health,info,openapi,swagger-ui
management.info.env.enabled=true
management.info.defaults.enabled=true

springdoc.show-actuator=false or true
springdoc.use-management-port=true
```

**Expected behavior**
The endpoint should allow exposition of yaml format

**Screenshots**
```ini
springdoc.show-actuator=false
```
![image](https://user-images.githubusercontent.com/3706415/209136940-6fc15632-88cf-45bb-8eb7-4174a5892cda.png)
![image](https://user-images.githubusercontent.com/3706415/209137043-28ab2bb2-e66d-4a4a-884c-ab79aa3f840c.png)
![image](https://user-images.githubusercontent.com/3706415/209137123-1ae5a6b2-d597-4dc9-858e-fa6a1341324e.png)

```ini
springdoc.show-actuator=true
```
![image](https://user-images.githubusercontent.com/3706415/209137373-06c17915-d68e-4ea9-8adf-6366614bb131.png)
![image](https://user-images.githubusercontent.com/3706415/209137430-356b0ee3-5614-454b-9a68-043485b09c5b.png)
![image](https://user-images.githubusercontent.com/3706415/209137510-6019eb54-4ffa-45a6-8240-6e790da82d27.png)

**Comment by bnasslahsen** [comment]
@DanielFran,

Instead of `openapi.yaml` try `openapi/yaml`

**Comment by DanielFran** [comment]
@bnasslahsen Confirmed it works.
Maybe would be better to update the documentation?
![image](https://user-images.githubusercontent.com/3706415/209193084-24d96475-861a-4bdd-b67f-8b917c2d9757.png)
