### ISSUE TITLE
How to use ArraySchema in @Parameter

### ISSUE THREAD

**Issue by huijiewei** [springdoc/springdoc-openapi#202]
I can't do success. thanks

@Operation(description = "List", parameters = {
            @Parameter(description = "Name", name = "name", in = ParameterIn.QUERY),
            @Parameter(description = "Phone", name = "phone", in = ParameterIn.QUERY),
            @Parameter(description = "createdFrom", name = "createdFrom", in = ParameterIn.QUERY, content = @Content(array = @ArraySchema(schema = @Schema(type = "string")))),
            @Parameter(description = "createdRange", name = "createdRange", in = ParameterIn.QUERY, array = @ArraySchema(schema = @Schema(type = "string", format = "date"), minItems = 2, maxItems = 2))
    })

**Comment by springdoc** [comment]
Hi, 

 A better support of this case using ArraySchema will be available on the next release of springdoc-openapi, v1.2.14.
