### ISSUE TITLE
OpenApiCustomiser does not exist ist version 2.0.2

### ISSUE THREAD

**Issue by vinkenfl** [springdoc/springdoc-openapi#2020]
The class org.springdoc.core.customizers.OpenApiCustomiser does not exist in SpringDoc version 2.0.2 anymore. I need to customize a header field during document generation. This is not possible any more.
I need to use the 2.x version because I am using Spring-Boot 3.0

**Comment by bnasslahsen** [comment]
Read https://springdoc.org/v2/#migrating-from-springdoc-v1
