### ISSUE TITLE
Specify a group as the default group

### ISSUE THREAD

**Issue by junweili** [springdoc/springdoc-openapi#2022]
Dear springdoc contributors,

How can I pick a specific group as the default group in the dropdown list of "Select a definition".

There is a property springdoc.swagger-ui.groups-order that I can configure to sort the groups by order. But it doesn't allow me to pick any random group as the default group. 
![example](https://user-images.githubusercontent.com/12969536/209373407-509bfd4e-9017-4e6f-92e5-ada3931df665.jpeg)

Such as in the above figure, for group "default", I haven't found a way to make it default in the dropdown list. Can this be supported? Thanks.

**Comment by FilipMalczak** [comment]
I may be wrong, but I believe that SpringDoc is something that takes Spring code stuff and makes OpenAPI YAML stuff. The screenshot that you attached is probably from Swagger UI. Swagger UI is a tool that takes OpenAPI YAML stuff and makes it into nice HTML page.

In other words, your question is probably better suited for https://github.com/swagger-api/swagger-ui

**Comment by junweili** [comment]
Thank you for the advice, @FilipMalczak Happy new year

**Comment by bnasslahsen** [comment]
@FilipMalczak,

You can use the following property 

```properties
springdoc.swagger-ui.urlsPrimaryName=yourDefaultGroupName
```

The explanation is available in the documentation: https://springdoc.org/#swagger-ui-properties
