### ISSUE TITLE
Hide a group in the dropdown list of "Select a definition"

### ISSUE THREAD

**Issue by junweili** [springdoc/springdoc-openapi#2023]
Dear springdoc contributors,

I need to create a group named as "internal" which is a collection of internal APIs. Internally people can access this group via url 

swagger-ui/index.html?urls.primaryName=internal

Hence is it possible to hide such group in the dropdown list of "Select a definition", so that externally this group is hidden, hence url swagger-ui/index.html?urls.primaryName=internal won't be exposed? Thanks. And happy holiday.

**Comment by bnasslahsen** [comment]
@junweili,

You load the external and internal groups related Beans, conditionally on properties the you define.
