### ISSUE TITLE
springdoc-openapi-kotlin support for spring-boot3

### ISSUE THREAD

**Issue by gdinant** [springdoc/springdoc-openapi#2026]
Hello there,

# Problem

Unless I'm way off, I cannot seem to make `springdoc-openapi` for `kotlin` work with `spring-boot 3.0.x`.

Dependencies:

```xml
<dependency>
	<groupId>org.springframework.boot</groupId>
	<artifactId>spring-boot-starter-webflux</artifactId>
	<version>3.0.1</version>
</dependency>

<dependency>
	<groupId>org.springdoc</groupId>
	<artifactId>springdoc-openapi-kotlin</artifactId>
	<version>1.6.14</version> <!-- latest I could find -->
</dependency>

<dependency>
	<groupId>org.springdoc</groupId>
	<artifactId>springdoc-openapi-starter-webflux-ui</artifactId>
	<version>2.0.2</version>
</dependency>
```

# Stacktrace

```java
***************************
APPLICATION FAILED TO START
***************************

Description:

An attempt was made to call a method that does not exist. The attempt was made from the following location:

    org.springdoc.webflux.ui.SwaggerWelcomeCommon.<init>(SwaggerWelcomeCommon.java:65)

The following method did not exist:

    'void org.springdoc.ui.AbstractSwaggerWelcome.<init>(org.springdoc.core.properties.SwaggerUiConfigProperties, org.springdoc.core.properties.SpringDocConfigProperties, org.springdoc.core.properties.SwaggerUiConfigParameters)'

The calling method's class, org.springdoc.webflux.ui.SwaggerWelcomeCommon, was loaded from the following location:

    jar:file:/Users/me/.m2/repository/org/springdoc/springdoc-openapi-starter-webflux-ui/2.0.2/springdoc-openapi-starter-webflux-ui-2.0.2.jar!/org/springdoc/webflux/ui/SwaggerWelcomeCommon.class

The called method's class, org.springdoc.ui.AbstractSwaggerWelcome, is available from the following locations:

    jar:file:/Users/me/.m2/repository/org/springdoc/springdoc-openapi-common/1.6.14/springdoc-openapi-common-1.6.14.jar!/org/springdoc/ui/AbstractSwaggerWelcome.class
    jar:file:/Users/me/.m2/repository/org/springdoc/springdoc-openapi-starter-common/2.0.2/springdoc-openapi-starter-common-2.0.2.jar!/org/springdoc/ui/AbstractSwaggerWelcome.class

The called method's class hierarchy was loaded from the following locations:

    org.springdoc.ui.AbstractSwaggerWelcome: file:/Users/me/.m2/repository/org/springdoc/springdoc-openapi-common/1.6.14/springdoc-openapi-common-1.6.14.jar
```

# Action

Would it be possible to release a version of `springdoc-openapi-kotlin` compatible with `spring-boot3`?

Thanks for the great lib! :)

**Comment by enenuki** [comment]
I have similar problem. However, my application starts and works as expected but I cannot get the swager UI. 
I've been following instructios from: https://springdoc.org/#kotlin-support

Here is my

`plugins {
    id("org.springframework.boot") version "3.0.0"
    id("io.spring.dependency-management") version "1.1.0"
    kotlin("jvm") version "1.7.21"
    kotlin("plugin.spring") version "1.7.21"
    jacoco
}
...
dependencies {

    val awsSdkVersion = "2.19.0"
    val ddmUtilsVersion = "1.0.3"
    val logstashLogbackEncoderVersion = "7.2"
    val mockitoKotlinVersion = "4.1.0"
    val springCloudSleuthVersion = "3.1.5"
    val springDocOpenAPIVersion = "1.6.14"

    implementation("org.jetbrains.kotlin:kotlin-stdlib-jdk8")
    implementation("org.jetbrains.kotlin:kotlin-reflect")
    implementation("org.jetbrains.kotlinx:kotlinx-coroutines-core")
    implementation("org.jetbrains.kotlinx:kotlinx-coroutines-reactor")
    implementation("io.projectreactor.kotlin:reactor-kotlin-extensions")

    implementation("org.springframework.boot:spring-boot-starter-webflux")
    implementation("org.springframework.boot:spring-boot-starter-actuator")
    implementation("org.springframework.boot:spring-boot-starter-validation")
    implementation("org.springframework.cloud:spring-cloud-starter-sleuth:${springCloudSleuthVersion}")
    implementation("org.springdoc:springdoc-openapi-starter-common:2.0.2")
    implementation("org.springdoc:springdoc-openapi-starter-webflux-ui:2.0.2")
    implementation("org.springdoc:springdoc-openapi-kotlin:${springDocOpenAPIVersion}")

    implementation("software.amazon.awssdk:dynamodb:${awsSdkVersion}")
    implementation("software.amazon.awssdk:dynamodb-enhanced:${awsSdkVersion}")
    implementation("software.amazon.awssdk:sts:${awsSdkVersion}")
    implementation("software.amazon.awssdk:sso:${awsSdkVersion}")


    implementation("com.fasterxml.jackson.module:jackson-module-kotlin")
    implementation("io.micrometer:micrometer-registry-prometheus")
    implementation("io.beyonnex.shared:utils:$ddmUtilsVersion")
    implementation("net.logstash.logback:logstash-logback-encoder:${logstashLogbackEncoderVersion}")

    testImplementation("org.springframework.boot:spring-boot-starter-test")
    testImplementation("org.mockito.kotlin:mockito-kotlin:$mockitoKotlinVersion")
}

`

**Comment by enenuki** [comment]
I have similar problem. However, my app starts but I seem unable to get swagger UI. Any updates on this?

**Comment by gdinant** [comment]
@enenuki Are running also with the latest version of kotling (1.8.0)?

**Comment by jfinancial** [comment]
I'm seeing this too and am using Spring Boot version 3.0.1, java version 17 and kotlin version 1.7.22.

I'm slightly confused about what dependencies I should actually be using. I've tried various combinations of the following:

`		<dependency>
			<groupId>io.springfox</groupId>
			<artifactId>springfox-boot-starter</artifactId>
			<version>3.0.0</version>
		</dependency>
		<dependency>
			<groupId>org.springdoc</groupId>
			<artifactId>springdoc-openapi-common</artifactId>
			<version>1.6.14</version>
		</dependency>
		<dependency>
			<groupId>org.springdoc</groupId>
			<artifactId>springdoc-openapi-starter-webmvc-ui</artifactId>
			<version>2.0.2</version>
		</dependency>
		<dependency>
			<groupId>org.springdoc</groupId>
			<artifactId>springdoc-openapi-kotlin</artifactId>
			<version>1.6.14</version>
			<scope>runtime</scope>
		</dependency>
		<dependency>
			<groupId>org.hibernate</groupId>
			<artifactId>hibernate-validator</artifactId>
			<version>8`
