### ISSUE TITLE
Recognize sealed classes

### ISSUE THREAD

**Issue by FilipMalczak** [springdoc/springdoc-openapi#2027]
**This is a request for an extension of an existing feature, without breaking backward compability.**

Polymorphism in OpenAPI is pretty straight-forward, but verbose. SpringDoc may (I am not aware that it does) figure out class hierarchies in parameters and responses, but for sure (just checked it) it doesn't recognizes the `sealed` types. An example follows.

Given situation like:

```
interface ObjectPointer {}
record ObjectId(String id) implements ObjectPointer {}
record ObjectCoordinates(String path, String name) implements ObjectPointer {}
record ObjectQuery(ObjectPointer pointer, Criteria criteria) {} 
```

if I declare an endpoint like:

```
@PostMapping(...)
Flux<ObjectRepresentation> fetchObjects(Flux<ObjectQuery> queries){...}
```

and in cases when I seal the `ObjectPointer`:

```
sealed interface ObjectPointer permits ObjectId, ObjectCoordinates {}
```

I still need to annotate it with schema:

```
@Schema(anyOf={ObjectId.class, ObjectCoordinates.class})
sealed interface ObjectPointer permits ObjectId, ObjectCoordinates {}
//ditto with non-sealed
```

Without it, the `ObjectPointe`r has no `anyOf` in the YAML, even though both `ObjectId` and `ObjectCoordinates` are represented too.

In case of non-sealed types, it is quite obvious and makes sense - there is no point in doing expensive scan of available classes to try and figure out the hierarchy (or bring in some nifty dependencies).

**In case of sealed classes though...**

> Describe the solution you'd like

I would like the `@Schema(anyOf=...)` to be derived automatically. To recognize sealed classes we can use [`Class.isSealed()`](https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/lang/Class.html#isSealed()), 
while to find out the permitted subtypes we can use [`Class.getPermittedSubclasses()`](https://docs.oracle.com/en/java/javase/17/docs/api/java.base/java/lang/Class.html#getPermittedSubclasses())

Notice that this feature should cover all the types that are represented in the YAML - parameters, responses, components, etc.

In my opinion, in case of "tiered" sealed types, we should represent tiering in the YAML. In other words, given:

```
sealed interface A permits B, C {}
record B ... implements A ...
sealed interface C permits D, E {}
record D ... implements C ...
record E ... implements C ...
```

I DO expect that types are represented as:

```
A=anyOf(ref:B, ref:C)
C=anyOf(ref:D, ref:E)
```

and I expect that we DON'T represent them as

```
A=anyOf(ref:B, ref:D, ref:E)
```

There is still a question of unsealed subhierarchies. Given

```
sealed interface A permits B, C {}
record B ... implements A ...
non-sealed interface C extends A {}
record D ... implements C ...
class E implements C ...
``` 

I DO expect:

```
A=anyOf(B, C)
```

and I DON'T expect:

```
A=anyOf(B, C)
C=anyOf(D, E /* and what else?*/)
```

In other words, I expect SpringDoc to follow the types "permits" clauses and stop traversing the tree branch as soon as it hits `non-sealed` or `final` type. Subtyping of `non-sealed` types should follow the rules that applied before (so, `C` should behave like unannotated `ObjectPointer` in the initial example).

**Describe alternatives you've considered**

None, doesn't really apply

**Additional context**

- The example is formulated that way (with additional level of indirection), because that's how I've noticed that issue; this ticket will become a bug in the worst case
  - I understand that this isn't the nicest API and definitely not RESTful. Remember that what you see is what I wrote stripped of almost everything (and then I made names generic "Object..." instead of "(term from my domain)...").
- This would require Java version that supports sealed types (so, 15 with preview, or... 16? 17 definitely supports it as stable feature). While keeping low minimum requirements is usually a good idea, this framework is targeted at Spring, which with its new release (3.x) set minimum Java to 17.

**Comment by bnasslahsen** [comment]
@FilipMalczak,

This is a feature nice to have. Can be valide with the branch 2.x only. 
Are you willing to propose a PR for it ?

**Comment by FilipMalczak** [comment]
Willing - yes. Capable? Maybe. Have capacity? Not sure. 

It doesn't seem big, but I wonder how to test it properly and how extensive a suite is required.

**Comment by bnasslahsen** [comment]
This enhancement will be abandoned, as the lack of interest and contributions.

**Comment by spalberg** [comment]
@bnasslahsen this would be a very nice feature for us as we extensively use algebraic data types in our backend and the generated frontend code could take advantage of this by using discriminated unions (TypeScript).

Do you by any chance know a good starting point for the implementation? I might have a stab at it later.

**Comment by be-hase** [comment]
Are there any plans to fix this issue?

**Comment by gsdatta** [comment]
This seems pretty important given that spring boot treats kotlin as a first class citizen and kotlin (and now java) + jackson support this natively

**Comment by Xstoudi** [comment]
Manifesting interest. I'm gonna try to contribute to this =)

**Comment by Xstoudi** [comment]
It seems it's already supported since this year thanks to 3ae776357005f117cab32253d13b6ba5e2a32fce, f4bad4d6fafad86d49b4607d4ce12cc2ab5ca83c and f4e632b5c51c4a700db02179ec44c9b5b39e022e.

Implementation is not exactly the one described by the OP, but I think it gives satisfying results.
