### ISSUE TITLE
Provide Customizers for Path, PathItem, Schemas, (and all OAS components)

### ISSUE THREAD

**Issue by BillyBolton** [springdoc/springdoc-openapi#2029]
**Is your feature request related to a problem? Please describe.**

- A clear and concise description of what the problem is. Ex. I'm always frustrated

Dynamically exposing APIs using an Operation's extensions, as recommended [here](https://github.com/OAI/OpenAPI-Specification/issues/433#issuecomment-1369190714) can be an expensive process since traversing the OAS tree to fetch an Operatoin's parent Path/PathItems can only be done top-down. `Customizers` that springdoc provides, such as the `OperationCustomizer` is a useful way to directly access the Operation components directly prior to the OAS is being generated. Customizers are not supported for every OAS component, however, resulting in expensive processing to hide associated Path, PathItem, Operations, and Schemas as defined by the singular Operation extension.

- What is the actual result using OpenAPI Description (yml or json)?

Should support both yaml and json but no result is needed to describe the output besides being valid.

**Describe the solution you'd like**

- A clear and concise description of what you want to happen.

Customizers should be provided for all OAS components, especially for Path, PathItem, and Schema components.

**Describe alternatives you've considered**

- A clear and concise description of any alternative solutions or features you've
  considered.

I've implemented a solution, that unfortunately I cannot share, by iterating through the entire OAS tree. This process is expensive though and I am looking for a way that is more efficient and consistent with what Springdoc already provides support for.

**Additional context**

- Add any other context or screenshots about the feature request here.

N/A

**Comment by bnasslahsen** [comment]
@BillyBolton,

The existing Customizers are fairly enough.
If you feel you have an added value to propose, feel free to propose a PR.
