### ISSUE TITLE
org.springframework.data.domain.Pageable is not handled correctly

### ISSUE THREAD

**Issue by kaibra** [springdoc/springdoc-openapi#203]
Hey again,

by looking at some other cases I saw, that the `Pageable`class ([`org.springframework.data:spring-data-commons`](https://docs.spring.io/spring-data/data-commons/docs/current/api/)) is not yet handled.

When used, there is a registered [`PageableHandlerMethodArgumentResolver` and `SortHandlerMethodArgumentResolver`](https://docs.spring.io/spring-data/data-commons/docs/current/reference/html/#core.web.basic.paging-and-sorting) which take care of a conversion from Query-Parameters to the `Pageable`-object.

I added a test in my fork https://github.com/kaibra/springdoc-openapi/commit/ee7f874652a7887f5f02be3ea6560307792bcbd5 , `app62_actual.json` shows the current behaviour. 

Regards,

Kai

**Comment by springdoc** [comment]
The support for Pageable of spring-data is added since v1.2.11.
The projects that uses spring-data-rest should add this dependency together with the springdoc-openapi-ui dependency, which defines the correct converter:

```xml
 <dependency>
            <groupId>org.springdoc</groupId>
            <artifactId>springdoc-openapi-data-rest</artifactId>
            <version>1.2.13</version>
 </dependency>
```
Could you please test and leave your feedback?

**Comment by kaibra** [comment]
Ok, I tested it and it worked after I included the `springdoc-openapi-data-rest` dependency (which registers the ModelConverter for Pageable) .

Only detail to mention here maybe:

> The projects that uses spring-data-rest should add this dependency ...

It is possible to only include `spring-data/data-commons` to get support for `Pageable` in Rest-Controllers. This is not related to `spring-data/rest` as far as I see.
