### ISSUE TITLE
Springdoc Swagger UI do not lookup the APIs in either @RestController and @Controller

### ISSUE THREAD

**Issue by TienNLN** [springdoc/springdoc-openapi#2034]
**Describe the bug**

- I've tried to show my APIs which are put in @RestController but the Swagger shows the message "No operations defined in spec!", please help me on this issue. Am I wrong something on setting up the project?

**Screenshots**
![image](https://user-images.githubusercontent.com/44812709/211355856-638db2be-4b86-4155-ab88-28eb7a4e5edb.png)

here is my project: https://github.com/TienNLN/springdoc-centralized-swagger

**Comment by bnasslahsen** [comment]
@TienNLN,

This is the result of your project.  There is no issue here
![image](https://user-images.githubusercontent.com/13404829/216814146-0b765510-543b-476d-89d7-d3db7fb477fb.png)

**Comment by TienNLN** [comment]
I've resolved so it can show successfully

**Comment by 3mingkai** [comment]
> I've resolved so it can show successfully

I have the same issue, could you tell me how do you solve it?
