### ISSUE TITLE
Error executing mvn -pnative native:compile

### ISSUE THREAD

**Issue by admintertar** [springdoc/springdoc-openapi#2039]
**Describe the bug**
Error: Unsupported features in 5 methods
Detailed message:
Error: Detected a ZipFile object in the image heap. A ZipFile object contains pointers to unmanaged C memory and file descriptors, and these resources are no longer available at image runtime.  To see how this object got instantiated use --trace-object-instantiation=java.util.jar.JarFile. The object was probably created by a class initializer and is reachable from a static field. You can request class initialization at image runtime by using the option --initialize-at-run-time=<class-name>. Or you can write your own initialization methods and call them explicitly from your main entry point.
Trace: Object was reached by
  reading field jdk.internal.module.ModuleReferences$JarModuleReader.jf of constant
    jdk.internal.module.ModuleReferences$JarModuleReader@416248d3: jdk.internal.module.ModuleReferences$JarModuleReader@416248d3
  reading field java.util.concurrent.ConcurrentHashMap$Node.val of constant
    java.util.concurrent.ConcurrentHashMap$Node@7063933c: [module org.graalvm.nativeimage.builder, location=file:///D:/development-tool/gr...
  indexing into array java.util.concurrent.ConcurrentHashMap$Node[]@394bcb91: [Ljava.util.concurrent.ConcurrentHashMap$Node;@394bcb91
  reading field java.util.concurrent.ConcurrentHashMap.table of constant
    java.util.concurrent.ConcurrentHashMap@5f60ce50: {[module org.graalvm.sdk, location=jrt:/org.graalvm.sdk]=jdk.internal.module.Sys...
  reading field jdk.internal.loader.BuiltinClassLoader.moduleToReader of constant
    jdk.internal.loader.ClassLoaders$AppClassLoader@649d209a: jdk.internal.loader.ClassLoaders$AppClassLoader@649d209a
  reading static field java.lang.ClassLoader.scl
Error: Detected a ZipFile object in the image heap. A ZipFile object contains pointers to unmanaged C memory and file descriptors, and these resources are no longer available at image runtime.  To see how this object got instantiated use --trace-object-instantiation=java.util.jar.JarFile. The object was probably created by a class initializer and is reachable from a static field. You can request class initialization at image runtime by using the option --initialize-at-run-time=<class-name>. Or you can write your own initialization methods and call them explicitly from your main entry point.
Trace: Object was reached by
  reading field jdk.internal.module.ModuleReferences$JarModuleReader.jf of constant
    jdk.internal.module.ModuleReferences$JarModuleReader@472305ea: jdk.internal.module.ModuleReferences$JarModuleReader@472305ea
  reading field java.util.concurrent.ConcurrentHashMap$Node.val of constant
    java.util.concurrent.ConcurrentHashMap$Node@471a9840: [module org.graalvm.nativeimage.objectfile, location=file:///D:/development-tool...
  indexing into array java.util.concurrent.ConcurrentHashMap$Node[]@394bcb91: [Ljava.util.concurrent.ConcurrentHashMap$Node;@394bcb91
  reading field java.util.concurrent.ConcurrentHashMap.table of constant
    java.util.concurrent.ConcurrentHashMap@5f60ce50: {[module org.graalvm.sdk, location=jrt:/org.graalvm.sdk]=jdk.internal.module.Sys...
  reading field jdk.internal.loader.BuiltinClassLoader.moduleToReader of constant
    jdk.internal.loader.ClassLoaders$AppClassLoader@649d209a: jdk.internal.loader.ClassLoaders$AppClassLoader@649d209a
  reading static field java.lang.ClassLoader.scl
Error: Detected a ZipFile object in the image heap. A ZipFile object contains pointers to unmanaged C memory and file descriptors, and these resources are no longer available at image runtime.  To see how this object got instantiated use --trace-object-instantiation=java.util.jar.JarFile. The object was probably created by a class initializer and is reachable from a static field. You can request class initialization at image runtime by using the option --initialize-at-run-time=<class-name>. Or you can write your own initialization methods and call them explicitly from your main entry point.
Trace: Object was reached by
  reading field jdk.internal.module.ModuleReferences$JarModuleReader.jf of constant
    jdk.internal.module.ModuleReferences$JarModuleReader@74a0a562: jdk.internal.module.ModuleReferences$JarModuleReader@74a0a562
  reading field java.util.concurrent.ConcurrentHashMap$Node.val of constant
    java.util.concurrent.ConcurrentHashMap$Node@62700f35: [module org.graalvm.nativeimage.pointsto, location=file:///D:/development-tool/g...
  indexing into array java.util.concurrent.ConcurrentHashMap$Node[]@394bcb91: [Ljava.util.concurrent.ConcurrentHashMap$Node;@394bcb91
  reading field java.util.concurrent.ConcurrentHashMap.table of constant
    java.util.concurrent.ConcurrentHashMap@5f60ce50: {[module org.graalvm.sdk, location=jrt:/org.graalvm.sdk]=jdk.internal.module.Sys...
  reading field jdk.internal.loader.BuiltinClassLoader.moduleToReader of constant
    jdk.internal.loader.ClassLoaders$AppClassLoader@649d209a: jdk.internal.loader.ClassLoaders$AppClassLoader@649d209a
  reading static field java.lang.ClassLoader.scl
Error: Detected a ZipFile object in the image heap. A ZipFile object contains pointers to unmanaged C memory and file descriptors, and these resources are no longer available at image runtime.  To see how this object got instantiated use --trace-object-instantiation=java.util.jar.JarFile. The object was probably created by a class initializer and is reachable from a static field. You can request class initialization at image runtime by using the option --initialize-at-run-time=<class-name>. Or you can write your own initialization methods and call them explicitly from your main entry point.
Trace: Object was reached by
  reading field jdk.internal.module.ModuleReferences$JarModuleReader.jf of constant
    jdk.internal.module.ModuleReferences$JarModuleReader@15754511: jdk.internal.module.ModuleReferences$JarModuleReader@15754511
  reading field java.util.concurrent.ConcurrentHashMap$Node.val of constant
    java.util.concurrent.ConcurrentHashMap$Node@8919cba: [module com.oracle.svm.svm_enterprise, location=file:///D:/development-tool/graa...
  indexing into array java.util.concurrent.ConcurrentHashMap$Node[]@394bcb91: [Ljava.util.concurrent.ConcurrentHashMap$Node;@394bcb91
  reading field java.util.concurrent.ConcurrentHashMap.table of constant
    java.util.concurrent.ConcurrentHashMap@5f60ce50: {[module org.graalvm.sdk, location=jrt:/org.graalvm.sdk]=jdk.internal.module.Sys...
  reading field jdk.internal.loader.BuiltinClassLoader.moduleToReader of constant
    jdk.internal.loader.ClassLoaders$AppClassLoader@649d209a: jdk.internal.loader.ClassLoaders$AppClassLoader@649d209a
  reading static field java.lang.ClassLoader.scl
Error: Detected a ZipFile object in the image heap. A ZipFile object contains pointers to unmanaged C memory and file descriptors, and these resources are no longer available at image runtime.  To see how this object got instantiated use --trace-object-instantiation=java.util.jar.JarFile. The object was probably created by a class initializer and is reachable from a static field. You can request class initialization at image runtime by using the option --initialize-at-run-time=<class-name>. Or you can write your own initialization methods and call them explicitly from your main entry point.
Trace: Object was reached by
  reading field jdk.internal.module.ModuleReferences$JarModuleReader.jf of constant
    jdk.internal.module.ModuleReferences$JarModuleReader@4568f1f: jdk.internal.module.ModuleReferences$JarModuleReader@4568f1f
  reading field java.util.concurrent.ConcurrentHashMap$Node.val of constant
    java.util.concurrent.ConcurrentHashMap$Node@65559fea: [module org.graalvm.nativeimage.base, location=file:///D:/development-tool/graal...
  indexing into array java.util.concurrent.ConcurrentHashMap$Node[]@394bcb91: [Ljava.util.concurrent.ConcurrentHashMap$Node;@394bcb91
  reading field java.util.concurrent.ConcurrentHashMap.table of constant
    java.util.concurrent.ConcurrentHashMap@5f60ce50: {[module org.graalvm.sdk, location=jrt:/org.graalvm.sdk]=jdk.internal.module.Sys...
  reading field jdk.internal.loader.BuiltinClassLoader.moduleToReader of constant
    jdk.internal.loader.ClassLoaders$AppClassLoader@649d209a: jdk.internal.loader.ClassLoaders$AppClassLoader@649d209a
  reading static field java.lang.ClassLoader.scl

**To Reproduce**

spring-boot 3.0.1
springdoc-openapi-starter-webmvc-ui 2.0.2
win10-22H2
 GraalVM EE 22.3.0

Execute mvn -Pnative spring-boot:run and stop the program, then execute mvn -Pnative native:compile

Already turned on 

springdoc:
  enable-native-support: true

demo :  https://github.com/admintertar/demo-aot

**Comment by bnasslahsen** [comment]
@admintertar,

Not reproducible.
This error is not linked to `springdoc-openapi `directly.
Check your GraalVM settings configuration.
