### ISSUE TITLE
@ResponseBody now required

### ISSUE THREAD

**Issue by wuttke** [springdoc/springdoc-openapi#2041]
In version 1.4.3, this method got an entry in Swagger.

```
@Controller
public class EncounterTypeController {

	@GetMapping("encounterTypes")
	public Mono<ResponseEntity<List<EncounterType>>> loadEncounterTypes(Pageable pageable) {
```

In version 1.6.14, it does not anymore.

Adding `@ResponseBody` fixes the issue for 1.6.14 - do I need to add this annotation to all my controllers / methods?
Originally, I did the upgrade to be able to use `@PageableAsQueryParam` and `@ParameterObject`
This code works as I want it to do:

	@GetMapping("encounterTypes")
	@PageableAsQueryParam
	@ResponseBody
	public Mono<ResponseEntity<List<EncounterType>>> loadEncounterTypes(@ParameterObject Pageable pageable) {

I think `ResponseEntity` implies `@ResponseBody`.

**Comment by bnasslahsen** [comment]
@wuttke

This is answered here: https://github.com/springdoc/springdoc-openapi/issues/516
