### ISSUE TITLE
 Security is not working properly with multiple GroupedOpenApi

### ISSUE THREAD

**Issue by MichielDx** [springdoc/springdoc-openapi#2043]
> The issue you are reporting here is not related directly to springdoc-openapi project.
> You can check the generated OpenAPI spec, where you will find the correct securtiy schemes are present, but it's more a GUI issue.
> 
> Your issue is more related to the [swagger-ui](https://github.com/swagger-api/swagger-ui). While switching, the popup seems only to show up when will refresh the page.
> 
> And there are already some existing issues that we are following: 
> 
> - https://github.com/swagger-api/swagger-ui/issues/6537
> - https://github.com/swagger-api/swagger-ui/issues/5404
> - https://github.com/swagger-api/swagger-ui/issues/5540
> 
> Once they are fixed, the new version will be added to springdoc-openapi.
> 
> _Originally posted by @bnasslahsen in https://github.com/springdoc/springdoc-openapi/issues/915#issuecomment-719498832_

            
In which version of springdoc-openapi-ui is this fixed? It's not working in 1.4.4
Or is there a property that I should/can set to fix this?

**Comment by bnasslahsen** [comment]
@MichielDx,

Go to https://springdoc.org/ and use the last stable version.
