### ISSUE TITLE
Redirecting to swagger-ui/index.html

### ISSUE THREAD

**Issue by jorozcof** [springdoc/springdoc-openapi#2045]
Hi.!
I am using Spring Webflux with Spring Framework Boot 3.0.1
How can I prevent swagger from redirecting me to swagger-ui/index.html.

I have set in my application.properties the following: 

- springdoc.swagger-ui.path=/api-docs/
- springdoc.webjars.prefix=/ui

so I can directly access http://localhost:5001/api-docs/ui but it redirects me to http://localhost:5001/api-docs/ui/swagger-ui/index.html

How can I avoid this redirect and directly access http://localhost:5001/api-docs/ui/

Is the redirection normal? Is there any way to avoid it?

**Comment by bnasslahsen** [comment]
@jorozcof,

Redirection is normal.
Alternatively, you can simply use  http://localhost:5001/api-docs/ui/swagger-ui/index.html as default, if you don't want to get access through redirects.

**Comment by g3t3vi7** [comment]
I'm facing the same issue. I went to the springdoc-openapi-ui source code (version 1.6.8). I don't know if this is a bug, but when we define springdoc.swagger-ui.path. It will redirect to the default swagger-ui index HTML. You can refer to this class, SwaggerWelcomeWebMvc#redirectToUi. It consumes SWAGGER_UI_PATH, which is the property that we set. Then it redirects to /swagger-ui/index.html in  AbstractSwaggerWelcome#getSwaggerUiUrl constant SWAGGER_UI_URL.

So what I did is a workaround, which I implemented WebMvcConfigurer#addViewControllers to redirect to the custom swagger page.

**Comment by alexmarques** [comment]
Hi @g3t3vi7 could you share the implementation? im having the same problem. Thanks!
