### ISSUE TITLE
swagger-ui.html not loading on JBOSS EAP 7

### ISSUE THREAD

**Issue by filten** [springdoc/springdoc-openapi#2049]
When I deploy two Spring Boot Web applications to JBOSS EAP 7.2.6, both using springdoc-openapi-ui but with different versions (say 1.6.14 & 1.6.9), then swagger-ui.html only works for the application which has been deployed first.

I have tried with different versions of springdoc-openapi-ui and Spring Boot but the only change that triggers the problem is when I do not use the same version of springdoc-openapi-ui in both applications (sic).

For the application deployed last I get an error page (whitelabel error page).

I am able to access /app-1/swagger-ui.html for the first application and then input the api for the second application, which will then show correctly.

I would expect that /app-2/swagger-ui.html also worked.

I am using spring-boot-starter-web from Spring Boot 2.7.7 and I am building WAR files to deploy.

**Comment by bnasslahsen** [comment]
see https://springdoc.org/#integration-with-wildfly
