### ISSUE TITLE
annotation to ignore some field of model

### ISSUE THREAD

**Issue by dario-frongillo** [springdoc/springdoc-openapi#205]
Hi,
is possible to generate openapi doc that ignore some field of a model ?
In other words:  i have a class ModelX with field A, B, C .. i want an open api docs with only docs for ModelX  that report only field A, B. Is it possible ? Maybe an annotation to ignore some field
thanks
ciao
dario

**Comment by springdoc** [comment]
Hi, 

 You can use the following annotation on the top of the field C that you want to hide: 

- `@Schema(hidden = true)`

**Comment by patilvamsi** [comment]
how to hide/ignore the RepresentationModel links in the model.

**Comment by lucassklp** [comment]
> how to hide/ignore the RepresentationModel's links in the model.

I am facing the exact same problem. If I find something I put here

**Comment by patilvamsi** [comment]
> > how to hide/ignore the RepresentationModel's links in the model.
> 
> I am facing the exact same problem. If I find something I put here

I extended RepresentationModel to a class and used @JsonIgnoreProperties
