### ISSUE TITLE
ClassGraph raised OOM error in my project

### ISSUE THREAD

**Issue by hantsy** [springdoc/springdoc-openapi#2050]
My project is based on Spring Boot 3/R2dbc + Kotlin/KotlinCoroutines + Java 17(set Language Level to 17).  I am using the latest 2.0.2 in my project.

The source codes archived 100k lines now. 

In the newest feature branch, I always encountered an OutOfMemoery error when running tests on Github Actions, even I used a custom larger runner with 4 core + 16G and increased the Gralde jvm args to use a larger heap size(4G, 8G, 12G) to build the project. It is 100% failed due to the OOM error.

There is a question I posted on StackOverFlow, https://stackoverflow.com/questions/75169922/outofmemoryerror-in-gradle-springboot-kotlin-coroutines-project

Today I tried to remove Spring Doc config, and spring-doc dep, it works. **And the build progress is shorten to 75%, and saved 2 min.**

I am not sure why if ClassGraph is a must for springdoc, Spring itself scan all beans at runtime. Why we need another scanner in the background and finally kill the application.

**Comment by hantsy** [comment]
I tried to add global packageToScan to the *applicaiton.properies*, still failed of OOM.

A question here, I have disabled spring doc(springdoc.api-docs and springdoc.swagger-ui) by default, it sill failed of OOM(caused by ClassGraph), why it still scan the classes info in the background?

**Comment by hantsy** [comment]
Today I tried to add `packageToScan` to every `groupedOpenAPI` beans, there are several  `GroupedOpenAPI` beans in our project, still encountered the same error(OOM).

**Comment by hantsy** [comment]
I wonder why ClassGraph is scanning class infos in the background even I disable springdoc.

**Comment by bnasslahsen** [comment]
@hantsy,

This is `ClassGraph` question. 
It should be addressed here instead https://github.com/classgraph/classgraph/issues

**Comment by hantsy** [comment]
@bnasslahsen I have discussed with the ClassGraph guys firstly, they confirmed it is related to the project and how to use it. So I created an issue here.

Obviously, I disabled springdoc in applicaiton.proerties, the ClassGraph still scanned at every Spring context setup phase in the tests. This is unreasonable.

And setup scan scopes to every grouped OpenAPI bean, it also does not work.

**Comment by hantsy** [comment]
> In the springdoc code, there are no explicit calls to ClassGraph.

So it can be removed?

But from the project dependency tree, spring doc depends on it directly.

**Comment by bnasslahsen** [comment]
@hantsy,

Classgraph is required by `webjars-locator-core`
<img width="560" alt="image" src="https://user-images.githubusercontent.com/13404829/216934038-1a9a1f73-ece5-4cd2-aa86-f779a8dee0b1.png">

This dependency is only required for the UI to hide the UI version from the URL.

Basically, if you don't reference the SWAGGER-UI, it will not be added.
You can exclude `org.webjars:webjars-locator-core` from the dependencies, and try:
`springdoc.enable-native-support=true`

You will see in the URL, the version of the swagger-ui.

If you are still having issues, you will need to Provide a [Minimal, Reproducible Example - with HelloController](https://stackoverflow.com/help/minimal-reproducible-example) that reproduces the problem

**Comment by hantsy** [comment]
Of course I would like provide a small example project to produce the errors, but I found it is only occurred when there are a bundle of classes existed in the project.

I noticed there is a PR to review webjar-locator-core #2173, hope it resolve my issue.

**Comment by bnasslahsen** [comment]
@hantsy,

You can try with the latest SNAPSHOT and provide your feedback.
