### ISSUE TITLE
Method level @Tag overwrites default `-controller` tag

### ISSUE THREAD

**Issue by braunsonm** [springdoc/springdoc-openapi#2056]
**Describe the bug**

By default springdoc-openapi will tag endpoints with the controller they come from, for example `example-controller`. When you add your own tag to a method, I would have expected the additional `@Tag` to be merged, but instead it overwrites the controller tag.

**To Reproduce**

```
@RestController
@RequestMapping("/api/v1/hello")
  public class HelloController {

  @GetMapping(produces = "application/json")
  @Operation(
      description = "Get a hello message",
      tags = {"SomeOtherTag"},
      responses = {
          @ApiResponse(responseCode = "200", description = "A hello message"),
      }
  )
  public ResponseEntity<String> getHelloMessage() {
      return ResponseEntity.ok("Hello World");
  }
}
```

**Expected behavior**

API is tagged as both `hello-controller` and `SomeOtherTag`. 

**Actual behavior**

API is tagged just as `SomeOtherTag`

**Context**

I'm not sure if this is intended behavior, but if it is would it be possible to put this behavior under a property for configuration? I have a use case where I want this API to still remain under the controller specific tagging but add an additional logical grouping for the API endpoint.

**Comment by bnasslahsen** [comment]
@braunsonm,

This is not the default behaviour. You are asking for something custom.
By default, auto-tag-classes will work if there are no `Tags` provided by the developer.
If any annotation provided, it will be used instead.

You should use Disable auto-tag-classes options. 
The details are available in the documentation: https://springdoc.org/
