### ISSUE TITLE
Generate object examples by attribute examples automatically

### ISSUE THREAD

**Issue by tdittmann** [springdoc/springdoc-openapi#2057]
Is it possible to generate the object examples automatically by the attributes of the object? Or do i need to add examples for every single object?

Example object:
```
@Schema(title = "MyCustomObject")
public class MyCustomObject {
    @Schema(description = "The first attribute.", example = "Hello World")
    private String attribute1;


    @Schema(description = "The second attribute.", example = "Hello Springdoc")
    private String attribute2;
}
```

An object example can be generated automatically on the basis of the attribute examples. Is this already supported?

**Comment by bnasslahsen** [comment]
This is a `swagger-annotations` question.
See the guidance how to use github issues: https://github.com/springdoc/springdoc-openapi/blob/master/CONTRIBUTING.adoc

You can use `ExampleObject`.See the project tests for more details.
