### ISSUE TITLE
Server servlet context path omitted when run with X-Forwarded-Prefix 

### ISSUE THREAD

**Issue by heuristicservices** [springdoc/springdoc-openapi#2058]
**Describe the bug**

The server servlet context path is omitted when Springdoc is proxied and an `X-Forwarded-Prefix` header is present.

Please see the minimum working example here https://github.com/heuristicservices/springdoc-context-path

A debug port is mapped to localhost `5050` to the Spring Boot application when running the Java docker container.

**To Reproduce**

1. Run Spring Boot application jar from local machine:

       java -jar target/springdoc-context-path-1.0-SNAPSHOT.jar
2. Navigate to `http://localhost:8080/petstore/v3/api-docs/swagger-config` to view `petstore` server context prepended to URL:

       {"configUrl":"/petstore/v3/api-docs/swagger-config","oauth2RedirectUrl":"http://localhost:8080/petstore/swagger-ui/oauth2-redirect.html","url":"/petstore/v3/api-docs","validatorUrl":""}
3. Stop application and run `docker compose up` which uses nginx `X-Forwarded-Prefix` header `/api`.
4. Navigate to `http://localhost:8080/api/petstore/v3/api-docs/swagger-config` which the application correctly routes. This displays the following:

       {"configUrl":"/api/v3/api-docs/swagger-config","oauth2RedirectUrl":"http://localhost:8080/api/swagger-ui/oauth2-redirect.html","url":"/api/v3/api-docs","validatorUrl":""}
5. The application prepends the URL with the `X-Forwarded-Prefix` value, however the server context is now missing within the `JSON` response.

- What version of spring-boot you are using?

*2.7.1*

- What modules and versions of springdoc-openapi are you using? 

*springdoc-openapi-ui 1.6.14*  *springdoc-openapi-security 1.6.14*

- Provide with a sample code (HelloController) or Test that reproduces the problem

Please see the minimum working example here https://github.com/heuristicservices/springdoc-context-path

**Expected behavior**

Navigating to the nginx proxied application at `http://localhost:8080/api/petstore/v3/api-docs/swagger-config` should display the `X-Forwarded-Prefix` `/api` in addition to the server servlet context path `petstore`:

           {"configUrl":"/api/petstore/v3/api-docs/swagger-config","oauth2RedirectUrl":"http://localhost:8080/api/petstore/swagger-ui/oauth2-redirect.html","url":"/api/petstore/v3/api-docs","validatorUrl":""}

**Comment by bnasslahsen** [comment]
@heuristicservices,

This is the fix for your code:
`proxy_set_header X-Forwarded-Prefix $http_x_forwarded_prefix;`

![image](https://user-images.githubusercontent.com/13404829/217376319-87a5bad1-9848-45f7-9f1e-a004be6755d3.png)

**Comment by joaonatalio** [comment]
@bnasslahsen even with that fix proposal its not working. 

I was about to report the same issue for spring-boot `3.0.2` and springdoc-openapi-starter-webmvc-ui `2.0.2` and came across this post.
