### ISSUE TITLE
@Hidden Not function in @RestControllerAdvice

### ISSUE THREAD

**Issue by jorozcof** [springdoc/springdoc-openapi#2060]
**Describe the bug**

-I have a class that customizes the response of each request. But when I consult the documentation in json, it throws me the following exception:
timestamp": "2023-01-30 11:34:16",
"status": "INTERNAL_SERVER_ERROR",
"message": "class app.dto.SuccessResponse cannot be cast to class java.lang.String (app.dto.SuccessResponse is in unnamed module of loader 'app'; java.lang.String is in module java.base of loader 'bootstrap')"

I use a wrapper to perform a response in a more optimized way.

**To Reproduce**

- What version of spring-boot you are using? **Spring Boot 3.0.1**
- What modules and versions of springdoc-openapi are you using? **springdoc-openapi-starter-webmvc-ui', version: '2.0.2'**

**Expected behavior**

- Hide the @RestControllerAdvice class from me
- 
**Screenshots**
My class RestoControllerAdvince
![image](https://user-images.githubusercontent.com/115189644/215552768-9732c5bd-f9bc-4cc4-b0d9-65bbc4c5b65d.png)

Error response:
![image](https://user-images.githubusercontent.com/115189644/215553290-617bc845-4b4a-4037-a3da-7e345815a7ff.png)

How can I solve and prevent the swagger documentation from documenting that class for me?

**Comment by bnasslahsen** [comment]
The @Hidden annotation on exception handler methods, is considered when building generic (error) responses from @ControllerAdvice exception handlers.

See documentation: https://springdoc.org/

If you are still having an issue, Provide a [Minimal, Reproducible Example - with HelloController](https://stackoverflow.com/help/minimal-reproducible-example) that reproduces the problem
