### ISSUE TITLE
OperationCustomizer is not working with Spring Data REST

### ISSUE THREAD

**Issue by golabk** [springdoc/springdoc-openapi#2062]
**Describe the Feature**

Operations exported by @RepositoryRestResource is not handled by OperationCustomizer. They cannot be customized.

**To Reproduce**
1. Create the entity
`
@Entity
public class MyEntity {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
}
`
3. Create spring data jpa repository  wtih @RepositoryRestResource annotation
`
@RepositoryRestResource
public interface MyRepository extends JpaRepository<MyEntity, Long> {
}
`
5. Create operation customizer
`
@Bean
    OperationCustomizer operationCustomizer() {
        return (operation, handlerMethod) -> {
            log.info("operation:" + operation.getOperationId());
            return operation;
        };
    }
`
6. Run the application and see the logs. There is no Spring Data REST operations in logs.

- What version of spring-boot you are using?
3.0.2
- What modules and versions of springdoc-openapi are you using?
2.0.2

**Expected behavior**
OperationCustomizer capability apply to all Spring Data REST methods.

**Additional context**
Methods exported by @RepositoryRestResource cannot be customized, but methods exported by @RepositoryRestController or @BasePathAwareController are handled by OperationCustomizer.

**Comment by bnasslahsen** [comment]
@golabk,

This is an enhancement request!
There are no `Customizers` supported for spring-data-rest

**Comment by bnasslahsen** [comment]
@golabk,

`DataRestRouterOperationCustomizer` is now introduced for this purpose.
