### ISSUE TITLE
@JsonView not works

### ISSUE THREAD

**Issue by xiemeilong** [springdoc/springdoc-openapi#2064]
**Describe the bug**

- @JsonView not works on parameters

**To Reproduce**
```
@Data
public class Foo {
    private Long id;

    @JsonView(Views.Value.class)
    private String value;

}
```
```
  @PostMapping
    public Foo create(
            @RequestBody @JsonView(Views.Value.class) Foo value) {
       return value;
    }
```

**Expected behavior**

- The id field should not be in Foo_Value schema.

**Additional context**
springdoc_version  2.0.2
spring boot version 3.0.2

**Comment by bnasslahsen** [comment]
@xiemeilong,

Your code is not complete. You are missing at leat the views definition.
Provide the link to a github repo with a [Minimal, Reproducible Example - with HelloController](https://stackoverflow.com/help/minimal-reproducible-example) that reproduces the problem.

I am closing this ticket and it can be reopened if you update it with the relevant information.
