### ISSUE TITLE
Oauth2 Authorize button not display scopes

### ISSUE THREAD

**Issue by suoyunqing** [springdoc/springdoc-openapi#2065]
**Describe the bug**
Our project use springdoc-openapi-starter-webmvc-ui:2.0.2 with springboot3 and use oauth2 implicit flow. Everything work fine but got one issue:
<img width="1568" alt="Screen Shot 2023-02-09 at 11 16 08 AM" src="https://user-images.githubusercontent.com/59526131/217709382-95b157a5-3e40-46d6-8c54-01963f6bb939.png">
In the swagger UI, we have two buttons to do oauth2 authentication. Like shown on the picture, one I call it primary button, the other I call it sub button.

When I click primary button, it displays client_id and scopes and can finish oauth2 authentication successfully :
<img width="654" alt="Screen Shot 2023-02-09 at 11 22 07 AM" src="https://user-images.githubusercontent.com/59526131/217709754-ea41fd54-5c64-418a-8fb0-79967311a4c8.png">

However, when I click sub button, it only displays client_id, but not display scopes. And we will get alerts of "The request body must contain the following parameter: 'scope'" when do the oauth2 authhorization.

<img width="650" alt="Screen Shot 2023-02-09 at 11 30 30 AM" src="https://user-images.githubusercontent.com/59526131/217710941-ebabf3a1-8894-4e46-af59-95c1cce93b31.png">

**Expected behavior**

We expect when click the sub button, it can also display scopes and send oauth2 request with scopes parameters.

**Comment by bgbglll** [comment]
![捕获](https://user-images.githubusercontent.com/11627429/217779027-8abc4250-b453-4a56-8076-85b18fcce894.PNG)
You need to add scopes in your @OAuthFlow.

**Comment by suoyunqing** [comment]
> ![捕获](https://user-images.githubusercontent.com/11627429/217779027-8abc4250-b453-4a56-8076-85b18fcce894.PNG) You need to add scopes in your @OAuthFlow.

<img width="1356" alt="Screen Shot 2023-02-10 at 10 27 53 AM" src="https://user-images.githubusercontent.com/59526131/217985027-06fe6294-da81-42f9-aff0-76457a1b6b38.png">
You see, scope is already configed and the primary button can fetch the scopes. Only the sub button fails to fetch

**Comment by suoyunqing** [comment]
@bnasslahsen  Hey, bro, I see you set it as invalid and closed the issue. But can you check my following reply a little bit?

**Comment by bnasslahsen** [comment]
@suoyunqing,

The springdoc tests are working.
You might be having issues with the swagger-ui.

You can add a minimal reproducible sample and would be happy to help

**Comment by suoyunqing** [comment]
> @suoyunqing,
> 
> The springdoc tests are working. You might be having issues with the swagger-ui.
> 
> You can add a minimal reproducible sample and would be happy to help

sample:  git@github.com:suoyunqing/springdoc-openapi-demo.git
yes, we also think that the issue happens on the swagger-ui. Swagger is also part of springdoc-openapi-starter-webmvc-ui, right, and it it reasonable to put up the issue here?

**Comment by bnasslahsen** [comment]
@suoyunqing,

springdoc-openapi is responsible of generating the OpenAPI Spec.
Are you having issues with the generated OpenAPI spec?

For the swagger-ui, issues needs to be logged here: https://github.com/swagger-api/swagger-ui/issues

**Comment by suoyunqing** [comment]
Thank you. Because I only import implementation 'org.springdoc:springdoc-openapi-starter-webmvc-ui:2.0.2', so I put up the issue here.
