### ISSUE TITLE
Server servlet context path omitted when run with X-Forwarded-Prefix

### ISSUE THREAD

**Issue by joaonatalio** [springdoc/springdoc-openapi#2068]
**Describe the bug**

The server servlet context path is omitted when Springdoc is running behind a reverse proxy and an `X-Forwarded-Prefix` header is present. The issue was originally reported in https://github.com/springdoc/springdoc-openapi/issues/2058 but dismissed, lacking some clarity in the reproduction.
Please see the new working example in https://github.com/joaonatalio/springdoc-context-path-bug demonstrating the issue for `spring-boot-parent:3.0.2` and `springdoc-openapi-starter-webmvc-ui:2.0.2`.

In `application.yml` we have `servlet.forward-headers-strategy: framework` defined so that our app processes the incoming `X-Forwarded-*` from our reverse proxy, like it's suggested in springdoc's 2.x FAQ.

In our case we defined the following `springdoc` config to show the problematic redirect behaviour more clearly:

```
springdoc:
  api-docs:
    path: /swagger/api-docs
  swagger-ui:
    path: /swagger/swagger-ui.html
```

**To Reproduce**
(For `spring-boot:3.0.2` and `springdoc-openapi-starter-webmvc-ui:2.0.2`)

1. Run Spring Boot application jar from local machine: `java -jar target/springdoc-context-path-1.0-SNAPSHOT.jar`

2. Navigate to `http://localhost:8080/petstore/swagger/swagger-ui.html` to view petstore's swagger-ui, all resources are loaded correctly since it redirects the initial request to the expected url `http://localhost:8080/petstore/swagger/swagger-ui/index.html`.

3. Stop application and run `docker compose up` which uses nginx `X-Forwarded-Prefix` header with fixed `/api` value, just for demo purposes.

4. Navigate to `http://localhost:8080/api/petstore/swagger/swagger-ui.html`. We're redirected to `http://localhost:8080/api/swagger/swagger-ui/index.html`, taking into account the passed `X-Forwarded-Prefix` header, but omitting the servlet context path entirely.

**Expected behavior**

In step 4) the `swagger-ui.html` should redirect to `http://localhost:8080/api/petstore/swagger/swagger-ui/index.html`, taking into account the passed `X-Forwarded-Prefix` and the servlet context path.

**Comment by bnasslahsen** [comment]
@joaonatalio,

It's all about your settings ...And your description...
You should just pass well `X-Forwarded-Prefix` ...

For https://github.com/springdoc/springdoc-openapi/issues/2058 the answer is correct, as he was just expecting the access to [swagger-config](http://proxy/api/petstore/v3/api-docs/swagger-config)

For your case, this is the fix, because your are looking for. You want also display the UI.
![image](https://user-images.githubusercontent.com/13404829/217950231-277c4ae3-845f-484d-8cfb-141b803793cb.png)

**Comment by joaonatalio** [comment]
@bnasslahsen the point of the example was to forward only the `/api` prefix in `X-Forwarded-Prefix` which is perfectly valid,  `petstore` is the name of servlet context and part of the original url and, as such, it should be handled by springdoc as expected... Given your suggestion, the expected url to be forwarded to would be `http://localhost:8080/api/petstore/petstore/swagger/swagger-ui/index.html` **if this issue didn't exist**. 
To be fair I'm not sure if the issue relies in springdoc or swagger-ui itself, but it definitely is there, but I don't have the full context and require a deeper analysis on the team's part.

If you still don't get mine and @heuristicservices 's point, I would kindly suggest to get an extra reviewer here.

**Comment by bnasslahsen** [comment]
@joaonatalio,

If you want forward `/api` only, then review your nginx rules.
You got your answer to have the expected result ...

The problem, is you are setting wrong X-Forwarded-Prefix. I hope you will understand.
We estimate, there will be no more efforts spent on this ticket.
