### ISSUE TITLE
java.lang.NoSuchMethodError: void org.springdoc.ui.AbstractSwaggerWelcome.<init> only during text execution

### ISSUE THREAD

**Issue by bisegni** [springdoc/springdoc-openapi#2069]
**Describe the bug**

I have a project based on spring boot 3.0.2, and i'm trying to use sprigdoc for documentation. During the normal application execution al work well, either the rest api and the documentation. The problem is that when i run the test, in this case i receive a log stack trace but the base problem is the whichone below:
`java
Caused by: java.lang.NoSuchMethodError: 'void org.springdoc.ui.AbstractSwaggerWelcome.<init>(org.springdoc.core.properties.SwaggerUiConfigProperties, org.springdoc.core.properties.SpringDocConfigProperties, org.springdoc.core.properties.SwaggerUiConfigParameters)'
	at org.springdoc.webmvc.ui.SwaggerWelcomeCommon.<init>(SwaggerWelcomeCommon.java:54)
	at org.springdoc.webmvc.ui.SwaggerWelcomeWebMvc.<init>(SwaggerWelcomeWebMvc.java:77)
	at org.springdoc.webmvc.ui.SwaggerConfig.swaggerWelcome(SwaggerConfig.java:83)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:139)
`

my build.gradle is:
`
plugins {
    id 'java'
    id 'org.springframework.boot' version '3.0.2'
    id 'io.spring.dependency-management' version '1.1.0'
    id 'com.adarshr.test-logger' version '3.2.0'
    id 'jacoco'
}

group = 'edu.stanford.slac'
version = '1.0.0'
sourceCompatibility = '19'

configurations {
    compileOnly {
        extendsFrom annotationProcessor
    }
}

repositories {
    mavenCentral()
}

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-test',
            'org.springframework.boot:spring-boot-starter-web',
            'org.springframework.boot:spring-boot-starter-data-mongodb',
            'org.springframework.boot:spring-boot-starter-actuator',
            'org.springdoc:springdoc-openapi-starter-webmvc-ui:2.0.2',
            'org.springdoc:springdoc-openapi-starter-webflux-ui:2.0.2',
            'org.springdoc:springdoc-openapi-webflux-ui:1.6.14',
            'javax.annotation:javax.annotation-api:1.3.2',
            'io.swagger.core.v3:swagger-annotations:2.2.8',
            'org.mapstruct:mapstruct:1.5.3.Final',
            'io.minio:minio:8.2.2'

    compileOnly 'org.projectlombok:lombok'
    annotationProcessor 'org.projectlombok:lombok'
    annotationProcessor 'org.mapstruct:mapstruct-processor:1.5.3.Final'

    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testImplementation 'org.awaitility:awaitility:4.0.3'
}

tasks.named('test') {
    useJUnitPlatform()
}

jacoco {
    reportsDirectory = layout.buildDirectory.dir('coverage')
}

test {
    finalizedBy jacocoTestReport // report is always generated after tests run
}

jacocoTestReport {
    dependsOn test // tests are required to run before generating the report
    reports {
        xml.enabled true
        csv.enabled true
        html.enabled true
    }
}

testlogger {
    theme 'standard'
    showExceptions true
    showStackTraces true
    showFullStackTraces false
    showCauses true
    slowThreshold 2000
    showSummary true
    showSimpleNames false
    showPassed true
    showSkipped true
    showFailed true
    showOnlySlow false
    showStandardStreams false
    showPassedStandardStreams true
    showSkippedStandardStreams true
    showFailedStandardStreams true
    logLevel 'lifecycle'
}

`

**Comment by bnasslahsen** [comment]
Remove `swagger-annotations` from your dependencies.

Try  at least to Use basic github.com formatting when you want write an issue
