### ISSUE TITLE
Default description on RequestBody annotation

### ISSUE THREAD

**Issue by kfirfer** [springdoc/springdoc-openapi#207]
Hello, 

"@io.swagger.v3.oas.annotations.parameters.RequestBody" annotation overridden default value

That overridden occurs by springdoc, you can see it here:
https://github.com/springdoc/springdoc-openapi/blob/master/springdoc-openapi-common/src/main/java/org/springdoc/core/RequestBodyBuilder.java#L48

I dont really think it is should be there, the annotation itself have a default value already

Thanks

**Comment by springdoc** [comment]
Hi @kfirfer, 

 You are right. This will be removed for the next release: v1.2.14;
