### ISSUE TITLE
@JSONVIEW not works 

### ISSUE THREAD

**Issue by xiemeilong** [springdoc/springdoc-openapi#2072]
**Describe the bug**
@JSONVIEW not works 

**To Reproduce**

[code](https://github.com/xiemeilong/springdoc-bugs)

**Expected behavior**

The id field should not be in Foo_Value schema.

**Screenshots**
![image](https://user-images.githubusercontent.com/2681638/218377256-fd9db177-bb3e-4f6e-a29e-3f6e44703bf1.png)
**Additional context**
springdoc_version 2.0.2
spring boot version 3.0.2

**Comment by uc4w6c** [comment]
An issue was created in swagger-core.
https://github.com/swagger-api/swagger-core/issues/4127

**Comment by bnasslahsen** [comment]
This ticket will be closed and we will follow the swagger-core issue instead.
