### ISSUE TITLE
Spring 3.0 does not support javadoc

### ISSUE THREAD

**Issue by xuxiaowei-com-cn** [springdoc/springdoc-openapi#2077]
https://github.com/xuxiaowei-cloud/xuxiaowei-cloud-next.git

**Comment by xuxiaowei-com-cn** [comment]
Interfaces and fields can be displayed

**Comment by xuxiaowei-com-cn** [comment]
![image](https://user-images.githubusercontent.com/46893436/219070437-3b106a8d-b2cd-4742-ad51-047cb9f76379.png)

**Comment by xuxiaowei-com-cn** [comment]
![image](https://user-images.githubusercontent.com/46893436/219070742-f68629c6-8ea7-4a3d-aa05-f6d18595bd6e.png)

**Comment by bnasslahsen** [comment]
@xuxiaowei-com-cn, 

You should either use v1 or v2 of springdoc-openapi.
Do not mix both.

**Comment by xuxiaowei-com-cn** [comment]
org.springdoc:springdoc-openapi-javadoc has not released 2. x.
org.springdoc:springdoc-openapi-security has not released 2. x.
https://s01.oss.sonatype.org/content/repositories/snapshots/org/springdoc/springdoc-openapi-javadoc/
![image](https://user-images.githubusercontent.com/46893436/219093539-809cde38-3fb4-43df-a8ba-df9a9ad274f9.png)

**Comment by xuxiaowei-com-cn** [comment]
https://s01.oss.sonatype.org/content/repositories/snapshots/org/springdoc/springdoc-openapi-security/
![image](https://user-images.githubusercontent.com/46893436/219094153-11439bc0-610b-4344-bc22-4661832c169a.png)

**Comment by bnasslahsen** [comment]
@xuxiaowei-com-cn,

In v2 - you dont need these dependencies
Please read the doc:
- https://springdoc.org/v2

You have demos:
- https://github.com/springdoc/springdoc-openapi-demos.git
