### ISSUE TITLE
Springdoc should not use LocalVariableTableParameterNameDiscoverer

### ISSUE THREAD

**Issue by rasifix** [springdoc/springdoc-openapi#2078]
Springdoc v2 still depends on deprecated LocalVariableTableParameterNameDiscoverer. As a result, Spring Boot 3.x applications log the following:

`Using deprecated '-debug' fallback for parameter name resolution. Compile the affected code with '-parameters' instead ...`

Springdoc should use the DefaultParameterNameDiscoverer instead.

I'll write a pull request if you agree that this is something that should be fixed in the way I have described it above.

**Comment by bnasslahsen** [comment]
see https://github.com/springdoc/springdoc-openapi/issues/2028

**Comment by rasifix** [comment]
can you show me the commit where you have dropped usage of LocalVariableTableParameterNameDiscoverer. I still see it used on master as well as 2.x branch, which will still produce the warning in the log.

**Comment by bnasslahsen** [comment]
@rasifix,

which version are you using ?

**Comment by rasifix** [comment]
@bnasslahsen - I must have been fooled by the Github search. The code on 2.x branch looks better. I am using 2.0.2 at the moment and will wait for 2.0.3, which contains the fix (?). If it won't work I'll report back.

**Comment by bnasslahsen** [comment]
2.0.2 already ships the fix

**Comment by rasifix** [comment]
oh, perfect. I have just validated and yes, 2.0.2 does no longer produce the warnings. I guess I saw the warnings on a version of the software still running 2.0.0.
