### ISSUE TITLE
Schema replacement changing type from string to object

### ISSUE THREAD

**Issue by jacob-swanson** [springdoc/springdoc-openapi#2079]
**Describe the bug**

I am attempting to fix the `OffsetTime` type in a schema. By default, it is introspecting the `OffsetTime` type instead of it being a primitive string, but I'm providing a replacement type like so: 
```java
SpringDocUtils.getConfig()
    .replaceWithSchema(OffsetTime.class, new StringSchema().format("time"));
```

However, on my object's properties, the type for the `OffsetTime` property is `object` instead of `string`.
Actual:
```json
          "time": {
            "type": "object",
            "format": "time"
          }
```
Expected:
```json
          "time": {
            "type": "string",
            "format": "time"
          }
```

**To Reproduce**

1. Create a class that has an `OffsetTime` property, and return it from an endpoint.
2. Configure Spring Doc to replace `OffsetTime` with a `StringSchema`.
3. Get the Open API schema.
4. See the type for the time property is `object`, when it should be `string`.

- What version of spring-boot you are using? 3.0.2
- What modules and versions of springdoc-openapi are you using? org.springdoc:springdoc-openapi-starter-webmvc-api:2.0.2

**Expected behavior**

The replacement schema should not have its type changed from `string` to `object`.

**Additional context**

I did some digging, and it looks like this change is the culprit:
https://github.com/springdoc/springdoc-openapi/commit/b274a0e517cc73c3f7a809f48b9b3771cf840308#diff-931d4bb6f2f18da311883e3b678418f90cccb6360c8dcc8e50e4578aa75282a7

The return value of this statement turns the `StringSchema` class into a `JsonSchema` in our application.
```java
return springDocObjectMapper.jsonMapper()
		.readValue(springDocObjectMapper.jsonMapper().writeValueAsString(modelToSchemaMap.get(cls)), new TypeReference<Schema>() {});
```

**Comment by bnasslahsen** [comment]
Not reproducible:

<img width="248" alt="image" src="https://user-images.githubusercontent.com/13404829/220882129-9bae3e3f-7700-4cf6-af09-c329b16fc2ea.png">

Try providing a Provide a [Minimal, Reproducible Example - with HelloController](https://stackoverflow.com/help/minimal-reproducible-example) that reproduces the problem
