### ISSUE TITLE
Parameter name disappeared

### ISSUE THREAD

**Issue by vincz777** [springdoc/springdoc-openapi#2080]
**Describe the bug**

When upgrading from 2.0.0 to 2.0.2, the names of the parameter are systematically replaced by `arg0`, `arg1`, ...

**To Reproduce**

Upgrade from version 2.0.0 to 2.0.2 of Springdoc.

- What version of spring-boot you are using? 3.0.2
- What modules and versions of springdoc-openapi are you using? springdoc-openapi-starter-webmvc-ui and springdoc-openapi-starter-common. Upgrading from 2.0.0 to 2.0.2
- What is the actual and the expected result using OpenAPI Description (yml or json)? Parameter names to be the ones from the Java method
- Provide with a sample code (HelloController) or Test that reproduces the problem

**Expected behavior**

The parameter names should be displayed without any change when upgrading from 2.0.0 to 2.0.2.

**Screenshots**

With version 2.0.0:
![image](https://user-images.githubusercontent.com/6137848/219589611-bee2f2e8-fb47-4343-b323-df66797aa308.png)

With version 2.0.2:
![image](https://user-images.githubusercontent.com/6137848/219592020-250a362d-4078-473e-a0ba-1f4c693f6ea9.png)

**Additional context**
Probably related to those changes: https://github.com/springdoc/springdoc-openapi/commit/3f62ad2008f2c56b95e0b5eb3b531305a493e5bb

Ready to help and create a pull-request if you give me some guidelines on how to perform the fix.

**Comment by springssprite** [comment]
I have the same problem. Upgraded from 1.6.14 to 2.0.2 and all parameter names changed to arg0,arg1 etc. Changed the version to 2.0.0 and the property names are what they're supposed to be again.

**Comment by bnasslahsen** [comment]
see https://github.com/springdoc/springdoc-openapi/issues/2028
