### ISSUE TITLE
@SecurityRequirement not support place holder?

### ISSUE THREAD

**Issue by suoyunqing** [springdoc/springdoc-openapi#2085]
**Describe the bug**

We are using springboot3 and openapi v2. We trying to add @SecurityRequirement(name = "${springdoc.oauth.name}"). But it fail to read springdoc.oauth.name value from application.yaml, while other annotation like @Operation、@OpenAPIDefinition are able to read springdoc.oauth.name value from application.yaml.

**Comment by bnasslahsen** [comment]
read https://springdoc.org/#can-i-use-spring-property-with-swagger-annotations
