### ISSUE TITLE
Customiser to update OpenAPI.info object when dealing with multiple APIs via GroupedOpenApi

### ISSUE THREAD

**Issue by boardbloke** [springdoc/springdoc-openapi#2087]
Related to https://github.com/springdoc/springdoc-openapi/issues/213

I couldn't find a supported way to attach application info to a GroupedOpenApi, similarly to how springfox does it, with AppInfo objects added to the Docket.

I managed to get the behavior I wanted by writing am OpenApiCustomiser class that can be wired into GroupedOpenApi via addOpenApiCustomiser, but I imagine that it something that other people would wish to have as well, so requesting that the feature be added.

What I did was have a class as below.  It would be nice if something similar existed that could be wired into GroupedOpenApi  via an more explicit method such as GroupedOpenApi.apiInfo(Info info)

```
class GroupedOpenApiInfoCustomiser implements OpenApiCustomiser {

    private Info info;

    @Override
    public void customise(OpenAPI openApi) {
        openApi.info(this.info);
    }

    GroupedOpenApiInfoCustomiser info(Info info) {
        setInfo(info);
        return this;
    }

    public Info getInfo() {
        return info;
    }

    public void setInfo(Info info) {
        this.info = info;
    }
}
```

**Comment by bnasslahsen** [comment]
@boardbloke,

Use: `GroupedOpenApi.addOpenApiCustomiser`

**Comment by boardbloke** [comment]
Hi @bnasslahsen ,

Yes that's exactly what I did - see description above.  I wasn't asking for a solution, (as I have one), what I was suggesting is that given I suspect this is common use case, would it make sense to have a framework provided OpenApiCustomiser implementation that did that.

**Comment by bnasslahsen** [comment]
@boardbloke,

This is the only available option.
If you feel you have a better proposal, feel free to propose a PR!
