### ISSUE TITLE
getOpenApi in AbstractOpenApiResource synchronized?

### ISSUE THREAD

**Issue by mbedna** [springdoc/springdoc-openapi#209]
Hi,

Method protected `OpenAPI getOpenApi()` in `AbstractOpenApiResource` uses `computeDone` flag. If there will concurrent threads running at the same time code which is after `if (!computeDone)` could be executed few times. What do you think about making `protected OpenAPI getOpenApi()` synchronized?

**Comment by springdoc** [comment]
Hi @mbedna, 

 This makes sens.  It will be available on v1.2.16 of springdoc-openapi.
