### ISSUE TITLE
Support for other NonNull annotations for required parameters and responses specially spring boot @NonNullApi and @NonNullFilelds

### ISSUE THREAD

**Issue by giovannicandido** [springdoc/springdoc-openapi#2092]
Hi, I'm currently using openapi-generator to read the swagger specification and generate typescript client models and request.
My problem is all return types are optional and nuable in the specification, that provides some headaches dealing with it in typescript code.
If I go property by property in the response object and annotate with @NotNull from jakart.validation.constraints, then swagger marks it as nonnuallble or required and the code generated is not optional. Problem with this approach is that is time consuming and boilerplate.

I research a little bit and check that there is a lot of other annotations for Non Nuability. The one that was most interesting for me was the spring boot org.pringframework.lang.NonNullApi combined with org.springframework.lang.NonNullFields and org.springframework.lang.Nullable and org.springframework.lang.NonNull

With that annotations I can mark a whole package as null safety, and create exceptions in a case by case with the @Nullble annotation. The @NonNull do the contratry.

It would be great if springdoc supports this annotations to generate the required fields in the response and in the requests in the same mode it supports jakarta.validation.constraints.NotNull.

Maybe this is a swagger core request, or the support is already implemented (I could not find a doc about)

**Comment by bnasslahsen** [comment]
@giovannicandido,

Are you willing to propose a PR for it ?

**Comment by bnasslahsen** [comment]
This ticket will be closed, and can be reopened if there is any initiative to support this feature.
