### ISSUE TITLE
How to cancel the "Required field is not provided"

### ISSUE THREAD

**Issue by shiminfxcvii** [springdoc/springdoc-openapi#2093]
**Describe the bug**

- If you are reporting a bug, please help to speed up problem diagnosis by providing as
  much information as possible:
- A clear and concise description of what the bug is: the title of an issue is not enough

**To Reproduce**

- What version of spring-boot you are using?
- 2.7.9
- What modules and versions of springdoc-openapi are you using?
- 1.6.15-SNAPSHOT
- What is the actual and the expected result using OpenAPI Description (yml or json)?
- the actual: query * required
- the expected: query
- Provide with a sample code (HelloController) or Test that reproduces the problem
- `@Parameter(name = "query", description = "app qurey parameter", required = false,
            schema = @Schema(name = "query", type = "string", requiredMode = Schema.RequiredMode.NOT_REQUIRED))
    @Operation(summary = "app query")
    @ApiPermission("sys:sampleSurveyTask:view")
    @GetMapping("/selectByCondition")
    public Result<AppInvestigationTaskDTO> selectByCondition(String query) {
        return Result.ok(service.selectByCondition(query));
    }`

**Expected behavior**

- A clear and concise description of what you expected to happen.
- What is the expected result using OpenAPI Description (yml or json)?
- no * required

**Screenshots**
![image](https://user-images.githubusercontent.com/36143469/221395289-6582daf0-8cc2-4125-a257-537738902168.png)

**Additional context**

**Comment by bnasslahsen** [comment]
@shiminfxcvii,

Your description is not clear.
Try writing a correct description with a clear code formatting.

This ticket will be closed and can be reopened if the relevant information are provided.
