### ISSUE TITLE
@ParameterObject not working with Spring Boot v3.0.2

### ISSUE THREAD

**Issue by tivanovski** [springdoc/springdoc-openapi#2095]
**Describe the bug**

I migrate project from springfox to springdoc, and I'm having a problem with the @ParameterObject annotation.
It doesn't seems to work - the result is in the swagger-ui has no parameters.

**To Reproduce**

My operations :
 
@Operation(summary = "Test Parameter Object Post", description = "Test")
    @ResponseStatus(HttpStatus.OK)
    @GetMapping(value = {"/test_get"}, produces = "application/json")
    public
    @ResponseBody
    ResponseEntity<DigestResponseDto> test1(
            @ParameterObject TestRequest testRequest) {

        return new ResponseEntity<>(null, HttpStatus.OK);
    }

	@Operation(summary = "Test Parameter Object Post", description = "Test")
    @ResponseStatus(HttpStatus.OK)
    @PostMapping(value = {"/test_post"}, consumes = {"multipart/form-data"}, produces = "application/json")
    public
    @ResponseBody
    ResponseEntity<DigestResponseDto> test2(
            @ParameterObject TestRequest testRequest) {

        return new ResponseEntity<>(null, HttpStatus.OK);
    }

My parameters class:

@Schema
@NoArgsConstructor
@Getter
@Setter
@ToString
public class TestRequest {
	private @NotNull(message = "{document.digest.time.missing}") long tetField1;
	private String testField2;

}

- I am using spring-boot v3.0.2.
- I use springdoc-openapi-starter-webmvc-ui v2.0.2

**Expected behavior**

To have parameter fields in swagger-ui

**Screenshots**
![image](https://user-images.githubusercontent.com/30000181/221544370-a9944958-c3d8-4fd3-a3ea-49482038da21.png)

![image](https://user-images.githubusercontent.com/30000181/221544532-08814155-9ff6-4638-86b0-ca976bec7413.png)

**Additional**

When I use springdoc-openapi-ui v.1.6.14 and SpringBoot v2.1.2 RELEASE this code works as expected

**Comment by bnasslahsen** [comment]
@tivanovski,

Try using correct code formatting when reporting any issue.
There is not known issue as you are describing.
Try Providing a [Minimal, Reproducible Example - with HelloController](https://stackoverflow.com/help/minimal-reproducible-example) that reproduces the problem.

This ticket will be closed. But can be reopened, if you provide the relevant information.
