### ISSUE TITLE
Can you support plugins like swagger2 OperationBuilderPlugin ？

### ISSUE THREAD

**Issue by xin-li-ui** [springdoc/springdoc-openapi#2096]
The following functions can be implemented

`
@Component
public class SwaggerPermissionsReader implements OperationBuilderPlugin {

    @Override
    public void apply(OperationContext context) {
        List<VendorExtension> extensions = new ArrayList<>();
        Optional<RequiresPermissions> requiresPermissions = context.findAnnotation(RequiresPermissions.class);
        // add privileges to swagger extensions
        if (requiresPermissions.isPresent()) {
            RequiresPermissions permission = requiresPermissions.get();
            VendorExtension vendorExtension = new StringVendorExtension("privilege", permission.value());
            extensions.add(vendorExtension);
        }

        context.operationBuilder().extensions(extensions);
    }

    @Override
    public boolean supports(DocumentationType documentationType) {
        return SwaggerPluginSupport.pluginDoesApply(documentationType);
    }
}`

**Comment by bnasslahsen** [comment]
see the answer https://github.com/springdoc/springdoc-openapi/issues/1769
