### ISSUE TITLE
@javax.validation.Size specs generation for String incorrect (maximum instead of maxLength)

### ISSUE THREAD

**Issue by membersound** [springdoc/springdoc-openapi#21]
@Size is to validate the minimum and maximum length eg of a `String`.

Problem: if you try to put an integer value into the field from swagger-ui, the size is interpreted as maximum-digit-value.

Example:
```
@RestController
@Validated
public class Contr {
   @GetMapping
   public void get(@RequestParam @Size(min=4, max=6) String name) {}
}
```

This will trigger the following specs creation:
```
"parameters": [
	"name": "name",
	"schema": {
		"maximum": 6
		"minimum": 6
		"maxItems": 6
		"minItems": 6
		"type": "string"
	}
]
```

Using `maximum` and `minimum` is only correct if type would be an `Integer`. But for `String` you have to use `minLength` and `maxLength`. See https://swagger.io/docs/specification/data-models/data-types/

So you'd have to detect the parameter type first, and then apply the restrictions accordingly.
Also using `maxItems` and `minItems` is wrong here. Those should only be applied in case of type `Array`.

Input "asd123" works. But input "12345" does not work as it evaluates to "12345 > 6", and thus does not even pass the swagger-ui validation and thus never reaches the endpoint.

**Comment by springdoc** [comment]
String size will be handled on release 1.1.7, of springdoc.
In fact, as per documentation @Size supports String, Collection, Map and arrays
