### ISSUE TITLE
Explicitly set which packages to scan

### ISSUE THREAD

**Issue by inspirsea** [springdoc/springdoc-openapi#210]
Hi, is there a way to set which package to scan for endpoints and models. 
The issue i am trying to solve is:
I have common libraries that expose endpoints, i don´t want these to be added to the documentation and i don´t want to set hidden on all those endpoints.
The common libraries don´t have a dependency to springdoc-openapi.
Currently i would rather specify a package or similar and ignore everything else. 
Is this currently possible?

**Comment by hemju** [comment]
Maybe not only packages, maybe `paths` to scan. E.g. I want to document all paths under `v1` but not under `internal`.

**Comment by inspirsea** [comment]
Defining it with a path would be completely fine with me, i just need a way to white-list rather than black-list resources.

**Comment by springdoc** [comment]
Hi @inspirsea, 

 This feature will be available with the next release v1.2.16.
 You will be able to set list of packages to include using the following propety:

```properties
springdoc.packagesToScan=package1, package2
```

**Comment by hemju** [comment]
Packages are not really the best way to a white list though, normally the controllers are in different packages and maybe mixed with internal controllers. Please consider a path like filter similar to what SwaggerConfig allowed. It would be so much easier to do on a path level.

**Comment by springdoc** [comment]
Hi @hemju,

 Depending on cases, it can be relevant to filter using packages. 
 Both features will be then available, for the next release.

  You will be able to set list of path to include using the following propety:

```properties
springdoc.pathsToMatch=/v1, /api/balance/**
```

**Comment by inspirsea** [comment]
Super, thank you.
