### ISSUE TITLE
@Deprecated is ignored when enumsAsRef==true / $refs can't be deprecated

### ISSUE THREAD

**Issue by daniel-frak** [springdoc/springdoc-openapi#2101]
**Describe the bug**

When `enumsAsRef` is set to `true`, the `@Deprecated` annotation on fields of type enum is ignored.

**To Reproduce**

- Using Spring Boot 3.0.3
- Using `springdoc-openapi-starter-common` and `springdoc-openapi-starter-webmvc-ui` version `2.0.2`

Given an example endpoint:
```java
import org.springframework.context.annotation.Configuration;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RestController;

@RestController
public class TestController {

    @GetMapping
    public MyClass testEndpoint() {
        return null;
    }

    public enum TestEnum {

        VAL1, VAL2
    }

    @Configuration
    public static class OpenApiConfig {

        static {
            // Generate enums on frontend
            io.swagger.v3.core.jackson.ModelResolver.enumsAsRef = true;
        }
    }

    public record MyClass(
            TestEnum field1,
            @Deprecated TestEnum field2
    ) {
    }
}
```

The produced OpenAPI schema is:
```yaml
openapi: 3.0.1
info:
  title: OpenAPI definition
  version: v0
servers:
- url: http://localhost:8080
  description: Generated server url
paths:
  /:
    get:
      tags:
      - test-controller
      operationId: testEndpoint
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/MyClass'
components:
  schemas:
    MyClass:
      type: object
      properties:
        field1:
          $ref: '#/components/schemas/TestEnum'
        field2:
          $ref: '#/components/schemas/TestEnum'
    TestEnum:
      type: string
      enum:
      - VAL1
      - VAL2
```

That is, the `@Deprecated` annotation gets ignored.

Removing the line io.swagger.v3.core.jackson.ModelResolver.enumsAsRef = true; produces correct output (the deprecation gets applied to the field) but, of course, the enum is not separately documented:
```yaml
openapi: 3.0.1
info:
  title: OpenAPI definition
  version: v0
servers:
- url: http://localhost:8080
  description: Generated server url
paths:
  /:
    get:
      tags:
      - test-controller
      operationId: testEndpoint
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/MyClass'
components:
  schemas:
    MyClass:
      type: object
      properties:
        field1:
          type: string
          enum:
          - VAL1
          - VAL2
        field2:
          type: string
          deprecated: true
          enum:
          - VAL1
          - VAL2
```

**Expected behavior**

When running an application with the endpoint given above, I would expect an OpenAPI description like this:

```yaml
openapi: 3.0.1
info:
  title: OpenAPI definition
  version: v0
servers:
- url: http://localhost:8080
  description: Generated server url
paths:
  /:
    get:
      tags:
      - test-controller
      operationId: testEndpoint
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/MyClass'
components:
  schemas:
    MyClass:
      type: object
      properties:
        field1:
          $ref: '#/components/schemas/TestEnum'
        field2:
          allOf:   
            - $ref: '#/components/schemas/TestEnum'
            - deprecated: true
    TestEnum:
      type: string
      enum:
      - VAL1
      - VAL2
```

That is, the description for `field2` should contain the `deprecated: true` line, which also means it must be wrapped in an `allOf` array.

**Additional context**

This bug might be related to another one in swagger-core, which I described here:
https://github.com/swagger-api/swagger-core/issues/4372

However, as far as I'm aware, these are different bugs as swagger-core doesn't contain any support for `@Deprecated` annotations and the behavior is different.

Unfortunately, this also means there doesn't seem to be any workaround for the Springdoc bug, as I can't use `@Schema(deprecated=true)` on the field (as it would make all fields using that type deprecated).

**Comment by daniel-frak** [comment]
Further research suggests this is an issue with `$ref` as a whole. In the example below `field4` also doesn't get marked as deprecated:

```java
import org.springframework.context.annotation.Configuration;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RestController;

@RestController
public class TestController {

    @GetMapping
    public MyClass testEndpoint() {
        return null;
    }

    public enum TestEnum {

        VAL1, VAL2
    }

    @Configuration
    public static class OpenApiConfig {

        static {
            // Generate enums on frontend
            io.swagger.v3.core.jackson.ModelResolver.enumsAsRef = true;
        }
    }

    public record MyClass(
            TestEnum field1,
            @Deprecated TestEnum field2,
            InnerClass field3,
            @Deprecated InnerClass field4
    ) {
    }

    public record InnerClass(
            String someField3
    ) {
    }
}
```

**Comment by bnasslahsen** [comment]
@daniel-frak,

Agree, this is a swagger-core limitation.

**Comment by daniel-frak** [comment]
@bnasslahsen This is not strictly a `swagger-core` limitation, as it is `springdoc-openapi` that handles the `@Deprecated` annotation, **not** `swagger-core`.

Are there any plans to address this? At the very least this issue should remain open until a fix is found - labeling it as "invalid" is disingenuous.

**Comment by bnasslahsen** [comment]
@daniel-frak,

We do not believe it's springdoc issue. That's why it's invalid.
Thus, there are no longer investigations planned on it.
But you can propose a PR, if you feel that you have a better solution.

**Comment by daniel-frak** [comment]
@bnasslahsen It would behoove you to put more trust into issue reporters and not assume that issues are invalid just because they are mildly related to `swagger-core`. I'm sad to say this is not the first time you have done this.

I have spent some more time digging into the issue and found a solution in `SchemaPropertyDeprecatingConverter`, which is most definitely not a `swagger-core` class. A simple check for `$getRef` is all that's needed, it seems, so I've created a PR:

https://github.com/springdoc/springdoc-openapi/pull/2116)](https://github.com/springdoc/springdoc-openapi/pull/2116

Can we, now, agree that this is not an invalid issue?

**Comment by bnasslahsen** [comment]
@daniel-frak,

Trust does not exclude control. (There is Huge differences between reporting  a bug and asking for an enchancement request)

As mentioned earlier this is not a springdoc-openapi bug. 
You can test the generated Schema spec with swagger-core classes only and without springdoc-openapi. 

Once you do it, you will understand that you are proposing à workaround inside springdoc-openapi. 

I invite you then to correct the description first, so it can be considered as an enchancement request. 

Then we can have a look to your PR to review it.
