### ISSUE TITLE
Difference between group and URL configuration not clear; inability to render the definition when using both

### ISSUE THREAD

**Issue by DawidNiezgodka** [springdoc/springdoc-openapi#2102]
**Describe the bug**

In my application, I have various controllers that are labeled, for example, like this:

```
@RestController
@RequestMapping(path = "/rest/protected/")
@Tag(name = "AdminController")
public class AdminController {
 
@RestController
@RequestMapping("/rest/public/")
@Tag(name = "UserController")
public class UserController {
```

I want to create two different groups. One group should only have access to public endpoints, while the other should have access to all endpoints.

In search of a solution, I came across the concept of groups in the documentation. I defined two groups as follows:

```
    @Bean
    public GroupedOpenApi adminApi() {
        return GroupedOpenApi.builder()
                .displayName("admin")
                .group("admin")
                .pathsToMatch("/rest/protected/**")
                .build();
    }
    @Bean
    public GroupedOpenApi userApi() {
        return GroupedOpenApi.builder()
                .group("user")
                .pathsToMatch("/rest/public/**")
                .build();
    }
```

Unfortunately, when I execute the program, I receive the following error:
```
Unable to render this definition
The provided definition does not specify a valid version field.
Please indicate a valid Swagger or OpenAPI version field. Supported version fields are swagger: "2.0" and those that match openapi: 3.0.n (for example, openapi: 3.0.0).
```
I can see, however, `admin` and `user` in the `select a definition` field.

In an attempt to address the error above, I added these two to `application.properties`:
```
springdoc.version=1.6.14
springdoc.api-docs.openapi.version=3.0.1
```
and then:
```
@Bean
public OpenAPI apiInfo(@Value("${springdoc.version}") String appVersion) {
    final OpenAPI openAPI = new OpenAPI();
    Paths paths = openAPI.getPaths();
    return openAPI.info(
            new Info().title("")
                    .description("")
                    .version(appVersion));
}
```
Unfortunately, to no avail, i.e.: I'm getting the same error. Also tried with ` .version("openapi: 3.0.0")`

I continued to search the documentation and came across fields related to URLs:
```
springdoc.swagger-ui.urls[0].url
springdoc.swagger-ui.urls[0].name
springdoc.swagger-ui.urlsPrimaryName
```

I added the following to the `application.properties`:
```
springdoc.swagger-ui.urlsPrimaryName=primary
springdoc.swagger-ui.urls[0].url=/v3/api-docs.yaml
springdoc.swagger-ui.urls[0].name=test
```

To my surprise, the REST API documentation appeared. Interestingly, in field `select a definition`, only `test` can be selected. It seems that configuring using the URL attribute completely invalidates the definitions of the groups.
When you open the documentation for the springdoc properties, you can read: 

> "The url of the swagger group, used by Topbar plugin. URLs must be
> unique among all items in this array, since they’re used as
> identifiers."

It say, "the url of the swagger group", but what group?

In light of this unusual behavior, I wonder what the difference is between the URL-config and groups-comfig. Why does setting a URL completely nullify the given group definitions through bean definitions?

**To Reproduce**

- What version of spring-boot you are using?
2.6.13
- What modules and versions of springdoc-openapi are you using?
`springdoc.version=1.6.14`
`springdoc.api-docs.openapi.version=3.0.1`
- What springdoc packages are you using:
```
 <dependency>
        <groupId>org.springdoc</groupId>
        <artifactId>springdoc-openapi-ui</artifactId>
        <version>1.6.14</version>
      </dependency>
      <dependency>
        <groupId>org.springdoc</groupId>
        <artifactId>springdoc-openapi-data-rest</artifactId>
        <version>1.6.14</version>
      </dependency>
```

**Expected behavior**

The possibility to choose two distinct groups from the `select a definition` field.

**Comment by bnasslahsen** [comment]
You should use: 

```properties
springdoc.api-docs.version=openapi_3_0
```

See documentation, for more details: https://springdoc.org/#springdoc-openapi-core-properties

**Comment by DawidNiezgodka** [comment]
Why was the issue immediately closed without confirmation that the proposed change resolves the problem?
After adding the line `springdoc.api-docs.version=openapi_3_0` to the `application.properties` file, the problem still persists. I made the first attempt without setting it explicitly, so it was taken as a default value anyway. I still can see the following after having started the app:
```
Unable to render this definition
The provided definition does not specify a valid version field.
Please indicate a valid Swagger or OpenAPI version field. Supported version fields are swagger: "2.0" and those that match openapi: 3.0.n (for example, openapi: 3.0.0).
```

**Comment by bnasslahsen** [comment]
The is no issue !
The problem is in your description which is Just not clear !
