### ISSUE TITLE
Hope to add a white list and blacklist annotation of requests and responses

### ISSUE THREAD

**Issue by gao-changxu** [springdoc/springdoc-openapi#2103]
In our project, when there are complex logic, it will cause a large number of description annotations in the Controller, which is very redundant. Therefore, I hope to provide a whitelist or blacklist. Laminate.
otherwise, is there any Good solution.

**Comment by bnasslahsen** [comment]
Remember, contributions to this repository should follow its [contributing guidelines](https://github.com/springdoc/springdoc-openapi/blob/9d6bd002f970d71975e11db59f45c28414a8d281/CONTRIBUTING.adoc), [security policy](https://github.com/springdoc/springdoc-openapi/blob/9d6bd002f970d71975e11db59f45c28414a8d281/SECURITY.md), and [code of conduct](https://github.com/springdoc/springdoc-openapi/blob/9d6bd002f970d71975e11db59f45c28414a8d281/CODE_OF_CONDUCT.md).
