### ISSUE TITLE
Javadocs Not Getting Picked Up

### ISSUE THREAD

**Issue by dan-thera** [springdoc/springdoc-openapi#2105]
**Describe the bug**
I can't get Javadocs to be picked up in my swagger docs despite my best attempts to follow the instructions [here](https://springdoc.org/v2/#javadoc-support). I had this working at one point -- I believe before I upgraded to Spring 3 and Spring Doc V2.

**To Reproduce**

- What version of spring-boot you are using? 3.0.4
- What modules and versions of springdoc-openapi are you using?
```
        <dependency>
            <artifactId>springdoc-openapi-starter-webmvc-ui</artifactId>
            <groupId>org.springdoc</groupId>
            <version>2.0.2</version>
        </dependency>
        <dependency>
            <groupId>org.springdoc</groupId>
            <artifactId>springdoc-openapi-starter-common</artifactId>
            <version>2.0.2</version>
        </dependency>
```

and

```
 <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <configuration>
                    <annotationProcessorPaths>
                        <path>
                            <groupId>com.github.therapi</groupId>
                            <artifactId>therapi-runtime-javadoc-scribe</artifactId>
                            <version>0.15.0</version>
                        </path>
                    </annotationProcessorPaths>
                </configuration>
            </plugin>
        </plugins>
    </build>
```
- What is the actual and the expected result using OpenAPI Description (yml or json)?
This code:
<img width="959" alt="image" src="https://user-images.githubusercontent.com/107228315/223218883-b71223ef-e48c-46f0-a57c-114d48124275.png">

generates these docs:
<img width="955" alt="image" src="https://user-images.githubusercontent.com/107228315/223218951-8f53a3b0-88dd-4f09-897b-ed5fa3d93999.png">

I would have expected `hours` to have a description of `This is the number of hours` instead of nothing.

**Comment by bnasslahsen** [comment]
@dan-thera,

Documentation is updated: https://springdoc.org/v2/#javadoc-support
You are missing the ` <!-- Runtime library -->` section
