### ISSUE TITLE
setNullable() is not respected for schemas that refer to reference types

### ISSUE THREAD

**Issue by gk-brown** [springdoc/springdoc-openapi#2108]
**Describe the bug**
Calling `setNullable()` on a property `Schema` instance that refers to a single instance of a reference type has no effect.

**To Reproduce**
Implementation of `import org.springdoc.core.customizers.OpenApiCustomiser`. Explicitly calls `setNullable()` on all property schemas (non-required properties are considered nullable; required properties are not).

```java
@Override
public void customise(OpenAPI openApi)
{
  Components components = openApi.getComponents();

  Map<String, Schema> schemas = components.getSchemas();

  // Set "nullable" to true for non-required properties
  for (Schema schema : schemas.values()) {
    Map<String, Schema> properties = Optional.ofNullable(schema.getProperties()).orElse(Collections.emptyMap());

    Set<String> required = new HashSet<>(Optional.ofNullable((List<String>) schema.getRequired()).orElse(Collections.emptyList()));

    for (Map.Entry<String, Schema> entry : properties.entrySet()) {
      String key = entry.getKey();
      Schema value = entry.getValue();

      value.setNullable(!required.contains(key));
    }
  }

  // Sort the types by name
  components.setSchemas(new TreeMap<>(schemas));
}
```

- What version of spring-boot you are using?
2.7.7

- What modules and versions of springdoc-openapi are you using?
springdoc-openapi-ui
springdoc-openapi-data-rest
1.6.14

**Expected behavior**
The "nullable" value for all non-required properties should be explicitly set to `true`. This seems to work for non-reference types and for arrays of reference types, but not for single instances of reference types. For example, "clients" and "optionLevel" below are correctly marked as "nullable", but "dates" and "clientData" are not:

```json
"AccountProfile" : {
  "required" : [ "accountType", "clients" ],
  "type" : "object",
  "properties" : {
    "clients" : {
      "type" : "array",
      "description" : "The clients associated with the account.",
      "nullable" : false,
      "items" : {
        "$ref" : "#/components/schemas/Client"
      }
    },
    "dates" : {
      "$ref" : "#/components/schemas/AccountProfileDates"
    },
    "clientData" : {
      "$ref" : "#/components/schemas/AccountProfileClientData"
    },
    "optionLevel" : {
      "type" : "string",
      "description" : "The account's option level.",
      "nullable" : true
    },
    ...
```

Since the code above explicitly calls `setNullable()` on all schemas, the output should contain a "nullable" value for each one (whether `true` or `false`).

**Screenshots**
n/a

**Additional context**
n/a

**Comment by bnasslahsen** [comment]
@gk-brown,

We don't see in your sample `"dates" `and `"clientData" ` real schema. You are only mentioning the `$ref`.
You will never get nullable together with `$ref.`

After adding the following code to this spring-data-rest : https://github.com/springdoc/springdoc-openapi/blob/master/springdoc-openapi-data-rest/src/test/java/test/org/springdoc/api/app16/SpringDocApp16Test.java

```
		@Bean
		public OpenApiCustomiser openApiCustomiser(Collection<Entry<String, Example>> examples) {
			return openApi -> {
				Components components = openApi.getComponents();
				Map<String, Schema> schemas = components.getSchemas();
				// Set "nullable" to true for non-required properties
				for (Schema schema : schemas.values()) {
					Map<String, Schema> properties = Optional.ofNullable(schema.getProperties()).orElse(Collections.emptyMap());

					Set<String> required = new HashSet<>(Optional.ofNullable((List<String>) schema.getRequired()).orElse(Collections.emptyList()));

					for (Map.Entry<String, Schema> entry : properties.entrySet()) {
						String key = entry.getKey();
						Schema value = entry.getValue();

						value.setNullable(!required.contains(key));
					}
				}
				// Sort the types by name
				components.setSchemas(new TreeMap<>(schemas));
			};
		}
```

SetNullable is correctly respected and no issue here.

If you believe you are having an issue in `springdoc-openapi` code, try providing a [Minimal, Reproducible Example - with HelloController](https://stackoverflow.com/help/minimal-reproducible-example) that reproduces the problem

**Comment by gk-brown** [comment]
Thank you for the response. Can you explain this statement?

> You will never get nullable together with `$ref`.

Why is it possible to use "nullable" with an array of `$ref` but not a single `$ref`?

**Comment by bnasslahsen** [comment]
@gk-brown,

This is the answer from the swagger editor: 
![image](https://user-images.githubusercontent.com/13404829/223730974-c85099e0-ade0-4ad1-a615-3fcf00929ca7.png)

Please note, this is not a questions related to springdoc-openapi.

You can follow [contributing guidelines](https://github.com/springdoc/springdoc-openapi/blob/d8da2edc90d9d294adb4f71a1240d9a676f6b267/CONTRIBUTING.adoc), to undestand which questions to ask in GITHUB ISSUES.

**Comment by gk-brown** [comment]
Thank you for the information. I found this link that explains the reasoning:

https://swagger.io/docs/specification/using-ref/#sibling

However, [NSwag](https://github.com/RicoSuter/NSwag) does appear to allow this. We have an API consumer that generates C# code from our OpenAPI spec (which is generated by springdoc-openapi). Because the `$ref` properties are missing the "nullable" attribute, NSwag treats them as non-optional when they should actually be optional.

I'm not sure any other siblings would be applicable, but it does seem like "nullable" should be respected for `$ref`s, at least when used in a property definition. But that's an OpenAPI issue, not springdoc.

**Comment by little-pinecone** [comment]
@gk-brown per [StackOverflow](https://stackoverflow.com/a/41752575) properties like `nullable` are supported for `$ref`, you just have to wrap it in `allOf`:
```yml
schema:
  nullable: true
  allOf:
    - $ref: '#/components/schemas/Pet'
```

In Swagger editor it works properly:
![image](https://user-images.githubusercontent.com/25420384/224388186-6fe328ee-a6e8-450d-9e29-b9c8332d0980.png)

**Comment by gk-brown** [comment]
@little-pinecone Thank you for the suggestion.
