### ISSUE TITLE
'boolean org.apache.commons.lang3.math.NumberUtils.isCreatable(java.lang.String)'

### ISSUE THREAD

**Issue by Kishangalgotra** [springdoc/springdoc-openapi#2109]
**Facing error '**boolean org.apache.commons.lang3.math.NumberUtils.isCreatable(java.lang.String)'****

Error length is quite long so adding just portion of it only.

### 
java.lang.NoSuchMethodError: 'boolean org.apache.commons.lang3.math.NumberUtils.isCreatable(java.lang.String)'
	at io.swagger.v3.core.util.AnnotationsUtils.getSchemaFromAnnotation(AnnotationsUtils.java:482) ~[swagger-core-jakarta-2.2.7.jar:2.2.7]
	at io.swagger.v3.core.util.AnnotationsUtils.getSchema(AnnotationsUtils.java:1170) ~[swagger-core-jakarta-2.2.7.jar:2.2.7]

- Using Java version 17
-  Am sharing pom.xml details below.

Now Plz check dependency used for Open API below.
```
        <dependency>
            <groupId>org.springdoc</groupId>
            <artifactId>springdoc-openapi-starter-webmvc-ui</artifactId>
            <version>2.0.2</version>
        </dependency>
```

``` <properties>
        <java.version>17</java.version>
        <spring-cloud.version>2020.0.3</spring-cloud.version>
        <hibernate-types-52.version>2.12.1</hibernate-types-52.version>
        <apache-poi.version>4.1.2</apache-poi.version>
        <swagger.version>2.9.2</swagger.version>
        <!--<springfox-swagger.version>3.0.0</springfox-swagger.version>-->
    </properties>```

``` <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-actuator</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-data-jpa</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-validation</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-data-rest</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>
        <dependency>
            <groupId>mysql</groupId>
            <artifactId>mysql-connector-java</artifactId>
            <version>8.0.12</version>
        </dependency>
```

**Comment by bnasslahsen** [comment]
Remember, contributions to this repository should follow its [contributing guidelines](https://github.com/springdoc/springdoc-openapi/blob/82d46fdf42c73edc39ac3298dfcd66662553cf9b/CONTRIBUTING.adoc), [security policy](https://github.com/springdoc/springdoc-openapi/blob/82d46fdf42c73edc39ac3298dfcd66662553cf9b/SECURITY.md), and [code of conduct](https://github.com/springdoc/springdoc-openapi/blob/82d46fdf42c73edc39ac3298dfcd66662553cf9b/CODE_OF_CONDUCT.md).
