### ISSUE TITLE
How to use the gateway url

### ISSUE THREAD

**Issue by Enaium** [springdoc/springdoc-openapi#2112]
I add the swagger url of all the services, but it doesn't use the gateway's url

```kotlin
@Configuration
@EnableScheduling
class SpringDocConfiguration(
    val configProperties: SwaggerUiConfigProperties,
    val routeLocator: RouteDefinitionLocator
) {
    @Scheduled(fixedDelay = 5)
    fun apis() {
        configProperties.urls = routeLocator.routeDefinitions.collectList().block()!!.filter { route: RouteDefinition ->
            route.uri.host != null
        }.distinct().map { route: RouteDefinition ->
            SwaggerUrl().apply {
                name = route.uri.host
                url = "/$name/v3/api-docs"
            }
        }.toSet()
    }
}
```

![](https://user-images.githubusercontent.com/32991121/224056348-05f6ba60-774d-47da-be73-159b1a2501ce.png)
I want it to use gateway's url(localhost:8080)

```kotlin
@Bean
fun openAPI(): OpenAPI =
    OpenAPI().info(Info().title("title").version("1.0.0"))
        .addServersItem(Server().url("http://localhost:8080"))
}
```

I've tried add a server for each service, and it solved the problem, but it doesn't change with the url of the gateway

**Comment by bnasslahsen** [comment]
@Enaium,

I invite you to provide a [Minimal, Reproducible Example - with HelloController](https://stackoverflow.com/help/minimal-reproducible-example) that reproduces the problem.

This ticket will be closed, but can be reopened if add the minimal project.
