### ISSUE TITLE
Springboot3 can use /v3/api-docs, but swagger-ui.html is blank page

### ISSUE THREAD

**Issue by ZhouYixun** [springdoc/springdoc-openapi#2113]
**Describe the bug**

- I am using spirngboot3, and I can use /v3/api-docs, but swagger-ui.html is blank page.

**To Reproduce**

My project: https://github.com/SonicCloudOrg/sonic-server/tree/feat/springboot3

My springboot version:
```
 <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>3.0.3</version>
        <relativePath/> <!-- lookup parent from repository -->
    </parent>
```

My springdoc version:
```
 <dependency>
            <groupId>org.springdoc</groupId>
            <artifactId>springdoc-openapi-starter-webmvc-ui</artifactId>
            <version>2.0.2</version>
        </dependency>
```

config:

```
springdoc:
  enable-native-support: true
```

**Expected behavior**

It may has a page.

**Screenshots**

I found a blank page.

![image](https://user-images.githubusercontent.com/56339314/224070434-fd19878f-0991-4525-8aa6-de3ecdd9657d.png)

but /v3/api-docs works

![image](https://user-images.githubusercontent.com/56339314/224071117-e913b42a-8cfb-487e-9d7c-73eb7c4db380.png)

**Additional context**

This problem has troubled me for several days. I would be grateful if you could help me. If you need any additional information, please contact me. Thank you.

**Comment by ZhouYixun** [comment]
My English is not very good. The description comes from Google Translator

**Comment by bnasslahsen** [comment]
@ZhouYixun,

Please  Provide a [Minimal, Reproducible Example - with HelloController](https://stackoverflow.com/help/minimal-reproducible-example) that reproduces the problem.

Once you provide this project, the ticket can be reopened.

**Comment by ZhouYixun** [comment]
I found the reason

```java
@Component
@Slf4j
public class PermissionFilter extends OncePerRequestFilter {
    @Override
    protected void doFilterInternal(HttpServletRequest request, HttpServletResponse response, FilterChain filterChain) throws ServletException, IOException {
       //xxxxx
       return;
    }
}
```

The correct way should be

```java
@Component
@Slf4j
public class PermissionFilter extends OncePerRequestFilter {
    @Override
    protected void doFilterInternal(HttpServletRequest request, HttpServletResponse response, FilterChain filterChain) throws ServletException, IOException {
       filterChain.doFilter(request, response);
    }
}
```

**Comment by Yuhong-He** [comment]
In my case,  I have a global AuthenticationFilter. The solution is adding `/swagger-ui/*` into the exclusion.
