### ISSUE TITLE
Explode attribute is not defined for "sort" parameter of @PageableAsQueryParam

### ISSUE THREAD

**Issue by syroeshko** [springdoc/springdoc-openapi#2115]
Currently code of the annotation looks like this:
```
...
@Parameter(in = ParameterIn.QUERY
		, description = "Sorting criteria in the format: property,(asc|desc). "
		+ "Default sort order is ascending. " + "Multiple sort criteria are supported."
		, name = "sort"
		, array = @ArraySchema(schema = @Schema(type = "string")))
...
```

I suspect, that there should also be `explode = Explode.TRUE`, because Spring allows sorting by multiple parameters. Am I missing something?

**Comment by bnasslahsen** [comment]
@syroeshko,

If you believe there is an enchancement, feel free to propose directly a PR with the related test case . 
And we will be happy to have a look at it.
