### ISSUE TITLE
update 2.0.3 error , 2.0.2 normal

### ISSUE THREAD

**Issue by JavaLionLi** [springdoc/springdoc-openapi#2118]
**Describe the bug**
springboot 3.0.4
![image](https://user-images.githubusercontent.com/31852897/224366969-687da64e-9cc9-44f1-8941-1502f53c4890.png)

- If you are reporting a bug, please help to speed up problem diagnosis by providing as
  much information as possible:
- A clear and concise description of what the bug is: the title of an issue is not enough

**To Reproduce**

- What version of spring-boot you are using?
- What modules and versions of springdoc-openapi are you using?
- What is the actual and the expected result using OpenAPI Description (yml or json)?
- Provide with a sample code (HelloController) or Test that reproduces the problem

**Expected behavior**

- A clear and concise description of what you expected to happen.
- What is the expected result using OpenAPI Description (yml or json)?

**Screenshots**

**Additional context**

**Comment by bnasslahsen** [comment]
See #2114
