### ISSUE TITLE
OAuth2 scopes are not displayed with security scheme in auth window opened near endpoints

### ISSUE THREAD

**Issue by marichka-spin** [springdoc/springdoc-openapi#2135]
Hello, team

I've upgraded our project to Spring Boot 3.0.1 and springdoc-openapi-ui 1.6.8 to springdoc-openapi-starter-webmvc-ui 2.0.3. We are using OAuth2 security scheme. When user tries to auth via main 'Authorize' button all oauth2 scope checkbox is displayed. But if user tries to auth via button near endpoint scope checkbox is missing. In version 1.6.8 everything was ok, and we didn't need to specify scopes in each endpoint annotation. Please take a look at screenshots.

Main auth window
<img width="688" alt="main_auth_window" src="https://user-images.githubusercontent.com/5120736/224993138-428d8c28-11cc-4f6b-be7b-23f1e9153ed2.png">

Auth button near endpoint
<img width="633" alt="auth_from_endpoint" src="https://user-images.githubusercontent.com/5120736/224993263-1dda0e0a-b10c-4ff3-8c55-7a54e6746995.png">

Auth window near endpoint
<img width="646" alt="auth_window_from_endpoint" src="https://user-images.githubusercontent.com/5120736/224993347-7466cbf3-d021-4bcb-a5fa-26367f214b53.png">

Thank you for any response!

**Comment by bnasslahsen** [comment]
@marichka-spin,

This is a [swagger-ui ](https://github.com/swagger-api/swagger-ui/issues/8219) change.
You should define your scopes per endpoint.
