### ISSUE TITLE
javadoc the comment above the controller cannot be recognized, you need to use the @Tag comment to take effect. Can you read the class comment directly without writing the comment?

### ISSUE THREAD

**Issue by JavaLionLi** [springdoc/springdoc-openapi#2137]
**Describe the bug**

- If you are reporting a bug, please help to speed up problem diagnosis by providing as
  much information as possible:
- A clear and concise description of what the bug is: the title of an issue is not enough

**To Reproduce**

- What version of spring-boot you are using?
- What modules and versions of springdoc-openapi are you using?
- What is the actual and the expected result using OpenAPI Description (yml or json)?
- Provide with a sample code (HelloController) or Test that reproduces the problem

**Expected behavior**

- A clear and concise description of what you expected to happen.
- What is the expected result using OpenAPI Description (yml or json)?

**Screenshots**

**Additional context**

**Comment by JavaLionLi** [comment]
I hope javadoc can recognize controller comments and replace @Tag.

**Comment by bnasslahsen** [comment]
@JavaLionLi,

You need to describe your context (the title of an issue is not enough)

See the section Using [GitHub Issues ](https://github.com/springdoc/springdoc-openapi/blob/master/CONTRIBUTING.adoc)

This ticket is closed as incomplete, and can be reopened if the relevant information are provided.

**Comment by JavaLionLi** [comment]
> @JavaLionLi,
> 
> You need to describe your context (the title of an issue is not enough)
> 
> See the section Using [GitHub Issues ](https://github.com/springdoc/springdoc-openapi/blob/master/CONTRIBUTING.adoc)
> 
> This ticket is closed as incomplete, and can be reopened if the relevant information are provided.

The framework does not recognize the annotation above the '@ Controller' class,
The generated documentation uses the class name as the interface group name,
This is not what we want,
We want to be able to read the comment above the class as the interface group name,
The current way to do this is to use the description attribute of the '@ Tag' annotation,
It is hoped that the framework can directly read comments to replace the description of '@ Tag' comments.

**Comment by JavaLionLi** [comment]
> @JavaLionLi,
> 
> You need to describe your context (the title of an issue is not enough)
> 
> See the section Using [GitHub Issues ](https://github.com/springdoc/springdoc-openapi/blob/master/CONTRIBUTING.adoc)
> 
> This ticket is closed as incomplete, and can be reopened if the relevant information are provided.

How do I reopen the issue?
