### ISSUE TITLE
SpringDocJacksonModuleConfiguration is loaded even though there is no ObjectMapperProvider when springdoc.api-docs.enabled = false

### ISSUE THREAD

**Issue by davefranken-ah** [springdoc/springdoc-openapi#2142]
**Describe the bug**
Caused by: https://github.com/springdoc/springdoc-openapi/issues/2114

Usually, Springdoc configuration classes include an annotation `@ConditionalOnBean(SpringDocConfiguration.class)`, this ensures they are only loaded if the beans from that configuration are loaded.

SpringDocJacksonModuleConfiguration does not have such an annotation. Thus, the constructor inside it is fired, which requires a bean of type ObjectMapperProvider, which is not available when springdoc.api-docs.enabled = false.

**To Reproduce**

- What version of spring-boot you are using? 3.0.4
- What modules and versions of springdoc-openapi are you using? 2.0.4
- What is the actual and the expected result using OpenAPI Description (yml or json)?
There should not be an error
- Provide with a sample code (HelloController) or Test that reproduces the problem
In application.yml (or .properties), set springdoc.api-docs.enabled to false
Try to start an application or run a test

**Expected behavior**
The application should start and/or tests should run

**Additional context**
This is likely caused by https://github.com/springdoc/springdoc-openapi/issues/2114 where the SpringDocJacksonModuleConfiguration was added without the proper annotations.

**Comment by davefranken-ah** [comment]
This may help others: until a new version is released, you can use the following workaround:

```kotlin
class SpringDocJacksonKotlinModuleConfigurationFilter : AutoConfigurationImportFilter, EnvironmentAware {

    private lateinit var environment: Environment

    override fun match(autoConfigurationClasses: Array<out String>, autoConfigurationMetadata: AutoConfigurationMetadata?): BooleanArray {
        if (environment.getProperty("springdoc.api-docs.enabled", Boolean::class.java) == false) {
            return autoConfigurationClasses.map { it != CLASS_TO_EXCLUDE }.toBooleanArray()
        }

        return BooleanArray(autoConfigurationClasses.size) { true }
    }

    companion object {
        private const val CLASS_TO_EXCLUDE = "org.springdoc.core.configuration.SpringDocJacksonKotlinModuleConfiguration"
    }

    override fun setEnvironment(environment: Environment) {
        this.environment = environment
    }
}
```
This will exclude the SpringDocJacksonKotlinModuleConfiguration file being loaded through auto-configuration whenever the property `springdoc.api-docs.enabled` is set to false (which leads to SpringDocConfiguration and consequently ObjectMapperProvider not being loaded).

You can add this file to META-INF/spring.factories:
`org.springframework.boot.autoconfigure.AutoConfigurationImportFilter=my.package.SpringDocJacksonKotlinModuleConfigurationFilter
`

**Comment by jurri-cz** [comment]
There is an easier workaround for Spring Boot (3.x included). Use in external config file where your `springdoc.api-docs.enabled=false` is:
```yaml
spring:
  autoconfigure:
    exclude: org.springdoc.core.configuration.SpringDocJacksonKotlinModuleConfiguration
```
