### ISSUE TITLE
Consider /api-docs/v3 instead of /v3/api-docs

### ISSUE THREAD

**Issue by onacit** [springdoc/springdoc-openapi#2145]
A lot of, or some, developers prefer prefixes for api versioning.

e.g.
* `.../context-path/v1/some`
* `.../context-path/v2/other`

Which may yield `.../context-path/v3/another` in some point in time.

Can we change the (default) value of the `/v3/api-docs` to `/api-docs/v3`?

**Comment by bnasslahsen** [comment]
@onacit,

Just use the first property of the documentation: 
- https://springdoc.org/#properties
