### ISSUE TITLE
Jackson Converter

### ISSUE THREAD

**Issue by samuelpsfung** [springdoc/springdoc-openapi#2146]
i'm using SpringBoot 3.0.3, SpringDoc 2.0.2, Jackson 2.14.2

I use a Jackson converter to flatten a list (of string) to comma-separated string, applied to a property in my model. In the generated OpenAPI doc, the property schema is still a list, while the value is actually a string. Does SpringDoc recognize a Jackson converter is applied?

```java
public class FlattenListSerializer implements Converter<List<String>, String> {

	@Override
	public String convert(List<String> value) {
		if (value == null)
			return null;
		return String.join(",", value);
	}

	@Override
	public JavaType getInputType(TypeFactory typeFactory) {
		return typeFactory.constructParametricType(List.class, String.class);
	}

	@Override
	public JavaType getOutputType(TypeFactory typeFactory) {
		return typeFactory.constructType(String.class);
	}

}
```

```java
public class MyModel {
  	@JsonSerialize(converter=FlattenListSerializer.class)
	private List<String> myList;
}
```

**Comment by bnasslahsen** [comment]
@samuelpsfung,

You should implement your own  `io.swagger.v3.core.converter.ModelConverter`.

This question is purely related how the swagger-core library works.
