### ISSUE TITLE
@Tag on the package-info.java

### ISSUE THREAD

**Issue by onacit** [springdoc/springdoc-openapi#2147]
I'll be better when I can put the `@Tag` on a `package-info.java` so that all controllers in the package implicitly annotated.

```java
@Tag(name = "v1")
package com.mycompany.v1;

import io.swagger.v3.oas.annotations.tags.Tag;
```

```java
@Tag(name = "v2")
package com.mycompany.v2;

import io.swagger.v3.oas.annotations.tags.Tag;
```

**Comment by bnasslahsen** [comment]
@onacit,

Thank you for your proposal.
There is no current plan for it. But feel free to propose a PR, if you feel it useful for the community.
