### ISSUE TITLE
@RequestParam(required = false) Broken Since v2.0.3

### ISSUE THREAD

**Issue by ZachGagnon1** [springdoc/springdoc-openapi#2149]
**Describe the bug**
Using @RequestParam(required = false) does not work since v2.0.3. It will always show the field as required in the specifications.

**To Reproduce**

- What version of spring-boot you are using?
3.0.4
- What modules and versions of springdoc-openapi are you using?
2.0.4
- Provide with a sample code (HelloController) or Test that reproduces the problem
public ResponseEntity<Page<Object>>getObject(@RequestParam(required = false) Boolean isOpen)
**Expected behavior**
Expect the swagger docs to say the field is not required.

**Screenshots**
### V2.0.4
<img width="584" alt="v2 0 4" src="https://user-images.githubusercontent.com/55711906/226404771-931d9896-44e5-4cb3-9542-de606c4e290f.png">

### V2.0.2
<img width="584" alt="v2 0 2" src="https://user-images.githubusercontent.com/55711906/226404891-1feb54f9-89b3-4b5c-a1a7-d9927f0b7a73.png">

No code has been changed between both pictures. Only the version.

**Additional context**
Using Java 17

**Comment by bnasslahsen** [comment]
Not reproducible
![image](https://user-images.githubusercontent.com/13404829/226460784-95264cc2-10e4-48f9-b8d0-12f3e008dcd0.png)

If you provide to a GITHUB repo with a [Minimal, Reproducible Example - with HelloController](https://stackoverflow.com/help/minimal-reproducible-example) that reproduces the problem, then this ticket can be reopened.

**Comment by JoeHegarty** [comment]
We're also seeing this, setting a param/header to `required=false` has no effect (it's true anyway) in `2.0.3` and later but works fine in `2.0.2`.

**Comment by tobiberger** [comment]
Sure, why not. This should do the trick.
