### ISSUE TITLE
Utilize X-Forwarded Headers

### ISSUE THREAD

**Issue by aaron-hooper** [springdoc/springdoc-openapi#215]
Please support the X-Forwarded headers (x-forwarded-host, x-forwarded-prefix, x-forwarded-port, x-forwarded-proto) when they exist to allow the swagger docs to be properly served from behind a reverse proxy.

**Comment by springdoc** [comment]
Hi @aaron-hooper,

 The procy headers are natively supported by spring-boot.
 Please have a look at the answer of #153. This should work without any issue.

Please don't forget to give a feedback about which option resolved your issue.

**Comment by aaron-hooper** [comment]
Setting `server.forward-headers-strategy=framework` does allow the redirect to resolve, but there is still an issue with the static content. 

When accessing the app directly without going through a proxy `localhost:8080/swagger-ui.html` the static resources are resolved, ie `localhost:8080/swagger-ui/swagger-ui-bundle.js`.

However when accessing via the reverse proxy `localhost:8081/app-context/swagger-ui.html` the static resources are returning a 404 because the path is missing `/swagger-ui/` ie `localhost:8081/app-context/swagger-ui-bundle.js`.

**Comment by springdoc** [comment]
Hi, 

 You need to make sure you reverse proxy is also well configured:
 For example using apache 2:

`RequestHeader set X-Forwarded-Prefix "/custom-path"
`

 Did you try with the Bean configuration?

```java
@Bean
ForwardedHeaderFilter forwardedHeaderFilter() {
   return new ForwardedHeaderFilter();
} 
```

**Comment by aaron-hooper** [comment]
The bean configuration results in the same issue. The proxy is properly configured. I've verified this by debugging and examining the request object.

**Comment by onacit** [comment]
Is the `/custom-path` a fixed one?
