### ISSUE TITLE
PageableDefault put field mandatory

### ISSUE THREAD

**Issue by marccollin** [springdoc/springdoc-openapi#2150]
I use springdoc 2.0.3

With this code

```
    @GetMapping()
    @Operation(description ="Search editor")
    public Page<Editor> searchEditor(@RequestParam(required=false) Long editorId, 
                                                        @PageableDefault(direction = Sort.Direction.ASC,sort = "nom" ) Pageable pageable);
```

I see then pageable is mandatory.
![springdoc_pageable_mandatory](https://user-images.githubusercontent.com/4097381/226444122-ee2ba5ac-34d5-413a-8d7d-3df4a274bb61.jpg)

This field should not be mandatory

I get the same result if it put

`     @Parameter(required = false)`

I know  i can put

`     @Parameter(hidden = true)`

but the field will not be displayed anymore

**Comment by bnasslahsen** [comment]
@marccollin,

You should add `@ParameterObject` to get full `PageableDefault` support.
You have samples here: 
- https://github.com/springdoc/springdoc-openapi/blob/2.x/springdoc-openapi-tests/springdoc-openapi-data-rest-tests/src/test/java/test/org/springdoc/api/app13/HelloController.java
