### ISSUE TITLE
How to expose Swagger UI without authentication?  in spring version -3.0.0

### ISSUE THREAD

**Issue by ThavamSelvam** [springdoc/springdoc-openapi#2151]
Hi Team ,

I'm glad that found this new project instead of SpringFox which is quite outdated now!

But I'm having issues with exposing the Swagger UI without requiring authentication, can you help me with that please?
I'm using Spring Boot 3.0.0 with Spring Security Starter

Below dependency I added in POM files

 
  <dependency>
            <groupId>org.springdoc</groupId>
            <artifactId>springdoc-openapi-ui</artifactId>
            <version>1.6.14</version>
        </dependency>

But Spring security says  **Securing GET /error**

In my SecurityFilterChain I have added 

http.csrf().and().cors().disable().
                sessionManagement().sessionCreationPolicy(SessionCreationPolicy.STATELESS).and()

                .authorizeHttpRequests()
                .requestMatchers("/v3/api-docs").permitAll()
                .requestMatchers("/v2/api-docs").permitAll()
                .requestMatchers("/configuration/ui").permitAll()
                .requestMatchers("/swagger-resources/*").permitAll()
                .requestMatchers("/configuration/security").permitAll()
                .requestMatchers("/swagger-ui.html").permitAll()
                .requestMatchers("/swagger-ui/*").permitAll()
                .requestMatchers("/webjars/*").permitAll()
                .requestMatchers("/v3/*").permitAll().and().build();  
                
                
                
                And I got some security error 
                
                Attached screen for reference 
                
Set SecurityContextHolder to anonymous SecurityContext
 Saved request http://localhost:8080/error?continue to session
  Pre-authenticated entry point called. Rejecting access
  
  ![Uploading error_screen_shot.png…]()

**Comment by bnasslahsen** [comment]
@ThavamSelvam,

For `spring-boot 3`, you should use [spring boot v2](https://springdoc.org/v2)

You have full working [example here](https://github.com/springdoc/springdoc-openapi-demos/tree/2.x/demo-oauth2/oauth-resource-server-webmvc) including `spring-securty` and the `spring-oauth2-authorization-server`:

And this a sample `spring-security` configuration class:
- https://github.com/springdoc/springdoc-openapi-demos/blob/2.x/demo-oauth2/oauth-resource-server-webmvc/src/main/java/org/springdoc/demo/resource/config/SecurityConfig.java

**Comment by ThavamSelvam** [comment]
@bnasslahsen

Thanks for the update
