### ISSUE TITLE
Redunant(wrong) direction appended to @PageableDefault

### ISSUE THREAD

**Issue by onacit** [springdoc/springdoc-openapi#2152]
**Describe the bug**

With following code,

```java
    public PagedModel<Some> read(
            @PageableDefault(sort = {
                    "some,desc",
                    "other,desc",
                    "another.that,desc"
            })
            @ParameterObject final Pageable pageable) {
}
```

Swagger UI renders a redundant direction,

<img width="795" alt="Screenshot 2023-03-21 at 5 57 34 PM" src="https://user-images.githubusercontent.com/247819/226558522-3b88c832-dbe4-4691-9b0b-16b4e75fe057.png">

**Comment by bnasslahsen** [comment]
@onacit,

springdoc-openapi will reflect your code description in the annotations.
Do no mix sort and direction definitions. Use the appropriate attributes for each:
- `sort`: for the sort attributes
- `direction`: for the expected direction

Here is an example:
```java
@PageableDefault(sort = {
					"some",
					"other",
					"another.that"
			}, direction = Direction.DESC)
```

**Comment by onacit** [comment]
@bnasslahsen Thanks. The way you described is exactly what I don't want to do.

What if I want to do following?

```java
    public PagedModel<Some> read(
            @PageableDefault(sort = {
                    "some,desc",
                    "other,asc",
                    "another.that,desc"
            })
            @ParameterObject final Pageable pageable) {
}
```

Thanks, again.

**Comment by bnasslahsen** [comment]
@onacit,

If you want that syntax, you can propose a PR!

**Comment by onacit** [comment]
@bnasslahsen Thank you, sir.

I'm not intending any PR-required syntax.

The following URIs are already valid.

```
/some?sort=some%2Cdesc&sort=other%2Cdesc&sort=another.that$2Cdesc
/some?sort=some&sort=other%2C&sort=another.that$2Cdesc
```

The problem is that the UI doesn't detect the `,desc` part of each `sort` parameters, and appends `,ASC`.

Thanks.
```
/some?sort=some%2Cdesc%2CASC&sort=other%2Cdesc%2CASC&sort=another.that$2Cdesc%2CASC
```

**Comment by onacit** [comment]
Apologies, if I'm understood in a very wrong way.

?sort     |?direction |effective ?sort
--------|-----------|------------|
`some`|                 |`some,asc`
`some`| `asc`       |`some,asc`
`some`| `desc`       |`some,desc`
`some.asc`|`asc`|`some,asc`
`some,asc`| `desc`|`some,asc`
`some.desc`|`asc`|`some,desc`
`some.desc`|`desc`|`some,desc`

**Comment by onacit** [comment]
@bnasslahsen Would you please take a look at the PR? Thanks.

**Comment by onacit** [comment]
https://github.com/spring-projects/spring-data-commons/issues/2810
