### ISSUE TITLE
openApi.getServers() is null in OpenApiCustomiser when using different locales

### ISSUE THREAD

**Issue by harsel** [springdoc/springdoc-openapi#2155]
**Describe the bug**

In an OpenApiCustomiser, calling OpenApi.getServers() may return null.

**To Reproduce**

- Using latest master
- Add a bean of type OpenApiCustomiser which invokes getServers()
- Request the open api document using header `Accept-Language: en-US`
- Request the open api document using header `Accept-Language: de-DE`
- The second request fails with a NullpointerException in the OpenApiCustomiser as openApi.getServers() returns null

**Comment by bnasslahsen** [comment]
@harsel,

Can you Provide a [Minimal, Reproducible Example - with HelloController](https://stackoverflow.com/help/minimal-reproducible-example) that reproduces the problem ?

**Comment by harsel** [comment]
I already created PR #2156 with a failing test.
