### ISSUE TITLE
about the return result of "/v3/api-docs" is changed from String to a byte[]

### ISSUE THREAD

**Issue by Alleninggx** [springdoc/springdoc-openapi#2157]
https://github.com/springdoc/springdoc-openapi/commit/a33e9291d8ac41397228abfcbb86b55135f4139b

The returned result has always been String. For what reason, how do I adapt it to byte[], swagger, or third-party API tools

my returned result：
![image](https://user-images.githubusercontent.com/40049392/226777993-84bd59f7-fa17-4c84-b301-d169ff4e0707.png)

**Comment by tloubrieu-jpl** [comment]
+1 , 

I've just made the upgrade to spring-framework 6 and springdoc-openapi 2, and and was finally arn with ble to get the /api-docs end-point to return without error which is mandatory for the swager-ui to work, but I had the surprise to see a long string instead of the expected json. The same comes for the /api-docs.yaml.

Thanks for the job done though, I did not realize all of these new versions were so new.

The project we are working on and where I encounter this issue is available there https://github.com/NASA-PDS/registry-api/tree/jdk_17

**Comment by Alleninggx** [comment]
邮件已收到！

**Comment by Alleninggx** [comment]
> 
[this  https://github.com/springdoc/springdoc-openapi/issues/2143](https://github.com/springdoc/springdoc-openapi/issues/2143#issuecomment-1474981955)

This is feasible，but I don't think it's the best solution, Just transferred the "String" pain point to "byte[]"

**Comment by Alleninggx** [comment]
> [this https://github.com/springdoc/springdoc-openapi/issues/2143](https://github.com/springdoc/springdoc-openapi/issues/2143#issuecomment-1474981955
> 
> This is feasible，but I don't think it's the best solution, Just transferred the "String" pain point to "byte[]"



> +1 ,
> 
> I've just made the upgrade to spring-framework 6 and springdoc-openapi 2, and and was finally arn with ble to get the /api-docs end-point to return without error which is mandatory for the swager-ui to work, but I had the surprise to see a long string instead of the expected json. The same comes for the /api-docs.yaml.
> 
> Thanks for the job done though, I did not realize all of these new versions were so new.
> 
> The project we are working on and where I encounter this issue is available there https://github.com/NASA-PDS/registry-api/tree/jdk_17


[this  https://github.com/springdoc/springdoc-openapi/issues/2143](https://github.com/springdoc/springdoc-openapi/issues/2143#issuecomment-1474981955)

This is feasible，but I don't think it's the best solution, Just transferred the "String" pain point to "byte[]"

**Comment by bnasslahsen** [comment]
@Alleninggx,

Agree with your answer!

**Comment by tloubrieu-jpl** [comment]
Thanks very much, I was able to fix my api-docs
