### ISSUE TITLE
@EnableWebMvc will generate 404 in GraalVM native mode

### ISSUE THREAD

**Issue by yangganboy** [springdoc/springdoc-openapi#2160]
@EnableWebMvc will generate 404 error in GraalVM native mode
it run well in jvm or remove @EnableWebMvc in GraalVM native mode
please explain in doc

**Comment by bnasslahsen** [comment]
@yangganboy,

If you are reporting a bug, please help to speed up problem diagnosis by providing as much information as possible.
Please follow the [contributing guidelines](https://github.com/springdoc/springdoc-openapi/blob/8aa498b37a2cc3bdb682e7d16fcca716822a07f9/CONTRIBUTING.adoc) to provide all the required information.
