### ISSUE TITLE
[question] In/Out Headers in Swagger UI

### ISSUE THREAD

**Issue by max-grigoriev** [springdoc/springdoc-openapi#2162]
I have the latest Springboot application 3.0.4 with WebFlux. I added Swagger UI:
```
    <dependency>
        <groupId>org.springdoc</groupId>
        <artifactId>springdoc-openapi-starter-webflux-ui</artifactId>
        <version>2.0.4</version>
    </dependency>

```
And everything works OK except for two things. 

For some reason, swagger doesn't display all response headers but only `content-length` and `content-type`
<img width="438" alt="Screenshot 2023-03-22 at 16 58 12" src="https://user-images.githubusercontent.com/691931/227347380-f2554d8e-1e5c-4dc8-b594-10090a627fcd.png">
but my service returns other headers:
<img width="1309" alt="headers_full" src="https://user-images.githubusercontent.com/691931/227347693-2d22b8aa-13da-4ec6-b696-069c901c5c04.png">

The second problem is different request headers that can be set. The endpoint method doesn't know about them because they are processed by web filters. So I can't add @RequestHeader to method params. Is it possible to have just text fields where I can set any header and its value and Swagger will send them with requests?

Thank you.

**Comment by bnasslahsen** [comment]
@max-grigoriev,

Are you reporting an issue with the generated OpenAPI spec or with the swagger-ui ?

**Comment by max-grigoriev** [comment]
> @max-grigoriev,
> 
> Are you reporting an issue with the generated OpenAPI spec or with the swagger-ui ?

It's about embedded `swagger-ui` which comes with `springdoc-openapi-starter-webflux-ui`

I checked original swagger UI demo: [https://petstore.swagger.io/#/pet/findPetsByStatus](https://petstore.swagger.io/#/pet/findPetsByStatus)  and it shows all response headers
<img width="604" alt="Screenshot 2023-03-24 at 12 49 10" src="https://user-images.githubusercontent.com/691931/227602076-e89b41b8-204b-4778-815b-69e4c7247d74.png">

Also, it's an open question how can I add a custom request header to any request? We have such UI for Swagger2:
<img width="908" alt="Screenshot 2023-03-24 at 12 51 39" src="https://user-images.githubusercontent.com/691931/227602558-71b6564b-b91d-44b8-bc74-a20e0881fc4e.png">

**Comment by bnasslahsen** [comment]
@max-grigoriev,

`springdoc-openapi ` generates the OpenAPI spec in JSON/YAML format. 
It's relying on the swagger-ui project.

For any swagger-ui issues, use https://github.com/swagger-api/swagger-ui/issues
