### ISSUE TITLE
Spring Doc child context / additional dispatcherservlets ignores dispatcherservlet context for some URLs

### ISSUE THREAD

**Issue by dodtsair** [springdoc/springdoc-openapi#2164]
**Describe the bug**

I have setup a demo project, that has two dispatcherservlets: https://github.com/dodtsair/demo-swagger-ui

If I follow instructions found here: 
https://springdoc.org/#how-to-integrate-open-api-3-with-spring-project-not-spring-boot
and in addition include the following code:
```
@SpringBootApplication(
		exclude = {
				SpringDocWebMvcConfiguration.class,
				MultipleOpenApiSupportConfiguration.class,
				SwaggerConfig.class,
				SwaggerUiConfigProperties.class,
				SwaggerUiConfigParameters.class,
				SwaggerUiOAuthProperties.class,
				SpringDocConfiguration.class,
				SpringDocConfigProperties.class
		}
)
```
and in each context:
```
		applicationContext.register(
				SwaggerConfig.class,
				SwaggerUiConfigProperties.class,
				SwaggerUiConfigParameters.class,
				SwaggerUiOAuthProperties.class,
				SpringDocWebMvcConfiguration.class,
				MultipleOpenApiSupportConfiguration.class,
				SpringDocConfiguration.class,
				SpringDocConfigProperties.class,
				JacksonAutoConfiguration .class
		);
```
(This allows SpringDoc to scan the controllers in the child context, and avoids the duplicate bean definitions with springdoc beans in the parent context)

I get swaggerUI loading at the right URL, also the config, and also the openAPI spec
However the UI itself refers to an absolute path on the domain that does not include the displatcerservlet's context path, even through it renders from that path.  

http://localhost:8080/api/swagger-ui/index.html -> "Failed to load remote configuration."
You can see its trying to access: http://localhost:8080/v3/api-docs/swagger-config

http://localhost:8080/api/v3/api-docs/swagger-config -> loads fine but returns
```
{"configUrl":"/v3/api-docs/swagger-config","oauth2RedirectUrl":"http://localhost:8080/swagger-ui/oauth2-redirect.html","url":"/v3/api-docs","validatorUrl":""}
```
Notice configUrl, oauth2RredirectUlr, and url all do not have the displatchservlet's context path.  

http://localhost:8080/v3/api-docs -> does not load
http://local.kahuapp.com:8080/api/v3/api-docs -> where as this one does

**To Reproduce**

- Clone: https://github.com/dodtsair/demo-swagger-ui
- Run the server in its default configuration
- Browse to: http://localhost:8080/api/swagger-ui/index.html
    - Results: "Failed to load remote configuration."
    - Expected: See four APIs for person /api/person
- Browse to:  http://localhost:8080/internal/swagger-ui/index.html
    - Results: "Failed to load remote configuration"
    - Expected: See three APIs for log /internal/log 

- What version of spring-boot you are using: 2.7.4
- What modules and versions of springdoc-openapi are you using: 1.6.14
- What is the actual and the expected result using OpenAPI Description (yml or json): OpenAPI document looks fine
- Provide with a sample code (HelloController) or Test that reproduces the problem: See https://github.com/dodtsair/demo-swagger-ui

```
@Configuration
public class InternalDispatcherServletConfig {

    @SuppressWarnings({"rawtypes", "unchecked"})
    @Bean
    public ServletRegistrationBean internalServletRegistrationBean() {
        DispatcherServlet dispatcherServlet = new DispatcherServlet();
        AnnotationConfigWebApplicationContext applicationContext = new AnnotationConfigWebApplicationContext();

        applicationContext.register(InternalComponentScan.class);

        dispatcherServlet.setApplicationContext(applicationContext);

        ServletRegistrationBean servletRegistrationBean = new ServletRegistrationBean(dispatcherServlet, "/internal/*");
        servletRegistrationBean.setName("internalServlet");

        enableSpringDoc(applicationContext);
        return servletRegistrationBean;
    }
}
```

**Expected behavior**

- SpringDoc endpoint /swagger-ui/index.html and /v3/api-docs/swagger-config should use dispatcherservlet's context path to construct URLs

I could probably use something like https://springdoc.org/#how-can-i-set-swagger-properties-programmatically to wrangle SpringDoc into submission, but it would be nice SpringDoc could do the work itself.

**Comment by dodtsair** [comment]
Based on the implementation in:
https://github.com/springdoc/springdoc-openapi/blob/master/springdoc-openapi-ui/src/main/java/org/springdoc/webmvc/ui/SwaggerWelcomeCommon.java
and
https://github.com/springdoc/springdoc-openapi/blob/master/springdoc-openapi-ui/src/main/java/org/springdoc/webmvc/ui/SwaggerUiHome.java

I do not think it is possible to deploy to instances of swagger in separate contexts, with separate dispatcherservlets (like in the linked example).  

Also https://springdoc.org/#how-can-i-set-swagger-properties-programmatically won't help as code like SwaggerUiHome injects springdoc.swagger-ui.path by `@Value` annotation bypassing the SwaggerUiConfigProperties configuration object entirely.

**Comment by bnasslahsen** [comment]
@dodtsair,

This is not a bug but an enhancement request.
There are no plans to support multiple swagger-ui instances in within the same spring-boot applications.

**Comment by dodtsair** [comment]
@bnasslahsen 

Fixed:

```
package org.springdoc.webmvc.ui;

import org.springdoc.core.SpringDocConfigProperties;
import org.springdoc.core.SwaggerUiConfigParameters;
import org.springdoc.core.SwaggerUiConfigProperties;
import org.springdoc.core.providers.SpringWebProvider;
import org.springframework.context.annotation.Configuration;
import org.springframework.web.servlet.support.ServletUriComponentsBuilder;

import javax.servlet.http.HttpServletRequest;

@Configuration
public class SwaggerController extends SwaggerWelcomeWebMvc {
    public SwaggerController(SwaggerUiConfigProperties swaggerUiConfig, SpringDocConfigProperties springDocConfigProperties, SwaggerUiConfigParameters swaggerUiConfigParameters, SpringWebProvider springWebProvider) {
        super(swaggerUiConfig, springDocConfigProperties, swaggerUiConfigParameters, springWebProvider);
    }

    @Override
    void buildFromCurrentContextPath(HttpServletRequest request) {
        super.init();
        contextPath = request.getServletPath();
        buildConfigUrl(ServletUriComponentsBuilder.fromCurrentContextPath());
    }

}
```

Specifically I changed the line
`contextPath = request.getServletPath()`
from the original
`contextPath = request.getContextPath()`
