### ISSUE TITLE
Custom Converters are not excluded if not registered for Http Message Converter

### ISSUE THREAD

**Issue by RittikeGhosh** [springdoc/springdoc-openapi#2165]
**Bug Description**
Feature to support **Custom Spring Converter**(#1534), is generating wrong openapi specification. I think all converters are considered as Http Message Converter, which it shouldn't. Hence it is generating  the request body schema as the Source Object picked from the converter  with target as the actual Object defined in the Request Handler Method in Controller. 
This is happening for both WebMvc and WebFlux.

**To Reproduce**
Using :
- spring boot `3.0.5`
- webflux
- `org.springdoc:springdoc-openapi-starter-webflux-ui:2.0.4`

Code setup:
```java
record ObjectA() {};

record ObjectB() {};

@Component
class BToAConvertor implements Converter<ObjectB, ObjectA> {
    @Override
    public ObjectA convert(ObjectB source) {
        return new ObjectA();
    }
}

@RestController
class Controller {
    @GetMapping("/test")
    public String test(@RequestBody ObjectA request) {
        return "OK!";
    }
}
```

Output OpenApi Specification:
Generated `ObjectB` instead of `ObjectA` as request schema
```yaml
openapi: 3.0.1
info:
  title: OpenAPI definition
  version: v0
servers:
  - url: http://localhost:8080
    description: Generated server url
paths:
  /test:
    get:
      tags:
        - controller
      operationId: test
      parameters:
        - name: request
          in: query
          required: true
          schema:
            $ref: '#/components/schemas/ObjectB'
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: string
components:
  schemas:
    ObjectB:
      type: object

```

**Expected behavior**
I expect the converters to be picked only if it is registered for Http Message Converter. Here I didn't register it for that, it is used for other internal purpose. 

Expected OpenApi Specification:
```yaml
openapi: 3.0.1
info:
  title: OpenAPI definition
  version: v0
servers:
  - url: http://localhost:8080
    description: Generated server url
paths:
  /test:
    get:
      tags:
        - controller
      operationId: test
      parameters:
        - name: request
          in: query
          required: true
          schema:
            $ref: '#/components/schemas/ObjectA'
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: string
components:
  schemas:
    ObjectA:
      type: object
```

**Workaround Code**
```java
@GetMapping(value = "/test")
@Operation(requestBody = @io.swagger.v3.oas.annotations.parameters.RequestBody(
        required = true,
        content = @Content(schema = @Schema(implementation = ObjectA.class)))
)
public String test(@RequestBody ObjectA request) {
    return "OK!";
}
```

**Comment by piotrp** [comment]
A shorter workaround is to use `@Schema(implementation = ObjectA.class)` directly on parameter:

```java
@GetMapping(value = "/test")
public String test(@Schema(implementation = ObjectA.class) @RequestBody ObjectA request) {
    return "OK!";
}
```

**Comment by RittikeGhosh** [comment]
@uc4w6c But that is true when we use `@Pathvariable`, not for `@RequestBody`. Also the bean may be present in the context,  but I do not think it is registered for payload conversion.

Tried testing if string data in body can be converted to ObjectA by setting content type as text/plain, and creating String to A converter. Did not work!

```java
@Component
class StringToAConvertor implements Converter<String, ObjectA> {
    @Override
    public ObjectA convert(String source) {
        return new ObjectA(source);
    }
}

@RestController
class Controller {
    @PostMapping(value = "/test", consumes = MediaType.TEXT_PLAIN_VALUE)
    public ObjectA test(@RequestBody ObjectA request) {
        return request;
    }

    @ExceptionHandler
    public void genericException(Exception e) {
        e.printStackTrace();
    }
}
```

**THROWS**
`org.springframework.web.server.UnsupportedMediaTypeStatusException: 415 UNSUPPORTED_MEDIA_TYPE "Content type 'text/plain' not supported for bodyType=com.example.springdoc.ObjectA"`

**Comment by uc4w6c** [comment]
@piotrp 
I'm sorry. As you pointed out, the converter doesn't work with @RequestBody, so it seems that the OpenApi Specification is incorrect.

**Comment by bnasslahsen** [comment]
@RittikeGhosh,

i have added a workaround for it.
You can test it with the [latest SNAPSHOT](https://springdoc.org/v2/#how-can-i-use-the-last-springdoc-openapi-snapshot) and let us know.

**Comment by RittikeGhosh** [comment]
This works now. Tested with the latest version `2.1.0`
Thanks!
