### ISSUE TITLE
Create Yaml during gradle's build

### ISSUE THREAD

**Issue by FTorchia** [springdoc/springdoc-openapi#217]
Hi Team,

We are using springdoc-openapi with gradle, version 1.1.49.
Once the project is running we are able to access to the generated yaml document on http '/v3/api-docs.yaml'.
Is it possible to generate the document during build phase and store it into the project path?
is there any gradle instruction or simila?

thanks for support.
F Torchia

**Comment by springdoc** [comment]
Hi,

There is no springdoc-gradle-plugin planned for short term.
But you can contribute to migrate the https://github.com/springdoc/springdoc-openapi-maven-plugin into gradle, which mainly relies on spring-boot-maven-plugin.
