### ISSUE TITLE
Allow OpenAPI customizers to run even for cached OpenAPI documents

### ISSUE THREAD

**Issue by emilchitas** [springdoc/springdoc-openapi#2171]
**Is your feature request related to a problem? Please describe.**

We have a service which is accessible through a wildcard domain (`*.example.com`), and users can access this system with some specific prefixes (e.g. `prefixA.example.com`, `prefixB.example.com`). 
When serving the OpenAPI document, we make use of the OpenAPICustomizer(s) to customize the server URL to also include the common path of the APIs present in that document. 
![image](https://user-images.githubusercontent.com/37291896/227988065-6cdda5de-1773-4a21-8d29-2fc032abbbe5.png)
This was possible, until the logic to be able to customize also cached OpenAPI documents was reverted with [this PR](https://github.com/springdoc/springdoc-openapi/issues/1820).
Now, even if a client would access the document with the `https://prefixB.example.com`, it would be served the cached OpenAPI with the `https://prefixA.example.com/my/foo` server URL, which was generated when it was first accessed. 

**Describe the solution you'd like**

- We would like to have the possibility  to register some customizer which would run also for cached OpenAPI's.

**Describe alternatives you've considered**

- This can be worked around by disabling the cache, but generating the whole OpenAPI on each request gets pretty expensive, the more this grows.

**Comment by bnasslahsen** [comment]
@emilchitas,

You can use `ServerBaseUrlCustomizer`.
Cache is not applied to it.

This is a sample code:

```java
	@Bean
	ServerBaseUrlCustomizer serverBaseUrlCustomizer(){
		return serverBaseUrl -> serverBaseUrl.replace(serverBaseUrl,  UUID.randomUUID().toString());
	}
```
