### ISSUE TITLE
Problem with long numbers

### ISSUE THREAD

**Issue by omids04** [springdoc/springdoc-openapi#2174]
Hi. There is a weird problem with long numbers, but I'm not sure if this is swagger-ui problem or springdoc.
 
![1](https://user-images.githubusercontent.com/53124724/228400686-57cc9f19-118b-4a30-94b5-43b9003b4c73.png)
![3](https://user-images.githubusercontent.com/53124724/228400716-b3365c46-595f-45fd-93ea-8d85a7e4f507.png)
As you can see, values are different, and It happens for all long numbers that are bigger than a value(I'm not sure what that value is, though).
It does not happen for smaller values:
![2](https://user-images.githubusercontent.com/53124724/228401092-446b0a07-d096-4a51-9c08-8d742bec3d33.png)
![4](https://user-images.githubusercontent.com/53124724/228401292-822d7075-1b6a-4a12-ba38-5b5f6c80284d.png)

To Reproduce

- What version of spring-boot you are using? 3.0.5
- What modules and versions of springdoc-openapi are you using? springdoc-openapi-starter-webmvc-ui 2.0.4

Test code that I used:

```
   public record TestRecord(long num){}

    @GetMapping("/test")
    public TestRecord get(){
        return  new TestRecord(55555456454545455L);
    }
```

**Comment by bnasslahsen** [comment]
@omids04,

Please share the generated OpenAPI spec to confirm the root cause of the problem.

**Comment by kuza2010** [comment]
@bnasslahsen same problem here!

Declaration
```java
@Data
@AllArgsConstructor
@Schema(description = "example")
public class ExampleResponse {

    @Schema(description = "long field", example = "2395149362243048630")
    private Long id;
}
```

The UI `/swagger-ui/index.html#` shows me: 

![image](https://github.com/springdoc/springdoc-openapi/assets/32107577/0afb2f6d-362c-4a2d-9354-d1c9ac6599bb)


`v3/api-docs` output is:
```json
  "ExampleResponse": {
    "type": "object",
    "properties": {
      "id": {
        "type": "integer",
        "description": "long field",
        "format": "int64",
        "example": 2395149362243048400
      }
    },
    "description": "example"
  }
```


If you need more information, please, let me know.

**Comment by bnasslahsen** [comment]
@kuza2010,

@atetzner,

This is not handled inside springdoc-openapicode, but with `swagger-core` library.

Try to introspect

```java
		ResolvedSchema resolvedSchema = ModelConverters.getInstance()
				.resolveAsResolvedSchema(
						new AnnotatedType(ExampleResponse.class));
		System.out.println(((Schema) resolvedSchema.schema.getProperties().get("id")).getExample());
```

Feel free to log an issue for the https://github.com/swagger-api/swagger-core project.
