### ISSUE TITLE
Springdoc-openpi version 1.6.15 is showing wrong encoding when using German umlauts

### ISSUE THREAD

**Issue by dimasadryantos** [springdoc/springdoc-openapi#2176]
**Bug Description**

I upgraded the springdoc-open api to **1.6.15** and I'm using German umlauts alphabet in the openApi Yaml file when run spring-boot then compile the swagger-ui in my local it will produce wrong umlauts alphabet : 

```
street:
          type: string
          description: The name of the street ����.
          example: Sch��������nhauser Allee
```

I tried to check in the console it seems the response header for Json & Yaml are not using UTF-8 see the following pict

<img width="915" alt="Screenshot 2023-03-29 at 16 23 34" src="https://user-images.githubusercontent.com/36557656/228573797-d49db134-cba3-45d3-9b7c-d0a99ca791db.png">

<img width="915" alt="Screenshot 2023-03-29 at 16 23 52" src="https://user-images.githubusercontent.com/36557656/228574033-c1fe70e5-c052-44a8-8178-dabca87e60dc.png">

**To Reproduce**

-Create spring-boot with open-api.yaml file
-Add German umlauts chars
-Run locally
-Compile for yaml and json
-Check response headers in the network and see content type = it should be UTF-8

- What version of spring-boot you are using? Spring-boot version 2.7.10
- What modules and versions of springdoc-openapi are you using? 1.6.15
- What is the actual and the expected result using OpenAPI Description (yml or json)? Resulting correct German umlauts for yml and json swagger-ui 

**Expected behavior**

 Resulting correct German umlauts for (yml or json) swagger-ui for version **1.6.15** and  (yml or json)  should produce UTF-8 format.

**Comment by bnasslahsen** [comment]
@dimasadryantos,

Not reproducible.
This related to your client request.

![image](https://user-images.githubusercontent.com/13404829/228970721-e0a8a96e-9c9a-4a32-bbc3-47727b8054cc.png)
