### ISSUE TITLE
Enum translation

### ISSUE THREAD

**Issue by FTorchia** [springdoc/springdoc-openapi#218]
Hi team,

we have this case in Java:

`public enum Op_enum
{
    EQ(0, "="),
    NE(1, "!="),.....`

the generated yaml describe this enum like:

`          enum:
          - EQ
          - NE.....`

How can we set translation in order to use the enum 'value' instead of the enum index
i.e.: `          enum:
          - '='
          - '!=' .....`
?
Is there any kind of swagger annotation or similia?

thanks for support
F Torchia

**Comment by springdoc** [comment]
Hi, 

 You could override toString on your enum:

```java
@Override
@JsonValue
public String toString() {
	return String.valueOf(action);
}
```

Or you could use allowableValues. For example:
`@Parameter(schema = @Schema(name = "from", allowableValues = {"1", "2"}))`

**Comment by FTorchia** [comment]
Works fine, thank you for help!
