### ISSUE TITLE
Non-nullable Get Request Parameters can not be set to not required.

### ISSUE THREAD

**Issue by fsoffel** [springdoc/springdoc-openapi#2180]
**Describe the bug**

I am writing a web application with Spring in Kotlin. And I have an endpoint defined similar to the following
`
    @GetMapping(
        produces = ["application/json"]
    )
    fun getValue(
        @RequestParam something: Boolean = false
    ) :ResponseEntity<Foo>
`
Switching from springdoc:org.springdoc:springdoc-openapi-starter-webmvc-ui 2.0.2 to 2.0.4 changed the generated OpenAPI docs: 
the `require` property of the non-nullable parameter `something` changed from `false` to `true` and I can not change anything about this state. Not with the `required` property of the `RequestParam` nor the `required` property of the `Parameter` annotation.

I expected the `required` property of the `RequestParam` annotation to be regarded.

**Comment by bnasslahsen** [comment]
@fsoffel.

This is expected to be default and not a bug.
See the property https://springdoc.org/#springdoc-openapi-core-properties to disable kotlin nullable in the docs.
