### ISSUE TITLE
Fix behaviuor of required flag for schema class fields.

### ISSUE THREAD

**Issue by mikehalmamoj** [springdoc/springdoc-openapi#2185]
**Describe the bug**

In schema generated from Kotlin classes the required flag defaults to false even if the type is non-nullable. This contradicts the [openapi-generator](https://github.com/OpenAPITools/openapi-generator) which uses the required flag to determine whether a generated property is nullable.

**To Reproduce**

```
  @Schema
  val id: Long,

```
This will generate a field that is not required. It should be required as it is non-nullable.

- What version of spring-boot you are using? 
**3.0.5**
- What modules and versions of springdoc-openapi are you using?
**org.springdoc:springdoc-openapi-starter-webmvc-ui:2.0.4**

**Expected behavior**
When deciding if a field is required we need to consider the Schema annotation required attribute, the type of the field and whether there is a default value. 

If there is a schema required value then respect that.
If not then required is true for non-nullable and false for nullable.
**Except** non-nullable with a default value for which required = false.

I would suggest the following test cases:

| required? | true | true | true | true | false | false | false | false | false | false | false | true |
| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |
| schema required value | true | true | true | true | false | false | false | false | none | none | none | none |
| nullable | true | true | false | false | true | true | false | false | true | true | false | false |
| default value | true | false | true | false | true | false | true | false | true | false | true | false | true | false | true | false |

**Comment by bnasslahsen** [comment]
@mikehalmamoj,

Would you be able to propose a PR respecting the test cases you mentioned ?

**Comment by mikehalmamoj** [comment]
Fair point, I'll see what I can do.

**Comment by bnasslahsen** [comment]
@mikehalmamoj ,

I have added the requested fix. Let me know if that works for you. 

You can test it with the [latest SNAPSHOT](https://springdoc.org/v2/#how-can-i-use-the-last-springdoc-openapi-snapshot) and let us know.

**Comment by nvinogr** [comment]
I am still facing this issue, despite using `2.1.1-SNAPSHOT` version: none of the non-nullable data class fields are identified as "required" by default. 

I have created a [small repo](https://github.com/nvinogr/openapi-required-demo) to demonstrate the issue, could anyone please check and confirm my configuration & usage is correct?
