### ISSUE TITLE
How can I set a null to oneOf using @Schema annotation,Java?

### ISSUE THREAD

**Issue by akaLogan** [springdoc/springdoc-openapi#2191]
![12C832A3-C832-4EE5-9C41-4A7CE37EA7A0](https://user-images.githubusercontent.com/45533843/229438610-1fdd7423-9154-4bd2-bf8d-c7a735f31cb8.png)

**Comment by akaLogan** [comment]
Hey everyone, did you know how to add 'null' to 'oneof' field to make schema accept null value? Thank.

**Comment by bnasslahsen** [comment]
@akaLogan,

This question is realted to [swagger-core](https://github.com/swagger-api/swagger-core/wiki/Swagger-2.X---Annotations) usage. It will not be addressed here.
Remember, contributions to this repository should follow its [contributing guidelines](https://github.com/springdoc/springdoc-openapi/blob/3ef7413432fb74bbf2c14d0c433895b2610e736d/CONTRIBUTING.adoc), [security policy](https://github.com/springdoc/springdoc-openapi/blob/3ef7413432fb74bbf2c14d0c433895b2610e736d/SECURITY.md), and [code of conduct](https://github.com/springdoc/springdoc-openapi/blob/3ef7413432fb74bbf2c14d0c433895b2610e736d/CODE_OF_CONDUCT.md).
