### ISSUE TITLE
Swagger UI with provided spec broken in 1.7.0

### ISSUE THREAD

**Issue by tobi-laa** [springdoc/springdoc-openapi#2193]
**Describe the bug**

Using Springdoc + Swagger UI with a provided spec as described [here](https://springdoc.org/#what-is-a-proper-way-to-set-up-swagger-ui-to-use-provided-spec-yml) seems to be broken in version `1.7.0`. Attempting to navigate to `swagger-ui.html` yields `404 Not Found`.

**To Reproduce**

- What version of spring-boot you are using?
`2.7.10`
- What modules and versions of springdoc-openapi are you using? 
  - `springdoc-openapi-ui`
  - `springdoc-openapi-security`

**Expected behavior**

The description found [here](https://springdoc.org/#what-is-a-proper-way-to-set-up-swagger-ui-to-use-provided-spec-yml) should either be updated to reflect additional steps or should work again.

**Additional context**

The problem appears to be the newly added `org.springdoc.core.SpringDocUIConfiguration`, which is only loaded when property `springdoc.api-docs.enabled` is set to `true`. With the aforementioned description to use a provided spec, said property needs to be set to `false`.

Maybe it is possible to simply remove `@ConditionalOnExpression("${springdoc.api-docs.enabled:true}")` from `SpringDocUIConfiguration`? As an alternative, the [minimal Beans configuration](https://springdoc.org/#what-is-a-proper-way-to-set-up-swagger-ui-to-use-provided-spec-yml) might be expanded to include the contents of `SpringDocUIConfiguration`.

**Comment by Kavan72** [comment]
@tobi-laa you are right, it's also broken for latest version of spring boot with version 2.1.0

**Comment by mrmacow** [comment]
+1 for 2.1.0 getting NS_CORRUPTED_ERROR and Swagger not rendering - 2.0.4 works perfectly

**Comment by blulic** [comment]
Hi! Do you plan to release updated SpringDoc 1.7.x  with this fix? Or we should revert to the earlier 1.6.x versions for Spring Boot 2.7.x ? Thanks!
