### ISSUE TITLE
Add custom description and example responses to actuator endpoints

### ISSUE THREAD

**Issue by mikelhamer** [springdoc/springdoc-openapi#2195]
I noticed that when I set `springdoc.show-actuator=true` it doesn't have any description of the endpoints, or the proper example responses. For example /actuator/health does not show the "status": "UP" response or have any schema definition.

**Comment by bnasslahsen** [comment]
@mikelhamer,

There is no planned enhancement on the descriptions of the actuator endpoints.
If you have a nice idea, please feel free to propose a PR.
