### ISSUE TITLE
springdoc.swagger-ui.try-it-out-enabled property not working

### ISSUE THREAD

**Issue by mikelhamer** [springdoc/springdoc-openapi#2196]
I have set `springdoc.swagger-ui.try-it-out-enabled=false` but the feature is still enabled in my docs

**Comment by uc4w6c** [comment]
This issue seems to be caused by swagger ui.
https://github.com/swagger-api/swagger-ui

**Comment by mikelhamer** [comment]
@uc4w6c any idea what is causing it, specifically?

**Comment by uc4w6c** [comment]
@mikelhamer 
yes.
But I don't think it's a good idea to have a conversation here.
Let's have a conversation in swagger ui issue.
Or create a PR if I have time.
