### ISSUE TITLE
Customize <title> of generated swagger-ui html

### ISSUE THREAD

**Issue by mikelhamer** [springdoc/springdoc-openapi#2197]
The title of the Swagger UI docs just says "Swagger UI", I would like to be able to customize this.

**Comment by uc4w6c** [comment]
I think it's good to create an issue on swagger ui as well.
https://github.com/swagger-api/swagger-ui

**Comment by mikelhamer** [comment]
@uc4w6c I just opened https://github.com/swagger-api/swagger-ui/issues/8562 , will report back here if I learn anything.

**Comment by uc4w6c** [comment]
Would you like to close this issue?
I think it would be better to create an issue again when swagger ui supports it.
