### ISSUE TITLE
Nullpointerexception with Spring Security

### ISSUE THREAD

**Issue by hc-codersatlas** [springdoc/springdoc-openapi#22]
Hi, I tried to use this with Spring Security and get:

17:03:04.897 ERROR: org.springframework.core.log.CompositeLog.error() - [4eb87eeb/6] 500 Server Error for HTTP GET "/api-docs": java.lang.NullPointerException
	at org.springdoc.core.RequestBuilder.build(RequestBuilder.java:36)

It works without Spring Security, so only change...

Can you please take a look? Thanks.

**Comment by springdoc** [comment]
Hi, 

 Not able to reproduce the issue with spring-security using spring-boot 2.
 You need to describe your configuration context:

- springdoc-openapi version.
- spring-boot version.
- The spring-security configuration that causes the issue.
- If you feel confident about the issue, you can try to reproduce it on: 
  - https://github.com/springdoc/springdoc-openapi-demos/

**Comment by springdoc** [comment]
No news about the reproduction of the issue.
