### ISSUE TITLE
404 error with spring doc open api 2.1.0

### ISSUE THREAD

**Issue by nidhikaushal** [springdoc/springdoc-openapi#2204]
Hi,
I am facing a similar issue. On accessing https://somecomp.com/service1/swagger-ui.html it redirects to https://somecomp.com/service1/swagger/index.html and then returns error 404.
I am using 'spring-boot-starter-webflux:3.0.3' with 'springdoc-openapi-starter-webflux-ui:2.1.0'. Following is the configuration in my application.yml:

`springdoc:
  packagesToScan: com.somecomp
  swagger-ui:
    defaultModelsExpandDepth: -1
    path: "/swagger-ui.html"
  webjars:
      prefix: /service1

Is there a way to disable the redirection and render swagger from https://somecomp.com/service1/swagger-ui.html

**Comment by nidhikaushal** [comment]
So the problem is, my service sits behind API Gateway, when the request is routed to my service the url used for routing is https://somecomp.com/swagger-ui.html hence when the swagger redirects it redirects to 'https://somecomp.com/webjars/swagger-ui/index.html'. The request goes back to the api gateway and since the service is missing the routing fails. 

Now I have created a WebFilter to add the service1 explicitly for requests that have uri as '/webjars/swagger-ui'. 

But this still does not work and swagger-config is failing :
springdoc:
  api-doc:
    path: /service1/v3/api-docs
  packagesToScan: com.somecomp
  swagger-ui:
    defaultModelsExpandDepth: -1
    path: "/swagger-ui.html"
    configUrl: /service1/v3/api-docs/swagger-config
  webjars:
    prefix: /service1/webjars
    
 I have added the same logic to append the service name in case of uri as /v3/api-docs/swagger-config and /v3/api-docs. But I am getting 404 when rendering 'https://somecomp.com/v3/api-docs/swagger-config'.
Response is : 
{"timestamp":"2023-04-14T12:40:06.453+00:00","path":"/v3/api-docs/swagger-config","status":404,"error":"Not Found","message":null,"requestId":"948e9383-17"}

**Comment by matt-hires** [comment]
For me this issue was resolved by adding:

```xml
<dependency>
	<groupId>org.webjars</groupId>
	<artifactId>webjars-locator</artifactId>
	<version>0.45</version>
</dependency>
```

The locator was removed with the following commit:
https://github.com/springdoc/springdoc-openapi/commit/bcaa2577

Unfortunately I was not able to understand why this was done, maybe to not depend on the locator directly but this is just an assumption.

Anyways this was necessary that the resource `/swagger-ui/index.html` could be resolved in:
https://github.com/springdoc/springdoc-openapi/blob/10bd99114ebd75e0de049fcf13adc3c450420598/springdoc-openapi-ui/src/main/java/org/springdoc/webmvc/ui/SwaggerResourceResolver.java#L31-L31

The application is using the following setup:
```xml
<dependency>
	<groupId>org.springdoc</groupId>
	<artifactId>springdoc-openapi-starter-webmvc-ui</artifactId>
	<version>2.1.0</version>
</dependency>

<dependency>
	<groupId>org.webjars</groupId>
	<artifactId>webjars-locator</artifactId>
	<version>0.45</version>
</dependency>
```

**Comment by nidhikaushal** [comment]
Hi @matt-hires , I tried the above but it does not solve my problem. If there is any way by which swagger ui renders without redirection probably that would work best, but the above workaround I have put in place also works.

**Comment by mschout** [comment]
In case it helps anyone here, I ran into this when upgrading to Spring Boot 3.2.0.  Suddenly `/swagger-ui/index.html` no longer worked with 404 due to missing `index.html`.  Solution was to explicitly add this dependency back:

```
    <dependency>
      <groupId>org.webjars</groupId>
      <artifactId>webjars-locator-core</artifactId>
      <version>0.55</version>
    </dependency>
```
