### ISSUE TITLE
java.lang.NoSuchMethodError: 'io.swagger.v3.oas.models.media.Schema io.swagger.v3.oas.models.media.Schema.addProperty(java.lang.String, io.swagger.v3.oas.models.media.Schema)

### ISSUE THREAD

**Issue by siddharthvnk1008** [springdoc/springdoc-openapi#2205]
**java.lang.NoSuchMethodError: 'io.swagger.v3.oas.models.media.Schema io.swagger.v3.oas.models.media.Schema.addProperty(java.lang.String, io.swagger.v3.oas.models.media.Schema)**

- In RequestBodyInfo.java:93 unable to find this method mergedSchema.addProperty(paramName, schemaN);
- addProperty is not found

**To Reproduce**

- springBootVersion = "3.0.2"
- org.springdoc:springdoc-openapi-starter-webmvc-ui:2.1.0
- once the service is running Failed to load API definition

**Expected behavior**

- Api should load

**Screenshots**
<img width="1438" alt="Screenshot 2023-04-13 at 6 43 44 PM" src="https://user-images.githubusercontent.com/46199168/231770324-1d29865f-4d36-42f0-a077-8eb42faf2fa9.png">
<img width="1083" alt="Screenshot 2023-04-13 at 6 44 15 PM" src="https://user-images.githubusercontent.com/46199168/231770336-96576846-08ec-44fb-920b-a032bc5a8c23.png">
<img width="1392" alt="Screenshot 2023-04-13 at 6 44 33 PM" src="https://user-images.githubusercontent.com/46199168/231770341-555b7c1a-7cb3-405b-b43a-a6a59a8d728e.png">

**Comment by bnasslahsen** [comment]
@siddharthvnk1008,

You are declaring wrong swagger-core dependencies.
Your project should not declare any swagger dependencies.
You just need to declare `springdoc-openapi` that will ship the correct versions for you.

See demos, for more details:
- https://springdoc.org/v2/#demos

**Comment by siddharthvnk1008** [comment]
> * org.springdoc:springdoc-openapi-starter-webmvc-ui:2.1.0

I have declared only this dependency which is as part of the documentation
org.springdoc:springdoc-openapi-starter-webmvc-ui:2.1.0

**Comment by wojciechcwek** [comment]
@mgvinuesa
I'm facing the same issue, after upgrading spring boot 2 to spring boot 3. I use spring-doc and avro and maven. Can you show an example how you solved?

**Comment by a13519** [comment]
swagger is garbage, full of exceptions

**Comment by wh81752** [comment]
> Hello, this error appears when in transitive mode appears other swagger dependencies, in my case due to I use AVRO and the wrong swagger dependency generate a internal conflict. I have excluded the dependency and now it works.
> 
> ![image](https://user-images.githubusercontent.com/11572462/249500339-877d4c3c-db89-4593-a0e7-f00c1fc8cc72.png)

Perfect! Solved my problem and made -- almost -- my day. Thanks.

**Comment by matijatrajkovic993** [comment]
> Hello, this error appears when in transitive mode appears other swagger dependencies, in my case due to I use AVRO and the wrong swagger dependency generate a internal conflict. I have excluded the dependency and now it works.
> 
> ![image](https://user-images.githubusercontent.com/11572462/249500339-877d4c3c-db89-4593-a0e7-f00c1fc8cc72.png)

This helped me out too! Thank you very much!

**Comment by smile-yushu** [comment]
> @siddharthvnk1008,
> 
> You are declaring wrong swagger-core dependencies. Your project should not declare any swagger dependencies. You just need to declare `springdoc-openapi` that will ship the correct versions for you.
> 
> See demos, for more details:
> 
> * https://springdoc.org/v2/#demos

This helped me out too! Thank you very much!

**Comment by YaroslavRenhevych** [comment]
I had a similar issue because there were some dependencies from the group "io.springdox" on the classpath as transitive ones.

**Comment by FeridQuluzade** [comment]
I am already using Spring Boot 3.2.6, and the same problem occurred. These dependencies fixed my problem:

```
implementation 'org.springdoc:springdoc-openapi-starter-webmvc-ui:2.2.0'
implementation 'io.swagger.core.v3:swagger-annotations-jakarta:2.2.10'
implementation 'io.swagger.core.v3:swagger-core:2.2.10'
```
