### ISSUE TITLE
swagger-initializer.js is sent endcoded in the JVM's default charset

### ISSUE THREAD

**Issue by roded** [springdoc/springdoc-openapi#2207]
**Describe the bug**

The `swagger-initializer.js` file being accepted by the browser is in the the JVM's default charset.
So on systems in which the default charset isn't UTF*, the browser seems to be getting a file which is unreadable.
Downloading the file and opening it up in the system's default encoding shows the correct contents.

**To Reproduce**
You'll have to load the JVM with a non-default charset.

- What version of spring-boot you are using?
2.7.10

- What modules and versions of springdoc-openapi are you using?
`springdoc-openapiUi = "org.springdoc:springdoc-openapi-ui:1.7.0"`

- What is the actual and the expected result using OpenAPI Description (yml or json)?
N/A, the OpenAPI JSON loads fine

- Provide with a sample code (HelloController) or Test that reproduces the problem
N/A

**Expected behavior**
- A clear and concise description of what you expected to happen.
The `swagger-initializer.js` file accepted by the browser should be readable.

- What is the expected result using OpenAPI Description (yml or json)?
N/A

**Screenshots**
![image](https://user-images.githubusercontent.com/903037/232021536-bebe82b7-41ee-4d0f-b7d0-24b44f5d676e.png)
![image](https://user-images.githubusercontent.com/903037/232021571-2b8cca11-de0c-420c-93b5-47e03d5594a7.png)

**Additional context**
N/A

**Comment by bnasslahsen** [comment]
@roded,

Your issue is not reproducible.
Without Provide a [Minimal, Reproducible Example - with HelloController](https://stackoverflow.com/help/minimal-reproducible-example) that reproduces the problem, or directly proposing a PR, we can do nothing for your issuel

**Comment by roded** [comment]
@bnasslahsen , of course, apologies.

See here for a reproduction: https://github.com/roded/springdoc-openapi-issue-2207

I suspect that the issue is the following snippet in `SwaggerIndexPageTransformer` which does not specify a charset in `getBytes()`:

```
if (isIndexFound) {
    String html = defaultTransformations(resource.getInputStream());
    return new TransformedResource(resource, html.getBytes());
}
```

The issue does not reproduce when running on JDK 18, not sure why that is.

**Comment by bnasslahsen** [comment]
@roded,

Issue reproduced and should be fixed.

**Comment by roded** [comment]
Much obliged @bnasslahsen . When is a new release expected? TY

**Comment by bnasslahsen** [comment]
Hopefully, by the end of this month
