### ISSUE TITLE
Is it possible to add on the swagger UI some stats related to the endpoints defined in the api-docs ?

### ISSUE THREAD

**Issue by ghevge** [springdoc/springdoc-openapi#2208]
Is it possible to add on the swagger UI some stats related to the endpoints defined in the api-docs ?
 eg:
- To see how many endpoints are available 
- To see how many GETs / POSTs / PUTs / DELETEs endpoints are available
- any other stats that might be relevant to others

**Comment by bnasslahsen** [comment]
@ghevge,

This is an enhancement request in the [swagger-ui](https://github.com/swagger-api/swagger-ui/issues) and not springdoc-openapi.
