### ISSUE TITLE
incorrect url while behind spring cloud gateway 

### ISSUE THREAD

**Issue by esotericman** [springdoc/springdoc-openapi#2209]
gateway routes all `/dev/micro-service/**` to my micro-service,but springdoc access error url like bellow:
```
http://127.0.0.1:8080/micro-service/v3/api-docs/swagger-config
```
correct is 
```
http://127.0.0.1:8080/dev/micro-service/v3/api-docs/swagger-config
```
refer to [reverse-proxy](https://springdoc.org/v2/#how-can-i-deploy-springdoc-openapi-starter-webmvc-ui-behind-a-reverse-proxy),I add 
```
server.forward-headers-strategy=framework
```
to my micro-service,but got
```
http://127.0.0.1:8080/dev/v3/api-docs/swagger-config
```
as you see,It seems like `server.servlet.context-path` ignored,
I use spring boot 3.0,any soultions?  Or how can I rewrite the springdoc contextPath in runtime programmatically, thanks!

**Comment by esotericman** [comment]
change ` server.servlet.context-path=/micro-service` to `spring.mvc.servlet.path=/micro-service`,It works now,Not support `server.servlet.context-path`?

**Comment by bnasslahsen** [comment]
Only `spring.mvc.servlet.path` is supported.
i confirm that `server.servlet.context-path` is not yet supported.
