### ISSUE TITLE
Can you support GRPC?

### ISSUE THREAD

**Issue by Jamel-jun** [springdoc/springdoc-openapi#2211]
If you ❤️ this project consider becoming a [sponsor](https://github.com/sponsors/springdoc).
If you already use the `springdoc-openapi`, please do not forget adding a ***github star*** to this repository.

**Is your feature request related to a problem? Please describe.**

- A clear and concise description of what the problem is. Ex. I'm always frustrated
  when [...]
- What is the actual result using OpenAPI Description (yml or json)?

**Describe the solution you'd like**

- A clear and concise description of what you want to happen.
- What is the expected result using OpenAPI Description (yml or json)?

**Describe alternatives you've considered**

- A clear and concise description of any alternative solutions or features you've
  considered.

**Additional context**

- Add any other context or screenshots about the feature request here.

**Comment by bnasslahsen** [comment]
@Jamel-jun,

There are no plans for GRPC support.
