### ISSUE TITLE
Native compiled spring app with swagger-ui produces HTTP 404

### ISSUE THREAD

**Issue by Spartan117ch** [springdoc/springdoc-openapi#2215]
Spring native compiled server does not show http://localhost:8080/swagger-ui/index.html you get a HTTP 404

Add this to pom.xml
```
<parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>3.0.5</version>
    </parent>

        <dependency>
            <groupId>org.springdoc</groupId>
            <artifactId>springdoc-openapi-starter-webmvc-ui</artifactId>
            <version>2.1.0</version>
        </dependency>
```
set this properties in my example application.yml
```
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
```
Execute `mvn -Pnative native:compile`

`GET /v3/api-docs/swagger-config` works and delivers the openapi spec

`GET /swagger-ui/index.html` you get a HTTP 404

**Expected behavior**
With just this propertie swagger-ui.enabled set to true, it should show me the swagger-ui as native or jvm.

**Workaround 1**
If you set the swagger-ui.version,  you get the Swagger-ui from native server. Because in the SpringDocUIConfiguration is the logic implemented to load it then.
```
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    version: 4.18.2
```
**Workaround 2**
If you set this resourcehint all the subdirectories and files are picked up and it also works and it is my preferred way to solve this actually so you dont have to maintain the version.
```
public class RuntimeHints implements RuntimeHintsRegistrar {
    @Override
    public void registerHints(org.springframework.aot.hint.RuntimeHints hints, ClassLoader classLoader) {
        //swagger resources welches von beiden zieht noch teste
        hints.resources().registerPattern("META-INF/resources/webjars/*");
    }
}
```

Hope this is clear enough to help.
Greetings and nice weekend.

**Comment by uc4w6c** [comment]
Your issue is not reproducible.
Please provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) that reproduces the problem.

Do you have a `springdoc.api-docs.path` setting in your application.yaml?
Is `GET /v3/api-docs` a response?

**Comment by bnasslahsen** [comment]
This ticket will be closed. But can be reopened if the relevant missing information is provided.
