### ISSUE TITLE
@Schema not picked up by swagger UI at entity field when @QuerydslPredicate predicate root type is used at controller

### ISSUE THREAD

**Issue by galegofer** [springdoc/springdoc-openapi#2216]
First at all not sure if it is an issue or a feature.

**Describe the bug**

When you have an endpoint which receives a QuerydslPredicate and the root is a JPA Entity, if you annotate the entity fields with @Schema, this is not getting reflected in the swagger-ui documentation.

**To Reproduce**

Create an Sprint boot webmvc endpoint:

@Override
    @GetMapping(produces = APPLICATION_JSON_VALUE)
    @ResponseStatus(OK)
    @ResponseBody
    public String getEntity(@ParameterObject @QuerydslPredicate(root = Entity.class) Predicate predicate) {
        return aRepository(predicate);
    }

and the entity being:

@NoArgsConstructor
@Immutable
@Entity
@Getter
@Setter(PROTECTED)
@Table(name = "MY_ENTITY")
@FieldDefaults(level = PRIVATE)
public class Entity {
    @Id
    @Column(name = "ENTITY_UID")
    String uid;

    @Schema(allowableValues = {"A", "B"}) // To restrict filed to "A" and "B" values
    @Column(name = "TYPE")
    String type;

    @Schema(implementation = String.class) // To force the param as an String instead of a date at the swagger
    @Column(name = "VALID_FROM")
    OffsetDateTime validFrom;
}

**Expected behavior**

"type" is not restricted to option "A" and "B" in the swagger ui, but it should only allow "A" and "B" in a dropbox
"validFrom" is taken as a string(date-time), but it should be string

**Screenshots**

**Additional context**

**Comment by bnasslahsen** [comment]
@galegofer,

Please make sure you provide a clear description and use the GitHub code formatting.
You should also provide a [Minimal, Reproducible Example - with HelloController](https://stackoverflow.com/help/minimal-reproducible-example) that reproduces the problem.
