### ISSUE TITLE
Jackson databind 2.14.2 breaks example generation

### ISSUE THREAD

**Issue by pablocarle** [springdoc/springdoc-openapi#2217]
**Describe the bug**

When using Spring Boot without `io.spring.dependency-management` with springdoc 1.7.0, jackson-databind is resolved to `2.14.2` which breaks schema serialization by adding `example: null` if it's not explicitly defined.
In normal situation, this value is not present in the JSON response from springdoc, and the example is auto-completed based on the schema of the response object. This is interpreted by the frontend as the literal `null` (see screenshots)

*Important:* This is only happening when `springdoc.writer-with-order-by-keys` is `true`

I managed to trace it to https://github.com/FasterXML/jackson-databind/blob/2.15/src/main/java/com/fasterxml/jackson/databind/introspect/AnnotatedMethodCollector.java#L53 where it resolved to `SortedSchemaMixin` and since `getExample` is annotated with `@JsonInclude(CUSTOM)`, this is defaulted to null serialization. I couldn't find the breaking change in jackson though.

Forcing jackson-databind to 2.13.5 works fine.

**To Reproduce**

- Spring Boot 2.7.10/2.7.11
- spring-doc-openapi-ui: 1.7.0
- What is the actual and the expected result using OpenAPI Description (yml or json)? JSON

**Expected behavior**

Previous releases do not include the `example` field in the JSON response if it's not defined.

**Screenshots**
<img width="1457" alt="image" src="https://user-images.githubusercontent.com/3085193/234002180-a8f9706b-33be-4cb1-840b-675efbac6970.png">

**Additional context**
Attached sample project, by default breaking.
* `springdoc.writer-with-order-by-keys` to `false` --> works
* Forcing jackson-databind 2.13.5 with either spring boot dependency management or explicitly --> works

[demo.zip](https://github.com/springdoc/springdoc-openapi/files/11310716/demo.zip)
.

**Comment by vupham04** [comment]
Can confirm that I got this error too. The field "example": null is auto generated with jackson-databind 2.15

**Comment by bnasslahsen** [comment]
closed as no response for more than 3 weeks.

**Comment by MVTalent** [comment]
Similar issue on springdoc 1.6.6 and jackson-databind 2.15.2
![image](https://github.com/springdoc/springdoc-openapi/assets/14983919/ff5527cd-33ca-41c0-b840-639bb56da7a1)

**Comment by MVTalent** [comment]
Solved the problem like this:
1) updated dependency from 1.6.6 to 1.6.15 and excluded swagger-annotations
```
<dependency>
	<groupId>org.springdoc</groupId>
	<artifactId>springdoc-openapi-webflux-ui</artifactId>
	<version>1.6.15</version>
	<exclusions>
		<exclusion>
			<groupId>io.swagger.core.v3</groupId>
			<artifactId>swagger-annotations</artifactId>
		</exclusion>
	</exclusions>
</dependency>
```
2) added dependency
```
<dependency>
	<groupId>io.swagger.core.v3</groupId>
	<artifactId>swagger-annotations</artifactId>
	<version>2.2.14</version>
</dependency>
```

**Comment by pablocarle** [comment]
Hi, @bnasslahsen I see that this was fixed in the main branch, which I assume it's targeted only to v2.x (since I don't see other branches in the repository)
Will you backport this commit (https://github.com/springdoc/springdoc-openapi/commit/2ae49927aabab8419d5e7f51defa5d0a2b52229b) to the 1.x springdoc? It would fix this issue and allow us to upgrade jackson-databind, until we can claim support of Java 17 for the Spring Boot 3 migration.

**Comment by bnasslahsen** [comment]
``springdoc-openapi v1.7.0 `` is the latest Open Source release supporting Spring Boot 2.x and 1.x. 

An extended support for [*springdoc-openapi v1*](https://springdoc.org/v1) 
project is now available for organizations that need support beyond 2023.
