### ISSUE TITLE
Cannot define extension with complicated structure

### ISSUE THREAD

**Issue by pugangxa** [springdoc/springdoc-openapi#2218]
If you ❤️ this project consider becoming a [sponsor](https://github.com/sponsors/springdoc).
If you already use the `springdoc-openapi`, please do not forget adding a ***github star*** to this repository.

**Is your feature request related to a problem? Please describe.**

- A clear and concise description of what the problem is. Ex. I'm always frustrated
I want to add an extension which should build to the yaml like:
```
      x-custom-extension:
        keys:
        - foo: bar
        - bar: foo
```
This cannot be done now

- What is the actual result using OpenAPI Description (yml or json)?
Now because the value must be String for and extension so cannot define extensions with structure.

**Describe the solution you'd like**
I expect the annotation should be :
```
                    @Extension(
                            name = "x-custom-extension",
                            properties = {
                                @ExtensionProperty(name = "keys", value = {
                                    @ExtensionProperty(name = "foo", value = "bar"),
                                    @ExtensionProperty(name = "bar", value = "foo")
                                })
                            }
                        )
```
- A clear and concise description of what you want to happen.
- What is the expected result using OpenAPI Description (yml or json)?

**Describe alternatives you've considered**

- A clear and concise description of any alternative solutions or features you've
  considered.

**Additional context**

- Add any other context or screenshots about the feature request here.

**Comment by bnasslahsen** [comment]
@pugangxa,

You can read this article which describes how to use extensions:
- https://dzone.com/articles/extending-swagger-and-spring-doc-open-api
