### ISSUE TITLE
Add support for MatrixVariable

### ISSUE THREAD

**Issue by yelhouti** [springdoc/springdoc-openapi#2219]
**Is your feature request related to a problem? Please describe.**

- When using matrixVariable the param is not added.
- json:
```json
{"tags":["product-location-resource"],"operationId":"getProductLocation","responses":{"200":{"description":"OK","content":{"*/*":{"schema":{"$ref":"#/components/schemas/ProductLocationDTO"}}}}}}
```

as you can see parameters are missing.

**Describe the solution you'd like**

Have the ability to specify the id manually. ideally specify the fields one by one or just have a tsring for all
- What is the expected result using OpenAPI Description (yml or json)?
```json
{"tags":["product-location-resource"],"operationId":"getProductLocation","parameters": [{"name": "id", "in": "path", "required": true, "schema": {"type": "integer", "format": "string"}}],"responses":{"200":{"description":"OK","content":{"*/*":{"schema":{"$ref":"#/components/schemas/ProductLocationDTO"}}}}}}
```

**Describe alternatives you've considered**

- I tried adding the param manually, it didn't seem to be taken into account.
Using:
```java
 @GetMapping("/product-locations/{id}")
    public ResponseEntity<ProductLocationDTO> getProductLocation(
        @Parameter(name="id", in = ParameterIn.PATH, required = true, example = "productId=1;locationId=1", description = "id as matrix variable", schema = @Schema(type = "string", format = "string"))
        @MatrixVariable(pathVar = "id") Map<String, String> idMap
    ) {
```

**Additional context**

- Add any other context or screenshots about the feature request here.

**Comment by bnasslahsen** [comment]
@yelhouti,

Unfortunately, there is no current plans to support this annotation.
Feel free to propose directly a PR, if you find it useful for the community.
