### ISSUE TITLE
Same path + HTTP operation , different produces and consumes section

### ISSUE THREAD

**Issue by Andrew3431** [springdoc/springdoc-openapi#222]
Hi, I have requirement to publish same path and HTTP operation , but having different produces and consumes section. Currently only one api appears in the swagger ui. Is this feature supported in springdoc-openapi ?

**Comment by timpamungkas** [comment]
I'm facing same issue

**Comment by springdoc** [comment]
Hi, 

 For the same path and HTTP operation, with different produces/consumes, it should publish a single API description. This is the only possible way, to be compliant with OpenAPI specification.
 But on the response/requestBody level - you should have the different types of produces/consumes related to both of your operation

 You can have a look at the following example:
 - https://github.com/springdoc/springdoc-openapi/blob/master/springdoc-openapi-webmvc-core/src/test/java/test/org/springdoc/api/app44/SpringDocApp44Test.java

 If you need more options, please  add more details about your request :
- What is the description of the actual behaviour ?
- What are the actual and the expected result using OpenAPI Description (yml or json)?
- Provide with a sample code code to reproduce it?

**Comment by Andrew3431** [comment]
@ghost @bnasslahsen  My use case is that I have an api `api/customers` with produces section as `application/json` which is deprecated. The newer api `api/customers` which is paginated has produces section as ` application/sample.customers.list+json`. Although we support both currently , I still want to show the old api as deprecated in the swagger documentation.

```java
@Operation(summary = "(Deprecated) List all customers ",
            description =
                    "List all customers. Use paginated api for latest support")
    @ApiResponses(value = {
            @ApiResponse(responseCode = "200", description = "ok"),
            @ApiResponse(responseCode = "400", description = "invalid request", content = @Content)
     })
    @RequestMapping(path = "api/customers", method = RequestMethod.GET, produces =     
            {APPLICATION_JSON_VALUE})
    @Deprecated
    @ResponseBody
    public List<Customers> list(........) { ....... }


@Operation(summary = " List customers in paginated way",
            description = "List all customers (is paginated).")
@ApiResponses(value = {
            @ApiResponse(responseCode = "200", description = "ok"),
            @ApiResponse(responseCode = "400", description = "invalid request", content = @Content)
          })
    @RequestMapping(path = "api/customers", method = RequestMethod.GET, produces = 
            {PaginatedCustomerMediaType})
    @ResponseBody
    public CustomerList<Customer> customerListPaginated( .... ) {.....}

```

Both of the apis are still in use and I want to show one of them as deprecated in swagger. Any help is highly appreciated.

**Comment by bnasslahsen** [comment]
@Andrew3431, 

I don't think what you are trying to achieve is possible using the same path, using OAS3.

**Comment by andrew-alchemy** [comment]
@Andrew3431 I am having similar challenges in trying to document a versionned API that uses media type rather than URI path (a decision I am starting to regret). One solution is to define the V1, V2 endpoints as separate APIs e.g.

```
	@Bean
	public GroupedOpenApi userApiVersion1() {
		return GroupedOpenApi.builder()
				.group("wisetail-users-v1")
				.packagesToScan("com.wisetail.api")
				.producesToMatch( EndpointVersion.V1 ) 
				.pathsToMatch("/user/**")
				.build();
	}
	@Bean
	public GroupedOpenApi userApiVersion2() {
		return GroupedOpenApi.builder()
				.group("wisetail-users-v2")
				.packagesToScan("com.wisetail.api")
				//NB. this is a strict comparison.. must match exactly the produces of the endpoint. if the endpoint has 2 "produces" we need both here
				// It is not an "OR" like with the paths and packages
				.producesToMatch( EndpointVersion.DEFAULT, EndpointVersion.V2 )
				.pathsToMatch("/user/**")
				.build();
	}

```

@bnasslahsen do you see any issues with this approach?
