### ISSUE TITLE
springdoc.swagger-ui.url not working as expected

### ISSUE THREAD

**Issue by crazycatMyopic** [springdoc/springdoc-openapi#2225]
based on this [url](https://springdoc.org/#how-can-use-custom-jsonyml-file-instead-of-generated-one) I should be able to use a custom json file (with the Open 3 specification) but i'm unable to, my code keeps giving me 404 not found. The path placed is correct btw.

why is this feature not working?

**Comment by moravcik94** [comment]
Hello,
I have same problem,
temporary workaround is to add dependency:
```
<dependency>
	<groupId>org.webjars</groupId>
	<artifactId>webjars-locator</artifactId>
	<version>0.45</version>
</dependency>
```
More here: #2204

**Comment by uc4w6c** [comment]
Your issue is not reproducible.
Please provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) that reproduces the problem.

I think that the files placed in resources are probably set to not be published.
e.g. `spring.web.resources.add-mappings` is set to false

**Comment by youtae** [comment]
I have the same issue in 2.1.0.

now, I solved this issue like this

I added this to my property file

springdoc.packagesToScan=your.package

**Comment by elgleidson** [comment]
I have similar issue, but with webflux:

```
<parent>
   <groupId>org.springframework.boot</groupId>
   <artifactId>spring-boot-starter-parent</artifactId>
   <version>3.0.6</version>
   <relativePath/> <!-- lookup parent from repository -->
</parent>
```

My dependencies:
```
<dependency>
	<groupId>org.springframework.boot</groupId>
	<artifactId>spring-boot-starter-webflux</artifactId>
</dependency>
...
<dependency>
    <groupId>org.springdoc</groupId>
    <artifactId>springdoc-openapi-starter-webflux-api</artifactId>
    <version>2.1.0</version>
</dependency>
```

No configuration at all:
http://localhost:8080/v3/api-docs -> OK
http://localhost:8080/swagger-ui.html -> 404
http://localhost:8080/swagger-ui/index.html -> 404
http://localhost:8080/webjars/swagger-ui/index.html -> 404

I've tried @moravcik94 workaround dependency + @youtae property but it is not working in my case.

**Comment by elgleidson** [comment]
Previously it was working fine:
```
<parent>
  <groupId>org.springframework.boot</groupId>
  <artifactId>spring-boot-starter-parent</artifactId>
  <version>2.7.11</version>
  <relativePath/> <!-- lookup parent from repository -->
</parent>
```
Dependencies:
```
<dependency>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-starter-webflux</artifactId>
</dependency>
<dependency>
    <groupId>org.springdoc</groupId>
    <artifactId>springdoc-openapi-webflux-ui</artifactId>
    <version>1.7.0</version>
</dependency>
```

http://localhost:8080/v3/api-docs -> OK
http://localhost:8080/swagger-ui.html -> OK
http://localhost:8080/webjars/swagger-ui/index.html -> OK

**Comment by elgleidson** [comment]
I create a reproducible example: https://github.com/elgleidson/springdoc-webflux-issue

**Comment by elgleidson** [comment]
Sorry guys, I must have copied the dependency wrong 🙈
Wrong:
```
<dependency>
    <groupId>org.springdoc</groupId>
    <artifactId>springdoc-openapi-starter-webflux-api</artifactId>
    <version>2.1.0</version>
</dependency>
```
Correct:
```
<dependency>
    <groupId>org.springdoc</groupId>
    <artifactId>springdoc-openapi-starter-webflux-ui</artifactId>
    <version>2.1.0</version>
</dependency>
```

It's working with the right dependency.

**Comment by iurylippo** [comment]
I am getting the same with Spring boot 3.1.0.
My swagger ui dependency: 
```
<dependency>
            <groupId>org.springdoc</groupId>
            <artifactId>springdoc-openapi-starter-webmvc-ui</artifactId>
            <version>2.1.0</version>
</dependency>
```

Tried: http://localhost:8000/swagger-ui/index.html => 404
Tried: http://localhost:8000/swagger-ui.html => 404

reproduce-able: https://github.com/iurylippo/sia-localiza/tree/develop
branch: develop
run: docker-compose up --build

**Comment by crazycatMyopic** [comment]
@uc4w6c find the minimum reproducible code here https://github.com/crazycatMyopic/issue_2/tree/main
as stated it is not considering my custom json but rather the default generated one

**Comment by uc4w6c** [comment]
@crazycatMyopic 
Did you remove the comment below?
`#springdoc.swagger-ui.url=/apidocs.json`

**Comment by uc4w6c** [comment]
displayed using the minimum reproducible code created by the creator of this issue (@crazycatMyopic), so I will close it.
If it still doesn't work, you can open it again.

What other people are commenting on may be different.
Please prepare a separate issue with minimum reproducible code.
or for any question post it on stackoverflow

**Comment by crazycatMyopic** [comment]
@uc4w6c  sorry for late reply's, this is my current properties

``` 
server.port=9090
spring.webflux.base-path=/test

#Open Api 3.0
#springdoc.swagger-ui.config-url=/v3/apidocs.json
springdoc.swagger-ui.url=/apidocs.json
#springdoc.swagger-ui.path=/apiDocuments
spring.web.resources.add-mappings=false
```

I'm still facing the issue, can you please let me know if this is correct?

**Comment by crazycatMyopic** [comment]
@uc4w6c also i'm unable to reopen the issue, please re open it
