### ISSUE TITLE
Description column has a textbox to enter values for "Try it Out" option appear by default.

### ISSUE THREAD

**Issue by Andrew3431** [springdoc/springdoc-openapi#223]
Although no values can be entered into box before clicking "Try it Out" , the box still appears with default value set as the name and description of the parameter. Is there any to make that box appear only when "Try it out" is clicked ?

![image](https://user-images.githubusercontent.com/58496081/70193681-c26bf200-16b4-11ea-86b2-2152a7e88df2.png)

**Comment by springdoc** [comment]
Hi, 

 Your description is related to swagger-ui default behaviour, and not to springdoc-openapi.
 Our library is built on top of official swagger-ui webjars.

 You can ask your question on swagger-ui projet:
- https://github.com/swagger-api/swagger-ui/issues
