### ISSUE TITLE
Support for regex paths in api documentation

### ISSUE THREAD

**Issue by CptOrange16** [springdoc/springdoc-openapi#2233]
Hello

I am not sure if this is possible or if it already exists, so feel free to close the issue if I am suggesting something that you already have.

### Suggestion: 
**generate api docs for requests paths with regex**

### Example:

Let's say i have a get request to find all fruits in my database:
```java
@GetMapping("/{fruit:(?:apples|bananas|pears)/{fruit_id}")
public ResponseEntity<Object> getAll(
@PathVariable String fruit,
            @PathVariable(value = "fruit_id") Long parentId)
```
When i open swagger api in localhost:8080, i see a single endpoint with both fields marked as required:

       /{fruit}/{fruit_id}

Instead it would be more useful to generate:

       /apples/{fruit_id}
       /bananas/{fruit_id}
       /pears/{fruit_id}

Let me know if you need anymore info.

**Comment by bnasslahsen** [comment]
@CptOrange16,

There is no plans for such a feature.
If you feel it useful for the community, feel free to propose a PR.
