### ISSUE TITLE
I set Swagger properties programmatically,but he reported an error

### ISSUE THREAD

**Issue by the-tsing** [springdoc/springdoc-openapi#2234]
**Describe the bug**

I use the programmatically set swagger property method provided by the official documentation, but this doesn't seem to work

**To Reproduce**

- What version of spring-boot you are using?
 3.0.5
- What modules and versions of springdoc-openapi are you using?
springdoc-openapi-starter-webmvc-ui
 2.1.0

**Screenshots**
Here is the case from the official docs
![image](https://github.com/springdoc/springdoc-openapi/assets/56435687/d8f8438e-2855-4079-926a-3761af12fc89)

Here is the configuration in my code
![image](https://github.com/springdoc/springdoc-openapi/assets/56435687/ccf9e32f-70e8-4687-819b-412fec3ee515)

This is the error when I start the program
![image](https://github.com/springdoc/springdoc-openapi/assets/56435687/9b8cb355-ee6c-4a2e-a756-d93ed0dbc291)

**Comment by uc4w6c** [comment]
@the-tsing 
Please try adding @Primary.

```java:
@Bean
@Primary
fun swaggerUiConfig(config: SwaggerUiConfigProperties): SwaggerUiConfigProperties {
    config.showCommonExtensions = true
    config.queryConfigEnabled = true
    return config
}
```

**Comment by the-tsing** [comment]
Thank you very much. I tried to add @ primary and it was set successfully. I would like to ask another question
![image](https://github.com/springdoc/springdoc-openapi/assets/56435687/42e0add9-e417-45ce-ab61-a7d9180cec1f)

Can I set the description of the request or corresponding parameter parameters as the default global extension? It's troublesome to click on each parameter individually

**Comment by uc4w6c** [comment]
@the-tsing 
See https://swagger.io/docs/open-source-tools/swagger-ui/usage/configuration/ for swagger ui configuration.
And if you have any requests, you can create an issue at https://github.com/swagger-api/swagger-ui.
