### ISSUE TITLE
Enable UrlTemplating

### ISSUE THREAD

**Issue by marccollin** [springdoc/springdoc-openapi#2236]
If you ❤️ this project consider becoming a [sponsor](https://github.com/sponsors/springdoc).
If you already use the `springdoc-openapi`, please do not forget adding a ***github star*** to this repository.

Actually with springfox it's possible to use url templating

@Bean
public Docket categoryApi() {
  return new Docket(DocumentationType.SWAGGER_2)
      .groupName("category-api")
      .apiInfo(apiInfo())
      .select()
      .paths(categoryPaths())
      .build()
      .ignoredParameterTypes(ApiIgnore.class)
      .[enableUrlTemplating](https://www.tabnine.com/code/java/methods/springfox.documentation.spring.web.plugins.Docket/enableUrlTemplating)(true);
}

Actually with springdoc when we have theses both endpoint

    @GetMapping(value = "/{id}", params = "name")
    @Operation(description = "check duplicate")
    public ResponseEntity<List<DuplicatePerson>> findDuplicatePerson(@PathVariable Long id, @RequestParam String name) {
        return new ResponseEntity<>(personService.findDuplicatePerson(id, nom), HttpStatus.OK);
    }

    @GetMapping("/{id}")
    @Operation(description = "Get person by its id")
    public ResponseEntity<PersonDto> findPersonById(@PathVariable
                                                      @NotNull
                                                      Long id) {
        return new ResponseEntity<>(personService.findPersonById(id), HttpStatus.OK);
    }

Only the first is displayed underswagger.

With sprindoc, when we enable url templating, both are displayed

Spring doc should have a similar option to support that

**Comment by uc4w6c** [comment]
Please see below.
https://github.com/springdoc/springdoc-openapi/issues/1726
https://github.com/springdoc/springdoc-openapi/issues/580
https://github.com/springdoc/springdoc-openapi/issues/71

**Comment by marccollin** [comment]
i checked 1726, seem like a pull request should be already merged to fix this issue.... don't seem true, i use already the newest release

**Comment by uc4w6c** [comment]
@marccollin 
sorry.
I was able to display both by adding the following code.

```java:
@Configuration
public class DuplicateConfiguration {
  @Bean
  public RouterOperationCustomizer addRouterOperationCustomizer() {
    return (routerOperation, handlerMethod) -> {
      if (routerOperation.getParams().length > 0) {
        routerOperation.setPath(routerOperation.getPath() + "?" + String.join("&", routerOperation.getParams()));
      }
      return routerOperation;
    };
  }
}
```

---

Controller

```java:
@RestController
@RequestMapping("duplicate2")
public class Duplicate2Controller {
  @GetMapping(value = "/{id}", params = "name")
  @Operation(description = "check duplicate")
  public String findDuplicatePerson(@PathVariable Long id, @RequestParam String name) {
    return "id:" + id.toString() + ", name:" + name;
  }

  @GetMapping("/{id}")
  @Operation(description = "Get person by its id")
  public String findPersonById(@PathVariable @NotNull Long id) {
    return id.toString();
  }
}
```

![スクリーンショット 2023-05-31 21 46 31](https://github.com/springdoc/springdoc-openapi/assets/36355491/311ad325-3629-4369-9710-4420a170e6db)

**Comment by marccollin** [comment]
you added code to your application. So the pull request was not merged?

**Comment by uc4w6c** [comment]
PR https://github.com/springdoc/springdoc-openapi/pull/1706 has been merged.
RouterOperationCustomizer is now available with this PR.

Since it is not a natural choice to create two methods for the same API resource, springdoc-openapi does not have this implementation by default, but you can customize it yourself using RouterOperationCustomizer.
