### ISSUE TITLE
SpringDocUtils.getConfig().replaceWithClass miss genericity info

### ISSUE THREAD

**Issue by yangganboy** [springdoc/springdoc-openapi#2237]
before
![image](https://github.com/springdoc/springdoc-openapi/assets/34567847/0a4caede-1f99-44e7-8ae5-b2c0705691f2)
use SpringDocUtils.getConfig().replaceWithClass
![image](https://github.com/springdoc/springdoc-openapi/assets/34567847/0101a1e1-a39b-4acf-9ee5-b479b5faf060)
mixin class
![image](https://github.com/springdoc/springdoc-openapi/assets/34567847/b91dca90-49c4-4872-b890-fc5cfe0e3aad)
![image](https://github.com/springdoc/springdoc-openapi/assets/34567847/fa325429-b3a4-4d40-8c32-ff5850788f43)

**Comment by bnasslahsen** [comment]
@yangganboy,

Make sure you Provide a [Minimal, Reproducible Example - with HelloController](https://stackoverflow.com/help/minimal-reproducible-example) that reproduces the problem.

Once the relevant information is provided. This ticket can be reopened.
