### ISSUE TITLE
Referring multiple same type class but defining different @Schema title causes showing same title

### ISSUE THREAD

**Issue by sissilab** [springdoc/springdoc-openapi#2238]
**Describe the bug**

- I define a `TestAn searchDto` in @RequestBody param
- the `TestAn` contains two same type (`SelectedField`) fields (`selectedField1` with `@Schema(title = "selectedField111")`  and `selectedField2` with `@Schema(title = "selectedField222")`)
- I expect to see `selectedField111` on `selectedField1`'s title and `selectedField222` on `selectedField2`'s title on swagger-ui
- but I see same title (defined in @Schema(title = "SelectedField title", description = "SelectedField desc") of `SelectedField` class) for both fields

**To Reproduce**

- version of spring-boot:  **2.7.8**
- versions of springdoc-openapi:  **1.7.0**
- Provide with a sample code or Test that reproduces the problem
```java
@RequestMapping("/api")
@RestController
public class SearchController {
  @Operation(summary = "Just a test")
  @PostMapping(value = "/test", consumes = "application/json", produces = "application/json")
  public HitPageResult search(@Parameter(description = "search param", required = true) @RequestBody TestAn searchDto) {
  return null;
  }
}

@Schema(title = "Test An title")
@Data
public class TestAn {

    @Schema(title = "filted field")
    private String field;

    @Schema(title = "selectedField111")
    private SelectedField selectedField1;

    @Schema(title = "selectedField222")
    private SelectedField selectedField2;

}

@Schema(title = "SelectedField title", description = "SelectedField desc")
@Data
public class SelectedField {
}
```

The  `/api/test` Schema in swagger-ui shows:
- `selectedField1`: the title shows `SelectedField title`, but exepcts `selectedField111`
- `selectedField2`: the title shows `SelectedField title`, but exepcts `selectedField222`

Maybe I use it inappropriately, please point it out.
Thanks!!!

**Comment by uc4w6c** [comment]
@sissilab 
Please see https://github.com/springdoc/springdoc-openapi/issues/685.
