### ISSUE TITLE
Disable load of external api-docs

### ISSUE THREAD

**Issue by dmentation** [springdoc/springdoc-openapi#224]
Hi.
Is it possible to disable the loading external documentation urls/files?

This is not really a huge problem but I've springdoc and if I use an external url like the default pets example, the pets example documentation loads. I used to have springfox, but I never managed to make the JSR-303 annotations work so I changed to springdoc but i don't really like the idea of being possible to load external documentation by changing the url parameter or the . 

[Not related]
Is it possible to change the layout with the new property to be the same as the springfox uses? If so how?

**Comment by springdoc** [comment]
Hi,

  Our library is built on top of official swagger-ui webjars.
 
 There is a related issue on swagger-ui project, not yet resolved: 
 - https://github.com/swagger-api/swagger-ui/issues/4332

 For layout options, you can use swagger-ui configuration options:
- https://github.com/swagger-api/swagger-ui/blob/master/docs/usage/configuration.md

 For example: 

```properties
springdoc.swagger-ui.layout=BaseLayout
```

**Comment by dranzerashi** [comment]
Hi, 
 when I'm passing springdoc.swagger-ui.layout=BaseLayout  property in application properties it is not being passed over to swagger-ui, when i directly pass the parameter in the url lets say http://localhost:8080/swagger-ui/index.html?configUrl=/api-docs/swagger-config&layout=BaseLayout it removes the top bar as expected.
