### ISSUE TITLE
Long init times for springdoc-openapi

### ISSUE THREAD

**Issue by DimitriSCOLE** [springdoc/springdoc-openapi#2241]
Describe the bug
I use springdoc-openapi for a project. We have a lot endpoints and the rendering of the swagger-ui takes very long Init duration for springdoc-openapi  and take a lot of memory.

is ther any issue if we have to many endpoints ?

Expected behavior
Render the swagger-ui as fast as before.

**Comment by bnasslahsen** [comment]
see https://github.com/springdoc/springdoc-openapi/blob/master/CONTRIBUTING.adoc
