### ISSUE TITLE
Swagger UI returning a blank page with Spring Boot v3

### ISSUE THREAD

**Issue by gmarciani** [springdoc/springdoc-openapi#2242]
Hello team,

I have the following issue with the SwaggerUI endpoint: it always returns a **blank page**.
It seems that it is not able to recognize the defined APIs, but the OpenAPI endpoint actually returns the expected result.
Details about my configuration below.

#### Dependencies
These are the relevant dependencies
```
# Spring Boot 3.1.0
implementation("org.springframework.boot:spring-boot-starter-web")
implementation("org.springframework.boot:spring-boot-starter-actuator")
implementation("org.springframework.boot:spring-boot-starter-security")

# SpringDoc 2.1.0
implementation("org.springdoc:springdoc-openapi-starter-webmvc-ui:2.1.0")
implementation("org.springdoc:springdoc-openapi-starter-webmvc-api:2.1.0")
```

#### Configuration
These are the relevant configuration properties
```
springdoc:
  api-docs:
    enabled: true
    path: /manage/openapi
  swagger-ui:
    enabled: true
    path: /manage/swagger-ui.html
  show-actuator: true
management:
  endpoints:
    enabled-by-default: false
    web:
      base-path: /manage
      exposure:
        include: configprops,env,health,info,mappings,metrics,openapi,prometheus,shutdown,swagger-ui
```

#### Controllers
This is an example of a controller definition:

```
@RestController
class CreateUser(
    @Autowired val userService: UserService
) {

    @PostMapping("/CreateUser")
    fun createUser(@Valid @RequestBody request: CreateUserRequest, authentication: Authentication?): CreateUserResponse {
        ...
    }
}
```

#### Results:
The OpenAPI endpoint is responding with the correct result at the expected endpoint `{{ADDRESS}}/manage/openapi `
The SwaggerUI endpoint is responding at the expected endpoint `{{ADDRESS}}/manage/swagger-ui.html`, but returns a blank page:

```
<!-- HTML for static distribution bundle build -->
<!DOCTYPE html>
<html lang="en">

<head>
	<meta charset="UTF-8">
	<title>Swagger UI</title>
	<link rel="stylesheet" type="text/css" href="./swagger-ui.css" />
	<link rel="stylesheet" type="text/css" href="index.css" />
	<link rel="icon" type="image/png" href="./favicon-32x32.png" sizes="32x32" />
	<link rel="icon" type="image/png" href="./favicon-16x16.png" sizes="16x16" />
</head>

<body>
	<div id="swagger-ui"></div>
	<script src="./swagger-ui-bundle.js" charset="UTF-8"> </script>
	<script src="./swagger-ui-standalone-preset.js" charset="UTF-8"> </script>
	<script src="./swagger-initializer.js" charset="UTF-8"> </script>
</body>

</html>
```

**Comment by uc4w6c** [comment]
@gmarciani 
Your issue is not reproducible.
Please provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) that reproduces the problem

It was displayed like this.
<img width="1317" alt="スクリーンショット 2023-05-27 21 48 23" src="https://github.com/springdoc/springdoc-openapi/assets/36355491/e714c039-985e-4a23-9fbe-a1eea404bdde">

**Comment by krnbr** [comment]
Does not work for me either, webflux and webmvc both are not working

**Comment by krnbr** [comment]
My bad it works for 3.1.0 with following version

```
<dependency>
    <groupId>org.springdoc</groupId>
    <artifactId>springdoc-openapi-starter-webflux-ui</artifactId>
    <version>2.1.0</version>
</dependency>
```

**Comment by gmarciani** [comment]
Tested and still `{{ADDRESS}}/manage/swagger-ui.html` shows blank page.
I'm using Kotlin, but I suppose this should not be an issue right?

**Comment by kdevkr** [comment]
The official documentation provides a demo for Spring Boot 3, and it appears that compatibility has been checked for 3.0.4 on the 2.x branch.

- https://springdoc.org/v2/#demos
- https://github.com/springdoc/springdoc-openapi-demos/blob/0b47ccd9c76e4b3bc4dd2e141d8e1e1401713b27/pom.xml#L14-L16

## Screenshot
![2023-06-01 22 43 46](https://github.com/springdoc/springdoc-openapi/assets/17937604/b61abe0c-74ea-40ef-bfb5-e3b7d32c4c17)

However, when I try it in 3.0.4, it doesn't work.

#### Solution
Replacing the `use-root-path` property with true will work.

```yml
springdoc:
  swagger-ui:
    use-root-path: true
```

Looking at the example code again...  → [2.x/demo-spring-boot-3-webmvc/src/main/resources/application.yml](https://github.com/springdoc/springdoc-openapi-demos/blob/2.x/demo-spring-boot-3-webmvc/src/main/resources/application.yml)

I didn't know about webflux and kotlin, so I didn't test it.
