### ISSUE TITLE
Swagger UI preauthorizeApiKey functionality support

### ISSUE THREAD

**Issue by BernardMenezes** [springdoc/springdoc-openapi#2245]
I have an application that configures SpringDoc based on the current Spring profile. For development profiling purposes I would like to be able to start SwaggerUI and already have the SecuritySchema component value filled in (I am using SecurityScheme.Type.APIKEY).

I searched and found a method from Swagger UI that seems to solve this situation 'preauthorizeApiKey'. Is it possible to support this functionality?

**Comment by uc4w6c** [comment]
Feel free to propose a PR.

Or you can do it by extending the implementation of SwaggerIndexPageTransformer.
read https://springdoc.org/#customizing-swagger-static-resources.
