### ISSUE TITLE
After calling the/v3/api-docs interface, the returned interface document becomes a Base64 encrypted string

### ISSUE THREAD

**Issue by Harolder** [springdoc/springdoc-openapi#2246]
<img width="1405" alt="image" src="https://github.com/springdoc/springdoc-openapi/assets/13034874/25293548-3579-4239-81c9-3ba1de67a934">

**Comment by uc4w6c** [comment]
Please see https://github.com/springdoc/springdoc-openapi/issues/2143

**Comment by Harolder** [comment]
Do any masters know how to solve this problem？

**Comment by Niclon** [comment]
I had similar problem. Problem is in your spring message converters. If you have big projects and need less impacting fast (not clean) fix then do this. 
Inherit org.springdoc.webmvc.api.OpenApiResource and practically copy OpenApiWebMvcResource.
Update endpoints methods so they returns string and not bytes (check super method and take logic before string to bytes array conversion). Change media type to text.
That did the trick for me. I do not recommend this approach, but it works.

**Comment by bnasslahsen** [comment]
Read https://springdoc.org/#why-am-i-getting-an-error-swagger-ui-unable-to-render-definition-when-overriding-the-default-spring-registered-httpmessageconverter
