### ISSUE TITLE
'org.springdoc:springdoc-openapi-ui:1.7.0' not Working with Spring 6 and Java 17

### ISSUE THREAD

**Issue by Akki-vinno24** [springdoc/springdoc-openapi#2247]
The open api SwaggerWelcomeWebMvc class is not working with Spring 6 and Java 17 as it needs  jakarta.servlet.http.HttpServletRequest but uses javax.servlet.http.HttpServletRequest. Please update this.

**Comment by uc4w6c** [comment]
SpringBoot v3 (Spring 6 and Java 17) is supported by springdoc-openapi v2.
Please see https://github.com/springdoc/springdoc-openapi#introduction

> For spring-boot v3 support, make sure you use [springdoc-openapi v2](https://springdoc.org/v2)

**Comment by Akki-vinno24** [comment]
@uc4w6c Thanks for help! It's working :+1:
