### ISSUE TITLE
set server.forward-headers-strategy=framework encountered other issues

### ISSUE THREAD

**Issue by the-tsing** [springdoc/springdoc-openapi#2248]
I have a SpringCloud project that introduces SpringDoc through a gateway and sets the server.forward-headers-setrategy=framework attribute of each microservice to its configuration file. This allows me to view Swagger documents through the gateway, and the documents for each microservice are correct, but I cannot obtain the real IP address in the requested access in any microservice, that is, getHeader ("x-forwarded for") is empty because I have set server.server.forward-headers-setrategy=framework

**Comment by bnasslahsen** [comment]
@the-tsing, 

You can see sample code for these demos: 
- https://springdoc.org/#demos

It's all working fine.
