### ISSUE TITLE
Order or operations

### ISSUE THREAD

**Issue by akoshman** [springdoc/springdoc-openapi#2250]
Is there any way to specify sort order of operations in UI like straightforward and clear one: GET, POST, PUT, DELETE?

**Comment by uc4w6c** [comment]
Please use StackOverflow for questions.
If you post on StackOverflow, I can answer this question right away.

**Comment by bnasslahsen** [comment]
Read https://springdoc.org/#how-can-i-sort-endpoints-alphabetically

Or https://github.com/springdoc/springdoc-openapi/issues/467#issuecomment-594093774
