### ISSUE TITLE
Actuator endpoint for write operation issue

### ISSUE THREAD

**Issue by ditogam** [springdoc/springdoc-openapi#2251]
Hello,
Actuator write operation doesn't generates proper request body

https://github.com/springdoc/springdoc-openapi/blob/493eaf6e45f382850195250f6719937a080b1621/springdoc-openapi-common/src/main/java/org/springdoc/core/customizers/ActuatorOperationCustomizer.java#L93

It just generates class prototype schema, not payload

Also there is problem for native build, need to add hints for MethodParameter,OperationMethodParameter and several other. 
I added all classes that was used with code `FieldUtils.getDeclaredField` and it become working

**Comment by bnasslahsen** [comment]
@ditogam,

Not sure what your issue is.
Try providing the expected information mentioned here: https://github.com/springdoc/springdoc-openapi/blob/master/CONTRIBUTING.adoc

And if you added any fixes, feel free to propose directly a PR.

**Comment by ditogam** [comment]
Sorry for bothering
As you can see from the first image, actuator/loggers POST generates example just with "TRACE" in text, after
```
MapSchema mapSchema = new MapSchema();
                                    mapSchema.addProperty(parameter.getName(), schema);

                                    operation.setRequestBody(new RequestBody()
                                        .content(new Content().addMediaType(org.springframework.http.MediaType.APPLICATION_JSON_VALUE,
                                            new MediaType().schema(mapSchema))));
```
after changes, it generates normal example

![Screenshot from 2023-06-04 08-00-08](https://github.com/springdoc/springdoc-openapi/assets/13191168/bc399dc4-a1ac-43d9-b4b1-9e45aa6e08ea)
![Screenshot from 2023-06-04 07-59-15](https://github.com/springdoc/springdoc-openapi/assets/13191168/bed5ac20-db6a-44c8-be8d-26ec35e0547d)

**Comment by bnasslahsen** [comment]
@ditogam,

Please propose a PR directly with the related test case.
