### ISSUE TITLE
Question - inject generated information in custom (manual generation) yml file

### ISSUE THREAD

**Issue by lhleonardo** [springdoc/springdoc-openapi#2253]
Hi. 
First, thank you for this great library. 

I'd like to talk about injecting runtime information in custom yml file. 

In my case, I need to write my swagger specification before developing my backend system. Sometimes, I receive the yml file from other people and build it. I know I may define my custom spec using the property `springdoc. swagger-ui.url: /swagger.yaml`. However, when I set my custom swagger like that, I lost the ability to automatic server generation using the current host. 

In this case, automatic server generation is beneficial when applied to CI/CD ecosystem (kubernetes+DNS system), which defines the current address based on the current environment.

My question is: Is it possible "inject" the automatic server detection (called by "Generated Server URL", generated in the automated process) in my custom yml file?

**Comment by bnasslahsen** [comment]
@lhleonardo,

when you use `springdoc.swagger-ui.url`, the static file is served as it is. There is no dynamic generartion of the server url.
It's up to your application, to provide dynamic swagger.yaml with the correct server generation.
