### ISSUE TITLE
Generated openapi document schema field type incorrect.

### ISSUE THREAD

**Issue by lkqm** [springdoc/springdoc-openapi#2254]
**Describe the bug**
Generated openapi document schema field type incorrect when model class annotation lombok @Accessors(chain = true) and field setter method annotations @JsonIgnore @JsonFormat。

API define:
```
@GetMapping("/hello") Result hello();
```

the generated openapi document schema:
```
"Result": {
  "type": "object",
  "properties": {
    "timestamp": {
      "$ref": "#/components/schemas/Result"
    }
  }
}
```

The HelloController:
```
@Tag(name = "hello")
@RestController
public class HelloController {

    @Operation(description = "hello")
    @GetMapping("/hello")
    public Result hello() {
        return null;
    }

    @Accessors(chain = true)
    @Data
    public static class Result {

        private Long timestamp;

        @JsonIgnore
        @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss")
        public Long getTimestamp() {
            return timestamp;
        }
    }
}
```

**To Reproduce**

- spring-boot: 2.7.10
- springdoc-openapi-ui, springdoc-openapi-webmvc-core: 1.7.0
- model class: @Accessors(chain = true). , the getter method: @JsonIgnore @JsonFormat

**Comment by uc4w6c** [comment]
It seems that swagger-core is not supported.
https://github.com/swagger-api/swagger-core/issues/3640

It was possible to hide it by setting @JsonIgnore on the field as well.

```java
  @Accessors(chain = true)
  @Data
  public static class Result {

    @JsonIgnore
    private Long timestamp;

    private String name;

    @JsonIgnore
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    public Long getTimestamp() {
      return timestamp;
    }
  }
```

**Comment by uc4w6c** [comment]
This ticket will be closed and we will follow the swagger-core issue instead.
