### ISSUE TITLE
The OAuth Authorize button missing in Swagger UI when native compiled with Spring Boot 3.0

### ISSUE THREAD

**Issue by magnus-larsson** [springdoc/springdoc-openapi#2255]
**Describe the bug**

- The OAuth Authorize button missing in Swagger UI when a resource server is native compiled with Spring Boot 3.0

**To Reproduce**

Version used:
- spring-boot version: v3.0.4
- springdoc-openapi module and version: springdoc-openapi-starter-webflux-ui, v2.1.0

- Use the  `demo-oauth2` example in <https://github.com/springdoc/springdoc-openapi-demos>, branch `2.x`
- Native compile the `oauth-resource-server-webflux` project and run it:

   ```
   cd oauth-resource-server-webflux
   mvn -Pnative clean native:compile 
   ./target/oauth-resource-server-webflux 
   ```

- Open the Web UI, <http://127.0.0.1:8082/resource-server/swagger-ui.html>, and note that the Authorize button is missing:

   <img width="748" alt="springdoc-oauth-native-no-auth-button" src="https://github.com/springdoc/springdoc-openapi/assets/1313727/bb612c37-5a50-419a-92ba-e082704c9a31">

**Expected behavior**

- Use the same project as above, build and run it:

   ```
   cd oauth-resource-server-webflux
   mvn clean package
   java -jar target/oauth-resource-server-webflux-3.1.7-SNAPSHOT.jar
   ```

- Open the Web UI, <http://127.0.0.1:8082/resource-server/swagger-ui.html>, and note that the Authorize button is present:

   <img width="748" alt="springdoc-oauth-java-jar-working" src="https://github.com/springdoc/springdoc-openapi/assets/1313727/e9a22c4d-8825-4aaa-9656-f9164ef2fa2e">

**Comment by giacgbj** [comment]
Same issue using 3.1.0.

**Comment by uc4w6c** [comment]
It seems that native compile removes code that has no implementation in classes (even classes with only annotations).

OpenApiConfig has been removed.
![スクリーンショット 2023-07-16 9 17 17](https://github.com/springdoc/springdoc-openapi/assets/36355491/13eab5ca-6217-43a5-86f1-bb9cb770765e)

It was resolved by setting @OpenAPIDefinition, @SecuritySchema. in the class with @SpringBootApplication (ResourceServerApp.java for the demo repository).

**Comment by magnus-larsson** [comment]
Hello @uc4w6c, thanks for your help and for explaining the problem!

I would prefer adding `@Configuration` in the `OpenApiConfig` - class instead of breaking the code structure to make it work when native compiled.

For details, see [GraalVM Native Image Support, Source Code Generation](https://docs.spring.io/spring-boot/docs/current/reference/html/native-image.html#native-image.introducing-graalvm-native-images.understanding-aot-processing.source-code-generation).

Shouldn't the source code in the Spring-boot OpenAPI Demo applications be updated, e.g. the `OpenApiConfig` - class, before this issue is closed?
(So that the demo applications work when native compiled)

Also, maybe it is worth mentioning that adding `@Configuration` to `@OpenAPIDefinition` and `@SecurityScheme` is required for GraalVM native images support in the docs at https://springdoc.org?

**Comment by uc4w6c** [comment]
That's true. I will update the docs.

**Comment by bnasslahsen** [comment]
@uc4w6c,

Thanks for the update. I confirm it's now published: https://springdoc.org/#is-graalvm-supported
