### ISSUE TITLE
SpringDoc bean naming conflict error with GraphQL Spring boot starter

### ISSUE THREAD

**Issue by ghoshrahul** [springdoc/springdoc-openapi#2256]
In a spring boot project which is using version 3.0.x and springdoc-openapi 2.x, there is a bean conflict for `ObjectMapperProvider`.

- What version of spring-boot you are using? **3.0.7**
- What modules and versions of springdoc-openapi are you using? **2.1.0**

**Expected behavior**

- Application with spring boot graphql starter and spring doc should have no conflicts and be running.

**Additional context**
Refer this [link](https://github.com/graphql-java-kickstart/graphql-spring-boot/issues/909)

**Comment by uc4w6c** [comment]
@ghoshrahul 
I changed the bean name. It will be resolved in the next version.
