### ISSUE TITLE
Cyclic dependencies with custom SpringDoc config or with programmatic configuration of SwaggerUi

### ISSUE THREAD

**Issue by Alf-Melmac** [springdoc/springdoc-openapi#2259]
**Description**

Following the documentation to set the SwaggerUi properties programmatically https://springdoc.org/v2/#how-can-i-set-swagger-properties-programmatically the dependencies of this configuration form a cycle.
This issue also occurs if you have a custom SpringDoc configuration and `springdoc.api-docs` is configured via the application.properties

**To Reproduce**
Fresh minimal Spring Boot install (version 3.1.0) with current springdoc-openapi-starter-webmvc-ui version (2.1.0). Create a configuration like shown in the [documentation](https://springdoc.org/v2/#how-can-i-set-swagger-properties-programmatically). See https://github.com/Alf-Melmac/springdoc-issue-swaggeruiconfig
```java
@Bean
public SwaggerUiConfigProperties swaggerUiConfigProperties(SwaggerUiConfigProperties config) {
	return config;
}
```
This issue also occurs if you have a custom SpringDoc configuration and `springdoc.api-docs` is configured via the application.properties. See [Repo with custom springdoc config](https://github.com/Alf-Melmac/springdoc-issue-swaggeruiconfig/tree/custom-springdoc-config)
```java
@Bean
public SpringDocConfigProperties springDocConfigProperties(SpringDocConfigProperties config) {
	return config;
}
``` 
```properties
springdoc.api-docs.enabled=false
```
***Result***
```
***************************
APPLICATION FAILED TO START
***************************

Description:

The dependencies of some of the beans in the application context form a cycle:

┌──->──┐
|  springDocConfigProperties defined in class path resource [de/webalf/swaggeruiconfig/SpringDocConfig.class]
└──<-──┘
```

**Expected behavior**

It should be possible to configure Spring doc and swagger ui programmatically.

**Comment by bnasslahsen** [comment]
see this [section](https://springdoc.org/#what-is-a-proper-way-to-set-up-swagger-ui-to-use-provided-spec-yml) to declare bean when `springdoc.api-docs.enabled=false`

**Comment by Alf-Melmac** [comment]
Okay, the second example is bad. The problem still occurs when other settings are made. Just replace `springdoc.api-docs.enabled=false` with `springdoc.packages-to-scan=/api` or anything else

**Comment by bnasslahsen** [comment]
@Alf-Melmac,

Your sample is declaring directly the cyclic dependency.
In your stackTrace there is no reference to springdoc `Beans` code.

There is nothing we can help you on that.

**Comment by Alf-Melmac** [comment]
The section regarding the setup with enabled=false helps. The other problem was the missing @Primary annotation. Thanks anyway
