### ISSUE TITLE
Request to upgrade Swagger UI to 5.1.0

### ISSUE THREAD

**Issue by JohnNiang** [springdoc/springdoc-openapi#2261]
[Swagger UI 5.1.0](https://github.com/swagger-api/swagger-ui/releases/tag/v5.1.0) was released a few hours ago. And the release brings support for [OpenAPI 3.1.0](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.1.0.md) specification. Support for OpenAPI 3.1.0 has been introduced in fully backward compatible way.

Meanwhile, I noticed that Swagger UI 5.1.0 in [webjars/swagger-ui](https://github.com/webjars/swagger-ui) has been released, please see https://github.com/webjars/swagger-ui/issues/191 for more.

**Comment by JohnNiang** [comment]
I was trying to upgrade Swagger UI into 5.0.0 in my local environment, but failed. I ran into 
 the problem described in <https://github.com/springdoc/springdoc-openapi/issues/2037>.

```diff
- <swagger-ui.version>4.19.0</swagger-ui.version>
+ <swagger-ui.version>5.0.0</swagger-ui.version>
```

Did I missing something? Please feel free to correct me.

**Comment by uc4w6c** [comment]
Closed because merge is complete
