### ISSUE TITLE
Incorrect parameter description for multiple fields of type JSONObject or JSONArray in entity class

### ISSUE THREAD

**Issue by JinghanHe** [springdoc/springdoc-openapi#2262]
When using SpringDoc to generate Swagger API documentation for an entity class containing multiple fields of type JSONObject or JSONArray, the parameter description for the parsed Swagger is incorrect. Specifically, only the last field's description is displayed for all fields of the same type.

I have confirmed that I am using the latest version of SpringDoc. Additionally, each field has its own @Schema annotation specifying the correct description.

Please let me know if there is a solution to this issue.

SpringBoot = 2.7.12
Springdoc = 1.7.0

If there are multiple fields of type JSONObject or JSONArray in the entity class, the parameter descriptions for these fields in the Swagger documentation only display the description for the last field. We are using knife4j-openapi3-spring-boot-starter, which relies on Springdoc (version 1.6.15) to parse the entity class and generate OpenAPI documentation. After working with the author of Knife4j, we have identified a bug in Springdoc when parsing JSON types. We have tried excluding all Springdoc-related dependencies in Knife4j and adding the latest Springdoc-related dependencies (version 1.7.0), but the issue persists.

If there is only one JSONObject or JSONArray or no JSONObject or JSONArray in the entity class, what Swagger shows is correct.

![Shot_2023_06_13_155200](https://github.com/springdoc/springdoc-openapi/assets/30678185/0af9c78f-be10-4789-84d0-ee146852e17d)
![Shot_20230613_160049](https://github.com/springdoc/springdoc-openapi/assets/30678185/abf7f4e7-d762-4e7b-9a16-585b94d8ed2f)
![Shot_2023_06_13_160108](https://github.com/springdoc/springdoc-openapi/assets/30678185/65f727ff-1787-49eb-adbf-51ab4f2dcdc6)

**Comment by bnasslahsen** [comment]
``springdoc-openapi v1.7.0 `` is the latest Open Source release supporting Spring Boot 2.x and 1.x. 

An extended support for [*springdoc-openapi v1*](https://springdoc.org/v1) 
project is now available for organizations that need support beyond 2023. 

For more details, feel free to reach out: sales@springdoc.org
