### ISSUE TITLE
Error while working with context-path on spring boot 3

### ISSUE THREAD

**Issue by guilhermecgs** [springdoc/springdoc-openapi#2263]
**Describe the bug**

After adding a single line:
`server.servlet.context-path=/mytest
`

I start receiving an error on (mvn clean verify)

```
[INFO] 
[INFO] --- springdoc-openapi-maven-plugin:1.4:generate (integration-test) @ demo ---
[ERROR] An error has occured: Response code 404
[INFO] 
[INFO] --- spring-boot-maven-plugin:3.1.0:stop (default) @ demo ---

```

**To Reproduce**
See here. Just clone to reproduce

https://github.com/guilhermecgs/demo/commit/1865f486a53316bac0938a863c2c27573b1d1249

**Expected behavior**

not 404

**Screenshots**
<img width="742" alt="image" src="https://github.com/springdoc/springdoc-openapi/assets/8465337/66aeb8dd-04ce-47b3-ae99-e0cd098f5653">

**Comment by uc4w6c** [comment]
@guilhermecgs 
Thank you.  
I can't open the link https://github.com/guilhermecgs/demo/commit/1865f486a53316bac0938a863c2c27573b1d1249, so please check.
