### ISSUE TITLE
@ParameterObject with @RequestBody in a POST request doesn't work as expected

### ISSUE THREAD

**Issue by tnaskali** [springdoc/springdoc-openapi#2267]
**Describe the bug**

- spring-boot-starter-parent: v3.1.0
- springdoc-openapi-starter-webflux-ui: v2.1.0

Using `@ParameterObject` together with `@RequestBody` and `consumes = MediaType.APPLICATION_JSON_VALUE` in a POST request doesn't work as expected. Fields in Swagger-ui are tagged as "query" parameters and are passed as such when using the "try it out" feature.

**To Reproduce**
Controller endpoint method :
```java
  @PostMapping(consumes = MediaType.APPLICATION_JSON_VALUE, produces = MediaType.APPLICATION_JSON_VALUE)
  @Operation(
      summary = "Manages plays of the current user",
      description = "Manages plays of the current user",
      security = @SecurityRequirement(name = "basicAuth"))
  public Mono<BggGeekplayV3ResponseBody> updateCurrentGeekplay(@Validated @RequestBody @ParameterObject BggGeekplayV3RequestBody body) {
    return authenticationService.requiredAuthentication().flatMap(
        authn -> geekplayRepository.updateGeekplay(authn.buildBggRequestHeader(), body));
  }
```
ParameterObject:
```java
@Data
public class BggGeekplayV3RequestBody {

  @NotNull
  @Min(1)
  @Max(1)
  @Parameter(example = "1", description = "Required to have data returned as JSON instead of HTML.")
  private Integer ajax;

  @NotNull
  @Pattern(regexp = "^(save|delete)$")
  @Parameter(example = "save", description = "Action to perform.<p>Possible values are:<li/>save (create or update)<li/>delete (delete)")
  private String action;

}
```

**Expected behavior**

- Fields should be tagged as "body" parameters in swagger-ui
- "Try it out" should pass the parameters as a JSON string body

**Screenshots**

![Screenshot 2023-06-16 at 10 44 07](https://github.com/springdoc/springdoc-openapi/assets/17480878/442a8ac2-85a5-4f92-8f24-a9af91c8c3b0)

**Comment by uc4w6c** [comment]
Remove `@ParameterObject`.
Please read https://springdoc.org/#how-can-i-extract-fields-from-parameter-object.
