### ISSUE TITLE
Multiplied schema generation for complex object definitions.

### ISSUE THREAD

**Issue by stosik** [springdoc/springdoc-openapi#2268]
**Describe the bug**
I have a small issue with how by some configuration means it generates schemas not only for top-level classes but as well for inner types within those.

**To Reproduce**
build.gradle.kts

```
implementation("org.springdoc:springdoc-openapi-webflux-ui:1.7.0")
runtimeOnly("org.springdoc:springdoc-openapi-kotlin:1.7.0")
```
Example Controller:
```
@RestController
class Controller {
    @ApiResponses(
        ApiResponse(
            responseCode = "200",
            description = "Successfully returned A",
            content = [
                Content(
                    mediaType = "application/json",
                    schema = Schema(implementation = A::class)
                )
            ]
        )
    )
    @GetMapping("/mobile-payments-api/payment-gateway/getA")
    suspend fun getA(): A {
        return A(B(name = "Tom"))
    }

    data class A(val b: B) {
        data class B(val name: String)
    }
}
```

**Expected behavior**
I am not sure if it is the problem of swagger core or Springdoc but I would expect SpringDoc to generate schemas for the top-level classes and represent the nested complex types as properties within those schemas.
So I would expect only to have the schema defined for `class A`

**Screenshots**
![Screenshot 2023-06-16 at 09 56 50](https://github.com/springdoc/springdoc-openapi/assets/13648207/51aa0a58-6221-42cd-9884-89f52b52c0c9)

**Additional context**

**Comment by bnasslahsen** [comment]
``springdoc-openapi v1.7.0 `` is the latest Open Source release supporting Spring Boot 2.x and 1.x. 

An extended support for [*springdoc-openapi v1*](https://springdoc.org/v1) 
project is now available for organizations that need support beyond 2023. 

For more details, feel free to reach out: sales@springdoc.org
