### ISSUE TITLE
Origin header should be not sent when the OAuth2 access token is requested

### ISSUE THREAD

**Issue by fabrizio-cannizzaro** [springdoc/springdoc-openapi#2269]
I have found this bug:
`@OpenAPIDefinition(info = @Info(title = "Imv Api Gateway", description = "Some long and useful description", version = "v1")) @SecurityScheme( name = "oauth2", type = SecuritySchemeType.OAUTH2, flows = @OAuthFlows( clientCredentials = @OAuthFlow( tokenUrl = "${springdoc.oAuthFlow.tokenUrl}", scopes = { @OAuthScope(name = "api://2a689d5e-1f7a-44cb-a1a6-d590a5405eca/.default", description = "api scope") } ) ) )`
It is creating a request with a basic authentication header, instead of payload Form Data. Please fix it

**Comment by bnasslahsen** [comment]
@fabrizio-cannizzaro,

There is no part of the `springdoc-openapi` that sends an Access Token directly.
Feel free to check the `swagger-ui `code instead.
