### ISSUE TITLE
Question:  Does springdoc-openapi  has any options to document classes when it is not possible to add annotations on it

### ISSUE THREAD

**Issue by Andrew3431** [springdoc/springdoc-openapi#227]
spring-security library provides class for authorization endpoints, we inherit this class and hence it is not possible to add Swagger annotations on it. We used ApiListingScannerPlugin provided by springfox to create the swagger documentation. Does springdoc-openapi provide any similar functionality, we are looking to migrate from springfox to springdoc-openapi ?

**Comment by springdoc** [comment]
Hi @Andrew3431, 

 We have chosen to rely on swagger-annotations official webjars only.
 If you want to add additional enpoints, that are not available on your code,  you can add your own implementation of OpenApiCustomiser. 

 You have access to the OpenAPI object, and this will help you add your custom paths.

An usage example of OpenApiCustomiser, is available on:

- https://github.com/springdoc/springdoc-openapi/blob/master/springdoc-openapi-webmvc-core/src/test/java/test/org/springdoc/api/app39/SpringDocApp39Test.java
