### ISSUE TITLE
Question about Springdoc 2.x compatibility with Spring Boot 2.7.x

### ISSUE THREAD

**Issue by adamjq** [springdoc/springdoc-openapi#2270]
Hi, I've got a quick question about compatibility based on [this FAQ question](https://springdoc.org/#what-is-the-compatibility-matrix-of-springdoc-openapi-with-spring-boot). Is `springdoc-openapi 2.0.x+` compatible with `spring-boot 2.7.x`, or is `springdoc-openapi 2.0.x+` only compatible with Spring Boot 3?

I've tried to follow [the migration guide](https://springdoc.org/v2/#Introduction
) from `springdoc-openapi 1.7.x -> 2.1.x` and am getting the following error for a `spring-boot 2.7.x` application:

```
***************************
APPLICATION FAILED TO START
***************************

Description:

The bean 'webConversionServiceProvider', defined in class path resource [org/springdoc/core/configuration/SpringDocConfiguration$WebConversionServiceConfiguration.class], could not be registered. A bean with that name has already been defined in class path resource [org/springdoc/core/SpringDocConfiguration$WebConversionServiceConfiguration.class] and overriding is disabled.

Action:

Consider renaming one of the beans or enabling overriding by setting spring.main.allow-bean-definition-overriding=true
 contextMap={} 

```

**Comment by JohnNiang** [comment]
IMO, `springdoc-openapi 2.x` is only compatible with `spring-boot 3.x` instead of `both`. Because it may use some features only available in `spring-boot 3.x`. See https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-3.0-Migration-Guide for more.
