### ISSUE TITLE
Performance issues with SecurityScheme

### ISSUE THREAD

**Issue by Lawrightax** [springdoc/springdoc-openapi#2278]
Hello, I found a performance issue on my side today and wanted to signal it in case it's a problem...
If I'm doing something wrong I would really like to know ! thanks ❤️ 

**To Reproduce**

- What version of spring-boot you are using?
- 3.1.0
- What modules and versions of springdoc-openapi are you using?
- springdoc-openapi-starter-webmvc-ui with 2.1.0

Explanation:
Okay so I'm working on an API and use SpringDoc to document it. I was wondering what took so long to generation my OpenApi definition... After some exploration, I found a big reflexion problem on the SecurityScheme annotation.
To declare my securitySchemes I used to do this like : 
```
OpenApiCustomizer locGeneralDocCustomiser = openApi -> {
      openApi.info(new Info().title("JUMP AMS API")
              .contact(new Contact().email("support@jump-informatique.com").url("https://www.jump-technology.com").name("JUMP Technology")));
      openApi.security(List.of(new SecurityRequirement().addList("basicAuth")));
      openApi.getComponents().addSecuritySchemes("basic", new SecurityScheme().type(Type.HTTP).scheme("Basic"));
      openApi.getComponents().addSecuritySchemes("cookie", new SecurityScheme().type(Type.APIKEY).in(In.COOKIE));
    };
```
but when OpenApi creates, it use the function "calculateSecurityScheme" that is gonna do a full reflexion inside all my classes (which is a lot) : 
![image](https://github.com/springdoc/springdoc-openapi/assets/55845231/6c8b61bc-4d24-476f-bc8a-b89f56002e7c)

To work around this I had to had the annotation on a Bean (which is not necessarily bad), but maybe we should make it use our "packagesToScan" defined in our GroupedOpenAPI to make the reflexion (would be a lot faster in my case) instead of using the base package

**Comment by bnasslahsen** [comment]
@Lawrightax,

This point is already in the documentation: For better performance, use spring managed beans to prevent classpath scanning.

- https://springdoc.org/#adding-api-information-and-security-documentation
