### ISSUE TITLE
server:servlet:context-path Spring config not showing in API spec

### ISSUE THREAD

**Issue by ramkumar-equinix** [springdoc/springdoc-openapi#2284]
Problem Statement:-
<img width="367" alt="image" src="https://github.com/springdoc/springdoc-openapi/assets/7531306/a4b46205-45c5-4b0c-8522-d753266f38ec">

context path specified in server.servlet.context-path is not showing in Swagger UI.

steps to reproduce:-
add the below config in application.yml and start the application 

```
server:
   servlet:
     context-path: mybasecontext
```
testing:- 
http://localhost:8080/mybasecontext/getusersapi
http://localhost:8080/mybasecontext/swagger-ui.html

in the above Screen shot the **mybasecontext** is missing 
please help to fix this issue

**Comment by bnasslahsen** [comment]
@ramkumar-equinix,

No reproducible.
Try providing  a [Minimal, Reproducible Example - with HelloController](https://stackoverflow.com/help/minimal-reproducible-example) that reproduces the problem.

**Comment by psramkumar** [comment]
https://github.com/psramkumar/spring-swagger-ui added the reproducible Sample here

**Comment by psramkumar** [comment]
<img width="581" alt="image" src="https://github.com/springdoc/springdoc-openapi/assets/602760/22954a61-56a4-49f1-82a4-e43cf58ff872">

**Comment by psramkumar** [comment]
Expected is `/**base**/test1` and /**base**/demo1` 
`/base` is missing, it shows above in api-docs and in generated server URL
