### ISSUE TITLE
Description and example for value objects can't be overwritten

### ISSUE THREAD

**Issue by YuKitAs** [springdoc/springdoc-openapi#2285]
**Describe the bug**

When value objects are used inside of response or request body objects (top level), the `description` and `example` attributes of the `@Schema` annotations on the value object class are ignored.

**To Reproduce**
1. Create a value object class with `@Schema` annotation and use it in the request body with `@Schema`:
```java
@Schema(name = "String VO", description = "some desc", example = "some example")
public class StringValueObject {
    private String value;
    ...
}
```
```java
public class DemoRequest {
    @Schema(description = "other desc", example = "other example")
    private StringValueObject name;
    ...
}
```
2. Create an endpoint:
```java
@RestController
@RequestMapping(value = "/hello")
public class DemoController {

    @PostMapping
    public String hello(@RequestBody DemoRequest request) {
        return "Hello " + request.getName().getValue();
    }

}
```
3.1 Replace the value object with String in the config:
```java
static {
    SpringDocUtils.getConfig().replaceWithClass(StringValueObject.class, String.class);
}
```
In this case, the description and example will be totally ignored:
![](https://gitlab.com/YuKitAs/springdoc-openapi-demo/-/raw/master/screenshots/schema.png)

3.2 As a workaround, we use a custom `ModelResolver` to set the description and example manually:
```java
    public Schema resolve(AnnotatedType type, ModelConverterContext context, Iterator<ModelConverter> chain) {
        JavaType javaType = mapper.constructType(type.getType());
        Class<?> clazz = javaType.getRawClass();
        if (StringValueObject.class.isAssignableFrom(clazz)) {
            io.swagger.v3.oas.annotations.media.Schema classSchema = clazz.getDeclaredAnnotation(io.swagger.v3.oas.annotations.media.Schema.class);
            StringSchema schema = new StringSchema();
            schema.setDescription(classSchema.description());
            schema.setExample(classSchema.example());
            return schema;
        }

        return super.resolve(type, context, chain);
    }
```

Then only the `description` and `example` of the `StringValueObject` class will be shown, but not of the actual object, which means they can't be overwritten:

![](https://gitlab.com/YuKitAs/springdoc-openapi-demo/-/raw/custom-resovler/screenshots/schema.png)

- What version of spring-boot you are using?
2.7.13
- What modules and versions of springdoc-openapi are you using?
```
<groupId>org.springdoc</groupId>
<artifactId>springdoc-openapi-ui</artifactId>
<version>1.7.0</version>
```
- What is the actual and the expected result using OpenAPI Description (yml or json)?
Actual schema generated in `v3/api-docs`:
```
"schemas":{"DemoRequest":{"type":"object","properties":{"name":{"type":"string","description":"some desc","example":"some example"}}}}
```
**Expected behavior**
We expect to see overwritten description and example as:
```
"schemas":{"DemoRequest":{"type":"object","properties":{"name":{"type":"string","description":"other desc","example":"other example"}}}}
```
- Provide with a sample code (HelloController) or Test that reproduces the problem
Example project: https://gitlab.com/YuKitAs/springdoc-openapi-demo/-/tree/master/ (see branch `master` and `custom-resolver`)

We'd appreciate it if you could provide a solution to allow us to overwrite the description and example in such cases.

**Comment by uc4w6c** [comment]
I think this will solve it.

```java:
@RestController
@RequestMapping(value = "/hello")
public class DemoController {

  @PostMapping
  public String hello(@RequestBody DemoRequest request) {
    return "Hello " + request.getName().getValue();
  }

  @Schema(description = "other desc", example = "other example", type = "string")
  public static class StringValueObject {
    private String value;

    public StringValueObject(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }
  }

  public static class DemoRequest {
    private StringValueObject name;

    public DemoRequest(StringValueObject name) {
      this.name = name;
    }

    public StringValueObject getName() {
      return name;
    }
  }
}
```

**Comment by uc4w6c** [comment]
@YuKitAs 
Please read https://springdoc.org/#how-can-i-have-pretty-printed-output-of-the-openapi-specification.

I think it is difficult to create a function to overwrite with @Schema because the openapi component is created from the class and the component is referenced.

**Comment by gf-smtzgr** [comment]
Sorry for the late reply (I'm a colleague of YuKitAs working on the same issue):
The issue we were facing here was that neither the class level annotation nor an annotation directly at the attribute did work. If the object behaves like a string (which to me  SpringDocUtils.getConfig().replaceWithClass(StringValueObject.class, String.class); would imply then at least the local annotation (the annotation inside DemoRequest) would work.
With our CustomResolver we actually can make both working, but imho the replaceWithClass command seems to imply that the respective class will be treated like the other class (a String in the example) and thus one would expect that the annotations work like they would with a string. So from the outside it seems that the replacement simply happens on the wrong level or the like? We did not investigate the code that normally resolves these cases, but again, with a custom resolver you can get both to work (which would currently be the workaround for anyone running into a similar issue), but that would imply that it should be possible to support generally. 
If you feel that is not something the project should support, fair enough - as a user that seems like a bug though or at least a bit misleading (meaning the fact that neither of both annotations gets used - is there perhaps simply another annotation that we should use there?). 
Regarding the link you provided, it addresses having different descriptions for a class, but here we don't want to represent the value object to the outside as a class, just as a string which natively can have different argument description/examples when used at different places.
