### ISSUE TITLE
StringIndexOutOfBoundsException at AbstractSwaggerResourceResolver.java:71

### ISSUE THREAD

**Issue by arcimen54** [springdoc/springdoc-openapi#2286]
Hello,
i have a springboot project with version 2.7.4 and Java 17.
I also recently integrated the library springdoc-openapi-ui with version 1.7.0, i also use maven.

>        <dependency>
>             <groupId>org.springdoc</groupId>
>             <artifactId>springdoc-openapi-ui</artifactId>
>             <version>1.7.0</version>
>         </dependency>

Every time i open the homepage of my swagger ui my project Throw a StringIndexOutOfBoundsException.

This is the stacktrace: 

> java.lang.StringIndexOutOfBoundsException: begin 11, end 10, length 10
>     at java.lang.String.checkBoundsBeginEnd(String.java:4602)
>     at java.lang.String.substring(String.java:2705)
>     at java.lang.String.substring(String.java:2678)
>     at org.springdoc.ui.AbstractSwaggerResourceResolver.path(AbstractSwaggerResourceResolver.java:71)
>     at org.springdoc.ui.AbstractSwaggerResourceResolver.findWebJarResourcePath(AbstractSwaggerResourceResolver.java:42)
>     at org.springdoc.webmvc.ui.SwaggerResourceResolver.resolveResource(SwaggerResourceResolver.java:34)
>     at org.springframework.web.servlet.resource.DefaultResourceResolverChain.resolveResource(DefaultResourceResolverChain.java:75)
>     at org.springframework.web.servlet.resource.ResourceHttpRequestHandler.getResource(ResourceHttpRequestHandler.java:627)
>     at org.springframework.web.servlet.resource.ResourceHttpRequestHandler.handleRequest(ResourceHttpRequestHandler.java:558)
>     at org.springframework.web.servlet.mvc.HttpRequestHandlerAdapter.handle(HttpRequestHandlerAdapter.java:52)
>     at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1071)
> 

On my REST method i use the annotation Operation, ApiResponse, and Parameter of io.swagger.v3.oas.annotations package.

I dont have any other configuration about swagger or OpenApi or SpringDoc.

**To Reproduce**

- Start the springboot project with this versione
- go to the address http://localhost:8080/swagger-ui/index.html

Thanks.

**Comment by uc4w6c** [comment]
This issue has been resolved. https://github.com/springdoc/springdoc-openapi/issues/2235
Please wait for the release of the next version.
