### ISSUE TITLE
How to prevent the generation of schema for non-existent classes

### ISSUE THREAD

**Issue by john1337** [springdoc/springdoc-openapi#2288]
How to prevent the generation of schema for non-existent classes,my situation is like this,all controller api return same stucture like this 
ApiResultDto<ClassA>,ApiResultDto<ClassB>,so there are lots of non exist schema like ApiResultDtoClassA,ApiResultDtoClassB,but i don't want to such non exist schema to be generated,but i don't know how

**Comment by bnasslahsen** [comment]
@john1337,

`springdoc.remove-broken-reference-definitions` should be already set to `true`. (which is the default value)
if you are still having 

if you believe you are having an issue, make sure you provide a [Minimal, Reproducible Example - with HelloController](https://stackoverflow.com/help/minimal-reproducible-example) that reproduces the problem
