### ISSUE TITLE
The `/v3/api-docs` api returns an illegal value when using custom `HttpMessageConverter`

### ISSUE THREAD

**Issue by wenlinfeng** [springdoc/springdoc-openapi#2289]
`OpenApiWebMvcResource#openapiJson` returns a `byte[]` of JSON as result, when my project using a custom `HttpMessageConverter` and  the argument of `setSupportedMediaTypes()` including a value of `application/json`, then `/v3/api-docs` returned value is a **Base64 encoded String** surround with **quotes**, such as `"eyjxxxxlafdsjfdsaljlkfdsal32454...67=="`, not a raw JSON object surround with **braces**, how to prevent it?

**Comment by TQiangLiu** [comment]
result ?

**Comment by fviale** [comment]
@wenlinfeng how did you solve your issue ? I have the same problem I don't know how to resolve it.

**Comment by lonniewen** [comment]
> sure a `ByteArrayHttpMessageConverter` must be added before custom `HttpMessageConverter` added.
