### ISSUE TITLE
Hide schemas used by hidden paths in OpenApiCustomiser

### ISSUE THREAD

**Issue by mbedna** [springdoc/springdoc-openapi#229]
Hi,
In `OpenApiCustomiser` I can hide particular paths and tags depending on environment. Is it possible to find schemas in components which are used by this hidden paths or tags, so I can hide them also?

**Comment by springdoc** [comment]
Hi, 

 Using OpenApiCustomiser, you have access to OpenAPI object. 
 Consequently all the elements: PathItem / Operation / parameters and responses schema. 
 An you have also full control on components related to the OpenAPI object.
