### ISSUE TITLE
Wrong response schema in OpenApi UI using SpringDoc with swagger yaml file

### ISSUE THREAD

**Issue by Borsoi** [springdoc/springdoc-openapi#2290]
**Describe the bug**

I'm having a issue where the response schema for the erros codes, such 400, 500 e etc. not being show as a no content in the swagger UI. It replicate the schema set for the 200 response code, when using the yaml file generated code.

I'm using the springdoc dependency to configure the UI from the swagger, in the documentation of springdoc I found that you can define no content response schema using this annotattions: [springdoc-documentation](https://i.stack.imgur.com/auv5W.png)

The main problem is that the code is generated by the swagger codegen, which I cannot modify and applied the solution present in the documentation. Here's my code:

**To Reproduce**
The yaml file:
`400:
  description: Requisição inválida
  content: { }
401:
  description: Falha na autenticação
  content: { }
500:
  description: Erro no sistema
  content: { }`

`@ApiResponses(value = { 
        @ApiResponse(responseCode = "202", description = "Solicitação recebida com sucesso.", content = @Content(mediaType = "application/json", schema = @Schema(implementation = ObjectName.class))),
        @ApiResponse(responseCode = "400", description = "Requisição inválida"),
        @ApiResponse(responseCode = "401", description = "Falha na autenticação"),
        @ApiResponse(responseCode = "500", description = "Erro no sistema") })
    @RequestMapping(value = "/evento-nao-financeiro",
        produces = { "application/json" }, 
        consumes = { "application/json" }, 
        method = RequestMethod.POST)
    default ResponseEntity<StatusSafRepresentation> methodName`

- I'm using springboot version 2.5.14 e springdoc version 1.7.0 and my swagger UI config file is:

`@Configuration
public class OpenApiConfiguration {

    @Value("${spring.application.name}")
    private String name;

    @Value("${spring.application.description}")
    private String description;

    @Value("${spring.application.version}")
    private String version;

    @Value("${spring.profiles.active}")
    private String activeProfile;

    @Bean
    public OpenAPI api() {
        return new OpenAPI()
                .info(apiInfo())
                .components(new Components());
    }

    private Info apiInfo() {
        return new Info()
                .title("Orquestrador de Eventos Não Financeiros")
                .description(description)
                .version(version);
    }

    @Bean
    public GroupedOpenApi eventosApi() {
        return GroupedOpenApi.builder()
                .group("Eventos Não Financeiros")
                .pathsToMatch("/evento-nao-financeiro")
                .build();
    }

    @Bean
    public GroupedOpenApi loginApi() {
        return GroupedOpenApi.builder()
                .group("Login")
                .pathsToMatch("/login")
                .build();
    }
}`

As you can see, if I could add the code 'content = @Content(schema = @Schema(hidden = true))' in those apiResponses that isn't the 202 status, probably my problem would be solved, but as I commented this is a generated code by swagger codegen.

**Expected behavior**
It was expected that the status code 400, 401 e 500 doens't had a response body in the swagger UI. 

**Screenshots**
- O resultado atual produzido pelo Swagger UI é a seguinte:
![image](https://github.com/springdoc/springdoc-openapi/assets/63875868/672f7886-8758-4c9f-8926-e615eb942f2f)
You can see that all the other status code has the same response body as the 202 code.

**Comment by bnasslahsen** [comment]
``springdoc-openapi v1.7.0 `` is the latest Open Source release supporting Spring Boot 2.x and 1.x. 

An extended support for [*springdoc-openapi v1*](https://springdoc.org/v1) 
project is now available for organizations that need support beyond 2023. 

For more details, feel free to reach out: sales@springdoc.org
