### ISSUE TITLE
Beans in the SpringDoc package are not being created

### ISSUE THREAD

**Issue by AlekseySeverinov** [springdoc/springdoc-openapi#2294]
Hello, in my application I am using SpringDoc 1.5.2 and Spring Boot 2.4.2. Additionally, my application uses the componentScan annotation which scans the packages in my application. I cannot disable it because it creates many circular dependencies.  
![image](https://github.com/springdoc/springdoc-openapi/assets/106344976/9b945d7d-0d5c-4a5c-b669-36e10110a983)
I am trying to import these libraries to work with SpringDoc, but I am getting an error.   
Caused by: java.lang.ClassNotFoundException: org.springdoc.webmvc.core.SpringDocWebMvcConfiguration
But, this package is in my application 
![image](https://github.com/springdoc/springdoc-openapi/assets/106344976/f46c38ef-2d83-4e06-9419-a4ab67d4f60a)

Can you help me with this problem?

**Comment by bnasslahsen** [comment]
``springdoc-openapi v1.7.0 `` is the latest Open Source release supporting Spring Boot 2.x and 1.x. 
An extended support for [springdoc-openapi v1](https://springdoc.org/v1) project is now available for organizations that need support beyond 2023.
For more details, feel free to reach out: sales@springdoc.org

**Comment by AlekseySeverinov** [comment]
I tried version 1.7.0, but the same error occurred. The SpringDoc configuration beans are not being created and the openApiJson and Yml methods are not working.
