### ISSUE TITLE
Setting Description on a complex type property via OpenApiCustomiser  does not work

### ISSUE THREAD

**Issue by IgorBuchelnikov** [springdoc/springdoc-openapi#2297]
Setting Description on a complex type property does not work.

- version of spring-boot: 2.5.4
- springdoc-openapi-ui: 1.7.0

```
import lombok.Data;

@Data
public class ClientAddress {
	private String value;
}

@Data
public class Client {
	private ClientAddress mailingAddress;
	private ClientAddress deliveryAddress;
	private String name;
}

@Bean
public OpenApiCustomiser  customizeDescription () {
    return openApi -> {
        Map clientProperties = openApi.getComponents().getSchemas().get("Client").getProperties();
        ((Schema) clientProperties.get("mailingAddress")).setDescription("mailng address");
        ((Schema) clientProperties.get("deliveryAddress")).setDescription("delivery address");
        ((Schema) clientProperties.get("name")).setDescription("client name");
    };
}
```

produces:
```
"Client": {
  "type": "object",
  "properties": {
	  "mailingAddress": {
		  "$ref": "#/components/schemas/ClientAddress"
	  },
	  "deliveryAddress": {
		  "$ref": "#/components/schemas/ClientAddress"
	  },
	  "name": {
		  "type": "string",
		  "description": "client name"
	  }
  }
}
```
The "description" tag is missing for "mailingAddress" and "deliveryAddress".
expected:
```
"Client": {
  "type": "object",
  "properties": {
	  "mailingAddress": {
		  "$ref": "#/components/schemas/ClientAddress",
		  "description": "mailng address"
	  },
	  "deliveryAddress": {
		  "$ref": "#/components/schemas/ClientAddress",
		  "description": "delivery address"
	  },
	  "name": {
		  "type": "string",
		  "description": "client name"
	  }
  }
}
```

i know about
https://github.com/springdoc/springdoc-openapi/issues/1178
https://springdoc.org/#how-can-i-define-other-schemas-for-the-same-class
and others
but my variant of using OpenApiCustomiser would be easier for me.
I plan to use my own annotations with property descriptions and use these annotations to document swagger.
In any case, I believe that OpenApiCustomiser should be a last link in the process of building of the swagger api. Then it will be a real customizer.

**Comment by bnasslahsen** [comment]
``springdoc-openapi v1.7.0 `` is the latest Open Source release supporting Spring Boot 2.x and 1.x. 

An extended support for [*springdoc-openapi v1*](https://springdoc.org/v1) 
project is now available for organizations that need support beyond 2023. 

For more details, feel free to reach out: sales@springdoc.org
