### ISSUE TITLE
Cannot exclude bytecode enhanced fields

### ISSUE THREAD

**Issue by Thomaleh** [springdoc/springdoc-openapi#2298]
I am using the `hibernate-enhance-maven-plugin` to bytecode enhance my entity classes. The enhancement adds these fields to the entity classses:
```
  @Transient
  private transient EntityEntry $$_hibernate_entityEntryHolder;
  @Transient
  private transient ManagedEntity $$_hibernate_previousManagedEntity;
  @Transient
  private transient ManagedEntity $$_hibernate_nextManagedEntity;
  @Transient
  private transient PersistentAttributeInterceptor $$_hibernate_attributeInterceptor;
```

The `customize` Method in `QuerydslPredicateOperationCustomizer` uses all declared fields of the entity class and it is only possible to include or exclude fields by using the QEntity bindings. Since the enhanced fields are not present in the QEntity they can not be excluded.

Inclusion of these fields leads to a number of errors, most noticable of all a NPE when trying to create a Schema for `org.hibernate.dialect.Dialect`.

- java version: 8
- spring-boot version: 2.7.2
- springdoc-openapi-ui version: 1.6.15
- springdoc-openapi-security version: 1.6.15
- springdoc-openapi-hateoas version: 1.6.15
- springdoc-openapi-data-rest version: 1.6.15
- hibernate-enhance-maven-plugin version: 5.6.10.Final

**Expected behavior**
Only paths in the QEntity class should be processed.
Alternatively provide a way to exclude bytecode enhanced fields.

**Comment by bnasslahsen** [comment]
``springdoc-openapi v1.7.0 `` is the latest Open Source release supporting Spring Boot 2.x and 1.x. 
An extended support for [*springdoc-openapi v1*](https://springdoc.org/v1) 
project is now available for organizations that need support beyond 2023. 

For more details, feel free to reach out: sales@springdoc.org
