### ISSUE TITLE
How to expose Swagger UI without authentication?

### ISSUE THREAD

**Issue by durimkryeziu** [springdoc/springdoc-openapi#230]
Hi,

I'm glad that found this new project instead of SpringFox which is quite outdated now!

But I'm having issues with exposing the Swagger UI without requiring authentication, can you help me with that please?
I'm using Spring Boot 2.2.1 with Spring Security Starter

Thanks in advance

**Comment by springdoc** [comment]
Hi  @durimkryeziu ,

 Adding this to your WebSecurityConfiguration class should do the trick.


```java
@Configuration
public class WebSecurityConfiguration extends WebSecurityConfigurerAdapter {
    @Override
    public void configure(WebSecurity web)  {
        web.ignoring().antMatchers("/v3/api-docs",
                "/swagger-ui.html",
                "/swagger-ui/**");
    }
}
```

**Comment by durimkryeziu** [comment]
Just tested, it works perfect now!!

Thank you @springdoc

**Comment by OutingDay** [comment]
can you share entire class along with imports

**Comment by bnasslahsen** [comment]
> can you share entire class along with imports

You have a full working example on [demos](https://github.com/springdoc/springdoc-openapi-demos/tree/master/sample-springdoc-openapi-oauth2/oauth-resource-server):
