### ISSUE TITLE
Do Not Expose X-API-KEY

### ISSUE THREAD

**Issue by wh81752** [springdoc/springdoc-openapi#2300]
**Is your feature request related to a problem? Please describe.**

We are using API-KEY authentication. It works fine. However, the API-KEY is "leaked" when using the Springdoc-UI,  i.e. the "curl"-box below "Responses" show the api-key in clear-text.

Now and of course, if it's just me using the UI, then so what?

However, as API designer, as PO or just as happy developer you want to demonstrate that something is working to a wider audience, for example in Teams. Most often, you have no control over the audience, i.e. perhaps an unfriendly person is watching as well.

**Describe the solution you'd like**

1. Show only part of X-API-KE or show a Hash of it by default. Then a there is a toggle to switch between showing are partially hiding / obscuring.
2. Show the "curl box" collapsed by default and have a toggle to show it (IMHO: curl box is most of time useless; only occasionally of interested). 
3. Make Springdoc-UI configurable beyond 6 hard-wired styles. I.e there could be a custom js and css folder in my Springboot project and - depending on some flags - the css/js files are appended to existing styles or replace them.

- Add any other context or screenshots about the feature request here.

Screenshot:
I had to "erase" a lot of info.  However, you can see that x-api-key is leaked.

![image](https://github.com/springdoc/springdoc-openapi/assets/7973309/1058ef8c-a95c-4f2d-87c3-1b8bcec7d78f)

**Comment by uc4w6c** [comment]
It might be better to create this ticket at [swagger-ui](https://github.com/swagger-api/swagger-ui).

Springdoc also allows you to customize swagger-ui static resources.
https://springdoc.org/#customizing-swagger-static-resources.

**Comment by wh81752** [comment]
Thx for the pointer.
