### ISSUE TITLE
No schema found in swagger-ui.html

### ISSUE THREAD

**Issue by lllhh685** [springdoc/springdoc-openapi#2301]
@Data
@AllArgsConstructor
@NoArgsConstructor
@Builder
@Schema(name = "user", description = "userEntity")
public class User {
    @Schema(description = "id", example = "34")
    int id;
    @Schema(description = "username", example = "Seb")
    String username;
    @Schema(description = "password", example = "123456")
    String password;
}

![image](https://github.com/springdoc/springdoc-openapi/assets/44913624/860865b5-8e1f-4a2c-a6ca-13b02fbc2563)

**Comment by uc4w6c** [comment]
Please provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) that reproduces the problem
