### ISSUE TITLE
Kindly request to update transitive dependency

### ISSUE THREAD

**Issue by michalwilk96** [springdoc/springdoc-openapi#2306]
Actually, springdoc-openapi-starter-webflux-ui-2.1.0 contains high vulnerability.
Dependency path is the following:
springdoc-openapi-starter-webflux-ui-2.1.0  -> springdoc-openapi-starter-webflux-api-2.1.0 -> springdoc-openapi-starter-common-2.1.0 -> spring-boot-autoconfigure-3.0.6.

spring-boot-autoconfigure-3.0.6 contains a vulnerability, please upgrade it to the newest one.

**Comment by vishalsingh2972** [comment]
Hi @michalwilk96 can you specify a bit what's the issue here?

**Comment by michalwilk96** [comment]
Low dependency inside springdoc-openapi-starter-webflux-ui, which contains security vulnerability.
There's spring-boot-autoconfigure-3.0.6, but actually there's available spring-boot-autoconfigure-3.1.1.

**Comment by uc4w6c** [comment]
The current main branch utilizes springboot 3.1.0.
Therefore, it will be resolved in the next release.
