### ISSUE TITLE
Upgrade Swagger to 5.x version

### ISSUE THREAD

**Issue by JayAhn2** [springdoc/springdoc-openapi#2307]
**Is your feature request related to a problem? Please describe.**

I want to introduce open api 3.1, but it requires Swagger 5.x version

**Describe the solution you'd like**

upgrade swagger version to 5.x

**Describe alternatives you've considered**

**Additional context**

**Comment by uc4w6c** [comment]
Development has been completed with this PR. https://github.com/springdoc/springdoc-openapi/pull/2266
Please wait for the release of the next version.
