### ISSUE TITLE
Root level Tags list doesn't get populated if the "description" field is not specified for the @Tag at Controller level

### ISSUE THREAD

**Issue by amitojduggal** [springdoc/springdoc-openapi#2308]
**Describe the bug**

Root level Tags list doesn't get populated if the "description" field is not specified for the Tag. 

If only the name is specified and not the description on the Controller level, the tags list is **not** generated on the root level. 
Though, if the name and description both are provided the tags list is generated correctly. 

This shouldnt be the case, only specifying name should suffice.

**To Reproduce**

- What version of spring-boot you are using? 3.0.5
- What modules and versions of springdoc-openapi are you using? springdoc-openapi-starter-webmvc-api
- What is the actual and the expected result using OpenAPI Description (yml or json)? json
```
{
  "openapi" : "3.0.1",
  "info" : {
    "title" : "Hello",
    "description" : "Hello",
    "version" : "1.0.1-SNAPSHOT"
  },
  "servers" : [ {
    "url" : "https://localhost:8080",
    "description" : "PROD"
  }, {
    "url" : "https://localhost",
    "description" : "TEST"
  } ],
  "paths" : {
    "/v1/hello" : {
      "post" : {
        "tags" : [ "Hello" ],
        "operationId" : "fetch",
        "requestBody" : {
          "content" : {
            "application/json" : {
              "schema" : {
                "type" : "string"
              }
            }
          },
          "required" : true
        },
        "responses" : {
          "200" : {
            "description" : "OK"
          }
        }
      }
    }
  },
  "components" : { }
}
```

- Provide a sample code (HelloController) or Test that reproduces the problem 

**HelloController**
```
@RestController
@Tag(name = "Hello")
@RequestMapping("/v1/hello")
class HelloController {
    fun get() {
        // do Nothing
    }
}
```

**Expected behavior**

- The root level tags list should be generated only if the name property is specified for tags
- What is the expected result using OpenAPI Description (yml or json)?

```
{
  "openapi" : "3.0.1",
  "info" : {
    "title" : "Hello",
    "description" : "Hello",
    "version" : "1.0.1-SNAPSHOT"
  },
  "servers" : [ {
    "url" : "https://localhost:8080",
    "description" : "PROD"
  }, {
    "url" : "https://localhost",
    "description" : "TEST"
  } ],
  "tags" : [ {
    "name" : "Hello",
    "description" : "Hello"
  } ],
  "paths" : {
    "/v1/hello" : {
      "post" : {
        "tags" : [ "Hello" ],
        "operationId" : "fetch",
        "requestBody" : {
          "content" : {
            "application/json" : {
              "schema" : {
                "type" : "string"
              }
            }
          },
          "required" : true
        },
        "responses" : {
          "200" : {
            "description" : "OK"
          }
        }
      }
    }
  },
  "components" : { }
}
```

The tags list on the root level gets generated if i specify by name and description.

**Comment by uc4w6c** [comment]
The tags field is not a required field.
Reference: https://swagger.io/specification/ (OpenAPI Object)
