### ISSUE TITLE
Any way of using properties from application.yml as schema example?

### ISSUE THREAD

**Issue by gruutak** [springdoc/springdoc-openapi#231]
I'm trying to set an example for an endpoint schema, but I'd like to keep the example in a property files, like application.yml. Is there any way of using it in the example?

I tried the following code, but it didn't work:

```java
@Operation(summary = "Something something")
@ApiResponses(value = {
        @ApiResponse(responseCode = "200", description = "Successful operation",
                content = @Content(schema = @Schema(example = "${swagger.examples.fooApi}")))
})
@GetMapping(path = "/foo/{bar}", produces = APIVersions.API_VERSION_V1)
public ResponseEntity getFoo(@PathVariable("bar") @LogParameter final String bar) {
    return ResponseEntity.ok(this.fooService.getFoo(bar));
}
```

**Comment by johnheitor** [comment]
I too am looking for a solution for passing config param to @OAuthFlow tokenUrl as per @gruutak example.

**Comment by kremers** [comment]
👍

**Comment by kremers** [comment]
Please release 1.2.18 ❤️

**Comment by springdoc** [comment]
Hi, 

 A support will be available on v1.2.18. 
 The support will not be added to all the parameters as the performance impact is not yet evaluated.

 You can declare the following urls with v1.2.18, inside spring-boot properties/yml files (application.yml) and inject them into the swagger annotations using securityScheme or oAuthFlow:
 - securityScheme.openIdConnectUrl
 - oAuthFlow.authorizationUrl
 - oAuthFlow.refreshUrl
 - oAuthFlow.tokenUrl

**Comment by edgeofoblivion** [comment]
I'd be interested in a way to load detailed operation descriptions (containing markdown) from yaml, something like:

 `@Operation(summary = "This API will do something.", description = "${springdoc.operation-descriptions.myOperation}")`

This would keep the controller class less polluted when providing a detailed, formatted description.

Thanks.

**Comment by johnheitor** [comment]
Fantastic news. Thank you for adding support.
