### ISSUE TITLE
Illegal swagger-ui address should not raises 500 error

### ISSUE THREAD

**Issue by ldcsaa** [springdoc/springdoc-openapi#2313]
**Suggestion**
- 500 is a CRITICAL error for metrics and monitor alerts, maybe return 404 is better

**To Reproduce**
- navigate to uri like  `http://127.0.0.1:10001/swagger-ui` and `http://127.0.0.1:10001/swagger-uixxxxx` etc.
- It will raises 500 error

**Comment by uc4w6c** [comment]
Please provide a [Minimal, Reproducible Example - with HelloController](https://stackoverflow.com/help/minimal-reproducible-example) that reproduces the issue.

**Comment by Alf-Melmac** [comment]
This is already fixed (but not yet released) https://github.com/springdoc/springdoc-openapi/issues/2235
