### ISSUE TITLE
@RequestHeader DTO autoprocessing

### ISSUE THREAD

**Issue by Wpfal** [springdoc/springdoc-openapi#2314]
**Is your feature request related to a problem? Please describe.**

I am trying to setup a thing for v1.7.0 that uses a dto object to automatically convert the 20 potential headers into an object (such that it can be used in the over 300 endpoints). Is there a way to automatically Specify @RequestHeader on a dto with a list of objects e.g:
```java
public class HeaderDTO {
    private String URL;
    private String appType;
    private String phoneOS;
    private double deviceRotation;
    boolean detailOnly = false;
}
```

**Describe the solution you'd like**

I'd like the @RequestHeader to be able to support autopopulating dto's. This could include some type of field validation e.g. @NotNull, @DecimalMin ect. (*See Additional context for further explanation*). This can be added to the new version but we need it for version `implementation group: 'org.springdoc', name: 'springdoc-openapi-ui', version: '1.7.0'` (due to dependency issues preventing us from updating to latest)

**Describe alternatives you've considered**

I currently use a custom resolver that implements HandlerMethodArgumentResolver. This allows me to use the header in the api functionally but it just doesnt work with springdoc. 

**Additional context**

example conversion:
```java
@PostMapping
public void testEndpoint(@RequestHeader HeaderDTO header, @Valid @RequestBody LoginPayload payload) {
```
this currently yields:
```
curl -X 'POST' \
 'http://localhost:8080/api/v2/testendpoint' \
 -H 'accept: application/json' \
 -H 'Content-Type: application/json' \
 -H 'Header: url,string,appType,string,phoneOS,string,deviceRotation,string,detailOnly,true'\
 -d '{
 "username": "string",
 "password": "string",
}'
```
Notice it doesnt split them into their own headers it makes them one header and splits all of them (key/value and entry with `,`)
This proposed functionality would need to make it `-H 'url:string'\ -H 'appType:string'` etc

Many thanks, keep up the great work!

**Comment by bnasslahsen** [comment]
``springdoc-openapi v1.7.0 `` is the latest Open Source release supporting Spring Boot 2.x and 1.x. 

An extended support for [*springdoc-openapi v1*](https://springdoc.org/v1) 
project is now available for organizations that need support beyond 2023. 

For more details, feel free to reach out: sales@springdoc.org
