### ISSUE TITLE
Add Info to OpenAPI and GroupedOpenAPI properties

### ISSUE THREAD

**Issue by simomonster** [springdoc/springdoc-openapi#2318]
**Is your feature request related to a problem? Please describe.**

When declaring groups with properties it's not possible to add info customizations dynamically, for each group. 

Programmatically I can add info (Title, Description) to openAPIs, but when I want to generate groups dynamically I can't customize (adding Info) each grouped openAPI identifying it by group.
  
**Describe the solution you'd like**

- adding properties: `springdoc.info` and `springdoc.group-configs[].info` where info will be mapped to `io.swagger.v3.oas.models.info.Info` or at least `title`, `description`, `version` fields. ie:
`springdoc.info.title`
`springdoc.info.description`
`springdoc.info.version`
- Document is generated automatically (without adding customization) with info included

**Describe alternatives you've considered**

- In alternative, simpler, but with more effort for clients. Add `OpenApiGroupedCustomizer`. This way we can add info dynamically for each group.  
The alternative could be added even in parallel with the main solution, as it could be useful for other purposes as well.

**Comment by bnasslahsen** [comment]
You can use addOpenApiCustomizer:

```java
	@Bean
	public GroupedOpenApi tweetsOpenApi(@Value("${springdoc.version}") String appVersion) {
		String[] paths = { "/tweets/**" };
		return GroupedOpenApi.builder().
				group("tweets")
				.addOpenApiCustomizer(openApi -> openApi.info(new Info().title("Tweets API").version(appVersion)))
				.pathsToMatch(paths)
				.build();
	}
```

**Comment by simomonster** [comment]
> There are no plans to add these new properties. But feel free to propose a PR if you feel it's useful for the community.
> 
> You can use `addOpenApiCustomizer` instead:
> 
> ```java
> 	@Bean
> 	public GroupedOpenApi tweetsOpenApi(@Value("${springdoc.version}") String appVersion) {
> 		String[] paths = { "/tweets/**" };
> 		return GroupedOpenApi.builder().
> 				group("tweets")
> 				.addOpenApiCustomizer(openApi -> openApi.info(new Info().title("Tweets API").version(appVersion)))
> 				.pathsToMatch(paths)
> 				.build();
> 	}
> ```

Hi @bnasslahsen, thanks for the answer.
However the solution you posted is hardcoded, if I'm using springdoc properties to dynamically configure groups, then I can't add a specific customizer for each group thus I can't set proper info.

**Comment by bnasslahsen** [comment]
@simomonster,

As explained, only the programmatic way is now possible ...
