### ISSUE TITLE
[Feature request?] Reusable Enums

### ISSUE THREAD

**Issue by luStopai** [springdoc/springdoc-openapi#232]
Hi,

I'm unable to get Reusable Enums as specified here https://swagger.io/docs/specification/data-models/enums/ 

I've tried many annotations combinations trying to achieve this with no success.

Is it possible? If yes, how? If no, can this feature be added in a future release?

Thanks

**Comment by springdoc** [comment]
Hi, 

 You can add `@Schema(enumAsRef = true)` on your enum.
 This should make it reusable.

**Comment by Sam-Kruglov** [comment]
Found how to make it the default, just add this static block to any of your classes:
```java
static {
    io.swagger.v3.core.jackson.ModelResolver.enumsAsRef = true;
}
```

**Comment by roncsak** [comment]
> Found how to make it the default, just add this static block to any of your classes:
> 
> ```java
> static {
>     io.swagger.v3.core.jackson.ModelResolver.enumsAsRef = true;
> }
> ```

Do you know how to use this with Kotlin?

**Comment by Amar97** [comment]
> > Found how to make it the default, just add this static block to any of your classes:
> > ```java
> > static {
> >     io.swagger.v3.core.jackson.ModelResolver.enumsAsRef = true;
> > }
> > ```
> 
> Do you know how to use this with Kotlin?

If you still need it:

```kotlin
companion object {
     init {
          io.swagger.v3.core.jackson.ModelResolver.enumsAsRef = true
     }
 }
