### ISSUE TITLE
Authentication error shows as Possible CORS issue

### ISSUE THREAD

**Issue by mrgrew** [springdoc/springdoc-openapi#2322]
**Describe the bug**

With SpringDoc using the actuator management port and an endpoint that expects an unauthorized response (401), unauthorized responses show an "Undocumented" code with details 

> Failed to fetch.
> Possible Reasons:
> CORS
> Network Failure
> URL scheme must be "http" or "https" for CORS request.

I would expect to see a "401" code with details "Unauthorized"

**To Reproduce**

1. Clone this repo: `git clone https://github.com/mrgrew/swagger-auth-cors`
2. Change to the repo directory and run it: `./gradlew bootRun`
3. In a browser, navigate to `http://localhost:9090/actuator/swagger-ui`
4. Authorize with `Bearer api-key`
5. Open the "/api" endpoint and click "Execute".
6. You'll see a 200 status code with response `{}`
7. Use the Authorize button to "Logout"
8. Click "Execute" again and see an "Undocumented" code with details "Failed to fetch."
9. Expected output would be a "401" code with details "Unauthorized"

The demo above uses Spring Boot 3.1.2 and springdoc-openapi-starter-webflux-ui version 2.1.0.

**Expected behavior**

I expect a 401 response status code to appear as "401 Unauthorized", not "Undocumented Failed to fetch"

**Comment by bnasslahsen** [comment]
@mrgrew,

See answer here: https://github.com/springdoc/springdoc-openapi/issues/2277
