### ISSUE TITLE
add support for grouping based on http method types in springdoc

### ISSUE THREAD

**Issue by Adwait-Joshi94** [springdoc/springdoc-openapi#2323]
I have an unique requirement in my project to group the APIs based on the http method type of the APIs in a given package and generate API documentation. I have explored few options from srpingdoc properties, there are ways to group based on paths, packages, headers using springdoc.group-configs[0]. I would like to know if there is any way to group API documentation based on http method types like get, put, post etc. If it is not present, can we add this enhancement?

**Comment by bnasslahsen** [comment]
@Adwait-Joshi94,

You can add `OpenApiCustomizer` that enable you filter your groups by HTTP methods.
