### ISSUE TITLE
Global configuration to display Long type fields as String in Springdoc documentation

### ISSUE THREAD

**Issue by Clover-You** [springdoc/springdoc-openapi#2324]
Hey guys!

How can we globally set up the display of one data type as another in the documentation? For example, we have Long-type fields that need to be displayed as String due to frontend requirements. In the business logic, I can configure the conversion during Jackson serialization, but I'm not sure how to approach this with Springdoc. Using @Schema(type = "string") for every Long field is cumbersome because there are too many of them.

I tried to find a hook using Idea DEBUG to solve the problem, but it seems I haven't found one yet!

**Comment by Clover-You** [comment]
I think I should be done! I have implemented my own io.swagger.v3.core.converter.ModelConverter. I'm not sure if there will be any issues, but it's working well for now!

<img width="1310" alt="image" src="https://github.com/springdoc/springdoc-openapi/assets/50982977/355d1a0a-fdc8-41c2-a0b9-25eb0ac42b6b">


<img width="907" alt="image" src="https://github.com/springdoc/springdoc-openapi/assets/50982977/921ed502-fcd0-4f59-aa3e-7c58eb9b2d08">

<img width="582" alt="image" src="https://github.com/springdoc/springdoc-openapi/assets/50982977/9a64085a-5656-47b0-afc2-248ad28f5b3c">

**Comment by bnasslahsen** [comment]
closed, as you found the workaround!
