### ISSUE TITLE
Non-existing class in documentation

### ISSUE THREAD

**Issue by xsmrcek** [springdoc/springdoc-openapi#2325]
Hello,
as metioned in issue: https://github.com/springdoc/springdoc-openapi/issues/2321
I am supposed to register this Bean:
```
@Bean
    fun springDocsUiConfiguration(optionalSwaggerUiConfigProperties: Optional<SwaggerUiConfigProperties?>?): SpringDocsUIConfiguration? {
        return SpringDocsUIConfiguration(optionalSwaggerUiConfigProperties)
    }
```
But this class doesn't exist.

**Comment by xsmrcek** [comment]
It's probably typo and class should be SpringDocConfigProperties.

**Comment by bnasslahsen** [comment]
docs are updated
