### ISSUE TITLE
sources and javadoc artifact are empty for 2.2.8 - 2.2.15

### ISSUE THREAD

**Issue by zyrano** [springdoc/springdoc-openapi#2329]
**Describe the bug**

The javadoc and sources .jars provided by mvnrepository.com for swagger-models-jakarta contain only some meta data (licences, po.xml) but all the real content is missing.

Check https://repo1.maven.org/maven2/io/swagger/core/v3/swagger-models-jakarta/2.2.15/swagger-models-jakarta-2.2.15-javadoc.jar for instance.

**To Reproduce**

- In your IDE (Eclipse) have a reference to a class such as io.swagger.v3.oas.models.media.Schema and click on that reference
- The IDE gives some representation of the byte code and says something like "The source attachment does not contain the source for the file Schema.class"
- Similar behavior/no JavaDoc shown if trying to view the JavaDoc 

**Expected behavior**

- The JavaDoc is shown in the JavaDoc view
- The source code for the referenced class is opened

**Comment by zyrano** [comment]
Ah, I forgot: The corresponding artifacts without the "-jakarta" in the name seem to be fine.

**Comment by uc4w6c** [comment]
Please provide a [Minimal, Reproducible Example - with HelloController](https://stackoverflow.com/help/minimal-reproducible-example) that reproduces the issue.

**Comment by bnasslahsen** [comment]
@zyrano,

You are creating issue in the wrong project.
We do not release: https://repo1.maven.org/maven2/io/swagger/core/v3/swagger-models-jakarta/2.2.15/swagger-models-jakarta-2.2.15-javadoc.jar f

**Comment by lbruun** [comment]
Addressed here:   https://github.com/springdoc/springdoc-openapi/pull/2463
