### ISSUE TITLE
Support group Parameter to /apidocs.yaml

### ISSUE THREAD

**Issue by brianwyka** [springdoc/springdoc-openapi#233]
Support `gorups?=group-a` paramter for example to filter the resources documented in the output specification by the provided group.

**Comment by springdoc** [comment]
You can use the stand swagger-ui property filter.
Using springdoc-openapi configuration: 
```propeties
springdoc.swagger-ui.filter= group-a
```

**Comment by brianwyka** [comment]
Is this documented anywhere?

**Comment by springdoc** [comment]
Hi, 

 On the welcome page: http://springdoc.org/

The library supports the swagger-ui official properties:

- https://swagger.io/docs/open-source-tools/swagger-ui/usage/configuration/

You need to declare swagger-ui properties as spring-boot properties. All these properties should be declared with the following prefix: **springdoc.swagger-ui**

A new FAQ is added, for better capitalization:
- https://springdoc.github.io/springdoc-openapi-demos/faq.html

**Comment by brianwyka** [comment]
This is a swagger UI filter.  This also sets up the `api-docs.yaml` to respect that filter as well?

**Comment by brianwyka** [comment]
In my case, I am not using the Swagger UI feature, only the generation of the Open API Spec Yaml.  I would like to be able to filter the results of the Open API Spec by group similar to how Springfox Swagger allows the `v2/api-docs` to be filtered by group.  Does this make sense?

**Comment by springdoc** [comment]
Hi @brianwyka, 

 This feature might be added for the next release.
 You can follow #213.

**Comment by ZPavel** [comment]
Hi. 
I have 2 groups and with api-docs.yaml?group=foo or api-docs?yaml?group=bar provides the same yaml of the second group
Do you know if there is an issue with this please.

`@Configuration
class MyOpenAPIConfiguration {
    @Bean
    public GroupedOpenApi fooApi() {
        return GroupedOpenApi.builder()
                .group("foo")
                .pathsToMatch("/basepath/**")
                .pathsToExclude("/basepath/api/**")
                .addOpenApiCustomiser(apiCustomizer())
                .build();
    }
    
    @Bean
    public GroupedOpenApi barApi() {
        return GroupedOpenApi.builder()
                .group("bar")
                .pathsToMatch("/basepath/api/**")
                .addOpenApiCustomiser(apiBarCustomizer())
                .build();
    }

    @Bean
    public OpenApiCustomiser apiCustomizer() {
        return openApi -> openApi
                .info(new Info().title("Foo").version("V2").description("Foo"))
                .addSecurityItem(new SecurityRequirement().addList("JDCAuth"))
                .getComponents().addSecuritySchemes("MyAuth", new SecurityScheme()
                        .type(SecurityScheme.Type.HTTP)
                        .scheme("bearer")
                        .bearerFormat("JWT")
                        .in(SecurityScheme.In.HEADER));
    }

    @Bean
    public OpenApiCustomiser apiBarCustomizer() {
        return openApi -> openApi
                .info(new Info().title("Bar").version("V2").description("Bar"))
                .addSecurityItem(new SecurityRequirement().addList("JDCApiAuth"))
                .getComponents().addSecuritySchemes("MyAuth", new SecurityScheme()
                        .type(SecurityScheme.Type.HTTP)
                        .scheme("bearer")
                        .bearerFormat("JWT")
                        .in(SecurityScheme.In.HEADER));
    }
}`

My version is : org.springdoc:springdoc-openapi-ui:jar:1.6.14

Thanks
