### ISSUE TITLE
components.getSchemas() is giving null

### ISSUE THREAD

**Issue by HimanshuGangwarOfficial** [springdoc/springdoc-openapi#2330]
**Describe the bug**

I want to hide some schemas on swagger-ui. I am using programatic approach to achieve this functionality. So when I am creating the object of Component and getting all the schemas from component object then it is returning null. But I have model classes in my project which are reflecting in swagger ui.

        Components components = new Components();
        Map<String, Schema> schemas = components.getSchemas();

Here components.getSchemas() is returning null

**To Reproduce**

- What version of spring-boot you are using?
Spring-boot: 2.7.4
- What modules and versions of springdoc-openapi are you using?
springdoc-openapi-ui : 1.7.0

- Provide with a sample code (HelloController) or Test that reproduces the problem

    private Components getFilteredComponents() {
       
        Components components = new Components();
        Map<String, Schema> schemas = components.getSchemas();

        if (schemas != null && !schemas.isEmpty()) {
            components.setSchemas(filterSchemas(schemas));
        }
        return components;
    }

Here components.getSchemas() is returning null

**Comment by uc4w6c** [comment]
See this. https://springdoc.org/#how-can-i-customize-the-openapi-object
Please see here as the link is incorrect. https://github.com/springdoc/springdoc-openapi/blob/main/springdoc-openapi-starter-webmvc-api/src/test/java/test/org/springdoc/api/v30/app39/SpringDocTestApp.java
