### ISSUE TITLE
springdoc.api-docs.enabled does not work with GraalVM

### ISSUE THREAD

**Issue by kthumin** [springdoc/springdoc-openapi#2331]
**Describe the bug**

If GraalVM is used, `springdoc.api-docs.enabled= false` and `springdoc.swagger-ui.enabled=false` , but swagger UI and api doc is still active. 

**To Reproduce**

- What version of spring-boot you are using? 
 Spring Boot 3.1.1

- What modules and versions of springdoc-openapi are you using? 
springdoc-openapi-starter-webmvc-ui: 2.1.0

- What is the actual and the expected result using OpenAPI Description (yml or json)? 
As described. 

- Provide with a sample code (HelloController) or Test that reproduces the problem
NA.

**Expected behavior**

Swagger UI and api docs should be disabled, if enabled flag is set to false in GraalVM.

**Screenshots**
NA

**Additional context**
NA

**Comment by uc4w6c** [comment]
Didn't reproduce on my local.
Please provide a [Minimal, Reproducible Example - with HelloController](https://stackoverflow.com/help/minimal-reproducible-example) that reproduces the issue.

**Comment by HyoKImAbsolut** [comment]
same issue
