### ISSUE TITLE
Failed to load API definition on URL /v3/api-docs/ (HTTP 404 not found error)

### ISSUE THREAD

**Issue by rasenderhase** [springdoc/springdoc-openapi#2332]
**Describe the bug**

<img width="1125" alt="image" src="https://github.com/springdoc/springdoc-openapi/assets/2706704/1d28c2f0-8987-4c0f-9163-b2e564a15a08">

The swagger-ui frontend tries to load the openapi data from the URL

`/v3/api-docs/` with trailing slash.

The backend resource `OpenApiWebMvcResource` listens per default on `/v3/api-docs` without trailing slash.

In fact, the URL `/v3/api-docs/` gets mapped wrongly by Spring:

```
2023-08-03 14:28:42,652 DEBUG [http-nio-8080-exec-1][][] o.s.s.w.FilterChainProxy: Secured GET /v3/api-docs/
2023-08-03 14:28:42,657 DEBUG [http-nio-8080-exec-1][][] o.s.w.s.DispatcherServlet: GET "/my-application/v3/api-docs/", parameters={}
2023-08-03 14:28:44,604 DEBUG [http-nio-8080-exec-1][][] o.s.w.s.h.SimpleUrlHandlerMapping: Mapped to ResourceHttpRequestHandler [classpath [META-INF/resources/], classpath [resources/], classpath [static/], classpath [public/], ServletContext [/]]
2023-08-03 14:28:45,977 DEBUG [http-nio-8080-exec-1][][] o.s.w.s.r.ResourceHttpRequestHandler: Resource not found
```

So the frontend displays the error `response status is 404 /my-application/v3/api-docs/`.

I am using...

```
 org.springdoc:springdoc-openapi-starter-webmvc-ui:2.1.0
 org.springframework.boot:spring-boot-gradle-plugin:3.1.2
```

Maybe the issue is caused by this change in Spring:

https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/web/servlet/config/annotation/PathMatchConfigurer.html#setUseTrailingSlashMatch(java.lang.Boolean)

The Spring framework is now more precise per default handling URLs. I think the controller that is providing the _swagger-config_ should be adapted. Currently it adds a trailing slash to the 1st url in the urls array:

```
{
    "configUrl": "/my-application/v3/api-docs/swagger-config",
    "defaultModelExpandDepth": "10",
    "defaultModelRendering": "model",
    "defaultModelsExpandDepth": "-1",
    "docExpansion": "full",
    "oauth2RedirectUrl": "http://127.0.0.1:16071/my-application/swagger-ui/oauth2-redirect.html",
    "urls": [
        {
            "url": "/my-application/v3/api-docs/",
            "name": ""
        },
        {
            "url": "/my-application/v3/api-docs/api",
            "name": "api"
        }
    ],
    "validatorUrl": ""
}
```

**Comment by uc4w6c** [comment]
Please provide a [Minimal, Reproducible Example - with HelloController](https://stackoverflow.com/help/minimal-reproducible-example) that reproduces the issue.

**Comment by rasenderhase** [comment]
I have created a demo [project](https://github.com/rasenderhase/demo-api-docs-issue). And of course it works... ;-)

However, the response of http://localhost:8080/v3/api-docs/swagger-config looks different in the demo project:
```
{
    "configUrl": "/v3/api-docs/swagger-config",
    "oauth2RedirectUrl": "http://localhost:8080/swagger-ui/oauth2-redirect.html",
    "url": "/v3/api-docs",
    "validatorUrl": ""
}
```

In the project with the issue, the property `url` is not present, instead there is the property `urls` which is an array. How can I achieve that in the demo project? Maybe that is causing the issue...?

**Comment by rasenderhase** [comment]
I have added the `OpenApiConfig` we are using, and that introduces the issue. see https://github.com/rasenderhase/demo-api-docs-issue/commit/d5e22662ecf49bc8aea21c24ea9f7354b7cdd1fa

**Comment by uc4w6c** [comment]
Thank you.
But it returns 404.
private repository?

**Comment by rasenderhase** [comment]
Now it's public. Sorry for that.

**Comment by bnasslahsen** [comment]
@rasenderhase,

The group Name cannot be null or empty.
I have updated the rule for the future release so there is no misunderstanding.

**Comment by EdgardHernandezp** [comment]
I'm having the same problem, apparently this was closed and fixed but I don't understand whats the workaround. I'm using version 2.20
<img width="1654" alt="image" src="https://github.com/springdoc/springdoc-openapi/assets/51146801/c0369be6-d18a-4637-a54d-cdc3a8d67980">

**Comment by rasenderhase** [comment]
If you are using config, check if the group name is empty. That is not allowed.

    @Bean
    public GroupedOpenApi all() {
        return createDefaultGroupedOpenApi("", "/**");
    }

**Comment by EdgardHernandezp** [comment]
I understand but in my case all I did was add the dependency and exclude from the authorization flow this paths:

/swagger-ui.html
/swagger-ui/**
/v3/api-docs/**
/v3/api-docs.yaml
/swagger-resources
/swagger-resources/**
/configuration/ui
/configuration/security
/swagger-ui/**
/webjars/**

At this point it should be working :(
