### ISSUE TITLE
 when use @Schema at ObjectNode or Map field, it does not work

### ISSUE THREAD

**Issue by wulcy** [springdoc/springdoc-openapi#2333]
**Describe the bug**
when use @Schema at ObjectNode or Map field,  it does not work

**To Reproduce**

- What version of spring-boot you are using?
- 3.0.7
- What modules and versions of springdoc-openapi are you using?
- 2.1.0
- What is the actual and the expected result using OpenAPI Description (yml or json)?
- <img width="679" alt="图片" src="https://github.com/springdoc/springdoc-openapi/assets/5967029/81cbcba5-07b3-475b-b862-d12e8c0194b8">
- Provide with a sample code (HelloController) or Test that reproduces the problem
```
import com.fasterxml.jackson.databind.node.ObjectNode;
...
@Schema(
        description = "description",
        requiredProperties = {"name", "type", "stage"},
        implementation = UpdateOpportunityRequest.class,
        additionalProperties = Schema.AdditionalPropertiesValue.TRUE
)
private ObjectNode attributes;
...
```
**Expected behavior**
attributes field should has UpdateOpportunityRequest's schema

**Comment by uc4w6c** [comment]
This seems to be a swagger-core issue.
Please create an issue at https://github.com/swagger-api/swagger-core.
