### ISSUE TITLE
Not support RequestMapping with params

### ISSUE THREAD

**Issue by ImmortalD** [springdoc/springdoc-openapi#2336]
**Describe the bug**

- I used the param parameter in the @RequestMapping annotation, and Swagger was unable to display properly.

**To Reproduce**

- write a test controller
```java
@RestController
@RequestMapping("/")
@Tag(name = "Test")
public class Test {

    @Operation(operationId = "Query", summary = "Query")
    @GetMapping(params = "Action=Query")
    public String query() {
        return "Query";
    }

    @Operation(operationId = "QueryById", summary = "QueryById")
    @GetMapping(params = "Action=QueryById")
    public String queryById() {
        return "Query by id";
    }

    @Operation(operationId = "Delete", summary = "Delete")
    @DeleteMapping(params = "Action=Delete")
    public String delete() {
        return "Delete";
    }
}
```

**Expected behavior**

The Action=Query API was not displayed, while QueryById was displayed. When I clicked "Try it out" on the Swagger page, then clicked the "Execute" button, the curl command below was also incorrect.

![image](https://github.com/springdoc/springdoc-openapi/assets/29126429/fbd08b70-f0ec-47e1-944b-e9cd8277ad1e)

**Comment by bnasslahsen** [comment]
@ImmortalD,

Please do not create duplicates.

See answer here:
- https://github.com/springdoc/springdoc-openapi/issues/580
