### ISSUE TITLE
`@Size` annotation on `List<String>` causes incorrect openapi spec to be generated.

### ISSUE THREAD

**Issue by caspianb** [springdoc/springdoc-openapi#2337]
Using a simple DTO can reproduce this issue:
```
static class RequestDto {
    @Size(min = 1, max = 5)
    @Schema(description = "List of values.")
    private List<String> values;
}
```

The `@Size` validation is only (correctly) applied to the list size. However, the api spec itself is showing this:
![image](https://github.com/springdoc/springdoc-openapi/assets/4147822/875616df-6d9b-448a-bb87-222253b45cf8)

The generated API spec is stating that:
* the list must be between 1 and 5 elements (correct);
* the length of the string of each element must be between 1 and 5 characters (incorrect)

You can also see that the description is also being duplicated from the array down to the element as well. I am uncertain if this is intentional and or desirable so not sure if that should also be considered a bug as well.

**Comment by bnasslahsen** [comment]
@caspianb,

This looks to be correct.
Anyway, you can ask the `swagger-core` project for more explanation, as this is purely handled by `swagger-core-jakarta`

```java
public class DemoApplication {

	record TestDTO(@Size(min = 1, max = 5)
						  @Schema(description = "List of values.")
						  List<String> values) {

	}
	
	public static void main(String[] args) {
		ResolvedSchema resolvedSchema = ModelConverters.getInstance()
				.resolveAsResolvedSchema(
						new AnnotatedType(TestDTO.class).resolveAsRef(false));
		resolvedSchema.schema.getMinLength();
		Assert.isTrue(((ArraySchema) resolvedSchema.schema.getProperties().get("values")).getMaxItems().equals(5));
		Assert.isTrue(((ArraySchema) resolvedSchema.schema.getProperties().get("values")).getItems().getMaxLength().equals(5));
	}
	
}
```

**Comment by caspianb** [comment]
Thanks for the quick response! -- I'll log an issue at swagger-core.

> This looks to be correct.

Can you explain this to me, though? The _item_ maxLength relates to the String itself. The @Size annotation only applies to the List, though. The String can still be any length (and that's how the spring-boot validations work). It seems like the openApi spec is saying the String must be between 1 and 5 characters -- which is not correct?

**Comment by bnasslahsen** [comment]
@caspianb,

You have already been answered.
No more answer will be added in this ticket.
