### ISSUE TITLE
Collapse tags  by default

### ISSUE THREAD

**Issue by programmer-luxw** [springdoc/springdoc-openapi#234]
how can I do for Collapse tags by default，Because there are so many paths。

**Comment by programmer-luxw** [comment]
i know

**Comment by joaodias14** [comment]
Would you mind to share the way you were able to do that? Thanks!

**Comment by springdoc** [comment]
Hi @joaodias14 ,

 You can set this property in your application.yml like so for example:

`springdoc.swagger-ui.doc-expansion= none
`

**Comment by joaodias14** [comment]
Many thanks @springdoc !

**Comment by programmer-luxw** [comment]
@springdoc 

@Hidden
public class IndexController 

I find the @HIidden on IndexController have no effect, is bug?
