### ISSUE TITLE
lombok @Data Not working for controller @RequestBody

### ISSUE THREAD

**Issue by zhaojigang** [springdoc/springdoc-openapi#2344]
**Describe the bug**

my code：
pom.xml
springboot 3.1.2
```
		<dependency>
			<groupId>org.springdoc</groupId>
			<artifactId>springdoc-openapi-starter-webmvc-ui</artifactId>
			<version>2.0.2</version>
		</dependency>
		<dependency>
			<groupId>org.projectlombok</groupId>
			<artifactId>lombok</artifactId>
			<version>1.18.28</version>
			<scope>provided</scope>
		</dependency>
```
```
@Data
public class TextToImageRequest {
    private String prompt;
    private String negative_prompt;
}
```
```
@CrossOrigin
@RestController
@RequestMapping("/sd")
public class StableDiffusionController {

    @PostMapping("textToImg")
    public Result<String> textToImg(@RequestBody TextToImageRequest request) {
       ...
    }
}
```
![image](https://github.com/springdoc/springdoc-openapi/assets/14085645/fef6d31e-be4c-4445-9a4c-602da6629995)

when i change TextToImageRequest.java to:(remove @Data and add noargconstructor/getter/setter)
```
public class TextToImageRequest {
    private String prompt;
    private String negative_prompt;

    public TextToImageRequest() {
    }

    public String getPrompt() {
        return prompt;
    }

    public void setPrompt(String prompt) {
        this.prompt = prompt;
    }

    public String getNegative_prompt() {
        return negative_prompt;
    }

    public void setNegative_prompt(String negative_prompt) {
        this.negative_prompt = negative_prompt;
    }
}

```
![image](https://github.com/springdoc/springdoc-openapi/assets/14085645/cd6e8f57-428d-49ad-975d-9cc7252c365f)

**Comment by bnasslahsen** [comment]
@zhaojigang,

Not reproducible.
if you are still having the issue, please make sure to provide the link to a 
[Minimal, Reproducible Example - with HelloController](https://stackoverflow.com/help/minimal-reproducible-example) that reproduces the problem

**Comment by zhaojigang** [comment]
thanks for reply, maybe i found the reason: i set java compiler with "eclipse" but not "javac", change to javac, its right
