### ISSUE TITLE
Jackson Module not applied

### ISSUE THREAD

**Issue by henke77** [springdoc/springdoc-openapi#235]
My request body contains a field of type javax.money.MonetaryAmount.
In order to get a usable swagger-ui-input field I want to apply the org.zalando.jackson.datatype.money.MoneyModule. I tried to add this Module both to a new and to an existing  com.fasterxml.jackson.databind.ObjectMapper. However, the swagger-ui output keeps on visualizing the monetaryamount like this:

{
factory{...}
context{...}
zero
negative
positive
positiveOrZero
negativeOrZero
currency{...}
number{...}
} 

It seems like the org.springdoc.core.converters.ObjectNodeConverter is taking care of MonetaryAmount before the MoneyModule is applied.

**Comment by springdoc** [comment]
Hi, 

You can override this behaviour by providing your own ModelConverter a spring bean.
- https://github.com/swagger-api/swagger-core/wiki/Swagger-2.X---Extensions#extending-core-resolver

 You can have a look, on a sample code using ModelConverter here:
- https://github.com/springdoc/springdoc-openapi/blob/master/springdoc-openapi-data-rest/src/main/java/org/springdoc/core/converters/PageableSupportConverter.java


 Did you define your own converter ?

**Comment by henke77** [comment]
Hi,

thanks for your reply. We now implemented a custom converter and it works fine. I was falsely assuming the Zalando MoneyModule would do this for me.

So, thanks again.

**Comment by jnfeinstein** [comment]
@henke77 any chance you'd be willing to share the converter that you came up with?  I'm plagued by the same exact issue!

**Comment by henke77** [comment]
@jnfeinstein At https://github.com/swagger-api/swagger-core/wiki/Swagger-2.X---Extensions you find an example how to implement a model converter. At https://github.com/zalando/jackson-datatype-money/issues/6 you can find an example of a custom money node class.
