### ISSUE TITLE
JWT Token truncated

### ISSUE THREAD

**Issue by mengyu-dev** [springdoc/springdoc-openapi#2354]
Hi, I have configured an OAuth2 SecuritySchemeType and it works correctly with a small JWT,
but when the size of JWT increase (for example because a user has a lot of information) when the api is called the token passed into parameter -H 'Authorization: Bearer JWT_TOKEN' is truncated by .. in the middle of token.

**Comment by uc4w6c** [comment]
Please provide a [Minimal, Reproducible Example - with HelloController](https://stackoverflow.com/help/minimal-reproducible-example) that reproduces the issue.

And if it's a "Try it Out" process, please create an issue in swagger-ui.
https://github.com/swagger-api/swagger-ui
