### ISSUE TITLE
ToString和@JsonValue 冲突  。toString失去作用

### ISSUE THREAD

**Issue by Ruan-WenBo** [springdoc/springdoc-openapi#2355]
我想通过重写ToString方法的形式自动生成枚举描述，但是不起作用，我将@JsonValue放在ToString方法上面但是影响了入参的解析。我应该怎么自定义展示描述，自动生成的方式？

**Comment by uc4w6c** [comment]
Please provide a [Minimal, Reproducible Example - with HelloController](https://stackoverflow.com/help/minimal-reproducible-example) that reproduces the issue.

This ticket will be closed and can be reopened if the relevant information are provided.
