### ISSUE TITLE
@Schema example not showing for dates

### ISSUE THREAD

**Issue by radulecu** [springdoc/springdoc-openapi#2356]
I am having a date as follows:
```
@Schema(
    type = "string",
    format = "date",
    example = "20230203"
    pattern = "yyyyMMdd"
)
@JsonFormat(pattern="yyyyMMdd")
LocalDate myDate;
```

What I get when I go in .../api-docs endpoint is: `"myDate" : {"type" : "string", "format" : "date", "pattern" : "yyyyMMdd"}`

As a result in the swagger I end up by default with today instead of my provided example, and even worse a date which is the wrong format '2023-08-22'.

I need to have the flexibility to put any valid value as example.

The solution of removing the format field is not ok because the swagger is used to generate the DTOs in a client application. 
I need to know that the field is a date so it will be generated as a LocaDate instead of a String in the client application. This is why the solution provide in [1472](https://github.com/springdoc/springdoc-openapi/issues/1472) ("if you need to keep your example, then remove the format, so it can be interpreted as string.") is not ok.

What is the logic of not providing the example just because the field is a date?

They are 2 complete different fields and if both are provided both should result in the swagger.

Also if you provide a pattern and no example the default value should be in that format. not the default one. (for yyyyMMdd pattern you should get '20230822' not '2023-08-22').

**Comment by uc4w6c** [comment]
If the 'format' is set to 'date', it must follow the RFC 3339 format.
More details: https://swagger.io/docs/specification/data-models/data-types/

Alternatively, you can use the format below.

```java
      @Schema(
          type = "string",
          example = "20230203",
          pattern = "yyyyMMdd"
      )
      @JsonFormat(pattern="yyyyMMdd")
      LocalDate myDate
```

**Comment by radulecu** [comment]
While I think we both agree that the code must encourage standards like the one you just mentioned, with defaults, and with warnings when the standard is not respected, there are a lot of places where legacy code does not fully respect them, and it is hard to migrate to the standards you mentioned immediately.

I would respect the standard if it was for new code. But such is not always the case.

So if the 'format' is set to 'date', it does not have to follow the RFC 3339 format. It just must do it by default and it must allow the client to override this behavior when he wants to do so, preferably with a waring log, even with the risk of breaking the standard.

**Comment by StefanSchrass** [comment]
Thank you @radulecu I was getting crazy over my examples (date-time but similar issue) not working. No Log, no nothing, just not working.

A pretty underwhelming experience and I have to totally agree with you on the documentation tool taking a bold stance here.
