### ISSUE TITLE
Just wondering why Spring Boot still use 1.7.0

### ISSUE THREAD

**Issue by Adriansun** [springdoc/springdoc-openapi#2358]
Title says it all. You have released a couple of new versions but Spring Boot and Maven repository does not seem to reflect that. What gives? By the way; looking forward to the virtual thread stuff. Might be good when everyone has switched over to it. Cheers.

**Comment by bnasslahsen** [comment]
@Adriansun,

Can you clarify this **Spring Boot still use 1.7.0** ?!
And in general title is not enough as mentioned in the [contributing guidelines](https://github.com/springdoc/springdoc-openapi/blob/d4f99ac9036a00ade542c3ebb1ce7780a171d7d8/CONTRIBUTING.adoc).
 
Anyway, feel free to follow the docs: https://springdoc.org/#Introduction
And if you have any other question, please make sure you follow the [contributing guidelines](https://github.com/springdoc/springdoc-openapi/blob/d4f99ac9036a00ade542c3ebb1ce7780a171d7d8/CONTRIBUTING.adoc),
