### ISSUE TITLE
Schema.RequiredMode.Required not working for spring mvc and kotlin

### ISSUE THREAD

**Issue by olbpetersson** [springdoc/springdoc-openapi#2360]
**Describe the bug**

When building the same case as the springdoc-kotlin-test module does [here](https://github.com/springdoc/springdoc-openapi/blob/main/springdoc-openapi-tests/springdoc-openapi-kotlin-tests/src/test/resources/results/app9.json) in a spring boot 3 webMVC app,  the openAPI-spec ends up with all the fields being reported as required.

**To Reproduce**
I've copied the resources from the test referenced above into an example app with a (failing) test which can be found here:
https://github.com/olbpetersson/springdoc-webmvc-test/blob/main/src/test/kotlin/com/example/demo/DemoApplicationTests.kt

and can be executed via `./gradlew bootRun & ./gradlew test`

**Expected behavior**
The fields annotated with @Schema.RequiredMode.NOT_REQUIRED should not end up in the required list. The openAPI-spec should be the same as the one in app9.json referenced above

**Screenshots**
-
**Additional context**
-

**Comment by bnasslahsen** [comment]
@olbpetersson,


Tests are following the test cases described here:
- https://github.com/springdoc/springdoc-openapi/issues/2185

If you have `@Schema.RequiredMode.NOT_REQUIRED` explicitly defined, you wil not end up with `required`.

**Comment by olbpetersson** [comment]
@bnasslahsen what you are writing is what I would expect, but when I run the test code that I provided that doesn't seem to be the case. As you can see in my test class, I am using `@field:Schema.RequiredMod.NOT_REQUIRED` on e.g. 
```
	@field:Schema(requiredMode = Schema.RequiredMode.NOT_REQUIRED, defaultValue = "a default value")
	val noRequiredNullableDefault2: String?,
```

but it still shows up as required in the schema (see my test) 
![image](https://github.com/springdoc/springdoc-openapi/assets/6216422/82ea9cfe-ac6d-45be-a489-bf1bdaba0af6)
. 

There seems to be a discrepancy between webflux and webmvc

**Comment by egrimstad** [comment]
Hi. Just hit this problem when migrating to springdoc from springfox, on Kotlin fields that are not nullable but have a default value:
```kotlin
@field:Schema(requiredMode = Schema.RequiredMode.NOT_REQUIRED)
val foo: String = "default"
```
This still gets marked as required. Are there any workarounds?
