### ISSUE TITLE
What is the default value of springdoc.swagger-ui.validatorUrl?

### ISSUE THREAD

**Issue by Quu-Ukko** [springdoc/springdoc-openapi#2362]
In the 1.6.2 release notes validation is mentioned to be turned of by default.  In the 1.7.0 documentation the default value is https://validator.swagger.io/validator . Is the documentation outdated or was the default value changed in a another release?

**Comment by uc4w6c** [comment]
Thank you.
I created a pull request because the documentation was incorrect.
https://github.com/springdoc/springdoc.github.io/pull/66
