### ISSUE TITLE
swagger-ui: Validation error: can't read from file

### ISSUE THREAD

**Issue by nicolasduminil** [springdoc/springdoc-openapi#2367]
Hello,

Using springdoc-openapi-starter-webmvc-ui 2.0.0 with SB 3.0.2. I'm running the swaggerapi/swagger-ui:latest image. 
Browsing to the home page, I get the the API page with the yellow "Invalid" widget in the right lower corner, as shown in the attached screen copy. Clicking on it, I get the message "Can't read from file ...", as shown in the 2nd attached screen copy. 
Clicking again on the message I get the content of the mentioned file, proving that the file can be read, as opposed to what the message is stating. Please see the 3rd attached screen copy.

**To Reproduce**

- Clone the repository at https://github.com/nicolasduminil/ncts
- Go to the openapi branch
- cd to the ncts directory
- run the build.sh script
- browse to 192.168.96.10:8080

The openapi page should display without any validation error. But the unexpected validation error message appears.
What am I doing wrong here ?

Many thanks in advance for any help.

![swgger-ui](https://github.com/springdoc/springdoc-openapi/assets/1037978/d5f2e04f-6ee5-4f75-bc8b-85e414283eae)
![swagger-ui3](https://github.com/springdoc/springdoc-openapi/assets/1037978/2fbbd408-bd03-43e7-8488-783d0ca0b391)
![swagger-ui2](https://github.com/springdoc/springdoc-openapi/assets/1037978/00acd3ee-90d2-462a-8ed7-f32ac8b605a9)

**Comment by uc4w6c** [comment]
I couldn't find https://github.com/nicolasduminil/ncts.
Please make your repository public.

This ticket will be closed and can be reopened if the relevant information are provided.
