### ISSUE TITLE
The copy button not working, can be upgrade swagger-ui version 5.3.1+

### ISSUE THREAD

**Issue by jsbxyyx** [springdoc/springdoc-openapi#2369]
**Is your feature request related to a problem? Please describe.**

- A clear and concise description of what the problem is. Ex. I'm always frustrated
  when [...]
- What is the actual result using OpenAPI Description (yml or json)?

**Describe the solution you'd like**

- A clear and concise description of what you want to happen.
- What is the expected result using OpenAPI Description (yml or json)?

**Describe alternatives you've considered**

- A clear and concise description of any alternative solutions or features you've
  considered.

**Additional context**

- Add any other context or screenshots about the feature request here.

**Comment by uc4w6c** [comment]
Which copy button specifically?

And please create an issue on swagger-ui.
https://github.com/swagger-api/swagger-ui
