### ISSUE TITLE
type error

### ISSUE THREAD

**Issue by FPEsocrter** [springdoc/springdoc-openapi#2375]
package com.A;

public class userAgentDto {

    private String userAgent;

}

package com.b;

public class userAgentDto {

    private String test;

}
Only one of them can be recognized
When used in interfaces
It can be a different interface

<dependency>
            <groupId>com.github.xiaoymin</groupId>
            <artifactId>knife4j-openapi3-jakarta-spring-boot-starter</artifactId>
            <version>4.3.0</version>
        </dependency>

**Comment by wellybean** [comment]
@FPEsocrter Set config property 'springdoc.use-fqn' to 'true' and the schema generated will have both classes
![image](https://github.com/springdoc/springdoc-openapi/assets/33156542/d336189f-7979-444a-b848-92ee9404c84d)
