### ISSUE TITLE
[I18n] Translation not working on @SecurityScheme - description

### ISSUE THREAD

**Issue by DVD27** [springdoc/springdoc-openapi#2377]
Hello, 

I think the security description should be translated like other description :

Potentially here : 
https://github.com/springdoc/springdoc-openapi/blob/d4f99ac9036a00ade542c3ebb1ce7780a171d7d8/springdoc-openapi-starter-common/src/main/java/org/springdoc/core/service/SecurityService.java#L247C10-L247C10

**Comment by bnasslahsen** [comment]
@DVD27,

If you are reporting a bug, please help to speed up problem diagnosis by providing as much information as possible:

You need to describe your context (the title of an issue is not enough)

What version of spring-boot you are using?

What modules and versions of springdoc-openapi are you using?

What are the actual and the expected result using OpenAPI Description (yml or json)?

Provide a [Minimal, Reproducible Example - with HelloController](https://stackoverflow.com/help/minimal-reproducible-example) that reproduces the problem
