### ISSUE TITLE
RangeError for larger list response

### ISSUE THREAD

**Issue by ddhananjay** [springdoc/springdoc-openapi#2378]
Hi Team,

For Swagger api response of List of Objects, if it Is exceeding count of more than around 3000 records, swagger api shows
😱 Could not render yt, see the console.

with console error
RangeError: Maximum call stack size exceeded.
Object

componentStack:  {base url}/api/swagger-ui/swagger-ui-bundle.js:2:542995↵
Could fine few traces of fix for this bug spring fox lib, but couldn't get rid with 2.2.0 version 

lib used:   implementation 'org.springdoc:springdoc-openapi-starter-webmvc-ui:2.1.0' 
and tried with   implementation 'org.springdoc:springdoc-openapi-starter-webmvc-ui:2.2.0' as well

**Comment by uc4w6c** [comment]
This is a swagger-ui issue.
https://github.com/swagger-api/swagger-ui

By the way, it may be resolved by `springdoc.swagger-ui.syntaxHighlight.activated=false`.
