### ISSUE TITLE
Wrong redirect with modified spring.mvc.servlet.path

### ISSUE THREAD

**Issue by GrmpfNarf** [springdoc/springdoc-openapi#238]
Hi,
I have a problem changing the `spring.mvc.servlet.path` property.
Because the SwaggerWelcome controller listens to `springdoc.swagger-ui.path` and also redirects to it the redirect breaks when i change the `springdoc.swagger-ui.path`.

Here are some examples

### Example 1
application.properties
````
spring.mvc.servlet.path=/api
springdoc.swagger-ui.path=/api/swagger-ui.html
````
Results in a 404 for `/context_path/swagger-ui.html` and `/context_path/api/swagger-ui.html` because the controller listens to `/context_path/api/api/swagger-ui.html`

### Example 2
application.properties
````
spring.mvc.servlet.path=/api
springdoc.swagger-ui.path=/swagger-ui.html
````
Now the controller listents correctly to `/context_path/api/swagger-ui.html` but redirects wrong to
`/context_path/swagger-ui/...`

Am I doing something wrong ?

**Comment by springdoc** [comment]
Hi, 
 
  spring.mvc.servlet.path was not handled. 
 The support will  be available on the next release: 1.2.18

```properties
spring.mvc.servlet.path=/api
springdoc.swagger-ui.path=/swagger-ui.html
```
 You will be able to have access to the UI, using the following url:  `/context_path/api/swagger-ui.html`
