### ISSUE TITLE
The description attribute of the @Schema annotation is not valid for Multipart attributes. Look at the generated JSON string, there is no descripton attribute, but it is normal to use other types.

### ISSUE THREAD

**Issue by LoveC521** [springdoc/springdoc-openapi#2380]
The description attribute of the @Schema annotation is not valid for Multipart attributes. Look at the generated JSON string, there is no descripton attribute, but it is normal to use other types.

**Comment by bnasslahsen** [comment]
Remember, contributions to this repository should follow its [contributing guidelines](https://github.com/springdoc/springdoc-openapi/blob/d51b98a8e4490e1e9ecd6b90f763d8993d2e2309/CONTRIBUTING.adoc), [security policy](https://github.com/springdoc/springdoc-openapi/blob/d51b98a8e4490e1e9ecd6b90f763d8993d2e2309/SECURITY.md), and [code of conduct](https://github.com/springdoc/springdoc-openapi/blob/d51b98a8e4490e1e9ecd6b90f763d8993d2e2309/CODE_OF_CONDUCT.md).
