### ISSUE TITLE
Update dependency versions to add boundary specific Content Type support for Multipart requests

### ISSUE THREAD

**Issue by fethiyildiz** [springdoc/springdoc-openapi#2382]
**Is your feature request related to a problem? Please describe.**

Hello,

Latest version (2.2.0) of springdoc-openapi-starter-webmvc-ui library doesn't support content type for multipart requests.

This problem already addressed below;
https://github.com/springdoc/springdoc-openapi/issues/820#issuecomment-672875450

Swagger UI finally fixed these issues.

This is the issue;
https://github.com/swagger-api/swagger-ui/issues/5356#issue-445220978

And this is the pull request;
https://github.com/swagger-api/swagger-ui/pull/9105

Also webjars/swagger-ui library bring this feature with 5.4.2 version;
https://github.com/webjars/swagger-ui/issues/196

But when i looked the pom, i saw latest version of (2.2.0) uses 5.2.0 version of webjars/swagger-ui library.
But this feature came with 5.4.2 release so could you update webjars/swagger-ui dependency version please?

<img width="1354" alt="image" src="https://github.com/springdoc/springdoc-openapi/assets/25123562/4b76ae6a-77da-4bf5-961f-0f20329ebf31">

**Describe alternatives you've considered**

I tried to override webjars dependency version like below; 
But somehow swagger-ui docs doesn't generated. Because i can't see any logs for "docs generated" like before. 
Also when i try to call swagger ui link it gives me 404 Not Found.
But i don't know why this is happening.

<img width="1397" alt="image" src="https://github.com/springdoc/springdoc-openapi/assets/25123562/52889e70-228b-4d18-8053-c232580142bf">

<img width="631" alt="image" src="https://github.com/springdoc/springdoc-openapi/assets/25123562/53bb9a16-ab79-4992-8f18-a2aa4ac2325c">

**Additional context**

Example code, i needed boundary specific content type;

```kotlin
@PostMapping("/admin/activities", consumes = [MediaType.MULTIPART_FORM_DATA_VALUE])
    @RequestBody(content = [Content(encoding = [Encoding(name = "activityDto", contentType = "application/json")])])
    fun createActivity(@RequestPart(name = "activityDto") request: CreateActivityRequest, @RequestPart image: MultipartFile): ResponseEntity<*> {
    }
```

**Comment by sebastianfilke** [comment]
I have the exact same problem in my application. Could you also please update the 1.x.x springdoc versions for this bug?

**Comment by SubhamPanda2003** [comment]
Hey I see this issue is closed, but I am having issues when I try to get files and json both as the request body....Is there a way I can explicitly define the content type?
