### ISSUE TITLE
server:servlet:context-path Spring config not showing in API spec #2284

### ISSUE THREAD

**Issue by ramkumar-equinix** [springdoc/springdoc-openapi#2384]
context path specified in server.servlet.context-path is not showing in Swagger UI.

steps to reproduce:-
add the below config in application.yml and start the application

server:
   servlet:
     context-path: mybasecontext

testing:-
http://localhost:8080/mybasecontext/getusersapi
http://localhost:8080/mybasecontext/swagger-ui.html

in the above Screen shot the mybasecontext is missing
please help to fix this issue

![image](https://github.com/springdoc/springdoc-openapi/assets/7531306/9bbeb338-3b9e-40a6-8c00-b22b1937869e)

Expected is /**base**/test1 and /base/demo1 

 /base` is missing, 

however it shows above in api-docs and in generated server URL

**Comment by ramkumar-equinix** [comment]
recreating the issue https://github.com/springdoc/springdoc-openapi/issues/2284 to attach the  code to reproduce  https://github.com/psramkumar/spring-swagger-ui

**Comment by bnasslahsen** [comment]
@ramkumar-equinix,

Your expectation is wrong. 
The paths are correct under the base.
