### ISSUE TITLE
The copy button not working, can be upgrade swagger-ui version 5.3.1+

### ISSUE THREAD

**Issue by jsbxyyx** [springdoc/springdoc-openapi#2386]
**Describe the bug**

see [https://github.com/swagger-api/swagger-ui/issues/9094](https://github.com/swagger-api/swagger-ui/issues/9094)

**To Reproduce**

- What version of spring-boot you are using?
- What modules and versions of springdoc-openapi are you using?
- What is the actual and the expected result using OpenAPI Description (yml or json)?
- Provide with a sample code (HelloController) or Test that reproduces the problem

**Expected behavior**

- A clear and concise description of what you expected to happen.
- What is the expected result using OpenAPI Description (yml or json)?

**Screenshots**

**Additional context**

**Comment by bnasslahsen** [comment]
Fixed by #2382
