### ISSUE TITLE
Support Unicode Categories

### ISSUE THREAD

**Issue by anar-orujov** [springdoc/springdoc-openapi#2389]
**Is your feature request related to a problem? Please describe.**

I can't use Unicode categories (such as `p{L}`, `p{Nd}`, etc) in the validation pattern. These Unicode categories allow validation of input strings according to groups of characters. For example, `p{L}` allows all letters.
Currently, I use Unicode categories for bean validation, and it would be consistent and more convenient to have the same validation patterns in the OpenAPI definition. Otherwise, I have to maintain different validation patterns in my beans and OpenAPI documentation. That is not always consistent and is also more error-prone.

**Describe the solution you'd like**

I propose to enable Unicode categories in **openapi.yaml** as the following:
`pattern: ^[\p{L}\p{Zs}\p{Nd}\p{Pd}]{3,32}$/u`

**Comment by bnasslahsen** [comment]
@anar-orujov,

There are no current plans to support Unicode Categories.
If you feel it useful for the community, please feel free to propose directly a PR.
