### ISSUE TITLE
All css/js are not loading in springdoc

### ISSUE THREAD

**Issue by baljeets01** [springdoc/springdoc-openapi#2392]
**Describe the bug**

I'm working on an upgrade task in a project where I'm upgrading the swagger from springfox(3.0.0) to springdoc(1.7.0).
The project uses microservices architecture where maximum microservices uses springboot (2.7.7) and a few are still on spring MVC(5.3.25)
I'm able to see the json from all the microservices.
There is a separate microservice that collects all the API definition and show it on swagger-ui page, but the swagger-ui page is shown as blank.
It is unable to load index.css and swagger-initializer.js.
I have tried all the possible solutions given but none of them worked.

![image](https://github.com/springdoc/springdoc-openapi/assets/100705230/947f2b6c-64bc-4bff-ae7d-ce23f74ccd4a)

Any help in this is highly appreciated.

**Comment by uc4w6c** [comment]
Please provide a [Minimal, Reproducible Example - with HelloController](https://stackoverflow.com/help/minimal-reproducible-example) that reproduces the issue.

This ticket will be closed and can be reopened if the relevant information are provided.
