### ISSUE TITLE
spring boot 3, /swagger-ui/index.html got 404, v3/api-docs is working

### ISSUE THREAD

**Issue by chengtangzheng2021** [springdoc/springdoc-openapi#2395]
**Describe the bug**

- If you are reporting a bug, please help to speed up problem diagnosis by providing as
  much information as possible:
- A clear and concise description of what the bug is: the title of an issue is not enough

**To Reproduce**

- What version of spring-boot you are using?
- What modules and versions of springdoc-openapi are you using?
- What is the actual and the expected result using OpenAPI Description (yml or json)?
- Provide with a sample code (HelloController) or Test that reproduces the problem

**Expected behavior**

- A clear and concise description of what you expected to happen.
- What is the expected result using OpenAPI Description (yml or json)?

**Screenshots**

**Additional context**

**Comment by chengtangzheng2021** [comment]
One of our spring boot app with boot 3.1.3, with java17 with springdoc-openapi-starter-webmvc-ui 2.2.0 tested with and without swagger config, the result is: swagger url of https://our-host.com/swagger-ui/index.html is not working, got 404. swagger url of https://our-host.com/v3/api-docs is working. swagger url of https://our-host.com/v3/api-docs/swagger-config is also working

**Comment by chengtangzheng2021** [comment]
how can 
the /v3/api-docs is working
the /v3/api-docs/swagger-config is working,
the swagger-ui/index.html is not working ?

**Comment by uc4w6c** [comment]
Please provide a [Minimal, Reproducible Example - with HelloController](https://stackoverflow.com/help/minimal-reproducible-example) that reproduces the issue.

This ticket will be closed and can be reopened if the relevant information are provided.

**Comment by chengtangzheng2021** [comment]
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<groupId>dell.koa</groupId>
	<artifactId>price-stage</artifactId>
	<version>0.4.0</version>
	<packaging>jar</packaging>

	<name>price-stage</name>
	<description>Price Stage microservice</description>

	<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>3.1.3</version>
		<relativePath /> 
	</parent>

	<properties>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
		<sonar.junit.reportPaths>target/surefire-reports</sonar.junit.reportPaths>
		<sonar.coverage.exclusions>sonar.coverage.exclusions=**/*CompensatorMinPrice*,**/*Test*,**/*AppRunner*,**/*Exception*,**/*Config*,**/*MongoEndpoint*,**/Swagger.java,**/Async.java,**/RedisEndpoint.java,**/HomeController.java</sonar.coverage.exclusions>
		<java.version>17</java.version>
		<jacoco.version>0.8.10</jacoco.version>
		<springdoc.openapi.version>2.2.0</springdoc.openapi.version>
		<snakeyaml.version>2.0</snakeyaml.version>
	</properties>

	<dependencies>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-web</artifactId>
		</dependency>

		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-data-mongodb</artifactId>
			<optional>true</optional>
		</dependency>

		
		<dependency>
			<groupId>org.openjdk.nashorn</groupId>
			<artifactId>nashorn-core</artifactId>
			<version>15.4</version>
		</dependency>

		
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-actuator</artifactId>
		</dependency>

		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-test</artifactId>
			<scope>test</scope>
		</dependency>

		<dependency>
			<groupId>junit</groupId>
			<artifactId>junit</artifactId>
			<scope>test</scope>
		</dependency>

		<dependency>
			<groupId>org.testng</groupId>
			<artifactId>testng</artifactId>
			<version>7.7.0</version>
			<scope>test</scope>
		</dependency>

		<dependency>
			<groupId>org.junit.vintage</groupId>
			<artifactId>junit-vintage-engine</artifactId>
			<scope>test</scope>
			<exclusions>
				<exclusion>
					<groupId>org.hamcrest</groupId>
					<artifactId>hamcrest-core</artifactId>
				</exclusion>
			</exclusions>
		</dependency>

		
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-data-redis</artifactId>
		</dependency>

		<dependency>
			<groupId>redis.clients</groupId>
			<artifactId>jedis</artifactId>
			<exclusions>
				<exclusion>
					<groupId>org.json</groupId>
					<artifactId>json</artifactId>
				</exclusion>
			</exclusions>
		</dependency>

		<dependency>
			<groupId>org.springdoc</groupId>
			<artifactId>springdoc-openapi-starter-webmvc-ui</artifactId>
			<version>${springdoc.openapi.version}</version>
		</dependency>

		<dependency>
			<groupId>jakarta.validation</groupId>
			<artifactId>jakarta.validation-api</artifactId>
		</dependency>

		
		<dependency>
			<groupId>com.jayway.jsonpath</groupId>
			<artifactId>json-path</artifactId>
		</dependency>

		
		<dependency>
			<groupId>de.flapdoodle.embed</groupId>
			<artifactId>de.flapdoodle.embed.mongo.spring30x</artifactId>
			<version>4.6.1</version>
		</dependency>

		
		<dependency>
			<groupId>io.micrometer</groupId>
			<artifactId>micrometer-core</artifactId>
		</dependency>

		<dependency>
			<groupId>io.micrometer</groupId>
			<artifactId>micrometer-registry-prometheus</artifactId>
		</dependency>

		<dependency>
			<groupId>org.springframework.security</groupId>
			<artifactId>spring-security-core</artifactId>
		</dependency>

		
		<dependency>
			<groupId>com.emc.ecs</groupId>
			<artifactId>object-client</artifactId>
			<version>3.4.5</version>
		</dependency>

		<dependency>
			<groupId>org.codehaus.jettison</groupId>
			<artifactId>jettison</artifactId>
			<version>1.5.4</version>
		</dependency>

		<dependency>
			<groupId>com.sun.xml.bind</groupId>
			<artifactId>jaxb-impl</artifactId>
			<version>2.2.5</version>
		</dependency>


		<dependency>
			<groupId>org.apache.httpcomponents</groupId>
			<artifactId>httpclient</artifactId>
			<version>4.5.14</version>
		</dependency>

		<dependency>
			<groupId>org.apache.httpcomponents</groupId>
			<artifactId>httpcore</artifactId>
			<version>4.4.16</version>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-aop</artifactId>
		</dependency>

		
		<dependency>
			<groupId>org.springframework.hateoas</groupId>
			<artifactId>spring-hateoas</artifactId>

		</dependency>

		<dependency>
			<groupId>javax</groupId>
			<artifactId>javaee-api</artifactId>
			<version>8.0.1</version>
		</dependency>

	</dependencies>

	<build>
		<plugins>
			<plugin>
				<groupId>org.jacoco</groupId>
				<artifactId>jacoco-maven-plugin</artifactId>
				<version>${jacoco.version}</version>
				<executions>
					<execution>
						<id>prepare-agent</id>
						<goals>
							<goal>prepare-agent</goal>
						</goals>
					</execution>
					<execution>
						<id>report</id>
						<phase>prepare-package</phase>
						<goals>
							<goal>report</goal>
						</goals>
					</execution>
					<execution>
						<id>post-unit-test</id>
						<phase>test</phase>
						<goals>
							<goal>report</goal>
						</goals>
						<configuration>
							
							<dataFile>target/jacoco.exec</dataFile>
							
							<outputDirectory>target/jacoco-ut</outputDirectory>
						</configuration>
					</execution>
				</executions>
				<configuration>
					<systemPropertyVariables>
						<jacoco-agent.destfile>target/jacoco.exec</jacoco-agent.destfile>
					</systemPropertyVariables>
				</configuration>
			</plugin>
			<plugin>
				<groupId>org.sonarsource.scanner.maven</groupId>
				<artifactId>sonar-maven-plugin</artifactId>
				<version>3.9.0.2155</version>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-surefire-plugin</artifactId>
			</plugin>
			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
				<configuration>
					<mainClass>dell.koa.pricestage.PriceStageApplication</mainClass>
				</configuration>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-help-plugin</artifactId>
				<version>3.1.0</version>
			</plugin>
		</plugins>

		<pluginManagement>
			<plugins>
				
				<plugin>
					<groupId>org.eclipse.m2e</groupId>
					<artifactId>lifecycle-mapping</artifactId>
					<version>1.0.0</version>
					<configuration>
						<lifecycleMappingMetadata>
							<pluginExecutions>
								<pluginExecution>
									<pluginExecutionFilter>
										<groupId>
											org.apache.maven.plugins
										</groupId>
										<artifactId>
											maven-compiler-plugin
										</artifactId>
										<versionRange>
											[3.8.1,)
										</versionRange>
										<goals>
											<goal>testCompile</goal>
										</goals>
									</pluginExecutionFilter>
									<action>
										<ignore></ignore>
									</action>
								</pluginExecution>
							</pluginExecutions>
						</lifecycleMappingMetadata>
					</configuration>
				</plugin>

				<plugin>
					<groupId>org.jacoco</groupId>
					<artifactId>jacoco-maven-plugin</artifactId>
					<configuration>
						<append>true</append>
						<excludes>
							<exclude>**/*CompensatorMinPrice*</exclude>
						</excludes>
					</configuration>
					<executions>
						<execution>
							<id>agent-for-ut</id>
							<goals>
								<goal>prepare-agent</goal>
							</goals>
						</execution>
						<execution>
							<id>agent-for-it</id>
							<goals>
								<goal>prepare-agent-integration</goal>
							</goals>
						</execution>
						<execution>
							<id>jacoco-site</id>
							<phase>verify</phase>
							<goals>
								<goal>report</goal>
							</goals>
						</execution>
					</executions>
				</plugin>

			</plugins>
		</pluginManagement>
	</build>

	<reporting>
		<plugins>
			<plugin>
				<groupId>org.jacoco</groupId>
				<artifactId>jacoco-maven-plugin</artifactId>
				<reportSets>
					<reportSet>
						<reports>
							
							<report>report</report>
						</reports>
					</reportSet>
				</reportSets>
			</plugin>
		</plugins>
	</reporting>

	<repositories>
		<repository>
			<id>spring-snapshots</id>
			<name>Spring Snapshots</name>
			<url>https://repo.spring.io/snapshot</url>
			<snapshots>
				<enabled>true</enabled>
			</snapshots>
		</repository>
		<repository>
			<id>spring-milestones</id>
			<name>Spring Milestones</name>
			<url>https://repo.spring.io/milestone</url>
			<snapshots>
				<enabled>false</enabled>
			</snapshots>
		</repository>
	</repositories>

	<pluginRepositories>
		<pluginRepository>
			<id>spring-snapshots</id>
			<name>Spring Snapshots</name>
			<url>https://repo.spring.io/snapshot</url>
			<snapshots>
				<enabled>true</enabled>
			</snapshots>
		</pluginRepository>
		<pluginRepository>
			<id>spring-milestones</id>
			<name>Spring Milestones</name>
			<url>https://repo.spring.io/milestone</url>
			<snapshots>
				<enabled>false</enabled>
			</snapshots>
		</pluginRepository>
	</pluginRepositories>

	<distributionManagement>
		<repository>
			<id>artifactory_central</id>
			<name>ipv4-1001164-maven-prd-local</name>
			<url>https://artifacts.dell.com:443/artifactory/ipv4-1001164-maven-prd-local/</url>
		</repository>
		<snapshotRepository>
			<id>artifactory_snapshots</id>
			<name>ipv4-1001164-maven-dev-local</name>
			<url>https://artifacts.dell.com:443/artifactory/ipv4-1001164-maven-dev-local/</url>
		</snapshotRepository>
	</distributionManagement>
</project>

**Comment by chengtangzheng2021** [comment]
Thanks [uc4w6c](https://github.com/uc4w6c)
the apps pom got posted.
tested this issue, it is not caused by controller and swagger config files.
it is caused by app's code, with deleting app code to some degree, the swagger ui is working.

**Comment by chengtangzheng2021** [comment]
Hi [uc4w6c](https://github.com/uc4w6c)
how to debug this app's code from spring boot service that is using this app?

**Comment by uc4w6c** [comment]
You can debug by putting a breakpoint in SwaggerUiHome.java.
https://github.com/springdoc/springdoc-openapi/blob/main/springdoc-openapi-starter-webmvc-ui/src/main/java/org/springdoc/webmvc/ui/SwaggerUiHome.java

Or please take a look as there are many other issues that deal with similar issues.

**Comment by chengtangzheng2021** [comment]
Hi [uc4w6c](https://github.com/uc4w6c)
thanks for your response, I did debuging there.

**Comment by chengtangzheng2021** [comment]
@Operation(hidden = true)
	@GetMapping(SWAGGER_UI_PATH)
	@Override
	public ResponseEntity<Void> redirectToUi(HttpServletRequest request) {
		return super.redirectToUi(request);
	}

**Comment by chengtangzheng2021** [comment]
http://[localhost:8080/swagger-ui/index.html](http://localhost:8080/swagger-ui/index.html)
doesn't hit:
	@GetMapping(DEFAULT_PATH_SEPARATOR)
	@Operation(hidden = true)
	public String index() {
		StringBuilder uiRootPath = new StringBuilder();
		if (SpringDocUtils.isValidPath(mvcServletPath))
			uiRootPath.append(mvcServletPath);

		return REDIRECT_URL_PREFIX + uiRootPath + swaggerUiPath;
	}

**Comment by chengtangzheng2021** [comment]
this class caused the issue, with it get deleted, swagger is working

package dell.koa.pricestage.config;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.module.SimpleModule;
import dell.koa.pricestage.model.PriceMetadataInfo;
import dell.koa.pricestage.model.PriceResult;
import dell.koa.pricestage.model.propertyviews.LeanMetadataMixIn;
import dell.koa.pricestage.model.propertyviews.LeanPriceResultMixIn;
import dell.koa.pricestage.model.propertyviews.response.ConstrainedMappingJackson2HttpMessageConverter;
import dell.koa.pricestage.model.propertyviews.response.Wrapper;
import dell.koa.pricestage.util.CurrencyCodeEnumConverter;

import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.format.support.FormattingConversionService;
import org.springframework.http.converter.HttpMessageConverter;
import org.springframework.http.converter.json.Jackson2ObjectMapperBuilder;
import org.springframework.web.servlet.config.annotation.WebMvcConfigurationSupport;

import java.util.List;

@Configuration
public class PropertyViewsConfig extends WebMvcConfigurationSupport {
    @Bean
    public HttpMessageConverter<?> constrainedJackson2HttpMessageConverter() {
        ConstrainedMappingJackson2HttpMessageConverter jsonConverter = new ConstrainedMappingJackson2HttpMessageConverter(Wrapper.class);
        ObjectMapper objectMapper = Jackson2ObjectMapperBuilder.json().build();
        SimpleModule module = new SimpleModule();

        module.addSerializer(Wrapper.class, new IndicatorSerializer());
        module.setMixInAnnotation(PriceResult.class, LeanPriceResultMixIn.class);
        module.setMixInAnnotation(PriceMetadataInfo.class, LeanMetadataMixIn.class);

        objectMapper.registerModule(module);
        jsonConverter.setObjectMapper(objectMapper);
        return jsonConverter;
    }

    @Override
    public void configureMessageConverters(List<HttpMessageConverter<?>> converters) {
        converters.add(constrainedJackson2HttpMessageConverter());
        super.addDefaultHttpMessageConverters(converters);
    }

    @Override
    public FormattingConversionService mvcConversionService() {
        FormattingConversionService conversionService = super.mvcConversionService();
        
        if (conversionService != null) {
            conversionService.addConverter(new CurrencyCodeEnumConverter());
        }

        return conversionService;
    }
}

**Comment by chengtangzheng2021** [comment]
a class in the class causing this issue:
package dell.koa.pricestage.model.propertyviews.response;

import org.springframework.http.MediaType;
import org.springframework.http.converter.json.MappingJackson2HttpMessageConverter;
import org.springframework.util.Assert;

import java.lang.reflect.Type;

public class ConstrainedMappingJackson2HttpMessageConverter extends MappingJackson2HttpMessageConverter {

    private final Class<?> type;

    public ConstrainedMappingJackson2HttpMessageConverter(Class<?> type) {
        Assert.notNull(type, "Type must not be null!");
        this.type = type;
    }

    @Override
    public boolean canRead(Class<?> clazz, MediaType mediaType) {
        return type.isAssignableFrom(clazz) && super.canRead(clazz, mediaType);
    }

    @Override
    public boolean canRead(Type type, Class<?> contextClass, MediaType mediaType) {
        return this.type.isAssignableFrom(getJavaType(type, contextClass).getRawClass())
                && super.canRead(type, contextClass, mediaType);
    }

    @Override
    public boolean canWrite(Class<?> clazz, MediaType mediaType) {
        return type.isAssignableFrom(clazz) && super.canWrite(clazz, mediaType);
    }
}

**Comment by chengtangzheng2021** [comment]
@Configuration














@Configuration
public class PropertyViewsConfig extends WebMvcConfigurationSupport {
}
when this class is there, the issue is there, when this class changed to be below, the issue is gone.

@Configuration
public class PropertyViewsConfig  extends DelegatingWebMvcConfiguration {
}

**Comment by lehaiquantb** [comment]
I face the same issue with
`springdoc-openapi-starter-webmvc-api 2.1.0`
`spring-boot 3.2.3`
`java 17`
