### ISSUE TITLE
Servers uses https scheme for localhost instead of http

### ISSUE THREAD

**Issue by CaptainDaVinci** [springdoc/springdoc-openapi#2397]
**Describe the bug**

- The servers list in swagger-ui uses https scheme for localhost instead of http

**To Reproduce**

- Spring boot version: 3.1.0
- org.springdoc:springdoc-openapi-starter-webmvc-ui:2.2.0

**Expected behavior**

- Use http scheme since the swagger ui is accessed using `http://localhost/swagger-ui` path

**Screenshots**
![Screenshot 2023-10-11 at 12 23 19 PM](https://github.com/springdoc/springdoc-openapi/assets/21019116/3e8d776e-2b8e-4e28-969a-271675fc4652)

**Additional context**

Explicitly setting the servers config to "/" fixes the issue, i.e, we can make API calls from the swagger ui which was earlier failing due to https scheme.
```kt
@SpringBootApplication
@OpenAPIDefinition(
    servers = [Server(url = "/")],
)
class Application
```

**Comment by marcospds** [comment]
Hi, I tried to make a sample, but the behavior you described didn't happen, could you provide a sample?

https://github.com/marcospds/springdoc-server-https-instead-http

**Comment by bnasslahsen** [comment]
@CaptainDaVinci,

Not reproducible.
Feel free to provide a [Minimal, Reproducible Example - with HelloController](https://stackoverflow.com/help/minimal-reproducible-example) that reproduces the problem

**Comment by hendisantika** [comment]
Is it already close?

I didn't get any resolution for this.

How to fix it?

Thanks

**Comment by hendisantika** [comment]
Nevermind. I solved it with adding server = /
