### ISSUE TITLE
The springboot3 Copy to clipboard is unavailable

### ISSUE THREAD

**Issue by 287056218** [springdoc/springdoc-openapi#2408]
The springboot3 Copy to clipboard is unavailable

**Comment by bnasslahsen** [comment]
Remember, contributions to this repository should follow its [contributing guidelines](https://github.com/springdoc/springdoc-openapi/blob/c9cff142f63f688b1b725d3baf573ac38c097481/CONTRIBUTING.adoc), [security policy](https://github.com/springdoc/springdoc-openapi/blob/c9cff142f63f688b1b725d3baf573ac38c097481/SECURITY.md), and [code of conduct](https://github.com/springdoc/springdoc-openapi/blob/c9cff142f63f688b1b725d3baf573ac38c097481/CODE_OF_CONDUCT.md).
