### ISSUE TITLE
Version 1.7 doesn't work with Java 8?

### ISSUE THREAD

**Issue by marcgise** [springdoc/springdoc-openapi#2409]
I was using version 1.6.15 of springdoc-openapi, and everything worked fine.
I tried to update to 1.7.0, and now nothing works.
I see in the MANIFEST.MF of the springdoc-openapi-ui dependency that the jar was generated for JDK 17, but I don't see in any documentation that this version needs Java 17.

1.7.0 version really needs Java 17 to work?

**Screenshots**
![image](https://github.com/springdoc/springdoc-openapi/assets/4680243/adfe303f-2424-41ce-b129-4b87f4d7b185)

**Comment by marcgise** [comment]
Also I tested in other project with Java 17, and Swagger web doesn't appears now. I only changed the version from springdoc-openapi-starter-webmvc-ui 2.0.8 to 2.2.0. Does exist any page indicating the changes from one version to other? And in case of need to migrade code, what I need to migrate...

**Comment by bnasslahsen** [comment]
springdoc 1.7.0 extends spring-boot 2.7.10, where the compilation level is set to 1.8
