### ISSUE TITLE
Show different endpoints depending on environment

### ISSUE THREAD

**Issue by Adriansun** [springdoc/springdoc-openapi#2413]
I would really like to see something like

Method1:
@Profile("companyA", "CompanyB")
Method2:
@Profile("companyA")
Method3:
@Profile("companyB")

over each method. Then in the application.properties I would write something like:

swagger-ui.profile=companyA
thus only the methods with companyA could show or

swagger-ui.profile=companyA , companyB
thus only the methods with companyA and companyB would show or

swagger-ui.profile= // or just nothing
thus all methods would show always

**Comment by bnasslahsen** [comment]
Remember, contributions to this repository should follow its [contributing guidelines](https://github.com/springdoc/springdoc-openapi/blob/296af61ecd2791599266083f2fe5461147adb376/CONTRIBUTING.adoc), [security policy](https://github.com/springdoc/springdoc-openapi/blob/296af61ecd2791599266083f2fe5461147adb376/SECURITY.md), and [code of conduct](https://github.com/springdoc/springdoc-openapi/blob/296af61ecd2791599266083f2fe5461147adb376/CODE_OF_CONDUCT.md).
