### ISSUE TITLE
SortedSchemaMixin31 doesn't use Schema31Mixin.TypeSerializer.class for types property

### ISSUE THREAD

**Issue by dmitry-izmerov** [springdoc/springdoc-openapi#2417]
SortedSchemaMixin31 doesn't use Schema31Mixin.TypeSerializer.class for types property in line https://github.com/springdoc/springdoc-openapi/blob/main/springdoc-openapi-starter-common/src/main/java/org/springdoc/core/mixins/SortedSchemaMixin31.java#L115 and therefore you cannot send requests in swagger-ui "Try out" section.

**Comment by bnasslahsen** [comment]
your description is not complete, and cannot be addressed.
