### ISSUE TITLE
support OIDC / extensible swagger-ui.html

### ISSUE THREAD

**Issue by natrem** [springdoc/springdoc-openapi#242]
I have specific use case where I want to support OIDC.
this is not currently supported by swagger ui but a js hack could make it work.

In order to provide such hackable feature you could use the process done by Swashbuckle library:
- server a [custom index.html](https://github.com/domaindrivendev/Swashbuckle.AspNetCore/blob/34dd8f9f5e66b55638af3c63d30302cacb7f424e/src/Swashbuckle.AspNetCore.SwaggerUI/index.html) file 
- have a list of available configurations
- dynamically replace the served file variables by the configuration 

This allows some tweaks in css/js and passing the configuration object from a serialized object.

This is something I will probably work on (on an internal project)
Would you be interested in such feature in springdoc-openapi-ui ? I could share my work but will probably not do it for both webmvc and webflux modules.

**Comment by springdoc** [comment]
Hi @natrem, 

 Thank you for your contribution. 
 As you know we rely on official swagger-ui webjars, and we do not add any changes to these webjars.
 You can post your PR to swagger-ui project who is more relevant for your proposal:
 - https://github.com/swagger-api/swagger-ui/pulls

 It seems there are already some related issues about OIDC support on the swagger-ui side:
 - https://github.com/swagger-api/swagger-ui/issues/5473

**Comment by natrem** [comment]
I don't think this kind of transformation can be embedded in default swagger ui but your position is understandable.
Thanks for taking the time.
