### ISSUE TITLE
APIs not getting generated defined in api-definition.yaml

### ISSUE THREAD

**Issue by sagarika4** [springdoc/springdoc-openapi#2420]
**Describe the bug**

APIs are not getting created that are generated via the OpenAPI YAML spec in the resources folder.
Below is the screenshot of swagger
<img width="1723" alt="Screenshot 2023-11-04 at 5 01 37 PM" src="https://github.com/springdoc/springdoc-openapi/assets/17711175/fac03fb6-765a-4634-9309-34d5a76eff16">
/v3/api-docs is taking to default OpenAPI yaml file:
`{"openapi":"3.0.1","info":{"title":"OpenAPI definition","version":"v0"},"servers":[{"url":"http://localhost:8080","description":"Generated server url"}],"paths":{},"components":{}}`

This is the directory structure. As you can see all classes are generated fine.
<img width="434" alt="Screenshot 2023-11-04 at 5 04 36 PM" src="https://github.com/springdoc/springdoc-openapi/assets/17711175/e906d784-328c-4a7e-991e-9723fbc2803b">

**api-definition.yaml:**
```
openapi: "3.0.1"
info:
  title: API Title
  version: "1.0"
servers:
  - url: http://localhost:8080/api
    description: Direct
paths:
  /test:
    get:
      responses:
        '200':
          description: OK
```

**pom.xml:**
plugin:
```
<plugin>
				<groupId>org.openapitools</groupId>
				<artifactId>openapi-generator-maven-plugin</artifactId>
				<version>7.0.1</version>
				<executions>
					<execution>
						<goals>
							<goal>generate</goal>
						</goals>
						<configuration>
							<inputSpec>
								${project.basedir}/src/main/resources/api-definition.yaml
							</inputSpec>
							<generatorName>spring</generatorName>
							<apiPackage>com.vidyatech.openapi.api</apiPackage>
							<modelPackage>com.vidyatech.openapi.model</modelPackage>
							<supportingFilesToGenerate>
								ApiUtil.java
							</supportingFilesToGenerate>
							<configOptions>
								<delegatePattern>true</delegatePattern>
							</configOptions>
						</configuration>
					</execution>
				</executions>
			</plugin>
```

**To Reproduce**
Steps to 
reproduce the behavior:

Following is the maven dependency tree:
 +- org.springframework.boot:spring-boot-starter-actuator:jar:2.7.17:compile
[INFO] |  +- org.springframework.boot:spring-boot-starter:jar:2.7.17:compile
[INFO] |  |  +- org.springframework.boot:spring-boot:jar:2.7.17:compile
[INFO] |  |  +- org.springframework.boot:spring-boot-autoconfigure:jar:2.7.17:compile
[INFO] |  |  +- org.springframework.boot:spring-boot-starter-logging:jar:2.7.17:compile
[INFO] |  |  |  +- ch.qos.logback:logback-classic:jar:1.2.12:compile
[INFO] |  |  |  |  \- ch.qos.logback:logback-core:jar:1.2.12:compile
[INFO] |  |  |  +- org.apache.logging.log4j:log4j-to-slf4j:jar:2.17.2:compile
[INFO] |  |  |  |  \- org.apache.logging.log4j:log4j-api:jar:2.17.2:compile
[INFO] |  |  |  \- org.slf4j:jul-to-slf4j:jar:1.7.36:compile
[INFO] |  |  +- jakarta.annotation:jakarta.annotation-api:jar:1.3.5:compile
[INFO] |  |  \- org.yaml:snakeyaml:jar:1.30:compile
[INFO] |  +- org.springframework.boot:spring-boot-actuator-autoconfigure:jar:2.7.17:compile
[INFO] |  |  +- org.springframework.boot:spring-boot-actuator:jar:2.7.17:compile
[INFO] |  |  \- com.fasterxml.jackson.datatype:jackson-datatype-jsr310:jar:2.13.5:compile
[INFO] |  \- io.micrometer:micrometer-core:jar:1.9.16:compile
[INFO] |     +- org.hdrhistogram:HdrHistogram:jar:2.1.12:compile
[INFO] |     \- org.latencyutils:LatencyUtils:jar:2.0.3:runtime
[INFO] +- org.springframework.boot:spring-boot-starter-data-jpa:jar:2.7.17:compile
[INFO] |  +- org.springframework.boot:spring-boot-starter-aop:jar:2.7.17:compile
[INFO] |  |  +- org.springframework:spring-aop:jar:5.3.30:compile
[INFO] |  |  \- org.aspectj:aspectjweaver:jar:1.9.7:compile
[INFO] |  +- org.springframework.boot:spring-boot-starter-jdbc:jar:2.7.17:compile
[INFO] |  |  +- com.zaxxer:HikariCP:jar:4.0.3:compile
[INFO] |  |  \- org.springframework:spring-jdbc:jar:5.3.30:compile
[INFO] |  +- jakarta.transaction:jakarta.transaction-api:jar:1.3.3:compile
[INFO] |  +- jakarta.persistence:jakarta.persistence-api:jar:2.2.3:compile
[INFO] |  +- org.hibernate:hibernate-core:jar:5.6.15.Final:compile
[INFO] |  |  +- org.jboss.logging:jboss-logging:jar:3.4.3.Final:compile
[INFO] |  |  +- net.bytebuddy:byte-buddy:jar:1.12.23:compile
[INFO] |  |  +- antlr:antlr:jar:2.7.7:compile
[INFO] |  |  +- org.jboss:jandex:jar:2.4.2.Final:compile
[INFO] |  |  +- org.hibernate.common:hibernate-commons-annotations:jar:5.1.2.Final:compile
[INFO] |  |  \- org.glassfish.jaxb:jaxb-runtime:jar:2.3.8:compile
[INFO] |  |     +- org.glassfish.jaxb:txw2:jar:2.3.8:compile
[INFO] |  |     +- com.sun.istack:istack-commons-runtime:jar:3.0.12:compile
[INFO] |  |     \- com.sun.activation:jakarta.activation:jar:1.2.2:runtime
[INFO] |  +- org.springframework.data:spring-data-jpa:jar:2.7.17:compile
[INFO] |  |  +- org.springframework.data:spring-data-commons:jar:2.7.17:compile
[INFO] |  |  +- org.springframework:spring-orm:jar:5.3.30:compile
[INFO] |  |  +- org.springframework:spring-context:jar:5.3.30:compile
[INFO] |  |  |  \- org.springframework:spring-expression:jar:5.3.30:compile
[INFO] |  |  +- org.springframework:spring-tx:jar:5.3.30:compile
[INFO] |  |  \- org.springframework:spring-beans:jar:5.3.30:compile
[INFO] |  \- org.springframework:spring-aspects:jar:5.3.30:compile
[INFO] +- org.springframework.boot:spring-boot-starter-data-rest:jar:2.7.17:compile
[INFO] |  +- org.springframework.boot:spring-boot-starter-web:jar:2.7.17:compile
[INFO] |  |  +- org.springframework.boot:spring-boot-starter-json:jar:2.7.17:compile
[INFO] |  |  |  +- com.fasterxml.jackson.datatype:jackson-datatype-jdk8:jar:2.13.5:compile
[INFO] |  |  |  \- com.fasterxml.jackson.module:jackson-module-parameter-names:jar:2.13.5:compile
[INFO] |  |  +- org.springframework.boot:spring-boot-starter-tomcat:jar:2.7.17:compile
[INFO] |  |  |  +- org.apache.tomcat.embed:tomcat-embed-core:jar:9.0.82:compile
[INFO] |  |  |  \- org.apache.tomcat.embed:tomcat-embed-websocket:jar:9.0.82:compile
[INFO] |  |  +- org.springframework:spring-web:jar:5.3.30:compile
[INFO] |  |  \- org.springframework:spring-webmvc:jar:5.3.30:compile
[INFO] |  \- org.springframework.data:spring-data-rest-webmvc:jar:3.7.17:compile
[INFO] |     +- org.springframework.data:spring-data-rest-core:jar:3.7.17:compile
[INFO] |     |  +- org.springframework.hateoas:spring-hateoas:jar:1.5.5:compile
[INFO] |     |  \- org.atteo:evo-inflector:jar:1.3:compile
[INFO] |     \- com.fasterxml.jackson.core:jackson-annotations:jar:2.13.5:compile
[INFO] +- com.h2database:h2:jar:2.1.214:runtime
[INFO] +- org.projectlombok:lombok:jar:1.18.28:compile
[INFO] +- org.springframework.boot:spring-boot-starter-test:jar:2.7.17:test
[INFO] |  +- org.springframework.boot:spring-boot-test:jar:2.7.17:test
[INFO] |  +- org.springframework.boot:spring-boot-test-autoconfigure:jar:2.7.17:test
[INFO] |  +- com.jayway.jsonpath:json-path:jar:2.7.0:compile
[INFO] |  |  \- net.minidev:json-smart:jar:2.4.11:compile
[INFO] |  |     \- net.minidev:accessors-smart:jar:2.4.11:compile
[INFO] |  |        \- org.ow2.asm:asm:jar:9.3:compile
[INFO] |  +- jakarta.xml.bind:jakarta.xml.bind-api:jar:2.3.3:compile
[INFO] |  |  \- jakarta.activation:jakarta.activation-api:jar:1.2.2:compile
[INFO] |  +- org.assertj:assertj-core:jar:3.22.0:test
[INFO] |  +- org.hamcrest:hamcrest:jar:2.2:test
[INFO] |  +- org.junit.jupiter:junit-jupiter:jar:5.8.2:test
[INFO] |  |  +- org.junit.jupiter:junit-jupiter-api:jar:5.8.2:test
[INFO] |  |  |  +- org.opentest4j:opentest4j:jar:1.2.0:test
[INFO] |  |  |  +- org.junit.platform:junit-platform-commons:jar:1.8.2:test
[INFO] |  |  |  \- org.apiguardian:apiguardian-api:jar:1.1.2:test
[INFO] |  |  +- org.junit.jupiter:junit-jupiter-params:jar:5.8.2:test
[INFO] |  |  \- org.junit.jupiter:junit-jupiter-engine:jar:5.8.2:test
[INFO] |  |     \- org.junit.platform:junit-platform-engine:jar:1.8.2:test
[INFO] |  +- org.mockito:mockito-core:jar:4.5.1:test
[INFO] |  |  +- net.bytebuddy:byte-buddy-agent:jar:1.12.23:test
[INFO] |  |  \- org.objenesis:objenesis:jar:3.2:test
[INFO] |  +- org.mockito:mockito-junit-jupiter:jar:4.5.1:test
[INFO] |  +- org.skyscreamer:jsonassert:jar:1.5.1:test
[INFO] |  |  \- com.vaadin.external.google:android-json:jar:0.0.20131108.vaadin1:test
[INFO] |  +- org.springframework:spring-core:jar:5.3.30:compile
[INFO] |  |  \- org.springframework:spring-jcl:jar:5.3.30:compile
[INFO] |  +- org.springframework:spring-test:jar:5.3.30:test
[INFO] |  \- org.xmlunit:xmlunit-core:jar:2.9.1:test
[INFO] +- org.openapitools:jackson-databind-nullable:jar:0.2.1:compile
[INFO] |  \- com.fasterxml.jackson.core:jackson-databind:jar:2.13.5:compile
[INFO] |     \- com.fasterxml.jackson.core:jackson-core:jar:2.13.5:compile
[INFO] +- org.springdoc:springdoc-openapi-ui:jar:1.7.0:compile
[INFO] |  +- org.springdoc:springdoc-openapi-webmvc-core:jar:1.7.0:compile
[INFO] |  |  \- org.springdoc:springdoc-openapi-common:jar:1.7.0:compile
[INFO] |  |     \- io.swagger.core.v3:swagger-core:jar:2.2.9:compile
[INFO] |  |        +- org.apache.commons:commons-lang3:jar:3.12.0:compile
[INFO] |  |        +- com.fasterxml.jackson.dataformat:jackson-dataformat-yaml:jar:2.13.5:compile
[INFO] |  |        \- io.swagger.core.v3:swagger-models:jar:2.2.9:compile
[INFO] |  \- org.webjars:swagger-ui:jar:4.18.2:compile
[INFO] +- javax.validation:validation-api:jar:2.0.1.Final:compile
[INFO] +- io.swagger:swagger-annotations:jar:1.6.6:compile
[INFO] +- javax.annotation:javax.annotation-api:jar:1.3.2:compile
[INFO] +- javax.servlet:servlet-api:jar:2.5:provided
[INFO] +- io.springfox:springfox-swagger2:jar:3.0.0:compile
[INFO] |  +- io.springfox:springfox-spi:jar:3.0.0:compile
[INFO] |  |  \- io.springfox:springfox-core:jar:3.0.0:compile
[INFO] |  +- io.springfox:springfox-schema:jar:3.0.0:compile
[INFO] |  +- io.springfox:springfox-swagger-common:jar:3.0.0:compile
[INFO] |  |  \- io.swagger.core.v3:swagger-annotations:jar:2.1.2:compile
[INFO] |  +- io.springfox:springfox-spring-web:jar:3.0.0:compile
[INFO] |  |  \- io.github.classgraph:classgraph:jar:4.8.83:compile
[INFO] |  +- io.springfox:springfox-spring-webmvc:jar:3.0.0:compile
[INFO] |  +- io.springfox:springfox-spring-webflux:jar:3.0.0:compile
[INFO] |  +- com.fasterxml:classmate:jar:1.5.1:compile
[INFO] |  +- org.slf4j:slf4j-api:jar:1.7.36:compile
[INFO] |  +- org.springframework.plugin:spring-plugin-core:jar:2.0.0.RELEASE:compile
[INFO] |  +- org.springframework.plugin:spring-plugin-metadata:jar:2.0.0.RELEASE:compile
[INFO] |  +- io.swagger:swagger-models:jar:1.5.20:compile
[INFO] |  \- org.mapstruct:mapstruct:jar:1.3.1.Final:runtime
[INFO] +- io.springfox:springfox-swagger-ui:jar:3.0.0:compile
[INFO] \- org.springframework.boot:spring-boot-starter-validation:jar:3.1.5:compile
[INFO]    +- org.apache.tomcat.embed:tomcat-embed-el:jar:9.0.82:compile
[INFO]    \- org.hibernate.validator:hibernate-validator:jar:6.2.5.Final:compile
[INFO]       \- jakarta.validation:jakarta.validation-api:jar:2.0.2:compile

**Expected behavior**
APIs defined in api-definition.yaml should get generated.

**Screenshots**

**Additional context**

**Comment by bnasslahsen** [comment]
not related to springdoc-openapi
