### ISSUE TITLE
Inability to Independently Annotate @Schema Descriptions for Multiple Instances of the Same Type

### ISSUE THREAD

**Issue by lihomev5** [springdoc/springdoc-openapi#2424]
**Describe the bug**

Currently, when using the @Schema annotation to describe fields in a class, and there are multiple instances of the same type within another class, it seems challenging to independently annotate each instance for accurate OpenAPI documentation.

**To Reproduce**

I'm using springdoc-openapi:1.7.0 with springboot 2.7.16.

Consider the following scenario:
```java
public class MyClass {
    @Schema(description = "Description for prev")
    private Abc prev;

    @Schema(description = "Description for next")
    private Abc next;
}
```

Despite annotating prev and next with different descriptions, the OpenAPI documentation seems to use $ref to reference a common `Abc` type, leading to the same description for both fields.
Like this (missing the "description" field):
```json
"prev": {
    "$ref": "#/components/schemas/Abc"
},
"next": {
    "$ref": "#/components/schemas/Abc"
},
```

**Expected behavior**
Ideally, it would be beneficial to have a mechanism that allows independent annotations for instances of the same type, ensuring that each field has its own distinct description in the generated OpenAPI documentation.

**Possible Solution**

Investigate if there is a way to introduce support for independent @Schema annotations for multiple instances of the same type, enabling more granular control over field descriptions in the generated OpenAPI documentation.

**Comment by GooDer** [comment]
Hi @lihomev5, we are facing same problem and solution should be already there. We just need to wait for release of new version.

Possibility of define different description for attributes of same type are part of OpenAPI spec 3.1 and final support was added in this commit: https://github.com/springdoc/springdoc-openapi/commit/d0021a2685f0652b39da026ac0b1dbfc82947399

You need to set OpenAPI specification version to 3.1 in your configuration after new release will be done and it should start to work as you expected :-)

**Comment by bnasslahsen** [comment]
@GooDer,

OpenAPI 3.1 is already supported.

You just need to set: 
```properties
springdoc.api-docs.version=openapi_3_1
```
