### ISSUE TITLE
Gibberish shown in example when jakarta.validation.constraints.Pattern annotation is used on a field and no defaultValue is provided

### ISSUE THREAD

**Issue by ZIRAKrezovic** [springdoc/springdoc-openapi#2425]
**Describe the bug**

When I annotate a field with @Schema, without providing a defaultValue, and the annotated field additionally has @jakarta.validation.constraints.Pattern annotation, the example shown in swagger-ui is literal gibberish

Example code:

```
import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.validation.constraints.Pattern;
import lombok.Data;

import java.io.Serial;
import java.io.Serializable;

@Data
@Schema(description = "Properties for creation of a user")
public class User implements Serializable {
    @Serial
    private static final long serialVersionUID = 1L;

    @Pattern(regexp = "^(?=.{4,256}$)(?:[a-zA-Z\\d]+(?:[.\\-_@][a-zA-Z\\d])*)+$", message = "{user.validation.username_invalid}")
    @Schema(description = "User name of a given user", requiredMode = Schema.RequiredMode.REQUIRED, defaultValue = "")
    private String username;

    @Pattern(regexp = "^[\\w-.]+@([\\w-]+\\.)+[\\w-]{2,4}$", message = "{user.validation.email_invalid}")
    @Schema(description = "E-mail of a given user", requiredMode = Schema.RequiredMode.REQUIRED, defaultValue = "")
    private String email;
}
```

Output in swagger-ui:

![image](https://github.com/springdoc/springdoc-openapi/assets/145535273/cb60232c-5f2a-47fc-b745-fa749eb94f83)

**To Reproduce**

- What version of spring-boot you are using? **3.2.0-RC2**
- What modules and versions of springdoc-openapi are you using? **2.2.0**

Example provided at: https://github.com/ZIRAKrezovic/openapi-report

Just issue: ./mvnw clean install spring-boot:run

And navigate to: http://localhost:8080/swagger-ui/index.html#/user-v1/get

**Expected behavior**

- A sensible default value. For objects not annotated with @Pattern object it just says "string"

**Comment by bnasslahsen** [comment]
You should report it to https://github.com/swagger-api/swagger-ui/issues instead.
