### ISSUE TITLE
Builder method in ExampleObjectBuilder misspelled as 'exampleOjectBuilder'

### ISSUE THREAD

**Issue by maryamkhan14** [springdoc/springdoc-openapi#2428]
This is not a bug per se, as there is no unexpected behavior that results. However, both in v1.7.0 and springdoc-openapi-starter-common, the ExampleObjectBuilder class's builder method is called "exampleOjectBuilder". Here is a [link](https://github.com/springdoc/springdoc-openapi/blob/c9cff142f63f688b1b725d3baf573ac38c097481/springdoc-openapi-starter-common/src/main/java/org/springdoc/core/fn/builders/exampleobject/Builder.java#L85) to the line in question.

**To Reproduce**
**- What version of spring-boot you are using?** This issue occurs for both Spring Boot 2 and 3.
**- What modules and versions of springdoc-openapi are you using?** This issue occurs in springdoc v1.7.0 as well as the springdoc-openapi-starter-common module.
**- What is the actual and the expected result using OpenAPI Description (yml or json)?** The actual and expected results match - there is no behavioral change.
**- Provide with a sample code (HelloController) or Test that reproduces the problem.** N/A

**Screenshots**
![image](https://github.com/springdoc/springdoc-openapi/assets/25802225/782f5837-dbf8-4ac3-9092-2489a72f18de)

**Additional context**
I'll be happy to resolve this issue with a PR if needed!

**Comment by bnasslahsen** [comment]
@maryamkhan14,

Feel free to propose a PR.
