### ISSUE TITLE
How do I create a link?

### ISSUE THREAD

**Issue by JavierYepez** [springdoc/springdoc-openapi#243]
I would like to know where I can find the documentation for all the annotations and how to use them.

If there isn't one for now, how I can create a link in an @ApiResponse?

I'm using Spring Boot 2.2.0 RELEASE and:
org.springdoc:springdoc-openapi-ui:1.2.17
org.springdoc:springdoc-openapi-webmvc-core:1.2.17
org.springdoc:springdoc-openapi-data-rest:1.2.17
org.springdoc:springdoc-openapi-security:1.2.17

Thank you in advance

**Comment by springdoc** [comment]
Hi, 

 Here is the link for springdoc-openapi documentation, which is built on top of swagger-annotations for OpenAPI 3:
 - http://springdoc.org/
 And this is the link for the swagger-annotations usage:
 - https://github.com/swagger-api/swagger-core/wiki/Swagger-2.X---Annotations#apiresponse
