### ISSUE TITLE
Does not handle @DateTimeFormat

### ISSUE THREAD

**Issue by toddlindner** [springdoc/springdoc-openapi#244]
This controller will run fine when the app is hit directly:
http://localhost:8080/test/date/echo/20191209

But when running through the swagger UI, it is not allowed to enter 20191209.  "Value must be a DateTime"  There is no way to run this method through swagger.

import org.springframework.format.annotation.DateTimeFormat;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RestController;

import java.util.Date;

@RestController
public class RestTestController {

	@GetMapping("/test/date/echo/{date}")
	public String testDateEcho(@DateTimeFormat(pattern = "yyyyMMdd") @PathVariable Date date) {
		return date.toString();
	}
}

**Comment by springdoc** [comment]
Hi, 

 By Default java.util.Date is mapped by swagger official jars to date-time, but in your case you just pass the date without the time. You can use LocalDate instead if you want it to be handled automatically.

 If you need to keep the type java.util.Date , you will need to add the relevant swagger annotation for the documentation of your date.

```
@GetMapping("/test/date/echo/{date}")
public String testDateEcho(@DateTimeFormat(pattern = "yyyyMMdd") @Parameter(schema = @Schema(type="string" ,format = "date", example = "20200217")) @PathVariable Date date) {
	return date.toString();
}
```

**Comment by EagleInNight** [comment]
Hi,

I have another problem related to discussed. I have some method in controller to retrive data for some date, that passed as query param.

`@Operation(
            summary = "Get some data on date",
            parameters = {
                    @Parameter(
                            in = ParameterIn.QUERY,
                            name = "date",
                            description = "date of data",
                            example = "14.05.2020",
                            schema = @Schema(
                                    required = true,
                                    type = "string",
                                    format = "date"
                            )
                    )
            }
    )
    @GetMapping("/dataOnDate")
    public DataDto getDataOnDate(
            @RequestParam("date")
            @DateTimeFormat(pattern = "dd.MM.yyyy")
                    LocalDate localDate) {
        ...
    }`

In swagger-ui I can enter any value for param.. Is it correct? I expected that it will give me validation error without making a call.

And I have a question: I thought that if I define pattern for param ("dd.MM.yyyy") - it will be displayed somewhere, but it is shown only in error message if I try pass any value.. (ex. 14.05.2020)

**Comment by bnasslahsen** [comment]
@EagleInNight, 

 As mentionned, `@DateTimeFormat` annotation is not supported.
 You can enable addtionnal validations on the swagger-ui, by defining your own extensions.

 Here is a sample code for defining custom validations:
 - https://github.com/teq-niq/sample/blob/extension-variation4/src/main/java/sample/CustomConverter.java

 If you feel its useful for the community, please feel free to propose a PR.

**Comment by liyingben** [comment]
There are the same problems
