### ISSUE TITLE
Invalid value type for attribute if starting with camunda

### ISSUE THREAD

**Issue by Jonbeckas** [springdoc/springdoc-openapi#2445]
**Describe the bug**

Spring boot does not start if used together with `io.camunda.spring:spring-boot-starter-camunda:8.3.1`

The following error is thrown:
```
Error processing condition on io.camunda.zeebe.spring.client.CamundaAutoConfiguration.zeebeLifecycleEventProducer

Caused by: java.lang.IllegalArgumentException: Invalid value type for attribute 'factoryBeanObjectType': java.lang.String

```

**Comment by bnasslahsen** [comment]
@Jonbeckas,

We do not maintain this starter.

**Comment by Jonbeckas** [comment]
But until i add `org.springdoc:springdoc-openapi-starter-webmvc-api` my projects starts. I thought it may be an issue like https://github.com/springdoc/springdoc-openapi/issues/1789.
