### ISSUE TITLE
@OAuthScoppe annotation not working with environment variable

### ISSUE THREAD

**Issue by fdlessard** [springdoc/springdoc-openapi#2458]
I have the following annotation to configure the security scheme:

 

```

@SecurityScheme(
    name = "Oauth2Security",
    type = SecuritySchemeType.OAUTH2,
    in = SecuritySchemeIn.HEADER,
    flows =  @OAuthFlows(
        implicit = @OAuthFlow(
            authorizationUrl = "${springdoc.authorizationUrl}",
            scopes =  {
                @OAuthScope(name = "${springdoc.apiScope}", description = "api"),
            }
        )
    )
)

```

 

with the following property file application.yaml

 
```

springdoc:
  authorizationUrl: https://toto.com/
  apiScope: totoScope

```

 

The ${springdoc.authorizationUrl} in the annotation is replaced with https://toto.com/ but not  ${springdoc.apiScope}. It's value is not replaced with "totoScope"... it is set to "${springdoc.apiScope}" in the open api

**Comment by bnasslahsen** [comment]
There is no such property: `springdoc.apiScope`
