### ISSUE TITLE
Custom examples for custom primitive types

### ISSUE THREAD

**Issue by testersen** [springdoc/springdoc-openapi#2460]
Hello, awesome project!

My feature request is to add the possibility to add "example values" in the generated openapi spec for custom `PrimitiveType`s.

In our domain models we have some types that are added as custom primitive types:

```kt
class MyModel {
  // ...
}

val customClasses = PrimitiveType.customClasses()

customClasses[MyModel::class.java.name] = PrimitiveType.STRING
```

As expected, this does indeed generate an openapi spec that accepts a type `STRING`. However, there's no default example value in the generated spec. Which is something we would like to add per custom type.

For example;

```kt
val customClasses = PrimitiveType.customClasses()
val customExamples = PrimitiveType.customExamples()

customClasses[MyModel::class.java.name] = PrimitiveType.STRING
customExamples[MyModel::class.java.name] = listOf("NOK 123", "SEK 200")
```

Now, when the model is used, it will also provide a default example value in the openapi spec.

**Comment by bnasslahsen** [comment]
use [swagger-examples](https://swagger.io/docs/specification/adding-examples/)
