### ISSUE TITLE
swagger-ui custom default documentation interface

### ISSUE THREAD

**Issue by BacemKannou** [springdoc/springdoc-openapi#2462]
**Is your feature request related to a problem? Please describe.**

- I am able to configure the swagger-ui using spring boot properties. as per swagger-ui documentation but i can't figure out how to make it like this 
![image](https://github.com/springdoc/springdoc-openapi/assets/59615991/1a3eb6b3-3406-4918-9f6c-36af1dee1be4)

- Is there a way or a guide to customize the swagger interface and make it like the screenshot a bevove

**Describe the solution you'd like**
-  Please provide the steps/guidelines 

thanks for your help

**Comment by bnasslahsen** [comment]
This is a [swagger-ui](https://github.com/swagger-api/swagger-ui) topic. Not springdoc-openapi.
