### ISSUE TITLE
OpneApi compatibility with swagger 2

### ISSUE THREAD

**Issue by Shivani-96** [springdoc/springdoc-openapi#2464]
Initially my project was using spring fox. To generate api description @ApiOperation was used. Now we are migrating to springdoc-openapi-ui. To generate api description @Operation is used. But since its a large project containing large number of apis, is there any way to use the old annotation?

**Comment by anishsharma** [comment]
@Shivani-96 There is no way around. The changes are inevitable. [Migration steps](https://springdoc.org/#migrating-from-springfox)
