### ISSUE TITLE
@ParameterObject don't exclude Objects subfields if field is annotated with @Hidden 

### ISSUE THREAD

**Issue by singh-sardar** [springdoc/springdoc-openapi#2465]
If a class annotated with `@ParameterObject `has  Complex objects (example "Locale" ) and we annotate the Locale field with `@Hidden`, it doesn't hide sub fields of the class. I can still see 
![Screenshot 2023-12-20 alle 11 40 40](https://github.com/springdoc/springdoc-openapi/assets/34491094/30d9ee8d-6c0a-411e-a7e6-30fd7055fded)

Even if the field is hidden 
![Screenshot 2023-12-20 alle 11 41 38](https://github.com/springdoc/springdoc-openapi/assets/34491094/99deaecb-96ee-4f9c-b971-ff6c59de9b94)

`MethodParameterPojoExtractor` should not expand fields of sub projects / it should elaborate and consider annotations (jackson also ? )

**Comment by bnasslahsen** [comment]
@singh-sardar,

Not reproducible.
Feel free to provide a [Minimal, Reproducible Example - with HelloController](https://stackoverflow.com/help/minimal-reproducible-example) that reproduces the problem
