### ISSUE TITLE
Add field level description for post mapping

### ISSUE THREAD

**Issue by Shivani-96** [springdoc/springdoc-openapi#2466]
I want to add field level description in request body for post apis. I am not able to use @Schema at field level. On researching I found out that @Schema can only be used at method level in controller class. Is there any way that can be used?

I want somethin like this - 
`AccountV2ListParam {
param1(Array[something]): description ,
param2(boolean, optional): description
}
something{
p1(string):description,
p2(string):description ,
p3(string, optional): description
}`

But I get this - 
`{
  "param1": [
    {
      "p1": "string",
      "p2": "string",
      "p3": "string"
    }
  ],
  "param2": true
}`

**Comment by bnasslahsen** [comment]
If you are reporting a bug, please help to speed up problem diagnosis by providing as much information as possible:

You need to describe your context (the title of an issue is not enough)

What version of spring-boot you are using?

What modules and versions of springdoc-openapi are you using?

What are the actual and the expected result using OpenAPI Description (yml or json)?

Provide a [Minimal, Reproducible Example - with HelloController](https://stackoverflow.com/help/minimal-reproducible-example) that reproduces the problem
