### ISSUE TITLE
Issue in compatibilty with Spring Boot 3.2.0

### ISSUE THREAD

**Issue by anishsharma** [springdoc/springdoc-openapi#2467]
According to the [OpenAPI documentation ](https://github.com/springdoc/springdoc-openapi/blob/main/CHANGELOG.md)  `springdoc-openapi-starter-webmvc-ui 2.3.0` is said to be compatible with **Spring boot 3.2.0** but I am getting below error while running it in **Tomcat 10.1.5** and **Amazon Corretto 17**

**Screenshots**
![image](https://github.com/springdoc/springdoc-openapi/assets/5786559/abdd2e18-381e-4fcd-a23d-5c220867ceba)
![image](https://github.com/springdoc/springdoc-openapi/assets/5786559/83829b6c-feb4-49f3-898d-cf4ce5fade50)

I assume it has to be the springdoc as class in question is `org.springdoc.core.configuration.SpringDocGroovyConfiguration`

**Comment by bgalek** [comment]
I have the same problem, seems like it's not working with Spring boot 3.2

**Comment by anishsharma** [comment]
Do we have any update on this ?

**Comment by anishsharma** [comment]
Hi Team,

This is impacting our upgrade to Spring boot 3.2.0 which is necessary to resolve Veracode issues with older spring-web lib.

**Comment by bnasslahsen** [comment]
@bgalek, 

Not reproducible.
Feel free to provide a [Minimal, Reproducible Example - with HelloController](https://stackoverflow.com/help/minimal-reproducible-example) that reproduces the problem
