### ISSUE TITLE
Any way of adding Alternate Type rules in Open API Spring Doc

### ISSUE THREAD

**Issue by chakilamt** [springdoc/springdoc-openapi#2468]
I have migrated from Springfox to Open API and my old Springfox config has some alternate type rules like the below:

  
```
new AlternateTypeRule(typeResolver.resolve(ResponseEntity.class,
                                typeResolver.resolve(ResponseVO.class, WildcardType.class)),
                                typeResolver.resolve(WildcardType.class)))
```

Similar way, I needed for Open API Config but was not able to find any, and even when I used the code below, it also its not work.

```
SpringDocUtils.getConfig().replaceWithClass(typeResolver.resolve(ResponseEntity.class,
                        typeResolver.resolve(ResponseVO.class, WildcardType.class)).getClass(),
                typeResolver.resolve(WildcardType.class).getClass());
```

Please help!!

**Comment by bnasslahsen** [comment]
@chakilamt,

Your description is not clear.
If you are reporting a bug, please help to speed up problem diagnosis by providing as much information as possible:

You need to describe your context (the title of an issue is not enough)

What version of spring-boot you are using?

What modules and versions of springdoc-openapi are you using?

What are the actual and the expected result using OpenAPI Description (yml or json)?

Provide a [Minimal, Reproducible Example - with HelloController](https://stackoverflow.com/help/minimal-reproducible-example) that reproduces the problem
