### ISSUE TITLE
Schema creation error in inner-class duplication

### ISSUE THREAD

**Issue by wleo04** [springdoc/springdoc-openapi#2473]
- When creating response dto with inner class, schema is not created properly if it is duplicated. In this case, you must write your name directly into @Schema annotation.

- I hope the schema is created using the "outer class.inner class" method rather than the schema creation by the name of the inner class.

- If there is no other way, I would like it to be possible to set it in the property or Yaml file and then set it in the "outer-class.inner-class" method. If you don't have the function, can I modify it myself and ask for PR?

**Comment by bnasslahsen** [comment]
use `springdoc.use-fqn=true`
