### ISSUE TITLE
Swagger Doesn't See @PostMapping

### ISSUE THREAD

**Issue by cemrecodes** [springdoc/springdoc-openapi#2474]
I have a @PostMapping endpoint in my controller layer but it's not shown on Swagger UI.
I use latest version (version 2.3.0)
My Spring Boot version is 3.2.1

Screenshots:
![image](https://github.com/springdoc/springdoc-openapi/assets/83655146/0caf7940-af96-4281-b723-737e115a3ba7)
![image](https://github.com/springdoc/springdoc-openapi/assets/83655146/854b6888-cabf-4271-b1e2-e3b0659e1699)

**Comment by bnasslahsen** [comment]
@cemrecodes,

Not reproducible.
Feel free to provide a [Minimal, Reproducible Example - with HelloController](https://stackoverflow.com/help/minimal-reproducible-example) that reproduces the problem.

This ticket will be closed, but can be reopened if your provide the reproducible sample.
