### ISSUE TITLE
Commit 80bc5a75361d1689fa72099963db84bcd95b2068 breaks project with JDK 11 + Kotlin

### ISSUE THREAD

**Issue by joaodias14** [springdoc/springdoc-openapi#248]
The commit 80bc5a75361d1689fa72099963db84bcd95b2068 is breaking again our project built with JDK 11 and Kotlin.
Can you please revert this? Additionally, what is the purpose of using `LocalVariableTableParameterNameDiscoverer` just to get the name of the parameters that you can get from `java.lang.reflect.Parameter` array that you already have at that point?
I've removed this `LocalVariableTableParameterNameDiscoverer` and no test is breaking.
I hope you can remove this again. Thanks!

Best regards,
João Dias

**Comment by springdoc** [comment]
Hi, 

 Depending on compiler options, when call parameter.getName(),  the calls yields synthetic names such as arg0, arg1, and arg2. LocalVariableTableParameterNameDiscoverer is able to get the real names.

 Maybe, you can submit a PR to better support your case, even  LocalVariableTableParameterNameDiscoverer is there.

**Comment by joaodias14** [comment]
Ok, I understand the reason now.
Sure, I will take a deeper look and try to find a solution. Thanks!
