### ISSUE TITLE
I developed an openapi ui document that supports swagger2 and openapi3. I hope everyone can improve it together.

### ISSUE THREAD

**Issue by rookie-luochao** [springdoc/springdoc-openapi#2480]
repo is: https://github.com/rookie-luochao/openapi-ui
![12](https://github.com/springdoc/springdoc-openapi/assets/22948077/d54837ce-f17a-4709-ae0d-0f46d7d1031e)

**Comment by bnasslahsen** [comment]
Thank you for sharing
