### ISSUE TITLE
访问/swagger-ui/index.html，  请求/v3/api-docs/swagger-config路径404

### ISSUE THREAD

**Issue by dhp666** [springdoc/springdoc-openapi#2482]
![123](https://github.com/springdoc/springdoc-openapi/assets/52535757/8b9f47c4-6691-4630-9148-2547625179dc)

因为我的访问我的服务是经过nginx代理的， 就是我的域名https://**.**.com.cn/analysisapi    经过nginx代理后 https://**.**.com.cn/， 去掉了analysisapi ，但是访问v3/api-docs/swagger-config 404, 有办法可以修改域名部分吗，我期待的是https://**.**.com.cn/analysisapi,而不是 https://**.**.com.cn/analysisapi， 比如访问这个静态js资源是对的
![456](https://github.com/springdoc/springdoc-openapi/assets/52535757/db92a299-f276-4b4a-9556-5e8c5020439a)
这个是个bug呢，还是有办法可以配置，谢谢大佬指教一下

**Comment by bnasslahsen** [comment]
@dhp666,

only support in English...
