### ISSUE TITLE
springdoc-openapi v2.3.0, "XXX PROPS " is displayed to standard error.

### ISSUE THREAD

**Issue by namhokim** [springdoc/springdoc-openapi#2486]
**Describe the bug**

- When using springdoc-openapi v2.3.0, a message starting with "XXX PROPS " is displayed to standard error.

**To Reproduce**

- Use springdoc-openapi v2.3.0 version
- Request to server API_DOCS_URL ([OpenApiWebMvcResource#openapiJson](https://github.com/springdoc/springdoc-openapi/blob/a714f41b7761a2edb8ed4f7874de1d8f6ef8bb10/springdoc-openapi-starter-webmvc-api/src/main/java/org/springdoc/webmvc/api/OpenApiWebMvcResource.java#L107-L112))

**Expected behavior**

- No System.err debugging message.

**Screenshots**

<img width="475" alt="ScreenShot 2024-01-16 21 30 07" src="https://github.com/springdoc/springdoc-openapi/assets/1442538/a4c2a605-8363-471a-bf4b-63cf80b29302">

**Additional context**

- It is not springdoc bug, but swagger-core 2.2.19 on https://github.com/swagger-api/swagger-core/commit/699f70e0d8023d7c82fc25ac401cf1858a975dec
- swagger-core 2.2.20 fix this problem on https://github.com/swagger-api/swagger-core/commit/bfd25e297a4efe5983b5382c0f71b8dafabf2bb9
- Thus It will be fix Upgrade swagger-core to 2.2.20, please.

**Comment by lbruun** [comment]
I would think this will be automatically fixed as a result of [PR-2463](https://github.com/springdoc/springdoc-openapi/pull/2463) (already merged). However, you would have to wait for current project to publish a new release.

**Comment by bnasslahsen** [comment]
Should be fixed with swagger-core upgrade.
