### ISSUE TITLE
Wrong enum values in OpenAPI spec when `toString()` is overridden

### ISSUE THREAD

**Issue by ch4mpy** [springdoc/springdoc-openapi#2494]
### Describe the Bug

When an enum overrides `toString()`, then the output of this method is used to set the acceptable values in the generated OpenAPI spec.

This goes against [Java specs for enums serilization](https://docs.oracle.com/en/java/javase/11/docs/specs/serialization/serial-arch.html#serialization-of-enum-constants) and, more importantly, against how Spring behaves by default. In both cases, if no more than a `toString()` method is provided what is used is still:
- `name()` for serialization
- `valueof(name)` for deserialization

Using `toString()` output could make sense when it is decorated with `@JsonValue`, but this is a slippery ground as:
- there could be other annotations involved for XML & other serialization mechanisms
- there is a difference between `@RequestBody` and `@RequestParam` deserialization in spring:
  * requests body is deserialized just like `@ResponseBody` is serialized: using `HttpMessageConverter` beans. Default implementations of which use Jackson and will use `toString()` for (de)serialization because of `@JsonValue`. So; **it seems fine to use whatever is decorated with `@JsonValue` for `@RequestBody` and `@ResponseBody`**.
  * request params are converted from a String using a `Converter<String, E>`. Spring Web generates default converters using enums `valueOf()` methods (ignoring `@JsonValue`). To use something else (like the output of `toString()`), one has to provide a custom converter. The spec generator can hardly do better than guess what such a custom converter accepts as input, and should probably **keep using `name()` for request parameters**, unless explicitly instructed to do otherwise.

I don't really care what `swagger-core` does. **What matters to me is the generated OpenAPI spec to be aligned with inputs and outputs of my Spring REST APIs**. When an enum contains just a `toString()` method (without `@JsonValue` or whatever), this is not the case.

### To Reproduce
[Minimal project](https://github.com/ch4mpy/springdoc-openapi-2494)

Consider the following Spring `RestController`
```java
@RestController
public class DemoController {
    
    @GetMapping("/demo")
    public Dto getDemo(Dto dto) {
        return dto;
    }

    public static enum EnumSerializedByName {
        ON("is on"), OFF("is off");
        
        String label;
        
        EnumSerializedByName(String label) {
            this.label = label;
        }
        
        @Override
        public String toString() {
            return label;
        }
    }
    
    public static record Dto(EnumSerializedByName status) {}
}
```
and the following test:
```java
@WebMvcTest(controllers = DemoController.class)
class DemoControllerTest {
    
    @Autowired
    MockMvc mockMvc;

    @Test
    void whenGetDemo_thenStatusIsSerializedByName() throws Exception {
        mockMvc.perform(get("/demo").param("status", EnumSerializedByName.ON.name())).andExpect(status().isOk()).andExpect(jsonPath("status", is(EnumSerializedByName.ON.name())));
        mockMvc.perform(get("/demo").param("status", EnumSerializedByName.ON.toString())).andExpect(status().is4xxClientError());
    }

}
```
We see here that `toString()` is ignored for (de)serialization. **The serialization and deserialization are done respectively using the `name()` and `valueOf()` methods**.

### Expected Behavior

The schema should be generated with the values expected by the endpoint and generated by it.

At bare minimum, the default for enum values should be what spring uses by default. Here we don't even have something like an annotation to notify the spec generator that we want it to use `name()` for the values it put in the OpenAPI spec for an enum.

### Additional context
I know about [this other issue](https://github.com/springdoc/springdoc-openapi/issues/2048) but can't comment on it as it is locked.

I also know about the workaround provided by @bnasslahsen in the same issue, but it affects all enums, even those implemented as below.

For illustration purposes, here is how an enum has to be implemented to behave as currently documented in the generated spec:
```java
public static enum BijectiveEnumSerializedByToString {
    A("bij a"),
    B("bij b");

    String label;

    BijectiveEnumSerializedByToString(String label) {
        this.label = label;
    }

    @Override
    @JsonValue // Forces serialization using toString()
    public String toString() {
        return label;
    }

    /**
     * Inverse operation for the toString() method
     *
     * @param str the serialized value of the enum
     * @return deserialized enum value
     */
    public static BijectiveEnumSerializedByToString fromString(String str) {
        for (final var e : BijectiveEnumSerializedByToString.values()) {
            if (Objects.equals(e.toString(), str)) {
                return e;
            }
        }
        return null;
    }

    /**
     * Register a Spring converter deserialize &#64;RequestParam from String to {@link BijectiveEnumSerializedByToString}
     */
    @Component
    static class StringEnumSerializedByToStringConverter implements Converter<String, BijectiveEnumSerializedByToString> {
        @Override
        public BijectiveEnumSerializedByToString convert(String source) {
            return BijectiveEnumSerializedByToString.fromString(source);
        }
    }
}
```
Note:
- `@JsonValue` decorating `public String toString()`
- the custom converter bean for request params

### Detailed Observations on the Currently Generated Spec
considering the following enums in addition to the `BijectiveEnumSerializedByToString ` above:
```java
public static enum EnumSerializedByName {
    A("name a"),
    B("name b");

    String label;

    EnumSerializedByName(String label) {
        this.label = label;
    }

    @Override
    public String toString() {
        return label;
    }
}
```
```java
public static enum EnumSerializedByToString {
    A("str a"),
    B("str b");

    String label;

    EnumSerializedByToString(String label) {
        this.label = label;
    }

    @Override
    @JsonValue // Forces serialization using toString()
    public String toString() {
        return label;
    }
}
```

with Spring default:
- `HttpMessageConverter` beans
- `Converter<String, EnumSerializedByName>`
- `Converter<String, EnumSerializedByToString>`
- ~~`Converter<String, BijectiveEnumSerializedByToString>`~~ (this one is not generated because we registered a `StringEnumSerializedByToStringConverter` instance as bean)

the generated spec for a `Dto` containing the three enum types is:
```json
  "components": {
    "schemas": {
      "Dto": {
        "required": ["bij", "name", "str"],
        "type": "object",
        "properties": {
          "name": { "type": "string", "enum": ["name a", "name b"] },
          "str": { "type": "string", "enum": ["str a", "str b"] },
          "bij": { "type": "string", "enum": ["bij a", "bij b"] }
        }
      }
    }
  }
```

this is:
- wrong for `EnumSerializedByName` wich is always serialized using `name()` and deserialised using `valueOf()` (acceptable values should be `["A", "B"]`)
- right for `BijectiveEnumSerializedByToString` because we provided quite some code for it:
  * `toString()` decorated with `@JsonValue`
  * a custom `Converter<String, BijectiveEnumSerializedByToString>` registered as a Spring bean
- tricky for `EnumSerializedByToString`:
  * right when `HttpMessageConverter` beans are used (`@RequestBody` and `@ResponseBody`)
  * wrong when the default `Converter<String, EnumSerializedByToString>` is used (`@RequestParam`)

**Comment by bnasslahsen** [comment]
@ch4mpy,

You can use the mentioned workaround and adapt it to filter for your own Enum types only.
It good to understand that the `springdoc-openapi` is built on top of `swagger-core`.
`springdoc-openapi` is not a replacement of `swagger-core` and the Enum Serialization is done in `swagger-core`.

We can add some enhancements in `springdoc-openapi` when we estimate it will be useful for the community.
If you feel you can propose any kind of enhancements, feel free to propose a PR.

**Comment by ch4mpy** [comment]
@bnasslahsen the issue I opened here is not about `swagger-core` serialization, it is about `springdoc-openapi` OpenAPI spec generation.

I think it is abrupt to close the ticket because, as demonstrated in the ticket opening, the generated doc is not conform with Spring API output and the proposed workaround is just some bandage on a wooden leg.

**Comment by bnasslahsen** [comment]
@ch4mpy,

Thank you for your feedback.
But your reproducer, doesn't show any problem in `springdoc-openapi` generation.
As explained, it's in the `swagger-core`.
In addition, it's duplicate of: 
- - https://github.com/springdoc/springdoc-openapi/issues/1247


if you are able to proof, that it's in the `springdoc-openapi` we will be happy to help you.

**Comment by ch4mpy** [comment]
@bnasslahsen no, it is not in `swagger-core`.

From the reproducer (please note the `toString()` method):
```java
public static enum EnumSerializedByName {
    A("name a"), B("name b");

    String label;

    EnumSerializedByName(String label) {
        this.label = label;
    }

    @Override
    public String toString() {
        return label;
    }
}
```

This is serialized as `A` or `B` and not as `name a` or `name b` as asserted by the [following test](https://github.com/ch4mpy/springdoc-openapi-2494/blob/eb2e628b1e6d70bdb0c6f552466dd4c28e2314a1/src/test/java/com/c4soft/DemoControllerTest.java#L37): 
```java
.andExpect(jsonPath("name", is(EnumSerializedByName.A.name())))
```
**But the OpenAPI spec generated by  `springdoc-openapi` states otherwise.**

This other ticket you link has little to do with the discussion: the author does not provide a `toString()` method in his enum and does change Jackson serialization configuration.

The reproducer I proposed keeps default Jackson (and swagger) config, but still, the generated OpenAPI spec is wrong when `toString()` is overriden (and unless it is decorated with `@JsonValue` and a custom `Converter` provided in the app context)

**Comment by bnasslahsen** [comment]
@ch4mpy,

We would be really happy to help you find a solution.
Could you please check the result of `resolvedSchema.schema`

```java
		ResolvedSchema resolvedSchema = ModelConverters.getInstance()
				.resolveAsResolvedSchema(
						new AnnotatedType(EnumSerializedByName.class));
```

This is what is used used by springdoc-openapi. As you can see it's plain swagger-core code. What do you propose for us to do else ?

FYI, your reproducer project is having all tests passing (which is not a real reproducer project though!)

**Comment by ch4mpy** [comment]
I'll add a test failing because the actual value from the `@RestController` call in the test (`A` in the test I linked above) is not in the possible values from the generated spec: `"enum": ["name a", "name b"]`.

This means that what `springdoc-openapi` uses is either bugged or not adapted to the need.

> What do you propose for us to do else ?

Produce a spec conforming with actual Spring REST APIs input & output

I'm not sure I have time anytime soon to dig into your project code to find a way to use Spring beans involved in enums (de)serialization and propose a PR (the time I spend for free on opensource projects is already much higher than my bank would like to).

**Comment by ch4mpy** [comment]
@bnasslahsen [test added](https://github.com/ch4mpy/springdoc-openapi-2494/blob/cfd6eddc81c40d7ec3531fd5da1307634276794a/src/test/java/com/c4soft/EnumBugReproducerApplicationTests.java#L52) 

This parses the spec retrieved from `/v3/api-docs` and test the actual returned serialized enums against the spec. The test fail for the enum having a `toString()` method which is not decorated with `@JsonValue`.

**Comment by bnasslahsen** [comment]
@ch4mpy,

You maybe do not understand which test should be failing.
It's not the REST API call of your endpoint, but the **expected OpenAPI result** vs the **actual OpenAPI spec**.

**Comment by bnasslahsen** [comment]
> I'll add a test failing because the actual value from the `@RestController` call in the test (`A` in the test I linked above) is not in the possible values from the generated spec: `"enum": ["name a", "name b"]`.
> 
> This means that what `springdoc-openapi` uses is either bugged or not adapted to the need.
> 
> > What do you propose for us to do else ?
> 
> Produce a spec conforming with actual Spring REST APIs input & output
> 
> I'm not sure I can dig into your project code anytime soon to to find a way to use Spring beans involved in enums (de)serialization and propose a PR (the time I spend for free on opensource projects is already much higher than my bank would like to).

Unfortunately, we appreciate better collaborative. approaches than that.

**Comment by bnasslahsen** [comment]
@ch4mpy, 

You should check in the transitive dependencies of the [reproducer pom](https://github.com/ch4mpy/springdoc-openapi-2494/blob/main/pom.xml).

This is the parts of code where the serialization is done: 
- https://github.com/swagger-api/swagger-core/blob/6ccd2f8132196ba8e51e3e0029c8c3ea4448825b/modules/swagger-core/src/main/java/io/swagger/v3/core/jackson/ModelResolver.java#L936-L974

When you have an issue in jackson, you will not as the spring team to fix it as far as i know.
It's not the right approach to change the behavior of the up stream dependencies...

If you want to do things right, try to proposing a PR to the `swagger-core` project instead for this use case.
And we will integrate it in a future release.

**Comment by ch4mpy** [comment]
#### Fixing `swagger-core`
As explained several times already, **changing the way `swagger-core` serializes enum values won't fix the Spring applications OpenAPI spec**. This is because enum values in Spring applications are, as far as I know, not (de)serialized using swagger but using:
- registered `Converter<String, E>` beans in the case of `@RequestParam`
- registered `HttpMessageConverter` beans in the case of `@RequestBody` and `@ResponseBody`

So probably, yes, changing `swagger-core` could provide with a slightly better default, but it won't solve the core problem with the specification of Spring APIs.

#### Request for clarifications
@bnasslahsen can we agree that providing with the OpenAPI specification of Spring REST APIs is an intended feature of `springdoc-openapi`? Because otherwise, I'm just at the wrong place.

If the answer to the preceding is yes, would you please enlight me how you can consider as a "desirable feature" the fact that the actual spec for enums contains possible values that:
- are not returned by Spring APIs as  `@ResponseBody`
- throw an error when deserialized as `@RequestBody` or `@RequestParam`

Last, could please confirm that the position you take about that is the "official" position of the team behind `springdoc-openapi`?

#### Dependencies
As you point out, Swagger is a **transitive** dependency of `springdoc-openapi`. This means that it is a choice of whoever implements `springdoc-openapi` to use it to achieve its purpose (which I can understand because it gets a lot of the job done). But this also means that my code should not depend on anything from Swagger, because `springdoc-openapi` could choose to use a newer version Swagger breaking my own code or even something completely different than Swagger.

Also, if you are curious enough, you can explore [this pom](https://github.com/ch4mpy/quiz/blob/f1806d128a352df1162e291201c6a4416fe86ae0/api/quiz-api/pom.xml#L154) which is a show-case for usage of `springdoc-openapi` dependencies: in a maven profile with `springdoc-openapi-maven-plugin` to generate the doc during the `integration-test` phase. So no, I don't have Swagger on the classpath at runtime, just because I don't have `springdoc-openapi` on the classpath at runtime (it is on the classpath only during integration-tests).

#### How I handle issues with transitive dependencies to my code
This is clearly off topic and of little interest, but I certainly don't close tickets, requesting users to open PRs on my transitive dependencies. Most users just don't have the skills, and anyhow, this is none of their business to fix what I choose to use.

What I do is opening tickets or PRs (or both) myself. And if the issue is critical for the feature I'm asked to provide, actually, yes, I implement a workaround until it the transitive dependency is fixed or enhanced. The reason for that is such requests are processed in another time-frame than the SLA I usually want to provide (for instance, it took you  more than a month to start reading this ticket or [this PR on spring-security](https://github.com/spring-projects/spring-security/pull/13648#pullrequestreview-1789927128) I opened more than 6 month ago is still pending for merge. Sometimes, some features are even rejected (a sample being the support for more than just one single issuer in Spring Boot resource server properties). I'm not blaming anyone for delays or libs orientation decision, I'm just explaining why I sometimes alter transitive dependencies behavior in my projects (temporarily or not).

**Comment by ch4mpy** [comment]
For the record, here is what the spec should look like for the reproducer:
```json
{
  "openapi": "3.0.1",
  "info": { "title": "OpenAPI definition", "version": "v0" },
  "servers": [
    { "url": "http://localhost", "description": "Generated server url" }
  ],
  "paths": {
    "/demo": {
      "get": {
        "tags": ["demo-controller"],
        "operationId": "getDemo",
        "parameters": [
          {
            "name": "nameRequestParam",
            "in": "query",
            "required": true,
            "schema": { "type": "string", "enum": ["A", "B"] }
          },
          {
            "name": "strRequestParam",
            "in": "query",
            "required": true,
            "schema": { "type": "string", "enum": ["A", "B"] }
          },
          {
            "name": "bijRequestParam",
            "in": "query",
            "required": true,
            "schema": { "type": "string", "enum": ["bij a", "bij b"] }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "*/*": { "schema": { "$ref": "#/components/schemas/Dto" } }
            }
          }
        }
      },
      "put": {
        "tags": ["demo-controller"],
        "operationId": "putDemo",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": { "$ref": "#/components/schemas/Dto" }
            }
          },
          "required": true
        },
        "responses": { "200": { "description": "OK" } }
      }
    }
  },
  "components": {
    "schemas": {
      "Dto": {
        "required": ["bij", "name", "str"],
        "type": "object",
        "properties": {
          "name": { "type": "string", "enum": ["A", "B"] },
          "str": { "type": "string", "enum": ["str a", "str b"] },
          "bij": { "type": "string", "enum": ["bij a", "bij b"] }
        }
      }
    }
  }
}
```
Please note the difference in the possible values for the `EnumSerializedByToString` depending it is a `@RequestParam("strRequestParam")` or the `Dto.str` embedded in a `@RequestBody` or `@ResponseBody`.

**Comment by ch4mpy** [comment]
> if you are able to proof, that it's in the `springdoc-openapi` we will be happy to help you.

What I proved is that what `springdoc-openapi` uses for enum values (de)serialization is not what Spring uses and that it leads to invalid OpenAPI specification (`swagger-core` in the case of `springdoc-openapi` and `Converter<String, E>` & `HttpMessageConverter` in the case of a Spring app).

Enums are not the only case for discrepancies between generated spec VS actual Spring API input & output: quite a lot of boilerplate annotations could be saved when Spring converters jump in. For instance, `springdoc-openapi` could be able to document correctly the following:
```java
@GetMapping("/messages/{messageId}")
public Message getMessage(@PathVariable(name = "messageId") Message message) {
    return message;
}
```
In the above, the schema should be made for a `messageId` with `String` as type, the conversion from `String` to `Message` being done "magically" with converters generated from repositories.
```java
@GetMapping("/demo")
public Dto getDemo(Dto dto) {
    return dto
}
```
There, the input should be exploded in many `@RequestParam` (one per `Dto` property), as if the method was written:
```java
@GetMapping("/demo")
public Dto getDemo(
        @RequestParam EnumSerializedByName nameRequestParam,
        @RequestParam("strRequestParam") EnumSerializedByToString strRequestParam,
        @RequestParam BijectiveEnumSerializedByToString bijRequestParam) {
    return new Dto(nameRequestParam, strRequestParam, bijRequestParam);
}
```

@bnasslahsen can you confirm that you have no plan to integrate such Spring beans usage to fix enum possible values or to document correctly Spring controllers "magic" attributes?

**Comment by bnasslahsen** [comment]
@ch4mpy,

Further discussions here will be a waste of time.
This ticket ER is rejected.

For the futur, make sure you respect the [code of conduct](https://github.com/springdoc/springdoc-openapi/blob/0fdfabadf9a51895ada8c432aa521715e971b149/CODE_OF_CONDUCT.md).
