### ISSUE TITLE
Inherited schemas are not shown in the "Schema" section of the ui, when component is referenced only in the response body

### ISSUE THREAD

**Issue by toghrulguliyev** [springdoc/springdoc-openapi#2496]
I have build an openapi specification in `yaml`. There is a general schema and several others, which are inheriting the general schema (with discriminator and mapping). The java classes are being correctly built.

When i put the generated object of the general schema as a response, the inherited classes are not being shown in the swagger-ui "Schemas" section. When i put the same schema into request body section in the yaml, then all the possible inherited schemas are being shown in the "Schemas" sections of the ui.

I am using:
- SpringBoot -> `3.2.2`
- `springdoc-openapi-starter-webmvc-ui` -> `2.3.0`
- OpenAPI Specification 3.0
- I have tried to use absolutely general construct, without anything extra. Simple polymorphism with discriminator & mapping of the inherited schemas in the general schema and `allOf` in the inherited schemas.
- I have 2 separate modules. In one i have `yaml` files (file for endpoints and one for models/components) and the other is the actual service with an example controller, which uses the generated jar from the api module.

This seems like a bug, where response body is not being checked for inherited schemas. If not, please provide some direction on how to solve this. May be i could override some classes, where i could fix this for now.

Thank you!

**Comment by bnasslahsen** [comment]
@toghrulguliyev,

Not reproducible.
Feel free to provide a [Minimal, Reproducible Example - with HelloController](https://stackoverflow.com/help/minimal-reproducible-example) that reproduces the problem.

This ticket will be closed, but can be reopened if your provide the reproducible sample.
