### ISSUE TITLE
@Schema required field based on @JsonView

### ISSUE THREAD

**Issue by bacao1994** [springdoc/springdoc-openapi#2498]
**Describe the bug**
I want to make the field **name** of my Request.class treated as an optional field( my update API) or required field(my creat API) as below based on my JsonView setting, without separating the POJO class. 

**To Reproduce**

- What version of spring-boot are you using? 
   3.0.7
- What modules and versions of springdoc-openapi are you using?
        <dependency>
            <groupId>org.springdoc</groupId>
            <artifactId>springdoc-openapi-starter-webmvc-ui</artifactId>
            <version>2.1.0</version>
        </dependency>

My Views.class:
```
public class Views {
    public interface Default { }
    public interface Get extends Default { }
    public interface Create extends Default { }
    public interface Update extends Default { }
}
```
My Request.class:

```
@Getter
@Setter
@JsonInclude(JsonInclude.Include.NON_EMPTY)
@Schema(description = "Request")
public class Request implements Serializable {

    @Serial
    private static final long serialVersionUID = -7069145691613164414L;

        @JsonView({Views.Default.class})
        @Schema(description = "name", required = true)
    @NotNull(groups = {Views.Create.class})
    private String name;
     ....  other fields
```
 ```
My Api class
    @Operation(description = "Create",
            responses = {
                    @ApiResponse(responseCode = "201",
                            description = "Request",
                            content = @Content(schema = @Schema(implementation = Request.class)))
            })
    @JsonView(Views.Get.class)
    @PostMapping
    public ResponseEntity<Request> create(@JsonView(Views.Create.class) @RequestBody @Validated({Views.Create.class}) @NotNull final Request request) {

        ...
    }

    @Operation(description = "Update ",
            responses = {
                    @ApiResponse(responseCode = "200",
                            description = "Request",
                            content = @Content(schema = @Schema(implementation = Request.class)))
            })
    @JsonView(Views.Get.class)
    @PutMapping("/{code}")
    public ResponseEntity<Request> update(@JsonView(Views.Update.class) @RequestBody @Validated({Views.Update.class}) final Request request,
                                                 @PathVariable("code") @NotNull String code) {
	...
	}
```

**Expected behavior**
  In my code, the @Schema(description = "name", required = true) will force the field name to be required in both create and update API. I know it's not good. Please help me to improve it. Thanks

- Create API: showing the field name is a required field in the UI (marked red * in swagger-ui/index.html)
- Update API: showing the field name is an optional field in the UI

**Comment by bnasslahsen** [comment]
@bacao1994,

This is not a bug but an enhancement request.
There is no plans for this support. 

If you feel it useful for the community, feel free to propose a PR.
