### ISSUE TITLE
Proposal: relative server url by default 

### ISSUE THREAD

**Issue by michaldo** [springdoc/springdoc-openapi#2499]
Openapi specification defines `server`
https://swagger.io/specification/#server-object

Springdoc by default creates a server object from HTTP request. It is problematic, because HTTP request may be jump between gateways and request which reached Springdoc may be different from request initiated by client. Base url calculate with 
`org.springdoc.webmvc.api.OpenApiWebMvcResource#getServerUrl`
or 
`org.springdoc.webmvc.api.OpenApiActuatorResource#getServerUrl`
may be completely useless (private host and port)

There is a simple solution: _do it well or not at all_

According to OpenAPI specification, `server` is not required

> If the servers property is not provided, or is an empty array, the default value would be a [Server Object](https://swagger.io/specification/#server-object) with a [url](https://swagger.io/specification/#server-url) value of /.

And 

> server.url: REQUIRED. A URL to the target host. This URL supports Server Variables and MAY be relative, to indicate that the host location is relative to the location where the OpenAPI document is being served. (...)

My proposal:  `server.url` by default is relative and  initialized with `${server.servlet.context-path}`

**Comment by bnasslahsen** [comment]
@michaldo,

If the generated server URL is not a right fit for your needs.
You still can set it by using `springdoc properties`.

**Comment by michaldo** [comment]
Indeed I can clear springdoc default and effectively restore swagger
default.

But why? Do you see any benefit in overriding Swagger default?

Swagger default is clever. URL is not part of application but part of
deployment. Dev URL is different than test URL but duet clever default it
is not necessary to specify it.

niedz., 3 mar 2024, 10:40 użytkownik Badr NASS LAHSEN <
***@***.***> napisał:

**Comment by MissakaI-Cloudtrix** [comment]
> [@michaldo](https://github.com/michaldo),
> 
> If the generated server URL is not a right fit for your needs. You still can set it by using `springdoc properties`.

But how, https://springdoc.org/#properties doesn't include any property to specify the server url.

**Comment by michaldo** [comment]
> > [@michaldo](https://github.com/michaldo),
> > If the generated server URL is not a right fit for your needs. You still can set it by using `springdoc properties`.
> 
> But how, https://springdoc.org/#properties doesn't include any property to specify the server url.

You can configure
```
@OpenAPIDefinition(servers = @Server(url = "${swagger.url}"))
@Configuration
class SwaggerConfiguration {
}
