### ISSUE TITLE
How to configure global security schemes?

### ISSUE THREAD

**Issue by tfedyanin** [springdoc/springdoc-openapi#25]
Hi, I can't understand how to correctly configure `components.securitySchemes` part of specification for all my controllers.

Now I use workaround:
```java
@Component
public class SecuritySchemeInjector implements BeanPostProcessor {
    @Override
    public Object postProcessAfterInitialization(Object bean, String beanName) throws BeansException {
        if (beanName.equals("openAPIBuilder")&&(bean instanceof OpenAPIBuilder)) {
            return injectSecurityScheme((OpenAPIBuilder) bean);
        }
        return bean;
    }

    private OpenAPIBuilder injectSecurityScheme(OpenAPIBuilder bean) {
        bean.getComponents().addSecuritySchemes("bearerAuth", getBearerScheme());
        bean.getComponents().addSecuritySchemes("googleApiKey", getApiKeyScheme());
        return bean;
    }

   ...

}
```

How to do it correctly?

**Comment by springdoc** [comment]
For global SecurityScheme, you can add it inisde your own OpenAPI definition. This will be fixed with #28.
@Bean
	public OpenAPI customOpenAPI() {
		return new OpenAPI()
				.components(new Components().addSecuritySchemes("basicScheme",
						new SecurityScheme().type(SecurityScheme.Type.HTTP).scheme("basic")))
				.info(new Info().title("Custom API").version("100")).addTagsItem(new Tag().name("mytag"));
	}
