### ISSUE TITLE
Unable to set Oauth redirect URI without adding default context path

### ISSUE THREAD

**Issue by SwapnilKhante** [springdoc/springdoc-openapi#2502]
Description:

I am trying to set up the Oauth2 Authorization flow and need to provide a specific redirection URI. When I am setting the `oauth2-redirect-URL`, for example, -> `appname://oauth2redirect` final URI formed always has a default context path added to it like `redirect_uri=http://localhost:8080/appname:/oauth2redirect` which I did not want in this case

Dependencies used

<dependency>
            <groupId>org.springdoc</groupId>
            <artifactId>springdoc-openapi-starter-webmvc-ui</artifactId>
            <version>2.3.0</version>
   </dependency>

Java 17

Sringboot version - 3.1.0

**Comment by bnasslahsen** [comment]
@SwapnilKhante,

You can extend `SwaggerWelcomeCommon`, override the `calculateOauth2RedirectUrl` and then declare your own `SwaggerWelcome` Bean.
