### ISSUE TITLE
Multiple schemas for same response code for same mime type is now working as expected in swagger ui

### ISSUE THREAD

**Issue by pavan-madanapalli** [springdoc/springdoc-openapi#2504]
**Description of the bug**
oneOf attribute of @Schema is not being rendered properly when multiple schemas can be returned for a single response code.

- If you are reporting a bug, please help to speed up problem diagnosis by providing as
  much information as possible:
- A clear and concise description of what the bug is: the title of an issue is not enough

**To Reproduce**

- What version of spring-boot you are using?
  spring-boot-starter-parent : 3.0.2
- What modules and versions of springdoc-openapi are you using?
   springdoc-openapi-starter-webmvc-ui : 2.3.0
   springdoc-openapi-security : 1.5.9
- What is the actual and the expected result using OpenAPI Description (yml or json)?
   Expected Output: (showing POST here as part of input for example)
![oneOf swagger example](https://github.com/springdoc/springdoc-openapi/assets/159184268/2ce8d5ba-6f51-4b8a-afd3-f66b2cc0f9e3)
Actual Output:
![oneOf actual](https://github.com/springdoc/springdoc-openapi/assets/159184268/828789de-8711-4030-8cbd-fdad25571c17)

- Provide with a sample code (HelloController) or Test that reproduces the problem
@Operation(summary = "Get list of Foo objects or Bar objects based on the query parameter category", description = "Get list of Foo objects or Bar objects based on the query parameter category")
@ApiResponses(value = {
            @ApiResponse(responseCode = "200", description = "Ok", content = {
                    @Content(array = @ArraySchema(schema = @Schema(oneOf = {Foo.class, Bar.class})),
                            mediaType = MediaType.APPLICATION_JSON_VALUE)            }),
            @ApiResponse(responseCode = "400", description = "Invalid Request.", content = {
                    @Content(schema = @Schema(implementation = ResponseStatus.class), mediaType = MediaType.APPLICATION_JSON_VALUE)})})
@GetMapping("/something")
public ResponseEntity<Object> getData(@RequestParam(value = "category", required = true) String category) throws IOException {
	return service.getData(category);
}

**Expected behavior**
- Please refer to expected screenshot where oneOf should show different schemas in the swagger ui
![oneOf swagger example](https://github.com/springdoc/springdoc-openapi/assets/159184268/2ce8d5ba-6f51-4b8a-afd3-f66b2cc0f9e3)

**Additional context**

![oneOf actual](https://github.com/springdoc/springdoc-openapi/assets/159184268/828789de-8711-4030-8cbd-fdad25571c17)

Actual Output is showing the combined string of all properties of Foo.class and Bar.class

**Comment by bnasslahsen** [comment]
@pavan-madanapalli,

You should not combine:
```
springdoc-openapi-starter-webmvc-ui : 2.3.0
springdoc-openapi-security : 1.5.9
```

Feel free to provide a [Minimal, Reproducible Example - with HelloController](https://stackoverflow.com/help/minimal-reproducible-example) that reproduces the problem when you clean your project.

This ticket will be closed, but can be reopened if your provide the reproducible sample.

**Comment by NiFNi** [comment]
@bnasslahsen We have the same issue. To reproduce use the following Controller:
```
@RestController
public class Controller {


    @ApiResponse(responseCode = "200",
            content = @Content(mediaType = MediaType.APPLICATION_JSON_VALUE,
                    array = @ArraySchema(schema = @Schema(anyOf = {
                            Dto1.class,
                            Dto2.class
                    }))))
    @GetMapping
    public List<? extends AbstractDto> get() {
        return List.of();
    }
}
```
Dtos:
```
public abstract class AbstractDto {
    private String test;
}
```
```
public class Dto1 extends AbstractDto {
    private String test1;
}
```
```
public class Dto2 extends AbstractDto {
    private String test2;
}
```
Application class:
```
@SpringBootApplication
public class DemoApplication {

    public static void main(String[] args) {
        SpringApplication.run(DemoApplication.class, args);
    }

}
```
pom.xml in case its helpful to reproduce:
```
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>3.2.3</version>
        <relativePath/> <!-- lookup parent from repository -->
    </parent>
    <groupId>com.example</groupId>
    <artifactId>demo</artifactId>
    <version>0.0.1-SNAPSHOT</version>
    <name>demo</name>
    <description>demo</description>
    <properties>
        <java.version>17</java.version>
    </properties>
    <dependencies>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
        </dependency>

        <dependency>
            <groupId>org.springdoc</groupId>
            <artifactId>springdoc-openapi-starter-webmvc-ui</artifactId>
            <version>2.2.0</version>
        </dependency>

        <dependency>
            <groupId>io.swagger.core.v3</groupId>
            <artifactId>swagger-annotations</artifactId>
            <version>2.2.20</version>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
            </plugin>
        </plugins>
    </build>

</project>
```


The result looks like this: 
![image](https://github.com/springdoc/springdoc-openapi/assets/11833155/7f73a6e8-3b36-4edc-921d-5ce5c4d6aff4)

I would have expected a oneOf schema like shown in @pavan-madanapalli screenshot. Are we somehow using the annotations wrong or is this an issue with springdoc?

**Comment by NiFNi** [comment]
I think this is an issue with swagger-core. I created an issue there: https://github.com/swagger-api/swagger-core/issues/4624

**Comment by Hyperkopite** [comment]
> @bnasslahsen We have the same issue. To reproduce use the following Controller:
> 
> ```
> @RestController
> public class Controller {
> 
> 
>     @ApiResponse(responseCode = "200",
>             content = @Content(mediaType = MediaType.APPLICATION_JSON_VALUE,
>                     array = @ArraySchema(schema = @Schema(anyOf = {
>                             Dto1.class,
>                             Dto2.class
>                     }))))
>     @GetMapping
>     public List<? extends AbstractDto> get() {
>         return List.of();
>     }
> }
> ```
> 
> Dtos:
> 
> ```
> public abstract class AbstractDto {
>     private String test;
> }
> ```
> 
> ```
> public class Dto1 extends AbstractDto {
>     private String test1;
> }
> ```
> 
> ```
> public class Dto2 extends AbstractDto {
>     private String test2;
> }
> ```
> 
> Application class:
> 
> ```
> @SpringBootApplication
> public class DemoApplication {
> 
>     public static void main(String[] args) {
>         SpringApplication.run(DemoApplication.class, args);
>     }
> 
> }
> ```
> 
> pom.xml in case its helpful to reproduce:
> 
> ```
> <?xml version="1.0" encoding="UTF-8"?>
> <project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
>          xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
>     <modelVersion>4.0.0</modelVersion>
>     <parent>
>         <groupId>org.springframework.boot</groupId>
>         <artifactId>spring-boot-starter-parent</artifactId>
>         <version>3.2.3</version>
>         <relativePath/> 
>     </parent>
>     <groupId>com.example</groupId>
>     <artifactId>demo</artifactId>
>     <version>0.0.1-SNAPSHOT</version>
>     <name>demo</name>
>     <description>demo</description>
>     <properties>
>         <java.version>17</java.version>
>     </properties>
>     <dependencies>
>         <dependency>
>             <groupId>org.springframework.boot</groupId>
>             <artifactId>spring-boot-starter-web</artifactId>
>         </dependency>
> 
>         <dependency>
>             <groupId>org.springframework.boot</groupId>
>             <artifactId>spring-boot-starter-test</artifactId>
>             <scope>test</scope>
>         </dependency>
> 
>         <dependency>
>             <groupId>org.springdoc</groupId>
>             <artifactId>springdoc-openapi-starter-webmvc-ui</artifactId>
>             <version>2.2.0</version>
>         </dependency>
> 
>         <dependency>
>             <groupId>io.swagger.core.v3</groupId>
>             <artifactId>swagger-annotations</artifactId>
>             <version>2.2.20</version>
>         </dependency>
>     </dependencies>
> 
>     <build>
>         <plugins>
>             <plugin>
>                 <groupId>org.springframework.boot</groupId>
>                 <artifactId>spring-boot-maven-plugin</artifactId>
>             </plugin>
>         </plugins>
>     </build>
> 
> </project>
> ```
> 
> The result looks like this: ![image](https://private-user-images.githubusercontent.com/11833155/309755553-7f73a6e8-3b36-4edc-921d-5ce5c4d6aff4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE5NDQ4NDMsIm5iZiI6MTcxMTk0NDU0MywicGF0aCI6Ii8xMTgzMzE1NS8zMDk3NTU1NTMtN2Y3M2E2ZTgtM2IzNi00ZWRjLTkyMWQtNWNlNWM0ZDZhZmY0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDAxVDA0MDkwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFmZDBmNDU4OTRjNDUyMDhiM2IzNWJkMjA1YzU2MzU1NjY2YTJiYjY1YjJlNzA3ZDU4MTliODY2ZGJmMGIwNzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.gxYVYX49w3LA2-8iOy26pEDukFoBM0BHHl8zyoxq33M)
> 
> I would have expected a oneOf schema like shown in @pavan-madanapalli screenshot. Are we somehow using the annotations wrong or is this an issue with springdoc?

U need to explicitly specify the value of "type" as "object"，like this:
![image](https://github.com/springdoc/springdoc-openapi/assets/9525971/8b76ff68-e1f4-4ae3-bad5-60b1dea19455)
Then your problem will be solved.
