### ISSUE TITLE
Ambiguous mapping. Cannot map 'swaggerUiHome' method  org.springdoc.webmvc.ui.SwaggerUiHome#index()

### ISSUE THREAD

**Issue by lidothui** [springdoc/springdoc-openapi#2505]
The URL mapping of SwaggerUiHome is "/", it is conflict with my application controller:
2024-02-07 02:48:22,996 197174 [http-nio-8080-exec-8] ERROR [o:, u: t:] org.springframework.web.servlet.DispatcherServlet - Context initialization failed
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'requestMappingHandlerMapping' defined in org.springframework.web.servlet.config.annotation.DelegatingWebMvcConfiguration: Ambiguous mapping. Cannot map 'swaggerUiHome' method 
org.springdoc.webmvc.ui.SwaggerUiHome#index()
to {GET [/]}: There is already 'webController' bean method
c.a.d.l.controller.web.WebController#verify() mapped.

I have set the property: springdoc.swagger-ui.use-root-path=false, but it did not work.

Any solution which I could disable SwaggerUiHome?

**Comment by bnasslahsen** [comment]
@lidothui,

Not reproducible.
Feel free to provide a [Minimal, Reproducible Example - with HelloController](https://stackoverflow.com/help/minimal-reproducible-example) that reproduces the problem.

This ticket will be closed, but can be reopened if your provide the reproducible sample.
