### ISSUE TITLE
@springdoc Great contribution! But we're still having issues with `Pageable`.

### ISSUE THREAD

**Issue by AnnaKarlsson** [springdoc/springdoc-openapi#251]
@springdoc Great contribution! But we're still having issues with `Pageable`. 

Version: 1.2.17

The pageable-parameters are passed as
`offset=0&pageNumber=0&pageSize=0&sort=sorted,true,unsorted,true,empty,true&paged=true&unpaged=true`

![image](https://user-images.githubusercontent.com/1784879/70525983-dbf3ba80-1b48-11ea-8f9d-2606f1418cb9.png)

_Originally posted by @NicklasWallgren in https://github.com/springdoc/springdoc-openapi/issues/177#issuecomment-563992434_

**Comment by GrmpfNarf** [comment]
Hi,
as a Workaround i have hidden the Pageable  param and add the parameters via annotation manually.
````java
@GetMapping
@Operation(
    parameters = {
        @Parameter(in = ParameterIn.QUERY
                            , description = "Page you want to retrieve (0..N)"
                            , name = "page"
                            , content = @Content(schema = @Schema(type = "integer", defaultValue = "0"))),
        @Parameter(in = ParameterIn.QUERY
                            , description = "Number of records per page."
                            , name = "size"
                            , content = @Content(schema = @Schema(type = "integer", defaultValue = "20"))),
        @Parameter(in = ParameterIn.QUERY
                            , description = "Sorting criteria in the format: property(,asc|desc). "
                            + "Default sort order is ascending. " + "Multiple sort criteria are supported."
                            , name = "sort"
                            , content = @Content(array = @ArraySchema(schema = @Schema(type = "string"))))
            })
public PagedModel<EntityModel<..>> getIspContractsByContractSearch(@PageableDefault @Parameter(hidden = true) Pageable pageable) {
     ...
}      
````

**Comment by AnnaKarlsson** [comment]
Thanks! Will use the workaround until solved

**Comment by AnnaKarlsson** [comment]
Created annotation to not have 15 lines of code in every pageable request. Hope it helps someone :)
`
@Target({METHOD, ANNOTATION_TYPE})
@Retention(RetentionPolicy.RUNTIME)
@Operation(parameters = {
        @Parameter(in = ParameterIn.QUERY
                , description = "Page you want to retrieve (0..N)"
                , name = "page"
                , content = @Content(schema = @Schema(type = "integer", defaultValue = "0"))),
        @Parameter(in = ParameterIn.QUERY
                , description = "Number of records per page."
                , name = "size"
                , content = @Content(schema = @Schema(type = "integer", defaultValue = "20"))),
        @Parameter(in = ParameterIn.QUERY
                , description = "Sorting criteria in the format: property(,asc|desc). "
                + "Default sort order is ascending. " + "Multiple sort criteria are supported."
                , name = "sort"
                , content = @Content(array = @ArraySchema(schema = @Schema(type = "string"))))
})
public @interface PageableOperation {

    @AliasFor(annotation = Operation.class)
    String summary() default "";

}`

**Comment by GrmpfNarf** [comment]
> @AnnaKarlsson Created annotation to not have 15 lines of code in every pageable request. Hope it helps someone :)

Cool, was looking for something like that. Thank you.

**Comment by springdoc** [comment]
Hi guys, 

 You will have to declare explicit mapping of Pageable fields as Query Params and add the `@Parameter(hidden = true) Pageable pageable` on your pageable parameter.

 You have started with some proposals. 
 With the version 1.2.18, of springdoc-openapi, you can declare Pageable object as follow.

```java
@Target({ElementType.METHOD, ElementType.ANNOTATION_TYPE})
@Retention(RetentionPolicy.RUNTIME)
@Parameters({
        @Parameter(in = ParameterIn.QUERY
                , description = "Page you want to retrieve (0..N)"
                , name = "page"
                , content = @Content(schema = @Schema(type = "integer", defaultValue = "0"))),
        @Parameter(in = ParameterIn.QUERY
                , description = "Number of records per page."
                , name = "size"
                , content = @Content(schema = @Schema(type = "integer", defaultValue = "20"))),
        @Parameter(in = ParameterIn.QUERY
                , description = "Sorting criteria in the format: property(,asc|desc). "
                + "Default sort order is ascending. " + "Multiple sort criteria are supported."
                , name = "sort"
                , content = @Content(array = @ArraySchema(schema = @Schema(type = "string"))))
})
public @interface PageableAsQueryParam {

}
```
If we can come up with something more elegant we can add it directly to springdoc-openapi.

**Comment by Majlanky** [comment]
Hello,

I was not able to find the solution anywhere in the documentation. If you want to pageable behave as a set of standard parameters you **have to  add dependency** of `springdoc-openapi-data-rest` to your classpath and annotate your Pageable with @ParameterObject like:
```java
@Operation(description = "blahblah")
@GetMapping(value = ALL_URI, produces = MediaType.APPLICATION_JSON_VALUE)
public Whatever getAll(@ParameterObject @PageableDefault(size = 20, sort = "name") Pageable pageable) {
        ...
    }
```
The annotation of @ParameterObject causes additional customizing of Pageable. It even transfer setting of PageableDefault to the final documentation! 👍
