### ISSUE TITLE
Add support for jackson-databind-nullable

### ISSUE THREAD

**Issue by noshua** [springdoc/springdoc-openapi#2512]
**Is your feature request related to a problem? Please describe.**

When using springdoc-openapi together with openapi-generator and it's jackson-databind-nullable the generated swagger-ui for nullable fields is broken. Instead of showing the Object attributes only "present": true is displayed.

**Describe the solution you'd like**

A JsonNullable<Object> attribute should be displayed like an Optional<Object>. So the Object attributes should be displayed.

**Describe alternatives you've considered**

And couldn't find any alternatives.

**Additional context**

![grafik](https://github.com/springdoc/springdoc-openapi/assets/98149942/22ac728c-0ecb-4d76-a63d-99db0b6d6880)
![grafik](https://github.com/springdoc/springdoc-openapi/assets/98149942/95f22dfe-a339-4873-b99e-f41ba9f884ac)

**Comment by xak2000** [comment]
@bnasslahsen Can you please clarify what points you mean exactly?

I read the contribution docs you mentioned and I do not see any mention of how an **enhancement request** should be filled.

I see some point in the secion:
> If you are reporting a **bug**, please help to speed up problem diagnosis by providing as much information as possible

Maybe that is what you meant? But these points are really more appropriate for bugs, than feature requests. For example, I'm not sure how to provide "Minimal, Reproducible Example" for a feature request. :)

I'm asking because I want this (or similar) feature too to be implemented (maybe as an additional library if it will be dependent on a class, that doesn't exist in _springdoc_, e.g. `JsonNullable`) so I want to understand what information is missing in your opinion.

I agree that this feature request is far from ideal, so maybe I can explain it better.

I think the author wants [JsonNullable](https://github.com/OpenAPITools/jackson-databind-nullable/blob/8861f83253b2373288772a55f8fb3938fa4824b9/src/main/java/org/openapitools/jackson/nullable/JsonNullable.java) class to be treated exactly as `java.lang.Optional` is currently treated by _springdoc_. I.e. unwrapped by default, as this is how [jackson-databind-nullable](https://github.com/OpenAPITools/jackson-databind-nullable) works. It provides Jackson serializer/deserializer that authomatically maps `JSON string` to `JsonNullable<String>` and vice versa.

I.e. this model

```java
public class Pet {
    public JsonNullable<String> name = JsonNullable.undefined();
 }
```

should be treated like it was this:

```java
public class Pet {
    public String name;
 }
```

**Also it would be very useful to add a recipe to the official FAQ on how to configure _springdoc_ to make a custom "wrapper" class to be automatically treated like `Optional` (i.e. unwrapped).** Personaly I do not use _jackson-databind-nullable_ library and `JsonNullable` class, but I want to configure my own custom wrapper. Maybe it is easy to do, but the docs do not explain custom configuration capabilities very well, most classes do not even have javadocs, so for now I'm trying to find how it is implemented for `Optional` and do the same..

**Comment by xak2000** [comment]
Answering my own question on how to configure springdoc to make a custom "wrapper" class to be automatically treated like `Optional` (i.e. unwrapped).

1. A `io.swagger.v3.core.converter.ModelConverter` bean should be registered:

```java
@ConditionalOnProperty(name = SPRINGDOC_ENABLED, matchIfMissing = true)
@Configuration
public class ApiDocModelConvertersConfig {

	@Bean
	ModelConverter nullableOptionalModelConverter(ObjectMapperProvider objectMapperProvider) {
		return new NullableOptionalModelConverter(objectMapperProvider);
	}

}
```

Springdoc will automatically register all found `ModelConverter` beans as OpenAPI resolvers _(if only this information was mentioned in the docs...)_.

2. An example of `ModelConverter` implementation that unwraps `NullableOptional` model:

```java
@Slf4j
public class NullableOptionalModelConverter implements ModelConverter {

	private final ObjectMapperProvider objectMapperProvider;

	public NullableOptionalModelConverter(ObjectMapperProvider objectMapperProvider) {
		this.objectMapperProvider = objectMapperProvider;
	}

	@SuppressWarnings("rawtypes")
	@Override
	public Schema resolve(AnnotatedType type, ModelConverterContext context, Iterator<ModelConverter> chain) {
		AnnotatedType unwrappedType = tryUnwrapNullableOptional(type);
		if (unwrappedType != null) {
			return context.resolve(unwrappedType);
		}

		return chain.hasNext() ? chain.next().resolve(type, context, chain) : null;
	}

	private AnnotatedType tryUnwrapNullableOptional(AnnotatedType type) {
		if (type == null) {
			return null;
		}

		try {
			JavaType jtype;
			if (type.getType() instanceof JavaType) {
				jtype = (JavaType) type.getType();
			} else {
				jtype = objectMapperProvider.jsonMapper().constructType(type.getType());
			}

			if (NullableOptional.class.isAssignableFrom(jtype.getRawClass())) {
				return new AnnotatedType()
						.type(jtype.containedType(0))
						.name(type.getName())
						.parent(type.getParent())
						.jsonUnwrappedHandler(type.getJsonUnwrappedHandler())
						.skipOverride(type.isSkipOverride())
						.schemaProperty(type.isSchemaProperty())
						.ctxAnnotations(type.getCtxAnnotations())
						.resolveAsRef(type.isResolveAsRef())
						.jsonViewAnnotation(type.getJsonViewAnnotation())
						.skipSchemaName(type.isSkipSchemaName())
						.skipJsonIdentity(type.isSkipJsonIdentity())
						.propertyName(type.getPropertyName());
			} else {
				return null;
			}
		} catch (Exception e) {
			log.error("Error unwrapping NullableOptional", e);
			return null;
		}
	}

}
```

`NullableOptional` is my own class, but the same principle could be used to unwrap any class with generic arguments, such as [JsonNullable](https://github.com/OpenAPITools/jackson-databind-nullable/blob/8861f83253b2373288772a55f8fb3938fa4824b9/src/main/java/org/openapitools/jackson/nullable/JsonNullable.java) from [jackson-databind-nullable](https://github.com/OpenAPITools/jackson-databind-nullable) library.

**Comment by mschout** [comment]
For anyone else, this is my working version of this, that uses `JsonNullable`:

1: Register `JsonNullable` for Jackson somewhere.  My solution is this:

```
import com.fasterxml.jackson.databind.Module;
import lombok.extern.slf4j.Slf4j;
import org.openapitools.jackson.nullable.JsonNullableModule;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

@Configuration
@Slf4j
public class JacksonConfiguration {
  @Bean
  Module jsonNullableModule() {
    log.info("Configuring Jackson to use JsonNullable as null value");
    return new JsonNullableModule();
  }
}
```

In your DTO, only include `NON_NULL` items.  E.g.:

```
@Data
@JsonInclude(JsonInclude.Include.NON_NULL)
public class UpdateDTO {
  private Long id;

  private JsonNullable<String> name = JsonNullable.undefined();
}
```

And finally, the part to get it working with springdoc-openapi, add a converter configuration class:

```
@Configuration
@Slf4j
public class JsonNullableApiDocModelConvertersConfig {
  @Bean
  ModelConverter jsonNullableModelConverter(ObjectMapperProvider objectMapperProvider) {
    return new JsonNullableModelConverter(objectMapperProvider);
  }

  @RequiredArgsConstructor
  static class JsonNullableModelConverter implements ModelConverter {
    private final ObjectMapperProvider objectMapperProvider;

    @Override
    public Schema<?> resolve(AnnotatedType type, ModelConverterContext context, Iterator<ModelConverter> iterator) {
      var unwrappedType = tryUnwrapJsonNullable(type);
      if (unwrappedType != null) {
        return context.resolve(unwrappedType);
      }

      return iterator.hasNext()
        ? iterator.next().resolve(type, context, iterator)
        : null;
    }

    private AnnotatedType tryUnwrapJsonNullable(AnnotatedType type) {
      var javaType = resolveType(type);

      if (JsonNullable.class.isAssignableFrom(javaType.getRawClass())) {
        return new AnnotatedType()
          .type(javaType.containedType(0))
          .name(type.getName())
          .parent(type.getParent())
          .jsonUnwrappedHandler(type.getJsonUnwrappedHandler())
          .skipOverride(type.isSkipOverride())
          .schemaProperty(type.isSchemaProperty())
          .ctxAnnotations(type.getCtxAnnotations())
          .resolveAsRef(type.isResolveAsRef())
          .jsonViewAnnotation(type.getJsonViewAnnotation())
          .skipSchemaName(type.isSkipSchemaName())
          .skipJsonIdentity(type.isSkipJsonIdentity())
          .propertyName(type.getPropertyName());
      }

      return null;
    }

    private JavaType resolveType(AnnotatedType type) {
      if (type.getType() instanceof JavaType javaType) {
        return javaType;
      }
      else {
        return objectMapperProvider.jsonMapper().constructType(type.getType());
      }
    }
  }
}
```

**Comment by daedrics** [comment]
Hi @duke1995 ,
How does your open api generated class look like after adding this configuration? I'm trying to send PATCH requests from the generated api client but I cannot tell the client to not send the fields that I didn't specify. 
Example:
I have this PatchDTO: 

```
@Schema(name = "PatchDto")
@Getter
@Setter
@NoArgsConstructor
public class PatchDto  {

    @Schema(description = "Voy status code", implementation = VoyStatusCode.class)
    private JsonNullable<VoyStatusCode> voyStatusCode;

    @Schema(description = "Voy Sales", implementation = VoySalesBlocked.class)
    private JsonNullable<VoySalesBlocked> paxSalesBlocked;

   @Schema(description = "Name", implementation = String.class)
    private JsonNullable<String> name;

}
```
When I want to send only the name field the request has also the other two fields as null but I don't want to send them.

**Comment by suchira19** [comment]
I am also having the requirement of distinguishing between a missing field in my request vs a field being explicitly set as null. And Jackson mapper is not working with openapi JsonNullableDeserializer. Has anyone able to resolve this?

**Comment by mschout** [comment]
@daedrics your DTO needs to set a default value of `JsonNullable.undefined()` for each field.
