### ISSUE TITLE
Custom object as query param annotated with @Validated is treated like a part of RequestBody

### ISSUE THREAD

**Issue by Roggired** [springdoc/springdoc-openapi#2513]
**Describe the bug**

Spring Web MVC supports objects of custom classes to be used as query params. The framework maps fields of such object to appropriate query params. `springdoc-openapi` handles this case correctly. However, if controller's argument of custom class is annotated with `@Validated`, `springdoc-openapi` generates the description of this parameter like a part of a request body instead of treating it as query params. 

**To Reproduce**

- `Spring Boot 3.1.3`
- `org.springdoc:springdoc-openapi-starter-webmvc-ui:2.3.0`
- Write a rest controller with following method:
```kotlin
    @PostMapping("/filtered")
    fun getCoursePageFiltered(
        @Validated pageParams: PageParams,
        @Validated @RequestBody request: CoursesFilteredRequest,
    ): PageView<CourseTableInfo> = courseStructureService.getCoursePageFiltered(
        request = request,
        pageParams = pageParams
    ).toView()
```
- Run Spring Boot application and open Swagger UI page in a browser.

**Expected behavior**
Expected the same output like the library generates in case if there is no `@Validated` annotation on `PageParams` method argument.  
![image](https://github.com/springdoc/springdoc-openapi/assets/55298411/03c8bfca-98d5-4c40-a601-0a1d1f243f3e)

**Actual behavior**  
![image](https://github.com/springdoc/springdoc-openapi/assets/55298411/1b441704-3718-4d8c-9975-5ca9e05e1591)

**Comment by bnasslahsen** [comment]
@Roggired,

This issue is similar to #2519
Should be now fixed with the latest SNAPHSOT
