### ISSUE TITLE
Generated schema contains an extra property without set prefix if there is a property starting with set.

### ISSUE THREAD

**Issue by rostanek** [springdoc/springdoc-openapi#2517]
**Describe the bug**

If the object contains a property which name starts with "set", then the generated specification contains also a property with "set" removed.

For example:
```
public class ExampleJson {
    private LocalDate settlement;
    // getters and setters
}
```

Output:
```
"ExampleJson": {
  "type": "object",
  "properties": {
    "tlement": {
      "$ref": "#/components/schemas/ExampleJson"
    }
    "settlement": {
      "type": "string",
      "format": "date"
    }
  }
}
```

**To Reproduce**

- What version of spring-boot you are using? 3.2.3
- What modules and versions of springdoc-openapi are you using? 2.3.0

**Expected behavior**

That extra property without "set" ("tlement" in this example) should not exist in the generated specification.

**Comment by bnasslahsen** [comment]
@rostanek,

Expected behaviour. You can use `@JsonProperty`, to use your own.
Check swagger-core documentation.

**Comment by rostanek** [comment]
I have these annotations:
```
@Schema(name = "settlement")
@JsonProperty("settlement")
```
Can you share a link that describes this expected behaviour? I don't know what swagger-core has to do with this.
