### ISSUE TITLE
text alightment issue in swagger-ui

### ISSUE THREAD

**Issue by wsl206** [springdoc/springdoc-openapi#2521]
**Describe the bug**
Swagger UI has css alignment issue for column Name/Description and Code/Description. This css bug was initially reported and fixed under this issue [1845](https://github.com/springdoc/springdoc-openapi/issues/1854). 

However, the same issue happened again in newer swagger version 4.18.2. As I understand, it seems caused by some css class change in the latest OAS3 UI.

I saw there is a fix for this issue in swagger-ui repo [8963](https://github.com/swagger-api/swagger-ui/pull/8963). But the solution is only applied for version 5.x.
The current spring-doc 1.7.0 is only using swagger-ui 4.18.2, and it's not compatible with swagger-ui 5.x.

May I know if there is any plan to update the spring-doc 1.7.x to support swagger-ui 5.x?

**To Reproduce**
spring-boot : 2.6.6
springdoc-open-ui : 1.7.0
swagger-ui : 4.18.2

**Comment by bnasslahsen** [comment]
springdoc-openapi v1.7.0 is the latest Open Source release supporting Spring Boot 2.x and 1.x.
An extended support for [springdoc-openapi v1](https://springdoc.org/v1) project is now available for organizations that need support beyond 2023.
For more details, feel free to reach out: [sales@springdoc.org](mailto:sales@springdoc.org)

**Comment by wsl206** [comment]
I realised springdoc has released version 1.8.0 recently. Tested on my side, and it seems the CSS alignment issue has been fixed on this latest version. Just FYI.
