### ISSUE TITLE
@Schema description is not added to reference object using springdoc-1.7.0

### ISSUE THREAD

**Issue by bednar2012** [springdoc/springdoc-openapi#2523]
**Describe the bug**

We are trying to use an OpenAPI 3.1.0 [feature](https://spec.openapis.org/oas/v3.1.0#fixed-fields-18) of having `description` next to `$ref` of common component reference object.

<img width="812" alt="image" src="https://github.com/springdoc/springdoc-openapi/assets/30436802/3ef85b7e-c98a-455d-9249-8dd61463e6bd">

It was previously raised in this [ticket](https://github.com/springdoc/springdoc-openapi/issues/2424) with proposed [solution](https://github.com/springdoc/springdoc-openapi/issues/2424#issuecomment-1837235089), but seems like it does not apply to `springdoc-1.7.0`.

**To Reproduce**

Feel free to checkout my `springdoc-openapi-demos` fork where my latest [commit](https://github.com/bednar2012/springdoc-openapi-demos/commit/bea1045071a0a5b778478aa728d12700882418c7) reproduces the issue.
- springdoc version is set to`1.7.0`

I basically added this little change in `Pet` class:
```java
@JsonProperty("category")
@JacksonXmlProperty(localName = "category")
@Schema(description = "category description")
private Category category;

@JsonProperty("otherCategory")
@JacksonXmlProperty(localName = "otherCategory")
@Schema(description = "otherCategory description")
private Category otherCategory;
```
The generated json or yaml definition does not generate proper `description` field.

```yaml
category:
  $ref: '#/components/schemas/Category'
otherCategory:
  $ref: '#/components/schemas/Category'
```

**Expected behavior**

`description` added next to `$ref`:
```yaml
category:
    $ref: '#/components/schemas/Category'
    description: 'category description'
otherCategory:
    $ref: '#/components/schemas/Category'
    description: 'otherCategory description'
```

I tested that on `springdoc-openapi-demos` 2.x branch with `springdoc-2.3.0` where all seems to work just fine.

**Comment by bnasslahsen** [comment]
@bednar2012,

I am answering you execptionnally for v1 springdoc-openapi.
You should use the latest version `springdoc-openapi v1.8.0` which is released lately.


NOTE: springdoc-openapi v1.8.0 is the latest Open Source release supporting Spring Boot 2.x and 1.x.An extended support for springdoc-openapi v1 project is now available for organizations that need support beyond 2023.For more details, feel free to reach out: sales@springdoc.org
