### ISSUE TITLE
Mirgrate from swagger 2 -> spring doc

### ISSUE THREAD

**Issue by ducanh2110** [springdoc/springdoc-openapi#2524]
Dear team, 
I've mirgrated from spring boot 2 -> spring boot 3. Modules: Spring cloud, gateway, zuul, discovery, eureka
In this project  we centralize the document using swagger in Gateway Service and using SwaggerResourceProvider, SwaggerResource to provide the link to the downstream service. And the url in each endpoints will be the domain of gateway-service + route-path of each downstream service + endpoints in each downstream. 
But when we migrated to Spring boot 3 and using springdoc, I've used some guideline from some issues and some suggestions team springdoc suggest in very old topic from 2019-2020. But it just resolve the centralize documents. But the problem is the server generated is always the direct IP of each downstream service. Not through the gateway-service. I've read the document that I need to setup the @OpenAPiDefinition with @Servers to configure each sever we have. 
I want to know that do springdoc team have plan for make it work again? Or alternative solution for our issue?
Thanks so much.

**Comment by bnasslahsen** [comment]
@ducanh2110,

Check the demo setup: https://github.com/springdoc/springdoc-openapi-demos/tree/2.x/demo-microservices/gateway-service

Which is deployed here:
[Demo Spring Boot 3 and Spring Cloud Gateway](https://demos.springdoc.org/demo-microservices/swagger-ui.html)

**Comment by bnasslahsen** [comment]
@ducanh2110,

In the provided sample, there is no IP used. It's based on domains.

**Comment by ducanh2110** [comment]
<img width="591" alt="image" src="https://github.com/springdoc/springdoc-openapi/assets/13704782/8e09046d-db45-4a09-99a9-dcdef4b534d4">
I've used your configuration in demo. But when it generated servers url it show IP @bnasslahsen

**Comment by bnasslahsen** [comment]
@ducanh2110,

All the spring-cloud-gateway configuration is available here:
- https://github.com/springdoc/springdoc-openapi-demos/blob/2.x/demo-microservices/config-service/src/main/resources/config/gateway-service.yml


Only difference in the samples we have a reverse proxy in front of the gateway.

By setting `ProxyPreserveHost On`,we ensure that the original host header from the client's request is preserved when forwarding the request to the backend server.
You can do similar in spring-cloud-gateway by setting `PreserveHostHeader`. But here we out of topic, and it's not anymore springdoc-openapi assitance.

**Comment by ducanh2110** [comment]
Thanks so much for support so enthusiastic @bnasslahsen
