### ISSUE TITLE
Inherited Methods Not Included in Swagger Documentation with @RouterOperation in Spring Boot WebFlux Application

### ISSUE THREAD

**Issue by oms12** [springdoc/springdoc-openapi#2525]
**Describe the bug**

When using **@RouterOperation** to document API endpoints in Spring Boot Webflux applications with springdoc-openapi, the Swagger does not include methods inherited from parent classes. This occurs because internally, **AopUtils.getTargetClass(handlerBean).getDeclaredMethods()** is used, which only retrieves **declared methods**, not methods from **parent classes**.

Because suppose there is a method already implemented in parent class and I don't want to implement that method again in child class and the method implemented in the parentClass is my **beanMethod**.
Since that method is already inherited by the child class it should be child class function also.

**To Reproduce**
1. Specify **@RouterOperation** for an endpoint in a Spring Boot application.
2. Define a method in a subclass that overrides a method from a parent class and parent class method is the beanMethod.
3. Check the generated Swagger documentation.

Spring Boot version: **3**
springdoc-openapi module version:
```
        <dependency>
            <groupId>org.springdoc</groupId>
            <artifactId>springdoc-openapi-starter-webflux-ui</artifactId>
            <version>2.3.0</version>
        </dependency>
```

**Expected behavior**

Swagger documentation should include methods inherited from **parent classes** when using **@RouterOperation**.

**Screenshots**
![image](https://github.com/springdoc/springdoc-openapi/assets/68958316/a81b3213-76e2-4771-b919-97d51934cb27)

**Additional context**
Code where beanClass and beanMethod is used.
```@RouterOperation(path = "v1/payment", method = RequestMethod.POST, beanClass = PaymentHandler.class, beanMethod = "handle", operation = @Operation(description = "Say hello GET", operationId = "lowercaseGET", tags = "persons"))```

**Comment by bnasslahsen** [comment]
@oms12,

Try adding a complete reproducible sample, so we can confirm the fix ?

**Comment by oms12** [comment]
Sure, I will add the one simple code to reproduce the issue.

**Comment by oms12** [comment]
**To Reproduce**
BaseHandler Class
```
package com.example.swagger.Handler;

import org.springframework.stereotype.Component;
import org.springframework.web.reactive.function.server.ServerRequest;
import org.springframework.web.reactive.function.server.ServerResponse;
import reactor.core.publisher.Mono;

@Component
public abstract class BaseHandler {
    protected abstract Mono<ServerResponse> apply (ServerRequest serverRequest);

    public Mono<ServerResponse> handle(ServerRequest serverRequest) {
        return this.apply(serverRequest);
    }
}
```
**GetNameHandlerClass**
```
package com.example.swagger.Handler;

import org.springframework.http.MediaType;
import org.springframework.stereotype.Component;
import org.springframework.web.reactive.function.server.ServerRequest;
import org.springframework.web.reactive.function.server.ServerResponse;
import reactor.core.publisher.Mono;

@Component
public class GetNameHandler extends BaseHandler{
    @Override
    protected Mono<ServerResponse> apply(ServerRequest serverRequest) {
        return ServerResponse.ok()
                .contentType(MediaType.APPLICATION_JSON)
                .bodyValue("Name API is called");
    }

    // Since handle function is present in the BaseHandler class so it is not able to detect but it should

    // Uncommenting below code will work as expected since now explicitly handle is declared here

//    @Override
//    public Mono<ServerResponse> handle(ServerRequest serverRequest) {
//        return super.handle(serverRequest);
//    }
}
```

**Router Class I am using Functional Endpoint**
```
package com.example.swagger.Router;

import com.example.swagger.Handler.GetNameHandler;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import org.springdoc.core.annotations.RouterOperation;
import org.springdoc.core.annotations.RouterOperations;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.http.MediaType;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.reactive.function.server.RequestPredicates;
import org.springframework.web.reactive.function.server.RouterFunction;
import org.springframework.web.reactive.function.server.RouterFunctions;
import org.springframework.web.reactive.function.server.ServerResponse;


@Configuration
public class GetNameRouter {

    @Bean
    @RouterOperations(
            value = {
                    @RouterOperation(path = "/v1/name", produces = {MediaType.APPLICATION_JSON_VALUE}, method = RequestMethod.GET,
                            beanClass = GetNameHandler.class, beanMethod = "handle", operation = @Operation(operationId = "getName",
                            description = "get name", responses = {@ApiResponse(responseCode = "200", description = "OK", content = @Content(schema = @Schema(implementation = String.class)))})
                    )
            })

    public RouterFunction<ServerResponse> routerFunction(GetNameHandler getNameHandler) {
        return RouterFunctions.route(RequestPredicates.GET("/v1/name"), getNameHandler::handle);
    }

}
```
In the GetNameHandler class I am commenting and uncommenting the code, I am getting the results as below.
Hitting this url - **http://localhost:8080/v1/swagger/swagger-ui.html**

**This is the result of keeping the code commented.**
![image](https://github.com/springdoc/springdoc-openapi/assets/68958316/864fa9b0-8831-4bc2-bfda-4578de94fb01)

**This is the result of uncommented code.**
![image](https://github.com/springdoc/springdoc-openapi/assets/68958316/3f213155-177a-452c-b483-caa4418d2b80)

Below is repo link of the simple Spring-Boot working code of above example.
https://github.com/oms12/Swagger

Please clone and check the results I mentioned above.

**Please let me know if anything wrong I am doing or any clarification regarding my code.**
