### ISSUE TITLE
SpringDoc bean naming conflict error with GraphQL Spring boot starter again

### ISSUE THREAD

**Issue by melo0187** [springdoc/springdoc-openapi#2526]
**Describe the bug**
On update to sprindoc 2.4.0 there is a bean conflict for ObjectMapperProvider.

**To Reproduce**

- What version of spring-boot you are using? **3.1.9**
- What modules and versions of springdoc-openapi are you using? **2.4.0**

**Expected behavior**
- Application with spring boot graphql starter and spring doc should have no conflicts and be running.

**Additional context**
Is sort of a regression on #2256 
The change introduced in 2.4.0 to [SpringDocJacksonKotlinModuleConfiguration.java](https://github.com/springdoc/springdoc-openapi/blob/v2.4.0/springdoc-openapi-starter-common/src/main/java/org/springdoc/core/configuration/SpringDocJacksonKotlinModuleConfiguration.java) seems to cause the problem.
Diff [here](https://github.com/springdoc/springdoc-openapi/compare/v2.3.0..v2.4.0#diff-eeb68978c721292695c9b02b3ccdc8c10d6d45b37090d4b29126732144cc5e3c).

**Comment by bnasslahsen** [comment]
Not reproducible.
Feel free to provide a [Minimal, Reproducible Example - with HelloController](https://stackoverflow.com/help/minimal-reproducible-example) that reproduces the problem.

This ticket will be closed, but can be reopened if your provide the reproducible sample.
