### ISSUE TITLE
No static resource swagger-ui/index.html with springdoc 2.4.0

### ISSUE THREAD

**Issue by nvervelle** [springdoc/springdoc-openapi#2528]
**Describe the bug**

On our project, when upgrading from springdoc 2.3.0 to 2.4.0, access to swagger becomes broken.
Using URL http://localhost:8080/swagger-ui/index.html :
* With 2.3.0 : swagger properly displays
* With 2.4.0 : error page

```json
{
  detail: "Internal Server Error",
  exceptionId: "869070aa-2794-454f-9fc7-16c780defc18",
  status: 500,
  timestamp: "2024-03-14T10:05:26.326404836Z",
  title: "Internal Server Error"
}
```

Stack trace :

```json
{
  "timestamp":"2024-03-14T10:05:26.32324657Z",
  "message":"No static resource swagger-ui/index.html.",
  "logger":"xxx.SpringServerErrorHandler",
  "thread":"http-nio-8080-exec-5",
  "level":"ERROR",
  "stack_trace":"
    o.s.w.s.r.NoResourceFoundException: No static resource swagger-ui/index.html.\n\tat 
    o.s.w.s.r.ResourceHttpRequestHandler.handleRequest(ResourceHttpRequestHandler.java:585)\n\tat 
    o.s.w.s.m.HttpRequestHandlerAdapter.handle(HttpRequestHandlerAdapter.java:52)\n\tat 
    o.s.w.s.DispatcherServlet.doDispatch(DispatcherServlet.java:1089)\n\tat 
    o.s.w.s.DispatcherServlet.doService(DispatcherServlet.java:979)\n\tat 
    o.s.w.s.FrameworkServlet.processRequest(FrameworkServlet.java:1014)\n\tat 
    o.s.w.s.FrameworkServlet.doGet(FrameworkServlet.java:903)\n\tat j.s.http.HttpServlet.service(HttpServlet.java:564)\n\tat 
    o.s.w.s.FrameworkServlet.service(FrameworkServlet.java:885)\n\tat j.s.http.HttpServlet.service(HttpServlet.java:658)\n\tat 
    o.a.c.c.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:205)\n\tat 
    o.a.c.c.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)\n\tat o.a.t.w.s.WsFilter.doFilter(WsFilter.java:51)\n\tat 
    o.a.c.c.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174)\n\tat 
    o.a.c.c.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)\n\tat 
    o.s.w.f.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:101)\n\tat 
    o.a.c.c.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174)\n\tat 
    o.a.c.c.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)\n\tat 
    o.s.w.f.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)\n\tat 
    o.s.w.f.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)\n\tat 
    o.a.c.c.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174)\n\tat 
    o.a.c.c.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)\n\tat 
    o.s.w.f.FormContentFilter.doFilterInternal(FormContentFilter.java:93)\n\tat 
    o.s.w.f.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116)\n\tat 
    o.a.c.c.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174)\n\tat 
    o.a.c.c.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149)\n\tat 
    o.s.w.f.ServerHttpObservationFilter.doFilterInternal(ServerHttpObservationFilter.java:109)\n\tat 
    o.s.w.f.OnceP...\n",
  "process.id":"869070aa-2794-454f-9fc7-16c780defc18"
}
```

**To Reproduce**

- What version of spring-boot you are using : 3.2.2
- What modules and versions of springdoc-openapi are you using : runtimeOnly("org.springdoc:springdoc-openapi-starter-webmvc-ui")
- What is the actual and the expected result using OpenAPI Description (yml or json)?
- Provide with a sample code (HelloController) or Test that reproduces the problem : sorry, I didn't extract a sample

**Expected behavior**

- A clear and concise description of what you expected to happen : display properly swagger-ui with the openapi specification
- What is the expected result using OpenAPI Description (yml or json)?

**Additional context**
It may be related to problems on swagger-ui 5.11.8 ([issue](https://github.com/swagger-api/swagger-ui/issues/9645)) but the description of the problem is different.

**Comment by bnasslahsen** [comment]
@nvervelle,

Not reproducible.
Feel free to provide a [Minimal, Reproducible Example - with HelloController](https://stackoverflow.com/help/minimal-reproducible-example) that reproduces the problem.

This ticket will be closed, but can be reopened if your provide the reproducible sample.

**Comment by madduci** [comment]
I'm experiencing the same Problem with SpringBoot 3.2.4 and SpringDoc 2.4.0. The `/v3/api-docs` endpoint works, but the `/swagger-ui/` isn't.

I've built a minimum example demonstrating the issue, here: https://github.com/madduci/springdoc-springboot-bug

**Comment by nvervelle** [comment]
Hi @bnasslahsen . Can the issue be reopened as an example as been provided demonstrating the problem ?

**Comment by bnasslahsen** [comment]
@nvervelle,

The issue is not reproducible:
<img width="1487" alt="image" src="https://github.com/springdoc/springdoc-openapi/assets/13404829/9a3dfbd0-5da5-4f63-afa3-2e5ce42b70dd">

**Comment by nvervelle** [comment]
@bnasslahsen 

Argh, you mean with the provided sample, you do not reproduce ?
Can you tell me on which OS you tested ? On my side, the problem occurs on Linux (Ubuntu for my development computer, oracle java image for production)

**Comment by bnasslahsen** [comment]
<img width="1068" alt="image" src="https://github.com/springdoc/springdoc-openapi/assets/13404829/525f76bd-21e3-4fed-880e-0338bd185822">

**Comment by nvervelle** [comment]
@bnasslahsen , given the differences depending on the OS we tested with our own application, running on docker compose locally :
* I'm on Linux Ubuntu : the swagger ui fails to display
* A colleague of mine is on Mac OS X : the swagge ui displays correctly

Have you the ability to test on Linux or Windows ?

**Comment by bnasslahsen** [comment]
@nvervelle,

It's all deployed on Linux https://springdoc.org/#demos

**Comment by nvervelle** [comment]
OK :thinking:

**Comment by madduci** [comment]
Update: with the 2.5.0 Version, it works for me again! Thank you @bnasslahsen

**Comment by petertogara** [comment]
For Spring Boot 3+ :
Use the [springdoc-openapi-starter-webmvc-ui](https://mvnrepository.com/artifact/org.springdoc/springdoc-openapi-starter-webmvc-ui) dependency

```
<dependency>
  <groupId>org.springdoc</groupId>
  <artifactId>springdoc-openapi-starter-webmvc-ui</artifactId>
  <version>2.0.3</version>
</dependency>
```

For Spring Boot 2:
Use [springdoc-openapi-ui](https://mvnrepository.com/artifact/org.springdoc/springdoc-openapi-ui) dependency:

```
<dependency>
  <groupId>org.springdoc</groupId>
  <artifactId>springdoc-openapi-ui</artifactId>
  <version>1.6.15</version>
</dependency>
```

**Comment by anhefti** [comment]
I still have this problem with:

```
<parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>3.3.2</version>
    </parent>
......
  <dependency>
            <groupId>org.springdoc</groupId>
            <artifactId>springdoc-openapi-starter-webmvc-ui</artifactId>
            <version>2.6.0</version>
        </dependency>
```

Java 17 on Windows 10. /v3/api-docs endpoint works, but the /swagger-ui/ doesn't.

**Comment by annstriganova** [comment]
https://github.com/springdoc/springdoc-openapi/issues/2528#issuecomment-2154283503 + adding `<useJakartaEe>true</useJakartaEe>` to each configuration of `openapi-generator-maven-plugin` solved the problem for me.

**Comment by erikvasilyan** [comment]
For me fixed just by changing version 2.6.0 to 2.1.0

**Comment by Lucas-Angelo** [comment]
> adding `<useJakartaEe>true</useJakartaEe>` to each configuration of `openapi-generator-maven-plugin` solved the problem for me.

me too

**Comment by Lucas-Angelo** [comment]
for spring boot 3 use 2.1.0

that solve my problem, 2.6.0 or anyone else return error "No static resource..."

```
<dependency>
        <groupId>org.springdoc</groupId>
        <artifactId>springdoc-openapi-starter-webmvc-ui</artifactId>
        <version>2.1.0</version>
 </dependency>
```

**Comment by DiegoYegros** [comment]
In my case, it didn't work with springdoc-openapi-starter-webmvc-ui 2.0.3, 2.1.0 and 2.6.0, but it did work with 2.2.0 -- I'm running Ubuntu 24.04, JDK 21 and 

```
<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>3.3.4</version>
		<relativePath/>
	</parent>
```

**Comment by cerib33** [comment]
In my case, it doesn't work with springdoc-openapi-starter-webmvc-ui 2.0.2, 2.1.0, 2.4.0 and 2.6.0
I'm using spring-security with csrf activated
spring-boot-starter-parent 3.3.3
Windows11, JDK 17

Path 	/app/swagger-ui/index.html
Error	Not Found
Status	404
Message	No static resource swagger-ui/index.html.

application.properties
springdoc.swagger-ui.csrf.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html

**Comment by mwhitis** [comment]
Same problem here 

Switching to 2.1.0 also worked for me like @Lucas-Angelo  suggested. This is a new app from start.spring.io today.

Spring boot starter parent 3.3.4
Mac Sonoma 14.7
JDK OpenJdk 22.0.2

**Comment by AsLi-IN** [comment]
@mwhitis Try using this url : http://localhost:8080/webjars/swagger-ui/index.html#/

**Comment by cerib33** [comment]
I did as recommended by @dhernape : Intellij IDEA try to invalidate caches and mvn clean install
I also cleared my maven local repo to force maven to reimport all needed
I shifted Spring Boot from 3.3.3 to 3.3.4, and springdoc-openapi-starter-webmvc-ui from 2.4.0 to 2.6.0
Conclusion: unfortunately it still doesn't work, always the same error

Path /app/swagger-ui/index.html
Error Not Found
Status 404
Message No static resource swagger-ui/index.html.

**Comment by cerib33** [comment]
@dhernape : /app is my application context path
application.properties/yaml:
server.servlet.context-path=/app

docs.spring.io:
server.context-path= # the context path, defaults to '/'

I tried without context-path ("/") : still fails
on the other hand, "/v3/api-docs" has always worked well

after all these attempts, I will start again from a new simple project via spring-initializr, I will be able to compare ...

**Comment by holyjacobes** [comment]
Hey,

try to define in your pom.xml both needed dependecies explicitly:      
```
         <dependency>
            <groupId>org.springdoc</groupId>
            <artifactId>springdoc-openapi-starter-webmvc-api</artifactId>
            <version>2.6.0</version>
        </dependency>
```

```
        <dependency>
          <groupId>org.springdoc</groupId>
          <artifactId>springdoc-openapi-starter-webmvc-ui</artifactId>
          <version>2.6.0</version>
        </dependency>
```

**Comment by cerib33** [comment]
Hey @holyjacobes 
Of course that's what I do every time :)

anyway my problem was elsewhere: my webapp was already using a WebMvcConfigurationSupport configuration before migration, and when moving to SpringBoot 3 and SpringSecurity 6.3.3 it was necessary to add a resource handler for swagger:
registry.addResourceHandler("/swagger-ui*/**")...
thanks for your advice

**Comment by hareshramasamy** [comment]
I am using Spring boot 3.3.4, and springdoc-openapi-starter-webmvc-api version 2.6.0, and I am facing the exact same issue as @cerib33  where the /swagger-ui/index.html, or the /swagger-ui.html does not work, but the /v3/api-docs works. Do let me know if there are any solutions to this issue! Thanks!

**Comment by cerib33** [comment]
Hi @hareshramasamy ,
did you tried to add WebMvcConfigurationSupport with SwaggerIndexTransformer ?

this works for /swagger-ui/index.html url

```
@Configuration
@RequiredArgsConstructor
public class WebMvcConfig extends WebMvcConfigurationSupport {

    private final SwaggerIndexTransformer swaggerIndexTransformer;

    final String[] swaggerLocations = {"/swagger-ui*/**"};

    @Override
    protected void addResourceHandlers (ResourceHandlerRegistry registry) {
        registry.addResourceHandler(swaggerLocations)
                .addResourceLocations("classpath:/META-INF/resources/webjars/")
                .resourceChain(false)
                .addTransformer(swaggerIndexTransformer);
    }
}
```

**Comment by chanchobrujo** [comment]
> @mwhitis Try using this url : http://localhost:8080/webjars/swagger-ui/index.html#/. This additional /webjars/ started working for me on webflux-ui

ADD webjars
It works for my http://localhost:8080/webjars/swagger-ui/index.html#/

**Comment by BOURGUI07** [comment]
> Had the same problem just now with Spring Boot 3.3.4
> 
> ```
>         <dependency>
>             <groupId>org.springdoc</groupId>
>             <artifactId>springdoc-openapi-starter-webmvc-ui</artifactId>
>             <version>2.6.0</version>
>         </dependency>        
> ```
> 
> If you are using Intellij IDEA try to invalidate caches and mvn clean install. That solved my issue. Both `/swagger-ui/index.html` and `/v3/api-docs` work It wont redirect if you use `/swagger-ui` though.


This solved my problem! Thank you!

**Comment by brunohenriquecontente** [comment]
I solved this problem:

I updated spring version to <version>3.4.1</version>
And I used this dependences:

              ```
  <dependency>
			<groupId>org.springdoc</groupId>
			<artifactId>springdoc-openapi-starter-webmvc-ui</artifactId>
			<version>2.8.0</version>
		</dependency>
		<dependency>
			<groupId>org.springdoc</groupId>
			<artifactId>springdoc-openapi-starter-webmvc-api</artifactId>
			<version>2.8.0</version>
		</dependency>
```

**Comment by sasidhar-chittumuru-jemmic** [comment]
I had similar issue, but finally I make it work with the following combination: 

spring boot version: 3.4.1
<dependency>
			<groupId>org.springdoc</groupId>
			<artifactId>springdoc-openapi-starter-webmvc-ui</artifactId>
			<version>2.7.0</version>
		</dependency>

both v3/api-docs and swagger-ui/index.html endpoints are working as expected.

**Comment by sasi040** [comment]
I had similar issue, but finally I make it work with the following combination:

spring boot version: 3.4.1

<dependency>
			<groupId>org.springdoc</groupId>
			<artifactId>springdoc-openapi-starter-webmvc-ui</artifactId>
			<version>2.7.0</version>
		</dependency>

both v3/api-docs and swagger-ui/index.html endpoints are working as expected.

**Comment by Youssef-Elouasbi** [comment]
@sasi040 
Please can you help me i did the same combination 
spring boot version 3.4.1 and :

```
<dependency>
			<groupId>org.springdoc</groupId>
			<artifactId>springdoc-openapi-starter-webmvc-ui</artifactId>
			<version>2.7.0</version>
		</dependency>
```

the v3/api-docs  work , but the swagger-ui/index.html  not :(

**Comment by sasidhar-chittumuru-jemmic** [comment]
@Youssef-Elouasbi  

Do you see any errors in the logs during start up ? I did not do anything special other than using these dependencies.

**Comment by Youssef-Elouasbi** [comment]
Thank you for your reply @sasidhar-chittumuru-jemmic 
I have fix the issue i did this steps but i am not sure what was the problem 

- I have run my db (PostgreSQL)
- I have run my docker for mailing service
- And i have turn off my PC then turn it on

this the version i use now :

```
<groupId>org.springframework.boot</groupId>
<artifactId>spring-boot-starter-parent</artifactId>
<version>3.4.1</version>
```

```
<dependency>
	<groupId>org.springdoc</groupId>
	<artifactId>springdoc-openapi-starter-webmvc-ui</artifactId>
	<version>2.8.0</version>
</dependency>
```

**Comment by jmpachonv** [comment]
Just in case this works for someone,

I updated versions in my project as follow:

SpringBoot: 3.4.2
springdoc-openapi-starter-webmvc-ui: 2.8.0
springdoc-openapi-starter-webmvc-api: 2.8.0

This worked for me.

**Comment by OhTheThree777** [comment]
> Had the same problem just now with Spring Boot 3.3.4
> 
> ```
>         <dependency>
>             <groupId>org.springdoc</groupId>
>             <artifactId>springdoc-openapi-starter-webmvc-ui</artifactId>
>             <version>2.6.0</version>
>         </dependency>        
> ```
> 
> If you are using Intellij IDEA try to invalidate caches and mvn clean install. That solved my issue. Both `/swagger-ui/index.html` and `/v3/api-docs` work It wont redirect if you use `/swagger-ui` though.

this worked   spring boot 3.3.6 and 2.6.0 both url are ok

**Comment by yas1th** [comment]
Invalidating the cache in Intellij Worked for me. 

Below steps helped me to invalidate the cache in Intellij

- Click on Help
- Click on Find Action
- Search for Invalidate Cache
- Click on Invalidate & Cache
- IDE gets restarted
- Build the project
- Run the application
