### ISSUE TITLE
get a big binary response when access /api-docs API

### ISSUE THREAD

**Issue by xuxiaojing2004** [springdoc/springdoc-openapi#2532]
**Describe the bug**

In a couple of our web applications, when we try to access the api docs, instead of getting a json document, we are getting a big binary data in the response. What could be the possible cause of such issue?

From our investigation, it seems it's related to MappingJackson2HttpMessageConverter.
In one application, the issue is solved by removing MappingJackson2HttpMessageConverter from converter list.
<mvc:annotation-driven >
        <mvc:message-converters register-defaults="true">
            <bean class="org.springframework.http.converter.StringHttpMessageConverter"/>
            <bean class="org.springframework.http.converter.json.MappingJackson2HttpMessageConverter">
                <property name="objectMapper" ref="jacksonObjectMapper" />
            </bean>
        </mvc:message-converters>
    </mvc:annotation-driven>
 MappingJackson2HttpMessageConverter interferes with ByteArrayHttpMessageConverter. 

But in another application, I am getting an exception when I remove the converter from 
 <bean class="org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter">
        <property name="messageConverters">
            <list>
                <ref bean="stringMessageConverter" />
                <ref bean="jackson2HttpMessageConverter"/>
            </list>
        </property>
    </bean>

**To Reproduce**

- What version of spring-boot you are using? Spring Boot 3.2.1
- What modules and versions of springdoc-openapi are you using? 2.4.0
- What is the actual and the expected result using OpenAPI Description (yml or json)?
- Provide with a sample code (HelloController) or Test that reproduces the problem

**Expected behavior**

- A clear and concise description of what you expected to happen.
- What is the expected result using OpenAPI Description (yml or json)?

**Screenshots**

**Additional context**

**Comment by codespearhead** [comment]
We need an [MRE](https://en.wikipedia.org/wiki/Minimal_reproducible_example#:~:text=In%20computing%2C%20a%20minimal%20reproducible,to%20be%20demonstrated%20and%20reproduced.) and more information about that "binary data".
