### ISSUE TITLE
Mispel in SpringRepositoryRestResourceProvider

### ISSUE THREAD

**Issue by marcuss** [springdoc/springdoc-openapi#2536]
I'm pretty sure this is an error:
https://github.com/springdoc/springdoc-openapi/blob/2db978a3983e1fc07d54e8902f7ddf428bb34407/springdoc-openapi-starter-common/src/main/java/org/springdoc/core/providers/SpringRepositoryRestResourceProvider.java#L95

**Comment by codespearhead** [comment]
Seems like it. I've just submitted a PR.
