### ISSUE TITLE
1.8.0 has transitive slf4j 2.0 dependency

### ISSUE THREAD

**Issue by stolyarchukav** [springdoc/springdoc-openapi#2543]
1.8.0 version has a transitive slf4j 2.0.9 dependency which does not work properly with Spring Boot 2.7.x, see https://github.com/spring-projects/spring-boot/issues/12649

**Comparative dependency graphs**
1.8.0
\--- io.swagger.core.v3:swagger-core:2.2.20
|    |    |         +--- jakarta.xml.bind:jakarta.xml.bind-api:2.3.3
|    |    |         |    \--- jakarta.activation:jakarta.activation-api:1.2.2
|    |    |         +--- org.apache.commons:commons-lang3:3.14.0
|    |    |         +--- org.slf4j:slf4j-api:2.0.9

1.7.0
\--- io.swagger.core.v3:swagger-core:2.2.9
|    |    |         +--- jakarta.xml.bind:jakarta.xml.bind-api:2.3.2
|    |    |         |    \--- jakarta.activation:jakarta.activation-api:1.2.1
|    |    |         +--- org.apache.commons:commons-lang3:3.12.0 -> 3.14.0
|    |    |         +--- org.slf4j:slf4j-api:1.7.36

**Comment by codespearhead** [comment]
Spring Boot 2.x is [EOL for OSS support and it won't be long until commercial support is dropped as well](https://endoflife.date/spring-boot).

**Comment by stolyarchukav** [comment]
> Spring Boot 2.x is [EOL for OSS support and it won't be long until commercial support is dropped as well](https://endoflife.date/spring-boot).

I thought 2.0.x versions should be based on Spring Boot 3, but 1.x line should keep Spring Boot 2 compatibility. Am I wrong?

**Comment by codespearhead** [comment]
Correct, but the readme of this project says there will be no more OSS support for version 1.x. However, commercial support is available.

**Comment by bnasslahsen** [comment]
@stolyarchukav,

The version used for slf4j will be `org.slf4j:slf4j-api:jar:1.7.36`

If you are having something else, make sure you provide [Minimal, Reproducible Example - with HelloController](https://stackoverflow.com/help/minimal-reproducible-example) that reproduces the problem

**Comment by blulic** [comment]
Confirming the issue @bnasslahsen @codespearhead. This is not an invalid issue. Dependency chain is very clear.

Upgrading SpringDoc to 1.8.0 in any Spring Boot 2.7.x project will make SLF4J unusable.

Latest io.swagger.core.v3:swagger-core version with SLF4J 1.7 is [2.2.16](https://mvnrepository.com/artifact/io.swagger.core.v3/swagger-core/2.2.16).  
[swagger-core 2.2.17](https://mvnrepository.com/artifact/io.swagger.core.v3/swagger-core/2.2.17) is on SLF4J 2.0.9 (it is not nice to introduce a breaking change in the patch version).

springdoc-openapi-common brings swagger-core [2.2.20](https://mvnrepository.com/artifact/org.springdoc/springdoc-openapi-common/1.8.0). [ Source link](https://github.com/springdoc/springdoc-openapi/blob/v1.8.0/pom.xml#L69).

 I can make a contribution for 1.8.1 if you would consider publishing it? Thanks a lot!
