### ISSUE TITLE
Not able to view browse button on swagger UI

### ISSUE THREAD

**Issue by shivgit87** [springdoc/springdoc-openapi#2544]
**Describe the bug**

- I am using following open-api specification
openapi: '3.0.1'
info:
  title: 'decisions'
  version: '#project.version#'
  description: xyz
servers:
  - url: http://localhost:8080/
    description: Local server
 
paths:
  /decisions/rule/upload:
    post:
      tags:
        - camunda-rule-config
      operationId: ruleUpload
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                files:
                  type: string
                  format: binary

Iam not getting as expected browse button for the above API.

I am using following dependency

<dependency>
			<groupId>org.springdoc</groupId>
			<artifactId>springdoc-openapi-starter-webflux-ui</artifactId>
			<version>2.3.0</version>
		</dependency>
		
<plugin>
				<groupId>org.openapitools</groupId>
				<artifactId>openapi-generator-maven-plugin</artifactId>
				<version>7.2.0</version>

</plugin>
					
I see following in swagger 

![image](https://github.com/springdoc/springdoc-openapi/assets/43037848/c8e5147b-c910-4cee-aeb2-8b91f92cf448)

It automatically converts to type:file
                                               Array.
                                               
this is the i/p method in controller (Autogenerated)

@RequestMapping(
        method = {RequestMethod.POST},
        value = {"/decisions/rule/upload"},
        produces = {"application/json"},
        consumes = {"multipart/form-data"}
    )
    default Mono<ResponseEntity<DeploymentWithDefinitions>> ruleUpload(@Parameter(name = "file",description = "") @RequestPart(value = "file",required = false) Flux<Part> file, @Parameter(hidden = true) final ServerWebExchange exchange) {
        return this.getDelegate().ruleUpload(file, exchange);
    }                                               
                                               

**To Reproduce**

use the above dependency 
- Use Upload API specification for 3.0.1

**Expected behavior**

- Browse button should appear in Swagger UI

**Screenshots**
Browse button to upload files.

**Comment by codespearhead** [comment]
What do you mean by "browse button"?

**Comment by shivgit87** [comment]
Browse button means , button to upload the file. Attaching screenshot for reference.

![image](https://github.com/springdoc/springdoc-openapi/assets/43037848/6403abcc-4295-46b8-916a-e5474f167fab)

**Comment by codespearhead** [comment]
As per #1615 , I just tried with the endpoint below and it worked as expected.

```java
import org.springframework.http.MediaType;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RestController;
import org.springframework.web.multipart.MultipartFile;

@RestController
public class FileUploadController {

    @PostMapping(value = "/", consumes = MediaType.MULTIPART_FORM_DATA_VALUE)
    public String handleFileUpload(@RequestBody final MultipartFile file) {
        String fileName = file.getOriginalFilename();
        return "You successfully uploaded " + fileName + "!";
    }
}
```

If that works for you, can you close this issue?

**Comment by shivgit87** [comment]
Hello My Code is different , As I am using webflux-ui dependency following code is generated for me i.e.

It takes (@Valid @RequestPart(value = "file",required = false) Flux<Part> file   as i/p for file upload. ( This api works fine with Postman.) Just sharing you method signature below :- .

    default Mono<ResponseEntity<DeploymentWithDefinitions>> ruleUpload(@ApiParam("APIM subscription key") @RequestHeader(value = "Ocp-Apim-Subscription-Key",required = false) String ocpApimSubscriptionKey, @ApiParam("") @Valid @RequestPart(value = "file",required = false) Flux<Part> file, @ApiIgnore ServerWebExchange exchange) {
        return this.getDelegate().ruleUpload(ocpApimSubscriptionKey, file, exchange);
    }

**Comment by shivgit87** [comment]
Let me know if you need more information on this.

**Comment by bnasslahsen** [comment]
@shivgit87,

Try using the latest [SNAPSHOT](https://springdoc.org/#how-can-i-use-the-last-springdoc-openapi-snapshot) where the `swagger-ui `has been upgraded.

If you are still facing the issue, then provide a [Minimal, Reproducible Example - with HelloController](https://stackoverflow.com/help/minimal-reproducible-example) that reproduces the problem
