### ISSUE TITLE
Spring Doc Sending OAuth Client Id as a Header

### ISSUE THREAD

**Issue by NirmalmaheshSubramani** [springdoc/springdoc-openapi#2545]
**Describe the bug**

The Swagger UI is sending client_id and client_secret in the headers ( Basic Authentication ) instead of sending it in the request body

**To Reproduce**

Here is the code I am using, The expectation is to have the client_id and the token to be send in the request body but it is send as a header.

private static final String OAUTH_SCHEME = "auth";

@Value("${spring.security.oauth2.resourceserver.jwt.issuer-uri}")
String authURL;

@Bean
public OpenAPI customizeOpenAPI() {
    return new OpenAPI()
            .addSecurityItem(new SecurityRequirement()
                    .addList(OAUTH_SCHEME))
            .components(new Components()
                    .addSecuritySchemes(OAUTH_SCHEME, createOAuthScheme()))
            .addSecurityItem(new SecurityRequirement().addList(OAUTH_SCHEME));
}

private SecurityScheme createOAuthScheme() {
    return new SecurityScheme().type(SecurityScheme.Type.OAUTH2).flows(createOAuthFlows());
}

private OAuthFlows createOAuthFlows() {
    final var oauthFlow = new OAuthFlow()
            .authorizationUrl(authURL + "/protocol/openid-connect" + "/auth")
            .refreshUrl(authURL + "/protocol/openid-connect" + "/token")
            .tokenUrl(authURL + "/protocol/openid-connect" + "/token")
            .scopes(new Scopes());
    return new OAuthFlows().authorizationCode(oauthFlow);
}

**Expected behavior**

The client_id and client_secret is expected to be present in the request body

**Comment by bnasslahsen** [comment]
@NirmalmaheshSubramani,

springdoc-openapi is built on top of `swagger-ui`.
If you believe the swagger-ui is sending the parameters wrong, report it to the swagger-ui project instead.
