### ISSUE TITLE
Vulnerability issue in spring boot `3.2.3`

### ISSUE THREAD

**Issue by dmmax** [springdoc/springdoc-openapi#2546]
In spring boot dependencies we do have a vulnerability issue: https://security.snyk.io/vuln/SNYK-JAVA-ORGSPRINGFRAMEWORK-6444790

It is fixed in the spring boot `3.2.4`

**Comment by codespearhead** [comment]
Can you [link this issue to that PR](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue) ( #2547 )?

**Comment by dmmax** [comment]
@codespearhead done

**Comment by codespearhead** [comment]
@dmmax Can you close this issue now that a duplicate PR ( #2538 ) was merged via commit #1ea110b4a5febeaf9e432ea357365a577ff39da4 ?

**Comment by bnasslahsen** [comment]
@dmmax,

Read the [security policy](https://github.com/springdoc/springdoc-openapi/blob/e8f5f12494d622bcb4a012692d3c20ea778030bc/SECURITY.md),
