### ISSUE TITLE
Example value for some methods is not presented properly in 2.4.0

### ISSUE THREAD

**Issue by avicentic** [springdoc/springdoc-openapi#2548]
**Describe the bug**

- In version 2.4.0 on some POST methods Example value is not presented as a structured json file with initial values. In version 2.3.0 everything works well.

**To Reproduce**

- Spring-boot version 3.2.3
- springdoc-openapi version 2.4.0
- Unfortunately, I cannot reproduce issue in a small demo project. It appears in production project that I cannot share.

**More details**

- Function in Rest controller is:
`@PostMapping(value = "/authenticate")
    public ResponseEntity<AuthenticateResponse> authenticate(HttpServletRequest request, @RequestBody AuthenticateRequest authenticateRequest) {
        AuthenticateResponse authenticateResponse = authService.authenticate(authenticateRequest, httpRequestUtil.getClientIP(request));
        return new ResponseEntity<>(authenticateResponse, HttpStatus.OK);
    }`
- AuthenticateRequest object is:
`@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class AuthenticateRequest {
    private String ou;
    private String username;
    private String password;
    private TokenGrantType grantType;
    private String refreshToken;
}
`
On swagger page schema for request body is presented properly:
![image](https://github.com/springdoc/springdoc-openapi/assets/3864783/678fd91d-a2c3-4d67-aaf8-59c10483db2f)
but example value is dummy "string":
![image](https://github.com/springdoc/springdoc-openapi/assets/3864783/ee6a94a0-9586-4579-9923-9343d8ad3866)

With springdoc-openapi version 2.3.0 example value is presented as a valid json object:
![image](https://github.com/springdoc/springdoc-openapi/assets/3864783/e70b4bc4-f888-4e8b-819a-e40882dd8b76)

Surprisingly, I have same issue with all rest methods within one controller file. Methods from another controller files has valid examples for request body's.

**Comment by noshua** [comment]
Just noticed the same bug, all POSTs are affected. PUT, PATCH and GET are fine.

**Comment by stalinone** [comment]
I noticed this issue as well. 

Additional info:
* Service with many controllers/endpoints cannot show POST request body schema
* Service with few controllers is able to show schemas.

The api-docs JSON is semantically the same.

Not sure if this is related to #2538. I cannot override library version as said.

**Comment by bnasslahsen** [comment]
@stalinone,

Try using The [latest SNAPSHOT](https://springdoc.org/#how-can-i-use-the-last-springdoc-openapi-snapshot) where the swagger-ui has been upgraded.

**Comment by avicentic** [comment]
@bnasslahsen I could confirm that bug is fixed in snapshot version.

**Comment by chaouki-reply** [comment]
@bnasslahsen Sorry to jump here in the discussion, Is there a plan for a release soon?

**Comment by bnasslahsen** [comment]
Hopefully by the end of the month

**Comment by chaouki-reply** [comment]
@bnasslahsen Great, looking forward to it!
