### ISSUE TITLE
The annotation Schema's description is duplicated in child level

### ISSUE THREAD

**Issue by wsl206** [springdoc/springdoc-openapi#2550]
**Describe the bug**

I have a simple MainObject.java and ChildObject.java. The MainObject will contains a Map of ChildObject values. Below is the sample code.
```
@Data
@Accessors(chain = true)
@JsonInclude(JsonInclude.Include.NON_NULL)
public class MainObject {

    @Schema(description = "Just some description")
    private Map<String, ChildObject> mapOfChildObjects;
}
```
```
@Data
@JsonInclude(JsonInclude.Include.NON_NULL)
@Accessors(chain = true)
public class ChildObject {

    private String field1;
    private String field2;

}
```

In the swagger, I would assume the description will be applied on the MainObject's mapOfChildObjects level only. However, it seems like the description is duplicated to ChildObject too.

<img width="821" alt="image" src="https://github.com/springdoc/springdoc-openapi/assets/21182307/a2430ea1-95a5-48b6-8515-4f06d88e2d68">

I'm able to avoid this issue if I set a description for the ChildObject schema. But this means I need to set description to all the existing class to avoid such duplication, which is a hassle and not right.

Besides that, I'm understand we also can use ArraySchema annotation to solve the description duplicate issue, only if the object is an Array/List. In my case, it is not.

Hence, I'm stuck at here. Please do advise.

**To Reproduce**
spring-boot : 2.6.6
springdoc-open-ui : 1.8.0

**Expected behavior**
The description of a Schema shouldn't be duplicated to the child object.

**Screenshots**

**Comment by bnasslahsen** [comment]
NOTE: springdoc-openapi v1.8.0 is the latest Open Source release supporting Spring Boot 2.x and 1.x.An extended support for springdoc-openapi v1 project is now available for organizations that need support beyond 2023.For more details, feel free to reach out: [sales@springdoc.org](mailto:sales@springdoc.org)
