### ISSUE TITLE
Unable to determine if it is a Kotlin type

### ISSUE THREAD

**Issue by mymx2** [springdoc/springdoc-openapi#2556]
**Unable to determine if it is a Kotlin type**

- method: SpringDocKotlinConfiguration.nullableKotlinRequestParameterCustomizer
- lineNum: 78
![image](https://github.com/springdoc/springdoc-openapi/assets/32814920/296d1c0c-a5f1-4494-a2f5-15743a6e02ff)

**To Reproduce**

- What version of spring-boot you are using?
  - 3.2.4
- What modules and versions of springdoc-openapi are you using?
  - 2.4.0
- What is the actual and the expected result using OpenAPI Description (yml or json)?
  - kotlin type isMarkedNullable
- Provide with a sample code (HelloController) or Test that reproduces the problem
```
interface AdminSysNoticePage {

  @Operation(summary = "adminSysNoticePage", description = "adminSysNoticePage")
  @GetMapping("adminSysNoticePage")
  fun adminSysNoticePage(
    @Validated request: AdminSysNoticePageRequest
  ): AdminSysNoticePageResponse
}

@Schema(description = "AdminSysNoticePageRequest")
data class AdminSysNoticePageRequest(

  @field:Schema(description = "id not required", example = "")
  var id: Long? = null,

  @field:Schema(description = "noticeTitle is required", example = "")
  var noticeTitle: String,
)

@Schema(description = " AdminSysNoticePageResponse")
data class AdminSysNoticePageResponse(

  @field:Schema(description = "id is required", example = "")
  var id: Long,

  @field:Schema(description = "updateBy is not required", example = "")
  var updateBy: String? = null,
)

```

**Screenshots**
- wrong: KotlinDetector.isKotlinType(methodParameter.parameterType)
![image](https://github.com/springdoc/springdoc-openapi/assets/32814920/74d60053-a6ef-4c98-a1e2-9c263339bfa9)

- right: KotlinDetector.isKotlinType(methodParameter.containingClass)
![image](https://github.com/springdoc/springdoc-openapi/assets/32814920/258b85cd-7f1e-4d4b-b6b9-a22f0e88a42c)

- fix: KotlinDetector.isKotlinType(methodParameter.containingClass)
![image](https://github.com/springdoc/springdoc-openapi/assets/32814920/62eacf9c-2e67-4c1d-9373-1476214eaddd)

is this fix code right?

**Additional context**
id dont know what fix use `methodParameter.toKParameter() `?

**Comment by codespearhead** [comment]
Can you make a PR and [link this issue to it](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue)?

**Comment by bnasslahsen** [comment]
@mymx2,

See the follwing tests:
https://github.com/springdoc/springdoc-openapi/blob/1ca8bc55da09660a8b6132b7271fc4e798732d52/springdoc-openapi-tests/springdoc-openapi-kotlin-webmvc-tests/src/test/kotlin/test/org/springdoc/api/app9/DemoController.kt#L21-L71

Tests are following the test cases described here:
- https://github.com/springdoc/springdoc-openapi/issues/2185

If you see any case, not respected, make sure you update the test and we can consider it.

**Comment by mymx2** [comment]
> @mymx2,
> 
> See the follwing tests:
> 
> https://github.com/springdoc/springdoc-openapi/blob/1ca8bc55da09660a8b6132b7271fc4e798732d52/springdoc-openapi-tests/springdoc-openapi-kotlin-webmvc-tests/src/test/kotlin/test/org/springdoc/api/app9/DemoController.kt#L21-L71
> 
> Tests are following the test cases described here:
> 
> * [Fix behaviuor of required flag for schema class fields. #2185](https://github.com/springdoc/springdoc-openapi/issues/2185)
> 
> If you see any case, not respected, make sure you update the test and we can consider it.

ok，i fork this resp and run kotlin-mvc tests. when i set `springdoc.default-flat-param-object = true`, fail with 2 cases.i will check other cases, and see what can i do.
![image](https://github.com/springdoc/springdoc-openapi/assets/32814920/eee9a299-2ec8-4396-a1c2-6198812e2560)

**Comment by codespearhead** [comment]
@mymx2 Try using OpenJDK 17, because there's a known issue in version 21 ( #4224 ).

**Comment by mymx2** [comment]
> @mymx2 Try using JDK 17, because JDK 21 isn't yet supported as per #2442 .

same result.
![image](https://github.com/springdoc/springdoc-openapi/assets/32814920/171d0677-3eb4-4c91-ab22-d0f2eb28a966)

i try add more cases...
![image](https://github.com/springdoc/springdoc-openapi/assets/32814920/a3353a45-5d74-4e16-bcc9-0d494f7b90d5)
more than:
![image](https://github.com/springdoc/springdoc-openapi/assets/32814920/c1e7ec17-b3ea-4eed-8211-0d4dc7cd7de4)
this cases not include `@Parameter` annotaion

**Comment by codespearhead** [comment]
I see.

I suggest forking this repository, updating the test suite so that there are failing tests and [creating a draft PR](https://github.blog/2019-02-14-introducing-draft-pull-requests/) [linked to this issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword), so we can take a look.
