### ISSUE TITLE
Serialization to openapi of org.springframework.data.domain.Sort is not done correctly

### ISSUE THREAD

**Issue by KimSchneider** [springdoc/springdoc-openapi#2558]
The Fix for Bug #2447 breaks our code.

After updating to version 1.8.0 openapi spec says

```
"sort": {
  "type": "array",
  "items": {
    "$ref": "#/components/schemas/OrderObject"
  }
},
```

But the server returns 

```
{
...
    "totalPages": 6,
    "totalElements": 180,
    "last": false,
    "numberOfElements": 30,
    "first": true,
    "sort": {
        "unsorted": false,
        "sorted": true,
        "empty": false
    },
    "number": 0,
    "size": 30,
    "empty": false
}
```

How can we fix that?

**Comment by bnasslahsen** [comment]
springdoc-openapi v1.8.0 is the latest Open Source release supporting Spring Boot 2.x and 1.x.An extended support for springdoc-openapi v1 project is now available for organizations that need support beyond 2023.For more details, feel free to reach out: [sales@springdoc.org](mailto:sales@springdoc.org)

**Comment by KimSchneider** [comment]
@bnasslahsen I work for one of your sponsors mentioned in your readme.md
The issue occures in internal projects as your "fix" is a breaking change and does not align with the spring result object.
