### ISSUE TITLE
When setting swaggerUiConfigProperties.setUrls GroupedOpenAPIs are ignored

### ISSUE THREAD

**Issue by JJWTimmer** [springdoc/springdoc-openapi#2559]
**Describe the bug**

I had added two GroupedOpenApi beans to my Spring Boot project, they appear in the dropdown, and they use the config of the beans. But when I add (via application.yml or bean)  two swagger URLs, with exact same name as the GroupedOpenApi, the config of the groups is ignored. I guess that's a bug? I got inspiration from this example: https://github.com/springdoc/springdoc-openapi/issues/1919#issuecomment-1714022855.

**To Reproduce**

- What version of spring-boot you are using? 3.2.4
- What modules and versions of springdoc-openapi are you using? springdoc-openapi-starter-webmvc-ui 2.4.0
- What is the actual and the expected result using OpenAPI Description (yml or json)? not relevant I think
- Provide with a sample code (HelloController) or Test that reproduces the problem

Shortest trigger I could think of is adding this bean to your config, the first half adds two URLs and the second half configures the groups, which is totally ignored. I also tried with two GroupedOpenApi beans and the application.yml for urls. Same effect.

```
@Bean
    public List<GroupedOpenApi> groupedOpenApis(final SwaggerUiConfigProperties swaggerUiConfigProperties) {
        final Set<AbstractSwaggerUiConfigProperties.SwaggerUrl> swaggerUrls = Set.of(
            new AbstractSwaggerUiConfigProperties.SwaggerUrl(
                "management",
                "/docs/openapi",
                "Management API"),
            new AbstractSwaggerUiConfigProperties.SwaggerUrl(
                "connector",
                "/api/connector/openapi.json",
                "Connector")
        );
        swaggerUiConfigProperties.setUrls(swaggerUrls);

        return List.of(
            GroupedOpenApi.builder()
                .group("connector")
                .pathsToMatch("/api/connector/**")
                .addOpenApiCustomizer(openApi -> openApi
                    .info(new Info().title("Connector"))
                    .components(new Components()
                        .addSecuritySchemes("http-basic", new SecurityScheme()
                            .type(SecurityScheme.Type.HTTP)
                            .scheme("basic"))))
                .build(),
            GroupedOpenApi.builder()
                .group("management")
                .pathsToMatch("/api/manage/**")
                .addOpenApiCustomizer(openApi -> openApi
                    .info(new Info()
                        .title("Management API"))
                    .components(new Components()
                        .addSecuritySchemes("bearer-key", new SecurityScheme()
                            .type(SecurityScheme.Type.HTTP)
                            .scheme("bearer")
                            .bearerFormat("JWT"))))
                .build()
        );
    }
```

**Expected behavior**

- A clear and concise description of what you expected to happen.
- What is the expected result using OpenAPI Description (yml or json)?

I expect to be able to customize the security and title of both groups.

**Screenshots**

**Additional context**

**Comment by bnasslahsen** [comment]
@JJWTimmer,

You are having wrong assumptions here, that might be confusing:

- When you use `GroupedOpenApi. It means you want `springdoc-openapi` to scan for for your groups based on paths/package - The spec will be generated by `springdoc-openapi`

-When you declare `SwaggerUrl`, it means you want to override the `springdoc-openapi` behavior and you are providing the spec URL (For example external OpenAPI specs URLs)

**Comment by JJWTimmer** [comment]
Thanks. Does that mean the workaround that I referenced in #1919 is also faulty? They also combine GroupedOpenApi and swaggerUrls, right?

**Comment by bnasslahsen** [comment]
i do not see the added value of this workaround. 
Yes, might be faulty and lead to errors.
