### ISSUE TITLE
Filtering the /api-docs

### ISSUE THREAD

**Issue by prowave** [springdoc/springdoc-openapi#256]
We have a larges number of endpoints in our app and our OAS3 spec is also large.  We have the endpoints organized into more digestible sections using Tags.  This method is leftover from using multiple Dockets with selectors in springfox/swagger 2.0.

What is the preferred way of breaking up the API docs using springdoc-openapi?

Is there a way to pass a tag to the /v3/api-docs?

I appreciate the project...so far all is good and working well. :)

Apologies if this isn't the best place to ask questions.

Thank you.

**Comment by springdoc** [comment]
Hi, 

 The standard annotations, includes Tags, to group paths.

 You have OpenApiCustomiser Interface that is available.
 You will need to override the method: customise.
You have on this method, the full control on the OpenAPI swagger Object, and you will be able to add any filtering of the elements as you wish.

An example of OpenApiCustomiser is available on:
https://github.com/springdoc/springdoc-openapi/blob/master/springdoc-openapi-webmvc-core/src/test/java/test/org/springdoc/api/app39/SpringDocApp39Test.java

**Comment by debargharoy** [comment]
Seems like the latest commit removed what you're referring to.

**Comment by bnasslahsen** [comment]
The tests 39, is still valid for this case.
Which commit are you refering to ?

**Comment by debargharoy** [comment]
> https://github.com/springdoc/springdoc-openapi/blob/master/springdoc-openapi-webmvc-core/src/test/java/test/org/springdoc/api/app39/SpringDocApp39Test.java

Commit ID: 4818415798336cc5d3ea2099d99a0adfed21fdd5, Jan-23-2020

**Comment by bnasslahsen** [comment]
@debargharoy, 

 This is the test class. Which is ok. I don't see the relation between the commit id and your  comment.

If you are looking for sample code, you should have a look at the @Bean definition of OpenApiCustomiser  which availbale on the test.
