### ISSUE TITLE
springdoc-openapi-starter-webmvc-ui 2.4.0 generates Swagger page as JSON for content type application/x-www-form-urlencoded

### ISSUE THREAD

**Issue by natasa-radenovic** [springdoc/springdoc-openapi#2560]
**Describe the bug**
When using springdoc-openapi-starter-webmvc-ui 2.4.0 in a Spring boot project, the Swagger page is generated incorrectly for content type `application/x-www-form-urlencoded`.

When using a `RestController`, if the input is annotated as `@ModelAttribute`, then the Swagger page renders the input as JSON. This results in a 415 response when used.

This issue doesn't happen with springdoc-openapi-starter-webmvc-ui 2.3.0. It generated the page for the request as formdata and it works correctly when used.

**To Reproduce**
Clone the Github repo: https://github.com/natasa-radenovic/springdoc-openapi-webmvc-ui-issue

Start the Spring boot project inside the v2.3.0 module with `mvn clean spring-boot:run`. Open the generated Swagger page http://localhost:8080/swagger-ui/index.html#. There, the Swagger page is generated as the expected formdata if the input is annotated with `@ModelAttribute`.

Then start the Spring boot project inside the v2.4.0 module with `mvn clean spring-boot:run`. Open the generated Swagger page http://localhost:8080/swagger-ui/index.html#. There, the Swagger page isn't generated as expected if the input is annotated with `@ModelAttribute` or `@RequestBody`. Instead, it's generated as JSON input and results in a 415 response.

**Environment**
- What version of spring-boot you are using?
  - spring-boot-starter-parent 3.2.4
- What modules and versions of springdoc-openapi are you using?
  - springdoc-openapi-starter-webmvc-ui version 2.3.0 and 2.4.0
- Provide with a sample code (HelloController) or Test that reproduces the problem
  - Github repo: https://github.com/natasa-radenovic/springdoc-openapi-webmvc-ui-issue

**Expected behavior**
The Swagger page is supposed to generate content type `application/x-www-form-urlencoded` as formdata, not as JSON.
This issue seems to only occur when using springdoc-openapi-starter-webmvc-ui version 2.4.0.

**Screenshots**
Content type `application/x-www-form-urlencoded` is generated as JSON.
![image](https://github.com/springdoc/springdoc-openapi/assets/115086889/e40cf7c6-5d28-40e6-810e-79ff49a2005f)

**Comment by bnasslahsen** [comment]
@natasa-radenovic,

This is duplicte of  #2439
As workaround can use @ModelAttribute in conjunction with @RequestBody, it typically binds the entire request body.
