### ISSUE TITLE
How to select scopes in Authorize dialog

### ISSUE THREAD

**Issue by onkobu** [springdoc/springdoc-openapi#2563]
https://github.com/swagger-api/swagger-ui/blob/master/docs/usage/oauth2.md states that scopes can be selected by calling initOAuth. I successfully used plain Spring YAML configuration to fill in client-id. Yet there seems to be no similar property for the scopes. I tried to match SecurityRequirement with SecuritySchema which does not seem to affect the dialog:

```
// some @Bean-method receiving a List<SecurityScheme>
// _NAME-constants are shared with SecurityScheme and the dialog displays the one with EXT_OAUTH_SCHEMA_NAME
// but its scopes are unchecked
final Components components = new Components();
  securitySchemas.forEach(scheme -> components.addSecuritySchemes(scheme.getName(), scheme));
  return new OpenAPI().addSecurityItem(new SecurityRequirement().
                        addList(BEARER_SCHEMA_NAME))
                .addSecurityItem(new SecurityRequirement().addList(EXT_OAUTH_SCHEMA_NAME, List.of("openid", "profile")))
                .components(components)
```

I could inject some JS like the CSS example from the FAQ. Is there a less sophisticated way like fixing my code with the SecurityRequirement? Or is it a feature request to provide a property that will be treated like client-id to select scopes`?

**Comment by bnasslahsen** [comment]
@onkobu,

You have complete OAuth2 samples how to setup scopes:
https://github.com/springdoc/springdoc-openapi-demos/tree/master/demo-oauth2

**Comment by onkobu** [comment]
Read carefully. I already setup scopes correctly. They show up in the dialog. But I want some of the checkboxes of scopes to be already checked. Background is an unexperienced user overwhelmed by the amount of scopes and their implications. All combinations yield tokens but not all combinations make sense. By pre-selecting scopes I'd suggest a common sense selection working for most cases with more opt-in by selecting more scopes.
