### ISSUE TITLE
@RequestBody $ref schema overwritten by default Content

### ISSUE THREAD

**Issue by dancerjohn** [springdoc/springdoc-openapi#2564]
**Describe the bug**

When using the @RequestBody annotation using `$ref` the schema is not rendered. If I use the below, it works properly: 
`@RequestBody
          @io.swagger.v3.oas.annotations.parameters.RequestBody(
              content =
                  @Content(
                      mediaType = MediaType.APPLICATION_JSON_VALUE,
                      schema = @Schema(implementation = CreateApiKeyDto.class),
                      examples =
                          @ExampleObject(
                              name = "default",
                              ref = COMPONENTS_EXAMPLES + CREATE_API_KEY_EXAMPLE)))`

However if I use the below, the schema does not render in the Request Body section:
`
@io.swagger.v3.oas.annotations.parameters.RequestBody(
              ref = COMPONENTS_REQUEST_BODIES + CREATE_API_KEY_REQUEST)
`
With below added to components:

    ModelConverters.getInstance().readAll(CreateApiKeyDto.class).forEach(components::addSchemas);
    components.addRequestBodies(
        CREATE_API_KEY_REQUEST,
        new io.swagger.v3.oas.models.parameters.RequestBody()
            .description("Create API Key Request Body")
            .required(true)
            .content(
                new io.swagger.v3.oas.models.media.Content()
                    .addMediaType(
                        MediaType.APPLICATION_JSON_VALUE,
                        new io.swagger.v3.oas.models.media.MediaType()
                            .schema(
                                AnnotationsUtils.resolveSchemaFromType(
                                    CreateApiKeyDto.class, components, null))
                            .addExamples(
                                "Allow All",
                                new Example()
                                    .$ref(COMPONENTS_EXAMPLES + CREATE_API_KEY_EXAMPLE)))));

With the above the following JSON is produced:
```
paths....
"requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/CreateApiKeyDto"
                            }
                        }
                    },
                    "required": true,
                    "$ref": "#/components/requestBodies/ApiKeyCrudController-CreateApiKeyDtoRequest"
                }

 "components": {
        "schemas": {
            "CreateApiKeyDto": {
                "required": [
                    "allowedDnsRegex",
                    "description",
```

When I use the RequestBody $ref, the example from the component requestBodies is respected but no schema is displayed. Not sure if this is because the RequestBody content has a schema (generated by default) as well as the component requestBodies.

**Expected behavior**
I would expect that if I reference requestBodies that contains a Schema to have that schema displayed.

**Screenshots**

![image](https://github.com/springdoc/springdoc-openapi/assets/1896224/e50d469c-8ebe-4be4-ac74-1c805b671bdf)
![image](https://github.com/springdoc/springdoc-openapi/assets/1896224/08b9af62-4294-49bb-b399-379d97de6839)

**Comment by bnasslahsen** [comment]
Not reproducible.
Feel free to provide a [Minimal, Reproducible Example - with HelloController](https://stackoverflow.com/help/minimal-reproducible-example) that reproduces the problem.

This ticket will be closed, but can be reopened if your provide the reproducible sample.
