### ISSUE TITLE
How to configure springdoc with a non-spring-boot project?

### ISSUE THREAD

**Issue by AutomationUIUser** [springdoc/springdoc-openapi#2565]
I am using Spring 6 in my applications. Due to dependencies of older version, I can't migrate my project to Spring Boot due to dependency issues. Earlier I was using SpringFox but it doesn't have support for Spring 6. I want to know if we can use springdoc with non-spring-boot projects. 

The latest version of library [springdoc-openapi-ui](https://mvnrepository.com/artifact/org.springdoc/springdoc-openapi-ui/1.8.0) is dependent on Spring 5.

Please provide the detailed steps of how to configure springdoc with Spring 6. Also, if there is already a demo project, then it will be of great help.

I followed the steps mentioned here: https://springdoc.org/#migrating-from-springfox. But after making all the changes, I am getting the following error:

![image](https://github.com/springdoc/springdoc-openapi/assets/58691782/fe5b927f-fcb2-4e05-ae7a-2b2a3f694a88)

**Comment by bnasslahsen** [comment]
Read https://springdoc.org/v1/#how-to-integrate-open-api-3-with-spring-project-not-spring-boot

**Comment by AutomationUIUser** [comment]
@bnasslahsen Is springdoc-openapi-1.8.0 compatible with Spring 6?

I am asking this question as from maven dependencies, springdoc-openapi-1.8.0 is dependent on Spring 5 and not on Spring 6.

**Comment by adn35350** [comment]
> @bnasslahsen Is springdoc-openapi-1.8.0 compatible with Spring 6?
> 
> I am asking this question as from maven dependencies, springdoc-openapi-1.8.0 is dependent on Spring 5 and not on Spring 6.
> 
> Edit: I tried deploying springdoc-openapi-1.8.0 with Spring 6, but I got the following error:
> 
> ![image](https://private-user-images.githubusercontent.com/58691782/320757389-2d45b1d7-c62e-482a-86c1-87ca2f23d3a8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ0ODc0OTUsIm5iZiI6MTcxNDQ4NzE5NSwicGF0aCI6Ii81ODY5MTc4Mi8zMjA3NTczODktMmQ0NWIxZDctYzYyZS00ODJhLTg2YzEtODdjYTJmMjNkM2E4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDMwVDE0MjYzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRkZDgxNzU4NTY4NzQzMmVlNWFhNjE5ZjYxM2ExNzBlYzIwM2RkY2M2YjkwMDM5NzgzODM3ZTM3ZWMzYTRlNTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.VMQIYrP_XrTH8ns0lzr1ZgeN-S0EfVA3awXrGHX9U6k)
> 
> I checked that the class `LocalVariableTableParameterNameDiscoverer` was available in Spring 5 (spring-core jar) and not available in Spring 6

I'm facing the same issue. Have you found any solution ?
