### ISSUE TITLE
ConverterNotFoundException when upgrading from 2.4.0 to 2.5.0

### ISSUE THREAD

**Issue by marcel-becker** [springdoc/springdoc-openapi#2566]
**Describe the bug**

When I upgrade my gradle dependency version from: 

`org.springdoc:springdoc-openapi-starter-webmvc-ui:2.4.0` 
to 
`org.springdoc:springdoc-openapi-starter-webmvc-ui:2.5.0`

I get an error when starting my spring boot application:
```
***************************
APPLICATION FAILED TO START
***************************

Description:

Failed to bind properties under 'springdoc' to org.springdoc.core.properties.SpringDocConfigProperties:

    Reason: org.springframework.core.convert.ConverterNotFoundException: No converter found capable of converting from type [java.lang.String] to type [org.springdoc.core.properties.SpringDocConfigProperties]

Action:

Update your application's configuration
``` 

In my application.yml I have: 
```
springdoc:
  swagger-ui:
    operationsSorter: method
    path: /swagger-ui.html
```

With version 2.4, the applications starts without any problem. 

- If you are reporting a bug, please help to speed up problem diagnosis by providing as
  much information as possible:
- A clear and concise description of what the bug is: the title of an issue is not enough

**To Reproduce**

- What version of spring-boot you are using?
3.2.4
- What modules and versions of springdoc-openapi are you using?
2.5.0
- What is the actual and the expected result using OpenAPI Description (yml or json)?
- Provide with a sample code (HelloController) or Test that reproduces the problem

**Expected behavior**

- A clear and concise description of what you expected to happen.
The expected behavior is for the application to start normally and be able to browse the swagger ui at the specified endpoint. 
 
- What is the expected result using OpenAPI Description (yml or json)?
The error message should provide more details about the specific problem and how to fix it. 
I could not find any documentation describing the changes from 2.4. to 2.5 that could cause this error. 

**Screenshots**

**Additional context**

**Comment by thijmenketel** [comment]
I'm also facing this issue, did you find a solution?

**Comment by marcel-becker** [comment]
@thijmenketel Still waiting for a solution. Using version 2.4 for now.

**Comment by bnasslahsen** [comment]
Not reproducible.
Feel free to provide a [Minimal, Reproducible Example - with HelloController](https://stackoverflow.com/help/minimal-reproducible-example) that reproduces the problem.

This ticket will be closed, but can be reopened if your provide the reproducible sample.

**Comment by gabrielevi10** [comment]
I fixed it by converting my application.yml to application.properties. It seems something related to not being capable of reading the application.yml file correctly for springdoc configs 🤔

**Comment by bnasslahsen** [comment]
@gabrielevi10,

Your comment can be more helpful if you provide a [Minimal, Reproducible Example - with HelloController](https://stackoverflow.com/help/minimal-reproducible-example) that reproduces the problem.

**Comment by marcel-becker** [comment]
I was able to get my system running with version 2.5.0:
```
org.springdoc:springdoc-openapi-starter-webmvc-ui:2.5.0
```
by adding this property to my `application.yml` file:

```
springdoc:
  api-docs:
    enabled: true
```
