### ISSUE TITLE
Update springdoc-openapi-ui 1.7.0 to 1.8.0 - generate "string" example value

### ISSUE THREAD

**Issue by Jdas33** [springdoc/springdoc-openapi#2568]
**Describe the bug**

Going from version **1.7.0** to version **1.8.0** (springdoc-openapi-ui), I get a display bug in swagger-ui.
Example objects are returned with "string".

Configuration :
`springdoc.swagger-ui.enabled: true`
`springdoc.swagger-ui.operationsSorter: alpha`
`springdoc.swagger-ui.tagsSorter: alpha`

An idea ?

**Screenshots**

springdoc-openapi-ui:1.7.0
![example_value_1 7 0](https://github.com/springdoc/springdoc-openapi/assets/79215657/9189f595-e944-4598-a51e-507bc51f7880)
springdoc-openapi-ui:1.8.0
![example_value_1 8 0](https://github.com/springdoc/springdoc-openapi/assets/79215657/3b6be40b-13e6-4967-865e-e4b3fdcb5dc8)

**Comment by bnasslahsen** [comment]
springdoc-openapi v1.8.0 is the latest Open Source release supporting Spring Boot 2.x and 1.x.An extended support for springdoc-openapi v1 project is now available for organizations that need support beyond 2023.For more details, feel free to reach out: [sales@springdoc.org](mailto:sales@springdoc.org)

**Comment by JasvinderF** [comment]
If there is any update on this.

**Comment by JasvinderF** [comment]
Is this a config related issue?
