### ISSUE TITLE
Not able to exclude the path from custom api.yaml file for a given group name

### ISSUE THREAD

**Issue by eddy8700** [springdoc/springdoc-openapi#2569]
I have a use case where i don't have the controller defined in my spring boot application , i have the open api definition file in yaml format that has say 3 endpoints /portfolio /transactions and /history now for group1 say i want to just display the /portfolio and /transactions endpoint and not the /history endpoint.

I am using the spring boot version 3.2.4
springdoc-openapi-starter-webmvc-ui 2.3.0

my application.properties file
spring.application.name=swagger-demo
springdoc.api-docs.enabled=false
springdoc.swagger-ui.urls[0].url=/user1api.yaml
springdoc.swagger-ui.urls[0].name=group1
springdoc.group-configs[0].group=group1
springdoc.group-configs[0].paths-to-exclude=/history

however on the swagger UI page under the group1 i can see all the 3 endpoints

**Comment by eddy8700** [comment]
i have followed the FAQs link
https://springdoc.org/#what-is-a-proper-way-to-set-up-swagger-ui-to-use-provided-spec-yml

**Comment by eddy8700** [comment]
@jryan128 really appreciate any help on this

**Comment by bnasslahsen** [comment]
Not reproducible.
Feel free to provide a [Minimal, Reproducible Example - with HelloController](https://stackoverflow.com/help/minimal-reproducible-example) that reproduces the problem.

This ticket will be closed, but can be reopened if your provide the reproducible sample.
