### ISSUE TITLE
When the openapi version is changed to 3.1.0 from 3.0.3, integer values are assigned the maximum value

### ISSUE THREAD

**Issue by DenysLiubchenko** [springdoc/springdoc-openapi#2573]
**Describe the bug**

When the openapi version is changed to 3.1.0 from 3.0.3, integer values are assigned the maximum value.
"id": {
    "type": "integer",
    "format": "int32"
}
and it shows up in ui as 1073741824 instead of 0, as it was before

**Screenshots**
![image](https://github.com/springdoc/springdoc-openapi/assets/113592044/10e5ff03-6716-411c-9df4-2f6c659ad9ae)

**Comment by bnasslahsen** [comment]
@DenysLiubchenko,

This is an enhancement in the https://github.com/swagger-api/swagger-ui
Feel free to set the example value, if you are not ok with the generated one.
