### ISSUE TITLE
/v3/api-docs response error

### ISSUE THREAD

**Issue by LkZtCode** [springdoc/springdoc-openapi#2578]
This is the result returned by the web page

![image](https://github.com/springdoc/springdoc-openapi/assets/59859440/9a204289-6ffb-4c4c-b341-2f7a649641ef)

This is the result returned by the breakpoint

![image](https://github.com/springdoc/springdoc-openapi/assets/59859440/b1d733fa-874d-471f-a326-574f4af99e1f)

Why is the returned json escaped? 

I'm not using a custom HttpMessageConverter

**Comment by LkZtCode** [comment]
![image](https://github.com/springdoc/springdoc-openapi/assets/59859440/411beebd-f0ee-416b-a493-4b66ad876d5c)
![image](https://github.com/springdoc/springdoc-openapi/assets/59859440/0e6c4646-d7cb-4c88-ba6d-63da7a3b3207)

**Comment by bnasslahsen** [comment]
@LkZtCode,

Not reproducible.


See the answer here: https://springdoc.org/#why-am-i-getting-an-error-swagger-ui-unable-to-render-definition-when-overriding-the-default-spring-registered-httpmessageconverter

Feel free to provide a [Minimal, Reproducible Example - with HelloController](https://stackoverflow.com/help/minimal-reproducible-example) that reproduces the problem.

This ticket will be closed, but can be reopened if your provide the reproducible sample.
