### ISSUE TITLE
Is it bug? objectMapper redefinition causes Swagger Petstore page

### ISSUE THREAD

**Issue by kuzds** [springdoc/springdoc-openapi#2585]
![image](https://github.com/springdoc/springdoc-openapi/assets/69766866/5f27b4cb-be37-4a53-a8d7-cdbd6780ebf6)
### **If you remove objectMapper redifinition, then**
![image](https://github.com/springdoc/springdoc-openapi/assets/69766866/22bea696-5371-42c8-8f1d-7af58a3ad9a0)

Example
[demo.zip](https://github.com/springdoc/springdoc-openapi/files/15138467/demo.zip)

**Comment by bnasslahsen** [comment]
@kuzds,

You are not having a JSON ObjectMapper in your application.
As result, http://localhost:8080/v3/api-docs/swagger-config content is serialized as XML.

```java
	@Bean
	@Primary
	public ObjectMapper jsonObjectMapper() {
		return Jackson2ObjectMapperBuilder.json().build();
	}

	@Bean
	public XmlMapper xmlObjectMapper() {
		return Jackson2ObjectMapperBuilder.xml().build();
	} 
```
