### ISSUE TITLE
Springdoc is adding a 404 status response for all endpoints, even if I don't add it explicitly

### ISSUE THREAD

**Issue by Juansecu** [springdoc/springdoc-openapi#2587]
**Describe the bug**

- If you are reporting a bug, please help to speed up problem diagnosis by providing as
  much information as possible:
- A clear and concise description of what the bug is: the title of an issue is not enough

A: I'm using Springdoc to document my API, but for any reason, all endpoints include a 404 response status, even if I don't add it explicitly.

**To Reproduce**

- What version of spring-boot you are using?

  A: I'm using version `3.2.5` of Spring Boot

- What modules and versions of springdoc-openapi are you using?

  A: I'm using version `2.5.0` from the module module `springdoc-openapi-starter-webmvc-ui` of Springdoc
- What is the actual and the expected result using OpenAPI Description (yml or json)?
- Provide with a sample code (HelloController) or Test that reproduces the problem

  A: For configuring Springdoc:

  ```java
  @Configuration
  public class OpenApiConfig {
      @Bean
      protected OpenAPI openAPI() {
          final Info info = new Info()
              .description("Description")
              .title("Name")
              .version("1.0.0");
          final SecurityScheme jwtHeaderSecurityScheme = new SecurityScheme()
              .bearerFormat("JWT")
              .in(SecurityScheme.In.HEADER)
              .name("AuthToken")
              .scheme("bearer")
              .type(SecurityScheme.Type.HTTP);
          final Components components = new Components().addSecuritySchemes(
              "AuthToken",
              jwtHeaderSecurityScheme
          );

          return new OpenAPI()
              .components(components)
              .info(info);
      }
  }
  ```

  And the controller:

  ```java
  @RequestMapping("/hello")
  @RequiredArgsConstructor
  @RestController
  @Tag(
      description = "Hello operations",
      name = "Hello"
  )
  public class HelloController {
      @ApiResponse(
          content = {
              @Content(
                  schema = @Schema(
                      type = "string"
                  )
              )
          },
          description = "Send greetings.",
          responseCode = "200"
      )
      @Operation(
          description = "Send greetings.",
          summary = "Send greetings"
      )
      @GetMapping()
      public String getAvatarImage() {
          return "Hello world!";
      }
  }
  ```

  By the way, you can find a real life example [here](https://github.com/OpenToonix/OpenToonix-HTTP-Server).

**Expected behavior**

- A clear and concise description of what you expected to happen.
- What is the expected result using OpenAPI Description (yml or json)?

A: I expected Springdoc to only add the response status that I explicitly add.

**Screenshots**

![image](https://github.com/springdoc/springdoc-openapi/assets/43616657/8021b2e9-a54d-4ab3-b135-c121ed421fb7)
![image](https://github.com/springdoc/springdoc-openapi/assets/43616657/009dd235-e663-4ef5-b4c0-d04d9d4db20c)

**Additional context**

**Comment by bnasslahsen** [comment]
@Juansecu,

Not reproducible, with the provided code.
Feel free to provide a [Minimal, Reproducible Example - with HelloController](https://stackoverflow.com/help/minimal-reproducible-example) that reproduces the problem.

This ticket will be closed, but can be reopened if your provide the reproducible sample.
