### ISSUE TITLE
SpringdocRouterFunctionDsl support

### ISSUE THREAD

**Issue by leandroBorgesFerreira** [springdoc/springdoc-openapi#2590]
Hello,

I see that support for SpringdocRouterFunctionDsl got removed in version 1.5.11. From your changelog:
```
#1261 - Removal of SpringdocRouterFunctionDsl.
``` 

Do you plan to support it again? 

Without this is it is not possible to use the functional endpoint in the way it was intended to be used in Kotlin. https://docs.spring.io/spring-framework/reference/web/webflux-functional.html (check the kotlin code) and the code can only be create in the Java way... 

Something like this:
``` 
fun routes() = router {
    "/api".nest {
        this.GET("hi") {
            ServerResponse.ok().body("H")
        }
    }
}
``` 

Doesn't work with this library anymore, only like this: 
``` 
fun routes(): RouterFunction<ServerResponse> =
    route()
        .GET(
            "/hi",
            { request ->
                ServerResponse.ok().body("Hi functional")
            },
            { ops -> ops.build() }
        )
        .build()
```

**Comment by bnasslahsen** [comment]
@leandroBorgesFerreira,

Have you tried to use: `withAttribute` ?

You should be able to document your endpoints as shown below:

```kotlin
	@Bean
	fun routes() = router {
		"/api".nest {
			this.GET("hi") {
				ServerResponse.ok().body("H")
			}
		}
	}.withAttribute(OPERATION_ATTRIBUTE,
		operationBuilder().operationId("sayHi")
			.response(Builder.responseBuilder()))



```

**Comment by huicunjun** [comment]
> [@leandroBorgesFerreira](https://github.com/leandroBorgesFerreira),
> 
> Have you tried to use: `withAttribute` ?
> 
> You should be able to document your endpoints as shown below:
> 
> 	@Bean
> 	fun routes() = router {
> 		"/api".nest {
> 			this.GET("hi") {
> 				ServerResponse.ok().body("H")
> 			}
> 		}
> 	}.withAttribute(OPERATION_ATTRIBUTE,
> 		operationBuilder().operationId("sayHi")
> 			.response(Builder.responseBuilder()))


How to declare documentation for each interface?


`
router {
            POST("/sayHi") { ServerResponse.ok().body("hi")  }.withAttribute(
                OPERATION_ATTRIBUTE,
                operationBuilder()
                    .operationId("sayHi")
                    .response(Builder.responseBuilder().implementation(String::class.java))
            )
            POST("/sayHi2") { ServerResponse.ok().body("hi2")  }.withAttribute(
                OPERATION_ATTRIBUTE,
                operationBuilder()
                    .operationId("sayHi")
                    .response(Builder.responseBuilder().implementation(String::class.java))
            )

        }


`
