### ISSUE TITLE
 Failed to instantiate [org.springdoc.core.converters.ModelConverterRegistrar] in a containerized environment

### ISSUE THREAD

**Issue by ffelipelimao** [springdoc/springdoc-openapi#2593]
**Describe the bug**

- I was migrating from Spingfox to use OpenDocs 2 with Spring Boot 3, and to run it locally on my machine everything went well, it runs Swagger UI, but when I went to deploy it to a container it gave an error in a Bean and not started the app

- I'm using kotlin with spring boot 3 ```implementation("org.springframework.boot:spring-boot-starter-webflux")```
- and using springdoc-openapi ```springdoc-openapi-starter-webflux-ui``` to generate my swagger-ui
- I'm in a gradle 8.7 environment and using jdk21 zulu
```
@Configuration
public class SwaggerConfiguration {
    @Bean
    public OpenAPI openAPI() {
        return new OpenAPI()
                .info(new Info().title("Service API")
                .description("This is my Service API")
                .version("v0.0.1"));
    }
}
```

- Stacktrace

```[2024-05-10 11:12:56,913] WARN Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'modelConverterRegistrar' defined in class path resource [org/springdoc/core/configuration/SpringDocConfiguration.class]: Failed to instantiate [org.springdoc.core.converters.ModelConverterRegistrar]: Factory method 'modelConverterRegistrar' threw exception with message: 'io.swagger.v3.core.converter.ModelConverters io.swagger.v3.core.converter.ModelConverters.getInstance(boolean)' (org.springframework.boot.web.reactive.context.AnnotationConfigReactiveWebServerApplicationContext:632)```

**To Reproduce**

- Upload an API with these configurations in a container with the information above

**Expected behavior**

- I would like to just generate swagger-ui with spring boot 3

- I'm publishing this, I believe it must be some configuration that I forgot to put that caused this error, but as I didn't find anything in the docs, I would like some help

**Comment by bnasslahsen** [comment]
Not reproducible.
Feel free to provide a [Minimal, Reproducible Example - with HelloController](https://stackoverflow.com/help/minimal-reproducible-example) that reproduces the problem.

This ticket will be closed, but can be reopened if your provide the reproducible sample.
