### ISSUE TITLE
Springdoc not producing correct OpenAPI specification for an Iterable of enums in Scala

### ISSUE THREAD

**Issue by nils1k** [springdoc/springdoc-openapi#2594]
**Describe the bug**

When I have a field of type Iterable of an enum, e.g. a `Set` or a `Seq`, then `springdoc` is not generating the correct OpenAPI specification.

**To Reproduce**

***What version of spring-boot you are using?***
Version `3.2.5`.

***What modules and versions of springdoc-openapi are you using?***
Version `2.5.0` and the `org.springdoc:springdoc-openapi-starter-webmvc-ui` module.

***What is the actual and the expected result using OpenAPI Description (yml or json)?***
Expected result:

```json
"fareClasses": {
    "type": "array",
    "description": "FareClasses",
    "items": {
        "type": "string"
    }
}
```

Actual result:

```json
"fareClasses": {
    "type": "array",
    "description": "FareClasses",
    "items": {
        "type": "string",
        "enum": [
            "FIRST_CLASS",
            "SECOND_CLASS",
            "THIRD_CLASS",
            "ECONOMY_CLASS"
        ]
    }
}
```

Please refer to the [sample code](https://github.com/nils1k/springdoc-scala-bug) that reproduces the issue.

**Expected behavior**

The `fareClasses` field should be an enum.

**Screenshots**
![swagger-ui](https://github.com/springdoc/springdoc-openapi/assets/3519430/9da202a1-1431-47a6-bdf9-15d55805569c)

**Additional context**
N/A

**Comment by bnasslahsen** [comment]
@nils1k,

I see you have already posted an issue in the swagger-core.
There is nothing specifc to scala in the springdoc side.

Feel free to provide a [Minimal, Reproducible Example - with HelloController](https://stackoverflow.com/help/minimal-reproducible-example) that reproduces the problem. (**In Java**)

This ticket will be closed, but can be reopened if your provide the reproducible sample.
