### ISSUE TITLE
Schema name ignored for abstract class with generics

### ISSUE THREAD

**Issue by ivansenic** [springdoc/springdoc-openapi#2598]
**Describe the bug**

I am having an issue that when I have an interface or an abstract class with generics and the generated YAML contains a very confusing name for that model, although the `name` in `@Schema` is explicitly defined. This seems reproducible for all such classes, so I assume it's a bug.

*Example*:

```
@Schema(
        name = "VideoData",
        description = "Data for a single article video.",
        discriminatorProperty = "videoType",
        discriminatorMapping = {
                @DiscriminatorMapping(value = "PRESENTER", schema = PresenterVideoData.class),
                @DiscriminatorMapping(value = "SUMMARY_SLIDESHOW", schema = SummaryVideoData.class),
                @DiscriminatorMapping(value = "SOCIAL_MEDIA", schema = SocialMediaVideoData.class)
        },
        oneOf = {
                PresenterVideoData.class,
                SummaryVideoData.class,
                SocialMediaVideoData.class
        })
public interface VideoData<T extends VideoType, S extends VideoSettings<T>, R extends VideoRevision<T>> {
```

which gets mapped to:

```
    VideoDataVideoTypeVideoSettingsObjectVideoRevisionObject:
      type: object
      description: Data for a single article video.
      discriminator:
        mapping:
          PRESENTER: '#/components/schemas/VideoData.Presenter'
          SOCIAL_MEDIA: '#/components/schemas/VideoData.SocialMedia'
          SUMMARY_SLIDESHOW: '#/components/schemas/VideoData.Summary'
        propertyName: videoType
      oneOf:
      - $ref: '#/components/schemas/VideoData.Presenter'
      - $ref: '#/components/schemas/VideoData.Summary'
      - $ref: '#/components/schemas/VideoData.SocialMedia'
```

I also can confirm that it seems that each generic element adds to the name. For example, I have another class `public abstract class VideoSettings<T extends VideoType>` which is translated to `VideoSettingsObject`. Again, in all schemas I do have name explicitly defined.

**To Reproduce**

- What version of spring-boot you are using? 
   - `3.1.11`
- What modules and versions of springdoc-openapi are you using? 
   - `2.5.0`
- What is the actual and the expected result using OpenAPI Description (yml or json)?
   - Should be exactly the name specified in the Schema annotation
- Provide with a sample code (HelloController) or Test that reproduces the problem
   - I think problem is simple enough, if needed I can create reproducer 

**Expected behavior**

Correct naming of the model.

**Additional context**

Note that explicit name in `@Schema` does work when there is no generics, I confirmed this.

**Comment by bnasslahsen** [comment]
@ivansenic,

Not reproducible, In springdoc-openapi code.
Feel free to provide a [Minimal, Reproducible Example - with HelloController](https://stackoverflow.com/help/minimal-reproducible-example) that reproduces the problem.

This ticket will be closed, but can be reopened if your provide the reproducible sample.
