### ISSUE TITLE
requestBody description is lost

### ISSUE THREAD

**Issue by tfedyanin** [springdoc/springdoc-openapi#26]
When I use 
```java
requestBody = @RequestBody(description = "smth")
```
it doesn't appear in the generated spec.
In method `org.springdoc.api.AbstractOpenApiResource#calculatePath` description is parses correctly on line 79 (org.springdoc.core.OperationBuilder#parse), but is ignored when 
```java
// requests
operation = requestBuilder.build(components, handlerMethod, requestMethod, operation, mediaAttributes.getAllConsumes());
```
on line 83.

**Comment by springdoc** [comment]
Hi, 

 As a workaround, you can use @Parameter annotation to get the description of your parameter.
 Or you pass the @RequestBody inside @Operation annotation.
Handling @RequestBody annotation directly at parameter level, will be available on v1.1.9 of sprindoc-openapi.
