### ISSUE TITLE
@Hidden not working at class level

### ISSUE THREAD

**Issue by prowave** [springdoc/springdoc-openapi#260]
I have `@Hidden` applied at the class level for a couple of controllers and they are still getting generated int the spec.

* springdocs-openapi 1.2.17 (also tried 1.2.18-SNAPSHOT)

![image](https://user-images.githubusercontent.com/4467101/70742653-07fb7100-1cec-11ea-81af-dd7a8f976784.png)

![image](https://user-images.githubusercontent.com/4467101/70742631-fade8200-1ceb-11ea-9668-5b6618b76bc5.png)

**Comment by springdoc** [comment]
Fix will be available on v1.2.18.

**Comment by prowave** [comment]
ok, cool.  I was trying to figure it out to create a PR, but if you already know what it is...thank you!
