### ISSUE TITLE
Unable to make @ApiResponse annotation take @JsonView into consideration

### ISSUE THREAD

**Issue by kaifresh** [springdoc/springdoc-openapi#2604]
**Describe the bug**

I am using
```xml
 <dependency>
    <groupId>org.springdoc</groupId>
    <artifactId>springdoc-openapi-starter-webmvc-ui</artifactId>
    <version>2.5.0</version>
</dependency>
```

I have defined a @JsonView for my @RestController. It works as far as JSON serialisation is concerned. However in the Swagger output, all fields (not just the @JsonView annotated fields) are included. As far as I can tell, my code mirrors the [Meal Party example](https://github.com/springdoc/springdoc-openapi/blob/e14f9755bdca66f5ba44ac8e76d69ec361700ad8/springdoc-openapi-tests/springdoc-openapi-javadoc-tests/src/test/java/test/org/springdoc/api/app54/HelloController.java#L59). 

I have wrapped my response body in a `ResponseEntity`.  The controller is annotated as follows:
```java
@GetMapping("/things")
@JsonView(Views.PublicRestView.class)
@Operation(summary = "...")
@ApiResponses(value = {
        @ApiResponse(responseCode = "200", description = "...."),
        @ApiResponse(responseCode = "400", description = "....",
                content = @Content(schema = @Schema(implementation = FailureDetail.class))),
        @ApiResponse(responseCode = "502", description = "...",
                content = @Content(schema = @Schema(implementation = FailureDetail.class)))})
```

The View is defined as:
```java
public class Views {
    public interface PublicRestView {}
}
```

**To Reproduce**

- What version of spring-boot you are using? 2.5.0
- What modules and versions of springdoc-openapi are you using? 
I am using the following 
```java
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.responses.ApiResponses;
import org.springdoc.core.annotations.ParameterObject;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;
```
- What is the actual and the expected result using OpenAPI Description (yml or json)?
- Provide with a sample code (HelloController) or Test that reproduces the problem

**Expected behavior**

- A clear and concise description of what you expected to happen: I should only see fields that have been annotated with the @JsonView in the response. 
- What is the expected result using OpenAPI Description (yml or json)? These fields should be completely omitted from the schema.

**Comment by bnasslahsen** [comment]
@kaifresh,

Remove the `implementation` class of your  `@ApiResponse`, which is taking precedence.
