### ISSUE TITLE
Spring Authorization Server Metadata Endpoint not compatible

### ISSUE THREAD

**Issue by jsantana3c** [springdoc/springdoc-openapi#2606]
**Describe the bug**

- Spring Authorization Server 1.3.0 metadata endpoint not compatible, it generates a "Null" Path, which prevents the serialization of jackson, preventing the creation of the openapi json.

**To Reproduce**

- What version of spring-boot you are using? 3.3.0
- What modules and versions of springdoc-openapi are you using? webmvc-ui-starter
- What is the actual and the expected result using OpenAPI Description (yml or json)? json
- Provide with a sample code (HelloController) or Test that reproduces the problem -> just add spring authorization server with defaults

**Expected behavior**
- spring authorization server metadata endpoint default url
**Screenshots**
the matcher is a lambda, so that's probably the reason why the code doesn't work properly
![image](https://github.com/springdoc/springdoc-openapi/assets/166711198/6ceea223-e958-42f7-9272-1b06da2d1d0a)

so in the method
org.springdoc.core.configuration.SpringDocSecurityOAuth2Customizer#buildPath
![image](https://github.com/springdoc/springdoc-openapi/assets/166711198/fbaf271b-d742-437f-a555-e10415a50c65)
no matching is being done, and the path ends up being null.

**Additional context**
spring is checking if it has multipleIssuers, so maybe you can guys customize the code and check if isMultipleIssuersAllowed directly and apply the default DEFAULT_OAUTH2_AUTHORIZATION_SERVER_METADATA_ENDPOINT_URI, otherwise leave it with the /** by default?

**Comment by senowang** [comment]
you just exclude @SpringBootApplication(exclude = {SpringDataWebAutoConfiguration.class})  and it will be fine

**Comment by aschade92** [comment]
> you just exclude @SpringBootApplication(exclude = {SpringDataWebAutoConfiguration.class}) and it will be fine

I'm having the same issue and this didn't fix the problem. From testing locally it looks like upgrading `spring-security-oauth2-authorization-server` to version `1.3.0` from `1.2.4` is when the issue started, so some change in the most recent version of that dependency started the issue.

**Comment by senowang** [comment]
> > you just exclude @SpringBootApplication(exclude = {SpringDataWebAutoConfiguration.class}) and it will be fine你只需排除 （exclude = {SpringDataWebAutoConfiguration.class}） 就可以了
> 
> I'm having the same issue and this didn't fix the problem. From testing locally it looks like upgrading `spring-security-oauth2-authorization-server` to version `1.3.0` from `1.2.4` is when the issue started, so some change in the most recent version of that dependency started the issue.我遇到了同样的问题，但这并没有解决问题。从本地测试来看，升级 `spring-security-oauth2-authorization-server` 到版本似乎是问题开始时的版本 `1.3.0` `1.2.4` ，因此该依赖项的最新版本中的一些更改引发了问题。
> 
> If I had to guess it was this change that's causing the issue: [spring-projects/spring-authorization-server@4cfe59c](https://github.com/spring-projects/spring-authorization-server/commit/4cfe59cd85197fff7732bea8576d519510965eb2)如果我不得不猜测是这个变化导致了这个问题：spring-projects/spring-authorization-server@ 4cfe59c

you can see this issues https://github.com/spring-projects/spring-data-commons/issues/2937

**Comment by bnasslahsen** [comment]
@jsantana3c,

The check if isMultipleIssuersAllowed can be done only in `spring-security` context on the runtime of the http request.
I have added a fix so both endpoints are exposed by default.

**Comment by strangeundersun** [comment]
> @jsantana3c,
> 
> The check if isMultipleIssuersAllowed can be done only in `spring-security` context on the runtime of the http request. I have added a fix so both endpoints are exposed by default.

Hey @bnasslahsen, is there a workaround before the fix released? I really can't downgrade _authorization server_ to `1.2.4`. 
And it would be great if you provide the time schedule that we can get the fix in a release. Thanks!

**Comment by joaquinjsb** [comment]
@bnasslahsen I just tried the release candidate, and seems that it's still not working.

**Comment by bnasslahsen** [comment]
@joaquinjsb, 

Not working, will not really help :)

Feel free to provide a [Minimal, Reproducible Example - with HelloController](https://stackoverflow.com/help/minimal-reproducible-example) that reproduces the problem.

Remember, contributions to this repository should follow its [contributing guidelines](https://github.com/springdoc/springdoc-openapi/blob/1fdddf6bc37476473f6e83dd83245f1cf51caee2/CONTRIBUTING.adoc)

**Comment by joaquinjsb** [comment]
sure, i'lll create another issue, but seems that the exception is still the same:
com.fasterxml.jackson.databind.JsonMappingException: Null key for a Map not allowed in JSON (use a converting NullKeySerializer?) (through reference chain: io.swagger.v3.oas.models.OpenAPI["paths"]->io.swagger.v3.oas.models.Paths["null"])
