### ISSUE TITLE
Question: Can scopes be assigned to Security Schemes (apiKey) globally?

### ISSUE THREAD

**Issue by Andrew3431** [springdoc/springdoc-openapi#261]
Thank you for providing and supporting this library.  I am using the apiKey security scope and I have two questions regarding that. Can scope be assigned to an "apiKey" security scheme and also can scopes be assigned at a global level to this security scheme ? #

**Comment by dlamoris** [comment]
Hi, i believe scopes are only used for oauth2 or openIdConnect security schemes

**Comment by springdoc** [comment]
Hi, 

 Yes i confirm that scopes are only for SecuritySchemeType.OAUTH2.
You can set it globally using OpenAPI Bean. For example:

```java
@Bean
public OpenAPI customOpenAPI() {
	return new OpenAPI()
	.components(new Components()
	.addSecuritySchemes("personstore_auth",
	new SecurityScheme().type(SecurityScheme.Type.OAUTH2).flows(new OAuthFlows()
	.implicit(new OAuthFlow().authorizationUrl("http://personstore.swagger.io/oauth/dialog")
	.scopes(new Scopes().addString("write:persons", "des"))))));
}
```
