### ISSUE TITLE
[BUG] Using the builder setter and setting JsonProperty Access will result in enumerating recursively the current type

### ISSUE THREAD

**Issue by fangzhengjin** [springdoc/springdoc-openapi#2610]
**Describe the bug**

Using the builder setter and setting JsonProperty Access will result in enumerating recursively the current type.

**To Reproduce**

```java
public class ResourceSearchVO implements Serializable {
    @JsonProperty(access = JsonProperty.Access.WRITE_ONLY)
    private ResourceEnum type;

    public ResourceEnum getType() {
        return type;
    }

    public ResourceSearchVO setType(ResourceEnum type) {
        this.type = type;
        return this;
    }
}
```

**Screenshots**
<img width="1320" alt="image" src="https://github.com/springdoc/springdoc-openapi/assets/12680972/e28ecfab-a679-412e-b827-1393e35f30a1">

**Additional context**
springdoc-openapi: 2.5.0

**Comment by fangzhengjin** [comment]
Link: https://github.com/swagger-api/swagger-core/issues/4690

**Comment by bnasslahsen** [comment]
@fangzhengjin,

Thanks for sharing.
This is a swagger-core bug, and once it's fixed we will integrate it.
