### ISSUE TITLE
Global tags are not populated from Tag at type level

### ISSUE THREAD

**Issue by piotrooo** [springdoc/springdoc-openapi#2612]
**Describe the bug**

Following example:

```java
@RestController
@Tag(name = "web")
public class WebController {
    //clean for brevity
}
```

doesn't produce a [global tag](https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.1.0.md#tag-object) because it lacks a `description` attribute.

When I define a:

```java
@OpenAPIDefinition(tags = {
        @Tag(name = "web")
})
```

the global tags are generated correctly.

**To Reproduce**

* Spring Boot 3.3.0
* Springdoc 2.5.0

**Expected behavior**

The `@Tag` annotation at the type level should generate global tags as well.

**Additional context**

In the `@OpenAPIDefinition` generation method, the `AnnotationsUtils.getTags(apiDef.tags(), false)` method is used with a `false` flag, which allows registering tags without a description. For type handling, the same method is used with `true` flag.

**Comment by bnasslahsen** [comment]
@piotrooo,

This is related to https://docs.swagger.io/swagger-core/v2.2.22/apidocs/io/swagger/v3/oas/annotations/tags/Tag.html

![image](https://github.com/springdoc/springdoc-openapi/assets/13404829/69d0b375-9f9a-44e1-8d44-025913c515a5)


> When applied at method or class level, if only a name is provided, the tag will be added to operation only; if additional fields are also defined, like description or externalDocs, the Tag will also be added to openAPI.tags field
