### ISSUE TITLE
`@Schema` annotation not picked up when used on another annotation.

### ISSUE THREAD

**Issue by Jardo-51** [springdoc/springdoc-openapi#2615]
**Describe the bug**

I created a [minimal reproducible example](https://github.com/Jardo-51/mres/tree/main/spring/springdoc-annotations) with the latest version of Spring Boot (3.3.0) and springdoc-openapi-starter-webflux-ui (2.5.0).

Let's say I have a large number of endpoints which use parameter `personId`. I want to document that parameter, but I don't want to copy-paste the doc annotations everywhere. So I created the following annotation:
```java
@Retention(RetentionPolicy.RUNTIME)
@Parameter(description = "Person identifier", example = "1234")
public @interface PersonIdParam {

}
```
I use the annotation in the following way:
```java
@GetMapping("/person/{id}")
public Mono<PersonDto> getById(@PathVariable @PersonIdParam String id) {
	...
}
```
This works fine, the description and example is added to every parameter in the generated docs.

But now, I would like to do the same thing for object fields. I created the following annotation:
```java
@Target(ElementType.FIELD)
@Retention(RetentionPolicy.RUNTIME)
@Schema(description = "Person identifier", example = "1234")
public @interface PersonIdField {

}
```
And I use it like this:
```java
public class PersonDto {

	@PersonIdField
	private String id;

	...
}
```
But this doesn't work. The description and example are not added to the generated docs.

**To Reproduce**

- Clone and run the [minimal reproducible example](https://github.com/Jardo-51/mres/tree/main/spring/springdoc-annotations)
- Open <http://localhost:8080/webjars/swagger-ui/index.html#/person-controller/getById>
- The description and example are missing on field `PersonDto.id`
     
![Screenshot from 2024-06-05 11-37-53](https://github.com/springdoc/springdoc-openapi/assets/6890442/86ff3550-3be1-47b6-ab72-774b52fd6296)
  
**Expected behavior**

- Field `PersonDto.id` has description and example value.

**Comment by bnasslahsen** [comment]
@Jardo-51,

Not in springdoc code, but `swagger-core`.

Add `@JacksonAnnotationsInside` to your class as follow:

```java
@Target(ElementType.FIELD)
@Retention(RetentionPolicy.RUNTIME)
@Schema(description = "Person identifier", example = "1234")
@JacksonAnnotationsInside
public @interface PersonIdField {

}

```

See explanation here: https://github.com/swagger-api/swagger-core/issues/4340
