### ISSUE TITLE
Issue Description: Swagger UI not accessible with Spring WebFlux

### ISSUE THREAD

**Issue by danielbradea** [springdoc/springdoc-openapi#2616]
Summary:
I've encountered an issue where Swagger UI is not accessible in my Spring WebFlux application despite configuring it with springdoc-openapi-starter-webflux-api.

Steps to Reproduce:

    Set up a Spring WebFlux project.
    Include springdoc-openapi-starter-webflux-api dependency.
    Start the application.
    Attempt to access Swagger UI via http://localhost:8080/swagger-ui.html.

Expected Behavior:
I expect Swagger UI to be accessible, allowing me to interact with the API documentation.

Actual Behavior:
When trying to access http://localhost:8080/swagger-ui.html, I receive a 404 error indicating that the resource cannot be found.

Additional Information:

    The OpenAPI JSON documentation endpoint (http://localhost:8080/v3/api-docs) returns the expected API documentation.
    I've verified the configuration and dependencies, and they seem to be correct.
    There are no relevant errors or warnings in the application logs.

Environment:

    Spring Boot version: 3.3.0
    springdoc-openapi-starter-webflux-api version: 2.5.0
    Java version: 17

**Comment by makhtardiouf** [comment]
Hello @danielbradea. How did you resolve this issue ?
For the me the ui loads, but without any documentation generated for my controllers .

**Comment by dreamstar-enterprises** [comment]
I have the same issue. OpenDocs loads, http://localhost:8080/v3/api-docs, but not http://localhost:8080/swagger-ui.html - it keeps saying 404 not found

**Comment by ApacheScribe** [comment]
Hi, I got it to work with the following pom.xml: 

    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>3.2.10</version>
        <relativePath /> 
    </parent>

 <properties>
        <java.version>17</java.version>
        <jasypt.version>3.0.5</jasypt.version>
        <sonar.core.codeCoveragePlugin>jacoco</sonar.core.codeCoveragePlugin>
        <sonar.dynamicAnalysis>reuseReports</sonar.dynamicAnalysis>
        <sonar.jacoco.reportPaths>${project.basedir}/target/jacoco.exec</sonar.jacoco.reportPaths>
        <spring-cloud.version>2023.0.1</spring-cloud.version>
        <org.mapstruct.version>1.5.3.Final</org.mapstruct.version>
    </properties>

<dependencies>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-webflux</artifactId>
            <exclusions>
                <exclusion>
                    <groupId>org.yaml</groupId>
                    <artifactId>snakeyaml</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>org.yaml</groupId>
            <artifactId>snakeyaml</artifactId>
            <version>2.0</version>
        </dependency>
        
        <dependency>
            <groupId>org.springdoc</groupId>
            <artifactId>springdoc-openapi-starter-webflux-ui</artifactId>
            <version>2.2.0</version>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-actuator</artifactId>
        </dependency>
       
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-data-redis-reactive</artifactId>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-validation</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-mail</artifactId>
        </dependency>
        <dependency>
            <groupId>io.micrometer</groupId>
            <artifactId>micrometer-registry-prometheus</artifactId>
            <scope>runtime</scope>
        </dependency>
        <dependency>
            <groupId>org.bouncycastle</groupId>
            <artifactId>bcprov-jdk18on</artifactId>
            <version>1.78</version>
        </dependency>
        <dependency>
            <groupId>jakarta.xml.bind</groupId>
            <artifactId>jakarta.xml.bind-api</artifactId>
            <version>4.0.0</version>
        </dependency>
        <dependency>
            <groupId>jakarta.xml.soap</groupId>
            <artifactId>jakarta.xml.soap-api</artifactId>
            <version>3.0.0</version>
        </dependency>
        <dependency>
            <groupId>jakarta.activation</groupId>
            <artifactId>jakarta.activation-api</artifactId>
            <version>2.1.1</version>
        </dependency>
        <dependency>
            <groupId>com.sun.xml.messaging.saaj</groupId>
            <artifactId>saaj-impl</artifactId>
            <version>3.0.1</version>
        </dependency>
        <dependency>
            <groupId>org.glassfish.jaxb</groupId>
            <artifactId>jaxb-runtime</artifactId>
            <version>3.0.2</version>
        </dependency>

        <dependency>
            <groupId>org.webjars</groupId>
            <artifactId>webjars-locator-core</artifactId>
        </dependency>

        <dependency>
            <groupId>com.icegreen</groupId>
            <artifactId>greenmail</artifactId>
            <version>2.0.1</version>
        </dependency>

        
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-bootstrap</artifactId>
            <exclusions>
                <exclusion>
                    <groupId>org.bouncycastle</groupId>
                    <artifactId>bcprov-jdk18on</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-config</artifactId>
            <exclusions>
                <exclusion>
                    <groupId>org.bouncycastle</groupId>
                    <artifactId>bcprov-jdk15on</artifactId>
                </exclusion>
            </exclusions>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-configuration-processor</artifactId>
            <optional>true</optional>
        </dependency>
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <optional>true</optional>
        </dependency>
        <dependency>
            <groupId>org.mapstruct</groupId>
            <artifactId>mapstruct</artifactId>
            <version>${org.mapstruct.version}</version>
        </dependency>
        <dependency>
            <groupId>com.github.loki4j</groupId>
            <artifactId>loki-logback-appender</artifactId>
            <version>1.5.1</version>
        </dependency>

          
          <dependency>
            <groupId>com.github.ulisesbocchio</groupId>
            <artifactId>jasypt-spring-boot-starter</artifactId>
            <version>${jasypt.version}</version>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>io.projectreactor</groupId>
            <artifactId>reactor-test</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>

**Comment by dreamstar-enterprises** [comment]
I have the issue still. 

Here is my stackoverflow: 
https://stackoverflow.com/questions/78990375/spring-boot-forward-headers-strategy-framework-keeps-giving-403-forbidden?noredirect=1#comment139278118_78990375

Then PhilWebb from the Spring Boot team, raised the issue here:
https://github.com/reactor/reactor-netty/issues/3432

This was after I raised the issue with the Spring Boot team here:
https://github.com/spring-projects/spring-boot/issues/42317

It is due to the Gateway prefix not being added, by Spring Boot, when Spring Docs generates the redirect URL for swagger, when re-directing from: swagger-index.html to webjars/swagger-ui/index.html

**BUT also** because of me getting a 404 Not Found, or 403 Forbidden, when I switch from 

```
server:
address: localhost
port: 8080
ssl:
enabled: false
forward-headers-strategy: native
```

to 

```
server:
address: localhost
port: 8080
ssl:
enabled: false
forward-headers-strategy: framework
```

using Spring Boot Webflux. So they are two interelated issues.
