### ISSUE TITLE
Add informative logs

### ISSUE THREAD

**Issue by apozo-copyright** [springdoc/springdoc-openapi#2617]
The library is totally missing informative logs to understand what it's doing and solve problems.
It's basically only logging exceptions.

Please, add LOGGER.infos and debugs all around.

**Comment by bnasslahsen** [comment]
@apozo-copyright,

Feel free to provide directly a PR and we will have a look at it.

**Comment by apozo-copyright** [comment]
Errrrr ... isn't the point of feature requests to see how many users demand the same? If you close it, that can't happen.
