### ISSUE TITLE
auto-configuration doesn't work when spring-context-indexer is present

### ISSUE THREAD

**Issue by ckoutsouridis** [springdoc/springdoc-openapi#262]
It seems that if a project has `org.springframework:spring-context-indexer` the auto-configuration  is broken.

the only configuration that gets executed is `SpringDocConfiguration` as it is the only one that has an entry in `spring.factories`. inside that single configuation there is a 

```
@Configuration
@EnableConfigurationProperties
@ComponentScan(basePackages = {"org.springdoc"})
public class SpringDocConfiguration {

```

And this component scan is never activated. I think it would be better to remove the component scan entirely and make every configuration as entries in `spring.factories`

**Comment by springdoc** [comment]
Hi @ckoutsouridis, 

 Can you please add a sample code describing the issue that you describe?

**Comment by ckoutsouridis** [comment]
with a simple project and a `pom.xml` such as :

```
		<dependency>
			<groupId>org.springdoc</groupId>
			<artifactId>springdoc-openapi-webflux-ui</artifactId>
			<version>1.2.18</version>
		</dependency>

```

once we start the project and navigate to `host:port/swagger-ui.html` we see the swagger ui.
now if the `pom.xml` is as such
```
		<dependency>
			<groupId>org.springdoc</groupId>
			<artifactId>springdoc-openapi-webflux-ui</artifactId>
			<version>1.2.18</version>
		</dependency>
		<dependency>
			<groupId>org.springframework</groupId>
			<artifactId>spring-context-indexer</artifactId>
		</dependency>
```
and we start the project, and navigate again to `host:port/swagger-ui.html` results in 404. And the reason is that the all the beans that are registered by the `springdoc-openapi-webflux-ui` are via `@ComponentScan` and via `spring.factories`
