### ISSUE TITLE
`@Schema` and `description` not picked up for polymorphic attributes.

### ISSUE THREAD

**Issue by aykborstelmann** [springdoc/springdoc-openapi#2620]
**Describe the bug**

On a polymorphic attribute, `PolymorphicModelConverter` simply creates a new schema and ignored the previous. 
Thus on the way the resolved `@Schema` annotation is lost with all it's custom documentation functions, such as `description`

**Comment by bnasslahsen** [comment]
@aykborstelmann,

Not reproducible.
Feel free to provide a [Minimal, Reproducible Example - with HelloController](https://stackoverflow.com/help/minimal-reproducible-example) that reproduces the problem.

This ticket will be closed, but can be reopened if your provide the reproducible sample.
