### ISSUE TITLE
Content-type for POST endpoints with multipart/form-data does not work since v2.4.0 

### ISSUE THREAD

**Issue by maxdobler** [springdoc/springdoc-openapi#2621]
**Describe the bug**

Sind version 2.4.0 POST Endpoints with content-type `multipart/form-data` are not generated properly in open api spec. This leads to missing content-type in swagger ui webpage.

**To Reproduce**

- What version of spring-boot you are using?
3.3.0
- What modules and versions of springdoc-openapi are you using?
springdoc-openapi-starter-webmvc-ui:2.4.0
- What is the actual and the expected result using OpenAPI Description (yml or json)?

- Provide with a sample code (HelloController) or Test that reproduces the problem
POST Endpoint which accepts multipart/form-data. Use [sprin](springdoc-openapi-starter-webmvc-ui in version `2.4.0` or `2.5.0`
`@PostMapping(produces = APPLICATION_JSON_VALUE, consumes = MULTIPART_FORM_DATA_VALUE)`

Go to swagger-ui webpage and the content-type is missing for the POST Endpoint.

**Expected behavior**

Adds content-type multipart/form-data to POST Endpoints in OpenApi docs

**Screenshots**
Open Api Diff:
![image](https://github.com/springdoc/springdoc-openapi/assets/2629317/b46db402-c455-4ff1-b3ef-132c24bffc4c)

Swagger UI in v2.3.0
![Screenshot 2024-06-12 at 18 13 45](https://github.com/springdoc/springdoc-openapi/assets/2629317/a77b764f-b09b-4620-96b7-af3dad937852)

Swagger UI in 2.4.0 / 2.5.0
![Screenshot 2024-06-12 at 18 14 50](https://github.com/springdoc/springdoc-openapi/assets/2629317/1770caf5-67a5-4cd8-9ffb-fd1d5cdccccd)

**Additional context**

**Comment by bnasslahsen** [comment]
Not reproducible.
Feel free to provide a [Minimal, Reproducible Example - with HelloController](https://stackoverflow.com/help/minimal-reproducible-example) that reproduces the problem.

This ticket will be closed, but can be reopened if your provide the reproducible sample.

**Comment by maxdobler** [comment]
I created an example to reproduce the bug: https://github.com/maxdobler/springdoc-example

I noticed that it makes a difference if the `UploadDto` has the `@Valid` annotation. With the annotation, the swagger-ui displays the dropdown an recognises the right content-type.

If you change the springdoc version to `2.5.0` the consuming content-type is not displayed in the swagger-ui.

Please reopen this issue.

**Comment by maxdobler** [comment]
@bnasslahsen Please reopen this issue

**Comment by bnasslahsen** [comment]
@maxdobler,

This behavior was a bug in previous versions. In version 2.5.0, the workaround is to explicitly declare `@RequestBody`.


```java
  @Operation(summary = "Upload new content", description = "Upload test content")
  @PostMapping(produces = APPLICATION_JSON_VALUE, consumes = MULTIPART_FORM_DATA_VALUE)
  HelloDto uploadContent(@RequestBody HelloUploadDto contentUploadDto) throws IOException;
```

**Comment by maxdobler** [comment]
Oh I see, thank you for the fast Feedback. It now works with `@RequestBody`. 👍
