### ISSUE TITLE
Kotlin value classes get an incorrect name

### ISSUE THREAD

**Issue by serandel** [springdoc/springdoc-openapi#2623]
**Describe the bug**

Springdoc is putting a random (?) suffix to the end of my fields when they're a Kotlin value class.

This is my DTO for this example:

```kotlin
@Serializable
data class Address(
    val streetName: String? = null,
    val postalCode: String? = null,
    val town: String? = null,
    val country: Country,
)

@JvmInline
@Serializable
value class Country(val isoCode: String)
```

Please, bear in mind that the other properties should also be value classes. I don't have it this way yet because I was researching this issue.

The problem is that when a schema is generated through

```kotlin
@Operation(summary = "foobar")
fun fooBar(
    @Parameter(schema = Schema(implementation = Address::class))
    address: Address
)
```

the `country` field is documented as being called `country-GvCqL24`, which is just wrong.

I've tested that KotlinX Serialization (which we're using instead of Jackson) is correctly defining the field name as `country` in the Json objects.

**To Reproduce**

- Spring Boot: 3.2.3
- SpringDoc: org.springdoc:springdoc-openapi-starter-webmvc-ui 2.5.0
- Expected description:
```json
      "Address": {
        "type": "object",
        "properties": {
          "streetName": {
            "type": "string"
          },
          "postalCode": {
            "type": "string"
          },
          "town": {
            "type": "string"
          },
          "country": {
            "type": "string"
          }
        }
      },
```
- Actual description:
```json
      "Address": {
        "type": "object",
        "properties": {
          "streetName": {
            "type": "string"
          },
          "postalCode": {
            "type": "string"
          },
          "town": {
            "type": "string"
          },
          "country-GvCqL24": {
            "type": "string"
          }
        }
      },
```
- Sample code: see above

**Expected behavior**

The field should be named as the field is in the enclosing object, in this case: "country". That it is a value class for better domain modelling in my Kotlin service should be irrelevant. (The type is already being translated to `string`, which is right, it's only the name what's being garbled.)

**Screenshots**

Here we can see the wrong name being generated.

![image](https://github.com/springdoc/springdoc-openapi/assets/1114574/9f79b7ac-d42a-40de-95f7-1eaa94ee073b)

![image](https://github.com/springdoc/springdoc-openapi/assets/1114574/cc8856ad-0d5f-4f71-ad86-69c3667e813f)

**Additional context**

This is a sample object when serialized from my controller:

```json
{
    "streetName":"Main St",
    "postalCode":"12345",
    "town":"Smallville",
    "country":"US"
}
```

**Comment by bnasslahsen** [comment]
@serandel,

Not reproducible.
Feel free to provide a [Minimal, Reproducible Example - with HelloController](https://stackoverflow.com/help/minimal-reproducible-example) that reproduces the problem.

This ticket will be closed, but can be reopened if your provide the reproducible sample.

**Comment by serandel** [comment]
(Well, asking for the issue to be reopened, of course. :D)

**Comment by serandel** [comment]
```json
{
  "openapi": "3.0.1",
  "info": {
    "title": "Foo API",
    "version": "v1"
  },
  "servers": [
    {
      "url": "http://localhost:8080",
      "description": "Generated server url"
    }
  ],
  "tags": [
    {
      "name": "Foo",
      "description": "Foo operations"
    }
  ],
  "paths": {
    "/foo/": {
      "post": {
        "tags": [
          "Foo"
        ],
        "summary": "Post a foo",
        "operationId": "postFoo",
        "parameters": [
          {
            "name": "foo",
            "in": "query",
            "required": true,
            "schema": {
              "$ref": "#/components/schemas/Foo"
            }
          }
        ],
        "responses": {
          "204": {
            "description": "Foo posted"
          }
        }
      }
    }
  },
  "components": {
    "schemas": {
      "Foo": {
        "type": "object",
        "properties": {
          "id": {
            "type": "string",
            "format": "uuid"
          },
          "bar-kCuQ4ew": {
            "type": "string"
          }
        }
      }
    }
  }
}
```

**Comment by bnasslahsen** [comment]
@serandel,

There is an important Note in the docs you are missing:
https://springdoc.org/#kotlin-support
![image](https://github.com/springdoc/springdoc-openapi/assets/13404829/a8d33f4a-2e39-45ad-8c3b-7915839b425c)

If you add, that should work better:
```kotlin
implementation("com.fasterxml.jackson.module:jackson-module-kotlin") 
```

**Comment by serandel** [comment]
Yes, I had missed that indeed. Good catch!

Now I just have to ask... would it be feasible and reasonable to ask, as a feature request, to not depend on Jackson and also work with KotlinX Serialization?

**Comment by bnasslahsen** [comment]
@serandel,

If you are having better proposal than `jackson-module-kotlin` and willing to submit a PR, we can have look to it!
