### ISSUE TITLE
Change or explain "Init duration for springdoc-openapi" logging level

### ISSUE THREAD

**Issue by artemptushkin** [springdoc/springdoc-openapi#2624]
**Is your feature request related to a problem? Please describe.**

I think [this logging should be in debug](https://github.com/springdoc/springdoc-openapi/blob/e14f9755bdca66f5ba44ac8e76d69ec361700ad8/springdoc-openapi-starter-common/src/main/java/org/springdoc/api/AbstractOpenApiResource.java#L390), and you better document how to enable this. I don't understand why apps with no issues here have it in the logs on every request.

**Describe the solution you'd like**

* The log level is DEBUG

**Comment by bnasslahsen** [comment]
@artemptushkin,

Thank you for your proposal.
There are no plans to change the logging level.

Feel free to change the logging level of `org.springdoc` on your end.

**Comment by artemptushkin** [comment]
@bnasslahsen okay but what's the idea to have it with info? Frome one request to another not many things change.. it looks like a debug info

**Comment by bnasslahsen** [comment]
@artemptushkin,

It is an informational message (INFO), which is typically used to show general operational information about the initialisation of the springdoc-openapi context.
This log line at the `INFO` level serves also to inform about the performance of the springdoc-openapi initialization process. 

It is part of good logging practices to ensure transparency, performance monitoring, and easier optimization of the application.
