### ISSUE TITLE
@RepositoryRestController endpoints and @RequestMapping endpoints are ignored

### ISSUE THREAD

**Issue by cndreiter** [springdoc/springdoc-openapi#263]
Endpoints both automatically generated and manually written within `@RepositoryRestController`s are not documented by springdoc-openapi.

Also, `@RequestMapping` endpoints seem to be ignored.

How are they supposed to be documented?

**Comment by kremers** [comment]
You need to use OAS3 annotations such as @Operation 

https://github.com/swagger-api/swagger-core/wiki/Swagger-2.X---Annotations

This is rather explicit over magic Auto generation that tends to have issues with new upstream functionality

**Comment by springdoc** [comment]
Hi, 

As @kremers  mentionned, you can use swagger-annotations to add OpenAPI description to `@RepositoryRestController` .

 For `@RequestMapping`, please add sample code.
 Note that only `@Controller` with `@ResponseBody` are deteced as Rest Controllers, if they don't declare `@RestController` annotation.
