### ISSUE TITLE
How can a Swagger document display the global return format normally after using the global unified format?

### ISSUE THREAD

**Issue by wendao8469759** [springdoc/springdoc-openapi#2631]
I used ResponseBodyAdvice for global unified encapsulation  
```java

@ControllerAdvice
@Hidden
public class GlobalResponseHandler implements ResponseBodyAdvice<Object> {

    @Override
    public boolean supports(MethodParameter returnType, Class<? extends HttpMessageConverter<?>> converterType) {
     
        return true;
    }

    @Override
    public Object beforeBodyWrite(Object obj, MethodParameter returnType, MediaType selectedContentType, Class<? extends HttpMessageConverter<?>> selectedConverterType, org.springframework.http.server.ServerHttpRequest request, ServerHttpResponse response) {
        return new BaseVo<>(obj);
    }
}
```
然后我的controller是这样写的
```java

@Tag(name = "useApi")
public interface UserApi {


    @Operation(summary = "useList")
    @PostMapping("/user/listNoPage")
    UserDetailVO listNoPage(@RequestBody @Validated UserListParam param);
}

```
The format returned after my actual request is
```java
{
  "code": "10000",
  "data": {
    "pid": 1,
    "loginAccount": "admin",
    "accountStatus": 2
  },
  "info": "处理成功！"
}
```
I expected Swagger to display in this format as well, but unfortunately, it only displays the number of instances of the UserDetailVO object and does not display the properties of BaseVo. I have tried many methods,
When I used Swagger 2 before, I solved it by writing plugins, but after Openapi3, I searched for a lot of information but couldn't find a solution

**Comment by bnasslahsen** [comment]
@wendao8469759,

Not reproducible.
Feel free to provide a [Minimal, Reproducible Example - with HelloController](https://stackoverflow.com/help/minimal-reproducible-example) that reproduces the problem.

This ticket will be closed, but can be reopened if your provide the reproducible sample.
