### ISSUE TITLE
The schema name generated by the inner class should add the outer class name by default

### ISSUE THREAD

**Issue by DanielLiu1123** [springdoc/springdoc-openapi#2632]
Look at the code below:

```java
@SpringBootApplication
public class QuickStartApp {

    public static void main(String[] args) {
        SpringApplication.run(QuickStartApp.class, args);
    }

    @RestController
    static class FruitController {

        @GetMapping("/apple")
        public List<Apple> apple() {
            return List.of();
        }

        record Apple(int id, String name) {}
    }

    @RestController
    static class PhoneController {

        @GetMapping("/iphone")
        public List<Apple> iphone() {
            return List.of();
        }

        record Apple(int id, String version) {}
    }
}
```

Check the openapi definition generated by the code above: `curl http://localhost:8080/v3/api-docs | jq '.components.schemas'`.

```json
{
  "Apple": {
    "type": "object",
    "properties": {
      "id": {
        "type": "integer",
        "format": "int32"
      },
      "version": {
        "type": "string"
      }
    }
  }
}
```

You will see that if the inner class names are the same, only one schema is generated. If you generate client code based on openapi, there will be a type mismatch problem.

There are two ways to solve this problem:
1. Add `@Schema(name = "PhoneController.Apple")`, but developers often don't know if the new code will have the same name. The framework should have a strong default behavior to avoid this problem.
2. Change the name of the inner class that has the same name, but doing this goes against the reason for using an inner class. One reason for using an inner class is to have a concise name.

One solution is to use the `<package>.<OuterClass>.<InnerClass>` naming to solve this problem, but this will expose the package structure, and Java's package naming style is not suitable for other languages. A better solution is to use the `<OuterClass>.<InnerClass>` naming, so the schema names generated here should be `FruitController.Apple` and `PhoneController.Apple`.

Example code is [here](https://github.com/DanielLiu1123/grpc-starter/blob/test-springdocs/examples/quick-start/src/main/java/grpcstarter/example/QuickStartApp.java).

I'm not sure if I should issue this to springdoc or [swagger-core](https://github.com/swagger-api/swagger-core), I post it here for now.

**Comment by bnasslahsen** [comment]
@DanielLiu1123,

Use: 

```properties
springdoc.use-fqn=true
```
