### ISSUE TITLE
The /v3/api-docs endpoint returns a JWT, causing Swagger to display the message “Unable to render this definition.”

### ISSUE THREAD

**Issue by mayipepsi** [springdoc/springdoc-openapi#2633]
**Describe the bug**

- The /v3/api-docs endpoint returns a JWT, causing Swagger to display the message “Unable to render this definition.”

**To Reproduce**

- springboot v3.3.0
- springdoc-openapi-starter-webmvc-ui v2.5.0
- spring-boot-starter-oauth2-resource-server v3.3.0

**Expected behavior**

- The expected result is that /v3/api-docs should respond with the normal JSON data.

**Screenshots**
<img width="1564" alt="image" src="https://github.com/springdoc/springdoc-openapi/assets/42597929/fb3633a6-74bf-4111-a3e4-b002a0177f7b">

<img width="1389" alt="image" src="https://github.com/springdoc/springdoc-openapi/assets/42597929/511cce28-e7a9-418d-85f1-77cd765b3de1">

**Comment by bnasslahsen** [comment]
@mayipepsi,

Not reproducible.
Feel free to provide a [Minimal, Reproducible Example - with HelloController](https://stackoverflow.com/help/minimal-reproducible-example) that reproduces the problem.

This ticket will be closed, but can be reopened if your provide the reproducible sample.

**Comment by ljp190** [comment]
我和你一样，遇到了这个问题，返回jwt
解决方案看这里:  https://springdoc.org/#why-am-i-getting-an-error-swagger-ui-unable-to-render-definition-when-overriding-the-default-spring-registered-httpmessageconverter
因为重写了mvc的序列化配置，导致swagger的返回不正常
把 ByteArrayHttpMessageConverter 补上，就可以了
![image](https://github.com/user-attachments/assets/c2f020bf-a15e-4805-9884-32dc2a3d5eea)
