### ISSUE TITLE
`@Hidden` Annotation Causes Swagger UI to Fail with "403 Forbidden" When Applied to All Controllers

### ISSUE THREAD

**Issue by shashiirk** [springdoc/springdoc-openapi#2635]
**Describe the bug**

When applying the `@Hidden` annotation to all controllers in a Spring Boot application, Swagger UI fails to load the API definition and returns a "403 Forbidden" error. This prevents access to the API documentation when all controllers are hidden.

**To Reproduce**

- Spring Boot version: 3.2.4
- springdoc-openapi-starter-webmvc-ui version: 1.5.10 
- Add multiple controllers and apply the `@Hidden` annotation to all of them.
- Now load the swagger docs page, it will say "Failed to load API definition."

**Expected behavior**

Swagger UI should handle the case where no endpoints are available for documentation gracefully, either by displaying a message indicating no endpoints are documented or by providing a default response.

**Screenshots**
![image](https://github.com/springdoc/springdoc-openapi/assets/48406108/7d977457-76fa-433b-8ef8-6252ab58f17a)

**Additional context**
This issue occurs only when the `@Hidden` annotation is applied to all controllers. If at least one controller is not hidden, the Swagger UI loads without any issues. This behavior is not intuitive and could be improved to handle cases where no endpoints are available for documentation.

**Comment by bnasslahsen** [comment]
@shashiirk,

Not reproducible.
Feel free to provide a [Minimal, Reproducible Example - with HelloController](https://stackoverflow.com/help/minimal-reproducible-example) that reproduces the problem.

This ticket will be closed, but can be reopened if your provide the reproducible sample.
