### ISSUE TITLE
Schema quality reduced after migrating from 2.3.0 to 2.6.0

### ISSUE THREAD

**Issue by bay73** [springdoc/springdoc-openapi#2639]
**Describe the bug**

We have a class hierarchy describing requests model with possibility of recursive elements. Version springdoc-openapi 2.3.0 produced pretty clean and understandable schema while in version 2.6.0 schema became more complex, includes unnecessary and repeated elements and causes swagger UI to hang when trying to expand endpoint definition. 
In the attached screenshots you can see how schema looked before and after migration.

**To Reproduce**

[springdoc_demo.zip](https://github.com/user-attachments/files/16108509/springdoc_demo.zip)

An example gradle project to to reproduce an issue is in the attach zip file. Unpack, build and run the application, navigate to `http://localhost:8080/swagger-ui/index.html` and see the incorrect schema in Swagger UI.

**Expected behavior**

Expected schema presented in correct_schema.json. Actual schema generated by version 2.6.0 is in wrong_schema.png
[wrong_schema.json](https://github.com/user-attachments/files/16108507/wrong_schema.json)
[correct_schema.json](https://github.com/user-attachments/files/16108508/correct_schema.json)

**Screenshots**
![Wrong_schema](https://github.com/springdoc/springdoc-openapi/assets/3797332/f9b3300e-3a67-443f-9eb9-8ddef0ead768)
![Correct_schema](https://github.com/springdoc/springdoc-openapi/assets/3797332/de082b89-ef97-4633-b33e-80c1896d73ac)

**Comment by solpower** [comment]
demo-spring-boot-3-webmvc   The data type is clearly visible in  Schema
![image](https://github.com/user-attachments/assets/cbb5cad4-3b24-44b9-a4ca-eb43564fab13)

but in my springdoc   Data types are collapsed，
 All data types are folded. It is too troublesome to open them one by one.  how to solve it 
 springdoc-openapi-starter-webmvc-ui  version  2.6.0
 spring.boot.version  3.3.2
![image](https://github.com/user-attachments/assets/9e0fb79c-5a07-45fd-8ee7-0ea338bfbbf2)

**Comment by jimirocks** [comment]
I hit this issue as well, most probably it's caused by this https://github.com/springdoc/springdoc-openapi/commit/497bfae781a2e637037892d333f625595675531c

**Comment by bnasslahsen** [comment]
@bay73,

The 2.6.0 makes sure we have the exact `oneOf` description you have in your schema description.
This is the comparison between the schemas for 2.5.0 and 2.6.0:

<img width="1534" alt="image" src="https://github.com/user-attachments/assets/7b853d81-d9e6-4986-9ab5-687d29b3d23d">

Not sure we can do more at this stage.
