### ISSUE TITLE
"Byte" property is mapped to "string" instead of "integer"

### ISSUE THREAD

**Issue by albertomozzone-spaceinformatica** [springdoc/springdoc-openapi#2641]
**Describe the bug**
In the "swagger-ui/index.html" a "Byte" property is shown with the type "string" instead of "integer".
In the "/v3/api-docs", the same property is shown as:
"type": "string"
"format": "byte"
I'd expect it to be:
"type": "integer"
"format": "byte"

**To Reproduce**
Create a Spring Boot project with a single Controller which exposes a POJO having a "Byte" property:
private Byte byte;
Navigate to the "/swagger-ui/index.html" and "/v3/api-docs" and observe that it is treated as a "string".

**Expected Behavior**
A "Byte" property should be treated as "integer".

Versions:
Spring Boot 3.2.4
SpringDoc 2.6

**Comment by albertomozzone-spaceinformatica** [comment]
Workaround: add "@Schema(implementation = Integer.class)" before each "private Byte prop;".

**Comment by bnasslahsen** [comment]
@albertomozzone-spaceinformatica 

This is considered as incomplete enhancement request.
You need to provide all the points mentioned in the section: Using GitHub Issues

https://github.com/springdoc/springdoc-openapi/blob/main/CONTRIBUTING.adoc
This ticket will be closed, but can be reopened if your provide all the elements.
