### ISSUE TITLE
wrong spring-boot version in v1.8.0 release note

### ISSUE THREAD

**Issue by noootime** [springdoc/springdoc-openapi#2644]
**Describe the bug**
Hi, I found there is wrong recording of spring-boot's version in [v1.8.0 Release Note](https://github.com/springdoc/springdoc-openapi/releases/tag/v1.8.0)

**Expected behavior**

`v1.8.0` upgraded **spring-boot** version from `v2.7.10` to `v2.7.18`, not `v2.7.14`

**Screenshots**

![image](https://github.com/springdoc/springdoc-openapi/assets/18703385/77b38abe-6526-4260-9e2a-c4f584ae1b9f)

---

![image](https://github.com/springdoc/springdoc-openapi/assets/18703385/abfd9f89-e3dd-4e56-952a-87f72bcfa876)

**Comment by bnasslahsen** [comment]
@noootime,

Corrected
