### ISSUE TITLE
spring6的路径匹配模式下接口调试无法设置值。

### ISSUE THREAD

**Issue by jiangqiang1996** [springdoc/springdoc-openapi#2648]
下面这种写法在对应的接口中在线执行会有问题，无法设置path的值。

    @Operation(summary = "test")
    @GetMapping(value = {"/test/{*path}"})
    public Result<String> test(@PathVariable String path) {
        return Result.ok(path);
    }

![image](https://github.com/user-attachments/assets/92dfd6fa-7876-4fa6-9e77-1e14ed673597)

左侧写的不是参数的值么，但是提交的却是代码中写的路径占位符。

**Comment by bnasslahsen** [comment]
@jiangqiang1996,

Please create issues in English!
