### ISSUE TITLE
Missing Response Content - Referencing issue #212

### ISSUE THREAD

**Issue by sjw0010** [springdoc/springdoc-openapi#265]
Hello,
Unfortunately the issues is still not fixed in the newest version quoted below. Still getting an empty list of Media Types in the UI when using Meta Annotations. If you guys need any more details please let me know. The detailed explanation is in issue #212 with pictures.

Thanks so much.

-------------------------------

Hi, 

 A fix for this issue will be available on v1.2.16;

_Originally posted by @springdoc in https://github.com/springdoc/springdoc-openapi/issues/212#issuecomment-560930968_

**Comment by kremers** [comment]
https://github.com/swagger-api/swagger-core/wiki/Swagger-2.X---Annotations#operation-annotations

You need to add responses in the @Operation with @APIResponse and content = @Content(mediaType = "application/json",

See documentation in the link

**Comment by sjw0010** [comment]
Okay, I will give that a try.
Thanks!

On Dec 14, 2019 4:55 AM, Martin Kremers <notifications@github.com> wrote:

https://github.com/swagger-api/swagger-core/wiki/Swagger-2.X---Annotations#operation-annotations

You need to add responses in the @operation<https://github.com/operation> with @APIResponse and content = @content<https://github.com/content>(mediaType = "application/json",

See documentation in the link

**Comment by springdoc** [comment]
#212 is already fixed. You can have a look at the related test.

If you have more questions, please provide more information in order to go further:
If you are still having more issues: Please make sure you provide:
- The sample (java) code to reproduce your issue.
- The result you have got in OpenAPI format
- The expected Result
