### ISSUE TITLE
The openapi interface generated by the javadoc plug-in is not a Chinese comment, but an English class name. I hope I can optimize whether comments can be used (for example, the first line of the comment is used as a name)

### ISSUE THREAD

**Issue by JavaLionLi** [springdoc/springdoc-openapi#2651]
**Describe the bug**

- If you are reporting a bug, please help to speed up problem diagnosis by providing as
  much information as possible:
- A clear and concise description of what the bug is: the title of an issue is not enough

![image](https://github.com/user-attachments/assets/55f84edb-3f40-48c2-a67d-f99be7ee7566)
![image](https://github.com/user-attachments/assets/de3c7878-5b4a-4574-ba71-8822c6ef7ed3)

Name is a class name, no comment is used.
I want to set the name to comment.

**To Reproduce**

- What version of spring-boot you are using?
- What modules and versions of springdoc-openapi are you using?
- What is the actual and the expected result using OpenAPI Description (yml or json)?
- Provide with a sample code (HelloController) or Test that reproduces the problem

**Expected behavior**

- A clear and concise description of what you expected to happen.
- What is the expected result using OpenAPI Description (yml or json)?

**Screenshots**

**Additional context**

**Comment by Free-LZJ** [comment]
You can refer to this implementation: [RuoYi-Vue-Plus](https://github.com/dromara/RuoYi-Vue-Plus/tree/5.X/ruoyi-common/ruoyi-common-doc/src/main/java/org/dromara/common/doc)

**Comment by JavaLionLi** [comment]
> You can refer to this implementation: [RuoYi-Vue-Plus](https://github.com/dromara/RuoYi-Vue-Plus/tree/5.X/ruoyi-common/ruoyi-common-doc/src/main/java/org/dromara/common/doc)

I am the author of RuoYi-Vue-Plus
I hope the official will take care of this

**Comment by Free-LZJ** [comment]
!!!没注意ID撞到大佬了

**Comment by bnasslahsen** [comment]
If there any enhancement for the javadoc generation, feel free to report it to https://github.com/dnault/therapi-runtime-javadoc
