### ISSUE TITLE
Support the spring web annotation @BindParam in @ParameterObject

### ISSUE THREAD

**Issue by ty-vincenthung** [springdoc/springdoc-openapi#2652]
**Is your feature request related to a problem? Please describe.**

- I would like to utilize the newly introduced annotation `@BindParam` in Spring Framework 6.1. 

**Describe the solution you'd like**

- Currently, to align the behaviours we MUST add `@Parameter(name = "custom-name")` and `@BindParam("custom-name")` at the same time. Which I would like to annotate the @BindParam to have the same behaviours on annotating both to avoid duplications.

**Describe alternatives you've considered**

- N/A

**Additional context**

- N/A

**Comment by Lifeclue** [comment]
I hope so too.

**Comment by bnasslahsen** [comment]
@ty-vincenthung,

This is incomplete enhancement request.
Feel free to provide a [Minimal, Reproducible Example - with HelloController](https://stackoverflow.com/help/minimal-reproducible-example) that explains what you are really expecting.

This ticket will be closed, but can be reopened if your provide the complete example.
