### ISSUE TITLE
Nested oneOf and allOf when using oneOf with @JsonSubTypes

### ISSUE THREAD

**Issue by ghovhannesVM** [springdoc/springdoc-openapi#2655]
**Describe the bug**
When I use @JsonSubTypes with @Schema(oneOf = {..}), the model schema shows infinite nested oneOf and allOf. When I remove @JsonSubTypes from the parent model, everything works well.  Am i doing something wrong or is this expected behaviour ?

**Expected behavior**
The expected behavior is to show only the oneOf field. After selecting one of the child classes, it should stop expanding.

**Screenshots**
The structure of the model 
![Screenshot 2024-07-23 at 18 10 25](https://github.com/user-attachments/assets/bbe93918-5a90-4698-be54-7e1655ba5fee)

The output
![Screenshot 2024-07-23 at 18 13 47](https://github.com/user-attachments/assets/0e93ea25-e5cc-4adb-954c-c82d11fe2445)

**Versions**
- springdoc-openapi-starter-webmvc-ui 2.1.0

**Comment by LouisXhaferi** [comment]
Also mentioned in #2575 and #2577, which have since been closed

> We ran into a similar (maybe the same?) issue when trying to use polymorphic types, like:
> 
> ```kotlin
> @JsonTypeInfo(use = NAME, include = PROPERTY, property = DISCRIMINATOR_PROPERTY)
> @JsonSubTypes(
>     Type(value = Activate::class, name = ACTIVATE)
> )
> @Schema(
>     subTypes = [Activate::class],
>     oneOf = [Activate::class],
>     discriminatorProperty = DISCRIMINATOR_PROPERTY,
>     discriminatorMapping = [
>         DiscriminatorMapping(value = ACTIVATE, schema = Activate::class)
>     ]
> )
> sealed interface PolymorphicEvent {
>     @Schema(requiredProperties = [DISCRIMINATOR_PROPERTY])
>     @SchemaProperty(name = DISCRIMINATOR_PROPERTY, schema = Schema(allowableValues = [ACTIVATE]))
>     data object Activate : PolymorphicEvent
> 
>     companion object {
>         const val DISCRIMINATOR_PROPERTY = "type"
>         const val ACTIVATE = "ACTIVATE"
>     }
> }
> ```
> 
> Defining this in 2.3.0 would work, but totally broke our Schema view in SwaggerUI after 2.5.0, where the `oneOf` definition just references itself recursively forever. (This might even be worth a second issue)
> 
> ![image](https://private-user-images.githubusercontent.com/52397677/325955600-30adb860-d060-4552-aafa-748f684a1beb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE5ODE2NzksIm5iZiI6MTcyMTk4MTM3OSwicGF0aCI6Ii81MjM5NzY3Ny8zMjU5NTU2MDAtMzBhZGI4NjAtZDA2MC00NTUyLWFhZmEtNzQ4ZjY4NGExYmViLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI2VDA4MDkzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA0M2Q5NWNmNGFmN2I5OGEwNmViMzU4MWVlZWJiMzY5MmFlZDBjMWYzMGVlYzhjYTg3ZDVhMWY0MjdhYzAxYmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.QXxGyFDFrEf42XK4bsuNu74BKC6Hp48iTpPBeszWyTk)

**Comment by ilaoud** [comment]
I have the same probleme  in 2.6.0

**Comment by Nhattd97** [comment]
Do you have any updates on this? Thanks!

**Comment by bnasslahsen** [comment]
@ghovhannesVM,

Not reproducible.
Feel free to provide a [Minimal, Reproducible Example - with HelloController](https://stackoverflow.com/help/minimal-reproducible-example) that reproduces the problem.

This ticket will be closed, but can be reopened if your provide the reproducible sample.
