### ISSUE TITLE
Add support for javadoc throws annotation

### ISSUE THREAD

**Issue by ibrahim7860** [springdoc/springdoc-openapi#2658]
The current Javadoc integration with springdoc is great, but it would be amazing if it would resolve the @throws javadoc tag to be @ApiResponse annotation. Is this a feature that is already currently implemented, and if not is it possible to implement this?

**Comment by bnasslahsen** [comment]
@ibrahim7860,

There are no plans to support this enhancement request.
If you believe, it will be useful for the community, please feel free to propose a PR
