### ISSUE TITLE
Swagger UI Display Options Support

### ISSUE THREAD

**Issue by thokuest** [springdoc/springdoc-openapi#266]
First of all, let me say thank you for this project. It's really a blessing!

swagger-ui supports [configuration](https://github.com/swagger-api/swagger-ui/blob/master/docs/usage/configuration.md) options that affect the display, such as being able to _explore_ user supplied OpenAPI specs. My question is, can I supply these via `springdoc-openapi`?

Things that bug me right now:

* petstore is opened by default right now if I remove the `url` query param
* Validator is applied which required web access I guess
* Top bar is visible which allows users to explore any APIs they want

Thank you!

**Comment by springdoc** [comment]
Hi, 

 For the url petstore: Here is the answer: https://github.com/springdoc/springdoc-openapi/issues/43
 Same answer applies to Validator.

  You can have a look at the follwing section of the FAQ:  **How can i configure Swagger UI?**
- https://springdoc.github.io/springdoc-openapi-demos/faq.html

**Comment by thokuest** [comment]
Thanks for RTFM pointer, @springdoc. I'm pretty sure I tried it but it was ignored somehow. However, it works now as expected.

However, users are still able to set (remove) query parameters on their own, hence getting all the default features of Swagger UI back. I guess the only thing to have this fixed is to replace `org.webjars:swagger-ui` with a custom build?

**Comment by thlaegler** [comment]
> Hi,
> 
> For the url petstore: Here is the answer: #43
> Same answer applies to Validator.
> 
> You can have a look at the follwing section of the FAQ: **How can i configure Swagger UI?**
> 
> * https://springdoc.github.io/springdoc-openapi-demos/faq.html

The link above seems to be broken. This is probably the correct link: https://springdoc.org/faq.html#how-can-i-configure-swagger-ui
