### ISSUE TITLE
【Feat】oneOf supports nested classes

### ISSUE THREAD

**Issue by shaunhurryup** [springdoc/springdoc-openapi#2666]
### Background
When a route is invoked, it might succeed or fail. In case of failure, our business logic uses different error codes to identify the error range. For example:

```json
{
	"code": 100001,
	"message": "User Not Found"
}
```

To reflect various exceptional states of the interface in the OpenAPI documentation, we need to define these exceptions on the routes. One way I know to implement this is based on the oneOf attribute:

```kt
@ApiResponse(
    content = @Content(
        schema = @Schema(
            oneOf = {UserDto.class, UserNotFound.class}
        )
    )
)
```

### Problem
However, the oneOf attribute must consist of const classes. If you use nested classes as the parameters for the schema, it will result in a syntax error.

![CleanShot 2024-08-01 at 21 08 47@2x](https://github.com/user-attachments/assets/6d570560-4da6-42db-bacf-144a87c0bf84)

In actual development, nested response classes are quite common, and we even have general response wrappers based on pagination, such as `CommonResult<Pagination<UserDto>>`. The oneOf attribute can't handle this, and you must declare each class separately, which becomes verbose.

### Solution

1. Add annotations to classes that need nested wrapping in the @ApiResponse.

```kt
@AllowNestWrapper({ CommonResult.class, Pagination.class })
class UserDto {}

@ApiResponse(
    content = @Content(
        schema = @Schema(
            oneOf = {UserDto.class}
        )
    )
)
public ResponseEntity<CommonResult<Pagination<UserDto>>> getUsers() {}
```

In the returned schema, it should display `CommonResultPaginationUserDto` instead of `UserDto`.

Is there a solution I might not be aware of to resolve this? Otherwise, this will be my reason for creating a merge request.

> By the way, I use springboot 2 = =

**Comment by bnasslahsen** [comment]
@shaunhurryup,

This option should be added in [swagger-core](https://github.com/swagger-api/swagger-core) level, as `ApiResponse` is a class from this project.
