### ISSUE TITLE
Swagger UI Missing "Choose File" Button for File Upload with springdoc.api-docs.version=openapi_3_1

### ISSUE THREAD

**Issue by m-titov** [springdoc/springdoc-openapi#2667]
When using springdoc.api-docs.version=openapi_3_1, the Swagger UI does not display the "Choose File" button for file upload endpoints. Instead, it shows a text area for inputting the Request Body. This issue is observed for both endpoints in the provided sample code. In contrast, with springdoc.api-docs.version=openapi_3_0, the "Choose File" button appears as expected.
To Reproduce

Configuration:

Configure your application.properties with the following settings:
properties

```spring.application.name=springdocbug
springdoc.api-docs.path=/doc
springdoc.api-docs.version=openapi_3_1
springdoc.auto-tag-classes=false
springdoc.nullable-request-parameter-enabled=true
springdoc.writer-with-order-by-keys=true
springdoc.swagger-ui.display-request-duration=true
springdoc.swagger-ui.disable-swagger-default-url=true
springdoc.swagger-ui.show-extensions=true
springdoc.swagger-ui.show-common-extensions=true
springdoc.swagger-ui.try-it-out-enabled=true
```

Use the following Java code for file upload endpoints:
```java
package demo;

import org.springframework.http.MediaType;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.bind.annotation.RestController;
import org.springframework.web.multipart.MultipartFile;

@RestController
public class FileController {

    @PostMapping(value = "/file1", consumes = MediaType.MULTIPART_FORM_DATA_VALUE)
    public String handleFileUpload(MultipartFile file) {
        return file.getOriginalFilename();
    }

    public record FileUpload(@RequestPart MultipartFile file) { }

    @PostMapping(value = "/file2", consumes = MediaType.MULTIPART_FORM_DATA_VALUE)
    public String handleFileUpload2(FileUpload fileUpload) {
        return fileUpload.file().getOriginalFilename();
    }
}
```

Add the following dependencies and plugin configuration:
```gradle
plugins {
    id 'java'
    id 'org.springframework.boot' version '3.3.2'
    id 'io.spring.dependency-management' version '1.1.6'
    id("org.springdoc.openapi-gradle-plugin") version "1.9.0"
}

group = 'some'
version = '0.0.1-SNAPSHOT'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

repositories {
    mavenCentral()
}

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation "org.springdoc:springdoc-openapi-starter-webmvc-ui:2.6.0"
    implementation "com.github.therapi:therapi-runtime-javadoc:0.15.0"
}

openApi {
    apiDocsUrl.set("http://localhost:8080/doc.yaml")
    outputDir.set(layout.buildDirectory.dir("doc"))
    outputFileName.set("doc.yaml")
    customBootRun {
        workingDir.set(project.rootProject.projectDir) // TODO remove it as soon as https://github.com/springdoc/springdoc-openapi-gradle-plugin/issues/150 is fixed
    }
}

```

**Observation:**

Access Swagger UI at http://localhost:8080/swagger-ui.html.
For the /file1 and /file2 endpoints, observe that the Swagger UI displays a text area for inputting the Request Body instead of the "Choose File" button.
Expected behavior

For endpoints that support file uploads, Swagger UI should display the "Choose File" button, allowing users to select and upload files through the Swagger interface.

Screenshots
![image](https://github.com/user-attachments/assets/11c7876c-37da-481e-9eea-cc47371578ae)

Additional context

The issue is specific to `springdoc.api-docs.version=openapi_3_1`
With `springdoc.api-docs.version=openapi_3_0`, the Swagger UI correctly displays the "Choose File" button for file upload endpoints.
It may be related to changes or differences in how OpenAPI 3.1 specifications handle file uploads compared to OpenAPI 3.0.

**Comment by m-titov** [comment]
It looks like it works for `/file1` endpoint if we make the following changes:
<img width="1044" alt="image" src="https://github.com/user-attachments/assets/4f7c6356-0d58-4ae6-b69e-55e1699ebdff">
<img width="763" alt="image" src="https://github.com/user-attachments/assets/2c179a1a-8620-4122-85f5-a394cc1510dc">

**Comment by bnasslahsen** [comment]
@m-titov,

The generated OpenAPI spec by `springdoc-openapi` is correct.
This is [swagger-ui](https://github.com/swagger-api/swagger-ui) issue that you can report.

**Comment by Mectron2** [comment]
Thank you, my time saver
