### ISSUE TITLE
@RequestAttribute parameter appears in the UI

### ISSUE THREAD

**Issue by derlin** [springdoc/springdoc-openapi#267]
**Context**

I have a filter that adds attributes to the HTTP requests that are derived from headers and other things. In my controllers, I have endpoints that uses these attributes, like this:

```kotlin
@GetMapping("/{id}")
fun getById(
    @PathVariable(value = "id") id: Long,
    @RequestAttribute(value = "userid") userId: Int, /* <= set in a filter */
    @RequestParam(name = "writable", required = false) writable: Boolean = false
) { /* ... */ }
```

The generated UI is:

![Screenshot 2019-12-14 at 17 47 17](https://user-images.githubusercontent.com/5463445/70851806-45056600-1e9a-11ea-981c-e7ca5f8f5afb.png)

**Problem**

I expect the `@RequestAttribute` to be ignored by OpenAPI, since it is an internal attribute that the client ignores. But it is still present in the interface (which is misleading) and marked as required (so the user cannot use *try it out*).

**Questions**

1. Is this a normal behavior ?
2. How can I mark a method parameter as *hidden* (and if possible globally, since the same attribute is used in many places) ? 

**versions**

* `org.springframework.boot` => 2.2.1.RELEASE
* `org.springdoc:springdoc-openapi-ui` => 1.2.17

**Comment by f12998765** [comment]
I tested in 1.2.33, the parameters of RequestAttribute annotation were not ignored .

Looking at the modified source code, it was found that RequestAttribute should not be added to PARAM_TYPES_TO_IGNORE, it is an annotation.

Finally, I achieved my goal by customizing the RequestBuilder.

```java
    @Bean
    @Primary
    RequestBuilder myRequestBuilder(GenericParameterBuilder parameterBuilder, RequestBodyBuilder requestBodyBuilder, OperationBuilder operationBuilder, Optional<List<OperationCustomizer>> customizers, Optional<List<ParameterCustomizer>> parameterCustomizers) {
        return new RequestBuilder(parameterBuilder, requestBodyBuilder, operationBuilder, customizers, parameterCustomizers) {
            @Override
            protected boolean isParamToIgnore(Parameter parameter) {
                if (parameter.isAnnotationPresent(RequestAttribute.class)) {
                    return true;
                }
                return super.isParamToIgnore(parameter);
            }
        };
    }
```

**Comment by ddeya** [comment]
This issue wasn't solved, can we re-open the issue, I can work on adding a "annotation based" ignore mechanism.

**Comment by bnasslahsen** [comment]
@ddeya, 

 It can be reopened if you add what is wrong for you, by respecting the contribution guide:
If you are reporting a bug, please help to speed up problem diagnosis by providing as much information as possible:
 - You need to describe your context (the title of an issue is not enough)
 - What version of spring-boot you are using?
 - What modules and versions of springdoc-openapi are you using?
 - What are the actual and the expected result using OpenAPI Description (yml or json)?
 - **Provide with a sample code (HelloController) or Test that reproduces the problem**

**Comment by ddeya** [comment]
Perfect, really fast.
