### ISSUE TITLE
Default Media Type application/xml is selected by default

### ISSUE THREAD

**Issue by x-carrier** [springdoc/springdoc-openapi#2671]
**Describe the bug**
I wrote an interface,produces = {"application/json", "application/xml"}, consumes = {"application/json", "application/xml"}
![image](https://github.com/user-attachments/assets/702119fc-02d3-40e2-9d03-23a223409702)
When the springdoc version was 2.5.0, application/json was selected by default
![image](https://github.com/user-attachments/assets/f9542eb2-4823-4398-ba6d-4876a05073c0)
![image](https://github.com/user-attachments/assets/8770343c-68e6-4204-b9d0-de41042523d3)
But when I switched to 2.6.0, the default choice changed to application/xml
![image](https://github.com/user-attachments/assets/2284d012-11ec-4bc1-a1cf-2ec0d4db6028)
![image](https://github.com/user-attachments/assets/5b679fdb-9582-4294-852a-c416de8a6bf9)
I haven't changed anything except the version number of springdoc and I would like to know how to configure the Media type to return to the default application/json value

**Comment by limehee** [comment]
When referring to the [5.1. springdoc-openapi core properties section](https://springdoc.org/#springdoc-openapi-core-properties), you can change the media type using `springdoc.default-consumes-media-type` and `springdoc.default-produces-media-type`.

Please add the following settings to see if they resolve the issue:
```properties
springdoc.default-consumes-media-type=application/json
springdoc.default-produces-media-type=application/json
```
```yaml
springdoc:
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
```
Can you check if the same issue persists after adding these settings?

**Comment by x-carrier** [comment]
> When referring to the [5.1. springdoc-openapi core properties section](https://springdoc.org/#springdoc-openapi-core-properties), you can change the media type using `springdoc.default-consumes-media-type` and `springdoc.default-produces-media-type`.
> 
> Please add the following settings to see if they resolve the issue:
> 
> ```ini
> springdoc.default-consumes-media-type=application/json
> springdoc.default-produces-media-type=application/json
> ```
> 
> ```yaml
> springdoc:
>   default-consumes-media-type: application/json
>   default-produces-media-type: application/json
> ```
> 
> Can you check if the same issue persists after adding these settings?
Yes, I added the configuration, changed it to version 2.6.0, and forced the browser to clear the cache refresh, but the result was still application/xml selected by default
![image](https://github.com/user-attachments/assets/898127f2-4e68-4ed5-9591-fc69bbe3bb9d)
![image](https://github.com/user-attachments/assets/8d31d5ea-1183-4929-a230-19dffcc228e3)
And when I rolled back to version 2.5.0, I reverted back to the default selection of application/json

**Comment by limehee** [comment]
@bnasslahsen I have identified the issue and submitted a PR to fix it. The problem with the media type order not being preserved, causing the default type not to be prioritized, has been addressed by using `LinkedHashSet`. I would appreciate it if you could review the PR.

#2672 

Thank you.

**Comment by cmark** [comment]
We ran into this issue just now and are happy to see a resolution for it already merged into main. May I ask what is the next release date for springdoc that contains this fix? Thanks!

**Comment by bnasslahsen** [comment]
@cmark,

Most probably, after spring-boot 3.4 goes GA: https://calendar.spring.io/
