### ISSUE TITLE
ParameterObject SubObject required issue

### ISSUE THREAD

**Issue by deblockt** [springdoc/springdoc-openapi#2673]
**Describe the bug**

I use the annotation @ParameterObject to bind GET request query params. 
My query params DTO looks like 
```
public record SearchParamsDTO(
            String orderId,
            @Valid StoreDTO store
    ) {
    }

public record StoreDTO(
        @NotBlank @Schema(description = "The store's code") String code,
        @NotNull @Schema(description = "The business unit of the store") BusinessUnit businessUnit,
        @NotNull @Schema(description = "The store's country") Country country) {
}
```

Using this DTO generate a swagger with the following query params: 

<img width="646" alt="Capture d’écran 2024-08-09 à 08 48 18" src="https://github.com/user-attachments/assets/7a5a37e1-8377-4193-94ed-78af2bd336c2">

In the generated query params `store.code` `store.businessUnit` and `store.country` are marked as mandatory, but in the spring behavior params are not mandatory. 
The spring behavior is "If one of store.code` `store.businessUnit` and `store.country` is set, so the all store query params are mandatory".

**To Reproduce**

- What version of spring-boot you are using? Spring 6.1.0
- What modules and versions of springdoc-openapi are you using? 2.5.0
- What is the actual and the expected result using OpenAPI Description (yml or json)?
- Provide with a sample code (HelloController) or Test that reproduces the problem 
``` java
    @Operation()
    @ApiResponse(responseCode = "200", description = "The result")
    @GetMapping("/test")
    public ResponseEntity<Object> search(
            @Valid @ParameterObject SearchParamsDTO params
    ) {}
```

**Comment by limehee** [comment]
This issue arises because `@NotBlank` and `@NotNull` annotations are interpreted as required fields when generating OpenAPI documentation. If a query parameter is not mandatory but needs validation when provided, you can resolve this by:

1. Using a custom validator, or
2. Implementing manual validation logic.

**Comment by deblockt** [comment]
Why not update the springdoc code so that it applies the same rules as Spring? 
I don't want to add a custom validation process whereas spring already validates as I want.

**Comment by bnasslahsen** [comment]
@deblockt,

The following annotations, converts to required fields:

`ANNOTATIONS_FOR_REQUIRED = { "NotNull", "NonNull", "NotBlank", "NotEmpty" }`

**Comment by deblockt** [comment]
I'm not agree with you response since the generated documentation don't respect the real spring behavior. 
We should have a way to have a correctly generated documentation who reflect the real rules
