### ISSUE TITLE
Swagger ui can be accessed in the browser, but cannot be accessed in<iframe>

### ISSUE THREAD

**Issue by Free-LZJ** [springdoc/springdoc-openapi#2675]
**Describe the bug**

Swagger ui had been working normally until one time when I wanted it to be displayed in the browser inline frame. The browser pop-up prompted:Unable to infer base url.

**To Reproduce**

- springboot: 2.7.18
- springdoc-openapi-ui: 1.6.15
- springdoc-openapi-webmvc-core: 1.6.15
- springdoc-openapi-javadoc: 1.6.15

Sample code:
```<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

    <iframe src="http://localhost:8080/swagger.html" frameborder="0"></iframe>

</body>
</html>
```

**Expected behavior**
It is possible to access the address of swagger ui directly in the browser:
![image](https://github.com/user-attachments/assets/87339eaa-2453-4b93-9f9b-5f7d7351e898)
 but accessing it in the browser's inline framework will result in an exception:
![image](https://github.com/user-attachments/assets/b5b7ac9d-fd7e-4d3b-a74b-ff81d721d643)

I am puzzled about the difference between accessing Swagger ui in these two situations!

**Comment by Free-LZJ** [comment]
> ** 描述Bug**
> 
> Swagger ui一直工作正常，直到有一次我想让它显示在浏览器的内联框架中。浏览器弹出提示：无法推断基网址。
> 
> ** 再现**再现行为的步骤：
> 
> * springboot：2.7.18
> * springdoc-openapi-ui：1.6.15
> * springdoc-openapi-webmvc-core：1.6.15
> * springdoc-openapi-javadoc：1.6.15
> 
>  示例代码： `
> 
> ```
> <iframe src=“http://localhost：8080/swagger.html”frameborder=“0”></iframe>
> ```
> 
> ** 预期行为**可以直接在浏览器中访问swagger ui的地址： ![image](https://private-user-images.githubusercontent.com/121116847/356885254-87339eaa-2453-4b93-9f9b-5f7d7351e898.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMzODgzMTUsIm5iZiI6MTcyMzM4ODAxNSwicGF0aCI6Ii8xMjExMTY4NDcvMzU2ODg1MjU0LTg3MzM5ZWFhLTI0NTMtNGI5My05ZjliLTVmN2Q3MzUxZTg5OC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxMVQxNDUzMzVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05NzZkY2IwNGRmNTljZWY4YmIyYjMxODIxYzdhYWE5MzQwMWFmYjVjZTFiNzdmNzVjYTcxZGM0MmJkMmI0MWY4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Zl2vuqdoHRlGKXRD86iaGqq-wAD-aeG7fX4QbFsvTb0)但在浏览器的内联框架中访问它将导致异常： ![image](https://private-user-images.githubusercontent.com/121116847/356886180-b5b7ac9d-fd7e-4d3b-a74b-ff81d721d643.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMzODgzMTUsIm5iZiI6MTcyMzM4ODAxNSwicGF0aCI6Ii8xMjExMTY4NDcvMzU2ODg2MTgwLWI1YjdhYzlkLWZkN2UtNGQzYi1hNzRiLWZmODFkNzIxZDY0My5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxMVQxNDUzMzVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05Mjk0NWIyZDc1ZmEzOWRjMzk3ZDYxNjFmNTBiOTY4YWY5ZjdkZjEyMTM2Nzk5ZjRjNTllZTYzZWUzOTkxOTBkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.HCYEa8vWSmpX5SuVO85EikySANAsB_aD6T7FVdkdDL4)
> 
> 我对这两种情况下访问Swagger ui的区别感到困惑！

**Comment by bnasslahsen** [comment]
@Free-LZJ,

sprindoc-openapi is responsible for generating OpenAPI specification.
The issue you are reporting is `swagger-ui` related.
If you have any issues, feel free ask the[ swagger-ui](https://github.com/swagger-api/swagger-ui) team instead.
