### ISSUE TITLE
Annotating Map properties not working

### ISSUE THREAD

**Issue by aleksandarvanced** [springdoc/springdoc-openapi#2678]
**Describe the bug**
I have a Java class that is using Open API Spring library and I have the following property
`private Map<String, BigDecimal> rates;`

I am using the following `@Schema` annotation to achieve the BigDecimal value of the map to be "displayed" as a String in Swagger
```
 @Schema(requiredMode = Schema.RequiredMode.REQUIRED, type = "object",
            additionalPropertiesSchema = {
                    @StringToClassMapItem(key = "rateX", value = String.class),
                    @StringToClassMapItem(key = "rateY", value = String.class)
            })
```

What I am getting generated instead is
```
"rates": {
      "additionalProp1": 0,
      "additionalProp2": 0,
      "additionalProp3": 0
    }
```
Am i missing something?
**To Reproduce**

- What version of spring-boot you are using? `3.2.4`
- What modules and versions of springdoc-openapi are you using? `2.5.0`

**Expected behavior**
The output should be - values being Strings instead of Numbers
```
"rates": {
      "additionalProp1": "0",
      "additionalProp2": "0",
      "additionalProp3": "0"
    }
```

**Comment by bnasslahsen** [comment]
@aleksandarvanced,

The code you are refering to, is not even compiling.

Feel free to provide a [Minimal, Reproducible Example - with HelloController](https://stackoverflow.com/help/minimal-reproducible-example) that reproduces the problem.


This ticket will be closed, but can be reopened if your provide the reproducible sample.
