### ISSUE TITLE
Locale in json body should be a language tag string

### ISSUE THREAD

**Issue by abccbaandy** [springdoc/springdoc-openapi#2679]
**Describe the bug**
In swagger, it shows these in default
````json
  "locale": {
    "language": "string",
    "displayName": "string",
    "country": "string",
    "variant": "string",
    "script": "string",
    "unicodeLocaleAttributes": [
      "string"
    ],
    "unicodeLocaleKeys": [
      "string"
    ],
    "displayLanguage": "string",
    "displayScript": "string",
    "displayCountry": "string",
    "displayVariant": "string",
    "extensionKeys": [
      "string"
    ],
    "iso3Language": "string",
    "iso3Country": "string"
  },
```` 

**To Reproduce**
````java
//pojo
public class MyVo {
    private Locale locale;
}

//controller
@PostMapping("/api")
    public void api(@RequestBody MyVo vo) {
}
````

- What version of spring-boot you are using?
3.2.5

- What modules and versions of springdoc-openapi are you using?
org.springdoc:springdoc-openapi-starter-webmvc-ui:2.5.0

**Expected behavior**
Should be a string like this:
````json
{
  "locale": "en_US"
}
````

**Comment by bnasslahsen** [comment]
@abccbaandy,

You have so many ways to achieve this: 

1. Globally: `SpringDocUtils.getConfig().replaceWithSchema`
2. For a particular method: `@RequestBody` swagger annotation

**Comment by bnasslahsen** [comment]
@abccbaandy,

Can you show in the `springdoc-openapi` code the wrong default config you are referring to ?

**Comment by bnasslahsen** [comment]
@abccbaandy, 

`springdoc-openapi` offers an easy-to-use automation tool and a flexible framework for developers. 
We've already responded to your inquiry, but you continue to request something else without providing any proof or relevant details.

Therefore, I am closing this conversation to avoid further delays.
