### ISSUE TITLE
springdoc.swagger-ui.layout

### ISSUE THREAD

**Issue by dalucasP** [springdoc/springdoc-openapi#2680]
**Describe the bug**
Using this property seems to only work with default layouts provided by swagger such as BaseLayout/StandaloneLayout.  Providing a custom layout documented here https://swagger.io/docs/open-source-tools/swagger-ui/customization/custom-layout/ and placing not only in the java/resources directory of the springboot service application but also /resources/META-INF/resources/webjars/swagger-ui/ returns the following error (as a .jsx file)

No layout defined for "MyCustomLayout" 

**To Reproduce**

- What version of spring-boot you are using? 3.3.2
- What modules and versions of springdoc-openapi are you using? 2.6.0
- What is the actual and the expected result using OpenAPI Description (yml or json)? json

**Expected behavior**
The layout of the swagger-ui page would show the custom layout provided 
MyCustomLayout.jsx

`import React from "react"
// Create the layout component
class MyCustomLayout extends React.Component {
  render() {
    const {
      getComponent
    } = this.props
    const BaseLayout = getComponent("BaseLayout", true)
    return (
      <div>
        <div id="headerBanner" style="background: #007a33;color: #fff;font-family: Roboto, Arial, Helvetica, sans-serif !important;display:block;width:100%;padding:3px;font-weight:700;font-size:14px;text-align:center,text-transform:uppercase;">Systems Online</div> 
        <BaseLayout />
		<div id="footerBanner" style="background: #007a33;color: #fff;font-family: Roboto, Arial, Helvetica, sans-serif !important;display:block;width:100%;padding:3px;font-weight:700;font-size:14px;text-align:center,text-transform:uppercase;">Systems Online</div> 
      </div>
    )
  }
}
// Create the plugin that provides our layout component
const MyCustomLayoutPlugin = () => {
  return {
    components: {
      MyCustomLayout: MyCustomLayout
    }
  }
}`

- A clear and concise description of what you expected to happen.
- Layout should be found and updated when the property is set springdoc.swagger-ui.layout=MyCustomLayout

**Comment by bnasslahsen** [comment]
@dalucasP,

Make sure your Layout is correctly declared.
For this follow the [swagger-ui instructions](https://swagger.io/docs/open-source-tools/swagger-ui/customization/custom-layout/).

If you are still having the issue, you need to provide a [Minimal, Reproducible Example - with HelloController](https://stackoverflow.com/help/minimal-reproducible-example) that reproduces the problem.

This ticket will be closed, but can be reopened if your provide the reproducible sample.
