### ISSUE TITLE
Springdoc does not take into account enum naming strategy chosen by Jackson's EnumNaming annotation

### ISSUE THREAD

**Issue by hajdamak** [springdoc/springdoc-openapi#2681]
**Describe the bug**

When enum that is exposed in API uses Jackson's `EnumNaming` (https://github.com/FasterXML/jackson-databind/blob/2.18/src/main/java/com/fasterxml/jackson/databind/annotation/EnumNaming.java) annotation to set naming strategy for enum entries, Springdoc in generated OpenAPI definition generates enum entries as they are defined in the source code and not as chosen by naming strategy.

**To Reproduce**
Annotate enum with `EnumNaming` using  `CamelCaseStrategy` strategy and check generated OpeanAPI JSON or YAML. 
For enum:
``` 
@EnumNaming(EnumNamingStrategies.CamelCaseStrategy.class)
enum Flavor {
        PEANUT_BUTTER,
}
```
generated OpenAPI will have:
```
"enum" : [ "PEANUT_BUTTER" ]
```
and should have:
```
"enum" : [ "peanutButter" ]
```

- What version of spring-boot you are using?
3.3.1
- What modules and versions of springdoc-openapi are you using?
springdoc-openapi-starter-webmvc-ui 2.6.0
- What is the actual and the expected result using OpenAPI Description (yml or json)?
Both.
- Provide with a sample code (HelloController) or Test that reproduces the problem
Provided in `To Reproduce` section.

**Expected behavior**

Generated enum entries in OpenAPI definition should follow naming strategy chosen by annotation.

**Comment by bnasslahsen** [comment]
@hajdamak,

This not springdoc-openapi issue, but should be handled in [swagger-core](https://github.com/swagger-api/swagger-core/issues)

This is sample code that shows it:

```java
		ResolvedSchema resolvedSchema = ModelConverters.getInstance()
				.resolveAsResolvedSchema(new AnnotatedType(Flavor.class).resolveAsRef(false));
		OpenAPI openAPI = new OpenAPI();
		openAPI.schema("Flavor", resolvedSchema.schema);
		String result = Json.mapper().writerFor(OpenAPI.class).writeValueAsString(openAPI);
		Assert.isTrue(result.contains("peanutButter"), "The enum value should be in camelCase");
```
