### ISSUE TITLE
Schema  Area Data types are collapsed

### ISSUE THREAD

**Issue by solpower** [springdoc/springdoc-openapi#2683]
demo-spring-boot-3-webmvc   The data type is clearly visible in  Schema

![image](https://github.com/user-attachments/assets/cbb5cad4-3b24-44b9-a4ca-eb43564fab13)

but in my springdoc   Data types are collapsed，
 All data types are folded. It is too troublesome to open them one by one.  how to solve it 
 springdoc-openapi-starter-webmvc-ui  version  2.6.0
 spring.boot.version  3.3.2

![image](https://github.com/user-attachments/assets/9e0fb79c-5a07-45fd-8ee7-0ea338bfbbf2)

**Comment by bnasslahsen** [comment]
@solpower,

Feel free to report it to [swagger-ui](https://github.com/swagger-api/swagger-ui) project instead
