### ISSUE TITLE
I don't understand why an irrelevant content was returned

### ISSUE THREAD

**Issue by zxuanhong** [springdoc/springdoc-openapi#2688]
**Describe the bug**

1. I don't understand why an irrelevant content was returned
2. If I make a configuration error, please let me know. But why did you return to this page????
<img width="1078" alt="iShot_2024-08-27_19 12 04" src="https://github.com/user-attachments/assets/8783357b-c322-4166-a6de-8932d2dc5f8d">

**Comment by limehee** [comment]
You can disable the default Swagger Petstore URL by adding the following configuration:

In properties format:
```properties
springdoc.swagger-ui.disable-swagger-default-url=true
```
Or in yaml format:
```yaml
springdoc:
  swagger-ui:
    disable-swagger-default-url: true
```

**Comment by zxuanhong** [comment]
@limehee Thank you very much
