### ISSUE TITLE
Path parameter with wildcard not getting replaced correctly

### ISSUE THREAD

**Issue by gamue** [springdoc/springdoc-openapi#2701]
**Describe the bug**
I'm having a api-path definition which contains a wildcard/star/asterisks to fetch also values which contain a slash. When doing a request of that on the OpenAPI-UI the path-parameter is not getting replaced with the inserted value.

**To Reproduce**

- Define Path-Parameter with wildcard like `{*vehicleId}`
- Open OpenAPI-UI
- use "try out" functionality and send request
- Result: the value is not set correctly into the url which is getting called

**Expected behavior**
The value which is set in the UI should be used for the request that is getting triggered

**Screenshots**
<img width="959" alt="image" src="https://github.com/user-attachments/assets/9fb5bd1a-88d0-4faa-823e-5aac0806e02c">

**Comment by bnasslahsen** [comment]
@gamue,

A fix is already available.
You can validate it already based on the [Latest SNAPSHOT](https://springdoc.org/#how-can-i-use-the-last-springdoc-openapi-snapshot)
