### ISSUE TITLE
Request body description not shown

### ISSUE THREAD

**Issue by muzuro** [springdoc/springdoc-openapi#2703]
I have created controller with optional RequestBody. I added RequestBody but description not shown in the generated Swagger UI.

Controller snippet:
```
import io.swagger.v3.oas.annotations.Operation
import io.swagger.v3.oas.annotations.responses.ApiResponse
import org.springframework.http.ResponseEntity
import org.springframework.web.bind.annotation.PostMapping
import org.springframework.web.bind.annotation.RequestBody
import org.springframework.web.bind.annotation.RestController
import java.util.UUID

@RestController
class HelloController {

    @PostMapping("/hello")
    @Operation(summary = "Say hello",
        requestBody = io.swagger.v3.oas.annotations.parameters.RequestBody(
            description = "Map uid -> string)",
            required = false
        ),
        responses = [
            ApiResponse(responseCode = "200", description = "Ok"),
        ])
    fun hello(@RequestBody(required = false) body: Map<UUID, String>?): ResponseEntity<*> {
        return ResponseEntity.ok().build<Any>()
    }
    
}
```
How Swagger UI looks:
![image](https://github.com/user-attachments/assets/51c98278-359f-45e0-95c6-4ca1072851d0)

Actual OpenAPI Description json:
`hello":{"post":{"tags":["hello-controller"],"summary":"Say hello","operationId":"hello","requestBody":{"description":"Map uid -> string)"},"responses":{"200":{"description":"Ok","content":{"*/*":{"schema":{"type":"object"}}}}}}},`

Expected behavior:
Request body shown

Actual behavior:
Request body not shown

Spring boot: 3.2.2
Spring doc: 2.6.0

**Comment by ShahrearBinAmin** [comment]
Facing the same issue, please fix it. Otherwise, it becomes hard to communicate with the frontend developers.
