### ISSUE TITLE
@Schema oneOf config is ignored when generate the api-docs

### ISSUE THREAD

**Issue by abccbaandy** [springdoc/springdoc-openapi#2705]
- What version of spring-boot you are using?
3.3.3

- What modules and versions of springdoc-openapi are you using?
2.6.0

- What is the actual and the expected result using OpenAPI Description (yml or json)?
````json
                    "MyPojo": {
                        "oneOf": [
                            {
                                "$ref": "#/components/schemas/Child1"
                            },
                            {
                                "$ref": "#/components/schemas/Child2"
                            },
                            {
                                "$ref": "#/components/schemas/Child3"
                            }
                        ]
                    },
````
should be
````json
                    "MyPojo": {
                        "oneOf": [
                            {
                                "$ref": "#/components/schemas/Child1"
                            },
                            {
                                "$ref": "#/components/schemas/Child2"
                            }
                        ]
                    },
````

- Provide with a sample code (HelloController) or Test that reproduces the problem
````java
    @Schema(oneOf = {Child1.class, Child2.class})
    private Parent obj;
````

Also, according to this issue
https://github.com/springdoc/springdoc-openapi/issues/2704
I think this issue relate to Springdoc now, instead swagger core, because even I use my own converter to "fix" it, it will overwrite by Springdoc's converter.

**Comment by bnasslahsen** [comment]
@abccbaandy,

There is no definition of `Child3` in you code.
Not reproducible.
Feel free to provide a [Minimal, Reproducible Example - with HelloController](https://stackoverflow.com/help/minimal-reproducible-example) that reproduces the problem.

This ticket will be closed, but can be reopened if your provide the reproducible sample.
