### ISSUE TITLE
Swagger does not show names that start with "Is" in requestParam

### ISSUE THREAD

**Issue by Space-Shon** [springdoc/springdoc-openapi#2706]
Link on my repo: https://github.com/Space-Shon/TestRepository

When there is a variable in DTO that starts with "is", it is not visible in Swagger, I am attaching screenshots and my test repository, where you can reproduce the bug.

data class UserGetByParameterRequest(
    @field:Schema(description = "Is deleted user", implementation = Boolean::class)
    val isDeleted: Boolean?,
)

@RestController
@RequestMapping("/test")
@Tag(name = "Test")
class UserController(
    private val userDomainService: UserDomainService
) {

    @GetMapping
    @Operation(summary = "Get all users")
    fun getAllUsers(
        @ParameterObject requestParam: UserGetByParameterRequest,
    ): ResponseEntity<List<UserResponse>> = ResponseEntity.ok(
        userDomainService.getAllUsers(requestParam = requestParam).map { it.toUserResponse() }
    )
}

![Снимок экрана 2024-09-12 113646](https://github.com/user-attachments/assets/05d3af5e-1f61-4137-a57d-8a8e20a11454)

I using 3.3.3 version of spring-boot, "org.springdoc:springdoc-openapi-starter-webmvc-ui:2.3.0"
I tried this - 
tasks.withType<JavaCompile> {
    options.compilerArgs = listOf("-parameters")
}, 
it doesn't help either.

**Comment by bnasslahsen** [comment]
@Space-Shon,

`@ParameterObject`objects should follow the [Java Bean Specification:](https://download.oracle.com/otndocs/jcp/7224-javabeans-1.01-fr-spec-oth-JSpec/)

**According to the JavaBeans specification, property names are derived from their getter and setter methods, not directly from the field names. This distinction is crucial for understanding why Introspector.getBeanInfo() reports the property as adult and not isAdult.**
