### ISSUE TITLE
Schema shown for Put but not Post

### ISSUE THREAD

**Issue by SSmale** [springdoc/springdoc-openapi#2707]
I have swagger in my spring boot project and it is correctly showing the request and response schemas for the DTOs in Put request endpoints but not for the Posts. 

I don’t have any version details currently but I think it is 3.2.3 we are running.

**Comment by bnasslahsen** [comment]
@SSmale,

Not reproducible.
Feel free to provide a [Minimal, Reproducible Example - with HelloController](https://stackoverflow.com/help/minimal-reproducible-example) that reproduces the problem.

This ticket will be closed, but can be reopened if your provide the reproducible sample.
