### ISSUE TITLE
Annotation @Hidden on rest controller class level doesn't work due to spring default proxying mechanism CGLIB

### ISSUE THREAD

**Issue by alla-gofman** [springdoc/springdoc-openapi#2709]
I mark a rest controller class as hidden (with @Hidden annotation) to skip it while reading, but this have no affect.

This behavior is due to original class name wrapped into proxy by Spring boot default proxying mechanism CGLIB, so class name followed by "$$SpringCGLIB$$0" suffix.
See code:
[https://github.com/springdoc/springdoc-openapi/blob/71a0684dc0eea2504f570aad90f5069319dfa061/springdoc-openapi-starter-common/src/main/java/org/springdoc/api/AbstractOpenApiResource.java#L303](url)

`public static boolean isHiddenRestControllers(Class<?> rawClass) {
		return HIDDEN_REST_CONTROLLERS.stream().anyMatch(clazz -> clazz.isAssignableFrom(rawClass));
	}`

**The Solution** is to get real class name, for example:
`org.springframework.util.ClassUtils.getUserClass(clazz).isAssignableFrom(rawClass)`

- spring-boot 3.2.4
- springdoc-openapi-starter-common 2.6.0
- The expected result is not to have controller with @Hidden annotation in the openapi documentation.

![image](https://github.com/user-attachments/assets/cad91632-0ce7-46ef-8d21-f22afd635567)

![image](https://github.com/user-attachments/assets/1f286a30-3b02-493c-b5c4-c7c5c973fb46)

**Comment by bnasslahsen** [comment]
@alla-gofman,

Added the fix you are requesting.
Can you validate it, at your end ?
