### ISSUE TITLE
OpenApiService does not render requestBody objects which use java.time.Instant

### ISSUE THREAD

**Issue by DennisBecker** [springdoc/springdoc-openapi#2714]
I try to generate OpenApi docs for a webhook and it is really complicated. I try it now building manually and get the following when opening the OpenAPI doc:

```
o.springdoc.core.service.OpenAPIService  : Json Processing Exception occurred: Java 8 date/time type `java.time.Instant` not supported by default: add Module "com.fasterxml.jackson.datatype:jackson-datatype-jsr310" to enable handling (through reference chain
```

The requestObject() is not added to the openapi.yaml file.

The issue is here:

https://github.com/springdoc/springdoc-openapi/blob/feb7f6c629e53aa0f3e00acc12f7b522adddf1cc/springdoc-openapi-starter-common/src/main/java/org/springdoc/core/service/OpenAPIService.java#L248

Someone has changed the initialisation of ObjectMapper with this commit: https://github.com/springdoc/springdoc-openapi/commit/cde2afa8a7c3ae373e9ffc748c91e0cc4e5cf8a4

Why don't you use the ObjectMapper factory where all modules get loaded? This would solve the issue.

**Comment by bnasslahsen** [comment]
@DennisBecker,

The issue your are reporting is Not reproducible.
Feel free to provide a [Minimal, Reproducible Example - with HelloController](https://stackoverflow.com/help/minimal-reproducible-example) that reproduces the problem.

To get to know the reason for changing ObjectMapper factory, just change it in the project and will notice the failing tests.

This ticket will be closed, but can be reopened if your provide the reproducible sample.
