### ISSUE TITLE
Group Order was by group name, why was it changed to order by display name?

### ISSUE THREAD

**Issue by kushg18** [springdoc/springdoc-openapi#2717]
**Describe the bug**

- Question about this change: https://github.com/springdoc/springdoc-openapi/commit/ef74a02c07222a31efed3cf584b33f92a3b8f05a

**To Reproduce**

- What version of spring-boot you are using?
- What modules and versions of springdoc-openapi are you using?
- What is the actual and the expected result using OpenAPI Description (yml or json)?
- Provide with a sample code (HelloController) or Test that reproduces the problem

**Expected behavior**

- A clear and concise description of what you expected to happen.
- What is the expected result using OpenAPI Description (yml or json)?

**Screenshots**

**Additional context**

**Comment by bnasslahsen** [comment]
The related issue is in the comment (https://github.com/springdoc/springdoc-openapi/issues/2576)
