### ISSUE TITLE
Request for New Release Including PR \#2668

### ISSUE THREAD

**Issue by GianniGiglio** [springdoc/springdoc-openapi#2718]
Dear SpringDoc Team,

I’m reaching out to request that a new release of SpringDoc be created to include the recently merged [PR \#2668](https://github.com/springdoc/springdoc-openapi/pull/2668).

This update potentially addresses the issue reported in [Issue \#2509](https://github.com/springdoc/springdoc-openapi/issues/2509), which was previously labeled as not reproducible. However, we have been encountering this issue quite frequently in our customers' production environments, and it’s been challenging to find a definitive fix.

Including this fix in a new release would greatly assist us in resolving these occurrences and improving our product's stability. We would appreciate it if this could be expedited, as the issue is currently impacting our users.

Thank you for your ongoing support and for considering this request.

Gianni

**Comment by bnasslahsen** [comment]
Hi @GianniGiglio,

The fix is coming hopefully by the end of the month release.

**Comment by GianniGiglio** [comment]
@bnasslahsen 

Do we have any updates on when the release will be available? Our customers are significantly impacted by this issue in Springdoc. Any information on timelines would be greatly appreciated.

Thank you!

**Comment by bnasslahsen** [comment]
@GianniGiglio,

Will try to release 2.7.0-RC1 by the end of the day

**Comment by isarang** [comment]
can you please release spring boot 3.3.x compatible version?
