### ISSUE TITLE
Question: Is there a way to serve data at v3/api-docs path as a static content ?

### ISSUE THREAD

**Issue by Andrew3431** [springdoc/springdoc-openapi#273]
Can we get the actual content of v3/api-docs and serve it as static content from the project directory. Is there any support provided in springdoc-openapi ?

**Comment by springdoc** [comment]
Hi @Andrew3431 , 

 The convention is to serve the REST OpenAPI description of your API using /v3/api-docs
 You can customise this path and the path of the swagger-ui.html.

 You can have a look at the documentation for more details:
- https://springdoc.github.io/springdoc-openapi-demos/
- https://springdoc.github.io/springdoc-openapi-demos/faq.html
