### ISSUE TITLE
Support Kotlin Kdoc to generate descriptions.

### ISSUE THREAD

**Issue by hsanson** [springdoc/springdoc-openapi#2731]
**Is your feature request related to a problem? Please describe.**

Springdoc supports [javadoc](https://springdoc.org/#javadoc-support) to generate API descriptions but this does not work when working in Kotlin rather than Java.

**Describe the solution you'd like**

Would be great if Springdoc could add same support for [Kdoc](https://kotlinlang.org/docs/kotlin-doc.html) that is the Kotlin version of javadoc.

**Describe alternatives you've considered**

The only way to create long descriptions is to define some constants and then use them as description in @Operation and @Schema annotations.

**Comment by bnasslahsen** [comment]
@hsanson,

This is something you could ask https://github.com/dnault/therapi-runtime-javadoc team to support!
If they are willing to support kdoc as well.

**Comment by lenalebt** [comment]
Hey, just a short note: I think it would be nice to get this in the docs, took me quite some time just to find out that kotlin is not supported: https://springdoc.org/#javadoc-support

I just did not even think about that it might be different between kotlin and java...

**Comment by jsnelgro** [comment]
Could we consider reopening this issue? The only solution I've found ([How can I parse info from kotlin docs to swagger-ui?](https://stackoverflow.com/questions/72748450/how-can-i-parse-info-from-kotlin-docs-to-swagger-ui)) relies on kapt, which is in maintenance mode.

IMO, kotlin doc comments feel like a reasonable thing for this library to support for a few reasons:
1. doc comments are the recommended way to write docs in kotlin
2. This is a pretty batteries-included library and I think folks working in a Spring Boot project intuitively expect doc comments to work the same across java and kotlin
3. Spring itself is committed to seamless kotlin support
4. It's surprising behavior to have doc comments work in Java but not Kotlin

**Comment by max-claravine** [comment]
> Could we consider reopening this issue? The only solution I've found ([How can I parse info from kotlin docs to swagger-ui?](https://stackoverflow.com/questions/72748450/how-can-i-parse-info-from-kotlin-docs-to-swagger-ui)) relies on kapt, which is in maintenance mode.
> 
> IMO, kotlin doc comments feel like a reasonable thing for this library to support for a few reasons:
> 
> 1. doc comments are the recommended way to write docs in kotlin
> 2. This is a pretty batteries-included library and I think folks working in a Spring Boot project intuitively expect doc comments to work the same across java and kotlin
> 3. Spring itself is committed to seamless kotlin support
> 4. It's surprising behavior to have doc comments work in Java but not Kotlin

Took me way too long to find this thread. I've been using Spring Boot + Kotlin heavily in my career for years now and spent a bunch of time this morning going down dead ends trying to get kdoc support going and ran into the fact that `kapt` is being sunset and does not play nice with my project anyways. I more or less have no solution right now except to repeat all my docs with `io.swagger.*` annotations which isn't the end of the world but not ideal.

Spring Kotlin is getting more and more use these days and it'd be amazing to support it here since as jsnelgro says this is such a common dependency to want to include.
