### ISSUE TITLE
Support for Checkbox Display for Boolean Parameters in Swagger UI

### ISSUE THREAD

**Issue by stepanov1997** [springdoc/springdoc-openapi#2757]
Currently, springdoc-openapi renders boolean query parameters as dropdown lists (true / false) in the Swagger UI. This can be unintuitive and less user-friendly when working with a large number of boolean flags. A checkbox option would provide a more natural and simpler way to handle boolean values, especially for users who are accustomed to standard web forms.

The request is to add support for displaying boolean parameters as checkboxes instead of dropdown lists in Swagger UI. This would align with typical UI practices for boolean inputs, providing a more intuitive user interface.

Current Behavior:
	•	Boolean query parameters are displayed as dropdowns with two values: true and false.
	•	There is no configuration option in springdoc-openapi or Swagger UI to switch the display to a checkbox.

Proposed Solution:
	•	Add a configuration option (e.g., springdoc.swagger-ui.boolean-display=checkbox) that would render boolean parameters as checkboxes in the Swagger UI.
	•	Alternatively, use a schema-level annotation or @Parameter attribute in the Spring controller to control how boolean parameters are rendered (e.g., @Parameter(schema = @Schema(booleanAsCheckbox = true))).

Use Case:
	•	Applications that heavily use boolean query parameters for filtering, toggles, or feature flags.
	•	Improving usability for API consumers by providing a more familiar input control for boolean values.

Benefits:
	•	Enhanced user experience with clearer representation of boolean parameters.
	•	Less confusion for users when selecting boolean values.
	•	Improved form input consistency across different API tools.

Impact:
	•	Minimal, as it introduces an optional configuration parameter or annotation without changing the existing behavior for users who prefer dropdown lists.
	•	Would improve the clarity and usability of APIs documented with springdoc-openapi.

Additional Context:
	•	This request aligns with typical UI patterns in forms and API tools where boolean values are commonly represented as checkboxes rather than dropdown lists.
	•	Checkbox input for boolean values is standard in many front-end frameworks and provides a visual cue for true/false options.

References:
	•	Similar requests have been raised in the Swagger UI community, suggesting that this is a desired feature for a broader audience.

**Comment by bnasslahsen** [comment]
@stepanov1997,

springdoc-openapi, is responsible of the OpenAPI 3 spec generation.
This is a feature you can propose to https://github.com/swagger-api/swagger-ui project instead.
