### ISSUE TITLE
Swagger aggregation

### ISSUE THREAD

**Issue by NoxFr** [springdoc/springdoc-openapi#276]
Is it possible to aggregate several swagger definition ? 
(SwaggerResourcesProvider in springfox.web)

**Comment by springdoc** [comment]
Hi, 

 This is duplicate of:  #108
This is an interesting feature, but we don't consider it as a a top priority.
 Please note, we don't change the behaviour of the official swagger-ui jars.
In addition, this behaviour is very specific to services that relies on Eureka.

If you need to achieve it, you can contribute to springdoc-openapi.

- You can have your back-end services to ship only the springdoc-openapi-core or springdoc-openapi-weblfux depending on your project APIs.
- This way, all your back-end services will expose their documentation using the following path by default; /v3/api-docs
- Then, you will need the swagger-ui to retrieve the documentation from the registred endepoints on Eureka.

**Comment by bnasslahsen** [comment]
You can agregate multiple OpenAPI definitions using springdoc-openapi.
Here is a sample in a microservices architecture:
- https://piotrminkowski.com/2020/02/20/microservices-api-documentation-with-springdoc-openapi/
 - https://github.com/piomin/sample-spring-microservices-new
