### ISSUE TITLE
How do I generate length properties with custom validation annotation?

### ISSUE THREAD

**Issue by kevinm416** [springdoc/springdoc-openapi#2768]
**Is your feature request related to a problem? Please describe.**

I'm switching off the Jakarta `@Size` annotation in favor of my own `@Size` validation. The jakarta `@Size` generated these items in the openapi.json:

```
            "maxLength": 20,
            "minLength": 1,
```

**Describe the solution you'd like**

I want to be able to generate those values with my own custom `@Size` annotation, but can't figure out how to.

Is that supported? If not, I'd like it to be. If it is, can you point me towards any documentation for how to do it?

**Comment by bnasslahsen** [comment]
@kevinm416,

You can override `org.springdoc.webmvc.core.service.RequestService` with your own implementation, and override `applyBeanValidatorAnnotations` method.
