### ISSUE TITLE
There was an unexpected error (type=Not Found, status=404)

### ISSUE THREAD

**Issue by bgawne** [springdoc/springdoc-openapi#277]
Installed for springboot 2.2.2.RELEASE , rest based api application.
Included following in gradle build:
    implementation group: 'org.springdoc', name: 'springdoc-openapi-ui', version: '1.2.18'
    implementation group: 'org.springdoc', name: 'springdoc-openapi-data-rest', version: '1.2.18'
    implementation group: 'org.springdoc', name: 'springdoc-openapi-security', version: '1.2.18'
    implementation group: 'org.springdoc', name: 'springdoc-openapi-webflux-ui', version: '1.2.18'

When I go to the command line and type in my url:

http://localhost:9500/swagger-ui.html
I get redirected to the url:
http://localhost:9500/swagger-ui/index.html?url=/v3/api-docs&validatorUrl=

This then gives me the following springboot error:
--------------------------------------------------
Whitelabel Error Page
This application has no explicit mapping for /error, so you are seeing this as a fallback.

Tue Dec 17 15:03:21 GMT 2019
There was an unexpected error (type=Not Found, status=404).
No message available

--------------------------------------------------

However, I am able to get the documentation from http://localhost:9500/v3/api-docs
which gives me the json file.

I have looked through dependancies and tried multiple variations. I cannot get this to properly display.

**Comment by springdoc** [comment]
Hi @bgawne , 

 For the ui, either choose: springdoc-openapi-ui if your application uses spring-mvc, or use springdoc-openapi-webflux-ui if your application is based on webflux.  You shouldn't declare both on the same application.

**Comment by s8v-nurb0L** [comment]
Did you solve that problem? I use only one library (`implementation('org.springdoc:springdoc-openapi-webflux-ui:1.2.27')`), but it still does not work.

**Comment by onacit** [comment]
@s8v-nurb0L Did you find any cause?

**Comment by bnasslahsen** [comment]
@onacit, 

 Make sure you are using the latest springdoc release (today v1.5.2).
 If you are new to springdoc-openapi, you have [code demos](https://github.com/springdoc/springdoc-openapi-demos) depending on your use case.
