### ISSUE TITLE
Integration with resteasy-spring-boot-starter

### ISSUE THREAD

**Issue by thegenius** [springdoc/springdoc-openapi#2774]
**Is your feature request related to a problem? Please describe.**
1. I want to define resource by jakarta.ws annotations, so I use resteasy-spring-boot-starter
2. I want to generate doc of these jakarta defined resource.

 when I try to generate openapi doc with springdoc, I found it's not work.
springdoc can not find the proper resource that defined by jakarta annotation.
```xml
   <dependency>
            <groupId>org.jboss.resteasy</groupId>
            <artifactId>resteasy-servlet-spring-boot-starter</artifactId>
            <version>6.2.0.Final</version>
</dependency>

<dependency>
            <groupId>org.springdoc</groupId>
            <artifactId>springdoc-openapi-starter-webmvc-ui</artifactId>
            <version>2.6.0</version>
</dependency>
```

I believe springdoc works perfectly with jakarta annotation will definitely improve the develop experience.

**Comment by bnasslahsen** [comment]
@thegenius,

`springdoc-openapi` supports spring-boot projects and not resteasy.
