### ISSUE TITLE
`@RequestBody` not working for `@GetMapping` endpoints

### ISSUE THREAD

**Issue by ML-Marco** [springdoc/springdoc-openapi#2775]
```java
@GetMapping("test")
public void getWithRequestBody(@RequestBody MyClass myClass) {
}
```
This results in a definition where `myClass` parameter is defined to appear `"in": "query"`. Correct behavior would be a `requestBody` block with $ref schema.
Neither `org.springframework.web.bind.annotation.RequestBody` nor `io.swagger.v3.oas.annotations.parameters.RequestBody` work.

**Actual**
```json
"/test": {
      "get": {
        "tags": [
          "test-controller"
        ],
        "operationId": "TestController.getWithRequestBody",
        "parameters": [
          {
            "name": "myClass",
            "in": "query",
            "required": true,
            "schema": {
              "$ref": "#/components/schemas/MyClass"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK"
          }
        }
      }
    }
```

**Expected part**
```json
"requestBody": {
  "content": {
    "application/json": {
      "schema": {
        "$ref": "#/components/schemas/MyClass"
      }
    }
  },
  "required": true
}
```

It would be nice if a fix could be backported to the 1.8.x release 🙏.

**Comment by bnasslahsen** [comment]
springdoc-openapi v1.8.0 is the latest Open Source release supporting [ Spring](https://springdoc.org/#) Boot 2.x and 1.x.
An extended support for [springdoc-openapi v1](https://springdoc.org/v1) project is now available for organizations that need support beyond 2023.
For more details, feel free to reach out: [sales@springdoc.org](mailto:sales@springdoc.org)

You should move to OpenAPI 3.1 to Allow requestBody creation for GET see #1814
Or move to 2.6.0, which has better support

**Comment by bnasslahsen** [comment]
@ML-Marco,

Both are supported.
But the `@RequestBody` for `GET` operations, is only allowed in **OpenAPI 3.1** and not OpenAPI 3.0.
