### ISSUE TITLE
Version 2.7.0-RC1 on Maven Central

### ISSUE THREAD

**Issue by pavelklecansky** [springdoc/springdoc-openapi#2776]
**Describe the bug**

On Maven Central (https://central.sonatype.com/artifact/org.springdoc/springdoc-openapi-starter-webmvc-ui) the newest version of this package is 2.7.0-RC1. Because then when the new dependencies for my project were downloaded, this version was downloaded and it crashed the build as the build could not find org.springframework.boot:spring-boot-starter-parent:3.4.0-RC1, which is not in Maven Central. The fix was easy, I just had to fix the version to 2.6. Maybe this is no problem and I have something wrongly configured, but I just wanted to let you know. So if the problem is on my side, you can just close this issue.

**Comment by bnasslahsen** [comment]
@pavelklecansky,

This is a pre-release. The release will be based on spring-boot-starter-parent:3.4..
If you are not allowed to use spring-boot 3.4.0-RC1, you will have to stick on the previous version 2.6.0

**Comment by bwaldvogel** [comment]
Unfortunately this can break the build tooling. We use Gradle’s `latest.release` mechanism in combination with dependency locking. We actually automatically exclude versions such as `2.7.0-RC1`. However, Gradle cannot even evaluate this POM since `spring-boot-starter-parent:3.4.0-RC1` is not available via Maven Central:

```
  > Could not resolve org.springdoc:springdoc-openapi-starter-common:2.7.0-RC1.
	 > Could not parse POM https://repo.maven.apache.org/maven2/org/springdoc/springdoc-openapi-starter-common/2.7.0-RC1/springdoc-openapi-starter-common-2.7.0-RC1.pom
		> Could not resolve org.springdoc:springdoc-openapi:2.7.0-RC1.
		   > Could not resolve org.springdoc:springdoc-openapi:2.7.0-RC1.
			  > Could not parse POM https://repo.maven.apache.org/maven2/org/springdoc/springdoc-openapi/2.7.0-RC1/springdoc-openapi-2.7.0-RC1.pom
				 > Could not find org.springframework.boot:spring-boot-starter-parent:3.4.0-RC1.
```

Honestly, I’m surprised that you were allowed to release `2.7.0-RC1` which references a parent that does not exist on Maven Central?

**Comment by chrko** [comment]
I agree with @bwaldvogel. This breaking as it requires additional repos to be configured (and version constraints unfortunately pickup also RC version in Java as their status is "release" and not "integration" (only SNAPSHOTS)). Therefore somehow resolving the pain for consumers of springdoc would be really nice.

**Comment by nicolasb29** [comment]
Thanks to publish this RC !
