### ISSUE TITLE
Allow proper configuration of validatorUrl and configUrl

### ISSUE THREAD

**Issue by kaibra** [springdoc/springdoc-openapi#278]
I looked at [SwaggerWelcome](https://github.com/springdoc/springdoc-openapi/blob/master/springdoc-openapi-ui/src/main/java/org/springdoc/ui/SwaggerWelcome.java) which redirects to the included `swagger-ui` adding configured queryParameters.

The `url` and `validatorUrl` parameters are always set.
That is why it is currently not possible to specify a `validatorUrl`, or set the `url` property in a config provided by a config-endpoint (`configUrl`).
This is because of the [precedence of configuration](https://github.com/swagger-api/swagger-ui/blob/master/docs/usage/configuration.md) properties for swagger-ui: 

```
From lowest to highest precedence:

* The swagger-config.yaml in the project root directory, if it exists, is baked into the application
* configuration object passed as an argument to Swagger UI (SwaggerUI({ ... }))
* configuration document fetched from a specified configUrl
* configuration items passed as key/value pairs in the URL query string
```

It would be nice to 
* be able to specify the `validatorUrl`
* have proper support for `configUrl`

(It is possible to get around this by disabling SwaggerConfig / SwaggerWelcome + providing custom redirects)

**Comment by springdoc** [comment]
Hi @kaibra, 

 Can you propose a PR for it ?

**Comment by glockbender** [comment]
Note that works only .json config for current latest swagger-ui version.
Also this feature allows retrieve many other properties such as multiple api urls. But there is a problem with configure url mapping. 

<img width="352" alt="Снимок экрана 2019-12-18 в 13 47 37" src="https://user-images.githubusercontent.com/16047417/71079815-0672f280-219d-11ea-8463-cce08a892374.png">

In this case, if your service (eg http://localhost/myservice/...}) deployed behind reverse-proxy (/myservice is proxy mapping path), then path to config will be http://localhost/api-docs/swagger-config.json

**Comment by kaibra** [comment]
See https://github.com/springdoc/springdoc-openapi/pull/281/commits/06fc757822d8b89611ea89ff4c9e4eb74a3e828c
