### ISSUE TITLE
Question on latest RF and SwaggerUiConfigParameters

### ISSUE THREAD

**Issue by GianniGiglio** [springdoc/springdoc-openapi#2781]
**Describe the bug**

This is technically not a bug but a question regarding the latest RC version 2.7.0.

In our setup, we currently define a custom `SwaggerIndexPageTransformer` to override the `transform` method. The `AbstractSwaggerIndexTransformer` class has a method:

```java
protected String defaultTransformations(SwaggerUiConfigParameters swaggerUiConfigParameters, InputStream inputStream) throws IOException {
    String html = this.readFullyAsString(inputStream);
    if (!CollectionUtils.isEmpty(this.swaggerUiOAuthProperties.getConfigParameters())) {
        html = this.addInitOauth(html);
    }
    return html;
}
```

We call this method in our custom transformer. This method depends on a bean of type SwaggerUiConfigParameters.

In version 2.6.0, this bean was auto-configured by the springdoc-common module. However, in the latest RC version (2.7.0), the SwaggerUiConfigParameters class still exists but is no longer auto-configured. To resolve this, I now have to explicitly declare the SwaggerUiConfigParameters as a bean in my configuration.

Is this the expected behavior in 2.7.0, or is there another recommended way to address this issue?

Here’s an example of how I’ve configured it:

```
@Bean
SwaggerUiConfigParameters swaggerUiConfigParameters(SwaggerUiConfigProperties swaggerUiConfig) {
    return new SwaggerUiConfigParameters(swaggerUiConfig);
}

@Bean
public SwaggerIndexTransformer swaggerIndexTransformer(
        SwaggerUiConfigProperties swaggerUiConfig,
        SwaggerUiOAuthProperties swaggerUiOAuthProperties,
        SwaggerUiConfigParameters swaggerUiConfigParameters,
        SwaggerWelcomeCommon swaggerWelcomeCommon,
        ObjectMapperProvider objectMapperProvider) {
    return new CustomResourceTransformer(
            swaggerUiConfig,
            swaggerUiOAuthProperties,
            swaggerUiConfigParameters,
            swaggerWelcomeCommon,
            objectMapperProvider);
}
```

To Reproduce

	1.	Use Spring Boot with the following setup:
	•	Spring Boot version: [provide your version]
	•	Modules and versions of springdoc-openapi: [e.g., springdoc-openapi-ui, version 2.7.0-RC]
	2.	Define a custom SwaggerIndexPageTransformer and call defaultTransformations within it.
	3.	Attempt to run the application without explicitly defining a SwaggerUiConfigParameters bean.
	4.	Observe that the SwaggerUiConfigParameters bean is not auto-configured, resulting in an error.

Expected behavior

The expected behavior was that the SwaggerUiConfigParameters bean would continue to be auto-configured as it was in version 2.6.0. However, in version 2.7.0-RC, this auto-configuration seems to have been removed, requiring manual bean declaration.

Clarification is needed on whether this is the intended change or if there is another recommended approach for customizing the SwaggerIndexPageTransformer.

Screenshots

Additional context

The SwaggerUiConfigParameters bean was previously auto-configured by the springdoc-common module in version 2.6.0. In the latest RC version (2.7.0), it appears this auto-configuration is no longer provided.

Could you confirm if this change is intentional and how best to handle this in the new version? Thank you!

**Comment by bnasslahsen** [comment]
@GianniGiglio,

You do not need to declare as Bean `SwaggerUiConfigParameters`
It's an intentional change to keep distinct object references, per request.

You can check this sample `SwaggerIndexPageTransformer`, to reuse the logic to initialize `SwaggerUiConfigParameters`
https://github.com/springdoc/springdoc-openapi/blob/b04a2c06aa190debc68b6d1524bb6c55a03d42d7/springdoc-openapi-starter-webmvc-ui/src/main/java/org/springdoc/webmvc/ui/SwaggerIndexPageTransformer.java#L73-L89

**Comment by GianniGiglio** [comment]
@bnasslahsen Thank you for your response, and apologies for my delayed reply. However, the issue still persists.

The SwaggerIndexPageTransformer depends on the bean SwaggerUiConfigParameters, but this bean is no longer being initialized, leading to the following error:

`required a bean of type 'org.springdoc.core.properties.SwaggerUiConfigParameters' that could not be found.`


also see:

`The public SwaggerIndexPageTransformer(SwaggerUiConfigProperties swaggerUiConfig, SwaggerUiOAuthProperties swaggerUiOAuthProperties,
			SwaggerWelcomeCommon swaggerWelcomeCommon, ObjectMapperProvider objectMapperProvider) {
		super(swaggerUiConfig, swaggerUiOAuthProperties, objectMapperProvider);
		this.swaggerWelcomeCommon = swaggerWelcomeCommon;
	}`

**Comment by GianniGiglio** [comment]
Never mind I was wrong
