### ISSUE TITLE
When 2.7.0 is going to be released?

### ISSUE THREAD

**Issue by bay73** [springdoc/springdoc-openapi#2785]
**Describe the bug**

Due to https://github.com/springdoc/springdoc-openapi/issues/2687 version 2.6.0 is not working with Spring Boot 3.4.0 which is released now. 
What is expected release date for the next version of SpingDoc-OpenAPI?

**Comment by codesorcery** [comment]
You may use `2.7.0-RC1` released 2 weeks ago. I guess there won't be many changes between this version and the `2.7.0` release.

**Comment by Kagenui-yozuru** [comment]
Spring Boot 3.4.0 has been released and looking forward to the quick release of version 2.7.0

**Comment by tleipzig** [comment]
A quick release is very much appreciated!

**Comment by codesorcery** [comment]
> I think you'll need to include the spring milestone repository in your `build.gradle.kts` in order to build with `2.7.0-RC1`, so
> 
> ```kotlin
> repositories {
>   maven("https://repo.spring.io/milestone")
> }
> ```
> 
> This is because `2.7.0-RC1` depends on `org.springframework.boot:spring-boot-starter-parent:3.4.0-RC1` which is only available in the spring milestone repository.

Only necessary, if you don't have the version managed elsewhere (e.g. Spring Boot parent POM, Spring Boot BOM, other Spring Boot starter libraries included before this). And I don't see a reason why you would be using this library without any of this (and if you are, it makes more sense to explicitly link to `org.springframework.boot:spring-boot-starter-parent:3.4.0`).

**Comment by khaledham10** [comment]
Hi, we are upgrading spring boot to 3.4.0, the /swagger-ui/index.html no longer works with the last version of spring-doc 
2.6.0 .. 

Any solutions? 

Thanks a lot.

**Comment by petergphillips** [comment]
as mentioned previously you need to upgrade to `2.7.0-RC1` (as `2.7.0` isn't out yet).  So (assuming kotlin build file) replace:
```kotlin
implementation("org.springdoc:springdoc-openapi-starter-webflux-ui:2.6.0")
```
with
```kotlin
implementation("org.springdoc:springdoc-openapi-starter-webmvc-ui:2.7.0-RC1")
```
and also (didn't work for me without this) add in the milestone repository so that it can find the spring boot starter parent
```kotlin
repositories {
  maven("https://repo.spring.io/milestone")
}
```

**Comment by bnasslahsen** [comment]
I'm still amazed that just a day after the Spring Boot release, people are already anticipating version 2.7.0. 
Hopefully, it will be available on Maven Central today, in just a few hours!

**Comment by bay73** [comment]
Thank you for a quick reaction.

> I'm still amazed that just a day after the Spring Boot release, people are already anticipating version 2.7.0.
Renovate bot are pretty fast - it updated Spring Boot couple of hourse after the release and immediately catch the failure with doc generation. :)
