### ISSUE TITLE
Applying validation rules does not take into account groups on rules

### ISSUE THREAD

**Issue by mc1arke** [springdoc/springdoc-openapi#2792]
**Describe the bug**

When using a jaxarta.validation.constraints.* annotation, a user can specify a 'groups' field on the annotation which causes that validation to only be applied if the validator has been configured to apply that group. If no groups are specified on the annotation then the annotation is applied for all inputs. springdoc-openapi is currently not checking for the presence of groups so it setting the limits from the validation globally, even where the validation would not apply to some requests.

**To Reproduce**
With an endpoint and model definition of
```java

	@GetMapping("/grouped-nullable")
	public void validationNotNullWithNonActiveGroup(@RequestBody RequestContent requestContent) {

	}

	public interface ValidationGroup {
		
	}

	public record RequestContent(
			@NotNull(groups = ValidationGroup.class) String value
	) {

	}
```

the project currently generates a JSON definition with the following parameters
```json
        "parameters": [
          {
            "name": "requestContent",
            "in": "query",
            "required": true,
            "schema": {
              "$ref": "#/components/schemas/RequestContent"
            }
          }
```

**Expected behavior**
Given no groups are known to be active, any validation that has groups specified should be presumed to be inactive and therefore not be applied to the model, e.g.
```json
        "parameters": [
          {
            "name": "requestContent",
            "in": "query",
            "required": false,
            "schema": {
              "$ref": "#/components/schemas/RequestContent"
            }
          }
```
The same applies for other annotations, e.g.`@Min`, `@Max`, `@Pattern` etc.

Ideally, it would be useful to be able to configure the generator to have a set of group combinations to match to, defaulting to the 'empty' group to ensure validations that are applied to all requests are the only ones specified in the request

**Comment by bnasslahsen** [comment]
@mc1arke,

There is no plans for this support.
Feel free to propose a PR if you feel it useful for the community, and we will have a look at it.

**Comment by mc1arke** [comment]
I've opened https://github.com/swagger-api/swagger-core/issues/4804 as I think changes need made in Swagger core before this can be properly supported in SpringDoc
