### ISSUE TITLE
Removing operationId via customizer does not work anymore

### ISSUE THREAD

**Issue by mb-nick** [springdoc/springdoc-openapi#2797]
**Describe the bug**

With 2.7.0 it is not possible anymore to remove the operationId via a customizer.
The version we used so far is 2.6.0.
Our customizer looks like this
```
    @Bean
    public OperationCustomizer operationIdCustomizer() {
        return (operation, handlerMethod) -> {
            operation.setOperationId(null);
            return operation;
        };
    }
```

The generated operation IDs in the OpenAPI spec are "null_1", "null_2" and so. 
With the customizer In 2.6.0 and before the operation ID field was omitted.

**To Reproduce**

- What version of spring-boot you are using?
   - 3.4.0 
- What modules and versions of springdoc-openapi are you using?
   - springdoc-openapi-starter-webmvc-ui
   - springdoc-openapi-starter-common

**Expected behavior**

I expect that, if the operation ID is set to null, that there won't be a field "operationId" for this operation in the generated OpenAPI spec. The field operationId is recommended but not mandatory.

**Comment by bnasslahsen** [comment]
@mb-nick,

I have added a fix for it.
Can you please test with the latest SNAPHSOT?

**Comment by mb-nick** [comment]
@bnasslahsen 

Sry for the late reply. With 2.7.1-SNAPSHOT it works as expected.
Thx.
