### ISSUE TITLE
Too many components in swagger when using HttpEntity instead of ResponseEntity

### ISSUE THREAD

**Issue by EstebanDugueperoux2** [springdoc/springdoc-openapi#280]
Hello,

When having a resource method whose return type is HttpEntity instead of ResponseEntity, generated swagger contains too many technical types.
Reproductible in your unit tests by replacing ResponseEntity by HttpEntity.

Best Regards.

**Comment by springdoc** [comment]
Hi, 

 Please provide more information in order to go further:
- The sample (java) code to reproduce your issue.
- The result you have got in OpenAPI format
- The expected Result

**Comment by code-d** [comment]
Hi, 
the bug remains in webflux project
eg. when using `Mono<HttpEntity<T>>`or `Flux<HttpEntity<T>>`

![62FED80E-BF24-458C-B6D5-E40B0BF7C5F9](https://user-images.githubusercontent.com/6970719/72580637-b8761980-3917-11ea-8e75-27b09ea19a1e.png)

**Comment by bnasslahsen** [comment]
It was only Handled for HttpEntity, return type
It will be Handled for Mono/Flux, in thé next release.
