### ISSUE TITLE
POJO property not included in generated swagger

### ISSUE THREAD

**Issue by proactif** [springdoc/springdoc-openapi#2806]
The generated swagger for a controller taking a pojo parameter with a name like "aProperty" will not be correctly generated.
The aProperty field will be missing.

This is due to this code in MethodParameterPojoExtractor :

```
return Stream.of(Introspector.getBeanInfo(paramClass).getPropertyDescriptors())
.filter(d -> d.getName().equals(field.getName()))
...
```

`d.getName()` is "AProperty", but `field.getName()` is "aProperty". 
The property is filtered out.

This happens for any field having its first camel case part of length 1.
Which seems to be an edge case of the java beans specification.
(see `Introspector.decapitalize()`)

**Comment by bnasslahsen** [comment]
@proactif,

See answer here: https://github.com/springdoc/springdoc-openapi/issues/2706#issuecomment-2372406707
