### ISSUE TITLE
Springdoc 2.7.0 doesnt Generate Schema and Request body ( Java 21 and Springboot 3)

### ISSUE THREAD

**Issue by kill3rstabs** [springdoc/springdoc-openapi#2807]
Java 21 SpringBoot 3, springdoc 2.7.0 doesnt generates the schema from the entity model and also does not detect the request body.

**Comment by bnasslahsen** [comment]
@kill3rstabs,

Not reproducible.
Feel free to provide a [Minimal, Reproducible Example - with HelloController](https://stackoverflow.com/help/minimal-reproducible-example) that reproduces the problem.

This ticket will be closed, but can be reopened if your provide the reproducible sample.
