### ISSUE TITLE
Different http methods in the same path and with common property names are rendered incorrectly

### ISSUE THREAD

**Issue by viniciusxyz** [springdoc/springdoc-openapi#2808]
**Describe the bug**

In the example project there are two endpoints a get and a post and the get response and the post body have different objects with different properties, but as the attribute name is the same the rendering is done incorrectly, let's look at swagger .yaml that I used as input to generate the code:

```yaml
openapi: 3.0.0
info:
  title: User API
  description: User API
  version: 1.0.0
paths:
  /vinc/account:
    get:
      summary: Get account
      description: Get account
      operationId: getAccount
      responses:
        200:
          description: "Get account"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccountTsDto'
    post:
      summary: Post Account
      description: Post Account
      operationId: postAccount
      requestBody:
        description: "Create account"
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AccountTsDtoTwo'
      responses:
        201:
          description: "Account"

components:
  schemas:
    AccountTsDto:
      type: object
      properties:
        account:
          $ref: '#/components/schemas/Account'

    Account:
      type: object
      properties:
        exampleOne:
          type: string

    AccountTsDtoTwo:
      type: object
      properties:
        account:
          $ref: '#/components/schemas/AccountExample'

    AccountExample:
      type: object
      properties:
        exampleTwo:
          type: string
```

And your visualization on Swagger Codegen

GET

![image](https://github.com/user-attachments/assets/eecb2f5e-16fa-48ae-a0eb-6e97792b4049)

POST

![image](https://github.com/user-attachments/assets/8b9b09a6-6729-4a19-b414-92a8c614e9f4)

Everything seems correct, now let's see the result of the interface in spring-docs:

```yaml
openapi: 3.0.1
info:
  description: |
    User API
servers:
- url: http://localhost:8080
  description: Generated server url
paths:
  /vinc/account:
    get:
      tags:
      - vinc-controller-adapter
      summary: Get account
      description: Get account
      operationId: getAccount
      responses:
        "200":
          description: Get account
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AccountTsDto"
    post:
      tags:
      - vinc-controller-adapter
      summary: Post Account
      description: Post Account
      operationId: postAccount
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/AccountTsDtoTwo"
        required: true
      responses:
        "201":
          description: Account
components:
  schemas:
    AccountTsDtoTwo:
      type: object
      properties:
        account:
          $ref: "#/components/schemas/account"
      description: Create account
    account:
      type: object
      properties:
        exampleOne:
          type: string
    AccountTsDto:
      type: object
      properties:
        account:
          $ref: "#/components/schemas/account"
```

Swagger UI

GET

![image](https://github.com/user-attachments/assets/735423ec-62e1-45b2-ae57-ec01b3b21df9)

POST

![image](https://github.com/user-attachments/assets/b61b3802-bc21-4dde-8547-91b74bb4c124)

**To Reproduce**

1. Download this project
[demo.zip](https://github.com/user-attachments/files/18066045/demo.zip)

2. Compile and run
3. Access http://localhost:8080/swagger-ui/index.html

As you can see, it appears that the Spring docs try to deduplicate items with the same names and this means that in the post where we should see `exampleTwo` we see `exampleOne`

**Extra information**

- Spring Boot 3.4.0
- Spring Docs 2.7.0

**Comment by bnasslahsen** [comment]
@viniciusxyz,

The problem comes, from defining twice two different schemas with the same names:
![image](https://github.com/user-attachments/assets/2645c82c-084b-442a-8c77-2172652f63c0)

![image](https://github.com/user-attachments/assets/c3650584-59e8-453d-9158-ac6583f92c77)

Removing the name as follow, will resolve your issue:

![image](https://github.com/user-attachments/assets/f5e7b60b-eb76-4019-a131-e19d311152ed)
![image](https://github.com/user-attachments/assets/ab974635-97ab-4aaa-969e-afd2d9f0fcb8)

**Comment by viniciusxyz** [comment]
@bnasslahsen Thank you for your help, I hadn't realized that the generator had this incorrect result.
