### ISSUE TITLE
OpenAPI + Springboot - Swagger not available

### ISSUE THREAD

**Issue by LouisLa88** [springdoc/springdoc-openapi#2813]
**Describe the bug**

the api-doc endpoint is available, but swagger is not accessible with springboot 3.4.0 and springdoc 2.7.0

**To Reproduce**

- What version of spring-boot you are using? 3.4.0
- What modules and versions of springdoc-openapi are you using? 2.7.0
- What is the actual and the expected result using OpenAPI Description (yml or json)?
- Provide with a sample code (HelloController) or Test that reproduces the problem

**Expected behavior**

Be able to use swagger-ui.html

**Screenshots**

**Additional context**

```
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
		 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		 xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<groupId>org.examples</groupId>
	<artifactId>rest-controller-openapi</artifactId>
	<version>0.0.1-SNAPSHOT</version>
	<packaging>jar</packaging>

	<properties>
		<maven.compiler.source>21</maven.compiler.source>
		<maven.compiler.target>21</maven.compiler.target>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
	</properties>

	<dependencies>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-web</artifactId>
			<version>3.4.0</version>
		</dependency>
  <dependency>
      <groupId>org.springdoc</groupId>
      <artifactId>springdoc-openapi-starter-webmvc-ui</artifactId>
      <version>2.7.0</version>
   </dependency>

		<dependency>
			<groupId>org.projectlombok</groupId>
			<artifactId>lombok</artifactId>
			<version>1.18.34</version>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-actuator</artifactId>
			<version>3.4.0</version>
		</dependency>
	</dependencies>

	<build>
		<finalName>rest-controller-openapi</finalName>
		<plugins>
			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
			</plugin>
		</plugins>
	</build>

</project>
```

**Comment by vianneynara** [comment]
Bumping this, I am having the same issue right after updating Spring Boot 3.4.0 from 3.3.4, and having to upgrade springdoc to 2.7.0.

**Comment by hiabhi-cpu** [comment]
Try adding this dependency
<dependency>
      <groupId>org.springdoc</groupId>
      <artifactId>springdoc-openapi-starter-webmvc-ui</artifactId>
      <version>2.6.0</version>
   </dependency>

i got swagger integrated into it

**Comment by KabarbekN** [comment]
Same issue with spring boot 3.4.0 and openapi 2.7.0

**Comment by vianneynara** [comment]
> Try adding this dependency org.springdoc springdoc-openapi-starter-webmvc-ui 2.6.0
> 
> i got swagger integrated into it
@hiabhi-cpu 

The OP has already shown that he has version `2.7.0` installed, downgrading it to `2.6.0` wouldn't solve the issue since Spring Boot 3.4.0 specifically requires springdoc to be `2.7.0`. Let me know if I'm wrong.

**Comment by socmia** [comment]
Same issue with spring boot when upgrade from 3.3.1 to 3.4.1

**Comment by vkopanja** [comment]
Same issue, Spring boot 3.4.0 and openapi 2.7.0

**Comment by rkdtmddnjs97** [comment]
same issue, spring boot 3.4.0

**Comment by KimChanJin97** [comment]
same issue, spring boot 3.4.0 and openapi 2.0.2

**Comment by b3kt** [comment]
tried with springboot 3.4.1 and springdoc 2.7.0-RC1, able to run as well.

**Comment by liululu-code** [comment]
http://localhost:8080/webjars/swagger-ui/index.html works, but i don't know what is it.
http://localhost:8080/swagger-ui.html doesn't work.

**Comment by carlosfrtr** [comment]
I'm using spring "3.4.1" and works, see:

`
	implementation("org.springdoc:springdoc-openapi-starter-webmvc-ui:2.7.0")
	implementation("org.springdoc:springdoc-openapi-starter-webmvc-api:2.7.0")
`

properties:
# swagger-ui custom path
springdoc.swagger-ui.path=/swagger-ui.html

**Comment by liululu-code** [comment]
> I'm using spring "3.4.1" and works, see:
> 
> ```
> 	implementation("org.springdoc:springdoc-openapi-starter-webmvc-ui:2.7.0")
> 	implementation("org.springdoc:springdoc-openapi-starter-webmvc-api:2.7.0")
> ```
> 
> properties:
> 
> ```
> # swagger-ui custom path
> springdoc.swagger-ui.path=/swagger-ui.html
> ```

Yes, it works: 
        
        <dependency>
            <groupId>org.springdoc</groupId>
            <artifactId>springdoc-openapi-starter-webmvc-ui</artifactId>
            <version>2.7.0</version>
        </dependency>

        
        <dependency>
            <groupId>org.springdoc</groupId>
            <artifactId>springdoc-openapi-starter-webmvc-api</artifactId>
            <version>2.7.0</version>
        </dependency>

**Comment by bnasslahsen** [comment]
@LouisLa88,

Not reproducible.
Feel free to provide a [Minimal, Reproducible Example - with HelloController](https://stackoverflow.com/help/minimal-reproducible-example) that reproduces the problem.

This ticket will be closed, but can be reopened if your provide the reproducible sample.

**Comment by MocicaRazvan** [comment]
2.7.0-RC1 works other version not, for spring boot 3.4.1 and java 21 or 23

**Comment by mminot-yseop** [comment]
> 2.7.0-RC1 works […] for spring boot 3.4.1 and java 21 […]

With this combination, even starting the application gives me trouble:

> Parameter 2 of method `springRepositoryRestResourceProvider` in `org.springdoc.core.configuration.SpringDocDataRestConfiguration$SpringRepositoryRestResourceProviderConfiguration` required a bean of type `'org.springframework.data.rest.webmvc.mapping.Associations'` that could not be found.

With 2.8.4×3.4.2 (latest at the moment) and Java 21, I get 403 errors, empty web pages, and no error log.
What’s driving me insane is that it seems to work fine when running tests through Maven or even when running the app itself in production, but running tests (with the same active profiles – none at all – and no extra property) or starting the app through IntelliJ somehow yields 403 errors (except on `/api-docs.yaml`). 🤔

Previously I had 2.8.1×3.4.1. This combination is OK for the HTML part but gets a 403 _within it_:

<details><summary>Expandable screenshot</summary>

![Image](https://github.com/user-attachments/assets/1a26474c-84e1-48f0-8d03-b006a4d4be6d)

</details>

When trying to load the page with 2.8.1×3.4.1, I get a stacktrace similar to the aforementioned startup issue (but at least it says something, while 2.8.4×3.4.2 is silent):

> No qualifying bean of type `'org.springframework.data.rest.webmvc.mapping.Associations'` available
	at `org.springframework.beans.factory.support.DefaultListableBeanFactory.getBean(DefaultListableBeanFactory.java:373) ~[spring-beans-6.2.1.jar:6.2.1]`

I obviously tried forcing IntelliJ to rebuild the project from scratch after POM changes, but to no avail. And it used to be OK with older Boot versions and Java 17. It still works like a charm with the same IntelliJ and 2.2.0×3.3.4 and Java 17 (I checked out an old release tag of our application right now to try).
