### ISSUE TITLE
Replace Page schema with PagedModel when Page is generic type param of anothor

### ISSUE THREAD

**Issue by 781574155** [springdoc/springdoc-openapi#2818]
I know this PR: https://github.com/springdoc/springdoc-openapi/pull/2626
It solve problem like this: 
```public Page<FileResp> readAll()```
But it does not solve problem like this:
```public GeneralOperationResult<Page<FileResp>> readAll()```

**Comment by bnasslahsen** [comment]
@781574155,

Feel free to propose a PR for that.
