### ISSUE TITLE
Springdoc OpenAPI does not work with spring data rest

### ISSUE THREAD

**Issue by seedarren** [springdoc/springdoc-openapi#282]
I have a AccountRepository annotated with @RepositoryRestResource, but the Springdoc seems does not work to expose API documentation for Spring data rest. Is it not supported or this is a bug?

```
@RepositoryRestResource
public interface AccountRepository extends JpaRepository<Account, UUID> {

}
```

**Comment by springdoc** [comment]
Hi @seedarren, 

There no support planned to @RepositoryRestResource annotations of spring data rest. 
You need to use OAS3 annotations such as @operation
- https://github.com/swagger-api/swagger-core/wiki/Swagger-2.X---Annotations

This is rather explicit over magic Auto generation that tends to have issues.
You can also contribute to migrate to add the support for @RepositoryRestResource out of the box.

**Comment by Marx2** [comment]
I think it would be good idea to gather such tasks in one common place with the topic: No planned support, contribute if you want to have it

**Comment by silentsnooc** [comment]
@Marx2 does this mean that what I am trying (see https://stackoverflow.com/questions/59868163/why-is-springfox-not-exposing-repositoryrestresource) cannot work?

**Comment by bnasslahsen** [comment]
Yes, it cannot work, as there is no automatic documentation génération for spring-data-rest using springdoc-openapi.

**Comment by silentsnooc** [comment]
@bnasslahsen Thanks for clarification!

That's really unfortunate as this would be an insanely powerful feature. For production and even more for prototyping.

May I ask: Why it this not working? Can't it "just" honor the endpoitns genereate by `@RepositoryRestResource` as well?

What would it take to make this export work?

**Comment by bnasslahsen** [comment]
spring-data-rest entities endpoints are dynamically generated at runtime, 
Spring Data REST dynamically creates an implementation of this interface, when you can the spring-data-rest endpoint and not on the application startup.

**Comment by carlajf** [comment]
You could solve this adding the _[springdoc-openapi-data-rest](https://mvnrepository.com/artifact/org.springdoc/springdoc-openapi-data-rest/1.4.8)_ dependency

```
<dependency>
    <groupId>org.springdoc</groupId>
    <artifactId>springdoc-openapi-data-rest</artifactId>
    <version>1.4.8</version>
</dependency>
```
![image](https://user-images.githubusercontent.com/5709431/95995334-a3d89a80-0e31-11eb-99d5-57d14335a116.png)

I'm using spring-boot 2.2.6 and works like charm :) 

You could find more info in https://springdoc.org/

**Comment by Meumo** [comment]
> You could solve this adding the _[springdoc-openapi-data-rest](https://mvnrepository.com/artifact/org.springdoc/springdoc-openapi-data-rest/1.4.8)_ dependency
> 
> ```
> <dependency>
>     <groupId>org.springdoc</groupId>
>     <artifactId>springdoc-openapi-data-rest</artifactId>
>     <version>1.4.8</version>
> </dependency>
> ```
> 
> ![image](https://user-images.githubusercontent.com/5709431/95995334-a3d89a80-0e31-11eb-99d5-57d14335a116.png)
> 
> I'm using spring-boot 2.2.6 and works like charm :)
> 
> You could find more info in https://springdoc.org/

help me i'm so confuse
