### ISSUE TITLE
the sort of pageable are not convert corretly

### ISSUE THREAD

**Issue by 781574155** [springdoc/springdoc-openapi#2820]
![image](https://github.com/user-attachments/assets/4e8dabd7-3847-4cca-afc5-ad5aca1e8858)

the correct is
```
http://127.0.0.1:8082/tanqi-diting/user/files/search?page=0&size=1&sort=createTime,desc&sort=filename,asc
```
the swagger page convert it to
```
http://127.0.0.1:8082/tanqi-diting/user/files/search?page=0&size=1&sort=%5B%22createTime%2Cdesc%22%2C%22filename%2Casc%22%5D'
```

**Comment by bnasslahsen** [comment]
@781574155,

Not reproducible.
Remember, contributions to this repository should follow its [contributing guidelines](https://github.com/springdoc/springdoc-openapi/blob/39ef9f4121c4abcda26a12833b5467ac9720503f/CONTRIBUTING.adoc), [security policy](https://github.com/springdoc/springdoc-openapi/blob/39ef9f4121c4abcda26a12833b5467ac9720503f/SECURITY.md), and [code of conduct](https://github.com/springdoc/springdoc-openapi/blob/39ef9f4121c4abcda26a12833b5467ac9720503f/CODE_OF_CONDUCT.md).
