### ISSUE TITLE
SpringDoc - Adding extra object's properties

### ISSUE THREAD

**Issue by GAbbona** [springdoc/springdoc-openapi#2824]
**Describe the bug**

When having on a model an attribute which name starts with 'set' (eg. settlement). It creates in the v3/api-docs Json and also in the swagger-ui, an extra property (not included in the Java Model), named 'tlement' (without the set). It happens on any property which name starts with 'set'.

**To Reproduce**

After having everything setup for sprindoc swagger-ui:

- Add on any response model, an attribute which name starts with 'set', eg. settings.
- Run web application.
- Check on sagger-ui/index.html, in the response model shows an extra property named 'tings': "string"

**Expected behavior**

The expected behavior is that extra field should not be created. 

**Additional context**
Using openapi-generator-maven-plugin to generate from swagger contract, in target folder.

**Comment by bnasslahsen** [comment]
@GAbbona,

You problem is not clear / not reproducible.
Feel free to provide a [Minimal, Reproducible Example - with HelloController](https://stackoverflow.com/help/minimal-reproducible-example) that reproduces the problem.

This ticket will be closed, but can be reopened if your provide the reproducible sample.
