### ISSUE TITLE
Make it possible to declare parameter type in annotation definition

### ISSUE THREAD

**Issue by kkochanski** [springdoc/springdoc-openapi#2825]
I'm trying to create a public API using:
- Spring Boot `v3.4.0`
- Springdoc OpenAPI `v2.7.0`
- Hibernate Validators `v8.0.1`

Request definition.

```
@PostMapping(path = "/process", consumes = MediaType.APPLICATION_FORM_URLENCODED_VALUE)
@ResponseStatus(value = HttpStatus.OK)
public Response process(
    @Boolean @RequestParam(name = "is_dummy", defaultValue = "false") String isDummy,
    @Integer @Min(10) @RequestParam(name = "age") String age
) {
}
```

For that definition, library will output specification below.
```
"paths": {
    "/process": {
        "post": {
            "parameters": [
                {
                    "name": "is_dummy",
                    "in": "query",
                    "required": false,
                    "schema": {
                        "type": "string",
                        "default": "false"
                    }
                },
                {
                    "name": "age",
                    "in": "query",
                    "required": true,
                    "schema": {
                        "minimum": 10,
                        "type": "string"
                    }
                }
            ],
        }
    }
}
```

Library takes parameter type from it's Java definition. 

There's a Spring Boot integration issue with Hibernate validators related to types validation. Before running validators, Spring is changing request default parameter type which is String to expected by Controller. Like it was done in given code.

For instance, we got that declaration.

```
@Min(10) @RequestParam(name = "age") int age
```

Then we're doing request where `age` gets some String value. That causes exception below.

```
org.springframework.web.method.annotation.MethodArgumentTypeMismatchException: Method parameter 'age': Failed to convert value of type 'java.lang.String' to required type 'int'; For input string: "asdas"
```

I can try to create `@Integer` validator, but it won't be reached, since I will get exception above first.

It means that every Controller parameter should be a `String` and then every validator should validate a type.

The disadvantage is that Swagger documentation won't be properly crafted. Every parameter will be marked as a `String` one, when in reality it's not.

I imagine it should be possible to provide an expected type in annotation as well. Like ...

```
@Parameter(name="age", type"integer")
```

**Comment by bnasslahsen** [comment]
@kkochanski,

see the swagger documentation, and not `springdoc-openapi`.

https://swagger.io/docs/specification/v3_0/describing-parameters/
