### ISSUE TITLE
Make it possible to mark parameters with `@RequestParam` annotation to be sent in `form` instead of `query`.

### ISSUE THREAD

**Issue by kkochanski** [springdoc/springdoc-openapi#2826]
I'm using.

- Spring Boot `v3.4.0`
- Springdoc OpenAPI `v2.7.0`

The `@RequestParam` annotation is tricky. Spring Boot will scan `query` and `form` to pass data to annotated variable. 

```
@PostMapping(path = "/process", consumes = MediaType.APPLICATION_FORM_URLENCODED_VALUE)
@ResponseStatus(value = HttpStatus.OK)
public String process(
    @Boolean @RequestParam(name = "is_dummy", defaultValue = "false") String isDummy,
    @Min(10) @RequestParam(name = "age") int age
) {
    return "";
}
```

For this definition, doing a cURL or request from generated API Docs will not work. 

cURL
```
curl -X 'POST' \
  'http://localhost:8080/process?is_dummy=false&age=11' \
  -H 'accept: application/json' \
  -d ''
```

Few issues here.
1. Spring Boot will return  `org.springframework.web.HttpMediaTypeNotSupportedException: Content-Type is not supported` exception.
2. We got a POST so technically speaking parameters should be send in `form` instead of `query`.
3. In endpoint definition there's a mention that it consumes `Form Url Encoded`, but still Swagger do not setup a content-type.

Instead, cURL should like below.

```
curl -X 'POST' \
  'http://localhost:8080/process' \
  -H 'accept: application/json' \
  -H 'Content-Type: application/x-www-form-urlencoded' \
  -d 'age=11&is_dummy=false'
```

It's possible to fix given code by removing `consumes = MediaType.APPLICATION_FORM_URLENCODED_VALUE`. So we got.
```
@PostMapping(path = "/process", consumes = MediaType.APPLICATION_FORM_URLENCODED_VALUE)
@ResponseStatus(value = HttpStatus.OK)
public String process(
    @Boolean @RequestParam(name = "is_dummy", defaultValue = "false") String isDummy,
    @Min(10) @RequestParam(name = "age") int age
) {
    return "";
}
```

Then cURL works. Although I still we'd love to have a possibility to tell users to send a data in `form` instead of `query`.

**Comment by kkochanski** [comment]
@bnasslahsen Thanks a lot for your changes. 

I noticed that after your changes, for annotation below, the proper Swagger docs are generated:
```
@PostMapping(path = "/dummy", consumes = MediaType.APPLICATION_FORM_URLENCODED_VALUE)
```

Although for another ones below, not (it's still as it was before - params are added to `query` instead of `form`).

```
@PostMapping(path = "/dummy", consumes = MediaType.MULTIPART_FORM_DATA_VALUE)
``` 

I think we should send parameters via `form` whether the endpoints consumes `multipart` or `form urlencoded`. 

Thanks!

**Comment by bnasslahsen** [comment]
@kkochanski,

For `MediaType.MULTIPART_FORM_DATA_VALUE`, there can be multiple options and you can use 

```properties
springdoc.default-support-form-data=true
```

And if you are having another issue, make sure you provide the full description of the minimal sample with the expected results.
