### ISSUE TITLE
Is there a way to limit model properties per API

### ISSUE THREAD

**Issue by imiduo** [springdoc/springdoc-openapi#284]
Thanks for providing this library.

I have one question about how to limit model properties(via anotation) per API. Let's say there are two APIs post same model(this model has properties a/b/c/d), and for API-1 need properties a/b/d, for API-2 need properties a/c/d. 

Supposing already support it, could you help provide an example.

**Comment by springdoc** [comment]
Hi @imiduo, 

 Our libray is built on top of swagger-annotations.
 You can follow the documentation here for the usage:
 - http://springdoc.org/

 If your question is about the usage of swagger-annotations, you can ask your questions here instead:
- https://github.com/swagger-api/swagger-core/wiki/Swagger-2.X---Annotations

If you are still having more questions: Please make sure you provide:

- The sample (java) code to reproduce your issue.
- The result you have got in OpenAPI format
- The expected Result
