### ISSUE TITLE
Define multiple specs

### ISSUE THREAD

**Issue by ThanksForAllTheFish** [springdoc/springdoc-openapi#285]
I am in the process of migrating from spingfox to springdoc and facing a conversion issue.

In springfox, it is possible to create multiple `Docket`, which are rendered ui-wised in a drop down menu with multiple `spec`. This is useful, for instance, to clearly divide api versions.

Is it possible to obtain something similar with springdoc and its ui too? I am struggling to find related documentation and looking at the available properties it seems it is not something achievable.

Apologies if this is not the right channel to ask, but in case it is a missing feature (as it seems to me) it might be an interesting addition.

**Comment by springdoc** [comment]
Hi @ThanksForAllTheFish, 

 You can follow #213. The support wil be available for this feature with the release v1.2.19.
 It should be released tomorrow.
