### ISSUE TITLE
custom swaggerconfig

### ISSUE THREAD

**Issue by sendreams** [springdoc/springdoc-openapi#287]
the library has a default swaggerconfig class which init the swagger setting, is any way can support developer to custom the swagger setting?

**Comment by springdoc** [comment]
you can change the swagger config using the swagger properties.

You can have look at the FAQ (How can i configure Swagger UI?)  for some samples with prefix (springdoc.swagger-ui):
- https://springdoc.github.io/springdoc-openapi-demos/faq.html
