### ISSUE TITLE
preserve order of @Parameters not working for spring-boot 2.2

### ISSUE THREAD

**Issue by ny-currenxie** [springdoc/springdoc-openapi#289]
The previous fix on #274 works nicely while testing with spring-boot 2.1.x but not working in spring-boot 2.2. 

Likely due to the changed annotation handling ([https://github.com/spring-projects/spring-framework/wiki/Upgrading-to-Spring-Framework-5.x#upgrading-to-version-52](url)), the method `AbstractRequestBuilder.getApiParameters` can now only dig out `@Parameter` annotations in the third call to `AnnotatedElementUtils.findAllMergedAnnotations(method, io.swagger.v3.oas.annotations.Parameter.class)` even though they are wrapped in `@Parameters`.

Suggest all 4 `Collectors.toMap` in the method `AbstractRequestBuilder.getApiParameters` be changed to collect the results in `LinkedHashMap`

Sample code:
```
@Target({ElementType.METHOD, ElementType.ANNOTATION_TYPE})
@Retention(RetentionPolicy.RUNTIME)
@Parameters({
  @Parameter(
      in = ParameterIn.QUERY,
      description = "Page you want to retrieve (0..N)",
      name = "page",
      content = @Content(schema = @Schema(type = "integer", defaultValue = "0"))),
  @Parameter(
      in = ParameterIn.QUERY,
      description = "Number of records per page.",
      name = "size",
      content = @Content(schema = @Schema(type = "integer", defaultValue = "20"))),
  @Parameter(
      in = ParameterIn.QUERY,
      description =
          "Sorting criteria in the format: property(,asc|desc). "
              + "Default sort order is ascending. "
              + "Multiple sort criteria are supported.",
      name = "sort",
      content = @Content(array = @ArraySchema(schema = @Schema(type = "string")))),
  @Parameter(in = ParameterIn.QUERY, name = "pageable", hidden = true),
})
public @interface PageableParameter {}
```
```
@PageableParameter
public void someController(Pageable pageable){
   ...
}
```

Generated api-doc On spring-boot 2.2
```
 {"name": "size",...},
 {"name": "page",...},
 {"name": "sort",...}
```

Generated api-doc On spring-boot 2.1.x
```
 {"name": "page",...},
 {"name": "size",...},
 {"name": "sort",...}
```

**Comment by springdoc** [comment]
Hi @ny-currenxie, 

 Can you add sample code to reproduce this behaviour you are describing?
