### ISSUE TITLE
I think there are problems with the new version

### ISSUE THREAD

**Issue by programmer-luxw** [springdoc/springdoc-openapi#290]
1.
@Configuration
@EnableWebMvc
@ConditionalOnProperty(name = SPRINGDOC_SWAGGER_UI_ENABLED, matchIfMissing = true)
@SuppressWarnings("deprecation")
public class SwaggerConfig extends WebMvcConfigurerAdapter { // NOSONAR

@EnableWebMvc  -> This annotation breaking the default behavior of spring MVC in my project， 
                                  make my project abnormal.

2.When I set the configuration “springdoc.api-docs.enabled=true”，Although I can't access the OpenAPI anymore,But many beans are configured by default in the new version，even if they're useless,I think the configuration in the old version is better

**Comment by springdoc** [comment]
Hi @programmer-luxw, 

 `@EnableWebMvc`, will be removed for the next release.
 By default, you don't need to set springdoc.api-docs.enabled=true.
-  Which beans are you mentionning that are configured by default ?
- If you have any issue, can you add the sample code to reproduce it ?

**Comment by springdoc** [comment]
This issue can be reopened, if you provide the  additional information needed.

**Comment by programmer-luxw** [comment]
for example：I set  springdoc.api-docs.enabled=true, But the class SpringDocConfiguration will 
                     create many beans,although I don't need it.
 I want to have a master switch to control the loading of these classes. When I close the production environment, these classes will not be loaded, which makes my project more optimized.

**Comment by programmer-luxw** [comment]
> This issue can be reopened, if you provide the additional information needed.

for example：I set springdoc.api-docs.enabled=true, But the class SpringDocConfiguration will
create many beans,although I don't need it.
I want to have a master switch to control the loading of these classes. When I close the production environment, these classes will not be loaded, which makes my project more optimized.
