### ISSUE TITLE
Migration guide from SpringFox

### ISSUE THREAD

**Issue by Aloren** [springdoc/springdoc-openapi#292]
I've noticed that a lot of existing users are migrating from springfox project to springdoc. 
I suppose it would be awesome to have some short migration guide (something simple as this one for example: https://joel-costigliola.github.io/assertj/assertj-core-migrating-from-fest.html). I would like to contribute it if you don't mind. @springdoc What do you think?

**Comment by springdoc** [comment]
Hi @Aloren, 

 Please feel free to contribute to documentation and any relevant pages:

 FYI main used pages are:
 - https://github.com/springdoc/springdoc-openapi-demos/blob/master/docs/src/main/resources/index.md
- https://github.com/springdoc/springdoc-openapi-demos/blob/master/docs/faq.md

**Comment by Aloren** [comment]
@springdoc Thanks for pointing to the documentation links. I haven't found these from the beginning :) as they are not referenced in `https://github.com/springdoc/springdoc-openapi/blob/master/README.md`. I just got that they are published to https://springdoc.github.io/, but I suppose it would be better to make a bold link to the https://springdoc.github.io/, so that it is obvious that detailed docs are available there (as it is done here: https://github.com/testcontainers/testcontainers-java/blob/master/README.md)

What do you think?

**Comment by Marx2** [comment]
I agree that such a guide would be very good idea. I'm currently migrating about 30 microservices from springfox to springdoc.
As for now I've managed to:
- replace @ApiParam with @Parameter
- migrate oauth configuration
- refactor @ApiResponses
- reuse @Pageable support (not so pretty as in Springfox but useful)
Now I'm working on replacing @ApiImplicitParams and I'm missing good examples how to make default values in @Paremeter, especcially for objects

**Comment by cmalla94** [comment]
On this topic, I have a somewhat working bash script that doe migration for refactoring of annotations and imports. Let me know if this something that would useful to be part of the migration documentation. [repo](https://github.com/chadmalla-ff/swagger-migration)

**Comment by bnasslahsen** [comment]
Hi @Aloren,

 This is a good idea! Please feel free to propose any relevant information to improve the documentation of the library.

**Comment by Aloren** [comment]
Initial version added here: https://github.com/springdoc/springdoc-openapi-demos/pull/8

**Comment by bnasslahsen** [comment]
Thank you @Aloren for this very useful documentation, which will certainly be enhanced with other contribution.
The main site has been updated. It contains a direct link to the migration guide you have initiated:
- https://springdoc.github.io/springdoc-openapi-demos/migrating-from-springfox.html

**Comment by Mastcard** [comment]
Updated URL : https://springdoc.org/migrating-from-springfox.html

**Comment by huseyinmobil** [comment]
We create a tool (MobilizIT/springfox-tospringdoc) according to https://springdoc.org/migrating-from-springfox.html It is not complete yet but works for most cases
