### ISSUE TITLE
This issue can be reopened, if you provide the  additional information needed.

### ISSUE THREAD

**Issue by programmer-luxw** [springdoc/springdoc-openapi#294]
This issue can be reopened, if you provide the  additional information needed.

_Originally posted by @springdoc in https://github.com/springdoc/springdoc-openapi/issues/290#issuecomment-568556863_

For example: 
When I set springdoc.api-docs.enabled=false,The class SpringDocConfiguration will help me configure many beans, although I don't need them.
I want to have a master switch to control the loading of these beans. When I close in the production environment, these beans will not be loaded, which makes my project more optimized

**Comment by Aloren** [comment]
Documentation states that this property disables only `springdoc-openapi` endpoints. 
I agree with @programmer-luxw that all springdoc autoconfigurations should be disabled based on this property.

**Comment by springdoc** [comment]
Hi all, 

 Agree. Will be Handled for next release
