### ISSUE TITLE
QueryDSL support

### ISSUE THREAD

**Issue by Marx2** [springdoc/springdoc-openapi#298]
I want to ask if there's planned support for @QuerydslPredicate annotation from Spring Data Rest?
I was asking similar question for springfox, no response received:
https://stackoverflow.com/questions/53081245/document-querydsl-endpoint-with-swagger

**Comment by bnasslahsen** [comment]
There no automatic generation planned to spring-data-rest annotations. You need to use OAS3 annotations on your spring-data-rest parameters. 

As you mentioned on #282,  its now listed on the welcome page: that there is no planned support of automatic generation of srping-data-annotations.
- http://springdoc.org/

You can also contribute to add the support for the different annotations (`@RepositoryRestResource`, `@QueryDSL`, …)

**Comment by silentsnooc** [comment]
@bnasslahsen So what I am trying (see here https://stackoverflow.com/questions/59868163/why-is-springfox-not-exposing-repositoryrestresource) is not working?

Is there a particular reason why this does not work?

**Comment by bnasslahsen** [comment]
@silentsnooc, you shouldn't mix the sprindoc-openapi and springfox dependencies.
You need to choose, either springdoc (For OpenAPI 3) or springfox (For OpenAPI 2)

Note that there is no automatic code generation for spring-data-rest, using springdoc-openapi.

**Comment by silentsnooc** [comment]
@bnasslahsen Thanks for the hint and clarification!

**Comment by gibahjoe** [comment]
> I want to ask if there's planned support for @QuerydslPredicate annotation from Spring Data Rest?
> I was asking similar question for springfox, no response received:
> https://stackoverflow.com/questions/53081245/document-querydsl-endpoint-with-swagger

I know this question is kind of old but i ran into this this issue a few days back and decided to write a small lib for this just incase theres someone else who needs it. 

You can find it here https://github.com/gibahjoe/springdoc-param-customizer.

The library adds @QueryDslPredicate annotation support to springdoc.
Hope it helps and let me know your thoughts.

**Comment by bnasslahsen** [comment]
Hi @gibahjoe, 

 If you have a contribution to support QueryDSL for springdoc-openapi, you can propose a PR and we will have a look at it.

**Comment by gibahjoe** [comment]
Sounds good. Will do that
