### ISSUE TITLE
Support Spring Boot WebFlux Netty

### ISSUE THREAD

**Issue by davidmelia** [springdoc/springdoc-openapi#3]
I think one of the biggest features missing from the SpringFox project is the official release of WebFlux Netty support. 

It would be great if springdoc support webflux netty.  I can see the demo 'springdoc-openapi-test-app3' attempts to do this but 'spring-boot-starter-web' should be removed so that it's a pure webflux project.  If you do this you get the error 

```
Description:

Field requestMappingHandlerMapping in org.springdoc.api.OpenApiResource required a bean of type 'org.springframework.web.servlet.mvc.method.RequestMappingInfoHandlerMapping' that could not be found.

The injection point has the following annotations:
	- @org.springframework.beans.factory.annotation.Autowired(required=true)
```

Thanks

**Comment by springdoc** [comment]
For the moment, WebFlux is not yet supported. 
It will be available in future releases.

**Comment by springdoc** [comment]
springdoc-openapi, supports now spring-weblfux with Annotated Controllers. 
For this, just add the following dependency: 
`  <dependency>
      <groupId>org.springdoc</groupId>
      <artifactId>springdoc-openapi-webflux-ui</artifactId>
      <version>1.1.6</version>
   </dependency>`

spring-weblfux with Functional Endpoints, will be available in the future release
