### ISSUE TITLE
Curl call for file upload not working

### ISSUE THREAD

**Issue by chaki13** [springdoc/springdoc-openapi#30]
For my POST service when I use the option "Try it out", upload image and choose Execute my curl call look like 

`curl -X POST "http://localhost:8080/my-service/api/documents" -H "accept: */*" -H "Content-Type: multipart/form-data" -F "files=[object File]"`

And I get response that no files are sent. And the curl call looks like it's missing file location or I'm wrong?

**Comment by springdoc** [comment]
Hi, 

 There is an open feature related to uploading files from the swagger-ui. Once fixed, we will add reference to the last version of the ui.
 Uploading an arbitrary number of files (an array of files) is not supported. 
There is an open feature request at: 

- https://github.com/OAI/OpenAPI-Specification/issues/254. 

For now, you can use a binary string array as a workaround for uploading an arbitrary number of files:

Note that this will not produce the file upload interface in Swagger UI.
