### ISSUE TITLE
Reverse proxy configuration - port is lost

### ISSUE THREAD

**Issue by Marx2** [springdoc/springdoc-openapi#306]
With Spring 2.1 and bean configuration (property is also set but probably not used - I plan to upgrade to 2.2 soon) springdoc generally works through nginx. 
I enter 
http://localhost:9001/rights/swagger-ui.html 
and get redirect to 
http://localhost/rights/swagger-ui/index.html?configUrl=/rights/v3/api-docs/swagger-config
which is wrong, because port is lost
After adding port manually - everything is working correctly

I suppose proxy configuration is correct, because springfox was working correctly with it.

**Comment by bnasslahsen** [comment]
Hi @Marx2 ,

Please have a look at our FAQ, section (How can i deploy the Doploy springdoc-openapi-ui, behind a reverse proxy?)

There are some spring-boot properties to set on your application depending on the version you use.

- https://springdoc.github.io/springdoc-openapi-demos/faq.html

**Comment by Marx2** [comment]
Hi
I've based solution exactly on this description, and  - as I said - it's not fully working. In redirect port is set incorrectly (I mean - it's truncated). Your example works correctly only, if nginx is listening on port 80

**Comment by bnasslahsen** [comment]
This looks like an issue on your nginx configuration. 
There no change of the port in case of reverse proxy, on the springdoc-openapi code.

Try to set the following parameter on your nginx configuration and let us know if this helps , 
location / {
**proxy_set_header X-Forwarded-Port $server_port;**
...}

**Comment by Marx2** [comment]
Didn't help. I'll investigate it more.

Another thing I've noticed is that if I configure
`springdoc.api-docs.path=/v3/api-docs`
it works directly, but doesn't work through proxy.
Without this property config is correctly prepended:
`configUrl=/rights/v3/api-docs/swagger-config`
Having this property makes param looks exactly like in config, not prepended:
`configUrl=/v3/api-docs/swagger-config`
I don't know if it's correct behaviour.

**Comment by aconchillo** [comment]
I'm having the same issue. If browser URL contains a port, the port is dropped during the redirect. My nginx reverse proxy setup:

```
    location / {
      proxy_pass http://api:8080/;

      proxy_set_header Host              $host;
      proxy_set_header X-Real-IP         $remote_addr;
      proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Port  $server_port;
    }
```

So, it seems `X-Forwarded-Port` is ignored.

**Comment by aconchillo** [comment]
I just updated to springdoc `1.4.2` and same behavior.

**Comment by bnasslahsen** [comment]
@aconchillo,  

 This is the guidance, how to set the proxy configuration:
- https://springdoc.org/faq.html#how-can-i-deploy-springdoc-openapi-ui-behind-a-reverse-proxy

**Comment by aconchillo** [comment]
Thank you @bnasslahsen. Unfortunately, that's what I did. I read that link a few times already and using NATIVE when reverse proxy is listening on something different than 80 or 443 (which don't have port in a host:port|) all it's fine. Of course, it is possible that I missed something, but when springdoc creates the redirect URL it seems to miss the port.

I have no idea but I was wondering if this could be related:

https://github.com/springdoc/springdoc-openapi/blob/master/springdoc-openapi-ui/src/main/java/org/springdoc/webmvc/ui/SwaggerWelcome.java#L90

Which uses `ServletUriComponentsBuilder`. Spring documentation says:

```
Note: As of 5.1, methods in this class do not extract "Forwarded" and "X-Forwarded-*" headers that specify the client-originated address. Please, use ForwardedHeaderFilter, or similar from the underlying server, to extract and use such headers, or to discard them.
```

**Comment by bnasslahsen** [comment]
@aconchillo, 

 You need to review your spring-boot application settings. I confirm that if you set s`erver.forward-headers-strategy=NATIVE`, the port is lost.

-  As mentionned on the F.A.Q, if you need a consistent "Forwarded" headers support, the framework should be used.

You can set the following property insetead:

```properties
server.forward-headers-strategy=framework
```

**Comment by aconchillo** [comment]
Thank you @bnasslahsen. That worked! I thought that `NATIVE` was also a valid option.

In case anyone gets here... if your reverse proxy is behind docker and you are exposing another port (different than the reverse proxy is listening), this won't work. So it needs to be:

```
exposed-docker-port(8080) -> nginx-container(8080) -> application(any port)
```

If instead you do:

```
exposed-docker-port(8081) -> nginx-container(8080) -> application(any port)
```

The redirect will be to `http://localhost:8080/swagger-ui/index.html?configUrl=/v3/api-docs/swagger-config` and it will fail since 8080 is the internal container port. This is normal since nginx doesn't know anything about the original port 8081.
