### ISSUE TITLE
@ConditionalOnBean(GroupedOpenApi.class) in MultipleOpenApiSupportConfiguration Not Working

### ISSUE THREAD

**Issue by brianwyka** [springdoc/springdoc-openapi#307]
When switching from version `1.2.20` to `1.2.21` the `GroupedOpenApi` support stopped working for me.

I am dynamically registering `GroupedOpenApi` beans like such in a `@Configuration` class.

```java
GroupedOpenApi groupedOpenApi = GroupedOpenApi.builder()
                .addOpenApiCustomiser(createOpenApiCustomiser(info))
                .setGroup(resourceGroupName)
                .packagesToScan(packages)
                .build();

applicationContext.getBeanFactory().registerSingleton("groupedopenApi", groupedOpenApi);
    
```

I tried adding `@AutoConfigureBefore(MultipleOpenApiSupportConfiguration .class)`, but that did not work either.

**Comment by brianwyka** [comment]
@Aloren, does this have something to do with your changes?  Or perhaps a bug in spring?

I had this working before when it was simple property based enabling...

**Comment by bnasslahsen** [comment]
Hi @brianwyka, 

 As you have noticed, with the change of @Aloren the is no need of additionnal property to enable spring beans configuration.

 You can try `@Bean` annotation as described in the documentation:
 - https://springdoc.github.io/springdoc-openapi-demos/faq.html#how-can-i-define-multiple-openapi-definitions-in-one-spring-boot-project
 
 If you really need to use beanFactory.registerSingleton. It should be also working.
 It has been tested on the demo-app and its working as well. Here is the sample configuration class:

```java
@Configuration
public class MyConfig {

    public ConfigurableListableBeanFactory beanFactory;

    public MyConfig(ConfigurableListableBeanFactory beanFactory) {
        this.beanFactory = beanFactory;
        GroupedOpenApi bean = GroupedOpenApi.builder()
                .setGroup("stores")
                .pathsToMatch("/store/**")
                .build();
        beanFactory.registerSingleton("groupedopenApi", bean);
    }
}
```

If the issue still persists, you can add the sample code to reproduce your issue in this ticket and we will have a look at it.

**Comment by cmagnuson-mck** [comment]
@bnasslahsen I am not having success defining GroupedOpenApi beans with the beanFactory.registerSingleton() example above, with Spring Boot 2.6.6 and springdoc 1.6.8

In my config here: https://github.com/springdoc/springdoc-openapi-demos/compare/master...cmagnuson-mck:demo-registersingleton-not-working if I define @Bean's it works as expected.  But if I call beanFactory.registerSingleton() it does not.

My use case is for a library which configures swagger for various services.  We may have a different # of GroupedOpenApi's depending on each service's config, so we can't statically declare @Bean's in advance (only during startup once we can read it from Environment)
