### ISSUE TITLE
Failed to load remote configuration

### ISSUE THREAD

**Issue by bfs-natewallman** [springdoc/springdoc-openapi#308]
After updating from 1.2.18 to the latest version I noticed swagger-ui isn't working anymore.  When I bring it up I just get a message about "Failed to load remote configuration." I'm using a pretty vanilla configuration.  Is there a migration step that isn't documented?

**Comment by bfs-natewallman** [comment]
The following is what I see.  I'm still trying to track down what changed.

![image](https://user-images.githubusercontent.com/58448628/71607512-a9cdeb00-2b3f-11ea-8b87-7414abfc98e6.png)

**Comment by m-kay** [comment]
If you are using spring-security you have to include the config path in your sercurity configuration.
What I did in my security config was to exclude those paths from websecurity.

```java
@Configuration
public class WebSecurityConfiguration extends WebSecurityConfigurerAdapter {
	@Override
	public void configure(WebSecurity web) throws Exception {
		web.ignoring().antMatchers("/swagger-ui/**", "/v3/api-docs/**");
	}
}
```

**Comment by bfs-natewallman** [comment]
I had that before but I didn't have the wild card on the end as it wasn't needed.  Thanks for the tip!

**Comment by saiteja-konda** [comment]
It worked for me, Thank you

**Comment by ZelalemGizachew** [comment]
Adding this "/v3/api-docs/**" as one of the WHITELISTED urls fixes the problem.

`private static final String[] AUTH_WHITELIST = {
            "/authenticate",
            "/swagger-resources/**",
            "/swagger-ui/**",
            "/v3/api-docs/**",
            "/api/v1/app/user/auth/**"
    };

    @Bean
    public SecurityFilterChain securityFilterChain(HttpSecurity httpSecurity) throws Exception {
        httpSecurity
                .csrf(AbstractHttpConfigurer::disable)
                .authorizeHttpRequests(
                        auth -> auth.requestMatchers(AUTH_WHITELIST).permitAll()
                                .anyRequest().authenticated()
                )
                .sessionManagement(session -> session.sessionCreationPolicy(SessionCreationPolicy.STATELESS))
                .authenticationProvider(authenticationProvider)
                .addFilterBefore(jwtAuthFilter, UsernamePasswordAuthenticationFilter.class);
        return httpSecurity.build();
    }`

**Comment by lo-rodriguez** [comment]
A query. If I do not have the spring security dependency included, then I must include the Snippet which has been mentioned in the previous comments. If not, what should I do?

**Comment by ZelalemGizachew** [comment]
> A query. If I do not have the spring security dependency included, then I must include the Snippet which has been mentioned in the previous comments. If not, what should I do?

If you are not using the Spring Security Dependency, adding the swagger dependency is enough to load your apis in Swagger. I understand your question...

**Comment by Mauricio-Carrion** [comment]
I have the same issue when I deploy my spring boot app behind a nginx reverse proxy using docker. In localhost, swagger works fine.
