### ISSUE TITLE
oauth2-redirect.html issue

### ISSUE THREAD

**Issue by bfs-natewallman** [springdoc/springdoc-openapi#311]
From 1.2.19 and beyond we begin to have issues with the OAuth2 redirect functionality.

1.) If you don't specify an oauth2-redirect.html it defaults to one in the root context which doesn't exist.  For example it defaults to http://localhost:8080/oauth2-redirect.html which returns a 404.  I believe by default it should be returning to the one located along side the swagger-ui.  For example http://localhost:8080/swagger-ui/oauth2-redirect.html.

2.) If you attempt to override that value to take into account of the context root as outlined in the comment below you still get a 404 that it doesn't exist.  https://github.com/springdoc/springdoc-openapi/issues/240#issuecomment-567818580

Short answer is I'm pretty sure the Oauth2 support from Swagger was broke with recent releases.  If I revert to 1.2.18 and override the oauth2RedirectUrl everything works fine.

**Comment by bnasslahsen** [comment]
Hi @bfs-natewallman, 

 The oauth2-redirect.html issue, will be fixed on the next release, v 1.2.22;
