### ISSUE TITLE
HTTPS on Generated Sever Url

### ISSUE THREAD

**Issue by bfs-natewallman** [springdoc/springdoc-openapi#314]
I like the current ability where if you don't provide the Severs to the OpenAPI specification it generates one based off the current host serving the specification.  The issue I have is the generated version always assumes http instead of https.  This works great locally but fails when I then deploy the application in other environments where https is being used.  Is there a way to modify this behavior?

**Comment by bnasslahsen** [comment]
There is no problem if your application uses https.
If your application is deployed behind a proxy who sets the **https** connection. You can configure the spring-boot application to use the url as the proxy:
 - https://springdoc.github.io/springdoc-openapi-demos/faq.html#how-can-i-deploy-the-doploy-springdoc-openapi-ui-behind-a-reverse-proxy

Or you can customize OpenAPI object programmatically and set the server url. But this should be the last solution for the issue you are facing
- https://springdoc.github.io/springdoc-openapi-demos/faq.html#can-i-customize-openapi-object-programmatically

**Comment by bfs-natewallman** [comment]
Thanks @bnasslahsen! I'll give those a shot.
