### ISSUE TITLE
Enable springdoc-openapi hides static files

### ISSUE THREAD

**Issue by ozooxo** [springdoc/springdoc-openapi#316]
After enable springdoc-openapi in POM file (Code in a quite complicated project https://github.com/gitenter/gitenter/commit/2f79ccdefe32a06aca96782c54f2f6dba676b6d5#diff-a4142f9482274ca34f324868c2c3d002R237, but just for references), [the static files in `src/main/webapp/resources` (e.g. the css file)](https://github.com/gitenter/gitenter/tree/2f79ccdefe32a06aca96782c54f2f6dba676b6d5/capsid/src/main/webapp/resources) can no longer be loaded. 

I understand it is not a problem in general, as a pure Restful Spring project doesn't use `webapp` at all. I am facing it because I am in the migration from Spring/Apache Tiles to API+a JS frontend. But just to ask if there's an easy fix for this.

**Comment by bnasslahsen** [comment]
Hi @ozooxo, 

 You can use the last version of springdoc, v1.2.22. The support is better for compatibility with other static ressources.  Let us know, if this version solves your problem.
