### ISSUE TITLE
name property from @Schema annotation on field level is duplicated in generated swagger json

### ISSUE THREAD

**Issue by Ndenn00** [springdoc/springdoc-openapi#319]
When @Schema annotation is used inline to define a model property, the name="xxx" setting is not reflected in the generated swagger yml file/json endpoint.  

Response body, class Dog, has the following annotations.  

```
@Schema(name = "Dog")
data class Dog(

    @JsonProperty("display_name")
    @Schema(
        name = "display_name",
        description = "A name given to the Dog",
        example = "Fido"
    )
    val displayName: String,
)
```

The generated file results in duplication, including both the jsonproperty and variable names. The intended name 'display_name' is then not picked up by tools such as Redoc. 

```
"components": {
        "schemas": {
            "Dog": {
                "type": "object",
                "properties": {
                    "display_name": {
                        "type": "string",
                        "description": "A name given to the Dog.",
                        "writeOnly": true,
                        "example": "Fido"
                    },
                    "displayName": {
                        "type": "string"
                    }
                }
            }
```

 Possible related issue in a similar project [https://github.com/micronaut-projects/micronaut-openapi/issues/4](url)

**Comment by bnasslahsen** [comment]
The result you are describing is not reproducible with the last version of springdoc-openapi:
You can have a look at the following test which confirms that: f4e3fe56818bf2817e40fc2f6a70f155f5cfe2fc

If you are still facing this same issue with springdoc-openapi, please add a sample HelloController with only the necessary information to reproduce your issue. 

There is no need to create new issues. If you add the necessary information to reproduce this issue, this ticket it will be reopened.
