### ISSUE TITLE
Support the io.swagger.v3.oas.annotations.Hidden annotation to exclude from swagger docs

### ISSUE THREAD

**Issue by leoherbie** [springdoc/springdoc-openapi#32]
The Hidden annotation does not appear to be supported yet.  For the time being, you can annotate the individual Controller methods with `@Operation(hidden = true)`

**Comment by springdoc** [comment]
Hi, 
@Hidden annoatation, was not yet supported. 
It will be possible to use it, from the release v1.1.18 of springdoc-openapi.
