### ISSUE TITLE
oauth2-redirect.hml issue if none specified

### ISSUE THREAD

**Issue by bfs-natewallman** [springdoc/springdoc-openapi#320]
I didn't have the option of re-opening https://github.com/springdoc/springdoc-openapi/issues/311 otherwise I would. If no oauth2RedirectUrl is provided it defaults to the root of the application which is incorrect.  The default behavior should be to point to webjar path where the corresponding html file resides.  Swagger-ui provides a oauth2-redirect.html file which is responsible for handling the redirect and parsing the token as seen here: https://github.com/swagger-api/swagger-ui/blob/master/dist/oauth2-redirect.html

**Comment by bnasslahsen** [comment]
Hi @bfs-natewallman, 

 What you are asking for is additional feature to calculate the oauth2RedirectUrl, if not provided without having to declare any property.
 It will be added on the next release v1.2.23.

 With v1.2.22, you can just declare:
```properties
springdoc.swagger-ui.oauth2RedirectUrl=/swagger-ui/oauth2-redirect.html
```
