### ISSUE TITLE
Resource return type not recognized as binary response

### ISSUE THREAD

**Issue by IvoMajic** [springdoc/springdoc-openapi#322]
It seems the Spring Resource type is currently not recognized as a binary response (I am returning a Resource subtype - FieSystemResource). The Resource object shows up as a schema in the UI. Here is my current method definition:

`@GetMapping("/{imageId}", produces = [MediaType.IMAGE_JPEG_VALUE])
fun getImage(@PathVariable(value = "imageId") imageId: String): Mono<Resource>`

Is it possible to somehow override this behavior, to recognize it as a binary response?

Thank you for your help

**Comment by bnasslahsen** [comment]
You can workaround it by overriding calculateSchemaFromParameterizedType method in the ResponseBuilder class.
We can also plan to add native support for it for the next release. 
For that you can propose a PR, or 
- Provide the sample (java) code to reproduce your issue.
- The result you have got in OpenAPI format
- The expected Result

**Comment by gotson** [comment]
Hello, i am interested in this also.

I created a gist with a minimal sample, along with the current and expected result: https://gist.github.com/gotson/57454f328ed5dfab26af0cafc67e2eef

---

I also added an example for `byte[]` that currently return a type `string` with format `byte`. 

According to the [spec](https://swagger.io/specification/) the format `byte` should be for "base64 encoded characters", while `binary` is for "any sequence of octets".

I would say that format `binary` would better fit a `byte[]`, but you may have another view.

**Comment by bnasslahsen** [comment]
Hello @gotson ,

 As you might know we rely on official swagger jars (who should be respectful to the spec)
 springdoc-openapi uses swagger-core, to generate the OpenAPI description.

 I can confirm this behaviour, is related to swagger-core. Here is the sample code, that confirms that:
```java
ResolvedSchema resolvedSchema = ModelConverters.getInstance()
		.resolveAsResolvedSchema(
				new AnnotatedType(byte[].class).resolveAsRef(true));
if (resolvedSchema.schema != null) {
	ArraySchema schemaN = (ArraySchema) resolvedSchema.schema;
	Assert.isTrue("string".equals(schemaN.getItems().getType()), "");
	Assert.isTrue("byte".equals(schemaN.getItems().getFormat()), "");
}
```

Now this is said, if you need byte which might be more correct/spec in your case, you can change the default response type using swagger-annotations:

`@ApiResponse(content = @Content(schema = @Schema(type = "string", format = "byte")))`

 There was a closed issue, related to this behaviour on swagger:-core project, but you can also share your opinion:
 - https://github.com/swagger-api/swagger-core/issues/1290#issuecomment-391105921

**Comment by gotson** [comment]
Thanks for the details, the issue you mentioned seems to be about the v2 of the spec only though. But that's OK, I'm overriding the behaviour already as you mentioned also. 

For the Spring Resource type do you have everything needed?

**Comment by bnasslahsen** [comment]
Not sure to understand what are you expecting about  Spring Resource.
Can you please elaborate ?

**Comment by gotson** [comment]
The same thing the OP requested, it should be considered a `binary` return type by default.

You mentionned:

> We can also plan to add native support for it for the next release.

So i provided the samples as you requested.

**Comment by bnasslahsen** [comment]
ok @gotson, 

 We can make the default behaviour of Resource to return binary, which might be useuful for many cases.
 If someone wants another Return type, he can anyway use @ApiResponse.
 It will be added to the next release v1.3.3.
