### ISSUE TITLE
Question: Displaying composition of models in example value of response

### ISSUE THREAD

**Issue by Jacob-cheng-2412** [springdoc/springdoc-openapi#326]
I would like to display a combination of two models as a complex object in an example value. I tried using allOf, but the result was a combination of the two models with fields having similar field names merged. 

```java
@ApiResponse(responseCode = "200", description = "ok", content = @Content(schema = @Schema(type = "object", allOf = {Customer.class, Order.class})))
```

**Model 1**
```json
Customer {
"id" : 1
"name"  : " "
"address"  : " "
}
```
**Model 2**
```json
Order {
 "id" : 1
 "name" : ""
 "date" :""
}
```
On trying to fetch complete customer information , I want the order information to be included as an array of objects within customer object.

**Expected Example Response** 
```json
{
"id" : 1
"name" : ""
"address" :""
"orders":
   [ 
       {
             "id" : 1
             "name" : ""
             "date" :""
        }
   ]
}
```

**Actual Example Response** 
```json
{
"id" : 1
"name" : ""
"address" :""
 "date" :""
}
```
 Is there any way to get a composite object ? Any help is highly appreciated , thanks

**Comment by m-kay** [comment]
If you have the composition in your actual java class then it is also generated like this.
Try with the following java classes:

```java
public class Customer {
    private int id;
    private String name;
    private String address;
    private List<Order> orders;
}

public class Order {
    private int id;
    private String name;
    private Date date;
}
```
In your annotation you should only use Customer.class as response object or if the Customer class is the return type of your controller method you should not even need the @ApiResponse annotation.

**Comment by bnasslahsen** [comment]
Thank you @m-kay for your answer. I totally agree.

**Comment by Jacob-cheng-2412** [comment]
Thanks @m-kay and @bnasslahsen for your quick response. I do have composition in my java classes. But the problem for me is only two of the apis associated `Customer` class have `Orders` class in the response. All the other apis **must not** have `Orders` in response.

For example GET /customers will return only `Customers` with `Order` information **only if** the 'orders' parameter in the api is set to 'true' (default is 'false')
```curl
http://localhost:8080/customers?orders=true
```
Otherwise `Order` must not be present in result. Also , `Order` must be shown only for GET requests.

Therefore , we need to have the below code 
```java
@JsonIgnoreProperties(value = {"orders"}, allowGetters = true)
```
On removing the above statement, the response is displaying all response examples (POST, GET etc) with `Order` in it, which is not what I want. Can we set a custom example for just one or two apis with `Order` in it ?

**Comment by m-kay** [comment]
Ok, there are two aspects in your question. One is how you implement the desired behaviour and the other is how you document this with springdoc. 

1. Implementation
I would suggest you to use `@JsonView`to achieve your functionality since `@JsonIgnoreProperties` will always ignore those properties on the annotated class. With `@JsonView`you can have different "views" of your object on different endpoints. See [Jackson JSON Views](https://www.baeldung.com/jackson-json-view-annotation)
2. Documentation with springdoc/OpenAPI 3.0
As far as I know the OAS 3.0 specification does not allow you to document different responses for the same endpoint with different parameters. It is only possible for different paths, methods or media types. However you could still use the `Customer` response which includes the `Order` list and mark it as `required=false`.

Hope this helps, otherwise it would be good to have an example of your code to better understand your needs.

**Comment by m-kay** [comment]
Actually I was wrong, OAS 3.0 allows you to have different responses with the oneOf schema, you can just not tell from the documentation which response will be used in which case.

Try this:
```java
public class Views {
	public static class Customer {
	}
	public static class CustomerWithOrders extends Customer {
	}
}
```
```java
public class Customer {
	@JsonView(Views.Customer.class)
	private int id;
	@JsonView(Views.Customer.class)
	private String name;
	@JsonView(Views.Customer.class)
	private String address;
	@JsonView(Views.CustomerWithOrders.class)
	private List<Order> orders;
}
```
```java
public class Order {
	private int id;
	private String name;
	private Date date;
}
```
```java
@RestController
public class CustomerController {
	@JsonView(Views.CustomerWithOrders.class)
	@GetMapping(value = "/customers", params = "orders=true")
	public Customer getCustomerWithOrders(@Parameter boolean orders){
		//your logic
		return new Customer();
	}

	@JsonView(Views.Customer.class)
	@GetMapping(value = "/customers")
	public Customer getCustomer(){
		//your logic
		return new Customer();
	}
}
```

**Comment by Jacob-cheng-2412** [comment]
So, I do not want different responses for the same endpoint. Customer controller has two apis. 

1.  GET /customers?orders=true ---> requires `orders` in response **example**
2. POST /customers ----> does not require `orders` in response **example**

The below line of code was introduced for `orders` variable because I do not want the POST /customers/{id} to be able to add an order while creating a new customer. Orders must be added to customers only using Order apis.
```java
@JsonIgnoreProperties(value = {"orders"}, allowGetters = true)
```
Can we allow orders to appear in GET requests because the @JsonIgnoreProperties has `allowGetters=true` ? 

My sample code below:
**Views.java**

```java
public class Views {
  public class Request {
  }

  public class Response extends Request {
  }

}
```

**CustomerModel.java**

```java
@JsonIgnoreProperties(value = {"orders"}, allowGetters = true)
public class Customer extends  {

  @Setter private String customerId;
  @Setter private String customerName;
  @Setter private List<Order> orders;


  @Schema(description = "Unique id of customers", example = "cust-id", required = true)
  @JsonView(Views.Request.class)
  @JsonProperty(value = "id")
  public String getCustomerId() {
      return customerId;
  }
  public Customer customerId(String customerId) {
      setCustomerId(customerId);
      return this;
  }

  @Schema(description = "Customer name", example = "cust-name", required = true)
  @JsonView(Views.Request.class)
  @JsonProperty(value = "name")
  public String getCustomerName() {
      return customerName;
  }
  public Customer customerName(String customerName) {
      setCustomerName(customerName);
      return this;
  }

  @Schema(description = "orders of customer")
  @JsonView(Views.Response.class)
  public Set<Order> getOrders() {
      return orders;
  }

.
.
.
}
```

**CustomerController.java**

```java
@Operation(summary = "List all customers")
@ApiResponse(responseCode = "200", description = "ok")
@RequestMapping(path = "/customers" method = RequestMethod.GET, produces = { "application/json"})
@JsonView(Views.Response.class)
@ResponseBody
public List<Customer> list(
        @Parameter(description = "set to 'true' to include the order information in the response, default is 'false'")
        @RequestParam(name = "orders", required = false, defaultValue = "false") boolean orders) {
          .
          .
    return customers;
}

@Operation(summary = "Adds a new customer")
@ApiResponses(value = {@ApiResponse(responseCode = "201", description = "a new customer is created")})
@RequestMapping(path = "/customers" method = RequestMethod.POST, consumes = {"application/json"})
@ResponseStatus(HttpStatus.CREATED)
@JsonView(Views.Request.class)
@ResponseBody
public Customer create(
        @Parameter(description = "customer details")
        @JsonView(Views.Request.class)
        @RequestBody Customer customer) {
          .
          .
}
```

**Comment by m-kay** [comment]
You don't need the `@JsonIgnoreProperties` because you already have `@JsonView(Views.Response.class)` on the orders property and you use this view for the POST request, so all should work fine. 
For the case where orders should only be shown in the GET request when orders parameter is true you have to change the json view of the current get method to `@JsonView(Views.Request.class)` and add another controller method with `@RequestMapping(path = "/customers" method = RequestMethod.GET, produces = { "application/json"}, params = "orders=true")` and `@JsonView(Views.Response.class)`

**Comment by Jacob-cheng-2412** [comment]
Just to clarify @JsonIgnoreProperties was introduced for functionality purposes and not for swagger display purposes. So even if someone randomly adds orders in the body of POST request (even though its not visible in POST request body example) it will not get set in the code. 
But you are saying even without the @JsonIgnoreProperties just setting a view for the variable should prevent users from setting its value in POST request body ?

**Comment by m-kay** [comment]
Ah ok, got it!
Maybe you should use a different model for the request and response. You could try the following:
```java
@JsonIgnoreProperties(value = {"orders"}, allowGetters = true)
public class CustomerRequest extends Customer {}
```

**Comment by Jacob-cheng-2412** [comment]
I will give that a try , thank you so much :)
