### ISSUE TITLE
Enhancement: Overwrite index.html from webjar with a generated index.html

### ISSUE THREAD

**Issue by m-kay** [springdoc/springdoc-openapi#328]
Instead of the redirect with parameters I would like to generate the index.html and set config parameters directly in the markup/javascript which is generated. This would allow more possibilities to configure swagger ui. E.g. one could add initOAuth() method in the script which is needed to pre-fill the authentication form with password flow.

Would you consider something like that or do you have any other ideas how to add additional scripts to the markup?

**Comment by bnasslahsen** [comment]
Hi @m-kay, 

 we have chosen to rely onthe official wejars and use the standard ui configuration parametrs.
 You can rely on the springdoc-openapi-webmvc-core or springdoc-openapi-webflux, and use add the exploded swagger-ui files to your application to customise them.
 If you find out a more flexible way to customise the index.html , please don't hesitate to contribute.

**Comment by m-kay** [comment]
I have done this in my own application because I could not find another way to initialize OAuth login form. I'm only overwriting the index.html which still links to the scripts from the webjar.

**Comment by bnasslahsen** [comment]
Hi @m-kay, 

 A futrue support is planned for for custom OAuth 2.0 configuration, of the swagger-ui.
 You can have a look at the master which integrated the fix for #333.

**Comment by m-kay** [comment]
Sounds great! 
Would you may consider to also generate the configuration for SwaggerUIBundle to get rid of the redirect with configUrl?

**Comment by bnasslahsen** [comment]
Yes, this is a good Idea. 
Don't hesitate to propose a PR.
