### ISSUE TITLE
Multiple OpenAPI definitions in spring webflux

### ISSUE THREAD

**Issue by cmario** [springdoc/springdoc-openapi#329]
Hi,

according to #213 this feature is available from version v1.2.19. I am just wondering if the same is supported for webflux or only for mvc as I cannot make it work following the example https://github.com/springdoc/springdoc-openapi/tree/master/springdoc-openapi-webmvc-core/src/test/java/test/org/springdoc/api/app68.

My configuration is the one below:
```
springdoc:
  swagger-ui:
    enabled: false
  api-docs:
    enabled: true
    groups:
      enabled: true

@Bean
public GroupedOpenApi userOpenApi() {
        return GroupedOpenApi.builder()
                .setGroup("users")
                .pathsToMatch("/api/v1/**")
                .build();
}
```
The expected result is to have the OpenAPI description under /v3/api-docs/users but I get a 404. I am using version 1.2.24.

Thank you
Regards
Mario

**Comment by bnasslahsen** [comment]
Hi @cmario,

 This feature is not available yet for webflux.
 Will be available for the next release. v1.2.25;

**Comment by cmario** [comment]
Thanks a lot @bnasslahsen. That was quick :-)
