### ISSUE TITLE
Support the io.swagger.v3.oas.annotations.security.SecurityScheme annotation

### ISSUE THREAD

**Issue by leoherbie** [springdoc/springdoc-openapi#33]
Support for this annotation looks implemented in org.springdoc.core.getSecurityScheme() but it is not yet called.  I realize this is a new project.  I hope filing these issues is helpful or at least not annoying.

It's nice to see a simple clean project for integrating swagger 3 & spring-boot.  Keep up the good work.  Much appreciated.

**Comment by springdoc** [comment]
Hi, 

 SecurityScheme definition is possible programmatically, by overriding OpenAPI: 
 
```java
 @Bean
 public OpenAPI customOpenAPI(@Value("${springdoc.version}") String appVersion) {
  return new OpenAPI()
	.components(new Components().addSecuritySchemes("basicScheme",
	new SecurityScheme().type(SecurityScheme.Type.HTTP).scheme("basic")))
	info(new Info().title("SpringShop API").version(appVersion)
	.license(new License().name("Apache 2.0").url("http://springdoc.org")));
 }
```
	
 
 The support of io.swagger.v3.oas.annotations.security.SecurityScheme was in progress. It will be available with v1.1.18 of springdoc-openapi.
