### ISSUE TITLE
Set default clientId in springdoc

### ISSUE THREAD

**Issue by artemmysikigorevich** [springdoc/springdoc-openapi#333]
Hi!
I migrate  from springfox-swagger2 library
and cant set default clientId when create OAuthFlows.
When use springfox-swagger2 
I decided it like this

   @Bean
    public SecurityConfiguration security() {
        return SecurityConfigurationBuilder.builder()
                .clientId("myClientIdForTest")
                .clientSecret("myClientIdSecretForTest")
                .build();
    }

(https://github.com/springfox/springfox/blob/master/springfox-swagger-common/src/main/java/springfox/documentation/swagger/web/SecurityConfiguration.java)
 
 
![image](https://user-images.githubusercontent.com/5956206/72047385-fa3a0b00-32ec-11ea-9b01-00294fc113f0.png)

How to set default clientId in springdoc?

**Comment by bnasslahsen** [comment]
Hi @artemmysikigorevich, 

 Unfortunately, there is no standard swagger-ui configuration property, but we will propose an enhancement to handle it:
 - https://swagger.io/docs/open-source-tools/swagger-ui/usage/configuration/

 We will need to rely on calling the initOAuth method, which is packaged inside the swagger-ui webjars and we haven't planned to embed custom swagger-ui, as used in springfox.
 - https://swagger.io/docs/open-source-tools/swagger-ui/usage/oauth2/

With the next release 1.2.27, you will be able, to use the custom swagger-ui oauth properties, and using the following prefix `springdoc.swagger-ui.oauth`:

```properties
springdoc.swagger-ui.oauth.clientId=myClientId
springdoc.swagger-ui.oauth.clientSecret=clientSecret
```

**Comment by rycee** [comment]
@bnasslahsen I'm using `springdoc-openapi-webflux-ui` and this change does not appear to be present in that module. Am I mistaken? If not then I can create an issue for adding it to `springdoc-openapi-webflux-ui`.

**Comment by bnasslahsen** [comment]
@rycee, 

 This feature has only been added for web-mvc.
 It will be added for web-flux for the next release: v1.2.34.

**Comment by rycee** [comment]
@bnasslahsen Ah, excellent. Thank you very much!
