### ISSUE TITLE
How to Edit the title of the swagger doc

### ISSUE THREAD

**Issue by anksngp** [springdoc/springdoc-openapi#335]
Hi,

While using swagger 2 wih spring boot, we used to put @configuration
@EnableSwagger2 annotation on top of a class with
@bean
public Docket api() {
return new Docket(DocumentationType.SWAGGER_2).directModelSubstitute(ZonedDateTime.class, String.class).select()
.apis(RequestHandlerSelectors.basePackage("com.test")).paths(PathSelectors.any()).build()
.enable(environmentProperties.isEnableSwagger());
}

But the same way is not working with swageger 3 , i still get the same default tile as

OpenAPI definition
v0
OAS3
/v3/api-docs

How can i customise this page title?

**Comment by bnasslahsen** [comment]
Hi @anksngp,

 You can use, swagger2 standard annotations `@OpenAPIDefinition`: 
 - https://github.com/swagger-api/swagger-core/wiki/Swagger-2.X---Annotations#OpenAPIDefinition

`@OpenAPIDefinition(info = @Info(title = "My App", description = "Some long and useful description", version = "v1", license = @License(name = "Apache 2.0", url = "https://www.apache.org/licenses/LICENSE-2.0")))`

 Or 
 You can do it programmatically:
- https://springdoc.github.io/springdoc-openapi-demos/faq.html#can-i-customize-openapi-object-programmatically

**Comment by amorenew** [comment]
@bnasslahsen It works with @ bean in application class
I wonder how could I put it in a seprate class ?
https://springdoc.org/faq.html#can-i-customize-openapi-object-programmatically
