### ISSUE TITLE
Using simple index.html under static does not work

### ISSUE THREAD

**Issue by lofidewanto** [springdoc/springdoc-openapi#336]
Hi All, 

I have following problem.
- I have a simple webapp with Spring Boot 2.2.2.RELEASE.
- In this webapp I only have one simple index.html.
- Everything works fine, I can access the index.html from http://localhost:9090/context-path/index.html

After this I added 
```            
<dependency>
    <groupId>org.springdoc</groupId>
    <artifactId>springdoc-openapi-ui</artifactId>
    <version>1.1.44</version>
</dependency>
```
- I could access http://localhost:9090/context-path/swagger-ui.html successfully but I cannot access my http://localhost:9090/context-path/index.html anymore. Got 404.

Is there anything I should configure?

BTW. Trying the same thing with SpringFox 2.9.2 works without any problems. I could get the swagger-ui and also the index.html. But I need to configure following:

```
@Configuration
@EnableSwagger2
public class SpringFoxConfig {
	@Bean
	public Docket api() {
		return new Docket(DocumentationType.SWAGGER_2).select().apis(RequestHandlerSelectors.any())
				.paths(PathSelectors.any()).build();
	}
}
```

Thanks a lot.

**Comment by bnasslahsen** [comment]
Hi, 

 Please use the last version: v1.2.25 and give us your feedback.

**Comment by lofidewanto** [comment]
Using 1.2.25 works, thanks
