### ISSUE TITLE
Facing performance issue, on many connected data

### ISSUE THREAD

**Issue by TLiese** [springdoc/springdoc-openapi#337]
I do notice poor client/server performance, when using heavily connected data with some circle references. Is this a configuration mistake or is there currently no option to set a max recursion depth?

**Comment by bnasslahsen** [comment]
Please add more precision about the poor performance you are facing. As you might know, performance issues can be related to many parameters on client and server side. There is no know issues of springdoc-openapi library itself.

Describe, what is slow: 
- Is it swagger-ui ?
- Is it the /v3/api-docs endpoint? Both ?
- what is the load time displayed on the log of the springdoc-openapi?
- Describe your architecture context: which server are you using ? what is the sizing of your server (RAM / CPU / OS) ? What are the caracteristics of your client (browser / os / CPU / RAM / OS)
- Precise the number of endpoints you are exposing.
- what is the size of the generated json on /v3/api-docs
- Ideally, add a sample code to reproduce.

**Comment by TLiese** [comment]
I guess it's both client and server sided as the client feels really slow and the server outputs a loading time of around 20s. `[INFO ] 10-01-2020 14:54:36.557 [http-nio-8080-exec-8] AbstractOpenApiResource - Init duration for springdoc-openapi is: 18398 ms`
/v3/api-docs endpoint? yes.
I use an I Mac with 24gigs of ram and an i7 quad core cpu.
The json size: Content-Length: 244510
Precise the number of endpoints you are exposing: I'm currently testing the setup locally, I do expose every endpoint our rest-api has.

**Comment by bnasslahsen** [comment]
Its taking 18 seconds on the server side.
You didn't give more precisions on the number of Apis / endpoints you are exposing.

- You content lenght is in which unit ?
- Can you confirm which springdoc-openapi components and versions are you using ?
- Do you have a sample code to reproduce ?

**Comment by TLiese** [comment]
I have around 100 api endpoints.
I use the latest version of Springboot and springdoc-openapi
` implementation 'org.springdoc:springdoc-openapi-common:1.2.26'
    implementation 'org.springdoc:springdoc-openapi-ui:1.2.26'
springBootVersion = '2.2.2.RELEASE'`
Unfortunately I don't have any sample code available for publication right now.

**Comment by bnasslahsen** [comment]
Please precise your content lenght and add the unit  (for example 1 MB)
What is the load performance of the UI, during:
 - The first Load
 - The second Load

**Comment by bnasslahsen** [comment]
@TLiese, can you provide the additional information asked about your issue ?

**Comment by TLiese** [comment]
So I ran the site again using cromes performance monitor with the following results:
1.st load: 
```
7 ms: Loading
1701 ms: Scripting
145 ms: Rendering
32 ms: Painting
97 ms: System
20s: idle after request waiting for the server resonse.
```

2.nd load:
```
7 ms: Loading
3114 ms: Scripting
88 ms: Rendering
22 ms: Painting
104 ms: System
393ms: idle after request waiting for the server resonse.
```

Memory usage:
```
JS heap size: 28mb
Content-Length: 244510 decimal number of octets -> Bytes 
```

**Comment by TLiese** [comment]
@bnasslahsen I did.

**Comment by bnasslahsen** [comment]
Hi @TLiese, 

 The first load duration, might be related to the size of your application. Without any sample code to reproduce it, its very difficult to go for further investigations on the server side..
 The second load shows that the server content is already optimized, after the first load.

 You can also split the 100 endpoints into multiple groups, which can be sometimes more convenient from the end user perspective.

Our library is built on the top of the swagger-an official wedge.
The load performance of the ui, is only based on the swagger-ui.

You can also ask on the github of swagger-ui for the performance on the client side:
 - https://github.com/swagger-api/swagger-ui/issues
