### ISSUE TITLE
pathsToMatch and packagesToScan only work in camel-case in application.yml

### ISSUE THREAD

**Issue by waschmittel** [springdoc/springdoc-openapi#338]
```yml
springdoc.pathsToMatch # works
springdoc.packagesToScan # works
springdoc.paths-to-match # is ignored
springdoc.packages-to-scan # is ignored
```

I assume this is because of the SpEL expressions definied in org.springdoc.core.Constants

This is especially unfortunate because the non-camel-case variant is specified in **spring-configuration-metadata.json** which is read by my IDE for auto-completion of application.yml

It took me a while to find out why it didn't work for me.

But I'm still very happy that I finally have OpenApi 3.0 :-)

**Comment by bnasslahsen** [comment]
Hi @waschmittel , 

 Thank you for your feedback.
 It will be fixed, for the next release.
