### ISSUE TITLE
Question: Is there a way to allow @JsonIgnoreProperties( allowGetters = true) to allow the variable to be present in response example values , instead of avoiding it ?

### ISSUE THREAD

**Issue by Andrew3431** [springdoc/springdoc-openapi#341]
The @JsonIgnoreProperties hides the variables from appearing in the swagger document, which is expected. But in cases where the variable has `allowGetters = true` property set, shouldn't the variable be displayed in response example values ? 
NOTE: @JsonIgnoreProperties was added not for swagger purposes in my code , but for functional use (to avoid deserialization) , therefore I cant use @JsonView instead of @JsonIgnoreProperties. 

Can springdoc-openapi support this feature ?

**Comment by bnasslahsen** [comment]
Hi @Andrew3431, 

 We rely on official swagger-api. 
 If you need to change this behaviour, you can ask it on the swagger-api github issue tracker.
 For the behaviour you are describing, the following annotation can maybe help you:
`@JsonProperty(access = JsonProperty.Access.READ_ONLY)`
