### ISSUE TITLE
Provide the generated OpenApi as injectable Spring Bean

### ISSUE THREAD

**Issue by sdoeringNew** [springdoc/springdoc-openapi#343]
The generated and prepared ``OpenApi`` object in the ``OpenApiResource`` might be necessary for more than just delivering the interface in a ``@RestController``.
I'm thinking about validating requests against the schema with the ``swagger-request-validator``.

If the ``OpenApi`` would be a Bean, it could be injected into all components that need it.
  
I see a further advantage in case that the ``OpenApi`` can not be generated in the first place. Currently the interface definition is generated at runtime.
In my opinion the Spring application should not start, if the ``OpenApi`` can not be generated.

**Comment by bnasslahsen** [comment]
Hi, 

 You can have full control of the OpenAPI Bean,using OpenApiCustomiser:
- https://springdoc.github.io/springdoc-openapi-demos/faq.html#how-can-i-customise-the-openapi-object-

**Comment by sdoeringNew** [comment]
How does the OpenApiCustomiser help?

The issue is not about customization. It's about getting the generated OpenApi from the Api annotations.

The particular example of the FAQ link you send contains an example OpenApi bean. But how to get the OpenApi object from the OpenApiResource? It's a private field in there.

**Comment by bnasslahsen** [comment]
You have full control of the OpenAPI Bean. 
It contains the generated OpenAPI Bean before that you can customise.

Note that the OpenAPI Bean is also available as a spring Bean, even its not clear what you need to achieve with it.
From the OpenApiRessource, you call getOpenApi() to get the generaated OpenAPI.

**Comment by ayofash1** [comment]
The getOpenApi() is private
