### ISSUE TITLE
Server list computed depending on first client domains and then cached

### ISSUE THREAD

**Issue by Kruschenstein** [springdoc/springdoc-openapi#348]
Hello, and first thanks for your work. I closely follow the development of this library, and new features are added quickly!

I have a problem with the way the server list is generated for the `api-docs.json`. Currently the default behaviour is to generate the server list depending on the first client request domain. Then the domain is cached and if the client domain change, the server last server list remains. We have multiple domains, some are company private domains, and the default behaviour is a real limit if we open the API outside the company, because the given server would not be reached.

Actually, we use a workaround which consist on disabling the cache. But the server list is computed each time, and because the long synchronized method (`AbstractOpenApiResource#getOpenApi) computes all the `api-docs.json` again and again, the user experience is not the best one.

I suggest to provide an option that allows library user to provide server list depending on client user request. If client requests swagger from `http://test.fr/...` and then from `https://another-test.fr/...` we respectively have `"servers": [ { "url": "http://test.fr", "description" ... } ],` and then `"servers": [ { "url": "http://another-test.fr", "description" ... } ],`.

Thanks you by advance

**Comment by bnasslahsen** [comment]
Hi @Kruschenstein, 

 In order to have the correct url on the servers list, you will have to set the following property:

```property
springdoc.cache.disabled= true
```

Its only available since : v1.2.26.

**Comment by Kruschenstein** [comment]
I know, that's the workaround I described when I said:

> Actually, we use a workaround which consist on disabling the cache

This issue was about implementing a solution that keep a kind of cache (a Map) for each end-user server. This feature may be enabled by library user configuration.

Is this possible?

**Comment by bnasslahsen** [comment]
You are serving the same swagger-ui from different serverBaseUrl. Consequently, the serverBaseUrl should be calculated dynamically. 

You can create your own OpenApiResource which can implement the kind of map you are describing.
Also, please feel free to propose a PR to share it with the community, if you identify additionnal optimizations.

**Comment by Kruschenstein** [comment]
Thanks for your answer :)

I don't have a lot of time to contribute for now, but I may. Is there a kind of code of conduct, style guide or anything?

**Comment by bnasslahsen** [comment]
Hi @Kruschenstein, 

 Please feel free to contribute. 
 The main rule is to make sure to respect standards and provide tests of the proposed code.
