### ISSUE TITLE
Spring data rest repositories not documented

### ISSUE THREAD

**Issue by paolodedo** [springdoc/springdoc-openapi#350]
Hello,

I have a spring boot data rest set of repositories that would like to auto-document: I have tried to add this dependency but with no luck, as the documentation is not generated on the `/swagger-ui.html` endpoint.

What I can see is only a custom ReST service that I exposed explicitly.

Can you help me? 

What I am using:

```
<dependency>
            <groupId>org.springdoc</groupId>
            <artifactId>springdoc-openapi-ui</artifactId>
            <version>1.2.26</version>
        </dependency>
        <dependency>
            <groupId>org.springdoc</groupId>
            <artifactId>springdoc-openapi-data-rest</artifactId>
            <version>1.2.26</version>
        </dependency>
```

**Comment by bnasslahsen** [comment]
Please have a look at the documentation: https://springdoc.github.io/springdoc-openapi-demos/

There no automatic generation planned to spring-data-rest annotations. You need to use OAS3 annotations on your spring-data-rest parameters. 
You can also contribute to add the support for the different annotations (@RepositoryRestResource, @QueryDSL, …)

**Comment by paolodedo** [comment]
[Swagger 3.0](https://springfox.github.io/springfox/docs/3.0.0/) is out now and it automatically generate Spring Data Rest repositories' documentation at the endpoint _/swagger-ui/index.html_ .

It's sufficient to add the following dependency:
```
<dependency>
	<groupId>io.springfox</groupId>
	<artifactId>springfox-boot-starter</artifactId>
	<version>3.0.0</version>
</dependency>
```

If you have Spring Security, you'll have to be able to access all these endpoints:
"/v3/api-docs", "/swagger-resources/**", "/swagger-ui/**", "/webjars/**", "favicon.ico"

Here is the SpringFoxConfig Java class that enables the possibility of adding an access token to the requests made by Swagger.
```
import com.google.common.collect.Lists;
import io.swagger.models.auth.In;
import org.apache.http.HttpHeaders;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import springfox.documentation.builders.PathSelectors;
import springfox.documentation.builders.RequestHandlerSelectors;
import springfox.documentation.service.ApiKey;
import springfox.documentation.service.AuthorizationScope;
import springfox.documentation.service.SecurityReference;
import springfox.documentation.spi.DocumentationType;
import springfox.documentation.spi.service.contexts.SecurityContext;
import springfox.documentation.spring.web.plugins.Docket;

import java.util.Collections;
import java.util.List;

@Configuration
public class SpringFoxConfig {

    @Bean
    public Docket api() {
        return new Docket(DocumentationType.OAS_30)
            .select()
            .apis(RequestHandlerSelectors.any())
            .paths(PathSelectors.any())
            .build()
            .pathMapping("/")
            .securitySchemes(Collections.singletonList(new ApiKey("Authorization", HttpHeaders.AUTHORIZATION, In.HEADER.name())))
            .securityContexts(Lists.newArrayList(securityContext()));
    }

    @Bean
    SecurityContext securityContext() {
        return SecurityContext.builder()
            .securityReferences(defaultAuth())
            .operationSelector(operationContext -> true)
            .build();
    }

    List<SecurityReference> defaultAuth() {
        AuthorizationScope authorizationScope
            = new AuthorizationScope("global", "accessEverything");
        AuthorizationScope[] authorizationScopes = new AuthorizationScope[1];
        authorizationScopes[0] = authorizationScope;
        return Lists.newArrayList(
            new SecurityReference("Authorization", authorizationScopes));
    }

}
```

So it is SOLVED!

Paolo

**Comment by Meumo** [comment]
> https://springdoc.github.io/springdoc-openapi-demos/

the lien does not fonctionne.

**Comment by bnasslahsen** [comment]
> > https://springdoc.github.io/springdoc-openapi-demos/
> 
> the lien does not fonctionne.

The link is updated!
