### ISSUE TITLE
WebFlux handlers using kotlin coroutines do not produce response documentation

### ISSUE THREAD

**Issue by jnfeinstein** [springdoc/springdoc-openapi#351]
I've created a demo application [here](https://github.com/jnfeinstein/springdoc-demo).

I believe the issue is related to [this line](https://github.com/springdoc/springdoc-openapi/blob/master/springdoc-openapi-common/src/main/java/org/springdoc/core/AbstractResponseBuilder.java#L206).  The return type for the `mono` implementation is `reactor.core.publisher.Mono<com.example.demo.SystemStatusResponse>` whereas the return type for the coroutine implementation is `class java.lang.Object`.  It appears that the correct response type is locked away somewhere in the parameters: `kotlin.coroutines.Continuation<? super com.example.demo.SystemStatusResponse> continuation`.

**Comment by jnfeinstein** [comment]
@joaodias14 JFYI...

**Comment by joaodias14** [comment]
Hi @jnfeinstein, honestly we never noticed that until now :D. 
It seems there is an issue out there.

**Comment by joaodias14** [comment]
Hi @jnfeinstein, I opened a PR to fix the issue. If you will, take a look and suggest any change you find relevant. Thanks!

**Comment by bnasslahsen** [comment]
Thank you @joaodias14 for your help.
The fix will be available in the next release v1.2.27.

**Comment by jnfeinstein** [comment]
We're loading this up now!  Thank you @joaodias14 and @bnasslahsen.

**Comment by neonomaly** [comment]
Guys, hi!

I'am using  springdoc-openapi-webflux-ui:1.2.30 lib and still have an issue:

```
@RestController
@RequestMapping("/v1")
class V1Controller {
  
  @GetMapping("/smth", produces = [MediaType.APPLICATION_JSON_VALUE])
  suspend fun getSmth(): List<Some> {
     return listOf(Some(), Some())
  }
}
```

and still has a required parameter $completion of request and ContinuationObject and CoroutineContext in schema section.

P.S. I'am using GroupedOpenAPI

**Comment by jnfeinstein** [comment]
@neonomaly do you have the kotlin extension installed?

**Comment by neonomaly** [comment]
> @neonomaly do you have the kotlin extension installed?

With springdoc-openapi-kotlin everything ok. Thank you!
