### ISSUE TITLE
The schema defined in the content of RequestBody ignores the setting of discriminator

### ISSUE THREAD

**Issue by lawli** [springdoc/springdoc-openapi#356]
It seems in the method of getSchemaFromAnnotation in AnnotationsUtils, it does not consider copying discriminatorProperty and discriminatorMapping.

**Comment by bnasslahsen** [comment]
Can you please add more details about your request :

- What is the description of the actual behaviour ?
- What are the actual and the expected result using OpenAPI Description (yml or json)?
- Provide with a sample code code to reproduce it?

Thank you in advance.

**Comment by lawli** [comment]
I am using the following annotation in the code

@Operation(
            description = "Sample",
            requestBody = @io.swagger.v3.oas.annotations.parameters.RequestBody(
                    content = @Content(schema = @Schema(
                            oneOf = {Debit.class, Credit.class},
                            discriminatorProperty = "transactionType",
                            discriminatorMapping = {
                                    @DiscriminatorMapping(value = "DEBIT", schema = Debit.class),
                                    @DiscriminatorMapping(value = "CREDIT", schema = Credit.class)                                    
                            }
                    ))
            )            
    )

The expect result is 

"requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "discriminator": {
                                    "propertyName": "transactionType",
                                    "mapping": {
                                        "DEBIT": "#/components/schemas/Debit",
                                        "CREDIT": "#/components/schemas/Credit"
                                    }
                                },
                                "oneOf": [
                                    {
                                        "$ref": "#/components/schemas/Debit"
                                    },
                                    {
                                        "$ref": "#/components/schemas/Credit"
                                    }
                                ]
                            }
                        }
                    }
                }	

But the actual result is 

"requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {                                
                                "oneOf": [
                                    {
                                        "$ref": "#/components/schemas/Debit"
                                    },
                                    {
                                        "$ref": "#/components/schemas/Credit"
                                    }
                                ]
                            }
                        }
                    }
                }

While I debug into the code, the requestbody is constructed in org.springdoc.core.RequestBodyBuilder and the Schema of the Content is extracted from method getSchemaFromAnnotation in class io.swagger.v3.core.util.AnnotationsUtils

**Comment by bnasslahsen** [comment]
Hi @lawli, 

 As you have described, this behaviour is mainly related to swagger-api.
 The main root cause issue, is the following:
 - https://github.com/swagger-api/swagger-core/issues/3421

 You can look at the sample how to generate the discriminator in the documentation.
 Your @Schema annotation, just needs to be added on the superclass.

 The following issue, contains an example of how to get the discriminator in the documentation:
 - https://github.com/swagger-api/swagger-core/issues/3046

**Comment by lawli** [comment]
I don't think it is the problem of swagger-api. If I populate the ComposedSchema manually, it shows the expected result.
<pre>
public OpenApiCustomiser apiCustomerser() {
    return openApi -> {
        MediaType md = new MediaType();
        Discriminator ds = new Discriminator();
        ds.setPropertyName("transactionType");
        ds.mapping("DEBIT", "#/components/schemas/Debit");
        ds.mapping("CREDIT", "#/components/schemas/Credit");
        ComposedSchema sc = new ComposedSchema();
        List<Schema> oneOf = Arrays.asList(
                new Schema().$ref("#/components/schemas/Debit"),
                new Schema().$ref("#/components/schemas/Credit")
        );
        sc.setOneOf(oneOf);
        sc.setDiscriminator(ds);
        md.schema(sc);

        openApi.getPaths().entrySet().stream()
                .flatMap(entry -> entry.getValue().readOperations().stream())
                .forEach(op -> op.getRequestBody().getContent().addMediaType("application/json", md));
    };
}
<pre>

**Comment by bnasslahsen** [comment]
Using the OpenApiCustomiser shoud be the silver bullet and the last solution to choose:

Your requirement looks quite standard and doesn't require any customisations.
When you use OpenApiCustomiser, then you are not using the native swagger-api annotations.

As mentioned, you can simply add the `@Schema` declaration on your class (and not on the `@RequestBody`) as proposed on swagger-api/swagger-core#3046. This is a safe workaround, until 
swagger-api/swagger-core#3421 is resolved.
