### ISSUE TITLE
Is there a way to pass the user provided custom Pagination details ?

### ISSUE THREAD

**Issue by javaHelper** [springdoc/springdoc-openapi#357]

**Comment by bnasslahsen** [comment]
Maybe you can provide more details about your request which is not clear.

**Comment by javaHelper** [comment]
I have below code which doesn't gives me correct options to set pagination details (like Page and Size). I want the correct way to pass the pagination details. Proper field like Path Variable field. 

With the below code its giving me whole object.
```
{
  "page": 0,
  "size": 0,
  "sort": [
    "string"
  ]
}
```

Like

```
@Operation(summary = "Find employees !!")
@ApiOperation(value = "Find Countries", nickname = "Find employees")
	@ApiResponses(value = { @ApiResponse(code = 200, message = "For Success as well as No Data found scenerio."),
			@ApiResponse(code = 500, message = "Internal Server Error") })
	@ApiImplicitParams({
			@ApiImplicitParam(name = "page", dataType = "int", paramType = "query", value = "Results page you want to retrieve (0..N)", defaultValue = 0),
			@ApiImplicitParam(name = "size", dataType = "int", paramType = "query", value = "Number of records per page.", defaultValue = 20) })
@GetMapping(value = "/employees")
public ResponseEntity<Page<EmployeeDto>> findEmployees(PageSetupParams pageParams, @Parameter(hidden=true) Pageable pageable) {
	Page<EmployeeDto> page = countryService.findAllemployees(pageParams, pageable);
	return new ResponseEntity<>(page, HttpStatus.OK);
}
```

**Comment by bnasslahsen** [comment]
Hi, 

 You are not using OpenAPI 3, annoations: 
 - https://github.com/swagger-api/swagger-core/wiki/Swagger-2.X---Annotations
 Please review the OpenAPI specification:
  - https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.2.md

 You need to remove `@ApiOperation` and `@ApiImplicitParams`
 If you need custom pageable description, a sample is available here:
 - https://github.com/springdoc/springdoc-openapi/issues/251

**Comment by Majlanky** [comment]
I was not able to find the solution anywhere in the documentation. If you want to pageable behave as a set of standard parameters you **have to  add dependency** of `springdoc-openapi-data-rest` to your classpath and annotate your Pageable with @ParameterObject like:
```java
@Operation(description = "blahblah")
@GetMapping(value = ALL_URI, produces = MediaType.APPLICATION_JSON_VALUE)
public Whatever getAll(@ParameterObject @PageableDefault(size = 20, sort = "name") Pageable pageable) {
        ...
    }
```
The annotation of @ParameterObject causes additional customizing of Pageable. It even transfer setting of PageableDefault to the final documentation! 👍
