### ISSUE TITLE
Kotlin @ResponseStatus ignored if function returns Unit

### ISSUE THREAD

**Issue by glockbender** [springdoc/springdoc-openapi#362]
When i using Unit(void) as return value in any `@RestController` method, there is no information about response status, despite i'm declaring it explicitly at `@ResponseStatus(HttpStatus.ACCEPTED)`

```kotlin
@PostMapping("/{id}/ready")
    @ApiResponses(
        ApiResponse(
            description = "Missing or illegal headers/query parameters",
            responseCode = "400",
            content = [Content(
                mediaType = "application/json",
                schema = Schema(implementation = ServerErrorsList::class))]),
        ApiResponse(
            description = "Unexpected order status change",
            responseCode = "409",
            content = [Content(
                mediaType = "application/json",
                schema = Schema(implementation = ServerErrorsList::class))])
    )
    @ResponseStatus(HttpStatus.ACCEPTED)
    fun ready(
        @PathVariable("id") id: UUID
    ): Unit =
        lifecycle.ready(id)
```

<img width="1423" alt="Снимок экрана 2020-01-21 в 19 46 05" src="https://user-images.githubusercontent.com/16047417/72824662-b3ea9180-3c86-11ea-9221-30bcbbc76a87.png">

using: springdoc-openapi-ui, version: 1.2.27

**Comment by joaodias14** [comment]
Hi @glockbender, that is happening because you are defining `@ApiResponses`. By doing so, the default response documentation is not added. This means that if you want to use `@ApiResponses`, then you need to document also `HttpStatus.ACCEPTED`.

**Comment by bnasslahsen** [comment]
Thank you @joaodias14 for your answer, i totally agree.
Because @glockbender, you have provided the @ApiResponses documentation of your response, it's used as the reference.
