### ISSUE TITLE
How to pass custom header in the request for each request ? I need to make sure its displays on Open API 3 UI 

### ISSUE THREAD

**Issue by javaHelper** [springdoc/springdoc-openapi#363]
I'm looking to perform API versioning using Custom Header and learning from the site: https://www.dariawan.com/tutorials/spring/documenting-spring-boot-rest-api-springdoc-openapi-3/.

I also look at : https://springdoc.github.io/springdoc-openapi-demos/faq.html#how-do-i-add-authorization-header-in-requests and https://springdoc.github.io/springdoc-openapi-demos/faq.html#how-can-i-set-a-global-header, but I don't see a way to pass/show the Custom Header information in the request.

Could you please guide me ?

I've below required  - 
1) Wanted to show Custom Header field on UI - Springdoc UI.
2) Will have option to pass header "Accept-version=v1" or "Accept-version=v2" in each request.
3) If user dont pass any header in the request then it will be defaulted to "Accept-version=v1".

Kindly suggest the solution for below sample endpoints.

```
@Operation(summary = "Find employees !!")
@ApiOperation(value = "Find Countries", nickname = "Find employees")
	@ApiResponses(value = { @ApiResponse(code = 200, message = "For Success as well as No Data found scenerio."),
			@ApiResponse(code = 500, message = "Internal Server Error") })
	@ApiImplicitParams({
			@ApiImplicitParam(name = "page", dataType = "int", paramType = "query", value = "Results page you want to retrieve (0..N)", defaultValue = 0),
			@ApiImplicitParam(name = "size", dataType = "int", paramType = "query", value = "Number of records per page.", defaultValue = 20) })
@GetMapping(value = "/employees")
public ResponseEntity<Page<EmployeeDto>> findEmployees(PageSetupParams pageParams, @Parameter(hidden=true) Pageable pageable) {
	Page<EmployeeDto> page = employeeService.findAllemployees(pageParams, pageable);
	return new ResponseEntity<>(page, HttpStatus.OK);
}
```

**Comment by bnasslahsen** [comment]
Here a sample code, how to pass custom Header to each request:

```java
@GetMapping("/items/search")
@Parameters({
		@Parameter(name = "pageNumber", description = "page number",
				in = ParameterIn.QUERY, schema = @Schema(type = "integer")),
		@Parameter(name = "pageSize", description = "page size",
				in = ParameterIn.QUERY, schema = @Schema(type = "integer")),
		@Parameter(name = "sort", description = "sort specification",
				in = ParameterIn.QUERY, schema = @Schema(type = "string")),
		@Parameter(in = ParameterIn.HEADER, name = "Accept-version", schema = @Schema(type = "string", allowableValues = {"v1", "v2"}, defaultValue = "v1"))
})
public List<ItemDTO> showItems(@Parameter(hidden = true) Pageable pageable) {
	return new ArrayList<ItemDTO>();
}
```

**Comment by javaHelper** [comment]
@bnasslahsen - Thanks for nice suggestion. However is there any ways if we can give ENUM for the Sorting Parameters?

**Comment by bnasslahsen** [comment]
@javaHelper, please have a look at the documentation of swagger-annotations (`allowableValues`): 
- https://github.com/swagger-api/swagger-core/wiki/Swagger-2.X---Annotations 

For example:
`@Schema(type = "string",allowableValues = {"asc","desc"})`

**Comment by javaHelper** [comment]
@bnasslahsen - Yes, Thanks  for the same. I went through this docs many times and I'm clear on it only support String[], is there any way if we can give the Java Enum class as it works with Swagger ? Thanks!

**Comment by javaHelper** [comment]
How can we pass the Custom Object or class through 

`@Parameter(name = "pageNumber", description = "page number",
				in = ParameterIn.QUERY, schema = @Schema(type = "integer")`
