### ISSUE TITLE
Add support for gradle.

### ISSUE THREAD

**Issue by TLiese** [springdoc/springdoc-openapi#365]
Right now only support for maven is documented in the wiki. To create the .json/yml at build time.
`springdoc-openapi-maven-plugin`.
As we use gradle official support for it would be highly appreciated.

**Comment by bnasslahsen** [comment]
Please have a look at our FAQ. This point is  already mentionned. 
 - https://springdoc.github.io/springdoc-openapi-demos/faq.html#is-there-a-gradle-plugin-available

 There no short term plan for adding gradle support. We are still focusing on covering the support of OpenAPI 3, core fonctionnalities.

 But you can contribute and propose the support.
