### ISSUE TITLE
Programmatic customization of the OpenAPI, problem with GroupedOpenApi?!

### ISSUE THREAD

**Issue by kaibra** [springdoc/springdoc-openapi#366]
The docs state that programmatic customization of the OpenAPI object is supported:
```Java
@Bean
public OpenAPI customOpenAPI(@Value("${springdoc.version}") String appVersion) {
  return new OpenAPI()
  .components(new Components().addSecuritySchemes("basicScheme",
          new SecurityScheme().type(SecurityScheme.Type.HTTP).scheme("basic")))
  .info(new Info().title("SpringShop API").version(appVersion)
          .license(new License().name("Apache 2.0").url("http://springdoc.org")));
}
```

Is it supported / allowed to add parts of the API spec here programmatically (paths)?
Something like this:
```Java
    @Bean
    public OpenAPI customOpenAPI() {
        return new OpenAPI()
                .path("/foo",
                        new PathItem().get(new Operation().operationId("foo").responses(new ApiResponses()
                                .addApiResponse("default",
                                        new ApiResponse()
                                                .description("")
                                                .content(new Content().addMediaType("fatz", new MediaType()))))));
    }
```

Use case might be if some generic endpoints exists and someone prefers to add the spec programmatically instead of adding hunderts of swagger annotations to the controller.
Or also someone has written the Open API spec by hand and wants to include it even before he actually implemented it (load from file, parse, add to object).

If it is supported / allowed, it currently causes a bug when using it at the same time with the GroupedOpenApi feature.
The definitions added to the OpenAPI object appear within every group-endpoint-response, no matter if they fullfill the conditions specified on the GroupedOpenApi or not.

If it is NOT supported / allowed, maybe there should be a comment in the docs about it?!

**Comment by bnasslahsen** [comment]
Hi @kaibra, 

 Maybe we need to add more explanation on the documentation about this behaviour your are describing.

 If you need the defintions to appear globally (withing every group), no matter if the group fulfills the conditions specified on the GroupedOpenApi , you can use OpenAPI Bean.

```java
@Bean
public OpenAPI customOpenAPI() {
	return new OpenAPI().path("/foo",
	new PathItem().get(new Operation().operationId("foo").responses(new ApiResponses()
	.addApiResponse("default",new ApiResponse()description("")
	content(new Content().addMediaType("fatz", new MediaType()))))));
}
```

 If you need the defintions to appear withing a specific group, and respect the conditions specified on the GroupedOpenApi, you can add OpenApiCustomiser to your GroupedOpenApi definition.

```java

GroupedOpenApi.builder().setGroup("users").pathsToMatch(paths).packagesToScan(packagedToMatch).addOpenApiCustomiser(customerGlobalHeaderOpenApiCustomiser())
                .build()

@Bean
public OpenApiCustomiser customerGlobalHeaderOpenApiCustomiser() {
	return openApi -> openApi.path("/foo",
	new PathItem().get(new Operation().operationId("foo").responses(new ApiResponses()
	.addApiResponse("default",new ApiResponse().description("")
	.content(new Content().addMediaType("fatz", new MediaType()))))));
}

```


 This should answer to boths usages. Please let me know if its ok for you.

**Comment by kaibra** [comment]
Ok! Thanks for your answer @bnasslahsen

**Comment by kaibra** [comment]
@bnasslahsen one more question regarding one of the mentioned cases.

I thought about doing this to add additional specs from resources in a first approach:
```Java
    @Bean
    public OpenApiCustomiser apiFromResourceCustomizer() {
        OpenAPI api = new OpenAPIV3Parser().read("spec/custom-spec.yml");
        return openapi -> {
            openapi.setComponents(api.getComponents());
            openapi.setPaths(api.getPaths());
            openapi.setExtensions(api.getExtensions());
            openapi.setInfo(api.getInfo());
            openapi.setExternalDocs(api.getExternalDocs());
            openapi.setOpenapi(api.getOpenapi());
            openapi.setSecurity(api.getSecurity());
            openapi.setServers(api.getServers());
            openapi.setTags(api.getTags());
        };
    }

    @Bean
    public GroupedOpenApi internalGroupedOpenApi(OpenApiCustomiser apiFromResourceCustomizer) {
        return GroupedOpenApi.builder()
                .setGroup("testGroup")
                .pathsToMatch("/nothingreally")
                .addOpenApiCustomiser(apiFromResourceCustomizer)
                .build();
    }
```
then I realized that I would overwrite the complete API-Definition gathered before by calling the setters.
Do you know if there are solutions out there already for that case?
Something like
```Java
   @Bean
    public OpenApiCustomiser apiFromResourceCustomizer() {
        OpenAPI api = new OpenAPIV3Parser().read("spec/custom-spec.yml");
        return openapi -> new ExtendibleOpenApi(openapi).addAllSpecsFrom(api);
    }
```

**Comment by bnasslahsen** [comment]
Hi @kaibra, 

 What are you trying to achieve seems more to be a new functionnality loading static spec definitions. 
 I am not sure, you can achieve the filtering based on the GroupedOpenApi Bean, as it filters only the application code (not the external definitions).
 With you use case, it makes sense not allow (pathsToMatch and packagesToScan) to be absent, if openApiCustomisers is present. 
 
 If you have many specs and you need to use groups, here a sample way to achieve it:



```java
@Bean
public GroupedOpenApi internalGroupedOpenApi() {
	String staticSpecLocation="static/api-docs.yaml";
	String[] pathsToMatch={"/user/**", "/pet/**"};
	return GroupedOpenApi.builder()
			.setGroup("testGroup").pathsToMatch(pathsToMatch)
			.addOpenApiCustomiser(new GroupCustomiser(staticSpecLocation, pathsToMatch))
			.build();
}

public class GroupCustomiser extends SpecFilter implements OpenApiCustomiser {

	private List<String> pathsToMatch;

	private final String specLocation;

	private final AntPathMatcher antPathMatcher = new AntPathMatcher();

	public GroupCustomiser(String specLocation, String... pathsToMatch) {
		this.specLocation = specLocation;
		this.pathsToMatch = Arrays.asList(pathsToMatch);
	}

	@Override
	public void customise(OpenAPI openApi) {
		OpenAPI api = new OpenAPIV3Parser().read(this.specLocation);
		//Apply necessary filterings ...
		api.getPaths().entrySet().removeIf(path -> !isPathToMatch(path.getKey()));
		api.getTags().removeIf(tag -> api.getPaths().entrySet().stream().anyMatch(pathItemEntry -> pathItemEntry.getValue().
				readOperations().stream().noneMatch(operation -> operation.getTags().contains(tag.getName()))));
		//Assign new values to the OpenAPI Bean
		openApi.setComponents(api.getComponents());
		openApi.setPaths(api.getPaths());
		openApi.setExtensions(api.getExtensions());
		openApi.setInfo(api.getInfo());
		openApi.setExternalDocs(api.getExternalDocs());
		openApi.setOpenapi(api.getOpenapi());
		openApi.setSecurity(api.getSecurity());
		openApi.setServers(api.getServers());
		openApi.setTags(api.getTags());
		super.removeBrokenReferenceDefinitions(openApi);
	}

	private boolean isPathToMatch(String operationPath) {
		return pathsToMatch.stream().anyMatch(pattern -> antPathMatcher.match(pattern, operationPath));
	}
}
```

**Comment by kaibra** [comment]
64ac49eff31ceafe8bce12fecbf9122927d9fdd4

Thanks!

**Comment by kaibra** [comment]
> @bnasslahsen What are you trying to achieve seems more to be a new functionnality loading static spec definitions.
Is this something you would include in the project (loading static spec definitions)?
If yes, I could contribute a PR if you would share some thoughts about how you would like it to be implemented.

**Comment by bnasslahsen** [comment]
Hi @kaibra, 

Sorry I haven't seen your message.
You can of course propose a PR, which integrates this functionality, so we can enhance the library.
It would have more sense in separate maven module: springdoc-openapi-swagger-parser.
We can add on the class GroupConfig, the property staticSpecLocation.

**Comment by mat373** [comment]
@bnasslahsen 
Can you take a look ? 
https://stackoverflow.com/questions/68622388/openapi-authorize-all-services?noredirect=1#comment121274993_68622388
