### ISSUE TITLE
1.2.27 Spring Security Class Not found issue

### ISSUE THREAD

**Issue by bfs-natewallman** [springdoc/springdoc-openapi#367]
After upgrading to 1.2.27 I started getting class not found exceptions and it appears to be related to the commit here: https://github.com/springdoc/springdoc-openapi/commit/8b5f3d7fc80f0bd9d0dc07dc1e10f21ce680106d#diff-7ad38bbb6293f3c7d51d01c996981ffa

It is referencing FrameworkEndpointHandlerMapping which doesn't exist on my classpath and I don't think is required to get Spring Security w/ Oauth working.  My current working theory is this has something to do with the changes Spring has made with Ouath(https://github.com/spring-projects/spring-security/wiki/OAuth-2.0-Migration-Guide).  I say that because my Oauth configuration is working fine without it.  

I'm not sure exactly what this commit is trying to solve but I wonder if there is a different way to solve it without tightly coupling to Spring specific files?

**Comment by joaodias14** [comment]
Hi @bfs-natewallman, if I am not mistaken, this was reported in #359 and fixed on v1.2.28. Could you please try with that version?

**Comment by bfs-natewallman** [comment]
Thanks @joaodias14, that works.  I didn't see that 1.2.28 listed on the maven repo so I didn't try it.
