### ISSUE TITLE
@ExtensionProperty is not generated without @Operation

### ISSUE THREAD

**Issue by wutzebaer** [springdoc/springdoc-openapi#368]
When i define
`@ApiResponse(content = @Content(schema = @Schema(type = "file")), extensions = @Extension(properties = @ExtensionProperty(name = "x-is-file", value = "true")))`

![grafik](https://user-images.githubusercontent.com/10062396/72910461-db019b80-3d38-11ea-85f2-9a4449cc3052.png)

the x-is-file is missing, but when i wrap it in an operation, it gets rendered:

`@Operation(responses = @ApiResponse(content = @Content(schema = @Schema(type = "file")), extensions = @Extension(properties = @ExtensionProperty(name = "x-is-file", value = "true"))))`

![grafik](https://user-images.githubusercontent.com/10062396/72910404-c8876200-3d38-11ea-9fbb-0ddafb87dc52.png)

which is annoying because i have an custom annotation which includes an @Operation definition

**Comment by bnasslahsen** [comment]
Yes @wutzebaer.  Extensions were only supported using `@Operation`.
The support for extensions on `@ApiResponse`, will be available on the next release.
