### ISSUE TITLE
Does springdoc-openapi gives information on time required to execute the endpoint ?

### ISSUE THREAD

**Issue by javaHelper** [springdoc/springdoc-openapi#369]

**Comment by bnasslahsen** [comment]
You can only display the request duration: using swagger-ui propperty: displayRequestDuration
You can have a look at the documentation for swagger-ui, is available:
- https://springdoc.github.io/springdoc-openapi-demos/faq.html#how-can-i-configure-swagger-ui

In general, for your requests, please refer to standard OpenAPI description:
 - https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.2.md
