### ISSUE TITLE
After configuring springdoc.swagger-ui.path the initial html page is served from the configured path but other requests are served without the path

### ISSUE THREAD

**Issue by leoherbie** [springdoc/springdoc-openapi#37]
If you configure: `springdoc.swagger-ui.path=foo` then ```http://localhost:3006/foo/swagger-ui.html``` works great.  The problem is it immediately redirects to ```http://localhost:3006/webjars/swagger-ui/index.html?url=/foo&validatorUrl=```

This greatly complicates things like configuring servlet filters based on path.

Ideally, you can configure a path to serve swagger docs from and every resource is served from that path.

**Comment by leoherbie** [comment]
Note: springfox has a similar problem but worse.  This issue is one reason we went looking for an alternative to springfox

**Comment by springdoc** [comment]
Depending on your spring version, you can override the base path of webjars.
You can extend WebMvcConfigurerAdapter (spring 4) or implement WebMvcConfigurer(spring 5) depending on your spring version.

We will add the support for serving all the swagger static resources, from the same base path on v1.1.22 of springdoc-openapi. 
This will be in experimental mode and we will be expecting your feedback.

**Comment by leoherbie** [comment]
Based on your latest build v1.1.24, everything seems to be serving exactly how we had hoped.  Thanks so much for the quick turnaround on all the issues we have filed.
