### ISSUE TITLE
Add support for async mappings returning CompletableFuture.

### ISSUE THREAD

**Issue by mvh77** [springdoc/springdoc-openapi#370]
Spring supports returning CompletableFutures for mappings marked with @Async. Should be pretty similar to https://github.com/springdoc/springdoc-openapi/issues/297.

**Comment by mvh77** [comment]
It's actually better if the inspected type is the more generic CompletionStage. I'll take a look at this later today.

**Comment by bnasslahsen** [comment]
@mvh77, can you please provide more informations about your request according to the contribution guide when Using GitHub Issues:

- https://github.com/springdoc/springdoc-openapi/blob/master/CONTRIBUTING.adoc

**Comment by mvh77** [comment]
Hi! I created a PR here https://github.com/springdoc/springdoc-openapi/pull/372
