### ISSUE TITLE
Why predicate field in RouterFunctions.DefaultRouterFunction<T extends ServerResponse> gets DefaultErrorWebExceptionHandler?

### ISSUE THREAD

**Issue by trip2gafa** [springdoc/springdoc-openapi#373]
![Screenshot from 2020-01-24 17-26-02](https://user-images.githubusercontent.com/53337963/73065814-ade6f180-3ece-11ea-9e09-5b4b1a3a09b4.png)

**Comment by bnasslahsen** [comment]
@trip2gafa , can you please respect the  contribution guide when Using GitHub Issues. 

- https://github.com/springdoc/springdoc-openapi/blob/master/CONTRIBUTING.adoc

There no known issue, about your description, and we encourage you to review your project configuration.

We have provided you all the elements on #361 .
If you have questions and you have followed the described steps, you should submit them on stackoverflow under the springdoc tag.
