### ISSUE TITLE
Hide ControllerAdvice from library from swagger documentation

### ISSUE THREAD

**Issue by jpmaas** [springdoc/springdoc-openapi#374]
As I know after reading a lot of issues and documentation, also @ControllerAdvice annotated classes are supposed to document their response based on OAS 3.0.

We are currently using some shared library code (e.g. for unified error handling) which also adds a @ControllerAdvice. This does not (yet) have a swagger documentation and since it is shared code used with old versions of swagger, it can not be added (yet). Is there any option to hide this @ControllerAdvice located in the library from the swagger generation without changing it?

**Comment by bnasslahsen** [comment]
@jpmaas, if you have questions, please make sure you have read the section of "Using GitHub Issues":
- https://github.com/springdoc/springdoc-openapi/blob/master/CONTRIBUTING.adoc

This kind of questions should go to stackoverflow.

You are referring to current issues on @ControllerAdvice, please be more precise and provide details as there has not known issues related to your description.

Even your @ControllerAdvice classes don't have the OAS 3 annotation, there is a basic generation of the OAS 3 documentation. 

 You can have a look at the source of demo1 or demo2, for samples:
- https://github.com/springdoc/springdoc-openapi-demos

 You can ignore classes or methods by adding swagger-annotation `@Hidden` on @ControllerAdvice or @ExceptionHandler.

If you are not happy with the generated documentation, you have access to the OpenAPI Bean using 
OpenApiCustomiser and you can make whatever changes you want:
- https://springdoc.github.io/springdoc-openapi-demos/faq.html#how-can-i-customise-the-openapi-object-
