### ISSUE TITLE
Add support to configure packages-to-scan as list using YAML Syntax

### ISSUE THREAD

**Issue by pieterdegraeuwe** [springdoc/springdoc-openapi#376]
I am not able to use packages-to-scan nor paths-to-match. using one package or one path does work.
However, from the moment I want a list of more than one element it resolves in just one list with one element, of null:

`springdoc :
  packages-to-scan :
  - val1
  - val2
(the dots are dashes, escaping them in markdown does not seem to work)
`

`springdoc :
  packages-to-scan : some.package
`
Gives a list, with one element.  (so this seems to work als long as you need only one package/path)

`springdoc :
  packages-to-scan : some.package, some.secondpackage
`
does resolve in a list with one element ; "some.package, some.secondpackage', which is of course not the result we want.

Looking to the code, I think that it just cannot work. It is used as a simple @Value(SPRINGDOC_PACKAGES_TO_SCAN) inside the AbstractOpenApiResource, while (I think) those lists only work in ConfigurationProperties.

Easy to reproduce:  add 
`    @Value(SPRINGDOC_PACKAGES_TO_SCAN)
    private List<String> packagesToScan;
`
in the test AbstractSpringDocTest. and add some packages to the application-test.yml

Any hints how to get around this? (or am I missing something?)
Thanks

**Comment by bnasslahsen** [comment]
@pablomusumeci,

The property `SPRINGDOC_PACKAGES_TO_SCAN `is already defined in SpringDocConfigProperties.
You have already sample tests with list of values; 
- https://github.com/springdoc/springdoc-openapi/blob/master/springdoc-openapi-webmvc-core/src/test/java/test/org/springdoc/api/app63/SpringDocApp63Test.java

 Maybe you are not testing with the latest stable version. v1.2.28
If you are still facing this problems, please add the sample code or your git repository link to reproduce and this issue will be reopened.

**Comment by pieterdegraeuwe** [comment]
I've created a repo which reproduces the problem.
Agreed, using comma separated paths, It seems to work. However, using the standard yml list notation, the list becomes null;

https://github.com/pieterdegraeuwe/springdoc-bugtest/blob/master/src/main/resources/application.yml

**Comment by bnasslahsen** [comment]
I confirm the support to configure package-to-scan as list using YAML syntax will be added for the next release v1.2.29.

**Comment by pieterdegraeuwe** [comment]
looking forward tot test that version.
Note that the comma separated list did only seem to work on springboot2, not on springboot1.5

Thx.
