### ISSUE TITLE
Swagger Petstore demo is included in dependency

### ISSUE THREAD

**Issue by Surerus** [springdoc/springdoc-openapi#379]
Hi, I just came to something funny. Please forgive me If I missed some configuration.

I'm using `springdoc-openapi-ui version 1.2.28`.

When I use the url `http://localhost:8080/swagger-ui.html` I can see my swagger normally.

If I use `http://localhost:8080/swagger-ui/index.html` I am taken to Swagger Petstore (which I assume is a demo version)

Is there a way to exclude anything not related with my own swagger?

**Comment by bnasslahsen** [comment]
We rely on swagger-ui official webjars. We build our library on top of it.
The index.html is available inside the webjar.

Its already answered here: #43
