### ISSUE TITLE
Spring Boot Devtools & CGLIB causes issues with SwaggerWelcome

### ISSUE THREAD

**Issue by plnordquist** [springdoc/springdoc-openapi#386]
Environment:
Spring Boot 2.2.4
springdoc-openapi-ui 1.2.29

Issue:
While using springdoc with my project using spring webmvc, if I depend on the spring-boot-devtools I get the following error on the console which fails the application startup in Visual Studio Code:

```
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'swaggerWelcome' defined in class path resource [org/springdoc/ui/SwaggerConfig.class]: Initialization of bean failed; nested exception is org.springframework.aop.framework.AopConfigException: Could not generate CGLIB subclass of class org.springdoc.ui.SwaggerWelcome: Common causes of this problem include using a final class or a non-visible class; nested exception is org.springframework.cglib.core.CodeGenerationException: java.lang.IllegalAccessError-->class org.springdoc.ui.SwaggerWelcome$$EnhancerBySpringCGLIB$$fe15ec27 cannot access its superclass org.springdoc.ui.SwaggerWelcome (org.springdoc.ui.SwaggerWelcome$$EnhancerBySpringCGLIB$$fe15ec27 is in unnamed module of loader org.springframework.boot.devtools.restart.classloader.RestartClassLoader @6dbb198b; org.springdoc.ui.SwaggerWelcome is in unnamed module of loader 'app')
```

I believe this is due to the SwaggerWelcome class being package private and due to the fact that I'm using spring-boot-starter-aop and CGLIB proxies.  Is there a reason that class is package private or can this visibility be changed to work with CGLIB?

**Comment by bnasslahsen** [comment]
@plnordquist, the visibility of the class can be changed  to public if there is a valid reason.
I am not able to reproduce the issue you are describing.
Can you please attach or link to github repo reproduce the issue you are describing using a simple project with HelloController ?

**Comment by plnordquist** [comment]
Project is here https://github.com/plnordquist/springdoc-cglib-issue.  It ended up being that the JavaMelody monitoring tool is trying to proxy Controller annotated beans for monitoring purposes.  I don't know if there is a way to exclude this SwaggerWelcome class or if I need to create a different configuration for the JavaMelody tool.  The monitoring is setup in this autoconfig class https://github.com/javamelody/javamelody/blob/master/javamelody-spring-boot-starter/src/main/java/net/bull/javamelody/JavaMelodyAutoConfiguration.java#L240-L251.

**Comment by bnasslahsen** [comment]
Hi @plnordquist, 

 This documented on spring-boot-devtools, documentation:
 - https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#using-boot-devtools-customizing-classload

You can fix the problem by adding .springdoc-openapi-ui jar to the restart class loader using META-INF/spring-devtools.properties which contains:

```java
restart.include.springdoc-openapi-ui=/springdoc-openapi-ui-.+\.jar
```
