### ISSUE TITLE
https://stackoverflow.com/questions/59967447/how-to-globally-ignore-api-of-spring-boot-from-open-api-3-specification

### ISSUE THREAD

**Issue by javaHelper** [springdoc/springdoc-openapi#388]
Could you please guide us here: https://stackoverflow.com/questions/59967447/how-to-globally-ignore-api-of-spring-boot-from-open-api-3-specification?

**Comment by bnasslahsen** [comment]
Add the sample java code of springdoc (not springfox)  you are using on stackoverflow.
