### ISSUE TITLE
setting springdoc.api-docs.enabled to false also disables the swagger ui

### ISSUE THREAD

**Issue by darrellme** [springdoc/springdoc-openapi#389]
Hi

I'm using spring boot 2 (2.2.4-RELEASE) and version 1.2.28 of springdoc-openapi-ui. I want to disable the auto generation of the api-docs along with the OpenApiResource controller and create my own custom OpenAPI bean based on a YAML file. If I create my own OpenAPI bean, this appears to be merged with the one that is generated, instead of overriding/replacing it. 

Ideally, I'd like to be able to generate the api-docs dynamically, which would mean having my own resource controller responding to the api-docs URL. However, I'm unable to use the springdoc.api-docs.enabled property to disable the default OpenApiResource controller, as this also disables the SpringDocConfiguration, which is required for the SwaggerWelcome/SwaggerConfig controllers/configuration to be enabled. 

Any ideas?

**Comment by bnasslahsen** [comment]
Hi @darrellme, 

 Please have a look at the following resposne:
- https://github.com/springdoc/springdoc-openapi/issues/358

 If it answers your request, it will be added to the FAQ,

**Comment by darrellme** [comment]
Perfect, thanks, works a treat

**Comment by bnasslahsen** [comment]
Thank you @darrellme for your feedback.
