### ISSUE TITLE
Question - do you have an example of setting a global header?

### ISSUE THREAD

**Issue by davidmelia** [springdoc/springdoc-openapi#39]

**Comment by springdoc** [comment]
Hi, 

 You can add headers to your requests/responses using the OpenAPI annotations: @ApiResponse, @Parameter (in header).
 Or if you use spring annotations @RequestHeader, it will be added as a header parameter.
 Examples are available here: 

- https://github.com/springdoc/springdoc-openapi-demos/tree/master/springdoc-openapi-test-app2

**Comment by davidmelia** [comment]
@springdoc  springfox provides the ability to add global request headers which is very useful
` public Docket globalOperationParameters(List<Parameter> operationParameters) {`
Would this be possible as a feature?

**Comment by springdoc** [comment]
Hi, 

 Can you please add more détails about this expected feature: 
 - The use case, with an example using swagger annotations for documentation (ideally)
 - The expected OpenAPI description as result, in yaml/or json format

**Comment by davidmelia** [comment]
Hi @springdoc 

See my springfox example in  https://github.com/davidmelia/springfox-webflux where SwaggerConfig has the magic
```
Parameter parameter = new ParameterBuilder().name("My-Client-Type").description("My Client Type Header").modelRef(new ModelRef("string")).parameterType("header").required(true)
        .allowableValues(new AllowableListValues(asList("browser", "android", "ios"), "BROWSER")).defaultValue("swagger").build();

return new Docket(DocumentationType.SWAGGER_2). . . .globalOperationParameters(asList(parameter));

```
which allows the setting of global parameters.  This is very useful for concepts such as a global client type header.

From an Open API point of view you could append My-Client-Type to each API like the below:

```
  "paths": {
    "/tweets": {
      "get": {
        "operationId": "getAllTweets",
        "parameters": [
          {
            "name": "My-Client-Type",
            "in": "header",
            "required": true,
            "schema": {
              "type": "string",
              "enum": [
                "browser",
                "android",
                "ios"
              ]
            }
          }
        ],
```
I think there is a ref ability in open API but that may make things more complex.

What do you think?

Thanks

**Comment by springdoc** [comment]
Hi, 

  You may have global parameters with Standard OpenAPI description. 
  You can define common parameters under parameters in the global components section and reference them elsewhere via $ref.  You can also define global header parameters.
 For this, you can override to OpenAPI Bean, and set the global headers or parameters definition on the components level.
 You will have better support for this feature on v1.1.25 of springdoc-openapi.
 
```java
@Bean
public OpenAPI customOpenAPI(@Value("${springdoc.version}") String appVersion) {
 return new OpenAPI().components(new Components().addSecuritySchemes("basicScheme",
 new SecurityScheme().type(SecurityScheme.Type.HTTP).scheme("basic"))
.addParameters("myHeader1", new Parameter().in("header").schema(new StringSchema()).name("myHeader1")).addHeaders("myHeader2", new Header().description("myHeader2 header").schema(new StringSchema())))
.info(new Info().title("Petstore API").version(appVersion).description("This is a sample server Petstore server.  You can find out more about     Swagger at [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/).      For this sample, you can use the api key `special-key` to test the authorization     filters.").termsOfService("http://swagger.io/terms/")
.license(new License().name("Apache 2.0").url("http://springdoc.org")));
	}
```

**Comment by davidmelia** [comment]
Thanks that's perfect.  Look forward to v1.1.25

**Comment by MugdhaB** [comment]
Can we add a header with default value? Similar to https://github.com/springdoc/springdoc-openapi/issues/39#issuecomment-522688395 where My-Client-Type has default value swagger
