### ISSUE TITLE
@JsonView and preventing additional schemas generation

### ISSUE THREAD

**Issue by fgoulet** [springdoc/springdoc-openapi#392]
In a Spring Boot controller, I have a method annotated with @JsonView(JSONViews.Summary.class).
This method return a DTO that have some properties annotated with @JsonView.

springdocs generate additionnal schemas with _Summary appended to the actual schema name.  

Is there a way to prevent springdocs to generate additional schemas for JsonView ?

**Comment by bnasslahsen** [comment]
You can use `@Operation(ignoreJsonView = true)`

**Comment by Nhoutain** [comment]
I create a related issue: https://github.com/springdoc/springdoc-openapi/issues/1527

Is there a way to perform this from a global point of view? 
I mean, I have a lot of endpoint... It's not really elegant to add `@Operation(ignoreJsonView = true)` on each of them
