### ISSUE TITLE
Cannot reach Swagger UI through reverse proxy

### ISSUE THREAD

**Issue by MarkusA380** [springdoc/springdoc-openapi#397]
**Describe the bug**
When using a reverse-proxy where my Spring service is hosted in a subdomain (e.g. `https://foo.bar/test`) the Swagger UI will attempt to resolve:

- `https://foo.bar/v3/api-docs/swagger-config` if ` server. use-forward-headers: false`
- `https://test/swagger-ui/index.html?configUrl=/v3/api-docs/swagger-config` if `server. use-forward-headers: true`

Both are incorrect.

Here are some of the headers sent by the reverse proxy to the service:

- `host: test`
- `x-forwarded-host: foo.bar, foo.bar`
- `x-forwarded-port: 443`
- `x-forwarded-prefix: /test`
- `x-forwarded-proto: https`
- `x-forwarded-server: foo.bar`
- `x-scheme: https`

In the prior, it fails to correctly resolve the subdomain, as it doesn't take `x-forwarded-prefix` into account.

In the latter, it attempts to resolve a completely incorrect path for `index.html`. This seems to stem from it using the `host` - header. What it should do is resolve the subdomain using `x-forwarded-prefix`.

**To Reproduce**

Spring-Boot version: `2.1.6.RELEASE`

Dependency:
```
		<dependency>
			<groupId>org.springdoc</groupId>
			<artifactId>springdoc-openapi-ui</artifactId>
			<version>1.2.19</version>
		</dependency>
```

Any basic REST controller behind a reverse proxy with the same set of headers will do.

**Expected behavior**
- With the correct configuration applied, the correct  `swagger-config` (e.g. `https://foo.bar/test/v3/api-docs/swagger-config`) should be loaded into the UI.

**Comment by bnasslahsen** [comment]
Can you please confirm the same issue happens applying the FAQ and using the last version 1.2 29:?
 - https://springdoc.github.io/springdoc-openapi-demos/faq.html#how-can-i-deploy-the-doploy-springdoc-openapi-ui-behind-a-reverse-proxy

**Comment by MarkusA380** [comment]
I found a solution by updating Spring Boot to `2.2.2.RELEASE` and using `server.forward-headers-strategy: framework`.

Unfortunately I don't have time to test the provided solution too, but I will update the dependency anyways.

**Comment by bnasslahsen** [comment]
Thank you @MarkusA380 for your feedback.
