### ISSUE TITLE
Sort GroupedOpenApi by name

### ISSUE THREAD

**Issue by stefan-huettemann** [springdoc/springdoc-openapi#398]
Hi,

### Problem: unsorted groups
when defining multiple groups as:
```
 @Bean
    public GroupedOpenApi openApiServices() {
        return GroupedOpenApi.builder()
                             .setGroup("Group Name A")
                             .pathsToMatch("/some/path/pattern/**")
                             .build();
    }
```
it seems to result in an arbitrary ordered list of groups in swagger config, as in example:
```
"urls": [
    {
      "url": "/sasmd/v3/api-docs/9-Actuator",
      "name": "9-Actuator"
    },
    {
      "url": "/sasmd/v3/api-docs/2-Security",
      "name": "2-Security"
    },
    {
      "url": "/sasmd/v3/api-docs/1-Other",
      "name": "1-Other"
    }
  ]
```

I would like as the default behavior to sort the groups by name.

### Solution
A possible solution would be to change `org/springdoc/core/SwaggerUiConfigProperties.java:376` (see: 26d58f27f5b08f7c11b8a7bf260a597e3571793e):
```
swaggerUrls = swaggerUrls.stream().filter(elt -> StringUtils.isNotEmpty(elt.getUrl())).sorted().sorted(Comparator.comparing(SwaggerUrl::getName)).collect(Collectors.toList());
```

### Alternatives

maybe also a "order" attribute on the `GroupedOpenApi.builder()` would be nice to have.

Best,
-Stefan

P.S.: if you like the idea and would prefer a pull request, let me know. Thanks.

**Comment by bnasslahsen** [comment]
Hi @stefan-huettemann, 

 The groups will be sorted by name (natural order) from the next release.
 By default, the sort order will be ascending.

 If you need to change the order, the following property is introduced:

```properties
springdoc.swagger-ui.groups-order=DESC
```

**Comment by stefannawrath** [comment]
I figured out, the sort is based on the name, not on Display-Name. For me, it makes more sense to sort the displayed group name.

**Comment by johncurrier** [comment]
For some reason AbstractSwaggerUiConfigProperties.Direction doesn't have public access, so this technique can't be used programmatically.
