### ISSUE TITLE
A Controller method that does not return a response body still documents a schema, media type, etc

### ISSUE THREAD

**Issue by leoherbie** [springdoc/springdoc-openapi#40]
@GetMapping("/health")
    @ResponseStatus(HttpStatus.OK)
    fun check() { }

This function only returns a status code and nothing more.  I would expect the generated documentation to reflect this.  Thank you.

**Comment by leoherbie** [comment]
Note that @ResponseStatus(HttpStatus.NO_CONTENT) doesn't make a difference either

**Comment by springdoc** [comment]
Hi, 

  The library supports java and not kotlin. You will have to replace in the example fun by void to test it.
  It will be possible to return only the status code, starting from v1.1.22.

**Comment by leoherbie** [comment]
We are developing a 100% kotlin project and your library is working great.  Figured you might want feedback related to alternative languages.  I will attempt to mess with the return type to see what happens.

**Comment by leoherbie** [comment]
FYI.  I did try:     
    `@GetMapping("/health")
    @ResponseStatus(HttpStatus.OK)
    @Suppress("EmptyFunctionBlock")
    fun check() : ResponseEntity<Void> = ResponseEntity.of(Optional.empty())`

Which generated the same result

**Comment by leoherbie** [comment]
Also tried adding `@ApiResponse(content = [Content(schema = Schema(hidden = true))])`

**Comment by onacit** [comment]
It seems work with following code.

```java
    @ApiResponse(content = {@Content(schema = @Schema(implementation = void.class, hidden = true))})
```
