### ISSUE TITLE
Question - java.time.Instant mapped to int64 (Long)

### ISSUE THREAD

**Issue by pwang1984** [springdoc/springdoc-openapi#400]
Hi, 

I am migrating from springfox. One thing I noticed is that our java.time.Instant is converted to int64, while springfox was generating string(date-time). I know if using @Schema should work, but we don't want to add the annotation to all our Instant. Is there a way to register some kind of global converter? 
Thanks.

I am using version 1.2.29.

`
class Test {
  private Instant expiry;
}
`

in /v3/api-docs (springdocs)
`
{
  expiry":{"type":"integer","format":"int64"}
}
`

in /v2/api-docs (springfox)
`
{
  expiry":{"type":"string","format":"date-time"}
}
`

**Comment by pwang1984** [comment]
May not be ideal but I managed to do it by adding 
`PrimitiveType.customClasses().put("java.time.Instant", PrimitiveType.DATE_TIME);`
before the OpenAPI Bean.

Is it the supposed way to add custom type mapping? Can we please add it to the doc?

Thanks

**Comment by bnasslahsen** [comment]
Hi @pwang1984, 

 This one of the solutions. You could also use ModelConverter.
 But your proposal seems to be Ok as well.

 You can propose a PR to update the FAQ.
 Here is the link for the documentation:
 - https://github.com/springdoc/springdoc-openapi-demos/blob/master/docs/faq.md
