### ISSUE TITLE
Wrong oauth2-redirect.html path using OAuth2 Code flow

### ISSUE THREAD

**Issue by patst** [springdoc/springdoc-openapi#403]
**Describe the bug**

This sounds very like https://github.com/springdoc/springdoc-openapi/issues/340 .
We are using openapi-ui version 1.2.30 and have an OAuth2 secured API (Authorization code flow).

When we use the authorize button in Swagger-UI after logging in we get redirected to something like `http://localhost:8080/oauth2-redirect.html` . Notice that the `/swagger-ui` part is missing in the path.

We use the generated Openapi Spec (`/v3/api-docs`).
The content of `/v3/api-docs/swagger-config` is:

```
{ 
   "configUrl":"/v3/api-docs/swagger-config",
   "oauth2RedirectUrl":"http://localhost:8088/swagger-ui/oauth2-redirect.html",
   "url":"/v3/api-docs",
   "validatorUrl":""
}
``` 

The `securityScheme` config in the spec looks like this:

```
"securitySchemes":{ 
   "oauth2":{ 
      "type":"oauth2",
      "in":"header",
      "bearerFormat":"jwt",
      "flows":{ 
         "authorizationCode":{ 
            "authorizationUrl":"https://localhost:9002/authorizationserver/oauth/authorize",
            "tokenUrl":"http://localhost:8080/oauth/token"
         }
      }
   }
}
```

**To Reproduce**
- What version of spring-boot you are using?
2.2.4.RELEASE
- What modules and versions of springdoc-openapi are you using?
org.springdoc:springdoc-openapi-ui:1.2.30'

**Expected behavior**

I would expect to be redirected to `http://localhost:8080/swagger-ui/oauth2-redirect.html` after logging in at the OAuth2 provider.

**Additional info**

Can you point me in a direction where to debug to further investigate the issue? Or is my config simply wrong?

**Comment by bnasslahsen** [comment]
Are you using any  configuration properties ?
Difficult to answer you without providing a sample project to reproduce.

**Comment by patst** [comment]
Thanks for your reply.
We are configuring a `client_id` and `client_secret` in the `application.yaml` and using a annotation to configure the `tokenUrl` and `authorizationUrl` .

I prepared the smallest example I can think of with an mock controller for the authorization server. It just prints the input params.
The project can be found here: https://github.com/patst/springdocs-redirect-problem

**Comment by bnasslahsen** [comment]
Hi, 

 The sample code you have provided is not complete:
- The /token endpoint doen not exist: You should mock your `token-url` inside you `IdentityProviderController`.
- Your authorise endpoint does not return to the redirect uri and passing the state and code parameters

Please note also that on the application.yml, there is no need to add the property oauth2RedirectUrl. 
as you are using the default value

Here is a sample working mock (don't forget to disable spring-security for the endopint /token):

```java
@Controller
public class IdentityProviderController {

    @GetMapping(value = "/oauth/authorize")
    public String authorize(@RequestParam("client_id") String clientId,
                            @RequestParam("redirect_uri") String redirectUri,
                            @RequestParam("response_type") String type,
                            @RequestParam("state") String state) {
		return "redirect:"+redirectUri+"?code=samplecode&state="+state;
    }

	@PostMapping(value = "/oauth/token", consumes = { MediaType.APPLICATION_FORM_URLENCODED_VALUE})
	@ResponseBody
	public OAuth2AccessToken token(@RequestParam("client_id") String clientId,
			@RequestParam("redirect_uri") String redirectUri,
			@RequestParam("grant_type") String type,
			@RequestParam("client_secret") String secret,
			@RequestParam("code") String code) {
		return new OAuth2AccessToken(TokenType.BEARER,"mytoken", Instant.now(), Instant.now().plusMillis(1000000));
	}


}
```

**Comment by patst** [comment]
Thanks for your reply and taking the time to look at the example.

Imho the example was complete enough to show the problem, which is the wrong redirect URL arriving at the `authorize` endpoint.

The `redirect_uri` value arriving at the `authorize` endpoint is `http://localhost:8080/oauth2-redirect.html?code=samplecode....`. This is even the case when I configure the `oauth2RedirectUrl` value which seems to be ignored completely.

The expected value would be `http://localhost:8080/**swagger-ui**/oauth2-redirect.html?code=samplecode....`.

I updated the example with your suggested changes. 
Would be great if you can give it another shot. Just run it with `./gradlew bootRun` and open http://localhost:8080/swagger-ui/index.html?url=/v3/api-docs and try the authorization

**Comment by bnasslahsen** [comment]
Hi @patst, 

 I have just ran your sample, and getting the following redirect_uri on both /token and /authorize:
- http://localhost:8080/swagger-ui/oauth2-redirect.html

 Is that what are you expecting, or maybe you are getting a different result?

**Comment by patst** [comment]
> Hi @patst,
> 
> I have just ran your sample, and getting the following redirect_uri on both /token and /authorize:
> 
> * http://localhost:8080/swagger-ui/oauth2-redirect.html
> 
> Is that what are you expecting, or maybe you are getting a different result?

Hi @bnasslahsen 

thanks for trying it!
That is super strange. I would expect it like it is on your machine.

I am getting a different result. ( http://localhost:8080/oauth2-redirect.html )

That leaves me puzzled. Any idea what might cause the difference?

**Comment by raghuraman1** [comment]
Hi @bnasslahsen,
I am also getting something like http://localhost:8081/swagger-ui/oauth2-redirect.html in a different implementation. So how did the above discussion actually conclude? How to ensure http://localhost:8081/oauth2-redirect.html ?
R

**Comment by raghuraman1** [comment]
Got it I think, Its configured using springdoc.swagger-ui.oauth2-redirect-url

**Comment by spirann** [comment]
Hi @patst,
did you find a solution ? , I've the same problem the oauth login box is loaded with the parameter `&redirect_uri=http:%2F%2Flocalhost:5000%2Foauth2-redirect.html` which result in a 404 on http://localhost:5000/oauth2-redirect.html?code=xxx

**Comment by verteil-surya** [comment]
@spirann have you find any solutions , i can access api doc , swagger-config but cannot access swagger-ui , getting 404 for swagger url
