### ISSUE TITLE
Property to exclude packages and paths from documentation

### ISSUE THREAD

**Issue by ilaktasic** [springdoc/springdoc-openapi#404]
**Is your feature request related to a problem? Please describe.**
Projects I'm working on have package by feature structure and most controllers need to be documented. Let's say there are two "maintenance" endpoints which are hidden. So there are two options to exclude documents from documentation 

1.  Add `@Hidden` annotation to controllers:
I'm not fond of adding extra annotations like `@Hidden` to code to disable default behavior if 
behavior can be changed. 

2.  Add all packages to which need to be documented to `springdoc.packagesToScan` property:
There would be too many packages in property and every time new controller is added property needs to be updated because of package by feature structure controllers are not in the same package.

**Describe the solution you'd like**
It would be useful to have property to exclude packages or paths from documentation.
For example: `springdoc.packagesToExclude` and `springdoc.pathsToExclude` properties.

**Comment by marichka-spin** [comment]
version 1.2.30

**Comment by bnasslahsen** [comment]
Hi @ilaktasic, 

 The support will be added on v1.2.31.
