### ISSUE TITLE
OAuth2 implicit flow "client_id" field is empty

### ISSUE THREAD

**Issue by marichka-spin** [springdoc/springdoc-openapi#405]
**Describe the bug**
I'm using SpringBoot 2.2 and trying to migrate from springfox 2.9.2 to springdoc-openapi. We use OAuth2 security Scheme. I'm trying to setup swagger ui to be able to go through implicit login flow.
But "client_id" property on auth dialog is empty and I need it filled with correct clientId.
My code to setup OpenAPI:

```java
@Bean
  public OpenAPI customOpenAPI() {
    String authorizeUrl = String.format(
        "https://login.microsoftonline.com/%s/oauth2/v2.0/authorize", tenantId);
    Scopes scopes = new Scopes();
    scopes.addString(apiScope, "Access API");
    OAuthFlow oAuthFlow = new OAuthFlow();
    oAuthFlow.authorizationUrl(authorizeUrl);
    oAuthFlow.setScopes(scopes);
    return new OpenAPI()
        .components(
            new Components()
                .addSecuritySchemes("oauth", new SecurityScheme()
                    .type(Type.OAUTH2)
                    .in(In.HEADER)
                    .bearerFormat("jwt")
                    .flows(
                        new OAuthFlows().implicit(oAuthFlow)
                )
        )));
  }
```

My application.pproperties
springdoc.swagger-ui.oauth.clientId=some client id
springdoc.swagger-ui.oauth.clientSecret=some client secret

Expected result
field "client_id" is populated with springdoc.swagger-ui.oauth.clientId value
![Screenshot from 2020-02-05 17-48-41](https://user-images.githubusercontent.com/5120736/73858467-1de76700-4841-11ea-9c1d-6e4c373324f8.png)

**Comment by bnasslahsen** [comment]
Which springdoc version are you using ?

**Comment by marichka-spin** [comment]
> Which springdoc version are you using ?

version 1.2.30

**Comment by marichka-spin** [comment]
Sorry for disturbing but after full clean and rebuilt and cleaning browser cache it finally worked. Thank you for nice project
