### ISSUE TITLE
Wrong redirect when deployed behind proxy

### ISSUE THREAD

**Issue by Orlan2806** [springdoc/springdoc-openapi#406]
Hi,
I know, the headline sounds like an already solved issue, but I tried any solution I found in previous issues and still couldn't fix my problem:

My Spring application with springdoc is deployed behind a proxy, the url for my static welcome page looks like this:
`server:port/contextpath`

In my application.yml, I have:
`springdoc:
    swagger-ui:
        path: "/swagger/swagger-ui.html"`

And (Not under springdoc:)

`contextroot: "contextpath"`

If I don't do anything about the proxy deployment, the swagger UI can be reached as I want it to be, under `server:port/contextpath/swagger/swagger-ui.html` which redirects to `server:port/contextpath/swagger/swagger-ui/index.html&(parameterstuff)`.

But the /v3/api-docs can not be found, as they are accessible under `server:port/v3/api-docs`

If I try and add any of the solutions I found (server.use-forward-headers or server.forward-headers-strategy or the ForwardedHeaderFilter Bean) and I type `server:port/contextpath/swagger/swagger-ui.html`, I get redirected to `server:port/contextpath/contextpath/swagger/swagger-ui/index.html&(parameterstuff)`, where no swagger-ui is found. Then I manually have to remove the duplicated contextpath to actually access the swagger-ui, but now the v3/api-docs are found.

As none of the solutions I found seem to work, I thought I should creat my own issue to address this problem.

Thing is that I am rather new into this project I am working on, so I don't know which interactions may or may not cause this problem, but feel free to ask me anything if you have an idea which other settings in the project could cause such behaviour.

As you see, we have a property called contextroot in our project for internal uses. I just added this info because I thought maybe this could interact with something springdoc related, but frankly I don't know.

**Comment by Orlan2806** [comment]
I also noticed that if it is deployed on a server where I can reach it with https://serverurl/swagger/swagger-ui.html and I have any of the proxy solutions I found, the generated server url ends up with http://serverurl which causes all requests to fail.

**Comment by bnasslahsen** [comment]
Hi @Orlan2806, 

 We invite you to review your configuration according to the properties in the FAQ, and using ForwardedHeaderFilter Bean.
- https://springdoc.github.io/springdoc-openapi-demos/faq.html#how-can-i-deploy-the-doploy-springdoc-openapi-ui-behind-a-reverse-proxy

 For example,  if you are using Spring Boot to 2.2.2.RELEASE, you should set `server.forward-headers-strategy: framework`
 Make sure you are using the last stable version: v1.2.30

 Make sure the right headers are sent by your proxy (x-forwarded-prefix and others) are sent by your proxy: Example here  #397, #391.
