### ISSUE TITLE
@Schema type does not override the generated type

### ISSUE THREAD

**Issue by jawpio** [springdoc/springdoc-openapi#409]
In some cases the type is not overriden e.g.

Create a simple interface describing the type e.g.
```
@Schema(type = "number", description = "Maximum length 25", format = "decimal", example = "100000.00", maxLength = 25, name = "PriceType")
public class PriceType {
}
```

Use it in a model as:
```
	@Schema(implementation = PriceType.class)
	@JsonProperty(value = "price")
	private BigDecimal price;
```

The generated yaml/json would contain following type in the definitions:
```
            "PriceType": {
                "maxLength": 25,
                "type": "object",
                "description": "Maximum length 25",
                "format": "decimal",
                "example": "100000.00"
            }
```

Please note that type of PriceType is **object** but it should be the **number**.

**Comment by bnasslahsen** [comment]
Hi @jawpio, 

 springdoc-openapi is built on top of swagger-api.
 The behaviour you are describing is the standard implementation: You can have a look at the javadoc of swagger-annotation `@Schema`

- implementation:  Provides a java class as implementation for this schema.  When provided, additional information in the Schema annotation (**except for type information**) will augment the java class after introspection.


 If you want to propose enhancements, you should submit them on the swagger-api project;
- https://github.com/swagger-api/swagger-core/issues
