### ISSUE TITLE
Consider using spring.mvc.static-path-pattern if set

### ISSUE THREAD

**Issue by leoherbie** [springdoc/springdoc-openapi#41]
Currently our configuration looks like the following:

`app.path=/foo`
`spring.mvc.static-path-pattern=${app.path}/**`
`springdoc.swagger-ui.path=${app.path}/swagger-ui.html`
`springdoc.api-docs.path=${app.path}/api-docs`

As a convenience, you may want to use the `spring.mvc.static-path-pattern` if set to serve the swagger resources.  Just a suggestion since the swagger docs could be considered static resources.  Anyway, we thought we'd make this suggestion and see what you guys thought.

**Comment by springdoc** [comment]
We rely on swagger-ui webjars, and there is a special case for Webjars content using spring-mvc. Any resources with a path in /webjars/** will be served from jar files if they are packaged in the Webjars format. Consequently, the default behaviour is using /webjars path for serving these resources.
 
If your config is: springdoc.swagger-ui.path=${app.path}/swagger-ui.html
With, the version 1.1.23 of springdoc-openapi, you will have the static ressources served from the path: ${app.path}/

If you need to serve these resources from another specific path, you can just override the org.springdoc.ui.SwaggerConfig.

**Comment by leoherbie** [comment]
Thanks so much for the feedback.  I just brought down the latest build and it seems to now be hiding webjars from the url which is great.  Everything is served from the correct place and working as expected
