### ISSUE TITLE
Support for kotlin.Deprecated

### ISSUE THREAD

**Issue by StevenKuypers** [springdoc/springdoc-openapi#414]
Hi,
This is about using OpenApi in a Kotlin project.

When an endpoint is marked with java.lang.Deprecated, then SpringDoc shows it as deprecated in the GUI (as expected). For Kotlin projects, it would be good to have the same support for when the annotation kotlin.Deprecated is used. It is possible to add "deprecated = true" to @Operation to see the strike-through on the swagger page, but then we still miss the message, level and ReplaceWith of the kotlin.Deprecated annotation.

**Comment by joaodias14** [comment]
Thanks @bnasslahsen !
