### ISSUE TITLE
Feature: Disable autotagging of @RestController Classes

### ISSUE THREAD

**Issue by notes-jj** [springdoc/springdoc-openapi#420]
**Is your feature request related to a problem? Please describe.**

Create application-properties property to prevent creation of tags for every class. In my case all Methods are tagged individually and the `@RestController` Classes should not appear as Tag.

**Describe the solution you'd like**
- application.properties:
  `springdoc.autotag-classes=false`
- Classes should not appear as Tags in /v3/api-docs

**Describe alternatives you've considered**
- None

**Comment by bnasslahsen** [comment]
Hi @notes-jj, 

 The following property will be added on v1.2.31 to disable auto-tagging of RestController Classes.
```properties
springdoc.auto-tag-classes=false
```
The default value of this property, is set to true.
