### ISSUE TITLE
Multiservice / Remote API-docs

### ISSUE THREAD

**Issue by jozzan** [springdoc/springdoc-openapi#421]
**Is your feature request related to a problem? Please describe.**
I'm having multiple services in a microservice infrastructure and each of them comes with their own API as well as documentation. Now I would like to gather that information in one service (or maybe even leave it as is) and display it using swagger-ui.
Currently there is support for Multiple APIs via MultiOpenapiResource but this one seems to rely on Annotations to be present in the local servcie.
I would like to specify multiple groups and let the ui fetch the specs from somewhere entirly else.

**Describe the solution you'd like**
Maybe more options to configure GroupedOpenApis?

**Describe alternatives you've considered**
Currently I've registered multiple GroupedOpenApi Beans with my Spring container as well as replaced MultiOpenapiResource's endpoints with my own to go fetch specs from somewhere.

**Comment by bnasslahsen** [comment]
Hi @jozzan, 

 Please look the answer of #309.
 If it works for you, it will be added to the FAQ.
