### ISSUE TITLE
Add Suppot for Hiding org.springframework.security.core.Authentication on ServerHttpResponse 

### ISSUE THREAD

**Issue by frankruegamer** [springdoc/springdoc-openapi#423]
I noticed this issue #245, but the Authentication definition still seems to be visible in the schema.
org.springframework.http.server.reactive.ServerHttpResponse on the other hand is hidden as expected.

Using springdoc v1.2.30. (Webflux)

**Comment by bnasslahsen** [comment]
The support will be available on v 1.2.31.

**Comment by frankruegamer** [comment]
After updating to 1.2.31 the Authentication object is still exported. Using the following method:

```
@PostMapping
public LoginResult login(Authentication authentication, ServerHttpResponse response) {
}
```

the following will be generated:
```
Authentication:
      type: object
      properties:
        principal:
          type: object
        credentials:
          type: object
        authorities:
          type: array
          items:
            $ref: '#/components/schemas/GrantedAuthority'
        authenticated:
          type: boolean
        details:
          type: object
        name:
          type: string
    GrantedAuthority:
      type: object
      properties:
        authority:
          type: string
```

Please let me know if you can't reproduce this issue as I'm happy to create a minimal project showcasing it.

**Comment by bnasslahsen** [comment]
Yes please, add the sample project to reproduce.

**Comment by frankruegamer** [comment]
https://github.com/frankruegamer/sprindoc-authentication-bug

Note that the schema looks exactly like the one above.

**Comment by bnasslahsen** [comment]
You are just missing the following dependency on your project:

```xml
<dependency>
	<groupId>org.springdoc</groupId>
	<artifactId>springdoc-openapi-security</artifactId>
	<version>1.2.31</version>
</dependency>
```

You can have a look at the documentation; (Section Spring security support)
- https://springdoc.github.io/springdoc-openapi-demos/

**Comment by frankruegamer** [comment]
Ah I didn't know this existed :) Works perfectly!
