### ISSUE TITLE
Filter parameter does not work

### ISSUE THREAD

**Issue by mariusreusch** [springdoc/springdoc-openapi#424]
I tried to add the filter edit box in the top bar in order to filter the tagged operations that are shown. As described here https://springdoc.github.io/springdoc-openapi-demos/ in the section Swagger-ui configuration, I added the following line to my application.properties files:
```
springdoc.swagger-ui.filter=true
```
Unfortunately the edit box does not appear. 

By providing the filter setting as url parameter (as described here https://github.com/swagger-api/swagger-ui/blob/master/docs/usage/configuration.md#how-to-configure) the edit box is displayed.

**To Reproduce**
- What version of spring-boot you are using? **2.0.8.RELEASE**
- What modules and versions of springdoc-openapi are you using? **org.springdoc:springdoc-openapi-ui:1.2.30**
- Provide with a sample code (HelloController) or Test that reproduces the problem: **https://github.com/mariusreusch/test-springdoc-swagger-filter**

**Expected behavior**
- See the filter edit box in the top bar.

**Comment by bnasslahsen** [comment]
Hi @mariusreusch, 

 This is a bug in swagger-ui.
 You can follow it :
 - https://github.com/swagger-api/swagger-ui/issues/4267

**Comment by bnasslahsen** [comment]
waiting for this issue to be resolved on swagger-ui side.
A workaround, will be availble on v1.3.1 of springdoc-openapi.
