### ISSUE TITLE
Feature: Please detect ModelAndView as text/html content

### ISSUE THREAD

**Issue by notes-jj** [springdoc/springdoc-openapi#428]
**Is your feature request related to a problem? Please describe.**
- No OpenApi Endpoint is rendered for return type `org.springframework.web.servlet.ModelAndView` (see example at the end)

**Describe the solution you'd like**
- springdoc-openapi should detect `ModelAndView`
- Return OpenApi Document like (mind the `"type": "string"`):

``` json
"responses": {
  "200": {
    "description": "default response",
    "content": {
      "text/html": {
        "schema": {
          "type": "string"
        }
      }
    }
  }
}
```

**Describe alternatives you've considered**

Workaround return Object. But this will not produce a correct return type.

```
@Operation(summary = "Get Status")
@GetMapping(value = "/status", produces = MediaType.TEXT_HTML_VALUE)
public Object getStatus()
```

OpenApi Response should be `"type": "string"` 

```
"responses": {
  "200": {
    "description": "default response",
    "content": {
      "text/html": {
        "schema": {
          "type": "object"
        }
      }
    }
  }
}
```

**Additional context**

Example:

```
@Operation(summary = "Get Status")
@GetMapping(value = "/status", produces = MediaType.TEXT_HTML_VALUE)
public ModelAndView getStatus()
```

**Comment by bnasslahsen** [comment]
Hi @notes-jj, 

 By default ModelAndView is ignored in springdoc-openapi. 
 With the next release: v1.2.31, you will be able to display RestControllers that use ModelAndView as well.
 For that, you will need to define the following property:

```properties
springdoc.model-and-view-allowed=true
```

 If you need to map ModelAndView to a another more convinient type (for example Object), you can just add the following declaration, in any static block:

```java
AdditionalModelsConverter.replaceWithSchema(ModelAndView .class, new ObjectSchema());
```

 You can hava a look at [SpringDocApp89Test ](https://github.com/springdoc/springdoc-openapi/blob/master/springdoc-openapi-webmvc-core/src/test/java/test/org/springdoc/api/app89/)for more details.
