### ISSUE TITLE
http://localhost:3006/swagger-ui/index.html serves Swagger Petstore.  Can this be disabled?

### ISSUE THREAD

**Issue by leoherbie** [springdoc/springdoc-openapi#43]
Navigating to http://localhost:3006/swagger-ui/index.html serves up the sample Swagger Petstore apis.  Can these be disabled?  I did not see any reference to the petstore within your codebase so perhaps this option does not exist just yet.  Thanks so much.

Here is a stackoverflow that may be helpful:

https://stackoverflow.com/questions/49515713/remove-petstore-spec-when-starting-swagger-editor

**Comment by springdoc** [comment]
Hi, 

 We rely on swagger-ui official webjars. We build our library on top of it.
 The index.html is available inside the webjar and it contains a JS call to https://petstore.swagger.io/v2/swagger.json, if url parameter is absent.
 You can submit an enhancement on the swagger-ui project: 

- https://github.com/swagger-api/swagger-ui/issues

 
 Also, you can rebuild the webjars for your own needs, if you don't want to have any reference to petsotre.
 Please, note that in the normal  behavior, users  will have access to index.html without query parameters, only if they remove the url query parameter manually.

**Comment by leoherbie** [comment]
I figured as much.  I just wondered if there was a way to prevent it from being served or available.  Sounds like there isn't.  Bummer.

**Comment by StephGit** [comment]
Hi @leoherbie, we use the following workaround to prevent serving petstore:
`@Configuration
public class SpringdocSwaggerFix implements WebMvcConfigurer {

  @Override
  public void addResourceHandlers(ResourceHandlerRegistry registry) {
    registry.addResourceHandler("/**/*.html")
        .addResourceLocations("classpath:/META-INF/resources/webjars/")
        .resourceChain(false)
        .addResolver(new WebJarsResourceResolver())
        .addResolver(new PathResourceResolver())
        .addTransformer(new IndexPageTransformer());
  }

  public class IndexPageTransformer implements ResourceTransformer {
    @Override
    public Resource transform(HttpServletRequest request, Resource resource,
                              ResourceTransformerChain transformerChain) throws IOException {
      if (resource.getURL().toString().endsWith("/index.html")) {
        String html = getHtmlContent(resource);
        html = overwritePetStore(html);
        return new TransformedResource(resource, html.getBytes());
      } else {
        return resource;
      }
    }

    private String overwritePetStore(String html) {
      return html.replace("https://petstore.swagger.io/v2/swagger.json",
          "/v3/api-docs");
    }
}
`

**Comment by anksngp** [comment]
Hi @StephGit I tried the way you have mentioned in the above comment, can you also post the contents of the method getHtmlContent

**Comment by StephGit** [comment]
Hi @anksngp

Sure:

` private String getHtmlContent(Resource resource) {
      try {
        InputStream inputStream = resource.getInputStream();
        java.util.Scanner s = new java.util.Scanner(inputStream).useDelimiter("\\A");
        String content = s.next();
        inputStream.close();
        return content;
      } catch (IOException e) {
        throw new RuntimeException(e); 
      }
    }`

**Comment by Andrew3431** [comment]
Hi @StephGit , @bnasslahsen 

When trying the above snippet I noticed that, the newly generated swagger document on calling just `localhost:8080/swagger/swagger-ui/index.html` (after replacing `https://petstore.swagger.io/v2/swagger.json` with `v3/api-docs`) does not have the application-properties that were set on swagger document like 
```
springdoc.swagger-ui.doc-expansion=none
springdoc.swagger-ui.operationsSorter=alpha
springdoc.swagger-ui.tagsSorter=alpha
```

Is there any way to get the properties applied to swagger document as well ?
P.S. On calling the complete url `http://localhost:8080/swagger/swagger-ui/index.html?configUrl=/v3/api-docs/swagger-config#/` the application properties are applied to the swagger document.

**Comment by thlaegler** [comment]
I'm using custom pathes for Swagger-UI and api-docs and to following application.yaml solved this issue for me (without using any of the above Workarounds):
```
springdoc:
  api-docs:
    enabled: true
    path: '/my/custom/path/api-docs'
  swagger-ui:
    path: '/my/custom/path/swagger-ui'
    configUrl: '/my/custom/path/api-docs/swagger-config'
    urls:
    - name: My Custom API
      url: '/my/custom/path/api-docs'
```
(Note the properties under `springdoc.swagger-ui.urls`)

**Comment by shasureshkumar** [comment]
> I'm using custom pathes for Swagger-UI and api-docs and to following application.yaml solved this issue for me (without using any of the above Workarounds):
> 
> ```
> springdoc:
>   api-docs:
>     enabled: true
>     path: '/my/custom/path/api-docs'
>   swagger-ui:
>     path: '/my/custom/path/swagger-ui'
>     configUrl: '/my/custom/path/api-docs/swagger-config'
>     urls:
>     - name: My Custom API
>       url: '/my/custom/path/api-docs'
> ```
> 
> Note the list of URLs under `springdoc.swagger-ui.urls` since I have multiple api-docs. If you just have one, replace the urls-part with:
> `springdoc.swagger-ui.url='/my/custom/path/api-docs'`

its not working for me, my configuration is as follows
```springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    configUrl: /v3/api-docs/swagger-config
    display-request-duration: false
    tags-sorter: alpha
    operations-sorter: alpha
    defaultModelRendering: example
    doc-expansion: none
    url: /v3/api-docs```

**Comment by SledgeHammer01** [comment]
> Hi @leoherbie, we use the following workaround to prevent serving petstore:
> 
> ```
> @Configuration
> public class SpringdocSwaggerFix implements WebMvcConfigurer {
> 
>   @Override
>   public void addResourceHandlers(ResourceHandlerRegistry registry) {
>     registry.addResourceHandler("/**/*.html")
>         .addResourceLocations("classpath:/META-INF/resources/webjars/")
>         .resourceChain(false)
>         .addResolver(new WebJarsResourceResolver())
>         .addResolver(new PathResourceResolver())
>         .addTransformer(new IndexPageTransformer());
>   }
> 
>   public class IndexPageTransformer implements ResourceTransformer {
>     @Override
>     public Resource transform(HttpServletRequest request, Resource resource,
>                               ResourceTransformerChain transformerChain) throws IOException {
>       if (resource.getURL().toString().endsWith("/index.html")) {
>         String html = getHtmlContent(resource);
>         html = overwritePetStore(html);
>         return new TransformedResource(resource, html.getBytes());
>       } else {
>         return resource;
>       }
>     }
> 
>     private String overwritePetStore(String html) {
>       return html.replace("https://petstore.swagger.io/v2/swagger.json",
>           "/v3/api-docs");
>     }
> }
> ```

I found this issue. Beware. Checking for ending with /index.html is not enough to disable petstore. You can get there with:

/swagger-ui/index.html?configUrl=

and a few other patterns I've found as well.

**Comment by bnasslahsen** [comment]
@SledgeHammer01 

To disable the swagger-ui default petstore url, just use the following property: 


```properties
springdoc.swagger-ui.disable-swagger-default-url=true
```

More details, are available on the springdoc-openapi properties list:
- https://springdoc.org/springdoc-properties.html

**Comment by schrek1** [comment]
StephGit's solution works better, because it replaces default page. Instead disabling by config file (disable-swagger-default-url) which makes page look like broken swagger page...

**Comment by schrek1** [comment]
should be option available for replace default page instead

**Comment by shilanand** [comment]
> @SledgeHammer01
> 
> To disable the swagger-ui default petstore url, just use the following property:
> 
> ```ini
> springdoc.swagger-ui.disable-swagger-default-url=true
> ```
> 
> More details, are available on the springdoc-openapi properties list:
> 
> * https://springdoc.org/springdoc-properties.html

I have tried this but looks like it is not working

**Comment by SledgeHammer01** [comment]
> StephGit's solution works better, because it replaces default page. Instead disabling by config file (disable-swagger-default-url) which makes page look like broken swagger page...
> 
> ![image](https://user-images.githubusercontent.com/17483576/88787615-6ea69f80-d194-11ea-8a8c-0bb5cde55501.png)

Agreed. Don't waste your time on this property. It is a poorly implemented hack. You just wind up with a broken swagger page instead.

**Comment by thlaegler** [comment]
It's also noteworthy that there is a difference between `http://localhost:8085/swagger-ui/index.html` and `http://localhost:8085/swagger-ui.html`. The latter URL redirects to the former URL (the actual swagger-ui) with the configured `configUrl`-parameter e.g. `http://localhost:8085/swagger-ui/index.html?configUrl=/v3/api-docs/swagger-config`
