### ISSUE TITLE
Swagger generation using springdoc fails when methods are annotated with @PreAuthorize

### ISSUE THREAD

**Issue by mishraomp** [springdoc/springdoc-openapi#432]
**Springdoc is unable to access path and components when the endpoint methods are annotated with @Preauthorize, commenting the annotation produces valid json document**
project github url:- https://github.com/bcgov/EDUC-PEN-REQUEST-EMAIL-API/tree/feature/swagger/api
**To Reproduce**
- What version of spring-boot you are using?**2.2.0.RELEASE**
- What modules and versions of springdoc-openapi are you using?**springdoc-openapi-webmvc-core:1.2.30,  springdoc-openapi-ui:1.2.30, springdoc-openapi-security:1.2.30 **
- Provide with a sample code :- git url is provided.

Actual:-
GET:- http://localhost:8080/v3/api-docs
{
    "openapi": "3.0.1",
    "info": {
        "title": "API for Pen Request Email.",
        "description": "This API is responsible for sending different type of email notification to students.",
        "version": "1"
    },
    "servers": [
        {
            "url": "http://localhost:8080",
            "description": "Generated server url"
        }
    ],
    "security": [
        {
            "OAUTH2": [
                "SEND_PEN_REQUEST_EMAIL"
            ]
        }
    ],
    "paths": {},
    "components": {}
}

Expected:-
GET:- http://localhost:8080/v3/api-docs
{
    "openapi": "3.0.1",
    "info": {
        "title": "API for Pen Request Email.",
        "description": "This API is responsible for sending different type of email notification to students.",
        "version": "1"
    },
    "servers": [
        {
            "url": "http://localhost:8080",
            "description": "Generated server url"
        }
    ],
    "security": [
        {
            "OAUTH2": [
                "SEND_PEN_REQUEST_EMAIL"
            ]
        }
    ],
    "paths": {
        "/verify": {
            "post": {
                "tags": [
                    "Pen Request Email"
                ],
                "description": "verify student email",
                "operationId": "verifyEmail",
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/PenRequestEmailVerificationEntity"
                            }
                        }
                    }
                },
                "responses": {
                    "204": {
                        "description": "NO CONTENT"
                    },
                    "500": {
                        "description": "INTERNAL SERVER ERROR."
                    }
                }
            }
        },
        "/health": {
            "get": {
                "tags": [
                    "Pen Request Email"
                ],
                "description": "health check",
                "operationId": "health",
                "responses": {
                    "200": {
                        "description": "OK",
                        "content": {
                            "*/*": {
                                "schema": {
                                    "type": "string"
                                }
                            }
                        }
                    },
                    "500": {
                        "description": "INTERNAL SERVER ERROR.",
                        "content": {
                            "*/*": {
                                "schema": {
                                    "type": "string"
                                }
                            }
                        }
                    }
                }
            }
        },
        "/complete": {
            "post": {
                "tags": [
                    "Pen Request Email"
                ],
                "description": "send complete email",
                "operationId": "sendCompletedPENRequestEmail",
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/PenRequestCompleteEmailEntity"
                            }
                        }
                    }
                },
                "responses": {
                    "204": {
                        "description": "NO CONTENT"
                    },
                    "500": {
                        "description": "INTERNAL SERVER ERROR."
                    }
                }
            }
        },
        "/info": {
            "post": {
                "tags": [
                    "Pen Request Email"
                ],
                "description": "send additional info request email",
                "operationId": "sendAdditionalInfoRequestEmail",
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/PenRequestAdditionalInfoEmailEntity"
                            }
                        }
                    }
                },
                "responses": {
                    "204": {
                        "description": "NO CONTENT"
                    },
                    "500": {
                        "description": "INTERNAL SERVER ERROR."
                    }
                }
            }
        },
        "/reject": {
            "post": {
                "tags": [
                    "Pen Request Email"
                ],
                "description": "send reject notification email",
                "operationId": "sendRejectedPENRequestEmail",
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/PenRequestRejectedEmailEntity"
                            }
                        }
                    }
                },
                "responses": {
                    "204": {
                        "description": "NO CONTENT"
                    },
                    "500": {
                        "description": "INTERNAL SERVER ERROR."
                    }
                }
            }
        }
    },
    "components": {
        "schemas": {
            "PenRequestEmailVerificationEntity": {
                "required": [
                    "emailAddress",
                    "identityTypeLabel",
                    "penRequestId"
                ],
                "type": "object",
                "properties": {
                    "emailAddress": {
                        "type": "string"
                    },
                    "penRequestId": {
                        "type": "string"
                    },
                    "identityTypeLabel": {
                        "type": "string"
                    }
                }
            },
            "PenRequestCompleteEmailEntity": {
                "required": [
                    "emailAddress",
                    "firstName"
                ],
                "type": "object",
                "properties": {
                    "emailAddress": {
                        "type": "string"
                    },
                    "firstName": {
                        "type": "string"
                    }
                }
            },
            "PenRequestAdditionalInfoEmailEntity": {
                "required": [
                    "emailAddress"
                ],
                "type": "object",
                "properties": {
                    "emailAddress": {
                        "type": "string"
                    }
                }
            },
            "PenRequestRejectedEmailEntity": {
                "required": [
                    "emailAddress",
                    "rejectionReason"
                ],
                "type": "object",
                "properties": {
                    "emailAddress": {
                        "type": "string"
                    },
                    "rejectionReason": {
                        "type": "string"
                    }
                }
            }
        }
    }
}

**Comment by bnasslahsen** [comment]
Hi, 

 Make sure you add aop to your project if you want @PreAuthorize to work, and springdoc-openapi as well:

```xml
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-aop</artifactId>
		</dependency>
```

**Comment by mishraomp** [comment]
Thank you @bnasslahsen that worked :).
