### ISSUE TITLE
@Parameter can not recognize generics T

### ISSUE THREAD

**Issue by nestingLee** [springdoc/springdoc-openapi#433]
I try to use springdoc-openapi 
springboot: version 2.2.4.RELEASE
springdoc-openapi-ui: version 1.2.30
My BaseController uses generics, but@Parameter cannot resolve type T.code like this:
<pre>
@Data
@Schema(description = "user info")
public class User {
    private String id;
    private String name;
    private String pwd;
}
</pre>
<pre>
public interface BaseController<T> {
    @GetMapping("/list2")
    @Operation(summary = "list2", description = "test for generic ")
    default List<T> list2(@Parameter(name = "entity") T entity) {
        List<T> list = new ArrayList<>();
        list.add(entity);
        return list;
    }
}
</pre>

<pre>
@RestController
@Tag(name = "user", description = "test springdoc-openapi")
public class UserController implements BaseController<User> {
    @GetMapping("/list1")
    @Operation(summary = "list1", description = "test for class")
    public List<User> list1(User entity) {
        List<User> list = new ArrayList<>();
        list.add(entity);
        return list;
    }
}
</pre>

swagger-ui :
/list1 Parameters:
<pre>
`{
  "id": "string",
  "name": "string",
  "pwd": "string"
}
</pre>
/list2 Parameters:
<pre>
{}
</pre>

springfox's@Apiparam is OK. like this：
<pre>
@ApiOperation(value = "create", notes = "create entity")
    public T save(@Validated @RequestBody @ApiParam(value = "entity", required = true) T entity) {
        return baseService.save(entity);
    }
</pre>
What should I do？

**Comment by bnasslahsen** [comment]
The code of your base controller you are providing does not compile.
Note, that T should be mapped to an object.

This issue will be closed. There is no need to create a new issue.
You can add comments here, if you have additional information to provide.

**Comment by nestingLee** [comment]
Hi @bnasslahsen  
The code shows problem，I re-edit the issue.

**Comment by bnasslahsen** [comment]
With you provided code, you can look at the openapi description that is generated.

[openapi.txt](https://github.com/springdoc/springdoc-openapi/files/4209863/openapi.txt)

If you are not having the same result, please add the link to your code to reproduce the issue.
