### ISSUE TITLE
Type information is lost on wildcard generic operation parameters or return types

### ISSUE THREAD

**Issue by robfletcher** [springdoc/springdoc-openapi#434]
If a controller operation has a parameter or return type with a wildcard generic type, the type information is lost and any customizers will see the generically typed property of the class as just an `Object` rather than the upper bound of the type parameter.

This is fairly complex so I've created an example on a fork of the project: https://github.com/robfletcher/springdoc-openapi/commit/6f212b22caecdfb1d6d5e3a048a86384108166f5

When considering the parameter and response types of the controller method here: https://github.com/robfletcher/springdoc-openapi/commit/6f212b22caecdfb1d6d5e3a048a86384108166f5#diff-3cea84ffe0d7e0808cc1ed9cd9c1fe9aR16-R18

With the wildcard the schemas in the API treat the `PetRecord.pet` property as just an `object`. If I change the generic declarations on the controller to `PetRecord<? extends Pet>` then it works correctly. However, this shouldn't be necessary since that is just re-declaring the same variance as on the `PetRecord` class. Removing the generic type altogether also works (with a compiler warning). I originally  ran into this problem in a Kotlin codebase where omitting the generic type is not possible.

**Comment by bnasslahsen** [comment]
Hi @robfletcher, 

 As you know we rely on swagger-core official libraries.
 The behaviour that you are describing is related to swagger-core.
https://github.com/OAI/OpenAPI-Specification/issues/957
 
 You can use the attached ModelConverter which should help you achieve your goal.
 Let me know if that helps, so we can plan to integrate it in future releases.

**Comment by robfletcher** [comment]
Thanks, that does help. 

I might amend it slightly as in my case it would make sense to always resolve using the raw type even when a bound _is_ specified, but that may be specific to my use case.

**Comment by sivakuna-aap** [comment]
@robfletcher can you please share the implementation? I could not find it in your repo.

**Comment by iliecirciumaru** [comment]
Interesting that for me it was not working for a while, then started to work and after I upgraded to OpenAPI from Swagger 2, again not working. Do you have any receipts how to make things to work ?

**Comment by bnasslahsen** [comment]
off topic, root cause not related to springdoc-openapi.
