### ISSUE TITLE
Overriding descriptions via properties

### ISSUE THREAD

**Issue by arthurlima96** [springdoc/springdoc-openapi#439]
**Describe the bug**
- An old version with springfox has support for descriptions about an external configuration file, when there was this change, there was a loss of that support.

**To Reproduce**
In the link below there is a demonstration of support:
- https://github.com/springfox/springfox/blob/master/docs/asciidoc/current-documentation.adoc#property-file-lookup

**Comment by bnasslahsen** [comment]
@arthurlima96, 

 This is not a bug. 
 FYI, you can add description via spring properties/yml files. This will be added to the FAQ.
 Here is a sample test, that shows how to use external description:
 - https://github.com/springdoc/springdoc-openapi/blob/master/springdoc-openapi-webmvc-core/src/test/java/test/org/springdoc/api/app15/SpringDocApp15Test.java

 If you have any feature request on the springdoc-openapi project, you need to be more explicit.
 Please make sure you have read our contribution guide:
https://github.com/springdoc/springdoc-openapi/blob/master/CONTRIBUTING.adoc
