### ISSUE TITLE
When using RestControllerAdvice, one of the responses is missing and replaced with a default

### ISSUE THREAD

**Issue by edgeofoblivion** [springdoc/springdoc-openapi#440]
**Describe the bug**
Empty default response is displayed instead of one described in exception handler.
```groovy
implementation 'org.springdoc:springdoc-openapi-ui:1.2.30'
```

**To Reproduce**
[demo.zip](https://github.com/springdoc/springdoc-openapi/files/4214923/demo.zip)
See the attached spring boot example with a single controller and a RestControllerAdvice having 2 exception handling methods.
One of the methods from the RestControllerAdvice is displayed with MediaType all and the "default response" description.

**Expected behavior**
Each of the handled responses displayed as described in the annotations in the Advice along with that from the GreetingController

**Screenshots**
![ControllerAdvice](https://user-images.githubusercontent.com/1918509/74671939-1c546200-51a4-11ea-80fa-8320a916a2b6.png)

**Additional context**
I also believe that one of those responses described in the controller advice will be replaced with the default (not always the same method). This can be seen when restarting the application and is particularly noticeable when many handler methods exist in the same class.
See screenshot following a restart - this time the 400 is incorrect and the 500 is as expected
![ControllerAdvice2](https://user-images.githubusercontent.com/1918509/74673861-0779cd80-51a8-11ea-871b-7c16228a1266.png)

**Comment by bnasslahsen** [comment]
Fix will be available on v1.2.31

**Comment by edgeofoblivion** [comment]
Confirmed this is resolved in 1.2.31, thanks so much.
