### ISSUE TITLE
ControllerAdvice content type defaults to */*

### ISSUE THREAD

**Issue by bfs-natewallman** [springdoc/springdoc-openapi#442]
When building a class annotated with '@ControllerAdvice' to handle exception conversion to JSON the default content type is '*/*' which is not ideal.  At the very least we should be able to override this at the class level with an annotation that overrides the behavior.

- What version of spring-boot you are using?
   2.2.2.RELEASE

- What modules and versions of springdoc-openapi are you using?  
   name: 'springdoc-openapi-ui', version: '1.2.31'
  name: 'springdoc-openapi-security', version: '1.2.31'
  
- What is the actual and the expected result using OpenAPI Description (yml or json)?
   Actual something like: "content":{"*/*"..."
   Expected something like: "content":{"application/json"..." 

I have actually found a work to annotate your methods with:

` @ResponseStatus(HttpStatus.INTERNAL_SERVER_ERROR)
  @ExceptionHandler(value = Exception.class)
  @RequestMapping(method = { GET, POST, PUT, DELETE, PATCH }, produces = MediaType.APPLICATION_JSON_VALUE)
  public ResponseEntity<ExceptionReportViewModel> handleException(HttpServletRequest req, Exception e) {
    return ResponseEntity.status(HttpStatus.INTERNAL_SERVER_ERROR).body(response);
  }`

I don't like having to apply all the methods to the RequestMapping annotation as that's not recommended.  I would like to be able to apply a RequestMapping at the class level and have that be used like such:

`@ControllerAdvice
@RequestMapping(produces = MediaType.APPLICATION_JSON_VALUE)
public class UseJsonExceptionResponseControllerAdvice {`

This doesn't work unfortunately. Is there another way this should be done or is this an enhancement to be made?

**Comment by bnasslahsen** [comment]
@bfs-natewallman, 

 With v1.2.32, you will be able to override the default produces mediaType:
 You can use the following property:

```properties
springdoc.default-produces-media-type=application/json
```

**Comment by bfs-natewallman** [comment]
@bnasslahsen Two questions regarding this fix:
1.) I think an improvement to this fix is to actually honor the `@RequestMapping` annotation if one is applied. This gives greater flexability.
2.) In the absense of #1, how can I configure those properties in code as opposed to via a properties file?

**Comment by bnasslahsen** [comment]
For 1), its already based on @RequestMapping annotation. But if you have better improvements, you can propose a PR.

For 2), you have access to SpringDocConfigProperties Bean, so you can have full control:

```java
@Bean
public BeanFactoryPostProcessor beanFactoryPostProcessor1(SpringDocConfigProperties springDocConfigProperties) {
	return beanFactory -> springDocConfigProperties.setDefaultProducesMediaType(MediaType.APPLICATION_JSON_VALUE);
}
```

**Comment by swarup-bhol** [comment]
Cannot solve the exception  for **with preset Content-Type 'video/mp4'** .While playing video

**Comment by bnasslahsen** [comment]
@swarup-bhol, 

 If you are reporting a bug, please help to speed up problem diagnosis by providing as
much information as possible:

 - You need to describe your context (the title of an issue is not enough)
 - What version of spring-boot you are using?
 - What modules and versions of springdoc-openapi are you using? 
 - What are the actual and the expected result using OpenAPI Description (yml or json)?
 - **Provide with a sample code (HelloController) or Test that reproduces the problem**

Please make sure you have read the section **Using GitHub Issues** in the [contribution guide.](https://github.com/springdoc/springdoc-openapi/blob/master/CONTRIBUTING.adoc)

**Comment by swarup-bhol** [comment]
Please have a look at this link that I was posted
[https://stackoverflow.com/questions/62976660/how-to-resolve-client-abort-exception-throwing-exception-with-preset-content-t](URL)

I will share the details soon

**Comment by bnasslahsen** [comment]
Your link is not working.
You either need to choose a communication channel. Our team is following both...
