### ISSUE TITLE
Support for non-nullable types in Kotlin

### ISSUE THREAD

**Issue by frank-van-eerden** [springdoc/springdoc-openapi#443]
NB: This is a more specific continuation of [issue #269](https://github.com/springdoc/springdoc-openapi/issues/269)

When generating apidocs from Kotlin data classes the non-nullable fields are not listed as required.
```
data class Person(
    val name: String
    val nickname: String?
)
```
The name property should be in the required list:
```
"Person": {
        "required": [
          "name"
        ],
...
```

There are workarounds like annotating the non-nullable properties with javax.validation.NotNull, but that is too verbose to my taste.

**Comment by bnasslahsen** [comment]
Hi @frank-van-eerden, 

 The support for non-nullable types in Kotlin will be available on v1.2.32.

**Comment by fveerden** [comment]
Hi @bnasslahsen ,

It seems to work for function parameters, but not on the response data classes in the components.schemas section of the openapi document.
Can you reopen the issue?

Kind regards, Frank.

**Comment by chrisatrotter** [comment]
I noticed that if a class is wrapped within an EntityModel, then it is not able to show non-nullable fields as required. This might be related to #453 .

**Comment by lsuski** [comment]
It seems that it does not work for request body parameters and responses wrapped with ResponseEntity

**Comment by lsuski** [comment]
It also does not work for fields with complex types (e.g. another data class)

**Comment by JavierSegoviaCordoba** [comment]
@bnasslahsen `implementation("org.springdoc:springdoc-openapi-ui:1.5.0")` should add automatically support for Kotlin non-nullable types out of the box?

I have:

```
@RestController
class DemoController {

    @GetMapping("/demo")
    fun demo(): Demo = Demo("Hello there")
}

data class Demo(val name: String)
```

But it is not working, all fields are marked as not required.

![image](https://user-images.githubusercontent.com/7463564/100891642-c6924180-34b9-11eb-9bca-8b8321bb1076.png)


I have to add `@field:Schema(required = true)` to get it working, but it adds a lot of boilerplate.

**Comment by cwboden** [comment]
For anyone still curious, I was able to solve this by adding `springboot-openapi-kotlin` to my `pom.xml`.
