### ISSUE TITLE
Payload/Request Examples no longer generated

### ISSUE THREAD

**Issue by bfs-natewallman** [springdoc/springdoc-openapi#444]
When upgrading from 1.2.28 to 1.2.31 I noticed the Example Payloads stopped being generated.

Here is psuedo code of an interface I've defined that documents an endpoint that works perfectly fine in 1.2.28 but fails in 1.2.31:

`@Tag(name = "Examples", description = "Endpoints supporting creating and managing Items")
public interface CreateItemSwaggerDefinition {

  @Operation(
      description = "Creates a item")
  @RequestBody(
      description = "Details of the Item to be created",
      required = true,
      content = @Content(
          schema = @Schema(implementation = ViewModel.class),
          mediaType = MediaType.APPLICATION_JSON_VALUE,
          examples = {
              @ExampleObject(
                  name = "An example request with the minimum required fields to create.",
                  value = Examples.MINIMUM,
                  summary = "Minimal request"),
              @ExampleObject(
                  name = "An example request with all fields provided with example values.",
                  value = Examples.FULL,
                  summary = "Full request") }))
  ResponseEntity<ViewModel> create(ViewModel viewModel);
}
`

**Comment by bnasslahsen** [comment]
Hi @bfs-natewallman, 

 Thank you for your feedback.
 A fix for this issue, will be available on v1.2.32.
