### ISSUE TITLE
[Feature] Deterministic order in the generated swagger output

### ISSUE THREAD

**Issue by dominic-jones** [springdoc/springdoc-openapi#445]
**Is your feature request related to a problem? Please describe.**
Understanding the exact change that OAS annotations have on the swagger output is not always easy. It is useful, as we did with Springfox, to generate the swagger and check-in the generated output. This allows developers reviewing PRs to understand the full implications of api / annotation changes.
However, unlike Springfox, the output of Springdoc is non-deterministic. The order of items on the generated output varies between different executions.

**Describe the solution you'd like**
A deterministic, predictable order of the generated operations, schemas, parameters.

**Describe alternatives you've considered**
I believe Springfox used parts of Jackson's model to order the output. e.g. the @JsonPropertyOrder annotation was respected. That's beyond my usecase. I don't need to control the output. I just want each run to order things the same way.

**Comment by bnasslahsen** [comment]
Hi @dominic-jones, 

 If you are having any issues related to order, you can submit examples of the issues you are facing and we will have a look at them. 
 Also, please have a look at the project tests: Each run order things the same way.

If you are reporting a bug, please help to speed up problem diagnosis by providing as much information as possible:

- You need to describe your context (the title of an issue is not enough)
- What version of spring-boot you are using?
- What modules and versions of springdoc-openapi are you using?
- What are the actual and the expected result using OpenAPI Description (yml or json)?
- Provide with a sample code (HelloController) or Test that reproduces the problem

**Comment by rcomblen** [comment]
For those landing here by Google, the order of the properties can now be alphabetical, as of release 1.5.0, using the following configuration property: 

    springdoc:
      writer-with-order-by-keys: true

**Comment by wallind** [comment]
> For those landing here by Google, the order of the properties can now be alphabetical, as of release 1.5.0, using the following configuration property:

@rcomblen still saving lives in 2023. This solution is still relevant^.
