### ISSUE TITLE
Hateoas CollectionModel - Do we follow HAL or OpenAPI 3.0 specification?

### ISSUE THREAD

**Issue by chrisatrotter** [springdoc/springdoc-openapi#446]
When creating a Hateoas CollectionModel with springdoc-openapi, then the naming "content" and "links" is given within the Schema as specified by OpenAPI 3.0. However, these names do not follow the convention of the HAL Specification which is "_embedded" and "_links".

**OpenAPI 3.0 Specification**
![image](https://user-images.githubusercontent.com/13899123/74843384-1c7f6980-532c-11ea-8a62-043905baecd6.png)

**HAL Specification**
![image](https://user-images.githubusercontent.com/13899123/74843456-391ba180-532c-11ea-912e-979a2ee9ad6a.png)

**Describe the solution you'd like**

It would be nice to change the OpenAPI 3.0 Specification of "content" and "links" to "_embedded" and "_links". It would be more natural to follow the HAL Specification as this is specific for Hateoas 1.0. Result shown below:

```json
"components":{
    "schemas": {
      "CollectionModel«EntityModel«RelatedCode»»":{ 
         "type":"object",
         "properties":{ 
            "_embedded":{ 
               ...
            },
            "_links":{ 
               ...
            }
         },
         "title":"CollectionModel«EntityModel«RelatedCode»»"
      }
   }
}
```
**Links to the specifications**
- OpenAPI 3.0 Specification: https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.2.md#response-object
- HAL Specification: https://tools.ietf.org/html/draft-kelly-json-hal-08#section-4.1

**Comment by bnasslahsen** [comment]
@chrisatrotter, 

 You can have a look at this issue:
 - https://github.com/springdoc/springdoc-openapi/issues/401

 It depends on your RepositoryRestConfiguration who can use or not Hal As  DefaultJsonMediaType.

**Comment by chrisatrotter** [comment]
@bnasslahsen, thank you for taking the time! It solved the issue! Keep up the great work!
