### ISSUE TITLE
Add Support for setting @Info fields, from properties/yml files

### ISSUE THREAD

**Issue by arthurlima96** [springdoc/springdoc-openapi#448]
**Describe the Feature**
- When replacing the description with a .properties value, the annotations do not set the correct value, the keys appear in place
- A clear and concise description of what the bug is: the keys appear in place of the value

**To Reproduce**
- I using spring-boot version 2 
- I using modules springdoc-openapi-core and springdoc-openapi-ui
-  The actual expected result using OpenAPI Description, is json
- Provide with a sample code (HelloController) or Test that reproduces the problem

**Expected behavior**
- The screenshot´s below describe what happening on my API.

**Screenshots**
![properties-open-api](https://user-images.githubusercontent.com/27455886/74858191-abd44f00-5323-11ea-8c43-1dbe93972ede.PNG)
swagger.properties
![open-api-config](https://user-images.githubusercontent.com/27455886/74858156-9d863300-5323-11ea-8555-b45109e760e8.PNG)
OpenAPI.java
![open-api-definition](https://user-images.githubusercontent.com/27455886/74858204-b1319980-5323-11ea-91f2-59346d8c5ea1.PNG)
swagger-ui.html

**Comment by bnasslahsen** [comment]
@arthurlima96 , 

 This is not a bug, but a new feature request. 
 You want to set the `@Info` fields, from properties/yml files.  

 Note that the support will not be added to all the parameters of OpenAPI, But only to @Info fields you have described, as the performance impact is not yet evaluated.
