### ISSUE TITLE
Documents get generated from annotations instead of the api.json

### ISSUE THREAD

**Issue by oskarstucki** [springdoc/springdoc-openapi#45]
I have tried setting the 

springdoc.api-docs.path

to point to my OpenAPI.json which includes my API spec but the documents that get generated don't include descriptions nor base url from the spec. Are these not supported?

**Comment by springdoc** [comment]
Hi, 

 This variable, is related to the path of OpenAPI description in json and yaml format.
 By default, the OpenAPI description will be available at the following url for json format: 

- http://server:port/context-path/v3/api-docs
- server: The server name or IP
- port: The server port
- context-path: The context path of the application

 The library uses the  java (spring-boot) code to generate the OpenAPI Description, using swagger-annotations.

 If you already, have the API description, you should use swagger-ui features directly with the url variable to point at the path of your OpenAPI file.
