### ISSUE TITLE
webjars are not served from the expected url in webflux-ui with swagger-ui prefix path set

### ISSUE THREAD

**Issue by maartenh** [springdoc/springdoc-openapi#454]
**Describe the bug**
When I have a custom path `/documentation/swagger-ui.html` set for the webflux-ui version, this redirects to `/documentation/webjars/swagger-ui/index.html?configUrl=/documentation/v3/api-docs/swagger-config`
However, the webjars are not available on this url, leading to a 404 response.
The webjars are available on the alternative path `/webjars/swagger-ui/index.html?configUrl=/documentation/v3/api-docs/swagger-config`, ie without the `/documentation` prefix. That however foils my plan to have everything under the `/documentation` prefix for easier management of access permissions.

I tried also setting `springdoc.webjars.prefix: /documentation/webjars`, but that just compounded the issue by redirecting to `/documentation/documentation/webjars/swagger-ui/index.html` without changing the actual location the webjars were served from.

**To Reproduce**
- What version of spring-boot you are using? v2.2.4
- What modules and versions of springdoc-openapi are you using? springdoc-openapi-webflux-ui v1.2.32
```yaml
springdoc.api-docs.path: /documentation/v3/api-docs
springdoc.swagger-ui.path: /documentation/swagger-ui.html
```
- Access the path `/documentation/swagger-ui.html` from a web browser.
- Observe 404 error

**Expected behavior**
The swagger ui is shown when accessing `/documentation/swagger-ui.html`

**Comment by bnasslahsen** [comment]
Hi, 

 You can use the following configuration class.
 We will make this functionnality out of the box, for webflux from the next release: v1.2.33

```java
@Configuration
public class SwaggerConfig implements WebFluxConfigurer {

	@Override
	public void addResourceHandlers(ResourceHandlerRegistry registry) {
		registry.addResourceHandler("/documentation/webjars/**")
				.addResourceLocations("classpath:/META-INF/resources/webjars/")
				.resourceChain(false);
	}

}
```

**Comment by joaodias14** [comment]
Hi @bnasslahsen, with https://github.com/springdoc/springdoc-openapi/commit/6414fbe7b75ce48253194dd954b8d0c8aca34f47 there is no longer the need to use the configuration you mentioned in your previous comment right?

**Comment by bnasslahsen** [comment]
Hi @joaodias14, 

 Yes i confirm. It will be available on the next release.

**Comment by joaodias14** [comment]
Many thanks @bnasslahsen!

**Comment by kanai0618** [comment]
Hi @joaodias14 @bnasslahsen , i am using spring webflux, my swagger url doesnot work with this url : **http://localhost:8080/swagger-ui/index.html**  but works with **http://localhost:8080/webjars/swagger-ui/index.html**, why webjars needed in the URL ?
