### ISSUE TITLE
Make calculateSchema method public

### ISSUE THREAD

**Issue by cnusp** [springdoc/springdoc-openapi#455]
**Feature Description**
I use my custom implementation of the `OpenApiCustomiser` interface to complete the auto-generated Open API specification. I inject the `ResponseBuilder` object to calculate `Schema` instances that describe non-2xx response bodies. Since `ResponseBuilder`'s `calculateSchema` method is a private method, it can only be called through reflection.

**To Reproduce**
- Inject `ResponseBuilder` into a `@Component`
- Try to call `ResponseBuilder::calculateSchema(...)`
- Compiler error: `'calculateSchema(io.swagger.v3.oas.models.Components, java.lang.reflect.ParameterizedType, com.fasterxml.jackson.annotation.JsonView)' has private access in 'org.springdoc.core.AbstractResponseBuilder'`

**Expected behavior**
`ResponseBuilder::calculateSchema(...)` should be a public method.

One of the core functionalities of `ResponseBuilder` is providing schema calculation functionality. I see no other way of easily calculating the schema of an arbitrary type, thus `ResponseBuilder::calculateSchema(...)` should be public, not private.

**Comment by bnasslahsen** [comment]
@cnusp, 

 calculateSchema, is private, because its internally used by ResponseBuilder. 
 There was no reason to expose it.  You are asking for new feature...
 Plese, note that people can just use: `SpringDocAnnotationsUtils.extractSchema` or `AnnotationsUtils.resolveSchemaFromType `to resovle the Schema directly.

**Comment by cnusp** [comment]
Thank you. `SpringDocAnnotationsUtils.extractSchema` is providing the desired functionality.
