### ISSUE TITLE
$ref attributes needs to be url-encoded

### ISSUE THREAD

**Issue by timpamungkas** [springdoc/springdoc-openapi#456]
`$ref` attributes is not url encoded, so validating springdoc josn at [editor.swagger.io](http://editor.swagger.io/) gives error:

```
Semantic error at paths./ping.get.responses.500.content.*/*.schema.$ref
$ref values must be RFC3986-compliant percent-encoded URIs
Jump to line 46
Structural error at paths./ping.get.responses.503.content.*/*.schema.$ref
should match format "uri-reference"
format: uri-reference
Jump to line 52
```

The resulting openapi spec is

```
'500':
          description: default response
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Json base response.'
        '503':
          description: default response
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Json base response.'
  '/api/v1/lead/{bfi_lead_id}':
```

Notice the `$ref` attribute.Character space should be encoded as %20.
This is result from `@Schema` annotation as follows:  `@Schema(name = "Json base response.")`

**Comment by bnasslahsen** [comment]
Hi @timpamungkas, 

 Our library is built on top of swagger-core.
 The resolved schema is not done by springdoc-openapi.
 You can have a look at: ModelResolver.resolve in swagger-core, to see how schema is constructed.
 You can submit your request to swagger-core project:
- https://github.com/swagger-api/swagger-core/issues
