### ISSUE TITLE
AnnotationsUtils.resolveSchemaFromType does not accept ParameterizedType

### ISSUE THREAD

**Issue by cnusp** [springdoc/springdoc-openapi#458]
**Describe the bug**
`AnnotationsUtils.resolveSchemaFromType` cannot be called with a `ParameterizedType` instance though it is suggested as a replacement for private method `ResponseBuilder::calculateSchema(...)` in [issue 455](https://github.com/springdoc/springdoc-openapi/issues/455)

**To Reproduce**
- Pass `ParameterizedType` object as first parameter of `AnnotationsUtils.resolveSchemaFromType`.
- This leads to `Error java: incompatible types: java.lang.reflect.Type cannot be converted to java.lang.Class<?>`

**Expected behavior**
`ParameterizedType` instance can be passed to `AnnotationsUtils.resolveSchemaFromType`, as when calling `ResponseBuilder::calculateSchema(...)`.

**Comment by bnasslahsen** [comment]
Hi, 

 AnnotationsUtils class is related to swagger-core project, and not to springdoc-openapi.
 On the post you are mentionning, its indicated you can use SpringDocAnnotationsUtils.extractSchema  as well, which supports ParameterizedType.
 
 If you really want only AnnotationsUtils, you can submit your request to the github project of swagger-core instead:
- https://github.com/swagger-api/swagger-core/issues

**Comment by cnusp** [comment]
`SpringDocAnnotationsUtils` is not available outside its package because it is not declared `public`. Thus its methods cannot be called.

**Comment by bnasslahsen** [comment]
SpringDocAnnotationsUtils will be public for the next release: v1.2.33
