### ISSUE TITLE
HTTP status codes in responses not according to spec

### ISSUE THREAD

**Issue by ali-rantakari** [springdoc/springdoc-openapi#46]
Thanks for providing this library.

HTTP status codes in response objects include the name/description of the status, which is not allowed in the spec:

<https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md#responsesObject>

- Expected: `200`
  Actual: `200 OK`

- Expected: `500`
  Actual: `500 INTERNAL_SERVER_ERROR`

**Comment by springdoc** [comment]
Hi, 

 A fix will be available for this issue on v1.1.25 of springdoc-openapi.
