### ISSUE TITLE
415 Unsupported Media Type

### ISSUE THREAD

**Issue by nguyenxndaidev** [springdoc/springdoc-openapi#460]
**Describe the bug**
Execute all operations, get the same error message:
```
{
  "timestamp": "2020-02-27T22:00:18.456+0000",
  "status": 415,
  "error": "Unsupported Media Type",
  "message": "Content type '' not supported",
  "path": "/api/todos"
}
```

**To Reproduce**
- Spring boot 2.2.4.RELEASE
- Gradle (Kotlin DSL): `implementation("org.springdoc:springdoc-openapi-ui:1.2.32")`
- Kotlin JVM version 1.3.61
- Redhat OpenJDK 11.0.3
```
@RestController
@RequestMapping(
    path = ["/api/todos"],
    consumes = [MediaType.APPLICATION_JSON_VALUE],
    produces = [MediaType.APPLICATION_JSON_VALUE]
)
@Tag(name = "Todo", description = "Todo API")
class TodoRestController {
    @GetMapping
    fun getTodos(@RequestParam("id", required = false) ids: Array<Int>?): ResponseEntity<List<Todo>> {
        //...
    }
}
```

**Expected behavior**
`Content-Type` header should be the same as configured in `@RequestMapping(consumes = "...")`.

**Screenshots**
![image](https://user-images.githubusercontent.com/24372782/75491138-b93da900-59b5-11ea-94af-e0b68d51acbf.png)

![image](https://user-images.githubusercontent.com/24372782/75490964-695ee200-59b5-11ea-82af-569362a03ff4.png)

**Comment by nguyenxndaidev** [comment]
It seems that springfox-swagger2 also has the same problem.
https://github.com/springfox/springfox/issues/2036

**Comment by bnasslahsen** [comment]
@nguyenxndaidev, 

 This is related to OpenAPI Specification, even its allowed in spring.
 You can have a look at the following thread:
 - https://github.com/OAI/OpenAPI-Specification/issues/581
