### ISSUE TITLE
Cannot resolve property for @operation.summary or @parameter.name

### ISSUE THREAD

**Issue by tdevilleduc** [springdoc/springdoc-openapi#463]
**Describe the bug**
I'm currently working to migrate from Springfox to Springdoc and i'm facing some trouble with property resolver

	@Operation(
        summary = "${swagger.controller.channel-rest-controller.findChannelById.value}",
        description = "${swagger.controller.channel-rest-controller.findChannelById.notes}")

Description is resolved but summary is not
I found in base code that line :
https://github.com/springdoc/springdoc-openapi/blob/c56751eb113d175bf1f539dd5e5912548bc261c6/springdoc-openapi-common/src/main/java/org/springdoc/core/OperationBuilder.java#L79

```
		if (StringUtils.isNotBlank(apiOperation.summary())) {
			operation.setSummary(apiOperation.summary());
		}
		if (StringUtils.isNotBlank(apiOperation.description())) {
			operation.setDescription(propertyResolverUtils.resolve(apiOperation.description()));
		}
```

Description is using propertyResolverUtils but not summary

**To Reproduce**
- spring-boot.version: 2.2.4.RELEASE
-  I'm using only springdoc-openapi-ui 

**Expected behavior**
I'm expecting to have my property value used as @Operation summary

**Additional context**
I'm facing the problem for other annotations and attributes :
- @parameter.description
- @parameter.name

**Comment by bnasslahsen** [comment]
Fixed by #464
