### ISSUE TITLE
Cannot use ::class.java for @Schema(implementation)

### ISSUE THREAD

**Issue by nguyenxndaidev** [springdoc/springdoc-openapi#465]
**Describe the bug**
I cannot set `implementation` for `@Schema` because of the compile error on Answer::class.java: An annotation argument must be a compile-time constant

**To Reproduce**
- Spring Boot 2.2.4.RELEASE
- org.springdoc:springdoc-openapi-ui:1.2.32
- Kotlin JVM 1.3.61

```
class AnswersRestController {
    @ApiResponses(
        // Compile error on Answer::class.java: An annotation argument must be a compile-time constant
        ApiResponse(content = [Content(schema = Schema(implementation = Answer::class.java))])
    )
}
```

Am I doing wrong? How could I define schema for response?

**Comment by bnasslahsen** [comment]
Hi @nguyenxndaidev, 

 Implemntation should be a class type:

```kotlin
class AnswersRestController {
    @ApiResponses(
        // Compile error on Answer::class.java: An annotation argument must be a compile-time constant
        ApiResponse(content = [Content(schema = Schema(implementation = Answer::class))])
    )
}
```

 You can have a look at @Schema documentation:
- https://github.com/swagger-api/swagger-core/wiki/Swagger-2.X---Annotations#schema

Please before opening any  issue/feature request on the springdoc-openapi project, make sure you have read our contribution guide:
- https://github.com/springdoc/springdoc-openapi/blob/master/CONTRIBUTING.adoc
