### ISSUE TITLE
Sorting/Ordering on method (POST, GET, UPDATE, DELETE)

### ISSUE THREAD

**Issue by YunaBraska** [springdoc/springdoc-openapi#467]
**Describe the bug**
I want to sort the endpoints/Method by methods. While having groups and tags. 

**Steps to reproduce**
I used Endpoints with tags.
I have grouped API endpoints like these:

```
@Bean
    public GroupedOpenApi internalApi() {
        return GroupedOpenApi.builder()
                .setGroup("internal")
                .packagesToScan(CatalogController.class.getPackageName())
                .build();
    }
```
And I used the OpenApiCustomiser like this:
```
@Bean
    public OpenApiCustomiser sort() {
        //WE DON'T UNDERSTAND WHERE 'openApi' IS COMMNG FROM - not debugable....
        return openApi -> openApi.setPaths(
                (Paths) openApi.getPaths().entrySet()
                        .stream()
                        .sorted(Comparator.comparingInt(pathItem -> {
                            if (pathItem.getValue().getGet() != null) {
                                return 1;
                            }
                            return 0;
                        }))
                        .collect(toMap(Map.Entry::getKey, Map.Entry::getValue, (x, y) -> y, LinkedHashMap::new))
        );
    }
```

**Expected behavior**
Sorting should be debugable and working.

**Additional context**
Would be nice to add these sorting like by Tag/Method,... to the already existing properties next to alphabetic sorting.
Also would be great to solve ordering with an annotation....

**Comment by tdevilleduc** [comment]
As I see it, `getPaths()` create a Set from `Map<String, Object> restControllers`
So it doesn't matter how you sort the map, there is no guarantee this order will be kept

I found many issues here about sorting things, and it seems it's not going to append (unfortunatly)

**Comment by bnasslahsen** [comment]
@YunaBraska, 

 Have you looked at the documentation?
- https://springdoc.github.io/springdoc-openapi-demos/springdoc-properties.html#swagger-ui-properties

You can use the swagger-ui properties (operationsSorter and tagsSorter). 

For example:

```properties
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha
```

**Comment by YunaBraska** [comment]
@bnasslahsen thank you! that's helpful but it works only on the UI not on the generated swagger json. can you please help me out with that?

**Comment by YunaBraska** [comment]
@tdevilleduc @bnasslahsen 
As I understand the implementation right, `Fasterxml` is generating the `OpenApi` object without any additional logic.
So I solved the issue by overwriting the `io.swagger.v3.oas.models.PathItem` and adding @JsonPropertyOrder({"post", "get","put", "patch", "delete", "head", "options", "trace"})
Would be nice to find a way for a dynamic config

**Comment by amalic** [comment]
> As I see it, `getPaths()` create a Set from `Map<String, Object> restControllers`
> So it doesn't matter how you sort the map, there is no guarantee this order will be kept
> 
> I found many issues here about sorting things, and it seems it's not going to append (unfortunatly)

An example would be great!
