### ISSUE TITLE
Descriptions in classes won't get included

### ISSUE THREAD

**Issue by oskarstucki** [springdoc/springdoc-openapi#47]
In my api I have defined for example 

```
@ApiOperation(value = "Build Version of the API.", nickname = "getBuildId", notes = "Returns the build version of the product recommendation api.", response = BuildVersion.class, tags = {})
```

However the notes get lost. Same applies to

```
@ApiParam(value = "Some description")
```

**Comment by springdoc** [comment]
Hi, 

 You are not using the right annotations.  Use @Operation and @Parameter instead.
 You can look at the demos, for more details;
- https://github.com/springdoc/springdoc-openapi-demos.git
