### ISSUE TITLE
Support GraphQL

### ISSUE THREAD

**Issue by Marx2** [springdoc/springdoc-openapi#470]
**Is your feature request related to a problem? Please describe.**
Better support for GraphQL

- A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
Current UI is not very convenient to use with GraphQL. There're separate UIs like GraphiQL or GraphQL playground, but they're not integrated with this project and they doesn't support security like OAuth 

- What is the actual result using OpenAPI Description (yml or json)?
You can use it but it's not convenient

**Describe the solution you'd like**
- Optionally integrate other UI like GraphiQL or GraphQL or sth else
- It would allow easy testing like with plain REST endpoints

**Describe alternatives you've considered**
- I can use other UIs, so it's not critical feature.

**Comment by bnasslahsen** [comment]
GraphQL is not supported by the OpenAPI Specification and by swagger-core. 
When the spec and swagger-core supports it, so will we.
