### ISSUE TITLE
Wrong redirection behind reverse proxy

### ISSUE THREAD

**Issue by aoudiamoncef** [springdoc/springdoc-openapi#471]
Hi @bnasslahsen,

We are using reverse proxy which add a namespace to api url like this: 

`my.server.et/swagger/my-api/swagger` redirect to -> `my.server.et/swagger-ui/index.html?configUrl=api/v1/api-docs/swagger-config` instead of `my.server.et/my-api/swagger-ui/index.html?configUrl=api/v1/api-docs/swagger-config`

I haven't this issue with SpringFox, so i think that's possible to implement it. 

Thanks

**Comment by bnasslahsen** [comment]
Hi @aoudiamoncef ,

  We invite you to review your configuration according to the properties in the FAQ, and using ForwardedHeaderFilter Bean.
- https://springdoc.github.io/springdoc-openapi-demos/faq.html#how-can-i-deploy-the-doploy-springdoc-openapi-ui-behind-a-reverse-proxy

 For example,  if you are using Spring Boot to 2.2.2.RELEASE, you should set `server.forward-headers-strategy: framework`
 Make sure you are using the last stable version: v1.2.33

 Make sure the right headers are sent by your proxy (x-forwarded-prefix and others) are sent by your proxy.
 
 Make sure also, your proxy is forwarding the right headers: X-Forwarded-For and X-Forwarded-Prefix, or any equivalent depending on the solution you are using.
 Example here  #397, #391.


 Anyway, if you are reporting a bug, please help to speed up problem diagnosis by providing as much information as possible:

- You need to describe your context (the title of an issue is not enough)
- What version of spring-boot you are using?
- What modules and versions of springdoc-openapi are you using?
- What are the actual and the expected result using OpenAPI Description (yml or json)?
- Provide with a sample code (HelloController) or Test that reproduces the problem
