### ISSUE TITLE
Multiple API Responses with the same code

### ISSUE THREAD

**Issue by Tienisto** [springdoc/springdoc-openapi#474]
**Is your feature request related to a problem? Please describe.**
I have a /dashboard route, depending on the role of the requesting user (e.g. admin, user, guest) the route responses differentely. Currently it seems that only one of the two are used for the documentation.

**Describe the solution you'd like**

in Kotlin:
```kotlin
@ApiResponses(
            ApiResponse(responseCode = "200", description = "for admins", content = [Content(schema = Schema(implementation = AdminResponse::class))]),
            ApiResponse(responseCode = "200", description = "for users", content = [Content(schema = Schema(implementation = UserResponse::class))])
    )
```

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by bnasslahsen** [comment]
You can have a look at OpenAPI 3 documentation:
- https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.3.md
 
For example you can use **oneOf** on your schema definition.
