### ISSUE TITLE
Hidden model properties when using jsonProperty not working

### ISSUE THREAD

**Issue by anderdev** [springdoc/springdoc-openapi#476]
Hi Guys,

So, I am working on a Spring Boot 2(2.2.4 release) rest API which we use springdoc v1.2.33 to generate our swagger definition.

Our API is responsible to create several types of documents, which we use only one endpoint for POST documents /api/documents which receives a generic object with common attributes between the documents.

So, I am trying to provide a better description of the POST documents, using oneOf and it works like charm, 

` @Schema(
        description = "Generic Document, check the oneOf node in the end of this generic document to get the correct document schema.",
        oneOf = {
                PurchaseOrderSchema.class,
                PurchaseOrderSchema.class,
                CommercialInvoiceSchema.class,
                ShipperLetterInstructionsSchema.class,
                AirwayBillSchema.class,
                ProformaInvoiceSchema.class
        }
)`

trying to hide the elements from this generic document I noticed that @Schema(hidden = true) works fine if the model property does not have @JsonProperty("some_name") for the snake case.

note that the image below reference has been annotated with @JsonProperty("reference") and @Schema(hidden = true) whcih makes it move to the top of the document and did not hide it.

![Screen Shot 2020-03-06 at 4 00 48 PM](https://user-images.githubusercontent.com/4452071/76046066-c2d19d00-5fc3-11ea-99e0-71d7034ad2d1.png)

<img width="1035" alt="Screen Shot 2020-03-06 at 6 30 59 PM" src="https://user-images.githubusercontent.com/4452071/76055575-ece18a00-5fd8-11ea-8ead-714111e2728e.png">

Am I doing something wrong or it is a real bug?

thanks in advance,'
Anderson Santos

**Comment by bnasslahsen** [comment]
Hi @anderdev, 

  You should replace the `@JsonProperty`  and `@Schema` by **`@JsonIgnore`**.
  Please note, that this behaviour is handled by swagger-core: ModelResolver.resolve and note springdoc-openapi.

**Comment by anderdev** [comment]
Hi @bnasslahsen I will try it ASAP, seems to me that doing that I will ignore the property organisation_to for instance, as the json object received uses snake case, is my assumption correct?

**Comment by anderdev** [comment]
yep, as per my assumption, @JsonIgnore won't work because the attribute is ignored as per the annotation.
