### ISSUE TITLE
Leading and trailing double quotes removed from example strings

### ISSUE THREAD

**Issue by jmoraleda** [springdoc/springdoc-openapi#478]
Example Swagger/OpenAPI definition:
```java
@Parameter(description="Optional json string that value associated with key must contain",
           example="\"text/x-python\"" )
@RequestParam(required=false) String value,
```
shows as 

![image](https://user-images.githubusercontent.com/23492126/75958602-72e2c100-5e71-11ea-9389-0ad1a4bc4098.png)

**I expect to see `"text/x-python"` as sample value instead of `text/x-python`.** 

To get the expected result, `"text/x-python"`, I need to write:

```java
@Parameter(description="Optional json string that value associated with key must contain",
           example="\"\\\"text/x-python\\\"\"" )
@RequestParam(required=false) String value,
```
![image](https://user-images.githubusercontent.com/23492126/76042606-197aa080-5f0a-11ea-8543-07fb3c3f786f.png)

I believe the issue may be in the block of code starting in line 145 onward of https://github.com/springdoc/springdoc-openapi/blob/master/springdoc-openapi-common/src/main/java/org/springdoc/core/GenericParameterBuilder.java
``` 
if (StringUtils.isNotBlank(parameterDoc.example())) {
	try {
		parameter.setExample(Json.mapper().readTree(parameterDoc.example()));
	}
	catch (IOException e) {
		parameter.setExample(parameterDoc.example());
	}
}
```
This code tries to parse the example string as json instead of simply setting it verbatim, which only happens if the conversion fails, in the catch block. I don't understand why it tries to do the parsing instead of just setting the text as given in all cases, perhaps there are legitimate use cases, but if the schema has mimeType `text/plain` it definitely should not parse it as json.

The results above were produced using:
springdoc-openapi: 1.2.33
spring-boot: 2.1.1
I just migrated this bug report from https://github.com/swagger-api/swagger-ui/issues/5898 after identifying the problem belongs here instead.

**Comment by bnasslahsen** [comment]
@jmoraleda, 

 This is the expected behaviour. You should esapce when necessary.
 Our library relies on swagger-core, and the example if of type Object and not String on the io.swagger.v3.oas.models.parameters.Parameter side.

And from the OpenAPI Specification:

> Example of the media type. The example SHOULD match the specified schema and encoding properties if present. The example object is mutually exclusive of the examples object. Furthermore, if referencing a schema which contains an example, the example value SHALL override the example provided by the schema. To represent examples of media types that cannot naturally be represented in JSON or YAML, a string value can contain the example with **escaping** where necessary.
