### ISSUE TITLE
Schema `{one,any,all}Of` not working when applied to a model property

### ISSUE THREAD

**Issue by ali-rantakari** [springdoc/springdoc-openapi#48]
Thanks for providing this library.

The `{one,any,all}Of` options of the `io.swagger.v3.oas.annotations.media.Schema` annotation do not have the expected effect when applied to a model class property.

## Example

Given:

```java
public class MyModel {

    @Schema(
        description = "Hello",
        type = "object",
        oneOf = {
            Foo.class,
            Bar.class,
            Baz.class
        }
    )
    private Object thing;

    public void setThing(Object thing) {
        this.thing = thing;
    }

    public Object getThing() {
        return thing;
    }
}
```

Expected output:

      "MyModel": {
        "properties": {
          "thing": {
            "description": "Hello",
            "type": "object",
            "oneOf": [
              {
                "$ref": "#/components/schemas/Foo"
              },
              {
                "$ref": "#/components/schemas/Bar"
              },
              {
                "$ref": "#/components/schemas/Baz"
              }
            ]
          }
        },
        "type": "object"
      },

Actual output:

      "MyModel": {
        "properties": {
          "thing": {
            "description": "Hello",
            "type": "object"
          }
        },
        "type": "object"
      },

**Comment by springdoc** [comment]
Hi, 

 This is not an issue on springdoc-openapi. We rely on swagger-core official jars. 
 This feature is not yet supported on swagger-core side. 

 You can have a look at ModelResolver class for more details. The concerned method is resolveSchemaMembers.  
 This method doesn't handle the mapping of oneOf,anyOf, allOf on properties/attributes level.

 Swagger-core supports OneOf,anyOf, allOf on class level with @schema annotation.

 You can submit your request to the swagger-core team for this feature:

- https://github.com/swagger-api/swagger-core/issues
