### ISSUE TITLE
Incomplete instructions on FAQ

### ISSUE THREAD

**Issue by theoamonteiro** [springdoc/springdoc-openapi#480]
**Describe the bug**
I tried to follow the recommendations on  "[What is a proper way to set up Swagger UI to use provided spec.yml?](https://springdoc.github.io/springdoc-openapi-demos/faq.html#what-is-a-proper-way-to-set-up-swagger-ui-to-use-provided-specyml)". But my "APPLICATION FAILED TO START" because of a missing bean. The log recommended me to "defining a bean of type 'org.springdoc.core.SpringDocConfigProperties' in your configuration.".

**To Reproduce**
- spring-boot: 2.2.5.RELEASE
- org.springdoc:springdoc-openapi-ui:1.2.33

Follow the instructions on [FAQ](https://springdoc.github.io/springdoc-openapi-demos/faq.html#what-is-a-proper-way-to-set-up-swagger-ui-to-use-provided-specyml). The application is going to fail to start.

**Screenshots**
None

**Expected behavior**
The application  should start and use the provided specs

**Additional context**
To fix is easy enough following the recommendation spring boot printed on the logs and also provide a bean:

```java
@Bean
public SpringDocConfigProperties springDocConfigProperties() {
	return new SpringDocConfigProperties();
}
```
This should be on the [FAQ](https://springdoc.github.io/springdoc-openapi-demos/faq.html#what-is-a-proper-way-to-set-up-swagger-ui-to-use-provided-specyml).

**Comment by bnasslahsen** [comment]
@theoamonteiro, 

 In fact, you have found a regression. 
 The FAQ is correct and will be fixed for the next release: v1.2.34
