### ISSUE TITLE
Configuration via springdoc.swagger-ui.swaggerUrls doesn't work

### ISSUE THREAD

**Issue by theoamonteiro** [springdoc/springdoc-openapi#481]
**Describe the bug**
I was trying to use the **springdoc.swagger-ui.swaggerUrls[0].name** and **springdoc.swagger-ui.swaggerUrls[0].name** properties presented on the [documentation](https://springdoc.github.io/springdoc-openapi-demos/springdoc-properties.html#swagger-ui-properties) but they didn't work. 

**To Reproduce**
- spring-boot: 2.2.5.RELEASE
- org.springdoc:springdoc-openapi-ui:1.2.33

Using the properties

```
springdoc.swagger-ui.swaggerUrls[0].name=REST API
springdoc.swagger-ui.swaggerUrls[0].url=/v3/api-docs
```
has no effect and the "Explore"search bar is still shown.

**Expected behavior**
With a single **swaggerUrls** provided the top bar should show the "Select a definition" combo.

**Screenshots**
Expected: 
![Screenshot from 2020-03-08 16-25-44](https://user-images.githubusercontent.com/5973390/76169687-82a42300-6159-11ea-940b-24ed8393b4c8.png)

Actual:
![Screenshot from 2020-03-08 16-32-56](https://user-images.githubusercontent.com/5973390/76169801-8edcb000-615a-11ea-8e43-e6b424fdc901.png)

**Additional context**
The example on de [App 2](https://github.com/springdoc/springdoc-openapi-demos/blob/master/springdoc-openapi-test-app2/src/main/java/org/springdoc/demo/app2/Application.java) on the [demos](https://github.com/springdoc/springdoc-openapi-demos)  leads to the conclusion that the only way to achieve that is programmatically. If that is the case, do not keep the [properties](https://github.com/springdoc/springdoc-openapi/blob/master/springdoc-openapi-common/src/main/java/org/springdoc/core/SwaggerUiConfigProperties.java) or its [documentation](https://springdoc.github.io/springdoc-openapi-demos/springdoc-properties.html#swagger-ui-properties).

I would also like to question why it is **swaggerUrls** instead of **urls** like on the [Swagger UI documentation](https://swagger.io/docs/open-source-tools/swagger-ui/usage/configuration/).

**Comment by bnasslahsen** [comment]
@theoamonteiro, 

 This will be fixed for the next release v1.2.34.
 The following properties will be used instead:

```properties
springdoc.swagger-ui.urls[0].name = users
springdoc.swagger-ui.urls[0].url = /api-docs.yaml
```

**Comment by javaHelper** [comment]
This is not working for me. I used below.
`
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.display-request-duration=true
springdoc.swagger-ui.tagsSorter=alpha
springdoc.swagger-ui.doc-expansion=no

springdoc.swagger-ui.urls[0].name = users
springdoc.swagger-ui.urls[0].url = /api-docs.yaml
`

**Comment by kishorsamadder** [comment]
How Can we customize implementation to read multiple springdoc.swagger-ui.urls[*]. urls from configuration. Same like we have in swaggerfox i.e. - 


@Primary
    @Bean
    public SwaggerResourcesProvider swaggerResourcesProvider(InMemorySwaggerResourcesProvider defaultResourcesProvider) {
        return () -> {
        	List<SwaggerResource> resources = new ArrayList<>();
            /*SwaggerResource wsResource = new SwaggerResource();
            wsResource.setName("TPS");
            wsResource.setSwaggerVersion("2.0");
            wsResource.setLocation("/swagger.json");*/
            
            /*SwaggerResource notificationResource = new SwaggerResource();
            notificationResource.setName("NOTIFICATION");
            notificationResource.setSwaggerVersion("2.0");
            notificationResource.setLocation("/notification-swagger.json");
            
            //resources.add(wsResource);
            tags.forEach(tag -> {
            	SwaggerResource resource = new SwaggerResource();
            	String tagName = tag.get("tagName");
                resource.setName(tagName);
                resource.setSwaggerVersion("2.0");
                resource.setLocation("/"+ tagName+".json");
                resources.add(resource);
            });
            resources.add(notificationResource);
            return resources;
        };
    }


I want the same impletation in springdoc/OpenApi?
