### ISSUE TITLE
missing OpenApiCustomiser in common jar for v 1.2.33

### ISSUE THREAD

**Issue by T0X1CCAT** [springdoc/springdoc-openapi#483]
**Describe the bug**
using springboot 2.2.5

**To Reproduce**
for version of springdoc 1.2.33 there is no OpenApiCustomiser class in the transitive dependency common jar. Where is it now located ?

**Comment by bnasslahsen** [comment]
look at: springdoc-openapi-common/src/main/java/org/springdoc/core/customizers/OpenApiCustomiser.java
