### ISSUE TITLE
@ControllerAdvice still corrupt the result schema class

### ISSUE THREAD

**Issue by bisegni** [springdoc/springdoc-openapi#485]
**Describe the bug**
I have a class as controller advice that permit to manage the api exception:

```java
@ControllerAdvice
public class RestExceptionHandler extends ResponseEntityExceptionHandler {
    private static final Logger log = LoggerFactory.getLogger(RestExceptionHandler.class);

    @ResponseStatus(value = HttpStatus.OK)
    @ExceptionHandler({ControllerLogicException.class})
    public ResponseEntity<ApiResultResponse<Object>> badRequest(HttpServletRequest req, Exception exception) {
        ApiResultResponse<Object> result = ((ControllerLogicException)exception).toApiResultResponse();
        log.error("{}-{}-{}",result.getErrorCode(), result.getErrorMessage(), result.getErrorDomain());
        return ResponseEntity.ok(result);
    }
}
```

**Expected behavior**
I have an api that return a class of type ApiResultResponse<String> and in documentation I want to get
```json
 {
  "errorCode": 0,
  "errorMessage": "string",
  "errorDomain": "string",
  "payload": "string"
}
```

**What I got**
but what I get is:
```json
{
  "errorCode": 0,
  "errorMessage": "string",
  "errorDomain": "string",
  "payload": {}
}
```
with complex generic I got always the same response type

**Comment by bnasslahsen** [comment]
@bisegni, 

 What is the structure of your ApiResultResponse?

**Comment by bisegni** [comment]
Hi, below the class:
```java
@JsonInclude(JsonInclude.Include.NON_NULL)
@JsonIgnoreProperties(ignoreUnknown = true)
public class  ApiResultResponse<T> {
    @Schema(description = "Is the error code returned from api", required = true)
    private int errorCode;
    @Schema(description = "In case of error not equal to 0, an error message can be reported by api, indicating what problem the problem")
    private String errorMessage;
    @Schema(description = "In case of error not equal to 0, an error domain can be reported by api, indicating where the problem is occured")
    private String errorDomain;
    @Schema(description = "Is the value returned by api")
    private T payload;

...all Getter and Setter
}
```

I use this to standardise the api answer.

**Comment by bnasslahsen** [comment]
payload is of type Object, so the reponse you are getting is correct.
If you want your payload to be returned of type string, you have to explicitly set it.
For example: 

```java
@Schema(description = "Is the value returned by api", type = "string")
private T payload;
```

**Comment by bisegni** [comment]
I can't do that because I have many version of class depending of what api return. Any way, why if I remove the class automatically all the documentation start to function. I obtain any variant of ApiResultResponse for example if I use `ApiResultResponse<String>` I got in documentation `ApiResultResponseString` and this is good.

Anyway I will remove the class and manage the error in other way.

thanks

**Comment by javaHelper** [comment]
Is there any way to set 'null' value to all string fields when doing HTTP POST request ? Its taking the 'string' as of now.
