### ISSUE TITLE
Wrong schema mapping with inheritance

### ISSUE THREAD

**Issue by rodrigoords** [springdoc/springdoc-openapi#489]
**Describe the bug**
 When project is using inheritance on controller with generic class, pringdoc-openpi can't map the child model correctly.

**To Reproduce**
Here is an example: [springdoc-openapi-inheritance](https://github.com/rodrigoords/examples/tree/master/springdoc-openapi-inheritance)

**Expected behavior**
 - All models mapped correctly with all child fields at the Schema sections on the web page.

**Additional context**

Related with: [https://github.com/springdoc/springdoc-openapi/issues/310](https://github.com/springdoc/springdoc-openapi/issues/310)

version: 
		
    <dependency>
        <groupId>org.springdoc</groupId>
        <artifactId>springdoc-openapi-ui</artifactId>
        <version>1.2.21</version>
    </dependency>
    
    <dependency>
        <groupId>org.springdoc</groupId>
        <artifactId>springdoc-openapi-security</artifactId>
        <version>1.2.21</version>
    </dependency>
    
    <dependency>
        <groupId>org.springdoc</groupId>
        <artifactId>springdoc-openapi-data-rest</artifactId>
        <version>1.2.21</version>
    </dependency>

**Comment by bnasslahsen** [comment]
@rodrigoords, 
 
 You can test with the next release v1.2.34.
 Some enhancements will be added to improve support of inheritance/generics.

**Comment by rodrigoords** [comment]
Checked with version 1.3.0 it's solved.

**Comment by bnasslahsen** [comment]
Thank you @rodrigoords for your feedback
