### ISSUE TITLE
Change heading's font in the document, please

### ISSUE THREAD

**Issue by onacit** [springdoc/springdoc-openapi#493]
Thank your for the efforts.

Whenever I try to read https://springdoc.github.io/springdoc-openapi-demos/.

As a non-English oriented, I really feel I'm having a difficulty for catching those headings.

Is that font the best one you could find? Thanks.

https://www.theverge.com/2012/7/4/3136652/cern-scientists-comic-sans-higgs-boson

**Comment by bnasslahsen** [comment]
@onacit, 

 The project uses github pages themes.
 Yes its the best we found.

 If you have a better proposal, you can propose a PR to the following project:
- https://github.com/springdoc/springdoc-openapi-demos

 If you have any other enhancements on the presentation, please raise them on the github project of the demos.

**Comment by bnasslahsen** [comment]
@onacit, 

 The theme has been changed. 
 If you have any other enhancements on the presentation, please don't hesitate to raise them or to contribute.

**Comment by onacit** [comment]
@bnasslahsen I've trying to contribute via forking and have been failing with jekyll stuff on my Windows machine.
New theme looks much better! Thank you.
