### ISSUE TITLE
Ignoring "is" prefix for attribute

### ISSUE THREAD

**Issue by Fredrik5** [springdoc/springdoc-openapi#495]
**Describe the bug**
In our case we use "is" prefix for boolean attributes. Simple example of request class:
`public class Foo{

private boolean isSelected;
private boolean isValid; 
}`

**To Reproduce**
In swagger definition - both json and yaml we can see
`Foo:
      type: object
         properties:
           selected:
             type: boolean
           valid:
             type: boolean`
We are using springdoc version 1.2.28 with spring boot 2.1.10.RELEASE version.

Is it really a bug or a feature? Is there any configuration to not ignore "is" prefix for those times of attributes?

Thank for any response,
Petr

**Comment by bnasslahsen** [comment]
Hi @Fredrik5, 

 It really depends on your jackson mapper settings.
 But you can force it to use it, by using 3 other different methods:

1. You use @JsonProperty annotation:
```java
public class Foo {

	@JsonProperty("selected")
	private boolean isSelected;

	@JsonProperty("valid")
	private boolean isValid;
	
}
```


2. You define the right getter:
```java
public class Foo {

	private boolean isSelected;
	private boolean isValid;

	public boolean isSelected() {

		return isSelected;
	}

	public boolean isValid() {
		return isValid;
	}

}
```
We invite you also to use the last stable version: v1.2.34.

If its not enough, you can attach the a sample code of your HelloController to reproduce or add the link to your github.
There is no need, to reopen new issue. You can add the sample in this one, and it will be reopened.
