### ISSUE TITLE
Add support for @Tags annotation

### ISSUE THREAD

**Issue by setarator** [springdoc/springdoc-openapi#496]
**Feature**
If I annotate the handler method with multiple `@Tag` annotations or aggregate them in `@Tags`, the builder will not read them (multiple `@Tag` after compilation will be aggregated in `@Tags`). I believe that the issue is in OpenAPIBuilder.buildTags method as it only tries to read Tag.class.

**To Reproduce**
- Annotate any handler method with multiple `@Tag` or use `@Tags`
We are using springdoc 1.2.33 & spring-boot 2.2.5.RELEASE

**Expected behavior**
Tags are read correctly.

Also would it be possible to have control over isAutoTagClasses? I would like to tag class automatically even when handler method tags are present.

Thanks,
Tom

**Comment by bnasslahsen** [comment]
@setarator, 

 The support of `@Tags` will be available for the next release: v1.2.35.
 `OpenAPIBuilder.splitCamelCase`, will be public.
 
 For your second request, you can use OperationCustomizer for that:

```java
@Component
public class OperationTagsCustomizer implements OperationCustomizer {
	@Override
	public Operation customize(Operation operation, HandlerMethod handlerMethod) {
		Set<String> tagsStr = new HashSet<>();
		tagsStr.add(OpenAPIBuilder.splitCamelCase(handlerMethod.getBeanType().getSimpleName()));
		if (!CollectionUtils.isEmpty(operation.getTags()))
			tagsStr.addAll(operation.getTags());
		operation.setTags(new ArrayList<>(tagsStr));
		return operation;
	}
}
```
