### ISSUE TITLE
Cannot build springdoc-openapi-rest-data

### ISSUE THREAD

**Issue by tdevilleduc** [springdoc/springdoc-openapi#497]
I forked springdoc project and try to build it
I had a issue with spring-openapi-rest-data

`
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project springdoc-openapi-data-rest: Compilation failure: Compilation failure:
[ERROR] /C:/Users/xkhs241/Documents/deux-repo/springdoc-openapi/springdoc-openapi-data-rest/src/main/java/org/springdoc/core/HalProvider.java:[21,24] cannot find symbol
[ERROR]   symbol:   class PostConstruct
[ERROR]   location: package javax.annotation
[ERROR] /C:/Users/xkhs241/Documents/deux-repo/springdoc-openapi/springdoc-openapi-data-rest/src/main/java/org/springdoc/core/HalProvider.java:[22,24] cannot find symbol
[ERROR]   symbol:   class PreDestroy
[ERROR]   location: package javax.annotation
[ERROR] /C:/Users/xkhs241/Documents/deux-repo/springdoc-openapi/springdoc-openapi-data-rest/src/main/java/org/springdoc/core/HalProvider.java:[39,10] cannot find symbol
[ERROR]   symbol:   class PostConstruct
[ERROR]   location: class org.springdoc.core.HalProvider
[ERROR] /C:/Users/xkhs241/Documents/deux-repo/springdoc-openapi/springdoc-openapi-data-rest/src/main/java/org/springdoc/core/HalProvider.java:[49,10] cannot find symbol
[ERROR]   symbol:   class PreDestroy
[ERROR]   location: class org.springdoc.core.HalProvider
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :springdoc-openapi-data-rest
`

On this file
https://github.com/springdoc/springdoc-openapi/blob/master/springdoc-openapi-data-rest/pom.xml

I would suggest to add 

`
<dependency>
			<groupId>jakarta.annotation</groupId>
			<artifactId>jakarta.annotation-api</artifactId>
		</dependency>
`

**Comment by tdevilleduc** [comment]
It seems it's specific to my environment : travis-ci is OK 
https://travis-ci.com/github/tdevilleduc/springdoc-openapi/builds/153897037

Do you have a clue ?

**Comment by bnasslahsen** [comment]
Maybe you are using java 11 to build ?

**Comment by tdevilleduc** [comment]
> Maybe you are using java 11 to build ?

Indeed.
After switching to java 8, it's ok
