### ISSUE TITLE
Support for runtime customization (e.g. post-processing) of generated spec

### ISSUE THREAD

**Issue by ali-rantakari** [springdoc/springdoc-openapi#50]
Thanks for providing this library.

It would be very useful to be able to customize the generated OpenAPI spec at runtime, e.g. generating response models dynamically.

For a more specific description of the kinds of hooks I refer to, please consider the `ReaderListener` and `SpecFilter` APIs described here: <https://github.com/swagger-api/swagger-core/wiki/Swagger-2.X---Extensions#configuration>

I see that #4 already implements support for preprocessing the definition but not for post-processing (or filtering/modification).

**Comment by springdoc** [comment]
Hi, 

If you need to achieve a post-processing customization of OpenAPI Object, you can simply extend AbstractOpenApiResource.
After the execution of getOpenApi method, you can add whatever customization you want.
More generally, you can override all the spring beans present on springdoc-openapi and add your customization.
