### ISSUE TITLE
Also ignore subtypes of configured classes to be ignored on Controllers

### ISSUE THREAD

**Issue by joaodias14** [springdoc/springdoc-openapi#502]
Currently, `org.springframework.security.core.Authentication` is configured to be ignored on Controllers and does not show up on Swagger.
The issue is that if one uses a custom class that implements this interface but also extends its functionalities, one needs to use this custom class as a parameter in a Controller's method. This custom class will not be ignored and will show up on Swagger.

Another possibility would be to simply use `@Parameter(hidden = true)` but this seems wrong.

**Comment by bnasslahsen** [comment]
Thank you @joaodias14 for your contribution.
Your enhancement, is now merged with master.

**Comment by joaodias14** [comment]
Thanks @bnasslahsen!
