### ISSUE TITLE
Response object with multiple subType always use first subType 

### ISSUE THREAD

**Issue by thrillstone** [springdoc/springdoc-openapi#504]
In my REST application, I have an `Envelope` object that wraps all REST responses. This object is implemented with a generic/subType that determines the type of a `data` variable. When using springdoc-openapi, even though there are many different classes used in the generic of the `Envelope`, it seems to create a schema for the first one and it uses that schema even where it's not applicable. I tried setting the subType property on the generic's schema definition, but that didn't help.

It's hard to explain so here's a sample class that can reproduce the issue. The following results in the `Response` object, which is the schema name fo the `Envelope` class, always having a subType of `User`; even for the `Pet` APIs.

```java
@SpringBootApplication
@RestController
public class SpringdocsEnvelopeApplication {

    public static void main(String[] args) {
        SpringApplication.run(SpringdocsEnvelopeApplication.class, args);
    }

    private Map<String, User> usersStore = new HashMap<>();
    private Map<String, Pet> petsStore = new HashMap<>();

    public SpringdocsEnvelopeApplication() {
        User user1 = new User("1", "John", "Doe");
        usersStore.put(user1.getId(), user1);
        User user2 = new User("2", "Jane", "Doe");
        usersStore.put(user2.getId(), user2);
        Pet pet1 = new Pet("1", "Snowball1");
        petsStore.put(pet1.getId(), pet1);
        Pet pet2 = new Pet("2", "Snowball2");
        petsStore.put(pet2.getId(), pet2);
    }

    @GetMapping("/users")
    public ResponseEntity<Envelope<Collection<User>>> getAllUsers() {
        Envelope<Collection<User>> users = new Envelope<>();
        users.setData(usersStore.values());
        return ResponseEntity.ok(users);
    }

    @GetMapping("/users/{id}")
    public ResponseEntity<Envelope<User>> getAllUsers(@PathVariable String id) {
        Envelope<User> user = new Envelope<>();
        user.setData(usersStore.get(id));
        return ResponseEntity.ok(user);
    }

    @GetMapping("/pets")
    public ResponseEntity<Envelope<Collection<Pet>>> getAllPets() {
        Envelope<Collection<Pet>> pets = new Envelope<>();
        pets.setData(petsStore.values());
        return ResponseEntity.ok(pets);
    }

    @GetMapping("/pets/{id}")
    public ResponseEntity<Envelope<Pet>> getAllPets(@PathVariable String id) {
        Envelope<Pet> pet = new Envelope<>();
        pet.setData(petsStore.get(id));
        return ResponseEntity.ok(pet);
    }

    @Schema(name = "Response")
    private static class Envelope<T> {
        private T data;
        private Map<String, Object> meta;

        public T getData() {
            return data;
        }

        public void setData(T data) {
            this.data = data;
        }

        public Map<String, Object> getMeta() {
            return meta;
        }

        public void setMeta(Map<String, Object> meta) {
            this.meta = meta;
        }
    }

    @Schema(name = "Pet")
    private static class Pet {
        private String id;
        private String name;

        public Pet(String id, String name) {
            this.id = id;
            this.name = name;
        }

        public String getId() {
            return id;
        }

        public void setId(String id) {
            this.id = id;
        }

        public String getName() {
            return name;
        }

        public void setName(String name) {
            this.name = name;
        }
    }

    @Schema(name = "User")
    private static class User {
        private String id;
        private String firstName;
        private String lastName;

        public User(String id, String firstName, String lastName) {
            this.id = id;
            this.firstName = firstName;
            this.lastName = lastName;
        }

        public String getId() {
            return id;
        }

        public void setId(String id) {
            this.id = id;
        }

        public String getFirstName() {
            return firstName;
        }

        public void setFirstName(String firstName) {
            this.firstName = firstName;
        }

        public String getLastName() {
            return lastName;
        }

        public void setLastName(String lastName) {
            this.lastName = lastName;
        }
    }

}
```

![image](https://user-images.githubusercontent.com/601527/77272919-b8342a80-6c88-11ea-893e-f514737a443c.png)

I believe this is a bug and there should be multiple `Envelope` schema objects created for each subType..

**Comment by bnasslahsen** [comment]
Hi @thrillstone, 

 The problem, you have specified a unique name for the schema of Envelope.
 Just remove the following annotation, and you will get the correct response:

```java
@Schema(name = "Response")
```

**Comment by thrillstone** [comment]
In my code base, I want a unique name for the schema though because my class is named using internal naming conventions that I don't want to be reflected in the Open API documentation. I still think this is a bug, but thank you for the workaround.

**Comment by thrillstone** [comment]
The workaround doesn't fix my issue because my schema names aren't as I'd like. In my real application, if I don't name the `Reponse` class with a Schema annotation, the name comes out as `ResponseApplication Domain`. The only way I could fix this was to create a class called `ApplicationDomainResponse` and give it a Schema annotation of `Application Domain Response` to get the naming the way I wanted. I could've live with `Response Application Domain` but without the whitespace between the first and second class names, it's just ugly. I ended up having to create dozens of these response objects in code to workaround this issue. I still think this is a bug worth addressing, @bnasslahsen.

**Comment by hsoftxl** [comment]
@bnasslahsen   I also think this is a bug

**Comment by bnasslahsen** [comment]
@hsoftxl, 
 
 Please read the [contribution guidelines](https://github.com/springdoc/springdoc-openapi/blob/master/CONTRIBUTING.adoc)
