### ISSUE TITLE
Webflux functional endpoints support

### ISSUE THREAD

**Issue by oxerek** [springdoc/springdoc-openapi#506]
All I found about handling functional endpoints in webflux is:

> Spring-weblfux with functional endpoints will be available in a future release.

from the last section of springdoc.org.
Can you say something more about the date of a release which will support functional endpoints?
I'm developing a Spring Cloud Gateway app on Netty without annotated controllers so it is quite important to me.

**Comment by bnasslahsen** [comment]
@oxerek,

As mentioned, there Spring-weblfux with functional endpoints are not yet supported.
For the moment, we are still focusing on the core functionality of the library.
You can also contribute to add the support. This might accelerate the release of this functionality.
