### ISSUE TITLE
Generation REST Implementation Stubs from OpenAPI 3

### ISSUE THREAD

**Issue by igbluz** [springdoc/springdoc-openapi#507]
First, I would like to congratulate you for this good and very useful project.

I would like to design a REST service based on an OpenAPI v3 and generate the corresponding artifacts (schema and API interfaces). Have you already thought about it? Is there a plan to provide such a generator? Maybe as part of the openapi-generator project? 

best regards,
Igor

**Comment by bnasslahsen** [comment]
Hi @igbluz, 

 This is not a functionnality of springdoc-openapi.
 As you mentionned, it should be part of  openapi-generator project.
 You can have a look at the project and submit any enhancements.
