### ISSUE TITLE
Support for Groovy metaclass/metadata 

### ISSUE THREAD

**Issue by felixsemmler** [springdoc/springdoc-openapi#509]
**Feature**
We use groovy in our Spring Boot microservice and tried to migrate from springfox/swagger to springdoc-openapi but ran into an issue. If the response of a RestController method is a groovy class, it breaks the whole swagger-ui. Swagger generates multiple schemas from the groovy metadata, which are also nested multiple times. This ended up that swagger-ui is not useable anymore and the browser requires a lot of memory and the browser tab/window is also not useable anymore.

I could not find a way to configure springdoc or swagger to ignore these metadata from groovy. With springfox/swagger it was possible by this way:
https://github.com/springfox/springfox/issues/752#issuecomment-312809615

**Reproduce**
I've created a minimal project which shows the problem to reproduce this issue:
https://github.com/felixsemmler/springdoc-swagger-issue

You can also check the branches `java-model` and `kotlin-model`, to see that it works fine if the response type is a java or kotlin class instead of groovy.

**Expected behavior**
The groovy metaclass informations should be ignored and not visible in the swagger-ui.

**Screenshots**
I also attached screenshots which should explain the problem in an easy way.
<img width="1484" alt="Bildschirmfoto 2020-03-26 um 12 45 21" src="https://user-images.githubusercontent.com/9789350/77643800-4990ee80-6f60-11ea-9315-154ec8cae00b.png">
<img width="524" alt="Bildschirmfoto 2020-03-26 um 12 45 52" src="https://user-images.githubusercontent.com/9789350/77643829-51e92980-6f60-11ea-99f7-016ddd4b69db.png">

If I can provide you more information or help you with solving this issue, please let me know. Thx in advance for your help and the great work on springdoc-open-api.

**Comment by felixsemmler** [comment]
I solved my issue in this way: https://github.com/swagger-api/swagger-core/issues/3388#issuecomment-605881154

Maybe this is something you want to integrate in springdoc. If you think that is something that should be fixed in swagger-core directly, you can close my issue.

**Comment by bnasslahsen** [comment]
Hi @felixsemmler, 

 Thank you for sharing your solution.
 It will be integrated by default, for the next version of springdoc-openapi: In order to have native support for Groovy metaclass/metadata
