### ISSUE TITLE
Do not expose parameters with Authentication type

### ISSUE THREAD

**Issue by akiraly** [springdoc/springdoc-openapi#511]
**Is your feature request related to a problem? Please describe.**
I am using webflux with spring security and sometimes I specify an org.springframework.security.core.Authentication parameter in my request handler metehods because I need access to the authenticated user info. Currently they are exposed authomatically in the OpenAPI desc but these shouldn't be there as this is not something the user specifies in the request.
For now I tried to hide them with `@Parameter(hidden = true)` but that doesn't seem to work either.

**Describe the solution you'd like**
Authentication parameters excluded/ignored by the OpenAPI desc

**Describe alternatives you've considered**
Marking them with `@Parameter(hidden = true)` and hiding them that way.

**Comment by joaodias14** [comment]
Hi @akiraly, please add the following dependency:
>         <dependency>
>             <groupId>org.springdoc</groupId>
>             <artifactId>springdoc-openapi-security</artifactId>
>         </dependency>

This should fix it.

**Comment by bnasslahsen** [comment]
@akiraly ,

 I agree with @joaodias14.
  You can find further details on the documentation:
- https://springdoc.org/

**Comment by akiraly** [comment]
Thanks, I wasn't aware of the security module.
