### ISSUE TITLE
Generating automatically server url ( add server url suffix ? or provide some methods to modify the server url)

### ISSUE THREAD

**Issue by rickldd** [springdoc/springdoc-openapi#513]
How is server url generated ?
Generating automatically server url may be useful, if the documentation is not present.
If the server annotations are present, they will be used instead.

  hello，nice to find you this project that's very cool !      
  I encountered some problems during use：
  sometimes i need provide a server url for Front and back separation development i want add a request suffix(eg: 127.0.0.1:8080/api) make swagger and static work normal
 
thanks!!!

**Comment by bnasslahsen** [comment]
@rickldd, 

 Your description is not clear.

 Please respect the guidance provided for new feature and have a look at the documentation:

 Also, have a look at the contribution guide: please help to speed up the diagnosis by providing as much information as possible.
- https://github.com/springdoc/springdoc-openapi/blob/master/CONTRIBUTING.adoc
