### ISSUE TITLE
Controller without @ResponseBody are not processed anymore

### ISSUE THREAD

**Issue by philippn** [springdoc/springdoc-openapi#516]
Hi there,

at some point since 1.2.25, a regression was introduced that has the effect that any Controller methods that are not annotated with `@ResponseBody` are being ignored.

In particular, this affects methods that have `ResponseEntity` as response type, as such methods do not need to be annotated with  `@ResponseBody`.

I can confirm that this problem was not existent in 1.2.25. Please find the attached screenshot that shows the code that performs the check. 

![isRestController-ResponseBody-check](https://user-images.githubusercontent.com/445105/77835147-5b35ea00-714a-11ea-89aa-c62adffe92c7.png)

Perhaps it would suffice to just add another condition for the `ResponseEntity` case.

Thanks in advance for looking into it and keep up the good work!

Kind regards,
Philipp

**Comment by philippn** [comment]
Examples regarding the use of `ResponseEntiity` can be found [here](https://www.baeldung.com/spring-response-entity).

**Comment by bnasslahsen** [comment]
Hi @philippn, 

 This is assumed choice, as there was some requests to handle that.
 You can change your controllers to `@RestControllers`. Or add `@ResponseBody` + `@Controller`.

 If its not possible, you can configure sprindoc to scan you additionnal controller using SpringDocUtils.

 For example:

```java
static {
	SpringDocUtils.getConfig().addRestControllers(HelloController.class);
}
```

**Comment by philippn** [comment]
Thank you for he quick response 👍
