### ISSUE TITLE
Endpoints in @Controller with HTTP 204 response are not displayed

### ISSUE THREAD

**Issue by l-lin** [springdoc/springdoc-openapi#519]
**Describe the bug**

The endpoints in a `@Controller` that returns nothing (i.e. no `@ResponseBody`) are not displayed in the online documentation, nor are they in the generated OpenAPI JSON.

**To Reproduce**

I created a demo project as a showcase of this issue: https://github.com/l-lin/demo-springdoc-no-content

**Expected behavior**

I'm not sure if it's intentional? Are `@Controller` not in springdoc's scope?

**Additional context**
I suspect the issue comes from the following lines:
https://github.com/springdoc/springdoc-openapi/blob/v1.3.0/springdoc-openapi-webmvc-core/src/main/java/org/springdoc/api/OpenApiResource.java#L149-L151

Indeed, it's trying to fetch the `@ResponseBody` annotation, however, `@Controller` do not have this annotation.

The easy workaround is to use `@RestController` instead.

**Comment by bnasslahsen** [comment]
You can have a look at the answer here:

- https://springdoc.org/faq.html#my-rest-controller-using-controller-annotation-is-ignored
