### ISSUE TITLE
Resource handler for UI overrides autoconfigured handlers

### ISSUE THREAD

**Issue by keliss** [springdoc/springdoc-openapi#52]
Hi,
there is an issue with mapping my own static resources from "resources" directory: SwaggerConfig class defines handler for mapping /** to /webjars/, which for some reason overrides default handler that maps /** to classpath:/META-INF/resources/, classpath:/resources/, classpath:/static/, classpath:/public/ and /. So all my requests to static resources get mapped to /webjars/. At this moment the only thing that helps is manually removing SwaggerConfig bean from context and defining my own bean that implements WebMvcConfigurer with correct mapping.
Possible solution: add stated above default paths to addResourceLocations() method in SwaggerConfig class.

**Comment by keliss** [comment]
Now I've come up with a more flexible solution. SwaggerConfig should contain something like this:
````
    @Value(SWAGGER_UI_PATH)
    private String swaggerPath;
    private ResourceProperties properties = new ResourceProperties();

    @Override
    public void addResourceHandlers(final ResourceHandlerRegistry registry) {
        String uiRootPath = "";
        if (swaggerPath.contains("/")) {
            uiRootPath = swaggerPath.substring(0, swaggerPath.lastIndexOf('/'));
        }
        ResourceHandlerRegistration resourceHandlerRegistration = registry.addResourceHandler(uiRootPath + "/**");
        resourceHandlerRegistration.addResourceLocations(WEB_JARS_PREFIX_URL + "/");
        for (String s : properties.getStaticLocations()) {
            resourceHandlerRegistration = resourceHandlerRegistration.addResourceLocations(s);
        }
        resourceHandlerRegistration.resourceChain(false);
    }
````

**Comment by springdoc** [comment]
Hi,

  This issue seems to be very specific to your application configuration. 
  Its possible to override SwaggerConfig for your application as you mentioned.
  
  Thanks for your feedback.
