### ISSUE TITLE
Has any way to filter swagger2 annotations

### ISSUE THREAD

**Issue by FlyInWind1** [springdoc/springdoc-openapi#521]
My old project has many swagger2 annotations, it is not easy to migrating them to v3, so i want v2 work with v3. But all v2 api present on v3 ui. Has any way to hidden them?

**Comment by bnasslahsen** [comment]
This is not the role of springdoc-openapi.
The standard is different from swagger2 to OpenAPI 3.
The annotations are different.
And the UIs are different.
