### ISSUE TITLE
No documented way to handle Mono/Flux without Webflux

### ISSUE THREAD

**Issue by pkubowicz** [springdoc/springdoc-openapi#523]
**Describe the bug**
- If you are reporting a bug, please help to speed up problem diagnosis by providing as much information as possible:
- A clear and concise description of what the bug is: the title of an issue is not enough

**To Reproduce**
I have Spring MVC (no spring-webflux) application based on Spring Boot 2.2.6 and Springdoc 1.3.0.

My controllers return Flux and Mono.

By default springdoc's swagger-ui page displays Flux response as:
```
{
  "prefetch": 0
}
``` 

When I include `org.springdoc:springdoc-openapi-webflux-core:1.3.0` my application fails to start:
```
***************************
APPLICATION FAILED TO START
***************************

Description:

An attempt was made to call a method that does not exist. The attempt was made from the following location:

    org.springdoc.core.SpringDocWebMvcConfiguration.openApiResource(SpringDocWebMvcConfiguration.java:60)

The following method did not exist:

    'void org.springdoc.api.OpenApiResource.<init>(java.lang.String, org.springdoc.core.OpenAPIBuilder, org.springdoc.core.AbstractRequestBuilder, org.springdoc.core.GenericResponseBuilder, org.springdoc.core.OperationBuilder, org.springframework.web.servlet.mvc.method.RequestMappingInfoHandlerMapping, java.util.Optional, java.util.Optional, org.springdoc.core.SpringDocConfigProperties, java.util.Optional)'

The method's class, org.springdoc.api.OpenApiResource, is available from the following locations:

    jar:file:/home/pkubowicz/.gradle/caches/modules-2/files-2.1/org.springdoc/springdoc-openapi-webflux-core/1.3.0/9254ae87d259128c266dcb64a8fdefefa776fbcb/springdoc-openapi-webflux-core-1.3.0.jar!/org/springdoc/api/OpenApiResource.class
    jar:file:/home/pkubowicz/.gradle/caches/modules-2/files-2.1/org.springdoc/springdoc-openapi-webmvc-core/1.3.0/13bab9bda41e79dbc041c5fb4e564548e7cd0ffd/springdoc-openapi-webmvc-core-1.3.0.jar!/org/springdoc/api/OpenApiResource.class
```

The work-around is to execute:
```
SpringDocUtils.getConfig().addResponseWrapperToIgnore(Mono::class.java)
SpringDocUtils.getConfig().addResponseWrapperToIgnore(Flux::class.java)
```

**Expected behavior**
This use case should be documented - should springdoc-openapi-webflux-core be used or not used, and if not the documentation should explain how to 'unwrap' Flux and Mono.

**Comment by bnasslahsen** [comment]
@pkubowicz, 

You can have a look at the full documentation:
- https://springdoc.org/

For spring-mvc you should use, only the springdoc-openapi-webmvc-core.
For spring-webflux, you should use only springdoc-openapi-webflux-core.

You should not ship both modules on the same application.

If you are using Mono and Flux types on you spring-mvc application (which is not natural), using SpringDocUtils might help achieve clean OpenAPI description as you mentionned.

**Comment by pkubowicz** [comment]
There is nothing 'unnatural' in using Mono and Flux in Spring MVC. It is [officially supported and documented](https://docs.spring.io/spring/docs/current/spring-framework-reference/web.html#mvc-ann-async-reactive-types). What is unnatural is that Springdoc considers a supported configuration 'unnatural'.

There is not a single sentence in the documentation supporting what you have written.

I still insist this is a bug (at least a bug in the documentation) and:
> This use case should be documented - should springdoc-openapi-webflux-core be used or not used, and if not the documentation should explain how to 'unwrap' Flux and Mono.

**Comment by bnasslahsen** [comment]
@pkubowicz, 

 If you feel the documentation for this part is not clear, please feel free to propose a PR to improve it:
  - https://github.com/springdoc/springdoc.github.io/blob/master/faq.md

**Comment by iyzana** [comment]
I've run into the same problem.
springdoc-openai-webmvc-core should be able to handle Mono and Flux return types too.

The suggested workaround above is not sufficient for Flux, because just stripping it is not correct, it should be handled as an array.
As a further workaround I had to annotate all endpoints returning a Flux with:
```
@Operation(responses = @ApiResponse(content = @Content(array = @ArraySchema(schema = @Schema(implementation = String.class)))))
```

**Comment by mvdobrinin** [comment]
BTW Mono and Flux are not supported. See `WebFluxSupportConverter` and `org.springdoc:springdoc-openapi-webflux-core` lib.

**Comment by mnbattaglia** [comment]
Is this still unsupported? I agree with others that this is a totally valid use case and must be supported

**Comment by bnasslahsen** [comment]
@mnbattaglia, 

There are many workarounds for that.
But as there some demands, it will be added out of the box for the next release.
