### ISSUE TITLE
HAL Link rendering

### ISSUE THREAD

**Issue by martinmaher** [springdoc/springdoc-openapi#524]
My spring boot (v2.2.5.RELEASE) project is using Spring HATEOAS with the link-style rendering configured to render all single links as an array. This is achieved using the following configuration:

```
@Bean
public HalConfiguration halConfiguration() {
  return new HalConfiguration()
      .withRenderSingleLinks(RenderSingleLinks.AS_ARRAY); 
}
```

Unfortunately the openapi-generator (v1.2.34) currently assumes that each Link Entry can only contain a **single** Link rather than a **collection** of links.

The generated Link schema is:
```
  "Links": {
    "type": "object",
    "additionalProperties": {
      "$ref": "#/components/schemas/Link"
    }
  }
  "Link": {
    "type": "object",
    "properties": {
      "href": {
        "type": "string"
      },
       ...
  }
```
Which is fine when Links are rendered like in the example below:

```
"_links": {
  "self": {
    "href": "http://localhost:8410/order/1"
  },
  "order-items": {
    "href": "http://localhost:8410/order/1/item/1"
  }
}
```

However in my application the links are rendered like this:
```
    "_links": {
      "self": [
        {
          "href": "http://localhost:8410/order/1"
        }
      ],
      "order-items": [
        {
          "href": "http://localhost:8410/order/1/item/1"
        }
      ]
    }
```

### What solution would I like?

When rendering links as an array I would expect the following schema:
```
      "Links": {
        "type": "object",
        "additionalProperties": {
          "$ref": "#/components/schemas/LinkArray"
        }
      },
      "LinkArray": {
        "type": "array",
        "items": {
          "$ref": "#/components/schemas/Link"
        }
      }
```

It would be great if springdoc could vary the Link schema generation based on some setting  and generate the Links definitions accordingly. This could be done by checking the HAL configuration or alternatively checking if a certain property is set (e.g. springdoc.api-docs.hateoas.render-single-links-as-array=true).

More information on link rendering can be found [here](https://docs.spring.io/spring-hateoas/docs/current/reference/html/#mediatypes.hal.configuration)

**Comment by bnasslahsen** [comment]
@martinmaher, 

 Please provide a complete description of your context.
 You can have a look at our contribution guide, on the following section: Using GitHub Issues. Because this kind of questions should go to stackoverflow:
- https://github.com/springdoc/springdoc-openapi/blob/master/CONTRIBUTING.adoc

 Please provide the exact springdoc-openapi modules you are using.
 For example, you didn't mentionne if you are using springdoc-openapi-data-rest as well.

If you are reporting a bug, please help to speed up problem diagnosis by providing as much information as possible:

- What modules and versions of springdoc-openapi are you using?
- What are the actual and the expected result using OpenAPI Description (yml or json)?
- Provide with a sample code (HelloController) or Test that reproduces the problem

**Comment by bnasslahsen** [comment]
closed, as not additional information provided.

**Comment by FranPregernik** [comment]
@bnasslahsen Sorry to hijack the issue ... could you perhaps weigh in on the linked issue swagger-api/swagger-codegen-generators#691. Can anything be done in springdoc to allow the codegen (typescript) to work around the issue?

**Comment by bnasslahsen** [comment]
@FranPregernik, 

  I don't see the relation between swagger-codegen-generators and springdoc-openapi., and how could any change on springdoc-openapi impact swagger-codegen-generators ?

**Comment by FranPregernik** [comment]
I am sorry. I didn't explain correctly.
I think springdoc-openapi generates a correct specification.

However, the customization [here](https://github.com/springdoc/springdoc-openapi/blob/v1.3.9/springdoc-openapi-data-rest/src/main/java/org/springdoc/data/rest/SpringDocDataRestConfiguration.java#L103) is triggering the issue in the typescript codegen. 

The MapSchema/StringSchema/ObjectSchema causes codegen to treat the links as a map but they don't have the `map` type defined in their [mappings](https://github.com/swagger-api/swagger-codegen-generators/blob/2a561d8587e5bea502941e6c5377ce89eff6f13d/src/main/java/io/swagger/codegen/v3/generators/typescript/AbstractTypeScriptClientCodegen.java#L86).

Do you have any suggestion how the `links` OpenApi spec could be generated differently while still being compatible with SpringDataRest and SpringHateoas?

**Comment by bnasslahsen** [comment]
@FranPregernik, 

 The link of the code, is not using the last stable version (v1.5.2).
 If the OpenAPI spec is correct, i am not sure how we could help.

 Note that any Bean defined by springdoc-openapi can be overrriden when necessary.

**Comment by FranPregernik** [comment]
@bnasslahsen,

Got it. I will retry this with the new version and go on from there. 
Thank you!
