### ISSUE TITLE
Be able to set Info values (title, description, contact, etc) from Spring config

### ISSUE THREAD

**Issue by econn9** [springdoc/springdoc-openapi#525]
if i just want to use the option to customize the api-docs url, i cannot massage any data that comes out, so it would be nice to be able to do that at least for the Info section since thats metadata that you wouldnt put into the app anywhere

could look like:
springdoc.api-docs.path=/my-custom-path
springdoc.api-docs.info.contact.name = Joe Developer

i found this because i have a requirement where i need to make an endpoint that gives back an OpenAPI doc of my service, but its a custom endpoint for a dashboard and it cant just be /v3/api-docs... setting the custom path in the config is a solution, but doesnt allow me to massage data like i would prefer to do

**Comment by bgulowaty** [comment]
@econn9 looks like its possible already https://github.com/springdoc/springdoc-openapi/issues/463

**Comment by bnasslahsen** [comment]
Thank you @bgulowaty !

@econn9

You can have a look at the documentation:
- https://springdoc.org/faq.html#can-i-use-spring-property-with-swagger-annotations

**Comment by econn9** [comment]
well, the answer given was for making an annotation, but it remains to be answered if one can set the value from the spring config??

the link given was not a very thorough document, so heres an example of the referenced annotation solution for anyone who comes across this: 

`
@OpenAPIDefinition(
    info = @Info(
            title = "SEAM Event Producer",
            termsOfService = "http://bmwusa.com",
            description = "Captures request events related to client interactions with service " +
                    "appointment requests, and notifies the SEAM backend of them",
            contact = @Contact(
                    name = "Team Orion",
                    url = "Orion_Scrum_team@list.bmw.com",
                    email = "https://code.connected.bmw/after-sales/seam-event-producer"
            )
    )
)
@RestController
public class SwaggerController {...}`
