### ISSUE TITLE
GroupedOpenApi Scan API's by Annotation

### ISSUE THREAD

**Issue by simoneliash** [springdoc/springdoc-openapi#526]
I'm trying to migrate my sprintBoot project from springFox, i need to set up a group that should only include API's with a specific custom annotation that i have in my project.

Is there a way to configure with OpenApiCustomiser to scan API's that use a specific annotation? e.g:
`RequestHandlerSelectors.withMethodAnnotation(MyCustomAnnotation.class)`

Update:
i managed to solve it by:

```
@Bean
    public GroupedOpenApi publicApi() {
        List<String> paths = new ArrayList<>();
        String[] pathsArr = {};
        this.requestHandlerMapping.getHandlerMethods()
                .forEach((key, value) -> {
                    if (AnnotationUtils.getAnnotation(value.getMethod(), MyCustomAnnotation.class) != null) {
                        paths.add(key.getPatternsCondition().getPatterns().iterator().next());
                    }
                });
        pathsArr = paths.toArray(pathsArr);
        return GroupedOpenApi.builder()
            .setGroup("myGroup")
            .pathsToMatch(pathsArr)
            .build();
    }
```

Is there a better way?

**Comment by bnasslahsen** [comment]
@simoneliash 

 OpenApiCustomiser can help but will be more complexe. 
  The filtering is achieved post-construction, and will have to remove all the paths.
  Your solution looks fine.

**Comment by phirzel** [comment]
@simoneliash you are a genious, thanks a lot!

**Comment by srinivaspeddireddy** [comment]
paths.add(key.getPatternsCondition().getPatterns().iterator().next());
This line is giving an error : arraycopy: length -2 is negative
Any idea
