### ISSUE TITLE
Generic (error) responses built from `ControllerAdvice` are nondeterministic

### ISSUE THREAD

**Issue by ali-rantakari** [springdoc/springdoc-openapi#53]
Thank you for providing this library.

Generic (error) responses built from `ControllerAdvice` exception handlers are built in an undefined order. In cases where multiple exception handler methods declare the same response status, which method’s return type ends up being used as the response schema for that status code is nondeterministic (might change between runs).

I’m speculating the issue is due to the use of the `Set` data type in iteration:

<https://github.com/springdoc/springdoc-openapi/blob/cca0857c9fbe687567179b8c233508b433742403/springdoc-openapi-common/src/main/java/org/springdoc/core/AbstractResponseBuilder.java#L74>

**Comment by springdoc** [comment]
Hi, 

 The description is not clear. Please provide more information in order to go further:
-  The sample (java) code to reproduce your issue. 
-  The result you have got in OpenAPI format
-  The expected Result

**Comment by ali-rantakari** [comment]
[repro.zip](https://github.com/springdoc/springdoc-openapi/files/3528533/repro.zip)

Please find attached a project to reproduce this.

Steps to repro:

1. Start the application in the project (running the `bootRun` Gradle task)
2. Inspect the `localhost:8080/v3/api-docs` output
3. Note the schema for the `GET /test` `500` response (is it `Foo` or `Bar`?)
4. Repeat the above steps until the schema changes from the previous time

Expected:

The schema is always the same

Actual:

The schema sometimes changes between runs.

**Comment by springdoc** [comment]
Hi, 

 A fix for this issue will be available on v1.1.26 on springdoc-openapi.
