### ISSUE TITLE
Swagger UI does not work in a kubernetes nginx-ingress setup

### ISSUE THREAD

**Issue by garrychnca** [springdoc/springdoc-openapi#534]
I don't think this is a bug on the springdoc's side, but rather some unusability with the setup of kubernetes nginx-ingress + webapp with springdoc.

The observation is as follows:
1. Browser visits https://some-host-name/some/path/prefix/swagger-ui.html
2. Browser gets back HTTP 307 to redirect to /webjars/swagger-ui/index.html?configUrl=/v3/api-docs/swagger-config
3. Browser visits https://some-host-name/webjars/swagger-ui/index.html?configUrl=/v3/api-docs/swagger-config

As step 3 above, the configured nginx-ingress does not recognize the path as it does not start with the /some/path/prefix, hence redirect the request to the nginx home page.

The nginx-ingress is configured with:

```javascript
{
    "apiVersion": "extensions/v1beta1",
    "kind": "Ingress",
    "metadata": {
        "annotations": {
            "kubernetes.io/ingress.class": "nginx-private",
            "nginx.ingress.kubernetes.io/rewrite-target": "/$2"
        },
        "name": "some-ingress",
        "namespace": "some-namespace"
    },
    "spec": {
        "rules": [
            {
                "host": "some-host-name",
                "http": {
                    "paths": [
                        {
                            "backend": {
                                "serviceName": "webapp-service",
                                "servicePort": 80
                            },
                            "path": "/some/path/prefix(/|$)(.*)"
                        }
                    ]
                }
            }
        ]
    }
}
```

I'm not sure if you have any solution for this kind of setup?

**Screenshots**
![Screen Shot 2020-04-02 at 8 58 34 PM](https://user-images.githubusercontent.com/2024176/78313545-1385d880-7525-11ea-9496-5923eddfd1c5.png)

**Additional context**

**Comment by bnasslahsen** [comment]
@garrychnca, 

 There is no issue on getting swagger-ui using kubernetes.

 You didn't mentionne, if you are using spring-mvc or spring-webflux.
 You didn't mentionne the springdoc-openapi version you are using. Be sure you use the last stable version: v1.3.0

 You can have the look at the following section: **How can I deploy the Doploy springdoc-openapi-ui, behind a reverse proxy?**

- https://springdoc.org/faq.html#how-can-i-deploy-the-doploy-springdoc-openapi-ui-behind-a-reverse-proxy

 There is configuratino needed on your spring-boot application level first.

 Additionally, you need to set the right headers depending on your reverse-proxy to make sure you forward X-Forwarded-Prefix:
- https://github.com/springdoc/springdoc-openapi/issues/153
