### ISSUE TITLE
springdoc.swagger-ui.layout=BaseLayout property is not passed over to swagger-ui

### ISSUE THREAD

**Issue by dranzerashi** [springdoc/springdoc-openapi#536]
When I'm passing springdoc.swagger-ui.layout=BaseLayout  property in application properties it is not being passed over to swagger-ui, when i directly pass the parameter in the url lets say http://localhost:8080/swagger-ui/index.html?configUrl=/api-docs/swagger-config&layout=BaseLayout it removes the top bar as expected. 

**Expected behavior**
- The query parameter layout=BaseLayout is added 
- The top bar with explore button should disappear
- here is how it should look https://ibb.co/4FHNDk3

**Current Behavior**
- the corresponding url parameter is missing
- the layout still comes with the top bar
- screenshot: https://ibb.co/Pj5S9dd

Additional details:
org.springframework.boot: spring-boot-starter-parent: 2.2.5.RELEASE
org.springdoc: springdoc-openapi-ui: tried both 1.3.0 & 1.2.32

**Comment by bnasslahsen** [comment]
@dranzerashi, 

 If you look at /v3/api-docs/swagger-config, you will see that you have **"layout":"BaseLayout "**.
 Its an issue, on the swagger-ui.
 I invite to log your description on the swagger-ui project:
 - https://github.com/swagger-api/swagger-ui/issues

 Meanwhile, we will try to find a workaround, for the next release.

**Comment by bnasslahsen** [comment]
waiting for this issue to be resolved on swagger-ui side.
A workaround, will be availble on v1.3.1 of springdoc-openapi.

**Comment by javaHelper** [comment]
Is this issue got resolved in which latest version ?

**Comment by dranzerashi** [comment]
Hi,
 I'd like to reopen this issue, I have some updates.

**Comment by dranzerashi** [comment]
It has been pointed out that this issue is being caused by a missing addition of the layout property to the params map in this file below line 189 configURL is added but there is no layout parameter, Adding that seems to have resolved the issue, Please fix this so that a future release may contain the fix:
https://github.com/springdoc/springdoc-openapi/blob/master/springdoc-openapi-common/src/main/java/org/springdoc/core/SwaggerUiConfigProperties.java

**Comment by dranzerashi** [comment]
Additionally in a similar fashion, there is an issue where configURL property seems to have no impact over the way the page behaves(setting configUrl still takes you to petstore). Only the .url property setting seems to have any impact. I am not sure if this is a bug or expected behavior. But I assume setting configURL should actually show the url for that swaggerdoc

**Comment by bnasslahsen** [comment]
@dranzerashi,

Its now available on v1.3.1. 
You can have a look at the CHANGELOG:
- https://github.com/springdoc/springdoc-openapi/blob/master/CHANGELOG.md

Did you test the setting of layout property using this version ?

**Comment by dranzerashi** [comment]
the below url corresponds to the v1.3.1 version of the same file.
https://github.com/springdoc/springdoc-openapi/blob/75377e9d7f21bf4033238ef9d16aefa8d090cb73/springdoc-openapi-common/src/main/java/org/springdoc/core/SwaggerUiConfigProperties.java 

 While I see the property name LAYOUT_PROPERTY on line 57, I do not see it being used in the function https://github.com/springdoc/springdoc-openapi/blob/75377e9d7f21bf4033238ef9d16aefa8d090cb73/springdoc-openapi-common/src/main/java/org/springdoc/core/SwaggerUiConfigProperties.java#L185

I'll double check the same while running it and update this

**Comment by dranzerashi** [comment]
Yep, This is working perfectly as expected in v1.3.1 Thanks a lot.  Setting configUrl still takes me to petstore though again not sure if this is a bug or I'm misunderstanding the purpose. setting url seems to work as expected so this is not a major issue.
