### ISSUE TITLE
The fields of the @ParameterObject marked object are required.

### ISSUE THREAD

**Issue by wangyanrui** [springdoc/springdoc-openapi#541]
version: 1.3.1

All fields are required when an object is used as an input parameter who marked @ParameterObject

eg: 
```
    @GetMapping(value = "/demo")
    public Result<?> list(@ParameterObject ParameterQuery query,
                          @ParameterObject @PageableDefault Pageable pageable) {
        return ResultCreator.success(null);
    }

    @Data
    @NoArgsConstructor
    @AllArgsConstructor
    public static class ParameterQuery implements Serializable {
        private String q1;
        private String q2;
        private String q3;
    }
```

And It is still invalid If I mark @Parameter(required = false) on the field like this

```
    @Parameter(required = false)
    private String q1;
```
![图片](https://user-images.githubusercontent.com/18323777/78524129-a6fd2900-7805-11ea-8d6a-d6b331afcb27.png)

I read the source code, probably because of a problem with these two lines of code or the way I use it ?

org.springdoc.core.AbstractRequestBuilder  row 352
org.springdoc.core.GenericParameterBuilder row 159

**Comment by bnasslahsen** [comment]
You can use this workaround, on the attributes of you object:
```java
	@Nullable
	@Parameter(description = "string parameter")
	private String stringParam;
```
Or
```java
	@Parameter(description = "string parameter")
	private Optional<String> stringParam;
```

For the support of  @Parameter(required = false), it will be added for the next release.
