### ISSUE TITLE
Support for Spring WebMvc.fn

### ISSUE THREAD

**Issue by nlochschmidt** [springdoc/springdoc-openapi#546]
You have a note on https://springdoc.org/ saying:
> Spring-weblfux with Functional Endpoints, will be available in the future release

However, I haven't seen any mention on supporting WebMvc.fn (classic servlets): https://docs.spring.io/spring/docs/current/spring-framework-reference/web.html#webmvc-fn

Do you already have an idea on how this could be supported? Given that this approach doesn't have a convenient place to put any annotations, I wonder how feasible it actually is.

Since the Functional Endpoints for Servlets are now pretty much stable, I am guessing that more people are going to ask for this.

As a side-note, here are two examples on how other libraries are solving this problem:

- [HTTP4K](https://www.http4k.org/guide/modules/contracts/) is using a `meta` dsl 
- [Jooby](https://jooby.io/modules/openapi/) is using a combination of build-time byte code analysis + annotation on handler functions

**Comment by bnasslahsen** [comment]
Hi @nlochschmidt, 

 This is a new feature added since 5.2 Release.
 The functional endpoints were first available in spring-webflux since 5.0. 
 And should be addressed first, before the Support for Spring WebMvc.fn.
 The approach should the same for Spring WebMvc.fn, once it will be addressed for spring-webflux.

 For the moment, we are still focusing on the core functionality of the library.
  You can also contribute to add this support. This might accelerate the release of this functionality.

**Comment by nlochschmidt** [comment]
Ok thanks.

I actually would love to prototype this, however since I don't have a massive amount of time, I was wondering which approach might be most interesting to the maintainers of springdoc.

I guess it is probably possible to get the root `RouterFunction`(s) from the spring context and add them to the [existing mappings][1] and then later use a [RouterFunctions.Visitor][2] in [OpenApiResource][3] to construct the right OpenAPI model from it.

However the main question I have now is where we should attach the OpenAPI3 annotations or whether we should skip the annotation and directly let the developer add OpenAPI values to the RouterFunctions somehow.

The latter could be possible by adding a `DocumentedRouterFunction` to springdoc that is functionally just a wrapper that is directly forwarding every request, but has an additional field for OpenAPI values.

Maybe @poutsma has an idea on how we could make this work best?

I haven't done anything with the reactive stack yet, but the RouterFunctions implementation looks pretty much identical. So likely the implementation in SpringDoc will be very similar as well.

[1]: https://github.com/springdoc/springdoc-openapi/blob/4182edefd06e64f3327b9a50c0559a782d347eae/springdoc-openapi-common/src/main/java/org/springdoc/core/OpenAPIBuilder.java#L147-L150
[2]: https://docs.spring.io/spring/docs/current/javadoc-api/org/springframework/web/servlet/function/RouterFunctions.Visitor.html
[3]: https://github.com/springdoc/springdoc-openapi/blob/master/springdoc-openapi-webmvc-core/src/main/java/org/springdoc/webmvc/api/OpenApiResource.java

**Comment by poutsma** [comment]
I don't know much about OpenAPI, but any kind of router functions inspection should indeed use the visitor mechanism.

**Comment by bnasslahsen** [comment]
@nlochschmidt, 

 The support is added and available with the latest stable release.

**Comment by nlochschmidt** [comment]
Great! Thank you so much 👍
