### ISSUE TITLE
@Parameter examples does not produce proper output

### ISSUE THREAD

**Issue by dranzerashi** [springdoc/springdoc-openapi#547]
@Parameter(description="Sample description",
            required=true, schema=@Schema(implementation = Sample.class), examples = {@ExampleObject(value = "{'name':'value'}"),@ExampleObject(value = "{'name':'value1'}")}) @RequestBody Sample sample)

should output 2 examples in the documentation instead the examples are coming as empty, and is missing in the api-docs

**Comment by bnasslahsen** [comment]
You should add the name for the ExampleObject, in order to have many examples displayed.
