### ISSUE TITLE
Fully qualified names

### ISSUE THREAD

**Issue by raghuraman1** [springdoc/springdoc-openapi#548]
Hi,

Is it possible to show fully qualified java type names in the schemas?
Its quite possible there might be multiple classes with same class simple name but different package names used .

R

**Comment by bnasslahsen** [comment]
The resolution of schema names is done using swagger-api.
springdoc-openapi ,will not override this behaviour by default.

You can achieve that by using your own OpenAPICustomiser and ModelConverters.

**Comment by raghuraman1** [comment]
Can you please elaborate please on how this can be achieved.
I was otherwise hoping you could provide a simpler configuration property for this.

**Comment by bnasslahsen** [comment]
You can have a look at the swagger documentation:
- https://github.com/swagger-api/swagger-core/wiki/Swagger-2.X---Annotations
We will not override swagger default schema ref, but you can achieve it as mentionned beforen only using swagger annotation.

**Comment by raghuraman1** [comment]
Hope I am not annoying you by coming to it again.
I would think all that you really need is to have a configuration property which allows the 
v3/api-docs url to have the following changes. in its output
Instead of current:
"$ref":"#/components/schemas/SomeType and "schemas":{"SomeType".

you could generate the follwing kind of text in the json
"$ref":"#/components/schemas/packagename.SomeType and "schemas":{"packagename.SomeType".

You could have a configuration property control this feature.
Hope I explained it clearly. 
By the way is there any rule which says we should not show fully qualified names.

**Comment by bnasslahsen** [comment]
@raghuraman1, 

  I d say, a little bit anoying ...

 As explained before, this generation is not done by springdoc-openapi.
 You have many Customizers on springdoc-openapi, which can help you achieve that. But the best way is to use your own modelconverter which is provided by swagger-api.

 You can submit your request for properties control to the swagger-core project, but its not the role of springdoc-openapi:
 - https://github.com/swagger-api/swagger-core

**Comment by raghuraman1** [comment]
Thanks for the information. Sorry about going on and on about it.  :) 
Will try exploring the modelconverter route.

**Comment by raghuraman1** [comment]
@bnasslahsen 
One doubt. Is io.swagger.v3.core.jackson.TypeNameResolver not the easier key. Currently it has only one implementation possible the way the library is currently. If you allow it to be injectable somehow that would achieve it in a easier manner. The approach could be similar to spring fox's TypeNameProviderPlugin. What do you think?

**Comment by bnasslahsen** [comment]
@raghuraman1,

 If you feel you have found any interesting functionality, you can propose a PR.

**Comment by raghuraman1** [comment]
@bnasslahsen
Ok. Will fork from your repository and try. will reach you for any help if needed. Trust that is ok.
I think I should be able to do it on my own generally speaking.
Will update you when ready.
Thanks.

**Comment by raghuraman1** [comment]
**_Here is a screenshot of what I tried._**
![image](https://user-images.githubusercontent.com/14346578/78828028-afba4e80-7a01-11ea-9d6a-aa632ddb2005.png)

**_and another screen shot_**
![image](https://user-images.githubusercontent.com/14346578/78828180-ec864580-7a01-11ea-96e6-0926036b044a.png)

So it works. The code change is not in springdoc-openapi library codebase.
The only code change that needed to be done is in
`<groupId>io.swagger.core.v3</groupId>
<artifactId>swagger-core</artifactId>`

I changed the class io.swagger.v3.core.jackson.TypeNameResolver  to
 the below after forking it in my personal repository.
`package io.swagger.v3.core.jackson;

//import io.swagger.annotations.ApiModel;

import com.fasterxml.jackson.databind.JavaType;
import io.swagger.v3.core.util.AnnotationsUtils;
import io.swagger.v3.core.util.PrimitiveType;
import org.apache.commons.lang3.StringUtils;
import org.apache.commons.lang3.text.WordUtils;

import java.util.Arrays;
import java.util.Collections;
import java.util.EnumSet;
import java.util.Set;

/**
 * Helper class used for converting well-known (property) types into
 * Swagger type names.
 */
public class TypeNameResolver {
    public final static TypeNameResolver std = new TypeNameResolver();
    **private boolean useFqn=false;**

    public void setUseFqn(boolean useFqn) {
		this.useFqn = useFqn;
	}

	protected TypeNameResolver() {
    }

    public String nameForType(JavaType type, Options... options) {
        return nameForType(type, options.length == 0 ? Collections.<Options>emptySet() :
                EnumSet.copyOf(Arrays.asList(options)));
    }

    public String nameForType(JavaType type, Set<Options> options) {
        if (type.hasGenericTypes()) {
            return nameForGenericType(type, options);
        }
        final String name = findStdName(type);
        return (name == null) ? nameForClass(type, options) : name;
    }

    protected String nameForClass(JavaType type, Set<Options> options) {
        return nameForClass(type.getRawClass(), options);
    }

    protected String nameForClass(Class<?> cls, Set<Options> options) {
        if (options.contains(Options.SKIP_API_MODEL)) {
            return getNameOfClass(cls);
        }

        io.swagger.v3.oas.annotations.media.Schema mp = AnnotationsUtils.getSchemaDeclaredAnnotation(cls);

        final String modelName = mp == null ? null : StringUtils.trimToNull(mp.name());
        return modelName == null ? getNameOfClass(cls) : modelName;
    }

	private String getNameOfClass(Class<?> cls) {
		return **useFqn?cls.getName():cls.getSimpleName();**
	}

    protected String nameForGenericType(JavaType type, Set<Options> options) {
        final StringBuilder generic = new StringBuilder(nameForClass(type, options));
        final int count = type.containedTypeCount();
        for (int i = 0; i < count; ++i) {
            final JavaType arg = type.containedType(i);
            final String argName = PrimitiveType.fromType(arg) != null ? nameForClass(arg, options) :
                    nameForType(arg, options);
            generic.append(WordUtils.capitalize(argName));
        }
        return generic.toString();
    }

    protected String findStdName(JavaType type) {
        return PrimitiveType.getCommonName(type);
    }

    public enum Options {
        SKIP_API_MODEL;
    }
}
`
**Note :** the only change was in adding this method private  getNameOfClass , a boolean useFqn and its setter and a small change in the code where it used to use Class.getSimpleName() it now conditionally calls Class.getName() or Class.getSimpleName()
There was no need for any change in the springdoc-openapi library.
In the sample application from where I took the screenshots I just added one line.

`public class SampleApplication {
	public static void main(String[] args) {
		**TypeNameResolver.std.setUseFqn(true);**
		SpringApplication.run(SampleApplication.class, args);
	}
}	`

I have removed some code to keep it simple.
I have forked the swagger-core repository.
What do you think?
Do you need me to share the actual  forked repositories and sample application?

I would be happy to raise the PR with swagger-core.
I have the code forked and ready.
What are your views? Will you vote for the PR?

**Comment by bnasslahsen** [comment]
@raghuraman1, 

 Starting with v1.4.4 of springdoc-openapi, the following property enables fully qualified names support:

```properties
springdoc.use-fqn=true
```
