### ISSUE TITLE
Map type with @RequestParam(required = false) in method isn't ignored

### ISSUE THREAD

**Issue by dlamoris** [springdoc/springdoc-openapi#553]
**Describe the bug**
given this RestController method
```
@GetMapping
    public SomeType get(
        @PathVariable String path,
        @RequestParam(required = false) Map<String, String> params) {
    }
```
params is included in documentation

**To Reproduce**
- What version of spring-boot you are using?
2.1.7
- What modules and versions of springdoc-openapi are you using?
tried springdoc-openapi-ui 1.2.27 and 1.3.1
- What is the actual and the expected result using OpenAPI Description (yml or json)?
using 1.2.26, Map doesn't show up, it shows up in doc after from 1.2.27 on
- Provide with a sample code (HelloController) or Test that reproduces the problem
```
@RestController
public class Controller {
    @GetMapping(value = "/get")
    public String get(@RequestParam Map<String, String> params) {
        return "healthy";
    }
}
```
**Expected behavior**
Map types in methods should be ignored

**Comment by bnasslahsen** [comment]
@dlamoris, 

 Your description is not correct.
 Map type is ignored. 
 But while you use @RequestParam, they won't be as @RequestParam contains required attribute =true.

 When RequestParam, contains required attribute=false, it makes sens to ignore the Map.
