### ISSUE TITLE
FQNs for java classes

### ISSUE THREAD

**Issue by raghuraman1** [springdoc/springdoc-openapi#554]
Hi,
@bnasslahsen
This is not directly an issue in springdoc-openapi code base.
Currently springdoc-openapi is not able to show fully qualified class names.
The problem has been traced to swagger-core.
To solve this I raised a PR.
https://github.com/swagger-api/swagger-core/pull/3510
It does affect springdoc-openapi functionality.

Please also refer to https://github.com/springdoc/springdoc-openapi/issues/548 where after ticket closing had a dicsussion on this which lead to me raising the PR with swagger-core.

I would request you guys to please vote  for the PR on swagger-core if you think it is useful.
In a project its quite possible to have two classes with same name and different packages. This will help in those scenarios.

I created this ticket so that it can be a place holder for tracking the PR.
Please close this ticket when you deem fit.

R

**Comment by bnasslahsen** [comment]
ok @raghuraman1, 
We will follow it.

**Comment by raghuraman1** [comment]
@bnasslahsen  Thanks for liking the PR. It seems to take real long for the merge. I hope I have not missed anything in the PR review.
