### ISSUE TITLE
Request support for adding a JSON schema specification to springdoc-openapi

### ISSUE THREAD

**Issue by jsimone-infoarmor** [springdoc/springdoc-openapi#557]
we have a JSON schema validating a spring boot POST request.  The schema is stored as a file in resources.  The request body makes its way into the spec with the following annotation: 

```      
@io.swagger.v3.oas.annotations.parameters.RequestBody(description = "Request Body:",
 content = @Content(schema = @Schema(implementation = EventCreateRequest.class)), required = true)
@RequestBody String requestBodyJson) throws ProcessingException, JsonProcessingException {
jsonSchemaValidationService.validateFromString(requestBodyJson, "/schema/profiles-post-request-body-schema.json");
...
}
```
It would be nice to be able to specify that the schema file is represented in the open-api spec.  This way one viewing the open-api spec can clearly see which fields are required, which are optional and the field types.  This is all given in the JSON schema.

When we were using bean constraint annotations to validate the request body via an @Valid annotation we were getting all the request body constraints in the spec.  But, having switched to using the full power of JSON schema for request body annotation we see no way of propagating this information in the open-api spec.

Please inform if there is some doc that you can point me to to show how this could be done.

**Comment by bnasslahsen** [comment]
@jsimone-infoarmor, 

 The springdoc-openapi library doesn't use json schema validation.
 Only  jsr 303 annotations are supported.

**Comment by dmushkov** [comment]
@jsimone-infoarmor Did you find a way for exposing json schema?

**Comment by jsimone-infoarmor** [comment]
no, I did not.

**Comment by dmushkov** [comment]
@jsimone-infoarmor 
I see ... Very cool idea by the way!

**Comment by valasatava** [comment]
You could try adding:
@Parameter(schema = @Schema(ref = "...path-to-schema-file..."))

**Comment by dmushkov** [comment]
@valasatava you made my day! thanks! That do the trick and now I have parameter described from JsonSchema. One disadvantage is that with this config nothing goes in Schemas of swagger ui interface... I still try to figure out why ... @valasatava do you have an idea how to apply @Schema(ref = ...) to a class level

**Comment by valasatava** [comment]
> One disadvantage is that with this config nothing goes in Schemas of swagger ui interface... 

I have abandoned SwaggerUI in favor of ReDoc, which has a better support for JSON Schema spec. You can see if it works better for you.

> do you have an idea how to apply @Schema(ref = ...) to a class level

not sure if annotations permit that, but I never looked into it
