### ISSUE TITLE
Spring Pageable should be broken down in its components and shouldn't be required

### ISSUE THREAD

**Issue by gotson** [springdoc/springdoc-openapi#559]
**Describe the bug**
When using a Pageable in its simple form:

```
@GetMapping("api/v1/books")
  fun getAllBooks(page: Pageable)
```

it results in the following in the Swagger UI:
<img width="254" alt="Screenshot 2020-04-12 at 16 03 07" src="https://user-images.githubusercontent.com/2139133/79063887-204dbd80-7cd7-11ea-8dd2-10bc5eab38c4.png">

This is incorrect in different ways:
- the arguments `page`, `size` and `sort` can be passed individually, not necessarily all at once, and not in an object form. I agree that when setting the object, the resulting URL is `http://localhost:8080/api/v1/books?page=0&size=0&sort=string`. However, this is confusing from a UX perspective, the `page` parameter is marked as an object, while this is clearly wrong. Spring maps 3 optional parameters to an internal object. Also the defaults are applied by Spring automatically, not at the request level, so those parameters should default to being empty.
- the parameter `page` is marked as required, while it is definitely not true. Not passing any of the `page`, `size`, and `sort` parameters result in valid queries.
- the default value of the `sort` parameter in the object (`"string"`) makes the default behavior when trying out to fail, as no field or property `"string"` is defined on the underlying repository. This is more a comment on the current behaviour. If it was working properly with 3 different optional parameters with no default value, it would work as expected.

**To Reproduce**
- What version of spring-boot you are using? `2.2.5.RELEASE`
- What modules and versions of springdoc-openapi are you using?
  - `org.springdoc:springdoc-openapi-ui:1.3.1`
  - `org.springdoc:springdoc-openapi-data-rest:1.3.1`
  - `org.springdoc:springdoc-openapi-security:1.3.1`
  - `org.springdoc:springdoc-openapi-kotlin:1.3.1`
- What is the actual and the expected result using OpenAPI Description (yml or json)? I am only looking at the resulting Swagger UI

**Comment by bnasslahsen** [comment]
@gotson, 

 You can have a look at the documentation:
- https://springdoc.org/faq.html#how-can-i-map-pageable-spring-date-commons-object-to-correct-url-parameter-in-swagger-ui

And you can have a look at code samples for many ways to achieve a better Pageable support:
 - https://github.com/springdoc/springdoc-openapi/blob/master/springdoc-openapi-data-rest/src/test/java/test/org/springdoc/api/app3/HelloController.java
 - https://github.com/springdoc/springdoc-openapi/blob/master/springdoc-openapi-data-rest/src/test/java/test/org/springdoc/api/app7/HelloController.java

**Comment by gotson** [comment]
I have a problem with the doc, because it says:

> If you use Pageable in a GET HTTP method

But by essence the 3 parameters that compose a Pageable **are** GET parameters.

It also poses a problem: by default the behaviour is broken and doesn't mean anything, and one need to add some extra parameters to make it work as it should.

`@ParameterObject` and `@PageableAsQueryParam` work, but it requires to add them on every single methode using Pageable.

Those should be the default, since the existing default makes no sense.

**Comment by bnasslahsen** [comment]
The doc says:  The replacement of `@PageableAsQueryParam` by `@ParameterObject` is valid for HTTP GET methods.  Its speciffic to the role of @ParameterObject.

If you feel you have any better enhancements, please feel free to contribute.

**Comment by gotson** [comment]
What I don't understand is why there is a need for those annotations? The default behavior should be to show 3 parameters that are optional, same as with 

I don't understand which use case does the default address exactly, would you be able to explain in which instance would someone want to have a Pageable object in their api specification, which doesn't exist as parameter in Spring?

**Comment by bnasslahsen** [comment]
Nothing prevent from other usages of Pageable. That's why we need to keep flexibility on the generated OpenAPI description.

By default, the generated object is passed as query param of type object (which is also correct).

Now, if people want to have some  handy display on swagger-ui, they can use @PageableAsQueryParam.

And as mentionned on the previous post, If you feel you have any better enhancements or ideas, please feel free to contribute.

**Comment by gotson** [comment]
I understand your point, but I am dubious about the use you mention, because Pageable in Spring is a repository convenience, with argument resolvers to map the 3 params to an instance of Pageable when passed in a url.

Maybe we could have a globale configuration property to switch the behavior to something similar to what @ParameterObject does, but without having to specify the annotation on each and every Pageable in the application.

Even better, this configuration could be set to true by default, and if someone really want to use a Pageable as an object parameter, they could change the configuration to false.
