### ISSUE TITLE
Add support kotlin Flow as response type

### ISSUE THREAD

**Issue by DVMaslov** [springdoc/springdoc-openapi#560]
example:
```
fun list(): kotlinx.coroutines.flow.Flow = ...
```

**Comment by bnasslahsen** [comment]
@DVMaslov, 


 You can have a look at the contribution guide (section **Using GitHub Issues**) before opening any feature or bug request:
- https://github.com/springdoc/springdoc-openapi/blob/master/CONTRIBUTING.adoc

If you provide a complete description, your ticket will be reopened.

**Comment by DVMaslov** [comment]
**versions**
spring boot 2.2.6
webFlux
// springdoc dependencies
implementation("org.springdoc:springdoc-openapi-webflux-ui:1.3.1")
implementation("org.springdoc:springdoc-openapi-kotlin:1.3.1")

I use kotlin coroutines in my WebFlux application:
https://spring.io/blog/2019/04/12/going-reactive-with-spring-coroutines-and-kotlin-flow

So I use Flow instead of Flux.

**Expected behaviour:** 
Flow is represented in swagger similarly to Flux

**Comment by bnasslahsen** [comment]
@DVMaslov, 

  The support is now add. You can validate it with the last SNAPSHOT:
 - https://springdoc.org/faq.html#how-can-i-use-the-last-springdoc-openapi-snapshot-

 It will be available for the next release v1.3.3
