### ISSUE TITLE
Pageable required

### ISSUE THREAD

**Issue by kfirfer** [springdoc/springdoc-openapi#561]
Hello

I'm using springdoc-openapi-ui  version 1.3.2
& springdoc-openapi-data-rest  1.3.2

And I encountered that "Pageable"  parameters size, page and sort are required
I can see it here:
https://github.com/springdoc/springdoc-openapi/blob/master/springdoc-openapi-data-rest/src/main/java/org/springdoc/data/rest/converters/Pageable.java

Does it should be required? 
If I don't pass them , spring inject its defaults values and can be overriden from äpplication.yaml:   
`
spring:
  data:
    rest:
      default-page-size: 20
      max-page-size: 1000
 `

**Comment by bnasslahsen** [comment]
Hi @kfirfer, 

 Yes, the Pageable attributes are required. 
 But there are default values already set, on the swagger-ui.

**Comment by kfirfer** [comment]
the sort is also required and quite annoying to set it with empty value in order to fire a request , also if I override the default values in spring application.yaml it is not reflected in the defaults of Pageable

**Comment by kfirfer** [comment]
I dont think the attributes should be required , since spring make the defaults by its own

**Comment by kfirfer** [comment]
I think the best solution is to give the user to decide the parameters in the object

**Comment by bnasslahsen** [comment]
@kfirfer, 

 If you can see this request, it explains why we have these constaints.
 - https://github.com/springdoc/springdoc-openapi/issues/499

 Even all these attributes (page, sort, size) **must not be null**, spring-data manages to fill them with default values if absent.

 You are right, that it makes more sense to give flexibility to the user to decide.
 The change, will be available for the next release: v1.3.3.
