### ISSUE TITLE
external articles:

### ISSUE THREAD

**Issue by raghuraman1** [springdoc/springdoc-openapi#564]
Hi All,
@bnasslahsen 
How can one give references to external articles example:
https://dzone.com/articles/openapi-3-documentation-with-spring-boot
This is an introductory article.
Will be writing a part II also.
Just bringing to your notice.  Please delete ticket as u deem fit.
If possible share a reference to the article.
Thanks.
Raghu

**Comment by bnasslahsen** [comment]
Hi @raghuraman1, 

 Thank you for this interesting tutorial.
 I have added a link on the FAQ, as it will be useful for developers who looks for a tutorial, step by step for using the libreary.

**Comment by raghuraman1** [comment]
Part II is coming with FQN and controller advice
