### ISSUE TITLE
@RestControllerAdvice and @ResponseStatus(HttpStatus.OK) overriding default response for @RestController methods

### ISSUE THREAD

**Issue by mmateyak** [springdoc/springdoc-openapi#565]
Springdoc v1.3.3-SNAPSHOT (and lower)

Issue with @RestControllerAdvice usage whereas @RestControllerAdvice methods annotated with @ResponseStatus(HttpStatus.OK) gain precedence in default response schemas for all @RestController methods, even if the @RestController methods are also explicitly annotated with or without @ResponseStatus(HttpStatus.OK)

In my case I override a certain Java exception with an HttpStatus.OK because I want to treat it as an acceptable condition.  To illustrate/simplify as a hypothetical example, if I wanted to return an HttpStatus.OK for a NullPointerException, I could define a @RestControllerAdvice method as follows:

```
	@ExceptionHandler(value={NullPointerException.class})
	@ResponseStatus(HttpStatus.OK)
	public NullPointerException handleNullPointerException(final NullPointerException ex, HttpServletRequest request, HttpServletResponse response) throws IOException{
		return ex;
	}	
```

Which will yield the following schema for a @RestController endpoint method (say /xyz):

```
cause | {...}
-- | --
stackTrace | [...]
message | string
localizedMessage | string
suppressed | [...]
```

However if I comment out the @ResponseStatus(HttpStatus.OK) in that method declaration as follows:

```
	@ExceptionHandler(value={NullPointerException.class})
	//@ResponseStatus(HttpStatus.OK)
	public NullPointerException handleNullPointerException(final NullPointerException ex, HttpServletRequest request, HttpServletResponse response) throws IOException{
		return ex;
	}	
```

Then the default response schema is correct for my @RestController endpoint methods:

```
property0 | [...]
-- | --
intProperty0 | integer($int32)
intproperty1 | integer($int32)
```

Is there a way to override the default handling/precedence or is documenting @RestController methods fully with comprehensive annotations the only way?

**Comment by bnasslahsen** [comment]
@mmateyak,

 You can add `@ApiResponse` on the top of your methods, of your controller advice, it will be used instead.

Also, you have another solution to use; `springdoc.override-with-generic-response`,  so that  springdoc-openapi will only add all generic responses if no `@ApiResponse` annotation is present on an operation of your cnotroller.

**Comment by mmateyak** [comment]
In this case, I already have the following set in my config trying to avoid generic responses from being generated, but the results are the same whether true or false.

```
springdoc.override-with-generic-response=false
```
Worth noting, I'm trying to document over 200 endpoints in this case and as much as I can automate with defaults initially would be beneficial.  In my case, unfortunately the @RestControllerAdvice is gaining precedence in default responses of all @RestController methods because the @RestControllerAdvice has a response with @ResponseStatus(HttpStatus.OK).  

Generally all exceptions are handled by the @RestControllerAdvice, while @RestController handles returning @ResponseStatus(HttpStatus.OK) for all methods/endpoints.  In my case, since I have that one @RestControllerAdvice method that responds with a @ResponseStatus(HttpStatus.OK), it results in losing the default parsing/identification by SpringDoc of @ResponseStatus(HttpStatus.OK) across all @RestController methods.  That's really the key observation of what I'm experiencing.

One option as you mentioned is to add an @ApiResponse definition for every @RestController method to explicitly define the @ResponseStatus(HttpStatus.OK) condition for SpringDoc to recognize properly.

The other option is to handle any @ResponseStatus(HttpStatus.OK) rendering exceptions in a try/catch of the corresponding @RestController methods that potentially throw that type of exception and explicitly return a @ResponseStatus(HttpStatus.OK) within those @RestController methods, thereby avoiding the use and definition of @ResponseStatus(HttpStatus.OK) within @RestControllerAdvice entirely.  This would allow all @RestController methods to implicitly acquire the default handling of their response object for @ResponseStatus(HttpStatus.OK) in respect to SpringDoc's parsing/documentation generation.

Hopefully that clarifies things from my end, but if you have any questions around the above, please let me know.  IMO it may be worthwhile to review the prioritizing of default response documentation generation from a Springdoc perspective relative to @ControllerAdvice/@RestControllerAdvice, as it would be more consistent to manage all exceptions within that singular class.  However, there are workable alternate solutions as mentioned above to achieve the same desired behavior.

Thanks again for the quick review!
