### ISSUE TITLE
Wrong hateoas relation

### ISSUE THREAD

**Issue by davidepedone** [springdoc/springdoc-openapi#566]
I've added springdoc-openapi-data-rest dependency (v1.3.2) to my project based on spring boot 2.2.6.RELEASE and hateoas relation in response are changed from:
`{
  "_embedded" : {
    "entityNameList" : [ {...}]
}`
to:
`{
  "_embedded" : {
    "entityName" : [ {...}]
}`

**Comment by bnasslahsen** [comment]
@davidepedone, 

 Your description is not enough to address:
 
 This ticket will be closed, and there is no need to reopen a new open for the same issue.
 If you are reporting a bug, please help to speed up problem diagnosis by providing as much information as possible: You can update your ticket with the necessary information and it will be reopened.

 Please have a look at the contribution guide section Using GitHub Issues:
- https://github.com/springdoc/springdoc-openapi/blob/master/CONTRIBUTING.adoc

**Comment by davidepedone** [comment]
@bnasslahsen sorry, here an updated and compliant description of the issue:

You can find a sample code [here](https://github.com/davidepedone/springdoc-openapi-566)

- spring boot version v2.2.6
- springdoc-openapi-ui v1.3.8
- springdoc-openapi-security v1.3.8

With this configuration calling the controller will produce a response like this:
```javascript
{
    "_embedded": {
        "postList": [
            {
                "author": "Baylee Lindgren",
                "content": "Adipisci nihil nemo non libero et minus. Dignissimos enim delectus soluta quos ut. Consequatur impedit est. Molestiae inventore qui exercitationem excepturi est quia. In vel qui inventore dolor est.",
                "createdAt": 1588226024153,
                "id": "5eb16ab40dc0546717ce7dc9"
            }
        ]
    },
    "_links": {
        "first": {
            "href": "http://127.0.0.1:8080/?page=0&size=1"
        },
        "last": {
            "href": "http://127.0.0.1:8080/?page=32&size=1"
        },
        "next": {
            "href": "http://127.0.0.1:8080/?page=1&size=1"
        },
        "self": {
            "href": "http://127.0.0.1:8080/?page=0&size=1"
        }
    },
    "page": {
        "number": 0,
        "size": 1,
        "totalElements": 33,
        "totalPages": 33
    }
}
```
So far so good, but the OpenApi description is wrong:
```javascript
[...]
            "PagedModelPostResource": {
                "properties": {
                    "content": {
                        "items": {
                            "$ref": "#/components/schemas/PostResource"
                        },
                        "type": "array"
                    },
                    "links": {
                        "items": {
                            "$ref": "#/components/schemas/Link"
                        },
                        "type": "array"
                    },
                    "page": {
                        "$ref": "#/components/schemas/PageMetadata"
                    }
                },
                "type": "object"
            }
[...]
```
So I've added the module springdoc-openapi-data-rest v1.3.8.
Here the new response from controller:
```javascript
{
    "_embedded": {
        "posts": [
            {
                "author": "Ada Kuhlman",
                "content": "Asperiores enim maiores. Quia natus quaerat. Suscipit libero quae reiciendis expedita facilis. Magni quam suscipit provident ut. Tempore ipsum ut accusantium consectetur sequi.",
                "createdAt": 1567161997761,
                "id": "5eb16c381442a77050d91fd7"
            }
        ]
    },
    "_links": {
        "first": {
            "href": "http://127.0.0.1:8080/?page=0&size=1"
        },
        "last": {
            "href": "http://127.0.0.1:8080/?page=32&size=1"
        },
        "next": {
            "href": "http://127.0.0.1:8080/?page=1&size=1"
        },
        "self": {
            "href": "http://127.0.0.1:8080/?page=0&size=1"
        }
    },
    "page": {
        "number": 0,
        "size": 1,
        "totalElements": 33,
        "totalPages": 33
    }
}
```
and OpenApi description:
```javascript
[...]
            "PagedModelPostResource": {
                "properties": {
                    "_embedded": {
                        "properties": {
                            "postResources": {
                                "items": {
                                    "$ref": "#/components/schemas/PostResource"
                                },
                                "type": "array"
                            }
                        },
                        "type": "object"
                    },
                    "_links": {
                        "$ref": "#/components/schemas/Links"
                    },
                    "page": {
                        "$ref": "#/components/schemas/PageMetadata"
                    }
                },
                "type": "object"
            },
[...]
```
As you can see the response from the controller is changed from
`{ "_embedded" : { "postList" : [ {...}] }`
to:
`{ "_embedded" : { "posts" : [ {...}] }`
and OpenApi description property is also wrong (postResources).

**Comment by valentinabojan** [comment]
This is something that I also noticed and I discovered that is because springdoc-openapi-data-rest comes with the following dependency:
```
<groupId>org.atteo</groupId>
<artifactId>evo-inflector</artifactId>
```

This will make the fields in the response type use the plural form (ie. posts in your example instead of postList). For me, the solution was to exclude that dependency when using springdoc-openapi-data-rest:
```
<dependency>
                <groupId>org.springdoc</groupId>
                <artifactId>springdoc-openapi-data-rest</artifactId>
                <version>${springdoc-openapi.version}</version>
                <exclusions>
                    <exclusion>
                        <groupId>org.atteo</groupId>
                        <artifactId>evo-inflector</artifactId>
                    </exclusion>
                </exclusions>
            </dependency>
```

**Comment by davidepedone** [comment]
@valentinabojan excluding evo-inflector works fine for controller but not for OpenApi description that become `postResourceList`

**Comment by davidepedone** [comment]
I guess I've figured out the issue.
I have defined a [PostResource](https://github.com/davidepedone/springdoc-openapi-566/blob/master/src/main/java/it/dpedone/openapi/hateoas/PostResource.java) class that is useless.
Deleting this class and change [PostResourceAssembler](https://github.com/davidepedone/springdoc-openapi-566/blob/master/src/main/java/it/dpedone/openapi/hateoas/PostResourceAssembler.java) from
`public class PostResourceAssembler implements RepresentationModelAssembler<Post, PostResource> {`
to
`public class PostResourceAssembler implements RepresentationModelAssembler<Post, EntityModel<Post>> {`
and excluding evo-inflector as suggested by @valentinabojan solved the issue.

**Comment by bnasslahsen** [comment]
@davidepedone and @valentinabojan, 

 Thank you for your feedback.
 I guess, for projects relying only spring-hateoas and not on spring-data-rest-core, it would be useful to update the documentation to exclude evo-inflector.

 The ideal would be to split springdoc-openapi-data-rest into two modules which will make the integration easier for spring-hateos projects:
- One module for spring-hateos
- And another module for spring-data-rest

**Comment by bnasslahsen** [comment]
Starting from the next release v1.3.10,  the projects that rely on spring-hateoas **only**, can use:  

- The new dependency springdoc-openapi-hateoas so they won't have to exclude evo-inflector jar.

```xml
		<dependency>
			<groupId>org.springdoc</groupId>
			<artifactId>springdoc-openapi-hateoas</artifactId>
			<version>${springdoc.version}</version>
		</dependency>
```

The projects that rely on spring-data-rest can keep using springdoc-openapi-data-rest. 
This enhancement will not be a breaking change, as springdoc-openapi-data-rest will depend on springdoc-openapi-hateoas.

Any project that was already using springdoc-openapi-data-rest dependency can keep using it.
