### ISSUE TITLE
HttpServletRequest and HttpServletResponse params are not ignored

### ISSUE THREAD

**Issue by anzap** [springdoc/springdoc-openapi#57]
If i have an api method like the following:

```
@Operation(description = "Just an example")
@GetMapping("/v1/example")
public ResponseDTO getExample(
            final RequestDTO request,
            final HttpServletRequest httpReq, final HttpServletResponse httpResp, final Locale locale) { .... }
```

I would expect httpReq and httpResp to be ignored on the generated documentation, but this is not the case.
Locale is indeed ignored as it should.

Edit:
Note that adding @Parameter(hidden=true) does indeed solve the issue, but it would be nice for this to be handled automatically as the Locale param is.

**Comment by springdoc** [comment]
Hi, 

 HttpServletResponse and HttpServletResponse will be added to the list of ignored types.
 This will be available on v1.1.25 of springdoc-openapi.

**Comment by anzap** [comment]
Nice and thanks for your effort on this project.
Also created PR #58 for this.

**Comment by leoherbie** [comment]
Duplicate Issue: https://github.com/springdoc/springdoc-openapi/issues/42
