### ISSUE TITLE
Question/Help with debugging

### ISSUE THREAD

**Issue by dlamoris** [springdoc/springdoc-openapi#571]
I have a SpringBoot 2.1.x app that pulls in a fair number of libraries and configurations. I suspect some combination is interfering with some aspects of the springdoc generator (and openapi 3 annotations), but not sure how to debug it. Can you offer some insight of what to look for? The following issues I'm seeing works fine in a minimal spring boot app.

Would appreciate any insight on how to proceed, thanks.

This is the app that currently works fine with springdoc - 
https://github.com/Open-MBEE/mms/tree/feature/openapi-hardening/example

It's using 
springdoc-ui 1.3.1 
springdoc-security 1.3.1
spring boot starter web 2.1.7
as well as imported dependencies that include spring-data-jpa, spring-ldap, spring-security, jackson annotations

I can download an expected api-docs.yaml and the springdoc swagger ui shows up correctly.
example of a controller: https://github.com/Open-MBEE/mms/blob/feature/openapi-hardening/crud/src/main/java/org/openmbee/sdvc/crud/controllers/elements/ElementsController.java

1st problem:
If I uncomment the `@SecuritySchemes` part of 
https://github.com/Open-MBEE/mms/blob/feature/openapi-hardening/example/src/main/java/org/openmbee/sdvc/example/ExampleApplication.java

The yaml no longer has any security schemes defined and the ui doesn't display any Authorize button

2nd problem:
If i add `name="Org"` to the `@Schema` annotation to this 
https://github.com/Open-MBEE/mms/blob/feature/openapi-hardening/json/src/main/java/org/openmbee/sdvc/json/OrgJson.java
or any `@Schema(name = "SomeName")` to any of the classes in that package, the swagger-ui hangs in showing and trying to get /v3/api-docs.yaml or /v3/api-docs.json results in no response

Again, all these problems go away in a minimal spring boot app without all the configurations and dependencies pulled in. Since the problematic app I linked to is not trivial to setup, are there any known conflicts or interactions that might cause this behavior that I can look into? I am using Intellij and would be fine with putting breakpoints on any lines that can help with debugging.

Thanks

---
steps to run the application:

copy https://github.com/Open-MBEE/mms/blob/feature/openapi-hardening/example/src/main/resources/application.properties.example to application.properties

run `docker run -e POSTGRES_PASSWORD=test1234 -e POSTGRES_USER=mmsuser -e POSTGRES_DB=mms -p 5432:5432 postgres:9-alpine`

run `../gradlew bootRun` under https://github.com/Open-MBEE/mms/tree/feature/openapi-hardening/example

`http://localhost:8080/v3/swagger-ui.html` should work fine, then if the 1st problem is uncommented or 2nd problem is added, the result would be as described

**Comment by bnasslahsen** [comment]
Would be happy to offer some insight, if your description is clear, which is not the case.
Please respect the template provided for opening issues.

And you can follow the contribution guide / section github issues: If you are reporting a bug, please help to speed up problem diagnosis by providing as much information as possible:


- https://github.com/springdoc/springdoc-openapi/blob/master/CONTRIBUTING.adoc

**Comment by dlamoris** [comment]
sorry, I didn't think it counted as a bug report or a feature request, will be editing the original comment with more info

**Comment by bnasslahsen** [comment]
Hi @dlamoris, 

 Wecouldn't run your project unfortunately.
 If you have a **Minimal**, Complete, and Verifiable example, would be happy to have a look again.

**Comment by ShebSid** [comment]
Hi @dlamoris,
have you found the root cause of your first problem. please let me know as I am also facing the same trouble with securitySchemes.
