### ISSUE TITLE
failed load group api behind reverse proxy

### ISSUE THREAD

**Issue by DVMaslov** [springdoc/springdoc-openapi#575]
**versions**
spring-boot 2.2.6
webflux
"org.springdoc:springdoc-openapi-webflux-ui:1.3.1")
"org.springdoc:springdoc-openapi-kotlin:1.3.1")

**settings**
x-forwarded-prefix enabled in ingress
server.forward-headers-strategy=framework

no additional settings in application.yml for springdoc

group api config
```
   @Bean
    fun publicApi(): GroupedOpenApi =
            GroupedOpenApi.builder()
                    .setGroup("my-public-api")
                    .pathsToMatch("/api/v*")
                    .build()
```

**description**
my application deployed on kubernetes: http://k8s/some-ns/appname/*
1. go to - http://k8s/some-ns/appname/swagger-ui.html
2. redirect - http://k8s/some-ns/appname/webjars/swagger-ui/index.html?configUrl=/some-ns/appname/v3/api-docs/swagger-config
3. load http://k8s/some-ns/appname/v3/api-docs/swagger-config
```
{
  "configUrl": "/some-ns/appname/v3/api-docs/swagger-config",
  "oauth2RedirectUrl": "http://k8s/webjars/swagger-ui/oauth2-redirect.html",
  "urls": [
    {
      "url": "/v3/api-docs/my-public-api",
      "name": "my-public-api"
    }
  ],
  "validatorUrl": ""
}
```
4. then failed get http://k8s/v3/api-docs/my-public-api

On 4 step lost x-forwarded-prefix.

**Comment by qanik1307** [comment]
Have you tried adding a ForwardedHeaderTransformer bean to your application context? I have a similiar setup with Traefik as a path based reverse proxy.

**Comment by bnasslahsen** [comment]
@DVMaslov, 

 You can have a look at the documentation and your own proxy configuration:
 - https://springdoc.org/faq.html#how-can-i-deploy-the-doploy-springdoc-openapi-ui-behind-a-reverse-proxy

 There no known issues while deploying the swagger-ui in k8s.

**Comment by DVMaslov** [comment]
@bnasslahsen,

I followed the instructions.
I enable `server.forward-headers-strategy=framework` in spring and  `x-forwarded-prefix` in ingress.

After that steps 1,2 and 3 work correctly.
But I got an error after adding `GroupedOpenApi`.

If I delete `GroupedOpenApi` I get the correct result.

Maybe I should add additional settings when creating a group? Unfortunately I didn't find anything about this in the documentation

**Comment by bnasslahsen** [comment]
@DVMaslov, 

 Please review your configuration;  It works with and without GroupedOpenApi.

 FYI all the demo applications are deployed using kuberntes on a cloud provider. (You can have a look at https://springdoc.org/. 
 And its already tested against different cloud providers.

**Comment by valkuc** [comment]
The problem is solved. Issue was in ingress configuration. `/v3/api-docs/swagger-config` has been rewrited to `/v3/api-docs` causing weird behavior. Sorry for inconvenience.
