### ISSUE TITLE
Adding Actuator as a groupedOpenApi ?

### ISSUE THREAD

**Issue by yawyaw1** [springdoc/springdoc-openapi#577]
Hi 
Could we add Actuator endpoints as a groupedOpenApi that will be gourped separately ?   

ex :
 @Bean
    public GroupedOpenApi actuatorApi() {
        return GroupedOpenApi.builder().setGroup("Actuator")
                .packagesToScan("org.springframework.boot.actuate")
                .pathsToMatch("/actuator/**")
                .build();
    }

Thanks

**Comment by bnasslahsen** [comment]
Hi @yawyaw1, 

 Using the definition you shared, we can add actuator as GroupedOpenAPI.
 Depending on project requirements, they can add it.

**Comment by yawyaw1** [comment]
Hi @bnasslahden,

Thank you for your answer, however i was wondering if there is a way to handle this like swagger 2 by implementing The Swagger OperationBuilderPlugin in order to expose it ?

Thanks

**Comment by bnasslahsen** [comment]
@yawyaw1, 

 We do not have such a class while using OpenAPI 3.
 GroupedOpenAPI, is enough.

**Comment by yawyaw1** [comment]
I think GroupedOpenApi can't handle this right now, cause it needs the package to scan where is the openApi annonation in order to expose the endpoits !
And we don't have access to actuator's package so it will never happen.

**Comment by bnasslahsen** [comment]
Your description is not clear. GroupedOpenApi is working with actuator and you can simply set your own group.

If you think there is any issue with it using actuator, you can submit more details by describing all the elements described in the section Using GitHub Issues. 
- https://github.com/springdoc/springdoc-openapi/blob/master/CONTRIBUTING.adoc

**Comment by yawyaw1** [comment]
Could you provide me an example of groupedOpenApi using actuator, please 
Because when i set my own group for actuator 

   ```
@Bean
    public GroupedOpenApi actuatorApi(){
        String[] paths = {"/actuator/**"};
        return GroupedOpenApi.builder()
                .setGroup("groups")
                .pathsToMatch(paths)
                .build();
    } 
```

i get an empty page with the message **No operations defined in spec!** as displyed on the image
![img](https://user-images.githubusercontent.com/10889896/79644650-9015e980-81aa-11ea-9486-1d60e7c0c2ff.png)

**Comment by bnasslahsen** [comment]
Did you add ` springdoc.show-actuator=true` ?

**Comment by yawyaw1** [comment]
Yes

**Comment by bnasslahsen** [comment]
And you still didn't succeed ?

**Comment by yawyaw1** [comment]
No, always an empty page, and i don't know how to display it

**Comment by bnasslahsen** [comment]
You can have a look at the demo2, which is using actuator as a group.
- https://github.com/springdoc/springdoc-openapi-demos/tree/master/springdoc-openapi-test-app2

Here are the steps of using actuator:
- https://github.com/springdoc/springdoc-openapi-demos/commit/aa6bcf1f0312c8fc36f94aeb4653718b36c308f6

**Comment by yawyaw1** [comment]
Now, it's working, the problem was related to my version 1.2.22, i change it to 1.3.0 and it seems ok 

Thank you @bnasslahsen apreciate
