### ISSUE TITLE
Issue with displaying generics model and return type in Swagger UI

### ISSUE THREAD

**Issue by tonjack** [springdoc/springdoc-openapi#578]
**Describe the bug**
We are having issues on displaying generics model as a return type for our controller in Swagger UI. Instead of showing GenericModel<Type>, it is showing GenericModelType. In Springfox, we are able to either show GenericModel<Type> or GenericModelOfType (http://springfox.github.io/springfox/docs/snapshot/#changing-how-generic-types-are-named). How can we achieve the same representation of generic model as return type using springdoc-openapi?

**To Reproduce**
- Currently using spring boot 2.2.6 with Java 11
- springdoc-openapi-ui version 1.3.0

Given this generic model:
```
public class BaseApiResponse<T> {
    private T data;
    private List<Error> errors = new ArrayList();
    private List<Message> messages = new ArrayList();
}
```
When we are returning the following type in our controller:
```
public ResponseEntity<BaseApiResponse<Account>> get(@PathVariable Long id) throws ResourceNotFoundException {
}
```
The schema created in the Swagger UI and API-docs for the return type is:
BaseApiResponseAccount instead of BaseApiResponse<Account>.

**Expected behavior**
We should expect similar behaviour as in Springfox (http://springfox.github.io/springfox/docs/snapshot/#changing-how-generic-types-are-named), where Swagger UI should either display BaseApiResponse<Account> or BaseApiResponseOfAccount

**Comment by bnasslahsen** [comment]
@tonjack, 

 This is not an issue on springxdoc-openapi. We only rely on standard OpenAPI 3 and official swagger jars.
 The generated OpenAPI description is Valid.

 The behaviour you are expecting, is not supported natively, by the API.
 There is already an Open issue on swagger-core, similar to the behaviour you are expecting:
 - https://github.com/swagger-api/swagger-core/issues/3323

**Comment by idkw** [comment]
This is really bad compared to what springfox was about to do :/
The issue on swagger-core has not been updated for years.
Can something be done on springdoc side like what springfox did by auto-generating a model like BaseApiResponseOfAccount ?

Currently the only workaround I've found is to create subclasses of such generic class.
Here following the example of @tonjack  it would be  : 


``` 
public class BaseApiResponseOfAccount extends BaseApiResponse<Account> {
}

public ResponseEntity<BaseApiResponseOfAccount> get(@PathVariable Long id) throws ResourceNotFoundException {
}
```

And with that, springdoc generates a good spec. 
Is there a way springdoc could do that automatically ?
