### ISSUE TITLE
Feature request: Ignore inheritance fields

### ISSUE THREAD

**Issue by kfirfer** [springdoc/springdoc-openapi#579]
Hello

I don't know if it already exists, was searched in the docs but didn't found any,

It will be very useful if there was a way to ignore inherited properties to get rendered

Found some old conversation about it in the core of swagger, not sure if its relevant:
https://github.com/swagger-api/swagger-core/issues/730

Using: springdoc openapi ui version 1.3.2
and spring boot 2.2.6

**Comment by bnasslahsen** [comment]
Hi @kfirfer, 

 This is the responsability of swagger-core, and not springdoc-openapi.
 Ideally, it should be added on @Schema OAS3 annotation.

 For the moment, all what you can do is adding @Schema(hidden = true) no the properties that you want to ignore from the superclass.

**Comment by kfirfer** [comment]
Yes you right but it is superclass of third party libraries
Ok ... nevermind =X I will figure it out ... thnx
