### ISSUE TITLE
Support @RequestMapping.param for overloaded endpoints

### ISSUE THREAD

**Issue by pcalouche** [springdoc/springdoc-openapi#580]
I saw this issues was marked as won't fix here https://github.com/springdoc/springdoc-openapi/issues/15, but I think there are valid uses cases for it and Spring supports it.  Springfox also supported this as well.

For example

```java
// handle save draft of audit
@PatchMapping(value = "/audits/{auditId}", params = "action=saveDraft")
public AuditDto saveDraft(@PathVariable int auditId, @RequestBody AuditPatchRequest auditPatchRequest) {
}

// save audit and mark it as reviewed
@PatchMapping(value = "/audits/{auditId}", params = "action=markReviewed")
public AuditDto markedReviewed(@PathVariable int auditId, @RequestBody AuditPatchRequest auditPatchRequest) {
}

// marks audit as complete, but makes no other changes
@PatchMapping(value = "/audits/{auditId}", params = "action=markComplete")
public AuditDto markComplete(@PathVariable int auditId) {

}
```

I would expect to see these endpoints generated in the documentation:

PATCH /audits/{auditId}?action=saveDraft
PATCH /audits/{auditId}?action=markReviewed
PATCH /audits/{auditId}?action=markComplete

I'm open to an alternate way to do handle such endpoints if you can suggest one along with constructive criticism as to why may not be good REST API practice.  Keep up the good work.

**Comment by bnasslahsen** [comment]
@pcalouche, 

 With OpenAPI 3, you can not have 3 endpoints for the same path:
 You will have one endpoint et only one OpenAPI description.
```
paths:
  '/audits/{auditId}':
    patch:
```

 What you can do is add the `@Operation` annotation on the top of one of the methods, where you add the OpenAPI documentation of the merged OpenAPI description of all your other methods as well  and add the `@Hidden` annotation on the two others
