### ISSUE TITLE
Default value 0 not show in swagger field

### ISSUE THREAD

**Issue by DVMaslov** [springdoc/springdoc-openapi#582]
**versions**
spring boot 2.2.6
implementation("org.springdoc:springdoc-openapi-webflux-ui:1.3.1")    implementation("org.springdoc:springdoc-openapi-kotlin:1.3.1")

**controller**
```
@GetMapping
    suspend fun some(
            @RequestParam("from", defaultValue = "0") from: Int,
            @RequestParam("to", defaultValue = "50") to: Int
    ) = flow {
        for (i in from..to) {
            emit(i)
        }
    }
```

**swagger**
<img width="451" alt="image" src="https://user-images.githubusercontent.com/6560360/79629229-6b8d2380-8150-11ea-967d-8f4f058f074f.png">

**expected**
Field "from" must have 0 as in field "to" have 50

**Comment by bnasslahsen** [comment]
@DVMaslov, 

 springdoc-openapi is build on top of swagger libraries.
 springdoc-openapi generates correctly the default value as 0, if you have a look at the /v3/api-docs.

 This is a known issue in swagger-ui, here are some references that you can follow:
- https://github.com/swagger-api/swagger-ui/issues/5573
- https://github.com/swagger-api/swagger-ui/issues/5920
- https://github.com/swagger-api/swagger-ui/issues/5950
