### ISSUE TITLE
get wrong config when upgrade 1.2.34

### ISSUE THREAD

**Issue by liaow** [springdoc/springdoc-openapi#584]
**Describe the bug**
- visit gateway service url `/v3/api-docs/swagger-config` return a wrong urls when i upgraded springdoc to 1.2.34:
```json
{
    "configUrl": "/v3/api-docs/swagger-config", 
    "oauth2RedirectUrl": "http://localhost:8060/v3/api-docs/swagger-config/webjars/swagger-ui/oauth2-redirect.html", 
    "url": "/v3/api-docs", 
    "validatorUrl": ""
}
```
Btw, the right urls is :
```json
{
    "configUrl": "/v3/api-docs/swagger-config", 
    "oauth2RedirectUrl": "http://localhost:8060/v3/api-docs/swagger-config/webjars/swagger-ui/oauth2-redirect.html", 
    "urls": [
        {
            "url": "/v3/api-docs/department", 
            "name": "department"
        }, 
        {
            "url": "/v3/api-docs/employee", 
            "name": "employee"
        }, 
        {
            "url": "/v3/api-docs/organization", 
            "name": "organization"
        }
    ], 
    "validatorUrl": ""
}
```

**To Reproduce**
- clone example repo  https://github.com/piomin/sample-spring-microservices-new
- run example repo config-service, discovery-server and gateway-service
- http://localhost:8060/swagger-ui.html

**Expected behavior**
- it works when revert [this commit](https://github.com/springdoc/springdoc-openapi/commit/f4943466e90884148ed9bc8920675ab6c6b8fc01) codes below :
```java 
# GroupedOpenApi.java L52
	SwaggerUiConfigProperties.addGroup(this.group);

# SwaggerUiConfigProperties.java L149
	private static Set<SwaggerUrl> urls = new HashSet<>();

# SwaggerUiConfigProperties.java L155
	public static void addGroup(String group) {
		SwaggerUrl swaggerUrl = new SwaggerUrl(group);
		urls.add(swaggerUrl);
	}
```

**Screenshots**
wrong:
<img width="1439" alt="wrong" src="https://user-images.githubusercontent.com/3170158/79690301-4ac9e880-828c-11ea-837e-33206174ce13.png">

right:
![image](https://user-images.githubusercontent.com/3170158/79690312-5cab8b80-828c-11ea-94dd-3d7609670d97.png)

**Comment by bnasslahsen** [comment]
Hi @liaow, 

Hi 

 Before, there was a high coupling between GroupedOpenApi and SwaggerUiConfigProperties, which is ugly, using static references and difficult to maintain.
 Here is a better configuration for your gateway, while you upgrade to v1.3.4:

  
```java
@Bean
public List<GroupedOpenApi> apis(SwaggerUiConfigProperties swaggerUiConfigProperties) {
	List<GroupedOpenApi> groups = new ArrayList<>();
	List<RouteDefinition> definitions = locator.getRouteDefinitions().collectList().block();
	definitions.stream().filter(routeDefinition -> routeDefinition.getId().matches(".*-service")).forEach(routeDefinition -> {
		String name = routeDefinition.getId().replaceAll("-service", "");
		swaggerUiConfigProperties.addGroup(name);
		GroupedOpenApi.builder().pathsToMatch("/" + name + "/**").setGroup(name).build();
	});
	return groups;
}
 
```

**Comment by an0nh4x0r** [comment]
> 

I am getting CORS error ... API Gateway is able to open all swaggers from internal microservice but when I try to hit API's it throws CORS errors and also doesn't send all the necessary headers params to the backend.
