### ISSUE TITLE
Pageable schema is incorrect

### ISSUE THREAD

**Issue by gotson** [springdoc/springdoc-openapi#586]
**Describe the bug**
The generated schema for the Pageable object is incorrect.

Generated:
```
"Pageable": {
        "type": "object",
        "properties": {
          "page": {
            "minimum": 0,
            "type": "integer",
            "format": "int32"
          },
          "size": {
            "maximum": 2000,
            "minimum": 1,
            "type": "integer",
            "format": "int32"
          },
          "sort": {
            "type": "array",
            "items": {
              "type": "string"
            }
          }
        }
      }
```

Expected:
```
"Pageable": {
        "type": "object",
        "properties": {
          "page": {
            "minimum": 0,
            "type": "integer",
            "format": "int32"
          },
          "size": {
            "maximum": 2000,
            "minimum": 1,
            "type": "integer",
            "format": "int32"
          },
          "sort": {
            "type": "object",
            "properties": {
              "sorted": {
                "type": "boolean"
              },
              "unsorted": {
                "type": "boolean"
              },
              "empty": {
                "type": "boolean"
              }
            }
          }
        }
      }
```

This is the Pageable that is included in the ` objects, for example a Page of object.

It seems there is a conflict with the version defined [here](https://github.com/springdoc/springdoc-openapi/blob/7fa2f34253bcfcf882eea090c9f6bdb8877a4e49/springdoc-openapi-data-rest/src/main/java/org/springdoc/data/rest/converters/Pageable.java#L32) which is used to handle the `in` query parameters with `@ParameterObject`.

**To Reproduce**
- What version of spring-boot you are using? `2.2.6.RELEASE`
- What modules and versions of springdoc-openapi are you using?
```
org.springdoc:springdoc-openapi-ui:1.3.3
org.springdoc:springdoc-openapi-data-rest:1.3.3
org.springdoc:springdoc-openapi-security:1.3.3
```
- What is the actual and the expected result using OpenAPI Description (yml or json)? see above

**Comment by bnasslahsen** [comment]
@gotson, 

 There is no conflict between @ParameterObject and Pageable. You just need to combine both.
 Or you use `@PageableAsQueryParam`.
 The default springdoc-openapi implementation of Pageable, uses the generated schema you described; 

 If you need to adapt it, you can all time override it.

**Comment by gotson** [comment]
I am sorry but i don't understand what you mean.

You override the Pageable in your code so that it maps well with the query parameters `page`, `size`, and `sort`. But by doing so, the `sort` parameter is of incorrect type in the `Pageable` schema.

I am talking about operations that return a `Page<Whatever>`, for which the schema is incorrect.

It has nothing to do with with `@PageableAsQueryParam`, which by the way is marked as deprecated.

Once again, i feel like this library, even though it's helping a lot and is up to date compared to Springfox, has an incorrect default behaviour.

There shouldn't be any need to override something that is incorrect, it should be correct in the first place.

**Comment by gotson** [comment]
Note also that since your replacement of `Pageable` and `@PageableAsQueryParam` are both in the module `springdoc-openapi-data-rest` which automatically register your `Pageable` as a replacement for Spring's `Pageable`.

So if i want to use `@PageableAsQueryParam` as you suggest, the schema for `Pageable` would still be broken.

It seems you removed the deprecation on `@PageableAsQueryParam`, but i'm still confused as to why there is both `@PageableAsQueryParam` and the custom `Pageable` to be used with `@ParameterObject`.

`@PageableAsQueryParam` seems enough, and the custom `Pageable` breaks the schema.

**Comment by bnasslahsen** [comment]
The problem, is that your description is not clear and doesn't show any broken schema.

The simple way is to have a look at the contribution guide:
- https://github.com/springdoc/springdoc-openapi/blob/master/CONTRIBUTING.adoc
 And provide a Minimal, Complete, and Verifiable sample code.

 For your questions: The springdoc`Pageable` type is historically used by other applications and exists before `@PageableAsQueryParam`.

 For `@ParameterObject`, its an annotation that can be applied with other objects than Pageable, to pass them as query parameters.

**Comment by gotson** [comment]
> The problem, is that your description is not clear and doesn't show any broken schema.

i gave in the first post the current and expected schema.

To help fixing the issue, how can i use `@PageableAsQueryParam` without having your `Pageable` breaking the schema for Spring's `Pageable`, since both are in the same module?

**Comment by gotson** [comment]
I copied your code from `@PageableAsQueryParam` and removed the dependency on `springdoc-openapi-data-rest`.

You should really think about revamping `springdoc-openapi-data-rest`, it's useless as it is:
- your `Pageable`, even though it predates `@PageableAsQueryParam` as you mention, breaks the existing Spring's Pageable schema. It should be removed in favor of `@PageableAsQueryParam`.

**Comment by bnasslahsen** [comment]
Instead of giving lessons.  all time using `you...` 

You do not seem proposing any solutions/alternatives or PR.

I invite you to read the code of conduct as well, before posting any new issue:
- https://github.com/springdoc/springdoc-openapi/blob/master/CODE_OF_CONDUCT.adoc

This thread is removed as your approach is not constructive
