### ISSUE TITLE
ParameterCustomizer and @RequestParam MultiValueMap<String, String>

### ISSUE THREAD

**Issue by mmateyak** [springdoc/springdoc-openapi#587]
I have an endpoint that uses @RequestParam MultiValueMap<String, String> requestParameters and I need to resolve the actual type argument of the deepest generic in the method return type (i.e. SomeType.class) in order to do customization of the request parameters that get serialized to the springdoc openapi output based on that deepest generic's class information (annotations).

Sample endpoint:
```
@GetMapping(value = {"/some-types"})		
public ResponseEntity<SomeGenericCollection<SomeType>> getSomeTypes(@RequestParam MultiValueMap<String, String> requestParameters, HttpServletResponse response) throws Exception {
```

One possible approach is to define a component (see below) which can determine the generic return type via reflection.  Unfortunately, the deepest it will go is to the String value representation of the full typing as noted.  At that point, I could parse that String value to get the inner most type and perform whatever logic I want to customize the Parameter parameterModel based on SomeType.class.

Is this the best way to achieve this, or is there a better way within springdoc?

```
@Component
public class ParameterCustomizer implements org.springdoc.core.customizers.ParameterCustomizer {
	
	@Override
	public Parameter customize(Parameter parameterModel, MethodParameter methodParameter) {
		
		// returns org.springframework.http.ResponseEntity<SomeGenericCollection<SomeType>>
		Type type = methodParameter.getMethod().getGenericReturnType();
		
		// String value "org.springframework.http.ResponseEntity<SomeGenericCollection<SomeType>>"
		String typeName = type.getTypeName();

                // read/process SomeType.class property annotations
		// do something to the Parameter
                       
                // return updated Parameter
                return parameterModel;
	}
}
```

**Comment by bnasslahsen** [comment]
@mmateyak, 

 But frankly, if you could make @RequestParam not using maps<String, String>. (If i understand, the string of the map, might be a complex object), but reference directly the objects you would use so that the generation of the documentation can be stright forward.

 If you are not able to change your controller paramerts to be more explicit, your solution should work.

**Comment by mmateyak** [comment]
Thanks @bnasslahsen 

It's a complex underlying API that is heavily abstracted and relies on the Map (dynamic request params based off abstracted modeling), so updating every endpoint to have explicit params is a very large task and less manageable for enhancements.  I implemented a ParameterCustomizer Component while I waited to hear back and it worked out well.  It creates a coupling to the parameterModel.getName() value, however that's one place to manage the change and also forces uniformity in naming throughout all endpoints.

**Comment by mmateyak** [comment]
@bnasslahsen 

The default impl is to convert the Map to a generic set of properties folded under a single object parameter.  My customizer is able to give those individual properties more meaningful names that reflect their underlying modeling and typing but they are still wrapped by the single object parameter.  Is there a customizer available (or some other strategy) to transform the single object's properties into individual parameters?

Example of default

```
 "paths": {
    "/some-endpoint": {
      "get": {
        "tags": [
          "someController"
        ],
        "operationId": "someOperation",
        "parameters": [
          {
            "name": "requestParameters",
            "in": "query",
            "required": true,
            "schema": {
              "type": "object",
              "properties": {
                "someInteger": {
                  "type": "integer",
                  "format": "int32"
                },
                "anotherInteger": {
                  "type": "integer",
                  "format": "int32"
                },
                "someDate": {
                  "type": "string",
                  "format": "date"
                },
                "someString": {
                  "type": "string"
                },
                "someFloat": {
                  "type": "number",
                  "format": "float"
                }
                "someEnum": {
                  "type": "string",
                  "enum": [
                    "0",
                    "1",
                    "2",
                    "3",
                    "4"
                  ]
                }
...
...
...
```

Transformed to something like (pseudo, not tested):

```
 "paths": {
    "/some-endpoint": {
      "get": {
        "tags": [
          "someController"
        ],
        "operationId": "someOperation",
        "parameters": [
          {
            "name": "someInteger",
            "in": "query",
            "required": true,
            "schema": {
              "type": "integer",
              "format": "int32"
          },
          {
            "name": "anotherInteger",
            "in": "query",
            "required": true,
            "schema": {
              "type": "integer",
              "format": "int32"
          },
          {
            "name": "someDate",
            "in": "query",
            "required": true,
            "schema": {
              "type": "string",
              "format": "date"
          },
          {
            "name": "someString",
            "in": "query",
            "required": true,
            "schema": {
              "type": "string"
          },  
           {
            "name": "someFloat",
            "in": "query",
            "required": true,
            "schema": {
              "type": "number",
              "format": "float"
          },
          {
            "name": "someEnum",
            "in": "query",
            "required": true,
            "schema": {
              "type": "string",
              "enum": [
                    "0",
                    "1",
                    "2",
                    "3",
                    "4"
                ]
          }             
...
...
...
```

**Comment by mmateyak** [comment]
@bnasslahsen 

I believe I figured out the issue, both explode and style had to be explicitly set.  Both were null in the Parameter object.  

```
parameterModel.setExplode(true);
parameterModel.setStyle(StyleEnum.FORM);
```

Worth noting, these both have defaults in Swagger as folllows:

> The default serialization method is style: form and explode: true.

https://swagger.io/docs/specification/serialization/#query

**Comment by mmateyak** [comment]
@bnasslahsen 

Adding to this, the resulting spec generated with explode=true, style=StyleEnum.FORM is imported into Postman correctly (every property in the @RequestParam MultiValueMap<String, String> requestParameters is defined a distinct query param), however the resulting Swagger UI form generated from that same spec still has a single requestParameters object with N properties contained within it.  

Not sure where that leaves things or where the issue is, but that same Swagger link shows the expected behavior based on explode=true, style=StyleEnum.FORM relative to an object being as follows where the "id" object is exploded into it's containing properties (just as I see in Postman, but NOT in the Swagger UI rendering):

```
Object id = {"role": "admin", "firstName": "Alex"}
--
/users?role=admin&firstName=Alex
```
https://swagger.io/docs/specification/serialization/#query

I'll keep digging around to see if I can figure out where things are going wrong between the spec and Swagger UI, but if you have any insight, please let me know.  Thanks!
