### ISSUE TITLE
assignableTypes attribute in @ControllerAdvice

### ISSUE THREAD

**Issue by raghuraman1** [springdoc/springdoc-openapi#588]
Hi,

In case assignableTypes  is specified when creating @ControllerAdvice the swagger documentation should change the responses as specified in the @ControllerAdvice implementation selectively using assignableTypes  .

Giving an Example- @ControllerAdvice(assignableTypes = {SampleController.class})

In swagger documentation this ControllerAdvice should not affect Controllers not in the assignableTypes  list.

Also should likewise consider basePackages, basePackageClasses attribute in @ControllerAdvice

Is that a gud bug?
R

**Comment by bnasslahsen** [comment]
@raghuraman1, 

 Reading your decription, looks a good one!

**Comment by raghuraman1** [comment]
In org.springdoc.api.AbstractOpenApiResource.java in getOpenApi() method after this line
Map<String, Object> findControllerAdvice = openAPIBuilder.getControllerAdviceMap(); we could use that as an input to build 2 Map<String, Object> - one we can call genericControllerAdvice where these attributes are not set or have zero length in case of array vals. The second could be targettedControllerAdvice and you could pass it to getPaths(). Of course easier said than done. :)
Glad you liked the ticket.

**Comment by raghuraman1** [comment]
I can easily write the part where we can split findControllerAdvice into a genericControllerAdvice and a targettedControllerAdvice.  The genericControllerAdvice can be used for responseBuilder.buildGenericResponse().
That will be a partial fix. Using targettedControllerAdvice will be timeConsuming for me.

Let know if you need a hand.

**Comment by bnasslahsen** [comment]
Hi @raghuraman1, 

 If you have clearly how to fix, please feel free to contribute and propose a PR.
 You can have a look at our contribution guide:
 - https://github.com/springdoc/springdoc-openapi/blob/master/CONTRIBUTING.adoc

**Comment by raghuraman1** [comment]
Will give it a shot for partial fix. 
Can build complete fix post that.
Thanks.
Cu tomorrow.

**Comment by raghuraman1** [comment]
Hi,
Created the PR- https://github.com/springdoc/springdoc-openapi/pull/593
Thats the first improvment.
in any case its needed.
Pls review.

R
