### ISSUE TITLE
One more article

### ISSUE THREAD

**Issue by raghuraman1** [springdoc/springdoc-openapi#589]
Hi,
@bnasslahsen 

I have another[ article](https://dzone.com/articles/doing-more-with-springdoc-openapi)- Its at https://dzone.com/articles/doing-more-with-springdoc-openapi

It just now got published by Dzone.
I hope you like it and refer to it like last time in your section where you mention articles.
Its part II of last article.
Hope to write more.
Really love springdoc-openapi.
Thanks.
R

**Comment by bnasslahsen** [comment]
Ok @raghuraman1, 

 The FAQ, is now updated as well.
  - https://springdoc.org/faq.html#where-can-i-find-a-tutorial-of-using-springdoc-openapi-

 Thank you for this nice article and your contribution.

**Comment by raghuraman1** [comment]
@bnasslahsen
Thanks for the kind words. Looks like I am making you work too much on the PR. 
Next time will try to figure out how to write the test cases and make it easier for you:)
Offtopic: Wish there was some way to ping u on gitter or something like that.

**Comment by bnasslahsen** [comment]
@raghuraman1, 

 You can use: support@springdoc.org

**Comment by raghuraman1** [comment]
@bnasslahsen
Ok. I will use support@springdoc.org for reaching you when needed.
Do give a thumbs up at dzone for the articles if its not much trouble.
