### ISSUE TITLE
Parameter documentation overwritten by schema calculation based on type

### ISSUE THREAD

**Issue by antechrestos** [springdoc/springdoc-openapi#59]
Hi,

I spotted a potential issue [in AbstractRequestBuilder](https://github.com/springdoc/springdoc-openapi/blob/91c437a8b903254b9cf6fb3d885114d5167ad01e/springdoc-openapi-common/src/main/java/org/springdoc/core/AbstractRequestBuilder.java#L75)

In the following code,

```kotlin
fun list(   @Parameter(name = "trackerId", `in` = ParameterIn.PATH, required = true, schema = Schema(type = "string", example = "the-tracker-id"))
            @PathVariable trackerId: String,
            @Parameter(name = "start", `in` = ParameterIn.QUERY, required = false, schema = Schema(type = "string", format = "date-time", required = false, example = "1970-01-01T00:00:00.000Z"))
            @RequestParam(value = "start", required = false) startDate: Instant?,
            @Parameter(name = "end", `in` = ParameterIn.QUERY, required = false, schema = Schema(type = "string", format = "date-time", required = false, example = "1970-01-01T00:10:00.000Z"))
            @RequestParam(value = "end", required = false) endDate: Instant?): Collection<Result> 
```

The parameters schemas are read from documentation, yet it gets overwritten by the call to `buildParams`.

In my understanding the code should more be something like

```java
                       if (parameterDoc != null) {
				if (parameterDoc.hidden()) {
					continue;
				}
				parameter = parameterBuilder.buildParameterFromDoc(parameterDoc, null);
			}
			else if (!isParamTypeToIgnore(paramType)) {
```

For now the  `Parameter` annotation is useless as the  `Instant` calculation leads to a `int64`, whatever the documentation may be.

**Comment by springdoc** [comment]
Hi, 

 This is due to the fact that the definition of the parameter is at @RequestParam and @Parameter.  The merge of the schema definition from documentation is overriden .
 A fix for this issue will be available as part of 1.1.26.

**Comment by antechrestos** [comment]
@springdoc Thanks

**Comment by antechrestos** [comment]
@springdoc It is ok
