### ISSUE TITLE
springdoc.cache is not part of additional-spring-configuration-metadata.json

### ISSUE THREAD

**Issue by ahoehma** [springdoc/springdoc-openapi#592]
If I add this to a springboot application.yml

```
springdoc:
  cache:
    disabled: true
```

"cache" is marked as "unknown property".

I'm using spring-boot: 2.2.5.RELEASE, springdoc-openapi: 1.3.4

I checked out the current snapshot version 1.3.5-SNAPSHOT but I can't  find the
file I'm searching for :) Maybe something was changed on spring-side regarding to
the schema for metadata?

/springdoc-openapi-common/src/main/resources/META-INF/additional-spring-configuration-metadata.json

In 1.3.4 I can see this file (not on source-code-level) I looked into the "jar".

**Comment by bnasslahsen** [comment]
@ahoehma, 

 This will be fixed on the next release: v1.3.5.
