### ISSUE TITLE
Spring-weblfux/WebMvc.fn with Functional Endpoints

### ISSUE THREAD

**Issue by katielevy1** [springdoc/springdoc-openapi#594]
I see in the readme that Spring WebFlux with functional endpoint will be available soon. I'm wondering when "soon" is. I'd love to use spring docs on my kotlin webflux service for swagger but need to know the timeline of when this is planned to be completed. Thank you!!

**Comment by bnasslahsen** [comment]
@katielevy1, 

 As responded in #546, for the moment, we are still focusing on the core functionality of the library.
You can also contribute to add this support. This might accelerate the release of this functionality.

 I invite you to use #546 for any proposals, to keep the discussions in one place.

**Comment by bnasslahsen** [comment]
@katielevy1, 

 The support is added and available with the latest stable release.
