### ISSUE TITLE
Request Body for Maps not available in Swagger-UI

### ISSUE THREAD

**Issue by mburri** [springdoc/springdoc-openapi#597]
**Describe the bug**

Given a ressource that excpects a request body of the following type:
`@RequestBody HashMap<String, String> body`

The Request Body is not available in the Swagger-UI for the resource since springdoc-openapi-ui 1.3.1 
But it works in springdoc-openapi-ui 1.3.0

**To Reproduce**

- What version of spring-boot you are using?
Spring Boot 2.2.6

- What modules and versions of springdoc-openapi are you using?
1.3.1 (also tested with 1.3.4 - same issue)

- What is the actual and the expected result using OpenAPI Description (yml or json)?

the requestbody is not available in the UI - but it should be. The generated api docs is the same for springdoc-openapi-ui 1.3.0 and 1.3.1 

- Provide with a sample code (HelloController) or Test that reproduces the problem

```
    @PostMapping
    public ResponseEntity<HashMap<String, Object>> hello(@RequestBody HashMap<String, Object> map) {
        return ResponseEntity.ok(map);
    }
```
**Expected behavior**
- A clear and concise description of what you expected to happen.

When trying out the API in Swagger UI - I should be able to pass in the request body.

**Screenshots**

This is a screenshot of the resource in Swagger-UI with springdoc-openapi-ui v1.3.0:
![Request Body available (Version 1.3.0)](https://user-images.githubusercontent.com/4577216/79982694-05353780-84a7-11ea-9012-2be3e868cafe.png)

This is a screenshot of the resource in Swagger-UI with springdoc-openapi-ui v1.3.1 and above:
![Missing Request Body with Version 1.3.1 and above](https://user-images.githubusercontent.com/4577216/79982756-17af7100-84a7-11ea-8055-1f97e9a6ee77.png)
The section for the request body is missing...
**Additional context**
none

**Comment by bnasslahsen** [comment]
Hi @mburri, 

 In fact its normal that Maps are ignored:
 - https://springdoc.org/faq.html#what-are-the-ignored-types-in-the-documentation

 With v1.3.4, you have a first workaround which is:

```java
	static {
		SpringDocUtils.getConfig().removeRequestWrapperToIgnore(java.util.Map.class);
	}
```

 For your case, because if you are using `@RequestBody` spring annotation before the parameter, it shouldn't be ignored as its required by default. 
 So the behaviour you are expecting will be out of the box, starting from the next release v1.3.5.
