### ISSUE TITLE
Specify Schemes

### ISSUE THREAD

**Issue by rohitrj2ee** [springdoc/springdoc-openapi#599]
Hi,

I am trying to schemes but I am not able to figure out how that can be achieved.

I want the user to select an option to select between 'http' and 'http' from the generated server url.

```yaml
swagger: "2.0"
info:
  title: Blah
  description: >-
    Blah.
  version: 1.0.0
schemes:
  - http
  - https

**Comment by bnasslahsen** [comment]
@rohitrj2ee, 

Please have a look at the contribution guide before opening new issues:
- https://github.com/springdoc/springdoc-openapi/blob/master/CONTRIBUTING.adoc


 You can have a look at the swagger documentation. if its not enough use stackoverflow with swagger tag.
 - https://github.com/swagger-api/swagger-core/wiki/Swagger-2.X---Annotations
