### ISSUE TITLE
Cannot override OpenApiResource autoconfiguration

### ISSUE THREAD

**Issue by jryan128** [springdoc/springdoc-openapi#608]
I see that SpringDocWebFluxConfiguration has @ConditionalOnMissingBean and @ConditionalOnProperty set, but when I set the property to false, or provide a bean spring still complains:

```java
@RestController("openApiResource")
public class MyOpenApiResource {    
}
```

> The bean 'openApiResource', defined in class path resource [org/springdoc/webflux/core/SpringDocWebFluxConfiguration.class], could not be registered. A bean with that name has already been defined in file [/Users//Desktop//services//target/classes/com////controllers/MyOpenApiResource.class] and overriding is disabled.

Using Spring Boot 2.2.6
Spring Doc 1.3.4

Thank you!

**Comment by jryan128** [comment]
I see that OpenApiResource has @ConditionalOnBean directly annotated on it, and I see this in Spring Boot ConditionalOnBean java docs

> You  need to be very careful about the order in which bean definitions are  added, as these conditions are evaluated based on what has been  processed so far. For this reason, we recommend using only @ConditionalOnBean and @ConditionalOnMissingBean  annotations on auto-configuration classes (since these are guaranteed  to load after any user-defined bean definitions have been added).

Maybe we need to remove it from the class itself?

**Comment by bnasslahsen** [comment]
Hi @jryan128, 

 In fact you can override by type. But not using bean name.
 I see what you need, and it might be useful if someone want to create his own OpenApiRessource class.
 A fix will be added for the next release.
