### ISSUE TITLE
springdoc-openapi-data-rest produces broken schema (`Link` self ref) for HAL hypermedia types

### ISSUE THREAD

**Issue by ch4mpy** [springdoc/springdoc-openapi#609]
**Describe the bug**
Schema definiton for `Link` is a reference to itself, leading to StackOverflowError in openapi-generator-cli

**versions**
- spring-boot **`2.2.6.RELEASE`**
- `springdoc-openapi-ui` and `springdoc-openapi-data-rest` both in version **`1.3.4`** & `springdoc-openapi-maven-plugin` version **`0.3`**

**Minimal sample to reproduce**
- clone https://github.com/ch4mpy/springdoc-openapi-609
- run `./mvnw install`
- submit generated `dtos.json` (`target` folder) to [https://apitools.dev/swagger-parser/online/](https://apitools.dev/swagger-parser/online/)

**Expected behavior**
Schema `Link` definition is as follow
``` json
"Link":{"$ref":"#/components/schemas/Link"}
```
It should be 
``` json
"Link": {
	"type": "object",
	"properties": {
	  "href": {
		"type": "string"
	  },
	  "hreflang": {
		"type": "string"
	  },
	  "media": {
		"type": "string"
	  },
	  "title": {
		"type": "string"
	  },
	  "type": {
		"type": "string"
	  },
	  "deprecation": {
		"type": "string"
	  },
	  "profile": {
		"type": "string"
	  },
	  "name": {
		"type": "string"
	  }
	}
}
```

**Comment by bnasslahsen** [comment]
@ch4mpy, 

 Its now fixed.  You can test with the lastest snapshot and give your feedback.

**Comment by ch4mpy** [comment]
I can now generate Angular code from Spring project without hacking intermediate schema.

Thank you!
