### ISSUE TITLE
Schema.example is ignored for string/date-time

### ISSUE THREAD

**Issue by antechrestos** [springdoc/springdoc-openapi#61]
Hi,

Given a response class:

```kotlin
@Schema(name = "TrackerData")
data class TrackerData(@Schema(name = "trackerId", type = "string", required = true, example = "the-tracker-id")
                          @JsonProperty("trackerId")
                          val trackerId: String,
                          @Schema(name = "timestamp", type = "string", format = "date-time", required = true, example = "1970-01-01T00:00:00Z")
                          @JsonProperty("timestamp")
                          val timestamp: Instant,
                          @Schema(name = "value", type = "number", format="double", description = "The data value", required = true, example = "19.0")
                          @JsonProperty("value") val value: Double)
```

When I look at the open api description generated it gives:

```json
{
...
  "TrackerData":{
       "required":["timestamp","trackerId","value"],
       "type":"object",
        "properties": {
          "trackerId":{"type":"string","example":"urn:lo:nsid:lora:0123456789ABCDEF"},
          "timestamp":{"type":"string","format":"date-time"},
           "value":{"type":"number","description":"The data value","format":"double","example":19.0}
        }
  }
}
```

As you can see, the `timestamp` field description misses the provided `example`. I removed the `format` field and then the example appears in the `json`. I tried removing the `miliseconds` part but it did not change anything (the couple format/example is also used for `Operation.parameter` or `Parameter` alone and it works in these two late cases).

Thank you.

**Comment by springdoc** [comment]
Hi, 

 This is not an issue related to springdoc-openapi. 
 This behaviour is related to swagger-core official api. While resolving schemas on member fields:
-  Class: ModelResolver
- Method: resolveSchemaMembers

 If you need to change the behaviour of swagger-core, you can submit an issue on: 
- https://github.com/swagger-api/swagger-core/issues


 When you define the format of your schema as date-time, the method cast inside DateTimeSchema  tries to cast the value into Date. 
 This method is called when resolving the example value. 

 Note also, that when you add the format attribute into schema, swagger-ui fills an example value automatically. 

```java
    @Override
    protected Date cast(Object value) {
        if (value != null) {
            try {
                if (value instanceof Date) {
                    return (Date) value;
                }
            } catch (Exception e) {
            }
        }
        return null;
    }
```

**Comment by antechrestos** [comment]
@springdoc Thanks I will do a feed back as soon as I integrate it

**Comment by antechrestos** [comment]
@springdoc it is ok. Thank you
