### ISSUE TITLE
ApiResponse DEFAULT_DESCRIPTION Improvement

### ISSUE THREAD

**Issue by raghuraman1** [springdoc/springdoc-openapi#610]
Hi @bnasslahsen

Remember below code in ControllerAdvice

![image](https://user-images.githubusercontent.com/14346578/80275501-3d36b780-86ff-11ea-972b-923c08185dc9.png)

   
Look at the corresponding responses:

![image](https://user-images.githubusercontent.com/14346578/80275355-4b380880-86fe-11ea-88f6-17cd9a75ad62.png)

Expectation is that instead of "defaultResponse" it should pickup the message from HttpStatus.getReasonPhrase().

Raghu

**Comment by raghuraman1** [comment]
@bnasslahsen The Travis test failed for related PR https://github.com/springdoc/springdoc-openapi/pull/611 and I presume thats a good thing. The related tests will need changing.

**Comment by bnasslahsen** [comment]
@raghuraman1, 

 Ok, i will see the impacts on the tests. 
 The improvement you propose, is not only related to the controllerAdvice.

**Comment by raghuraman1** [comment]
Agreed. I was just writing that its beyond ControlerAdvice.

**Comment by raghuraman1** [comment]
@bnasslahsen  I can fix the tests as part of the PR

**Comment by bnasslahsen** [comment]
@raghuraman1, 

 It's ok. I have already started the merge.

**Comment by raghuraman1** [comment]
I just noticed what you typed. Was committing the test changes

**Comment by raghuraman1** [comment]
@bnasslahsen  I do wish I could have some PR committed in my name also. :)

**Comment by bnasslahsen** [comment]
@raghuraman1, 

 Next time 👍

**Comment by raghuraman1** [comment]
@bnasslahsen This time it was like a robbery from my point of view. :)
But you guys are making a great product.
I
