### ISSUE TITLE
StackOverflowError on loading APIs

### ISSUE THREAD

**Issue by jotedia** [springdoc/springdoc-openapi#612]
**Describe the bug**
- I am having a problem trying to load the APIs of my project getting a StackOverflowError.

This happens to me on a CentOS server, on my local machine it does not happen to me (Windows 10). I do not know if it can be useful to provide the OS information, but just in case.

This is my configuration:

- pom.xml:
```
<!-- OpenAPI -->
        <dependency>
            <groupId>org.springdoc</groupId>
            <artifactId>springdoc-openapi-ui</artifactId>
            <version>1.3.4</version>
        </dependency>
        <dependency>
            <groupId>org.springdoc</groupId>
            <artifactId>springdoc-openapi-webmvc-core</artifactId>
            <version>1.3.4</version>
        </dependency>
```

OpenApiConfig.java
```
@Bean
    public OpenAPI customOpenAPI() {
		Contact contact = new Contact();
		contact.setEmail("XXX");
		contact.setName("XXXX");
		contact.setUrl("XXXX");
		
        return new OpenAPI()
                .components(new Components().addSecuritySchemes("bearer-key",
								new SecurityScheme()
										.type(SecurityScheme.Type.HTTP)
										.scheme("bearer")
										.bearerFormat("JWT"))
				)
				.info(new Info().title("Spring REST OM - XXX")
						.description("XXX API in Swagger framework")
						.contact(contact)
						.version("V.01.00")
				);
    }
```

**To Reproduce**
- What version of spring-boot you are using? `<version>2.1.4.RELEASE</version>`
- What modules and versions of springdoc-openapi are you using? Up
- What is the actual and the expected result using OpenAPI Description (yml or json)? Can't provide.

**Expected behavior**
- When I try to enter on swagger-ui.html I'm getting the next:
![image](https://user-images.githubusercontent.com/28892625/80280280-61949300-8703-11ea-8025-ca08b7ed800d.png)

**Screenshots**
Log with the error: https://pastebin.com/bm7pSKi3

Can someone help me on this, this is urgent :(

**Comment by bnasslahsen** [comment]
Hi @jotedia, 

 This error is not related to springdoc from your stacktrace.
 Its related to your jackson configuration...

**Comment by jotedia** [comment]
It started when we migrate from springfox 2.9.2 to springdoc OpenApi... :


```
14:54:58.027 [https-jsse-nio-8092-exec-2] ERROR o.a.c.c.C.[.[.[.[dispatcherServlet] - Servlet.service() for servlet [dispatcherServlet] in context with path [/XXX] threw exception [Handler dispatch failed; nested exception is java.lang.StackOverflowError] with root cause
java.lang.StackOverflowError: null
        at io.swagger.v3.core.jackson.ModelResolver.resolve(ModelResolver.java:122)
        at org.springdoc.core.converters.AdditionalModelsConverter.resolve(AdditionalModelsConverter.java:60)
        at org.springdoc.core.converters.PropertyCustomizingConverter.resolve(PropertyCustomizingConverter.java:42)
        at org.springdoc.core.converters.FileSupportConverter.resolve(FileSupportConverter.java:44)
```

**Comment by bnasslahsen** [comment]
if you follow the guidelines ans provide as much information as requested we could help: 

- https://github.com/springdoc/springdoc-openapi/blob/master/CONTRIBUTING.adoc

You can share SomeClass or equivalent class triggering the issue.
But with only your stacktrace. The ERROR not on springdoc library..

**Comment by jotedia** [comment]
I cannot reproduce the problem. The project has like 200 Java classes... And it started when we migrate to OpenApi 3. It occurs when trying to access api-docs, but I don't know where.
It's a circular reference in ModelResolver...

Thanks anyway.
