### ISSUE TITLE
Enhancing ControllerAdvice Response

### ISSUE THREAD

**Issue by raghuraman1** [springdoc/springdoc-openapi#613]
Hi @bnasslahsen,

When we attach a  @ResponseStatus(code = HttpStatus.INTERNAL_SERVER_ERROR") to a ControllerAdvice method we should also be able to do it like this:-

 @ResponseStatus(code = HttpStatus.INTERNAL_SERVER_ERROR, **reason** = "my own message").

_Expectation should be that we can change the message for the response code._

**A little complication:**
Not sure which should get more priority for being displayed.
@ApiResponses({@ApiResponse(responseCode = "202", description = "another own message")} when applied on  a controller method.

I generally dont like using @ApiResponse. Too much clutter. But if it is present I assume it should override what would come out of @ResponseStatus in controller advice methods.

Because of this complication dont want to attempt it.  We will also have to see that when we use reason in @ResponseStatus nothing breaks.

But I think its a valuable feature.
What do you think?
R

**Comment by bnasslahsen** [comment]
The problem is that on the same controller advice, you might have many @ResponseStatus, declared for different types of exception:

`@ResponseStatus(code = HttpStatus.INTERNAL_SERVER_ERROR, reason = "my own message2") `

`@ResponseStatus(code = HttpStatus.INTERNAL_SERVER_ERROR, reason = "my own message2")` 


And, on the ApiResponseObject, we can just have one message description. And, shouldn't add a lot of complexity. So which reason to choose ?

**Comment by raghuraman1** [comment]
Thats another complexity. Why dont we just add all the messages and separate by a "/"

**Comment by bnasslahsen** [comment]
Is it really worth ? This might create confusion, with many descriptions.

The generic description that you have proposed in #610, seems a better aproach.
But, anyway, if you want to propose a PR for this feature, its welcome, with the reated test cases :)

**Comment by raghuraman1** [comment]
https://github.com/springdoc/springdoc-openapi/issues/610 is already done by you.
No more PRs from me for a while. :)
But my two cents is people may want to use the reason because when using the controllerAdvice they might want to change the message centrally.

**Comment by bnasslahsen** [comment]
i will see, if we can have any improvements then!

**Comment by raghuraman1** [comment]
I can attempt next weekend. But will need some guidance when I attempt. This is a ticket best done by you

**Comment by raghuraman1** [comment]
Hi @bnasslahsen 
There is one strong reason why its not worth it.
I had noticed it earlier and hinted that adding reason might be breaking something.
So here it is:
There is this method setResponseStatus() in class org.springframework.web.method.support.ServletInvocableHandlerMethod  :
See line 148 in spring code image below. Basically **if reason is provided** the response gets written immediately.
Effectively makes the controller advice method useless in terms of actual response even though the controller advice does its work  because the response is committed even before that.
Till there is a solution for that we are better off not attempting this.
You can verify it if you like.

![image](https://user-images.githubusercontent.com/14346578/80286537-9b888800-8749-11ea-864c-c9b2e66acad9.png)
Was very intersting.

R

**Comment by bnasslahsen** [comment]
@raghuraman1, 

 Thank you for this analysis. 
 Yeah, it's another reason, to leave this enhancement on hold.
