### ISSUE TITLE
How to handle Map<String,Object> in the response

### ISSUE THREAD

**Issue by nehalshah50** [springdoc/springdoc-openapi#614]
I have an endpoint which returns Map<Locale,Product>. I am not sure how annotate it correctly. My Swagger UI shows empty in the response. 

enum class Locale(en_US, en_CA, fr_CA)
data class Product(name:String, description:String)

Also, where ever I have Map object, it always shows as following in the swagger

"additionalProp1": "string",
"additionalProp2": "string",
"additionalProp3": "string"

With swagger 2 i was able to manually fix the spec by doing something like following
 `description:
          type: object
          properties:
            en_US:
              type: string
              example: 'Open'
            fr_CA:
              type: string
              example: 'OUVERT'
            en_CA:
              type: string
              example: 'Open'`

or using this

`details:
          description: This map represents locale specific map for various product names
          type: object
          properties:
            en_US:
              $ref: '#/components/schemas/ProductNameDetails'
            fr_CA:
              $ref: '#/components/schemas/ProductNameDetails'
            en_CA:
              $ref: '#/components/schemas/ProductNameDetails'`

I also found this stackoverflow but not sure how to do this with springdoc
https://stackoverflow.com/questions/46552863/how-to-write-openapi-3-swagger-specification-for-property-name-in-map-object

**Comment by bnasslahsen** [comment]
@nehalshah50, 

 Your question is not directly related to springdoc-openapi, but to the usage of OpenAPI 3.
 Anyway, here is a sample working code that you can customize:

```java
@RestController
public class TestController {

	@ApiResponse(ref ="#/components/responses/myCustomResponse" )
	@GetMapping(value = "/search", produces = MediaType.APPLICATION_JSON_VALUE)
	public Map<String, Object> getAll() {
		return null;
	}

	@Bean
	public OpenAPI customOpenAPI() {
		return new OpenAPI()
		.components(new Components()
			.addResponses("myCustomResponse", new io.swagger.v3.oas.models.responses.ApiResponse().description("This map represents locale specific map for various product names type")
				.content(new Content().addMediaType(MediaType.APPLICATION_JSON_VALUE,
					new io.swagger.v3.oas.models.media.MediaType().schema(new MapSchema()
					.addProperties("en_US", new StringSchema())
					.addProperties("fr_CA", new StringSchema()))))));
	}

}
```

**Comment by nehalshah50** [comment]
Above works fine when you for the responses. How about when it is not the actule response type but part of another type. 
Example:
`Response: Product(id:String, code:String, detail: Map<Locale,ProductDetail>)`

**Comment by bnasslahsen** [comment]
you can use `org.springdoc.core.customizers.PropertyCustomizer`, and apply the same schema that you applied on ApiResponse above, on the field `detail`, of the class Product.
You can have a look at this example and adapt it:
- https://github.com/springdoc/springdoc-openapi/blob/master/springdoc-openapi-webmvc-core/src/test/java/test/org/springdoc/api/app70/customizer/PropertyCustomizer.java

**Comment by florin05** [comment]
@bnasslahsen your response is almost solving a different problem I am facing.
The one thing that I could not figure out is how to refer to a Schema object for a known class.
For example:
```
...
.addProperties("valueASuccess", new Schema<MyClass>())
.addProperties("valueBError", new Schema<MyErrorClass>()) 
...
```
` new Schema<MyClass>()` is empty, not exposing properties of the "MyClass". I can try to use `setExample` or `setDefault` but feels like there should be an easier way.
Looking for the same outcome as when using annotations:
```
...
schema = @Schema(implementation = MyClass.class))
...
```

**Comment by bnasslahsen** [comment]
There is no such method using swagger-api.
You can use, other alternatives:

```java
ResolvedSchema resolvedSchema = ModelConverters.getInstance()
            .resolveAsResolvedSchema(
                    new AnnotatedType(className).resolveAsRef(false));
Schema  mySchema = resolvedSchema.schema;
```

**Comment by florin05** [comment]
Great, that is exactly what I was looking for, `io.swagger.v3.core.converter.ResolvedSchema` class!
Thank you @bnasslahsen
