### ISSUE TITLE
Hide or not a field base on group's option

### ISSUE THREAD

**Issue by mcamelot** [springdoc/springdoc-openapi#616]
**Is your feature request related to a problem? Please describe.**
I have an object like below

```
@Data
@JsonInclude(JsonInclude.Include.NON_NULL)
public class Foo {

    @Schema(example = "5db6cd1c707443697af33662", description = "Post -> Null | Put -> Not Null")
    @NotNull(groups = { Put.class })
    @Null(groups = { Post.class })
    @JsonProperty("id")
    private String id;

    @JsonProperty("other")
    private String other;

}
```

In the controller's interface, i specify a post method

```
@Operation(security = {@SecurityRequirement(name = "bearer-token")}, description = "Creates a new Foo object", summary = "Creates a new Foo", operationId = "postFoo")
    @PostMapping(value = "/foos", consumes = {"application/json"})
    ResponseEntity<Void> post(
            @Parameter(description = "Foo object that needs to be created", required = true)
            @Validated(Post.class)
            @RequestBody Foo foo);
```

But in swagger, the id appears like mandatory

```
foo {
     id* | string
           example: 5db6cd1c707443697af33662Post -> Null \| Put -> Not Null
    other | string
           example: 5E:FF:56:A2:AF:15
}
```

**Describe the solution you'd like**
I wish i could use one Object for Post and Put method.
I would like, that field's visibility were based on group's option.
It will prevent to create one object for Post and one Object for Put.

_the swagger for Put_
```
foo {
     id* | string
           example: 5db6cd1c707443697af33662Post -> Null \| Put -> Not Null
    other | string
           example: 5E:FF:56:A2:AF:15
}
```

_the swagger for Post_
```
foo {
    other | string
           example: 5E:FF:56:A2:AF:15
}
```

**Describe alternatives you've considered**
- I Have to create one Object for Post and one Object for Put

**Comment by bnasslahsen** [comment]
@mcamelot, 

 By default, you get will get only one schema for your Type Foo. 
 If you are expecting two differents schemas, you have two solutions:
 - Declare explicitely using `@Parameter` annotations
 - Use two different objects

 For hiding fields from the documentation, you should use swagger-2 annotations instead:
 - https://springdoc.org/faq.html#how-can-i-ignore-some-field-of-model-
 - https://github.com/swagger-api/swagger-core/wiki/Swagger-2.X---Annotations


 At the end the resolution of JSR 303 annotations for the fileds of class, is not handled by springdoc-openapi directly, but with swagger-core: `ModelResolver.applyBeanValidatorAnnotations`

```
ResolvedSchema resolvedSchema = ModelConverters.getInstance()
		.resolveAsResolvedSchema(new AnnotatedType(Foo.class));
if (resolvedSchema.schema != null) {
	Schema schemaN = resolvedSchema.schema;
	Map<String, Schema> schemaMap = resolvedSchema.referencedSchemas;
	Assert.isTrue(schemaMap.get("Foo").getRequired().contains("id"),"");
```

 You can override this behaviour of swagger-core, by defining your own PropertyCustomizer ans a return you can define your own expected schema for a property (which can be a composed schema)
