### ISSUE TITLE
Further Improvements to MonetaryAmount

### ISSUE THREAD

**Issue by raghuraman1** [springdoc/springdoc-openapi#617]
Hi @bnasslahsen ,
This is further to - https://github.com/springdoc/springdoc-openapi/issues/606
I am reporting two possible improvements.

- org.springdoc.core.converters.MonetaryAmount is not implementing javax.money.MonetaryAmount
- @org.hibernate.validator.constraints.Currency does not validate with it because of previous point. 

Spring developers will expect that.
R

**Comment by bnasslahsen** [comment]
@raghuraman1, 

 Why do you need org.springdoc.core.converters.MonetaryAmount  to implement javax.money.MonetaryAmount ?

**Comment by bnasslahsen** [comment]
I have seen the sample: https://github.com/teq-niq/sample/tree/monetary-amount

You shouldn't extend org.springdoc.core.converters.MonetaryAmount.
Its internal springdoc class. 
An application should only use javax.money.MonetaryAmount .

**Comment by bnasslahsen** [comment]
I have updated the test and the visibility of the class, so there is no misunderstanding:
- https://github.com/springdoc/springdoc-openapi/blob/master/springdoc-openapi-webmvc-core/src/test/java/test/org/springdoc/api/app114/SpringDocApp114Test.java

**Comment by raghuraman1** [comment]
@bnasslahsen 
Thats why I needed you to look. That said:-
Its solving 4 things.

1. Makes an actual implementation of javax.money.MonetaryAmount
2. Enables @Currency to work
3. Also it allows me to defer the usage of the actual delegate implementation.
4. It helps me avoid bringing in moneta-core library and keeps the money api at api level.

If its ok to bring in moneta-core libray in classpath we can make the org.springdoc.core.converters.MonetaryAmount concrete.
Do suggest what we can do more? Need some guidance.

**Comment by raghuraman1** [comment]
@bnasslahsen  Let me check .And get back to what you said.
You are to fast how you move the tests. :)

**Comment by bnasslahsen** [comment]
I have seen your example, and i don't understant why you extend org.springdoc.core.converters.MonetaryAmount.

Please have a look at the test i mentionned. @Currency should work without any change.

**Comment by raghuraman1** [comment]
@bnasslahsen Checking

**Comment by raghuraman1** [comment]
@bnasslahsen  Tried your test- https://github.com/teq-niq/sample/tree/monetary-amount-check
I also saw you changed the visibility of the converter. Issue is when we POST.
So here is the issue.

{
  "timestamp": "2020-04-26T21:03:16.727+0000",
  "status": 400,
  "error": "Bad Request",
  "message": "JSON parse error: Cannot construct instance of `sample.HelloController$CarDTO` (although at least one Creator exists): non-static inner classes like this can only by instantiated using default, no-argument constructor; nested exception is com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot construct instance of `sample.HelloController$CarDTO` (although at least one Creator exists): non-static inner classes like this can only by instantiated using default, no-argument constructor\n at [Source: (PushbackInputStream); line: 1, column: 2]",
  "path": "/foos1"
}

**Comment by bnasslahsen** [comment]
If a project uses javax.money.MonetaryAmount , it needs to configure a deserializer.
We do not provide the configuration of the MoneyModule as it depends on the project settings.

```
@Bean
public MoneyModule moneyModule() {
	return new MoneyModule().withMonetaryAmount(Money::of);
}
```

**Comment by raghuraman1** [comment]
@bnasslahsen That works. Looks like I  forced you to change the visibility of your converter.
Now its great. We can close the PR attempt and close the this ticket.
Sorry about it.

**Comment by bnasslahsen** [comment]
@raghuraman1, 

 No pb, that helps. 
 So that other developers, don't reference it directly in their apps.

**Comment by raghuraman1** [comment]
@bnasslahsen 
I did say I wanted you to approve first.
Thanks. U are a friend in my friend list. :)

**Comment by bnasslahsen** [comment]
You are welcome @raghuraman1.
