### ISSUE TITLE
Escaped Json when using Gson

### ISSUE THREAD

**Issue by nicofari** [springdoc/springdoc-openapi#619]
Hello
I have a Spring Boot (latest version at the moment 2.2.6) in which I disabled Jackson to use Gson. As a final step I added springdoc-openapi to have the nice auto-generated open-api docs.
But then, surprise, the api-docs json is escaped. After digging and searching it seems to me that the spring-doc code is heavilty bound to Jackson.
Am I right? Or is there a way to solve this problem maintaing Gson as default converter in my app?
Or do i need to come back to Jackson?
Thanks a lot
Nicola

**Comment by bnasslahsen** [comment]
Hi @nicofari, 

 springdoc-openapi, depends on swagger-core project: 
 - https://github.com/swagger-api/swagger-core/wiki/Swagger-2.X---Annotations

 swagger-core, is based on jackson. so in order to to have things work, you will need jackson.

**Comment by bnasslahsen** [comment]
Hi @nicofari, 

 It seems you having the same problem here: #624

**Comment by nicofari** [comment]
Hi @bnasslahsen 
for this project I reverted back to Jackson, and sorry I don't have time to come back to Gson again.
But I will certainly test it on the next project.
Thanks
Nicola
