### ISSUE TITLE
Property defined in abstract parent class

### ISSUE THREAD

**Issue by nehalshah50** [springdoc/springdoc-openapi#620]
I have an abstract class for all of my controller request body. 

`abstract class BaseRequest(

        @Schema(example = "user@userorg")
        @field:NotBlank @field:NotEmpty
        @field:Pattern(regexp = "^(?=.{1,64}\$)([a-zA-Z0-9]+)@([a-zA-Z0-9-]){1,6}\$",message = "must be upto 64 alphanumeric characters in total length and must have upto 6 characters after '@'. ex. myusername@myorg")
        open val userID: String

)
`
Then all of my requests extends from this abstract class

`data class SampleRequest(val id:String, override userID: String): BaseRequest(userID)`

The generated OpenAPI spec doesn't show up information about userID attribute. It shows up as String without other information like pattern, description, example
`userID:
          type: string`

I expect to see following for all requests
`userID:
          pattern: '^(?=.{1,64}$)([a-zA-Z0-9]+)@([a-zA-Z0-9-]){1,6}$'
          type: string
          example: user@userorg`

**Comment by bnasslahsen** [comment]
@nehalshah50, 

Your description is not enough to address:
 -  The example you have provided is incomplete. And not even formatted.

This ticket will be closed, and there is no need to reopen a new open for the same issue.
If you are reporting a bug, please help to speed up problem diagnosis by providing as much information as possible: You can update your ticket with the necessary information and it will be reopened.

Please have a look at the contribution guide section Using GitHub Issues:

 - https://github.com/springdoc/springdoc-openapi/blob/master/CONTRIBUTING.adoc
