### ISSUE TITLE
@Currency and swagger documentation

### ISSUE THREAD

**Issue by raghuraman1** [springdoc/springdoc-openapi#621]
Hi @bnasslahsen 

Please have a look at this- https://github.com/teq-niq/sample/tree/extending1
I am trying to show using swagger extensions validation constraints that swagger or springdoc might not be showing.
![image](https://user-images.githubusercontent.com/14346578/80372356-0c967f80-88b1-11ea-97bd-7abb18dc109e.png)
As you can see Its generally working well. But I dont see a x-Currency: USD.
Can we solve this? Any suggestions?

Raghu
A valid input will be this
{
  "id": 0,
  "worth": {
    "amount": 99.96,
    "currency": "USD"
  },
  "registrationDate": "20200101",
  "firstName": "string",
  "lastName": "string",
  "email": "string@b.com",
  "email1": "strin@a.comg",
  "age": 20,
  "creditCardNumber": "4111111111111111"
}

The @Currency check is working well.

**Comment by raghuraman1** [comment]
@bnasslahsen  Hope its an interesting problem. My guess is its because of the replacement of the MonetaryAmount by the converter - cant see the @Currency since the type having @Currency is replaced

**Comment by raghuraman1** [comment]
@bnasslahsen  Also see https://github.com/teq-niq/sample/tree/extending3
It avoids creating the converter and uses latest master branch of springdoc.
I am trying to understand if it can be solved.

**Comment by raghuraman1** [comment]
False alarm. The annotations are there. I will figure it out.

**Comment by raghuraman1** [comment]
Hi @bnasslahsen ,
I was using 1.3.6 version from maven.
Noticed that you have removed 
public class SpringDocMonetaryAmountConfiguration {

	static {
		SpringDocUtils.getConfig().replaceWithClass(MonetaryAmount.class, org.springdoc.core.converters.MonetaryAmount.class);
	}

}
So unless below is  called explicitly it causes exception from sample code we get the exception we discussed earlier.
SpringDocUtils.getConfig().replaceWithClass(MonetaryAmount.class, org.springdoc.core.converters.MonetaryAmount.class);

Thought I will let you know. Didnt raise a new ticket.
Raghu

**Comment by bnasslahsen** [comment]
@raghuraman1, 


 In order to give more flexibility to the applications, to choose or not to use it, and aslo to make it easier to support extensions for MonetaryAmount as you mentionned.
 Yes thats normal and documented on the F.A.Q:
 - https://springdoc.org/faq.html#how-can-i-use-enable-springdoc-openapi-monetaryamount-support-

**Comment by raghuraman1** [comment]
Ok. It broke my examples that I had shared to swagger-core for the extensions. 
It looks like Francesco Tumanischvili of swagger-core has been inactive for a few days.
Hoping he is doing well. 
These are tough times.
