### ISSUE TITLE
Missing extension to schema property

### ISSUE THREAD

**Issue by raghuraman1** [springdoc/springdoc-openapi#622]
Hi @bnasslahsen ,

Please see  https://github.com/teq-niq/sample/tree/extending3
In the person schema for worth field am expecting a extension x-Currency with value USD.

In springdoc-openapi-webmvc-core\src\main\java\org\springdoc\webmvc\api\OpenApiResource.java I debugged this method - openapiJson()

I can see the extension with correct value in this object
OpenAPI openAPI = this.getOpenApi();

But the extension is missing in the api-docs json. The other extensions are all appearing properly.
![problem](https://user-images.githubusercontent.com/14346578/80395868-73c42c00-88d1-11ea-9ae1-cfc5999fcd92.png)

Attaching the json txt:
[json.txt](https://github.com/springdoc/springdoc-openapi/files/4540807/json.txt)

Raghu

**Comment by bnasslahsen** [comment]
@raghuraman1, 

 This is due to the fact that MonetaryAmount is a complex object wich is by default resolved using $ref.
 When an object has $ref, No sibling values are allowed.

 If an application wants to enable the springdoc-openapi support, it declares:
```java
SpringDocUtils.getConfig().replaceWithClass(MonetaryAmount.class, org.springdoc.core.converters.MonetaryAmount.class);
```
 
In order to enable the extension for a complex object, it shouldn't be resolved as $ref; If you declare the following, it should work.

```java
SpringDocUtils.getConfig().replaceWithSchema(MonetaryAmount.class, new ObjectSchema()
				.addProperties("amount", new NumberSchema()).example(99.96)
				.addProperties("currency", new StringSchema().example("USD")));
```

PS: Please don't open many issues on the same topic. In this case are related to add the MonetaryAmount on springdoc. #621, #622, #617, #606.
 Even an issue is closed, if someone adds a comment, we keep following it.

**Comment by raghuraman1** [comment]
Hi @bnasslahsen  
Was wondering where you disappeared and hoped you are fine. :) Gud to hear from you again. 
Noted about " don't open many issues on the same topic."
My motive was to avoid confusion.But what you said makes sense from the perspective you mentioned. Will abide by that.
I will try what you suggested and get back tomorrow.
I suspected it had something to do with ref.

**One doubt:**
Any complex property will tend to be a ref- Right (because you are referring to the schemas in components)? If so and if i need ability to add extensions to any complex property this looks complicated. If that's correct can it be simplified?

R

**Comment by bnasslahsen** [comment]
@raghuraman1, 

 The rendering of Complex properties is not done by springdoc-openapi, but using swagger-core.
 You can test it with the following:

```
ResolvedSchema resolvedSchema = ModelConverters.getInstance()
		.resolveAsResolvedSchema(new AnnotatedType(Person.class));
if (resolvedSchema.schema != null) {
	Schema schemaN = resolvedSchema.schema;
	Map<String, Schema> schemaMap = resolvedSchema.referencedSchemas;
}
```

I don't see how you can get extension on complex properties with the current swagger-core implementation. 
But, if you find a way, please feel free to share.

**Comment by raghuraman1** [comment]
@bnasslahsen 
Have 2 solutions. Will get back

**Comment by bnasslahsen** [comment]
@bnasslahsen, 

 I was going to release v1.3.5.  If its a minor change, i can wait.
 Do your solutions require any change on springdoc-openapi?

**Comment by raghuraman1** [comment]
@bnasslahsen 
You carry on with 1.3.5. This can wait. Lots of new features people are waiting for.Lets not prolong the wait.
But I will outline what I see. There are two ways:
A) In OpenApiResource.openapiJson() we can provide a different ObjectMapper than what we get from io.swagger.v3.core.util.Json.mapper(). All the code is there in swagger-core we need a small change after copying their code.
B) In io.swagger.v3.core.jackson.SchemaSerializer in swagger-core we change this
![image](https://user-images.githubusercontent.com/14346578/80507386-6fad1280-8994-11ea-89af-50ff7195954b.png)
I vote for B. And we try convincing swagger guys like last time. I can look at what code they have in their latest and try raising a PR.
What do you say? We do have a requirement.

**Comment by raghuraman1** [comment]
@bnasslahsen 
I can even attempt A let me see how simple or complex its. Will get back

**Comment by bnasslahsen** [comment]
@bnasslahsen, 

The springdoc-openapi relies on swagger-core. Option B, is the better choice.

**Comment by raghuraman1** [comment]
@raghuraman1 
I will write an implementation and raise a PR on swagger-core. Do give your support like the last time.
Thanks.

**Comment by raghuraman1** [comment]
@bnasslahsen ,
The code changes I tried on io.swagger.v3.core.jackson.SchemaSerializer.
They cause proper json and yaml.
There is a little rabbit hole. Looks like ui- the reactjs code will also need improving.
I can attempt that also after this.
Meanwhile for your opinion attaching the following
json:
[api-docs.json.txt](https://github.com/springdoc/springdoc-openapi/files/4547323/api-docs.json.txt)
yaml:
[api-docs.yaml.txt](https://github.com/springdoc/springdoc-openapi/files/4547325/api-docs.yaml.txt)
code changes:
<img width="1754" alt="codechanges" src="https://user-images.githubusercontent.com/14346578/80516875-cbca6380-89a1-11ea-9c4a-4ebb67a649ae.png">

**Comment by raghuraman1** [comment]
@bnasslahsen 
I have further simplified io.swagger.v3.core.jackson.SchemaSerializer code changes as shown above.
I hope you give a thumbs up on https://github.com/swagger-api/swagger-core/pull/3539
I have also detailed different samples and different outputs in the ticket.
I am hoping it gets merged.

**Comment by breno-ki** [comment]
> @raghuraman1,
> 
> This is due to the fact that MonetaryAmount is a complex object wich is by default resolved using $ref.
> When an object has $ref, No sibling values are allowed.
> 
> If an application wants to enable the springdoc-openapi support, it declares:
> 
> ```java
> SpringDocUtils.getConfig().replaceWithClass(MonetaryAmount.class, org.springdoc.core.converters.MonetaryAmount.class);
> ```
> 
> In order to enable the extension for a complex object, it shouldn't be resolved as $ref; If you declare the following, it should work.
> 
> ```java
> SpringDocUtils.getConfig().replaceWithSchema(MonetaryAmount.class, new ObjectSchema()
> 				.addProperties("amount", new NumberSchema()).example(99.96)
> 				.addProperties("currency", new StringSchema().example("USD")));
> ```
> 
> PS: Please don't open many issues on the same topic. In this case are related to add the MonetaryAmount on springdoc. #621, #622, #617, #606.
> Even an issue is closed, if someone adds a comment, we keep following it.

FYI the first solution is outdated (also in the FAQ https://springdoc.org/faq.html#how-can-i-use-enable-springdoc-openapi-monetaryamount-support-), the class that should be used is `org.springdoc.core.converters.models.MonetaryAmount.class`.

Using sprindoc 1.5.6 here, still get the error without manually setting the converter. I believe this was mentioned to be an issue with swagger-core, is there any update on this?

**Comment by bnasslahsen** [comment]
@breno-ki, 

 Doc is now updated. Note that you can propose PR for it which is welcome in Open Source projects.
 You can [see this sample test ](https://github.com/springdoc/springdoc-openapi/blob/master/springdoc-openapi-webmvc-core/src/test/java/test/org/springdoc/api/app114/SpringDocApp114Test.java) for how this is applied.

**Comment by breno-ki** [comment]
> @breno-ki,
> 
> Doc is now updated. Note that you can propose PR for it which is welcome in Open Source projects.
> You can [see this sample test ](https://github.com/springdoc/springdoc-openapi/blob/master/springdoc-openapi-webmvc-core/src/test/java/test/org/springdoc/api/app114/SpringDocApp114Test.java) for how this is applied.

Lovely, cheers for fixing! :)
