### ISSUE TITLE
Springdoc with Actuator server in different port that embedded tomcat server

### ISSUE THREAD

**Issue by cfpperche** [springdoc/springdoc-openapi#626]
**Describe the bug**
Dependencies:
org.springframework.boot:spring-boot-starter-web:2.2.6-RELEASE
org.springframework.boot:spring-boot-starter-actuator:2.2.6-RELEASE
org.springdoc:springdoc-openapi-ui:1.3.4

If I change the actuator server por and set springdoc-show-actuator property to true I have error like this
....
....
....
servico-planocontas    | ***************************
servico-planocontas    | APPLICATION FAILED TO START
servico-planocontas    | ***************************
servico-planocontas    |
servico-planocontas    | Description:
servico-planocontas    |
servico-planocontas    | Parameter 0 of method actuatorProvider in org.springdoc.webmvc.core.SpringDocWebMvcConfiguration$SpringDocWebMvcActuatorConfiguration required a bean of type 'org.springframework.boot.actuate.endpoint.web.servlet.WebMvcEndpointHandlerMapping' that could not be found.
servico-planocontas    |
servico-planocontas    |
servico-planocontas    | Action:
servico-planocontas    |
servico-planocontas    | Consider defining a bean of type 'org.springframework.boot.actuate.endpoint.web.servlet.WebMvcEndpointHandlerMapping' in your configuration.
 
If I have disable springdoc.show-actuator and keep server and management.server with different ports this works but I can't map actuator endpoints in swagger-ui

sorry my english, i try...

**To Reproduce**

application.yml
....
server.port: 8080
management.server.port: 4004
springdoc.show-actuator: true

**Expected behavior**
to be executed without any errors

**Screenshots**

**Comment by bnasslahsen** [comment]
@cfpperche, 

 This is a partial fix, in order to hide the error.
 The support for actuator on different ports can be addressed in a future release.
