### ISSUE TITLE
Question: How can I set ApiResponse description from an Enum

### ISSUE THREAD

**Issue by bluelurker** [springdoc/springdoc-openapi#629]
Hello, We recently started using springdoc. While it serves all our needs, we are struggling to assign some ApiDescription from an Enum.

In our application, constants are defined like this

```
enum Errors {
  E101("101", "Invalid user"),
  E102("101", "Invalid Order"),
  E103("101", "Invalid Product");

  private final String code;
  private final String description;

  private Errors(String code, String description) {
    this.code = code;
    this.description = description;
  }

  public String getDescription() {
    return description;
  }

  public String getCode() {
    return code;
  }
}
```

We are annotating our method like following 

```
@ApiResponses(
      value = {
        @ApiResponse(
            responseCode = "400",
            description = "E101:Invalid user",
            content = @Content(schema = @Schema(implementation = ErrorResponse.class))),
        @ApiResponse(
            responseCode = "400",
            description = "E102:Invalid Order",
            content = @Content(schema = @Schema(implementation = ErrorResponse.class))),
)
@GetMapping(path = "/customers")
public List<?> getCustomerList(.....){
///
}
```
Write now we have to duplicate the description. We were wondering if we can use Error enums directly so that any changes in Error codes are automatically reflected. Any direction?

I read one of the other issues and it seems it can be achieved by customizing `OpenAPI` model. Am  I right? Could you point to some documentation or example?

**Comment by bnasslahsen** [comment]
@bluelurker, 

 springdoc-openapi is based on swagger-core annotations.
@ApiResponse is not a springdoc annotation. And the description type is String.

 You can use the OperationCustomizer.

```java
@Component
class OperationCustomizerWithEnums implements OperationCustomizer {
	@Override
	public Operation customize(Operation operation, HandlerMethod handlerMethod) {
		if ("getCustomerList".equals(handlerMethod.getMethod().getName())) {
			for (Map.Entry<String, io.swagger.v3.oas.models.responses.ApiResponse> entry : operation.getResponses().entrySet()) {
				if ("400".equals(entry.getKey())) {
					io.swagger.v3.oas.models.responses.ApiResponse apiResponse = entry.getValue();
					apiResponse.setDescription(Errors.E101.description);
				}
			}
		}
		return operation;
	}
}
```

If you want it for the all the http 400 responses, you can use OpenAPICustomiser .
- https://springdoc.org/faq.html#how-can-i-customise-the-openapi-object-

More examples of code are available on the tests of the project.

**Comment by bluelurker** [comment]
Thank you OpenApiCustomer did the trick.
