### ISSUE TITLE
Can't seem to generate docs for InputStream parameters

### ISSUE THREAD

**Issue by chadselph** [springdoc/springdoc-openapi#631]
**Describe the bug**
I'm writing a controller that does a "direct" file upload (i.e. send the content in the body, without multi-part encoding. like `curl --upload-file`). When I use the type `InputStream` for my request body, the generated openapi docs omit the field. For example:

```java
  @PostMapping(path = "/upload")
  public String upload(@RequestParam final String someParam, @RequestBody final InputStream body) {
    return "";
  }
```

produces

```yaml
paths:
  /upload:
    post:
      operationId: upload
      parameters:
      - name: someParam
        in: query
        required: true
        schema:
          type: string
      responses:
        "200":
          description: default response
          content:
            '*/*':
              schema:
                type: string
```

Well, an InputStream could be anything, not necessarily a file, so it kind of makes sense but even when I add annotations from `io.swagger.v3.oas.annotations`

```java
  @PostMapping(path = "/upload")
  public String upload(
      @RequestParam final String someParam,
      @io.swagger.v3.oas.annotations.parameters.RequestBody(
              content =
                  @Content(
                      mediaType = "application/octet-stream",
                      schema = @Schema(type = "string", format = "binary")))
          @RequestBody
          final InputStream body) {
    return "";
  }
```

Interestingly, when I change the parameter type to `File`, the code fails at runtime but it does produce the correct swagger code, even without the additional annotations.

```java
  @PostMapping(path = "/upload")
  public String upload(@RequestParam final String someParam, @RequestBody final File body) {
    return "";
  }
```

```yaml
paths:
  /upload:
    post:
      operationId: upload
      parameters:
      - name: someParam
        in: query
        required: true
        schema:
          type: string
      requestBody:
        content:
          '*/*':
            schema:
              type: string
              format: binary
      responses:
        "200":
          description: default response
          content:
            '*/*':
              schema:
                type: string
```
To be clear, the `requestBody` section is what is missing in the other ones. And with annotations on File, I'm able to change the content-type and format.

**Versions**
Spring boot 2.2.4 plus
```
[INFO] +- org.springframework.restdocs:spring-restdocs-mockmvc:jar:2.0.4.RELEASE:test
[INFO] |  +- javax.servlet:javax.servlet-api:jar:4.0.1:test
[INFO] |  \- org.springframework.restdocs:spring-restdocs-core:jar:2.0.4.RELEASE:test
[INFO] +- org.springdoc:springdoc-openapi-core:jar:1.1.44:compile
[INFO] |  \- org.springdoc:springdoc-openapi-common:jar:1.1.44:compile
[INFO] |     +- io.swagger.core.v3:swagger-models:jar:2.0.9:compile
[INFO] |     +- io.swagger.core.v3:swagger-annotations:jar:2.0.9:compile
[INFO] |     \- io.swagger.core.v3:swagger-integration:jar:2.0.9:compile
[INFO] |        +- io.github.classgraph:classgraph:jar:4.6.32:compile
[INFO] |        \- io.swagger.core.v3:swagger-core:jar:2.0.9:compile
[INFO] |           +- com.fasterxml.jackson.dataformat:jackson-dataformat-yaml:jar:2.10.2:compile
[INFO] |           \- javax.validation:validation-api:jar:2.0.1.Final:compile
```

**Expected behavior**
I expect the behavior I get with a File parameter, which produces a spec like this one https://swagger.io/docs/specification/describing-request-body/file-upload/

**Comment by bnasslahsen** [comment]
@chadselph, 

 Please have a look at the list of the ignored types:
 - https://springdoc.org/faq.html#what-are-the-ignored-types-in-the-documentation

 However, if you add @RequestBody (spring annotation), it should work as expected.
 You didn't specify the version of springdoc-openapi are you using...

 Please before opening any issue, have a look at the contribution guide section Using GitHub Issues:
 - https://github.com/springdoc/springdoc-openapi/blob/master/CONTRIBUTING.adoc


 Tested with the last version of springdoc-openapi v1.3.6 without any issues:

```java
@RestController
public class HelloController {

	@PostMapping(path = "/upload")
	public String upload(@RequestParam final String someParam, @RequestBody  @io.swagger.v3.oas.annotations.parameters.RequestBody(
			content =@Content(mediaType = "application/octet-stream",schema = @Schema(type = "string", format = "binary"))) final InputStream body) {
		return "";
	}

}
```

 This ticket will be closed, and there is no need to reopen a new open for the same issue. You can add your comments if needed and we will follow it.

**Comment by chadselph** [comment]
Thanks for the quick reply @bnasslahsen. I did mention the springdoc version, it's in that section of mvn dependency:tree output. I wasn't sure which artifacts were relevant so I just did everything with springdoc and below. I was 1.1.44.

I've updated to v1.3.6 and the same code that previously was broken is working 🎉
