### ISSUE TITLE
support  for spring rest data jpa

### ISSUE THREAD

**Issue by raghuraman1** [springdoc/springdoc-openapi#632]
Hi,
@bnasslahsen 
Does springdoc support or plans to support documentation for spring rest data jpa.

Mainly it needs to detect some interfaces like org.springframework.data.repository.PagingAndSortingRepository and understand @RepositoryRestResource
See if needed : https://spring.io/guides/gs/accessing-data-rest/

What would be the best way to inject this additional behaviour?
Using a custom converter?
Whats a good starting point?
R

**Comment by bnasslahsen** [comment]
Hi @raghuraman1, 

 Ideally, enhancing by springdoc-openapi-data-rest.
 For the moment, we have already the support for @QueryDslPredicate, spring-hateoas and Pageable are already supported.

 There still more work to support: @RepositoryRestResource and the other spring-data-rest. But not yet a priority, as you can see, we are still focusing on the core functionnalities of the library
