### ISSUE TITLE
Response Content-Type header changed in version 1.3.5

### ISSUE THREAD

**Issue by prondzyn** [springdoc/springdoc-openapi#633]
**Describe the bug**
Till version 1.3.4 I was getting `application/json;charset=UTF-8` in `Content-Type` header. 
Since 1.3.5 I have `text/plain;charset=UTF-8`.

**To Reproduce**
Just check the `Content-Type` header value.

**Expected behavior**
Expecting to have `application/json;charset=UTF-8` again.

**Comment by bnasslahsen** [comment]
@prondzyn, 

If you are reporting a bug, please help to speed up problem diagnosis by providing as much information as possible:
 Please have a look at the section Using GitHub Issues, and provide all the necessary information:
https://github.com/springdoc/springdoc-openapi/blob/master/CONTRIBUTING.adoc
