### ISSUE TITLE
Allow defining a method as explicitly not requiring security

### ISSUE THREAD

**Issue by yissacharcw** [springdoc/springdoc-openapi#639]
**Is your feature request related to a problem? Please describe.**
We have an API where all methods are secured except for a few. Currently SpringDoc requires `@SecurityRequirement` on all the methods that require security and leaving the others blank.

**Describe the solution you'd like**
We would like to instead define the security requirement globally (possible currently by using `OpenApiCustomiser`) and then only annotate the methods that do not require security.

**Describe alternatives you've considered**
In our `OpenApiCustomiser` we can manually exclude the paths that do not require security. The problem with this is twofold:

1. It moves the security away from the method definition so it is not obvious looking at a method whether it requires security or not
1. Our `OpenApiCustomiser` is generic and used for multiple microservices which all have different unsecured paths. Defining the paths manually makes it difficult to have the `OpenApiCustomiser` be generic.

**Comment by bnasslahsen** [comment]
Hi @yissacharcw, 

 You can enable the global security using `@OpenAPIDefinition` as follow:

```java
@SecurityScheme(
		name = "bearerToken",
		type = SecuritySchemeType.HTTP,
		scheme = "bearer",
		bearerFormat = "JWT"
)
@OpenAPIDefinition(security = @SecurityRequirement(name = "bearerToken"))
```

And then, on the particular method you want exclude, you add the following annotation on the method level: `@SecurityRequirements`
