### ISSUE TITLE
Schema.readOnly/writeOnly ignored on class attribute ignored

### ISSUE THREAD

**Issue by antechrestos** [springdoc/springdoc-openapi#64]
The following code

```kotlin
@Schema(name = "Entity", requiredProperties = ["required"])
data class Entity
@JsonIgnore
constructor(@Schema(name="id", type="string", readOnly = true ) @JsonProperty("id") val id: String,
            @JsonProperty("required") val required: String,
            @JsonProperty("optional") val optional: String? : "") 
```

generates the following documentation

```
{
 //...
 "HttpPush":{
    "required":["required"],
     "type":"object",
     "properties":{
            "required":{"type":"string"},
            "optional":{"type":"string"}
      }
 }
 //...
}
```
The attribute `readOnly` is not read.

Thanks

**Comment by springdoc** [comment]
Hi, 

You can add @Schema annotations on the attribute level instead of constructor.
Please note that read-only is deprecated and you should be using accessMode = AccessMode. READ_ONLY instead.

**Comment by antechrestos** [comment]
@springdoc in the example above it is both constructor parameter and attribute that are annotated. I will test the solution you pointed and will let you know. Thanks
