### ISSUE TITLE
Rename Schema Object returned

### ISSUE THREAD

**Issue by Ichigo85** [springdoc/springdoc-openapi#642]
Hi. I have a generic type object for my controller response, Response<Type>, which I would like to rename on swagger.json generation to something different from a name ResponseType (for every type name that I want). I thought that something like this could work, but it's ignored.

```
@Operation(operationId = "getGroups", ...)
@GetMapping(path = "group")
@Schema(name = "PageOfGroup")
    public Response<Group> getGroups() {
...
}
```

which generates something like
```
...
schema": {
     "$ref": "#/components/schemas/ResponseGroup"
}
...
"components": {
		"schemas": {
                          "ResponseGroup": {
                                       "type": "object",
                                       ...
                          }
                 }
}
```

But I would like it to be called with a different name, without changing everything. Is that possible?

**Comment by bnasslahsen** [comment]
@Ichigo85, 

 This request is not related to springdoc-openapi but to swagger-core.

 You can have a look at the description at the swagger github:
 - https://github.com/swagger-api/swagger-core/issues/3323

 There is a sample of swagger annotations that you can use to have your custom response;
