### ISSUE TITLE
@RepositoryRestResource Example

### ISSUE THREAD

**Issue by JoeMcCaffrey** [springdoc/springdoc-openapi#644]
Hello - Is RepositoryRestResource supported at all? 

I have tried to annotate with @Operation but can't seem to get it to work.

I've also searched for a unit test with RepositoryRestResource as an example but cannot find one.

Can one annotate with @Operation without a @Path or HTTP Verb? (@GET)

**Comment by bnasslahsen** [comment]
Hi @JoeMcCaffrey, 

 If you didn't find any unit test about it, that simply means not yet supported.
 Its also listed here:
 - https://springdoc.org/

 You can have a look at my answer for the reasons:
 - https://github.com/springdoc/springdoc-openapi/issues/282, 

 One of the main goals of springdoc-openapi is to achieve automatic documentation generation (when possible).  

The support of `@RepositoryRestResource`, just was not the priority as there was no simple way for the automatic generation at application startup.

But for the manual annotations, even the `@Operation` does not contain the path, it can be added for the next release (hopefully).

You can also contribute to add the support if you feel conforable with this topic...

**Comment by bnasslahsen** [comment]
Hi @jdbranham, @JoeMcCaffrey,

 I have started looking at the support of the @RepositoryRestResource out of the box.
 I will push a first version to master today and you can have a look for enhancements.

 We hopefully will release the first support @RepositoryRestResource  by the end of this week (Friday 29th May).

**Comment by jdbranham** [comment]
That's great! I'll test it in my current project!

**Comment by loukkyy** [comment]
I am using springdoc-openapi-data-rest release 1.4.0 and my repositories are annotated with  `@RepositoryRestResource`.
Is there anything else to configure? Because, it doesn't seem to generate the doc for these repo...
