### ISSUE TITLE
ModelConverters are registered multiple times 

### ISSUE THREAD

**Issue by valentinabojan** [springdoc/springdoc-openapi#647]
Hi,

We're using springdoc-openapi 1.3.4 and wrote some tests for swagger doc generation. As all our tests are annotated with @SpringBootTest, the model converters will be registered for every test class. In order to mitigate this, we would need to use your approach from test.org.springdoc.api.AbstractSpringDocTest and unregister all model converters on @AfterAll.

However, this approach is not applicable for us, as we run our tests in parallel.

There would be useful if the model converters are registered only if they are not already.  This way that cleanup on @AfterAll would not be necessary anymore for sequential tests and for the parallel tests would be covered out of the box.

**Comment by bnasslahsen** [comment]
@valentinabojan, 

 Your description is not clear.
 Maybe you can add some code samples or propose a PR directly, if its an improvement.

**Comment by valentinabojan** [comment]
The main problem is that for every test class the model converter beans are scanned and registered in the ModelConverters (this is done in ModelConverterRegistrar class). If we don't clean up the registered converters after the test class is done, they accumulate as for the next test class will be registered again.

Same model converter registered twice will alter the generated swagger docs.

**Comment by bnasslahsen** [comment]
@valentinabojan, 

 I see your point; And thanks again for your great contribution.
  Your PR, is now merged with master and should be released today.

**Comment by valentinabojan** [comment]
@bnasslahsen I cannot find version 1.3.9 in maven central repo. Was it really released?

**Comment by bnasslahsen** [comment]
Hi @valentinabojan, 

 It was absolutley planned for the night. But it seems oss.sonatype.org was not available temporarily.
 Its relaunched now, and deployed.
