### ISSUE TITLE
Static javascript and css not serving

### ISSUE THREAD

**Issue by airam85** [springdoc/springdoc-openapi#649]
We have a Java Spring Boot application running 2.2.5.RELEASE.
We are using springdoc-openapi-ui and springdoc-openapi-security version 1.3.0 (also tried 1.3.6).  Ingress Nginx configured with the x-forwarded-prefix annotation (as seen in [this isue](https://github.com/kubernetes/ingress-nginx/issues/3670)):
`nginx.ingress.kubernetes.io/x-forwarded-prefix: "true"`

We have tried both the yaml:
```
server.use-forward-headers: true
server.forward-headers-strategy: framework
```

And the bean:
```
@Bean
ForwardedHeaderFilter forwardedHeaderFilter() {
        return new ForwardedHeaderFilter();
} 
```

The issue is, with this configuration the index.html gets served, but the .js and .css don't because the paths are relative and the context path is not used. What I mean is, since our server is:
http://server/context-path/swagger-ui.html
This redirects to http://server/context-path/swagger-ui/index.html?configUrl=/context-path/v3/api-docs/swagger-config
The index.html gets served, but as the code is:
`<script src="./swagger-ui-bundle.js"> </script>`
The URL of this js loaded is
http://server/context-path/swagger-ui-bundle.js
Which gets a 404 since the js is actually in
http://server/context-path/swagger-ui/swagger-ui-bundle.js
You can see this in this screen capture:
![image](https://user-images.githubusercontent.com/4747429/81089019-16952f80-8efc-11ea-9da9-279cd6d74c58.png)

Is there any configuration so the static files load from the correct path?

**Comment by bnasslahsen** [comment]
@airam85, 

 There is no static files configuration required. And there is no known issue about your description.

 You can have a look at the answer here: https://github.com/springdoc/springdoc-openapi/issues/607

 You should just make sure, all the steps described here are respected:
 - https://springdoc.org/faq.html#how-can-i-deploy-springdoc-openapi-ui-behind-a-reverse-proxy

**Comment by airam85** [comment]
I've found a similar issue here: [215](https://github.com/springdoc/springdoc-openapi/issues/215)

To my knowledge, I've already put all those options and tried to explained it in the issue.

**Comment by bnasslahsen** [comment]
Its the only necessary settings on springdoc-openapi side.
If you are still having issues, you should revisit your infrastructure configuration.
