### ISSUE TITLE
Global Parameter issue

### ISSUE THREAD

**Issue by okosiuta** [springdoc/springdoc-openapi#65]
Hi!

I want to add an authentication header to the parameter section on the Swagger UI.
I tried to do it in a next way:

```Java
@Bean
    public OpenAPI customOpenAPI(@Value("${springdoc.version}") String apiVersion) {
        return new OpenAPI()
                .components(new Components()
                        .addParameters("auth", new Parameter()
                                .name("Authorization")
                                .required(true)
                                .in("header")
                                .description("Idp token")
                                .schema(new StringSchema())))
                .info(new Info().title("Connect API").version(apiVersion));
    }
```

```Java
@GetMapping(value = "employees", params = "query")
    public Mono<List<Employee>> getEmployeeByName(@Parameter(description = "Employee name", required = true)
                                                  @RequestParam("query") String value,
                                                  @Parameter(ref = "auth") String header)
```

Result: 

![Auth](https://user-images.githubusercontent.com/51987498/63776231-a0aae400-c8e9-11e9-81e7-602efb5827f4.PNG)

After populating parameter fields and executing the request Authorization header didn't appear in the request headers. But if I change header name for example "auth" everything works like a charm. 

P.S. Is there any opportunity to inject Parameters to request without passing them to the method arguments.

Thank you.

**Comment by springdoc** [comment]
Hi, 

 You can have multiple ways to pass Authorization Header, and set it globally.

Here is an example:

```java
@Bean
public OpenAPI customOpenAPI(@Value("${springdoc.version}") String apiVersion) {
	return new OpenAPI()
			.components(new Components().addSecuritySchemes("api-key",
					new SecurityScheme().type(SecurityScheme.Type.APIKEY).in(In.HEADER).name("Authorization")))
			.info(new Info().title("Connect API").version(apiVersion));
}

@Operation(security = { @SecurityRequirement(name = "api-key") })
@GetMapping(value = "employees", params = "query")
public Mono<List<TweetDTO>> getEmployeeByName(
		@Parameter(description = "Employee name", required = true) @RequestParam("query") String value) 
```

**Comment by okosiuta** [comment]
Thank you for your response, but I want to add the header as a parameter as shown above on the screenshot.
Maybe you can suggest to me with another option or help me with my code sample.
Actually, issue reproduces only when header named Authorization in other cases everything works fine.

**Comment by springdoc** [comment]
You can have a look at the OpenAPI Specification:  Authorization header is on a blacklist
`If in is "header" and the name field is "Accept", "Content-Type" or "Authorization", the parameter definition SHALL be ignored.`

 -  https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.2.md#parameterObject

 The behaviour you are facing is related to swagger-ui (js)  which tries to follow the specification as closely as possible:
- https://github.com/swagger-api/swagger-js/issues/1405

If you want to use the UI with the Authorization Header, you should use the security definitions and requirements as mentioned above.
