### ISSUE TITLE
Map custom annotations to swagger information via "hooks"

### ISSUE THREAD

**Issue by pcornelissen** [springdoc/springdoc-openapi#650]
We are using springfox in a large project with many services. The project makes heavy use of custom annotations that are used for data protection etc. and in spring fox we use some kind of plugins to map these custom annotations to information in the swagger doc.
This way we have a canonical source for the API and other tools and processes can operate on a single file that describes the API.

As far as I have seen, this doesn't seem to be possible with springdoc-openapi, which is a bummer, because I'd like to move away from springfox for the obvious reasons you also describe in your FAQ.

Do you see a chance of providing some kind of hooks/plugin/... mechanism to be able to achieve something like that?

**Comment by bnasslahsen** [comment]
@pcornelissen, 

 I am not sure to understand well your request.
 Could you please add an code example of the requested functionnality and the expcted behaviour in terms of OpenAPI spec generation.

**Comment by bnasslahsen** [comment]
@pcornelissen, 

  Any news about providing a code example of the requested functionnality and the expcted behaviour in terms of OpenAPI spec generation?

**Comment by pcornelissen** [comment]
I can't provide source code as it's my customers code.
They are using the springfox OperationBuilderPlugin interface forexample and based on custom annotations they add VendorExtentions like "ObjectVendorExtentions" and others to create swagger entries for headers and default responses based on our security abstraction that is in use everywhere in the project.

I'm sory I can't be more specific here, but this is a standard springfox mechanism. Similar to a "hook" that is called during the analysis of the sourcecode to modify the generated swagger doc

**Comment by bnasslahsen** [comment]
Hi @pcornelissen, 

 Not sure about your requirement. 
 You can have a look at the different springdoc OpenAPI Customizers  (OpenAPI / Operation / Parameter / Property ) which might help.

- OpenApiCustomiser: To customize the OpenAPI object
- OperationCustomizer: To customize an operation based on the HandlerMethod 
- ParameterCustomizer: To customize a parameter based on the MethodParameter
- PropertyCustomizer: To customize a schema property based on the AnnotatedType

If you its not enough. You can describe your feature more precisely and we will address it.

**Comment by pcornelissen** [comment]
Ah, I didn't find that. Thanks, that should do it.
