### ISSUE TITLE
Unable to create a group via properties, only via bean

### ISSUE THREAD

**Issue by antonalechnovic** [springdoc/springdoc-openapi#653]
**Describe the bug**

**openapigroups.properties**
```
springdoc.group-configs[0].group=bla
springdoc.group-configs[0].packages-to-scan=com.bla 
```

as 

```
@PropertySource("classpath:openapigroups.properties")
public class OpenApiConfiguration {

```

does not work. Group is not accessible on the api spec endpoint.

**application.yml**
```
springdoc:
  group-configs:
    -
      group: bla
      packages-to-scan: ['com.bla']
```
does not work. Group is not accessible on the api spec endpoint.

```
    @Bean
    public GroupedOpenApi userOpenApi() {

        String[] packagedToMatch = { "com.bla" };
        return GroupedOpenApi.builder()
                             .setGroup("bla")
                             .packagesToScan(packagedToMatch)
                             .build();
    }

```
works.

**Comment by bnasslahsen** [comment]
Hi @antonalechnovic, 

 You can have a look at the following source code, which shows the two ways of creating groups:
 - https://github.com/springdoc/springdoc-openapi-demos/tree/master/springdoc-openapi-test-app2

**Comment by antonalechnovic** [comment]
Thanks here as well, I think my problem was old version :+1:
