### ISSUE TITLE
Allow nested @Schema annotations

### ISSUE THREAD

**Issue by agustisanchez** [springdoc/springdoc-openapi#655]
With the `Schema` class, it is possible to define nested properties this way:

```java
        new Schema().type("object")
                .addProperties("prop1",
                        new Schema().type("string"))
                .addProperties("prop2", 
                        new Schema().type("boolean"));
```

Apparently there's no way to achieve the same with the related `@Schema` annotation which forces to define classes only to generate documentation, which is not a good practice.

**Comment by zarebski-m** [comment]
Both `Schema` class and `@Schema` annotation are part of swagger-core project, not springdoc-openapi. Please open feature request there: https://github.com/swagger-api/swagger-core

**Comment by agustisanchez** [comment]
Moved to https://github.com/swagger-api/swagger-core/issues/3547
