### ISSUE TITLE
Java Byte considering as String

### ISSUE THREAD

**Issue by mcamelot** [springdoc/springdoc-openapi#656]
**Describe the bug**
Java Byte is considering as String in swagger

**To Reproduce**
Creates a Class with a Byte attribute

```java
public class Foo {
    @JsonProperty("bar")
    private Byte bar;
}
```

it's producing in api-doc

```json
{
    "bar": {
        "type": "string",
        "format": "byte"
    }
}
```

**Expected behavior**
According to the swagger documentation
https://swagger.io/docs/specification/data-models/data-types/#numbers

Byte (int-16) does not seems to be managed.
But i expected to have an integer  or number and not a string type.

Thanks

**Comment by bnasslahsen** [comment]
@mcamelot, 

 springdoc-openapi relies on swagger-core which implements the OpenAPI sepecification.
 There is already existing request related to this issue that you can follow:
 - https://github.com/swagger-api/swagger-core/issues/3171

 Alternatively you can use @Schema on the top of your property to change the type.
