### ISSUE TITLE
GroupedOpenApi OperationCustomizer 

### ISSUE THREAD

**Issue by torshid** [springdoc/springdoc-openapi#658]
Hi,
I tried to customize my operations with OperationCustomizer according to GroupedOpenApi but couldn't find a way to do so. Is it possible?
Thank you.

**Comment by bnasslahsen** [comment]
Hi @torshid, 

 Once you declare the OperationCustomizer, it will be applied to all the operations.
 If you want it to be applied to only to a scope of Operations related to your GroupedOpenApi. 
 This is a new feature which seems interesting and will be available for the next release

**Comment by torshid** [comment]
I appreciate your answer. Thanks you for your work. :)
