### ISSUE TITLE
Content-type: application/json is not autogenerated for @RestController return type?

### ISSUE THREAD

**Issue by antonalechnovic** [springdoc/springdoc-openapi#659]
Example:
```
@Tag(name = "deployments")
@RestController
public class DeploymentController {
    @PostMapping("/bla")
    @ResponseStatus(HttpStatus.ACCEPTED)
    @Operation(operationId = "deployment")
    public DeploymentPostResponse createDeployment(@Valid @RequestBody DeploymentPostRequest deploymentPostRequest) {
return new DeploymentPostRequest();
}
}
```
Generates (note missing content-type: application/json, request however has it)
```
{
  "responses": {
    "202": {
      "description": "Accepted",
      "content": {
        "*/*": {
          "schema": {
            "$ref": "#/components/schemas/DeploymentPostResponse"
          }
        }
      }
    }
  }
}
```
Then after adding @Opeation with application/json on `createDeployment`
```
@Operation(operationId = "deployment", responses=@ApiResponse(content = @Content(mediaType = "application/json")))
```

I get:
```
{
  "responses": {
    "default": {
      "description": "default response",
      "content": {
        "application/json": {}
      }
    }
  }
}
```

Few things which seems unclear:

1. Why content-type generated for say for request ? but not for response?
2. Would it make sense to combine autogen with annotations, annotations overriding? Or that would be too verbose?

**Comment by bnasslahsen** [comment]
Here is the explanation:

`springdoc.default-consumes-media-type` default value is: `application/json`	
And `springdoc.default-produces-media-type` default value is:` */*`	

 You can view more details here:
- https://springdoc.org/springdoc-properties.html#springdoc-openapi-core-properties

You can change these default values if you need.

The most important thing, is that once you fill the mediaType in the `@Operation` annotation it gets used.

You can also fill the mediaType (produces and consumes) on the level of your @PostMapping which makes more sense (so you won't need to fill it on @Operation` annotation)

**Comment by antonalechnovic** [comment]
Oh great, thanks for your time. But if I annotate my controller as @RestController should not this imply that consumes and produces are both application/json? I've seen on my age only single API which accept json and return XML it was MTN :grin:

**Comment by bnasslahsen** [comment]
@antonalechnovic, 

 No, its pure spring. You can even have many consumes and many produces (which are definitely different headers)

**Comment by antonalechnovic** [comment]
:+1: , I followed the advice, I have one response as an autogen object and another manually specified 400, if I use 'responses' it stops autogenerating 202

**Comment by bnasslahsen** [comment]
You can define HTTP 400 errors in controllerAdvice, so it can be used. So it can be half automatic (202) and half manual with HTTP (400) responses.

If its specific to one controller. Once you add responses on the controller level, it will be used as reference. So it can't be half manual and and half automatic  At this moment, you should fill the expected responses codes.
