### ISSUE TITLE
Incorrect response-type if method of REST-controller returns Mono<Map<String, Object>>

### ISSUE THREAD

**Issue by mlatypov** [springdoc/springdoc-openapi#662]
**Describe the bug**
I try to generate OpenAPI-schema with `springdoc-openapi-webflux-ui`, version `1.3.9` for my REST-controller which returns `Mono<Map<String, Object>>` and I see incorrect response type (Object instead of Map) in generated yaml-file.

**To Reproduce**
1. Create a new controler-class with `@RestController` annotation;
2. Create a method with the following signature 
```
    @GetMapping("/test")
    public Mono<Map<String, Object>> testMap() {
        return Mono.just(new HashMap<>());
    }
```

3. Run application and download yaml-file with /api-docs.yaml endpoint

Result: responses-section contains:
```
      responses:
        "200":
          description: OK
          content: {}
```

**Expected behavior**
responses-section contains:

```
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: object
                additionalProperties:
                  type: object
```

**Comment by bnasslahsen** [comment]
@mlatypov, 

 You description is not reproducible.
 This is the generated OpenAPI response for your sample:

```yaml
  responses:
	'200':
	  description: OK
	  content:
		'*/*':
		  schema:
			type: object
			additionalProperties:
			  type: object
```
