### ISSUE TITLE
Https TypeError: Failed to Fetch

### ISSUE THREAD

**Issue by phearun008** [springdoc/springdoc-openapi#663]
Hey there!
I got an error while trying to access https server url. Is there any way to solve this problem?

![image](https://user-images.githubusercontent.com/12493037/81662237-798c4680-9467-11ea-8b95-83f64b394d22.png)

**Comment by bnasslahsen** [comment]
@phearun008, 

 You can google this error.  Its not related to springdoc-openapi but to your https configuration.
