### ISSUE TITLE
@Hidden does not work for fields named in upper camel case style

### ISSUE THREAD

**Issue by Strunevskiy** [springdoc/springdoc-openapi#664]
**Describe the bug**
- When there are fields named in upper camel case style using ```@JsonProperty``` annotation that is marked by   Hidden annotation , fields are displayed on swagger-ui and in OpenAPI spec

**To Reproduce**
- spring-boot - 2.1.4
- springdoc-openapi-ui - 1.3.9
- When there are fields named in upper camel case style using ```@JsonProperty``` and marked by   ```@Hidden``` annotation , fields are displayed on swagger-ui and in spec

```java
  @Schema(name = "FirstName")
  @JsonProperty(value = "FirstName")
  @Hidden
  private String firstName;
  public String getFirstName() {
    return firstName;
  }
  public void setFirstName(String firstName) {
    this.firstName = firstName;
  }
```

**Expected behavior**
When there are fields named in upper camel case style using ```@JsonProperty``` and marked by   ```@Hidden``` annotation , fields do not have to be displayed on swagger-ui and in spec

**Additional context**
```@Hidden``` annotation works well for not displaying fields named in lower camel case style on swagger-ui.

```@Hidden``` works well for the following case
```java
  @Schema(name = "firstName")
  @JsonProperty(value = "firstName")
  @Hidden
  private String firstName;
  public String getFirstName() {
    return firstName;
  }
  public void setFirstName(String firstName) {
    this.firstName = firstName;
  }
```

**Comment by bnasslahsen** [comment]
Hi @Strunevskiy, 

 The annotation @Hidden is a swagger-annotation.  Springdoc-openapi is built on top of this library.

 If you don't need the getters/setters the annotation will work for the case you are describing as swagger seems to be confused with your getter/setter naming !

 More generally, this issue should be logged on the swagger-project:
 - https://github.com/swagger-api/swagger-core

**Comment by Strunevskiy** [comment]
@bnasslahsen  Could you please provide any hint of how I can form question for swagger-core regarding the described issue?

**Comment by bnasslahsen** [comment]
You describe the same way as you did.
You can reference directly swagger classes call, for example:

```java
public class Foo {

	@Schema(name = "FirstName", hidden = true)
	@JsonProperty(value = "FirstName")
	@Hidden
	private String firstName;

	@JsonProperty(value = "lastName")
	private String lastName;

	public String getFirstName() {
		return firstName;
	}
	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}
}
```
And a sample test to expalin, for exampel:

```java
ResolvedSchema resolvedSchema = ModelConverters.getInstance()
		.resolveAsResolvedSchema(new AnnotatedType(Foo.class));
if (resolvedSchema.schema != null) {
	Schema schemaN = resolvedSchema.schema;
	Map<String, Schema> schemaMap = resolvedSchema.referencedSchemas;
	Assert.isNull( schemaMap.get("Foo").getProperties().size()==1, "Foo should only contain lastName");

}
```

**Comment by Strunevskiy** [comment]
@bnasslahsen  Thank you
