### ISSUE TITLE
swagger-ui custom layout issue

### ISSUE THREAD

**Issue by schedella** [springdoc/springdoc-openapi#666]
**Is your feature request related to a problem? Please describe.**
- I am able to configure the swagger-ui Base Layout using spring boot properties. as per swagger-ui documentation we can create custom layout using React but no guidelines to integrate that in springboot application.

**Describe the solution you'd like**
- Expecting a way of creating custom layout using Java API.

**Additional context**
- If someone already tried custom layout using springdoc-openapi then please provide the steps/guidelines

**Comment by bnasslahsen** [comment]
@schedella, 

 springdoc-openapi uses the official swagger-ui webjars.
 If you need create your custom layout, you need to build your own webjars.
Here is the simple way to integrate it:
 - Get the lastest version https://github.com/swagger-api/swagger-ui
 - Add your custom layout
 - Package your application a webjar or add it as static resources in your application
 - On the springdoc-openapi-ui dependency, **exclude** the following dependency:

```xml
		<dependency>
			<groupId>org.webjars</groupId>
			<artifactId>swagger-ui</artifactId>
		</dependency>
```
