### ISSUE TITLE
Reverse proxy + base path on the app create UI issue

### ISSUE THREAD

**Issue by jaubin** [springdoc/springdoc-openapi#667]
**Describe the bug**
Hi,

I have a webapp that's accessible this way : 
http://localhost:8080/foo
My Swagger URI is defined with path /swagger and reachable through : 
http://localhost:8080/foo/swagger

I have now a reverse proxy with a base URL like this and the following reverse proxy rules : 
Base URL : http://myreverseproxy/external
Rules : 
http://myreverseproxy/external/foo -> http://<servicehost>:<port>/foo

The X-Forwarded-For header of the proxy contains only : http://myreverseproxy/external/ (this is due to the fact we do have *many* services on the reverse proxy due to a somewhat complicated setup)

I've enabled the usual trick with Spring Boot and the server.forward-headers-strategy set to framework. However when I'm accessing the web page Swagger UI attempts to redirect itself to : 
http://myreverseproxy/external/swagger-ui.html instead of http://myreverseproxy/external/foo/swagger-ui.html

I've tried everything including playing with the path of the Swagger UI but got stuck at some time or other.

**To Reproduce**
- What version of spring-boot you are using? 
Springboot version : 2.2.6.RELEASE
- What modules and versions of springdoc-openapi are you using?
1.3.0

- What is the actual and the expected result using OpenAPI Description (yml or json)?
Expected : we get the /external/foo prefix (I could make this work but it breaks some other parts of Swagger UI)

- Provide with a sample code (HelloController) or Test that reproduces the problem
A reverse proxy which indicates only part of the path due to multiple services behind this proxy
A web service with a subpath as its root path.

Example : X-Forwarded-For prefix set to : http://myreverseproxy/external and webservice root path set to : http://myreverseproxy/external/foo

**Expected behavior**
- A clear and concise description of what you expected to happen.
- What is the expected result using OpenAPI Description (yml or json)?

Expected : have a way to specify a relative path under the reverse proxy path.

**Screenshots**

**Additional context**

**Comment by bnasslahsen** [comment]
@jaubin, 

 Please use the last stable version for your tests: v1.3.9.

**Comment by jaubin** [comment]
Same behaviour with 1.3.9

**Comment by bnasslahsen** [comment]
Please add your configuration properties related to springdoc-openapi.

**Comment by jaubin** [comment]
springdoc.swagger-ui.path: /swagger
springdoc.paths-to-exclude: /health
springdoc.swagger-ui.configUrl: /external/foo/v3/api-docs/swagger-config

**Comment by bnasslahsen** [comment]
@jaubin, 

 how is /foo set in your application which property are you using: server.servlet.context-path  or spring.mvc.servlet.path?

Do you confirm you have used server.forward-headers-strategy=framework and restarted your application and your proxy after the changes as well ?

**Comment by jaubin** [comment]
Hi, it is set using server.servlet.context-path

I confirm for the server.forward-headers-strategy trick.

**Comment by bnasslahsen** [comment]
Hi @jaubin, 

 `springdoc.swagger-ui.configUrl`, is not necessary.
 Here is a sample minimal working configuration for your description, tested with apache:
 Please make sure, you restart you proxy and your backends after the changes. 

```properties
springdoc.swagger-ui.path= /swagger
springdoc.paths-to-exclude= /health
server.servlet.context-path=/foo
server.forward-headers-strategy=framework
```
And on the proxy side:

```
ProxyPass "/external"  "http://localhost:8080/"
ProxyPassReverse "/external"  "http://localhost:8080/"
RequestHeader set X-Forwarded-Prefix "/external/foo"
```

**Comment by jaubin** [comment]
I'm aware of the X-Forwarded-Prefix trick but due to the use of various technology we cannot play on this parameter sadly. Would it be possible to add some "relativePathToPrefix" to work around this ?

**Comment by bnasslahsen** [comment]
`X-Forwarded-Prefix` is standard header supported by most of the web servers.
Changing standard Headers logic or adding custom handling might lead to errors or regressions for other projects.
If you need to add any custom logic, you can fork the project and add your own variable.

**Comment by jaubin** [comment]
OK thanks
