### ISSUE TITLE
Process @Parameters method parameters as Spring MergedAnnotations

### ISSUE THREAD

**Issue by jryan128** [springdoc/springdoc-openapi#669]
**Is your feature request related to a problem? Please describe.**
I want to be able to used Spring MergedAnnotations for `@Parameter` inside controller **method parameters**(`@RequestParam, @PathVariable`) (method annotations are actually Merged) 

**Describe the solution you'd like**
https://github.com/springdoc/springdoc-openapi/pull/668

**Describe alternatives you've considered**
- None

**Additional context**
- Add any other context or screenshots about the feature request here.

**Comment by jryan128** [comment]
Sorry I closed it on accident, this functionally does not exist currently in springdoc-openapi.

**Comment by bnasslahsen** [comment]
Fixed thank to #668.
