### ISSUE TITLE
Object request parameter issue

### ISSUE THREAD

**Issue by okosiuta** [springdoc/springdoc-openapi#67]
Hi!

Thank you for providing this awesome library.
I wrote the next code sample:

```java
@Operation(summary = "Get employee", tags = {"Employee"})
    @GetMapping(value = "employee")
    public Mono<Employee> searchEmployee(String id, RequestParameter requestParam) {
        return Mono.empty();
    }
```
```java
public class RequestParameter {
    String firstParam;
    String secondParam;
}
```

Swagger UI result:

![Embedded_Parameters](https://user-images.githubusercontent.com/51987498/63859326-d7e3c880-c9af-11e9-8ab6-8114af1b56cb.PNG)

And I wonder if there any way to show RequestParameter, not as an object but as a list of object properties.

Thank you!

**Comment by springdoc** [comment]
Hi, 

  We generate the OpenAPI description, and then we mainly reley on the official swagger jars (annotations/models/ui) .

 This is the behaviour of swagger-ui. And there is a related enhancement on swagger-ui that we follow. This isn't yet resolved: 
- https://github.com/swagger-api/swagger-ui/issues/4581
