### ISSUE TITLE
Setting empty content for responses does not work anymore

### ISSUE THREAD

**Issue by AmreenWahab** [springdoc/springdoc-openapi#672]
It was possible to set empty content for responses using, 
`content = @Content` or `content = @Content(schema = @Schema(hidden = true))` as mentioned in #305 and https://springdoc.org/faq.html#how-can-i-return-an-empty-content-as-response
But recently, its not working and all responses contain examples/schema even after adding the above syntax

- We are using spring-boot version 2.2.7
- We are using springdoc-openapi-ui module with version 1.2.30

**Comment by bnasslahsen** [comment]
Hi @AmreenWahab, 

 Please use v1.3.9 which is the last stable release.
 If you are having any issue. Please add sample code to reproduce.
