### ISSUE TITLE
Multiple values for method level @RequestMapping

### ISSUE THREAD

**Issue by mobouchard** [springdoc/springdoc-openapi#676]
Hi, 

We have REST controller methods with multiple value for the `RequestMapping` annotations.
E.g.: 
```
@GetMapping(value = {"/v1/foo", "/v2/foo"}, produces = MediaType.APPLICATION_JSON_VALUE)
public Object getFoo(@RequestParam("bar") int bar) {
   // get some stuff
}
```

However when we request the OpenAPI definition (both UI and JSON), we only get the first mapping value (i.e. `/v1/foo` from the previous example).

I would say this is a bug, unless there's something that can be done/configured on our end?

**Comment by bnasslahsen** [comment]
Hi @mobouchard, 

 Please make sure you are using the last stable version v1.3.9;
 Here is the result for the code you attached:
![image](https://user-images.githubusercontent.com/13404829/82356764-5253ed00-9a04-11ea-9c55-b4e13135ecc3.png)

**Comment by bnasslahsen** [comment]
@chasegawa,

Try Providing a [Minimal, Reproducible Example - with HelloController](https://stackoverflow.com/help/minimal-reproducible-example) that reproduces the problem
