### ISSUE TITLE
GUI does not initialise when using a reverse proxy, direct access works as expected.

### ISSUE THREAD

**Issue by abickerton-upc** [springdoc/springdoc-openapi#677]
**Describe the bug**
When accessing the GUI from behind a reverse proxy, the gui fails to initialise. 

This is an internal corporate application, so I cannot provide much more details.
Direct link : http://host:port/api/swagger.ui.html (Works )
Proxied link : https://proxy/build/swaggger.html (Fails to initialise)

The only message available in the browser console is 
"
 SwaggerUIBundle is not defined 
"
Proxy configuration (Apache)
`

ProxyPass         /build  balancer://loadbalancerGroup/api
ProxyPassReverse  /build  balancer://loadbalancerGroup/api
RequestHeader set X-Forwarded-Prefix "/build"
RequestHeader set X-Forwarded-Proto https

`
**To Reproduce**
spring boot version :  2.2.5 
springdoc-openapi-ui : 1.3.0
springdoc-openapi-webmvc-core : 1.3.0
springdoc-openapi-security : 1.3.0
springdoc-openapi-data-rest : 1.3.0

Create a spring boot application from the iniitializer site,using spring-hateoas 1.0. 
Add the spring-doc dependencies. 

  @Bean
  public OpenAPI apiDocumentation() {
    return new OpenAPI()
        .components(new Components())
        .info(
            new Info()
                .title("Service")
                .description("Service to do stuff")
                .contact(
                    new Contact()
                        .name("Service")
                        .email("XXXXXXXXXXXX")
                        .url("XXXXXXXXXXXXX"))
                .version(
                    Optional.ofNullable(
                            ServiceStarter.class.getPackage().getImplementationVersion())
                        .orElse("IDE")));
  }
 
**Expected behavior**
The GUI initialises the same way it does when accessed directly.

**Screenshots**
![openapi-reverse](https://user-images.githubusercontent.com/43068992/82351749-49135200-99fd-11ea-8611-901de6319ef4.jpg)

**Additional context**
The spring-boot application has the configuration properties described in the FAQ.

Context
server:
  use-forward-headers: true
  forward-headers-strategy: framework

A ForwardHeaderFilter bean is defined as described in the FAQ (https://springdoc.org/faq.html)

**Comment by bnasslahsen** [comment]
Hi @abickerton-upc, 

 There is no know issue about proxy configuration and your description is not enough to confirm any issue. 

 I invite you first to review your configuration.
 Please use test with the last stable version: v1.3.9 before reporting any issue.

 Make sure you restart the application and the webserver after the changes of the configuration.

 Can you validate if you are having this issue using this version as well?

  If you are reporting a bug, please help to speed up problem diagnosis by providing as much information as possible.

**Comment by abickerton-upc** [comment]
Sadly, my application doesn't even compile wiith 1.3.9. It seems the PageableAsQueryParam was removed after 1.3.0.

This is an internal corporate application, so I cannot provide much more details.
Direct link : http://host:port/api/swagger.ui.html
Proxied link : https://proxy/build/swaggger.html

**Comment by bnasslahsen** [comment]
PageableAsQueryParam is available on v1.3.9. 
 - https://github.com/springdoc/springdoc-openapi/blob/v1.3.9/springdoc-openapi-data-rest/src/main/java/org/springdoc/data/rest/converters/PageableAsQueryParam.java

Please make sure you use the right versions and your configuration is well reviewed.

**Comment by abickerton-upc** [comment]
Removing PageableAsQuery is not the problem. 
I removed it, and the same issue remains.

**Comment by bnasslahsen** [comment]
You don't need to remove PageableAsQuery. its available on v1.3.9.
There is no known issue about using reverse proxy over https. We have tried to reproduce it without any success.

If you have any issue, please provide a complete Minimal, Reproducible Example.
The elements you have provided are not enough to reproduce your issue.

Once you provide the additional elements, this issue can be reopened.

**Comment by abickerton-upc** [comment]
I request that you try reading the description of the issue, there is a problem hosting the gui behind a reverse proxy. 
AdditionalIy, I have provided enough information for the issue to be recreated trivially.   
This issue should be reopened until the problem is solved!
