### ISSUE TITLE
Spring ResponseEntity returning empty MediaType for no-body responses.

### ISSUE THREAD

**Issue by Stexxen** [springdoc/springdoc-openapi#68]
An Extension of issue #40 and commit [aef3e1f](https://github.com/springdoc/springdoc-openapi/commit/aef3e1f077835dbfded4b7282e1b1a05365f4a4c)

Also not a big problem.

I'm aware you check for a void return to determine if a content type is nessecary, however this doesn't work when using the ResponseEntity&lt;T&gt; type of response with error responses.

example
```
@Operation(summary = "Get Something by key",
    responses = {
      @ApiResponse(description = "Successful Operation", responseCode = "200",
        content = @Content(mediaType = "application/json", schema = @Schema(oneOf = {String.class, Integer.class}),
        examples = {
          @ExampleObject(name = "The String example", value = "urgheiurgheirghieurg"),
          @ExampleObject(name = "The Integer example", value = "311414")
        })),
      @ApiResponse(responseCode = "404", description = "Thing not found"),
      @ApiResponse(responseCode = "401", description = "Authentication Failure")
    }
  )
```

The @APIResponse for error conditions (401 and 404 in the example), do not have a @content specified, but the generator creates `content {}` in the output, which swagger-ui then shows an empty Media Type
![image](https://user-images.githubusercontent.com/4494301/63868999-5db34400-c9af-11e9-8883-3c719aedb749.png)

To not change existing behaviour, can I request a check for a return type of ResponseEntity<T> and then if no Content is specified treat as no-body.

I can create this as PR if you would accept it?

**Comment by springdoc** [comment]
Hi, 

 A new enhancement will be available on v1.1.31 of springdoc-openapi. 
 Please let us know, if it works for you.
