### ISSUE TITLE
name attribute does nothing in @Schema annotation

### ISSUE THREAD

**Issue by jainishan** [springdoc/springdoc-openapi#680]
**The bug**
I have an oAuth endpoint in my spring boot application for which I am using a DTO as @ModelAttribute to capture the request payload. I am trying to document the whole thing in swagger UI and I am using the springdoc for that.
Just having the @Operation annotation on the method was not working out for me as it was documenting it incorrectly. I added the brand new @ParamObject annotation and that seems to work nicely. Except one problem, the name of the attribute I am trying to specify within the @Schema annotation applied to attributes of the request DTO, they seem to be useless. I even tried setting `resolve-schema-properties: true` in application config.

**To Reproduce**

### Controller
```
@RestController
public class OauthController {


  @Operation(
      description = "Retrieve an Authentication Token",
      responses = {
          @ApiResponse(responseCode = "200"),
          @ApiResponse(responseCode = "401", content = @Content(schema = @Schema(hidden = true))),
          @ApiResponse(responseCode = "403", content = @Content(schema = @Schema(hidden = true))),
          @ApiResponse(responseCode = "422", content = @Content(schema = @Schema(hidden = true)))
      }
  )
  @PostMapping(path = ENDPOINT_OAUTH2_TOKEN, consumes = MediaType.APPLICATION_FORM_URLENCODED_VALUE)
  public ResponseEntity<AuthenticationResponse> createAuthenticationToken(
      @Valid @ModelAttribute @ParameterObject AuthenticationRequest authenticationRequest) {
	  ...
	  }
```

### AuthenticationRequest DTO
```
public class AuthenticationRequest {

  @Schema(name = "client_id", description = "Client ID as issued ")
  @NotBlank
  private String clientId;

  @Schema(name = "client_secret", description = "Client secret as issued ")
  @NotBlank
  private String clientSecret;
}
```

**Expected behavior**
I expected fields like `clientId` to show up as `client_id` but they don't.

**Comment by bnasslahsen** [comment]
@jainishan, 

 Add the getter/setter or @JsonProperty of the fields on your AuthenticationRequest DTO.

**Comment by jainishan** [comment]
I added the getter and setter. I am not sure though how they are relevant as this post is about the name property of @Schema when applied on some attribute.

**Comment by harunergul** [comment]
I think it will be very good for **@Schema** to provide the functionality of  **@JsonProperty**
