### ISSUE TITLE
Question: How to hide schemas at the bottom of swagger

### ISSUE THREAD

**Issue by dheeruasdf** [springdoc/springdoc-openapi#682]
Hide the highlighted section in the following image

![image](https://user-images.githubusercontent.com/34265120/82493967-77c91f80-9b06-11ea-8e39-bb33a024dd4a.png)

I am new to springdocs. 
In springfox swagger, I am able to manage it with css given as a part of description name like below.
descriptionName = "`This app provides REST APIs for order entities <style>.models{ display: none !important} </style>`"
But the above method is not working for springdocs.

Could someone please help me on how to hide schemas section entirely in springdocs.

Thanks

**Comment by bnasslahsen** [comment]
Hi @dheeruasdf, 

 You add `@Schema(hidden = true)` on your DTO.

**Comment by milindrao** [comment]
From other issues I have read on hiding schemas, this seems to work.  But it's not working for me.  This is what I have

```
@SuppressWarnings("rawtypes")
@Schema (example = "{\"_links\": {\"self\": {\"href\": \"https://<host>/cases/id/unique-key/case_id\"}}}", hidden = true)
class CaseHrefRepresentation extends RepresentationModel {}

```
I have declared this in an interface class.  Could that be a problem?

Also, I'd like to hide the org.springframework.hateoas.Links and the org.springframework.hateoas.Link class.  Is that possible?  Obviously I can't change the annotations on them.

**Comment by AJESH-CR** [comment]
Set value for the property `springdoc.swagger-ui.defaultModelsExpandDepth=-1` in **application.properties** as described [here](https://springdoc.org/properties.html#_swagger_ui_properties).

**Comment by kunalbarchha** [comment]
@AJESH-CR I am using micro-services, and swagger configurations are defined as bean in a common module, where there's no application.properties / yml. Any idea how to do it in the Bean definition itself so no other services importing the common module has to redo this configuration separately  ?
