### ISSUE TITLE
Unable to render this definition

### ISSUE THREAD

**Issue by nnzbz** [springdoc/springdoc-openapi#683]
**Error**
access <http://127.0.0.1:xxxx/swagger-ui.html> :

![Screen Capture_select-area_20200521091123](https://user-images.githubusercontent.com/3138908/82512575-170c0800-9b43-11ea-8251-30eee571a7a5.png)

**Development environment**

- SpringBoot 2.3.0 + springdoc 1.3.9

```xml
<dependency>
    <groupId>org.springdoc</groupId>
    <artifactId>springdoc-openapi-ui</artifactId>
    <version>1.3.9</version>
</dependency>
```

- I don't config application.yml about springdoc and swagger-ui(default)

- Application.java

```java
@OpenAPIDefinition(info = @Info(//
        title = "xxx", //
        version = "1.2.0", //
        description = "xxxxx"//
))
@SpringCloudApplication
public class Application {

    public static void main(final String[] args) {
        SpringApplication.run(Application.class, args);
    }

}
```

**Comment by nnzbz** [comment]
**But**

![Screen Capture_select-area_20200521094237](https://user-images.githubusercontent.com/3138908/82514201-b29f7780-9b47-11ea-9425-2589be2b24be.png)

**Comment by nnzbz** [comment]
**Diffrent**
- Error
  ![Screen Capture_select-area_20200521094815](https://user-images.githubusercontent.com/3138908/82514425-4ffaab80-9b48-11ea-8754-37eb143e6931.png)
- Success
  ![Screen Capture_select-area_20200521095019](https://user-images.githubusercontent.com/3138908/82514515-86d0c180-9b48-11ea-8a82-93e16b710664.png)

**Comment by nnzbz** [comment]
- Error
```
"{\"openapi\":\"3.0.1\",\"info\":{\"title\":\"JWT微服务\",\"description\":\"基于SpringCloud架构提供JWT服务\",\"version\":\"1.2.0\"},\"servers\":[{\"url\":\"http://127.0.0.1:9500\",\"description\":\"Generated server url\"}],\"paths\":{\"/jwt/verify\":{\"get\":{\"tags\":[\"jwt-ctrl\"],\"summary\":\"验证JWT签名\",\"operationId\":\"verify\",\"parameters\":[{\"name\":\"toVerifySign\",\"in\":\"query\",\"description\":\"要验证的签名\",\"required\":true,\"schema\":{\"type\":\"string\"}}],\"responses\":{\"default\":{\"description\":\"验证JWT签名的结果\",\"content\":{\"application/json; charset=utf-8\":{\"schema\":
```
- Success
```yaml
openapi: 3.0.1
info:
  title: JWT微服务
  description: 基于SpringCloud架构提供JWT服务
  version: 1.2.0
servers:
- url: "http://127.0.0.1:9500"
  description: Generated server url
paths:
  /jwt/verify:
    get:
      tags:
      - jwt-ctrl
      summary: 验证JWT签名
      operationId: verify
      parameters:
      - name: toVerifySign
        in: query
        description: 要验证的签名
        required: true
```

**Comment by nnzbz** [comment]
![Screen Capture_select-area_20200521094815](https://user-images.githubusercontent.com/3138908/82514733-17a79d00-9b49-11ea-9434-a30d31d10c4e.png)

**Comment by nnzbz** [comment]
![Screen Capture_select-area_20200521095019](https://user-images.githubusercontent.com/3138908/82514748-21c99b80-9b49-11ea-8091-929d99af1563.png)

**Comment by bnasslahsen** [comment]
@nnzbz, 

 Your OpenAPI 3 in json format is not using jackson or using a HttpMessageConverter. 
 Maybe you are using Gson or another json library that causes this issue.
 You can look at the sample code to resolve this case here.:
 - https://github.com/springdoc/springdoc-openapi/issues/624#issuecomment-628196234
