### ISSUE TITLE
Schema cannot be seems in swagger UI

### ISSUE THREAD

**Issue by kkkksiu** [springdoc/springdoc-openapi#684]
**Describe the bug**
When I created a new API with new entity, the new api can be seen in swagger UI but the schema show a empty class. The class is also empty in schemas section.

**To Reproduce**
- What version of spring-boot you are using?
2.1.8
- What modules and versions of springdoc-openapi are you using?
1.3.9

- Provide with a sample code (HelloController) or Test that reproduces the problem
New API:
	@Operation(summary = "Test on ApiError", description = "", security = { @SecurityRequirement(name = "bearer-key") })
	@RequestMapping(value = "/apiError", method = RequestMethod.PUT)
	public ApiError test() throws Exception {
		return new ApiError("a","a","a");
	}

New Class:
package com.cityline.urbtix.dtodomain.model;

public class ApiError {
    private String code;
    private String field;
    private String message;

    public ApiError(String code, String field, String message) {
        this.code = code;
        this.field = field;
        this.message = message;
    }

    @Override
    public String toString() {
        final StringBuilder sb = new StringBuilder("ApiError{");
        sb.append("code=").append(code);
        sb.append(", field='").append(field);
        sb.append(", message=").append(message);
        sb.append('}');
        return sb.toString();
    }
}

**Expected behavior**
The schema of ApiError should be shown.

**Screenshots**
API Section:
![image](https://user-images.githubusercontent.com/65699355/82525362-c2c55000-9b63-11ea-8f95-045715495433.png)
In Schemas Section:
![image](https://user-images.githubusercontent.com/65699355/82525403-de305b00-9b63-11ea-91ae-d2bb623da471.png)

**Additional context**

**Comment by bnasslahsen** [comment]
This is not an issue.
