### ISSUE TITLE
Pretty print output of springdoc-open-api-maven-plugin

### ISSUE THREAD

**Issue by dominic-jones** [springdoc/springdoc-openapi#687]
**Is your feature request related to a problem? Please describe.**
It can be useful to check OpenApi doc in to source control to view diffs of the OpenApi. For example, the annotations are altered on Spring controllers, but additionally code reviewing the content of the OpenApi json to be certain of the overall change.
The json file output by the springdoc-open-api-maven-plugin is not formatted/pretty printed by default, making it not very human-readable without extra processing.

**Describe the solution you'd like**
I would like the output to be pretty printed for human readability.

**Describe alternatives you've considered**
This could be set through a config file if not always desirable. 

**Additional context**
No additional context

**Comment by bnasslahsen** [comment]
@dominic-jones, 

 Please log your feature request on the repository of springdoc-open-api-maven-plugin:
  - https://github.com/springdoc/springdoc-openapi-maven-plugin/issues
