### ISSUE TITLE
Spring-boot 1, warning about bean creation - cache disabled

### ISSUE THREAD

**Issue by lrozenblyum** [springdoc/springdoc-openapi#689]
**Describe the bug**
The logs of start-up contain a warning
```
ConfigurationClassEnhancer - @Bean method SpringDocConfiguration.springdocBeanFactoryPostProcessor2 is non-static and returns an object assignable to Spring's BeanFactoryPostProcessor interface. This will result in a failure to process annotations such as @Autowired, @Resource and @PostConstruct within the method's declaring @Configuration class. Add the 'static' modifier to this method to avoid these container lifecycle issues; see @Bean javadoc for complete details.
```

**To Reproduce**
Spring Boot OpenApi 1.3.9
Spring Boot 1.5.13.RELEASE
Boot the app.

**Expected behavior**
- No warnings in logs due to beans definitions

**Comment by bnasslahsen** [comment]
@lrozenblyum, 

 I have tried to reproduce the log error using the demo of spring-boot 1, and using the same version of spring-boot-A:
 - https://github.com/springdoc/springdoc-openapi-demos/tree/master/springdoc-openapi-spring-boot-1

 You can find attached the startup log.
[logs.txt](https://github.com/springdoc/springdoc-openapi/files/4681825/logs.txt)

 Can you provide a simple project with HelloController that reproduces this warning so we can fix it quickly?

**Comment by lrozenblyum** [comment]
Thank you @bnasslahsen. Sorry for late response.
It looks like I haven't disable the cache (at least not explicitly).
I'll double check my configuration.
(NOTE: I'm starting Spring Boot in a Spring MVC project manually similarly to what was described in 
https://springdoc.org/faq.html 'How to Integrate Open API 3 with Spring project (not Spring Boot)?')

**Comment by bnasslahsen** [comment]
Or maybe you enabled the groups?

**Comment by lrozenblyum** [comment]
Yes, groups are enabled!

**Comment by bnasslahsen** [comment]
Yeah, this explains the reason: BeanFactoryPostProcessor is enabled if CacheOrGroupedOpenApiCondition is met.

**Comment by lrozenblyum** [comment]
Thank it's clear. Thanks for fixing @bnasslahsen
