### ISSUE TITLE
Getting yaml and json in compile time

### ISSUE THREAD

**Issue by pLotoniC** [springdoc/springdoc-openapi#69]
I need to generate those files in compile time to generate internal pdf documentation. Would it be possible or when this feature is already implemented, how can I do it?

**Comment by springdoc** [comment]
Hi, 

 This enhancement can be donne using a maven plugin.
 We can plan it for next releases.
 Can you please confirm what are your requirements ?

**Comment by pLotoniC** [comment]
Thanks for the answer!

I actually need it to convert a JSON or YAML file into AsciiDoc on build time or compile time to get the document out of the API. This feature was available on https://github.com/Swagger2Markup/swagger2markup, which doesn't support OpenAPI 3.*. 

The maven plugin would be great. My requirements are to be able to generate json and yaml file in compile/build time and make an AsciiDoc or/and PDF out of them. I would like to get an OpenAPI Object in compile time to write json/yaml file in a resource folder programmaticly or have an maven plugin to get them direcly.

Regards

**Comment by springdoc** [comment]
Hi, 

 A new maven plugin is available for this functionnality: 
- https://github.com/springdoc/springdoc-openapi-maven-plugin.git
 
Can you please test it, and give us your feedback?

**Comment by pLotoniC** [comment]
Hi,

I've tested it and it is failed with this:

`Failed to execute goal org.springframework.boot:spring-boot-maven-plugin:2.1.8.RELEASE:start (pre-integration-test) on project k2-peak: Spring application did not start before the configured timeout (30000ms)`

Do you have any suggestion for it? Thanks for your efforts!

**Comment by pLotoniC** [comment]
Hi,

I've tested it and it is failed with this:

`Failed to execute goal org.springframework.boot:spring-boot-maven-plugin:2.1.8.RELEASE:start (pre-integration-test) on project "sample-project": Spring application did not start before the configured timeout (30000ms)`

Do you have any suggestion for it? Thanks for your efforts!

**Comment by springdoc** [comment]
Hi, 

 This seems to be an issue related to spring-boot-maven-plugin.
 Can you please add the sample code to reproduce the issue so we can confirm the root cause?

**Comment by developerc4fl** [comment]
Hi
springdoc-openapi-maven-plugin:1.3:generate (default) @ swagger-demo ---
[ERROR] An error has occured
java.net.ConnectException: Connection refused

it expects the server to be running on port 8080. 

when it's running, doc is generated, but when server is killed am getting this connection refused error. 

is it the desired behavior?

**Comment by bnasslahsen** [comment]
yes
