### ISSUE TITLE
Use generated json by springdoc-openapi-maven-plugin when invoke api-docs endpoint

### ISSUE THREAD

**Issue by jarpz** [springdoc/springdoc-openapi#690]
- If I use the maven plugin to generate the openapi.(json|yaml) in integration-test time I expect when invoking api-docs endpoint It will use this file to serve response, instead, It calculates once again the specification file.

```
<plugin>
                <groupId>org.springdoc</groupId>
                <artifactId>springdoc-openapi-maven-plugin</artifactId>
                <version>1.0</version>
                <executions>
                    <execution>
                        <phase>integration-test</phase>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                    </execution>
                </executions>
                <configuration>
                    <apiDocsUrl>http://localhost:8080/api-docs</apiDocsUrl>
                    <outputDir>${project.build.directory}</outputDir>
                </configuration>
            </plugin>
```

Invoking /api-docs after run java -jar .....

I see in logs:
``` 
o.springdoc.api.AbstractOpenApiResource  : Init duration for springdoc-openapi is: 412 ms
``` 
And even if I use some ```OperationCustomizer``` they are invoked.. so 

-  I guess if there is a file openapi.json in some path it should be used to serve the responses

Regards

**Comment by bnasslahsen** [comment]
@jarpz, 

  Please log your request on the repository of springdoc-open-api-maven-plugin:
  - https://github.com/springdoc/springdoc-openapi-maven-plugin/issues
