### ISSUE TITLE
Question: Add PathParams For controller

### ISSUE THREAD

**Issue by xiaoxiangmoe** [springdoc/springdoc-openapi#691]
```java
public class ServerConstant {
    public static final String API = "/my-server/{client:api|iphone|ipad|android|win|mac}";
}
```

```java
@RestController
@RequestMapping(ServerConstant.API)
public class FooController {

    @Operation(summary = "Create foo")
    @RequestMapping(value = "/foo", method = RequestMethod.POST)
    public Foo createFooOperation() {
        return someLogic.createFoo();
    }

    @Operation(summary = "Create bar")
    @RequestMapping(value = "/bar", method = RequestMethod.POST)
    public Bar createBarOperation() {
        return someLogic.createBar();
    }
}
```

We have thousands of operations and all have a  `@PathParameter("client")`. This parameter is used in Controller and only used by a few operations. We are not currently marked in the operation parameters. 

But we hope that when swagger is generated,`client` will be correctly marked as the path parameter and displayed as enum. What should we do?

**Comment by bnasslahsen** [comment]
@xiaoxiangmoe, 

 You can use the different Customizers depending on your needs:

- OpenApiCustomiser: To customize the OpenAPI object
- OperationCustomizer: To customize an operation based on the HandlerMethod

**Comment by xiaoxiangmoe** [comment]
@bnasslahsen 
I temporarily solved it through OperationCustomizer.
But I think this is a feature worth adding.

**Comment by bnasslahsen** [comment]
@xiaoxiangmoe, 

 Yeah, your PR would be welcome !
