### ISSUE TITLE
Exception handler response documentation is not empty when using void return type 

### ISSUE THREAD

**Issue by IvanPavlov1995** [springdoc/springdoc-openapi#692]
I have an ExceptionHandler
```java
@ExceptionHandler
@ApiResponse(responseCode = "500", description = "Internal server error")
public void handleException(Exception e) {
}
```
but it produces incorrect docs (containing content):
```yaml
responses:
  "500":
    description: Internal server error
    content:
      '*/*':
        schema:
          type: array
          items:
            type: string
```
Adding `content=@Content` or `content = @Content(schema = @Schema(hidden = true))` has no effect. However when I remove `responseCode` content doesn't appear and it becomes
```yaml
responses:
  default:
    description: Internal server error
```

**Comment by bnasslahsen** [comment]
@IvanPavlov1995, 

 I invite you to review your code: The following code sample doesn't produce any content.
	`@ApiResponse(responseCode = "500", description = "Internal error", content = @Content)`

Make sure you haven't declared the http 500 code, else where.

If you are reporting a bug, please help to speed up problem diagnosis by providing as much information as possible:
- **Provide with a sample code (HelloController) or Test that reproduces the problem**

More details on the usage of github issues are available here:
- https://github.com/springdoc/springdoc-openapi/blob/master/CONTRIBUTING.adoc
