### ISSUE TITLE
@ParameterObject works not as expected with POST endpoints (@PostMapping)

### ISSUE THREAD

**Issue by svetlana-nikitina** [springdoc/springdoc-openapi#693]
**springdoc-openapi-ui version: 1.3.9**

In my spring web endpoint I have an object which summarise query params 
To make it work properly, I see `@ParameterObject` was introduced in https://github.com/springdoc/springdoc-openapi/pull/505
It works for GET requests (`@GetMapping`) -> all properties of object are parsed as separate query parameters 

```
    @GetMapping("/test")
    public void testGet(@ParameterObject QueryObject queryObject) {
    }
```

```
    @Getter
    @Setter
    public class QueryObject {
        private String queryParam1;
        private String queryParam2;
    }
```
UI:
![image](https://user-images.githubusercontent.com/42933021/83016995-25669200-a023-11ea-8101-80725658def6.png)

json:
```
  "parameters": [
    {
      "name": "queryParam1",
      "in": "query",
      "required": false,
      "schema": {
        "type": "string"
      }
    },
    {
      "name": "queryParam2",
      "in": "query",
      "required": false,
      "schema": {
        "type": "string"
      }
    }
  ]
```

However I don't see this behaviour with POST requests
And object holding query params is parsed as BODY object
Example of my code
```
  @PostMapping("/test")
    public void testPost(@ParameterObject QueryObject queryObject) {
    }
```

UI:
![image](https://user-images.githubusercontent.com/42933021/83017057-47601480-a023-11ea-9770-b34da7864355.png)

json:
```
"requestBody": {
    "content": {
      "application/json": {
        "schema": {
          "type": "object",
          "properties": {
            "queryParam1": {
              "type": "string"
            },
            "queryParam2": {
              "type": "string"
            }
          }
        }
      }
    }
  }
```

**Expected behavior**
Objects in POST endpoints annotated with `@ParameterObject` should behave the same way as for GET and all fields of this object are parsed as query params

**Comment by bnasslahsen** [comment]
@svetlana-nikitina, 

 @ParameterObject is designed for HTTP GET Methods.
 Please have a look at the documentation:
 - https://springdoc.org/faq.html#how-can-i-map-pageable-spring-date-commons-object-to-correct-url-parameter-in-swagger-ui

**Comment by svetlana-nikitina** [comment]
@bnasslahsen  is there any way to map an object holding query params to query params in swagger for POST? this behaviour is supported by spring and controller itself works fine, but apparently not supported by springdoc-openapi

**Comment by bnasslahsen** [comment]
@svetlana-nikitina, 

 We will add the support for @ParameterObject with POST endpoints for the next release.

**Comment by jarpz** [comment]
> @svetlana-nikitina,
> 
> We will add the support for @ParameterObject with POST endpoints for the next release.

Question?, just for post-method? because for put or patch methods are also possible..

Regards

**Comment by bnasslahsen** [comment]
@jarpz, 

 Yes, for other methods you mentionned as well. 
  This is already deployed with v1.4.0.

**Comment by sh4wn** [comment]
How about POST with application/x-www-form-urlencoded conent type?
