### ISSUE TITLE
Servers block resets after customizing using GroupedOpenApi as Bean

### ISSUE THREAD

**Issue by neonomaly** [springdoc/springdoc-openapi#694]
Hi!

Version 1.3.9 webflux+kotlin.

I'am using GroupedOpenAPI as Spring Bean with customizers of OpenAPI. Setting up servers manually in customizers. 

When I get OpenAPI I took original, calculated by SpringDoc servers. This happens, because OpenAPI object has isServersPresent = false and setting up servers in customizers doesn't fix this flag.

Please, fix this bug. Thanks!

**Comment by bnasslahsen** [comment]
@neonomaly, 
  
 Your description is not enough to confirm any bug to fix ...
If you are reporting a bug, please help to speed up problem diagnosis by providing as much information as possible:
- What version of spring-boot you are using?
- What modules and versions of springdoc-openapi are you using?
- What are the actual and the expected result using OpenAPI Description (yml or json)?
- **Provide with a sample code (HelloController) or Test that reproduces the problem**

More details on the usage of github issues are available here:
- https://github.com/springdoc/springdoc-openapi/blob/master/CONTRIBUTING.adoc
