### ISSUE TITLE
Servers OpenAPI block resets after customizing with GroupedOpenApi

### ISSUE THREAD

**Issue by neonomaly** [springdoc/springdoc-openapi#695]
I'am using springdoc's GroupedOpenApi as a bean with defining openApi customizers and setting up custom Servers block. But after that OpenApi builder resets OpenAPI Block to defaults. This happens, because isServersPresent in OpenApiBuilder doesn't change after customizing.  

Environment:
SpringBoot: 2.3.0.RELEASE,
SpringDoc: webFlux-ui:1.3.9; kotlin:1.3.9
Problem  exists in both notations: JSON and YAML.
Sample Project: https://github.com/neonomaly/springdoc-groupedopenapi-bug 

Expected Behavior:
Servers block saves servers defined by me. In example: 
- for sample-v1 group: http://localhost:8080/v1
- for sample-v2 group: http://localhost:8080/v2 

Actual Behavior:
Servers block resets servers to recalculated. In example:
- for sample-v1 group: http://localhost:8080
- for sample-v2 group: http://localhost:8080 (after second Getting)

**Comment by bnasslahsen** [comment]
@neonomaly, 

 This issue is confirmed. With v1.3.9, you have a first workaround, is to disable the cache:

```properties
springdoc.cache.disabled=true
```
 We will add the fix for the next releae with the cache enabled as well.





springdoc.cache.disabled
--



springdoc.cache.disabled
--
