### ISSUE TITLE
Can I use openapi.yaml

### ISSUE THREAD

**Issue by yshinkarev** [springdoc/springdoc-openapi#697]
I can customize OpenAPI from code. Thanks for https://springdoc.org/faq.html#can-i-customize-openapi-object-programmatically.
But can I do same over openapi.yaml like here https://github.com/swagger-api/swagger-petstore/blob/master/src/main/resources/openapi.yaml

**Comment by bnasslahsen** [comment]
@yshinkarev, 

 You can either have access to the Json, or Yaml definition of the customized OpenAPI Bean.
 
For Json:
 - http://localhost:8080/v3/api-docs
 
And for Yaml:
 - http://localhost:8080/v3/api-docs.yaml

**Comment by yshinkarev** [comment]
Seems, you didn't understand me.
Try to clarify.
For example, I want to change info (title, version, description).
1) I can create in code new @Configuration file and define bean with creation OpenAPI object.
2) But I want to do same  without code and by yml file only.
So I create openapi.yaml in resource directory with info.title, info,version, info.description values. And want to achieve the same effect as in 1)
Are you understand me now?

**Comment by bnasslahsen** [comment]
Yeah, your description was not clear.

If you need configuration file, you can have a look at the FAQ, documentation:
- https://springdoc.org/faq.html#can-i-use-spring-property-with-swagger-annotations

And here is the link for code samples:
- https://raw.githubusercontent.com/springdoc/springdoc-openapi/master/springdoc-openapi-webmvc-core/src/test/java/test/org/springdoc/api/app15/SpringDocApp15Test.java
