### ISSUE TITLE
Error in jboss deployment for open_api with springboot project

### ISSUE THREAD

**Issue by manavvidhudi** [springdoc/springdoc-openapi#698]
created springboot project with open api version 1.2.32 which is working perfectly fine in locally and in tomcat. but when i going to deploy in jboss server it is giving error like 
Forwarding to error page from request [/v3/api-docs] due to exception [FAIL_ON_TRAILING_TOKENS]: java.lang.NoSuchFieldError: FAIL_ON_TRAILING_TOKENS

Step to reproduce 
1. create spring boot projcet with POM

<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>2.3.0.M4</version>
		<relativePath /> 
	</parent>

	<groupId>com.pg.example</groupId>
	<artifactId>Demo</artifactId>
	<version>2</version>
	<packaging>war</packaging>

	<properties>
		<java.version>1.8</java.version>
	</properties>
	<repositories>
		<repository>
			<id>project.local</id>
			<name>project</name>
			<url>file:${project.basedir}/lib</url>
		</repository>
		<repository>
			<id>spring-milestones</id>
			<name>Spring Milestones</name>
			<url>https://repo.spring.io/milestone</url>
		</repository>
	</repositories>

	<dependencies>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-data-jpa</artifactId>
		</dependency>

		<dependency>
			<groupId>com.oracle</groupId>
			<artifactId>ojdbc7</artifactId>
			<version>12.1.0.2</version>
		</dependency>

		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-web</artifactId>
		</dependency>

		<dependency>
			<groupId>org.projectlombok</groupId>
			<artifactId>lombok</artifactId>
			<optional>true</optional>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-tomcat</artifactId>
			<scope>provided</scope>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-test</artifactId>
			<scope>test</scope>
			<exclusions>
				<exclusion>
					<groupId>org.junit.vintage</groupId>
					<artifactId>junit-vintage-engine</artifactId>
				</exclusion>
			</exclusions>
		</dependency>
		
		<dependency>
			<groupId>org.springdoc</groupId>
			<artifactId>springdoc-openapi-ui</artifactId>
			<version>1.2.32</version>
			<exclusions>
				<exclusion>
					<groupId>com.fasterxml.jackson.core</groupId>
					<artifactId>jackson-databind</artifactId>
				</exclusion>
				<exclusion>
					<groupId>com.fasterxml.jackson.module</groupId>
					<artifactId>jackson-module-jaxb-annotations</artifactId>
				</exclusion>
			</exclusions>
		</dependency>
		<dependency>
			<groupId>org.webjars</groupId>
			<artifactId>webjars-locator-jboss-vfs</artifactId>
			<version>0.1.0</version>
		</dependency>
		<dependency>
			<groupId>com.h2database</groupId>
			<artifactId>h2</artifactId>
			<scope>test</scope>
		</dependency>

	</dependencies>

	<build>
		<plugins>
			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
			</plugin>
		</plugins>
	</build>

	<pluginRepositories>
		<pluginRepository>
			<id>spring-milestones</id>
			<name>Spring Milestones</name>
			<url>https://repo.spring.io/milestone</url>
		</pluginRepository>
	</pluginRepositories>

</project>

2. creating bean 

  @Bean
    public OpenAPI customOpenAPI(@Value("${application-description}") String appDesciption, @Value("${application-version}") String appVersion) {

    	ArrayList<Tag> listofTags= new ArrayList<Tag>();
    	
    	listofTags.add(new Tag().name("demo1").description("add modify and update description"));
    	listofTags.add(new Tag().name("demo2").description("add modify and update description"));
    	
    	
     return new OpenAPI()
    	  .components(new Components().addSecuritySchemes("basicScheme", new SecurityScheme().type(SecurityScheme.Type.HTTP).scheme("basic")))
    	  .info(new Info()
          .title("DemoApplication API's")
          .version(appVersion)
          .description(appDesciption)
          .termsOfService("http://swagger.io/terms/")
          .license(new License().name("Apache 2.0").url("https://www.apache.org/licenses/LICENSE-2.0.html")))
          .tags(listofTags);

    }

and created controller with get Mapping

	@Tag(name = "Demo")
	@GetMapping("/getData")
	public Iterable<PET> demo()
	{
		return jpaRepo.findAll();
	}

Getting Error like below snapshot:-
![file](https://user-images.githubusercontent.com/14887237/83255832-d1001580-a1ce-11ea-991d-b33b200952f1.png)

**Comment by bnasslahsen** [comment]
@manavvidhudi, 

 Please use the last stable version before reporting any issue.
If you are reporting a bug, please help to speed up problem diagnosis by providing as much information as possible:
 Also, please review your code formatting, to help us to investigate, and make sure we have all the data about your context.

**Comment by manavvidhudi** [comment]
i am using jboss 7.0 version where it is not working.

**Comment by bnasslahsen** [comment]
The same sample is working without any issue on  jboss EAP 7.1, and there are no know issues on Jboss.

We have provided you a minimal sample provided working on different jboss versions. 
- If this one is not working on your jboss installation. You should review your application server configuration.
- If its working, then you should review your application configuration.

If you need more assistance, please provide a minimal reproducible example that will help us speed up your problem diagnosis.
