### ISSUE TITLE
Oauth2 Authentification Header Not Present 

### ISSUE THREAD

**Issue by laurentiu-miu** [springdoc/springdoc-openapi#701]
After a successful login with oauth2, ui doesn't send the access_token in the authentication header when accessing endpoints configured in controllers.

spring boot app 2.2.7.RELEASE
springdoc-openapi-ui 1.3.9
springdoc-openapi-webmvc-core 1.3.9

`@Bean
  public OpenAPI customOpenAPI() {
    OAuthFlow oAuthFlowObject = new OAuthFlow();
    HashMap extensions = new HashMap<>();
    extensions.put("grant_type","client");
    extensions.put("realm_id","realm");
    oAuthFlowObject.setExtensions(extensions);
    oAuthFlowObject.setTokenUrl("...server.../oauth2/access_token");

    OAuthFlows oAuthFlows = new OAuthFlows();
    oAuthFlows.clientCredentials(oAuthFlowObject);

    return new OpenAPI()
        .components(new Components().addSecuritySchemes("bearerAuth", new SecurityScheme()
                .type(Type.OAUTH2)
                .flows(oAuthFlows)
                .in(In.HEADER)
                .bearerFormat("JWT")
                .scheme("bearer")
            ))
        .info(new Info().title("Contact Application API").description(
            "This is a sample Spring Boot RESTful service using springdoc-openapi and OpenAPI 3."));
  }`

When I login with client_id/secret it returns the token with success
<img width="652" alt="1" src="https://user-images.githubusercontent.com/2171550/83290944-2ef12500-a1f0-11ea-9d80-00253bba3d07.png">
<img width="468" alt="2" src="https://user-images.githubusercontent.com/2171550/83291041-5d6f0000-a1f0-11ea-9ca7-77889662b9fb.png">
<img width="1374" alt="3" src="https://user-images.githubusercontent.com/2171550/83291559-36fd9480-a1f1-11ea-979f-2741d9730f2f.png">

**Comment by bnasslahsen** [comment]
@laurentiu-miu, 

 You can have a look at the following example using oauth flows: 
- https://github.com/springdoc/springdoc-openapi-demos/tree/master/sample-springdoc-openapi-oauth2

 Your endpoints should be secured using : @SecurityRequirement annotation.
 If its the case, please add a sample code to help us speed up problem diagnosis by providing as much information as possible.

**Comment by laurentiu-miu** [comment]
10x a lot @bnasslahsen
