### ISSUE TITLE
How to model a common response class in individual service projects

### ISSUE THREAD

**Issue by mattkvm** [springdoc/springdoc-openapi#702]
We have a common class Response class defined in another library and we don't have access to add/modify this class.

for e.g. 
public class RestResponse implements Serializable {
           protected MetadataType metadata;
           protected List<Object> any;
        ......
    
}

This class will be used in multiple services  (multiple projects) to generate the response, 'any' field in the RestResponse class is populated with the individual services business object.

How can i model the response class for each individual service using @Schema.

Thanks in advance.

**Comment by bnasslahsen** [comment]
@mattkvm, 

 Your question is not related to springdoc-openapi but to the usage of swagger @Schema.
 You should better ask it on stackoverflow under swagger tag.

  You can have a look at the tests where you have sample code and expected responses.
 - https://github.com/springdoc/springdoc-openapi/blob/master/springdoc-openapi-webmvc-core/src/test/java/test/org/springdoc/api/app104/SpringDocApp104Test.java
 - https://github.com/springdoc/springdoc-openapi/blob/master/springdoc-openapi-webmvc-core/src/test/resources/results/app104.json

 You might find some other examples on the tests.
