### ISSUE TITLE
[Feature] Pretty print OpenApi spec

### ISSUE THREAD

**Issue by dominic-jones** [springdoc/springdoc-openapi#703]
**Is your feature request related to a problem? Please describe.**
This maven plugin is useful for creating an offline representation of the OpenApi specification. 
It can be useful to check in the generated spec to diff it in pull requests when the api changes.
However, it is not formatted, and is difficult for humans to read as generated.

**Describe the solution you'd like**
I would like a pretty-printed output of the OpenApi specification.

**Describe alternatives you've considered**
This could be behind a configuration to pretty print if desired.

**Comment by bnasslahsen** [comment]
@dominic-jones, 

 This feature will be available with the next release. v1.4.1.
 You can use with the springdoc-openapi-maven plugin, by adding the following command line arguement:

`-Dspring-boot.run.arguments=--springdoc.writer-with-default-pretty-printer=true`
