### ISSUE TITLE
Mark parameters as required until @Nullable annotation is present

### ISSUE THREAD

**Issue by vladimirshefer** [springdoc/springdoc-openapi#704]
### Intro
In my project we do not use `@NotNull` annotations, bit it is implicitly implied until the `@Nullable` annotation is present.

### Problem
I am enforced to mark variables as `@Schema(required=true)`, then code becomes dirty with boilerplate 

### Expected solution
I would like a flag like `springdoc.required.default=true`, which does the following:
1. If the property of `@RequestBody` is not marked as `@Nullable` or `@Schema(required=false)`, then it is required by default
2. If `@RequestParam` is not marked as `@Nullable` or `@Schema(required=false)`, then it is required by default

**Comment by bnasslahsen** [comment]
@vladimirshefer, 

 This will not be handled in springdoc-openapi. It's related to your application context.

 You can achieve your goal in a transversal way using ParameterCustomizer or PropertyCustomizer depending on how deep you want to change properties:

 - ParameterCustomizer: To customize a parameter based on the MethodParameter
 - PropertyCustomizer: To customize a schema property based on the AnnotatedType

 Examples are available on the project tests:
 - https://github.com/springdoc/springdoc-openapi/tree/master/springdoc-openapi-webmvc-core/src/test

**Comment by pmalkani-blk** [comment]
Hi, we are facing similar issue, whichever fields are marked as @NotNull in pojos, we are required to explicitly mark them @Schema(required=true). 
In this type of simple pojo, I want the labelName to be marked as mandatory/required field in yaml/json file.

public class ApiType {

	private Duration duration;

	@NotNull
	private String labelName;
}

**Comment by pmalkani-blk** [comment]
Hi, we are facing similar issue, whichever fields are marked as @NotNull in pojos, we are required to explicitly mark them @Schema(required=true).
In this type of simple pojo, I want the labelName to be marked as mandatory/required field in yaml/json file.

public class ApiType {
private Duration duration;
@NotNull
private String labelName;
}

**Comment by pitumalkani** [comment]
Hi, we are facing similar issue, whichever fields are marked as @NotNull in pojos, we are required to explicitly mark them @Schema(required=true).
In this type of simple pojo, I want the labelName to be marked as mandatory/required field in yaml/json file.
public class ApiType {
private Duration duration;
@NotNull
private String labelName;
}

**Comment by superxiao** [comment]
I answered [here](https://stackoverflow.com/a/79238650/2770518) for a possible workaround using byte-buddy to add `@Nonnull` annotation to all fields that aren’t already annotated with `@Nullable`. This effectively makes springdoc-openapi recognize those fields as required.
