### ISSUE TITLE
[USAGE QUESTION] How to customise swagger-ui.html url?

### ISSUE THREAD

**Issue by nmarquesantos** [springdoc/springdoc-openapi#710]
I'm looking to customise the path for the swagger ui.

I can definitely customise the property on application.properties.

However, this still redirected to an auto-generated URL like **https://${HOSTNAME}/webjars/swagger-ui/index.html?configUrl=/v3/api-docs/swagger-config**

Is there a way to let's say, just have it accessible via https://${HOSTNAME}/swagger-ui.html without any other redirects?

**Comment by bnasslahsen** [comment]
Hi @nmarquesantos, 

 I will ask you first to read the section using girhub issues here:
 - https://github.com/springdoc/springdoc-openapi/blob/master/CONTRIBUTING.adoc

 As your answer is not clear. i will ask you first to add more information about your context.
 - What is your spring-boot version ?
 - What is your springdoc-modules you are using ?
 - What springdoc-properties you are using ?

**Comment by bnasslahsen** [comment]
Closed, as not additional information provided.
