### ISSUE TITLE
Please point me on how to add new collection types (e.g. Vavr / Guava)

### ISSUE THREAD

**Issue by domdorn** [springdoc/springdoc-openapi#712]
I'm trying to add the collection types ( Option, List, Tuple, etc.) from the vavr-library, but can't seem to find where to plug them in (https://www.vavr.io/vavr-docs/). 
I already figured out on how to make the Future<T> type work here https://dominikdorn.com/2020/05/spring-doc-openapi-swagger-vavr-future/ 
but I'm a little lost on how to make the collections types work. 
It would be great if you could point me in the right direction!

This is what I tried so far:
1) I've already tried creating a `io.swagger.v3.core.converter.ModelConverter` but this leads to NPEs when swagger tries to clone the schema. 
2) I also tried `SpringDocUtils.getConfig().replaceWithClass(io.vavr.control.Option.class, java.util.Optional.class); ` but this seems to be unable to handle generics. 
3) I tried to register the VavrModule with the ObjectMapper of SpringDoc/Swagger, but this also doesn't help ( `Json.mapper().registerModule(new VavrModule());` ) 

Thx,
Dominik

**Comment by bnasslahsen** [comment]
@domdorn, 

 Can you please add a minimal reproducible example or the link to your github complete sample, in order to help us speed up diagnosis?

**Comment by domdorn** [comment]
perfect, thank you @bnasslahsen ! While the replaceWithClass didn't had the intended result (e.g. it lost type information and thus all collections became untyped arrays), your code of the ModelConverter works good enough so I could also implement it for the collection types. Will create a blog post with the full code soon and give attribution to you @bnasslahsen !

**Comment by rhushikeshSahaj** [comment]
Hi @domdorn, did you write a blog post for collection types. I am also facing the same problem so it would be a great help for me

**Comment by rhushikeshSahaj** [comment]
hi @domdorn found your gist here https://gist.github.com/domdorn/bddf5ce1348464179fdd4ffc65b70870

thanks, it helped. 

Commenting it here so that others will be able to find it easily

**Comment by domdorn** [comment]
The post is supposed to be this one: 
https://dominikdorn.com/2020/05/spring-doc-openapi-swagger-vavr-future/
but apparently the github-gist plugin for wordpress fails for some reason.. anyway, you've found the right gist :-)
