### ISSUE TITLE
@ParameterObject doesn't work for generic objects 

### ISSUE THREAD

**Issue by adian** [springdoc/springdoc-openapi#716]
**Describe the bug**
```java
@GetMapping
public Object getMessagesAudits(@ParameterObject Message<String, String> message) {
...
}
```

**To Reproduce**

- spring-boot: 2.3.0.RELEASE
- springdoc-openapi-ui

**Expected behavior**
I think it should work like for non-generic objects.

**Screenshots**
![Screenshot 2020-06-07 at 23 41 52](https://user-images.githubusercontent.com/22716160/83980753-78d8ba00-a918-11ea-8fd0-f4642ecab0fe.png)

**Comment by bnasslahsen** [comment]
This is not a bug, but a feature request, which is not a priority.
@ParameterObject, supports simpleTypes and nested Parameter objects and swagger primitive types, 

You can propose a PR, if you feel it useful for the community.
