### ISSUE TITLE
when endpoint method doesn't contain HTTP method (spring treats it as any), is not added to OpenApi

### ISSUE THREAD

**Issue by bartlomiej-kedziora** [springdoc/springdoc-openapi#718]
When spring security endpoints are exposed in swagger-ui and don't have HTTP method specification, springdoc-openapi is skipping it. Example:
```java
package org.springframework.security.oauth2.provider.endpoint;

@FrameworkEndpoint
@SessionAttributes({AuthorizationEndpoint.AUTHORIZATION_REQUEST_ATTR_NAME, AuthorizationEndpoint.ORIGINAL_AUTHORIZATION_REQUEST_ATTR_NAME})
public class AuthorizationEndpoint extends AbstractEndpoint {
...
@RequestMapping(value = "/oauth/authorize")
	public ModelAndView authorize(Map<String, Object> model, @RequestParam Map<String, String> parameters,
			SessionStatus sessionStatus, Principal principal) {...}
...
}
```
_As we know If don't specify any mapping then method will resolve all the http request i.e. you can send GET, POST, HEAD, OPTIONS, PUT, PATCH, DELETE, TRACE request to the specified url and it will be resolved._

It'll be nice to make visible all of them with possibility to exclude by HTTP method

**Comment by bnasslahsen** [comment]
@bartlomiej-kedziora, 

 You should add springdoc-openapi-security (which scans for spring-security-oauth @FrameworkEndpoint ).
```xml
   <dependency>
      <groupId>org.springdoc</groupId>
      <artifactId>springdoc-openapi-security</artifactId>
      <version>latest.version</version>
   </dependency>
```

 If you have any additional controllers to add:
 You add them using: 

```java
 SpringDocUtils.getConfig().addRestControllers(Class<?>... classes)
```

**Comment by bartlomiej-kedziora** [comment]
dependency was added before and other spring security endpoints are exposed in a proper way, but they have annotation specified like @GetMapping etc, but this one I mentioned above has not specified Http method and is not visible in swagger-ui

**Comment by bnasslahsen** [comment]
@bartlomiej-kedziora, 

 You can have a look at the following property, because i see you want display a method which returns:

```properties
springdoc.model-and-view-allowed=true
```

More details here:
- https://springdoc.org/springdoc-properties.html

**Comment by bartlomiej-kedziora** [comment]
Thank you! It works
