### ISSUE TITLE
Question: produces Application/XML <!-- XML example cannot be generated; root element name is undefined --> with not annotated classes

### ISSUE THREAD

**Issue by Sslimon** [springdoc/springdoc-openapi#719]
Hi all

I hope it's fine to ask here a question. 

I have a Spring Boot Rest Api and I want to have the swagger documentation. Mostly the Api produces application/xml. When the return class is annotated with XmlRootElement and the properties have the XmlElement attributes everything is working fine. But if a primitive type or a List is returned, the root element is missing. Is it somehow possible to tell springdoc he should use jaxb to generate all this information/names. So that the xml has the root name and everything which then really gets returned?

Thank you very much and best
Simon

**Comment by bnasslahsen** [comment]
@Sslimon, 

 The springdoc-openapi, generates the OpenAPI description. But is based on swagger-core and swagger-ui libraries.

 This the existing issue in the swagger-ui where you cas add you comment: 
 - https://github.com/swagger-api/swagger-ui/issues/4650
