### ISSUE TITLE
Query parameter with defaultValue specified should not be marked as required

### ISSUE THREAD

**Issue by akiraly** [springdoc/springdoc-openapi#72]
I have an (webflux) endpoint like this:

```java
  @GetMapping(produces = MediaType.TEXT_PLAIN_VALUE)
  public String echo(@RequestParam(name = "text", defaultValue = "Hello, World!") String text) {
    return text;
  }
```

Currently springdoc interprets `text` as a required parameter (probably because the `required` property of the `@RequestParam` annotation defaults to `true`). If I specify `required = false` then the Swagger UI will handle the query parameter as optional.
However this shouldn't be necessary. For spring it is enough to specify the default value. As the javadoc for `defaultValue` says:
```
The default value to use as a fallback when the request parameter is not provided or has an empty value.
Supplying a default value implicitly sets required to false.
```

Springdoc should handle it the same way.

**Comment by springdoc** [comment]
Hi, 

 A fix will be available on v1.1.34 of springdoc-openapi.
