### ISSUE TITLE
two Post method with different name and input merged as one visible with required params from both of them

### ISSUE THREAD

**Issue by bartlomiej-kedziora** [springdoc/springdoc-openapi#720]
I have one endpoint **'/v1/group'** and two methods:
```java
...
@PostMapping
@ResponseStatus(HttpStatus.OK)
void deleteGroupByUser(@RequestParam("user") String user) {...}

@PostMapping(consumes = RemoveRequestDTO.MEDIA_TYPE)
@ResponseStatus(HttpStatus.OK)
void deleteGroupByUserAndType(@Valid @RequestBody RemoveRequestDTO removeRequestDto){...}
```

in swagger-ui I see one POST endpoint **'/v1/group'** with merged parameters from both of them (marked as required). It is not possible to make call with only "user" as request param or "RemoveRequestDTO" as body

It would be nice to have two POST endpoints **'/v1/group'** for separated methods.

**Comment by bnasslahsen** [comment]
This is not possible in OpenAPI.
You can only exppose a single endpoint, for each HTTP Method ...
If you really can't have separate endpoints, you add the expected OpenAPI documentation manually.

**Comment by bartlomiej-kedziora** [comment]
Thank you for answer.
