### ISSUE TITLE
[question] is it possible to hide endpoints by Http method ?

### ISSUE THREAD

**Issue by bartlomiej-kedziora** [springdoc/springdoc-openapi#721]
Is it possible to hide endpoints by the HTTP method globally? I don't need OPTION, HEAD, PATH in swagger-ui for some methods.

**Comment by bnasslahsen** [comment]
@bartlomiej-kedziora, 

You can use the different Customizers depending on your needs.
For example, you can use OpenApiCustomiser and filter/exclude all the operations you want to hide:
- OpenApiCustomiser: To customize the OpenAPI object
