### ISSUE TITLE
oneOf declaration on Scheme annotation ignored when using type Object

### ISSUE THREAD

**Issue by neonomaly** [springdoc/springdoc-openapi#722]
I describe generic property of my data class with Scheme annotation and set up oneOf property with options. But in generated scheme on oneOf block.

Spring Boot Version: 2.3.0.RELEASE
SpringDoc Version: 1.4.0

To reproduce: 
Repository: https://github.com/neonomaly/springdoc-groupedopenapi-bug 
Look at SampleControllerV1.kt and check generated OpenAPI at http://localhost:9999/v3/api-docs

Expected Behavior:
1. Schemas OneDetails and TwoDetails presented in OpenAPI
2. components->schemas->Global->properties->details contains "oneOf" property with list of references to OneDetails and TwoDetails

Actual Behavior:
1. Schemas missed
2. No oneOf property of Global.details property

If I use SpringDoc incorrectly for obtaining described (expected behavior) result, please, tell me the right way. 

Thank you very much.

**Comment by bnasslahsen** [comment]
@neonomaly ,

 This is not an issue on springdoc-openapi. We rely on swagger-core official jars. 
 You are using the @Schema annotation on an Type Generic.
 
 swagger-core considers it as Object, and then its doesn't go further to check for oneOf content.
 If you are using a concrete class, oneOf will not be ignored .

 You can have a look at ModelResolver class for more details. The concerned method is resolveSchemaMembers.  

 You can submit your request to the swagger-core team for this feature/issue to support oneOf annotation on an attribute of type object:

- https://github.com/swagger-api/swagger-core/issues
