### ISSUE TITLE
Maven enforcer error

### ISSUE THREAD

**Issue by redfoos** [springdoc/springdoc-openapi#728]
**Describe the bug**
org.springdoc:springdoc-openapi-ui:1.4.1 maven enforcer error:
Dependency convergence error for io.github.classgraph:classgraph:4.8.44 paths to dependency are:
```
+-my.package:0.0.1
  +-org.springdoc:springdoc-openapi-ui:1.4.1
    +-org.springdoc:springdoc-openapi-webmvc-core:1.4.1
      +-org.springdoc:springdoc-openapi-common:1.4.1
        +-io.github.classgraph:classgraph:4.8.44
and
+-my.package:0.0.1
  +-org.springdoc:springdoc-openapi-ui:1.4.1
    +-org.webjars:webjars-locator-core:0.45
      +-io.github.classgraph:classgraph:4.8.69
```

**To Reproduce**
run maven enforcer plugin

**Comment by bnasslahsen** [comment]
@redfoos, 

 You can test with the latest available snapshot.
 This depency update will be resolved with the next release.

**Comment by ahoehma** [comment]
@bnasslahsen  I tried 1.4.2-SNAPSHOT and still got this warning:

Dependency convergence error for io.github.classgraph:classgraph:4.8.69 paths to dependency are:
+-com.siemens.spice.cc:rest-service:2020.1.0-SNAPSHOT
  +-org.springdoc:springdoc-openapi-ui:1.4.2-SNAPSHOT
    +-org.webjars:webjars-locator-core:0.45
      +-io.github.classgraph:classgraph:4.8.69
and
+-com.siemens.spice.cc:rest-service:2020.1.0-SNAPSHOT
  +-org.springdoc:springdoc-openapi-security:1.4.2-SNAPSHOT
    +-org.springdoc:springdoc-openapi-common:1.4.2-SNAPSHOT
      +-io.swagger.core.v3:swagger-integration:2.1.2
        +-io.github.classgraph:classgraph:4.8.65

**Comment by bnasslahsen** [comment]
@ahoehma, 

 Great, thank you for your test.
 We will correct it in the next commit.
