### ISSUE TITLE
Swagger UI does not show Server Sent Events until end of the stream is reached

### ISSUE THREAD

**Issue by akiraly** [springdoc/springdoc-openapi#73]
I have a webflux endpoint like this:

```java
  @GetMapping(path = "/stream", produces = MediaType.TEXT_EVENT_STREAM_VALUE)
  public Flux<String> stream() {
    return Flux.interval(Duration.ZERO, Duration.ofSeconds(1))
        .map(Object::toString)
        .take(30);
  }
```

If I call this endpoint directly in a browser then it works as expected: a new value is generated and received by the browser every second.
However if I do the same thing through the Swagger UI then I won't see any values until all 30 of them are received by the client.

Ideally Swagger UI should output the already received values when it receives them - instead of waiting until the end of the stream.

**Comment by springdoc** [comment]
Hi, 

 We rely on swagger-ui official webjars. We build our library on top of it.
 You can submit this enhancement on the swagger-ui project instead:

- https://github.com/swagger-api/swagger-ui/issues
