### ISSUE TITLE
Failed to load remote configuration.

### ISSUE THREAD

**Issue by prateek-gupta-wawa** [springdoc/springdoc-openapi#730]
I am using the Open API version 1.4.0 for one of my applications.
And I get the error: Failed to load remote configuration.

I had a look at one of the earlier resolved issues where it was stated to allow swagger end points through security although this particular application does not have any security related configuration as of now.

I have tried the previous versions as well but it does not work.

I have a multi-modular application where the main pom has the property:
<springdoc-openapi.version>1.4.0</springdoc-openapi.version>

The app module which has the Spring Boot loader has the following dependency:
`<dependency>
            <groupId>org.springdoc</groupId>
            <artifactId>springdoc-openapi-ui</artifactId>
            <version>${springdoc-openapi.version}</version>
</dependency>`

The only application configuration I have right now is:
![YAML](https://user-images.githubusercontent.com/63592589/84599690-8995ac80-ae91-11ea-9565-66c49117993c.PNG)

Can someone please let me know if this is a bug or if I am missing something.

**Comment by bnasslahsen** [comment]
Here is the link for some working code demos:
- https://github.com/springdoc/springdoc-openapi-demos
