### ISSUE TITLE
Can't retrieve webjar content with server context path

### ISSUE THREAD

**Issue by aoudiamoncef** [springdoc/springdoc-openapi#735]
**Describe the bug**
- Can't render Swagger UI with server context path.

**To Reproduce**

Spring Boot: 1.5.4
```xml
        <dependency>
            <groupId>org.springdoc</groupId>
            <artifactId>springdoc-openapi-ui</artifactId>
            <version>1.4.1</version>
        </dependency>
```
- Properties:
```
server.context-path=/custom
springdoc.swagger-ui.path=/swagger
springdoc.api-docs.enabled=true
springdoc.api-docs.path=/api-docs
```

**Expected behavior**
- Render SwaggerUI  index.html page.

**Screenshots**
![springdoc](https://user-images.githubusercontent.com/22281426/84825945-82ea6f00-b022-11ea-9b01-3d8fb4be2ce0.png)

**Additional context**
- `/custom/swagger` : ok
- `/custom/api-docs` : ok
- `/custom/api-docs/swagger-config` : ok

> Note
> I haven't this issue with SpringFox 2.9.2

**Comment by bnasslahsen** [comment]
@aoudiamoncef, 

 The behaviour you are describing is not reproducible using a spring-boot 1 application, with the provided configuration.

By default, you need no additional configuration settings.

If your application uses already `@EnableWebMvc`, or you override WebMvcConfigurerAdapter, this might cause the issue you are facing.

This is the link to a working demo using spring-boot-1:
- https://github.com/springdoc/springdoc-openapi-demos/tree/master/springdoc-openapi-spring-boot-1

You can provide a more complete **minimal, reproducible sample**, (for example based on the spring-boot-1 demo) if you feel there is any issue there,
