### ISSUE TITLE
Is is possible to add custom CSS to Swagger UI?

### ISSUE THREAD

**Issue by michaldo** [springdoc/springdoc-openapi#737]
I know that springdoc use static HTML files from swagger-ui webjars

Is there any way to tweak a bit layout, for example inject piece of custom CSS or JavaScript or something like that?

I'm looking how to solve  [[Question] How can you modify page title or header title of the swagger-ui page ](https://github.com/springfox/springfox/issues/2304)

> In a world of microservices i have 3 or 4 Swagger UI opened in my browser. And all of them are titled the same

**Comment by bnasslahsen** [comment]
@michaldo, 

 You have different title/version and all the metadata of your OpenAPI definition that you can define.

 If you need custom CSS/JS, you can just replace the swagger-ui webjars with the content of the relevant swagger-ui release:
- https://github.com/swagger-api/swagger-ui

**Comment by michaldo** [comment]
I can customize metadata 
```java
@OpenAPIDefinition(info = @Info(title = my custom title"))
```
and modify for example

```html
<h2 class="title"><!-- react-text: 58 -->my custom title<!-- /react-text --></h2>
```

I would like to modify other part of page
```html
<head>
    <meta charset="UTF-8">
    <title>Swagger UI</title>
```

I would like to do it without replacing whole webjar. Just add a small hook to replace 
`<title>Swagger UI</title>`

**Comment by Blackbaud-LouisPujol** [comment]
@bnasslahsen would this be something you would be comfortable with someone doing the work and raising a PR for to achieve this functionality or is this something that the springdoc team does not want to support?

**Comment by manniar** [comment]
I had quite similar need - wanted to override just a few of the swagger css properties. I ended up doing it like this:
```java
@RestController
@RequestMapping(path="/swagger-ui")
public class SwaggerController {
    @GetMapping(path="/swagger-ui.css", produces = "text/css")
    public String getCss() {
        String orig = toText(getClass().getResourceAsStream("/META-INF/resources/webjars/swagger-ui/3.47.1/swagger-ui.css"));
        String append = toText(getClass().getResourceAsStream("swagger-ui.css"));
        return orig + append;
    }

    static String toText(InputStream in) {
        return new BufferedReader( new InputStreamReader(in, StandardCharsets.UTF_8))
            .lines().collect(Collectors.joining("\n"));
    }
}

```
( Spring Boot 2.4.5 )

**Comment by visto** [comment]
> I had quite similar need - wanted to override just a few of the swagger css properties. I ended up doing it like this:
> 
> ```java
> @RestController
> @RequestMapping(path="/swagger-ui")
> public class SwaggerController {
>     @GetMapping(path="/swagger-ui.css", produces = "text/css")
>     public String getCss() {
>         String orig = toText(getClass().getResourceAsStream("/META-INF/resources/webjars/swagger-ui/3.47.1/swagger-ui.css"));
>         String append = toText(getClass().getResourceAsStream("swagger-ui.css"));
>         return orig + append;
>     }
> 
>     static String toText(InputStream in) {
>         return new BufferedReader( new InputStreamReader(in, StandardCharsets.UTF_8))
>             .lines().collect(Collectors.joining("\n"));
>     }
> }
> ```
> 
> ( Spring Boot 2.4.5 )

How did you configure your application.properties? If I set springdoc.swagger-ui.enabled=true then the SwaggerController is never called. Instead the default css is loaded.
