### ISSUE TITLE
How do I set up OAuth2.0 Request Headers

### ISSUE THREAD

**Issue by hero-zhanghao** [springdoc/springdoc-openapi#740]
I wanted to put a value, like postman, on the SpringDoc Swagger page, and apply it to all requests.

![1592552949(1)](https://user-images.githubusercontent.com/16066564/85109850-92490280-b244-11ea-9b06-92bde041c0dd.jpg)

![1592552634(1)](https://user-images.githubusercontent.com/16066564/85109910-b0166780-b244-11ea-8274-84dfe33160f2.jpg)

And swagger is not expected to pop up an input popup for user names and passwords.

Thanks for all the answers.

**Comment by gerasimovv88** [comment]
You should set up flows for OAuth 2, which you will use.
I guess, I want to use **Password Flow**

In your configuration:
1) This helps you to authorize by **Password Flow** in SwaggerUI

```
@Bean
public OpenAPI openAPI() {
	return new OpenAPI()
		....
                .components(getComponents())
		.info(new Info())
		.addSecurityItem(new SecurityRequirement().addList("Password Flow"));
}

private Components getComponents() {
		SecurityScheme passwordFlowScheme = new SecurityScheme()
				.type(SecurityScheme.Type.OAUTH2)
				.flows(new OAuthFlows()
						.password(
								new OAuthFlow()
										.tokenUrl("http://localhost:8080/oauth/token")
										.scopes(new Scopes().addString("trust", "trust all"))
						)
				);

		return new Components()
				.securitySchemes(Map.of("Password Flow", passwordFlowScheme));
}
```

2) This is help you to attach Access Token to you requests. This is useful, when you already have an access token and want to attach it only. 

```
@Bean
public OpenAPI openAPI() {
	return new OpenAPI()
		....
                .components(getComponents())
		.info(new Info())
		.addSecurityItem(new SecurityRequirement().addList("Access Token"));
}

private Components getComponents() {
		SecurityScheme authorizationHeaderSchema = new SecurityScheme()
				.name("Authorization")
				.type(SecurityScheme.Type.APIKEY)
				.in(SecurityScheme.In.HEADER);

		return new Components()
				.securitySchemes(Map.of("Access Token", authorizationHeaderSchema));
}
```

You can combine the methods and inject some others.

**Comment by bnasslahsen** [comment]
Additionally, you can have a look on a complete working sample:

- https://github.com/springdoc/springdoc-openapi-demos/tree/master/sample-springdoc-openapi-oauth2

**Comment by hero-zhanghao** [comment]
The second answer is exactly what I want. Thank you very much
