### ISSUE TITLE
Sorting schemas alphabetically in UI

### ISSUE THREAD

**Issue by avapup** [springdoc/springdoc-openapi#741]
Hi, I want to ask, if exists any option how to sort schemas shown in UI in alphabetical order? Thanks.

**Comment by gerasimovv88** [comment]
Hi!
What's about next properties in your yml or properties file:
```
springdoc:
  swagger-ui:
    tags-sorter: alpha
    operations-sorter: alpha
```

**tags-sorter** is about tags sorting (e.g. your controllers)
**operations-sorter** is about methods sorting

Good luck!

**Comment by avapup** [comment]
Yes, I know this properties, but they are sorting only tags and operations below the tag. But schemas are not sorted alphabetically. In older version, where were models instead of schemas, they were sorted alphabetically by default. It would be great to add such feature to allow sort schemas too. But thanks for the answer.

**Comment by shilanand** [comment]
I have asked the same questions on stackoverflow.
https://stackoverflow.com/q/62473023/3493829

Hope we will have these feature in next release

**Comment by bnasslahsen** [comment]
You can have full control of the schemas order using OpenApiCustomiser.
This is a sample code that you can customize using Comparators, depending on the sorting logic you want:

```java
@Bean
public OpenApiCustomiser sortSchemasAlphabetically() {
	return openApi -> {
		Map<String, Schema> schemas = openApi.getComponents().getSchemas();
		openApi.getComponents().setSchemas(new TreeMap<>(schemas));
	};
}

```

If you are interested on the sorting on the swagger-ui, not on the server side, then you can log a feature request on the swagger-ui project instead.

**Comment by dagnelies** [comment]
Perhaps it would be nice to make this sorting the default as well.

```
springdoc:
  swagger-ui:
    tags-sorter: alpha
    operations-sorter: alpha
```

**Comment by tschniewind** [comment]
> ```java
> @Bean
> public OpenApiCustomiser sortSchemasAlphabetically() {
> 	return openApi -> {
> 		Map<String, Schema> schemas = openApi.getComponents().getSchemas();
> 		openApi.getComponents().setSchemas(new TreeMap<>(schemas));
> 	};
> }
> ```

Keep in mind to use GlobalOpenApiCustomizer instead of OpenApiCustomiser if you have multiple api-groups and want to apply sorting to all of them.
