### ISSUE TITLE
How to map a schema to a single Map<String, String> parameter

### ISSUE THREAD

**Issue by Mestru** [springdoc/springdoc-openapi#743]
There doesn't seem to be any relevant documentation regarding this problem. What I'm trying to achieve is mapping a schema to a single parameter in REST method.

**What I want to achieve**
A method which takes `Map<String, String> params` as method parameter but in swagger shows exact model with query params.

**What I tried**
I registered a bean which adds relevant schema information to Spring context:
```
@Bean
public OpenAPI customOpenAPI() {
    return new OpenAPI()
        .components(new Components().addSchemas("MyCustomSchema", new MapSchema()
            .addProperties("propA", new NumberSchema())
            .addProperties("propB", new NumberSchema())
            .addProperties("propC", new StringSchema())
        ));
}
```

I tried to assign it using `@Parameter` annotation which didn't work:
```
@GetMapping
public MyResponse myQuery(
    @RequestParam(required = false)
    @Parameter(name = "params", description = "Parameter with a map", content =
        @Content(schema =
            @Schema(ref = "#/components/schemas/MyCustomSchema")))
    final Map<String, String> params) { return null; }
```

I also tried using `@Parameters` on method level which also didn't work:
```
@Parameters({
    @Parameter(name = "params", description = "Map of parameters", content =
        @Content(schema =
            @Schema(type = "object", ref = "#/components/schemas/MyCustomSchema")))
})
```

One thing that showed something in Swagger is using `@RequestBody` annotation but it shows itself as a request body and what I want are query parameters
I did:
```
@RequestBody(description = "List of query parameters", content = @Content(schema =
    @Schema(type = "object", ref = "#/components/schemas/MyCustomSchema")))
@GetMapping
public MyResponse myQuery(
    @RequestParam(required = false)
    final Map<String, String> params) { return null; }
```
And it showed as a request body which is not what I want but it's close (I want it as a list of query parameters, not a json request body)

**Summary**
Is there a proper way of achieving thing described above? If yes, is there a documentation for this? If no, should this be supported?

**Comment by bnasslahsen** [comment]
@Mestru, 

 In fact Maps are ignored, by default if they are defined as RequestParams:
 - https://springdoc.org/faq.html#what-are-the-ignored-types-in-the-documentation

 You have many way to achieve your expected documentation.
 
-  You can use ParameterCustomizer:

```java
@Component
public class MyParameterCustomizer implements org.springdoc.core.customizers.ParameterCustomizer {

	static {
		SpringDocUtils.getConfig().removeRequestWrapperToIgnore(java.util.Map.class);
	}

	@Override
	public Parameter customize(Parameter parameterModel, MethodParameter methodParameter) {
		if ("params".equals(parameterModel.getName())) {
			Schema customSchema = new MapSchema()
					.addProperties("propA", new NumberSchema())
					.addProperties("propB", new NumberSchema())
					.addProperties("propC", new StringSchema());
			parameterModel.setSchema(customSchema);
		}
		return parameterModel;
	}
}
```

Or if you want you parameters as query params, simply:

```java
@GetMapping("/api")
@Parameter(name = "propA", schema = @Schema(type="number"))
@Parameter(name = "propB", schema = @Schema(type="number"))
@Parameter(name = "propC", schema = @Schema(type="string"))
public String myQuery(@RequestParam(required = false) final Map<String, String> params) {
	return null;
}
```

Or you can use OperationCustomizer, where you have also the full control of the operation parameters.
