### ISSUE TITLE
WebFlux Multipart File Upload not possible with annotations @RouterOperations and @RequestBody. Enpoints defined as 'RouterFunction'

### ISSUE THREAD

**Issue by FrantisekSchneider** [springdoc/springdoc-openapi#746]
![85558121-bb90d680-b628-11ea-8290-e758474b2efa](https://user-images.githubusercontent.com/60005108/85558900-7c16ba00-b629-11ea-87dc-8cdb6b3f3362.png)
For an endpoint using Spring WebFlux to upload a file, the Swagger UI documentation is not generated properly. It doesn't allow to choose a file and send it as a multipart request.

``` operation = Operation(
                    method = "POST",
                    operationId = "uploadExcelfile",
                     requestBody = RequestBody(
                        required = true,
                        description = "Excel file",
                        content = [
                            Content(
                                schema = Schema(
                                    description = "Excel file",
                                    type = "object",
                                    name = "excelfile",
                                ),
                                mediaType = MediaType.MULTIPART_FORM_DATA_VALUE,
                                encoding = [Encoding(
                                    name = "excelfile",
                                    contentType = MediaType.APPLICATION_OCTET_STREAM_VALUE
                                )]
                            )
                        ]
                    )```



```
     "/api/files/smart-matching": {
      "post": {
        "operationId": "uploadExcelfile",
        "requestBody": {
          "content": {
            "multipart/form-data": {
              "encoding": {
                "excelfile": {
                  "contentType": "application/octet-stream"
                }
              },
              "schema": {
                "description": "Excel file",
                "type": "object"
              }
            }
          },
          "description": "Excel file",
          "required": true
        },
```
--- 
* Environment + Language *
Spring Boot : 2.2.4
Kotlin: 1.3.7
org.springdoc:springdoc-openapi-webflux-ui:1.4.1

---
**Possible solution?**
I guess I need the properties support like in issue mentioned in https://stackoverflow.com/questions/14455408/how-to-post-files-in-swagger-openapi
`
 "paramType": "body",
 "dataType": "file",
`

**Comment by bnasslahsen** [comment]
@FrantisekSchneider, 

 This is not directly a springdoc-openapi issue.
 But this is related to missing properties from the swagger-annotations: springdoc-openapi is built on top of swagger-core and swagger-annotations.
 
 This is the link to the existing swagger-core issue:
- https://github.com/swagger-api/swagger-core/issues/3433

 You can log you comments here, for the support, or directly propose a PR on the swagger-core project.


 You can correct this behaviour with springdoc-openapi: For example, you can declare minimal informations on using @RouterOperation.

```java
@RouterOperation(method = RequestMethod.POST,
		operation = @Operation(operationId = "uploadExcelfile",
				requestBody = @RequestBody(required = true, description = "Excel file"),
				responses = @ApiResponse()))
```

And then enhance it using OpenApiCustomiser:
```java
@Bean
OpenApiCustomiser openApiCustomiser() {
	return openApi ->
			openApi.getPaths().values().stream().flatMap(pathItem -> pathItem.readOperations().stream())
					.forEach(operation -> {
						if ("uploadExcelfile".equals(operation.getOperationId())) {
							RequestBody requestBody = operation.getRequestBody();
							requestBody.setContent(new Content().addMediaType(MediaType.APPLICATION_FORM_URLENCODED_VALUE,
									new io.swagger.v3.oas.models.media.MediaType().schema(new ObjectSchema().addProperties("excelfile", new FileSchema()))));
						}
					});
}
```

**Comment by FrantisekSchneider** [comment]
thank you very much -> closed
