### ISSUE TITLE
@RestController @ExceptionHandler not generated in OpenAPI

### ISSUE THREAD

**Issue by wtell400** [springdoc/springdoc-openapi#748]
When creating an `@ExceptionHandler` in a `@RestController`, similar to `@RestControllerAdvice` I expect the OpenAPI documentation to contain the response for this ExceptionHandler. I'm not sure if this is a bug of a missing feature and thus a feature request.

```java
@RestControllerAdvice
public class ExceptionControllerAdvice
{
    // This is generated in OpenAPI documentation
    @ExceptionHandler(CustomException1.class)
    @ResponseStatus(HttpStatus.NOT_FOUND)
    public ErrorMessage handleException1(RuntimeException e)
    {
        return new ErrorMessage(HttpStatus.NOT_FOUND, e.getMessage());
    }
}
```

```java
@RestController
public class ClassExceptionHandlerController
{
    // This is not generated in OpenAPI documentation
    @ExceptionHandler(CustomException2.class)
    @ResponseStatus(HttpStatus.BAD_REQUEST)
    public ErrorMessage handleException(RuntimeException e)
    {
        return new ErrorMessage(HttpStatus.BAD_REQUEST, e.getMessage());
    }

    @GetMapping("/classexceptionhandler/1")
    public void test1() {
        throw new CustomException1();
    }

    @GetMapping("/classexceptionhandler/2")
    public void test2() {
        throw new CustomException2();
    }
}
```

Expected:
- Both 400 (from `@RestController`) and 404 (from `@RestControllerAdvice`) as responses of mappings.

Actual:
- Only 404 (from `@RestControllerAdvice`) as response of mappings.

Using springdoc-openapi 1.4.1. See attached project.
[springdoc-bug-classexceptionhandler.zip](https://github.com/springdoc/springdoc-openapi/files/4826069/springdoc-bug-classexceptionhandler.zip)

**Comment by bnasslahsen** [comment]
@wtell400, 

 The support is now added on master, and you can validate it with the latest SNAPHSOT; 
 It will be available in the next release.
