### ISSUE TITLE
WebFlux Multipart File Upload - not possible to use FilePart

### ISSUE THREAD

**Issue by pugr** [springdoc/springdoc-openapi#75]
For an endpoint using Spring WebFlux to upload a file, the Swagger UI documentation is not generated properly. It doesn't allow to choose a file and send it as a multipart request:

![image](https://user-images.githubusercontent.com/1968107/64151831-84e49800-ce2b-11e9-920d-76e034011138.png)

This is the endpoint that has a `FilePart` parameter for reactive file upload:

```
@Operation(summary = "Parse Resume")
@PostMapping(value = "/parse-resume", produces = {MediaType.APPLICATION_JSON_VALUE}, consumes = { MediaType.MULTIPART_FORM_DATA_VALUE })
  @ApiResponses({
      @ApiResponse(responseCode = "400", description = "Invalid input")
  })
  public Mono<ResumeDTO> parse(
      @RequestPart(name = "resumeFile")
      @Parameter(description = "Resume file to be parsed", content = @Content(mediaType = MediaType.APPLICATION_OCTET_STREAM_VALUE)) FilePart resumeFile) {
...
}
```

The generated apidoc for the endpoint looks as following:

```
"/api/parse-resume":{  
         "post":{  
            "tags":[  
               "Resume"
            ],
            "summary":"Parse Resume",
            "operationId":"parse",
            "requestBody":{  
               "description":"Resume file to be parsed",
               "content":{  
                  "multipart/form-data":{  
                     "schema":{  
                        "$ref":"#/components/schemas/FilePart"
                     }
                  }
               },
               "required":false
            },
...
}
```

**Comment by springdoc** [comment]
Hi, 

 A fix for this issue will be available on v1.1.34 of springdoc-openapi.
 Can you please test it and give us your feedback.

**Comment by pugr** [comment]
Hi, 

I can confirm the issue has been fixed. Thanks!

**Comment by codemasterbish** [comment]
> Hi,
> 
> I can confirm the issue has been fixed. Thanks!

Can you please help me to suggest which springdoc-openapi, I have to add to fix the swagger issue.

common, openapi-ui, openapi-core etc

**Comment by bnasslahsen** [comment]
Hi, 

 If your app, uses webflux, you just need to add the following dependency:

```xml
 <dependency>
      <groupId>org.springdoc</groupId>
      <artifactId>springdoc-openapi-webflux-ui</artifactId>
      <version>1.2.25</version>
   </dependency>
```

**Comment by silentsnooc** [comment]
I have the same issue with the following dependencies 

```xml
<dependency>
    <groupId>org.springdoc</groupId>
    <artifactId>springdoc-openapi-core</artifactId>
    <version>1.1.49</version>
    <exclusions>
        <exclusion>
            <groupId>io.github.classgraph</groupId>
            <artifactId>classgraph</artifactId>
        </exclusion>
    </exclusions>
</dependency>

<dependency>
    <groupId>org.springdoc</groupId>
    <artifactId>springdoc-openapi-ui</artifactId>
    <version>1.1.49</version>
</dependency>

<dependency>
    <groupId>io.github.classgraph</groupId>
    <artifactId>classgraph</artifactId>
    <version>4.8.44</version>
</dependency>
```

using Spring Boot 2.2.2.RELEASE

**Comment by bnasslahsen** [comment]
> I have the same issue with the following dependencies
> 
> ```
> <dependency>
>     <groupId>org.springdoc</groupId>
>     <artifactId>springdoc-openapi-core</artifactId>
>     <version>1.1.49</version>
>     <exclusions>
>         <exclusion>
>             <groupId>io.github.classgraph</groupId>
>             <artifactId>classgraph</artifactId>
>         </exclusion>
>     </exclusions>
> </dependency>
> 
> <dependency>
>     <groupId>org.springdoc</groupId>
>     <artifactId>springdoc-openapi-ui</artifactId>
>     <version>1.1.49</version>
> </dependency>
> 
> <dependency>
>     <groupId>io.github.classgraph</groupId>
>     <artifactId>classgraph</artifactId>
>     <version>4.8.44</version>
> </dependency>
> ```
> 
> using Spring Boot 2.2.2.RELEASE

Your issue is different. The support for @RequestParam for file upload, will be added on v 1.2.29.
