### ISSUE TITLE
SpringDoc behind an SSL terminating load balancer generates incorrect http server url

### ISSUE THREAD

**Issue by maartenh** [springdoc/springdoc-openapi#751]
**Describe the bug**
When a service with SpringDoc is deployed behind a load balancer, in such a way that the service itself is accessed over **http** by the load balancer, but the load balancer only accepts **https** from the outside, the auto-generated server url is incorrectly using **http** as the protocol instead of **https**.

**To Reproduce**
- spring boot v2.3.1
- springdoc-openapi-ui v1.4.2
- deploy the service in a kubernetes cluster
- use an ingress that terminates the https connection and disallows http connections
- access the swagger ui through from the outside using the https connection to the cluster

**Expected behavior**
The automatically generated server url should start with the **https** scheme

**Additional context**
I have a fix prepared locally, which I'd like to contribute as a PR.
Using headers such as Forwarded and X-Forwarded-*, it is possible to determine the correct server url in most cases, and I can contribute some code using that to generate the correct server url in more cases.

**Comment by maartenh** [comment]
I would appreciate some guidance on where best to place the new code.
I developed it as part of the method `calculateServerUrl` in the `org.springdoc.webmvc.OpenApiResource` class, but I see that the `org.springdoc.webflux.OpenApiResource` class has an identical method.

Since they both derive from `org.springdoc.api.AbstractOpenApiResource` that might be the most straightforward place to put the extended `calculateServerUrl` method.

**Comment by bnasslahsen** [comment]
@maartenh, 

 There should be no additionnal settings.
You need to make sure you use the spring properties for that and your proxy is configured to forward the correct headers:
- enable server.forward-headers-strategy=framework in spring-boot application
- and x-forwarded-prefix in ingress. (x-forwarded-proto: https)

You can have a look at the guidance here:
- https://springdoc.org/faq.html#how-can-i-deploy-springdoc-openapi-ui-behind-a-reverse-proxy

**Comment by maartenh** [comment]
@bnasslahsen,

Thank you for the reference to this faq (which I should have been able to find myself).
Using the setting you specify, it works like charm now.
