### ISSUE TITLE
Openapi Server Object url supports reverse proxy

### ISSUE THREAD

**Issue by oursy** [springdoc/springdoc-openapi#752]
There is a webflux-functional endpoint A service. Proxy via Spring Cloud Gateway.
A service is behind the gateway, so use the following solution
  https://springdoc.org/faq.html#how-can-i-deploy-springdoc-openapi-ui-behind-a-reverse-proxy

After setting the `forward-headers-strategy: framework` property
The webflux-functional endpoint request starts at 404.
 Specific information can be viewed spring-projects/spring-framework#25270

**Comment by bnasslahsen** [comment]
@oursy, 

 The settings are for reverse proxies: apache/nginx or others ...
 For spring-cloud-gateway, you don't need to set `server.forward-headers-strategy=framework`. 

 Basically, all what you need:
 - Declare `springdoc-openapi-webflux-ui`, on the spring-cloud-gateway side
 - Declare `springdoc-openapi-webflux-core`, on your back-end services that using spring-webflux (account-service).

You can have access, 
 1)- By just updating, your application.yml on the gateway side:
```yaml
springdoc:
  swagger-ui:
    urls[0]:
      name: account
      url: /account/v3/api-docs/
```
 2)- Or programatically:  This is the sample demo code for the integration with spring-cloud-gateway:
 - https://github.com/springdoc/springdoc-openapi-demos/tree/master/sample-springdoc-openapi-microservices

You can find attached, the working sample as well;
[forward-proxy-demo-v1.zip](https://github.com/springdoc/springdoc-openapi/files/4845193/forward-proxy-demo-v1.zip)

**Comment by oursy** [comment]
@bnasslahsen 

Sorry, I didn’t make it clear.

In the example, `account service` has a `hi` endpoint created by `RouterFunction`
But when `account service` configures `server.forward-headers-strategy=framework` attribute,

The following error will appear:
Access the following interfaces through `Spring Cloud Gateway`
http://localhost:8080/account/hi is 404.
But the interface annotated with RequestMapping is normal
This difference needs to be explained by spring team members.

I think SpringDoc can avoid this problem. Resolve the reverse proxy IP when getting 'serverBaseUrl'.

PR #753  Complete support for reverse proxy resolution
