### ISSUE TITLE
Endpoint which produces different media type on error

### ISSUE THREAD

**Issue by mivr83** [springdoc/springdoc-openapi#760]
**Bug description**
When endpoint with multiple return media types (upon 200/ok is returned `multipart/form-data` and on 400/bad request is returned `application/json`) returns error i get in swagger ui 406 instead of 404.

This is how endpoint looks like:
```java
  @GetMapping(value = "/{id}/file", produces = {MediaType.APPLICATION_JSON_VALUE, MediaType.MULTIPART_FORM_DATA_VALUE})
  @Operation(summary = "Get file", description = "Get file for id")
  @ApiResponse(responseCode = "200", description = "file content")
  @ApiResponse(responseCode = "404", description = "Not found", content = @Content(mediaType = MediaType.APPLICATION_JSON_VALUE, schema = @Schema(implementation = Error.class)))
  public ResponseEntity<Resource> getFile(@Parameter(description = "ID", required = true, example = "0") @PathVariable long Id) {
    MediaType csvType = new MediaType("text", "csv");
    return ResponseEntity.ok()
        .contentType(csvType)
        .header(HttpHeaders.CONTENT_DISPOSITION, "attachment; filename=file")
        .body(new ByteArrayResource(fileService.getFileContent(Id).getBytes()));
  }
```

In swagger ui i get definition for 200/ok with drop-down list where i can chose returned type (i also explicitly set returned type for 200/ok to only multipart/... with same result)

When is selected multipart type in swagger ui and endpoint returns error json, then is returned 406 instead of expected 404. When i set media type to json then it returns 404 as expected.

This is caused by fact that swagger makes curl call with exact media typ `-H  "accept: application/json"` or `-H  "accept: multipart/form-data"`.

**Expected behavior**
I would expect when plugin finds out that multiple media types can be returned by endpoint then curl will make call with  `-H  "accept: multipart/form-data, application/json"`

Note: when i set none type then curl calls with `-H  "accept: */*"` and then it goes all ok but in swagger ui i cant see media type for particular response code

**Comment by bnasslahsen** [comment]
sprindoc-openapi generates the OpenAPI documentation.
- If you are having any issues on that, make sure you describe the actual and the expected result using OpenAPI Description (yml or json).

Your expected behaviour on the swagger-ui, is not handled by springdoc-openapi.
If you feel any need to submit an enhancement or an issue on the ui, you should log it on the swagger-ui project instead.

**Comment by rajdevelopersglobalservices** [comment]
I am getting json response when I hit /v3/api-docs, but when I hit /v3/api-docs.yml getting 406 with not found acceptable representation .
