### ISSUE TITLE
Multiple definitions re-encodes URL

### ISSUE THREAD

**Issue by SledgeHammer01** [springdoc/springdoc-openapi#762]
Version:

```
		<dependency>
			<groupId>org.springdoc</groupId>
			<artifactId>springdoc-openapi-ui</artifactId>
			<version>1.4.2</version>
		</dependency>

```

I have multiple definitions in my app. v1 & v2. They show up correctly in the drop down.

The startup URL is:

/swagger-ui/index.html?configUrl=/v3/api-docs/swagger-config#/

When I switch to v2, the url gets re-encoded and we end up with:

/swagger-ui/index.html?configUrl=%2Fv3%2Fapi-docs%2Fswagger-config&urls.primaryName=v2

The forward slashes are getting re-encoded to %2F. It does work, just a bit ugly :). Is this on your side or swagger-ui?

Thanks.

**Comment by bnasslahsen** [comment]
This is a swagger-ui behaviour.
Its more relevant, to ask on the swagger-ui github project.
