### ISSUE TITLE
Re: new springdoc.swagger-ui.disable-swagger-default-url=true property

### ISSUE THREAD

**Issue by SledgeHammer01** [springdoc/springdoc-openapi#763]
Thank you very much for adding this recently :). I just came across this "bug".

Right now, it does work, but we land on a page that says "No API definition provided.".  I think we would all prefer if you redirect to: /swagger-ui/index.html?configUrl=/v3/api-docs/swagger-config. If I go to: /swagger-ui.html, it redirects to /swagger-ui/index.html?configUrl=/v3/api-docs/swagger-config as I describe already.

**Comment by bnasslahsen** [comment]
This is the actual behaviour.
You can override SwaggerIndexPageTransformer, to have any page you would prefer.

**Comment by SledgeHammer01** [comment]
> This is the actual behaviour.
> You can override SwaggerIndexPageTransformer, to have any page you would prefer.

@bnasslahsen Sorry, just to clarify do you mean expected behavior is to land on a "No API definition provided." page or to redirect to /swagger-ui/index.html?configUrl=/v3/api-docs/swagger-config?

After setting the flag, If I browse to localhost:8080/swagger-ui/index.html, it lands on a "No API definition provided." page right now.

**Comment by bnasslahsen** [comment]
Yes it is the expected behaviour.

**Comment by SledgeHammer01** [comment]
> Yes it is the expected behaviour.

@bnasslahsen Hi, I'm very confused looking at the code lol.

When I debug the code, it is going into SwaggerIndexTransformer, not SwaggerIndexPageTransformer which looks something like:

```
	@Override
	public Resource transform(HttpServletRequest request, Resource resource,
			ResourceTransformerChain transformerChain) throws IOException {
		final AntPathMatcher antPathMatcher = new AntPathMatcher();
		boolean isIndexFound = antPathMatcher.match("**/swagger-ui/**/index.html", resource.getURL().toString());
		if (isIndexFound && !CollectionUtils.isEmpty(swaggerUiOAuthProperties.getConfigParameters()) && swaggerUiConfig.isDisableSwaggerDefaultUrl()) {
			String html = readFullyAsString(resource.getInputStream());
			html = addInitOauth(html);
			html = overwriteSwaggerDefaultUrl(html);
			return new TransformedResource(resource, html.getBytes());
		}
		else if (isIndexFound && !CollectionUtils.isEmpty(swaggerUiOAuthProperties.getConfigParameters())) {
			String html = readFullyAsString(resource.getInputStream());
			html = addInitOauth(html);
			return new TransformedResource(resource, html.getBytes());
		}
		else if (isIndexFound && swaggerUiConfig.isDisableSwaggerDefaultUrl()) {
			String html = readFullyAsString(resource.getInputStream());
			html = overwriteSwaggerDefaultUrl(html);
			return new TransformedResource(resource, html.getBytes());
		}
		else
			return resource;
	}

```

I'm searching through your repo and I can't for the life of me find this code. It appears you completely restructured this code since 1.4.2? So once the new version is released, I can just declare a bean of  SwaggerIndexTransformer indexPageTransformer, extend SwaggerIndexPageTransformer and @override  overwriteSwaggerDefaultUrl?

Thanks again!

**Comment by bnasslahsen** [comment]
SwaggerIndexPageTransformer is available since v1.4.3.
This is the link to the code :
- https://github.com/springdoc/springdoc-openapi/blob/master/springdoc-openapi-ui/src/main/java/org/springdoc/webmvc/ui/SwaggerIndexPageTransformer.java

**Comment by SledgeHammer01** [comment]
> SwaggerIndexPageTransformer is available since v1.4.3.
> This is the link to the code :
> 
> * https://github.com/springdoc/springdoc-openapi/blob/master/springdoc-openapi-ui/src/main/java/org/springdoc/webmvc/ui/SwaggerIndexPageTransformer.java

@bnasslahsen  Hi, I upgraded to 1.4.3 and overrode the bean and did:

```
	@Override
	protected String overwriteSwaggerDefaultUrl(String html) {
		return html.replace(Constants.SWAGGER_UI_DEFAULT_URL, "https://xxx.yyy.com:8080/v3/api-docs");
	}

```

This did load my swagger, but its not quite right. The bar at the top is the explorer bar vs the definition drop down. I tried a few different things in the url replacement. When I go to the correct URL, there is no api explorer bar, it just shows the drop down.

Is there a way to do a full redirect?

**Comment by Grosskopferter** [comment]
Hey, could you please give an example of how to Override the SwaggerIndexPageTransformer?
Do I have to register the newly created class overriding the behaviour in some way?

**Comment by bnasslahsen** [comment]
You register your own Transformer as a spring beans that implements SwaggerIndexTransformer.
The design for overriding is explained here:  https://github.com/springdoc/springdoc-openapi/issues/745
