### ISSUE TITLE
MultipleOpenApiResource not support hateoas OpenApiCustomiser

### ISSUE THREAD

**Issue by xiaoyao9184** [springdoc/springdoc-openapi#764]
When i add `springdoc-openapi-hateoas` dependency. it not work with GroupedOpenApi.

After that, I found that `MultipleOpenApiResource` initialization.
https://github.com/springdoc/springdoc-openapi/blob/86a3168dabe7fdf9b897893608faf39440ce051e/springdoc-openapi-webmvc-core/src/main/java/org/springdoc/webmvc/api/MultipleOpenApiResource.java#L160-L183

`OpenApiCustomiser` come from `GroupedOpenApi`
https://github.com/springdoc/springdoc-openapi/blob/86a3168dabe7fdf9b897893608faf39440ce051e/springdoc-openapi-webmvc-core/src/main/java/org/springdoc/webmvc/api/MultipleOpenApiResource.java#L175

`GroupedOpenApi` come from `SpringdocBeanFactoryConfigurer`
https://github.com/springdoc/springdoc-openapi/blob/86a3168dabe7fdf9b897893608faf39440ce051e/springdoc-openapi-common/src/main/java/org/springdoc/core/SpringdocBeanFactoryConfigurer.java#L60-L79

Builder did not set any OpenApiCustomiser
https://github.com/springdoc/springdoc-openapi/blob/86a3168dabe7fdf9b897893608faf39440ce051e/springdoc-openapi-common/src/main/java/org/springdoc/core/SpringdocBeanFactoryConfigurer.java#L68

So is there a way to enable hateoas support for GroupedOpenApi, mybe better way is to start supporting part of GroupedOpenApi.

**Comment by bnasslahsen** [comment]
@xiaoyao9184, 

The code you are looking at, is for setting groups through configuration properties:
- https://springdoc.org/faq.html#how-can-i-define-groups-using-applicationyml


MultipleOpenApiResource supports OpenApiCustomiser. You just need to define GroupedOpenApi programmatically.

```java
public OpenApiCustomiser serverOpenApiCustomiser1() {
	return openApi -> openApi.info(new Info().title("Group 1 API").version("v1").description("Group 1 API"));
}

@Bean
public GroupedOpenApi group1() {
	return GroupedOpenApi.builder().group("group1")
			.pathsToMatch("/employees/**").addOpenApiCustomiser(serverOpenApiCustomiser1())
			.build();
}


public OpenApiCustomiser serverOpenApiCustomiser2() {
	return openApi -> openApi.info(new Info().title("Group 2 API").version("v2").description("Group 2 API"));
}

@Bean
public GroupedOpenApi group2() {
	return GroupedOpenApi.builder().group("group2")
			.pathsToMatch("/employees/**").addOpenApiCustomiser(serverOpenApiCustomiser2())
			.build();
}
```
