### ISSUE TITLE
How to set description for enum members?

### ISSUE THREAD

**Issue by rainmanhhh** [springdoc/springdoc-openapi#765]
I want to set description for enum members. but this not works:
enum Level {
  @Parameter(description = "90+")
  A,
  @Parameter(description = "80-89")
  B,
  @Parameter(description = "70-79")
  C,
  @Parameter(description = "60-69")
  D,
  @Parameter(description = "60-")
  F
}
What is the right way?

**Comment by bnasslahsen** [comment]
@rainmanhhh, 

This seems like a new feature on swagger: Enum values description. The enum type, does not have on OpenAPI such a field.
You request, should go to the swagger-core project instead:

- https://github.com/swagger-api/swagger-core/issues
