### ISSUE TITLE
No page property for endpoint created by Spring data REST

### ISSUE THREAD

**Issue by adian** [springdoc/springdoc-openapi#767]
Hi!

I'm trying to setup springdoc-openapi in my project. I'm facing an issue when using spring-data-rest.
Used dependencies: 
* spring-boot:2.3.1.RELEASE
* spring-boot-starter-data-rest:2.3.1.RELEASE
* spring-boot-starter-data-mongodb:2.3.1.RELEASE
* springdoc-openapi-ui:1.4.3
* springdoc-openapi-data-rest:1.4.3

My endpoint returns:
```json
{
  "_embedded": {
    "objects": []
  },
  "_links": {
    "self": {
      "href": "http://localhost:8080/api/objects?page=0&size=20"
    },
    "profile": {
      "href": "http://localhost:8080/api/profile/objects"
    }
  },
  "page": {
    "size": 20,
    "totalElements": 0,
    "totalPages": 0,
    "number": 0
  }
}
```

In swagger I have:
```json
{
  "_embedded": {
    "objects": [{....}]
  },
  "_links": {
    "additionalProp1": {
      "href": "string",
      "hreflang": "string",
      "title": "string",
      "type": "string",
      "deprecation": "string",
      "profile": "string",
      "name": "string",
      "templated": true
    },
    "additionalProp2": {
      "href": "string",
      "hreflang": "string",
      "title": "string",
      "type": "string",
      "deprecation": "string",
      "profile": "string",
      "name": "string",
      "templated": true
    },
    "additionalProp3": {
      "href": "string",
      "hreflang": "string",
      "title": "string",
      "type": "string",
      "deprecation": "string",
      "profile": "string",
      "name": "string",
      "templated": true
    }
  }
}
```

Where is `page` property? How can I get it? 
Thank you!

**Comment by bnasslahsen** [comment]
@adian, 

 Can you provide more information about your request:
- Provide with a sample code (HelloController) or Test that reproduces the problem
- What are the actual and the expected result using OpenAPI Description (yml or json)?

**Comment by bnasslahsen** [comment]
This ticket will be closed, and there is no need to reopen a new ticket for the same issue.
You can add your the relevant information for further investigations and we will reopen it.
