### ISSUE TITLE
@Schema issue with generics

### ISSUE THREAD

**Issue by SledgeHammer01** [springdoc/springdoc-openapi#768]
On version 1.4.3.

I'm using @Schema(name="xxx") to rename some models to get rid of the Dto suffix. Mostly works, but I found an issue with something like:

`public class PageDto<T>`

and a return type of:

`PageDto<ItemDto>`

This shows up in the schema as PageDtoItemDto.

I use @Schema(name="Item") on ItemDto and that gets me to PageDtoItem in the schema.

If I use @Schema(name="Page") on PageDto, the schema gets just Page in the schema and I get a confict (assuming I have multiple PageDto<T> types).

In the case of generics, you should apply the @Schema name on each part separately, no? I was expecting PageItem in the schema. Or maybe add some kind of placeholder for T?

**Comment by bnasslahsen** [comment]
@SledgeHammer01, 

 Your question is about swagger annotation usage and not sprindoc-openapi. 
 Please log your request on the swagger github or stackoverflow swagger tag instead.
