### ISSUE TITLE
Hide responses node

### ISSUE THREAD

**Issue by membersound** [springdoc/springdoc-openapi#77]
Usually the developer knows that an endpoint can at least produce HTTP 200 OK, 400 Bad Request and 5xx Server Error.

Therefore I'd like to hide the responses node (or at least any responses beside 200 OK).

But none of the following approaches work:
```
    @GetMapping(value = "/persons")
    @Operation(summary = "GET Persons",
            responses = {})
    public PersonRsp persons(final Person person) {
       return null;
    }

    @GetMapping(value = "/persons2")
    @Operation(summary = "GET Persons",
            responses = @ApiResponse(responseCode = "200"))
    public PersonRsp persons2(final Person person) {
       return null;
    }
```

Both endpoints will show:
```
"responses":{
   "502":{
      "description":"default response",
      "content":{
         "*/*":{
            "schema":{
               "type":"object"
            }
         }
      }
   },
   "400":{
      "description":"default response",
      "content":{
         "*/*":{
            "schema":{
               "type":"object"
            }
         }
      }
   },
   "200":{
      "description":"default response",
      "content":{
         "*/*":{
            "schema":{
               "$ref":"#/components/schemas/PersonRsp"
            }
         },
         "application/json":{
            "schema":{
               "$ref":"#/components/schemas/PersonRsp"
            }
         }
      }
   }
}
```

springdoc-1.1.33 and spring-boot-2.1.7

**Comment by springdoc** [comment]
Hi, 

 Can you please add more details about your request : 
-  What is the actual behaviour ?
- What is the code to reproduce it?
- What is the expected result using OpenAPI Description?

 Thank you in advance.

**Comment by membersound** [comment]
The actual behavior is described above: Use one of the `@GetMapping` examples with empty response `responses = {}`, or with response setting 200 OK only `responses = @ApiResponse(responseCode = "200")`.

Both will produce the json api-doc above (error codes 200, 400 and 502 are shown).

Instead, I'd expect an empty `response = {}` to hide the json `responses` node entirely. And I'd expect the `responses = @ApiResponse(responseCode = "200")` to show only the `200` in json  `responses` node.

**Comment by springdoc** [comment]
If you get on the response not only error code 200. 

- Do you have an error Handling using @ControllerAdvice ?
- Is what  you expecting using only the @ApiResponse available HTTP Codes  (And ignore any additional existing HTTP Codes with @ControllerAdvice ?

**Comment by membersound** [comment]
Oh yes, I did not notice it would be coming from `@ControllerAdvice`.

But you're correct, if I override the `@ApiResponse`, I'd expect springdoc to ignore just _any_ other http code configurations.

**Comment by springdoc** [comment]
As per OpenAPI  3 specification, your API description needs to specify the responses for all API operations. Each operation must have **at least one response** defined, usually a successful response. A response is defined by its HTTP status code and the data returned in the response body and/or headers:

- https://swagger.io/docs/specification/describing-responses/

If you need to hide HTTP Codes from other configurations (@ControllerAdvice), you can use @Hidden annotation on the methods of your ControllerAdvice.

**Comment by membersound** [comment]
Ok thanks for clarifying this. Let's leave this issue closed, as my main question "how to hide responses" is solved then.

But I had to create a follow up issue regarding `@Hidden` on `@ControllerAdvise`.
