### ISSUE TITLE
[Question] Is it possible to disable example data generation?

### ISSUE THREAD

**Issue by dandew** [springdoc/springdoc-openapi#770]
First thanks a lot for `springdoc-openapi-ui`, it works great out of the box!

Because of some recursion in my data model, the example data Swagger generates is massive [1] and doesn't render at all in the browser (the tab that loaded the doc page hangs).

Is it possible to disable this generation when `springdoc-openapi-ui` produces the documentation?

____
[1] I have discovered this by trying an alternate path:
1. Run `generateOpenApiDocs` from `org.springdoc.openapi-gradle-plugin`
1. A valid 240KB `openapi.json` is generated 👍 
1. Run `swagger-codegen generate -l html -I openapi.json`
1. A single page HTML doc is generated: it's > 3MB and is mostly composed of a completely useless example data section.

**Comment by bnasslahsen** [comment]
Hi @dandew, 

 Are you using groups (or GroupedOpenApi Bean) ?

**Comment by dandew** [comment]
Thanks for your reply!

I am not using groups nor any annotations besides the Spring ones (so far). Do you think using one of these annotations could help?

**Comment by bnasslahsen** [comment]
Which springdoc-openapi version, are you using ?


You can try the following property (if not using Oauth): This resolves a bug on swagger-ui where it loads some resources twice if using configurl as query parameter.

```properties
springdoc.swagger-ui.display-query-params-without-oauth2=true
```

Or if using Oauth2: 

```properties
springdoc.swagger-ui.display-query-params	= true
```

Let us know if this improves the performance.

**Comment by dandew** [comment]
I'm using version `1.4.3`.

I gave `springdoc.swagger-ui.display-query-params-without-oauth2` a shot, since I'm not using OAuth2, but to no avail. All I see is a spinning wheel when opening the detail section of the POST request on the concerned REST controller's doc.

**Comment by bnasslahsen** [comment]
I would guess, it might be more related to the performance of the rendering on the client side.

There are some existing requests to improve the performance of the UI, as for example:
- https://github.com/swagger-api/swagger-ui/issues/5779

I am quite sure, if you provide them the relevant information they need, they could help.

**Comment by dandew** [comment]
Thanks a lot, I'm going to keep on eye on the progress on Swagger UI's side as it's pretty clear the issue is on that side of the fence. Again thanks for your quick support 🙇
