### ISSUE TITLE
Support fluent api

### ISSUE THREAD

**Issue by flexguse** [springdoc/springdoc-openapi#772]
In my company when we create code in Java we always use a fluent api, mostly using Project Lombok.

```
@lombok.Data
@lombok.experimental.Accessors(fluent=true)
public class Person{
  
     private String name;

}
```

lombok creates the accessors

```
    public String name()

    public void name(String name)

```

for us.

In our current setup:

- spring-boot 2.3.1 with webmvc and tomcat
- springdoc-openapi-ui 1.4.2

the OpenAPI 3 Description does not contain name at all, I suppose it is looked for the getName() method which does not exist.

Please add the support of recognize getter / setter methods without the prefixes get/set as it is already implemented in the [micronaut-openapi project](https://github.com/micronaut-projects/micronaut-openapi/issues/19).

If the addition of this feature is too much effort, please give me a hint which class in springdoc-openapi needs to be extended.

**Comment by bnasslahsen** [comment]
Hi @flexguse, 

 The recognition of the attributes through getters/setters is done by swagger-core library.
 You can not log your request into the swagger project instead:

- https://github.com/swagger-api/swagger-core
