### ISSUE TITLE
Include/Exclude API Paths based on Regex

### ISSUE THREAD

**Issue by debargharoy** [springdoc/springdoc-openapi#773]
Hi,
It would be great to **include** and/or **exclude** endpoints based on `Regex` patterns, if possible at the Open-API-Definition level. Something as given below
```java
@Bean
public OpenAPI openApiDefinition() {
    return new OpenAPI().info(new Info())
                        // include anything starting with /api
                        .includePaths({"^\/api.*"}) 
                        // exclude anything endpoint with /temp in it's path
                        .excludePaths({".*\/temp*."})
}
```
I am aware of the `GroupedOpenApi` approach but the drawback seems to be the lack of regex support. Even the support for `Regex` in the `GroupedOpenApi`'s `pathsToExclude()`/`pathsToMatch()` would do if the one at Definition level seems irrelevant.
```java
   @Bean
    public GroupedOpenApi hideApis() {
        return GroupedOpenApi.builder().group("v1 APIs")
                .pathsToExclude("/api/v2/**", "/v2/**")
                .build();
    }
```
**Edit:** Just noticed that when using the above approach to exclude paths, the common set of header and parameters that are shared across all the APIs are also omitted.

**Comment by bnasslahsen** [comment]
You can use the following set of properties:

```java
springdoc.paths-to-match=/api/**
springdoc.paths-to-exclude=/api/v1/**
```

 The explanation of springdoc properties is available here:
- https://springdoc.org/springdoc-properties.html

**Comment by debargharoy** [comment]
> 
> 
> You can use the following set of properties:
> 
> ```java
> springdoc.paths-to-match=/api/**
> springdoc.paths-to-exclude=/api/v1/**
> ```
> 
> The explanation of springdoc properties is available here:
> 
>     * https://springdoc.org/springdoc-properties.html

How do we specify a set? Let's say we want to ignore endpoints with v2 and v3, how to do it then?

**Comment by bnasslahsen** [comment]
@debargharoy, 

 For regex support, its already the case:
 Please, have a look at the documentation of AntPathMatcher that is used by Spring, for paths matching on controllers:
 - https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/util/AntPathMatcher.html

 When you declare `GroupedOpenApi`, you attach the `OperationCustomizer`, you want:
 - https://github.com/springdoc/springdoc-openapi/blob/76b9c186b135d64b6766054dfc995a7ce4ee6a91/springdoc-openapi-webmvc-core/src/test/java/test/org/springdoc/api/app68/SpringDocTestApp.java#L56-L63
