### ISSUE TITLE
Spring boot actuator endpoint parameters

### ISSUE THREAD

**Issue by paveljandejsek** [springdoc/springdoc-openapi#775]
Currently when enabling actuator with `springdoc.show.actuator=true` there are some endpoints that use parameters in URL, e.g. `/actuator/metrics/{requiredMetricName}`
Due to way spring boot handles the actuator endpoints (single handler method, no `@PathParam`) there is no possibility to input the requiredMetricName parameter. 

Is there any workaround for this that would somehow enable inputing of this param or somehow edit the url manually?

**Comment by bnasslahsen** [comment]
Hi @paveljandejsek, 

 There is a workaround by defining an OpenApiCustomiser. 

```java
@Bean
public OpenApiCustomiser actuatorOpenApiCustomiser() {
    final Pattern pathPathern = Pattern.compile("\\{(.*?)}");
    return openApi -> openApi.getPaths().entrySet().stream()
            .filter(stringPathItemEntry -> stringPathItemEntry.getKey().startsWith("/actuator/"))
            .forEach(stringPathItemEntry -> {
                String path = stringPathItemEntry.getKey();
                Matcher matcher = pathPathern.matcher(path);
                while (matcher.find()) {
                    String pathParam = matcher.group(1);
                    PathItem pathItem = stringPathItemEntry.getValue();
                    pathItem.readOperations().forEach(operation -> operation.addParametersItem(new PathParameter().name(pathParam)));
                }
            });
}
```

This Bean will be available out of the box with the next release.

**Comment by paveljandejsek** [comment]
Awesome, thanks a lot for super fast reply and nice solution! 🙂
