### ISSUE TITLE
Links support

### ISSUE THREAD

**Issue by AtzDT** [springdoc/springdoc-openapi#779]
I struggled to find any information on how to use the links specification in OpenAPI 3.0 (https://swagger.io/docs/specification/links/) with springdoc-openapi. The only reference I found was in this stackoverflow post: https://stackoverflow.com/questions/61792071/how-to-create-a-link-in-openapi-3-0-with-springdoc

Is this already supported? And if so could you add documentation on how to correctly use this feature?

**Comment by bnasslahsen** [comment]
@AtzDT, 

 Links are part of standard OpenAPI 3 annotations and they are supported, as any of the standard swagger 2 annotation.
 You can have a look at the documentation of these annotations on the swagger documentation instead:
 - https://github.com/swagger-api/swagger-core/wiki/Swagger-2.X---Annotations
