### ISSUE TITLE
Dto properties of type Object missing from schema

### ISSUE THREAD

**Issue by halvorsone** [springdoc/springdoc-openapi#78]
When our Dto contains multiple properties of type Object, only the last Object property gets included in the generated schema.

Our Dto:
```java
public class MyTestDto {
    public Object object1;
    public Object object2;
    public Object object3;
}
```

Our controller method:
```java
@PostMapping("/test")
public MyTestDto test(@RequestBody final MyTestDto test) {
    return test;
}
```

Resulting component schema from /v3/api-docs:
```json
"MyTestDto": {
    "type": "object",
    "properties": {
        "object3": {
            "type": "object"
        }
    }
}
```

We are using:
```
"org.springdoc:springdoc-openapi-ui:1.1.26"
"org.springframework.boot:spring-boot-starter-web:2.1.7.RELEASE"
```

Is there something we are missing? Thanks.

**Comment by springdoc** [comment]
Hi, 

  This is not an issue on springdoc-openapi. We rely on swagger-core official jars.
  You have the following workaround:

```java 
  public class MyTestDto {
		@Schema(name = "object1")
		public Object object1;
		@Schema(name = "object2")
		public Object object2;
		@Schema(name = "object3")
		public Object object3;
	}
```
	
 This behaviour is related to swagger-core-2.0.9 official api. 
 You can have a look at ModelResolver class for more details. The concerned method is resolve.
 This method doesn't handle the case of multiple embeded Object types without schema description.

You can submit your request to the swagger-core team for this feature:
- https://github.com/swagger-api/swagger-core/issues

**Comment by halvorsone** [comment]
Thank you for looking into this so promptly and for providing a workaround.
