### ISSUE TITLE
$ref does not appear on .json file but does appear on .yaml file

### ISSUE THREAD

**Issue by canserkanuren** [springdoc/springdoc-openapi#780]
Hello everyone. 
I have been using swagger-core for a day and I tried to set some `ApiResponse` on my function. 
So I set it up like this :

```
@Operation(
  method = "GET",
  description = "Get all applications by trigram",
  tags = {"applications"},
  responses = {
    @ApiResponse(
      responseCode = "200",
      description = "All applications have been fetched",
      content = @Content(array = @ArraySchema(schema = @Schema(implementation = ApplicationDto.class)))
    ),
    @ApiResponse(responseCode = "204", description = "No application has been found with trigram")
  }
)
```

But when I try to display it with `springdocs`, I do have this error :
![Capture](https://user-images.githubusercontent.com/22659909/87060330-ae6c0e00-c20a-11ea-814c-082661b9fd4d.PNG)

After investigating a little further, I have found this differences between my JSON and YAML swagger.

Here's the JSON structured Swagger :
```
"/infocentre_api/applications": {
  "get": {
    "tags": ["applications"],
    "description": "Get all applications by trigram",
    "operationId": "getApplications",
    "parameters": [
      {
        "name": "trigram",
        "in": "query",
        "description": "Given application trigram in order to perform search",
        "schema": { "type": "string" },
        "example": "ABC"
      }
    ],
    "responses": {
      "200": {
        "description": "All applications have been fetched",
        "content": { "application/json": { "schema": { "type": "array" } } }
      },
      "204": { "description": "No application has been found with trigram" }
    }
  }
},
```
Here's the YAML structured Swagger :
```
  /infocentre_api/applications:
    get:
      tags:
      - applications
      description: Get all applications by trigram
      operationId: getApplications
      parameters:
      - name: trigram
        in: query
        description: Given application trigram in order to perform search
        schema:
          type: string
        example: ABC
      responses:
        "200":
          description: All applications have been fetched
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Application"
        "204":
          description: No application has been found with trigram
```

Here is my `pom.xml` :
```
<dependency>
  <groupId>io.swagger.core.v3</groupId>
  <artifactId>swagger-annotations</artifactId>
  <version>2.1.3</version>
</dependency>
<dependency>
  <groupId>io.swagger.core.v3</groupId>
  <artifactId>swagger-core</artifactId>
  <version>2.1.3</version>
</dependency>
<dependency>
  <groupId>io.swagger.core.v3</groupId>
  <artifactId>swagger-jaxrs2</artifactId>
  <version>2.1.3</version>
  <exclusions>
    <exclusion>
      <groupId>io.github.classgraph</groupId>
      <artifactId>classgraph</artifactId>
    </exclusion>
  </exclusions>
</dependency>
<dependency>
  <groupId>org.springdoc</groupId>
  <artifactId>springdoc-openapi-ui</artifactId>
  <version>1.2.18</version>
</dependency>
```
The difference between theses two are the `$ref` attribute that is not set for the JSON file, but is set for the YAML file..
Am I doing something wrong ? Is it a bug on your end or did I just miss something ?
Thank you for your answers.

PS: I made a issue on swagger-core repo but they sais to create an issue in this repo, even though I don’t believe that the problem comes from springdoc.. Here’s the issue that I created : https://github.com/swagger-api/swagger-core/issues/3622

**Comment by bnasslahsen** [comment]
@canserkanuren, 

- Please note you only need to declare **springdoc-openapi-ui**, all the other dependencies you are useless (already included using springdoc-openapi).

 Can you please test with the latest stable version v1.4.3, and report your feedback?

 If the issue persists, please provide a complete sample code (HelloController) or Test that reproduces the problem. (from your description, the java code of the parameters is missing)

 You can have a look at the guidance, of creating issues on github here:
 - https://github.com/springdoc/springdoc-openapi/blob/master/CONTRIBUTING.adoc

**Comment by canserkanuren** [comment]
Problem resolved, it came from the wrong use of a ObjectMapper, to convert swagger fron a JSON to a Java Object. 
Thank your for your time.
