### ISSUE TITLE
Possibility to disable parse of javax constraints in openapi with annotation on desired classes

### ISSUE THREAD

**Issue by kostya05983** [springdoc/springdoc-openapi#781]
#### Description
We have such Dto
```kotlin
@Schema(name = "ModelDraft", description="bla-bla")
data ModelDraftDto(
    @field:NotNull
    val param: String?,

    @field:NotNull
    val param1: String?
)

data class ModelDto(
    val param: String.
    val param1: String
)
```
And endpoint to update ModelDraftDto without validation
```kotlin
@PostMapping
suspend fun postModel(@RequestBody draft: ModelDraft): ResponseEntity<ModelDraft> {
}
```
But when we transform ModelDraftDto into ModelDto we use javax validation in api, but we do it mannually
with validator.validate().

#### What it is now in openapn
Now our draft models generate in openapi as required properties 'cause of NotNull javax annotation and We want a possibility to disable it. @Schema(required=false) on property doesn't work.
```json
"ModelDraftDto": {
"required": [
"param",
"param1"
],
....
}

```

#### Description
I want to add annotation something like @IgnoreJavaxConstraint.
and when I put it on my model, openapi doesn't parse javax constraints

```kotlin
@IgnoreJavaxConstraint
data ModelDraftDto(
   @field:NotNull
    val param: String?
)
```

#### What is the expected result using OpenAPI Description (yml or json)?
In openApi param isn't added in `required` section
```json
"ModelDraftDto": {
"required": [],
....
}
```

### What we do now to ignore this
```kotlin

    private val draftUnrequired = listOf(
        "ModelDraftDto"
    )

    @Bean
    fun swaggerCustomizer(): OpenApiCustomiser {
        return OpenApiCustomiser { api ->
            api.components.schemas.values.forEach { schema ->
                if (draftUnrequired.contains(schema.name)) {
                    schema.required.removeAll()
                }
            }
        }
    }
```

Also if you don't have much time, I can help with pr if you introduce me in code

**Comment by bnasslahsen** [comment]
@kostya05983, 

 The support of JSR303, is primarly available using swagger-core:
- https://github.com/swagger-api/swagger-core/issues/1522

 You can propose your enhancement on the swagger project instead.
 
 Using springdoc-openapi, you can override this default behaviour using OpenApiCustomiser, as you proposed.
