### ISSUE TITLE
@JsonIgnoreProperties is ignored for incoming request who has a property annotated with @JsonIgnoreProperties

### ISSUE THREAD

**Issue by Jojoooo1** [springdoc/springdoc-openapi#783]
**Describe the bug**
- In a @RestController an incoming request  like this one`public ResponseEntity<ApiSuccess<Network>> create(@Valid @RequestBody RequestNetwork request)` containg a Class named RequestNetwork who contain a property with @JsonIgnoreProperties(values = {name}) is not being ignored in Swagger-ui

**To Reproduce**
- What version of spring-boot you are using? 2.4.0-M1
- What modules and versions of springdoc-openapi are you using? 1.4.2
- What is the actual and the expected result using OpenAPI Description (yml or json)? json

**Expected behavior**
- When using @JsonIgnoreProperties on an incoming request property I would expect the property to be ignored by swagger-ui 

**Screenshots**
![3](https://user-images.githubusercontent.com/17641873/87363960-bef0f100-c548-11ea-93e9-676d8aaf94f4.png)
![1](https://user-images.githubusercontent.com/17641873/87363986-cc0de000-c548-11ea-9e0e-6ee4619e0fdc.png)
![2](https://user-images.githubusercontent.com/17641873/87363990-cdd7a380-c548-11ea-84ba-aeaa73c3e94a.png)

**Comment by bnasslahsen** [comment]
@Jojoooo1, 

 springdoc-openapi is built on top of swagger-core library.
 This is issue is related to swagger core, and there are already existing issues around that:

 - https://github.com/swagger-api/swagger-core/issues/3442
 - https://github.com/swagger-api/swagger-core/issues/2845

 As a workaround, you can add @JsonIgnoreProperties on your Company class level instead (if this is expected for all instances of Company)

 You can add you comment so this issues in swagger github project so they are prioritized, or directly propose a PR.
