### ISSUE TITLE
Context Path issue with Apache2 ReverseProxy

### ISSUE THREAD

**Issue by agokulravikumar** [springdoc/springdoc-openapi#784]
Integrated **Spring Doc v1.4.3** into **Spring Boot v2.2.5.RELEASE** application.

Spring Doc modules used,

1) springdoc-openapi-ui
2) springdoc-openapi-security

It works fine in the local embedded tomcat server. But the problem encountered during production deployment.

There is a Apache2 and Tomcat 9 server running on the production machine. The URL **https://apidev.example.com** is connected with the tomcat url **https://localhost:8443/app-dev/** through reverse proxy.

```
<IfModule mod_ssl.c>
<VirtualHost *:443>
	ServerName apidev.example.com
	ProxyRequests Off
	ProxyPreserveHost On
	<Proxy *>
		Order deny,allow
		Allow from all
	</Proxy>
	SSLProxyEngine on
	SSLProxyVerify none
	SSLProxyCheckPeerCN off
	SSLProxyCheckPeerName off
	SSLProxyCheckPeerExpire off
	ProxyPass / https://localhost:8443/app-dev/ retry=0
	ProxyPassReverse / https://localhost:8443/app-dev/
	SSLCertificateFile /etc/letsencrypt/live/example.com/fullchain.pem
	SSLCertificateKeyFile /etc/letsencrypt/live/example.com/privkey.pem
	Include /etc/letsencrypt/options-ssl-apache.conf
</VirtualHost>
</IfModule>
```

Now, all my APIs inside **app-dev** war file can be accessed by **https://apidev.example.com/users** without any context path.

Similarly the Spring Doc API can be accessed by following URLs,
https://apidev.example.com/api-docs (Working)
https://apidev.example.com/api-docs/swagger-config (Working)
https://apidev.example.com/api-docs.html (Not working)
https://apidev.example.com/api-docs.yaml (Working)

The Swagger UI (**/api-docs.html**) is getting redirected to the URL **https://apidev.example.com/app-dev/swagger-ui/index.html?configUrl=/app-dev/api-docs/swagger-config** along with the context path **/app-dev** and it throws **404 - Not Found** error in Spring Boot

The Swagger-config is below,

`{
"configUrl": "/app-dev/api-docs/swagger-config",
"oauth2RedirectUrl": "https://apidev.example.com/app-dev/swagger-ui/oauth2-redirect.html",
"url": "/app-dev/api-docs",
"validatorUrl": ""
}`

It should ideally be,

`{
"configUrl": "/api-docs/swagger-config",
"oauth2RedirectUrl": "https://apidev.example.com/swagger-ui/oauth2-redirect.html",
"url": "/api-docs",
"validatorUrl": ""
}`

**Suggested Solution:**

Can we add a configuration to ignore the context path and handling the same in buildConfigUrl method in  AbstractSwaggerWelcome ?

Anyother solutions are welcome

**Comment by bnasslahsen** [comment]
You are not setting X-Forwarded-Prefix, and on your spring-boot application, you have to make sure you have got: `enable server.forward-headers-strategy=framework`, or any equivalent depending on spring-boot version.

Please have a look at the F.A.Q, before creating any issues: It's all explained there.
- https://springdoc.org/faq.html#how-can-i-deploy-springdoc-openapi-ui-behind-a-reverse-proxy

And you can have a look at many older issues, before creating new one:
- https://github.com/springdoc/springdoc-openapi/issues/751#issuecomment-650734224
