### ISSUE TITLE
WebFlux functional endpoints

### ISSUE THREAD

**Issue by obv-mikhail** [springdoc/springdoc-openapi#785]
Question about functional endpoints, are these now supported?

The README states `spring-webflux with Functional Endpoints, will be available in the future release`, but yet there already exists a usage example here - https://github.com/springdoc/springdoc-openapi-demos/tree/master/springdoc-openapi-spring-boot-2-webflux-functional..

Thanks!

**Comment by bnasslahsen** [comment]
Yes they are supported.
That Readme is now updated.

Further documentation is available here:
 - https://springdoc.org/
