### ISSUE TITLE
Support for customizability of api-docs.yaml?

### ISSUE THREAD

**Issue by aubrey-y** [springdoc/springdoc-openapi#788]
**Is your feature request related to a problem? Please describe.**
- A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
I'm always frustrated when I have to edit api-docs.yaml by hand to make it a valid OAS

- What is the actual result using OpenAPI Description (yml or json)?

```yaml
openapi: 3.0.1
info:
  title: OpenAPI definition
  version: v0
servers:
- url: http://localhost:8080
  description: Generated server url
paths:
  /api/v1/repeat:
    get:
      tags:
      - repeat-controller
      operationId: repeat
      parameters:
      - name: text
        in: query
        required: true
        schema:
          type: string
      - name: times
        in: query
        required: true
        schema:
          type: integer
          format: int32
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: string
components: {}
```

**Describe the solution you'd like**
- A clear and concise description of what you want to happen.

A way to arrive at something close to:

```yaml
swagger: '3.0.1'
info:
  title: Cloud Endpoints + Cloud Run
  description: Sample API on Cloud Endpoints with a Cloud Run backend
  version: 1.0.0
host: e************ka-ue.a.run.app
schemes:
  - https
produces:
  - application/json
x-google-backend:
  address: https://*******************a-ue.a.run.app/
  protocol: h2
paths:
  /api/vi/repeat:
    get:
      summary: Repeat text
      operationId: repeat
      parameters:
        - name: text
          in: query
          required: true
          type: string
        - name: times
          in: query
          required: true
          type: integer
      responses:
        '200':
          description: A successful response
          schema:
            type: string
```

- What is the expected result using OpenAPI Description (yml or json)?

re: above

**Describe alternatives you've considered**
- A clear and concise description of any alternative solutions or features you've considered.

I don't really have many other alternatives but suggestions are welcome

**Additional context**
- Add any other context or screenshots about the feature request here.

I'm not sure whether additional configuration of the generated OAS already exists, so if it does please point me in the right direction.

**Comment by bnasslahsen** [comment]
@aubrey-y, 

 Not sure why you expect a custom api-docs.yaml with the following header: swagger: '3.0.1'?
 
  For customizability of the OpenAPI Bean, you can have a look at the [F.A.Q](https://springdoc.org/faq.html#how-can-i-customise-the-openapi-object-):

**Comment by aubrey-y** [comment]
I don't expect anything necessarily, just the more high level parts of it and less about minute details is what I was curious about. My project requires some of those fields like `x-google-backend` which wasn't generated when I visited the swagger url and I was looking for any kind of configurability so those fields could be generated with everything else, if that makes sense @bnasslahsen 

I will have a look at [your maven plugin](https://github.com/springdoc/springdoc-openapi-maven-plugin) though, seems like the right path.
