### ISSUE TITLE
All PATCH requests of Spring Data REST could be described in generated specification

### ISSUE THREAD

**Issue by kkonrad** [springdoc/springdoc-openapi#789]
**Is your feature request related to a problem? Please describe.**
Spring Data REST supports various kinds of `PATCH` requests. [From documentation](https://docs.spring.io/spring-data/rest/docs/3.3.1.RELEASE/reference/html/#reference):

> The PATCH method supports the following media types:
> 
> * application/hal+json
> * application/json
> * application/patch+json
> * application/merge-patch+json

And they differ in what is structure of the body.

Currently springdoc-openapi doesn't generate documentation for all supported media types. It covers only `application/json`.

**Describe the solution you'd like**

It would be great if SpringDoc would handle also other media types, so that they are described in generated OpenAPI specification.
Of course, also it would be great if this would also work in Swagger.

**Comment by bnasslahsen** [comment]
@kkonrad, 

 springdoc scans for the existing spring REST annotations, on the Rest controllers that describe the mediaTypes.  

 For example, prodcues / consumes on @RequestMapping level on spring-data-rest code.

 If the mediaType description is not present on the conroller level, springdoc will not have access to the exact mediaType. 

 At this moment, you can complete the mediaType using `OpenApiCustomiser` Bean, to add the necessary mediatypes.

**Comment by kkonrad** [comment]
Thx @bnasslahsen for the explanation. I just wonder now, does it mean that in perfect situation it should be addressed in Spring Data REST?
