### ISSUE TITLE
@JsonUnwrapped is ignored

### ISSUE THREAD

**Issue by chadselph** [springdoc/springdoc-openapi#793]
**Describe the bug**
When including `@JsonUnwrapped` from Jackson on a method, the fields don't show up in the api docs.

swagger-core supports this feature: https://github.com/swagger-api/swagger-core/issues/1682

**To Reproduce**
- What version of spring-boot you are using? *2.3.1*
- What modules and versions of springdoc-openapi are you using? *1.4.3*
- What is the actual and the expected result using OpenAPI Description (yml or json)?

Expected:
```yaml
openapi: 3.0.1
info:
  title: OpenAPI definition
  version: v0
servers:
- url: "http://localhost:8007"
  description: Generated server url
paths:
  /api:
    get:
      tags:
      - controller
      operationId: get
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/Response"
components:
  schemas:
    Response:
      required: page
      type: object
      properties:
        foo:
          type: integer
          format: int32
        page:
            type: string
```

Actual:

```yaml
openapi: 3.0.1
info:
  title: OpenAPI definition
  version: v0
servers:
- url: "http://localhost:8007"
  description: Generated server url
paths:
  /api:
    get:
      tags:
      - controller
      operationId: get
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/Response"
components:
  schemas:
    Response:
      type: object
      properties:
        foo:
          type: integer
          format: int32
        page:
          type: string
```

sample: https://github.com/chadselph/spring-boot-swagger-json-unwrapped

**Comment by bnasslahsen** [comment]
@chadselph, 

 springdoc-openapi relies on swagger-core library, and doesn't reference jackson JsonUnwrapped  directly, which is provided by the swagger-core project.

 This looks like an enhancement on swagger-core.
 Note that if you define your type on classes instead, JsonUnwrapped is working without any issue:

```java
public class Common {

  @Schema(required = true)
  @JsonProperty
  String page;

}
```
