### ISSUE TITLE
How to make the generated API use re-usable enums?

### ISSUE THREAD

**Issue by TumbleMagnet** [springdoc/springdoc-openapi#794]
We use springdoc-openapi-ui 1.3.9 to generate an API definition from a spring-boot application (2.2.6) and some of the schema elements use the same enum classes in Java (for example one of these enums is called Language).

In the generated API definition (yaml), the enum values are "in-lined" in every element. For example:

    ContactDetails:
      type: object
      properties:
        language:
          type: string
          enum:
          - EN
          - FR
          - NL

The specification is correct but it would be better for us if it used "re-usable enums" like documented on this page: https://swagger.io/docs/specification/data-models/enums/

Here is the result we would like:

    ContactDetails:
      type: object
      properties:
        language:
          type: string
            $ref: '#/components/schemas/Language'

    Language:
      type: string
      enum:
          - EN
          - FR
          - NL

The issue with the first specification (with in-lined enums) is that when we generate Java code from it, a different enum class is generated for every use. It is then cumbersome to write code which has to compare/copy values from different elements which use different enum classes.

**Comment by bnasslahsen** [comment]
@TumbleMagnet, 

 Its already answered here: https://github.com/springdoc/springdoc-openapi/issues/232

**Comment by TumbleMagnet** [comment]
Thank you!
