### ISSUE TITLE
Springdocs generated api-docs.yaml doesn't respect null or empty servers customOpenApi configuration

### ISSUE THREAD

**Issue by aubrey-y** [springdoc/springdoc-openapi#796]
**Describe the bug**
- If you are reporting a bug, please help to speed up problem diagnosis by providing as much information as possible:
- A clear and concise description of what the bug is: the title of an issue is not enough

Springdocs currently supports customization of its api-docs.yaml through a bean in the SBA as shown here

https://github.com/springdoc/springdoc-openapi/blob/5842104a4d4d4d68d2744eaa779afb29285b5f58/springdoc-openapi-webflux-core/src/test/java/test/org/springdoc/api/app39/SpringDocTestApp.java#L40-L45

Everything works as expected, except when I try to delete certain fields in the yaml definition.

My code looks like this

```java
    @Bean
    public OpenAPI customOpenApi() {
        return new OpenAPI()
                .info(new Info()
                        .title("Cloud Endpoints + Cloud Run")
                        .description("Sample API on Cloud Endpoints with a Cloud Run backend")
                        .version("1.0.0"))
                .servers(null)
                .extensions(Map.of(
                        "host", "<YOUR_HOST_HERE>-ue.a.run.app",
                        "schemes", Collections.singletonList("https"),
                        "produces", Collections.singletonList("application/json"),
                        "x-google-backend", Map.of(
                                "address", "https://<YOUR_APP_URI_HERE>-ue.a.run.app/",
                                "protocol", "h2"
                        )));
    }
```

which you can find here https://github.com/aubrey-y/java-docs-samples/blob/run-endpoints/run/endpoints-v2-backend/src/main/java/com/example/endpoints/EndpointsApplication.java

**To Reproduce**
- What version of spring-boot you are using?
- What modules and versions of springdoc-openapi are you using?
- What is the actual and the expected result using OpenAPI Description (yml or json)?
- Provide with a sample code (HelloController) or Test that reproduces the problem

```xml
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot</artifactId>
            <version>2.3.1.RELEASE</version>
        </dependency>
        <dependency>
            <groupId>org.springdoc</groupId>
            <artifactId>springdoc-openapi-ui</artifactId>
            <version>1.4.3</version>
        </dependency>
```

**Actual behavior**

```yaml
openapi: 3.0.1
info:
  title: Cloud Endpoints + Cloud Run
  description: Sample API on Cloud Endpoints with a Cloud Run backend
  version: 1.0.0
servers:
- url: http://localhost:8080
  description: Generated server url
paths:
  /api/v1/repeat:
    get:
      tags:
      - repeat-controller
      operationId: repeat
      parameters:
      - name: text
        in: query
        required: true
        schema:
          type: string
      - name: times
        in: query
        required: true
        schema:
          type: integer
          format: int32
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: string
components: {}
x-google-backend:
  protocol: h2
  address: https://<YOUR_APP_URI_HERE>-ue.a.run.app/
produces:
- application/json
host: <YOUR_HOST_HERE>-ue.a.run.app
schemes:
- https
```

code was linked above, just check out the branch `run-endpoints`, `cd run/endpoints-v2-backend`, `mvn:spring-boot:run`, and visit [http://localhost:8080/v3/api-docs.yaml](http://localhost:8080/v3/api-docs.yaml).

**Expected behavior**
- A clear and concise description of what you expected to happen.
- What is the expected result using OpenAPI Description (yml or json)?

```yaml
openapi: 3.0.1
info:
  title: Cloud Endpoints + Cloud Run
  description: Sample API on Cloud Endpoints with a Cloud Run backend
  version: 1.0.0
# No servers field
paths:
  /api/v1/repeat:
    get:
      tags:
      - repeat-controller
      operationId: repeat
      parameters:
      - name: text
        in: query
        required: true
        schema:
          type: string
      - name: times
        in: query
        required: true
        schema:
          type: integer
          format: int32
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: string
components: {}
x-google-backend:
  protocol: h2
  address: https://<YOUR_APP_URI_HERE>-ue.a.run.app/
produces:
- application/json
host: <YOUR_HOST_HERE>-ue.a.run.app
schemes:
- https
```

**Screenshots**

**Additional context**

It's possible, since I haven't looked at any of the underlying code, that it's someone else's fault, like `swagger-core`, but I wanted to check here first, since clearly springdocs is doing some interpolation of the customization bean.

**Comment by debargharoy** [comment]
It's not a problem with Springdoc, but with Swagger in general. Swagger 3 has the server auto-generated, but back in Swagger 2, it was mandatory to provide a not-null server. 
Additionally, having the server variable is important as it specifies, where to look for the APIs.
