### ISSUE TITLE
Problem returning array of byte and representing form-data

### ISSUE THREAD

**Issue by debargharoy** [springdoc/springdoc-openapi#797]
I have the following piece of code,
```java
@PostMapping(value = "/create/{userId}", consumes = MediaType.MULTIPART_FORM_DATA_VALUE)
public ResponseEntity<Object> saveFile(
        @Parameter(description = "ID of the user") @PathVariable(value = "userId") final String userId,
        @Parameter(description = "Avatar of the user", content = @Content(mediaType = MediaType.APPLICATION_OCTET_STREAM_VALUE)) @RequestParam(value = "avatar", required = true) final MultipartFile file
) {
    ...
}

@GetMapping(value = "/get", produces = MediaType.IMAGE_PNG_VALUE)
@ApiResponse(responseCode = "200", description = "OK", content = {@Content(array = @ArraySchema(schema = @Schema(implementation = Byte.class)))})
public ResponseEntity<byte[]> getFile() {
    ...
}
```
And below are the expected and the actual result. 
<img width="451" alt="temp" src="https://user-images.githubusercontent.com/30570555/88274274-0f124500-ccf9-11ea-9111-b55a01990859.png">

How do I achieve the expected result?

**Comment by debargharoy** [comment]
The Get method was solved. by changing as below
```java
{@Content(array = @ArraySchema(schema = @Schema(implementation = Byte.class)))}
// change to 
{@Content(schema = @Schema(implementation = Byte.class))}

@bnasslahsen can you please help with the post issue?

**Comment by bnasslahsen** [comment]
@debargharoy, 

 For file format, the not type byte on the spec.    You should send `type: string, format: binary`.
  - https://swagger.io/docs/specification/describing-request-body/file-upload/

So, your requestBody for the post methods is correct.
 
 To describe the return of  type array of byte on your POST method, you can add the following description:

  `@ApiResponse(content = @Content(schema = @Schema(type = "string", format = "binary")))`

**Comment by debargharoy** [comment]
@bnasslahsen thanks for the update on the get method. 

How would you suggest changing the post's parameter so that the `avatar` instead of showing the type as `string($binary)` shows as `file` in the UI as shown in the expected image in the actual question?

**Comment by bnasslahsen** [comment]
it's already the case, you just need to click on the try out button;

**Comment by debargharoy** [comment]
yes, but is it possible to show **file** instead of **string($binary)** is what I'm asking

**Comment by bnasslahsen** [comment]
No, this is the **swagger-ui** default label.

**Comment by debargharoy** [comment]
@bnasslahsen the parameter for `avatar` in the POST should be a **required** field. But it allows sending empty values. 

![image](https://user-images.githubusercontent.com/30570555/89531428-d81a5400-d80d-11ea-8502-3022c24b5add.png)

I tried changing the code to the one below but was no help.
```java
@Parameter(description = "Avatar of the user", required = true, content = @Content(mediaType = MediaType.APPLICATION_OCTET_STREAM_VALUE)) @RequestParam(value = "avatar", required = true) final MultipartFile file
```
