### ISSUE TITLE
Exclude packages or paths globally programatically 

### ISSUE THREAD

**Issue by Huo12345** [springdoc/springdoc-openapi#803]
**Is your feature request related to a problem? Please describe.**
I'm currently writing a custom starter library to wrap springdoc-openapi and adapt it to our needs. One of the requirements is to exclude a list of paths and packages from the generated documentation by default, which can be extended by a list provided in the properties.
According to the [Migration Guide for Springfox](https://springdoc.org/migrating-from-springfox.html), `packagesToScan` and `pathsToMatch` are configured in the application properties. This [issue]( https://github.com/springdoc/springdoc-openapi/issues/404) states that the properties `packagesToExclude` and `pathsToExclude` are supported in the application properties from v1.2.31 onward. But I couldn't find a way to set them programmatically as required to implement my requirements properly.

**Describe the solution you'd like**
It would be useful to have a way to globally configure the four properties `packagesToScan`, `pathsToMatch`, `packagesToExclude` and `pathsToExclude` programmatically like it is possible in `GroupedOpenApi`.

**Comment by bnasslahsen** [comment]
@Huo12345, 

 The usage for groups is different, as we have many beans with prototype scope. 

 If you are not using groups, you can use `SpringDocConfigProperties` directly, which relies on spring @ConfigurationProperties: So you can use spring org.springframework.core.env.Environment to set this properties programmatically;

 Or simply, set them as System properties:

```java
static {
      System.setProperty("springdoc.pathsToExclude", "/api/**, /test/**");
}
```
