### ISSUE TITLE
Setting `springdoc.swagger-ui.path` results in redirect

### ISSUE THREAD

**Issue by ElvenSpellmaker** [springdoc/springdoc-openapi#808]
**Describe the bug**
Hi there, we're setting `springdoc.swagger-ui.path` to `swagger/index.html` and when you hit that endpoint it redirects to `.../api/swagger/swagger-ui/index.html?configUrl=/api/v3/api-docs/swagger-config`.

We don't want the `swagger-ui` portion in the URL, and can't find any option that lets us override this.

**To Reproduce**
  1. Set the above variable
  2. Navigate to the URL `https://foo.bar.com/api/swagger/index.html`

**Expected behavior**
  1. Navigate to page with the variable set
  2. Either a redirect back to the same page, i.e. `.../api/swagger/index.html?configUrl=/api/v3/api-docs/swagger-config`, or no redirect at all (preferable).

**Additional context**
$ curl https://foo.bar.com/api/swagger/index.html -I
...
Location: https://foo.bar.com/api/swagger/swagger-ui/index.html?configUrl=/api/v3/api-docs/swagger-config

(This is not a question about `X-Forwarded-Prefix` I already have that set up fine.)

As a side point, other implementations of this (such as .NET) embed the config options into the UI page, which avoids any need for any redirect as the config is already there and doesn't need to be added to a URL.
Java:
![image](https://user-images.githubusercontent.com/2286713/88829540-a2012280-d1c4-11ea-8580-4fd5ea7bcad2.png)

.NET:
![image](https://user-images.githubusercontent.com/2286713/88829512-9a417e00-d1c4-11ea-83f8-951f6478a025.png)

**Comment by bnasslahsen** [comment]
@ElvenSpellmaker, 

 This is not a bug. But the expected url of swagger-ui url
 It points to the location of the static resources on swagger-ui webjars.
