### ISSUE TITLE
Incorrect results when using multiple media types with @JsonView

### ISSUE THREAD

**Issue by DRF13** [springdoc/springdoc-openapi#810]
**Describe the bug**
We are using json views to represent versions within our application and media types to 'select' which version is being called (implemented in SpringBoot).  However, we've been unable to generate the OpenApi docs as expected as our defined examples are only available for the V1 version of the API and you just get a 'generic' example for V2.  Also the V2 example is not taking into account the view.  If we remove the examples we have seen this working as expected that as we pick each media type the example updates correctly based on the JsonView.

**To Reproduce**
`
    @RestController
    @RequestMapping("/foo")
    public class FooController {

      @Operation(summary = "Gets a Baz.", description = "Gets a Baz.")
      @GetMapping(value = "/{eventId}", produces = {"application/vnd.bar.v1+json" })
      @JsonView(Views.V1.class)
      @ApiResponse(
          responseCode = "200",
          description = "Operation was successful",
          content = {
              @Content(schema = @Schema(implementation = Baz.class), examples = {
                  @ExampleObject(name = "Example1", ref = "Example1"),
                  @ExampleObject(name = "Example2", ref = "Example2"),
                  @ExampleObject(name = "Example3", ref = "Example3"),
              })
          }
      )
      public Baz process1(@PathVariable final Long bazId) {
        Baz baz = new Baz(bazId);
        return baz;
      }

      @GetMapping(value = "/{eventId}", produces = {"application/vnd.bar.v2+json" })
      @JsonView(Views.V2.class)
      @ApiResponse(
          responseCode = "200",
          description = "Operation was successful",
          content = {
              @Content(schema = @Schema(implementation = Baz.class), examples = {
                  @ExampleObject(name = "Example1", ref = "Example1"),
                  @ExampleObject(name = "Example2", ref = "Example2"),
                  @ExampleObject(name = "Example3", ref = "Example3"),
              })
          }
      )
      public Baz process2(@PathVariable final Long bazId) {
          Baz baz = new Baz(bazId);
          return baz;
      }
    }`

**Expected behavior**
We are expecting to have a media drop down containing two types (this works) with an example drop down containing three examples (this only works for the v1 media type) and the examples to correctly represent the view as detailed by the JsonView annotation.

**Comment by bnasslahsen** [comment]
This issue does not respect the contribution rules and will be deleted:
- https://github.com/springdoc/springdoc-openapi/blob/master/CONTRIBUTING.adoc
