### ISSUE TITLE
how can i generate pdf/html swagger doc by `/v3/api-doc` path

### ISSUE THREAD

**Issue by dragontree101** [springdoc/springdoc-openapi#811]
visit `springdoc-openapi`'s `/v3/api-doc` request path can get openapi doc (json format)

how can i convert this json format doc to pdf or html format? 

when i use openapi2 use `Swagger2Markup`, but this plugin not support openapi 3 version.

has any other plugin likes `Swagger2Markup` could support this feature?

thanks

**Comment by bnasslahsen** [comment]
A possible solution is to convert your OpenAPI 3.0 definition to an HTML doc, then use a browser's "Save to PDF" feature to convert HTML to PDF.

Follow these steps:

1. Go to https://editor.swagger.io.
2. Paste your OpenAPI 3.0 YAML/JSON definition.
3. Select **Generate Client > html**.
4. Download & unzip the file.
5. Open the `index.html` page in a browser, e.g. Chrome.
6. Select **File > Print**, change the **Destination** to **Save as PDF**, and save the page.

Its also answred here:
- https://stackoverflow.com/questions/54259816/how-to-generate-a-pdf-or-markup-from-openapi-3-0
