### ISSUE TITLE
QuerydslPredicateOperationCustomizer: black and whitelist no longer works because of Spring Data Commons change since SpringBoot 2.3.2

### ISSUE THREAD

**Issue by chrisupb** [springdoc/springdoc-openapi#814]
Because of this breaking change in Spring Data commons https://jira.spring.io/browse/DATACMNS-1744, the following lines in https://github.com/springdoc/springdoc-openapi/blob/master/springdoc-openapi-data-rest/src/main/java/org/springdoc/data/rest/customisers/QuerydslPredicateOperationCustomizer.java 
lead to a null pointer exception:

`
Set<String> blacklist = getFieldValues(bindings, "blackList");
Set<String> whiteList = getFieldValues(bindings, "whiteList");
`

SpringBoot 2.3.2
Springdoc-openapi 1.4.1

**Comment by bnasslahsen** [comment]
@chrisupb, 

 springdoc-openapi 1.4.1, was released and tested against spring-boot 2.3.0;

 Next release will support the impacts introduced by 2.3.2 spring-boot release:  see this commit for more details 94f9207a4325f566cdfca910a3f6708be0f2e4c6

**Comment by chrisupb** [comment]
Please reopen. The latest version of springdoc-openapi 1.4.4 improves the situation, however black and whitelists are still not evaluated.

SpringBoot 2.3.2, springdoc-openapi 1.4.4; For this code OpenAPI contains ALL properties of QMyClassEntity.

` @QuerydslPredicate(root = QMyClassEntity.class, bindings = MyClassBinder .class) Predicate predicate,`

` private static class MyClassBinder implements QuerydslBinderCustomizer<QMyClassEntity> {

    @Override
    public void customize(QuerydslBindings bindings, QMyClassEntity root) {

      // exclude all properties from QMyClassEntity
      bindings.excludeUnlistedProperties(true);

      // define an explicit whitelist for properties to include
      bindings.including(root.quantity);

      // define an explicit blacklist for properties to include
      bindings.excluding(root.orderId);
    }
  }`

**Comment by sscholl** [comment]
@bnasslahsen yes, blacklist/whitelist not working

**Comment by bnasslahsen** [comment]
@chrisupb or @sscholl, 

 All existing tests are passing on v1.4.4
 Can you add the test case or the sample HelloController code that shows blacklist/whitelist are not working.
