### ISSUE TITLE
Ability to define description and example values for the same class depending on usage

### ISSUE THREAD

**Issue by Strunevskiy** [springdoc/springdoc-openapi#817]
Is there a way to define description and example values for fields in the the same depending on usage?

```java
@Data
public class Company {
    @Schema
    private String key;
    @Schema
    private String value;
}

@Data
public class Contract {
    @Schema(description = "unique id")
    private String id;

    @Schema
    private Company client;

    @Schema
    private Company partner;
}}
```

I would like to define description and example values for key and value fields depending on usage.
If it is client I would like to have one things there and if it is partner I would to have there the other things

**Comment by bnasslahsen** [comment]
@Strunevskiy, 

 It's already answred here:
- https://github.com/springdoc/springdoc-openapi/issues/685
or Here:
- https://github.com/springdoc/springdoc-openapi/issues/782

**Comment by Strunevskiy** [comment]
@bnasslahsen  I do not think that the situation I am describing is exactly the same as to which you are referring me.

**Comment by bnasslahsen** [comment]
@Strunevskiy, 

 Why do you think so ?

**Comment by Strunevskiy** [comment]
@bnasslahsen  I would like to have different descriptions for class' fields, not just for class whereas in examples you are referring to only class description is different.

**Comment by bnasslahsen** [comment]
@Strunevskiy, 

 The same response apply, depending on your usage you just have to update the description of the property schema you would like.

The following code, shows how you can get different email descriptions for the same class.

```java
public class PersonDTO {

	@JsonProperty
	private String email;

	@JsonProperty
	private String firstName;

	@JsonProperty
	private String lastName;


}

	@Bean
	public OpenAPI customOpenAPI() {
		return new OpenAPI().components(new Components()
				.addSchemas("PersonDTO1", getFieldSchemaWithDifferentDescription(PersonDTO.class, "work email" ))
				.addSchemas("PersonDTO2", getFieldSchemaWithDifferentDescription(PersonDTO.class, "home email" )));
	}

	private Schema getFieldSchemaWithDifferentDescription(Class className, String description){
		ResolvedSchema resolvedSchema = ModelConverters.getInstance()
				.resolveAsResolvedSchema(
						new AnnotatedType(className).resolveAsRef(false));
		return resolvedSchema.schema.addProperties("email", new StringSchema().description(description));
	}
```
