### ISSUE TITLE
More precise exception response

### ISSUE THREAD

**Issue by cn-src** [springdoc/springdoc-openapi#818]
**Is your feature request related to a problem? Please describe.**

Support the configuration of global default exceptions responses, and generate responses based on throws declarations.

**Comment by bnasslahsen** [comment]
@cn-src, 

 Please try to be more precise about your feature request.
 You can have a look at the contribution guide section `[using GITHUB Issues](https://github.com/springdoc/springdoc-openapi/blob/master/CONTRIBUTING.adoc)`.

 This ticket will be closed, and can be reopened if you provide more explantation about your feature with examples...
