### ISSUE TITLE
OpenAPI documentation with Spring WebFlux is not working 

### ISSUE THREAD

**Issue by ZinfinityDarshan** [springdoc/springdoc-openapi#819]
I have added below things as per documentation 

pom.xml
`	   <dependency>
	      <groupId>org.springdoc</groupId>
	      <artifactId>springdoc-openapi-webflux-ui</artifactId>
	      <version>1.4.4</version>
	   </dependency>
	   <dependency>
	      <groupId>org.springdoc</groupId>
	      <artifactId>springdoc-openapi-security</artifactId>
	      <version>1.4.4</version>
	   </dependency>
`
application.properties
`springdoc.api-docs.path=/api-docs `

getting below response 
![image](https://user-images.githubusercontent.com/44725488/89643050-90113500-d8d2-11ea-85c7-64ef2bb5153e.png)

Can you please help me out ....

**Comment by bnasslahsen** [comment]
@ZinfinityDarshan ,

 Please review your application configuration, as you are getting HTTP 401.
 You can have a look at different samples depending on your case:
 - https://github.com/bnasslahsen/springdoc-openapi-demos/
