### ISSUE TITLE
Not Scanning All Methods in Controller

### ISSUE THREAD

**Issue by amirbayan** [springdoc/springdoc-openapi#821]
**Describe the bug**
when I upgrade to version 1.4.4, springboc was not able to scan all the controllers and put them in swagger-ui web page. 

**To Reproduce**
- version 1.4.4
- openapi-ui only
- some controller is not shown in the ui or the Jons (api-docs)

**Comment by bnasslahsen** [comment]
@amirbayan, 

If you are reporting a bug, please help to speed up problem diagnosis by providing as much information as possible:

All is described in the contrubution guide section[ using github issues](https://github.com/springdoc/springdoc-openapi/blob/master/CONTRIBUTING.adoc)

This ticket will be reopened, if the relevant information are provided.

**Comment by amirbayan** [comment]
I have found where is the problem. Springboc does not scan the methods that return ModelAndView by default, you have to explicitly add the special flag for it in the application.properties and assign it to true: 
`springdoc.model-and-view-allowed=true`

I am adding this comment in case someone faced same issue like me.
