### ISSUE TITLE
OpenAPI bean addSchemas() doesn't generate schema definitions when schema is not referenced

### ISSUE THREAD

**Issue by soulshined** [springdoc/springdoc-openapi#823]
**Describe the bug**
I've followed the migration guidelines from [here](https://springdoc.org/migrating-from-springfox.html) and it works great overall. The only issue is schema definitions are not generated.

**To Reproduce**
- What version of spring-boot you are using? 2.2.7.RELEASE
- What modules and versions of springdoc-openapi are you using?
```xml
<dependency>
   <groupId>org.springdoc</groupId>
   <artifactId>springdoc-openapi-ui</artifactId>
   <version>1.4.3</version>
</dependency>
<dependency>
   <groupId>org.springdoc</groupId>
   <artifactId>springdoc-openapi-security</artifactId>
   <version>1.4.3</version>
</dependency>
```

```java
@Configuration
public class OpenAPIConfig implements OperationCustomizer {

    @Bean
    public OpenAPI getOpenAPI() {
        return new OpenAPI()
             .components(getComponents());
    }
    
    public Components getComponents() {
        return new Components()
            .addParameters("Works", new QueryParameter()
                .name("workingParam")
                .description("This works")
                .schema(new StringSchema()._default(""))
            )
            .addResponses("Works", new ApiResponse().description("This works too"))
            .addSchemas("HelloWorld", new StringSchema()
                .name("HelloWorld")
                .type("String")
                .description("Some schema")
            );
    }

}
```

**Expected behavior**
Expected behavior is for the schemas to be added to the generated yaml file like the parameters and responses are; here is what's appended to my `/v3/api-docs.yaml` file:

```
components:
  schemas:
      ...
  responses:
    Works:
      description: This works too
  parameters:
    Works:
      name: workingParam
      in: query
      description: This works
      schema:
        type: string
        default: ""
```

**Comment by bnasslahsen** [comment]
@soulshined, 

 If your schema is not referenced, springdoc-openapi removes any broken references.
 You should have your schema references somewhere in your code (responses, parameters, requestbody...), or if you really wants it to be displayed, then disable the removal of broken references:

```properties
springdoc.remove-broken-reference-definitions=false
```

Note that all the available propperties are alrready documented here:
 - https://springdoc.org/springdoc-properties.html

**Comment by soulshined** [comment]
Ah. @bnasslahsen that resolves it. I saw that property but didn't figure to try because I didn't consider it be 'broken'. Thank you for the guidance
