### ISSUE TITLE
Missing springdoc-openapi-groovy-1.4.4.jar in public repositories

### ISSUE THREAD

**Issue by vsvyatski** [springdoc/springdoc-openapi#824]
**Describe the bug**
During the v1.4.4 release you seem to forget to publish the springdoc-openapi-groovy-1.4.4.jar artifact.

**To Reproduce**
Take any public Maven repository (including your own) and navigate to .../org/springdoc/springdoc-openapi-groovy/1.4.4/. 

**Expected behavior**
springdoc-openapi-groovy-1.4.4.jar is there. But instead you'll see a lot of other files except for the most important one

**Additional context**
I have the following dependency in my Gradle script:
```
implementation("org.springdoc:springdoc-openapi-groovy:$springDocVersion")
```
When `$springDocVersion` was set to 1.4.3 things worked, once I updated to 1.4.4 I started seeing the following:
```
Execution failed for task ':compileGroovy'.
> Could not resolve all files for configuration ':compileClasspath'.
   > Could not find org.springdoc:springdoc-openapi-groovy:1.4.4.
```
Then I started to browse the repositories manually and didn't find the most important JAR, only javadocs, sources, hashes, etc.

**Comment by bnasslahsen** [comment]
@vsvyatski, 

 Thank you for reporting this missing artifact; 
 There was a synchronisation issue with maven central, which has been now resolved by the team.
