### ISSUE TITLE
Upgrade from Swagger2 to Springdocs lead to 404 on /v3/api-docs and 'Failed to load API definition'.

### ISSUE THREAD

**Issue by eldjarn** [springdoc/springdoc-openapi#825]
**Describe the bug**
I have simple Spring Boot + Swagger 2 application, Keycloack is used for authorization. All worked fine, I could see AuthorizationController endpoint in swagger-ui, push Authorize button, provide token given by keycloack in following form 'Bearer ***' and try it out.

**To Reproduce**
I tried to switch to springdoc and failed - I get 'Failed to load API definition' in swagger-ui (/v3/api-docs responses with 404).
I didn't find replacements for:
```
//    private SecurityContext securityContext() {
//        return SecurityContext.builder()
//                                    .securityReferences(defaultAuth())
//                                    .build();
//    }

//    private ApiKey apiKey() {
//        return new ApiKey("JWT", "Authorization", "header");
//    }

//    private List<SecurityReference> defaultAuth() {
//        return Collections.singletonList(new SecurityReference("JWT",
//                new AuthorizationScope[]{
//                        new AuthorizationScope("global", "accessEverything")
//                }));
//    }
```
in the new apis, so maybe that's the problem.

I use last release versions
```
<spring.boot.version>2.3.2.RELEASE</spring.boot.version>
<springdoc.version>1.4.4</springdoc.version>
```
and springdoc dependencies as follows springdoc-openapi-ui, springdoc-openapi-security.

My open api configuration is:
```
@OpenAPIDefinition(
        info = @Info(
                title = "User Service",
                description = "Service that handle user operations",
                version = "v2"
        )
)
@SecurityScheme(
        name = "Authorization",
        type = SecuritySchemeType.APIKEY,
        scheme = "Authorization",
        in = SecuritySchemeIn.HEADER,
        bearerFormat = "Authorization",
        paramName = "Authorization"
)
public class OpenApiConfiguration {}
```

and `@SecurityRequirement(name = "Authorization")` on controller and/or operations.

Sample project containing postgresql, keycloak with sample users and roles and application with AuthorizationController and springdoc, logs and HAR provided. README.MD in root directory describes how to run the sample.

**Expected behavior**
Swagger ui shows `AuthorizationController` endpoints, I can authorize requests with token and try it out.

[log.log](https://github.com/springdoc/springdoc-openapi/files/5083081/log.log)
[localhost.zip](https://github.com/springdoc/springdoc-openapi/files/5083083/localhost.zip)
[user-service.zip](https://github.com/springdoc/springdoc-openapi/files/5083090/user-service.zip)

**Comment by bnasslahsen** [comment]
@eldjarn, 

 Have you looked at this demo application code? 
 - https://github.com/springdoc/springdoc-openapi-demos/tree/master/sample-springdoc-openapi-oauth2

**Comment by bnasslahsen** [comment]
@eldjarn, 

 This ticket will be closed, as there is no answer.

 It can be reopened if you provide a **minimal** reproducible example, which works without any additionnal configuration.
  You current attached project, requires additionnal postgresql database configuration, and keykloack configuration as well.

**Comment by eldjarn** [comment]
@bnasslahsen 
Project I attached contains database and keycloack configuration. 
It works as follows:
docker-compose up community-postgres community-keycloak -d
starts pg+keycloack, configures keycloak with 2 users - admin : admin, user : user

`./mvnw clean package `
builds service, 
`docker-compose up user-service -d`
runs service.

One can run pg+keycloack and then service, or run the whole project: `docker-compose up user-service`. Then you'll see swagger ui at: `http://localhost:8080/swagger-ui.html` (but it works well only with swagger2).
