### ISSUE TITLE
@Schema(hidden = true) does not work with data model class

### ISSUE THREAD

**Issue by abuklis** [springdoc/springdoc-openapi#826]
Hi, 
I am Hanna Buklis, backend developer.
I started using springdoc-openapi-ui on my current project a few days ago.
I faced the following issue: I cannot hide on certain schema from 'Schemas' list in ui section.
Schemas list:
![image](https://user-images.githubusercontent.com/20967414/90392145-fc402580-e096-11ea-9218-fed7490594e2.png)

I checked documentation, it looks like @Schema(hidden = true) should hide a class from the list above.

**My setup:**
Spring Boot 2.2.6.RELEASE
springdoc-openapi: 1.4.3
springdoc-openapi-data-rest: 1.4.3

**Entity class which I want to hide:**
```@Document@Data
@AllArgsConstructor
@NoArgsConstructor
@Schema(hidden = true)
public class FailedUser {
    @Id
    private String id;
}
```

**Application properties :**
springdoc.api-docs.resolve-schema-properties=true
springdoc.api-docs.enabled=true
springdoc.api-docs.path=/doc/definition
springdoc.swagger-ui.path=/doc/docs
springdoc.swagger-ui.supportedSubmitMethods=["get"]

After this configuration, I expect FailedUser to be absent in 'Schemas' list. But it is still in place.
Could you please tell me if this is a bug or wrong configuration?

Thank you in advance.

Best regards,
Hanna Buklis.

**Comment by bnasslahsen** [comment]
Hi @abuklis, 

 Not sure which springdoc documentation you are refering to about the usage of @Schema on the class level:
 It looks more an issue in the swagger-core code:
  - https://github.com/swagger-api/swagger-core/issues

 Here is the code snippet, that shows it. 
 You can submit your issue to the swagger team with the following:

```java
	ResolvedSchema resolvedSchema = ModelConverters.getInstance()
				.resolveAsResolvedSchema(
						new AnnotatedType(FailedUser.class).resolveAsRef(true));
		Assert.isNull(resolvedSchema.schema, "The schema should be hidden.");
```

 This is said, you have many workarounds depending on your case:
 

- if the class `FailedUser `is a parameter of your controller, you can use: `@Parameter(hidden = true) ` or `@RequestBody(hidden=true)`

 

- If its on the response, you can use: empty content return if its relevant: 

   - https://springdoc.org/faq.html#how-can-i-return-an-empty-content-as-response

    Otherwise, if you want the schema to be hidden from the response object, the OpenAPI generated documentation will be not valid.

-  if the class `FailedUser` is a field in another class, then: You can add on the field level instead:

    - https://springdoc.org/faq.html#how-can-i-ignore-some-field-of-model-

**Comment by jlorenzoC** [comment]
Hi @bnasslahsen , I'm new at springdoc openapi 3 cuz I'm collaborating on a project that is using it. So, in my case my problem is that I'm not seen some defined models in this object schemas list. Some models are there, but other not. Please why is that happening? Cheers.

**Comment by bnasslahsen** [comment]
@jlorenzoC, 

 You should have the getter/setter, for all your fields.
 If it is already the case, could you add more details about your class A, with a sample minimal sample including a HelloController that references it?

**Comment by jlorenzoC** [comment]
> @jlorenzoC,
> 
> You should have the getter/setter, for all your fields.
> If it is already the case, could you add more details about your class A, with a sample minimal sample including a HelloController that references it?

Thanks @bnasslahsen for your fast replay. How would you reference a model in a controller?

**Comment by bnasslahsen** [comment]
@jlorenzoC, 

 You have a lot of samples for test controllers in the project tests. 
 For example, the code here: 
 - https://github.com/springdoc/springdoc-openapi/tree/master/springdoc-openapi-webmvc-core/src/test/java/test/org/springdoc/api/app130

 If you have any other question, please make sure you provide the requested code samples.

**Comment by jlorenzoC** [comment]
@bnasslahsen thanks bro. Issue solved! You helped me to solve the issue. The problem was that the controller of the model A wasn't referencing it like you just showed me. Thanks a lot!
