### ISSUE TITLE
Add support for syntaxHighlight: false

### ISSUE THREAD

**Issue by SledgeHammer01** [springdoc/springdoc-openapi#828]
In 1.4.4, you ingested the latest version of swagger-ui which introduced syntax highlighting. Can you add support for the syntaxHighlight: false on the config property so we can opt out? Thanks!

**Comment by bnasslahsen** [comment]
@SledgeHammer01, 


 Would be nice if you stop creating the same request on different channels.


 It seems you already initiated this on stackoverflow:
 - https://stackoverflow.com/questions/63417152/changing-swagger-ui-theme-in-springdoc

Please have a look at the contribution guide for more details about which channel is most appropriate for each case: 
- https://github.com/springdoc/springdoc-openapi/blob/master/CONTRIBUTING.adoc

**Comment by SledgeHammer01** [comment]
@bnasslahsen 

Would be nice if you weren't so rude. I'm not interested in creating a custom theme. I'm interested in using a flag that swagger-ui exposes for this purpose. That is a feature request.

If you are not interested in supporting your product, don't make one.

**Comment by bnasslahsen** [comment]
@SledgeHammer01, 

  You are not welcome here. As you are not respecting the code of conduct:
 - https://github.com/springdoc/springdoc-openapi/blob/master/CODE_OF_CONDUCT.adoc
