### ISSUE TITLE
Inherited property missing from child Dto but present on identical sibling Dto

### ISSUE THREAD

**Issue by halvorsone** [springdoc/springdoc-openapi#83]
We are trying to represent a tree of logic operators with Dtos using simple inheritance.

This is essentially what our Dtos look like:
```java
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "operator")
@JsonSubTypes({ @JsonSubTypes.Type(value = MyAndDto.class, name = "and"),
        @JsonSubTypes.Type(value = MyOrDto.class, name = "or"),
        @JsonSubTypes.Type(value = MyEqualsDto.class, name = "equals") })
public class MyBaseDto {
    public String operator;
}

public class MyEqualsDto extends MyBaseDto {
    public String field;
    public String value;
}

public class MyPartsDto extends MyBaseDto {
    public MyBaseDto[] parts;
}

public class MyAndDto extends MyPartsDto {
}

public class MyOrDto extends MyPartsDto {
}
```
As you can see, the `MyAndDto` and `MyOrDto` are pretty much identical.

However, the result generated from `/v3/api-docs` looks like this:
```json
"MyAndDto":{
    "type":"object",
    "allOf":[
        {
            "$ref":"#/components/schemas/MyBaseDto"
        },
        {
            "type":"object",
            "properties":{
                "parts":{
                    "type":"array",
                    "items":{
                        "$ref":"#/components/schemas/MyBaseDto"
                    }
                }
            }
        }
    ]
},

"MyBaseDto":{
    "type":"object",
    "properties":{
        "operator":{
            "type":"string"
        }
    },
    "discriminator":{
        "propertyName":"operator"
    }
},

"MyEqualsDto":{
    "type":"object",
    "allOf":[
        {
            "$ref":"#/components/schemas/MyBaseDto"
        },
        {
            "type":"object",
            "properties":{
                "field":{
                    "type":"string"
                },
                "value":{
                    "type":"string"
                }
            }
        }
    ]
},

"MyOrDto":{
    "type":"object",
    "allOf":[
        {
            "$ref":"#/components/schemas/MyBaseDto"
        }
    ]
}
```
For some reason, the `MyAndDto` generates correctly with the inherited `parts` property. But, the identical `MyOrDto` is missing the inherited `parts` property entirely.

Shouldn't the results generated for both Dtos be the same?

We are using:
```
"org.springdoc:springdoc-openapi-ui:1.1.35"
"org.springframework.boot:spring-boot-starter-web:2.1.7.RELEASE"
```

Thank you.

**Comment by springdoc** [comment]
Hi, 

 The JsonSubTypes description do not look right:

- MyOrDto and MyAndDto are not subtypes of MyBaseDto. They are subtypes of MyPartsDto

 Here is a working exampel:
```java
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "parts")
@JsonSubTypes({ @JsonSubTypes.Type(value = MyAndDto.class, name = "and"),
		@JsonSubTypes.Type(value = MyOrDto.class, name = "or") })
public class MyPartsDto extends MyBaseDto {
	public MyBaseDto[] parts;
}
```

**Comment by halvorsone** [comment]
Thank you for taking the time to look into this.

It still doesn't explain why MyAndDto is generated correctly, while MyOrDto is not.

MyPartsDto extends MyBaseDto. So, strictly speaking, MyAndDto and MyOrDto do extend from MyBaseDto. The jackson serialization/deserialization has been working fine the way we currently have it. It was just the generated model that wasn't quite right.

Ultimately, we don't want to expose in the model that MyPartsDto even exists since it should never be instantiated. It was just there to share code common to both MyAndDto and MyOrDto. So, we will probably just remove the MyPartsDto subclass and duplicate that code on MyAndDto and MyOrDto then.

Thanks.

**Comment by halvorsone** [comment]
I did some debugging, and this appears to be an issue in swagger core. So, I submitted an issue there:
https://github.com/swagger-api/swagger-core/issues/3312

**Comment by bnasslahsen** [comment]
Great. Thank you. 
We will follow it as well.

**Comment by balajiv113** [comment]
@bnasslahsen - Am also facing the same issue. Looks like there will not be a fix from open-api any time soon. 
As a workaround is there a way to enforce the order in which my RestControllers are loaded. If this is possible i can have the generic schema read first so the child schema will be correct.

**Comment by raghuraman1** [comment]
Hi @bnasslahsen,

Please refer- https://github.com/teq-niq/sample/tree/swagger-core-issue3312-hack
More important also please refer- https://github.com/teq-niq/sample/tree/swagger-core-issue3312-better

What are your views about the branches swagger-core-issue3312-hack and swagger-core-issue3312-better in repository- https://github.com/teq-niq/sample.git ?
I thought I will check with you before taking up with Swagger-core for hopefully a new PR to provide some indirection when creating SchemaSerializer instance.
If that works out it can also help get more community driven extensions of io.swagger.v3.core.jackson.SchemaSerializer and cause improvement in io.swagger.v3.core.jackson.SchemaSerializer

Thanks waiting for your suggestions.

Raghu

**Comment by raghuraman1** [comment]
Hi @bnasslahsen ,

I think I have a fix for this over here -https://github.com/teq-niq/sample/tree/swagger-core-issue3312-better
While this can help. I hope it helps solve multiple issues based on the concepts here in the fix.
I am hoping to share this with swagger-core and try for a subsequent PR limited to only providing extensibility to SchemaSerializer based on this demo code.

Please suggest if this can be improved?
Raghu
