### ISSUE TITLE
Multipart with JSON and files payload

### ISSUE THREAD

**Issue by blaluc** [springdoc/springdoc-openapi#833]
I didn't catch if this issue has a solution or if it depends on the standard swagger-ui.
There's one of the test cases:
https://github.com/springdoc/springdoc-openapi/blob/master/springdoc-openapi-webmvc-core/src/test/java/test/org/springdoc/api/app119/HelloController.java
that does not work when invoked from the UI.

The error reported in the console is:

Resolved [org.springframework.web.HttpMediaTypeNotAcceptableException: Could not find acceptable representation]

Is it possible to annotate a mulitpart post request in a way that it allows to submit both a json payload and one or more files from the swagger-ui?

**Comment by little-pinecone** [comment]
The workaround from #820 still leaves Swagger UI in a broken state.

A working workaround for Swagger is to provide a custom `HttpMessageConverter` to deserialize `application/octet-stream` as shown here: [#6462](https://github.com/swagger-api/swagger-ui/issues/6462#issuecomment-929189296).

The converter:

```java
@Bean
public MappingJackson2HttpMessageConverter octetStreamJsonConverter() {
    MappingJackson2HttpMessageConverter converter = new MappingJackson2HttpMessageConverter();
    converter.setSupportedMediaTypes(List.of(new MediaType("application", "octet-stream")));
    return converter;
}
```

The endpoint code should look like in the snippet below:

```java
@PostMapping(consumes = MediaType.MULTIPART_FORM_DATA_VALUE)
public ResponseEntity<Void> saveDocu2ment(
        @RequestPart PersonDTO personDTO,
        @RequestPart(value = "file") MultipartFile file
) {
    …
}
```

Thanks to that you get a proper OpenAPI specification and working Swagger UI (tested with Spring Boot 2.5.6, Springdoc 1.6.6).

This should also work for #820 and #964.
