### ISSUE TITLE
Spring Data Rest Documentation Question

### ISSUE THREAD

**Issue by MiellyEllen** [springdoc/springdoc-openapi#834]
**Is your feature request related to a problem? Please describe.**
Question about how to better document Spring Data Rest Repositories 

**Describe the solution you'd like**
I would like to override the "entityname"-entity-controller, "entityname"-search-controller tags and exclude the property apis.

**Describe alternatives you've considered**
Is there a way to do this without a code change

**Additional context**
I'm an instructor for LinkedIn Learning.https://www.linkedin.com/learning/instructors/mary-ellen-bowman. I'd like to include a demo of springdocs  in one of my courses. I have MVC Controllers and Spring Data Rest Repositories. The MVC Controllers are easy to assign documentation with @Tag, but I cannot figure out how to document my Spring Data REST API's better than what is generated by default.

**Comment by MiellyEllen** [comment]
Thanks for the in-depth example.
The spring-docs video I'm adding to my course will only be about 7 minutes, and I only update my courses once a year.
I was hoping for something easy to demonstrate in application.properties, but seems like that's currently not possible. 
But that's fine.
I was able to step through your code in a debugger and tinker with the existing properties to get me somewhat there to do a decent demonstration:
springdoc.pathsToMatch=/tours,/tours/*,/tours/search/**,/tours/*/ratings/**,/ratings/**,/packages,/packages/search/**,/packages/*
springdoc.autoTagClasses=false

BTW, is property referencing really a thing in Spring Data Rest API's? I get that impression for the generated docs.
I have a Spring Data Restful repository for an api called /tours with an attribute called "title". When I hit /tours/1/title i get a 404 back.

I'd like to share the video with you when the course goes live in about a month. Are you on LinkedIn? Here's my LinkedIn page: https://www.linkedin.com/in/mebowman.  And my teaching website https://MaryEllenTeaches.me

**Comment by bnasslahsen** [comment]
Hi @MiellyEllen, 

 In fact property referencing is part of spring data rest: Here is sample about it:
 - https://www.baeldung.com/spring-data-rest-relationships
 
 For the moment, it's generated by default for all entities on spring-data-rest.

 But what would be suitable for the projects, is to generate it dynamically, depending on the  entity has relationships: : This is the ongoing enhancement about it: https://github.com/springdoc/springdoc-openapi/issues/792

 It should be hopefully improved with the next release v1.4.5. Where we will introduce also the ability to add `@Tags` and `@SecurityRequirements `annotation on the `@Repository` level, in order to override the default tags.

**Comment by bnasslahsen** [comment]
@MiellyEllen, 

 FYI, the version v1.4.5 is now released. 
 The support of spring-data-rest has been enhanced with this release.

**Comment by MiellyEllen** [comment]
Wow! Great improvement!
I already recorded the video with 1.4.4 a few days ago and was preparing to send the equipment back to LinkedIn, but will definitely re-record with these updates.
Was there a way to re-tag the "profile-controller", if not, no big deal.

**Comment by bnasslahsen** [comment]
In Fact, for your repositories you can use `@Tag` swagger annotation on top of the Repository:
- https://github.com/springdoc/springdoc-openapi/blob/a382dd3150e59ae3981023fb282dd3e1b9f3bc92/springdoc-openapi-data-rest/src/test/java/test/org/springdoc/api/app16/AccountRepository.java#L41.

For the profile-controller, it can be renamed, if needed using `OpenApiCustomiser` :

```java
@Bean
OpenApiCustomiser OpenApiTagsCustomiser() {
	return openApi -> openApi.getPaths().values().stream().flatMap(pathItem -> pathItem.readOperations().stream())
			.forEach(operation -> {
				String tagName = operation.getTags().get(0);
				// rename the profile-controller tag
				if ("profile-controller".equals(tagName)) {
					// Replace with the new tag value
					operation.getTags().set(0, "my-profile");
				}
			});
}
```

**Comment by MiellyEllen** [comment]
Yep, the first thing I did was add @Tag. happy to see it work.
For my example I don't need the /profile api to confuse the learner, so I just excluded it.
Thanks for you help. I'll let you know when it's live. Probably in a month

**Comment by MiellyEllen** [comment]
<div style="position:relative;height:0;padding-bottom:56.25%"><iframe width="640" height="360" src="https://www.linkedin.com/learning/embed/extending-securing-and-dockerizing-spring-boot-microservices/documenting-apis-with-swagger-2?claim=AQE83tsfxrdBQAAAAXUDGyleVWB8Yl_antYg--NoQxePlB6bRg6kivGqI1C-K0xZTIuKxaw9TlRkC3aOT5HeOG6SQWt5Yg1msQWAP7Qm9Rb7n4Xsa7s4mqADSwOftdMv4JGYPAwKQJZdiU17-A_1LrmtjA-mClpLitqRNQTeiK0TV2XwUeTShNVxvec9K_km5Zz0Yfr_6PLqnJRH6z-xx2YwGygFNjVnI_hsQCsmeq0_7uRj6XJXSdXIUGhLaQPGPrYmUeUzfMwurcuR3uNmAVP1r72gT-yGjERIjaMBuopqggOOCtdK96sSG1tHbMpvTHtEE2SLwPjqE4fLhII8MLnA9iwBltLuTG41dTz-AOwL3pU_OIOmZnhfDfWygkuVpLhvoRjgvHuXmN2h_zgqwFmwsFQU4f0Xs61GLB8xS3FI0zLYZVonXWI1rpXTzjVkouXUhVoieCAJ-D7d-Edh6KgaHsLr2FqgsdBIuxvtdajDQHpqF2h-DiX5x4nhom6KPmKWYInZ1SjxJrNvEc0dalakioKmGVOXgVCrQyhCJX5yAPkUu_89PNmviKhJIclvesp4h9lWbyV9VJcvE9iOamvndm2QMGgo5W4guDJ51S8NEep9DdLhEb4PqPelfGkFsbZlOr7MB5lohaiZgZUg7DtYdyAWd57ZD-0_0TVYruB29ZxwyJ5Nr-Z6gYYjKwxvekiqMI1LGL_tTJcnHWHqxb9ArR2mdfykauKuozaErRwz&autoplay=true" mozallowfullscreen="true" webkitallowfullscreen="true" allowfullscreen="true" frameborder="0" style="position:absolute;width:100%;height:100%;left:0"></iframe></div><p><strong><a href="https://www.linkedin.com/learning/extending-securing-and-dockerizing-spring-boot-microservices/documenting-apis-with-swagger-2?trk=embed_lil">Documenting APIs with Swagger</a></strong> from <strong><a href="https://www.linkedin.com/learning/extending-securing-and-dockerizing-spring-boot-microservices?trk=embed_lil">Extending, Securing, and Dockerizing Spring Boot Microservices</a></strong> by <strong><a href="https://www.linkedin.com/learning/instructors/mary-ellen-bowman?trk=embed_lil">Mary Ellen Bowman</a></strong></p>
