### ISSUE TITLE
Endpoint Ordering not working

### ISSUE THREAD

**Issue by milindrao** [springdoc/springdoc-openapi#835]
This is the same issue as https://github.com/springdoc/springdoc-openapi/issues/467

I commented on that bug, but perhaps not got any response since that ticket has been closed.  So creating a new one.

I'm using v1.4.3 and I have enabled sorting of the endpoints using the method name
In my application.properties file, I have 
springdoc.swagger-ui.operationsSorter=method

Instead of getting the methods sorted as GET, PATCH, POST, I get them as POST, GET, PATCH.

In addition to the endpoints itself, even some (though not all) attribute order has changed. Not sure what I need to do to fix that.

This makes it very difficult to compare two jsons to see the differences between versions.

My pom file has the following parent

> 	<parent>
> 		<groupId>org.springframework.boot</groupId>
> 		<artifactId>spring-boot-starter-parent</artifactId>
> 		<version>2.3.0.RELEASE</version>
> 		<relativePath/> 
> 	</parent>

and has the following dependencies

> 		
> 		<dependency>
> 		    <groupId>org.springframework.hateoas</groupId>
> 		    <artifactId>spring-hateoas</artifactId>
> 		    <version>1.1.0.RELEASE</version>
> 		</dependency>
> 
> 		<dependency>
> 		    <groupId>com.github.java-json-tools</groupId>
> 		    <artifactId>json-patch</artifactId>
> 		    <version>1.12</version>
> 		</dependency>
> 		
> 		<dependency>
> 	    	<groupId>org.springdoc</groupId>
> 	    	<artifactId>springdoc-openapi-ui</artifactId>
> 	    	<version>1.4.3</version>
> 		</dependency>
> 		
>  		<dependency>
>       	<groupId>org.springdoc</groupId>
>       	<artifactId>springdoc-openapi-hateoas</artifactId>
> 	    	<version>1.4.3</version>
>    		</dependency>		
>
> 		<dependency>
> 			<groupId>org.springframework.boot</groupId>
> 			<artifactId>spring-boot-starter-web</artifactId>
> 		</dependency>
> 
> 		<dependency>
> 			<groupId>org.springframework.boot</groupId>
> 			<artifactId>spring-boot-starter-validation</artifactId>
> 		</dependency>

Please let me know if there's any additional information I can provide.  Thanks.

**Comment by bnasslahsen** [comment]
@milindrao, 

You should get the sorting by HTTP METHODS. (DELETE / GET / HEAD / PATCH / POST / PUT)
If you are not getting this, please add a **minimal reproducible sample**, or you can try to reproduce your issue on the demos repo and provide the link to your code:
- https://github.com/springdoc/springdoc-openapi-demos/tree/master/sample-springdoc-openapi-hateoas-service

**Comment by milindrao** [comment]
I haven't been able to nail down what causes this.  If I comment/uncomment a property in the application.properties and restart, sometimes I'll get it ordered and other times it doesn't.  I'll try to see if I could reproduce it in the sample project.  So far, with a few tries it doesn't happen in the sample app.

**Comment by bnasslahsen** [comment]
ok @milindrao, 
This ticket is closed now, and can be reopened once you provide the relevant information.
