### ISSUE TITLE
Add support of swagger annotations @SecurityRequirement and @Tag on @Repository interface

### ISSUE THREAD

**Issue by mtshane** [springdoc/springdoc-openapi#837]
**Describe the bug**
No annotations that I add to @Repository interfaces are used to guide the config creation

**To Reproduce**
- new Spring Boot 2.2.9-RELEASE
- springdoc-openapi-ui 1.4.4
- springdoc-openapi-data-rest 1.4.4
- Create a standard @RestController and annotate it with @Tag and @SecurityRequirement
- Apply the same annotations to a @Repository interface
- The generation for the controller works as expected, but the Repository interface annotations are ignored

`@RestController
@RequestMapping(
  value = "/api/v1/integration/hawksearch",
  produces = MediaType.APPLICATION_JSON_VALUE
)
@Tag(name = "hawksearch-admin-controller", description = "Manage Hawksearch Data through the API")
@SecurityRequirement(name = "EntityAPIs")
public class HawksearchAdminController {

  private final HawksearchFieldService fieldService;
  private final HawksearchProductService hawksearchProductService;
  private final HawksearchIndexService hawksearchIndexService;

  @Autowired
  public HawksearchAdminController(HawksearchFieldService fieldService,
    HawksearchProductService hawksearchProductService,
    HawksearchIndexService hawksearchIndexService) {
    this.fieldService = fieldService;
    this.hawksearchProductService = hawksearchProductService;
    this.hawksearchIndexService = hawksearchIndexService;
  }

  @GetMapping( "/fields")
  @Operation(summary = "Get All Fields")
  public ResponseEntity<?> getAllFields(@RequestParam Map<String, Object> parameters) {
    try {
      Preconditions.checkNotNull(parameters.get("instance"), "Parameter (instance) is required");
      return new ResponseEntity<>(fieldService.getFields((String) parameters.get("instance")), HttpStatus.OK);
    }
    catch (Exception e) {
      throw new RemoteServiceException(e.getMessage(), e);
    }
  }

  @PostMapping( "/fields")
  @Operation(summary = "Create a new Field")
  public ResponseEntity<?> createField(@RequestBody NewFieldRequest newFieldRequest) {
    try {
      Preconditions.checkArgument(StringUtils.isNotEmpty(newFieldRequest.getInstance()), "instance is required");
      Preconditions.checkArgument(Objects.nonNull(newFieldRequest.getField()), "field is required");
      return new ResponseEntity<>(fieldService.createField(newFieldRequest.getInstance(), newFieldRequest.getField()), HttpStatus.OK);
    }
    catch (Exception e) {
      throw new RemoteServiceException(e.getMessage(), e);
    }
  }
}`

`@Tag(name = "Address Entity", description = "Address objects attached to Users")
@SecurityRequirement(name = "EntityAPIs")
@Repository
public interface AddressRepository extends JpaRepository<Address, Long>, JpaSpecificationExecutor<Address> {

  Optional<Address> findOneById(Long id);

  @Query("select ua from UserAddress ua JOIN FETCH ua.address a JOIN FETCH ua.user u where u = ?1")
  Collection<UserAddress> findAllAddressesByUser(User user);

}`

**Expected behavior**
- The lock on the operation in swagger-ui should reference the correct authorization method to use for that path
- The Tags array at the path/operation, and the global config should contain an entry with the annotation Tag name and description
- The operation security array should contain the define security requirement

**Screenshots**

![Screen Shot 2020-08-25 at 7 04 35 AM](https://user-images.githubusercontent.com/7014209/91178012-c821c180-e6a1-11ea-8d7e-ad194664a382.png)
![Screen Shot 2020-08-25 at 7 04 49 AM](https://user-images.githubusercontent.com/7014209/91178023-cb1cb200-e6a1-11ea-9b47-77dfbecf8590.png)

**Additional context**
Attached example of generated json from above two classes
[springdoc.json.zip](https://github.com/springdoc/springdoc-openapi/files/5123920/springdoc.json.zip)

**Comment by bnasslahsen** [comment]
@mtshane, 

 It's already answered here: https://github.com/springdoc/springdoc-openapi/issues/777 and here https://github.com/springdoc/springdoc-openapi/issues/644.

**Comment by mtshane** [comment]
Thank you @bnasslahsen ..  sorry, I searched for `@SecurityRequirement` and went through the first two pages of issues and didn't see anything relevant.   Appreciate the response

**Comment by bnasslahsen** [comment]
Great @mtshane, 

 We hopefully will add the support for` @SecurityRequirement` and `@Tags` (on the Repository level) for the next release v1.4.4;
