### ISSUE TITLE
How to change text present on swagger authorization screen using springdoc

### ISSUE THREAD

**Issue by shilanand** [springdoc/springdoc-openapi#839]
**I want to change the Authorized label to Stored.**

The reason I want to change it as it is miss leading. If the user passes an invalid credential still it is showing as authorized.

![image](https://user-images.githubusercontent.com/29447129/91423364-138cc900-e876-11ea-94ed-1e6393c0e3c9.png)

Actual validation of Username and password is happening once we execute the request.

I am also good if anyone has an answer to validate the credentials once we hit the Authorize button as shown below.

The same question is asked on StackOverflow [here](https://stackoverflow.com/q/63610291/3493829)

**Comment by bnasslahsen** [comment]
@shilanand, 

 You don't need to create same topic on many channels. This ticket will be deleted.
 Just choose the appropriate one as described on the contribution guide:
 - https://github.com/springdoc/springdoc-openapi/blob/master/CONTRIBUTING.adoc
