### ISSUE TITLE
@Callback not rendering list of operations

### ISSUE THREAD

**Issue by rafael-bm** [springdoc/springdoc-openapi#840]
**Describe the bug**
An API `@PostMapping` annotated with `@Callback` should display list of operations when rendering the swagger.

**To Reproduce**
```
  @Callback(
      name = "myCallBack",
      callbackUrlExpression = "{$request.body#/callbackUrl}",
      operation = {
          @Operation(
              operationId = "12345",
              method = "GET",
              responses = @ApiResponse(
                  responseCode = "200",
                  description = "response"
              )
          )
      }
  )
@PostMapping(value = {"/myAPI"}, produces = "application/json")
public TransactionResponse myAPI(@RequestBody DataRequest dataRequest){}
```

**Expected behavior**
- should display list of operations

**Screenshots**
<img width="638" alt="Screenshot 2020-08-27 at 15 41 44" src="https://user-images.githubusercontent.com/15720390/91457199-01158e00-e87c-11ea-9b13-5f0d95d49ec6.png">

**Comment by bnasslahsen** [comment]
@rafael-bm, 

 Your get method should be in lowercase.
 Or, you can use the springdoc constants: `method = org.springdoc.core.Constants.GET_METHOD`
