### ISSUE TITLE
GroupedOpenApi not working in Spring MVC

### ISSUE THREAD

**Issue by onlykalu** [springdoc/springdoc-openapi#841]
My Application is Sping MVC not boot.

I'm using springdoc-openapi-ui 1.4.4

also, I added the following imports to one of my @Configuration class;

```
@Import({ 
	org.springdoc.core.SpringDocConfigProperties.class, org.springdoc.core.SpringDocConfiguration.class, 
	org.springdoc.webmvc.core.SpringDocWebMvcConfiguration.class,
	org.springdoc.webmvc.core.MultipleOpenApiSupportConfiguration.class,
	org.springdoc.core.SwaggerUiConfigProperties.class, org.springdoc.core.SwaggerUiOAuthProperties.class,
	org.springdoc.webmvc.ui.SwaggerConfig.class, org.springdoc.core.CacheOrGroupedOpenApiCondition.class,
	org.springframework.boot.autoconfigure.jackson.JacksonAutoConfiguration.class })

```

and implement the beans as below

    @Bean
    public GroupedOpenApi publicApi() {
        return GroupedOpenApi.builder()
                .group("user")
                .pathsToExclude("/api/v2/**", "/v2/**")
                .pathsToMatch("/api/v1/**", "/v1/**")
                .build();
    }
    @Bean
    public GroupedOpenApi adminApi() {
        return GroupedOpenApi.builder()
                .group("admin")
                .pathsToExclude("/api/v1/**", "/v1/**")
                .pathsToMatch("/api/v2/**", "/v2/**")
                .build();
    }
    
    @Bean
    public OpenAPI customOpenAPI() {
        return new OpenAPI()
	        .components(new Components())
	        .info(new Info()
	        	.title("titleI")
	        	.version("1.0.0"));
    }

But when I try `http://localhost:8080/MyApp/v3/api-docs/user`

gives me 404.

but I get all the APIs listed in `http://localhost:8080/MyApp/v3/api-docs`

Also it comes in `http://www.onlykalu.com:81/MyApp/swagger-ui/index.html?configUrl=/MyApp/v3/api-docs/swagger-config`

also without definition drop down.

if I add

```
springdoc.group-configs[0].group=user
springdoc.group-configs[1].group=admin
```
to application.properties then I get 

![image](https://user-images.githubusercontent.com/4756250/91520551-e523f200-e938-11ea-85d6-c8f8fd262723.png)

Do I need to import any other class to get group functionality work?

Thanks

**Comment by bnasslahsen** [comment]
@onlykalu, 

 What version of spring are you using ?
 Can you attach the stacktace of your error ?

 If you can add a minimal reproducible sample, it will be easier to help.

**Comment by onlykalu** [comment]
I'm using spring 5.2.3.RELEASE.

And I'm not getting any error. you can reproduce this issue in any Spring MVC project.

Please find the attached sample project I created.

`http://localhost:8081/SpringMVCRest/v3/api-docs` - works
`http://localhost:8081/SpringMVCRest/swagger-ui.html` - works

but 
`http://localhost:8081/SpringMVCRest/v3/api-docs/user` -  not working

[SpringMVCRest.zip](https://github.com/springdoc/springdoc-openapi/files/5142054/SpringMVCRest.zip)

Thanks

**Comment by bnasslahsen** [comment]
@onlykalu, 

 You can find attached the working configuration example: You just needed to put your Beans defintion inside a dedicated configuration class, and add it to the springdoc-openapi Beans imports, so that the Beans are loaded by the same mechanism..

[SpringMVCRest-review.zip](https://github.com/springdoc/springdoc-openapi/files/5143776/SpringMVCRest-review.zip)

**Comment by lio-wd** [comment]
I'm following the same pattern, and `/v3/api-docs/user` works at runtime, but can't get it to work in a unit test. I don't see any coverage for this case in the `test` folder either.
