### ISSUE TITLE
@Schema(hidden = true) does not work along with @JsonSerialize(using = LocalDateTimeSerializer.class)

### ISSUE THREAD

**Issue by ravipyadav** [springdoc/springdoc-openapi#842]
I have the following code -

public class Test {
  @Schema(hidden = true)
  @JsonSerialize(using = LocalDateTimeSerializer.class)
  private LocalDateTime someDate;
}

Gradle dependency - 
compile group: 'org.springdoc', name: 'springdoc-openapi-ui', version: '1.4.4'

The generated docs still contain someDate. 

I expect someDate to be hidden in generate API docs.

**Comment by bnasslahsen** [comment]
@ravipyadav, 

 You have just created a duplicate.
 It's already answered here: https://github.com/springdoc/springdoc-openapi/issues/184
