### ISSUE TITLE
Using springdoc.swagger-ui.urls[0].* in beans

### ISSUE THREAD

**Issue by onlykalu** [springdoc/springdoc-openapi#843]
How do I configure 

```
springdoc.swagger-ui.urls[0].name=Public API
springdoc.swagger-ui.urls[0].url=/v3/api-docs/user
springdoc.swagger-ui.urls[1].name=Private API
springdoc.swagger-ui.urls[1].url=/v3/api-docs/admin
```

in 

```
	@Bean
	public GroupedOpenApi publicApi() {
		return GroupedOpenApi.builder()
			.group("user")
			.pathsToExclude("/api/v2/**")
			.pathsToMatch("/api/v1/**")
			.build();
	}

	@Bean
	public GroupedOpenApi adminApi() {
		return GroupedOpenApi.builder()
				.group("Private API")
				.pathsToExclude("/api/v1/**")
				.pathsToMatch("/api/v2/**")
				.build();
	}

```

so then in `http://localhost:8081/SpringMVCRest/api-docs/swagger-config` here I can get as

```
{
  "configUrl": "/MyApp/api-docs/swagger-config",
  "oauth2RedirectUrl": "http://localhost:8081/MyApp/swagger-ui/oauth2-redirect.html",
  "urls": [
    {
      "url": "/MyApp/api-docs/user",
      "name": "Public API"
    },
    {
      "url": "/MyApp/api-docs/admin",
      "name": "PrivateAPI"
    }
  ],
  "validatorUrl": ""
}
```

Im using Pring MVC not boot, version 5.2.3.RELEASE with spingdoc-openapi-ui 1.4.5

**Comment by bnasslahsen** [comment]
@onlykalu, 

 The properties `springdoc.swagger-ui.urls.*`, are suitable to configure external (/v3/api-docs url), for example if you want to agreagte all the endpoints of other services, inside one single application. 
 In general, some projects just want to the springdoc-openapi-ui to serve external swaggers. This property is then suitable. For that, don't forget that CORS needs to be enabled as well.


 For groups configuration, you have two way : (you use either one or the other)
 - By configuration properties: 
For groups configuration: You should have a look at the following properties instead: `springdoc.group-configs.*`
You can confiugre, the group name, packages-to-scan, paths-to-match, paths-to-exclude, packages-to-exclude. This will create on the fly the instances of GroupedOpenApi. 

 - By declaring GroupedOpenApi , programmatically:
Note that using the GroupedOpenApi Bean programmatically, offers feature options for example to configure OpenApiCustomiser.


Note that all properties are available here: https://springdoc.org/springdoc-properties.html#springdoc-openapi-core-properties
And you can have a look at the project tests or demos for examples.

If you have additional questions, you don't need to open a new ticket. You can add your comments here, and the ticket can be reopened if necessary.
