### ISSUE TITLE
ClassNotFoundException: javax.servlet.Filter when using springdoc-openapi-security module in webflux application

### ISSUE THREAD

**Issue by Birthright50** [springdoc/springdoc-openapi#845]
This bug appeared in version 1.4.5 in all webflux applications.
` javax.servlet.Filter` from servlet api was added to `SpringDocSecurityConfiguration`
Problem in this commit:
https://github.com/springdoc/springdoc-openapi/commit/38f70b1b3fcce57049fb97b6d6a29bc37553069b#diff-750e327ff07341b2a6f35ad00e8cd0f0

**Comment by bnasslahsen** [comment]
@Birthright50 ,

 Thank you for pointing out the cause of this error.
 v1.4.6 will be released shortly...
