### ISSUE TITLE
Example and description for @requestpart

### ISSUE THREAD

**Issue by uuk007** [springdoc/springdoc-openapi#849]
The requirement is a user will upload files to spring boot (ReST request) using angular. The ReST interface store the file into gitlab for further processing. Using @RequestPart annotation, content with a different name will be retrieved from a request and placed into Gitlab.  The ReST implementation looks like as follows:

`

    @ApiOperation(value = "Upload java files into Gitlab")
    @RequestMapping(method = RequestMethod.POST, consumes = MediaType.MULTIPART_FORM_DATA_VALUE, produces = "application/json")
    @ApiResponses(value = { @ApiResponse(code = 200, response = CustomResponse.class, message = "Success"),
            @ApiResponse(code = 400, response = ErrorResponse.class, message = "Bad Request"),
            @ApiResponse(code = 500, response = ErrorResponse.class, message = "Internal Server Error") })

    public CustomResponse uploadJava(
            @ApiParam(value = "Interface", required = true)
            @RequestPart(name = "interface", required = true) final MultipartFile interfaceClass,

            @ApiParam(value = "Java Class", required = false) 
            @RequestPart(name = "javaClass", required = false) final MultipartFile javaClass) {
        return null;
}

`

When I access the Swagger UI, couldn't fine description and example. 

I found that the following will resolve the issue:
`
@Parameter(
              description = "This is the configuration",
              content = @Content(mediaType = MediaType.APPLICATION_JSON_VALUE))
`

But it didn't.

**My question is,**

1. How to add description and example for the above. (Similar to RequestParam)
2. How to set content type for each file.

**Note:**

My current POM
`

        <dependency>

            <groupId>io.springfox</groupId>

            <artifactId>springfox-boot-starter</artifactId>

            <version>3.0.0</version>

        </dependency>
`

**Comment by bnasslahsen** [comment]
@uuk007, 

 You are creating your issue on the wrong project. Your question is not related to springdoc-openapi...
