### ISSUE TITLE
[question] convert already provided yaml files

### ISSUE THREAD

**Issue by bilak** [springdoc/springdoc-openapi#85]
Hello,
sorry for asking question here but I didn't found better place. If I understand it correctly this project is aimed to generate openapi-ui based on openapi annotations found in project. I don't use those annotations, but I'm generating models from openapi definitions (contract first). Is there way how to convert those yaml files to `openapi-ui`? 
I'm using composed structures like `commons.yaml` with common parts (errors, base dtos, ...) and then `domain.yaml` which usess definitions from `commons.yaml`.
Also if I have multiple modules would this work?

Thanks in advance.

**Comment by springdoc** [comment]
Hi, 

 You can pass your openapi json description, to swagger-ui.  You can ask your question on stackoverflow as well for more answers.
 Please have a look at the swagger-ui project and how to pass json file as parameter:
- https://github.com/swagger-api/swagger-ui
