### ISSUE TITLE
Allow for pre-loading OpenAPI

### ISSUE THREAD

**Issue by Dodecahedra** [springdoc/springdoc-openapi#850]
In our project generating Swagger for large instances can take a long time, causing a long delay for the user (30+ seconds). After upgrading from `1.4.4` to SpringDoc `1.4.6` our existing solution no longer works. We currently have a custom pre-loader that forces OpenAPI to generate swagger by making a HTTP request to SpringDoc when the application starts

Our proposal would be to allow for pre-loading swagger when starting the application, using a method call.

**Comment by bnasslahsen** [comment]
@Dodecahedra, 

 Do you have any PR to propose?

**Comment by Dodecahedra** [comment]
Not yet, I can open one if you are interested.
