### ISSUE TITLE
Don't have Authorize function

### ISSUE THREAD

**Issue by nghiapt1112** [springdoc/springdoc-openapi#851]
When i use version 1.4.6 and no further customize settings, only use default after deploy , i didn't see any thing like Authorize button as the demo version.
![image](https://user-images.githubusercontent.com/38048406/92128206-5fb6ab00-ee2c-11ea-9b61-58aa20662aab.png)

**Comment by bnasslahsen** [comment]
@nghiapt1112, 

 You can have a look at the demo applications here: https://springdoc.org/. 
 The following section: `springdoc applications demos`

 The source code of the demos, is available here:
 -  https://github.com/springdoc/springdoc-openapi-demos
