### ISSUE TITLE
Exclude Schemas from showing up on swagger-ui does not work

### ISSUE THREAD

**Issue by judos** [springdoc/springdoc-openapi#853]
**Describe the bug**
- I have dto and model classes (entities in db). I want swagger-ui to show only dto, as the entities are private to the backend implementation. Even with configuration I can't stop the entity classes from showing up under schema

**To Reproduce**
- Spring-boot: 2.3.3.RELEASE
- What modules and versions of springdoc-openapi are you using?
```
<dependency>
	<groupId>org.springdoc</groupId>
	<artifactId>springdoc-openapi-ui</artifactId>
	<version>1.4.6</version>
</dependency>
```

- What is the actual and the expected result using OpenAPI Description (yml or json)? I don't know exactly how to fetch this or what it should look like as i'm not familiar with the underlying syntax.

- Provide with a sample code (HelloController) or Test that reproduces the problem:

```
import io.swagger.v3.oas.annotations.Hidden
import javax.persistence.*
@Entity
@Hidden
open class Client {
...
}
```

application.properties:
```
springdoc.swagger-ui.operationsSorter=method
springdoc.packages-to-scan=ch.myapp.controller, ch.myapp.core.dto
springdoc.packages-to-exclude=ch.myapp.core.model
```

**Expected behavior**
- The dto classes show up, but not the entity classes (located in core.model package)

**Screenshots**
![grafik](https://user-images.githubusercontent.com/5525810/92240653-3b56df00-eebd-11ea-837f-fc64af72613c.png)

**Comment by bnasslahsen** [comment]
@judos, 

 @Hidden is more used for Controllers (resources) or operations, as you can see here:
 - https://springdoc.org/faq.html#how-can-i-hide-an-operation-or-a-controller-from-documentation-


You can have a look at the F.A.Q how to hide a parameter or a field:
 - https://springdoc.org/faq.html#how-can-i-hide-a-parameter-from-the-documentation-

**Comment by judos** [comment]
Hi @bnasslahsen 

Ok so I remove the hidden annotation but the ticket is not solved with that. As the title says: "exclude schemas from showing up on swagger-ui does not work"

The parameter annotation is apparently for parameters which makes sense, but I want the model classes to NOT show up on swagger-ui.

Does the "springdoc.packages-to-exclude" not work in this case? Is that only for controllers?

**Comment by RomanukAlex** [comment]
application.properties --> propirtespringdoc.swagger-ui.default-models-expand-depth=-1
