### ISSUE TITLE
Support creating multiple definitions based on SecurityScheme

### ISSUE THREAD

**Issue by Blackbaud-BethRichardson** [springdoc/springdoc-openapi#855]
**Is your feature request related to a problem? Please describe.**
I need to define two different OpenApi definitions for the same API within a single application: one for internal developers and one for external developers. The external definition would include some of the operations from the internal definition, but not all of them. I would like to provide a shared config for the GroupedOpenApi builder that does not rely on maintaining a separate list of paths to include or exclude in my configuration for each project and instead rely on existing OpenAPI annotations for access control to define the different swagger documents for each SecurityScheme.

**Describe the solution you'd like**
It seems like either SecurityScheme or tags could be used to define which operations are included in a given definition using GroupedOpenApi. So for example, I could define the definition for my external API with something like the following:

```java
GroupedOpenApi.builder()
            .group("externalGroupName")
            .securitySchemesToInclude("externalSchemeName") // propose to add this
            .build();
```

And then any of the operations that are tagged with a SecurityRequirement with that SecurityScheme would get added to this external definition. So for example I could have the following two endpoints defined within the same RestController:

**Would be included:**
```java
    @SecurityRequirement(name = "externalSchemeName")
    @GET
    @Path("/pets")
    public Response getResponse(){
        return null;
    }
}
```

**Would not be included:**
```java
    @SecurityRequirement(name = "internalSchemeName")
    @GET
    @Path("/pets/internal")
    public Response getInternalResponse(){
        return null;
    }
}
```

With this approach, it would be nice to provide for included and excluded security schemes similar to current support for paths/package inclusions/exclusions.

**Describe alternatives you've considered**
I have looked at using packages or paths on the GroupedOpenApi builder to create the two definitions, but this requires that I move the endpoints that should be excluded from the external definition into a separate RestController and move to an excluded package, which would not be included in the definition for the external developers, but would still be included in the internal definition. I would prefer to structure my code based on the API definition and not based on the security access for my endpoints. 

I also would prefer not to maintain a list of all the paths that should be excluded from the group in config if possible as this is error prone and doesn't allow for providing a shared config across multiple services. I would prefer an annotation-driven method similar to the way other swagger customization is done so that I define the config once and then update each resource as it is defined or modified based on an annotation to drive the swagger that is generated.

**Additional context**
I wrote up my basic idea in this stackoverflow to identify if an existing pattern would work for my use case: [stackoverflow question](https://stackoverflow.com/questions/63712552/in-springdocs-can-i-define-multiple-openapi-definitions-based-on-tags-on-the-op)

**Comment by bnasslahsen** [comment]
@Blackbaud-BethRichardson, 

 For you sample, exclusion by path looks enough.
 Anyway, you can filter groups depending on any criteria of the swagger annotations (not only the name of SecurityRequirement), by providing an `OpenApiCustomiser `to the group.

 Here is a sample code that you can adapt, for your case:

```java
@Bean
GroupedOpenApi externalGroup() {
	return GroupedOpenApi.builder()
			.group("externalGroupName")
			.pathsToMatch("/pets/*")
			.addOpenApiCustomiser(externalGroupOpenApiCustomiser())
			.build();
}

OpenApiCustomiser externalGroupOpenApiCustomiser() {
	return openApi -> openApi.getPaths().entrySet().removeIf(path -> path.getValue().readOperations().stream()
			.anyMatch(operation -> operation.getSecurity() != null && operation.getSecurity().stream().noneMatch(
					securityRequirement -> securityRequirement.get("external") != null)
			));
}

@Bean
GroupedOpenApi internalGroup() {
	return GroupedOpenApi.builder()
			.group("internalGroupName")
			.pathsToMatch("/pets/internal/*")
			.addOpenApiCustomiser(internalGroupOpenApiCustomiser())
			.build();
}


OpenApiCustomiser internalGroupOpenApiCustomiser() {
	return openApi -> openApi.getPaths().entrySet().removeIf(path -> path.getValue().readOperations().stream()
			.anyMatch(operation -> operation.getSecurity() != null && operation.getSecurity().stream().noneMatch(
					securityRequirement -> securityRequirement.get("internal") != null)
			));
}
```

**Comment by Blackbaud-BethRichardson** [comment]
Maintaining a list of paths in config will not work for me, but it looks like the OpenApiCustomiser filtering operations on security will be a good fit. Thank you!

**Comment by Blackbaud-BethRichardson** [comment]
It looks like the solution of removing paths in a OpenApiCustomiser will not remove the component schemas or any of the readOperations on that path that do not match the SecurityRequirement from the secondary swagger. So, this doesn't seem like it actually addresses the concern.

**Comment by bnasslahsen** [comment]
@Blackbaud-BethRichardson, 

 Not sure what is your concern. 
 But if you add a concrete sample code, which describes what you are getting as result and the difference between what you are expecting. we can help...

**Comment by Blackbaud-BethRichardson** [comment]
Specifically, the above solution will only remove a path if all readOperations are excluded. However, that path will still contain all the operations for all methods regardless of if each operation uses that SecurityRequirement. Additionally, all component > schemas are included in the final object regardless of what paths you remove in the customizer. It seems like a big challenge to post process all the operations under each path and all the request, responses, and linked schemas for each operation based on path after the OpenApi object has already been built rather than during pre-processing. I can build out a stripped down version of what I am seeing when I work on setting up an example for the [caching issue](#858) that I was seeing, but I think any post-processing seems less efficient than not including these operations when building the OpenApi object initially.

**Comment by bnasslahsen** [comment]
@bnasslahsen, 

 For excluding non used components/schemas, your OpenApiCustomiser should extend SpecFilter as well ...
 Anyway, as mentionned previousuly,you should add a [**concrete sample code**](https://stackoverflow.com/help/minimal-reproducible-example), which describes what you are getting as result and the difference between what you are expecting. we can help...
