### ISSUE TITLE
Cache is shared between all resources created for different GroupedOpenApi beans

### ISSUE THREAD

**Issue by Blackbaud-BethRichardson** [springdoc/springdoc-openapi#858]
**Describe the bug**
The cached OpenApi for a different group configuration will be returned when requesting a GroupedOpenApi from the MultipleOpenApiResource if a different group was built first. This is because the same cached OpenApi is used in all resources built from the MultipleOpenApiResource.

In `MultipleOpenApiResource`, the same OpenApiBuilder (`defaultOpenAPIBuilder`) is used for each OpenApiResource that is built for each GroupedOpenApi. This defaultOpenAPIBuilder has a single cached OpenApi object that is set whenever the first OpenApiResource is called for any of the groups. This results in the cached result for a previous group to be returned for subsequent calls for different groups.

In the `MultipleOpenApiResource`, in the `afterPropertiesSet` method, each OpenApiResource is built with the same defaultOpenAPIBuilder. In the `AbstractOpenApiResource`, when the `getOpenApi` method is called, the cache for that builder is retrieved, which, if already called for a different resource, will be populated with the results of that previous call, which was built with a different group configuration.

**To Reproduce**
- What version of spring-boot you are using?
2.2.4.RELEASE

- What modules and versions of springdoc-openapi are you using?
org.springdoc:springdoc-openapi-ui:1.4.5

- What is the actual and the expected result using OpenAPI Description (yml or json)?
json

- Provide with a sample code (HelloController) or Test that reproduces the problem

Define this config:
```java
@Bean
    public GroupedOpenApi externalOpenApi() {
        return GroupedOpenApi.builder()
                .group("external")
                .addOpenApiCustomiser(new ExternalCustomizer())
                .build();
    }

    @Bean
    public GroupedOpenApi internalOpenApi() {
        return GroupedOpenApi.builder()
                .group("internal")
                .addOpenApiCustomiser(new InternalCustomizer())
                .build();
    }
```

Then, the customizers look like (one for external and one for internal, where they result in two different sets of paths included):
```java
public class ExternalCustomizer implements OpenApiCustomiser {

    @Override
    public void customise(OpenAPI openApi) {
        openApi.getPaths().entrySet().removeIf(path -> path.getValue().readOperations().stream()
                .noneMatch(this::isExternal));
    }

    private boolean isExternal(Operation operation) {
        return operation.getSecurity() != null && operation.getSecurity().stream().anyMatch(
                securityRequirement -> securityRequirement.get(SecuritySchemes.EXTERNAL) != null);
    }
}
```

Then, request "GET /v3/api-docs/external" followed by "GET /v3/api-docs/internal" without restarting your application. The response for the first request matches response for second. 

Disable caching by setting `springdoc.cache.disabled=true` and perform the previous step again. Each response represents the correctly built OpenApi for the requested group.

**Expected behavior**
_Expected_: Expect that a call to "GET /v3/api-docs/external" would return those paths that match external customizer
and then call to "GET /v3/api-docs/internal" would return those paths that match internal customizer. Expect that disabling cache would not affect this result.

_Actual_: The first resource call results in a cached result being returned to the second resource call. Disabling cache fixes this problem and both return the OpenApi built for the requested group.

**Screenshots**

**Additional context**

**Comment by bnasslahsen** [comment]
@Blackbaud-BethRichardson, 

 The issue you are reporting about cache shared between Groups, is not reproducible.

 Your assumptions here are not true.


> In MultipleOpenApiResource, **the same** OpenApiBuilder (defaultOpenAPIBuilder) is used for each OpenApiResource that is built for each GroupedOpenApi. **This defaultOpenAPIBuilder has a single cached OpenApi object** that is set whenever the first OpenApiResource is called for any of the groups. This results in the cached result for a previous group to be returned for subsequent calls for different groups.
> 
> In the MultipleOpenApiResource, in the afterPropertiesSet method, each OpenApiResource **is built with the same defaultOpenAPIBuilder.** In the AbstractOpenApiResource, when the getOpenApi method is called, the cache for that builder is retrieved, which, if already called for a different resource, will be populated with the results of that previous call, which was built with a different group configuration.



  OpenApiBuilder is with scope prototype.  You can view here the related code here:
 - https://github.com/springdoc/springdoc-openapi/blob/422b8abe2709c728baa3790b151878e9353df453/springdoc-openapi-common/src/main/java/org/springdoc/core/SpringdocBeanFactoryConfigurer.java#L86

 And here the conditional beans creation:
https://github.com/springdoc/springdoc-openapi/blob/3ea72c607f987de4c282e363a0ece0108090817b/springdoc-openapi-common/src/main/java/org/springdoc/core/SpringDocConfiguration.java#L307

If you believe you are facing an issue. Please make sure you provide a minimal reproducible project, so that this ticket can be reopened.

**Comment by Blackbaud-BethRichardson** [comment]
Do you have any existing projects I can start with or do I have to create something from scratch for this?

**Comment by bnasslahsen** [comment]
@Blackbaud-BethRichardson,

 You have some demos available here:
- https://github.com/springdoc/springdoc-openapi-demos
