### ISSUE TITLE
readme.md: should the yaml endpoint not be documented as "v3/api-docs.yaml (not .yml)

### ISSUE THREAD

**Issue by man-at-home** [springdoc/springdoc-openapi#86]
See _OpenApiResource_ class (_DEFAULT_API_DOCS_URL_YAML_). 

For me at least I got the url localhost:8080/v3/api-docs.yaml after including springdoc into my project.

want to add: thanks for this nice library!

**Comment by springdoc** [comment]
Yes, you are absolutely right.
Thank you for your feedback.
