### ISSUE TITLE
springdoc-openapi-ui is not working as expected for services under zuul proxy

### ISSUE THREAD

**Issue by PraneethPathireddy** [springdoc/springdoc-openapi#860]
I have services behind zuul proxy server.
When I try to render the API documentation of a service through swagger ui, it fails to load the configuration.

I am using following spring component versions

spring-boot : 2.2.6
springdoc-openapi-ui : 1.3.4

**Expected behavior**
- When I hit the following url
    https://exampleHost.com/serviceContext/swagger-ui.html
    it should render api documentation.

**Actual behavior**
It loads page with error : Failed to load remote configuration.

**Additional context**
I tried to use following properties without success
springdoc:
    api-docs:
        path: /serviceContext/api-docs
    swagger-ui:
        configUrl: /service-context/api-docs/swaggerJsonFile

**Comment by bnasslahsen** [comment]
@PraneethPathireddy,

Please use the last stable version v1.4.6, before you raise any issue.

 There is no need to create a new ticket. 
 This one can be reppened if you are still facing an issue ansd you are providing the relevant information.
