### ISSUE TITLE
Wrong @ManyToOne relationship naming 

### ISSUE THREAD

**Issue by marcel-steinbach-mpf** [springdoc/springdoc-openapi#861]
**Describe the bug**
for relationships like `/entity/{id}/childProperty`, spring doc creates the `childProperty` name based on the type instead of the name

**To Reproduce**
https://github.com/marcel-steinbach-mpf/springdoc-data-rest

**Expected behavior**
```    
    @ManyToOne
    @JoinColumn(name = "child_property_id")
    private ChildProperty myChildPropertyName;
```

should be:
```
    "/properties/{id}/myChildPropertyName": {
```

but is:
```
    "/properties/{id}/childProperty": {
```

**Additional context**
related to https://github.com/springdoc/springdoc-openapi/issues/792

**Comment by bnasslahsen** [comment]
@marcel-steinbach-mpf, 

 A fix is now added to master. And should be available with the next release.
You can validate it using the last snapshot.

**Comment by marcel-steinbach-mpf** [comment]
Awesome! Thanks!!
