### ISSUE TITLE
No operations defined in spec!

### ISSUE THREAD

**Issue by mikt** [springdoc/springdoc-openapi#862]
Hi,
So I attempted to follow the getting started guide, and get inspiration from the sample projects, however for some reason my endpoint or models are not visible on the swagger UI, instead I'm faced with "No operations defined in spec!"

I would appreciate any tips to what I've might have missed :)

My controller/interface:
```java
@Tag(name = "Test", description = "Just a test endpoint")
@RequestMapping(value = DEFAULT_PATH, produces = APPLICATION_JSON_VALUE)
@RestController
public interface TestEndpoint {
    String DEFAULT_PATH = "/test";

    String ID = "/{test-id}";

    @Operation(
            description = "Get test by test-id",
            summary = "Get test summary"
    )
    @ResponseStatus(code = HttpStatus.OK)
    @ApiResponses({
            @ApiResponse(
                    responseCode = HttpURLConnection.HTTP_OK + "",
                    description = "The request succeeded.",
                    content = @Content(schema = @Schema(implementation = TestModel.class))
            )
    })
    @GetMapping(value = ID)
    TestModel getAgreement(@Parameter(description = "Id of the test", required = true) @PathVariable("test-id") Long testId);
}
```

Application properties:
```
server.port=8090
application-description=@project.description@
application-version=@project.version@
springdoc.packages-to-scan=*
springdoc.paths-to-match=/*
```

My application runner
```java
@SpringBootApplication
public class AuthApplication {

    @Bean
    public OpenAPI springShopOpenAPI(@Value("${application-version}") String appVersion) {
        return new OpenAPI()
                .info(new Info().title("HoN Core Auth API")
                        .description("Authentication & authorization API")
                        .version(appVersion)
                        .license(new License().name("(C) HoN")));
    }

//    @Bean
//    public GroupedOpenApi publicApi() {
//        String[] paths = {TestEndpoint.DEFAULT_PATH.concat("/**")};
//        return GroupedOpenApi.builder()
//                .group("public")
//                .pathsToMatch(paths)
//                .build();
//    }

    public static void main(String[] args) {
        SpringApplication.run(AuthApplication.class, args);
    }

}
```

My model:
```java
@Schema(description = "This model represents a test result")
@JsonNaming(PropertyNamingStrategy.SnakeCaseStrategy.class)
@Builder
@Data
public class TestModel {
    @Schema(description = "Test description", example = "First test case")
    String description;

    @Schema(description = "Test id", example = "1", required = true)
    @NotNull
    Long id;

    @Schema(description = "Was the test a success", example = "true", required = true)
    @NotNull
    Boolean isSuccess;
}
```

**Comment by bnasslahsen** [comment]
@mikt,

 Where is the implementation of your interface TestEndpoint?

**Comment by mikt** [comment]
@bnasslahsen I didn't make an implementation yet, this was just supposed to be my contract.

**Comment by bnasslahsen** [comment]
@mikt, 

 This can be contract, but an interface is not going to generate a spring controller.
 If the controller does not effectively exist, springdoc-openapi will not detect it.

 You need to add the implementation class even it's not yet complete...
 You can have a look at the project tests for samples.

**Comment by mikt** [comment]
Hi, so I added a small implementation, but it's still not showing anything for me:

```java
@RestController
public class TestResource implements TestEndpoint {
    @Override
    public TestModel getTest(Long testId) {
        return TestModel
                .builder()
                .description("Test case " + testId)
                .id(testId)
                .isSuccess(true)
                .build();
    }
}
```

**Comment by bnasslahsen** [comment]
@mikt, 

 Did you have a look at the repo demos ?
 I am sure which documentation you are getting from this configuration :

```properties
springdoc.packages-to-scan=*
springdoc.paths-to-match=/*
```

 Remove these two settings, which seems useless.
 
If you are still facing the same issue, then attach your project or add the link to your github and we will have a look at it.

**Comment by dafuemu** [comment]
Hi! I am having same issue. Because i was expecting to have the swagger ui generated by having all the annotation on the interface, not the implementation.
https://springdoc.org/#does-this-library-supports-annotations-from-interfaces
Did i misunderstand the info on that link?? 
Thanks

**Comment by geld0r** [comment]
I am having the same issue. Did anyone find a solution or workaround?
I don't want to move all the annotations to the implementation as I find that separation way cleaner...

**Comment by shopizer-ecommerce** [comment]
same issue

**Comment by bnasslahsen** [comment]
@shopizer-ecommerce, 

  Your comment is not useful, without providing any Reproducible Example.
  Make sure you [Provide the link to a Minimal, Reproducible Example - with HelloController ](https://stackoverflow.com/help/minimal-reproducible-example)that reproduces the problem.

**Comment by jerryleooo** [comment]
Hi @bnasslahsen 
I have the same issue, the version I am using is 1.6.6. I am not using yml file to configure, and instead there is only a simple `@Configuration`:

```java
@Configuration
public class DocsConfig
{
    @Bean
    public GroupedOpenApi api()
    {
        return GroupedOpenApi.builder()
                .group("xxx")
                .packagesToScan("xxx")
                .build();
    }

```

at `/v3/api-docs`, I can see the paths I defined inside the controller are listed. So I guess somewhat the configure works.

but on `swagger-ui/index.html`, "No operations defined in spec!" is displayed.

**Comment by bnasslahsen** [comment]
@jerryleooo,
Make sure you [Provide the link to a Minimal, Reproducible Example - with HelloController ](https://stackoverflow.com/help/minimal-reproducible-example)that reproduces the problem.

**Comment by jerryleooo** [comment]
Hi @bnasslahsen the MVP you asked is [here](https://github.com/jerryleooo/OpenApiDemo), hope it helps, thanks.

**Comment by bnasslahsen** [comment]
@jerryleooo, 

Your config is wrong.
You are inverting the `group` and the `package`.

This is the correct configuration.

```java
  @Bean
  public GroupedOpenApi api()
  {
      return GroupedOpenApi.builder()
              .group("OpenApiController")
              .packagesToScan("com.example")
              .build();
  }
```

**Comment by jerryleooo** [comment]
Thanks @bnasslahsen , it's fixed, for similar issues can refer to https://github.com/jerryleooo/OpenApiDemo/commit/8821e78e8942cb5d094578fc38fd210353c5ba90

**Comment by TohidMakari** [comment]
Hi @bnasslahsen ,
For it works well in our dev environment , but  deploying  in another Environment(production) with the same config dose not work, can you guide me?

```
springdoc:
  swagger-ui.path: swagger-ui
  api-docs.path: /${spring.application.name}
  paths-to-match: /api/**
```
