### ISSUE TITLE
SpringDoc does not scan library @Controller

### ISSUE THREAD

**Issue by efitapia** [springdoc/springdoc-openapi#865]
**Versions:**
- Spring Boot: 2.3.1.RELEASE
- SpringDoc: 1.4.6

All springdoc properties are defaults!

**The Problem**
I have a library that provides me with a statuscheck endpoint:
```
@Controller
public class StatusInfoController
```
Configuration (also in the library):
```
@Configuration
public class StatusInfoConfiguration {

    @Bean
    public StatusInfoController statusController() {
        return new StatusInfoController();
    }
}
```
And in my app:
```
@SpringBootApplication
@Import(StatusInfoConfiguration.class)
public class MyApplication
```
I've checked this status endpoint via curl, but still SpringDoc cannot find this controller:
![image](https://user-images.githubusercontent.com/20131027/93084050-2982f200-f69c-11ea-85bb-0f75f05d1140.png)
![image](https://user-images.githubusercontent.com/20131027/93084137-46b7c080-f69c-11ea-825c-d9cca54d00ee.png)

**Comment by bnasslahsen** [comment]
@efitapia, 

 Please have a look at the F.A.Q:
 - https://springdoc.org/faq.html#my-rest-controller-using-controller-annotation-is-ignored
