### ISSUE TITLE
Parameter annotation doesn't take defaultValue attribute

### ISSUE THREAD

**Issue by satyavemuri** [springdoc/springdoc-openapi#868]
**Describe the bug**
- io.swagger.v3.oas.annotations.Parameter doesn't have defaultValue attribute which is required in our case because we have default value available for one of our query parameters and also we were migrating from  io.springfox for swagger2.0 and which was supporting it.
- May I know, is there any reason for not having it?

Version:   'org.springdoc:springdoc-openapi-ui:1.4.6'

![image](https://user-images.githubusercontent.com/11781556/93296698-9681af00-f7a4-11ea-80fd-1843fc3da27f.png)

**Comment by ricardo-t-morgado** [comment]
I believe the defaultValue is part of the "@Schema" and not the "@Parameter".

See the example below (from [this sample project](https://github.com/ricardo-t-morgado/springdoc-inconsistency-example/blob/master/src/main/java/com/springdoc/inconsistencysample/model/UseCase1.java)):
```
    @Schema(description = "Test enum object", defaultValue = "TestEnum.C")
    @NotNull
    @JsonProperty("testEnum")
    private TestEnum testEnum = TestEnum.C;
```

**Comment by bnasslahsen** [comment]
@satyavemuri,  

 The class `io.swagger.v3.oas.annotations.Parameter` is not a springdoc-openapi class.
 Please raison your question on the [swagger  github](https://github.com/swagger-api/swagger-core/issues) instead.

**Comment by satyavemuri** [comment]
Hi @bnasslahsen,

Thanks for the response, I will raise the issue in Swagger Github.

**Comment by tgolob** [comment]
for convenience: https://github.com/swagger-api/swagger-core/issues/4174
