### ISSUE TITLE
ExternalDocumentation does not show anymore the doc's url in 1.4.6

### ISSUE THREAD

**Issue by mcamelot** [springdoc/springdoc-openapi#871]
**Describe the bug**
- ExternalDocumentation is no more shown in swagger-ui

**To Reproduce**
- Migrating from 1.3.4 version to the version 1.4.6 via gradle in springboot project
```
    implementation group: 'org.springdoc', name: 'springdoc-openapi-ui', version: '1.4.6'
    implementation group: 'org.springdoc', name: 'springdoc-openapi-security', version: '1.4.6'
```
- Using @ExternalDocumentation 
```
@Tag(name = "foos", description = "Manages foo",
        externalDocs = @ExternalDocumentation(description = "exigences", url = "https://docs/foos"))
public interface foos {
...
}
```

**Expected behavior**
- The doc's url must appears on the endpoint description

**Screenshots**
Before migration
![image](https://user-images.githubusercontent.com/7313840/93599671-cc01e480-f9be-11ea-9e2e-d86e3a3926b9.png)

After migration
![image](https://user-images.githubusercontent.com/7313840/93599534-8d6c2a00-f9be-11ea-8489-1f309bc37f18.png)

**Additional context**
- migrating from 1.3.4 to 1.4.6
- the swagger.json is correct : http://localhost:8080/v3/api-docs

```
tags": [
    {
      "name": "Foos",
      "description": "Manages Foos",
      "externalDocs": {
        "description": "exigences",
        "url": "https://docs/foos"
      }
    }
]
```

**Comment by bnasslahsen** [comment]
@mcamelot, 

 The Generated OpenAPI documentation is correct and contains the url: 
- This is a swagger-ui issue, related to version 3.32.5.

 The following dependencies declaration, should temporareely fix the ExternalDocumentation issue:
```xml
<dependency>
	<groupId>org.springdoc</groupId>
	<artifactId>springdoc-openapi-ui</artifactId>
	<exclusions>
		<exclusion>
			<groupId>org.webjars</groupId>
			<artifactId>swagger-ui</artifactId>
		</exclusion>
	</exclusions>
	<version>1.4.6</version>
</dependency>
<dependency>
	<groupId>org.webjars</groupId>
	<artifactId>swagger-ui</artifactId>
	<version>3.32.3</version>
</dependency>
```

 I will let you know if released yesterday 3.34.0, fixes this issue. 
 If it's not the case, you will have to create an issue on the swagger-ui project instead.

**Comment by bnasslahsen** [comment]
@mcamelot, 

 We just tested with version  3.34.0 and it doesn't resolve this issue.
 Please raise a ticket on the [swagger-ui](https://github.com/swagger-api/swagger-ui) github project instead. 
 Meanwhile, you can combine v3.32.3 of `swagger-ui`  with the latest `springdoc-opernapi` version as a workaround. (As described on my previous comment)

**Comment by mcamelot** [comment]
Hi, 

i've tested your solution with exclusion and it works thanks.
thanks for testing the 3.34.0.

I'll open an issue ont the swagger-ui project

thanks a lot

**Comment by planetf1** [comment]
Raised https://github.com/swagger-api/swagger-ui/issues/7305 to see if there's anything that could be done in the default layout engine.

The alternative is we look at removing the external link, or implementing our own formatted.

See https://swagger.io/docs/open-source-tools/swagger-ui/customization/custom-layout/
