### ISSUE TITLE
Javascript error occurs when I set springdoc.swagger-ui.csrf.enabled=true 

### ISSUE THREAD

**Issue by video-vocabulary** [springdoc/springdoc-openapi#872]
**Describe the bug**
Javascript error occurs when I set `springdoc.swagger-ui.csrf.enabled=true` and try to send any request from `swagger-ui.html`: 

TypeError: Cannot set property 'X-XSRF-TOKEN' of undefined at requestInterceptor (index.html?configUrl=/v3/api-docs/swagger-config:50)
<img width="637" alt="Screen Shot 2020-09-21 at 12 07 25 AM" src="https://user-images.githubusercontent.com/10354348/93718578-1772e900-fb9f-11ea-81f1-9bf0411fe9f2.png">

So I debugged line 50 of `index.html` and found that `headers` object is indeed undefined:
<img width="457" alt="Screen Shot 2020-09-21 at 12 28 04 AM" src="https://user-images.githubusercontent.com/10354348/93719009-a41ea680-fba1-11ea-82f7-15fcc9753c94.png">

According to [swagger-ui documentation](https://github.com/swagger-api/swagger-ui/blob/master/docs/usage/configuration.md#network) isn't `requestInterceptor` function accepts one argument requestInterceptor(request) and headers should be set to this object rather than function itself?
For example:
```javascript
window.onload = function() {
  const ui = SwaggerUIBundle({
    requestInterceptor: (request) => {
      const value = `; ${document.cookie}`;
      const parts = value.split(`; XSRF-TOKEN=`);
      console.log(parts);
      if (parts.length === 2) {
        request.headers['X-XSRF-TOKEN'] = parts.pop().split(';').shift();
      }
      return request;
    }
}
```

**To Reproduce**
- What version of spring-boot you are using - v2.3.4.RELEASE
- What modules and versions of springdoc-openapi are you using?
```Groovy
dependencies {
	implementation 'org.springdoc:springdoc-openapi-ui:1.4.6'
}
```
- Provide with a sample code (HelloController) or Test that reproduces the problem
```Java
@RestController
@RequestMapping("/tvshow")
public class TvshowController {

    @GetMapping
    String findAll() {
        return "test";
    }
}
```
- Spring Security Configuration
```Java
@Configuration
@EnableWebSecurity
public class WebSecurityConfig extends WebSecurityConfigurerAdapter {

    @Override
    protected void configure(HttpSecurity http) throws Exception {
        http
                .csrf().csrfTokenRepository(CookieCsrfTokenRepository.withHttpOnlyFalse())
                .and()
                .authorizeRequests().antMatchers("/").permitAll();
    }
}
```

**Additional context**
Have tested on the following browsers, error occurs on all of them:
Google Chrome Version 85.0.4183.102 (Official Build) (64-bit)
Safari Version 14.0 (15610.1.28.1.9, 15610)

**Comment by bnasslahsen** [comment]
@video-vocabulary, 

 There seem to be some errors on requestInterceptor with the latest swagger-ui versions.
 Here is a first workaround:

```xml
<dependency>
	<groupId>org.springdoc</groupId>
	<artifactId>springdoc-openapi-ui</artifactId>
	<exclusions>
		<exclusion>
			<groupId>org.webjars</groupId>
			<artifactId>swagger-ui</artifactId>
		</exclusion>
	</exclusions>
	<version>1.4.6</version>
</dependency>
<dependency>
	<groupId>org.webjars</groupId>
	<artifactId>swagger-ui</artifactId>
	<version>3.31.1</version>
</dependency>
```
