### ISSUE TITLE
Syntax highlighting in Swagger-ui can't be configured in Springdoc

### ISSUE THREAD

**Issue by ErwanLeroux** [springdoc/springdoc-openapi#877]
The syntax highlighting feature added in [swagger-ui v3.30.0](https://github.com/swagger-api/swagger-ui/releases/tag/v3.30.0) can't configured in springDoc and it's preventing me from disabling it. I want to disable it because it's causing performance issue on large json response

**To Reproduce**
I'm using the following versions :
- spring-boot : 2.3.3.RELEASE
- springdoc-openapi-ui:1.4.7
- springdoc-openapi-security:1.4.7"

**Expected behavior**
I'm expecting to be able to deactivate the syntax highlighting

**Screenshots**
![With_highlight](https://user-images.githubusercontent.com/1643338/94010139-d26cd380-fda5-11ea-9930-fb7cb30620b8.png)
![Without_highlighting](https://user-images.githubusercontent.com/1643338/94010150-d6005a80-fda5-11ea-9727-3236a5614d21.png)

**Additional context**
You can see the difference in the screenshots I provided.
The parameters are [here](https://github.com/swagger-api/swagger-ui/blob/master/docs/usage/configuration.md#user-content-syntaxhighlight) in swagger-ui but i couldn't find where they are used in springdoc

**Comment by bnasslahsen** [comment]
@ErwanLeroux, 

 This will be available for the next  release:
 To disable Syntax use the following property:

```properties
springdoc.swagger-ui.syntaxHighlight.activated=false
```

Property to change the theme will be also available:

```properties
springdoc.swagger-ui.syntaxHighlight.theme=monokai
```

**Comment by ErwanLeroux** [comment]
I just tested it, it work like a charm with
```ini
springdoc.swagger-ui.syntaxHighlight.activated=false
```
