### ISSUE TITLE
SpringDoc OpenAPI Reverse Proxy Issue For Static Content (SWAGGER-UI)

### ISSUE THREAD

**Issue by DebajitKumarPhukan** [springdoc/springdoc-openapi#880]
**Problem Statement:**
When accessing the app directly without going through a proxy localhost:8080/swagger-ui.html the static resources are resolved, i.e. localhost:8080/swagger-ui/swagger-ui-bundle.js.

However when accessing via the reverse proxy localhost:8081/app-context/swagger-ui.html the static resources are returning a 404 because the path is missing /swagger-ui/ ie localhost:8081/app-context/swagger-ui-bundle.js

**Things Tried:**
`X-Forwarded-Prefix "/app-context"`
and
`server.forward-headers-strategy=framework`

```
@Bean
ForwardedHeaderFilter forwardedHeaderFilter() {
   return new ForwardedHeaderFilter();
}
```

**Dependencies:**
1. SpringBoot:
```
<parent>
<groupId>org.springframework.boot</groupId>
<artifactId>spring-boot-starter-parent</artifactId>
<version>2.3.3.RELEASE</version>
<relativePath />
</parent>
```
2. SpringDoc Open API :
```
<dependency>
<groupId>org.springdoc</groupId>
<artifactId>springdoc-openapi-ui</artifactId>
<version>1.4.7</version>
</dependency>
```
3. Spring Cloud Gateway MVC
```
<dependency>
<groupId>org.springframework.cloud</groupId>
<artifactId>spring-cloud-gateway-mvc</artifactId>
<version>2.2.5.RELEASE</version>
</dependency>
```
**Additional Notes:**
1. localhost:8081/app-context/ -> is a reverse proxy created by spring cloud gateway mvc
2. localhost:8080/ -> the host where the application is actually hosted
3. Header `X-Forwarded-Prefix "/app-context"` was set using ProxyExchange.header() [in Spring Cloud Gateway MVC]

**Comment by bnasslahsen** [comment]
@DebajitKumarPhukan,

 Please have a look at the documentation, on how to configuration reverse proxy:
 - https://springdoc.org/faq.html#how-can-i-deploy-springdoc-openapi-ui-behind-a-reverse-proxy

 For the usage with spring-cloud-gateway

You can have a look at a sample here:
 - https://github.com/springdoc/springdoc-openapi-demos/tree/master/sample-springdoc-openapi-microservices

If you are still facing any issue, please add a minimal reproducible sample, so we can have a look at more details.

**Comment by DebajitKumarPhukan** [comment]
> 
> 
> @DebajitKumarPhukan,
> 
> Please have a look at the documentation, on how to configuration reverse proxy:
> 
>     * https://springdoc.org/faq.html#how-can-i-deploy-springdoc-openapi-ui-behind-a-reverse-proxy
> 
> 
> For the usage with spring-cloud-gateway
> 
> You can have a look at a sample here:
> 
>     * https://github.com/springdoc/springdoc-openapi-demos/tree/master/sample-springdoc-openapi-microservices
> 
> 
> If you are still facing any issue, please add a minimal reproducible sample, so we can have a look at more details.

**Comment by DebajitKumarPhukan** [comment]
@bnasslahsen Do you have any samples with reverse proxy examples ?. Correct me if I am wrong but the sample repository which you provided contains very basic level of Open API implementation.

**Comment by DebajitKumarPhukan** [comment]
Can this issue be reopened ?. I think the issues are being closed even without evaluation and no amount of time is being spent. I created one more ticket because I am unable to reopen this ticket.

**Comment by bnasslahsen** [comment]
@DebajitKumarPhukan, 

 If you are reporting a bug, please help to speed up problem diagnosis by providing as much information as possible: This is not the case, if you start creating many tickets ...
 
 As mentionned on the previous comment of the duplicate ticket, please make sure you respect the [contribution guide ](https://github.com/springdoc/springdoc-openapi/blob/master/CONTRIBUTING.adoc)when you create any ticket.

 If you need this ticket to be reopened, make sure you add a [minimal reproducible sample](https://stackoverflow.com/help/minimal-reproducible-example), this ticket can be then reopened.

**Comment by DebajitKumarPhukan** [comment]
@bnasslahsen closing a ticket is fine. But why are you changing the title to something different ?. I didn't upload any sample project because I saw the developers instantly understanding what the reporter says. But I will do it soon. I even saw the same issue which you closed. The only difference is that i am using spring cloud gateway and the reporter in the below issue is using Zuul. I think some effort has to be put by the developer to resolve this issue instead of just blindly closing out the issues without doing any introspection. I am also a developer and if I spend time to create sample projects when will i do my actual development. Issues are created which help the community to refine their products. If you keep closing the tickets without putting any efforts to figure out or reproduce the issue yourself, how do you expect to refine the product ?.

https://github.com/springdoc/springdoc-openapi/issues/860

**Comment by bnasslahsen** [comment]
@DebajitKumarPhukan,

 You are not respecting the contribution guidelines and rules for creating issues.
 Additionnally the [code of conduct](https://github.com/springdoc/springdoc-openapi/blob/master/CODE_OF_CONDUCT.adoc) is not respected.
