### ISSUE TITLE
Support requests/responses in the JSON:API format for Spring HATEOAS

### ISSUE THREAD

**Issue by metacubed** [springdoc/springdoc-openapi#881]
Spring HATEOAS allows the registration of custom media types and serializers for various hypermedia formats. It produces the HAL format by default.

Another popular hypermedia format is [JSON:API](https://jsonapi.org). It is provided by the [`spring-hateoas-jsonapi`](https://github.com/toedter/spring-hateoas-jsonapi) library. When this dependency is included in a Spring HATEOAS application, it produces `application/vnd.api+json` responses instead of `application/hal+json` responses.

However, SpringDoc still produces documentation for the HAL format. This is a mismatch from the actual response json.

Please provide a library to support the JSON:API HATEOAS format in addition to HAL.

**Comment by bnasslahsen** [comment]
@metacubed, 

 We only support spring-hateoas project that is maintained by the spring team. 
 Please feel free to contribute and propose this support.

**Comment by toedter** [comment]
I am the author of [spring-hateoas-jsonapi](https://github.com/toedter/spring-hateoas-jsonapi). I'll take a look at it when I find the time.  Are there any examples available for other media types? BTW, Spring HATEOAS supports UBER, HAL-FORMS; COLLECTION+JSON, and other media types out of the box.

**Comment by metacubed** [comment]
Thanks @toedter. In case you haven't seen these already, JSON:API has some examples here:
https://jsonapi.org/examples/

**Comment by toedter** [comment]
@metacubed, I meant examples for springdoc extensions other than Spring HATEOAS or Spring Data REST :).
