### ISSUE TITLE
Example for requestBody

### ISSUE THREAD

**Issue by ldebello** [springdoc/springdoc-openapi#882]
**Describe the bug**
It seems it is not possible to define an example for RequestBody annotation however it seems possible to do that in OpenAPI.

**To Reproduce**

springboot version: 2.3.4.RELEASE
springdoc-openapi version: 1.4.7
swagger-annotations version: 2.1.4

Controller Method:

@Operation(summary = "Register Operation")
    @RequestMapping(method = RequestMethod.POST)
    public ResponseEntity register(
            @PathVariable("customerId") @Parameter(description = "Customer Id") String orgId,
            @Valid @RequestBody RegistrationRequest registrationRequest) {
}

**Expected behavior**
The previous code generates (YAML Output)

```
requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RegistrationRequest'
        required: true
```

I would like to be able to define

@Operation(requestBody = @RequestBody(example ="{my_example_here}")) // Ideally support inline example or url.

**Additional context**
I would like to validate if this is possible in other way because I am new to the library if this is no possible but you consider useful and can dig into the code and create a PR for this. 

Sorry for using a github issue but I was not able to find gitter or slack to ask this. I was checking stack-overflow but I didn't find the answer.

**Comment by ldebello** [comment]
One additional comment I was able to provide one example using the Schema annotation, but that define the example a schema level and it is just one schema.

Also in order to support examples I am assuming there should be a change in the RequestBody annotation which I think belongs to swagger itself not sure if there a chance to extend that annotation

**Comment by bnasslahsen** [comment]
@ldebello, 

 You have many ways to add examples:
 - examples objects array on the Content level
 - example attribute of Schema

 If all these are not enough or you want additional feature, please raise your request on the[ swagger-core ](https://github.com/swagger-api/swagger-core/issues)project instead, as the `@RequestBody `annotation, is not a springdoc-opanpi one.
