### ISSUE TITLE
SpringDoc OpenAPI Reverse Proxy Issue - springfox-boot-starter Works Fine In Same Situation

### ISSUE THREAD

**Issue by DebajitKumarPhukan** [springdoc/springdoc-openapi#888]
### Problem Statement:
When accessing the app directly without going through a proxy localhost:8080/swagger-ui.html the static resources are resolved, i.e. localhost:8080/swagger-ui/swagger-ui-bundle.js.

However when accessing via the reverse proxy localhost:8081/app-context/swagger-ui.html the static resources are returning a 404 because the path is missing /swagger-ui/ ie localhost:8081/app-context/swagger-ui-bundle.js

### Things I Tried Already:

**Docs:**
https://springdoc.org/faq.html#how-can-i-deploy-springdoc-openapi-ui-behind-a-reverse-proxy
https://github.com/springdoc/springdoc-openapi-demos/tree/master/sample-springdoc-openapi-microservices

`X-Forwarded-Prefix "/app-context"`
and
`server.forward-headers-strategy=framework`

```
@Bean
ForwardedHeaderFilter forwardedHeaderFilter() {
   return new ForwardedHeaderFilter();
}
```

### Dependencies:
**SpringBoot**

```
<parent>
<groupId>org.springframework.boot</groupId>
<artifactId>spring-boot-starter-parent</artifactId>
<version>2.3.3.RELEASE</version>
<relativePath />
</parent>

```
**SpringDoc Open API**

```
<dependency>
<groupId>org.springdoc</groupId>
<artifactId>springdoc-openapi-ui</artifactId>
<version>1.4.7</version>
</dependency>

```
**Spring Cloud Gateway MVC**

```
<dependency>
<groupId>org.springframework.cloud</groupId>
<artifactId>spring-cloud-gateway-mvc</artifactId>
<version>2.2.5.RELEASE</version>
</dependency>

```
### Additional Notes:

    localhost:8081/app-context/ -> is a reverse proxy created by spring cloud gateway mvc
    localhost:8080/ -> the host where the application is actually hosted
    Header X-Forwarded-Prefix "/app-context" was set using ProxyExchange.header() [in Spring Cloud Gateway MVC]

### Suspect:
I think the problem is in the redirection that happens when a client hits "/swagger-ui.html" which redirects to "swagger-ui/index.html?configUrl=/v3/api-docs/swagger-config". Now if you closely inspect the configUrl param, if the <app-context> is missing as shown below, then the redirection would be wrong.

swagger-ui/index.html?configUrl=**_/app-context_**/v3/api-docs/swagger-config

Surprisingly, the below dependency (alternate of spring doc open api) works fine even if behind a reverse proxy. They have changed their path from "swagger-ui.html" to _"swagger-ui/index.html"_. May be they have already identified the issue, worked on it and resolved it already

```
<dependency>
	<groupId>io.springfox</groupId>
	<artifactId>springfox-boot-starter</artifactId>
	<version>3.0.0</version>
</dependency>
```

This is a snippet from their code:

```
@Override
  public void addViewControllers(ViewControllerRegistry registry) {
    registry.addViewController(baseUrl + "/swagger-ui/")
        .setViewName("forward:" + baseUrl + "/swagger-ui/index.html");
}
```

**Comment by bnasslahsen** [comment]
@DebajitKumarPhukan, 

 There is no need you create duplicate tickets.
 If you suspect any issue, you can add the relevant information on the original ticket: #880 and it can be reopened.

 You should add a [minimal reproducible sample](https://stackoverflow.com/help/minimal-reproducible-example) if you supsect any issue;

 This ticket will be deleted as its just a duplicate...
