### ISSUE TITLE
How to change the "generated Servers" dropdown values

### ISSUE THREAD

**Issue by Azyl** [springdoc/springdoc-openapi#89]
Hello,

I am having an issue as due to our environment only https calls are permitted. A proxy is handling the conversion from https to http

As the springboot project is deployed as http the generated swagger-ui points all URLs to http although it is accessed through https.

I have tried to add a new server to the OpenApi Bean in order define a HTTPS version but to no avail.

Could you please let me know how can I change the basePath so that we are using HTTPS

![image](https://user-images.githubusercontent.com/796994/65285576-8f9a6f00-db45-11e9-84e5-fb23961a3967.png)

Thank you for the help

**Comment by springdoc** [comment]
Hi, 

 You have different ways for setting serverUrl:  For example:

- You can set them on the OpenAPI definition Bean
```java
@Bean
public OpenAPI customOpenAPI() {
	return new OpenAPI().addServersItem(new Server().url("https://myserver.com"))
			.components(new Components().addSecuritySchemes("basicScheme",
					new SecurityScheme().type(SecurityScheme.Type.HTTP).scheme("basic")))
			.info(new Info().title("SpringShop API").version("V0")
					.license(new License().name("Apache 2.0").url("http://springdoc.org")));
}
```

- You can use the @OpenAPIDefinition swagger annotation

```java
@OpenAPIDefinition(servers = { @Server(url = "https://myserver1.com"),
		@Server(url = "https://myserver2.com") }, info = @Info(title = "the title", version = "v1", description = "My API", license = @License(name = "Apache 2.0", url = "http://foo.bar"), contact = @Contact(url = "http://gigantic-server.com", name = "Fred", email = "Fred@gigagantic-server.com")))
```

**Comment by Azyl** [comment]
Hi,

Thank you for taking the time to educate others.

I have tried the first approach before writing here and it does not work, the servers values do not appear to be used. I have even used the code snippet you provided above.

The end result is the same:

<img width="1388" alt="image" src="https://user-images.githubusercontent.com/796994/65372979-a513b400-dc7f-11e9-86d9-96d418304987.png">

The second option with the annotations is working:

<img width="1388" alt="image" src="https://user-images.githubusercontent.com/796994/65372999-0f2c5900-dc80-11e9-89a3-844963290a20.png">

So perhaps there is something here, perhaps a Bug.

If needed I can try to recreate and submit a test project for you.

Thank you and have a nice weekend.

**Comment by springdoc** [comment]
Hi,

 Overriding OpenAPI Bean Definition should also work. 
 Can you please add/upload an example, of the code that is not working ?

**Comment by Azyl** [comment]
Hi,

I uploaded it to github at https://github.com/Azyl/springdocserverlistfrombeanissue.git

Let me know if the format is ok.

It is just the starter springboot project with springdoc and a configuration class with the OpenApi bean.

the result is:

<img width="1388" alt="image" src="https://user-images.githubusercontent.com/796994/65376866-ee7af800-dcad-11e9-80e7-d180367a596d.png">


Thanks for the help

**Comment by springdoc** [comment]
Hi, 

 On your class OpenApiSwaggerConfig, just remove @OpenAPIDefinition annotation, and it should work, also while overriding OpenAPI Bean Definition :

```Java
@Configuration
public class OpenApiSwaggerConfig 
```

**Comment by kaus02** [comment]
How is the url generated in case the application is behind the reverse proxy? it does not takes into account the prefix path set by the proxy.

**Comment by bnasslahsen** [comment]
> How is the url generated in case the application is behind the reverse proxy? it does not takes into account the prefix path set by the proxy.

Read the [documentation](https://springdoc.org/index.html#how-can-i-deploy-springdoc-openapi-ui-behind-a-reverse-proxy).
