### ISSUE TITLE
CSRF support not working or not clear

### ISSUE THREAD

**Issue by michaldo** [springdoc/springdoc-openapi#892]
**Describe the bug**
springdoc.swagger-ui.csrf.enabled: true

Does not works as expected - expect pair header/will be added each request

**To Reproduce**
1. I clone https://github.com/springdoc/springdoc-openapi-demos.git (commit 27813aff7e436ca2f48f6dbe40e9f238e21eda9a)
2. I put `springdoc.swagger-ui.csrf.enabled: true` to `springdoc-openapi-spring-boot-2-webmvc/src/main/resources/application.yml`
3. I run [`springdoc-openapi-spring-boot-2-webmvc/src/main/java/org/springdoc/demo/app2/Application.java`]
4. I open springdoc-ui on localhost:8080 and I call http://localhost:8080/swagger-ui/index.html?configUrl=/v3/api-docs/swagger-config#/user/updateUser

- What version of spring-boot you are using? 2.3.4.RELEASE

**Expected behavior**
I expect that with springdoc.swagger-ui.csrf.enabled: true every request to endpoint will be enhanced with cookie XSRF-TOKEN and header X-XSRF-TOKEN with the same token. The screenshot shows that no header is sent. Cookies are empty

**Screenshots**
(url
![no-csrf-header](https://user-images.githubusercontent.com/4304236/95263978-e9dc9f80-082e-11eb-99e5-10d38adddbfd.png)
)

**Comment by bnasslahsen** [comment]
@michaldo, 

 On the project you have mentionned, there is no csrf protection. Then adding paramter `springdoc.swagger-ui.csrf.enabled` is useless.
 For example, you can use spring-security and enable csrf support: This is a sample project for that:
 -https://github.com/Stjerndal/springdoc-csrf

 And then you make sure you use the last stable version of springdoc-openapi: v1.4.8.
