### ISSUE TITLE
Does this library springdoc-openapi-ui 1.3.8 support only Spring boot project?

### ISSUE THREAD

**Issue by ManjunathBiradar** [springdoc/springdoc-openapi#895]
How to configure this library to work with spring web mvc project which is not based on spring boot project?

**Comment by bnasslahsen** [comment]
@ManjunathBiradar, 

 You can red the F.A.Q: Where your question is already answered.
Make sure you use the last stable version as well v1.4.8 (and not 1.3.8 as mentionned in your title.) 
 -https://springdoc.org/faq.html#how-to-integrate-open-api-3-with-spring-project-not-spring-boot
