### ISSUE TITLE
Is it possible to serve a "static" openapi.yaml instead of using auto generated one?

### ISSUE THREAD

**Issue by northernbird** [springdoc/springdoc-openapi#897]
**Is your feature request related to a problem? Please describe.**
My spring API has to serve a huge and complex response structure. So we decided not to create a rest api controller and add corresponding annotations manually, instead of doing that, created a swagger spec file as a yaml and let [openapi-generator-maven-plugin](https://github.com/OpenAPITools/openapi-generator/tree/master/modules/openapi-generator-maven-plugin) create pojos automatically.
In that case, we still want to serve swagger ui + this spec like what we can do with annotated controllers.
I'm trying to debug code but can't find the workaround so far 😞

**What I tried**
1. Created a static resource URL for my swagger spec (e.g. created `static` directory in `main/resources`.
2. Associate to `springdoc.api-docs.path` to use the yaml spec data in `application.properties` (like `springdoc.api-docs.path=/my-spec.yaml`)
It didn't work as the endpoins seems to be overridden by `org.springdoc.webmvc.api.OpenApiResource` controller and swagger ui still uses the generated one (not mine)
https://github.com/springdoc/springdoc-openapi/blob/a3553d39a6a0a878080493b3803bd39d0c6cc8bb/springdoc-openapi-webmvc-core/src/main/java/org/springdoc/webmvc/api/OpenApiResource.java#L190-L192

**Current workaround (without springdoc-openapi)**
By making use of swagger-ui webjar & swagger-ui properties (https://swagger.io/docs/open-source-tools/swagger-ui/usage/configuration/) :
- Created static resource path for swagger-ui webjar
```
@Configuration
public class APISpecificationConfig implements WebMvcConfigurer {

  @Override
  public void addResourceHandlers(ResourceHandlerRegistry registry) {
    registry.addResourceHandler("/swagger-ui/**")
        .addResourceLocations("classpath:/META-INF/resources/webjars/swagger-ui/3.35.1/");
  }

}
```
- Added static spec file path to the `url` parameter
```
http://localhost:8080/swagger-ui/index.html?url=/my-spec.yaml
```

**I might misunderstand the usage or configuration. In that case, it would be helpful to help how to serve a static spec file correctly 🙏**

**Describe the solution you'd like**
We will have several use cases to work with OpenApi specs. It's not always enough to generate swagger spec from source code and serve them with swagger-ui.
I assume for quite a few use cases (e.g. to handle the generated spec files), we want to copy a spec file and let them handle with swagger-ui.
So, it would be very helpful if you could give configuration flexibility for that.
I really look forward to hear your feedback and thanks a lot in advance 🙇‍♀️ 

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by bnasslahsen** [comment]
@northernbird, 

 Yes, this is possible.
 It's already answered on the F.A.Q here:
 - https://springdoc.org/faq.html#how-can-use-custom-jsonyml-file-instead-of-generated-one-
