### ISSUE TITLE
swagger url forward is removing context path from the url?

### ISSUE THREAD

**Issue by ManjunathBiradar** [springdoc/springdoc-openapi#899]
Mine is Spring mvc project not based on Spring boot, Hence i have followed the steps mentioned in https://springdoc.org/faq.html#how-to-integrate-open-api-3-with-spring-project-not-spring-boot

I have added below dependencies : 

1. compile(group: 'org.springdoc', name: 'springdoc-openapi-ui', version: '1.4.8')
2.   compile(group: 'org.springframework.boot', name: 'spring-boot-autoconfigure', version: '2.1.3.RELEASE')
3.  compile(group: 'org.springframework.boot', name: 'spring-boot', version: '2.1.3.RELEASE')

My spring framework version is 5.1.5.RELEASE

So when i run the application in local as http://localhost:8080/api/v3/api-docs, it works.
but when i hit the url as http://localhost:8080/api/swagger-ui.html it redirects to 
http://localhost:8080/swagger-ui/index.html?configUrl=/v3/api-docs/swagger-config

Expected behaviour is it should retain the context path as well (/api) as http://localhost:8080/api/swagger-ui/index.html?configUrl=/api/v3/api-docs/swagger-config

Also when i manually enter the context path /api, page opens with 
Failed to load API definition. Fetch errorNot Found  /v3/api-docs

To the above error, in explore text box, if i put the context path manually again as /api/v3/api-docs, it works fine.

How to make sure to not to remove the context path in spring project not based on spring boot?

**Comment by bnasslahsen** [comment]
@ManjunathBiradar, 

 The project supports standard spring-boot properties, to define the context-path.
 You can have a look a the tests, to see the different context properties used:
 - https://github.com/springdoc/springdoc-openapi/tree/master/springdoc-openapi-webmvc-core/src/test

 If you still believe, you are facing an issue, then please add exactly the following information so this ticket can be reopened:

 - Provide a [**Minimal, Reproducible Example - with HelloController**](https://stackoverflow.com/help/minimal-reproducible-example) that explains the issue you are facing.

**Comment by ManjunathBiradar** [comment]
@bnasslahsen 
Please find the reproducible example code:
`package com.swagger.config;

import javax.servlet.ServletContext;
import javax.servlet.ServletException;
import javax.servlet.ServletRegistration;

import org.springframework.web.WebApplicationInitializer;
import org.springframework.web.context.ContextLoaderListener;
import org.springframework.web.context.support.AnnotationConfigWebApplicationContext;
import org.springframework.web.servlet.DispatcherServlet;

public class WebAppInitializer implements WebApplicationInitializer
{

    @Override
    public void onStartup(ServletContext servletContext) throws ServletException
    {
        
        AnnotationConfigWebApplicationContext beanContainer = new AnnotationConfigWebApplicationContext();
        beanContainer.setConfigLocations("");
		
        beanContainer.register(this.getClass(), org.springdoc.webmvc.ui.SwaggerConfig.class,
				org.springdoc.core.SwaggerUiConfigProperties.class, org.springdoc.core.SwaggerUiOAuthProperties.class,
				org.springdoc.core.SwaggerUiConfigParameters.class,
				org.springdoc.webmvc.core.SpringDocWebMvcConfiguration.class,
				org.springdoc.webmvc.core.MultipleOpenApiSupportConfiguration.class,com.swagger.config.DocumentationConfig.class,
				org.springdoc.core.SpringDocConfiguration.class, org.springdoc.core.SpringDocConfigProperties.class,
				org.springframework.boot.autoconfigure.jackson.JacksonAutoConfiguration.class);
        
	
		 
        servletContext.addListener(new ContextLoaderListener(beanContainer));
        ServletRegistration.Dynamic dispatcher = servletContext.addServlet("MyApp", new DispatcherServlet(beanContainer));

        dispatcher.setLoadOnStartup(1);
        dispatcher.addMapping("/api/*");
    }

}
`
`package com.swagger.config;

import org.springframework.beans.BeansException;
import org.springframework.context.ApplicationContext;
import org.springframework.context.ApplicationContextAware;
import org.springframework.context.annotation.ComponentScan;
import org.springframework.context.annotation.Configuration;
import org.springframework.context.annotation.EnableAspectJAutoProxy;
import org.springframework.jms.annotation.EnableJms;
import org.springframework.scheduling.annotation.EnableScheduling;
import org.springframework.web.servlet.config.annotation.CorsRegistry;
import org.springframework.web.servlet.config.annotation.EnableWebMvc;
import org.springframework.web.servlet.config.annotation.WebMvcConfigurationSupport;

@Configuration
@ComponentScan(basePackages = { "com.swagger", "org.springdoc" })
@EnableAspectJAutoProxy
@EnableWebMvc
@EnableJms
@EnableScheduling
public class MyAppConfig extends WebMvcConfigurationSupport implements ApplicationContextAware
{

	@Override
	public void addCorsMappings(CorsRegistry registry) {
		registry.addMapping("/*/**/***/****").allowedOrigins("*").allowedMethods("*");

	}

	static ApplicationContext applicationContext = null;

	public void setApplicationContext(ApplicationContext context) throws BeansException {
		applicationContext = context;
	}

	public static ApplicationContext getContext() {
		return applicationContext;
	}
}
`

`package com.swagger.config;

import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.web.servlet.config.annotation.EnableWebMvc;

import io.swagger.v3.oas.models.Components;
import io.swagger.v3.oas.models.OpenAPI;
import io.swagger.v3.oas.models.info.Info;

@Configuration
@EnableWebMvc
public class DocumentationConfig 
{
	 
	@Bean
	public OpenAPI myOpenAPI() 
	{
		return new OpenAPI().components(new Components())
				.info(new Info().title("My Application").description("My application documentation").version("V2"));

	}
}
`

`package com.swagger.config;

import org.springframework.context.annotation.Configuration;
import org.springframework.web.servlet.config.annotation.EnableWebMvc;
import org.springframework.web.servlet.config.annotation.WebMvcConfigurer;

@Configuration
@EnableWebMvc
public class OpenApiConfig implements WebMvcConfigurer 
{
		 
}
`

**Comment by ManjunathBiradar** [comment]
@bnasslahsen 
Attached is the dependencies used : 
![dependencies](https://user-images.githubusercontent.com/20626305/95723959-63431a80-0c93-11eb-84de-ca6da7d59ab9.PNG)

**Comment by bnasslahsen** [comment]
@ManjunathBiradar, 

 Could you please at least make sure, your code is readable. 
 Please review the formatting of your sample code.

**Comment by ManjunathBiradar** [comment]
@bnasslahsen  Added the formatted code pls check

**Comment by bnasslahsen** [comment]
> @bnasslahsen Added the formatted code pls check
> As mentioned in the issue i am using below dependencies:
> compile(group: 'org.springdoc', name: 'springdoc-openapi-ui', version: '1.4.8')
> compile(group: 'org.springframework.boot', name: 'spring-boot-autoconfigure', version: '2.1.3.RELEASE')
> compile(group: 'org.springframework.boot', name: 'spring-boot', version: '2.1.3.RELEASE')

Please add the whole **minimal project** link, that you can host on your own repo. That will make things easier, espacially, that you seem not be using spring-boot correctly. 

You code is refering to JMS. We don't use that, and it shouldn't be on a minimal reproducible sample.

**Comment by ManjunathBiradar** [comment]
[SpringSwaggerOpenApi.zip](https://github.com/springdoc/springdoc-openapi/files/5364354/SpringSwaggerOpenApi.zip)
@bnasslahsen  please find the attached sample code

**Comment by bnasslahsen** [comment]
@ManjunathBiradar, 

 Here are the main modifications you need:

 Declare the following property:

```properties
spring.mvc.servlet.path=/api
```

 Load the property file: 

```java
@PropertySource("classpath:/application.properties")
```

 You will find attached the complete working sample.

[SpringSwaggerOpenApi.zip](https://github.com/springdoc/springdoc-openapi/files/5365498/SpringSwaggerOpenApi.zip)

**Comment by bnasslahsen** [comment]
@ManjunathBiradar, 

So, did you make it work? Your feedback is appreciated.

**Comment by ManjunathBiradar** [comment]
@bnasslahsen Yup! It worked. Thank you so much for the help.
