### ISSUE TITLE
Hide a field from a Schema despite @JsonProperty

### ISSUE THREAD

**Issue by waschmittel** [springdoc/springdoc-openapi#902]
First of all, thanks a lot for this lib - we're using it intensively and it works great.

We have a DTO class like this
```java
public class ContentTreeItem {
    ...

    @JsonProperty(access = JsonProperty.Access.WRITE_ONLY)
    @Schema(hidden = true)
    private Integer position;

    ...
```

We need the position internally, but we don't serialize it. 
We do de-serialize it - but not in our API, which we are describing here.

So my expectation would be that we can hide it from the schema description.

Neither `@Schema(hidden = true)` nor `@Hidden` can be used to hide it, though.

When I remove the `@JsonProperty`, it is indeed hidden, so that seems to be part of our problem. We need this annotation, however, to tell Jackson to use it only for de-serialization.

**Comment by bnasslahsen** [comment]
@waschmittel, 

 which springdoc-openapi version are you using ?

**Comment by waschmittel** [comment]
We are using 1.4.8 @bnasslahsen

**Comment by bnasslahsen** [comment]
@waschmittel, 

 The issue you are description is not reproducible, from your description using the v1.4.8:
 If you feel, you are still facing an issue, please provide a [Minimal, Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example) - with HelloController that reproduces the problem.

 This is the controller code used to confirm:

```java
@RestController
public class HelloController {

	@GetMapping("/testA")
	public ContentTreeItem testA(ContentTreeItem hello) {
		return  null;
	}


	@GetMapping("/testB")
	public ContentTreeItem testB(ContentTreeItem hello) {
		return  null;
	}


	class ContentTreeItem {
		@JsonProperty(access = JsonProperty.Access.WRITE_ONLY)
		@Schema(hidden = true)
		private Integer position;

		public Integer getPosition() {
			return position;
		}

		public void setPosition(Integer position) {
			this.position = position;
		}
	}
}
```

And this is the result:

```yaml
openapi: 3.0.1
info:
  title: OpenAPI definition
  version: v0
servers:
  - url: 'http://localhost:8080'
    description: Generated server url
paths:
  /testB:
    get:
      tags:
        - hello-controller
      operationId: testB
      parameters:
        - name: hello
          in: query
          required: true
          schema:
            $ref: '#/components/schemas/ContentTreeItem'
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ContentTreeItem'
  /testA:
    get:
      tags:
        - hello-controller
      operationId: testA
      parameters:
        - name: hello
          in: query
          required: true
          schema:
            $ref: '#/components/schemas/ContentTreeItem'
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/ContentTreeItem'
components:
  schemas:
    ContentTreeItem:
      type: object

```

**Comment by waschmittel** [comment]
Hi @bnasslahsen the issue can be reproduced in https://github.com/waschmittel/springdoc-902

**Comment by bnasslahsen** [comment]
@waschmittel, 

 The issue you are facing is not related directly to springdoc-openapi, but to [swagger-core project](https://github.com/swagger-api/swagger-core/issues).
 Here is a sample code how you can confirm it:

```java
ResolvedSchema resolvedSchema = ModelConverters.getInstance()
			.resolveAsResolvedSchema(
					new AnnotatedType(ContentTreeItem.class));
	IntegerSchema propertySchema = (IntegerSchema) resolvedSchema.schema.getProperties().get("position");
	if (propertySchema != null)
		throw new IllegalStateException("Should not exist");
```

This is said, you can at anytime with springdoc-openapi override the swagger-core library result, using the available Customizers:

Here is a sample code for a workaround on your case (by just adding this bean to your app):

```java
@Component
public class HiddenPropertyCustomizer implements PropertyCustomizer {

	@Override
	public Schema customize(Schema schema, AnnotatedType type) {
		if ("position".equals(type.getPropertyName()))
			return null;
		return schema;
	}
}
```


Please feel free to log you request on the swagger-core project, if you feel it's useful for the community.
