### ISSUE TITLE
@Schema(accessMode = Schema.AccessMode.READ_ONLY) on method change access mode for all fields with the same type

### ISSUE THREAD

**Issue by adian** [springdoc/springdoc-openapi#903]
**Describe the bug**
I have a model that has the method `B getA()`. In `GET` request it is shown as a field - ok. But I also see it as a field in `POST`.

So I added `@Schema` annotation:
```java
@Schema(accessMode = Schema.AccessMode.READ_ONLY)
B getA() {
...
}
```

Now I don't see `a` property on `POST` request. But there is a new problem. Now every field in my app that has `B` type is now read-only. 

**To Reproduce**
```
    implementation("org.springdoc:springdoc-openapi-ui:1.4.8")
    implementation("org.springdoc:springdoc-openapi-data-rest:1.4.8")
    implementation("org.springdoc:springdoc-openapi-security:1.4.8")
```

**Expected behavior**
- If there is no setter, the field should be read-only.
- Should @Schema on the method that returns `B` change Schema for all fields with `B` type?

**Comment by bnasslahsen** [comment]
@adian, 

If you are reporting a bug, please help to speed up problem diagnosis by providing as much information as possible:
-  Please make sure you provide a [Minimal, Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example) - with HelloController that reproduces the problem.

 This ticket will be reopened, if the relevant information are provided.

**Comment by adian** [comment]
@bnasslahsen 
`application.yaml`:
```
...
spring:
    data:
        rest:
            return-body-on-create: true
            return-body-on-update: true
            detection-strategy: annotated
springdoc:
    swagger-ui:
        docExpansion: none
...
```

dependencies:
```
dependencies {
    implementation("org.springframework.boot:spring-boot-starter-web")
    implementation("org.springframework.boot:spring-boot-starter-webflux")
    implementation("org.springframework.boot:spring-boot-starter-data-rest")
    implementation("org.springframework.boot:spring-boot-starter-data-mongodb")
    implementation("org.springframework.boot:spring-boot-starter-security")

    implementation("org.springdoc:springdoc-openapi-ui:1.4.8")
    implementation("org.springdoc:springdoc-openapi-data-rest:1.4.8")
    implementation("org.springdoc:springdoc-openapi-security:1.4.8")
```

```java
@Configuration
class OpenApiConfig {

    private static final String SECURITY_SCHEME_NAME = "bearerAuth";

    @Bean
    OpenAPI myOpenAPI() {

        return new OpenAPI()
            .info(
                new Info().title("mobile backend")
            )
            .addSecurityItem(new SecurityRequirement().addList(SECURITY_SCHEME_NAME))
            .components(
                new Components().addSecuritySchemes(SECURITY_SCHEME_NAME,
                    new SecurityScheme()
                        .name(SECURITY_SCHEME_NAME)
                        .type(SecurityScheme.Type.HTTP)
                        .scheme("bearer")
                        .bearerFormat("JWT")
                )
            );

    }
}
```

**Comment by bnasslahsen** [comment]
@adian ,

 Your code is not complete.
 Please make sure you add your controller code  and your model.
 Also, you should describe what are the actual and the expected result using OpenAPI Description (yml or json)?

**Comment by adian** [comment]
I'm using Spring Data REST. 

```java
@Getter
@Setter
public abstract class AbstractDocument {
    @Id
    @Schema(accessMode = Schema.AccessMode.READ_ONLY)
    private String id;
}
```

```java
@Data
@EqualsAndHashCode(callSuper = true)
public class A extends AbstractDocument  {

    @CreatedBy
    @Schema(accessMode = Schema.AccessMode.READ_ONLY)
    private String userId;
    
    private String description;

    private Money originalPrice;

    @Schema(accessMode = Schema.AccessMode.READ_ONLY)
    public Money getEstimatedValue() {
        // some logic
    }
}
```

```java
@Data
@NoArgsConstructor
@AllArgsConstructor
public class Money {

    @Schema(example = "USD" )
    private String currency;

    @Schema(example = "99.96", format = "double")
    private BigDecimal amount;
}
```

When I open Swagger UI I see `POST` example JSON:
```json
{
    "description": "string"
}
```
Where is `originalPrice`? I didn't set it as `Schema.AccessMode.READ_ONLY`.

 In `GET` example everything is ok:
```json
{
  "_embedded": {
    "a": [
      {
        "createdAt": "2020-10-16T14:12:59.965Z",
        "userId": "string",
        "originalPrice": {
          "currency": "USD",
          "amount": 99.96
        },
        "description": "string",
        "estimatedValue": {
          "currency": "USD",
          "amount": 99.96
        }
      }
    ]
  },
  "_links": [
    {
      "href": "string",
      "hreflang": "string",
      "title": "string",
      "type": "string",
      "deprecation": "string",
      "profile": "string",
      "name": "string",
      "templated": true
    }
  ]
}
```

**Comment by adian** [comment]
And why I need annotate  `getEstimatedValue` with `@Schema(accessMode = Schema.AccessMode.READ_ONLY)`?
Shouldn't it by default be read-only?

**Comment by bnasslahsen** [comment]
@adian, 

 For your question about the AccessMode, yes you should add it to your Schema description. Or it should come from JsonProperty.  Note that this behaviour, is handled directly on the swagger-core library.


 Also, you description is still not complete: You didn't add the code of your **HelloController**  as requested earlier.

 To help speed up problem diagnosis, you can simply provide the link to a GIHTUB project, where you describe **a minimal reproducible sample** that reproduces your issue.
