### ISSUE TITLE
Support for placeholders for default value in @RequestParam Annotation

### ISSUE THREAD

**Issue by punit-kulal** [springdoc/springdoc-openapi#904]
Spring Boot supports placeholder values in @ReqestParam annotation defaultValue parameter.
However SwaggerUI does not resolve the configuration value and instead uses the placeholder as a literal string.
This, results in configuration values being exposed to the SwaggerUI.

**Comment by bnasslahsen** [comment]
@punit-kulal, 

 This feature will be available for the next release.
