### ISSUE TITLE
Support for auto conversion of Kotlin nullable type to schema: { nullable: true }

### ISSUE THREAD

**Issue by martin-walsh** [springdoc/springdoc-openapi#906]
Currently the distinction between Kotlin nullable vs non-nullable fields is used to determined for the `required` fields list. This works very nicely.

Could a similar solution be applied to work out the `nullable` property on a field?  It is quite tedious to add the Schema annotation (e.g. `@field:Schema(nullable = true) val myString: String?`) on every nullable field so that it decorates the generated schema rather than inspecting it from the field declaration.

**Comment by bnasslahsen** [comment]
@martin-walsh, 

 This is a sample Bean that you can declare on your application, and which might help:

```kotlin
@Bean
fun nullableCustomiser(): OpenApiCustomiser? {
	return OpenApiCustomiser { openAPI: OpenAPI ->
		openAPI.components.schemas.values.stream().filter { schema: Schema<*> -> "object" == schema.type }
			.forEach { schema: Schema<*> -> 
			    val properties = schema.properties
			    properties.entries.stream()
					.filter { prop: Map.Entry<String, Schema<*>> -> !schema.required.contains(prop.key) }
					.forEach { entry: Map.Entry<String, Schema<*>> -> entry.value.setNullable(true) }
				}
	}
}
```

 Let us know, if it's working for you, and we can add an option for it out of the box.

**Comment by martin-walsh** [comment]
Hi, thanks for the response. It does indeed work, with the addition of a null check for `schema.properties`.

Unfortunately I mistakenly stated that Kotlin non-null types were correctly detected. This is not the case, detection of nullable is based upon `javax.validation.constraints.NotNull`, which makes sense. I would need a more complete solution in order to achieve the effect I want, something along the lines of having the compiler add the `@Schema` annotations if missing based upon Kotlin not-null type.

**Comment by bnasslahsen** [comment]
@martin-walsh, 

 Not sure to understand what you want to achieve here.
 Please add document your words with a sample, that shows what is the actual and the expected result.

**Comment by bnasslahsen** [comment]
@martin-walsh, 

 This issue will be closed.
  It can be reopened, if the relevant information is provided.

**Comment by ondrejlerch** [comment]
@bnasslahsen
Given:
```
data class Aaa(
    val xxx: String?,
    val yyy: String,
)
```
I would like to generate:
```
Aaa:
  type: object
  properties:
    xxx:
      type: string
      nullable: true
    yyy:
      type: string
```
Currently this works if I define:
```
data class Aaa(
    @field:Schema(nullable = true)
    val xxx: String?,
    val yyy: String,
)
```
It would be nice if I don't have to specify `@field:Schema(nullable = true)` for Kotlin nullables.

I defined `@Bean fun nullableCustomiser()` as suggested above but this sets `nullable: true` everywhere, even for `yyy`.

Do you have a suggestion how to achieve that?

Many thanks!

**Comment by bnasslahsen** [comment]
@ondrejlerch, 

Just tested the `nullableCustomiser` and works fine.
Try providing the link to a Provide a [Minimal, Reproducible Example - with HelloController](https://stackoverflow.com/help/minimal-reproducible-example) that reproduces the problem.

**Comment by ondrejlerch** [comment]
@bnasslahsen
Sorry for my previous mistake about forgetting to add `org.springdoc:springdoc-openapi-kotlin` dependency.

a) After adding `org.springdoc:springdoc-openapi-kotlin` dependency I am getting:
```
Aaa:
  type: object
  required:
  - yyy
  properties:
    xxx:
      type: string
    yyy:
      type: string
```

b) After adding `nullableCustomiser` as well I am getting:
```
Aaa:
  type: object
  required:
  - yyy
  properties:
    xxx:
      type: string
      nullable: true
    yyy:
      type: string
```

So everything works fine.

Question is what is nicer API, a) or b)?

I am not OpenAPI expert but I am happy to start with a), i.e. clients either sends `"xxx": "something"` or does not send `"xxx"` at all.
With b) he could also send `"xxx": null` as described here:
https://stackoverflow.com/questions/45575493/what-does-required-in-openapi-really-mean

What do you think?

Many thanks!

**Comment by bnasslahsen** [comment]
@ondrejlerch, 

From your kotlin code, you have a nullable type. 
If the null value needs to be allowed, add nullable: true: So b) looks better!

**Comment by ondrejlerch** [comment]
@bnasslahsen
I Agree, b) is less restrictive to consumers so `nullableCustomiser` nicely helps.

1. Will you add an option for `nullableCustomiser` functionality for Kotlin out of the box?

2. What about adding similar functionality for Java where javax.annotation.Nullable would mean `nullable: true` and everything else would mean `required`?

Many thanks!

**Comment by bnasslahsen** [comment]
@ondrejlerch, 

Please feel free to propose a PR and will have a look at it.
