### ISSUE TITLE
@Hidden controller showing up in swagger UI when springdoc.show-actuator is enabled

### ISSUE THREAD

**Issue by moxaj** [springdoc/springdoc-openapi#907]
**Describe the bug**
If I set `springdoc.show-actuator` to `true`, controllers annotated with `@Hidden` are visible in the swagger UI.

**To Reproduce**
In a spring boot project:
 - add `springdoc.show-actuator=true` to `application.properties`
 - create a new controller with a `@Hidden` annotation:

```java
@Controller
@Hidden
public class SomeController {
  @RequestMapping("/hello")
  public String index() {
    return "..";
  }
}

```

**Expected behavior**
`SomeController` shouldn't show up in the swagger UI. However, it does, along with `basic-error-controller`, which was previously hidden.

**Additional context**
Spring boot version: `2.3.4.RELEASE`
Springdoc version: `1.4.8` (using `springdoc-openapi-ui`, `springdoc-openapi-data-rest`, `springdoc-openapi-security`)

**Comment by bnasslahsen** [comment]
@moxaj, 

 Resolved by https://github.com/springdoc/springdoc-openapi/pull/919.
