### ISSUE TITLE
Schema and JsonFormat annotations interaction

### ISSUE THREAD

**Issue by manuelCordon** [springdoc/springdoc-openapi#908]
When fields in a class are annotated with `io.swagger.v3.oas.annotations.media.Schema` and `com.fasterxml.jackson.annotation.JsonFormat`, the schema  annotation seems to be ignored.

A class specified as follows:
```
public class TestObject {
    @Schema(example = "10/31/2020", type = "string", format = "date"))
    private Date publicDate;

    @Schema(hidden = true)
    private Date hiddenDate;

    @Schema(hidden = true)
    @JsonFormat(
            shape = JsonFormat.Shape.STRING,
            pattern = US_DATE_FORMAT_STRING,
            timezone = REQUEST_TIMEZONE
    )
    private Date jsonFormattedDate;

}
```

The `jsonFormattedDate` is visible in the json output and `publicDate` is displayed as ISO date format

**Comment by bnasslahsen** [comment]
@manuelCordon, 

 Your description is more related to swagger-core.
 Please make sure you use the right [GitHub project.](https://github.com/swagger-api/swagger-core/issues)
 You can check if there is an existing issue and add your comment above, or create a new one if it doesn't exist.
