### ISSUE TITLE
Deploy as .war

### ISSUE THREAD

**Issue by luStopai** [springdoc/springdoc-openapi#91]
Hi

I'm trying to use springdoc on a springboot application packaged as .war and deployed on wildfly

Assuming this is the project template
![imagen](https://user-images.githubusercontent.com/39245981/65372842-7ee91680-dc75-11e9-89c7-59a7ec280a24.png)

and adding this dependency

```
<dependency>
   <groupId>org.springdoc</groupId>
   <artifactId>springdoc-openapi-ui</artifactId>
   <version>1.1.40</version>
</dependency>
```

I'm able to access http://localhost:8080/demo-0.0.1-SNAPSHOT/v3/api-docs but when I try to access to http://localhost:8080/demo-0.0.1-SNAPSHOT/swagger-ui.html, it redirects me to http://localhost:8080/demo-0.0.1-SNAPSHOT/swagger-ui/index.html?url=/demo-0.0.1-SNAPSHOT/v3/api-docs&validatorUrl= which returns 404 not found

Any idea how can I fix this?

**Comment by springdoc** [comment]
Hi, 

 Unable to reproduce your issue, after deploying the war on a tomcat.
 Here is what you should get on an empty project: 
 
- http://localhost:8080/demo-0.0.1-SNAPSHOT/swagger-ui/index.html?url=/demo-0.0.1-SNAPSHOT/v3/api-docs&validatorUrl=

<img width="482" alt="Capture" src="https://user-images.githubusercontent.com/52804136/65374829-a4cee500-dc8e-11e9-8eb6-fd40e44e6251.PNG">



 Can you please, describe where are you deploying your application and upload your project.

**Comment by luStopai** [comment]
Here's the source code I use. 
[demo_1.zip](https://github.com/springdoc/springdoc-openapi/files/3638924/demo_1.zip)

**Comment by luStopai** [comment]
FYI, I just tried with a dockerized payara server https://hub.docker.com/r/payara/server-full/ and it worked fine, so it seems an issue related to wildfly

**Comment by springdoc** [comment]
Hi, 

This issue as you mentioned is related to worldly.
You just need to add the following dependency to your pom.xml:

```java
<dependency>
	<groupId>org.webjars</groupId>
	<artifactId>webjars-locator-jboss-vfs</artifactId>
	<version>0.1.0</version>
</dependency>
```

**Comment by luStopai** [comment]
Hi @ghost

It's me again, I think this dependency is no longer needed. 
To check this I just downloaded the source code I provided when I created this issue, I updated springboot from 2.1.8 to 2.3.4 and everything works fine, so it seems that at some point springboot changed something that makes this dependency no longer needed.
You may wanna update the documentation, although you may wanna first check this issue I reported (#940), just in case
