### ISSUE TITLE
redirect index.html based on http

### ISSUE THREAD

**Issue by mimonk** [springdoc/springdoc-openapi#912]
**Describe the bug**
starting swagger-ui via https://www.someurl.com/{server.servlet.context-path}/swagger-ui.html redirects to index.html.
http://www.someurl.com/{server.servlet.context-path}/swagger-ui/index.html?configUrl=/api/v1/v3/api-docs/swagger-config.
index.hmtl not showed up based on our policy forbidden traffic to http port 80.
Changes http -> https works.
Currently it`s not possible to set correct basePath

**To Reproduce**
springBoot version 2.3.3.RELEASE
springdoc-api-ui version 1.4.8

**Expected behavior**
redirect should use correct protocoll.

**Comment by bnasslahsen** [comment]
@mimonk, 

 There are no known issue about redirects.
 Make sure your application is configured well to handle all [the proxy requests](https://springdoc.org/faq.html#how-can-i-deploy-springdoc-openapi-ui-behind-a-reverse-proxy).
