### ISSUE TITLE
Empty Annotation List in PropertyCustomizer when Annotation resides on the type parameter of an java.util.Optional Field

### ISSUE THREAD

**Issue by tweigel** [springdoc/springdoc-openapi#913]
**Describe the bug**
- We tried to generate parts of our documentation by using a PropertyCustomizer to parse our custom Annotations. This worked pretty well except for the cases where we are using Optional and the Annotation resides on the type parameter. In those cases a call to getCtxAnnotations() returns an empty list.

**To Reproduce**
1. Write a simple Controller that will return a DTO
2. Add two fields to the DTO, one of type String, the other of type Optional<String>
3. Annotate the fields with any Annotation so it would look similar to this:
```
public class DummyResponse {
    @MyCustomAnnotation
    private String prop1;
    private Optional<@MyCustomAnnotation String> prop2;

    /* Getter / Setter */
}
```
4. Write a PropertyCustomizer and read out the annotations of the AnnotatedType parameter
```
public class MyPropertyCustomizer implements PropertyCustomizer {
    @Override
    public Schema customize( Schema property, AnnotatedType type) {
        type.getCtxAnnotations();

    }
}
```

**Expected behavior**
- ```getCtxAnnotations()``` should return a non empty list containing the @MyCustomAnnotation for both fields

**Additional context**
Springboot Version 2.3.4.RELEASE
springdoc-openapi-ui Version 1.4.8

**Comment by bnasslahsen** [comment]
@tweigel, 

 The code you described with Optional doesn't even compile. 
 Additionnly make sure you describe all the components to reproduce your issue: `MyCustomAnnotation` is missing

 **A reminder:** If you are reporting a bug, please help to speed up problem diagnosis by providing as much information as possible:

 - What are the actual and the expected result using OpenAPI Description (yml or json)?
- Provide a [Minimal, Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example) - with HelloController that reproduces the problem 

 This ticket will be reopened, if the relevant information are provided.
