### ISSUE TITLE
OpenAPI not working correctly with array type

### ISSUE THREAD

**Issue by eaxdev** [springdoc/springdoc-openapi#916]
I using `SpringBoot` and `springdoc-openapi-ui`. I have controller with method, which contain array as url param:

```java
 @Parameters(value = {
            @Parameter(in = ParameterIn.QUERY, name = "output", example = "[f1,f2,f3]",
                    content = @Content(array = @ArraySchema(schema = @Schema(type = "string"))))
})
public ResponseEntity<Object> showReportData(@RequestParam(value = "output") String[] outputFields) {
//some body
}
```
But, when I open `SwaggerUI`, I can't see my example values in items textbox:
![image](https://user-images.githubusercontent.com/13472225/97754924-62224200-1b09-11eb-9de7-0983a9699c76.png)

And when I click execute, I see this param in request:

![image](https://user-images.githubusercontent.com/13472225/97754967-6d756d80-1b09-11eb-9799-6257fd116d39.png)

Why is this happening? Why is the example array not displayed in item?

**Comment by bnasslahsen** [comment]
@eaxdev, 

 Your examples are generated as you described on your code: And the generated request is correct.

![image](https://user-images.githubusercontent.com/13404829/97756834-dc4bca00-1afb-11eb-9dad-91046443b192.png)

 Please make sure you check the OpenaAPI generated json file, before raising any issues on the springdoc-openapi project.
