### ISSUE TITLE
Login form for JWT auth

### ISSUE THREAD

**Issue by judos** [springdoc/springdoc-openapi#922]
**Is your feature request related to a problem? Please describe.**
I would like JWT authentication with an small form to login easily in swagger-ui.html.
Currently I have the security scheme enabled but I only get a field to enter my jwt token. So every user has to manually authenticate, then add the jwt to be logged in.

My code is:
```
@OpenAPIDefinition(info = Info(title = "GAG Loyalty-Backend"))
@SecurityScheme(name = "jwt_auth", type = SecuritySchemeType.HTTP, bearerFormat = "JWT", scheme = "bearer")
public class OpenApiConfig
```
And in the controller:
```
@RestController(value = "adminRewardController")
@RequestMapping("admin/rewards", produces = ["application/json"])
@SecurityRequirement(name = "jwt_auth")
class RewardController @Autowired constructor(
[...]
```

**Describe the solution you'd like**
In the code I would need to define the endpoint where swagger can authenticate, and also parameter names like username, password, and returned parameter name "jwt" where swagger can get the token to store and use later.

**Additional context**
This would only be a small usability extension.

I read the samples and in the documentation: [Springdoc - Add auth header](https://springdoc.org/#how-do-i-add-authorization-header-in-requests)

[This Ticket](https://github.com/springdoc/springdoc-openapi/issues/827) seems related but I don't get what the result of the ticket was. Was it solved? Is my request already possible? If yes I didn't see in the documentation how...

Thanks for your help!

**Comment by bnasslahsen** [comment]
@judos, 

 You can a look at the following example code, which shows how it works:

- https://github.com/springdoc/springdoc-openapi/tree/master/springdoc-openapi-security/src/test/java/test/org/springdoc/api/app6

 You need to set: 

```properties
springdoc.show-login-endpoint=true
```

 More details are available on the documentation:
 - https://springdoc.org/#springdoc-openapi-core-properties
