### ISSUE TITLE
Improvement for QuerydslPredicateOperationCustomizer#excludeUnlistedProperties

### ISSUE THREAD

**Issue by chrisupb** [springdoc/springdoc-openapi#925]
This relates to #866.
The fix in #866 removes all Querydsl properties which are explicitly whitelisted with:

`bindings.including(XXXX);`

The wanted behavior is: If _excludeUnlistedProperties_ is true, add defined bindings AND ONLY whitelisted properties to the generated parameters list in OpenAPI.

Pullrequest follows...

**Comment by chrisupb** [comment]
OK, I see test app19 fail because 
`bindings.bind(root.name).first(StringExpression::containsIgnoreCase);`
 is not on the whitelist.

**What is the expected behavior here?**

Really ONLY include fields on the whitelist and ignore additional bindings? Than the test case would change to 

`public void customize(QuerydslBindings bindings, QApplication root) {`
`bindings.excludeUnlistedProperties(true);`
`bindings.bind(root.name).first(StringExpression::containsIgnoreCase);`
`bindings.including(root.name);`
`bindings.including(root.icon);`
`}`


 Or always include all bindings bindings.bind() [QuerydslBindings.pathSpecs] no matter what is on the whitelist.

**Comment by bnasslahsen** [comment]
should be fixed by #934.
