### ISSUE TITLE
is there any feature available to hide or replace with * for a text input field in swagger?

### ISSUE THREAD

**Issue by Suddhasatta** [springdoc/springdoc-openapi#927]
**Is your feature request related to a problem? Please describe.**
- A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
- What is the actual result using OpenAPI Description (yml or json)?

**Describe the solution you'd like**
- A clear and concise description of what you want to happen.
- What is the expected result using OpenAPI Description (yml or json)?

**Describe alternatives you've considered**
- A clear and concise description of any alternative solutions or features you've considered.

**Additional context**
- Add any other context or screenshots about the feature request here.

**Comment by bnasslahsen** [comment]
@Suddhasatta, 
  
 Please make sure you read the contribution guide, section **[Using GITHUB ISSUES](https://github.com/springdoc/springdoc-openapi/blob/master/CONTRIBUTING.adoc)** before submitting an issue.
 It's clearly written: **You need to describe your context (the title of an issue is not enough)**

 This ticket will be reopned, if the relevant information are provided.
