### ISSUE TITLE
Release [1.4.9]

### ISSUE THREAD

**Issue by Samsonkin** [springdoc/springdoc-openapi#928]
Hi, could you please release [1.4.9] :-)

**Comment by bnasslahsen** [comment]
@Samsonkin, 

 The next release, has many features that depend on spring-boot release 2.4.0 GA on November 12.
 Our current plan is to release the next release (certainly 1.5.0), just few hours after.

**Comment by Samsonkin** [comment]
@bnasslahsen Thanks for the answer)

**Comment by bnasslahsen** [comment]
@Samsonkin, 

 F.Y.I v1.5.0 is now available.

**Comment by Samsonkin** [comment]
Thank you very much!

сб, 14 нояб. 2020 г. в 03:34, bnasslahsen <notifications@github.com>:
