### ISSUE TITLE
Improve indentation Json Response

### ISSUE THREAD

**Issue by fabiankuhn** [springdoc/springdoc-openapi#931]
**Problem**
- Regarding the Springdoc user-interface and the handling of responses in particular: When a long json response is received, like a large string, the line is broken with no indentation. This makes responses harder to read.

**Request**
- Request: Align indentation of json responses on line break.

**Additional context**
- A Screenshot with the described problem is attached.
<img width="1406" alt="Screenshot 2020-11-10 at 21 39 50" src="https://user-images.githubusercontent.com/34968622/98731576-35d6b300-239e-11eb-83a1-d72e55782a70.png">

**Comment by bnasslahsen** [comment]
@fabiankuhn, 

 We do not modify the code of the swagger-ui. 
 Springdoc-openapi project relies on swagger-ui webjars.

 You can ask the [swagger-ui team](https://github.com/swagger-api/swagger-ui), if you want any enhancements on the swagger-ui.
