### ISSUE TITLE
OpenApiCustomiser not called during integration test via MockMvc

### ISSUE THREAD

**Issue by Allsimon** [springdoc/springdoc-openapi#932]
After setting an `OpenApiCustomiser` and making sure it's being applied via requesting `http://localhost:8080/v3/api-docs/`, it doesn't get called when we GET this endpoint with MockMvc.

I'm calling the endpoint like this in my test:
```java
  private final MockMvc mockMvc;

  @Test
  void customizerNotCalled() {
    var generatedOpenAPIFile = mockMvc.perform(get("/v3/api-docs")).andReturn().getResponse().getContentAsString();
    System.out.println(generatedOpenAPIFile);
  }
```

**To Reproduce**
- What version of spring-boot you are using? 2.3.4
- What modules and versions of springdoc-openapi are you using? 1.4.8

**Comment by bnasslahsen** [comment]
@Allsimon, 

 Not reproducible.

 You can have a look at sample code here, that uses OpenApiCustomiser with MockMvc:

 - https://github.com/springdoc/springdoc-openapi/tree/master/springdoc-openapi-webmvc-core/src/test/java/test/org/springdoc/api/app39

 If you believe, you are facing a bug, make sure you provide a **Minimal, Reproducible Example** - with HelloController that reproduces the problem.

 This ticket will be for now closed; And can be reopened, if you are providing the relevant information.

**Comment by Allsimon** [comment]
Hello,

I created a minimal repo that reproduces the issue here: https://github.com/Allsimon/springdoc-repro-932

**Comment by bnasslahsen** [comment]
@Allsimon, 

 This is the correction of your test:
 - https://github.com/Allsimon/springdoc-repro-932/pull/1
