### ISSUE TITLE
Need alternative of springfox-swagger public Docket globalResponses(HttpMethod httpMethod, List<Response> responses) 

### ISSUE THREAD

**Issue by asuri3** [springdoc/springdoc-openapi#936]
As of now if we need to customize globalResponse for each http methods, it's not possible in springdoc-openapi.
We can either add a response globally for all endpoints or else we can use @ApiResponses annotation on each endpoint to customize response code and description.
If I need to have a generic response for each HttpMethod, we can't do it here. But in springfox-swagger it can be done by writing following snippet:

`return new Docket(DocumentationType.SWAGGER_2)
       .additionalModels(new TypeResolver().resolve(ErrorResponse.class),
            new TypeResolver().resolve(ErrorResponse400.class),
            new TypeResolver().resolve(ErrorResponse409.class),
            new TypeResolver().resolve(ErrorResponse500.class))
        .globalResponses(HttpMethod.PUT, createDefaultResponses())
        .globalResponses(HttpMethod.POST, createDefaultPostResponses())
        .globalResponses(HttpMethod.GET, createDefaultGetResponses())
        .globalResponses(HttpMethod.DELETE, createDefaultResponses())

 private List<Response> createDefaultPostResponses() {
    List<Response> responseMessageList = createDefaultResponses();
    responseMessageList.add(getResponseMessage(HttpStatus.CONFLICT));
    return responseMessageList;
  }`

  private List<Response> createDefaultResponses() {
    List<Response> responseMessageList = new ArrayList<>();
    responseMessageList.add(getResponseMessage(HttpStatus.BAD_REQUEST));
    responseMessageList.add(getResponseMessage(HttpStatus.INTERNAL_SERVER_ERROR));
    return responseMessageList;
  }

  private List<Response> createDefaultGetResponses() {
    List<Response> responseMessageList = createDefaultResponses();
    responseMessageList.add(getResponseMessage(HttpStatus.NO_CONTENT));
    return responseMessageList;
  }

private Response getResponseMessage(HttpStatus httpStatus) {
    String errorResponseModel;
    switch (httpStatus.value()) {
      case 400:
        errorResponseModel = "ErrorResponse400";
        break;
      case 409:
        errorResponseModel = "ErrorResponse409";
        break;
      case 500:
        errorResponseModel = "ErrorResponse500";
        break;
      case 204:
        errorResponseModel = null;
        break;
      default:
        errorResponseModel = "ErrorResponse";
        break;
    }

`

**Describe the solution you'd like**
- An option to access HttpMethod in OperationCustomizer and to group response code by HTTP method globally with the option to assign a different class for each response code.
`
.addOperationCustomizer(new OperationCustomizer() {
          @Override
          public Operation customize(Operation operation, HandlerMethod handlerMethod) {
`

**Comment by bnasslahsen** [comment]
@asuri3, 

 You have `OpenApiCustomiser` where you have access to all the HTTP Methods and operations.
 This a sample code that you can adapt depending on your case:

```java
@Bean
public OpenApiCustomiser customerGlobalHeaderOpenApiCustomiser() {
	HandlerMethod handlerMethod;
	return openApi -> {
		openApi.getPaths().values().forEach(pathItem -> pathItem.readOperations().forEach(operation -> {
			// Change only paths with GET Méthods
			if (pathItem.getPost() != null) {
				ApiResponses apiResponses = operation.getResponses();
				ApiResponse apiResponse = new ApiResponse().description("Custom Error")
						.content(new Content()
								.addMediaType(org.springframework.http.MediaType.APPLICATION_JSON_VALUE, new MediaType()));
				apiResponses.addApiResponse("400", apiResponse);
			}
		}));
	};
}
```

**Comment by asuri3** [comment]
Thank you OpenApiCustomer did the trick.
