### ISSUE TITLE
Cookies are not sent to the server

### ISSUE THREAD

**Issue by Nick0L** [springdoc/springdoc-openapi#937]
**Describe the bug**
- Cookie are not sent to the server

**To Reproduce**
- Latest library
- Create endpoint with parameter `@CookieValue String token`

**Expected behavior**
- Cookies must be sent in the request

![springdoc](https://user-images.githubusercontent.com/51759022/99127348-c0264d80-2610-11eb-9dd1-174d3ac13186.PNG)

**Comment by bnasslahsen** [comment]
@Nick0L, 

 springdoc-openapi is built on top of the swagger-ui.
 The generated OpenAPI spec is correct, which is done by springdoc-openapi.

Please raison your issue, with the same description in the[ swagger-ui ](https://github.com/swagger-api/swagger-ui)project instead.
