### ISSUE TITLE
Swagger-UI Property "persistAuthorization" is missing 

### ISSUE THREAD

**Issue by constantine008** [springdoc/springdoc-openapi#938]
We are migrating from Springfox to Springdoc, which worked very well. We expect preserve authorization on browser refresh and close/reopen. swagger-ui fixed it on Swagger UI v3.34.0 . But this can't be set currently via springdoc-properties.

[https://github.com/swagger-api/swagger-ui/commit/96aecc8860a906d2d185bcbba60fae61ca847fdc](url)
[https://github.com/swagger-api/swagger-ui/pull/5939
![Swagger UI v3.34.0](https://user-images.githubusercontent.com/20673815/99237156-11ae2280-2833-11eb-9dda-61975b6f807d.png)
](url)

What we expect:

it is possible to define the swagger-ui property persistAuthorization,  e.g. by defining the spring-boot property springdoc.swagger-ui.persistAuthorization

**Comment by bnasslahsen** [comment]
@constantine008, 

 This is not yet supported. It will be planned for next release.
 You can propose a PR, if you wish to contribute.
