### ISSUE TITLE
@ApiResponses should also consider @ResponseStatus and return value

### ISSUE THREAD

**Issue by pavelkryl** [springdoc/springdoc-openapi#939]
**Avoid Redundancy**
- I have a controller method like this one:

```
    @Operation(
        summary = "Operation summary",
        description = "Operation description",
        security = [SecurityRequirement(name = SwaggerConfig.FIREBASE_AUTH_SCHEME)]
    )
    @GetMapping("/v1/me/nearby-profile")
    @ApiResponses(
        ApiResponse(
            responseCode = "200",
            description = "Default nearby profile",
            content = [Content(schema = Schema(implementation = PublicUserProfileEntity::class))]
        ),
        ApiResponse(
            responseCode = "404",
            description = "When profile does not exist",
            content = [Content(schema = Schema(implementation = ApiErrorBean::class))]
        )
    )
    @ResponseStatus(HttpStatus.OK)
    @PreAuthorize(AuthRules.RULE_USER_WITH_PROFILE)
    fun getDefaultNearbyProfile(@AuthenticationPrincipal userIdentity: AuthIdentity): Mono<PublicUserProfileEntity> =

```

- notice the redundancy in @ApiResponses - the first "200" element just duplicates @ResponseStatus and the return value 'Mono<PublicUserProfileEntity>'
- if I change the success responseCode or return value, I must change it on two places
- if I don't change the doc accordingly, I get a wrong API docs

**Describe the solution you'd like**
- I would like a special flag on ApiResponse and ApiResponses which would mean: consider *also* @ResponseStatus and return value, so that I do not have to repeat what is obvious

Thanks for consideration!

**Comment by bnasslahsen** [comment]
@pavelkryl, 

  Note that if you are using Error Handlers, like @ControllerAdvice it's already supported without extra swagger-annotations.
 But in the controller level, you can make sure not to be redundant:

 - By default, you don't need to return @ResponseStatus(HttpStatus.OK), as it's already the default response by spring.
 For error codes, you can use Error Handlers.

 @ApiResponse is not a springodc-openapi annotation. Hence, this is not the right github.
 You can have a look at swagger-annotations here:
 - https://github.com/swagger-api/swagger-core/wiki/annotations
