### ISSUE TITLE
Viewing all properties of protobuf which causes ui to hang

### ISSUE THREAD

**Issue by bucknerns** [springdoc/springdoc-openapi#942]
**Describe the bug**
- If you are reporting a bug, please help to speed up problem diagnosis by providing as much information as possible:
ui hangs when expanding api because using protobufs
- A clear and concise description of what the bug is: the title of an issue is not enough

**To Reproduce**
- What version of spring-boot you are using?
refer to the example repo https://github.com/bucknerns/spring-webflux-json-protobuf
- What modules and versions of springdoc-openapi are you using?
https://github.com/bucknerns/spring-webflux-json-protobuf
- What is the actual and the expected result using OpenAPI Description (yml or json)?
Only gets the protobufs that are used and only the fields that aren't builtins
- Provide with a sample code (HelloController) or Test that reproduces the problem
https://github.com/bucknerns/spring-webflux-json-protobuf
./gradlew bootRun, then open ui

**Expected behavior**
- A clear and concise description of what you expected to happen.
It to work
- What is the expected result using OpenAPI Description (yml or json)?
json

**Screenshots**
![image](https://user-images.githubusercontent.com/4094535/99441685-16271980-28cd-11eb-8e6a-314b5b9847f9.png)

**Additional context**

**Comment by bucknerns** [comment]
Hoping I am just missing something obvious like a flag or something.

**Comment by bnasslahsen** [comment]
@bucknerns, 

 The link you have provided to the repo is broken.
 This ticket, will be closed, and can be reopened if you provide the relevant information.

**Comment by osya** [comment]
@bucknerns Am I right, that the root cause of this issue is `unknownFields` generated from protobuf? And to solve this issue it is needed to ignore protobuf unknownFields during serialization to JSON/YAML? How do you solve this issue?
