### ISSUE TITLE
Working reference is interpreted as broken

### ISSUE THREAD

**Issue by Sam-Kruglov** [springdoc/springdoc-openapi#944]
**Describe the bug**
My config ([api-docs.yaml.txt](https://github.com/springdoc/springdoc-openapi/files/5560400/api-docs.yaml.txt)):
```yaml
openapi: 3.0.1
paths:
  /api/users/self:
    get:
      tags:
      - users
      operationId: getMe
      responses:
        "200":
          description: OK
          content:
            '*/*':
              schema:
                type: string
        default:
          $ref: '#/components/responses/default'
components:
  schemas:
    ErrorResponse:
      type: object
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
  responses:
    default:
      description: other error responses
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
      $ref: '#/components/responses/default'
```

The important part is that an endpoint uses `$ref` to reference the `components/responses` which in turn uses `$ref` to go to `componenets/schemas`. And so that schema gets removed unless I set `springdoc.remove-broken-reference-definitions=false`. 

On a separate note, I noticed that `componenets.responses[0].$ref` is included in the yaml which is not supposed to be there.

Here's my java code (Spring Boot 2.4.0, Springdoc 1.5.0):
```java
    public static final String JWT_SECURITY_SCHEME = "jwt";

    private final List<CommonResponse> commonResponses = new LinkedList<>();

    @Bean
    public OpenAPI openApi() {
        val components = new Components();
        components.addSecuritySchemes(JWT_SECURITY_SCHEME,
                new SecurityScheme()
                        .type(Type.HTTP)
                        .scheme("bearer")
                        .bearerFormat("JWT")
        );
        addCommonSecurityResponses(components);
        addDefaultErrorResponse(components);
        return new OpenAPI()
                .components(components)
                .addSecurityItem(new SecurityRequirement().addList(JWT_SECURITY_SCHEME));
    }

    private void addDefaultErrorResponse(Components components) {
        val schema = createSchema(components, ErrorResponse.class);
        val key = ApiResponses.DEFAULT;
        val response = new ApiResponse()
                .$ref(key)
                .description("other error responses")
                .content(new Content().addMediaType(
                        org.springframework.http.MediaType.APPLICATION_JSON_VALUE,
                        new MediaType().schema(schema)
                ));
        components.addResponses(key, response);
        commonResponses.add(new CommonResponse(key, response.get$ref()));
    }

    private Schema<?> createSchema(Components components, Class<?> clazz) {
        val type = new AnnotatedType(clazz).resolveAsRef(true);
        val context = new ModelConverterContextImpl(ModelConverters.getInstance().getConverters());
        val schema = context.resolve(type);
        context.getDefinedModels().forEach(components::addSchemas);
        return schema;
    }

    @Value
    private static class CommonResponse {
        String httpStatusCode;
        String reference;
    }

    private void addCommonSecurityResponses(Components components) {
        Stream.of(HttpStatus.UNAUTHORIZED, HttpStatus.FORBIDDEN).forEach(securityError -> {
                    val httpCodeStr = String.valueOf(securityError.value());
                    val response = new ApiResponse()
                            .$ref(httpCodeStr)
                            .description(securityError.getReasonPhrase())
                            .addHeaderObject(
                                    HttpHeaders.WWW_AUTHENTICATE,
                                    new Header().description("https://tools.ietf.org/html/rfc6750#section-3")
                            )
                            .content(new Content());
                    components.addResponses(httpCodeStr, response);
                    commonResponses.add(new CommonResponse(httpCodeStr, response.get$ref()));
                }
        );
    }

    

    /**
     * see https://swagger.io/docs/specification/describing-responses/#reuse
     */
    @Bean
    OperationCustomizer defaultResponsesOperationCustomizer() {
        return ((operation, handlerMethod) -> {
            commonResponses.forEach(commonResponse -> {
                val response = new ApiResponse().$ref(commonResponse.getReference());
                operation.getResponses().addApiResponse(commonResponse.getHttpStatusCode(), response);
            });
            return operation;
        });
    }
```

**Comment by Sam-Kruglov** [comment]
I actually had to add `response.$ref(null);` after the response creation because my code generation tool didn't like it there

**Comment by bnasslahsen** [comment]
@Sam-Kruglov, 

 If your $ref is not referenced, it will not deleted.
 In the yaml, you have attached, you are having redundant definitions in the components section.
 You either should use $ref or the literal object definition, but not both.

**Comment by Sam-Kruglov** [comment]
@bnasslahsen could you clarify where you see a redundant definition? `ErrorReponse` component schema is referenced by `default` component schema which is in turn referenced by `getMe` operation.

**Comment by bnasslahsen** [comment]
this is an example
![image](https://user-images.githubusercontent.com/13404829/99879212-96ba8280-2c0b-11eb-9f1a-ebbbf41e3d33.png)

You are defining $ref as well ass the response attributes ...

**Comment by Sam-Kruglov** [comment]
@bnasslahsen yes, you are right. I mentioned it above, basically, I populated the `#ref` just to prepend the `#/components/responses/` string to the name but I see I better just prepend it myself.

**Comment by bnasslahsen** [comment]
@Sam-Kruglov, 

 Please make sure you describe the exact issue you are facing, and do not add any useless code.
 -  You should provide a [Minimal, Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example) - with HelloController that reproduces the problem.
 - Describe, what are the actual and the expected result using OpenAPI Description (yml or json)?


 There is no need to create multiple tickets for the same topic.
 This one, can be reopened, if you provide the relevant information.

**Comment by Sam-Kruglov** [comment]
@bnasslahsen sorry for the confusion, this ticket got steered in the wrong direction so I created a smaller more specific one.
I described 2 issues here, we only talked about 1, so I edited this and removed mentions of it.

**Comment by Sam-Kruglov** [comment]
I can't find my other issue I created, guess it got removed? Anyway, it is still visible here.
So, if you ignore the redundant `$ref`, the `ErrorResponse` schema gets removed by springdoc because it thinks it is not referenced anywhere, so I have to disable removal of broken references. However, as you can see, it is referenced like this: `paths/getMe` -> `responses/default` -> `schemas/ErrorResponse`. This approach is described here https://swagger.io/docs/specification/describing-responses/#reuse

**Comment by bnasslahsen** [comment]
@Sam-Kruglov, 

 By default, any broken references is removed. 
 You have a property, to disable this default behavior.
 
I am not sure to understand, what is your problem here.

**Comment by Sam-Kruglov** [comment]
@bnasslahsen paths/getMe -> responses/default -> schemas/ErrorResponse is **not** a broken reference but springdoc things that it is and removes the ErrorResponse. So, I think it's a bug

**Comment by bnasslahsen** [comment]
@Sam-Kruglov, 

 As Explained before, this is not a bug. Your definition is wrong.
 This line is useless:  `$ref: '#/components/responses/default'`
 Additionally, if you go to the swagger-editor, you will see the warning: **sibling values alongside refs are ignored**

![image](https://user-images.githubusercontent.com/13404829/99914387-6ce18880-2cfd-11eb-8e02-f1d6d9ebc022.png)

**Comment by Sam-Kruglov** [comment]
@bnasslahsen as I also explained above, ignore that, even if my definition is as following, ErrorResponse is still getting removed
```
default:
      description: other error responses
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
```

**Comment by bnasslahsen** [comment]
ok, i am ignoring this issue.
Please make sure you respect the [contribution guide ](https://github.com/springdoc/springdoc-openapi/blob/master/CONTRIBUTING.adoc), before opening any new issue.
