### ISSUE TITLE
Ways to create an object schema from model

### ISSUE THREAD

**Issue by ashviswam** [springdoc/springdoc-openapi#945]
I want to create a global header parameter and map it to the schema of a  model that is not used elsewhere in the application. Though the model is annotated with @Schema, it is not generated under components. Hence I cannot refer to it by:
`
ObjectSchema mySchema = new ObjectSchema();  
  mySchema
  .type("object")
  .$ref("#/components/schemas/MyRequest")
  .name("MySchema")`

Is there a feature like ModelRef in Springfox, whereby you can create a schema out of Object type. 
`            .additionalModels(typeResolver.resolve(ExceptionDto.class))
`

**Comment by bnasslahsen** [comment]
@ashviswam, 

 You can see the answer here: https://github.com/springdoc/springdoc-openapi/issues/790
