### ISSUE TITLE
Need alternative for springfox  Docket.directModelSubstitute(final Class clazz, final Class with)

### ISSUE THREAD

**Issue by asuri3** [springdoc/springdoc-openapi#946]
- In springfox, we can substitute model generically by calling this method
public Docket directModelSubstitute(final Class clazz, final Class with) 

Ex: .directModelSubstitute(LocalTime.class, String.class) -> Will use String implementation at all places wherever we have LocalTime

In springdoc-openapi UI, we can do it only by providing an implementation in @Schema() on the attribute.

but I don't wanna do this at all places manually. There should be a generic way to substitute a class with another class.

Can we have the same feature in springdoc-openapi?

**Comment by bnasslahsen** [comment]
@asuri3, 

 You can have a look at: `SpringDocUtils.getConfig().replaceWithClass`
 Example, is available here:
 - https://springdoc.org/#spring-data-rest-support

**Comment by asuri3** [comment]
Tried the same but seems like there is a bug in the implementation.

```
   SpringDocUtils.getConfig()
        .replaceWithClass(ZoneId.class, String.class);

 @Schema(example = "America/New_York" )
  private ZoneId locale;

```
Swagger UI -> 
"locale": "string",

now instead of  having the example value as "America/New_York", "string" is coming on UI

Initially, I was adding implementation in schema annotation, and the example was coming properly on UI.
@Schema(implementation = String.class, example = "America/New_York" )
  private ZoneId locale;

**Comment by asuri3** [comment]
there are few examples on my swagger UI which were populating correctly in springfox but after the switch to springdoc, examples are not coming properly.
In a few places, for LocalTime, on UI the type is shown as LocalTime but the example value is a Map {} which is weird. as I provided an example in @Schema annotation but it's showing an example of another attribute from the same request
