### ISSUE TITLE
swagger paths filter not work

### ISSUE THREAD

**Issue by raoyjhahah** [springdoc/springdoc-openapi#947]
In the process of using springboot to integrate swagger, I clearly configured paths filtering, but it does not take effect. The following is my code, help me!

`
swagger:
  basePackage: com.makeit.controller.api
  antPath : /auth/department/**         
`

`
@EnableSwagger2
@Configuration
@ConfigurationProperties(prefix = "swagger")
//@ConditionalOnProperty(prefix = "spring",value = {"profiles.active"},havingValue = "dev")
public class Swagger2Config {

    private String basePackage;
    private String antPath;
    private String title;
    private String description;
    private String serviceUrl;
    private String version;
    private Boolean enable;
    private String contactName;
    private String contactEmail;
    private String contactUrl;
    private String license;
    private String licenseUrl;

    /**
     * 
     *
     * @return
     */
    @Bean
    public Docket api() {
        Docket docket = new Docket(DocumentationType.SWAGGER_2)
                .apiInfo(apiInfo())
                //
                .enable(enable);
        ApiSelectorBuilder builder = docket.select();
        //
        builder = builder.apis(Predicates.or(apisFilter()));
        //
        if (!StringUtils.isEmpty(antPath)) {
            builder = builder.paths(PathSelectors.ant(antPath));
        }
        return builder.build();
    }
`
In addition, I also integrated SpringSecurity,Will it have an impact?
`
@Configuration
@EnableWebSecurity
public class WebSecurityConfig  extends WebSecurityConfigurerAdapter  {

    @Override
    protected void configure(HttpSecurity http) throws Exception {

  
    	http.authorizeRequests().anyRequest().permitAll().and().logout().permitAll();
    	
    	http.authorizeRequests().anyRequest().permitAll().and().csrf().disable();
    }
}

`

**Comment by bnasslahsen** [comment]
@raoyjhahah, 

 Your code is not related to springdoc-openapi project.
