### ISSUE TITLE
Kotlin List of MultipartFile not recognised

### ISSUE THREAD

**Issue by johkin** [springdoc/springdoc-openapi#95]
After reviewing the details of #11 I found an issue with ParameterBuilder when using Kotlin to generate a file-upload endpoint.
Since Kotlin handles variance in a slightly different way than Java, the generated bytecode of a Kotlin kotlin.collections.List<MultipartFile> is actually a java.util.List<? extends MultipartFile>
(java.util.List<? extends org.springframework.web.multipart.MultipartFile>)

I guess this could be solved by using a WildcardType as an argument in the isFile-method, but I'm not sure how to handle this correctly.

A work-around in my code is to use java.util.List<MultipartFile> instead of kotlin.collections.List

**Comment by springdoc** [comment]
Hi, 

 A fix is available on v1.1.44 of springdoc-openapi release.
 Can you please test it and give us your feedback?

**Comment by johkin** [comment]
Looks good! Thanks!
