### ISSUE TITLE
Customize Swagger-ui appearance

### ISSUE THREAD

**Issue by andrey-nakin** [springdoc/springdoc-openapi#951]
It would be great to have a way to customize Swagger-UI appearance. For example, via user-defined stylesheets and scripts.

At a very minimum, I'd like to change the SwaggerUI logo and colors on the top of the documentation page.

**Comment by bnasslahsen** [comment]
@andrey-nakin, 

 springdoc-openapi relies on the swagger-ui webjars.
 If you want to customise the ui, here is what you can do: 

 - Exclude the swagger-ui webjars dependency:
```xml
<dependency>
    <groupId>org.springdoc</groupId>
    <artifactId>springdoc-openapi-ui</artifactId>
    <version>1.5.0</version>
    <exclusions>
        <exclusion>
            <groupId>org.webjars</groupId>
            <artifactId>swagger-ui</artifactId>
        </exclusion>
    </exclusions>
</dependency>
```

 - Copy the content of the corresponding swagger-ui dist from [github]( https://github.com/swagger-api/swagger-ui/tree/v3.37.0/dist), or directly unzip the [swagger-ui webjar](https://mvnrepository.com/artifact/org.webjars/swagger-ui/3.37.0): 
  
   Into -> classpath:/META-INF/resources/webjars/swagger-ui 

 Then feel free to customize all the resources as you like :)

**Comment by MostafaaRamadan** [comment]
can you specify how this can be done in gradle, thanks in advance

**Comment by MostafaaRamadan** [comment]
For Gradle the dependency should like this

```
	// Spring doc swagger ui
	implementation("org.springdoc:springdoc-openapi-ui:${springDocVersion}") {
		exclude group: "org.webjars", module: "swagger-ui"
	}
```

And then create it under the resources folder (/META-INF/resources/webjars/swagger-ui) each on is directory inside each other
```
- META-INF
  - resources
     - webjars
        - swagger-ui 
```
        
and copy the swagger dist folder content inside this, run gradle clean build
