### ISSUE TITLE
ExternalDocumentation does not show anymore the doc's url in 1.5.0

### ISSUE THREAD

**Issue by marichka-spin** [springdoc/springdoc-openapi#955]
Description:
I've upgraded springdoc version from 1.3.9 -> 1.5.0 but urls of tags external documentation are not visible anymore

With version 1.3.9
<img width="1405" alt="Знімок екрана 2020-11-26 о 17 07 12" src="https://user-images.githubusercontent.com/5120736/100366769-ee8d2b00-3009-11eb-95be-972341213829.png">

With version 1.5.0
<img width="1420" alt="Знімок екрана 2020-11-26 о 17 06 57" src="https://user-images.githubusercontent.com/5120736/100366831-02389180-300a-11eb-9fbc-62c689981abc.png">

**Expected behavior**
Urls of tags external documentation should be visible

**Comment by bnasslahsen** [comment]
@marichka-spin, 

 This is not related to springdoc-openapi.

 This is already answered here.  https://github.com/springdoc/springdoc-openapi/issues/871
