### ISSUE TITLE
Setting server.servlet.context-path programmatically

### ISSUE THREAD

**Issue by knyttl** [springdoc/springdoc-openapi#956]
**Is your feature request related to a problem? Please describe.**

Our spring application is fully configured either via environment variables or directly in the code. We are not using `application.properties` file. It seems that setting custom `context-path` is only possible with the `properties` file.

**Describe the solution you'd like**

I would like to be able to set the context path programmatically, eg.

```kotlin
      OpenAPI()
            .info()
            .setContextPath("...")
```

**Describe alternatives you've considered**

I tried setting the property on the class init:
```kotlin
    init {
        System.setProperty("server.servlet.context-path", "/services/$SERVICE_NAME")
    }
```

or just before the open Api initialization:

```kotlin
    @Bean
    open fun api(): OpenAPI {
        System.setProperty("server.servlet.context-path", "/services/$SERVICE_NAME")
        return OpenAPI()...
```

However that has no effect.

**Comment by bnasslahsen** [comment]
@knyttl, 

 `server.servlet.context-path` is a standard spring-boot property, and not a springdoc-openapi property.
 You can have a look at the spring-boot documentation, or use stackoverflow under the spring-boot tag.
