### ISSUE TITLE
Does springdoc support type rules similar to springfox?

### ISSUE THREAD

**Issue by affanshahid** [springdoc/springdoc-openapi#958]
Springfox allows "type rules" to allow generic customization of the generated doc. For example `Iterable<T>` is not natively recognized by springfox (or springdoc apparently) but using the following:

```java
...
.alternateTypeRules(newRule(resolver.resolve(Iterable.class, WildcardType.class),
                        resolver.resolve(List.class, WildcardType.class)))
```

I can tell springfox to treat `Iterable<T>` as a `List<T>`. Does something similar exist here?

**Comment by bnasslahsen** [comment]
You can use:

```java
SpringDocUtils.getConfig().replaceWithClass(targetClass,replacementClass);
SpringDocUtils.getConfig().replaceWithSchema(targetClass,replacementSchema);
```

Alternatively, you declare a Spring bean of type ModelConverter.

You can see the example here for Vavr / Guava, that you can adapt for Iterable, if you want something generic:  https://github.com/springdoc/springdoc-openapi/issues/712

**Comment by chakilamt** [comment]
Not working from the above approach.
