### ISSUE TITLE
@ApiImplicitParam( dataTypeClass = String.class)如何使用@Parameter替代

### ISSUE THREAD

**Issue by YAGAMIL** [springdoc/springdoc-openapi#960]
When I use springfox, I can specify the data type of the mapping by @ApiImplicitParam( dataTypeClass = String.class) or @ApiParam(type = ""), but when I use @Parameter, I did not find an alternative

**Comment by bnasslahsen** [comment]
@YAGAMIL, 

 You can read the documentation of [swagger-annotation](https://github.com/swagger-api/swagger-core/wiki/annotations) instead.

**Comment by YAGAMIL** [comment]
> @YAGAMIL，
> 
> 您可以改为阅读[夸张注释的文档](https://github.com/swagger-api/swagger-core/wiki/annotations)。

No, no, I mean, when I migrated from springfox to springdoc-openapi, I encountered a problem, and the link you sent me did not have the annotations under oas3

**Comment by bnasslahsen** [comment]
@YAGAMIL, 

 The link is updated. 
 Please read the[ contribution guide ](https://github.com/springdoc/springdoc-openapi/blob/master/CONTRIBUTING.adoc)before opening issues.
