### ISSUE TITLE
SpringdocRouteBuilder redundant parameter

### ISSUE THREAD

**Issue by Sam-Kruglov** [springdoc/springdoc-openapi#968]
During nesting, there is a redunant operation builder consumer, which I always leave empty. Does that have any purpose in mind? 
```kotlin
SpringdocRouteBuilder.route()
          .nest(
                  RequestPredicates.path("/users").and(RequestPredicates.accept(APPLICATION_JSON)),
                  Supplier {
                    SpringdocRouteBuilder.route()
                            .GET("", userHandler::getById, Consumer { it.beanClass(UserService::class.java).beanMethod("getById") })
                            ...
                            .build()
                  },
                  {} // what's the point of that?
          ).build()
```

**Comment by bnasslahsen** [comment]
@Sam-Kruglov, 

It's not required to use `SpringdocRouteBuilder.route().nest()`,  unless you want to add attributes to the resulting nested route as well.

If you only need to add attributes for Routes that are defined as parameter of nest, you can use `RouterFunctions.nest`, which is more relevant in this case.

You can see some code samples for the nest: 
 - https://github.com/springdoc/springdoc-openapi/blob/f99176f4687b23095f357b642ac54ea8ee34bf17/springdoc-openapi-webflux-core/src/test/java/test/org/springdoc/api/app90/book/BookRouter.java#L62

**Comment by Sam-Kruglov** [comment]
Well, I could do `SpringdocRouteBuilder.route().GET(...).GET(...).PUT(...).build().and(RouterFunctions.nest(...))` but I would rather do `SpringdocRouteBuilder.route().GET(...).GET(...).PUT(...).nest(...).build()` it would look better. Just adding one overloaded `SpringdocRouteBuilder#nest` without operation customizer would be nicer IMO

**Comment by bnasslahsen** [comment]
Nothing prevents you from submitting your proposal, if you estimate it will be more handy from developer perspective.

**Comment by Sam-Kruglov** [comment]
FYI just found that the suggested solution does not work for 2+ level nesting. If I nest to `/users` and then deeper I nest to `/groups` then this `.build().and(nest(...))` will result in `/groups` url. It is required to do `.nest(...).build()` to get `/users/groups`

**Comment by bnasslahsen** [comment]
@Sam-Kruglov, 

 This should work out of the box. If it's not the case, there is an issue there...
