### ISSUE TITLE
How to add additional documentation from JSON? 

### ISSUE THREAD

**Issue by siller174** [springdoc/springdoc-openapi#97]
Hello, I have a question. Looks like swagger.v3 doesn't automatically document spring-ws endpoints (websocket). I didn't find any solution how to document it manually, so I decided to write Swagger JSON doc manually, serve it as a static content and add it to  swagger-ui.html page. 
Now I want to add it in the application the code. Could you tell me how to do this? Or how to add endpoints to existing generated documentation manually?

**Comment by springdoc** [comment]
Hi, 

 There is no official support for websockets, on OpenAPI 3. 
 We support OpenAPI 3.0 specification for Rest APIs. 
 If you want use callbacks you can define them using swagger annotations: https://swagger.io/docs/specification/callbacks/

**Comment by alexey-atiskov** [comment]
Hmm seems like question was more about "How to add additional documentation from JSON" (not only websockets)...
