### ISSUE TITLE
Response validation, especially for null properties

### ISSUE THREAD

**Issue by xeoneux** [springdoc/springdoc-openapi#972]
If my class is marked with a not null attribute, the generated openapi spec has the property as required. However, spring still responds with the object that has those null properties. Will springdoc support such response validation and throw an error (maybe during development) when the generated schema does not match the response body?

**Comment by Sam-Kruglov** [comment]
I think Spring doesn't validate responses, only requests. https://stackoverflow.com/questions/46213935/how-to-validate-spring-boot-rest-response

If you use Lombok, you could specify `@lombok.NonNull` on the response fields and then Lombok itself will throw an error on object creation. I think it will also be picked up by SpringDoc by matching via annotation's simple class name, it's mentioned in `io.swagger.v3.core.jackson.ModelResolver#NOT_NULL_ANNOTATIONS`

**Comment by bnasslahsen** [comment]
@xeoneux, 

 Your feature request is not clear.

 You can try being more explicit by providing code samples that cover:
-  The actual and the expected result using OpenAPI Description (yml or json)
 - Provide a [Minimal, Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example) - with HelloController that describes your feature

This ticket will be now closed, and can be reopened if you provide the relevant information.

**Comment by Sam-Kruglov** [comment]
@xeoneux just FYI lombok's annotation won't be picked up because it doesn't exist at runtime
