### ISSUE TITLE
root endpoint documentation is not generated

### ISSUE THREAD

**Issue by arysin** [springdoc/springdoc-openapi#974]
**Describe the bug**
I have root endpoint defined with controller 
`    @RequestMapping(value = {"", "/"},
            method = {RequestMethod.GET, RequestMethod.HEAD}, 
            produces = { APPLICATION_JSON_VALUE }
            )
`
and the documentation is not getting generated

**To Reproduce**
- sping-boot 2.1.18
- springdoc-opeapi 1.5.0

openapi json missing root endpoint

**Expected behavior**
root endpoint should be generated along all other eddpoints

**Comment by bnasslahsen** [comment]
Not reproducible.

Make sure you provide a [Minimal, Reproducible Example - with HelloController](https://stackoverflow.com/help/minimal-reproducible-example) that reproduces the problem.
This ticket is now closed, and can be reopened if any relevant information is provided.

**Comment by azige** [comment]
I encountered same problem and found the reason is my root mapping doesn't have `@ResponseBody`(it's a forward).
  
    // kotlin
    @Controller
    class HelloController {
        @GetMapping("/")
        @Operation(summary = "root endpoint")
        fun hello(): String = "forward:/message"
    
        @GetMapping("/message")
        @Operation(summary = "give some message")
        @ResponseBody
        fun message(): String = "hello"
    }

How should I expose such endpoints? `SpringDocUtils.getConfig().addRestControllers(HelloController.class)` does not work for this.

**Comment by bnasslahsen** [comment]
@azige, 

 It's explained in the [documentation](https://springdoc.org/#my-rest-controller-using-controller-annotation-is-ignored) how to achieve this.

 And if you are still struggling, make sure you provide a [Minimal, Reproducible Example - with HelloController](https://stackoverflow.com/help/minimal-reproducible-example) that reproduces the problem.

**Comment by azige** [comment]
Yes, I read the document. I just want to find a way to expose a endpoint without `@ResponseBody`. In real world project that thing forward to something out of Spring MVC. I'm not sure whether I missed something or it's a missing feature.

**Comment by bnasslahsen** [comment]
@azige, 

 This doesn't seem to be a missing feature ...

**Comment by azige** [comment]
I'm searching the document. The only way to expose such endpoints is using `OpenApiCustomiser` to configure the OpenAPI model manually I guess?

I tried springfox before and it does expose such endpoints as long as they annotated `@ApiOperation`. But when I migrate to sprindoc, it's gone. 😞

**Comment by bnasslahsen** [comment]
This is not the only way. 
You can use `SpringDocUtils.getConfig().addRestControllers(HelloController.class);` as explained in the documentation.

As mentioned before, if you are still struggling, just provide a [Minimal, Reproducible Example - with HelloController](https://stackoverflow.com/help/minimal-reproducible-example) that reproduces the problem.

**Comment by arysin** [comment]
I've got rid of some missing api docs when using springdoc by changing my `@Controller` to `@RestController`

**Comment by azige** [comment]
@bnasslahsen Thanks for your replays and sorry for my bad writing. Let me make a summary.

Current situation:
1. SpringDoc only picks methods with `@ResponseBody`
2. There are reasons a method can not be annotated `@ResponseBody`
3. I want such methods included in OpenAPI model.

What I expected:
1. A method should be picked and included in OpenAPI model as long as it annotated `@RequestMapping` and `@Operation`

There are detailed codes to describe what I want.

    // kotlin
    // The class can not be @RestController or every method is implicit @ResponseBody
    @Controller
    class HelloController {
        // I want this to be included in OpenAPI model
        // but it cannot be annotated @RequestBody as it uses "forward:"
        // and SpringDocUtils.getConfig().addRestControllers(HelloController.class) does not work
        @GetMapping("/")
        @Operation(summary = "root endpoint")
        fun hello(): String = "forward:/message"
    
        // This is included in OpenAPI model
        @GetMapping("/message")
        @Operation(summary = "give some message")
        @ResponseBody
        fun message(): String = "hello"
    }

I can provide a full project with a failing test if need.

I'm not sure whether my case is rare. I implemented a OpenAPI generator my own and it picks every method with `@RequestMapping` and `@MyOperationAnno`. SpringFox has similar behaviours too.

**Comment by bnasslahsen** [comment]
Yes add the Sample project reproducing what you describe.

**Comment by azige** [comment]
Wait, sorry I found the cause is I put `SpringDocUtils.getConfig().addRestControllers(HelloController.class)` in the spring boot main method and the test didn't execute that.

It does work with `SpringDocUtils.getConfig().addRestControllers(HelloController.class)`.

Excuse me but I'm curious why using a static class config rather than a config bean? And still, I hope a method to be picked as long as it annotated `@RequestMapping` and `@Operation` without any further configuration.

**Comment by bnasslahsen** [comment]
Good that you finally make it work.
The config class is a Singleton, so the simple way have access to it is with the static access to the singleton Instance.

**Comment by azige** [comment]
@bnasslahsen Sorry for taking your time. What about the other opnion of mine? Is it worth opening a new issue to discuss?

**Comment by bnasslahsen** [comment]
which option ?

**Comment by azige** [comment]
A method annotated `@RequestMapping` and `@Operation` should be included in generated OpenAPI model by default without any further configuration.

In short, users expect thier methods be picked or why they annotate it `@Operation`?

**Comment by bnasslahsen** [comment]
It is the case ..., if your application is well configured.
Are you sure you haven't forgotten to annotate the controller or missed any other configuration as you did previously with the `static` initialisation ?

Note that there are no know issues with `@RequestMapping`. 

If you think you are facing an issue, make sure you add the **Sample project** reproducing what you describe.

**Comment by azige** [comment]
I upload the project and the key point is here https://github.com/azige/springdoc-demo/blob/master/src/main/kotlin/com/example/demo/HelloController.kt#L33

**Comment by bnasslahsen** [comment]
I have seen your project now.
There is no `@RequestMapping` on it.

About your comments: I have answered each.
   - SpringDoc won't pick a method without `@ResponseBody` by default: 
     - Springdoc only scans for the REST Controllers, ie`@RestController` annotations which is equivalent to :`@Controller `+ `@ResponseBody`
   -  It can be picked if there is SpringDocUtils.getConfig().addRestControllers(HelloController.class):
      - Extra Controllers, for example with only @Controller annotation, could be added By declaring them in the configuration class. Why that? Because, `@Controller`annotation is on only for exposing REST APIs...
  
Note, that i will delete this issue by the end of the day as this is not the[ right place f](https://github.com/springdoc/springdoc-openapi/blob/master/CONTRIBUTING.adoc)or asking questions.

**Comment by azige** [comment]
> There is no `@RequestMapping` on it.

I mean meta annotation on `@GetMapping` etc.

> Springdoc only scans for the REST Controllers, ie`@RestController` annotations which is equivalent to :`@Controller` + `@ResponseBody`

Yes and methods with `@ResponseBody` in a `@Controller` do get picked. I think it makes more sense any `@Operation` in a `@Controller` get picked as `@RestController` is just a shortcut. I have explained even in a REST controller there may be methods can not be annotated `@ResponseBody`(and so the class can not be `@RestController`)

I think the problem is SpringDoc not only picking methods in `@RestController` but any `@ResponseBody` in `@Controller`. Users get confused why some methods in `@Controller` get picked but others are not if they don't know this mechanism.

**Comment by bnasslahsen** [comment]
@azige, 

 Good you are understanding now the purpose of the library.
 And if you want to add any enhancement, you could just propose a PR!

 Make sure if you need to create any ticket, to respect the [contribution guide](https://github.com/springdoc/springdoc-openapi/graphs/contributors).

 This will help us speedup problems diagnosis.

 I will delete now this ticket.
