### ISSUE TITLE
@ExtensionProperty generates property on the field class not the field itself

### ISSUE THREAD

**Issue by arysin** [springdoc/springdoc-openapi#975]
**Describe the bug**
When `@ExtensionProperty` is applied to a field with a referenced class springdoc moves that property to the class itself (but that class could be used without property in other places so it's not correct)

**To Reproduce**
- sping-boot 2.1.18
- springdoc-opeapi 1.5.0

`
    @Schema(description="Number of time points", required=false, accessMode = AccessMode.READ_ONLY,
            extensions = { @Extension(properties = { @ExtensionProperty(name =  SwaggerConstants.INTERNAL, value = "true") }) }
    )
    private int timePointCount;
    @Schema(description="maximum time point", required=false, accessMode = AccessMode.READ_ONLY,
            extensions = { @Extension(properties = { @ExtensionProperty(name =  SwaggerConstants.INTERNAL, value = "true") }) }
    )
    private TimePoint maxTimePoint;
`

What I get is
`
          "timePointCount": {
            "type": "integer",
            "description": "Number of time points",
            "format": "int32",
            "readOnly": true,
            "x-internal": "true"
          },
          "maxTimePoint": {
            "$ref": "#/components/schemas/TimePoint"
          }, 
...
      "TimePoint": {
...
        "readOnly": true,
        "x-sas-internal": "true"
      }, `

**Expected behavior**

What I expect is:
`
          "timePointCount": {
            "type": "integer",
            "description": "Number of time points",
            "format": "int32",
            "readOnly": true,
            "x-internal": "true"
          },
          "maxTimePoint": {
            "$ref": "#/components/schemas/TimePoint",
            "x-internal": "true"
          }, 
...
      "TimePoint": {
...
        "readOnly": true
      }, 
`

**Comment by bnasslahsen** [comment]
same answer as: https://github.com/springdoc/springdoc-openapi/issues/974

**Comment by arysin** [comment]
* run `gradlew bootRun`
* open http://localhost:8080/api/v3/api-docs
* observe: 'x-internal' applied to the whole class Other
* 'x-internal' should be only applied to to the field 'other' in Api (as Api2 does not this class as 'x-internal')
[springdoc-example.zip](https://github.com/springdoc/springdoc-openapi/files/5655424/springdoc-example.zip)

**Comment by bnasslahsen** [comment]
you can read the explanation and the workaround of what you are facing here: https://github.com/springdoc/springdoc-openapi/issues/685#issuecomment-636028451
