### ISSUE TITLE
Only one endpoint shown when using params in @Postmapping

### ISSUE THREAD

**Issue by svenkost** [springdoc/springdoc-openapi#977]
I have a SpringBoot project with multiple controllers. One of the controllers has 2 `@Postmappings`, which only difference is in the `params` parameter.

I'm using SpringBoot 1.5.9 and springdoc-openapi version 1.5.1. 

The problem now is that there is only one of the endpoint is documented. It is the first one in the code, but with parameters of the second one. The framework can't handle the `params` differentiation between endpoints.

I would expect two endpoints documented and not just one, with the right parameters.

<img width="1110" alt="Screen Shot 2020-12-09 at 8 00 50" src="https://user-images.githubusercontent.com/6765152/101591279-d8617080-39f4-11eb-81e5-c3482c8ee7ed.png">

**example:**
```java
package com.svenkost.resource;

import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.tags.Tag;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RestController;

import javax.servlet.http.HttpServletRequest;

@RestController
public class SampleController {

    @PostMapping(value = "/api/test/{user}/myauth", consumes = MediaType.APPLICATION_FORM_URLENCODED_VALUE, 
            produces = { MediaType.APPLICATION_JSON_VALUE },params = {"code"})
    @Tag(name = "Get authorization")
    public ResponseEntity<String> auth(HttpServletRequest request,
                                                    @Parameter(name="user", description = "The user to get authorization", required = true) @PathVariable("user") final String user) throws Exception {
        // do something
        return null;
    }

    @PostMapping(value = "/api/test/{user}/myauth", consumes = MediaType.APPLICATION_FORM_URLENCODED_VALUE, 
            produces = { MediaType.APPLICATION_JSON_VALUE },params = {"refresh"})
    @Tag(name = "Get refreshed authorization")
    public ResponseEntity<String> refresh(HttpServletRequest request,
                                                       @Parameter(name="user", description = "The user to get refreshed authorization", required = true) @PathVariable("user") final String user) throws Exception {
        // do something
        return null;
    }
}
```

**Comment by bnasslahsen** [comment]
@svenkost, 

 You will get one endpoint shown.

 OpenAPI defines a [unique operation as a combination of a path and an HTTP method](https://swagger.io/docs/specification/paths-and-operations/):
-  This means that two POST methods for the same path are not allowed – even if they have different parameters (parameters have no effect on uniqueness)
