### ISSUE TITLE
Inconsistent sorting criteria object (Pageable's sort)

### ISSUE THREAD

**Issue by jernejcvek** [springdoc/springdoc-openapi#979]
**Bug description**
`Pageable` holds inconsistent `sort` object of type `List<String>`.  Please see the following examples:
- query parameter: `?sort=id`, sort object: `["id"]`, size of the object: 1
- **query parameter: `?sort=id,desc`, sort object: `["id", "desc"]`, size of the object: 2**
- query parameter: `?sort=id,desc&sort=name`, sort object: `["id,desc", "name"]`, size of the object: 2
- query parameter: `?sort=id,desc&sort=name,desc`, sort object: `["id,desc", "name,desc"]`, size of the object: 2
- query parameter: `?sort=id,desc&sort=name,desc&sort=address`, sort object: `["id,desc", "name,desc", "address"]`, size of the object: 3
- query parameter: `?sort=id,desc&sort=name,desc&sort=address,desc`, sort object: `["id,desc", "name,desc", "address,desc"]`, size of the object: 3

**Versions and usage**
- Spring Boot `2.2.2`
- **springdoc-openapi-ui** & **springdoc-openapi-data-res**t: 1.4.8
- Controller's method is annotated with `@PageableAsQueryParam`, with hidden method's parameter: `@Parameter(hidden = true) Pageable pageable` so that pagination and sorting criteria are properly shown in the UI:
![swagger-ui-sort](https://user-images.githubusercontent.com/18633393/101641995-c0104680-3a32-11eb-919a-aa14f9a11c43.png)
- Example of Swagger UI's generated request URL for the problematic case: `...&page=0&size=20&sort=id%2Cdesc`

**Expected behaviour**
- When the query parameter is `sort=id,desc` (bolded example above) the `Pageable`'s sort object should contain only one element `["id,desc"]`.

**Comment by bnasslahsen** [comment]
@jernejcvek, 

 Not sure what issue you are pointing out here.
 Anyway, this doesn't seem related to the OpenAPI spec, which is generated by the springdoc-openapi.

 If you think, there is any isseu, please make sure all the information described in the [contribution guide](https://github.com/springdoc/springdoc-openapi/blob/master/CONTRIBUTING.adoc).

 If you are having issues with the UI. You can have at the [swagger-ui ](https://github.com/swagger-api/swagger-ui/issues)project instead.
