### ISSUE TITLE
Change behaviour to not overwrite an existing common schema. 

### ISSUE THREAD

**Issue by davidmelia** [springdoc/springdoc-openapi#98]
Hi,

I use micro types as controller path variables and if I define a microtype as 
```
public class TweetId {
  private final String value;
  public TweetId(String value) {
    this.value = value;
  }
  public String getValue() {
    return value;
  }
}
```
and controller as 
```
  @GetMapping("/tweets/{id}")
  public Mono<Tweet> getTweet(@PathVariable TweetId id) {
    return Mono.just(new Tweet("hello"));
  }
```
and define TweetId as a common string schema
```
  @Bean
  public OpenAPI customOpenAPI() {
    return new OpenAPI()
        .components(new Components()
            .addSchemas("TweetId", new StringSchema()));
  }
```
so that I can use this throughout my API.

Problem is spring doc overwrites my common string schema creating an object schema which messes up swagger :
```
TweetId: {
  type: "object",
  properties: {
       value: {
       type: "string"
   }
  }
},
```

One way around this is to define the schema like so

 @GetMapping("/tweets/{id}")
  public Mono<Tweet> getAllTweets( @PathVariable  @Parameter(schema = @Schema(ref = "#/components/schemas/TweetId")) TweetId id) {
    return Mono.just(new Tweet("hello"));
  }

but would it be possible for springdoc to check if the schema already exist and if it does to **not** overwrite it.  This will cut down on boiler plate annotations.

Thanks

**Comment by springdoc** [comment]
Hello, 

 This enhancement, will be available on v1.1.44 of springdoc-openapi release.
