### ISSUE TITLE
Functional DSL incorrect path mapping

### ISSUE THREAD

**Issue by Sam-Kruglov** [springdoc/springdoc-openapi#980]
**Describe the bug**
When I try to do deep nesting (deeper than 1 level), the path mappings "go wild".

**To Reproduce**
- What version of spring-boot you are using?
   2.4.0
- What modules and versions of springdoc-openapi are you using?
   1.5.0 of webflux-ui, kotlin, and security
- Provide with a sample code (HelloController) or Test that reproduces the problem
```kotlin
class Handler{
  suspend fun getUsers(request: ServerRequest) = ServerResponse.ok().buildAndAwait()
  suspend fun getUserGroups(request: ServerRequest) = ServerResponse.ok().buildAndAwait()
}

@Bean
fun routeDocs(): RouterFunction<ServerResponse> = Handler().let{ handler ->
  RouterFunctions.nest(
    path("/users"),
    SpringdocRouteBuilder.route()
        .GET("", asHandlerFunction(handler::getUsers), {it.operationId("get-users")})
        .POST("/special", asHandlerFunction(handler::getUsers), {it.operationId("create-user-special")})
        .nest(
            path("/groups"),
            Supplier {
              SpringdocRouteBuilder.route()
                  .GET("", asHandlerFunction(handler::getUserGroups), {it.operationId("get-user-groups")})
                  .POST("/special", asHandlerFunction(handler::getUserGroups), {it.operationId("create-user-group-special")})
                  .build()
            },
            {}
        ).build()
)}
```
- What is the actual and the expected result using OpenAPI Description (yml or json)?
actual:
```yaml
paths:
  /users:
    get:
      operationId: get-users_1
      responses: {}
  /users/groups:
    post:
      operationId: create-user-special
      responses: {}
  /users/special:
    post:
      operationId: create-user-group-special
      responses: {}
```
expected:
```yaml
paths:
  /users:
    get:
      operationId: get-users #DIFF
      responses: {}
  /users/special: #DIFF
    post:
      operationId: create-user-special
      responses: {}
  /users/groups: #DIFF
    get: #DIFF
      operationId: get-user-groups #DIFF
      responses: {} #DIFF
  /users/groups/special: #DIFF
    post:
      operationId: create-user-group-special
      responses: {}
```

**Expected behavior**
- A clear and concise description of what you expected to happen.
  The paths are way off as you can see, also, operation id gets changed for some reason.
- What is the expected result using OpenAPI Description (yml or json)? 
   above

**Additional context**
I also tried to call these requests and WebFlux resolves all paths correctly, so the error is only displayed in the open API, the requests work fine.

**Comment by bnasslahsen** [comment]
@Sam-Kruglov, 

 This is now fixed. You can test it using the last SNAPSHOT.

**Comment by indanit** [comment]
@Sam-Kruglov How did you make it work with suspend functions? Where is `asHandlerFunction` coming from?

**Comment by Sam-Kruglov** [comment]
@indanit copied from ‘org.springframework.web.reactive.function.server.CoRouterFunctionDsl’ or ‘org.springframework.web.reactive.function.server.RouterFunctionDsl’
