### ISSUE TITLE
Handle custom JsonSerializers

### ISSUE THREAD

**Issue by hookumsnivy** [springdoc/springdoc-openapi#981]
**Background:**
The default serialization for Spring's org.springframework.data.domain.Page class is less than ideal (not worth going into detail here). I therefore created a custom serializer using @JsonComponent with Spring Boot. The application automatically picks it up and serializes the response properly. 
However, when viewing the Example value and schema in the swagger-ui for the controller returning a Page, it uses the default format and it looks like this:
```
PageComponentInfoDto{
  totalPages	integer($int32)
  totalElements	integer($int64)
  first	boolean
  size	integer($int32)
  content	[...]
  number	integer($int32)
  sort	Sort{...}
  numberOfElements	integer($int32)
  pageable	Pageable{...}
  last	boolean
  empty	boolean
}
```
With the example looking like this:
```
{
  "totalPages": 0,
  "totalElements": 0,
  "first": true,
  "size": 0,
  "content": [
    {
      "id": 0,
      "name": "string"
    }
  ],
  "number": 0,
  "sort": {
    "sorted": true,
    "unsorted": true,
    "empty": true
  },
  "numberOfElements": 0,
  "pageable": {
    "page": 0,
    "size": 0,
    "sort": [
      "string"
    ]
  },
  "last": true,
  "empty": true
}
```

Maybe there is a way to handle this already and I'm missing it, but I would like the example value and the schema to match the actual JSON format produced.
I looked into `SpringDocUtils.getConfig().replaceWithClass` but we're dealing with generics too which complicates it a bit.

**Comment by hookumsnivy** [comment]
In the short term, I came up with my own solution - custom object.

**Comment by bnasslahsen** [comment]
For custom mapping, you can just declare a bean that implements `ModelConverter`.
You have here some `ModelConverter` [sample code](https://github.com/springdoc/springdoc-openapi/tree/master/springdoc-openapi-common/src/main/java/org/springdoc/core/converters);
