### ISSUE TITLE
Wrong request body when mixing POJO and FilePart

### ISSUE THREAD

**Issue by ydemartino** [springdoc/springdoc-openapi#982]
**Describe the bug**
When using form data and mixing java object and filePart, the generated request body is showing "object" instead of expanded properties

**To Reproduce**
Use the following HelloController (kotlin):
```@RestController
@RequestMapping("/hello")
class HelloController {

    @PostMapping(consumes = [MediaType.MULTIPART_FORM_DATA_VALUE])
    suspend fun hello(user: User, @RequestPart picture: FilePart) {
    }
}

class User(val username: String)
```

**Expected behavior**
The parameter user is showing as object, I should be able to see the detail of the parameter. If I remove the FilePart parameter, I get the correct result (user object expanded)

**Screenshots**
Incorrect behavior:
<img width="564" alt="Capture d’écran 2020-12-10 à 17 08 40" src="https://user-images.githubusercontent.com/3692818/101797491-68450e80-3b0a-11eb-8229-00990efc30b1.png">

Behavior when removing the FilePart:
<img width="564" alt="Capture d’écran 2020-12-10 à 17 08 01" src="https://user-images.githubusercontent.com/3692818/101797647-90347200-3b0a-11eb-9f6d-5c7497d0a4e6.png">

What I would like to see is:
```
username *
string

picture
string($binary)
```

**Comment by bnasslahsen** [comment]
@ydemartino, 

 You can just use `@ParameterObject` , and it should work as expected.

```kotlin
fun hello( @ParameterObject user: User?, @RequestPart picture: FilePart?)
```

**Comment by ydemartino** [comment]
Thank you, it is not exactly what I needed, because the object is showing in the query instead of the request body, but I can work with this.
