### ISSUE TITLE
StackOverflowError when using ObjectId with @ParameterObject

### ISSUE THREAD

**Issue by ydemartino** [springdoc/springdoc-openapi#985]
**Describe the bug**
I am using an ObjectId with the @ParameterObject, this prevent the doc from being generated and fail with a StackOverflowError. This is the error I got when I applied your suggestions (my User object actually had an ObjectId property).

**To Reproduce**
Use this HelloController (Kotlin):
```@RestController
@RequestMapping("/hello")
class HelloController {

    @GetMapping
    fun hello(@ParameterObject id: ObjectId) {
    }

    @Bean
    fun openApi(): OpenAPI {
        return OpenAPI()
            .schema("ObjectId", Schema<ObjectId>().type("string"))
    }
}```
(The schema is not needed to reproduce the issue, but it shows what I was expecting to see)

**Expected behavior**
Doc is displayed correctly with id as string

**Screenshots**
<img width="545" alt="Capture d’écran 2020-12-11 à 10 01 47" src="https://user-images.githubusercontent.com/3692818/101883701-ea2f4900-3b97-11eb-83c8-3863b4bf0b2b.png">

**Comment by bnasslahsen** [comment]
@ydemartino, 

 Not reproducible.
 Provide a [Minimal, Reproducible Example - with HelloController](https://stackoverflow.com/help/minimal-reproducible-example) that reproduces the problem

 If you are reporting a bug, please help to speed up problem diagnosis by at least, reviewing the formatting style when you submit an issue.

 This ticket will be now closed and can be reopened if the relevant information is provided.

**Comment by ydemartino** [comment]
Sorry about the formatting.

How are you not able to reproduce the issue?

I cloned your demo project and changed this line: 
https://github.com/springdoc/springdoc-openapi-demos/blob/master/springdoc-openapi-spring-boot-2-webflux/src/main/java/org/springdoc/demo/app3/controller/TweetController.java#L65
with:
```
	public Flux<TweetDTO> getAllTweets(@ParameterObject ObjectId id) {
```

And I get the exact same issue

**Comment by bnasslahsen** [comment]
This issue was not reproducible as your description was incomplete. 
Your second try, is a little better.
