### ISSUE TITLE
PropertyCustomizer is only given a referenced schema

### ISSUE THREAD

**Issue by Sam-Kruglov** [springdoc/springdoc-openapi#986]
**Is your feature request related to a problem? Please describe.**
I noticed via a debugger that `org.springdoc.core.converters.PropertyCustomizingConverter` only supplies an already resolved schema to a customizer, i.e. with only `$ref` field populated for `/components/schema`. I think this kinda defeats the purpose.

**Describe the solution you'd like**
Personally, I am not interested in anything but `ObjectSchema` that contains my properties of each DTO. This is accessible from the converter mentioned above via `context.getDefinedModels()`. However, if I have a DTO with field `Int, String`, then this converter will fire 3 times: `IntegerSchema`, `StringSchema`, `Schema`(with `$ref`), and I think all these 3 times the `context.getDefinedModels()` will return the same `ObjectSchema` of the DTO. So, it should probably only fire once for the object schema.

**Describe alternatives you've considered**
Write an `OpenApiCustomizer` and scroll through `components/schemas`

**Comment by bnasslahsen** [comment]
This the purpose of `PropertyCustomizingConverter`...
And you have other alternatives, for what you want to achieve. 

This ticket is not respecting the contribution guidelines and will be deleted.
