### ISSUE TITLE
Testing for Swagger UI does not work

### ISSUE THREAD

**Issue by TribuneX** [springdoc/springdoc-openapi#99]
I migrated from Springfox to this project. However, I can't get the following test to pass:

```java
@ExtendWith(SpringExtension.class)
@SpringBootTest
@AutoConfigureMockMvc
public class SwaggerUITest extends AbstractSpringBootTest {

    @Autowired
    private MockMvc mvc;

    @Test
    void shouldDisplaySwaggerUiPage() throws Exception {

        MvcResult mvcResult = mvc.perform(get("/swagger-ui/index.html"))
                .andExpect(status().isOk())
                .andReturn();
        String contentAsString = mvcResult.getResponse().getContentAsString();

        assertThat(contentAsString).contains("Swagger UI");
    }

}
``` 

The same test worked for Springfox while using the url `/swagger-ui.html`. 
Strangely the tests works while executing it with Intellij, but does not when it is executed by maven with `maven test`

The url does not seem to be available since I get a `404` instead of `200`: 
```
SwaggerUITest.shouldDisplaySwaggerUiPage:28 Status expected:<200> but was:<404>
```

Any suggestions?

**Comment by springdoc** [comment]
Hi, 

 You can have a look on this sample test of the ui: 
- https://github.com/springdoc/springdoc-openapi/blob/master/springdoc-openapi-ui/src/test/java/test/org/springdoc/ui/app1/SpringDocApp1Test.java
