### ISSUE TITLE
Documenting Spring Binding Parameter as PathVariable

### ISSUE THREAD

**Issue by kintomiko** [springdoc/springdoc-openapi#990]
**Is your feature request related to a problem? Please describe.**
- I want to document spring binding parameter as path variable as same as query parameters
e.g.
```
@GetMapping("/{projectId}/{date}")
    fun getBindingPathParameter(reportId: ReportId): ResponseEntity<ReportId> {
        return ResponseEntity.ok(
                reportId
        )
    }

@ParameterObject
    data class ReportId(
            val projectId: Int,
            val date: String
    )
```
projectId and date are bound into reportId automatically by spring mvc. And the open api doc should display the same.

- Currently all binding parameter as Path variable will be documented as query parameter, and the curl generated by swagger doc will construct these parameters as query parameter as well

**Describe the solution you'd like**
- no additional config should be need, but springdoc should be able to scan the mapping definition and match it with the object in the same way as spring mvc binding.
- swagger doc should be able to generate correct curl with pameters in the path.

**Describe alternatives you've considered**
- currently I'm using the DelegateMethodParameterCustomizer
```
@Target(AnnotationTarget.VALUE_PARAMETER)
@Retention(AnnotationRetention.RUNTIME)
annotation class PathVariableObject

@Component
class POJOPathVariableCustomizer: DelegatingMethodParameterCustomizer{
    override fun customize(originalParameter: MethodParameter, methodParameter: MethodParameter) {
        if (originalParameter.hasParameterAnnotation(PathVariableObject::class.java)) run {
            val field = DelegatingMethodParameter::class.java.getDeclaredField("additionalParameterAnnotations")
            field.isAccessible = true
            field.set(
                    methodParameter,
                    (field.get(methodParameter) as Array<Annotation>).plus(PathVariable::class.createInstance())
            )
        }
    }
}
```
The problem is I need additional @PathVariableObject. Also currently only one  DelegatingMethodParameterCustomizer is allowed so it will conflict with other DelegatingMethodParameterCustomizer.

**Additional context**
This is existing issue in springfox haven't been resolved yet. If spring doc can solve it will be great!
- https://github.com/springfox/springfox/issues/1421

**Comment by bnasslahsen** [comment]
@kintomiko, 

 Without any extra overriding of `DelegateMethodParameterCustomizer`:

-  You can simply on the top of your `date` attribute, add the swagger annotation:

	`@Parameter(description = "date parameter", in = ParameterIn.PATH)`

**Comment by kintomiko** [comment]
sorry not clean enough

the problem is `ReportId` can be reused in another API which is bound as query parameter
e.g.
```
@GetMapping("/{projectId}/{date}")
    fun getBindingPathParameter(reportId: ReportId): ResponseEntity<ReportId>
@GetMapping("/query")
    fun getQueryBindingPathParameter(reportId: ReportId): ResponseEntity<ReportId>
```

**Comment by bnasslahsen** [comment]
@kintomiko, 

 This means you are expecting two different schemas for the same object ...
 You can see how to achieve that here: https://github.com/springdoc/springdoc-openapi/issues/685
