### ISSUE TITLE
Unable to define property with no type in the generated schema. No type means any type

### ISSUE THREAD

**Issue by ratoaq2** [springdoc/springdoc-openapi#993]
springdoc uses as a default type "object" (`ObjectSchema`).

I'm unable to generate the openapi spec with any type.
```
public class Foo {
      private Serializable bar;
... getters/setters
}
```

As openapi specification, no type means any type:
https://swagger.io/docs/specification/data-models/data-types/#any

I tried to add a open api customizer, but even removing the type object from the schema, but the generated schema always includes `type: object`.

**Comment by bnasslahsen** [comment]
Your description is not clear.
If you are reporting a bug, please help to speed up problem diagnosis by providing as much information as possible.
Make sure you provide the listed information in the [contribution guide](https://github.com/springdoc/springdoc-openapi/blob/master/CONTRIBUTING.adoc)...

- What version of spring-boot you are using?
- What modules and versions of springdoc-openapi are you using?
- What are the actual and the expected result using OpenAPI Description (yml or json)?
- Provide a [Minimal, Reproducible Example - with HelloController ](https://stackoverflow.com/help/minimal-reproducible-example)that reproduces the problem

There is no need to create a new ticket. 
If the relevant information are provided, this one can be reopened.

**Comment by ratoaq2** [comment]
Sorry.
I added all the required information.
Let me know if this issue can be reopened.

**Comment by bnasslahsen** [comment]
@ratoaq2, 

 Could you please review your expected OpenAPI spec, which is not valid?
 You review it in the [swagger-editor ](https://editor.swagger.io/) before pasting it.

**Comment by ratoaq2** [comment]
Done

**Comment by bnasslahsen** [comment]
You can exactly get the same expected result, using many methods.
This is a sample working code:

```java


@RestController
public class HelloController {

	@GetMapping
	public Foo getFoo() {
		return new Foo();
	}

	class Foo {

		@JsonProperty
		private Serializable bar;

	}

	@Bean
	public OpenAPI customOpenAPI() {
		return new OpenAPI().components(new Components().addSchemas(
				"Foo", new Schema().type("object")
						.addProperties("bar", new Schema())));
	}
}
```

**Comment by ratoaq2** [comment]
That should work (I still didn't try it, since I fixed my issue with a workaround while generating code from the spec).

But I raised this issue because I believe the default generation is wrong (or at least inconsistent).

If you map `java.lang.Object` to `type: object` in the OpenAPI spec, that means that schema only accepts an object with no properties. Using JSON representation, this would be the only acceptable value: `"bar": {}`.
But in the end `"bar": 3` or `"bar": "value-01"` or `"bar": true` should also be acceptable, because they are possible values for that property in Java.

`java.lang.Object` means that it can be of any type (`java.lang.String`, `java.lang.Integer`, `java.lang.Boolean`, etc). `java.lang.Object` is an arbitrary type. And the way to represent that in OpenAPI spec is with no type:
https://swagger.io/docs/specification/data-models/data-types/#any
> A schema without a type matches any data type – numbers, strings, objects, and so on. {} is shorthand syntax for an arbitrary-type schema


The default generated schema should be:

```
components:
  schemas:
    Foo:
      type: object
      properties:
        bar: {}
```

or 

```
components:
  schemas:
    Foo:
      type: object
      properties:
        bar:
          anyOf:
          - type: string
          - type: number
          - type: integer
          - type: boolean
          - type: array
            items: {}
          - type: object
```

**Comment by bnasslahsen** [comment]
@ratoaq2, 

This is just your interpretation of the spec ...
And we do not believe there is any issue in here.

You can use the following code to understand how the default generation is done:
```java
ModelConverters.getInstance()
		.resolveAsResolvedSchema(
		         new AnnotatedType(Foo.class));
```

springdoc-openapi is based on the [swagger project](https://github.com/swagger-api/swagger-core/issues).
If you feel you have found an issue, you can ask the swagger team instead.
