### ISSUE TITLE
Wrong doc when use JsonProperty.Access.WRITE_ONLY

### ISSUE THREAD

**Issue by John-Chan** [springdoc/springdoc-openapi#994]
**Describe the bug**

code

![1-src](https://user-images.githubusercontent.com/2360910/102645834-0b96c300-419e-11eb-9002-90aa1c78bf9c.png)

swagger-ui

![1](https://user-images.githubusercontent.com/2360910/102645826-09ccff80-419e-11eb-9af4-b4c9d52d07af.png)

If I remove `@JsonProperty(access = JsonProperty.Access.WRITE_ONLY)`,

![2-src](https://user-images.githubusercontent.com/2360910/102645838-0cc7f000-419e-11eb-9fc3-b54cd12a1414.png)

![2](https://user-images.githubusercontent.com/2360910/102645835-0c2f5980-419e-11eb-8c7d-90b203b4475b.png)

**Additional context**
- `springdoc-openapi.version` : `1.5.0`
- `spring-boot.version` : `2.3.5.RELEASE`

**Comment by bnasslahsen** [comment]
Not reproducible.
Make sure you provide a **[Minimal, Reproducible Example - with HelloController](https://stackoverflow.com/help/minimal-reproducible-example)** that reproduces the problem
This ticket will be closed and can be reopened if any relevant information is provided.

**Comment by John-Chan** [comment]
Demo project : https://github.com/John-Chan/springdoc-issue994


```SHELL
$ diff UserA.java UserB.java
7d6
< import lombok.experimental.Accessors;
19c18
< @Accessors(chain = true)
---
> //@Accessors(chain = true)
21c20
< public class UserA implements Serializable {
---
> public class UserB implements Serializable {
```

![DOC](https://user-images.githubusercontent.com/2360910/102746214-c1c5fc80-4398-11eb-8597-466fb1b486b1.png)


- Use `@Accessors(chain = true)`  And `@JsonProperty(access = JsonProperty.Access.WRITE_ONLY)`  can reproduces the problem. 
- Remove one of them  can solve the problem.

**Comment by John-Chan** [comment]
> Not reproducible.
> Make sure you provide a **[Minimal, Reproducible Example - with HelloController](https://stackoverflow.com/help/minimal-reproducible-example)** that reproduces the problem
> This ticket will be closed and can be reopened if any relevant information is provided.

please check my demo project  @bnasslahsen

**Comment by bnasslahsen** [comment]
@John-Chan, 

 First i note that you haven mentioned lombok `@Accessors`, in your initial description...
 Your issue coms from **chain = true**, combined with `@Accessors`, which doesn't generate standard Java Bean Getters/Setters.

 You could remove **chain = true** as workaround. Or add the missing setter manually.
 Note that this behavior is not handled in springodc-openapi code. But the usage of standard Getters/Setters, comes from the swagger-core directly.
