### ISSUE TITLE
Allow auhetication of the OpenAPi description endpoint

### ISSUE THREAD

**Issue by goodhoko** [springdoc/springdoc-openapi#997]
## Problem

Hi,
we like this library for how it makes it easy to generate OpanApi docs. However we do not want our services to expose the generated docs publicly. We'd like the `v3/api-docs` (and `v3/api-docs.yaml`) endpoints to be authenticated.

Also, since we use a custom authentication implementation we'd like an ability to hook into the auth process.

## Solution we'd like
An ability to define a custom function that will be run for each request to the mentioned paths. Something along the lines of (Kotlin example)
```kotlin
@Bean
open fun openApi(): GroupedOpenApi = GroupedOpenApi.builder()
        .group("GoOut API")
        .pathsToMatch("/**")
        // if lamba returns true, the request is authenticated. 403 is returned otherwise.
        .auth { request ->
              // authenticate() might be a custom auth implementation
              return authenticate(request.getHeader("token"))
         }
        .build()
```

## Alternatives
I have little experience with Spring and springdoc so I'm not sure what is the canonical solution to the problem. I just tried to give one that seems simplest from our user perspective.

**Comment by bnasslahsen** [comment]
@goodhoko, 

 You don't need any enhancement for that on springdoc-openapi.
  
 In general, it's more convenient to use spring-security to enable the authentication of the OpenAPI endpoint or simply enable standard java security.
 We do not find any added value of the proposed change. 
 If you need some custom changes, you still can override the sprindoc-openapi endpoint and add your custom security controls.

**Comment by goodhoko** [comment]
@bnasslahsen Right, that makes sense. .) Could you maybe point me (and possible future readers) to some examples or tutorials on how spring security can be enabled for the particular endpoints exposed by springdoc? A mention in the docs would be certainly helpful as well. I'd happily submit a PR to extend the docs if only I new what to write there? ./
