### ISSUE TITLE
ResponseBodyAdvice convert response body, how to show real response

### ISSUE THREAD

**Issue by hsoftxl** [springdoc/springdoc-openapi#998]
use ResponseBodyAdvice , convert all response to BaseResult<T>

@Data
public class BaseResult<T> {

    public static final int CODE_SUCCESS = 1000;
    public static final int CODE_ERROR = 0;

    /**
     * 状态,1000 代表成功(数据可用)
     */
    @Schema(description = "状态码")
    private int state = CODE_ERROR;
    /**
     * 错误消息
     */
    @Schema(description = "错误消息")
    private String message;
    /**
     * 错误详情
     */
    @Schema(description = "错误详情")
    private String exception;
    /**
     * 响应级别
     */
    @Schema(description = "响应级别")
    private Integer level;
    /**
     * 响应数据
     */
    @Schema(description = "响应数据")
    private T data;
}

but swagger-ui.html show return type resonsebody, like this

![image](https://user-images.githubusercontent.com/6965803/102877052-1a70c480-4481-11eb-8d29-e885bb2ad925.png)

how can i do

**Comment by bnasslahsen** [comment]
@hsoftxl, 

These are some basic guidelines before opening an issue. First of all you need to make sure, you don't create duplicate issues, and there no question already answered on https://stackoverflow.com/tags/springdoc.

If you are starting using springdoc-openapi, we advise you to use the last available release.

Then refer to the relevant documentation:

1. For OpenAPI specification 3:
   - https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.2.md
2. For swagger2-annotations:
    - https://github.com/swagger-api/swagger-core/wiki/Swagger-2.X---Annotations
3. For swagger-ui configuration:
    - https://github.com/swagger-api/swagger-ui/blob/master/docs/usage/configuration.md
4. For springdoc-openapi:
    - https://springdoc.org/
    - https://springdoc.org/faq.html
    - https://springdoc.org/migrating-from-springfox.html
If you are reporting a bug, please help to speed up problem diagnosis by providing as
much information as possible:

 - You need to describe your context (the title of an issue is not enough)
 - What version of spring-boot you are using?
 - What modules and versions of springdoc-openapi are you using? 
 - What are the actual and the expected result using OpenAPI Description (yml or json)?
 - Provide a [**Minimal, Reproducible Example - with HelloController** ](https://stackoverflow.com/help/minimal-reproducible-example) that reproduces the problem

This ticket is now closed. And can be reopened if the relevant information are provided.
