### ISSUE TITLE
Adding Getter/Setter breaks @JsonView functionality

### ISSUE THREAD

**Issue by affanshahid** [springdoc/springdoc-openapi#999]
This is related to #989.

I am having a strange issue where my `@JsonView` annotation is being ignored if I add a getter/setter, it works just fine otherwise.

I previously did not understand the actual issue but if you take the working example from this comment: https://github.com/springdoc/springdoc-openapi/issues/989#issuecomment-744725691 and add a getter/setter for the `tree` property you will see that the generated API will not ignore the `tree` property as it is suppose to due to the `@JsonView` annotation.

**Comment by bnasslahsen** [comment]
Please, do not create duplicates.
If you have any comments, add them on the original issue and we will have a look at them.
